### PR TITLE
Fix machete version

### PR DESCRIPTION
**Pull request by shaharsamocha7**

### CODE REVIEW

**Comment by shaharsamocha7** [comment]
* **#914** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/914?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/914?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `dev`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by zmalatrax — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/914)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`.github/workflows/ci.yaml` line 200 at r2](https://reviewable.io/reviews/starkware-libs/stwo/914#-OD6nJCfDPH249zvT0fm:-OD6nJCfDPH249zvT0fn:b-vbuw9o) ([raw file](https://github.com/starkware-libs/stwo/blob/227bde8ed5eef86025175008db93907b0a3a7710/.github/workflows/ci.yaml#L200)):*
> ```YAML
>       - uses: actions/checkout@v4
>       - name: Run Machete (detect unused dependencies)
>         uses: bnjbvr/cargo-machete@v0.6.1
> ```

We had the same issue on the [`stwo-brainfuck`](https://github.com/kkrt-labs/stwo-brainfuck/pull/107/files), we inlined the cargo-machete action and used the `--locked` flag when installing `cargo-machete`, to still use `cargo-platform@0.1.8` and not `cargo-platform@0.1.9` which is not supported on rustc 1.77 (used by nightly-2024-01-04)

```yaml
  machete:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2024-01-04
      - uses: Swatinem/rust-cache@v2
      - run: cargo +nightly-2024-01-04 install --locked cargo-machete
      - name: Run Machete (detect unused dependencies)
        uses: cargo +nightly-2024-01-04 machete
```

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/914)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @zmalatrax)

___
*[`.github/workflows/ci.yaml` line 200 at r2](https://reviewable.io/reviews/starkware-libs/stwo/914#-OD6nJCfDPH249zvT0fm:-ODMJXPr7jRL-4To8ch5:b32wy2) ([raw file](https://github.com/starkware-libs/stwo/blob/227bde8ed5eef86025175008db93907b0a3a7710/.github/workflows/ci.yaml#L200)):*
<details><summary><i>Previously, zmalatrax (malatrax) wrote…</i></summary><blockquote>

We had the same issue on the [`stwo-brainfuck`](https://github.com/kkrt-labs/stwo-brainfuck/pull/107/files), we inlined the cargo-machete action and used the `--locked` flag when installing `cargo-machete`, to still use `cargo-platform@0.1.8` and not `cargo-platform@0.1.9` which is not supported on rustc 1.77 (used by nightly-2024-01-04)

```yaml
  machete:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2024-01-04
      - uses: Swatinem/rust-cache@v2
      - run: cargo +nightly-2024-01-04 install --locked cargo-machete
      - name: Run Machete (detect unused dependencies)
        uses: cargo +nightly-2024-01-04 machete
```
</blockquote></details>

ty

**Review by andrewmilson — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/914#-:-ODMK548957URPAHZq0Y:bnfp4nl)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @zmalatrax)

**Pull request merged**
