### PR TITLE
Add lookup final boundary constraints.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/664)

### CODE REVIEW

**Comment by alonh5** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/664?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#664** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/664?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#662** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/662?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#646** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/646?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#644** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/644?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#654](https://github.com/starkware-libs/stwo/pull/654) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/654?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#642** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/642?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#639** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/639?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#638** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/638?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#637** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/637?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#636** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/636?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#651** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/651?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/664)* status: 0 of 13 files reviewed, 3 unresolved discussions (waiting on @alonh5 and @spapinistarkware)

___
*[`crates/prover/src/core/prover/mod.rs` line 209 at r3](https://reviewable.io/reviews/starkware-libs/stwo/664#-O0mHOb45PTXLh1c11kH:-O0mHOb59DugesXfYPcf:bg67jp6) ([raw file](https://github.com/starkware-libs/stwo/blob/4a0804a9ab2580f37d920f21b40a8252b0550734/crates/prover/src/core/prover/mod.rs#L209)):*
> ```XML
>     }
> 
>     proof.lookup_values.mix_in_channel(channel);
> ```

Why can't you use channel.mix_felts()?



_Code quote:_
```XML
    proof.lookup_values.mix_in_channel(channel);
```
___
*[`crates/prover/src/examples/wide_fibonacci/constraint_eval.rs` line 76 at r3](https://reviewable.io/reviews/starkware-libs/stwo/664#-O0mII2iC4vbo9fSQGRC:-O0mII2j4fTC7sxl85LV:bar10xd) ([raw file](https://github.com/starkware-libs/stwo/blob/4a0804a9ab2580f37d920f21b40a8252b0550734/crates/prover/src/examples/wide_fibonacci/constraint_eval.rs#L76)):*
> ```XML
>         let mut last_point_denoms = vec![];
>         for point in trace_eval_domain.iter() {
>             first_point_denoms.push(point_vanishing(zero_domain.at(0), point));
> ```

We have point_vanishing_fraction for faster impl (no division)



_Code quote:_
```XML
          first_point_denoms.push(point_vanishing(zero_domain.at(0), point));
```
___
*[`crates/prover/src/examples/wide_fibonacci/constraint_eval.rs` line 86 at r3](https://reviewable.io/reviews/starkware-libs/stwo/664#-O0mINcW78W9Cv8hifHO:-O0mINcX3enhpbJ0FFnT:bvafb0a) ([raw file](https://github.com/starkware-libs/stwo/blob/4a0804a9ab2580f37d920f21b40a8252b0550734/crates/prover/src/examples/wide_fibonacci/constraint_eval.rs#L86)):*
> ```XML
>         BaseField::batch_inverse(&last_point_denoms, &mut last_point_denom_inverses);
>         let mut first_point_numerators = vec![SecureField::zero(); 1 << (max_constraint_degree)];
>         let mut last_point_numerators = vec![SecureField::zero(); 1 << (max_constraint_degree)];
> ```

Maybe we can use line vanishing instead of 2 point vanishing?



_Code quote:_
```XML
        let mut first_point_numerators = vec![SecureField::zero(); 1 << (max_constraint_degree)];
        let mut last_point_numerators = vec![SecureField::zero(); 1 << (max_constraint_degree)];
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/664)* status: 0 of 13 files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/core/prover/mod.rs` line 209 at r3](https://reviewable.io/reviews/starkware-libs/stwo/664#-O0mHOb45PTXLh1c11kH:-O0mSGrJApZJo2D-7E_b:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/4a0804a9ab2580f37d920f21b40a8252b0550734/crates/prover/src/core/prover/mod.rs#L209)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why can't you use channel.mix_felts()?
</blockquote></details>

Done.
___
*[`crates/prover/src/examples/wide_fibonacci/constraint_eval.rs` line 76 at r3](https://reviewable.io/reviews/starkware-libs/stwo/664#-O0mII2iC4vbo9fSQGRC:-O0meZ7z3jsWWvLMJ1hl:b-7yd1q4) ([raw file](https://github.com/starkware-libs/stwo/blob/4a0804a9ab2580f37d920f21b40a8252b0550734/crates/prover/src/examples/wide_fibonacci/constraint_eval.rs#L76)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

We have point_vanishing_fraction for faster impl (no division)
</blockquote></details>

Added a TODO.
___
*[`crates/prover/src/examples/wide_fibonacci/constraint_eval.rs` line 86 at r3](https://reviewable.io/reviews/starkware-libs/stwo/664#-O0mINcW78W9Cv8hifHO:-O0mUy_00tgQ0uSPgmuX:bcgwnfz) ([raw file](https://github.com/starkware-libs/stwo/blob/4a0804a9ab2580f37d920f21b40a8252b0550734/crates/prover/src/examples/wide_fibonacci/constraint_eval.rs#L86)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Maybe we can use line vanishing instead of 2 point vanishing?
</blockquote></details>

Each of the constraints is on a different column so I don't think I can combine them into a line.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/664)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @spapinistarkware)

___
*[`crates/prover/src/examples/wide_fibonacci/constraint_eval.rs` line 86 at r3](https://reviewable.io/reviews/starkware-libs/stwo/664#-O0mINcW78W9Cv8hifHO:-O0sM6_l9FQPuO2OA2Eb:b2spi0z) ([raw file](https://github.com/starkware-libs/stwo/blob/4a0804a9ab2580f37d920f21b40a8252b0550734/crates/prover/src/examples/wide_fibonacci/constraint_eval.rs#L86)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Each of the constraints is on a different column so I don't think I can combine them into a line.
</blockquote></details>

I think that the denoms could be combined using a line between those two points.

Also the code here is multiplied x2, shouldn't we create a boundary constraint helper function?

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/664)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/examples/wide_fibonacci/constraint_eval.rs` line 86 at r3](https://reviewable.io/reviews/starkware-libs/stwo/664#-O0mINcW78W9Cv8hifHO:-O0sQTfg15NS_yM_51zS:bb5evyt) ([raw file](https://github.com/starkware-libs/stwo/blob/4a0804a9ab2580f37d920f21b40a8252b0550734/crates/prover/src/examples/wide_fibonacci/constraint_eval.rs#L86)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I think that the denoms could be combined using a line between those two points.

Also the code here is multiplied x2, shouldn't we create a boundary constraint helper function?
</blockquote></details>

The denoms can, but the numerators are from different columns so I can't combine them into one constraint.
Regarding the helper function you're right, I'm working on it in a new PR.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/664)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @spapinistarkware)

___
*[`crates/prover/src/examples/wide_fibonacci/constraint_eval.rs` line 86 at r3](https://reviewable.io/reviews/starkware-libs/stwo/664#-O0mINcW78W9Cv8hifHO:-O0saX2W1Jb95YqPYcpo:bly20tu) ([raw file](https://github.com/starkware-libs/stwo/blob/4a0804a9ab2580f37d920f21b40a8252b0550734/crates/prover/src/examples/wide_fibonacci/constraint_eval.rs#L86)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

The denoms can, but the numerators are from different columns so I can't combine them into one constraint.
Regarding the helper function you're right, I'm working on it in a new PR.
</blockquote></details>

I still think they can be together (same as in FRI quotients)

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/664)* status: 0 of 13 files reviewed, all discussions resolved (waiting on @spapinistarkware)

___
*[`crates/prover/src/examples/wide_fibonacci/constraint_eval.rs` line 86 at r3](https://reviewable.io/reviews/starkware-libs/stwo/664#-O0mINcW78W9Cv8hifHO:-O0skKYL7DWNt2-j14FB:b-alcytu) ([raw file](https://github.com/starkware-libs/stwo/blob/4a0804a9ab2580f37d920f21b40a8252b0550734/crates/prover/src/examples/wide_fibonacci/constraint_eval.rs#L86)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I still think they can be together (same as in FRI quotients)
</blockquote></details>

Talked offline, we can consider it in the future for optimization.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 11 files at r1, 4 of 10 files at r2, 2 of 2 files at r3, 2 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/664)* status: 10 of 13 files reviewed, 3 unresolved discussions (waiting on @alonh5 and @spapinistarkware)

___
*[`crates/prover/src/core/air/mod.rs` line 102 at r4](https://reviewable.io/reviews/starkware-libs/stwo/664#-O1CMNvMDGChBLDQ52aj:-O1CMNvMDGChBLDQ52ak:b-oxz3) ([raw file](https://github.com/starkware-libs/stwo/blob/f9a19f5a490d28dc88487f25ef3dec719ce03870/crates/prover/src/core/air/mod.rs#L102)):*
> ```XML
>     /// Returns the values needed to evaluate the components lookup boundary constraints.
>     fn lookup_values(&self, _trace: &ComponentTrace<'_, B>) -> LookupValues {
>         LookupValues::default()
> ```

Do we want a default implementation?



_Code quote:_
```XML
        LookupValues::default()
```
___
*[`crates/prover/src/core/fields/mod.rs` line 417 at r4](https://reviewable.io/reviews/starkware-libs/stwo/664#-O1CMr-92QUBd3aZH4dj:-O1CMr-92QUBd3aZH4dk:boh6l5z) ([raw file](https://github.com/starkware-libs/stwo/blob/f9a19f5a490d28dc88487f25ef3dec719ce03870/crates/prover/src/core/fields/mod.rs#L417)):*
> ```XML
>                 }
>                 self.0.try_into().map_err(|_| ())
>             }
> ```

This implementation is risky as a macro.
I think it should be implemented specifically for each of our field impls.

e.g. Consider a quadratic extension field that implemented directly (x0,x1,x2,x3)



_Code quote:_
```XML
            fn try_into(self) -> Result<M31, Self::Error> {
                if self.1 != <$extended_field_name>::zero() {
                    return Err(());
                }
                self.0.try_into().map_err(|_| ())
            }
```
___
*[`crates/prover/src/core/prover/mod.rs` line 137 at r4](https://reviewable.io/reviews/starkware-libs/stwo/664#-O1CO2E--OmUjRU3OT0d:-O1CO2E--OmUjRU3OT0e:bw8j7yp) ([raw file](https://github.com/starkware-libs/stwo/blob/f9a19f5a490d28dc88487f25ef3dec719ce03870/crates/prover/src/core/prover/mod.rs#L137)):*
> ```XML
> 
>     if composition_oods_value
>         != air.eval_composition_polynomial_at_point(
> ```

Where is the change in the interface?
Please document what Lookup_values are



_Code quote:_
```XML
!= air.eval_composition_polynomial_at_point(
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/664)* status: 10 of 13 files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/core/air/mod.rs` line 102 at r4](https://reviewable.io/reviews/starkware-libs/stwo/664#-O1CMNvMDGChBLDQ52aj:-O1CRVh59GZ_Ne3qX9yh:b3kzlhv) ([raw file](https://github.com/starkware-libs/stwo/blob/f9a19f5a490d28dc88487f25ef3dec719ce03870/crates/prover/src/core/air/mod.rs#L102)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Do we want a default implementation?
</blockquote></details>

Probably not, I did it so I don't have to add this method for every component right away. Should I remove it?
___
*[`crates/prover/src/core/fields/mod.rs` line 417 at r4](https://reviewable.io/reviews/starkware-libs/stwo/664#-O1CMr-92QUBd3aZH4dj:-O1CRuAbDbtaz7B69fjP:b27puvo) ([raw file](https://github.com/starkware-libs/stwo/blob/f9a19f5a490d28dc88487f25ef3dec719ce03870/crates/prover/src/core/fields/mod.rs#L417)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

This implementation is risky as a macro.
I think it should be implemented specifically for each of our field impls.

e.g. Consider a quadratic extension field that implemented directly (x0,x1,x2,x3)
</blockquote></details>

Why is it risky? I think it's pretty clear when it should work and when it should fail.
___
*[`crates/prover/src/core/prover/mod.rs` line 137 at r4](https://reviewable.io/reviews/starkware-libs/stwo/664#-O1CO2E--OmUjRU3OT0d:-O1CStcaBX4M9iQetsbI:b-nvolz0) ([raw file](https://github.com/starkware-libs/stwo/blob/f9a19f5a490d28dc88487f25ef3dec719ce03870/crates/prover/src/core/prover/mod.rs#L137)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Where is the change in the interface?
Please document what Lookup_values are
</blockquote></details>

I don't understand the question.
I added:
```
/// Returns the values needed to evaluate the components lookup boundary constraints.
```
over the `lookup_values()` function. Should I document somewhere else?

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/664)* status: 10 of 13 files reviewed, 4 unresolved discussions (waiting on @alonh5 and @spapinistarkware)

___
*[`crates/prover/src/core/air/mod.rs` line 71 at r4](https://reviewable.io/reviews/starkware-libs/stwo/664#-O1DP-iMA6j1H9fyThk0:-O1DP-iMA6j1H9fyThk1:b7gcnsa) ([raw file](https://github.com/starkware-libs/stwo/blob/ffeb96a7be4820f8eddd5e0dc5268f5ef88d2ba1/crates/prover/src/core/air/mod.rs#L71)):*
> ```XML
> 
>     /// Evaluates the constraint quotients combination of the component, given the mask values.
>     fn evaluate_constraint_quotients_at_point(
> ```

Fix documentation



_Code quote:_
```XML
    /// Evaluates the constraint quotients combination of the component, given the mask values.
    fn evaluate_constraint_quotients_at_point(
```
___
*[`crates/prover/src/core/air/mod.rs` line 102 at r4](https://reviewable.io/reviews/starkware-libs/stwo/664#-O1CMNvMDGChBLDQ52aj:-O1DMnZW8ATR3gUoyKJg:btv6ib6) ([raw file](https://github.com/starkware-libs/stwo/blob/f9a19f5a490d28dc88487f25ef3dec719ce03870/crates/prover/src/core/air/mod.rs#L102)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Probably not, I did it so I don't have to add this method for every component right away. Should I remove it?
</blockquote></details>

hmm IMO there is no reason to have this default (I don't think this is the common impl)
Can add a TODO for now
___
*[`crates/prover/src/core/fields/mod.rs` line 417 at r4](https://reviewable.io/reviews/starkware-libs/stwo/664#-O1CMr-92QUBd3aZH4dj:-O1DN6rL5PJiHRSdgMOq:b2hc11y) ([raw file](https://github.com/starkware-libs/stwo/blob/f9a19f5a490d28dc88487f25ef3dec719ce03870/crates/prover/src/core/fields/mod.rs#L417)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Why is it risky? I think it's pretty clear when it should work and when it should fail.
</blockquote></details>

Consider the fifth extension field (size P^5) and  the impl of ext felt is `F =  (x0, x1, x2, x3, x4)`
Given the value (1, 0 , 1, 1, 1), the code accept downcast to a BaseField.

Not sure if that would scenario is real
___
*[`crates/prover/src/core/prover/mod.rs` line 137 at r4](https://reviewable.io/reviews/starkware-libs/stwo/664#-O1CO2E--OmUjRU3OT0d:-O1DOkV6CpBlVPYRD1vH:b-q1ztvp) ([raw file](https://github.com/starkware-libs/stwo/blob/f9a19f5a490d28dc88487f25ef3dec719ce03870/crates/prover/src/core/prover/mod.rs#L137)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I don't understand the question.
I added:
```
/// Returns the values needed to evaluate the components lookup boundary constraints.
```
over the `lookup_values()` function. Should I document somewhere else?
</blockquote></details>

Nvm, I comment in the interface

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/664)* status: 11 of 13 files reviewed, 6 unresolved discussions (waiting on @alonh5 and @spapinistarkware)

___
*[`crates/prover/src/examples/wide_fibonacci/component.rs` line 70 at r4](https://reviewable.io/reviews/starkware-libs/stwo/664#-O1FpPR71kpRzlzGzrOI:-O1FpPR71kpRzlzGzrOJ:bio6zz7) ([raw file](https://github.com/starkware-libs/stwo/blob/f9a19f5a490d28dc88487f25ef3dec719ce03870/crates/prover/src/examples/wide_fibonacci/component.rs#L70)):*
> ```XML
> 
>         let numerator = mask[self.n_columns() - 2][0] - lookup_values[LOOKUP_VALUE_N_MINUS_2_ID];
>         let denom = point_vanishing(constraint_zero_domain.at(0), point);
> ```

Remove
you already calculated it



_Code quote:_
```XML
let denom = point_vanishing(constraint_zero_domain.at(0), point);
```
___
*[`crates/prover/src/examples/wide_fibonacci/component.rs` line 158 at r4](https://reviewable.io/reviews/starkware-libs/stwo/664#-O1FphCQCbSeyTtVx4CO:-O1FphCQCbSeyTtVx4CP:b-q7jghc) ([raw file](https://github.com/starkware-libs/stwo/blob/f9a19f5a490d28dc88487f25ef3dec719ce03870/crates/prover/src/examples/wide_fibonacci/component.rs#L158)):*
> ```XML
> impl Component for WideFibComponent {
>     fn n_constraints(&self) -> usize {
>         self.n_columns() + 4
> ```

Why is it n_columns + 4?



_Code quote:_
```XML
self.n_columns() + 4
```

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/664)* status: 11 of 13 files reviewed, 6 unresolved discussions (waiting on @alonh5 and @spapinistarkware)

___
*[`crates/prover/src/examples/wide_fibonacci/component.rs` line 158 at r4](https://reviewable.io/reviews/starkware-libs/stwo/664#-O1FphCQCbSeyTtVx4CO:-O1FqtggDmz-xu8o0HkJ:buhl7yk) ([raw file](https://github.com/starkware-libs/stwo/blob/f9a19f5a490d28dc88487f25ef3dec719ce03870/crates/prover/src/examples/wide_fibonacci/component.rs#L158)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why is it n_columns + 4?
</blockquote></details>

I think that this is due the 4 boundary constraints that you have on the original trace, is that right?

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/664)* status: 3 of 13 files reviewed, 6 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/core/air/mod.rs` line 71 at r4](https://reviewable.io/reviews/starkware-libs/stwo/664#-O1DP-iMA6j1H9fyThk0:-O1GFmso2d9jRb0bWk6s:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/ffeb96a7be4820f8eddd5e0dc5268f5ef88d2ba1/crates/prover/src/core/air/mod.rs#L71)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Fix documentation
</blockquote></details>

Done.
___
*[`crates/prover/src/core/air/mod.rs` line 102 at r4](https://reviewable.io/reviews/starkware-libs/stwo/664#-O1CMNvMDGChBLDQ52aj:-O1GGOyk4lWSVWF9r9Mw:bw5kv5m) ([raw file](https://github.com/starkware-libs/stwo/blob/f9a19f5a490d28dc88487f25ef3dec719ce03870/crates/prover/src/core/air/mod.rs#L102)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

hmm IMO there is no reason to have this default (I don't think this is the common impl)
Can add a TODO for now
</blockquote></details>

np I did it here.
___
*[`crates/prover/src/core/fields/mod.rs` line 417 at r4](https://reviewable.io/reviews/starkware-libs/stwo/664#-O1CMr-92QUBd3aZH4dj:-O1GGd9aC9HqBgK-kwVH:b52fg24) ([raw file](https://github.com/starkware-libs/stwo/blob/f9a19f5a490d28dc88487f25ef3dec719ce03870/crates/prover/src/core/fields/mod.rs#L417)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Consider the fifth extension field (size P^5) and  the impl of ext felt is `F =  (x0, x1, x2, x3, x4)`
Given the value (1, 0 , 1, 1, 1), the code accept downcast to a BaseField.

Not sure if that would scenario is real
</blockquote></details>

Okay I see your point. Done.
___
*[`crates/prover/src/core/prover/mod.rs` line 137 at r4](https://reviewable.io/reviews/starkware-libs/stwo/664#-O1CO2E--OmUjRU3OT0d:-O1GIAK6Csgm-P_Ng2rt:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/f9a19f5a490d28dc88487f25ef3dec719ce03870/crates/prover/src/core/prover/mod.rs#L137)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Nvm, I comment in the interface
</blockquote></details>

Done.
___
*[`crates/prover/src/examples/wide_fibonacci/component.rs` line 70 at r4](https://reviewable.io/reviews/starkware-libs/stwo/664#-O1FpPR71kpRzlzGzrOI:-O1GKb4s6nJUQgr3k924:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/f9a19f5a490d28dc88487f25ef3dec719ce03870/crates/prover/src/examples/wide_fibonacci/component.rs#L70)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Remove
you already calculated it
</blockquote></details>

Done.
___
*[`crates/prover/src/examples/wide_fibonacci/component.rs` line 158 at r4](https://reviewable.io/reviews/starkware-libs/stwo/664#-O1FphCQCbSeyTtVx4CO:-O1GL1Ju-NLSn_E0gNzs:b-aqtmw1) ([raw file](https://github.com/starkware-libs/stwo/blob/f9a19f5a490d28dc88487f25ef3dec719ce03870/crates/prover/src/examples/wide_fibonacci/component.rs#L158)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I think that this is due the 4 boundary constraints that you have on the original trace, is that right?
</blockquote></details>

we have one for every column (minus 2) for the fibonacci step, 4 boundary constraints on the original trace, 1 boundary constraint on the lookup column, and one step constraint on the lookup column. Next PR there will be the final boundary constraint on the lookup column that will result to n_columns + 5.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 13 of 13 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/664#-:-O1GOu505YR8_HKPcTMK:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Comment by alonh5** [comment]
### Merge activity

* **Jul 8, 4:33 AM EDT**: @alonh5 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/664).

**Pull request merged**
