### PR TITLE
Commit to FRI first layer

### PR DESCRIPTION
**Pull request by andrewmilson**
Return opening positions and query positions per column size in FRI

Add FRI layer 0

### CODE REVIEW

**Comment by andrewmilson** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/897?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#897** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/897?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/897?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#852** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/852?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#856](https://github.com/starkware-libs/stwo/pull/856) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/856?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#832** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/832?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#831** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/831?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/prover/src/core/pcs/quotients.rs` line 150 at r1](https://reviewable.io/reviews/starkware-libs/stwo/897#-OCSR_m0-PBU41Yx2IE2:-OCSR_m0-PBU41Yx2IE3:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/2955551144e0b58cc9bb438ec296f4ab7989e78a/crates/prover/src/core/pcs/quotients.rs#L150)):*
> ```XML
>     for &query_position in query_positions {
>         let domain_point = commitment_domain.at(bit_reverse_index(query_position, log_size));
>         let row = row_index_iter.next().unwrap();
> ```





_Suggestion:_
```XML
    for (row, &query_position) in query_positions.iter().enumerate() {
        let domain_point = commitment_domain.at(bit_reverse_index(query_position, log_size));
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/prover/src/core/fri.rs` line 658 at r1](https://reviewable.io/reviews/starkware-libs/stwo/897#-OCSUOJKCZzioEzeABQ3:-OCSUOJKCZzioEzeABQ4:b-7hbpla) ([raw file](https://github.com/starkware-libs/stwo/blob/2955551144e0b58cc9bb438ec296f4ab7989e78a/crates/prover/src/core/fri.rs#L658)):*
> ```XML
>     /// Stores the evaluations the verifier can't compute but needs in order to perform folding and
>     /// verify the merkle decommitment.
>     pub missing_evals: Vec<SecureField>,
> ```

wdyt?



_Suggestion:_
```XML
    /// values that the verifier needs but cannot deduce from previous computations, in the
    /// order they are needed.
    /// This complements the values that were queried. These must be supplied directly to
    /// the verifier.
    pub fri_witness: Vec<SecureField>,
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/prover/src/core/fri.rs` line 131 at r1](https://reviewable.io/reviews/starkware-libs/stwo/897#-OCTCfPo7UBqnpnBdlcT:-OCTCfPo7UBqnpnBdlcU:b-fhmpd8) ([raw file](https://github.com/starkware-libs/stwo/blob/2955551144e0b58cc9bb438ec296f4ab7989e78a/crates/prover/src/core/fri.rs#L131)):*
> ```XML
> pub struct FriProver<'a, B: FriOps + MerkleOps<MC::H>, MC: MerkleChannel> {
>     config: FriConfig,
>     first_layer: FriFirstLayerProver<'a, B, MC::H>,
> ```

not sure about the names since it includes all layers.



_Code quote:_
```XML
first_layer: FriFirstLayerProver<'a, B, MC::H>,
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/prover/src/core/pcs/quotients.rs` line 157 at r1](https://reviewable.io/reviews/starkware-libs/stwo/897#-OCTKU9m6pW07IlZUa9Q:-OCTKU9m6pW07IlZUa9R:bspp2w1) ([raw file](https://github.com/starkware-libs/stwo/blob/c46d77be6a8d17d679139544c4e3ca021c1b1bef/crates/prover/src/core/pcs/quotients.rs#L157)):*
> ```XML
>             let eval = CircleEvaluation::new(
>                 domain,
>                 queried_values.take(domain.size()).copied().collect_vec(),
> ```

Here you have 2 eval points per query, right?

How does this work after the change?



_Code quote:_
```XML
 queried_values.take(domain.size()).copied().collect_vec(),
```

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/897)* status: 0 of 11 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @shaharsamocha7)

___
*[`crates/prover/src/core/fri.rs` line 658 at r1](https://reviewable.io/reviews/starkware-libs/stwo/897#-OCSUOJKCZzioEzeABQ3:-OCTiSuB-7_vhyOyXsxn:bb6ywmx) ([raw file](https://github.com/starkware-libs/stwo/blob/2955551144e0b58cc9bb438ec296f4ab7989e78a/crates/prover/src/core/fri.rs#L658)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

wdyt?
</blockquote></details>

LGTM
___
*[`crates/prover/src/core/pcs/quotients.rs` line 157 at r1](https://reviewable.io/reviews/starkware-libs/stwo/897#-OCTKU9m6pW07IlZUa9Q:-OCThybN0lt0qk_2-tH8:b-1wpzam) ([raw file](https://github.com/starkware-libs/stwo/blob/c46d77be6a8d17d679139544c4e3ca021c1b1bef/crates/prover/src/core/pcs/quotients.rs#L157)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Here you have 2 eval points per query, right?

How does this work after the change?
</blockquote></details>

That was the case previously. 
Now only 1 eval per query now with FRI layer 0
___
*[`crates/prover/src/core/pcs/quotients.rs` line 150 at r1](https://reviewable.io/reviews/starkware-libs/stwo/897#-OCSR_m0-PBU41Yx2IE2:-OCTiKj2AlC-3CTeWXcr:b-q55qe5) ([raw file](https://github.com/starkware-libs/stwo/blob/2955551144e0b58cc9bb438ec296f4ab7989e78a/crates/prover/src/core/pcs/quotients.rs#L150)):*
> ```XML
>     for &query_position in query_positions {
>         let domain_point = commitment_domain.at(bit_reverse_index(query_position, log_size));
>         let row = row_index_iter.next().unwrap();
> ```

Done tyty

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/897)* status: 0 of 11 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @shaharsamocha7)

___
*[`crates/prover/src/core/fri.rs` line 131 at r1](https://reviewable.io/reviews/starkware-libs/stwo/897#-OCTCfPo7UBqnpnBdlcT:-OCTigr17f-uFbTqzyqY:bnrm9ni) ([raw file](https://github.com/starkware-libs/stwo/blob/2955551144e0b58cc9bb438ec296f4ab7989e78a/crates/prover/src/core/fri.rs#L131)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

not sure about the names since it includes all layers.
</blockquote></details>

Open to suggestions.

I guess the way I think about it is that the first layer could includes all possible sizes. But all these polynomials are still commited and folded in a single layer (what I currently have called the first layer).

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/prover/src/core/fri.rs` line 324 at r3](https://reviewable.io/reviews/starkware-libs/stwo/897#-OCTxxpt-W53RezzmPoe:-OCTxxpt-W53RezzmPof:b-5tqloe) ([raw file](https://github.com/starkware-libs/stwo/blob/492bb14239ff2f38afc2005f4bdadac45bc18d79/crates/prover/src/core/fri.rs#L324)):*
> ```XML
>     // TODO(andrew): Consider making this an `Option` since there may be curcumstances where we
>     // don't actually want to commit to the first layer evaluations. This is a simple change. FRI
>     // just returns more query positions for the first layer.
> ```

I think this might be a per-log-size configuration rather than a global one.



_Code quote:_
```XML
    // TODO(andrew): Consider making this an `Option` since there may be curcumstances where we
    // don't actually want to commit to the first layer evaluations. This is a simple change. FRI
    // just returns more query positions for the first layer.
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 3 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/897)* status: 2 of 11 files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/897)* status: 2 of 11 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @shaharsamocha7)

___
*[`crates/prover/src/core/fri.rs` line 324 at r3](https://reviewable.io/reviews/starkware-libs/stwo/897#-OCTxxpt-W53RezzmPoe:-OCU6ur73XG2bpqizrH4:b-q4nu4a) ([raw file](https://github.com/starkware-libs/stwo/blob/492bb14239ff2f38afc2005f4bdadac45bc18d79/crates/prover/src/core/fri.rs#L324)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I think this might be a per-log-size configuration rather than a global one.
</blockquote></details>

Updated the TODO. WDYT?

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 6 of 11 files at r1, 2 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/897#-:-OCWwqRvAeTg0qKXvBno:bnfp4nl)* status: 8 of 11 files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Pull request merged**
