### PR TITLE
Added `add_intermediate` and `add_secure_intermediate` to eval API.

### PR DESCRIPTION
**Pull request by Alon-Ti**

### CODE REVIEW

**Comment by Alon-Ti** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/919?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#919** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/919?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/919?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#918** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/918?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#908** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/908?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#904** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/904?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#903** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/903?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#901** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/901?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#894** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/894?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#893** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/893?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#892** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/892?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#889** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/889?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#888** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/888?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#887** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/887?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#879** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/879?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#883](https://github.com/starkware-libs/stwo/pull/883) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/883?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#876** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/876?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#875** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/875?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by ohad-agadi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/919)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @Alon-Ti and @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/mod.rs` line 122 at r2](https://reviewable.io/reviews/starkware-libs/stwo/919#-ODBSC4r8NA_VMs7UJuG:-ODBSC4r8NA_VMs7UJuH:b45h) ([raw file](https://github.com/starkware-libs/stwo/blob/2fe62b34237e4fddef3858f8f09c2b2602e531d7/crates/prover/src/constraint_framework/mod.rs#L122)):*
> ```XML
>     /// Adds a secure intermediate value to the component and returns its value.
>     /// Does nothing by default.
>     fn add_secure_intermediate(&mut self, val: Self::EF) -> Self::EF {
> ```





_Suggestion:_
```XML
extension
```

**Review by Alon-Ti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/919)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/mod.rs` line 122 at r2](https://reviewable.io/reviews/starkware-libs/stwo/919#-ODBSC4r8NA_VMs7UJuG:-ODBZSTx2a1gta2bghJS:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/2fe62b34237e4fddef3858f8f09c2b2602e531d7/crates/prover/src/constraint_framework/mod.rs#L122)):*
> ```XML
>     /// Adds a secure intermediate value to the component and returns its value.
>     /// Does nothing by default.
>     fn add_secure_intermediate(&mut self, val: Self::EF) -> Self::EF {
> ```

Done.

**Review by ohad-agadi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/919#-:-ODBes2CBgOTXWRwSUTo:bnfp4nl)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Comment by Alon-Ti** [comment]
### Merge activity

* **Dec 3, 8:19 AM EST**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/919).

**Pull request merged**
