### PR TITLE
Split circle poly module

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/420)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
Current dependencies on/for this PR:
* **#420** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/420?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/420?utm_source=stack-comment).

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/420)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`src/core/poly/circle/mod.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/stwo/420#-Ns3MSZN5HfLI3d70ERV:-Ns3MSZN5HfLI3d70ERW:bscaetx) ([raw file](https://github.com/starkware-libs/stwo/blob/411a40a60020defceee7238add067e55cb18e31e/src/core/poly/circle/mod.rs#L17)):*
> ```XML
> pub use evaluation::{CircleEvaluation, CosetSubEvaluation};
> pub use ops::PolyOps;
> pub use poly::CirclePoly;
> ```

Is this common practice? Or do we want to change the imports everywhere to match the file reorg?



_Code quote:_
```XML
pub use canonic::CanonicCoset;
pub use domain::CircleDomain;
pub use evaluation::{CircleEvaluation, CosetSubEvaluation};
pub use ops::PolyOps;
pub use poly::CirclePoly;
```
___
*[`src/core/poly/circle/mod.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/stwo/420#-Ns3MpqA7ZJPOoHHnsRO:-Ns3MpqA7ZJPOoHHnsRP:bcdmvow) ([raw file](https://github.com/starkware-libs/stwo/blob/411a40a60020defceee7238add067e55cb18e31e/src/core/poly/circle/mod.rs#L47)):*
> ```XML
>             .expect("Not in points")]
>     }
> }
> ```

You can remove this while you're at it.



_Code quote:_
```XML
#[derive(Clone, Debug)]
pub struct PointMapping<F: ExtensionOf<BaseField>> {
    pub points: Vec<CirclePoint<F>>,
    pub values: Vec<F>,
}

impl<F: ExtensionOf<BaseField>> PointMapping<F> {
    pub fn new(points: Vec<CirclePoint<F>>, values: Vec<F>) -> Self {
        assert_eq!(points.len(), values.len());
        Self { points, values }
    }

    pub fn len(&self) -> usize {
        self.points.len()
    }

    pub fn is_empty(&self) -> bool {
        self.points.is_empty()
    }

    // TODO(AlonH): Consider optimizing data structures for a more efficient get_at.
    pub fn get_at(&self, point: CirclePoint<F>) -> F {
        self.values[self
            .points
            .iter()
            .position(|p| *p == point)
            .expect("Not in points")]
    }
}
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/420)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5)

___
*[`src/core/poly/circle/mod.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/stwo/420#-Ns3MSZN5HfLI3d70ERV:-Ns3w6Zo9fRY5UcGsFDc:bu5naw7) ([raw file](https://github.com/starkware-libs/stwo/blob/411a40a60020defceee7238add067e55cb18e31e/src/core/poly/circle/mod.rs#L17)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Is this common practice? Or do we want to change the imports everywhere to match the file reorg?
</blockquote></details>

I want to reexport them, so that consumers of this api won't have to know the internal structure of the lib.
Yes, it's common.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/420)* status: 9 of 14 files reviewed, 2 unresolved discussions (waiting on @alonh5)

___
*[`src/core/poly/circle/mod.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/stwo/420#-Ns3MpqA7ZJPOoHHnsRO:-Ns3xxjk65Tpa68491pp:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/411a40a60020defceee7238add067e55cb18e31e/src/core/poly/circle/mod.rs#L47)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

You can remove this while you're at it.
</blockquote></details>

Done.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/420#-:-Ns7bNEGDgYaa7yh5g64:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
