### PR TITLE
PackedCM31

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/415)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`src/core/backend/avx512/cm31.rs` line 7 at r1](https://reviewable.io/reviews/starkware-libs/stwo/415#-Ns2KWVe2cixiggzWumk:-Ns2KWVe2cixiggzWuml:b-kl43c0) ([raw file](https://github.com/starkware-libs/stwo/blob/83cbbe6dfd7da8bc6520519728a0e91762d40e9b/src/core/backend/avx512/cm31.rs#L7)):*
> ```XML
> 
> #[derive(Copy, Clone)]
> pub struct PackedCM31(pub [PackedBaseField; 2]);
> ```

document



_Code quote:_
```XML
pub struct PackedCM31(pub [PackedBaseField; 2]);
```

**Comment by ilyalesokhin-starkware** [comment]
*[`src/core/backend/avx512/cm31.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/stwo/415#-Ns2Kk0x74D6wXtbgxIP:-Ns2Kk0x74D6wXtbgxIQ:bsb3g3d) ([raw file](https://github.com/starkware-libs/stwo/blob/83cbbe6dfd7da8bc6520519728a0e91762d40e9b/src/core/backend/avx512/cm31.rs#L30)):*
> ```XML
>         let ac = self.0[0] * rhs.0[0];
>         let bd = self.0[1] * rhs.0[1];
>         let m = (self.0[0] + self.0[1]) * (rhs.0[0] + rhs.0[1]);
> ```

document
computes

(a+ib) * (c + i*d) = ...



_Code quote:_
```XML
        let ac = self.0[0] * rhs.0[0];
        let bd = self.0[1] * rhs.0[1];
        let m = (self.0[0] + self.0[1]) * (rhs.0[0] + rhs.0[1]);
```

**Comment by ilyalesokhin-starkware** [comment]
*[`src/core/backend/avx512/cm31.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/stwo/415#-Ns2Kk0x74D6wXtbgxIP:-Ns2L2AvAniTMl8iM7nU:b-lse7dh) ([raw file](https://github.com/starkware-libs/stwo/blob/83cbbe6dfd7da8bc6520519728a0e91762d40e9b/src/core/backend/avx512/cm31.rs#L30)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

document
computes

(a+ib) * (c + i*d) = ...
</blockquote></details>

mention  Karatsuba

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/415)* status: all files reviewed, 2 unresolved discussions (waiting on @ohad-starkware and @spapinistarkware)

**Comment by ilyalesokhin-starkware** [comment]
*[`src/core/backend/avx512/cm31.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/stwo/415#-Ns2N_V60ZPJ5ptFZdHB:-Ns2N_V60ZPJ5ptFZdHC:b-smfml1) ([raw file](https://github.com/starkware-libs/stwo/blob/83cbbe6dfd7da8bc6520519728a0e91762d40e9b/src/core/backend/avx512/cm31.rs#L28)):*
> ```XML
>     type Output = Self;
>     fn mul(self, rhs: Self) -> Self::Output {
>         let ac = self.0[0] * rhs.0[0];
> ```

consider adding getters



_Suggestion:_
```XML
    let ac = self.a() * rhs.a();
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/415)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @ohad-starkware)

___
*[`src/core/backend/avx512/cm31.rs` line 7 at r1](https://reviewable.io/reviews/starkware-libs/stwo/415#-Ns2KWVe2cixiggzWumk:-Ns2QaNF6liK9LpcdeoN:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/83cbbe6dfd7da8bc6520519728a0e91762d40e9b/src/core/backend/avx512/cm31.rs#L7)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

document
</blockquote></details>

Done.
___
*[`src/core/backend/avx512/cm31.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/stwo/415#-Ns2N_V60ZPJ5ptFZdHB:-Ns2QmSt7S_SRiIyfZdA:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/83cbbe6dfd7da8bc6520519728a0e91762d40e9b/src/core/backend/avx512/cm31.rs#L28)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

consider adding getters
</blockquote></details>

Done.
___
*[`src/core/backend/avx512/cm31.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/stwo/415#-Ns2Kk0x74D6wXtbgxIP:-Ns2R1jsDqzo_HXSmmnN:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/83cbbe6dfd7da8bc6520519728a0e91762d40e9b/src/core/backend/avx512/cm31.rs#L30)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

mention  Karatsuba
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/415#-:-Ns2Z9uW4a8uFJsTUfWr:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ohad-starkware)

**Pull request merged**
