### PR TITLE
Remove InteractionElements and LookupValues

### PR DESCRIPTION
**Pull request by andrewmilson**
InteractionElements removed in favour of storing interaction elements the components directly with LookupElements.  LookupValues removed in favour of storing lookup values on a claim struct.

This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/802)

### CODE REVIEW

**Comment by andrewmilson** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/802?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#802** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/802?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#801** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/801?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#800** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/800?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#799** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/799?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#798** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/798?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @andrewmilson and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/802)* status: all files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/lib.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/stwo/802#-O5DTI3Z1EXXd_4fzyqQ:-O5EW91t6c_W2H1QuPY0:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/b03472cb2c3fe2c5534241e83a62a7c0529ab8c9/crates/prover/src/lib.rs#L26)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Remove. This exists in github history.
</blockquote></details>

Done.
___
*[`crates/prover/src/examples/mod.rs` line 4 at r1](https://reviewable.io/reviews/starkware-libs/stwo/802#-O5DTRopEmK8Whmg4sKv:-O5EW9lU6NlGDP25xKh5:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/b03472cb2c3fe2c5534241e83a62a7c0529ab8c9/crates/prover/src/examples/mod.rs#L4)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Same
</blockquote></details>

Done.

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/802)* status: 9 of 24 files reviewed, 3 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo/802#-O5IjRKiEOAGPFycFvVy:-O5IjRKiEOAGPFycFvVz:bt669vu) (no related file):*
Samocha is doing this, without deleting fib
https://reviewable.io/reviews/starkware-libs/stwo/812

___

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 15 files at r2, 1 of 3 files at r3, 17 of 17 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/802)* status: all files reviewed, 2 unresolved discussions (waiting on @andrewmilson)

___
*[`crates/prover/src/examples/mod.rs` line 4 at r4](https://reviewable.io/reviews/starkware-libs/stwo/802#-O6GHsyODoBSPqQxuRLy:-O6GHsyPCPaOVMBEe4hx:byp18fd) ([raw file](https://github.com/starkware-libs/stwo/blob/1ee6a7073ec63dcecd8e7b791fcaf2925e22086b/crates/prover/src/examples/mod.rs#L4)):*
> ```XML
> pub mod plonk;
> pub mod poseidon;
> pub mod wide_fibonacci;
> ```

Remove



_Code quote:_
```XML
pub mod wide_fibonacci;
```

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/802)* status: all files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/prover/src/examples/mod.rs` line 4 at r4](https://reviewable.io/reviews/starkware-libs/stwo/802#-O6GHsyODoBSPqQxuRLy:-O6KPdvN6bWsUgP8kG-O:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/1ee6a7073ec63dcecd8e7b791fcaf2925e22086b/crates/prover/src/examples/mod.rs#L4)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Remove
</blockquote></details>

Done.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/802#-:-O6KYB6q63sEr-8Ts5Z9:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @andrewmilson)

**Review by shaharsamocha7 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/802)* status: all files reviewed, 1 unresolved discussion (waiting on @andrewmilson)

**Pull request merged**
