### PR TITLE
Generate secure powers helper function

### PR DESCRIPTION
**Pull request by shaharsamocha7**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/553)

### CODE REVIEW

**Comment by shaharsamocha7** [comment]
* **#554** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/554?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#553** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/553?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @shaharsamocha7 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/553#-:-Nu3xJu56PlzSi2zBmk6:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`src/core/utils.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/stwo/553#-Nu3vLT74LgMHI-IEfmV:-Nu3vLT74LgMHI-IEfmW:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/81c97a62fad890d4905329e573f2f86dad711cea/src/core/utils.rs#L42)):*
> ```XML
> }
> 
> pub fn generate_secure_powers(felt: SecureField, max_log_size: usize) -> Vec<SecureField> {
> ```





_Suggestion:_
```XML
max_exp
```
___
*[`src/core/backend/cpu/quotients.rs` line 86 at r1](https://reviewable.io/reviews/starkware-libs/stwo/553#-Nu3xAPKDhtW7O3x49QI:-Nu3xAPLB39fJmbqRp-s:bbha3e1) ([raw file](https://github.com/starkware-libs/stwo/blob/81c97a62fad890d4905329e573f2f86dad711cea/src/core/backend/cpu/quotients.rs#L86)):*
> ```XML
>     sample_batches
>         .iter()
>         .zip(random_coeff_powers.iter())
> ```

I find this more readable. Maybe you'll prefer it too.



_Suggestion:_
```XML
    zip(sample_batches, random_coeff_powers)
```

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/553)* status: all files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7)

___
*[`src/core/utils.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/stwo/553#-Nu3zr3a-bbXG66bkj7G:-Nu3zr3a-bbXG66bkj7H:b-6av9wm) ([raw file](https://github.com/starkware-libs/stwo/blob/81c97a62fad890d4905329e573f2f86dad711cea/src/core/utils.rs#L42)):*
> ```XML
> }
> 
> pub fn generate_secure_powers(felt: SecureField, max_log_size: usize) -> Vec<SecureField> {
> ```

and make exclusive



_Suggestion:_
```XML
 n_powers:
```

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/553)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @spapinistarkware)

___
*[`src/core/utils.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/stwo/553#-Nu3zr3a-bbXG66bkj7G:-NuIJEvS7GdKgVGMcAbW:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/81c97a62fad890d4905329e573f2f86dad711cea/src/core/utils.rs#L42)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

and make exclusive
</blockquote></details>

Done.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/553#-:-NuJPdJn878ClMpPFoxe:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/553)* status: all files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`src/core/utils.rs` line 46 at r4](https://reviewable.io/reviews/starkware-libs/stwo/553#-NuTTU584tqjN7IsjhLS:-NuTTU584tqjN7IsjhLT:b-1rmnu7) ([raw file](https://github.com/starkware-libs/stwo/blob/b452907121dbea3b50ab681b291960b6936c8338/src/core/utils.rs#L46)):*
> ```XML
> pub fn generate_secure_powers(felt: SecureField, n_powers: usize) -> Vec<SecureField> {
>     let mut res = vec![];
>     for _ in 0..min(1, n_powers) {
> ```

Try to use scan

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/553)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`src/core/utils.rs` line 46 at r4](https://reviewable.io/reviews/starkware-libs/stwo/553#-NuTTU584tqjN7IsjhLS:-NuXb7yX2WJPoB5nBhP1:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/b452907121dbea3b50ab681b291960b6936c8338/src/core/utils.rs#L46)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Try to use scan
</blockquote></details>

Done.

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/553)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Comment by shaharsamocha7** [comment]
### Merge activity

* **Apr 3, 3:03 AM EDT**: @shaharsamocha7 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/553).

**Pull request merged**
