### PR TITLE
Update CI to test Wasm simd128, avx2 and aarch64 neon

### PR DESCRIPTION
**Pull request by andrewmilson**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/614)

### CODE REVIEW

**Comment by andrewmilson** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/614?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#616** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/616?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#615** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/615?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#614** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/614?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#613** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/613?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#612** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/612?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#611** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/611?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#610** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/610?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#609** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/609?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#608** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/608?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#607** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/607?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#606** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/606?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#605** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/605?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#604** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/604?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#603** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/603?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#599** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/599?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#596** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/596?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#602** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/602?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#595** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/595?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#601** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/601?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#594** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/594?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#600** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/600?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#593** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/593?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#592** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/592?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#591** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/591?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @andrewmilson and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/614)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @alon-dotan-starkware and @andrewmilson)

___
*[`.github/workflows/ci.yaml` line 52 at r1](https://reviewable.io/reviews/starkware-libs/stwo/614#-NxC5rLpA8lwPe6fbSdd:-NxC5rLpA8lwPe6fbSde:b-4trsq7) ([raw file](https://github.com/starkware-libs/stwo/blob/aceec97a560b3bff612e71547c23155b973c2cd9/.github/workflows/ci.yaml#L52)):*
> ```YAML
>       - run: cargo +nightly-2024-01-04 doc
> 
>   run-wasm32-wasi-tests:
> ```

Can this be done with a matrix instead?

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/614)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @alon-dotan-starkware and @spapinistarkware)

___
*[`.github/workflows/ci.yaml` line 52 at r1](https://reviewable.io/reviews/starkware-libs/stwo/614#-NxC5rLpA8lwPe6fbSdd:-NxDClTNElG-ZG-XZs9b:bx6tj5h) ([raw file](https://github.com/starkware-libs/stwo/blob/aceec97a560b3bff612e71547c23155b973c2cd9/.github/workflows/ci.yaml#L52)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Can this be done with a matrix instead?
</blockquote></details>

It can. The way I thought about doing it with matrix required so many `if`s (for wasmtime, env variable, rustc flags) I figured it was much clearer just to have a seperate job. WDYT?

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/614)* status: all files reviewed, 1 unresolved discussion (waiting on @alon-dotan-starkware and @andrewmilson)

**Review by alon-dotan-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/614)* status: all files reviewed, 1 unresolved discussion (waiting on @andrewmilson)

**Review by alon-dotan-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/614#-:-NyLE7CsAQMkdxgOy3A7:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @andrewmilson)

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/614)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`.github/workflows/ci.yaml` line 52 at r1](https://reviewable.io/reviews/starkware-libs/stwo/614#-NxC5rLpA8lwPe6fbSdd:-NyLITLBBMsJMZ11LaBl:b-s5ixfk) ([raw file](https://github.com/starkware-libs/stwo/blob/5dd85bc011fc62a69a6fe967428ce86c4d7846c9/.github/workflows/ci.yaml#L52)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Then maybe just unite neon and avx to a matrix?
</blockquote></details>

AFAICT also requires `if`s. I think it's more maintainable having separate jobs

**Pull request merged**
