### PR TITLE
Generalize Stwo for generic Channel and MerkleHasher

### PR DESCRIPTION
**Pull request by carlogf**
Adapt Code to Accept Generic Channels and MerkleHashers

The objective of this PR is to adapt the code to accept generic `Channels` and `MerkleHashers`. This is already done for Fri and the vector commitment scheme. However the rest of the protocol works only with `Blake2sChannel` and `Blake2sMerkleHasher`.

This is achieved by adding generic types to function signatures to accept any type that implements the Channel and MerkleHasher traits. [Here](https://github.com/eryxcoop/stwo/blob/a6c836305ef0995098c051e3638f563b7e425477/crates/prover/src/trace_generation/prove.rs#L20) is an example of such a function.

We [added a test in wide_fibonacci](https://github.com/eryxcoop/stwo/blob/a6c836305ef0995098c051e3638f563b7e425477/crates/prover/src/examples/wide_fibonacci/mod.rs#L249) to verify functionality using Poseidon.

##### On the Hash Trait
The `Hasher` as it was was not natural to implement for Poseidon given that it assumes that the hash is essentialy a vector of `NativeType`. We noticed also that the `Hasher` was mainly used to avoid code repetition for the `concat_and_hash` and `hash` methods in `Blake2s` and `Blake3`. So we changed the `Hasher` to `BlakeHasher` and hardcoded the `NativeType` as `u8`. This allowed us to remove all appearances of `NativeType` in the trait bounds of `Hash`, making it straightforward to implement it for `FieldElement252`.

##### On Generalizing Channel in Proof_of_Work:
The proof of work still uses blake as a hash in the `hash_with_nonce` function. Therefore, to generalize the `Channel` in `proof_of_work`, we need the channel `Digest` as an array of bytes. We Added a `Serializable` trait and implemented it for `Blake2sHash` and `FieldElement252`.
We think it is better to leave generalizing the proof of work to use other hash functions for a future PR.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/759)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/759)* status: 1 of 23 files reviewed, 1 unresolved discussion (waiting on @carlogf)

___
*[`crates/prover/src/core/pcs/prover.rs` line 44 at r1](https://reviewable.io/reviews/starkware-libs/stwo/759#-O2sFo-a5VXu80ocNfkL:-O2sFo-a5VXu80ocNfkM:b-izoonn) ([raw file](https://github.com/starkware-libs/stwo/blob/eff694bc131b81f26814355d99758c7fd5bf5bf9/crates/prover/src/core/pcs/prover.rs#L44)):*
> ```XML
>     }
> 
>     pub fn commit(
> ```

I tihnk you have conflicts. This shouldn't be pub, and commit_on_evals shouldn't exist.
They were replaced with TreeBuilder.

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/759)* status: 1 of 23 files reviewed, 5 unresolved discussions (waiting on @carlogf)

___
*[`crates/prover/src/core/pcs/verifier.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/stwo/759#-O2sG5KU4mN2mJ1AxUTU:-O2sG5KU4mN2mJ1AxUTV:b-a84oqc) ([raw file](https://github.com/starkware-libs/stwo/blob/eff694bc131b81f26814355d99758c7fd5bf5bf9/crates/prover/src/core/pcs/verifier.rs#L15)):*
> ```XML
> use super::utils::TreeVec;
> use super::CommitmentSchemeProof;
> use crate::core::channel::Channel as ChannelTrait;
> ```

Why is it aliased?
___
*[`crates/prover/src/core/prover/mod.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/stwo/759#-O2sGHJa2ZYqlyarFEkL:-O2sGHJa2ZYqlyarFEkM:b-vjxpu5) ([raw file](https://github.com/starkware-libs/stwo/blob/eff694bc131b81f26814355d99758c7fd5bf5bf9/crates/prover/src/core/prover/mod.rs#L17)):*
> ```XML
> use crate::core::air::{Air, AirExt, AirProverExt};
> use crate::core::backend::CpuBackend;
> use crate::core::channel::Channel as ChannelTrait;
> ```

No need to alias anymore, right?
___
*[`crates/prover/src/core/vcs/hasher.rs` line 6 at r1](https://reviewable.io/reviews/starkware-libs/stwo/759#-O2sH5COClsxLZ4-IRWI:-O2sH5COClsxLZ4-IRWJ:blx2zsv) ([raw file](https://github.com/starkware-libs/stwo/blob/eff694bc131b81f26814355d99758c7fd5bf5bf9/crates/prover/src/core/vcs/hasher.rs#L6)):*
> ```XML
> use serde::{Deserialize, Serialize};
> 
> pub trait Name {
> ```

I think this is also not relevant anymore and can be deleted.
___
*[`crates/prover/src/core/vcs/hasher.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/stwo/759#-O2sGn6X6aaF04thilDz:-O2sGn6X6aaF04thilE-:b-sbrgfi) ([raw file](https://github.com/starkware-libs/stwo/blob/eff694bc131b81f26814355d99758c7fd5bf5bf9/crates/prover/src/core/vcs/hasher.rs#L28)):*
> ```XML
> /// ```
> 
> pub trait BlakeHasher: Sized + Default {
> ```

I think this trait is no longer relevant, and we can delete it.

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 22 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/759)* status: all files reviewed, 5 unresolved discussions (waiting on @carlogf)

**Review by spapinistarkware — COMMENTED** [review]
Re proof of work. This is fine as a first step, but we will need POW in other hashes too, and not necessarily through byte serialization. This will probably require some trait (e.g. PowHash)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/759#-:-O2sM_ML30MgHm3WHJ0Y:bahsmuv)* status: all files reviewed, 5 unresolved discussions (waiting on @carlogf)

**Comment by carlogf** [comment]
Hey!
We addressed all requested changes :)

On the `Hasher` trait:
We removed the hasher trait along with the docstring example it had. The file is now named hash.rs since it is the only trait left in it.
Also, we passed its logic to blake2sHasher and Blake3Hasher. We removed `reset` since it was not used and moved `finalize_reset` to the tests module. 
I think it is ok for now and we can try to improve it in the future

Best!

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 14 of 19 files at r2, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/759#-:-O3BkK-98frjqwGOW0Vd:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @carlogf)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/759#-:-O3REZlf9DbLzEjfvo1Z:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @carlogf)

**Pull request merged**
