### PR TITLE
Fix merkle benchmarks

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/517)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
* **#517** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/517?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ohad-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/517)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`benches/merkle_bench.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/stwo/517#-NtUeLGn2eLKSdh8B52f:-NtUeLGn2eLKSdh8B52g:b-mkkhit) ([raw file](https://github.com/starkware-libs/stwo/blob/45655b8b9810b8d6a13844c29e7421ddfa99e842/benches/merkle_bench.rs#L21)):*
> ```XML
> }
> 
> fn merkle_bench<T: Hasher>(group: &mut BenchmarkGroup<'_, WallTime>, elems: &[M31])
> ```

can you also change this to H:Hasher? just looks weird
___
*[`benches/merkle_bench.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/stwo/517#-NtUe6j4ABXP3uQx-pFj:-NtUe6j4ABXP3uQx-pFk:b-wnyyyu) ([raw file](https://github.com/starkware-libs/stwo/blob/45655b8b9810b8d6a13844c29e7421ddfa99e842/benches/merkle_bench.rs#L34)):*
> ```XML
>     group.sample_size(10);
>     group.throughput(Throughput::Bytes((size * N_BYTES_U32) as u64));
>     group.bench_function(BenchmarkId::new(T::Hash::NAME, size), |b| {
> ```

the clone might add noise to the benchmark, iter_batched lets you do the clone outside the bench loop.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/517)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ohad-starkware)

___
*[`benches/merkle_bench.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/stwo/517#-NtUe6j4ABXP3uQx-pFj:-NtUnBtP77MwcrvAvWtI:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/45655b8b9810b8d6a13844c29e7421ddfa99e842/benches/merkle_bench.rs#L34)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

the clone might add noise to the benchmark, iter_batched lets you do the clone outside the bench loop.
</blockquote></details>

Done.

**Review by ohad-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/517#-:-NtUni512W-liOejk20w:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Comment by spapinistarkware** [comment]
### Merge activity

* **Mar 21, 3:02 AM EDT**: @spapinistarkware merged this pull request with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/517).

**Pull request merged**
