### PR TITLE
Optimized lookup combine

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/765)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/765?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#765** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/765?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#764** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/764?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#761** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/761?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#712** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/712?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#711** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/711?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#710** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/710?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#708** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/708?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#707** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/707?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#715** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/715?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#714** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/714?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#713** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/713?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#706** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/706?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#705** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/705?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#704** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/704?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#702** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/702?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#701** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/701?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 9 files at r2, 7 of 7 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/765)* status: all files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/constraint_framework/logup.rs` line 118 at r4](https://reviewable.io/reviews/starkware-libs/stwo/765#-O3WU2Ss5lRxunDExo51:-O3WU2St4hJJSIadqwjQ:byp1ktf) ([raw file](https://github.com/starkware-libs/stwo/blob/fe41cc23ac6ff31c34c718f11d1553280e90948d/crates/prover/src/constraint_framework/logup.rs#L118)):*
> ```XML
>     pub alpha: SecureField,
>     /// Precomputed powers of alpha.
>     powers: Vec<SecureField>,
> ```

Rename



_Suggestion:_
```XML
alpha_powers: Vec<SecureField>,
```
___
*[`crates/prover/src/constraint_framework/logup.rs` line 121 at r4](https://reviewable.io/reviews/starkware-libs/stwo/765#-O3WUB2E3tz3IT5XW_Lr:-O3WUB2E3tz3IT5XW_Ls:byp1ktf) ([raw file](https://github.com/starkware-libs/stwo/blob/fe41cc23ac6ff31c34c718f11d1553280e90948d/crates/prover/src/constraint_framework/logup.rs#L121)):*
> ```XML
> }
> impl LookupElements {
>     pub fn draw(channel: &mut Blake2sChannel, n_powers: usize) -> Self {
> ```

Rename



_Suggestion:_
```XML
n_alpha_powers: usize
```
___
*[`crates/prover/src/examples/poseidon/mod.rs` line 371 at r4](https://reviewable.io/reviews/starkware-libs/stwo/765#-O3WUbax1D630oiqtu-n:-O3WUbax1D630oiqtu-o:baf6zlm) ([raw file](https://github.com/starkware-libs/stwo/blob/fe41cc23ac6ff31c34c718f11d1553280e90948d/crates/prover/src/examples/poseidon/mod.rs#L371)):*
> ```XML
>     span.exit();
> 
>     // Draw lookup element.
> ```

non-blocking



_Suggestion:_
```XML
   // Draw lookup elements.
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/765)* status: 8 of 10 files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/logup.rs` line 118 at r4](https://reviewable.io/reviews/starkware-libs/stwo/765#-O3WU2Ss5lRxunDExo51:-O3WhT5h5vaWxcINPbVL:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/fe41cc23ac6ff31c34c718f11d1553280e90948d/crates/prover/src/constraint_framework/logup.rs#L118)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Rename
</blockquote></details>

Done.
___
*[`crates/prover/src/constraint_framework/logup.rs` line 121 at r4](https://reviewable.io/reviews/starkware-libs/stwo/765#-O3WUB2E3tz3IT5XW_Lr:-O3WhVeVDbVgyjsO53MV:b2o6swu) ([raw file](https://github.com/starkware-libs/stwo/blob/fe41cc23ac6ff31c34c718f11d1553280e90948d/crates/prover/src/constraint_framework/logup.rs#L121)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Rename
</blockquote></details>

This goes away next PR, and I'd ike to avoid conflicts:)

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/765#-:-O3X5E9k0oeaJzRyeByP:bnfp4nl)* status: 9 of 10 files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
