### PR TITLE
changed fft space tests to fri space

### PR DESCRIPTION
**Pull request by ohad-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/627)

### CODE REVIEW

**Comment by ohad-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/627?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#627** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/627?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#619** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/619?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#598** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/598?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#618](https://github.com/starkware-libs/stwo/pull/618) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/618?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#588** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/588?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#597](https://github.com/starkware-libs/stwo/pull/597) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/597?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#583** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/583?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ohad-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — APPROVED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/627)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @ohad-starkware)

___
*[`crates/prover/src/core/poly/circle/poly.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/stwo/627#-NxfyVpw7pVjPiZLrdxp:-NxfyVpw7pVjPiZLrdxq:b2umj6e) ([raw file](https://github.com/starkware-libs/stwo/blob/694dc868f18dec13e6a3540e642da19f77fae878/crates/prover/src/core/poly/circle/poly.rs#L83)):*
> ```XML
> 
> #[cfg(test)]
> impl crate::core::backend::cpu::CPUCirclePoly {
> ```

Move inside mod tests?



_Code quote:_
```XML
impl crate::core::backend::cpu::CPUCirclePoly {
```
___
*[`crates/prover/src/core/poly/circle/poly.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/stwo/627#-NxfyMzM1SjEFNquieqC:-NxfyMzM1SjEFNquieqD:b-j4vea9) ([raw file](https://github.com/starkware-libs/stwo/blob/694dc868f18dec13e6a3540e642da19f77fae878/crates/prover/src/core/poly/circle/poly.rs#L84)):*
> ```XML
> #[cfg(test)]
> impl crate::core::backend::cpu::CPUCirclePoly {
>     pub fn is_in_fri_space(&self, log_fft_size: u32) -> bool {
> ```

Document that those are all the polynomials with monoms of total degree at most n/2
You can write which monom you expect at index `(1 << log_fft_size) + 1`



_Code quote:_
```XML
pub fn is_in_fri_space(&self, log_fft_size: u32) -> bool {
```
___
*[`crates/prover/src/core/poly/circle/poly.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/stwo/627#-NxfzlckB_-Eldd4pCIL:-Nxfzlcl-ta8Hpwo07YJ:b-fo5d4i) ([raw file](https://github.com/starkware-libs/stwo/blob/694dc868f18dec13e6a3540e642da19f77fae878/crates/prover/src/core/poly/circle/poly.rs#L84)):*
> ```XML
> #[cfg(test)]
> impl crate::core::backend::cpu::CPUCirclePoly {
>     pub fn is_in_fri_space(&self, log_fft_size: u32) -> bool {
> ```

Can this function just do the assert?



_Code quote:_
```XML
 -> bool 
```
___
*[`crates/prover/src/core/poly/circle/poly.rs` line 91 at r1](https://reviewable.io/reviews/starkware-libs/stwo/627#-NxfzOa69OoSez4DuqvP:-NxfzOa69OoSez4DuqvQ:bqsp5tq) ([raw file](https://github.com/starkware-libs/stwo/blob/694dc868f18dec13e6a3540e642da19f77fae878/crates/prover/src/core/poly/circle/poly.rs#L91)):*
> ```XML
>             coeffs.pop();
>         }
>         coeffs.len() <= (1 << log_fft_size) + 1
> ```

consider



_Suggestion:_
```XML
let fri_space_max_degree = (1 << log_fft_size) + 1
..
coeffs.len() <= fri_space_max_degree
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/627)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/prover/src/core/poly/circle/poly.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/stwo/627#-NxfyVpw7pVjPiZLrdxp:-Nxg0MR_1jFwCmOKjkcJ:bz98kbo) ([raw file](https://github.com/starkware-libs/stwo/blob/694dc868f18dec13e6a3540e642da19f77fae878/crates/prover/src/core/poly/circle/poly.rs#L83)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Move inside mod tests?
</blockquote></details>

I moved it to the existing #[test] impl 
___
*[`crates/prover/src/core/poly/circle/poly.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/stwo/627#-NxfzlckB_-Eldd4pCIL:-Nxg0hLR8jGzxrIB40fE:b-z9h3oh) ([raw file](https://github.com/starkware-libs/stwo/blob/694dc868f18dec13e6a3540e642da19f77fae878/crates/prover/src/core/poly/circle/poly.rs#L84)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can this function just do the assert?
</blockquote></details>

I think the bool is better, because sometimes you might want to know that the polynomial is not in the said space before testing something else (I think I'm doing that now, asserting p is not in fft space -> decompose -> assert it is in fft space now).
___
*[`crates/prover/src/core/poly/circle/poly.rs` line 84 at r1](https://reviewable.io/reviews/starkware-libs/stwo/627#-NxfyMzM1SjEFNquieqC:-NxgDGAI5qfq2gj8TnR6:bb7f2mf) ([raw file](https://github.com/starkware-libs/stwo/blob/694dc868f18dec13e6a3540e642da19f77fae878/crates/prover/src/core/poly/circle/poly.rs#L84)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Document that those are all the polynomials with monoms of total degree at most n/2
You can write which monom you expect at index `(1 << log_fft_size) + 1`
</blockquote></details>

done
___
*[`crates/prover/src/core/poly/circle/poly.rs` line 91 at r1](https://reviewable.io/reviews/starkware-libs/stwo/627#-NxfzOa69OoSez4DuqvP:-NxgBzzODr2oRWzQboY1:b-8nruyq) ([raw file](https://github.com/starkware-libs/stwo/blob/694dc868f18dec13e6a3540e642da19f77fae878/crates/prover/src/core/poly/circle/poly.rs#L91)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

consider
</blockquote></details>

it's more of an index and not a degree, the location of the coefficient of `x^(n/2 - 1)y` is n-1  , the one after that is x^n/2.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/627)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @ohad-starkware)

___
*[`crates/prover/src/core/poly/circle/poly.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/stwo/627#-NxfyVpw7pVjPiZLrdxp:-NxgIGgy9wHST0UWOYuC:b-4d8lm3) ([raw file](https://github.com/starkware-libs/stwo/blob/694dc868f18dec13e6a3540e642da19f77fae878/crates/prover/src/core/poly/circle/poly.rs#L83)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

I moved it to the existing #[test] impl
</blockquote></details>

Can you also move is_in_fft_space?
___
*[`crates/prover/src/core/poly/circle/poly.rs` line 91 at r1](https://reviewable.io/reviews/starkware-libs/stwo/627#-NxfzOa69OoSez4DuqvP:-NxgIvmZDtSRkmPlDhaS:b8ieq93) ([raw file](https://github.com/starkware-libs/stwo/blob/694dc868f18dec13e6a3540e642da19f77fae878/crates/prover/src/core/poly/circle/poly.rs#L91)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

it's more of an index and not a degree, the location of the coefficient of `x^(n/2 - 1)y` is n-1  , the one after that is x^n/2.
</blockquote></details>

I still think that an extra variable can be helpful

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/627)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/prover/src/core/poly/circle/poly.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/stwo/627#-NxfyVpw7pVjPiZLrdxp:-NxgkQFT5ri8jbkuE8Sf:b-42k812) ([raw file](https://github.com/starkware-libs/stwo/blob/694dc868f18dec13e6a3540e642da19f77fae878/crates/prover/src/core/poly/circle/poly.rs#L83)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can you also move is_in_fft_space?
</blockquote></details>

they're in the same place now
___
*[`crates/prover/src/core/poly/circle/poly.rs` line 91 at r1](https://reviewable.io/reviews/starkware-libs/stwo/627#-NxfzOa69OoSez4DuqvP:-NxgkPjF183jqW3rQDHo:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/694dc868f18dec13e6a3540e642da19f77fae878/crates/prover/src/core/poly/circle/poly.rs#L91)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I still think that an extra variable can be helpful
</blockquote></details>

Done.

**Review by shaharsamocha7 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/627)* status: all files reviewed, 1 unresolved discussion (waiting on @ohad-starkware)

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/627#-:-Nxh2Cdh2ZIp1YhGBAfN:bnfp4nl)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @ohad-starkware)

___
*[`crates/prover/src/core/poly/circle/poly.rs` line 81 at r4](https://reviewable.io/reviews/starkware-libs/stwo/627#-Nxh26_-3S7REa1k5Oda:-Nxh26_-3S7REa1k5Odb:bit258f) ([raw file](https://github.com/starkware-libs/stwo/blob/07577db9e2f14c448b8c38aae673c466c7619652/crates/prover/src/core/poly/circle/poly.rs#L81)):*
> ```XML
>         // The highest degree monomial in a fft-space polynomial is x^{(n/2) - 1}y.
>         // And it is at offset (n-1). x^{(n/2)} is at offset `n`, and is not allowed.
>         let highest_degree_allowed_monomial_offset = 1 << log_fft_size;
> ```

to match the variable name in is_in_fri_space



_Suggestion:_
```XML
        let highest_degree_monomial_offset = 1 << log_fft_size;
```

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/627)* status: all files reviewed, 1 unresolved discussion (waiting on @ohad-starkware)

___
*[`crates/prover/src/core/poly/circle/poly.rs` line 85 at r4](https://reviewable.io/reviews/starkware-libs/stwo/627#-Ny-X5PhCcoQ-MZZk3z5:-Ny-X5PhCcoQ-MZZk3z6:bg72hp4) ([raw file](https://github.com/starkware-libs/stwo/blob/d08a50793d0aff658abbd38f1afc44b04fbf4169/crates/prover/src/core/poly/circle/poly.rs#L85)):*
> ```XML
>     }
> 
>     /// Fri space is the space of polynomials of total degree n/2.
> ```

the terminology we use for this space should be consistent with the docs in decompose().

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/627)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/core/poly/circle/poly.rs` line 85 at r4](https://reviewable.io/reviews/starkware-libs/stwo/627#-Ny-X5PhCcoQ-MZZk3z5:-Ny-ln_K5_qESCZM4H7J:bb3n969) ([raw file](https://github.com/starkware-libs/stwo/blob/eae24c7ed54e9e1e21566f4948ce61617944a04a/crates/prover/src/core/poly/circle/poly.rs#L85)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

I left the FRI-space definition here and referred to it from the decompose (using FRI-space as a defined term).
</blockquote></details>

nevermind it's a test function, I changed the doc to be consistent.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/627#-:-Ny0MHkG11Vru80wZsAg:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ohad-starkware)

**Pull request merged**
