### PR TITLE
Add measurement logs

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/493)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/493?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#495** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/495?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#494** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/494?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#493** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/493?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#492** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/492?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#491** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/491?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#490** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/490?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#489** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/489?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#488** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/488?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#487** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/487?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#486** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/486?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#484** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/484?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#483** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/483?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#482** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/482?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#481** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/481?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#480** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/480?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#479** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/479?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#478** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/478?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#463** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/463?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#477** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/477?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#476** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/476?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — APPROVED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/493)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`src/examples/wide_fibonacci/avx.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/stwo/493#-NvWL7Sd9JNpz3NOjR5L:-NvWL7Se2GpFIjsG8O5G:b-1h5eoy) ([raw file](https://github.com/starkware-libs/stwo/blob/82a86ae7afb5380f3d4a8a778232c3d5042c3dc5/src/examples/wide_fibonacci/avx.rs#L39)):*
> ```XML
>     log_size: usize,
> ) -> ColumnVec<CircleEvaluation<AVX512Backend, BaseField, BitReversedOrder>> {
>     let _span = span!(Level::INFO, "Trace generation").entered();
> ```

Can you move it to the caller?
https://github.com/starkware-libs/stwo/blob/f3da0ed3fccf130007d87904362823129715775b/src/examples/fibonacci/mod.rs#L53



_Code quote:_
```XML
  let _span = span!(Level::INFO, "Trace generation").entered();
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/493)* status: 7 of 11 files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`src/examples/wide_fibonacci/avx.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/stwo/493#-NvWL7Sd9JNpz3NOjR5L:-NvWPn4f2hj1lYLuM2EP:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/82a86ae7afb5380f3d4a8a778232c3d5042c3dc5/src/examples/wide_fibonacci/avx.rs#L39)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can you move it to the caller?
https://github.com/starkware-libs/stwo/blob/f3da0ed3fccf130007d87904362823129715775b/src/examples/fibonacci/mod.rs#L53
</blockquote></details>

Done.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/493)* status: 10 of 11 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`src/core/commitment_scheme/prover.rs` line 163 at r2](https://reviewable.io/reviews/starkware-libs/stwo/493#-NvWPRJB1SpBzRzXJrus:-NvWPRJB1SpBzRzXJrut:b-8iy4b) ([raw file](https://github.com/starkware-libs/stwo/blob/eeb1ad03d48c0cf67b53396e623940c4ac622d1e/src/core/commitment_scheme/prover.rs#L163)):*
> ```XML
>         span.exit();
> 
>         let _span = span!(Level::INFO, "Commitment merkle").entered();
> ```

Why do you need to bind it to a variable?



_Code quote:_
```XML
let _span = 
```
___
*[`src/examples/wide_fibonacci/avx.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/stwo/493#-NvWQNCKBO6q4vm9fDcy:-NvWQNCL0ikp9IOLHvJY:b-chzzcw) ([raw file](https://github.com/starkware-libs/stwo/blob/eeb1ad03d48c0cf67b53396e623940c4ac622d1e/src/examples/wide_fibonacci/avx.rs#L74)):*
> ```XML
>         evaluation_accumulator: &mut DomainEvaluationAccumulator<AVX512Backend>,
>     ) {
>         let span = span!(Level::INFO, "Constraint eval extension").entered();
> ```

This is not just the extension here.



_Code quote:_
```XML
 let span = span!(Level::INFO, "Constraint eval extension").entered();
```
___
*[`src/examples/wide_fibonacci/avx.rs` line 170 at r3](https://reviewable.io/reviews/starkware-libs/stwo/493#-NvWQ_HeDEa8f0NLdhU-:-NvWQ_Hf1uiqupHkOPnF:b4bqcv9) ([raw file](https://github.com/starkware-libs/stwo/blob/c79fbdb31aa4e390df848a203926eafaa3275d92/src/examples/wide_fibonacci/avx.rs#L170)):*
> ```XML
>     fn test_avx_wide_fib_prove() {
>         // Note: To see time measurement, run test with
>         //   RUST_LOG_SPAN_EVENTS=enter,close RUST_LOG=info RUST_BACKTRACE=1 RUSTFLAGS="-Awarnings
> ```

Why do you have warnings here?



_Code quote:_
```XML
RUSTFLAGS="-Awarnings
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/493)* status: 10 of 11 files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7)

___
*[`src/core/commitment_scheme/prover.rs` line 163 at r2](https://reviewable.io/reviews/starkware-libs/stwo/493#-NvWPRJB1SpBzRzXJrus:-NvWRf3u2MeQyTMBlx47:b-tgj51u) ([raw file](https://github.com/starkware-libs/stwo/blob/eeb1ad03d48c0cf67b53396e623940c4ac622d1e/src/core/commitment_scheme/prover.rs#L163)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why do you need to bind it to a variable?
</blockquote></details>

I think it's more consistent with the `let span=` calls.
___
*[`src/examples/wide_fibonacci/avx.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/stwo/493#-NvWQNCKBO6q4vm9fDcy:-NvWRYv073Z2gUgfsEAQ:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/eeb1ad03d48c0cf67b53396e623940c4ac622d1e/src/examples/wide_fibonacci/avx.rs#L74)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

This is not just the extension here.
</blockquote></details>

Done.
___
*[`src/examples/wide_fibonacci/avx.rs` line 170 at r3](https://reviewable.io/reviews/starkware-libs/stwo/493#-NvWQ_HeDEa8f0NLdhU-:-NvWRe4eCeN9_TsNkOVw:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/c79fbdb31aa4e390df848a203926eafaa3275d92/src/examples/wide_fibonacci/avx.rs#L170)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why do you have warnings here?
</blockquote></details>

Done.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/493#-:-NvWVH3xDm1TtFENVIAD:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Comment by spapinistarkware** [comment]
### Merge activity

* **Apr 15, 7:31 AM EDT**: @spapinistarkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/493).

**Pull request merged**
