### PR TITLE
integrated decomposition in fri

### PR DESCRIPTION
**Pull request by ohad-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/598)

### CODE REVIEW

**Comment by ohad-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/598?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#598** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/598?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#588** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/588?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#597](https://github.com/starkware-libs/stwo/pull/597) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/597?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#583** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/583?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ohad-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by andrewmilson — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/598)* status: 1 of 3 files reviewed, 8 unresolved discussions (waiting on @alonh5, @ohad-starkware, and @spapinistarkware)

___
*[`crates/prover/src/core/fri.rs` line 932 at r1](https://reviewable.io/reviews/starkware-libs/stwo/598#-NwrVZ1g74r1d2D5VZB2:-NwrVZ1g74r1d2D5VZB3:b45h) ([raw file](https://github.com/starkware-libs/stwo/blob/2b44fb33f64d46d8b1109f24704fb625fef0d9a5/crates/prover/src/core/fri.rs#L932)):*
> ```XML
>     }
> 
>     // self = self * alpha + rhs.
> ```





_Suggestion:_
```XML
/// Computes `self = self * alpha + rhs`.
```
___
*[`crates/prover/src/core/fri.rs` line 933 at r1](https://reviewable.io/reviews/starkware-libs/stwo/598#-NwrVyCn363P1yFm56Ek:-NwrVyCn363P1yFm56El:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/2b44fb33f64d46d8b1109f24704fb625fef0d9a5/crates/prover/src/core/fri.rs#L933)):*
> ```XML
> 
>     // self = self * alpha + rhs.
>     fn accumulate(&mut self, rhs: SparseCircleEvaluation, alpha: SecureField) {
> ```





_Suggestion:_
```XML
Self
```
___
*[`crates/prover/src/core/fri.rs` line 1507 at r1](https://reviewable.io/reviews/starkware-libs/stwo/598#-NwrMjvFBk4GWmsKWJba:-NwrMjvFBk4GWmsKWJbb:b45h) ([raw file](https://github.com/starkware-libs/stwo/blob/2b44fb33f64d46d8b1109f24704fb625fef0d9a5/crates/prover/src/core/fri.rs#L1507)):*
> ```XML
> 
>     // Result is an evaluation of a polynomial that is out of FFT-space but inside
>     // riemann-roch-space.
> ```





_Suggestion:_
```XML
    /// Returns an evaluation of a polynomial that is out of FFT-space but inside
    /// riemann-roch-space.
```
___
*[`crates/prover/src/core/fri.rs` line 1530 at r1](https://reviewable.io/reviews/starkware-libs/stwo/598#-NwrXdfX8op9lbFq3uJj:-NwrXdfX8op9lbFq3uJk:b-6a9qr2) ([raw file](https://github.com/starkware-libs/stwo/blob/2b44fb33f64d46d8b1109f24704fb625fef0d9a5/crates/prover/src/core/fri.rs#L1530)):*
> ```XML
>     }
> 
>     #[test]
> ```

Can these tests be moved above the helper functions plz
___
*[`crates/prover/src/core/fri.rs` line 1531 at r1](https://reviewable.io/reviews/starkware-libs/stwo/598#-Nwr_0e940IyBcXfTgE7:-Nwr_0e940IyBcXfTgE8:b-7zi8ni) ([raw file](https://github.com/starkware-libs/stwo/blob/2b44fb33f64d46d8b1109f24704fb625fef0d9a5/crates/prover/src/core/fri.rs#L1531)):*
> ```XML
> 
>     #[test]
>     fn high_degree_proof_passes_verification() -> Result<(), FriVerificationError> {
> ```

WDYT?



_Suggestion:_
```XML
low_degree_polynomial_outside_fft_space_passes_verification
```
___
*[`crates/prover/src/core/fri.rs` line 1535 at r1](https://reviewable.io/reviews/starkware-libs/stwo/598#-NwrWUeI19alXKJvHMG_:-NwrWUeI19alXKJvHMGa:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/2b44fb33f64d46d8b1109f24704fb625fef0d9a5/crates/prover/src/core/fri.rs#L1535)):*
> ```XML
>         const LOG_DOMAIN_SIZE: u32 = LOG_DEGREE + 1;
> 
>         let evaluation = riemann_roch_polynomial_evaluation(LOG_DOMAIN_SIZE);
> ```





_Suggestion:_
```XML
        const LOG_DOMAIN_SIZE: u32 = LOG_DEGREE + 1;
        let evaluation = riemann_roch_polynomial_evaluation(LOG_DOMAIN_SIZE);
```
___
*[`crates/prover/src/core/fri.rs` line 1559 at r1](https://reviewable.io/reviews/starkware-libs/stwo/598#-Nwr_3Dm4_7nFOQl-tAA:-Nwr_3Dm4_7nFOQl-tAB:b-7zi8ni) ([raw file](https://github.com/starkware-libs/stwo/blob/2b44fb33f64d46d8b1109f24704fb625fef0d9a5/crates/prover/src/core/fri.rs#L1559)):*
> ```XML
> 
>     #[test]
>     fn valid_mixed_high_degree_proof_passes_verification() -> Result<(), FriVerificationError> {
> ```

WDYT?



_Suggestion:_
```XML
low_degree_polynomials_outside_fft_space_pass_verification
```
___
*[`crates/prover/src/core/fri.rs` line 1560 at r1](https://reviewable.io/reviews/starkware-libs/stwo/598#-NwrZcy725wzoU0o5HI1:-NwrZcy725wzoU0o5HI2:b-gn55x0) ([raw file](https://github.com/starkware-libs/stwo/blob/2b44fb33f64d46d8b1109f24704fb625fef0d9a5/crates/prover/src/core/fri.rs#L1560)):*
> ```XML
>     #[test]
>     fn valid_mixed_high_degree_proof_passes_verification() -> Result<(), FriVerificationError> {
>         const LOG_DEGREES: [u32; 3] = [6, 5, 4];
> ```

Might be worth having a couple with the same degree to cover the combination logic



_Suggestion:_
```XML
[6, 5, 5]
```

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/598)* status: 1 of 3 files reviewed, 9 unresolved discussions (waiting on @alonh5 and @ohad-starkware)

___
*[`crates/prover/src/core/fri.rs` line 211 at r1](https://reviewable.io/reviews/starkware-libs/stwo/598#-NwsSYb2Cw6oCYuH44Hj:-NwsSYb2Cw6oCYuH44Hk:b-dg9k6l) ([raw file](https://github.com/starkware-libs/stwo/blob/2b44fb33f64d46d8b1109f24704fb625fef0d9a5/crates/prover/src/core/fri.rs#L211)):*
> ```XML
>             // Check for any columns (circle poly evaluations) that should be combined.
>             while let Some(column) = columns.next_if(|c| folded_len(c) == layer_evaluation.len()) {
>                 let (g, lambda) = B::decompose(column);
> ```

Please try to decompose after accumulating, it's way more efficient.

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/598)* status: 0 of 7 files reviewed, 9 unresolved discussions (waiting on @alonh5, @andrewmilson, and @spapinistarkware)

___
*[`crates/prover/src/core/fri.rs` line 211 at r1](https://reviewable.io/reviews/starkware-libs/stwo/598#-NwsSYb2Cw6oCYuH44Hj:-Nx6ojW278kK9LeSZkVn:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/2b44fb33f64d46d8b1109f24704fb625fef0d9a5/crates/prover/src/core/fri.rs#L211)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Please try to decompose after accumulating, it's way more efficient.
</blockquote></details>

Done.
___
*[`crates/prover/src/core/fri.rs` line 932 at r1](https://reviewable.io/reviews/starkware-libs/stwo/598#-NwrVZ1g74r1d2D5VZB2:-Nx6SY_j0W9GcqrofM5Q:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/2b44fb33f64d46d8b1109f24704fb625fef0d9a5/crates/prover/src/core/fri.rs#L932)):*
> ```XML
>     }
> 
>     // self = self * alpha + rhs.
> ```

Done.
___
*[`crates/prover/src/core/fri.rs` line 933 at r1](https://reviewable.io/reviews/starkware-libs/stwo/598#-NwrVyCn363P1yFm56Ek:-Nx6SQlE7nu9w6R3-AcE:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/2b44fb33f64d46d8b1109f24704fb625fef0d9a5/crates/prover/src/core/fri.rs#L933)):*
> ```XML
> 
>     // self = self * alpha + rhs.
>     fn accumulate(&mut self, rhs: SparseCircleEvaluation, alpha: SecureField) {
> ```

Done.
___
*[`crates/prover/src/core/fri.rs` line 1507 at r1](https://reviewable.io/reviews/starkware-libs/stwo/598#-NwrMjvFBk4GWmsKWJba:-Nx6SLhC2IzjTuK6oiZP:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/2b44fb33f64d46d8b1109f24704fb625fef0d9a5/crates/prover/src/core/fri.rs#L1507)):*
> ```XML
> 
>     // Result is an evaluation of a polynomial that is out of FFT-space but inside
>     // riemann-roch-space.
> ```

Done.
___
*[`crates/prover/src/core/fri.rs` line 1530 at r1](https://reviewable.io/reviews/starkware-libs/stwo/598#-NwrXdfX8op9lbFq3uJj:-Nx6SHxT6B_zAPD5Tadp:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/2b44fb33f64d46d8b1109f24704fb625fef0d9a5/crates/prover/src/core/fri.rs#L1530)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Can these tests be moved above the helper functions plz
</blockquote></details>

Done.
___
*[`crates/prover/src/core/fri.rs` line 1531 at r1](https://reviewable.io/reviews/starkware-libs/stwo/598#-Nwr_0e940IyBcXfTgE7:-Nx6S4Go4eW_7jQ8YU_d:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/2b44fb33f64d46d8b1109f24704fb625fef0d9a5/crates/prover/src/core/fri.rs#L1531)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

WDYT?
</blockquote></details>

Done.
___
*[`crates/prover/src/core/fri.rs` line 1535 at r1](https://reviewable.io/reviews/starkware-libs/stwo/598#-NwrWUeI19alXKJvHMG_:-Nx6S9m_1OdD8_GaH5Mf:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/2b44fb33f64d46d8b1109f24704fb625fef0d9a5/crates/prover/src/core/fri.rs#L1535)):*
> ```XML
>         const LOG_DOMAIN_SIZE: u32 = LOG_DEGREE + 1;
> 
>         let evaluation = riemann_roch_polynomial_evaluation(LOG_DOMAIN_SIZE);
> ```

Done.
___
*[`crates/prover/src/core/fri.rs` line 1559 at r1](https://reviewable.io/reviews/starkware-libs/stwo/598#-Nwr_3Dm4_7nFOQl-tAA:-Nx6S6uxAehjWSbL6a36:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/2b44fb33f64d46d8b1109f24704fb625fef0d9a5/crates/prover/src/core/fri.rs#L1559)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

WDYT?
</blockquote></details>

Done.
___
*[`crates/prover/src/core/fri.rs` line 1560 at r1](https://reviewable.io/reviews/starkware-libs/stwo/598#-NwrZcy725wzoU0o5HI1:-Nx6OnqUELcw--VAFhO3:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/2b44fb33f64d46d8b1109f24704fb625fef0d9a5/crates/prover/src/core/fri.rs#L1560)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Might be worth having a couple with the same degree to cover the combination logic
</blockquote></details>

Done.

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/598)* status: 0 of 7 files reviewed, 9 unresolved discussions (waiting on @alonh5, @andrewmilson, and @ohad-starkware)

___
*[`crates/prover/src/core/fri.rs` line 211 at r1](https://reviewable.io/reviews/starkware-libs/stwo/598#-NwsSYb2Cw6oCYuH44Hj:-NxBf-gL2stG9ChIAyUz:bwbuzqu) ([raw file](https://github.com/starkware-libs/stwo/blob/2b44fb33f64d46d8b1109f24704fb625fef0d9a5/crates/prover/src/core/fri.rs#L211)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Yeah, I was wrong. sorry.

**Review by andrewmilson — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 5 of 6 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/598#-:-NxCyqzA5tYyyIs77jmW:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @ohad-starkware)

___
*[`crates/prover/src/core/fri.rs` line 1530 at r1](https://reviewable.io/reviews/starkware-libs/stwo/598#-NwrXdfX8op9lbFq3uJj:-NxCyQh2-INbq34jAUe_:brbfpnc) ([raw file](https://github.com/starkware-libs/stwo/blob/2b44fb33f64d46d8b1109f24704fb625fef0d9a5/crates/prover/src/core/fri.rs#L1530)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I mean there are all the `#[test]` functions then all the helper functions, `polynomial_evaluation` being the first

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/598)* status: 1 of 7 files reviewed, 1 unresolved discussion (waiting on @alonh5, @andrewmilson, and @spapinistarkware)

___
*[`crates/prover/src/core/fri.rs` line 211 at r1](https://reviewable.io/reviews/starkware-libs/stwo/598#-NwsSYb2Cw6oCYuH44Hj:-NxC-EcQ-927h6PNnKSC:b4flyc5) ([raw file](https://github.com/starkware-libs/stwo/blob/2b44fb33f64d46d8b1109f24704fb625fef0d9a5/crates/prover/src/core/fri.rs#L211)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Yeah, I was wrong. sorry.
</blockquote></details>

reverted  and took a screenshot of comment.
___
*[`crates/prover/src/core/fri.rs` line 1530 at r1](https://reviewable.io/reviews/starkware-libs/stwo/598#-NwrXdfX8op9lbFq3uJj:-NxRZf9b4ALtmJ93r5eT:b-cos5r3) ([raw file](https://github.com/starkware-libs/stwo/blob/2b44fb33f64d46d8b1109f24704fb625fef0d9a5/crates/prover/src/core/fri.rs#L1530)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

I mean there are all the `#[test]` functions then all the helper functions, `polynomial_evaluation` being the first
</blockquote></details>

right, done.

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/598)* status: 1 of 7 files reviewed, 1 unresolved discussion (waiting on @alonh5, @andrewmilson, and @ohad-starkware)

___
*[`crates/prover/src/core/fri.rs` line 461 at r5](https://reviewable.io/reviews/starkware-libs/stwo/598#-NxvADQEAYSSwmysGUWl:-NxvADQEAYSSwmysGUWm:bubbvs7) ([raw file](https://github.com/starkware-libs/stwo/blob/8c110d71d2600da9cfabd71c8b56d841abfa409e/crates/prover/src/core/fri.rs#L461)):*
> ```XML
>         let mut layer_query_evals = vec![SecureField::zero(); layer_queries.len()];
> 
>         for layer in self.inner_layers.iter() {
> ```

The function looked beautiful before. It's a shame to make it look messy.
Can you make it pretty again?

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/598)* status: 1 of 7 files reviewed, 1 unresolved discussion (waiting on @alonh5, @andrewmilson, and @ohad-starkware)

___
*[`crates/prover/src/core/fri.rs` line 461 at r5](https://reviewable.io/reviews/starkware-libs/stwo/598#-NxvADQEAYSSwmysGUWl:-NxvB-LA4oG6vAPkbcl_:bkqah1w) ([raw file](https://github.com/starkware-libs/stwo/blob/8c110d71d2600da9cfabd71c8b56d841abfa409e/crates/prover/src/core/fri.rs#L461)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

The function looked beautiful before. It's a shame to make it look messy.
Can you make it pretty again?
</blockquote></details>

e.g. Extract something to a method / function

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 5 of 6 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/598)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @ohad-starkware)

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/598)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @alonh5, @andrewmilson, and @spapinistarkware)

___
*[`crates/prover/src/core/fri.rs` line 461 at r5](https://reviewable.io/reviews/starkware-libs/stwo/598#-NxvADQEAYSSwmysGUWl:-NxwJFUe3AG-l7_3hPvO:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/8c110d71d2600da9cfabd71c8b56d841abfa409e/crates/prover/src/core/fri.rs#L461)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

e.g. Extract something to a method / function
</blockquote></details>

Done.

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/598)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5 and @ohad-starkware)

___
*[`crates/prover/src/core/fri.rs` line 469 at r6](https://reviewable.io/reviews/starkware-libs/stwo/598#-Ny-Uy1p39hHabMASJAD:-Ny-Uy1p39hHabMASJAE:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/caae05756c5b9114544b8fb340b4ad02a9e47378/crates/prover/src/core/fri.rs#L469)):*
> ```XML
>                 // factor of alpha^2 for every column combined, even in mixed degree.
>                 // log base is circle_poly_alpha_sq.
>                 let mut log_previous_layer_combination_factor = 1;
> ```





_Suggestion:_
```XML
            let mut n_columns_in_layer = 1;
```
___
*[`crates/prover/src/core/fri.rs` line 483 at r6](https://reviewable.io/reviews/starkware-libs/stwo/598#-Ny-VhL80vR4Jm3rjmx1:-Ny-VhL80vR4Jm3rjmx2:bky3fnl) ([raw file](https://github.com/starkware-libs/stwo/blob/caae05756c5b9114544b8fb340b4ad02a9e47378/crates/prover/src/core/fri.rs#L483)):*
> ```XML
> 
>                 // Fix the combined polynomial into fft space using coefficient from the proof.
>                 // NOTE: specific to when log Blowup factor is 2.
> ```

Should this note be inside decomopose() instead?
___
*[`crates/prover/src/core/fri.rs` line 512 at r6](https://reviewable.io/reviews/starkware-libs/stwo/598#-Ny-W3_A1YfRTYuC1UoX:-Ny-W3_A1YfRTYuC1UoY:b-f21xg7) ([raw file](https://github.com/starkware-libs/stwo/blob/caae05756c5b9114544b8fb340b4ad02a9e47378/crates/prover/src/core/fri.rs#L512)):*
> ```XML
> 
>     /// See [`CPUBackend::decompose`] for the explanation of the decomposition.
>     fn decompose(layer_queries: &Queries, evals: &mut SparseCircleEvaluation, lambda: SecureField) {
> ```

This doesn't really decompose, right? Just projects to the fft-space part. (it doesn't return lambda).



_Suggestion:_
```XML
    /// Projects a polynomial evaluation to the fft-space.
    /// See [`CPUBackend::decompose`] for the explanation of the decomposition.
    fn project_to_fft_space(layer_queries: &Queries, evals: &mut SparseCircleEvaluation, lambda: SecureField) {
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/598)* status: 6 of 7 files reviewed, 3 unresolved discussions (waiting on @alonh5 and @spapinistarkware)

___
*[`crates/prover/src/core/fri.rs` line 469 at r6](https://reviewable.io/reviews/starkware-libs/stwo/598#-Ny-Uy1p39hHabMASJAD:-Ny-XXUe5OkS8uJ_PiIc:b-7rl0jd) ([raw file](https://github.com/starkware-libs/stwo/blob/caae05756c5b9114544b8fb340b4ad02a9e47378/crates/prover/src/core/fri.rs#L469)):*
> ```XML
>                 // factor of alpha^2 for every column combined, even in mixed degree.
>                 // log base is circle_poly_alpha_sq.
>                 let mut log_previous_layer_combination_factor = 1;
> ```

done.
___
*[`crates/prover/src/core/fri.rs` line 483 at r6](https://reviewable.io/reviews/starkware-libs/stwo/598#-Ny-VhL80vR4Jm3rjmx1:-Ny-YCGk98SI29tDPiFV:b9w9r5l) ([raw file](https://github.com/starkware-libs/stwo/blob/caae05756c5b9114544b8fb340b4ad02a9e47378/crates/prover/src/core/fri.rs#L483)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Should this note be inside decomopose() instead?
</blockquote></details>

moved it to project function doc
___
*[`crates/prover/src/core/fri.rs` line 512 at r6](https://reviewable.io/reviews/starkware-libs/stwo/598#-Ny-W3_A1YfRTYuC1UoX:-Ny-XASV5LHm9jJu33Z2:b-7jzv7t) ([raw file](https://github.com/starkware-libs/stwo/blob/caae05756c5b9114544b8fb340b4ad02a9e47378/crates/prover/src/core/fri.rs#L512)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

This doesn't really decompose, right? Just projects to the fft-space part. (it doesn't return lambda).
</blockquote></details>

right

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/598#-:-Ny0MB8w6VjP21-MPG5P:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Pull request merged**
