### PR TITLE
Add errors in prove.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/468)

### CODE REVIEW

**Comment by alonh5** [comment]
* **#468** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/468?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/468)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

___
*[`src/core/prover/mod.rs` line 62 at r2](https://reviewable.io/reviews/starkware-libs/stwo/468#-NswinXFD0ByzCK3vqgJ:-NswinXFD0ByzCK3vqgK:b-2ukgey) ([raw file](https://github.com/starkware-libs/stwo/blob/1909b0aef2727ef451adeb377494d49f6e5b679c/src/core/prover/mod.rs#L62)):*
> ```XML
> ) -> Result<StarkProof, ProvingError> {
>     // Check that traces are not too big.
>     for (i, trace) in trace.iter().enumerate() {
> ```

Add tests that catch these.
___
*[`src/core/prover/mod.rs` line 63 at r2](https://reviewable.io/reviews/starkware-libs/stwo/468#-NswiJ830yP1uCogFoxK:-NswiJ830yP1uCogFoxL:b-e59uwg) ([raw file](https://github.com/starkware-libs/stwo/blob/1909b0aef2727ef451adeb377494d49f6e5b679c/src/core/prover/mod.rs#L63)):*
> ```XML
>     // Check that traces are not too big.
>     for (i, trace) in trace.iter().enumerate() {
>         if trace.domain.log_size() > 30 - LOG_BLOWUP_FACTOR {
> ```

Should be a meaningully named constant.



_Code quote:_
```XML
30
```
___
*[`src/core/prover/mod.rs` line 63 at r2](https://reviewable.io/reviews/starkware-libs/stwo/468#-NswiOUo6ztDh5fPeoRX:-NswiOUo6ztDh5fPeoRY:boi1142) ([raw file](https://github.com/starkware-libs/stwo/blob/1909b0aef2727ef451adeb377494d49f6e5b679c/src/core/prover/mod.rs#L63)):*
> ```XML
>     // Check that traces are not too big.
>     for (i, trace) in trace.iter().enumerate() {
>         if trace.domain.log_size() > 30 - LOG_BLOWUP_FACTOR {
> ```

Move to lhs, to avoid overflow



_Code quote:_
```XML
- LOG_BLOWUP_FACTOR
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/468)* status: 0 of 8 files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`src/core/prover/mod.rs` line 62 at r2](https://reviewable.io/reviews/starkware-libs/stwo/468#-NswinXFD0ByzCK3vqgJ:-NsxItXG1WggPGSfTBKj:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/1909b0aef2727ef451adeb377494d49f6e5b679c/src/core/prover/mod.rs#L62)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Add tests that catch these.
</blockquote></details>

Done.
___
*[`src/core/prover/mod.rs` line 63 at r2](https://reviewable.io/reviews/starkware-libs/stwo/468#-NswiJ830yP1uCogFoxK:-NsxJr701k5_CA5mmFeU:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/1909b0aef2727ef451adeb377494d49f6e5b679c/src/core/prover/mod.rs#L63)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Should be a meaningully named constant.
</blockquote></details>

Done.
___
*[`src/core/prover/mod.rs` line 63 at r2](https://reviewable.io/reviews/starkware-libs/stwo/468#-NswiOUo6ztDh5fPeoRX:-NsxKCXb6YjyP07Nj0os:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/1909b0aef2727ef451adeb377494d49f6e5b679c/src/core/prover/mod.rs#L63)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Move to lhs, to avoid overflow
</blockquote></details>

Done.

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 5 of 7 files at r3, 2 of 3 files at r4, 2 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/468)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

___
*[`src/core/prover/mod.rs` line 282 at r6](https://reviewable.io/reviews/starkware-libs/stwo/468#-NtGPtn6Drq1prl6i1vH:-NtGPtn6Drq1prl6i1vI:bw1nvdd) ([raw file](https://github.com/starkware-libs/stwo/blob/faee35185ac23a6a0875f27f68e5ecf780a80d82/src/core/prover/mod.rs#L282)):*
> ```XML
>     #[error(
>         "Trace column {trace_index} log degree bound ({degree}) exceeded max log degree ({}).",
>         30 - LOG_BLOWUP_FACTOR
> ```

Use the constant



_Code quote:_
```XML
30 
```
___
*[`src/core/prover/mod.rs` line 293 at r6](https://reviewable.io/reviews/starkware-libs/stwo/468#-NtGPwka1v_Lkxa0MFTC:-NtGPwka1v_Lkxa0MFTD:b-2dslep) ([raw file](https://github.com/starkware-libs/stwo/blob/faee35185ac23a6a0875f27f68e5ecf780a80d82/src/core/prover/mod.rs#L293)):*
> ```XML
> 
> #[cfg(test)]
> pub fn test_channel() -> Blake2sChannel {
> ```

Consider moving inside tests module
___
*[`src/core/prover/mod.rs` line 358 at r6](https://reviewable.io/reviews/starkware-libs/stwo/468#-NtGQ-jj-EcDbCAw0-wx:-NtGQ-jj-EcDbCAw0-wy:bekoxa1) ([raw file](https://github.com/starkware-libs/stwo/blob/faee35185ac23a6a0875f27f68e5ecf780a80d82/src/core/prover/mod.rs#L358)):*
> ```XML
> 
>     #[test]
>     #[ignore]
> ```

Explain why this is ignore in a short comment.

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 7 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/468)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Comment by alonh5** [comment]
### Merge activity

* **Mar 20, 4:13 AM EDT**: @alonh5 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/468).

**Pull request merged**
