### PR TITLE
Use precomputed twiddles

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/494)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/494?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#495** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/495?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#494** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/494?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#493** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/493?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#492** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/492?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#491** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/491?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#490** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/490?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#489** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/489?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#488** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/488?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#487** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/487?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#486** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/486?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#484** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/484?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#483** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/483?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#482** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/482?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#481** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/481?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#480** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/480?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#479** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/479?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#478** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/478?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#463** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/463?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#477** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/477?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#476** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/476?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/494)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

___
*[`src/core/prover/mod.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/stwo/494#-NvWOCYEBEXdl4Mcr66e:-NvWPm2W6MACh_h2_QAL:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/87aa9c7fd74426f86e8f509a43ecfdf01fdc6437/src/core/prover/mod.rs#L75)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

+ LOG_BLOWUP_FACTOR?
</blockquote></details>

Done.
___
*[`src/core/prover/mod.rs` line 387 at r1](https://reviewable.io/reviews/starkware-libs/stwo/494#-NvWMjSH50I-iSsyLfOR:-NvWPbkq64Ab4w9q5qFj:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/87aa9c7fd74426f86e8f509a43ecfdf01fdc6437/src/core/prover/mod.rs#L387)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

What's that change?
</blockquote></details>

Done.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/494)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo/494#-NvWQnaJ2jWFG0ldJx2g:-NvWQnaJ2jWFG0ldJx2h:b-u5n2ss) (no related file):*
Do we need to add a "Could not compute twiddles for this domain" error?

___

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/494#-:-NvWREJ5AK2rBdT4LSEM:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Comment by spapinistarkware** [comment]
### Merge activity

* **Apr 15, 7:31 AM EDT**: @spapinistarkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/494).

**Pull request merged**
