### PR TITLE
Separate componenet and air trace writers.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/651)

### CODE REVIEW

**Comment by alonh5** [comment]
* **#646** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/646?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#644** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/644?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#642** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/642?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#639** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/639?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#638** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/638?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#637** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/637?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#636** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/636?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#651** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/651?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/651)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5 and @ohad-starkware)

___
*[`crates/prover/src/core/air/mod.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/stwo/651#-Nz8o_t14b1SuEiDRNem:-Nz8o_t14b1SuEiDRNen:b806k5) ([raw file](https://github.com/starkware-libs/stwo/blob/cb15009bdffc1394667ea08249e0e449c4737358/crates/prover/src/core/air/mod.rs#L29)):*
> ```XML
> pub trait AirTraceVerifier {
>     fn interaction_elements(&self, channel: &mut Blake2sChannel) -> InteractionElements;
> }
> ```

What is this trait?
Should this function be a part of the regular Air trait?



_Code quote:_
```XML
pub trait AirTraceVerifier {
    fn interaction_elements(&self, channel: &mut Blake2sChannel) -> InteractionElements;
}
```
___
*[`crates/prover/src/core/air/mod.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/stwo/651#-Nz8onA-DxJzRbpV3JL8:-Nz8onA01M0i5dJNheIo:bp4d3pk) ([raw file](https://github.com/starkware-libs/stwo/blob/cb15009bdffc1394667ea08249e0e449c4737358/crates/prover/src/core/air/mod.rs#L80)):*
> ```XML
> }
> 
> // TODO(AlonH): Rethink this trait.
> ```

I think you can remove that



_Code quote:_
```XML
// TODO(AlonH): Rethink this trait.
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/651)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5)

___
*[`crates/prover/src/core/air/mod.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/stwo/651#-Nz8p3E70XB8pBzKJXaJ:-Nz8p3E70XB8pBzKJXaK:b-v4e7yr) ([raw file](https://github.com/starkware-libs/stwo/blob/cb15009bdffc1394667ea08249e0e449c4737358/crates/prover/src/core/air/mod.rs#L38)):*
> ```XML
>     ) -> ComponentVec<CircleEvaluation<B, BaseField, BitReversedOrder>>;
> 
>     fn to_air_prover(&self) -> &dyn AirProver<B>;
> ```

why dyn here? wouldn't it be a static type in every implementation?

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/651)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5)

___
*[`crates/prover/src/core/air/mod.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/stwo/651#-Nz8p3E70XB8pBzKJXaJ:-Nz8pml44jEUR9fpmdKv:bc9dsa3) ([raw file](https://github.com/starkware-libs/stwo/blob/cb15009bdffc1394667ea08249e0e449c4737358/crates/prover/src/core/air/mod.rs#L38)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

why dyn here? wouldn't it be a static type in every implementation?
</blockquote></details>

nevermind you changed it later

**Review by ohad-starkware — COMMENTED** [review]
:lgtm: other than the trait seperation (every Air is an AirVerifier)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/651#-:-Nz8s_bB2YGoYv7X_0Mz:beyw96c)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5)

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/651)* status: all files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/prover/src/core/air/mod.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/stwo/651#-Nz8o_t14b1SuEiDRNem:-NzN8SKR1pLAbOlUpyli:b7rvrhy) ([raw file](https://github.com/starkware-libs/stwo/blob/cb15009bdffc1394667ea08249e0e449c4737358/crates/prover/src/core/air/mod.rs#L29)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

What is this trait?
Should this function be a part of the regular Air trait?
</blockquote></details>

Then `AirTraceWriter` would also have to be an `Air` and therefore implement `components`, which it can't. This is part of the separation we needed.
___
*[`crates/prover/src/core/air/mod.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/stwo/651#-Nz8onA-DxJzRbpV3JL8:-NzN6kTq5ssXEAmK8TcW:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/cb15009bdffc1394667ea08249e0e449c4737358/crates/prover/src/core/air/mod.rs#L80)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I think you can remove that
</blockquote></details>

Done.

**Review by ohad-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/651#-:-NzRpAk19CQh9Ax3wH9i:bnfp4nl)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7)

**Review by shaharsamocha7 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/651)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/651#-:-O-GUwKyEmeNwchwKCRV:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Pull request merged**
