### PR TITLE
Combine opening and decommiting in commitnment scheme.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/440)

### CODE REVIEW

**Comment by alonh5** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/440?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#440** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/440?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#439** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/439?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#434** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/434?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#435** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/435?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/440)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @shaharsamocha7)

___
*[`src/core/commitment_scheme.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/stwo/440#-NsMNE7bBmVzKTqsRs_i:-NsMNE7bBmVzKTqsRs_j:bchp3ks) ([raw file](https://github.com/starkware-libs/stwo/blob/83918a3a8da25288cabd9e7f3edd207bf63f4658/src/core/commitment_scheme.rs#L52)):*
> ```XML
>     }
> 
>     pub fn decommit(
> ```

Decommit and pen are different things.
I think we need to change the itnerface to this thing a bit.
The interface should be open, and decommit positions should be an implementation detail.

The user of a commitmentscheme want to prove the "opening" at some points (in our case, the mask at the oods point), and to do this the commitment scheme uses FRI, which needs decommitments in its working.

Let's discuss.

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/440)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`src/core/commitment_scheme.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/stwo/440#-NsMNE7bBmVzKTqsRs_i:-NsNGFkA2Aj0HUqBs2IK:bpkkbw0) ([raw file](https://github.com/starkware-libs/stwo/blob/83918a3a8da25288cabd9e7f3edd207bf63f4658/src/core/commitment_scheme.rs#L52)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Decommit and pen are different things.
I think we need to change the itnerface to this thing a bit.
The interface should be open, and decommit positions should be an implementation detail.

The user of a commitmentscheme want to prove the "opening" at some points (in our case, the mask at the oods point), and to do this the commitment scheme uses FRI, which needs decommitments in its working.

Let's discuss.
</blockquote></details>

As discussed, changed `scheme` -> `tree` and added a todo to create a commitment scheme.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/440#-:-NsNKjI_391kejO4ZKnt:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/440)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Pull request merged**
