### PR TITLE
Fall back to cpu in small fft size.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/827)

### CODE REVIEW

**Comment by alonh5** [comment]
* **#827** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/827?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by andrewmilson — CHANGES_REQUESTED** [review]
Can all relevant tests be added please

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/827#-:-O6NPr7iEBaCzFiMIq-O:b-fm3asn)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

___
*[`crates/prover/src/core/backend/simd/circle.rs` line 148 at r1](https://reviewable.io/reviews/starkware-libs/stwo/827#-O6NOKNEBC7rJvD9eogc:-O6NOKNF3Bd_vgDKdSGA:b-1s0npx) ([raw file](https://github.com/starkware-libs/stwo/blob/da9d4c76f4d48a32fbee01f9a69238d61253e5a1/crates/prover/src/core/backend/simd/circle.rs#L148)):*
> ```XML
>         let log_size = eval.values.length.ilog2();
>         if log_size < MIN_FFT_LOG_SIZE {
>             let cpu_poly = CpuBackend::interpolate(eval.to_cpu(), &twiddles.to_cpu());
> ```

twiddles.to_cpu() could be very expensive. 



_Suggestion:_
```XML
let cpu_poly = eval.to_cpu().interpolate();
```
___
*[`crates/prover/src/core/backend/simd/circle.rs` line 241 at r1](https://reviewable.io/reviews/starkware-libs/stwo/827#-O6NP4V02XYLGpiaDbuZ:-O6NP4V02XYLGpiaDbu_:brhumzt) ([raw file](https://github.com/starkware-libs/stwo/blob/da9d4c76f4d48a32fbee01f9a69238d61253e5a1/crates/prover/src/core/backend/simd/circle.rs#L241)):*
> ```XML
>                 &CirclePoly::new(poly.coeffs.to_cpu()),
>                 domain,
>                 &twiddles.to_cpu(),
> ```

Same here.
___
*[`crates/prover/src/core/backend/simd/circle.rs` line 244 at r1](https://reviewable.io/reviews/starkware-libs/stwo/827#-O6NPZThBw0kuz8uA1tj:-O6NPZTiB3YFRGzf3mSm:br144au) ([raw file](https://github.com/starkware-libs/stwo/blob/da9d4c76f4d48a32fbee01f9a69238d61253e5a1/crates/prover/src/core/backend/simd/circle.rs#L244)):*
> ```XML
>             );
>             return CircleEvaluation::new(
>                 cpu_eval.domain,
> ```

Won't this be expensive if cpu_domain is large?

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/827)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`crates/prover/src/core/backend/simd/circle.rs` line 148 at r1](https://reviewable.io/reviews/starkware-libs/stwo/827#-O6NOKNEBC7rJvD9eogc:-O6pDXqo3mcQek3DFblo:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/da9d4c76f4d48a32fbee01f9a69238d61253e5a1/crates/prover/src/core/backend/simd/circle.rs#L148)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

twiddles.to_cpu() could be very expensive.
</blockquote></details>

Done.
___
*[`crates/prover/src/core/backend/simd/circle.rs` line 241 at r1](https://reviewable.io/reviews/starkware-libs/stwo/827#-O6NP4V02XYLGpiaDbuZ:-O6pDYGdBPd0FjWWO7Ha:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/da9d4c76f4d48a32fbee01f9a69238d61253e5a1/crates/prover/src/core/backend/simd/circle.rs#L241)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.
___
*[`crates/prover/src/core/backend/simd/circle.rs` line 244 at r1](https://reviewable.io/reviews/starkware-libs/stwo/827#-O6NPZThBw0kuz8uA1tj:-O6pMipf4q4AQ6cROxCb:bxdrwk5) ([raw file](https://github.com/starkware-libs/stwo/blob/da9d4c76f4d48a32fbee01f9a69238d61253e5a1/crates/prover/src/core/backend/simd/circle.rs#L244)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Won't this be expensive if cpu_domain is large?
</blockquote></details>

The worst it will be is `4 + log_blowup_factor`. So it shouldn't be that bad, right?

**Review by andrewmilson — APPROVED** [review]
:lgtm: with comment

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/827#-:-O6rUg-4EI51s4liksZY:b10c0l0)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

___
*[`crates/prover/src/core/backend/simd/circle.rs` line 229 at r2](https://reviewable.io/reviews/starkware-libs/stwo/827#-O6rV0Tc3uGSdNsYxEIm:-O6rV0Tc3uGSdNsYxEIn:b4655j2) ([raw file](https://github.com/starkware-libs/stwo/blob/9dcd61b23d832fac152320ac0aefcf1521721b62/crates/prover/src/core/backend/simd/circle.rs#L229)):*
> ```XML
>     ) -> CircleEvaluation<Self, BaseField, BitReversedOrder> {
>         // TODO(spapini): Precompute twiddles.
>         // TODO(spapini): Handle small cases.
> ```

I think these can be removed now.



_Code quote:_
```XML
        // TODO(spapini): Precompute twiddles.
        // TODO(spapini): Handle small cases.
```
___
*[`crates/prover/src/core/poly/twiddles.rs` line 36 at r2](https://reviewable.io/reviews/starkware-libs/stwo/827#-O6rU_rb8sGz7buzjBki:-O6rU_rb8sGz7buzjBkj:ba6xw9b) ([raw file](https://github.com/starkware-libs/stwo/blob/9dcd61b23d832fac152320ac0aefcf1521721b62/crates/prover/src/core/poly/twiddles.rs#L36)):*
> ```XML
>         }
>     }
> }
> ```

Can this be removed?



_Code quote:_
```XML
impl TwiddleTree<SimdBackend> {
    pub fn to_cpu(&self) -> TwiddleTree<CpuBackend> {
        TwiddleTree {
            root_coset: self.root_coset,
            twiddles: self
                .twiddles
                .iter()
                .map(|x| BaseField::from(x >> 1))
                .collect_vec(),
            itwiddles: self
                .itwiddles
                .iter()
                .map(|x| BaseField::from(x >> 1))
                .collect_vec(),
        }
    }
}
```

**Review by alonh5 — COMMENTED** [review]
Fixed comments. Regarding the tests, there are still places where the minimum bound needs to be removed. I'm fixing it and will add tests in the next PR.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/827#-:-O6teEbLDKw6N4SZz-2Z:bld52vm)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`crates/prover/src/core/backend/simd/circle.rs` line 229 at r2](https://reviewable.io/reviews/starkware-libs/stwo/827#-O6rV0Tc3uGSdNsYxEIm:-O6tduWn6vVnmZ_NNokz:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/9dcd61b23d832fac152320ac0aefcf1521721b62/crates/prover/src/core/backend/simd/circle.rs#L229)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

I think these can be removed now.
</blockquote></details>

Done.
___
*[`crates/prover/src/core/poly/twiddles.rs` line 36 at r2](https://reviewable.io/reviews/starkware-libs/stwo/827#-O6rU_rb8sGz7buzjBki:-O6te9VR91mZWqlrFIWH:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/9dcd61b23d832fac152320ac0aefcf1521721b62/crates/prover/src/core/poly/twiddles.rs#L36)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Can this be removed?
</blockquote></details>

Done.

**Review by andrewmilson — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/827#-:-O6uA2Iw444NayJToUDB:bnfp4nl)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Comment by alonh5** [comment]
### Merge activity

* **Sep 24, 4:47 AM EDT**: @alonh5 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/827).

**Pull request merged**
