### PR TITLE
Move all MLE eval related constraints into same module

### PR DESCRIPTION
**Pull request by andrewmilson**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/798)

### CODE REVIEW

**Comment by andrewmilson** [comment]
* **#799** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/799?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#798** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/798?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @andrewmilson and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/798)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @andrewmilson)

___
*[`crates/prover/src/examples/xor/gkr_lookups/mle_eval.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/stwo/798#-O4sonCWBfyemNzXGSd5:-O4sonCWBfyemNzXGSd6:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/e0f10637be44d1231edc19cf676fb7fe9b26909b/crates/prover/src/examples/xor/gkr_lookups/mle_eval.rs#L10)):*
> ```XML
> use crate::core::lookups::utils::eq;
> 
> /// Evaluates constraints that grantee a MLE evaluates to a claim at a given point.
> ```





_Suggestion:_
```XML
Evaluates constraints that guarantee an MLE evaluates to a claim at a given point.
```
___
*[`crates/prover/src/examples/xor/gkr_lookups/mle_eval.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/stwo/798#-O4socymENukxDfMOoYg:-O4socymENukxDfMOoYh:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/e0f10637be44d1231edc19cf676fb7fe9b26909b/crates/prover/src/examples/xor/gkr_lookups/mle_eval.rs#L14)):*
> ```XML
> /// `mle_coeffs_col_eval` should be the evaluation of the column containing the coefficients of the
> /// MLE in the multilinear Lagrange basis. `mle_claim_shift` should equal `claim / 2^N_VARIABLES`.
> pub fn eval_mle_eval_constrants<E: EvalAtRow, const N_VARIABLES: usize>(
> ```





_Suggestion:_
```XML
eval_mle_eval_constraints
```

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/798#-:-O4spzAL2Q5uKUq-c-x9:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @andrewmilson)

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/798)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/prover/src/examples/xor/gkr_lookups/mle_eval.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/stwo/798#-O4sonCWBfyemNzXGSd5:-O4uWhxc9DvR7UjIB_LF:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/e0f10637be44d1231edc19cf676fb7fe9b26909b/crates/prover/src/examples/xor/gkr_lookups/mle_eval.rs#L10)):*
> ```XML
> use crate::core::lookups::utils::eq;
> 
> /// Evaluates constraints that grantee a MLE evaluates to a claim at a given point.
> ```

Done.

**Pull request merged**
