### PR TITLE
Eval framework preperation

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/705)

### CODE REVIEW

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/705)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/core/utils.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/stwo/705#-O1Gu23cAn9q_Il4-8kE:-O1Gu23cAn9q_Il4-8kF:b-qmrl8s) ([raw file](https://github.com/starkware-libs/stwo/blob/625094894f5c47ef3df5557d7e840e32553a65d9/crates/prover/src/core/utils.rs#L73)):*
> ```XML
> }
> 
> pub(crate) fn offset_bit_reversed_circle_domain_index(
> ```

Add a unit test?
___
*[`crates/prover/src/core/utils.rs` line 150 at r1](https://reviewable.io/reviews/starkware-libs/stwo/705#-O1Gx3tS5oxzcgu7aU-I:-O1Gx3tS5oxzcgu7aU-J:br3pxdu) ([raw file](https://github.com/starkware-libs/stwo/blob/625094894f5c47ef3df5557d7e840e32553a65d9/crates/prover/src/core/utils.rs#L150)):*
> ```XML
> where
>     EF: Copy + Zero + Mul<EF, Output = EF> + Add<F, Output = EF> + Sub<EF, Output = EF>,
> {
> ```

Why not like this?



_Suggestion:_
```XML
pub fn shifted_secure_combination<F: ExtensionOf<BaseField>, EF: ExtensionOf<F>>(
    values: &[F],
    alpha: EF,
    z: EF,
) -> EF {
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/705)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @alonh5)

___
*[`crates/prover/src/core/utils.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/stwo/705#-O1Gu23cAn9q_Il4-8kE:-O1H51sS1B3zZwphtE-Y:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/625094894f5c47ef3df5557d7e840e32553a65d9/crates/prover/src/core/utils.rs#L73)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Add a unit test?
</blockquote></details>

Done.
___
*[`crates/prover/src/core/utils.rs` line 150 at r1](https://reviewable.io/reviews/starkware-libs/stwo/705#-O1Gx3tS5oxzcgu7aU-I:-O1H50AY0ucpB1hqfsQF:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/625094894f5c47ef3df5557d7e840e32553a65d9/crates/prover/src/core/utils.rs#L150)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Why not like this?
</blockquote></details>

Done.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/705)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/prover/src/core/utils.rs` line 212 at r2](https://reviewable.io/reviews/starkware-libs/stwo/705#-O1Hd_8K-DEBkC73SaYt:-O1Hd_8K-DEBkC73SaYu:b-2vzusc) ([raw file](https://github.com/starkware-libs/stwo/blob/640ba293f43e5b4f1d4012cbcdb46aaea67e231a/crates/prover/src/core/utils.rs#L212)):*
> ```XML
>     #[test]
>     fn test_offset_bit_reversed_circle_domain_index() {
>         let actual = offset_bit_reversed_circle_domain_index(5, 3, 6, -2);
> ```

Please extract these into variables

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/705)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/prover/src/core/utils.rs` line 212 at r2](https://reviewable.io/reviews/starkware-libs/stwo/705#-O1Hd_8K-DEBkC73SaYt:-O1Kq7x6AlfgC2Q3j0Ia:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/640ba293f43e5b4f1d4012cbcdb46aaea67e231a/crates/prover/src/core/utils.rs#L212)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Please extract these into variables
</blockquote></details>

Done.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/705#-:-O1LM5nY9b-7HieOJBjs:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Comment by spapinistarkware** [comment]
### Merge activity

* **Jul 10, 2:10 AM EDT**: @spapinistarkware merged this pull request with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/705).

**Pull request merged**
