### PR TITLE
optimized batch inverse

### PR DESCRIPTION
**Pull request by ohad-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/437)

### CODE REVIEW

**Comment by ohad-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/437?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#437** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/437?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#430** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/430?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#429** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/429?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#427** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/427?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ohad-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/437)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @andrewmilson and @ohad-starkware)

___
*[`src/core/fields/mod.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/stwo/437#-NsJDPwD4YWDZvlI5YNA:-NsJDPwE36ELKVWy2m2s:b-b91gdw) ([raw file](https://github.com/starkware-libs/stwo/blob/7710774cc10df6b48de782e889512544856d0735/src/core/fields/mod.rs#L41)):*
> ```XML
> 
>     /// Inverts a batch of up to 4 elements using Montgomery's trick.
>     // Optimized over the classic batch inversion by reducing the dependency of consecutive
> ```

Those line are still part of the doc, right?



_Suggestion:_
```XML
///
```
___
*[`src/core/fields/mod.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/stwo/437#-NsJDV4I679U6AdAvXdg:-NsJDV4I679U6AdAvXdh:bt5ulzn) ([raw file](https://github.com/starkware-libs/stwo/blob/7710774cc10df6b48de782e889512544856d0735/src/core/fields/mod.rs#L43)):*
> ```XML
>     // Optimized over the classic batch inversion by reducing the dependency of consecutive
>     // instructions.
>     fn slice_batch_inverse(column: &[Self], dst: &mut [Self]) {
> ```

Why do we call it slice?
Do you think it will be nicer if we will just explain it in the comment?

I think that the api function should be called batch_inverse as the caller doesn't care how you implement that



_Code quote:_
```XML
slice_
```
___
*[`src/core/fields/mod.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/stwo/437#-NsJDrLaBIHUBFWZW3Hw:-NsJDrLaBIHUBFWZW3Hx:bcdudsv) ([raw file](https://github.com/starkware-libs/stwo/blob/7710774cc10df6b48de782e889512544856d0735/src/core/fields/mod.rs#L52)):*
> ```XML
>         }
> 
>         // First pass.
> ```

IMO this comment should explain why we split it to multiple prods.



_Code quote:_
```XML
// First pass.
```
___
*[`src/core/fields/mod.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/stwo/437#-NsJFGtX2y_d2xbw7rrM:-NsJFGtX2y_d2xbw7rrN:bl3xz8z) ([raw file](https://github.com/starkware-libs/stwo/blob/7710774cc10df6b48de782e889512544856d0735/src/core/fields/mod.rs#L53)):*
> ```XML
> 
>         // First pass.
>         let mut cum_prod: [Self; WIDTH] = column[..WIDTH].try_into().unwrap();
> ```

Can you initialise those to Ones instead?
In my mind it will be more readable



_Code quote:_
```XML
let mut cum_prod: [Self; WIDTH] = column[..WIDTH].try_into().unwrap();
```
___
*[`src/core/fields/mod.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/stwo/437#-NsJFbK7ABy7OxMUuk3T:-NsJFbK82xrwWUuleux9:b-bs2ayk) ([raw file](https://github.com/starkware-libs/stwo/blob/7710774cc10df6b48de782e889512544856d0735/src/core/fields/mod.rs#L59)):*
> ```XML
>             dst[i] = cum_prod[i % WIDTH];
>         }
>         debug_assert_eq!(dst.len(), n);
> ```

Why we have this assert? can't `dst` be incorporated in a larger vector (theoretically)?



_Code quote:_
```XML
debug_assert_eq!(dst.len(), n)
```
___
*[`src/core/fields/mod.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/stwo/437#-NsJG0ymDWqtMYoIulUV:-NsJG0ymDWqtMYoIulUW:b8zipjs) ([raw file](https://github.com/starkware-libs/stwo/blob/7710774cc10df6b48de782e889512544856d0735/src/core/fields/mod.rs#L63)):*
> ```XML
>         // Inverse cumulative products.
>         // Use classic batch inversion.
>         let mut tail_inverses = [Self::one(); WIDTH];
> ```

Vec::with_capacity(WIDTH)?



_Code quote:_
```XML
let mut tail_inverses = [Self::one(); WIDTH];
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/437)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`src/core/fields/mod.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/stwo/437#-NsJDPwD4YWDZvlI5YNA:-NsJHpxB5au2tuDU43tO:bbiqtyj) ([raw file](https://github.com/starkware-libs/stwo/blob/7710774cc10df6b48de782e889512544856d0735/src/core/fields/mod.rs#L41)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Those line are still part of the doc, right?
</blockquote></details>

IMO that is an implementation detail.
___
*[`src/core/fields/mod.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/stwo/437#-NsJDV4I679U6AdAvXdg:-NsJH3UUBOlMfjz-1gBx:b-68358a) ([raw file](https://github.com/starkware-libs/stwo/blob/7710774cc10df6b48de782e889512544856d0735/src/core/fields/mod.rs#L43)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why do we call it slice?
Do you think it will be nicer if we will just explain it in the comment?

I think that the api function should be called batch_inverse as the caller doesn't care how you implement that
</blockquote></details>

this function is here to be called by backends, the backend knows how to tramute it's column type into a slice and give it to slice_batch_inverse.
e.g. avx512 transmutes BaseFieldVec into &[PackedBaseField] and PackedBaseField implements slice_batch_inverse()
___
*[`src/core/fields/mod.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/stwo/437#-NsJDrLaBIHUBFWZW3Hw:-NsJIeR05QPid0oTyDKc:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/7710774cc10df6b48de782e889512544856d0735/src/core/fields/mod.rs#L52)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

IMO this comment should explain why we split it to multiple prods.
</blockquote></details>

Done.
___
*[`src/core/fields/mod.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/stwo/437#-NsJFGtX2y_d2xbw7rrM:-NsJInMI4uSD3odlqcFj:bb7oryy) ([raw file](https://github.com/starkware-libs/stwo/blob/7710774cc10df6b48de782e889512544856d0735/src/core/fields/mod.rs#L53)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can you initialise those to Ones instead?
In my mind it will be more readable
</blockquote></details>

sure
___
*[`src/core/fields/mod.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/stwo/437#-NsJFbK7ABy7OxMUuk3T:-NsJJRnK9M3fJZUJfgZf:b41xqef) ([raw file](https://github.com/starkware-libs/stwo/blob/7710774cc10df6b48de782e889512544856d0735/src/core/fields/mod.rs#L59)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why we have this assert? can't `dst` be incorporated in a larger vector (theoretically)?
</blockquote></details>

Yes, it was just a sanity check I forgot to remove. 
changed, do we want to test this logic?
___
*[`src/core/fields/mod.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/stwo/437#-NsJG0ymDWqtMYoIulUV:-NsJKAglDDI-gJk755a_:b-5jam0w) ([raw file](https://github.com/starkware-libs/stwo/blob/7710774cc10df6b48de782e889512544856d0735/src/core/fields/mod.rs#L63)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Vec::with_capacity(WIDTH)?
</blockquote></details>

1. I don't want a vec
2. Vec::with_capacity() allocates but doesn't initialise so vector[i] panics.

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/437)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`src/core/fields/mod.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/stwo/437#-NsJDPwD4YWDZvlI5YNA:-NsMwVrN-YQzSuKfD14n:b2nign6) ([raw file](https://github.com/starkware-libs/stwo/blob/7710774cc10df6b48de782e889512544856d0735/src/core/fields/mod.rs#L41)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

maybe now it can be removed at all as it written in the other place?
</blockquote></details>

yes
___
*[`src/core/fields/mod.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/stwo/437#-NsJDV4I679U6AdAvXdg:-NsMvu0I7Bk4LfzgrPKv:b-scibvb) ([raw file](https://github.com/starkware-libs/stwo/blob/7710774cc10df6b48de782e889512544856d0735/src/core/fields/mod.rs#L43)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

yeah, but that's the backend problem.
From this function perspective it inverses all the elements that it gets.
</blockquote></details>

I'm okay with removing the slice, but then we get two functions with the same name
___
*[`src/core/fields/mod.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/stwo/437#-NsJFbK7ABy7OxMUuk3T:-NsJMahO9GB39evAJ_tE:b-l2razk) ([raw file](https://github.com/starkware-libs/stwo/blob/7710774cc10df6b48de782e889512544856d0735/src/core/fields/mod.rs#L59)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

not sure. Do you think that we'll use it that way?
</blockquote></details>

I doubt it, and even if so, it's a slice, just splice it.
___
*[`src/core/fields/mod.rs` line 40 at r2](https://reviewable.io/reviews/starkware-libs/stwo/437#-NsJLtWR0c8LvpUP0NB5:-NsMwLXA1ilRX-iCH2-R:bpdibi8) ([raw file](https://github.com/starkware-libs/stwo/blob/0cf87e63d20c614534aabd4e7c47e8f4dac8f600/src/core/fields/mod.rs#L40)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

This belongs to the other function right?
And also why it is a limitation there?

Remove
</blockquote></details>

it was incorrect, removed.
___
*[`src/core/fields/mod.rs` line 77 at r3](https://reviewable.io/reviews/starkware-libs/stwo/437#-NsJMQAI1Z9LyD4hOTgC:-NsMxgQUAGcL6ZMSUUVl:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/94c5b604a9423357714bbc7c153b13e0994cf8ca/src/core/fields/mod.rs#L77)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

maybe we should add that this function assumes that dst is initiliazed and has the same length of column?
Maybe we can add a panic test for that
</blockquote></details>

Done.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/437#-:-NsNXz0M1TkjaUmh80lM:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @andrewmilson)

**Pull request merged**
