### PR TITLE
Implement LogupOps for SIMD backend

### PR DESCRIPTION
**Pull request by andrewmilson**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/641)

### CODE REVIEW

**Comment by andrewmilson** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/641?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#641** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/641?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#640** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/640?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#630** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/630?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#629** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/629?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#623** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/623?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#620** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/620?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#621** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/621?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#581** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/581?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#617** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/617?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#616** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/616?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#615** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/615?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#614** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/614?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#613** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/613?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#612** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/612?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#611** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/611?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#610** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/610?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @andrewmilson and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/641)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @andrewmilson)

___
*[`crates/prover/src/core/backend/simd/lookups/gkr.rs` line 211 at r1](https://reviewable.io/reviews/starkware-libs/stwo/641#-O08uWf96MgaQexT_3RZ:-O08uWf96MgaQexT_3R_:b-bsbf5l) ([raw file](https://github.com/starkware-libs/stwo/blob/11372711eebe9ea7ab3fe71514862af08df53216/crates/prover/src/core/backend/simd/lookups/gkr.rs#L211)):*
> ```XML
> }
> 
> // TODO: Code duplication of `next_logup_generic_layer`. Consider unifying these.
> ```

Don't you want to do that in this pr?



_Code quote:_
```XML
// TODO: Code duplication of `next_logup_generic_layer`. Consider unifying these.
```
___
*[`crates/prover/src/core/lookups/utils.rs` line 199 at r1](https://reviewable.io/reviews/starkware-libs/stwo/641#-O08qxUz28HlhQ4n1Nu5:-O08qxUz28HlhQ4n1Nu6:b-tmpigu) ([raw file](https://github.com/starkware-libs/stwo/blob/11372711eebe9ea7ab3fe71514862af08df53216/crates/prover/src/core/lookups/utils.rs#L199)):*
> ```XML
> /// Projective fraction.
> #[derive(Debug, Clone, Copy)]
> pub struct Fraction<N, D> {
> ```

Why do you need it to be that generic?
Isn't it only for Field/ExtensionField elements?



_Code quote:_
```XML
Fraction<N, D> 
```
___
*[`crates/prover/src/core/lookups/utils.rs` line 272 at r1](https://reviewable.io/reviews/starkware-libs/stwo/641#-O08qCQ7Bl1Bp247SkXu:-O08qCQ7Bl1Bp247SkXv:bhzkhcg) ([raw file](https://github.com/starkware-libs/stwo/blob/11372711eebe9ea7ab3fe71514862af08df53216/crates/prover/src/core/lookups/utils.rs#L272)):*
> ```XML
>             denominator: self.x * rhs.x,
>         }
>     }
> ```

Can you add a test for this?



_Code quote:_
```XML
    fn add(self, rhs: Self) -> Fraction<T, T> {
        // `1/a + 1/b = (a + b)/(a * b)`
        Fraction {
            numerator: self.x + rhs.x,
            denominator: self.x * rhs.x,
        }
    }
```

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/641)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/prover/src/core/backend/simd/lookups/gkr.rs` line 211 at r1](https://reviewable.io/reviews/starkware-libs/stwo/641#-O08uWf96MgaQexT_3RZ:-O0ESc98EL9HPzMMdw84:b-a8dhxd) ([raw file](https://github.com/starkware-libs/stwo/blob/11372711eebe9ea7ab3fe71514862af08df53216/crates/prover/src/core/backend/simd/lookups/gkr.rs#L211)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Don't you want to do that in this pr?
</blockquote></details>

I'd want to just don't think we have the traits in order to express this function as generic
___
*[`crates/prover/src/core/lookups/utils.rs` line 199 at r1](https://reviewable.io/reviews/starkware-libs/stwo/641#-O08qxUz28HlhQ4n1Nu5:-O0ET-jO9IFI7K8P6US9:bxml8au) ([raw file](https://github.com/starkware-libs/stwo/blob/11372711eebe9ea7ab3fe71514862af08df53216/crates/prover/src/core/lookups/utils.rs#L199)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why do you need it to be that generic?
Isn't it only for Field/ExtensionField elements?
</blockquote></details>

We don't implement Field or ExtensionOf traits on packed field elements. 
If we had abstract Field/Extension traits it would work

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/641)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/prover/src/core/lookups/utils.rs` line 272 at r1](https://reviewable.io/reviews/starkware-libs/stwo/641#-O08qCQ7Bl1Bp247SkXu:-O46W-EAADwN0VLglplb:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/11372711eebe9ea7ab3fe71514862af08df53216/crates/prover/src/core/lookups/utils.rs#L272)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can you add a test for this?
</blockquote></details>

Done.

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 1 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/641)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

___
*[`crates/prover/src/core/backend/simd/lookups/gkr.rs` line 211 at r1](https://reviewable.io/reviews/starkware-libs/stwo/641#-O08uWf96MgaQexT_3RZ:-O4pA-H00SNoks8dE7WI:bq7nbgl) ([raw file](https://github.com/starkware-libs/stwo/blob/11372711eebe9ea7ab3fe71514862af08df53216/crates/prover/src/core/backend/simd/lookups/gkr.rs#L211)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

I'd want to just don't think we have the traits in order to express this function as generic
</blockquote></details>

Can you just be generic on F, with a where clause for everything this funciotn needs? Even if it is a bit long?

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 1 of 3 files at r3, 2 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/641)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/641)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

___
*[`crates/prover/src/core/backend/simd/lookups/gkr.rs` line 211 at r1](https://reviewable.io/reviews/starkware-libs/stwo/641#-O08uWf96MgaQexT_3RZ:-O4pFOUG-tPpkqB28IfT:bwd7wts) ([raw file](https://github.com/starkware-libs/stwo/blob/11372711eebe9ea7ab3fe71514862af08df53216/crates/prover/src/core/backend/simd/lookups/gkr.rs#L211)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Can you just be generic on F, with a where clause for everything this funciotn needs? Even if it is a bit long?
</blockquote></details>

Not really. A new trait needs to be introduced to handle the deinterleave.

**Pull request merged**
