### PR TITLE
Extension FRI optimization

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/685)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/685?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#685** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/685?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#684** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/684?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/685)* status: all files reviewed, 5 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/quotients.rs` line 23 at r2](https://reviewable.io/reviews/starkware-libs/stwo/685#-O0ivcJR4K1ViZzFndHQ:-O0ivcJR4K1ViZzFndHR:bs5i0qk) ([raw file](https://github.com/starkware-libs/stwo/blob/0287e628f40b33b11954901e1ac378bf09783b1b/crates/prover/src/core/backend/simd/quotients.rs#L23)):*
> ```XML
> use crate::core::utils::{bit_reverse, bit_reverse_index};
> 
> impl QuotientOps for SimdBackend {
> ```

Update documentation in the trait



_Code quote:_
```XML
impl QuotientOps for SimdBackend {
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/685)* status: all files reviewed, 5 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/prover/src/core/backend/simd/quotients.rs` line 23 at r2](https://reviewable.io/reviews/starkware-libs/stwo/685#-O0ivcJR4K1ViZzFndHQ:-O0lVZ5K98bVeaIsJ72v:bxqxwqo) ([raw file](https://github.com/starkware-libs/stwo/blob/0287e628f40b33b11954901e1ac378bf09783b1b/crates/prover/src/core/backend/simd/quotients.rs#L23)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Update documentation in the trait
</blockquote></details>

Seems we forgot to update it with Ohad's changes, so it's already updated!
___
*[`crates/prover/src/core/backend/simd/quotients.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/stwo/685#-O0iq6o944Mu42-9-SDG:-O0lVkY4Dop3IkG5Igeh:b-t4zyfj) ([raw file](https://github.com/starkware-libs/stwo/blob/0287e628f40b33b11954901e1ac378bf09783b1b/crates/prover/src/core/backend/simd/quotients.rs#L24)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

This function should have a test, where you accumulate on the entire domain directly
Does the comparison to the CPU impl gived that?
</blockquote></details>

Yes. The optimization doesn't exist in the CPU impl (which is probably a good thing, as it is more of a reference implementation)
___
*[`crates/prover/src/core/backend/simd/quotients.rs` line 32 at r2](https://reviewable.io/reviews/starkware-libs/stwo/685#-O0iMiyHAQM6HkCJiCM0:-O0lVzyi579lvnZ6AXqL:buff1tq) ([raw file](https://github.com/starkware-libs/stwo/blob/0287e628f40b33b11954901e1ac378bf09783b1b/crates/prover/src/core/backend/simd/quotients.rs#L32)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

WDYT?
</blockquote></details>

It's no initials, since subdomain has a nonzero initial. How is it now?
___
*[`crates/prover/src/core/backend/simd/quotients.rs` line 71 at r2](https://reviewable.io/reviews/starkware-libs/stwo/685#-O0iNOjABtqb7qAyfKyK:-O0lZe9I9YSu8OjfXhZ9:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/0287e628f40b33b11954901e1ac378bf09783b1b/crates/prover/src/core/backend/simd/quotients.rs#L71)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Document
</blockquote></details>

Done.
___
*[`crates/prover/src/core/poly/circle/domain.rs` line 84 at r2](https://reviewable.io/reviews/starkware-libs/stwo/685#-O0iMzS59i7JGrkxvBEW:-O0lZct55-6yyCaBqyup:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/0287e628f40b33b11954901e1ac378bf09783b1b/crates/prover/src/core/poly/circle/domain.rs#L84)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

This should have a unit test.
</blockquote></details>

Done.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/685)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/quotients.rs` line 25 at r3](https://reviewable.io/reviews/starkware-libs/stwo/685#-O0nNCx1-EIVQ8rtmtKE:-O0nNCx1-EIVQ8rtmtKF:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/21492c97a44603aee9b5bb0dfde7efb28d856fda/crates/prover/src/core/backend/simd/quotients.rs#L25)):*
> ```XML
> impl QuotientOps for SimdBackend {
>     fn accumulate_quotients(
>         outer_domain: CircleDomain,
> ```





_Suggestion:_
```XML
domain: CircleDomain
```
___
*[`crates/prover/src/core/backend/simd/quotients.rs` line 32 at r3](https://reviewable.io/reviews/starkware-libs/stwo/685#-O0nKzxF4ZDQWkQLOuss:-O0nKzxG4vLXRk1BdbSb:b-ryurz) ([raw file](https://github.com/starkware-libs/stwo/blob/21492c97a44603aee9b5bb0dfde7efb28d856fda/crates/prover/src/core/backend/simd/quotients.rs#L32)):*
> ```XML
>         // Split the domain into a subdomain and a shift coset.
>         // TODO(spapini): Move to the caller when Columns support slices.
>         let (subdomain, mut domain_shifts) = outer_domain.split(LOG_BLOWUP_FACTOR);
> ```

(non-blocking)



_Suggestion:_
```XML
let (subdomain, mut subdomain_shifts
```

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/685)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/quotients.rs` line 25 at r3](https://reviewable.io/reviews/starkware-libs/stwo/685#-O0nNCx1-EIVQ8rtmtKE:-O0nNIDl3wXBLAXRAcMA:b-s07uv1) ([raw file](https://github.com/starkware-libs/stwo/blob/21492c97a44603aee9b5bb0dfde7efb28d856fda/crates/prover/src/core/backend/simd/quotients.rs#L25)):*
> ```XML
> impl QuotientOps for SimdBackend {
>     fn accumulate_quotients(
>         outer_domain: CircleDomain,
> ```

Does it work for general CircleDomain or only for CanonicCoset?

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/685#-:-O0nPaXIBwYIjjLD-Moi:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/quotients.rs` line 76 at r3](https://reviewable.io/reviews/starkware-libs/stwo/685#-O0nOyXADdACqa8k-Lwa:-O0nOyXBC4-1Fz5-00vb:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/21492c97a44603aee9b5bb0dfde7efb28d856fda/crates/prover/src/core/backend/simd/quotients.rs#L76)):*
> ```XML
>         //   b0 b1 b2 b3 b4 b5
>         // b0 adds P, b1 adds 2P, etc.. (b5 is special and flips the sign of the point).
>         // Splitting the coset to 4 parts yields:
> ```





_Suggestion:_
```XML
// Splitting the domain to 4 parts yields:
```

**Pull request merged**
