### PR TITLE
Use simple merkle tree

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/526)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/526?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#526** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/526?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#525** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/525?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#518** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/518?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by andrewmilson — APPROVED** [review]
:lgtm:

> Reviewed 2 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/526#-:-NtovShBEn29BQ-nSROf:bnfp4nl)* status: 2 of 7 files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`src/commitment_scheme/blake2_merkle.rs` line 34 at r2](https://reviewable.io/reviews/starkware-libs/stwo/526#-NtoRR9ID2Afo84Drdk1:-NtoRR9J8B7iOEFxraC3:bjyw7nu) ([raw file](https://github.com/starkware-libs/stwo/blob/05397c7ca794a3ba04ef089e37c17027ebed5574/src/commitment_scheme/blake2_merkle.rs#L34)):*
> ```XML
>             state = compress(state, unsafe { std::mem::transmute(chunk) }, 0, 0, 0, 0);
>         }
>         unsafe { std::mem::transmute(state) }
> ```

Can we avoid the unsafe by implementing `From<[u8; 32]>` on Blake2sHash?
___
*[`src/commitment_scheme/blake2_merkle.rs` line 130 at r2](https://reviewable.io/reviews/starkware-libs/stwo/526#-NtoRu-Y75mrVICqQ5WH:-NtoRu-ZCOp5j5XgJGgw:bm2ygeo) ([raw file](https://github.com/starkware-libs/stwo/blob/05397c7ca794a3ba04ef089e37c17027ebed5574/src/commitment_scheme/blake2_merkle.rs#L130)):*
> ```XML
>     fn test_merkle_invalid_witness() {
>         let (queries, mut decommitment, values, verifier) = prepare_merkle();
>         decommitment.witness[20] = Blake2sHash::from(&[0u8; 32][..]);
> ```

Might be worth implementing `From<[u8; 32]>` on Blake2sHash
___
*[`src/core/commitment_scheme/prover.rs` line 155 at r2](https://reviewable.io/reviews/starkware-libs/stwo/526#-NtoSSr59hrv0sp8MVlU:-NtoSSr64bc7P1RrdL67:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/05397c7ca794a3ba04ef089e37c17027ebed5574/src/core/commitment_scheme/prover.rs#L155)):*
> ```XML
>         let evaluations = polynomials
>             .iter()
>             .sorted_by_key(|eval| Reverse(eval.log_size()))
> ```





_Suggestion:_
```XML
.sorted_by_key(|poly| Reverse(poly.log_size()))
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/526)* status: 2 of 7 files reviewed, 3 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`src/commitment_scheme/blake2_merkle.rs` line 34 at r2](https://reviewable.io/reviews/starkware-libs/stwo/526#-NtoRR9ID2Afo84Drdk1:-Ntp0b-L4qm7Z-Tk-NfS:b25suck) ([raw file](https://github.com/starkware-libs/stwo/blob/05397c7ca794a3ba04ef089e37c17027ebed5574/src/commitment_scheme/blake2_merkle.rs#L34)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Can we avoid the unsafe by implementing `From<[u8; 32]>` on Blake2sHash?
</blockquote></details>

This is actually [u32; 8]. The implementation would also be unsafe, right? So we won't really avoid it.
___
*[`src/commitment_scheme/blake2_merkle.rs` line 130 at r2](https://reviewable.io/reviews/starkware-libs/stwo/526#-NtoRu-Y75mrVICqQ5WH:-Ntp0TdLCmJWblIj2dQm:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/05397c7ca794a3ba04ef089e37c17027ebed5574/src/commitment_scheme/blake2_merkle.rs#L130)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Might be worth implementing `From<[u8; 32]>` on Blake2sHash
</blockquote></details>

Done.
___
*[`src/core/commitment_scheme/prover.rs` line 155 at r2](https://reviewable.io/reviews/starkware-libs/stwo/526#-NtoSSr59hrv0sp8MVlU:-Ntp0UUSE9Or1VXnkjph:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/05397c7ca794a3ba04ef089e37c17027ebed5574/src/core/commitment_scheme/prover.rs#L155)):*
> ```XML
>         let evaluations = polynomials
>             .iter()
>             .sorted_by_key(|eval| Reverse(eval.log_size()))
> ```

Done.

**Review by andrewmilson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/526)* status: 2 of 8 files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`src/commitment_scheme/blake2_merkle.rs` line 34 at r2](https://reviewable.io/reviews/starkware-libs/stwo/526#-NtoRR9ID2Afo84Drdk1:-Ntp3_ArAwkO3bNeHLBe:b-ydagaa) ([raw file](https://github.com/starkware-libs/stwo/blob/05397c7ca794a3ba04ef089e37c17027ebed5574/src/commitment_scheme/blake2_merkle.rs#L34)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

This is actually [u32; 8]. The implementation would also be unsafe, right? So we won't really avoid it.
</blockquote></details>

Oh right I see. Isn't there the possibility of an endianness bug here?

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/526)* status: 2 of 8 files reviewed, 3 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`src/commitment_scheme/blake2_merkle.rs` line 34 at r2](https://reviewable.io/reviews/starkware-libs/stwo/526#-NtoRR9ID2Afo84Drdk1:-NtpPxtkBQZwyLZjydwt:b-5gwpz4) ([raw file](https://github.com/starkware-libs/stwo/blob/05397c7ca794a3ba04ef089e37c17027ebed5574/src/commitment_scheme/blake2_merkle.rs#L34)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Oh right I see. Isn't there the possibility of an endianness bug here?
</blockquote></details>

What is the alternative?

**Review by andrewmilson — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/526#-:-NttAYIe8qQL-cpQKpbe:bnfp4nl)* status: 2 of 8 files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`src/commitment_scheme/blake2_merkle.rs` line 34 at r2](https://reviewable.io/reviews/starkware-libs/stwo/526#-NtoRR9ID2Afo84Drdk1:-Ntt98TZ1drAjygCXItd:b-r6jc4l) ([raw file](https://github.com/starkware-libs/stwo/blob/05397c7ca794a3ba04ef089e37c17027ebed5574/src/commitment_scheme/blake2_merkle.rs#L34)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

What is the alternative?
</blockquote></details>

```
#[cfg(target_endian = "little")]
unsafe { std::mem::transmute(state) }
#[cfg(target_endian = "big")]
unimplemented!()
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/526)* status: 2 of 8 files reviewed, 2 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`src/commitment_scheme/blake2_merkle.rs` line 34 at r2](https://reviewable.io/reviews/starkware-libs/stwo/526#-NtoRR9ID2Afo84Drdk1:-NttUk2IAtKUB6i2SCYk:bn19ihs) ([raw file](https://github.com/starkware-libs/stwo/blob/05397c7ca794a3ba04ef089e37c17027ebed5574/src/commitment_scheme/blake2_merkle.rs#L34)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

```
#[cfg(target_endian = "little")]
unsafe { std::mem::transmute(state) }
#[cfg(target_endian = "big")]
unimplemented!()
```
</blockquote></details>

Found a nice way.

**Review by andrewmilson — CHANGES_REQUESTED** [review]
> Reviewed 7 of 10 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/526)* status: 8 of 11 files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`src/core/commitment_scheme/prover.rs` line 177 at r7](https://reviewable.io/reviews/starkware-libs/stwo/526#-NuINnSu4Cr5pRLIONPP:-NuINnSu4Cr5pRLIONPQ:b-1fjstp) ([raw file](https://github.com/starkware-libs/stwo/blob/58af368a72a64801bd4b82f0705f4b963d759ec0/src/core/commitment_scheme/prover.rs#L177)):*
> ```XML
>     fn decommit(
>         &self,
>         queries: BTreeMap<u32, Vec<usize>>,
> ```

What is this a mapping of? Can it be documented please?
___
*[`src/core/prover/mod.rs` line 212 at r7](https://reviewable.io/reviews/starkware-libs/stwo/526#-NuIOMOv3ysXunK_N8sH:-NuIOMOv3ysXunK_N8sI:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/58af368a72a64801bd4b82f0705f4b963d759ec0/src/core/prover/mod.rs#L212)):*
> ```XML
>     InvalidStructure(String),
>     #[error(transparent)]
>     MerkleError(#[from] MerkleVerificationError),
> ```





_Suggestion:_
```XML
Merkle
```
___
*[`src/examples/fibonacci/mod.rs` line 214 at r7](https://reviewable.io/reviews/starkware-libs/stwo/526#-NuIOY_Q7-IuY9rHMI_z:-NuIOY_Q7-IuY9rHMIa-:bopzr35) ([raw file](https://github.com/starkware-libs/stwo/blob/58af368a72a64801bd4b82f0705f4b963d759ec0/src/examples/fibonacci/mod.rs#L214)):*
> ```XML
> 
>         let error = fib.verify(invalid_proof).unwrap_err();
>         assert!(matches!(error, VerificationError::MerkleError(_)));
> ```

Just realised there is an assert_matches macro which gives a more informative failure printout. 



_Suggestion:_
```XML
#![feature(assert_matches)]

...

use std::assert_matches::assert_matches;

...

assert_matches!(error, VerificationError::MerkleError(_));
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/526)* status: 8 of 11 files reviewed, 3 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`src/core/commitment_scheme/prover.rs` line 177 at r7](https://reviewable.io/reviews/starkware-libs/stwo/526#-NuINnSu4Cr5pRLIONPP:-NuSTQQI7w6sieMTVh7c:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/58af368a72a64801bd4b82f0705f4b963d759ec0/src/core/commitment_scheme/prover.rs#L177)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

What is this a mapping of? Can it be documented please?
</blockquote></details>

Done.
___
*[`src/core/prover/mod.rs` line 212 at r7](https://reviewable.io/reviews/starkware-libs/stwo/526#-NuIOMOv3ysXunK_N8sH:-NuSSitoDLwW5qI8IgSD:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/58af368a72a64801bd4b82f0705f4b963d759ec0/src/core/prover/mod.rs#L212)):*
> ```XML
>     InvalidStructure(String),
>     #[error(transparent)]
>     MerkleError(#[from] MerkleVerificationError),
> ```

Done.
___
*[`src/examples/fibonacci/mod.rs` line 214 at r7](https://reviewable.io/reviews/starkware-libs/stwo/526#-NuIOY_Q7-IuY9rHMI_z:-NuST2v33BQWhJMA5ftC:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/58af368a72a64801bd4b82f0705f4b963d759ec0/src/examples/fibonacci/mod.rs#L214)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Just realised there is an assert_matches macro which gives a more informative failure printout.
</blockquote></details>

Done.

**Review by andrewmilson — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/526)* status: 8 of 11 files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`src/core/commitment_scheme/verifier.rs` line 94 at r8](https://reviewable.io/reviews/starkware-libs/stwo/526#-NuW_o54EF9WvHDxXqsa:-NuW_o557pmS8uOwX6TQ:bb91i71) ([raw file](https://github.com/starkware-libs/stwo/blob/80d5e43dcd3d13d6a938c4644f3fe94bfb9c04d2/src/core/commitment_scheme/verifier.rs#L94)):*
> ```XML
>         self.trees
>             .as_ref()
>             .zip(proof.decommitments)
> ```

Why do we have iterator like methods implemented on TreeVec? Can't we achieve the same thing with regular iterators
___
*[`src/core/commitment_scheme/verifier.rs` line 123 at r8](https://reviewable.io/reviews/starkware-libs/stwo/526#-NuWYXGsCTPQtUqM8mA8:-NuWYXGsCTPQtUqM8mA9:ba3dfna) ([raw file](https://github.com/starkware-libs/stwo/blob/80d5e43dcd3d13d6a938c4644f3fe94bfb9c04d2/src/core/commitment_scheme/verifier.rs#L123)):*
> ```XML
>                 .flatten()
>                 .into_iter()
>                 // .map(|x| x)
> ```

Remove?

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/526)* status: 8 of 11 files reviewed, 2 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`src/core/commitment_scheme/verifier.rs` line 94 at r8](https://reviewable.io/reviews/starkware-libs/stwo/526#-NuW_o54EF9WvHDxXqsa:-NuXbRUj3ZeKJv7gofWH:b-4bw9ff) ([raw file](https://github.com/starkware-libs/stwo/blob/80d5e43dcd3d13d6a938c4644f3fe94bfb9c04d2/src/core/commitment_scheme/verifier.rs#L94)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Why do we have iterator like methods implemented on TreeVec? Can't we achieve the same thing with regular iterators
</blockquote></details>

I want to keep the structure of the tree, to make sure I don't screw things up.
___
*[`src/core/commitment_scheme/verifier.rs` line 123 at r8](https://reviewable.io/reviews/starkware-libs/stwo/526#-NuWYXGsCTPQtUqM8mA8:-NuXbkKM2Z7VHy_QqwBv:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/80d5e43dcd3d13d6a938c4644f3fe94bfb9c04d2/src/core/commitment_scheme/verifier.rs#L123)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Remove?
</blockquote></details>

Done.

**Review by andrewmilson — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/526#-:-NuXdPqx8Y0BCc22fqOO:bnfp4nl)* status: 8 of 11 files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Comment by spapinistarkware** [comment]
### Merge activity

* **Apr 3, 2:29 AM EDT**: @spapinistarkware merged this pull request with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/526).

**Pull request merged**
