### PR TITLE
trace to evals

### PR DESCRIPTION
**Pull request by ohad-starkware**

### CODE REVIEW

**Comment by ohad-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/945?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#945** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/945?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/945?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#944** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/944?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#943** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/943?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#942** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/942?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/945)* status: all files reviewed, 2 unresolved discussions (waiting on @ohad-starkware)

___
*[`crates/air_utils/src/trace/component_trace.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/stwo/945#-OFG9zPr6AsnSvmy0qGD:-OFG9zPr6AsnSvmy0qGE:b1j7qg) ([raw file](https://github.com/starkware-libs/stwo/blob/a972671e57f843ebfe9ee2e7e84278180663c4c1/crates/air_utils/src/trace/component_trace.rs#L50)):*
> ```XML
> #[derive(Debug)]
> pub struct ComponentTrace<const N: usize> {
>     data: [Vec<PackedM31>; N],
> ```

Document (specifically that each refers to a column of the same length)



_Code quote:_
```XML
data: [Vec<PackedM31>; N],
```
___
*[`crates/air_utils/src/trace/component_trace.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/stwo/945#-OFGACc37I2hAoucFMf8:-OFGACc37I2hAoucFMf9:bb3pkif) ([raw file](https://github.com/starkware-libs/stwo/blob/a972671e57f843ebfe9ee2e7e84278180663c4c1/crates/air_utils/src/trace/component_trace.rs#L88)):*
> ```XML
>                 data: column,
>                 length: 1 << self.log_size,
>             };
> ```

Didn't @Gali-StarkWare added a function for that?



_Code quote:_
```XML
            let eval = BaseColumn {
                data: column,
                length: 1 << self.log_size,
            };
```

**Review by Gali-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/945)* status: all files reviewed, 2 unresolved discussions (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`crates/air_utils/src/trace/component_trace.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/stwo/945#-OFGACc37I2hAoucFMf8:-OFGaRvf725jpAKDddO9:b-x2pkm0) ([raw file](https://github.com/starkware-libs/stwo/blob/a972671e57f843ebfe9ee2e7e84278180663c4c1/crates/air_utils/src/trace/component_trace.rs#L88)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Didn't @Gali-StarkWare added a function for that?
</blockquote></details>

Yes, BaseColumn::from_simd().

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/945)* status: all files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`crates/air_utils/src/trace/component_trace.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/stwo/945#-OFG9zPr6AsnSvmy0qGD:-OFGkqW-EGyrKs8rCxTX:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/a972671e57f843ebfe9ee2e7e84278180663c4c1/crates/air_utils/src/trace/component_trace.rs#L50)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Document (specifically that each refers to a column of the same length)
</blockquote></details>

Done.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/945#-:-OFGqfIi61Rpzh49U7VA:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ohad-starkware)

**Comment by ohad-starkware** [comment]
### Merge activity

* **Dec 29, 9:27 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/945).

**Pull request merged**
