### PR TITLE
Update wide fibonacci to 256 columns

### PR DESCRIPTION
**Pull request by shaharsamocha7**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/575)

### CODE REVIEW

**Comment by shaharsamocha7** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/575?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#575** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/575?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#569** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/569?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#568** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/568?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#567** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/567?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @shaharsamocha7 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/575#-:-NvVrT0c1OopJakIjfLz:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @shaharsamocha7)

___
*[`src/examples/wide_fibonacci/structs.rs` line 4 at r1](https://reviewable.io/reviews/starkware-libs/stwo/575#-NvVrMzw0xWkFDhElSnl:-NvVrMzw0xWkFDhElSnm:b-rw7gsx) ([raw file](https://github.com/starkware-libs/stwo/blob/58ef4994e863a478eb56ea24f3b1e99b178cc863/src/examples/wide_fibonacci/structs.rs#L4)):*
> ```XML
> use crate::core::backend::CPUBackend;
> use crate::core::fields::m31::BaseField;
> ```

Rename file to component.rs?

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/575#-:-NvWLSZsEfPkpbG6nQEF:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Comment by shaharsamocha7** [comment]
### Merge activity

* **Apr 15, 6:45 AM EDT**: @shaharsamocha7 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/575).

**Pull request merged**
