### PR TITLE
Added eval on exprs.

### PR DESCRIPTION
**Pull request by Alon-Ti**

### CODE REVIEW

**Comment by Alon-Ti** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/904?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#904** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/904?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/904?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#903** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/903?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#901** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/901?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#894** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/894?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#893** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/893?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#892** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/892?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#889** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/889?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#888** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/888?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#887** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/887?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#879** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/879?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#883](https://github.com/starkware-libs/stwo/pull/883) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/883?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#876** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/876?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#875** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/875?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/904)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Alon-Ti)

___
*[`crates/prover/src/constraint_framework/expr.rs` line 196 at r2](https://reviewable.io/reviews/starkware-libs/stwo/904#-OD14yueDJbDMUCs51Kw:-OD14yufDO6QiUt30o5R:br80n0h) ([raw file](https://github.com/starkware-libs/stwo/blob/7ac8b10e398e1b45092ab2824e2c82076656f006/crates/prover/src/constraint_framework/expr.rs#L196)):*
> ```XML
>     }
> 
>     pub fn eval_expr<E, C, V>(&self, columns: &C, vars: &V) -> E::F
> ```

Document!
Should we use this function only for tests?
#cfg(tests)



_Code quote:_
```XML
pub fn eval_expr<E, C, V>(&self, columns: &C, vars: &V) -> E::F
```

**Review by Alon-Ti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/904)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/expr.rs` line 196 at r2](https://reviewable.io/reviews/starkware-libs/stwo/904#-OD14yueDJbDMUCs51Kw:-OD15ziwAR8OXKoFhh32:by6c952) ([raw file](https://github.com/starkware-libs/stwo/blob/7ac8b10e398e1b45092ab2824e2c82076656f006/crates/prover/src/constraint_framework/expr.rs#L196)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Document!
Should we use this function only for tests?
#cfg(tests)
</blockquote></details>

Done; no, we'll need it in the interaction trace generator soon.

**Review by shaharsamocha7 — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/904)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @Alon-Ti)

___
*[`crates/prover/src/constraint_framework/expr.rs` line 196 at r2](https://reviewable.io/reviews/starkware-libs/stwo/904#-OD1VcVTCSJXP361PhDd:-OD1VcVTCSJXP361PhDe:bfrovch) ([raw file](https://github.com/starkware-libs/stwo/blob/7ac8b10e398e1b45092ab2824e2c82076656f006/crates/prover/src/constraint_framework/expr.rs#L196)):*
> ```XML
>     }
> 
>     pub fn eval_expr<E, C, V>(&self, columns: &C, vars: &V) -> E::F
> ```

Don't you need ext_vars here as well?



_Code quote:_
```XML
pub fn eval_expr<E, C, V>(&self, columns: &C, vars: &V) -> E::F
```
___
*[`crates/prover/src/constraint_framework/expr.rs` line 272 at r2](https://reviewable.io/reviews/starkware-libs/stwo/904#-OD1WzIz2ChK354UwGFN:-OD1WzIz2ChK354UwGFO:b-yhdaaw) ([raw file](https://github.com/starkware-libs/stwo/blob/7ac8b10e398e1b45092ab2824e2c82076656f006/crates/prover/src/constraint_framework/expr.rs#L272)):*
> ```XML
>     }
> 
>     pub fn eval_expr<E, C, V, W>(&self, columns: &C, vars: &V, ext_vars: &W) -> E::EF
> ```

WDYT?



_Suggestion:_
```XML
vars: &V, ext_vars: &EV
```
___
*[`crates/prover/src/constraint_framework/expr.rs` line 763 at r2](https://reviewable.io/reviews/starkware-libs/stwo/904#-OD1X83JDd0nPnA-E4fv:-OD1X83JDd0nPnA-E4fw:b-bcs999) ([raw file](https://github.com/starkware-libs/stwo/blob/7ac8b10e398e1b45092ab2824e2c82076656f006/crates/prover/src/constraint_framework/expr.rs#L763)):*
> ```XML
>         let ext_vars = HashMap::from([("c".to_string(), var_c)]);
> 
>         let expr = ExtExpr::SecureCol([
> ```

Does it mean we need to evaluate ExtExpr?
It seems that BaseExpr can't evaluate ExtExprs..



_Code quote:_
```XML
ExtExpr::SecureCol([
```

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/904)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @Alon-Ti)

**Review by Alon-Ti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/904)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/expr.rs` line 196 at r2](https://reviewable.io/reviews/starkware-libs/stwo/904#-OD1VcVTCSJXP361PhDd:-OD1g8J87hGjq6EBQ2rI:b-l1e7uk) ([raw file](https://github.com/starkware-libs/stwo/blob/7ac8b10e398e1b45092ab2824e2c82076656f006/crates/prover/src/constraint_framework/expr.rs#L196)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Don't you need ext_vars here as well?
</blockquote></details>

You can't use ext_vars within a base expression so I think it's better not to pass them at all.
___
*[`crates/prover/src/constraint_framework/expr.rs` line 272 at r2](https://reviewable.io/reviews/starkware-libs/stwo/904#-OD1WzIz2ChK354UwGFN:-OD1gMWg5rzz-7yfX0e2:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/7ac8b10e398e1b45092ab2824e2c82076656f006/crates/prover/src/constraint_framework/expr.rs#L272)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

WDYT?
</blockquote></details>

Done.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/904#-:-OD1lIRHERzn-2g8iZZw:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Alon-Ti)

**Comment by Alon-Ti** [comment]
### Merge activity

* **Dec 1, 10:37 AM EST**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/904).

**Pull request merged**
