### PR TITLE
Added `SecureColumnByCoordsMutSlice`.

### PR DESCRIPTION
**Pull request by Alon-Ti**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/750)

### CODE REVIEW

**Comment by Alon-Ti** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/750?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#750** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/750?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#749** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/749?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#748** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/748?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Alon-Ti and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/750#-:-O2TV_CT6litL8rK_Wx-:bnfp4nl)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @Alon-Ti and @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/column.rs` line 199 at r3](https://reviewable.io/reviews/starkware-libs/stwo/750#-O2TVY1w9S37_U4EOzgp:-O2TVY1w9S37_U4EOzgq:bkff7b1) ([raw file](https://github.com/starkware-libs/stwo/blob/28f2cfb13b676e3408e9521f3bab14ed614aeede/crates/prover/src/core/backend/simd/column.rs#L199)):*
> ```XML
> pub struct SecureColumnByCoordsMutSlice<'a>(pub [BaseColumnMutSlice<'a>; SECURE_EXTENSION_DEGREE]);
> 
> // TODO(alont): Is there a way to eliminate this code duplication?
> ```

Relevant?



_Code quote:_
```XML
// TODO(alont): Is there a way to eliminate this code duplication?
```
___
*[`crates/prover/src/core/backend/simd/column.rs` line 346 at r3](https://reviewable.io/reviews/starkware-libs/stwo/750#-O2TVB_fCpU5QOxuebhz:-O2TVB_fCpU5QOxuebi-:b-v7n9cu) ([raw file](https://github.com/starkware-libs/stwo/blob/28f2cfb13b676e3408e9521f3bab14ed614aeede/crates/prover/src/core/backend/simd/column.rs#L346)):*
> ```XML
>     #[test]
>     fn test_secure_column_by_coords_chunks_mut() {
>         let a: [BaseField; N_LANES * 16] = array::from_fn(BaseField::from);
> ```

Why is it 16 here?
Can you apply the same changes as I asked in the test above?



_Code quote:_
```XML
let a: [BaseField; N_LANES * 16]
```

**Review by Alon-Ti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/750)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/column.rs` line 346 at r3](https://reviewable.io/reviews/starkware-libs/stwo/750#-O2TVB_fCpU5QOxuebhz:-O2ULmqa3ksWuokl3xL0:beh57fs) ([raw file](https://github.com/starkware-libs/stwo/blob/28f2cfb13b676e3408e9521f3bab14ed614aeede/crates/prover/src/core/backend/simd/column.rs#L346)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why is it 16 here?
Can you apply the same changes as I asked in the test above?
</blockquote></details>

(note that this writes packed elements, so 3 is the maximum within a chunk of 4).

**Comment by Alon-Ti** [comment]
### Merge activity

* **Jul 23, 10:28 AM EDT**: @Alon-Ti started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/750).

**Pull request merged**
