### PR TITLE
Add interaction to proof.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/636)

### CODE REVIEW

**Comment by alonh5** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/636?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#636** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/636?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#634** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/634?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#633** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/633?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#631** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/631?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#582** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/582?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#589](https://github.com/starkware-libs/stwo/pull/589) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/589?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#573** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/573?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#574](https://github.com/starkware-libs/stwo/pull/574) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/574?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#572** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/572?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#562** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/562?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/636)* status: 1 of 12 files reviewed, 7 unresolved discussions (waiting on @alonh5 and @andrewmilson)

___
*[`crates/prover/src/core/air/air_ext.rs` line 83 at r4](https://reviewable.io/reviews/starkware-libs/stwo/636#-Nyz8_V65OdphtNf4m9D:-Nyz8_V65OdphtNf4m9E:b-ftkzx8) ([raw file](https://github.com/starkware-libs/stwo/blob/f0a5bb72ee4af832e887b067e49a6cef47dd0e6e/crates/prover/src/core/air/air_ext.rs#L83)):*
> ```XML
>     }
> 
>     fn component_traces<'a, B: Backend + MerkleOps<Blake2sMerkleHasher>>(
> ```

What will we do if we want another hash function for the merkle tree?
@ohad-starkware is this what you encountered?



_Code quote:_
```XML
MerkleOps<Blake2sMerkleHasher>>
```
___
*[`crates/prover/src/core/air/air_ext.rs` line 101 at r4](https://reviewable.io/reviews/starkware-libs/stwo/636#-Nyz8rytBTGr-zsTGBDe:-Nyz8ryu63oBnsepA4TV:b-p19lmh) ([raw file](https://github.com/starkware-libs/stwo/blob/f0a5bb72ee4af832e887b067e49a6cef47dd0e6e/crates/prover/src/core/air/air_ext.rs#L101)):*
> ```XML
>         });
> 
>         if trees.len() > 1 {
> ```

do we want to assert that we only have 1 or 2 trees for now?



_Code quote:_
```XML
if trees.len() > 1
```
___
*[`crates/prover/src/core/air/air_ext.rs` line 109 at r4](https://reviewable.io/reviews/starkware-libs/stwo/636#-Nyz8zlSCr32bc6mf2-I:-Nyz8zlSCr32bc6mf2-J:bgz1uxz) ([raw file](https://github.com/starkware-libs/stwo/blob/f0a5bb72ee4af832e887b067e49a6cef47dd0e6e/crates/prover/src/core/air/air_ext.rs#L109)):*
> ```XML
>                 .for_each(|(_component, component_trace)| {
>                     // TODO(AlonH): Implement n_interaction_columns() for component.
>                     let polys = poly_iter.take(1).collect_vec();
> ```

Why is this only 1?
Recall that a component may have more than 1 lookup. 
i.e. An OpCode can call both Range_check and Memory and it will need to have 2 lookup columns.



_Code quote:_
```XML
1
```
___
*[`crates/prover/src/core/prover/mod.rs` line 60 at r4](https://reviewable.io/reviews/starkware-libs/stwo/636#-Nyz9LbV6sDwvyIOcWtX:-Nyz9LbV6sDwvyIOcWtY:b-3ou3y4) ([raw file](https://github.com/starkware-libs/stwo/blob/f0a5bb72ee4af832e887b067e49a6cef47dd0e6e/crates/prover/src/core/prover/mod.rs#L60)):*
> ```XML
>     let span = span!(Level::INFO, "Trace interpolation").entered();
>     let trace_polys = trace
>         .clone()
> ```

Can we remove this clone?
If not we do need a TODO for that because cloning the trace is very expensive.



_Code quote:_
```XML
.clone()
```
___
*[`crates/prover/src/core/prover/mod.rs` line 121 at r4](https://reviewable.io/reviews/starkware-libs/stwo/636#-Nyz9pWI-Q0NFhPQt4OA:-Nyz9pWI-Q0NFhPQt4OB:b-8fudrp) ([raw file](https://github.com/starkware-libs/stwo/blob/f0a5bb72ee4af832e887b067e49a6cef47dd0e6e/crates/prover/src/core/prover/mod.rs#L121)):*
> ```XML
>     // First tree - trace.
>     let mut sample_points = TreeVec::new(vec![sample_points.flatten()]);
>     if commitment_scheme.trees.len() > 2 {
> ```

maybe we need a has_interaction() API?



_Code quote:_
```XML
if commitment_scheme.trees.len() > 2 {
```
___
*[`crates/prover/src/examples/fibonacci/mod.rs` line 158 at r4](https://reviewable.io/reviews/starkware-libs/stwo/636#-NyzA59R5S5EFFZGvpEN:-NyzA59R5S5EFFZGvpEO:byp18fd) ([raw file](https://github.com/starkware-libs/stwo/blob/f0a5bb72ee4af832e887b067e49a6cef47dd0e6e/crates/prover/src/examples/fibonacci/mod.rs#L158)):*
> ```XML
> 
>         // TODO(ShaharS), Change to a channel implementation to retrieve the random
>         // coefficients from extension field.
> ```

Remove



_Code quote:_
```XML
        // TODO(ShaharS), Change to a channel implementation to retrieve the random
        // coefficients from extension field.
```
___
*[`crates/prover/src/examples/wide_fibonacci/constraint_eval.rs` line 55 at r4](https://reviewable.io/reviews/starkware-libs/stwo/636#-NyzAFgpCWMC0-UuvRGu:-NyzAFgpCWMC0-UuvRGv:b9e5qzq) ([raw file](https://github.com/starkware-libs/stwo/blob/f0a5bb72ee4af832e887b067e49a6cef47dd0e6e/crates/prover/src/examples/wide_fibonacci/constraint_eval.rs#L55)):*
> ```XML
>                     * (trace_evals[0][j][i].square() + trace_evals[0][j + 1][i].square()
>                         - trace_evals[0][j + 2][i]);
>             }
> ```

Can you avoid a change in this code?
I would like to generate this code as it was, and then add it to a vec if that's possible.



_Code quote:_
```XML
            for j in 0..self.n_columns() - 2 {
                numerators[i] += accum.random_coeff_powers[self.n_columns() - 3 - j]
                    * (trace_evals[0][j][i].square() + trace_evals[0][j + 1][i].square()
                        - trace_evals[0][j + 2][i]);
            }
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/636)* status: 1 of 12 files reviewed, 7 unresolved discussions (waiting on @andrewmilson, @ohad-starkware, and @shaharsamocha7)

___
*[`crates/prover/src/core/air/air_ext.rs` line 83 at r4](https://reviewable.io/reviews/starkware-libs/stwo/636#-Nyz8_V65OdphtNf4m9D:-NyzBnffAYJQ43MkkzQf:b4dk8ku) ([raw file](https://github.com/starkware-libs/stwo/blob/f0a5bb72ee4af832e887b067e49a6cef47dd0e6e/crates/prover/src/core/air/air_ext.rs#L83)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

What will we do if we want another hash function for the merkle tree?
@ohad-starkware is this what you encountered?
</blockquote></details>

We can trait bound it instead. I don't think it should be a problem.
___
*[`crates/prover/src/core/air/air_ext.rs` line 101 at r4](https://reviewable.io/reviews/starkware-libs/stwo/636#-Nyz8rytBTGr-zsTGBDe:-NyzDDQx3Sjx-8ThjyWS:b-kc6t5t) ([raw file](https://github.com/starkware-libs/stwo/blob/f0a5bb72ee4af832e887b067e49a6cef47dd0e6e/crates/prover/src/core/air/air_ext.rs#L101)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

do we want to assert that we only have 1 or 2 trees for now?
</blockquote></details>

Is it necessary? I don't think there's a way to have more than that.
___
*[`crates/prover/src/core/air/air_ext.rs` line 109 at r4](https://reviewable.io/reviews/starkware-libs/stwo/636#-Nyz8zlSCr32bc6mf2-I:-NyzCM_R5fU4ZppHPC0h:b-wezmzg) ([raw file](https://github.com/starkware-libs/stwo/blob/f0a5bb72ee4af832e887b067e49a6cef47dd0e6e/crates/prover/src/core/air/air_ext.rs#L109)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why is this only 1?
Recall that a component may have more than 1 lookup. 
i.e. An OpCode can call both Range_check and Memory and it will need to have 2 lookup columns.
</blockquote></details>

That is why there that TODO. This is also something that i'm fixing upstack (638).
___
*[`crates/prover/src/core/prover/mod.rs` line 60 at r4](https://reviewable.io/reviews/starkware-libs/stwo/636#-Nyz9LbV6sDwvyIOcWtX:-NyzCiCV0rl_eH8OM2Zg:b-trdubd) ([raw file](https://github.com/starkware-libs/stwo/blob/f0a5bb72ee4af832e887b067e49a6cef47dd0e6e/crates/prover/src/core/prover/mod.rs#L60)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can we remove this clone?
If not we do need a TODO for that because cloning the trace is very expensive.
</blockquote></details>

Right I wanted to talk about this. Added a TODO for now.
___
*[`crates/prover/src/core/prover/mod.rs` line 121 at r4](https://reviewable.io/reviews/starkware-libs/stwo/636#-Nyz9pWI-Q0NFhPQt4OA:-NyzDrW3BgWVFIln5RcR:b3pflwk) ([raw file](https://github.com/starkware-libs/stwo/blob/f0a5bb72ee4af832e887b067e49a6cef47dd0e6e/crates/prover/src/core/prover/mod.rs#L121)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

maybe we need a has_interaction() API?
</blockquote></details>

This part is also encompassed in `air.mask_points()` upstack.
___
*[`crates/prover/src/examples/fibonacci/mod.rs` line 158 at r4](https://reviewable.io/reviews/starkware-libs/stwo/636#-NyzA59R5S5EFFZGvpEN:-NyzD28VA2es4hSx-vaz:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/f0a5bb72ee4af832e887b067e49a6cef47dd0e6e/crates/prover/src/examples/fibonacci/mod.rs#L158)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Remove
</blockquote></details>

Done.
___
*[`crates/prover/src/examples/wide_fibonacci/constraint_eval.rs` line 55 at r4](https://reviewable.io/reviews/starkware-libs/stwo/636#-NyzAFgpCWMC0-UuvRGu:-NyzEhrV5YJ2Cgs9uUrm:bqped8e) ([raw file](https://github.com/starkware-libs/stwo/blob/f0a5bb72ee4af832e887b067e49a6cef47dd0e6e/crates/prover/src/examples/wide_fibonacci/constraint_eval.rs#L55)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can you avoid a change in this code?
I would like to generate this code as it was, and then add it to a vec if that's possible.
</blockquote></details>

The only change here is using indexing (`[i]`), instead of `values.at(i)`. Isn't that more convenient? I can revert if you want

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/636)* status: 1 of 12 files reviewed, 3 unresolved discussions (waiting on @andrewmilson, @ohad-starkware, and @shaharsamocha7)

___
*[`crates/prover/src/core/air/air_ext.rs` line 83 at r4](https://reviewable.io/reviews/starkware-libs/stwo/636#-Nyz8_V65OdphtNf4m9D:-NyzIRC694MRu-dGPZPy:b-th291h) ([raw file](https://github.com/starkware-libs/stwo/blob/f0a5bb72ee4af832e887b067e49a6cef47dd0e6e/crates/prover/src/core/air/air_ext.rs#L83)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Ok.
I wonder if we should have a TODO to fix that when support more hash functions or just leave it be.
</blockquote></details>

When we want to support more hash functions we'll have to change it, so I don't think a TODO is necessary.
___
*[`crates/prover/src/core/prover/mod.rs` line 121 at r4](https://reviewable.io/reviews/starkware-libs/stwo/636#-Nyz9pWI-Q0NFhPQt4OA:-NyzIYOa4n7todtca8lT:b-tgnwz9) ([raw file](https://github.com/starkware-libs/stwo/blob/f0a5bb72ee4af832e887b067e49a6cef47dd0e6e/crates/prover/src/core/prover/mod.rs#L121)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

WDYM?
</blockquote></details>

PR 639.
___
*[`crates/prover/src/examples/wide_fibonacci/constraint_eval.rs` line 55 at r4](https://reviewable.io/reviews/starkware-libs/stwo/636#-NyzAFgpCWMC0-UuvRGu:-NyzIfGL7ADLQWLpwuWH:bf162nl) ([raw file](https://github.com/starkware-libs/stwo/blob/f0a5bb72ee4af832e887b067e49a6cef47dd0e6e/crates/prover/src/examples/wide_fibonacci/constraint_eval.rs#L55)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

We are going to use code gen for that. 
I don't think that the [i] vs values.at(i) is an issue. More worried about the [0] prefix although not sure if that's a problem.

It's just that this change breaks the code_gen in the air_infra repo.
</blockquote></details>

You're right there's also the [0] addition. But it must be changed, because the trace evals changed. It will also change in later PRs when actually adding the lookup constraints. This is an example for the code gen no? we should use it to implement the code gen, and not vice versa.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/636)* status: 1 of 12 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @andrewmilson)

___
*[`crates/prover/src/examples/wide_fibonacci/constraint_eval.rs` line 55 at r4](https://reviewable.io/reviews/starkware-libs/stwo/636#-NyzAFgpCWMC0-UuvRGu:-NyzNtRL94JbB-ecCz6k:bef1u6t) ([raw file](https://github.com/starkware-libs/stwo/blob/f0a5bb72ee4af832e887b067e49a6cef47dd0e6e/crates/prover/src/examples/wide_fibonacci/constraint_eval.rs#L55)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

You're right there's also the [0] addition. But it must be changed, because the trace evals changed. It will also change in later PRs when actually adding the lookup constraints. This is an example for the code gen no? we should use it to implement the code gen, and not vice versa.
</blockquote></details>

Agree, but we should think of how to do those changes without breaking the code in the stwo-air-infra
Please wait with merging those.

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/636)* status: 1 of 12 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @andrewmilson)

___
*[`crates/prover/src/core/air/air_ext.rs` line 83 at r4](https://reviewable.io/reviews/starkware-libs/stwo/636#-Nyz8_V65OdphtNf4m9D:-Nz28yMS9NdqxkScTUu6:btvt86s) ([raw file](https://github.com/starkware-libs/stwo/blob/f0a5bb72ee4af832e887b067e49a6cef47dd0e6e/crates/prover/src/core/air/air_ext.rs#L83)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

When we want to support more hash functions we'll have to change it, so I don't think a TODO is necessary.
</blockquote></details>

I Agree with Alon

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/636)* status: 1 of 12 files reviewed, 1 unresolved discussion (waiting on @andrewmilson and @shaharsamocha7)

___
*[`crates/prover/src/examples/wide_fibonacci/constraint_eval.rs` line 55 at r4](https://reviewable.io/reviews/starkware-libs/stwo/636#-NyzAFgpCWMC0-UuvRGu:-Nz2Ej5t-0dJOBAPzhFJ:bahuix2) ([raw file](https://github.com/starkware-libs/stwo/blob/f0a5bb72ee4af832e887b067e49a6cef47dd0e6e/crates/prover/src/examples/wide_fibonacci/constraint_eval.rs#L55)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Agree, but we should think of how to do those changes without breaking the code in the stwo-air-infra
Please wait with merging those.
</blockquote></details>

Sure np.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 11 files at r1, 2 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/636)* status: 3 of 13 files reviewed, 5 unresolved discussions (waiting on @alonh5 and @andrewmilson)

___
*[`crates/prover/src/core/prover/mod.rs` line 121 at r4](https://reviewable.io/reviews/starkware-libs/stwo/636#-Nyz9pWI-Q0NFhPQt4OA:-O-GuE3iBJ5KjW849eg3:bg64v8n) ([raw file](https://github.com/starkware-libs/stwo/blob/f0a5bb72ee4af832e887b067e49a6cef47dd0e6e/crates/prover/src/core/prover/mod.rs#L121)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

PR 639.
</blockquote></details>

I don't see a change to this here?
Is this the best way to know if there was an interaction in the trace?
___
*[`crates/prover/src/core/prover/mod.rs` line 213 at r7](https://reviewable.io/reviews/starkware-libs/stwo/636#-O-GvwQnDbB8Rxaf8Cxm:-O-GvwQnDbB8Rxaf8Cxn:b-oanqfg) ([raw file](https://github.com/starkware-libs/stwo/blob/e6f186de4a5dffe02a78bee5b4869621689a38cd/crates/prover/src/core/prover/mod.rs#L213)):*
> ```XML
>     let interaction_elements = air.interaction_elements(channel);
> 
>     if proof.commitments.len() > 2 {
> ```

I suggest to add a function for air that returns the number of phases.
Currently we ok with support only 1 or 2 phases of trace writing.



_Code quote:_
```XML
    if proof.commitments.len() > 2 {
```
___
*[`crates/prover/src/core/prover/mod.rs` line 282 at r7](https://reviewable.io/reviews/starkware-libs/stwo/636#-O-GxulB5VBzlqeiZwaw:-O-GxulB5VBzlqeiZwax:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/e6f186de4a5dffe02a78bee5b4869621689a38cd/crates/prover/src/core/prover/mod.rs#L282)):*
> ```XML
>         .iter();
>     let mut trace_oods_values = vec![];
>     air.components().iter().for_each(|c| {
> ```





_Suggestion:_
```XML
    air.components().iter().for_each(|component| {
```
___
*[`crates/prover/src/core/prover/mod.rs` line 285 at r7](https://reviewable.io/reviews/starkware-libs/stwo/636#-O-GyQad4zsU_dLbK3Xq:-O-GyQae050A5B1GsvP0:b-8moksu) ([raw file](https://github.com/starkware-libs/stwo/blob/e6f186de4a5dffe02a78bee5b4869621689a38cd/crates/prover/src/core/prover/mod.rs#L285)):*
> ```XML
>         trace_oods_values.push(
>             flat_trace_values
>                 .take(c.mask_points(CirclePoint::zero()).len())
> ```

Why is it the zero point here?



_Code quote:_
```XML
CirclePoint::zero()
```
___
*[`crates/prover/src/core/prover/mod.rs` line 304 at r7](https://reviewable.io/reviews/starkware-libs/stwo/636#-O-GyqQ57ypuM8FPdFku:-O-GyqQ57ypuM8FPdFkv:b-xfr2wd) ([raw file](https://github.com/starkware-libs/stwo/blob/e6f186de4a5dffe02a78bee5b4869621689a38cd/crates/prover/src/core/prover/mod.rs#L304)):*
> ```XML
>                 values.extend(interaction_values.take(1).cloned().collect_vec())
>             });
>     }
> ```

This code retrieves the mask values that are relevant for the interaction values?



_Code quote:_
```XML
    if sampled_values.len() > 2 {
        let interaction_values = &mut sampled_values
            .get(1)
            .ok_or(InvalidOodsSampleStructure)?
            .iter();

        air.components()
            .iter()
            .zip_eq(&mut trace_oods_values)
            .for_each(|(_component, values)| {
                // TODO(AlonH): Implement n_interaction_columns() for component.
                values.extend(interaction_values.take(1).cloned().collect_vec())
            });
    }
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/636)* status: 3 of 13 files reviewed, 5 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`crates/prover/src/core/prover/mod.rs` line 121 at r4](https://reviewable.io/reviews/starkware-libs/stwo/636#-Nyz9pWI-Q0NFhPQt4OA:-O-VF38v5lMVRbzxLZd7:bl9419z) ([raw file](https://github.com/starkware-libs/stwo/blob/f0a5bb72ee4af832e887b067e49a6cef47dd0e6e/crates/prover/src/core/prover/mod.rs#L121)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I don't see a change to this here?
Is this the best way to know if there was an interaction in the trace?
</blockquote></details>

Added the function you suggested in the next PR.
___
*[`crates/prover/src/core/prover/mod.rs` line 213 at r7](https://reviewable.io/reviews/starkware-libs/stwo/636#-O-GvwQnDbB8Rxaf8Cxm:-O-VEWwD9aw22kNn_27r:b-mkpbra) ([raw file](https://github.com/starkware-libs/stwo/blob/e6f186de4a5dffe02a78bee5b4869621689a38cd/crates/prover/src/core/prover/mod.rs#L213)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I suggest to add a function for air that returns the number of phases.
Currently we ok with support only 1 or 2 phases of trace writing.
</blockquote></details>

Done in the next PR (PTAL) because that's where I'm also separating between CPU and SIMD wide fib.
___
*[`crates/prover/src/core/prover/mod.rs` line 282 at r7](https://reviewable.io/reviews/starkware-libs/stwo/636#-O-GxulB5VBzlqeiZwaw:-O-VAtqM4Ecz7d0kx8Mo:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/e6f186de4a5dffe02a78bee5b4869621689a38cd/crates/prover/src/core/prover/mod.rs#L282)):*
> ```XML
>         .iter();
>     let mut trace_oods_values = vec![];
>     air.components().iter().for_each(|c| {
> ```

Done.
___
*[`crates/prover/src/core/prover/mod.rs` line 285 at r7](https://reviewable.io/reviews/starkware-libs/stwo/636#-O-GyQad4zsU_dLbK3Xq:-O-VB1V62RZxQAg7ebqF:bmydn6a) ([raw file](https://github.com/starkware-libs/stwo/blob/e6f186de4a5dffe02a78bee5b4869621689a38cd/crates/prover/src/core/prover/mod.rs#L285)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why is it the zero point here?
</blockquote></details>

Because we only want the length of the mask points so we don't care which point it is. (This was already in the code before this PR)
___
*[`crates/prover/src/core/prover/mod.rs` line 304 at r7](https://reviewable.io/reviews/starkware-libs/stwo/636#-O-GyqQ57ypuM8FPdFku:-O-VBWLXE6vIXSQiDHqa:bek1ry8) ([raw file](https://github.com/starkware-libs/stwo/blob/e6f186de4a5dffe02a78bee5b4869621689a38cd/crates/prover/src/core/prover/mod.rs#L304)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

This code retrieves the mask values that are relevant for the interaction values?
</blockquote></details>

Yes. The `take(1)` is generalized in a later PR.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 10 files at r3, 2 of 6 files at r4, 5 of 8 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/636)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @andrewmilson)

___
*[`crates/prover/src/core/prover/mod.rs` line 282 at r7](https://reviewable.io/reviews/starkware-libs/stwo/636#-O-GxulB5VBzlqeiZwaw:-O-WSi8Z-Kn8hLQ0XSIN:bulygo3) ([raw file](https://github.com/starkware-libs/stwo/blob/1a133489d9273726cbaa2b9ef6922c42a1e493b7/crates/prover/src/core/prover/mod.rs#L282)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Is it?

**Review by andrewmilson — APPROVED** [review]
:lgtm:

> Reviewed 2 of 11 files at r1, 3 of 10 files at r3, 2 of 6 files at r4, 7 of 8 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/636#-:-O-X869YANiBZj9u5eAs:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5)

___
*[`crates/prover/src/core/prover/mod.rs` line 216 at r7](https://reviewable.io/reviews/starkware-libs/stwo/636#-O-X7gZd3hyG4HqhMuY9:-O-X7gZe7god1m1lW3ot:b4wping) ([raw file](https://github.com/starkware-libs/stwo/blob/1a133489d9273726cbaa2b9ef6922c42a1e493b7/crates/prover/src/core/prover/mod.rs#L216)):*
> ```XML
>         commitment_scheme.commit(
>             proof.commitments[1],
>             air.column_log_sizes()[..1].to_vec(),
> ```

I don't understand why the first column size is passed here

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/636)* status: 12 of 13 files reviewed, 2 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`crates/prover/src/core/prover/mod.rs` line 216 at r7](https://reviewable.io/reviews/starkware-libs/stwo/636#-O-X7gZd3hyG4HqhMuY9:-O-e9RHJ5gwsqY5c6boJ:b-cwer36) ([raw file](https://github.com/starkware-libs/stwo/blob/1a133489d9273726cbaa2b9ef6922c42a1e493b7/crates/prover/src/core/prover/mod.rs#L216)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

I don't understand why the first column size is passed here
</blockquote></details>

You're right, I did this as a patch, it only works for the current example. Fixed it in PR 638 (which you can also TAL at).
___
*[`crates/prover/src/core/prover/mod.rs` line 282 at r7](https://reviewable.io/reviews/starkware-libs/stwo/636#-O-GxulB5VBzlqeiZwaw:-O-e8ccDAWohGn_8lgQU:bwhu7y) ([raw file](https://github.com/starkware-libs/stwo/blob/1a133489d9273726cbaa2b9ef6922c42a1e493b7/crates/prover/src/core/prover/mod.rs#L282)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Is it?
</blockquote></details>

Now it is.

**Review by andrewmilson — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/636#-:-O-iSiYlCe5LgOBdi0-J:bnfp4nl)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/636#-:-O-og-aI4mQI7gqtmI66:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Comment by alonh5** [comment]
### Merge activity

* **Jun 20, 6:54 AM EDT**: @alonh5 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/636).

**Pull request merged**
