### PR TITLE
QuotientOps

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/481)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/481?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#481** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/481?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#480** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/480?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#479** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/479?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#478** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/478?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#463** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/463?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#477** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/477?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#476** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/476?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/481)* status: all files reviewed, 6 unresolved discussions (waiting on @andrewmilson and @spapinistarkware)

___
*[`src/core/backend/cpu/quotients.rs` line 17 at r4](https://reviewable.io/reviews/starkware-libs/stwo/481#-NtWA1wIAtoj7Gbcbjn9:-NtWA1wJ2EA8bulqvb5E:b-grofqg) ([raw file](https://github.com/starkware-libs/stwo/blob/552036a486ad048957fdd3691bfb6bdc2f8e85aa/src/core/backend/cpu/quotients.rs#L17)):*
> ```XML
>     fn accumulate_quotients(
>         domain: CircleDomain,
>         mut accum: ColumnAccumulator<'_, Self>,
> ```

Shouldn't it be by reference?



_Suggestion:_
```XML
accum: &mut ColumnAccumulator<'_, Self>,
```
___
*[`src/core/backend/cpu/quotients.rs` line 30 at r4](https://reviewable.io/reviews/starkware-libs/stwo/481#-NtWBYIWEJGAIzx0VD-n:-NtWBYIWEJGAIzx0VD-o:b5dcos0) ([raw file](https://github.com/starkware-libs/stwo/blob/552036a486ad048957fdd3691bfb6bdc2f8e85aa/src/core/backend/cpu/quotients.rs#L30)):*
> ```XML
>                     let column = &columns[*column_index];
>                     let value = column[row];
>                     numerator = numerator * random_coeff + (value - *open_value);
> ```

This should be a line between the value and it's complex conjugate.



_Code quote:_
```XML
*open_value
```
___
*[`src/core/backend/cpu/quotients.rs` line 39 at r4](https://reviewable.io/reviews/starkware-libs/stwo/481#-NtWBm300iIx_lj1MJps:-NtWBm300iIx_lj1MJpt:b-w7ebg2) ([raw file](https://github.com/starkware-libs/stwo/blob/552036a486ad048957fdd3691bfb6bdc2f8e85aa/src/core/backend/cpu/quotients.rs#L39)):*
> ```XML
>                 );
> 
>                 row_accumlator *= random_coeff.pow(opening.column_indices_and_values.len() as u128)
> ```

This should also be fixed.



_Code quote:_
```XML
opening.column_indices_and_values.len() as u128
```
___
*[`src/core/commitment_scheme/quotients.rs` line 9 at r4](https://reviewable.io/reviews/starkware-libs/stwo/481#-NtVxzVS1PiAbVeCq9HQ:-NtVxzVS1PiAbVeCq9HR:by8lm26) ([raw file](https://github.com/starkware-libs/stwo/blob/552036a486ad048957fdd3691bfb6bdc2f8e85aa/src/core/commitment_scheme/quotients.rs#L9)):*
> ```XML
> 
> pub trait QuotientOps: Backend {
>     fn accumulate_quotients(
> ```

Document.



_Code quote:_
```XML
fn accumulate_quotients(
```
___
*[`src/core/commitment_scheme/quotients.rs` line 18 at r4](https://reviewable.io/reviews/starkware-libs/stwo/481#-NtVyqB00ZL21zAyYQQM:-NtVyqB00ZL21zAyYQQN:by8lm26) ([raw file](https://github.com/starkware-libs/stwo/blob/552036a486ad048957fdd3691bfb6bdc2f8e85aa/src/core/commitment_scheme/quotients.rs#L18)):*
> ```XML
> }
> 
> pub struct BatchedColumnOpenings {
> ```

Document.
___
*[`src/core/commitment_scheme/quotients.rs` line 18 at r4](https://reviewable.io/reviews/starkware-libs/stwo/481#-NtWAjbF6FLRALxxZvuu:-NtWAjbF6FLRALxxZvuv:bnhi2sh) ([raw file](https://github.com/starkware-libs/stwo/blob/552036a486ad048957fdd3691bfb6bdc2f8e85aa/src/core/commitment_scheme/quotients.rs#L18)):*
> ```XML
> }
> 
> pub struct BatchedColumnOpenings {
> ```

Can we change all open/opening to oods? opening is overloaded.



_Suggestion:_
```XML
BatchedColumnOods
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/481)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @alonh5 and @andrewmilson)

___
*[`src/core/backend/cpu/quotients.rs` line 30 at r4](https://reviewable.io/reviews/starkware-libs/stwo/481#-NtWBYIWEJGAIzx0VD-n:-NtWRM33BVpd6SzB8X0f:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/552036a486ad048957fdd3691bfb6bdc2f8e85aa/src/core/backend/cpu/quotients.rs#L30)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

This should be a line between the value and it's complex conjugate.
</blockquote></details>

Done.
___
*[`src/core/backend/cpu/quotients.rs` line 39 at r4](https://reviewable.io/reviews/starkware-libs/stwo/481#-NtWBm300iIx_lj1MJps:-NtWRN704jaW61pViw9J:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/552036a486ad048957fdd3691bfb6bdc2f8e85aa/src/core/backend/cpu/quotients.rs#L39)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

This should also be fixed.
</blockquote></details>

Done.
___
*[`src/core/commitment_scheme/quotients.rs` line 9 at r4](https://reviewable.io/reviews/starkware-libs/stwo/481#-NtVxzVS1PiAbVeCq9HQ:-NtWTFiU-cZnYXPm_JY8:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/552036a486ad048957fdd3691bfb6bdc2f8e85aa/src/core/commitment_scheme/quotients.rs#L9)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Document.
</blockquote></details>

Done.
___
*[`src/core/commitment_scheme/quotients.rs` line 18 at r4](https://reviewable.io/reviews/starkware-libs/stwo/481#-NtVyqB00ZL21zAyYQQM:-NtWScOc1gYIfBzZLkOQ:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/552036a486ad048957fdd3691bfb6bdc2f8e85aa/src/core/commitment_scheme/quotients.rs#L18)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Document.
</blockquote></details>

Done.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/481)* status: all files reviewed, 6 unresolved discussions (waiting on @andrewmilson and @spapinistarkware)

___
*[`src/core/backend/cpu/quotients.rs` line 24 at r5](https://reviewable.io/reviews/starkware-libs/stwo/481#-Ntjj7VX8kzxoKUAv6XS:-Ntjj7VX8kzxoKUAv6XT:br9xaof) ([raw file](https://github.com/starkware-libs/stwo/blob/8e046cb65c34562bae7027d53e5802fd456ab449/src/core/backend/cpu/quotients.rs#L24)):*
> ```XML
>         let mut res = SecureColumn::zeros(domain.size());
>         for row in 0..domain.size() {
>             let domain_point = domain.at(bit_reverse_index(row, domain.log_size()));
> ```

Not for this PR but do you think we should have a more efficient way to iterate over the domain in bit reverse order? Maybe also store an array of points in the domain?



_Code quote:_
```XML
let domain_point = domain.at(bit_reverse_index(row, domain.log_size()));
```
___
*[`src/core/backend/cpu/quotients.rs` line 25 at r5](https://reviewable.io/reviews/starkware-libs/stwo/481#-NtjlEWs369dS-hs91_Y:-NtjlEWs369dS-hs91_Z:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/8e046cb65c34562bae7027d53e5802fd456ab449/src/core/backend/cpu/quotients.rs#L25)):*
> ```XML
>         for row in 0..domain.size() {
>             let domain_point = domain.at(bit_reverse_index(row, domain.log_size()));
>             let row_accumlator =
> ```





_Suggestion:_
```XML
row_value
```
___
*[`src/core/backend/cpu/quotients.rs` line 91 at r5](https://reviewable.io/reviews/starkware-libs/stwo/481#-NtjoqAo60RssQ4WEL9G:-NtjoqApEEk2MvX9wups:bbpx1it) ([raw file](https://github.com/starkware-libs/stwo/blob/8e046cb65c34562bae7027d53e5802fd456ab449/src/core/backend/cpu/quotients.rs#L91)):*
> ```XML
>         );
>         let quot_poly_base_field =
>             CPUCircleEvaluation::new(eval_domain, quot_eval.columns[0].clone()).interpolate();
> ```

Why are you only testing the first base filed column is in the fft space?



_Code quote:_
```XML
quot_eval.columns[0]
```
___
*[`src/core/commitment_scheme/quotients.rs` line 11 at r5](https://reviewable.io/reviews/starkware-libs/stwo/481#-NtjhXucAo84FC1eUZ6T:-NtjhXucAo84FC1eUZ6U:b45h) ([raw file](https://github.com/starkware-libs/stwo/blob/8e046cb65c34562bae7027d53e5802fd456ab449/src/core/commitment_scheme/quotients.rs#L11)):*
> ```XML
> pub trait QuotientOps: Backend {
>     /// Accumulates the quotients of the columns at the given domain.
>     /// For a column f(x), and a point opening (p,v), the quotient is
> ```





_Suggestion:_
```XML
sample/sampling
```
___
*[`src/core/commitment_scheme/quotients.rs` line 20 at r5](https://reviewable.io/reviews/starkware-libs/stwo/481#-Ntji6CqCy_FdJb6a_61:-Ntji6CqCy_FdJb6a_62:b45h) ([raw file](https://github.com/starkware-libs/stwo/blob/8e046cb65c34562bae7027d53e5802fd456ab449/src/core/commitment_scheme/quotients.rs#L20)):*
> ```XML
>         columns: &[&CircleEvaluation<Self, BaseField, BitReversedOrder>],
>         random_coeff: SecureField,
>         openings: &[ColumnSampleBatch],
> ```





_Suggestion:_
```XML
samples/samplings
```
___
*[`src/core/commitment_scheme/quotients.rs` line 26 at r5](https://reviewable.io/reviews/starkware-libs/stwo/481#-NtjhJrd0jPZel63CiY8:-NtjhJre0W9oi-2LlSXx:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/8e046cb65c34562bae7027d53e5802fd456ab449/src/core/commitment_scheme/quotients.rs#L26)):*
> ```XML
> /// A batch of column samplings at a point.
> pub struct ColumnSampleBatch {
>     /// The point at which the columns are opened.
> ```





_Suggestion:_
```XML
sampled.
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/481)* status: all files reviewed, 5 unresolved discussions (waiting on @alonh5 and @andrewmilson)

___
*[`src/core/backend/cpu/quotients.rs` line 24 at r5](https://reviewable.io/reviews/starkware-libs/stwo/481#-Ntjj7VX8kzxoKUAv6XS:-NtkRdAYA9JBAWgL4cDG:b-vwl1h3) ([raw file](https://github.com/starkware-libs/stwo/blob/8e046cb65c34562bae7027d53e5802fd456ab449/src/core/backend/cpu/quotients.rs#L24)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Not for this PR but do you think we should have a more efficient way to iterate over the domain in bit reverse order? Maybe also store an array of points in the domain?
</blockquote></details>

We can, it's not super complicated.
___
*[`src/core/backend/cpu/quotients.rs` line 91 at r5](https://reviewable.io/reviews/starkware-libs/stwo/481#-NtjoqAo60RssQ4WEL9G:-NtkRvQz4bu5i9e3SkOs:blb7jig) ([raw file](https://github.com/starkware-libs/stwo/blob/8e046cb65c34562bae7027d53e5802fd456ab449/src/core/backend/cpu/quotients.rs#L91)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Why are you only testing the first base filed column is in the fft space?
</blockquote></details>

Good enough fot the test
___
*[`src/core/commitment_scheme/quotients.rs` line 11 at r5](https://reviewable.io/reviews/starkware-libs/stwo/481#-NtjhXucAo84FC1eUZ6T:-NtkSReE3qjNGcC0hHDA:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/8e046cb65c34562bae7027d53e5802fd456ab449/src/core/commitment_scheme/quotients.rs#L11)):*
> ```XML
> pub trait QuotientOps: Backend {
>     /// Accumulates the quotients of the columns at the given domain.
>     /// For a column f(x), and a point opening (p,v), the quotient is
> ```

Done.
___
*[`src/core/commitment_scheme/quotients.rs` line 20 at r5](https://reviewable.io/reviews/starkware-libs/stwo/481#-Ntji6CqCy_FdJb6a_61:-NtkSUU32B5EsWvyqylZ:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/8e046cb65c34562bae7027d53e5802fd456ab449/src/core/commitment_scheme/quotients.rs#L20)):*
> ```XML
>         columns: &[&CircleEvaluation<Self, BaseField, BitReversedOrder>],
>         random_coeff: SecureField,
>         openings: &[ColumnSampleBatch],
> ```

Done.
___
*[`src/core/commitment_scheme/quotients.rs` line 26 at r5](https://reviewable.io/reviews/starkware-libs/stwo/481#-NtjhJrd0jPZel63CiY8:-NtkSWPHDf0PJNnTO9Tf:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/8e046cb65c34562bae7027d53e5802fd456ab449/src/core/commitment_scheme/quotients.rs#L26)):*
> ```XML
> /// A batch of column samplings at a point.
> pub struct ColumnSampleBatch {
>     /// The point at which the columns are opened.
> ```

Done.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/481#-:-NtkWX2oC9RzZ6keu6Qc:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @andrewmilson and @spapinistarkware)

___
*[`src/core/backend/cpu/quotients.rs` line 24 at r5](https://reviewable.io/reviews/starkware-libs/stwo/481#-Ntjj7VX8kzxoKUAv6XS:-NtkTKMy5ZAApnGvRHSP:b-8gpyxc) ([raw file](https://github.com/starkware-libs/stwo/blob/8e046cb65c34562bae7027d53e5802fd456ab449/src/core/backend/cpu/quotients.rs#L24)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

We can, it's not super complicated.
</blockquote></details>

Add a TODO? You can put it on me
___
*[`src/core/backend/cpu/quotients.rs` line 14 at r6](https://reviewable.io/reviews/starkware-libs/stwo/481#-NtkTe7U4TnnQYCSYFLB:-NtkTe7U4TnnQYCSYFLC:b-rwph7y) ([raw file](https://github.com/starkware-libs/stwo/blob/fed4457eb6178e001db968219ac21d39b83e58c9/src/core/backend/cpu/quotients.rs#L14)):*
> ```XML
> use crate::core::poly::BitReversedOrder;
> use crate::core::utils::bit_reverse_index;
> ```

`open(ing)` -> `sample` in this file too.

**Comment by spapinistarkware** [comment]
### Merge activity

* **Mar 24, 9:16 AM EDT**: @spapinistarkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/481).

**Pull request merged**
