### PR TITLE
Split CP oods quotient.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/434)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/434)* status: 3 of 5 files reviewed, 5 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

___
*[`src/core/commitment_scheme.rs` line 18 at r2](https://reviewable.io/reviews/starkware-libs/stwo/434#-NsMIRxA4-J4fixRLYs8:-NsMIRxB-lwtvu-V8eYM:bdm3d9m) ([raw file](https://github.com/starkware-libs/stwo/blob/cb056121b92cf6f0d1cc2bea1b4a4ed29105670b/src/core/commitment_scheme.rs#L18)):*
> ```XML
> 
> pub struct CommitmentSchemeProver {
>     pub polynomials: Vec<CPUCirclePoly<BaseField>>,
> ```

Should these also be ColumnVec?
___
*[`src/core/commitment_scheme.rs` line 52 at r2](https://reviewable.io/reviews/starkware-libs/stwo/434#-NsMIdDI-p0CN-i0vyeZ:-NsMIdDI-p0CN-i0vye_:b-lkhe08) ([raw file](https://github.com/starkware-libs/stwo/blob/cb056121b92cf6f0d1cc2bea1b4a4ed29105670b/src/core/commitment_scheme.rs#L52)):*
> ```XML
>     }
> 
>     pub fn open(&self, positions: &[usize]) -> ColumnVec<Vec<BaseField>> {
> ```

Not all coluns are of the same size, so this inerface doesn't make sense to me.
Something that makes more since is to give a vec of indices for each column.
___
*[`src/core/air/mod.rs` line 97 at r2](https://reviewable.io/reviews/starkware-libs/stwo/434#-NsMIqrYDBN_yqh23FHf:-NsMIqrYDBN_yqh23FHg:b-8q70n3) ([raw file](https://github.com/starkware-libs/stwo/blob/cb056121b92cf6f0d1cc2bea1b4a4ed29105670b/src/core/air/mod.rs#L97)):*
> ```XML
>         let mut bounds = bounds_visitor.finalize();
>         // Add the composition polynomial's log degree bounds.
>         bounds.push(self.max_constraint_log_degree_bound());
> ```

Something like this maybe?
bounds.extend([self.max(); 4])
___
*[`src/core/poly/circle/secure_poly.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/stwo/434#-NsMKrM5EVX8s8YQZUlk:-NsMKZ7SCfCy-XA3OkHS:bho4r3h) ([raw file](https://github.com/starkware-libs/stwo/blob/cb056121b92cf6f0d1cc2bea1b4a4ed29105670b/src/core/poly/circle/secure_poly.rs#L20)):*
> ```XML
>     }
> 
>     pub fn eval_columns_at_point(&self, point: CirclePoint<SecureField>) -> SecureValue {
> ```

I think SecureValue is kind of an overkill. You only ever gonna use it in 2 places, prover and verifier.
The  SecureArray might also be and overkill.

You can just use arrays of size SECURE_EXTENSION_DEGREE, and have a function near the prove() that combines them (you are gonna use it twice in the entire code AFAIU).
And remove `eval_at_point` from here. just have eval_columsn.
___
*[`src/fibonacci/mod.rs` line 213 at r2](https://reviewable.io/reviews/starkware-libs/stwo/434#-NsMK-Zf3Sr_rZUSc_Gv:-NsMK-Zf3Sr_rZUSc_Gw:bd9neq6) ([raw file](https://github.com/starkware-libs/stwo/blob/cb056121b92cf6f0d1cc2bea1b4a4ed29105670b/src/fibonacci/mod.rs#L213)):*
> ```XML
>     );
>     assert_eq!(
>         composition_polynomial_oods_value,
> ```

Remove `composition_polynomial_oods_value` from the proof, and compute it from the combine(), instead of this assert

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/434)* status: 3 of 5 files reviewed, 4 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

___
*[`src/core/commitment_scheme.rs` line 18 at r2](https://reviewable.io/reviews/starkware-libs/stwo/434#-NsMIRxA4-J4fixRLYs8:-NsMM_zN5nN9UVpLqt6m:b-qrbo4d) ([raw file](https://github.com/starkware-libs/stwo/blob/cb056121b92cf6f0d1cc2bea1b4a4ed29105670b/src/core/commitment_scheme.rs#L18)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Should these also be ColumnVec?
</blockquote></details>

I see you did this in another PR

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/434)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`src/core/commitment_scheme.rs` line 52 at r2](https://reviewable.io/reviews/starkware-libs/stwo/434#-NsMIdDI-p0CN-i0vyeZ:-NsNDFqz4ySF0rUDvylp:bw53jl5) ([raw file](https://github.com/starkware-libs/stwo/blob/cb056121b92cf6f0d1cc2bea1b4a4ed29105670b/src/core/commitment_scheme.rs#L52)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Not all coluns are of the same size, so this inerface doesn't make sense to me.
Something that makes more since is to give a vec of indices for each column.
</blockquote></details>

You're right, this is still the basic merkle tree. I added a TODO.
___
*[`src/core/air/mod.rs` line 97 at r2](https://reviewable.io/reviews/starkware-libs/stwo/434#-NsMIqrYDBN_yqh23FHf:-NsN9OyM0orA1DiomVVl:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/cb056121b92cf6f0d1cc2bea1b4a4ed29105670b/src/core/air/mod.rs#L97)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Something like this maybe?
bounds.extend([self.max(); 4])
</blockquote></details>

Done.
___
*[`src/core/poly/circle/secure_poly.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/stwo/434#-NsMKrM5EVX8s8YQZUlk:-NsN9rPV7I1ao27-B379:bkzycog) ([raw file](https://github.com/starkware-libs/stwo/blob/cb056121b92cf6f0d1cc2bea1b4a4ed29105670b/src/core/poly/circle/secure_poly.rs#L20)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I think SecureValue is kind of an overkill. You only ever gonna use it in 2 places, prover and verifier.
The  SecureArray might also be and overkill.

You can just use arrays of size SECURE_EXTENSION_DEGREE, and have a function near the prove() that combines them (you are gonna use it twice in the entire code AFAIU).
And remove `eval_at_point` from here. just have eval_columsn.
</blockquote></details>

Done. I'll remove `eval_at_point` in a new PR it causes a few more changes.
___
*[`src/fibonacci/mod.rs` line 213 at r2](https://reviewable.io/reviews/starkware-libs/stwo/434#-NsMK-Zf3Sr_rZUSc_Gv:-NsNDTL40z3Ryib__vtM:bmtzp6s) ([raw file](https://github.com/starkware-libs/stwo/blob/cb056121b92cf6f0d1cc2bea1b4a4ed29105670b/src/fibonacci/mod.rs#L213)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Remove `composition_polynomial_oods_value` from the proof, and compute it from the combine(), instead of this assert
</blockquote></details>

(discussed offline).

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/434#-:-NsNI1tn0l9QC_IvwzwM:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Pull request merged**
