### PR TITLE
integerated batch inverse to oods

### PR DESCRIPTION
**Pull request by ohad-agadi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/466)

### CODE REVIEW

**Comment by ohad-starkware** [comment]
* **#466** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/466?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ohad-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/466)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @ohad-starkware and @spapinistarkware)

___
*[`src/core/oods.rs` line 60 at r2](https://reviewable.io/reviews/starkware-libs/stwo/466#-NssJUuP1zLGbmnySWgI:-NssJUuP1zLGbmnySWgJ:b-729ffu) ([raw file](https://github.com/starkware-libs/stwo/blob/2818f4f195b6320a20d79b272ae70d9e7a805df2/src/core/oods.rs#L60)):*
> ```XML
> 
> const CHUNK_LOG_SIZE: usize = 7;
> const CHUNK_SIZE: usize = 1 << CHUNK_LOG_SIZE;
> ```

Can this code go to a generic place where all the places use it?
This value only depends on the L1 cache_size right?



_Code quote:_
```XML
const CHUNK_LOG_SIZE: usize = 7;
const CHUNK_SIZE: usize = 1 << CHUNK_LOG_SIZE;
```
___
*[`src/core/oods.rs` line 83 at r2](https://reviewable.io/reviews/starkware-libs/stwo/466#-NssK25E5BSMG_RR8oYV:-NssK25FEguA2k4uY-Uw:b7v24qw) ([raw file](https://github.com/starkware-libs/stwo/blob/2818f4f195b6320a20d79b272ae70d9e7a805df2/src/core/oods.rs#L83)):*
> ```XML
>             ));
>         }
>     } else {
> ```

Consider using an early return / match patern



_Code quote:_
```XML
    if eval.domain.log_size() < CHUNK_LOG_SIZE as u32 {
        for (i, point) in enumerate(eval.domain.iter()) {
            let index = bit_reverse_index(i, eval.domain.log_size());
            values.push(eval_pair_oods_quotient_at_point(
                point,
                eval.values[index],
                oods_point,
                oods_value,
            ));
        }
    } else {
```
___
*[`src/core/oods.rs` line 92 at r2](https://reviewable.io/reviews/starkware-libs/stwo/466#-NssKNPo7asAy6arh2gD:-NssKNPo7asAy6arh2gE:b-matlo4) ([raw file](https://github.com/starkware-libs/stwo/blob/2818f4f195b6320a20d79b272ae70d9e7a805df2/src/core/oods.rs#L92)):*
> ```XML
> 
>             let numerators: [SecureField; CHUNK_SIZE] = std::array::from_fn(|i| {
>                 let point = chunk[i].1;
> ```

open also chunk[i].0



_Code quote:_
```XML
let point = chunk[i].1;
```
___
*[`src/core/oods.rs` line 101 at r2](https://reviewable.io/reviews/starkware-libs/stwo/466#-NssKfnXAd1hOPeym4ar:-NssKfnXAd1hOPeym4as:b-u84k8n) ([raw file](https://github.com/starkware-libs/stwo/blob/2818f4f195b6320a20d79b272ae70d9e7a805df2/src/core/oods.rs#L101)):*
> ```XML
>                 let point = chunk[i].1;
>                 pair_vanishing(oods_point, oods_point.complex_conjugate(), point.into_ef())
>             });
> ```

Consider to combine the denom in the same function as the numerators and return zipped array.



_Code quote:_
```XML
            let denominators: [SecureField; CHUNK_SIZE] = std::array::from_fn(|i| {
                let point = chunk[i].1;
                pair_vanishing(oods_point, oods_point.complex_conjugate(), point.into_ef())
            });
```
___
*[`src/core/oods.rs` line 102 at r2](https://reviewable.io/reviews/starkware-libs/stwo/466#-NssKa0P6OfQcJLt15rb:-NssKa0P6OfQcJLt15rc:b-bkihcd) ([raw file](https://github.com/starkware-libs/stwo/blob/2818f4f195b6320a20d79b272ae70d9e7a805df2/src/core/oods.rs#L102)):*
> ```XML
>                 pair_vanishing(oods_point, oods_point.complex_conjugate(), point.into_ef())
>             });
>             let mut inversed_denominators = [SecureField::zero(); CHUNK_SIZE];
> ```

Do you need an initialized array here? or can you use with_capacity instead?



_Code quote:_
```XML
[SecureField::zero(); CHUNK_SIZE];
```

**Review by ohad-agadi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/466)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`src/core/oods.rs` line 60 at r2](https://reviewable.io/reviews/starkware-libs/stwo/466#-NssJUuP1zLGbmnySWgI:-NssQYSYB7fLBCXWazXy:b-40zsz9) ([raw file](https://github.com/starkware-libs/stwo/blob/2818f4f195b6320a20d79b272ae70d9e7a805df2/src/core/oods.rs#L60)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can this code go to a generic place where all the places use it?
This value only depends on the L1 cache_size right?
</blockquote></details>

moved it to the cpu backend
___
*[`src/core/oods.rs` line 83 at r2](https://reviewable.io/reviews/starkware-libs/stwo/466#-NssK25E5BSMG_RR8oYV:-NssRppX-5tSx-fAfZMx:b4sy2au) ([raw file](https://github.com/starkware-libs/stwo/blob/2818f4f195b6320a20d79b272ae70d9e7a805df2/src/core/oods.rs#L83)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Consider using an early return / match patern
</blockquote></details>

refactored
___
*[`src/core/oods.rs` line 92 at r2](https://reviewable.io/reviews/starkware-libs/stwo/466#-NssKNPo7asAy6arh2gD:-NssSIHM3FNqX39fp448:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/2818f4f195b6320a20d79b272ae70d9e7a805df2/src/core/oods.rs#L92)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

open also chunk[i].0
</blockquote></details>

Done.
___
*[`src/core/oods.rs` line 101 at r2](https://reviewable.io/reviews/starkware-libs/stwo/466#-NssKfnXAd1hOPeym4ar:-NssSPoy2fLHEmhteCEy:bysxsbd) ([raw file](https://github.com/starkware-libs/stwo/blob/2818f4f195b6320a20d79b272ae70d9e7a805df2/src/core/oods.rs#L101)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Consider to combine the denom in the same function as the numerators and return zipped array.
</blockquote></details>

Zipped doesn't go well with batch inverse.
___
*[`src/core/oods.rs` line 102 at r2](https://reviewable.io/reviews/starkware-libs/stwo/466#-NssKa0P6OfQcJLt15rb:-NssSclm45ETOxy345Bh:bfwf8nb) ([raw file](https://github.com/starkware-libs/stwo/blob/2818f4f195b6320a20d79b272ae70d9e7a805df2/src/core/oods.rs#L102)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Do you need an initialized array here? or can you use with_capacity instead?
</blockquote></details>

this is stack-allocated, vec::with_capacity is heap, also batch inverse 'writes' to the slice rather than pushing to it which is faster, but if the values are not initialized(like what happens if you vec::with_capacity) you crash.
I'm hoping the compiler realizes this is just zeroed-out memory and this is optimized, haven't tested it yet.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/466)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @ohad-starkware and @spapinistarkware)

___
*[`src/core/oods.rs` line 95 at r3](https://reviewable.io/reviews/starkware-libs/stwo/466#-NssXst_1cp6t1Du8rI7:-NssXst_1cp6t1Du8rI8:bt3ax87) ([raw file](https://github.com/starkware-libs/stwo/blob/b73120e8cc61b033f72fb2ea6ab12dd76ec6e37c/src/core/oods.rs#L95)):*
> ```XML
>         // Cached values for complex conjugate lines calculation.
>         let mul = (oods_value.complex_conjugate() - oods_value) * denom_inv;
>         let add = oods_value + mul * (-oods_point.y);
> ```

Can we find another name for those?



_Code quote:_
```XML
        let mul = (oods_value.complex_conjugate() - oods_value) * denom_inv;
        let add = oods_value + mul * (-oods_point.y);
```
___
*[`src/core/oods.rs` line 97 at r3](https://reviewable.io/reviews/starkware-libs/stwo/466#-NssVt2U3PCdSzlb8WDb:-NssVt2V9-vagSE4gJC5:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/b73120e8cc61b033f72fb2ea6ab12dd76ec6e37c/src/core/oods.rs#L97)):*
> ```XML
>         let add = oods_value + mul * (-oods_point.y);
> 
>         let numerators: [SecureField; N_SECUREFIELD_IN_CACHE] = std::array::from_fn(|i| {
> ```





_Suggestion:_
```XML
N_SECURE_FIELD_IN_CACHE
```
___
*[`src/fibonacci/component.rs` line 142 at r3](https://reviewable.io/reviews/starkware-libs/stwo/466#-NssXevw0JgHSaXfimUz:-NssXevx5XHwT2Llp1WC:bhkm011) ([raw file](https://github.com/starkware-libs/stwo/blob/b73120e8cc61b033f72fb2ea6ab12dd76ec6e37c/src/fibonacci/component.rs#L142)):*
> ```XML
>                 {
>                     // Collect denominators and inverse.
>                     let mut buff: [BaseField; N_SECUREFIELD_IN_CACHE] = std::array::from_fn(|i| {
> ```

Those are BaseField



_Code quote:_
```XML
BaseField; N_SECUREFIELD_IN_CACHE
```

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/466)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @ohad-starkware and @spapinistarkware)

___
*[`src/core/backend/cpu/mod.rs` line 13 at r3](https://reviewable.io/reviews/starkware-libs/stwo/466#-NssY0VQ7ZcN2jrHbEEg:-NssY0VQ7ZcN2jrHbEEh:b-h2lyyc) ([raw file](https://github.com/starkware-libs/stwo/blob/b73120e8cc61b033f72fb2ea6ab12dd76ec6e37c/src/core/backend/cpu/mod.rs#L13)):*
> ```XML
> 
> // TODO(Ohad): figure out exact numbers.
> pub(crate) const LOG_N_SECUREFIELD_IN_CACHE: usize = 10;
> ```

Document how you got those numbers (roughly) and that which size of L1 cache you assume



_Code quote:_
```XML
pub(crate) const LOG_N_SECUREFIELD_IN_CACHE: usize = 10;
```

**Review by ohad-agadi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/466)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`src/core/oods.rs` line 95 at r3](https://reviewable.io/reviews/starkware-libs/stwo/466#-NssXst_1cp6t1Du8rI7:-NssZPee3Tw3SimANkFE:b-sr8b0r) ([raw file](https://github.com/starkware-libs/stwo/blob/b73120e8cc61b033f72fb2ea6ab12dd76ec6e37c/src/core/oods.rs#L95)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can we find another name for those?
</blockquote></details>

better
___
*[`src/core/oods.rs` line 97 at r3](https://reviewable.io/reviews/starkware-libs/stwo/466#-NssVt2U3PCdSzlb8WDb:-NssYFdl4h2Mzefyg51g:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/b73120e8cc61b033f72fb2ea6ab12dd76ec6e37c/src/core/oods.rs#L97)):*
> ```XML
>         let add = oods_value + mul * (-oods_point.y);
> 
>         let numerators: [SecureField; N_SECUREFIELD_IN_CACHE] = std::array::from_fn(|i| {
> ```

Done.
___
*[`src/core/backend/cpu/mod.rs` line 13 at r3](https://reviewable.io/reviews/starkware-libs/stwo/466#-NssY0VQ7ZcN2jrHbEEg:-NssZ4vN-ryhzPZAx8kI:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/b73120e8cc61b033f72fb2ea6ab12dd76ec6e37c/src/core/backend/cpu/mod.rs#L13)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Document how you got those numbers (roughly) and that which size of L1 cache you assume
</blockquote></details>

Done.
___
*[`src/fibonacci/component.rs` line 142 at r3](https://reviewable.io/reviews/starkware-libs/stwo/466#-NssXevw0JgHSaXfimUz:-NssYHaC2OxB2ewjV-7I:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/b73120e8cc61b033f72fb2ea6ab12dd76ec6e37c/src/fibonacci/component.rs#L142)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Those are BaseField
</blockquote></details>

Done.

**Pull request closed without merging**
