### PR TITLE
Use only canonic domains

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/463)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
* **#463** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/463?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 10 files at r1, 3 of 7 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/463)* status: 9 of 10 files reviewed, 6 unresolved discussions (waiting on @spapinistarkware)

___
*[`src/core/air/evaluation.rs` line 172 at r3](https://reviewable.io/reviews/starkware-libs/stwo/463#-NtUizRrBL7r_JY4lrB5:-NtUizRrBL7r_JY4lrB6:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/4dc88e93af17a77c7932698d546c42a695a96900/src/core/air/evaluation.rs#L172)):*
> ```XML
>                 cols: values.cols.map(|c| {
>                     CPUCircleEvaluation::<_, BitReversedOrder>::new(
>                         CanonicCoset::new(log_size as u32).circle_domain(),
> ```





_Suggestion:_
```XML
CanonicCoset::new(log_size).circle_domain()
```
___
*[`src/core/air/evaluation.rs` line 307 at r3](https://reviewable.io/reviews/starkware-libs/stwo/463#-NtUj2Ww4To5S37RbAvW:-NtUj2Wx3okyQiRtJljQ:b-jqpkys) ([raw file](https://github.com/starkware-libs/stwo/blob/4dc88e93af17a77c7932698d546c42a695a96900/src/core/air/evaluation.rs#L307)):*
> ```XML
>         for (log_size, values) in pairs.into_iter() {
>             res = res * alpha
>                 + CPUCircleEvaluation::new(CanonicCoset::new(log_size).circle_domain(), values)
> ```

IMO keep the constraint_evaluation_domain function
and put this code inside



_Code quote:_
```XML
CanonicCoset::new(log_size).circle_domain()
```
___
*[`src/core/poly/circle/domain.rs` line 110 at r3](https://reviewable.io/reviews/starkware-libs/stwo/463#-NtUjgyqCNHkivt1iz2Q:-NtUjgyqCNHkivt1iz2R:b-bfuxx5) ([raw file](https://github.com/starkware-libs/stwo/blob/6443804265b6bcd05bcd70d8818cd3e89c5e9a83/src/core/poly/circle/domain.rs#L110)):*
> ```XML
> 
>     #[test]
>     fn test_circle_domain_iterator() {
> ```

I think that you should change this test to work with CanonicCoset circle domain.
Do we have another test for the iterator?



_Code quote:_
```XML
fn test_circle_domain_iterator() {
```
___
*[`src/fibonacci/component.rs` line 108 at r3](https://reviewable.io/reviews/starkware-libs/stwo/463#-NtUkmbe-2aAHjzB4bVi:-NtUkmbe-2aAHjzB4bVj:b-244agp) ([raw file](https://github.com/starkware-libs/stwo/blob/4dc88e93af17a77c7932698d546c42a695a96900/src/fibonacci/component.rs#L108)):*
> ```XML
>                 let res = self.step_constraint_eval_quotient_by_mask(point, &mask);
>                 accum.accumulate(bit_reverse_index(i + off, constraint_log_degree_bound), res);
>                 let res = self.boundary_constraint_eval_quotient_by_mask(point, &[mask[0]]);
> ```

I think that res should be renamed



_Code quote:_
```XML
                let res = self.step_constraint_eval_quotient_by_mask(point, &mask);
                accum.accumulate(bit_reverse_index(i + off, constraint_log_degree_bound), res);
                let res = self.boundary_constraint_eval_quotient_by_mask(point, &[mask[0]]);
```
___
*[`src/fibonacci/component.rs` line 113 at r3](https://reviewable.io/reviews/starkware-libs/stwo/463#-NtUkQnO1J3Fac34loWb:-NtUkQnO1J3Fac34loWc:bwrksyw) ([raw file](https://github.com/starkware-libs/stwo/blob/6443804265b6bcd05bcd70d8818cd3e89c5e9a83/src/fibonacci/component.rs#L113)):*
> ```XML
> 
>         // Boundary constraint.
>         let constraint_log_degree_bound = trace_domain.log_size();
> ```

Why did this code go?



_Code quote:_
```XML
        // Boundary constraint.
        let constraint_log_degree_bound = trace_domain.log_size();
```
___
*[`src/fibonacci/component.rs` line 130 at r3](https://reviewable.io/reviews/starkware-libs/stwo/463#-NtUkqSL5J0fmis6Fa1p:-NtUkqSL5J0fmis6Fa1q:bb7hquh) ([raw file](https://github.com/starkware-libs/stwo/blob/4dc88e93af17a77c7932698d546c42a695a96900/src/fibonacci/component.rs#L130)):*
> ```XML
>         let res = self
>             .boundary_constraint_eval_quotient_by_mask(point, &mask[0][..1].try_into().unwrap());
>         let constraint_log_degree_bound = self.log_size + 1;
> ```

huh?



_Code quote:_
```XML
self.log_size + 1
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/463)* status: 9 of 10 files reviewed, 6 unresolved discussions (waiting on @shaharsamocha7)

___
*[`src/core/air/evaluation.rs` line 172 at r3](https://reviewable.io/reviews/starkware-libs/stwo/463#-NtUizRrBL7r_JY4lrB5:-NtUo4X-0ViSuUccg0dU:bo5olci) ([raw file](https://github.com/starkware-libs/stwo/blob/4dc88e93af17a77c7932698d546c42a695a96900/src/core/air/evaluation.rs#L172)):*
> ```XML
>                 cols: values.cols.map(|c| {
>                     CPUCircleEvaluation::<_, BitReversedOrder>::new(
>                         CanonicCoset::new(log_size as u32).circle_domain(),
> ```

It's usize
___
*[`src/core/air/evaluation.rs` line 307 at r3](https://reviewable.io/reviews/starkware-libs/stwo/463#-NtUj2Ww4To5S37RbAvW:-NtUoJqP6gnANhUxSBRH:b-71500c) ([raw file](https://github.com/starkware-libs/stwo/blob/4dc88e93af17a77c7932698d546c42a695a96900/src/core/air/evaluation.rs#L307)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

IMO keep the constraint_evaluation_domain function
and put this code inside
</blockquote></details>

It's not the constraint evalaution domain no more. What name should I give it then?
___
*[`src/core/poly/circle/domain.rs` line 110 at r3](https://reviewable.io/reviews/starkware-libs/stwo/463#-NtUjgyqCNHkivt1iz2Q:-NtUoiqqDzsbPoyxDE4Y:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/6443804265b6bcd05bcd70d8818cd3e89c5e9a83/src/core/poly/circle/domain.rs#L110)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I think that you should change this test to work with CanonicCoset circle domain.
Do we have another test for the iterator?
</blockquote></details>

Done.
___
*[`src/fibonacci/component.rs` line 108 at r3](https://reviewable.io/reviews/starkware-libs/stwo/463#-NtUkmbe-2aAHjzB4bVi:-NtUozmQDzQ3AxKcfuBS:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/4dc88e93af17a77c7932698d546c42a695a96900/src/fibonacci/component.rs#L108)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I think that res should be renamed
</blockquote></details>

Done.
___
*[`src/fibonacci/component.rs` line 113 at r3](https://reviewable.io/reviews/starkware-libs/stwo/463#-NtUkQnO1J3Fac34loWb:-NtUolaU7ZLKB1sZfem5:b3pf4gv) ([raw file](https://github.com/starkware-libs/stwo/blob/6443804265b6bcd05bcd70d8818cd3e89c5e9a83/src/fibonacci/component.rs#L113)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why did this code go?
</blockquote></details>

The 2 constraints are now computed on the same domain
___
*[`src/fibonacci/component.rs` line 130 at r3](https://reviewable.io/reviews/starkware-libs/stwo/463#-NtUkqSL5J0fmis6Fa1p:-NtUp3d-3XO0JhlEriDK:bao4i33) ([raw file](https://github.com/starkware-libs/stwo/blob/4dc88e93af17a77c7932698d546c42a695a96900/src/fibonacci/component.rs#L130)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

huh?
</blockquote></details>

Now both constraints are computed on the same domain. These sizes should match the sizes in eval_on_domain

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/463)* status: 9 of 10 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`src/core/poly/circle/domain.rs` line 110 at r3](https://reviewable.io/reviews/starkware-libs/stwo/463#-NtUjgyqCNHkivt1iz2Q:-NtUwhDd2cWetmj7ZNJu:bewptzh) ([raw file](https://github.com/starkware-libs/stwo/blob/6443804265b6bcd05bcd70d8818cd3e89c5e9a83/src/core/poly/circle/domain.rs#L110)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Using a CanonicCoset?
Actually CanonicCoset iteration can be done in two ways (right?), so maybe the test can be better.
___
*[`src/fibonacci/component.rs` line 128 at r4](https://reviewable.io/reviews/starkware-libs/stwo/463#-NtUx9fr0o8GAJIbmHw6:-NtUx9fr0o8GAJIbmHw7:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/004de96a87f610f372de431082eaab92f23f16c6/src/fibonacci/component.rs#L128)):*
> ```XML
>         evaluation_accumulator: &mut PointEvaluationAccumulator,
>     ) {
>         let constraint_log_degree_bound = self.log_size + 1;
> ```





_Suggestion:_
```XML
let constraints_log_degree_bound = self.log_size + 1;
```
___
*[`src/fibonacci/component.rs` line 133 at r4](https://reviewable.io/reviews/starkware-libs/stwo/463#-NtUx3Rf4b1zN0qiJFi6:-NtUx3Rf4b1zN0qiJFi7:byp18fd) ([raw file](https://github.com/starkware-libs/stwo/blob/004de96a87f610f372de431082eaab92f23f16c6/src/fibonacci/component.rs#L133)):*
> ```XML
>             self.step_constraint_eval_quotient_by_mask(point, &mask[0][..].try_into().unwrap()),
>         );
>         let constraint_log_degree_bound = self.log_size + 1;
> ```

Remove



_Code quote:_
```XML
let constraint_log_degree_bound = self.log_size + 1;
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/463)* status: 6 of 10 files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7)

___
*[`src/fibonacci/component.rs` line 128 at r4](https://reviewable.io/reviews/starkware-libs/stwo/463#-NtUx9fr0o8GAJIbmHw6:-NtVDgVW3TNa8GNCCkcz:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/004de96a87f610f372de431082eaab92f23f16c6/src/fibonacci/component.rs#L128)):*
> ```XML
>         evaluation_accumulator: &mut PointEvaluationAccumulator,
>     ) {
>         let constraint_log_degree_bound = self.log_size + 1;
> ```

Done.
___
*[`src/fibonacci/component.rs` line 133 at r4](https://reviewable.io/reviews/starkware-libs/stwo/463#-NtUx3Rf4b1zN0qiJFi6:-NtVDg4eDToccP422Ra2:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/004de96a87f610f372de431082eaab92f23f16c6/src/fibonacci/component.rs#L133)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Remove
</blockquote></details>

Done.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/463#-:-NtVdGfEBZtvtNlWxiMP:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Comment by spapinistarkware** [comment]
### Merge activity

* **Mar 21, 7:23 AM EDT**: @spapinistarkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/463).

**Pull request merged**
