### PR TITLE
integrated batch inverse to cpu component 

### PR DESCRIPTION
**Pull request by ohad-agadi**
Reverse order of evaluations (#395)

integrated batch inverse to cpu fib component

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/448)

### CODE REVIEW

**Comment by ohad-starkware** [comment]
* **#448** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/448?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ohad-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/448)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @andrewmilson, @ohad-starkware, and @shaharsamocha7)

___
*[`src/fibonacci/component.rs` line 34 at r2](https://reviewable.io/reviews/starkware-libs/stwo/448#-Nsd0LCR4050QL-JeuU9:-Nsd0LCS2HbKWPFIZ-vM:bm9349l) ([raw file](https://github.com/starkware-libs/stwo/blob/e80ef0b6a1dad7d12a67da6b89fe216ca4850474/src/fibonacci/component.rs#L34)):*
> ```XML
>         point: CirclePoint<F>,
>         mask: &[F; 3],
>     ) -> F {
> ```

WDYT about keeping this a function on a single point, but it returns num,denom instead of num/denom?
And then add a wrapper that calls it in a chunk.
___
*[`src/fibonacci/component.rs` line 149 at r2](https://reviewable.io/reviews/starkware-libs/stwo/448#-Nsd0_NM1gyC8J0VcLn5:-Nsd0_NM1gyC8J0VcLn6:bpk1tjw) ([raw file](https://github.com/starkware-libs/stwo/blob/d52cd500431d4f096feee8df25be9ddde382de36/src/fibonacci/component.rs#L149)):*
> ```XML
>                         ]
>                     })
>                     .collect_vec()
> ```

Don't collect to vec, it's not efficient. You can use std::array::from_fn.

**Review by ohad-agadi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/448)* status: 0 of 15 files reviewed, 2 unresolved discussions (waiting on @andrewmilson, @shaharsamocha7, and @spapinistarkware)

___
*[`src/fibonacci/component.rs` line 34 at r2](https://reviewable.io/reviews/starkware-libs/stwo/448#-Nsd0LCR4050QL-JeuU9:-NsgvEkf8EDXbbRZLjwz:bx228yx) ([raw file](https://github.com/starkware-libs/stwo/blob/e80ef0b6a1dad7d12a67da6b89fe216ca4850474/src/fibonacci/component.rs#L34)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

WDYT about keeping this a function on a single point, but it returns num,denom instead of num/denom?
And then add a wrapper that calls it in a chunk.
</blockquote></details>

the problem with an array of tuples is that you don't get an easy column to inverse
it's the reason I think we should quotient inside backend, giving it an iterator(a generator) that produces arrays of nominators and denominators of constant size.
I improved it a bit in any case.
___
*[`src/fibonacci/component.rs` line 149 at r2](https://reviewable.io/reviews/starkware-libs/stwo/448#-Nsd0_NM1gyC8J0VcLn5:-NsgvDRWA8ZC-RCnQF0V:b4sy2au) ([raw file](https://github.com/starkware-libs/stwo/blob/d52cd500431d4f096feee8df25be9ddde382de36/src/fibonacci/component.rs#L149)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Don't collect to vec, it's not efficient. You can use std::array::from_fn.
</blockquote></details>

refactored

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/448)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @andrewmilson, @ohad-starkware, and @spapinistarkware)

___
*[`src/fibonacci/component.rs` line 45 at r3](https://reviewable.io/reviews/starkware-libs/stwo/448#-NshWGEm-t2bMUxpFvo8:-NshWGEm-t2bMUxpFvo9:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/44663720a43da6be8f50fd3ae03c0f5157c2d18e/src/fibonacci/component.rs#L45)):*
> ```XML
>     }
> 
>     fn step_consnstraint_nominator<F: ExtensionOf<BaseField>>(
> ```





_Suggestion:_
```XML
constraint
```
___
*[`src/fibonacci/component.rs` line 45 at r3](https://reviewable.io/reviews/starkware-libs/stwo/448#-NshY14MElZtJY31WgCh:-NshY14MElZtJY31WgCi:b2hbi9c) ([raw file](https://github.com/starkware-libs/stwo/blob/44663720a43da6be8f50fd3ae03c0f5157c2d18e/src/fibonacci/component.rs#L45)):*
> ```XML
>     }
> 
>     fn step_consnstraint_nominator<F: ExtensionOf<BaseField>>(
> ```

This function is way too long to read, is there some logic that could be separated to util functions?



_Code quote:_
```XML
fn step_consnstraint_nominator<F: ExtensionOf<BaseField>>(
```
___
*[`src/fibonacci/component.rs` line 72 at r3](https://reviewable.io/reviews/starkware-libs/stwo/448#-NshW_WlC4BJ-AGuwkcP:-NshW_Wm1mig_hkQvTpb:bhq55qs) ([raw file](https://github.com/starkware-libs/stwo/blob/44663720a43da6be8f50fd3ae03c0f5157c2d18e/src/fibonacci/component.rs#L72)):*
> ```XML
>         let num = self.boundary_constraint_nominator(point, mask);
>         let denom = self.boundary_constraint_denominator(point);
>         num / denom
> ```

Here we do regular inverse because the mask is small?
Generally the mask could be relatively big (>= n_columns)



_Code quote:_
```XML
num / denom
```
___
*[`src/fibonacci/component.rs` line 148 at r3](https://reviewable.io/reviews/starkware-libs/stwo/448#-NshXbonCZhFKSyNsIvY:-NshXbonCZhFKSyNsIvZ:b-u8xf6u) ([raw file](https://github.com/starkware-libs/stwo/blob/44663720a43da6be8f50fd3ae03c0f5157c2d18e/src/fibonacci/component.rs#L148)):*
> ```XML
>                 }
>             } else {
>                 for chunk in point_coset
> ```

Can you open that to two values?
point, mask or something



_Code quote:_
```XML
chunk
```
___
*[`src/fibonacci/component.rs` line 156 at r3](https://reviewable.io/reviews/starkware-libs/stwo/448#-NshWuBY0DGUZA1EipOC:-NshWuBY0DGUZA1EipOD:b-2tsbcb) ([raw file](https://github.com/starkware-libs/stwo/blob/44663720a43da6be8f50fd3ae03c0f5157c2d18e/src/fibonacci/component.rs#L156)):*
> ```XML
>                     let mut buff1: [BaseField; CPU_CHUNK_SIZE] =
>                         std::array::from_fn(|i| self.step_constraint_denominator(chunk[i].1));
>                     let mut buff2 = [BaseField::zero(); CPU_CHUNK_SIZE];
> ```

inverses_buff?



_Code quote:_
```XML
buff2
```

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/448#-:-NsmMYBRBRuc6Gnq5yVO:bnfp4nl)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @andrewmilson and @ohad-starkware)

**Review by ohad-agadi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/448)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`src/fibonacci/component.rs` line 45 at r3](https://reviewable.io/reviews/starkware-libs/stwo/448#-NshWGEm-t2bMUxpFvo8:-NsqgyhaAPdt8_vM4CPH:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/44663720a43da6be8f50fd3ae03c0f5157c2d18e/src/fibonacci/component.rs#L45)):*
> ```XML
>     }
> 
>     fn step_consnstraint_nominator<F: ExtensionOf<BaseField>>(
> ```

Done.
___
*[`src/fibonacci/component.rs` line 45 at r3](https://reviewable.io/reviews/starkware-libs/stwo/448#-NshY14MElZtJY31WgCh:-Nsqjm34D80P7m-eqqBI:bgret0n) ([raw file](https://github.com/starkware-libs/stwo/blob/44663720a43da6be8f50fd3ae03c0f5157c2d18e/src/fibonacci/component.rs#L45)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

This function is way too long to read, is there some logic that could be separated to util functions?
</blockquote></details>

splitted it to step constraint and boundary constraint accumelations
___
*[`src/fibonacci/component.rs` line 72 at r3](https://reviewable.io/reviews/starkware-libs/stwo/448#-NshW_WlC4BJ-AGuwkcP:-Nsqh7U1Azq-b_HxZOMk:b-xrsr8e) ([raw file](https://github.com/starkware-libs/stwo/blob/44663720a43da6be8f50fd3ae03c0f5157c2d18e/src/fibonacci/component.rs#L72)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Here we do regular inverse because the mask is small?
Generally the mask could be relatively big (>= n_columns)
</blockquote></details>

this is only called when the entire 
___
*[`src/fibonacci/component.rs` line 148 at r3](https://reviewable.io/reviews/starkware-libs/stwo/448#-NshXbonCZhFKSyNsIvY:-NsqhYvK29zVmUoIr1iS:b-ymm84l) ([raw file](https://github.com/starkware-libs/stwo/blob/44663720a43da6be8f50fd3ae03c0f5157c2d18e/src/fibonacci/component.rs#L148)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can you open that to two values?
point, mask or something
</blockquote></details>

no because it's an array
___
*[`src/fibonacci/component.rs` line 156 at r3](https://reviewable.io/reviews/starkware-libs/stwo/448#-NshWuBY0DGUZA1EipOC:-Nsqhje9648WZfJQ5MxE:bb7f2mf) ([raw file](https://github.com/starkware-libs/stwo/blob/44663720a43da6be8f50fd3ae03c0f5157c2d18e/src/fibonacci/component.rs#L156)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

inverses_buff?
</blockquote></details>

done

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/448)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @andrewmilson and @ohad-starkware)

___
*[`src/fibonacci/component.rs` line 103 at r4](https://reviewable.io/reviews/starkware-libs/stwo/448#-NsqmEGQ7ek17195XePb:-NsqmEGRCwlvFKSOr7A7:b9uvv1b) ([raw file](https://github.com/starkware-libs/stwo/blob/c97ddf3ab6b1c6bde3ed9708af1c2135b2f58e17/src/fibonacci/component.rs#L103)):*
> ```XML
> 
> const CPU_CHUNK_LOG_SIZE: usize = 2;
> const CPU_CHUNK_SIZE: usize = 1 << CPU_CHUNK_LOG_SIZE;
> ```

chunk is of size 4?



_Code quote:_
```XML
const CPU_CHUNK_LOG_SIZE: usize = 2;
const CPU_CHUNK_SIZE: usize = 1 << CPU_CHUNK_LOG_SIZE;
```
___
*[`src/fibonacci/component.rs` line 191 at r4](https://reviewable.io/reviews/starkware-libs/stwo/448#-NsqmbedCcWMT_MJA-41:-Nsqmbee88aIHXlaY3tr:b-hff6xw) ([raw file](https://github.com/starkware-libs/stwo/blob/c97ddf3ab6b1c6bde3ed9708af1c2135b2f58e17/src/fibonacci/component.rs#L191)):*
> ```XML
>                 {
>                     // Collect denominators and inverse.
>                     let mut buff1: [BaseField; CPU_CHUNK_SIZE] =
> ```

rename?



_Code quote:_
```XML
buff1
```
___
*[`src/fibonacci/component.rs` line 195 at r4](https://reviewable.io/reviews/starkware-libs/stwo/448#-Nsqmjjr6T7IgLkDmgsV:-Nsqmjjs12lQszzAjfCY:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/c97ddf3ab6b1c6bde3ed9708af1c2135b2f58e17/src/fibonacci/component.rs#L195)):*
> ```XML
>                     let mut inverses_buff = [BaseField::zero(); CPU_CHUNK_SIZE];
>                     BaseField::batch_inverse(&buff1, &mut inverses_buff);
>                     // Collect nominators.
> ```





_Suggestion:_
```XML
// Collect numerators.
```
___
*[`src/fibonacci/component.rs` line 198 at r4](https://reviewable.io/reviews/starkware-libs/stwo/448#-NsqmoPc0QfivFb-ES0K:-NsqmoPc0QfivFb-ES0L:b-q2q8oq) ([raw file](https://github.com/starkware-libs/stwo/blob/c97ddf3ab6b1c6bde3ed9708af1c2135b2f58e17/src/fibonacci/component.rs#L198)):*
> ```XML
>                     buff1 = std::array::from_fn(|i| {
>                         self.step_constraint_nominator(
>                             chunk[i].1,
> ```

Can we open here chunk[i] to two values? I want them to have names.
WDYT?



_Code quote:_
```XML
chunk[i].1
```
___
*[`src/fibonacci/component.rs` line 246 at r4](https://reviewable.io/reviews/starkware-libs/stwo/448#-Nsqn4kEClXulExfPZwp:-Nsqn4kEClXulExfPZwq:b-y5x4tj) ([raw file](https://github.com/starkware-libs/stwo/blob/c97ddf3ab6b1c6bde3ed9708af1c2135b2f58e17/src/fibonacci/component.rs#L246)):*
> ```XML
>                     accum.accumulate(bit_reverse_index(i + off, constraint_log_degree_bound), res);
>                 }
>             } else {
> ```

Same changes here.
Can we reutilize the code from before? It is very similar



_Code quote:_
```XML
} else {
```

**Review by ohad-agadi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/448)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`src/fibonacci/component.rs` line 103 at r4](https://reviewable.io/reviews/starkware-libs/stwo/448#-NsqmEGQ7ek17195XePb:-NsqnfGlB0sd4wQIP-hV:b-n9tkhd) ([raw file](https://github.com/starkware-libs/stwo/blob/c97ddf3ab6b1c6bde3ed9708af1c2135b2f58e17/src/fibonacci/component.rs#L103)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

chunk is of size 4?
</blockquote></details>

changed
___
*[`src/fibonacci/component.rs` line 195 at r4](https://reviewable.io/reviews/starkware-libs/stwo/448#-Nsqmjjr6T7IgLkDmgsV:-NsrAkYD-NjE81zg411X:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/c97ddf3ab6b1c6bde3ed9708af1c2135b2f58e17/src/fibonacci/component.rs#L195)):*
> ```XML
>                     let mut inverses_buff = [BaseField::zero(); CPU_CHUNK_SIZE];
>                     BaseField::batch_inverse(&buff1, &mut inverses_buff);
>                     // Collect nominators.
> ```

Done.
___
*[`src/fibonacci/component.rs` line 198 at r4](https://reviewable.io/reviews/starkware-libs/stwo/448#-NsqmoPc0QfivFb-ES0K:-NsrCZCm1v1XmQ60w6TT:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/c97ddf3ab6b1c6bde3ed9708af1c2135b2f58e17/src/fibonacci/component.rs#L198)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can we open here chunk[i] to two values? I want them to have names.
WDYT?
</blockquote></details>

Done.
___
*[`src/fibonacci/component.rs` line 246 at r4](https://reviewable.io/reviews/starkware-libs/stwo/448#-Nsqn4kEClXulExfPZwp:-NsrCZuv66pufSo5L4jl:b-jyzwqr) ([raw file](https://github.com/starkware-libs/stwo/blob/c97ddf3ab6b1c6bde3ed9708af1c2135b2f58e17/src/fibonacci/component.rs#L246)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Same changes here.
Can we reutilize the code from before? It is very similar
</blockquote></details>

I tried to share the quotienting part, but the denom/numerator functions for step constraint have different signatures than the boundary ones. I'm thinking the solution is having structs that implement  some 'ConstraitGen' traits , but I'm not sure it will be shorter.for now,  can this be a Todo?

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/448)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @andrewmilson and @ohad-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo/448#-NsrUuS3BAncUYEEgzAA:-NsrUuS3BAncUYEEgzAB:b-dzgm4z) (no related file):*
Please move all the functions to a utils.rs file in this dir.
IMO only the implementation of the component should be in this file.

___
___
*[`src/fibonacci/component.rs` line 246 at r4](https://reviewable.io/reviews/starkware-libs/stwo/448#-Nsqn4kEClXulExfPZwp:-NsrUeC55J815n0iM73M:bxatdpw) ([raw file](https://github.com/starkware-libs/stwo/blob/c97ddf3ab6b1c6bde3ed9708af1c2135b2f58e17/src/fibonacci/component.rs#L246)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

I tried to share the quotienting part, but the denom/numerator functions for step constraint have different signatures than the boundary ones. I'm thinking the solution is having structs that implement  some 'ConstraitGen' traits , but I'm not sure it will be shorter.for now,  can this be a Todo?
</blockquote></details>

maybe not a struct but rather a trait.
It can be a TODO, yes.

**Review by ohad-agadi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/448)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @andrewmilson and @shaharsamocha7)

*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo/448#-NsrUuS3BAncUYEEgzAA:-NsrWr260HfRnNralg4U:b-3q7vju) (no related file):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Please move all the functions to a utils.rs file in this dir.
IMO only the implementation of the component should be in this file.
</blockquote></details>

these are all functions that are specific to the CPUBackend component, maybe 'cpu.rs' ?

___

**Review by shaharsamocha7 — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/448)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @andrewmilson)

**Pull request merged**
