### PR TITLE
Simple mixed merkle tree

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/525)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/525?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#525** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/525?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#518** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/518?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/525)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @andrewmilson and @spapinistarkware)

___
*[`src/commitment_scheme/prover.rs` line 10 at r2](https://reviewable.io/reviews/starkware-libs/stwo/525#-Ntky_8HE3c2h3bF7T9p:-Ntky_8HE3c2h3bF7T9q:b-oposh1) ([raw file](https://github.com/starkware-libs/stwo/blob/7b36b0ec3ca7826de84a8a0cd9657336b5ffa2a7/src/commitment_scheme/prover.rs#L10)):*
> ```XML
> 
> pub struct MerkleProver<B: MerkleOps<H>, H: MerkleHasher> {
>     pub layers: Vec<Col<B, H::Hash>>,
> ```

Document (also the order)



_Code quote:_
```XML
    pub layers: Vec<Col<B, H::Hash>>,
```
___
*[`src/commitment_scheme/prover.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/stwo/525#-NtkxeEK2uJkElEnQPlA:-NtkxeEK2uJkElEnQPlB:b-h801vq) ([raw file](https://github.com/starkware-libs/stwo/blob/7b36b0ec3ca7826de84a8a0cd9657336b5ffa2a7/src/commitment_scheme/prover.rs#L13)):*
> ```XML
> }
> impl<B: MerkleOps<H>, H: MerkleHasher> MerkleProver<B, H> {
>     /// Commits to columns.
> ```

Document: Each column leaves is in the height of the length of the column



_Code quote:_
```XML
/// Commits to columns.
```
___
*[`src/commitment_scheme/prover.rs` line 51 at r2](https://reviewable.io/reviews/starkware-libs/stwo/525#-NtkyvzQ6E20YIp5Bpnx:-NtkyvzRACpqh4WbF2Xw:b-m9ayq3) ([raw file](https://github.com/starkware-libs/stwo/blob/7b36b0ec3ca7826de84a8a0cd9657336b5ffa2a7/src/commitment_scheme/prover.rs#L51)):*
> ```XML
>                 if layer.len() > 1 {
>                     witness.push(layer.at(query ^ 1));
>                 }
> ```

Remove and replace with 
```for layer in &self.layers[:-1]```



_Code quote:_
```XML
                if layer.len() > 1 {
                    witness.push(layer.at(query ^ 1));
                }
```
___
*[`src/commitment_scheme/verifier.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/stwo/525#-Ntkxn5h91lTPufHshA9:-Ntkxn5i6fvCPLxqysUd:b3wv0rj) ([raw file](https://github.com/starkware-libs/stwo/blob/7b36b0ec3ca7826de84a8a0cd9657336b5ffa2a7/src/commitment_scheme/verifier.rs#L16)):*
> ```XML
> impl<H: MerkleHasher> MerkleTreeVerifier<H> {
>     /// Verifies the decommitment of the columns.
>     /// Queries are given as indices to the largest column.
> ```

We are assuming that this is enough



_Code quote:_
```XML
    /// Queries are given as indices to the largest column.
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/525)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`src/commitment_scheme/prover.rs` line 10 at r2](https://reviewable.io/reviews/starkware-libs/stwo/525#-Ntky_8HE3c2h3bF7T9p:-Nto8XdQ1KZOTa-NgPD-:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/c1ab6847184f931812d287fc86042effcc67cac3/src/commitment_scheme/prover.rs#L10)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Document (also the order)
</blockquote></details>

Done.
___
*[`src/commitment_scheme/prover.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/stwo/525#-NtkxeEK2uJkElEnQPlA:-Nto8fGp3eB4s5JzzoJD:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/c1ab6847184f931812d287fc86042effcc67cac3/src/commitment_scheme/prover.rs#L13)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Document: Each column leaves is in the height of the length of the column
</blockquote></details>

Done.
___
*[`src/commitment_scheme/prover.rs` line 51 at r2](https://reviewable.io/reviews/starkware-libs/stwo/525#-NtkyvzQ6E20YIp5Bpnx:-Nto9vQ47MCYe7QJDGjv:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/c1ab6847184f931812d287fc86042effcc67cac3/src/commitment_scheme/prover.rs#L51)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Remove and replace with 
```for layer in &self.layers[:-1]```
</blockquote></details>

Done.
___
*[`src/commitment_scheme/verifier.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/stwo/525#-Ntkxn5h91lTPufHshA9:-NtoAnuA9y1Ns3-vywTZ:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/c1ab6847184f931812d287fc86042effcc67cac3/src/commitment_scheme/verifier.rs#L16)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

We are assuming that this is enough
</blockquote></details>

Done.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/525)* status: all files reviewed, 6 unresolved discussions (waiting on @andrewmilson and @spapinistarkware)

___
*[`src/commitment_scheme/ops.rs` line 9 at r4](https://reviewable.io/reviews/starkware-libs/stwo/525#-NtpJ3OQ00vA2RUvV-xL:-NtpJ3ORAx6RnKrMYBcp:bwwn29h) ([raw file](https://github.com/starkware-libs/stwo/blob/16a10c7868c61fd6d516d89cb72af20b7cfdefee/src/commitment_scheme/ops.rs#L9)):*
> ```XML
>     /// The node may or may not need to hash 2 hashes from the previous layer - depending if it is a
>     /// leaf or not.
>     /// In addition, the node may have extra column values that need to be hashed.
> ```

How did ohad describe that as well?



_Code quote:_
```XML
    /// Hashes a single Merkle node.
    /// The node may or may not need to hash 2 hashes from the previous layer - depending if it is a
    /// leaf or not.
    /// In addition, the node may have extra column values that need to be hashed.
```
___
*[`src/commitment_scheme/prover.rs` line 14 at r3](https://reviewable.io/reviews/starkware-libs/stwo/525#-Ntom828CVI1_r9mywp5:-Ntom828CVI1_r9mywp6:bz6if7) ([raw file](https://github.com/starkware-libs/stwo/blob/027ceda689b2008714b6be2744d784f2654520cc/src/commitment_scheme/prover.rs#L14)):*
> ```XML
>     /// The last layer is the root.
>     /// Layer n holds the 2^n hashes of the previous layer if exists, and all the columns of size
>     /// 2^n.
> ```

How did Ohad described that?



_Code quote:_
```XML
    /// Layer n holds the 2^n hashes of the previous layer if exists, and all the columns of size
    /// 2^n.
```
___
*[`src/commitment_scheme/verifier.rs` line 21 at r3](https://reviewable.io/reviews/starkware-libs/stwo/525#-NtonyGA9VGWp7Z2ejnE:-NtonyGA9VGWp7Z2ejnF:b5a43wv) ([raw file](https://github.com/starkware-libs/stwo/blob/027ceda689b2008714b6be2744d784f2654520cc/src/commitment_scheme/verifier.rs#L21)):*
> ```XML
>     ///
>     /// * `queries` - A vector of indices representing the queries to the largest column. This is
>     ///   assumed to be sufficient for our use case, though it could be extended to support queries
> ```

for bit reversed commitments



_Code quote:_
```XML
for our use case
```
___
*[`src/commitment_scheme/verifier.rs` line 79 at r4](https://reviewable.io/reviews/starkware-libs/stwo/525#-NtpK_fz0bZVXG8JKi0v:-NtpK_fz0bZVXG8JKi0w:b-jimjls) ([raw file](https://github.com/starkware-libs/stwo/blob/16a10c7868c61fd6d516d89cb72af20b7cfdefee/src/commitment_scheme/verifier.rs#L79)):*
> ```XML
> }
> 
> struct MerkleVerifier<H: MerkleHasher> {
> ```

Document



_Code quote:_
```XML
struct MerkleVerifier<H: MerkleHasher> {
```
___
*[`src/commitment_scheme/verifier.rs` line 82 at r4](https://reviewable.io/reviews/starkware-libs/stwo/525#-NtpMN3B5rpRyQDlycHB:-NtpMN3B5rpRyQDlycHC:b4hpnz5) ([raw file](https://github.com/starkware-libs/stwo/blob/16a10c7868c61fd6d516d89cb72af20b7cfdefee/src/commitment_scheme/verifier.rs#L82)):*
> ```XML
>     witness: std::vec::IntoIter<<H as MerkleHasher>::Hash>,
>     column_values: Peekable<std::vec::IntoIter<(u32, Vec<BaseField>)>>,
>     layer_column_values: Vec<std::vec::IntoIter<BaseField>>,
> ```

document all



_Code quote:_
```XML
    witness: std::vec::IntoIter<<H as MerkleHasher>::Hash>,
    column_values: Peekable<std::vec::IntoIter<(u32, Vec<BaseField>)>>,
    layer_column_values: Vec<std::vec::IntoIter<BaseField>>,
```
___
*[`src/commitment_scheme/verifier.rs` line 162 at r4](https://reviewable.io/reviews/starkware-libs/stwo/525#-NtpLyNTA-SRiYEXCHxn:-NtpLyNTA-SRiYEXCHxo:b2p0uf7) ([raw file](https://github.com/starkware-libs/stwo/blob/16a10c7868c61fd6d516d89cb72af20b7cfdefee/src/commitment_scheme/verifier.rs#L162)):*
> ```XML
>         children_hashes: ChildrenHashesAtQuery<H>,
>     ) -> Result<H::Hash, MerkleVerificationError> {
>         let hashes_part = children_hashes
> ```

Read witness from decommitment if not already known.



_Code quote:_
```XML
let hashes_part = children_hashes
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/525)* status: all files reviewed, 5 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`src/commitment_scheme/ops.rs` line 9 at r4](https://reviewable.io/reviews/starkware-libs/stwo/525#-NtpJ3OQ00vA2RUvV-xL:-NtpSAzJ3vpiEtogX6Sy:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/16a10c7868c61fd6d516d89cb72af20b7cfdefee/src/commitment_scheme/ops.rs#L9)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

How did ohad describe that as well?
</blockquote></details>

Done.
___
*[`src/commitment_scheme/prover.rs` line 14 at r3](https://reviewable.io/reviews/starkware-libs/stwo/525#-Ntom828CVI1_r9mywp5:-NtpSP4G7ivkyELhEoEW:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/027ceda689b2008714b6be2744d784f2654520cc/src/commitment_scheme/prover.rs#L14)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

How did Ohad described that?
</blockquote></details>

Done.
___
*[`src/commitment_scheme/verifier.rs` line 79 at r4](https://reviewable.io/reviews/starkware-libs/stwo/525#-NtpK_fz0bZVXG8JKi0v:-NtpT64103PtXTuCfmQS:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/16a10c7868c61fd6d516d89cb72af20b7cfdefee/src/commitment_scheme/verifier.rs#L79)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Document
</blockquote></details>

Done.
___
*[`src/commitment_scheme/verifier.rs` line 82 at r4](https://reviewable.io/reviews/starkware-libs/stwo/525#-NtpMN3B5rpRyQDlycHB:-NtpT6Nt3j9kg1QqDGt-:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/16a10c7868c61fd6d516d89cb72af20b7cfdefee/src/commitment_scheme/verifier.rs#L82)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

document all
</blockquote></details>

Done.
___
*[`src/commitment_scheme/verifier.rs` line 162 at r4](https://reviewable.io/reviews/starkware-libs/stwo/525#-NtpLyNTA-SRiYEXCHxn:-NtpTXhxEy0LKXg_W-7f:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/16a10c7868c61fd6d516d89cb72af20b7cfdefee/src/commitment_scheme/verifier.rs#L162)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Read witness from decommitment if not already known.
</blockquote></details>

Done.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/525)* status: all files reviewed, 2 unresolved discussions (waiting on @andrewmilson and @spapinistarkware)

___
*[`src/commitment_scheme/ops.rs` line 8 at r5](https://reviewable.io/reviews/starkware-libs/stwo/525#-NtpzD5kAHzYV8y9UDpa:-NtpzD5kAHzYV8y9UDpb:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/5db48f05ae05dba6e147e21fd43c1983d93dfd3e/src/commitment_scheme/ops.rs#L8)):*
> ```XML
> /// "[]" denotes optional values.
> /// The largest Merkle layer has no left and right child hashes. The rest of the layers have
> /// children hases
> ```





_Suggestion:_
```XML
/// The largest Merkle layer has no left and right child hashes. The rest of the layers have
/// children hashes
```
___
*[`src/commitment_scheme/verifier.rs` line 79 at r5](https://reviewable.io/reviews/starkware-libs/stwo/525#-NtpznM8AChCqD0rc9fV:-NtpznM986_SWmCu_4iC:b-sok57c) ([raw file](https://github.com/starkware-libs/stwo/blob/5db48f05ae05dba6e147e21fd43c1983d93dfd3e/src/commitment_scheme/verifier.rs#L79)):*
> ```XML
> }
> 
> /// A helper struct for verifying a [Decommitment].
> ```

Rename to MerkleDecommitment



_Suggestion:_
```XML
/// A helper struct for verifying a [MerkleDecommitment].
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/525)* status: all files reviewed, 2 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`src/commitment_scheme/ops.rs` line 8 at r5](https://reviewable.io/reviews/starkware-libs/stwo/525#-NtpzD5kAHzYV8y9UDpa:-Ntq-eJa8KXbeBxc-TnB:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/5db48f05ae05dba6e147e21fd43c1983d93dfd3e/src/commitment_scheme/ops.rs#L8)):*
> ```XML
> /// "[]" denotes optional values.
> /// The largest Merkle layer has no left and right child hashes. The rest of the layers have
> /// children hases
> ```

Done.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/525)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`src/commitment_scheme/verifier.rs` line 79 at r5](https://reviewable.io/reviews/starkware-libs/stwo/525#-NtpznM8AChCqD0rc9fV:-NttIGkdEjRWNsPlfF-j:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/5db48f05ae05dba6e147e21fd43c1983d93dfd3e/src/commitment_scheme/verifier.rs#L79)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Rename to MerkleDecommitment
</blockquote></details>

Done.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/525#-:-NttTIBk30Sj3kgnqUtm:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @andrewmilson)

**Pull request merged**
