### PR TITLE
Remove InteractionElements LookupValues and trace_generation

### PR DESCRIPTION
**Pull request by shaharsamocha7**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/812)

### CODE REVIEW

**Comment by shaharsamocha7** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/812?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#812** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/812?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#811** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/811?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#809** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/809?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @shaharsamocha7 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 12 of 13 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/812#-:-O5Ic0R53TJ6BcrsURo3:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/812)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/812)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 10 of 13 files at r1, 1 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/812#-:-O5SF-0m9UoD7EK8U2bY:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Review by alonh5 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/812)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/812)* status: all files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`crates/prover/src/trace_generation/prove.rs` line 1 at r6](https://reviewable.io/reviews/starkware-libs/stwo/812#-O5StpSYDcsq0zwTSiTy:-O5StpSYDcsq0zwTSiTz:b-dbicio) ([raw file](https://github.com/starkware-libs/stwo/blob/fd1a9ff099fdf67b8117215edcc39125b53415f5/crates/prover/src/trace_generation/prove.rs#L1)):*
> ```XML
> use itertools::Itertools;
> ```

This file should be deleted no?

**Review by shaharsamocha7 — COMMENTED** [review]
> Reviewed 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/812)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @alonh5)

**Review by shaharsamocha7 — COMMENTED** [review]
> Reviewed 1 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/812)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

**Review by andrewmilson — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/812#-:-O5TBdFK42ufaNdW-oSx:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Pull request merged**
