### PR TITLE
Poseidon merkle hasher

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/657)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/657?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#657** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/657?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#655** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/655?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ohad-agadi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/657)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/core/vcs/poseidon252_merkle.rs` line 19 at r2](https://reviewable.io/reviews/starkware-libs/stwo/657#-O-0eDtrEep4Oy7AefC5:-O-0eDtrEep4Oy7AefC6:b-wqe2sg) ([raw file](https://github.com/starkware-libs/stwo/blob/deda0fed52136c6fc53c5772e29e8cfcb6002bdf/crates/prover/src/core/vcs/poseidon252_merkle.rs#L19)):*
> ```XML
>         column_values: &[BaseField],
>     ) -> Self::Hash {
>         let mut values = vec![];
> ```

values_len = column_values.len().ceil_div(8) + 2
values = vec::with_capcity(...)
___
*[`crates/prover/src/core/vcs/poseidon252_merkle.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/stwo/657#-O-0glTg9lAe07IhLhgI:-O-0glTg9lAe07IhLhgJ:b13hmgw) ([raw file](https://github.com/starkware-libs/stwo/blob/deda0fed52136c6fc53c5772e29e8cfcb6002bdf/crates/prover/src/core/vcs/poseidon252_merkle.rs#L24)):*
> ```XML
>             values.push(right);
>         }
>         let rem = 7 - ((column_values.len() + 7) % 8);
> ```

document 
___
*[`crates/prover/src/core/vcs/poseidon252_merkle.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/stwo/657#-O-0fFzQ-nTBG-CZFR0f:-O-0fFzQ-nTBG-CZFR0g:b-emdgyp) ([raw file](https://github.com/starkware-libs/stwo/blob/deda0fed52136c6fc53c5772e29e8cfcb6002bdf/crates/prover/src/core/vcs/poseidon252_merkle.rs#L25)):*
> ```XML
>         }
>         let rem = 7 - ((column_values.len() + 7) % 8);
>         let padded_values = column_values
> ```

consider avoiding the copy with .remainder(). it does make the code ugly. non-blocking.
___
*[`crates/prover/src/core/vcs/poseidon252_merkle.rs` line 158 at r2](https://reviewable.io/reviews/starkware-libs/stwo/657#-O-0k8pcAvZs2eVXxc3m:-O-0k8pcAvZs2eVXxc3n:b-qdumvl) ([raw file](https://github.com/starkware-libs/stwo/blob/deda0fed52136c6fc53c5772e29e8cfcb6002bdf/crates/prover/src/core/vcs/poseidon252_merkle.rs#L158)):*
> ```XML
> 
>     #[test]
>     fn test_merkle_witness_too_long() {
> ```

move next to witness_too_long

**Review by shaharsamocha7 — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/657)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/657)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @ohad-starkware and @spapinistarkware)

___
*[`crates/prover/src/core/vcs/poseidon252_merkle.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/stwo/657#-O-FQB4sBuFk_pi2fQWD:-O-FQB4tE_eWbFy1sY0F:byfm1y5) ([raw file](https://github.com/starkware-libs/stwo/blob/deda0fed52136c6fc53c5772e29e8cfcb6002bdf/crates/prover/src/core/vcs/poseidon252_merkle.rs#L24)):*
> ```XML
>             values.push(right);
>         }
>         let rem = 7 - ((column_values.len() + 7) % 8);
> ```

Make a constant for this 8



_Code quote:_
```XML
8
```

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/657)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @ohad-starkware and @spapinistarkware)

___
*[`crates/prover/src/core/vcs/poseidon252_merkle.rs` line 35 at r3](https://reviewable.io/reviews/starkware-libs/stwo/657#-O-VBiz73VDBUmQJjRo_:-O-VBiz73VDBUmQJjRoa:b-ewqydh) ([raw file](https://github.com/starkware-libs/stwo/blob/168138a8f2fe9a15b5af156464feec81243f7be8/crates/prover/src/core/vcs/poseidon252_merkle.rs#L35)):*
> ```XML
>             .copied()
>             .chain(std::iter::repeat(BaseField::zero()).take(padding_length));
>         for chunk in padded_values.array_chunks::<8>() {
> ```

can you rename ELS_IN_BLOCK to ELEMENTS_IN_BLOCK?



_Suggestion:_
```XML
for chunk in padded_values.array_chunks::<ELS_IN_BLOCK>() {
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/657)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`crates/prover/src/core/vcs/poseidon252_merkle.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/stwo/657#-O-0glTg9lAe07IhLhgI:-O-Uvkl65pbwNaG6DYt8:b-1cpayq) ([raw file](https://github.com/starkware-libs/stwo/blob/deda0fed52136c6fc53c5772e29e8cfcb6002bdf/crates/prover/src/core/vcs/poseidon252_merkle.rs#L24)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

document
</blockquote></details>

Is this better?
___
*[`crates/prover/src/core/vcs/poseidon252_merkle.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/stwo/657#-O-FQB4sBuFk_pi2fQWD:-O-UvDplCZ_1I8Y-SSrv:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/deda0fed52136c6fc53c5772e29e8cfcb6002bdf/crates/prover/src/core/vcs/poseidon252_merkle.rs#L24)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Make a constant for this 8
</blockquote></details>

Done.
___
*[`crates/prover/src/core/vcs/poseidon252_merkle.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/stwo/657#-O-0fFzQ-nTBG-CZFR0f:-O-UvU-TAGHM2ksH2_xk:bdit6ni) ([raw file](https://github.com/starkware-libs/stwo/blob/deda0fed52136c6fc53c5772e29e8cfcb6002bdf/crates/prover/src/core/vcs/poseidon252_merkle.rs#L25)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

consider avoiding the copy with .remainder(). it does make the code ugly. non-blocking.
</blockquote></details>

There isn't a copy here really, I believe. Also, this won't run in the optimized simd impl (which doesn't exist yet).
___
*[`crates/prover/src/core/vcs/poseidon252_merkle.rs` line 158 at r2](https://reviewable.io/reviews/starkware-libs/stwo/657#-O-0k8pcAvZs2eVXxc3m:-O-UwhVfAZvZ1wVdFE-x:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/deda0fed52136c6fc53c5772e29e8cfcb6002bdf/crates/prover/src/core/vcs/poseidon252_merkle.rs#L158)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

move next to witness_too_long
</blockquote></details>

Done.

**Review by ohad-agadi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/657#-:-O-j7GmbAZ4ejqva15g8:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/prover/src/core/vcs/poseidon252_merkle.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/stwo/657#-O-0fFzQ-nTBG-CZFR0f:-O-j6n359nPZQrMR5eyq:bb7ohn6) ([raw file](https://github.com/starkware-libs/stwo/blob/deda0fed52136c6fc53c5772e29e8cfcb6002bdf/crates/prover/src/core/vcs/poseidon252_merkle.rs#L25)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

There isn't a copy here really, I believe. Also, this won't run in the optimized simd impl (which doesn't exist yet).
</blockquote></details>

sgtm

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/657)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`crates/prover/src/core/vcs/poseidon252_merkle.rs` line 35 at r3](https://reviewable.io/reviews/starkware-libs/stwo/657#-O-VBiz73VDBUmQJjRo_:-O-powGR5GbQfzIg7MXm:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/168138a8f2fe9a15b5af156464feec81243f7be8/crates/prover/src/core/vcs/poseidon252_merkle.rs#L35)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

can you rename ELS_IN_BLOCK to ELEMENTS_IN_BLOCK?
</blockquote></details>

Done.

**Review by ohad-agadi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/657#-:-O1GMEk3CAke6rVHCM6O:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

___
*[`crates/prover/src/core/channel/poseidon252.rs` line 70 at r4](https://reviewable.io/reviews/starkware-libs/stwo/657#-O1GKkjC0C74PGR8lZOz:-O1GKkjC0C74PGR8lZP-:bunp8k7) ([raw file](https://github.com/starkware-libs/stwo/blob/bf32a1f504774fb014e4289d89cb65cb4f3705f9/crates/prover/src/core/channel/poseidon252.rs#L70)):*
> ```XML
>     fn mix_felts(&mut self, felts: &[SecureField]) {
>         let shift = (1u64 << 31).into();
>         let mut res = vec![self.digest];
> ```

consider reserving
___
*[`crates/prover/src/core/channel/poseidon252.rs` line 71 at r4](https://reviewable.io/reviews/starkware-libs/stwo/657#-O1GLmpt3E1QBmDcRr3B:-O1GLmpt3E1QBmDcRr3C:b45h) ([raw file](https://github.com/starkware-libs/stwo/blob/bf32a1f504774fb014e4289d89cb65cb4f3705f9/crates/prover/src/core/channel/poseidon252.rs#L71)):*
> ```XML
>         let shift = (1u64 << 31).into();
>         let mut res = vec![self.digest];
>         for chunk in felts.chunks(2) {
> ```





_Suggestion:_
```XML
felts.array_chunks::<2>()
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/657)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

___
*[`crates/prover/src/core/channel/poseidon252.rs` line 71 at r4](https://reviewable.io/reviews/starkware-libs/stwo/657#-O1GLmpt3E1QBmDcRr3B:-O1HARlU5XjQn-tuPcmh:bc4bvbv) ([raw file](https://github.com/starkware-libs/stwo/blob/bf32a1f504774fb014e4289d89cb65cb4f3705f9/crates/prover/src/core/channel/poseidon252.rs#L71)):*
> ```XML
>         let shift = (1u64 << 31).into();
>         let mut res = vec![self.digest];
>         for chunk in felts.chunks(2) {
> ```

Don't wanna write extra code for the remainder

**Review by ohad-agadi — APPROVED** [review]
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/657)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
