### PR TITLE
Unite PackedBaseField with AVX M31 impl

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/414)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`src/core/backend/avx512/mod.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/stwo/414#-Ns2IAqc-nqDfJo3SQjq:-Ns2IAqc-nqDfJo3SQjr:b13hmha) ([raw file](https://github.com/starkware-libs/stwo/blob/4b09ff0609f87e4b5e4f1e601e38712e0c162116/src/core/backend/avx512/mod.rs#L74)):*
> ```XML
>         self.length
>     }
>     fn at(&self, index: usize) -> BaseField {
> ```

document.



_Code quote:_
```XML
fn at(&self, index: usize) -> BaseField {
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 2 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/414)* status: 2 of 9 files reviewed, 1 unresolved discussion (waiting on @ohad-starkware and @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/414)* status: 2 of 9 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @ohad-starkware)

___
*[`src/core/backend/avx512/mod.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/stwo/414#-Ns2IAqc-nqDfJo3SQjq:-Ns2LFjQ4V2nOKAi_5Uv:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/4b09ff0609f87e4b5e4f1e601e38712e0c162116/src/core/backend/avx512/mod.rs#L74)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

document.
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 9 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/414#-:-Ns2MET005ovHYdOiY90:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ohad-starkware)

**Pull request merged**
