### PR TITLE
Revert "removed computing line coeffs (#643)"

### PR DESCRIPTION
**Pull request by spapinistarkware**
Revert "removed computing line coeffs (#643)"

This reverts commit a150b8f75351820c027683b79e42a7ca90feef48.

Revert "integrated point vanishing in fri quotients (#619)"

This reverts commit a6eabddaf88abee1e0c051327baada989cc81c49.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/684)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
* **#685** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/685?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#684** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/684?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/684)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/core/constraints.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/stwo/684#-O0iK4XFC-ii3byMff9D:-O0iK4XG2uL3rF8yyuXp:bm6co9u) ([raw file](https://github.com/starkware-libs/stwo/blob/e33378a36e1f210b42ca13c1fbe6045e0dd60df4/crates/prover/src/core/constraints.rs#L94)):*
> ```XML
> 
> /// Evaluates the coefficients of a line between a point and its complex conjugate. Specifically,
> /// `a, b, and c, s.t. a*x + b -c*y = 0` for (x,y) being (sample.y, sample.value) and
> ```

Can we change it so the equation will be
a*x + b*y +-c = 0?

Seems more intuitive for me (non-blocking)



_Code quote:_
```XML
a*x + b -c*y = 0`
```
___
*[`crates/prover/src/core/backend/cpu/quotients.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/stwo/684#-O0iKXFjDTUH94gA3Cqm:-O0iKXFjDTUH94gA3Cqn:b-tomimj) ([raw file](https://github.com/starkware-libs/stwo/blob/e33378a36e1f210b42ca13c1fbe6045e0dd60df4/crates/prover/src/core/backend/cpu/quotients.rs#L59)):*
> ```XML
>     ) {
>         let mut numerator = SecureField::zero();
>         for ((column_index, _), (a, b, c)) in zip_eq(&sample_batch.columns_and_values, line_coeffs)
> ```

These already multiply by the constraint random element.
Can you document that or rename the variable names to contain the alpha?

We had exactly this bug here.



_Code quote:_
```XML
(a, b, c)
```
___
*[`crates/prover/src/core/backend/simd/quotients.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/stwo/684#-O0iLNw5BmIEgpU_gnBk:-O0iLNw5BmIEgpU_gnBl:byp18fd) ([raw file](https://github.com/starkware-libs/stwo/blob/e33378a36e1f210b42ca13c1fbe6045e0dd60df4/crates/prover/src/core/backend/simd/quotients.rs#L82)):*
> ```XML
>             // at sample_point and conj(sample_point) if the original polynomial had the values
>             // sample_value and conj(sample_value) at these points.
>             // TODO(AlonH): Use single point vanishing to save a multiplication.
> ```

Remove



_Code quote:_
```XML
            // TODO(AlonH): Use single point vanishing to save a multiplication.
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/684)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/prover/src/core/constraints.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/stwo/684#-O0iK4XFC-ii3byMff9D:-O0laJHw7rt5uSp_rZNv:begf3w3) ([raw file](https://github.com/starkware-libs/stwo/blob/e33378a36e1f210b42ca13c1fbe6045e0dd60df4/crates/prover/src/core/constraints.rs#L94)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can we change it so the equation will be
a*x + b*y +-c = 0?

Seems more intuitive for me (non-blocking)
</blockquote></details>

That does sound better. Let's do it in another PR.
___
*[`crates/prover/src/core/backend/cpu/quotients.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/stwo/684#-O0iKXFjDTUH94gA3Cqm:-O0l_S2o56HohULTLEbi:ba1kqlj) ([raw file](https://github.com/starkware-libs/stwo/blob/e33378a36e1f210b42ca13c1fbe6045e0dd60df4/crates/prover/src/core/backend/cpu/quotients.rs#L59)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

These already multiply by the constraint random element.
Can you document that or rename the variable names to contain the alpha?

We had exactly this bug here.
</blockquote></details>

Added in the last PR.
___
*[`crates/prover/src/core/backend/simd/quotients.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/stwo/684#-O0iLNw5BmIEgpU_gnBk:-O0l_IEQAz4ZkC5qnjOZ:b-g5c8zt) ([raw file](https://github.com/starkware-libs/stwo/blob/e33378a36e1f210b42ca13c1fbe6045e0dd60df4/crates/prover/src/core/backend/simd/quotients.rs#L82)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Remove
</blockquote></details>

This gets removed in the following PRs. Better to keep this as a pure revert PR.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/684#-:-O0mskzj-Jd8KUKrEs37:bnfp4nl)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/prover/src/core/constraints.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/stwo/684#-O0iK4XFC-ii3byMff9D:-O0msepf2Jo_B7MOwh_x:b-80z19o) ([raw file](https://github.com/starkware-libs/stwo/blob/e33378a36e1f210b42ca13c1fbe6045e0dd60df4/crates/prover/src/core/constraints.rs#L94)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

That does sound better. Let's do it in another PR.
</blockquote></details>

TODO?

**Pull request merged**
