### PR TITLE
CircleDomainBitRevIterator

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/744)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/744?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#744** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/744?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#743** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/743?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ohad-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/744)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/domain.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/stwo/744#-O2OOF0O9uJ76HQJTD-A:-O2OOF0P2wKlpvhjwe52:b-nyro4g) ([raw file](https://github.com/starkware-libs/stwo/blob/1cb8ae5e5368689ed37ca1adcd7d231274a043a3/crates/prover/src/core/backend/simd/domain.rs#L15)):*
> ```XML
>     flips: [CirclePoint<M31>; (M31_CIRCLE_LOG_ORDER - LOG_N_LANES) as usize],
> }
> impl CircleDomainBitRevIterator {
> ```

drop line
___
*[`crates/prover/src/core/backend/simd/domain.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/stwo/744#-O2OOirRDLpSEWVoEDCp:-O2OOirRDLpSEWVoEDCq:b-nyro4g) ([raw file](https://github.com/starkware-libs/stwo/blob/1cb8ae5e5368689ed37ca1adcd7d231274a043a3/crates/prover/src/core/backend/simd/domain.rs#L45)):*
> ```XML
>     }
> }
> impl Iterator for CircleDomainBitRevIterator {
> ```

drop line

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/744)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @ohad-starkware)

___
*[`crates/prover/src/core/backend/simd/domain.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/stwo/744#-O2OOF0O9uJ76HQJTD-A:-O2cbThs2C-w1Lw2_jSJ:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/1cb8ae5e5368689ed37ca1adcd7d231274a043a3/crates/prover/src/core/backend/simd/domain.rs#L15)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

drop line
</blockquote></details>

Done.
___
*[`crates/prover/src/core/backend/simd/domain.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/stwo/744#-O2OOirRDLpSEWVoEDCp:-O2cbTw77y8afN6gjekZ:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/1cb8ae5e5368689ed37ca1adcd7d231274a043a3/crates/prover/src/core/backend/simd/domain.rs#L45)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

drop line
</blockquote></details>

Done.

**Review by ohad-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/744#-:-O2ceDZU6cJabR0iVkHL:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
