### PR TITLE
Write trace and trace asserts

### PR DESCRIPTION
**Pull request by shaharsamocha7**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/542)

### CODE REVIEW

**Comment by shaharsamocha7** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/542?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#542** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/542?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#541** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/541?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#540** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/540?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @shaharsamocha7 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/542)* status: all files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`src/example_airs/wide_fibonacci/trace_gen.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/stwo/542#-NttYKiv6amifoJsy62D:-NttYKiv6amifoJsy62E:b8ftvw3) ([raw file](https://github.com/starkware-libs/stwo/blob/f94db636f1e31d8b38b035419ee138cb7012c0ba/src/example_airs/wide_fibonacci/trace_gen.rs#L8)):*
> ```XML
>     let a = private_input.a;
>     let b = private_input.b;
>     let col0 = a;
> ```

Add a TODO to try to make this a for loop, and use intermedaite variables to save computation.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/542#-:-Ntzb5Ct21Lwh7zHv_gj:bnfp4nl)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/542)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`src/example_airs/wide_fibonacci/trace_gen.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/stwo/542#-NttYKiv6amifoJsy62D:-Ntzhcn1By144vmyQYJL:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/f94db636f1e31d8b38b035419ee138cb7012c0ba/src/example_airs/wide_fibonacci/trace_gen.rs#L8)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Add a TODO to try to make this a for loop, and use intermedaite variables to save computation.
</blockquote></details>

Done.

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 2 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/542)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Comment by shaharsamocha7** [comment]
### Merge activity

* **Mar 27, 8:10 AM EDT**: @shaharsamocha7 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/542).

**Pull request merged**
