### PR TITLE
Use PackedBaseField in avx fft

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/455)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/455?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#455** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/455?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#443** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/443?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#401** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/401?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#399** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/399?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#398** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/398?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#397** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/397?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#396** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/396?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#395** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/395?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#394** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/394?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#390** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/390?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#389** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/389?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#383** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/383?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#382** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/382?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#381** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/381?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#380** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/380?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#379** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/379?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#378** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/378?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#377** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/377?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#368** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/368?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#367** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/367?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#366** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/366?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#365** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/365?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by ilyalesokhin-starkware** [comment]
*[`src/core/backend/avx512/m31.rs` line 41 at r2](https://reviewable.io/reviews/starkware-libs/stwo/455#-NsgNQ_c8F_2Croz5C_I:-NsgNQ_c8F_2Croz5C_J:bi6c6i3) ([raw file](https://github.com/starkware-libs/stwo/blob/1768412e17bf27639887ab65dc85b9da21914250/src/core/backend/avx512/m31.rs#L41)):*
> ```XML
>     }
> 
>     pub fn permute_with(self, idx: __m512i, other: Self) -> Self {
> ```

document.

condiser
adding
interleave_lower_halfs
and
interleave_upper_halfs

functions.



_Code quote:_
```XML
permute_with
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/455)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/455)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`src/core/backend/avx512/m31.rs` line 41 at r2](https://reviewable.io/reviews/starkware-libs/stwo/455#-NsgNQ_c8F_2Croz5C_I:-NslBceK7oddf56t7Au0:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/1768412e17bf27639887ab65dc85b9da21914250/src/core/backend/avx512/m31.rs#L41)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

document.

condiser
adding
interleave_lower_halfs
and
interleave_upper_halfs

functions.
</blockquote></details>

Done.

**Comment by ilyalesokhin-starkware** [comment]
*[`src/core/backend/avx512/m31.rs` line 41 at r2](https://reviewable.io/reviews/starkware-libs/stwo/455#-NsgNQ_c8F_2Croz5C_I:-NslJVei2rR_uYcatwff:b-9wglsn) ([raw file](https://github.com/starkware-libs/stwo/blob/1768412e17bf27639887ab65dc85b9da21914250/src/core/backend/avx512/m31.rs#L41)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

you didn't document permute_with, tough I guess it is no longer used.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/455)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

___
*[`src/core/backend/avx512/m31.rs` line 41 at r2](https://reviewable.io/reviews/starkware-libs/stwo/455#-NsgNQ_c8F_2Croz5C_I:-Nsluue2B_u7mK3Z_pU8:b-pgp3ca) ([raw file](https://github.com/starkware-libs/stwo/blob/1768412e17bf27639887ab65dc85b9da21914250/src/core/backend/avx512/m31.rs#L41)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

you didn't document permute_with, tough I guess it is no longer used.
</blockquote></details>

Sorry, meant to delete it.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/455#-:-NsmVdKvCptIFakyd6PP:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
