### PR TITLE
Separate cpu and avx wide fib.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/573)

### CODE REVIEW

**Comment by alonh5** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/573?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#573** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/573?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#572** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/572?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#562** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/562?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/573)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @shaharsamocha7)

___
*[`src/core/prover/mod.rs` line 122 at r2](https://reviewable.io/reviews/starkware-libs/stwo/573#-NvVqtwU4xH3lhbO8Gs9:-NvVqtwU4xH3lhbO8GsA:b8rsew0) ([raw file](https://github.com/starkware-libs/stwo/blob/32e9e84dcc3f2e201506ccc0e08eda8fce21a4dc/src/core/prover/mod.rs#L122)):*
> ```XML
> }
> 
> pub fn verify<B: Backend>(
> ```

Why do you want to support a non cpu verifier?

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/573)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`src/core/prover/mod.rs` line 122 at r2](https://reviewable.io/reviews/starkware-libs/stwo/573#-NvVqtwU4xH3lhbO8Gs9:-NwiCIEME_BgwVXZNNI8:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/32e9e84dcc3f2e201506ccc0e08eda8fce21a4dc/src/core/prover/mod.rs#L122)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Why do you want to support a non cpu verifier?
</blockquote></details>

Done.

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 6 of 8 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/573)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/573#-:-NxBmGed0Sp50PbpVa5R:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Comment by alonh5** [comment]
### Merge activity

* **May 16, 10:02 AM EDT**: @alonh5 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/573).

**Pull request merged**
