### PR TITLE
Fix FibonacciAirGenerator test.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/717)

### CODE REVIEW

**Comment by alonh5** [comment]
* **#717** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/717?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ohad-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/717)* status: 0 of 1 files reviewed, all discussions resolved

**Review by ohad-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/717)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/prover/src/examples/fibonacci/mod.rs` line 259 at r1](https://reviewable.io/reviews/starkware-libs/stwo/717#-O1QUO-RCuHehDi3DqkL:-O1QUO-RCuHehDi3DqkM:bqsp5tq) ([raw file](https://github.com/starkware-libs/stwo/blob/ca2cc49e38aa924a3bdea61107c67fde2980ccc7/crates/prover/src/examples/fibonacci/mod.rs#L259)):*
> ```XML
> 
>         let fib = Fibonacci::new(FIB_LOG_SIZE, CLAIM);
>         fib.verify(proof).unwrap();
> ```

consider



_Suggestion:_
```XML
        let channel =
            &mut Blake2sChannel::new(Blake2sHasher::hash(BaseField::into_slice(&[CLAIM])));
        let fib_air = Fibonacci::new(FIB_LOG_SIZE, CLAIM).air;
        verify(proof, &fib_air, channel).unwrap();
```

**Review by ohad-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/717)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Pull request merged**
