### PR TITLE
Add wide fib lookup step constraint.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/646)

### CODE REVIEW

**Comment by alonh5** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/646?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#646** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/646?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#644** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/644?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#642** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/642?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#639** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/639?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#638** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/638?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#637** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/637?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#636** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/636?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#634** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/634?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#633** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/633?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#631** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/631?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#582** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/582?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#589](https://github.com/starkware-libs/stwo/pull/589) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/589?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#573** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/573?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#574](https://github.com/starkware-libs/stwo/pull/574) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/574?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#572** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/572?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#562** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/562?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/646)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @shaharsamocha7)

___
*[`crates/prover/src/core/utils.rs` line 76 at r4](https://reviewable.io/reviews/starkware-libs/stwo/646#-O-psT6pCnUSNlnEB36t:-O-psT6q5eUFxrlEp-LC:b-djumbb) ([raw file](https://github.com/starkware-libs/stwo/blob/3ced4d292564c1eaf8285125e2eb57a19245b3f0/crates/prover/src/core/utils.rs#L76)):*
> ```XML
> }
> 
> pub(crate) fn circle_domain_order_to_coset_order(values: &[BaseField]) -> Vec<BaseField> {
> ```

1. Do we need these in the long term? If not, add a TODO to remove. If yes, they are currently not efficient, and seem to only do things in the CPU, and not in a backend. Also, should the oeprate on Vec, and no on Evaluation or something?

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/646)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/core/utils.rs` line 76 at r4](https://reviewable.io/reviews/starkware-libs/stwo/646#-O-psT6pCnUSNlnEB36t:-O0JFWlhBa4RL9-1RV7d:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/3ced4d292564c1eaf8285125e2eb57a19245b3f0/crates/prover/src/core/utils.rs#L76)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

1. Do we need these in the long term? If not, add a TODO to remove. If yes, they are currently not efficient, and seem to only do things in the CPU, and not in a backend. Also, should the oeprate on Vec, and no on Evaluation or something?
</blockquote></details>

Done.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r2, 2 of 3 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/646)* status: all files reviewed, 6 unresolved discussions (waiting on @alonh5 and @spapinistarkware)

___
*[`crates/prover/src/core/utils.rs` line 71 at r6](https://reviewable.io/reviews/starkware-libs/stwo/646#-O0m8ujF-qOM-ScAwbsK:-O0m8ujG0PrdoWfMQ3m5:b-eikv4s) ([raw file](https://github.com/starkware-libs/stwo/blob/3495fde0e8442252b017fc1687b644f4ae4dcf4a/crates/prover/src/core/utils.rs#L71)):*
> ```XML
>         prev_index = (prev_index + half_size - 1) % half_size;
>     } else {
>         prev_index = ((prev_index + 1) % half_size) + half_size;
> ```

Does it work for constraint degree > 2?
I think that you need the extension degree as well



_Suggestion:_
```XML
        prev_index = ((prev_index + extension_degree / 2) % half_size) + half_size;
```
___
*[`crates/prover/src/examples/wide_fibonacci/component.rs` line 159 at r6](https://reviewable.io/reviews/starkware-libs/stwo/646#-O0mAd9V-R95mRVuOG-C:-O0mAd9V-R95mRVuOG-D:bsq8sz3) ([raw file](https://github.com/starkware-libs/stwo/blob/3495fde0e8442252b017fc1687b644f4ae4dcf4a/crates/prover/src/examples/wide_fibonacci/component.rs#L159)):*
> ```XML
>             .map(|eval| {
>                 let coset = CanonicCoset::new(trace[0].domain.log_size());
>                 CpuCircleEvaluation::new_canonical_ordered(coset, eval)
> ```

What is this change? Adding bit reverse?



_Code quote:_
```XML
                let coset = CanonicCoset::new(trace[0].domain.log_size());
                CpuCircleEvaluation::new_canonical_ordered(coset, eval)
```
___
*[`crates/prover/src/examples/wide_fibonacci/constraint_eval.rs` line 137 at r6](https://reviewable.io/reviews/starkware-libs/stwo/646#-O0mBVq5DFr_xpprUKcU:-O0mBVq5DFr_xpprUKcV:b-1lsjf5) ([raw file](https://github.com/starkware-libs/stwo/blob/3495fde0e8442252b017fc1687b644f4ae4dcf4a/crates/prover/src/examples/wide_fibonacci/constraint_eval.rs#L137)):*
> ```XML
>     }
> 
>     fn evaluate_lookup_step_constraints(
> ```

Let's add a TODO to try to simplify this function (moving parts to utility functions)
not for this pr



_Code quote:_
```XML
    fn evaluate_lookup_step_constraints(
```
___
*[`crates/prover/src/examples/wide_fibonacci/mod.rs` line 153 at r6](https://reviewable.io/reviews/starkware-libs/stwo/646#-O0mCi612m2DzQ-UQ5tU:-O0mCi612m2DzQ-UQ5tV:b-qg7dx7) ([raw file](https://github.com/starkware-libs/stwo/blob/3495fde0e8442252b017fc1687b644f4ae4dcf4a/crates/prover/src/examples/wide_fibonacci/mod.rs#L153)):*
> ```XML
>             .into_iter()
>             .map(|eval| CpuCircleEvaluation::new_canonical_ordered(trace_domain, eval))
>             .collect_vec();
> ```

This applies bit reverse on the entire trace.
It would be better to just bit reverse the lookup column?



_Code quote:_
```XML
        let trace = trace_values
            .into_iter()
            .map(|eval| CpuCircleEvaluation::new_canonical_ordered(trace_domain, eval))
            .collect_vec();
```
___
*[`crates/prover/src/examples/wide_fibonacci/trace_gen.rs` line 50 at r6](https://reviewable.io/reviews/starkware-libs/stwo/646#-O0mD9vj4-mKddqJ89Sb:-O0mD9vj4-mKddqJ89Sc:b-kx7yqt) ([raw file](https://github.com/starkware-libs/stwo/blob/3495fde0e8442252b017fc1687b644f4ae4dcf4a/crates/prover/src/examples/wide_fibonacci/trace_gen.rs#L50)):*
> ```XML
>             circle_domain_order_to_coset_order(column)
>         })
>         .collect_vec();
> ```

Add a TODO, the better thing to do is to bit reverse only the expressions that relevant for the lookup
instead of bit reversing the entire trace which can be expensive



_Code quote:_
```XML
    let natural_ordered_trace = input_trace
        .iter_mut()
        .map(|column| {
            bit_reverse(column);
            circle_domain_order_to_coset_order(column)
        })
        .collect_vec();
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/646)* status: all files reviewed, 6 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/core/utils.rs` line 71 at r6](https://reviewable.io/reviews/starkware-libs/stwo/646#-O0m8ujF-qOM-ScAwbsK:-O0mGsGQD10Q1uiAagNu:b-flm6be) ([raw file](https://github.com/starkware-libs/stwo/blob/3495fde0e8442252b017fc1687b644f4ae4dcf4a/crates/prover/src/core/utils.rs#L71)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Does it work for constraint degree > 2?
I think that you need the extension degree as well
</blockquote></details>

Yes I wrote it in the documentation, but i generalized it now.
___
*[`crates/prover/src/examples/wide_fibonacci/component.rs` line 159 at r6](https://reviewable.io/reviews/starkware-libs/stwo/646#-O0mAd9V-R95mRVuOG-C:-O0mIlMdEfYjW903uflJ:b-do5kvx) ([raw file](https://github.com/starkware-libs/stwo/blob/3495fde0e8442252b017fc1687b644f4ae4dcf4a/crates/prover/src/examples/wide_fibonacci/component.rs#L159)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

What is this change? Adding bit reverse?
</blockquote></details>

It reorders it in circle domain order and also bit reverses. This is needed for constraints between rows to be consistent.
___
*[`crates/prover/src/examples/wide_fibonacci/constraint_eval.rs` line 137 at r6](https://reviewable.io/reviews/starkware-libs/stwo/646#-O0mBVq5DFr_xpprUKcU:-O0mHGPV5J-U4y8__FkA:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/3495fde0e8442252b017fc1687b644f4ae4dcf4a/crates/prover/src/examples/wide_fibonacci/constraint_eval.rs#L137)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Let's add a TODO to try to simplify this function (moving parts to utility functions)
not for this pr
</blockquote></details>

Done.
___
*[`crates/prover/src/examples/wide_fibonacci/mod.rs` line 153 at r6](https://reviewable.io/reviews/starkware-libs/stwo/646#-O0mCi612m2DzQ-UQ5tU:-O0mPIe2B-VzxbinFTU3:b9m5l13) ([raw file](https://github.com/starkware-libs/stwo/blob/3495fde0e8442252b017fc1687b644f4ae4dcf4a/crates/prover/src/examples/wide_fibonacci/mod.rs#L153)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

This applies bit reverse on the entire trace.
It would be better to just bit reverse the lookup column?
</blockquote></details>

I need to turn the trace order into circle domain and bit reverse for the same reason above.
___
*[`crates/prover/src/examples/wide_fibonacci/trace_gen.rs` line 50 at r6](https://reviewable.io/reviews/starkware-libs/stwo/646#-O0mD9vj4-mKddqJ89Sb:-O0mIR_50lm_fNifobHp:bv05yj7) ([raw file](https://github.com/starkware-libs/stwo/blob/3495fde0e8442252b017fc1687b644f4ae4dcf4a/crates/prover/src/examples/wide_fibonacci/trace_gen.rs#L50)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Add a TODO, the better thing to do is to bit reverse only the expressions that relevant for the lookup
instead of bit reversing the entire trace which can be expensive
</blockquote></details>

There's already a TODO to remove the cloning of the whole trace for this calculation. Only the relevant columns should be passed here after that change so this will stay the same. I edited to TODO to be clearer.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/646#-:-O0msX2V60xHual_yw_W:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5 and @spapinistarkware)

___
*[`crates/prover/src/examples/wide_fibonacci/mod.rs` line 153 at r6](https://reviewable.io/reviews/starkware-libs/stwo/646#-O0mCi612m2DzQ-UQ5tU:-O0mrOIF5O0zVnz4WWV0:bcub5ll) ([raw file](https://github.com/starkware-libs/stwo/blob/3495fde0e8442252b017fc1687b644f4ae4dcf4a/crates/prover/src/examples/wide_fibonacci/mod.rs#L153)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I need to turn the trace order into circle domain and bit reverse for the same reason above.
</blockquote></details>

ok but we can also apply the todo here in order to reverse only the columns that are relevant for the lookup, right?

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 3 of 7 files at r2, 1 of 3 files at r5, 1 of 2 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/646)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/646)* status: all files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`crates/prover/src/examples/wide_fibonacci/mod.rs` line 153 at r6](https://reviewable.io/reviews/starkware-libs/stwo/646#-O0mCi612m2DzQ-UQ5tU:-O0mtbBdBxDCkR2XuG3q:b-c5z9ld) ([raw file](https://github.com/starkware-libs/stwo/blob/3495fde0e8442252b017fc1687b644f4ae4dcf4a/crates/prover/src/examples/wide_fibonacci/mod.rs#L153)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

ok but we can also apply the todo here in order to reverse only the columns that are relevant for the lookup, right?
</blockquote></details>

First of all this is a test just making sure you noticed. Secondly in the actual trace I don't think we can only change the order of some of the columns because that would mess up the constraints in the same row.

**Review by shaharsamocha7 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/646)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Comment by alonh5** [comment]
### Merge activity

* **Jul 2, 8:47 AM EDT**: @alonh5 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/646).

**Pull request merged**
