### PR TITLE
Configure wide fib.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/562)

### CODE REVIEW

**Comment by alonh5** [comment]
* **#562** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/562?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/562)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

___
*[`src/examples/wide_fibonacci/structs.rs` line 1 at r3](https://reviewable.io/reviews/starkware-libs/stwo/562#-NvVng-E8FsAjHm6VLOO:-NvVng-E8FsAjHm6VLOP:bsvxz4g) ([raw file](https://github.com/starkware-libs/stwo/blob/a4b4c44c7299f62a264be74c4be80e6704644242/src/examples/wide_fibonacci/structs.rs#L1)):*
> ```XML
> use itertools::Itertools;
> ```

Rename file to component.rs
___
*[`src/examples/wide_fibonacci/structs.rs` line 18 at r3](https://reviewable.io/reviews/starkware-libs/stwo/562#-NvVnnDWEeKxDCe4oOBt:-NvVnnDWEeKxDCe4oOBu:bfhbgew) ([raw file](https://github.com/starkware-libs/stwo/blob/a4b4c44c7299f62a264be74c4be80e6704644242/src/examples/wide_fibonacci/structs.rs#L18)):*
> ```XML
> 
> impl WideFibComponent {
>     pub fn fill_initial_trace(&self, private_input: Vec<Input>) -> ColumnVec<Vec<BaseField>> {
> ```

I don't think this should be a method of the component. AVX will have a different trace gen impl.
The component is shared.
___
*[`src/examples/wide_fibonacci/trace_gen.rs` line 7 at r3](https://reviewable.io/reviews/starkware-libs/stwo/562#-NvVoCvQ8mKZNyLGCIGb:-NvVoCvQ8mKZNyLGCIGc:bnhn5jl) ([raw file](https://github.com/starkware-libs/stwo/blob/a4b4c44c7299f62a264be74c4be80e6704644242/src/examples/wide_fibonacci/trace_gen.rs#L7)):*
> ```XML
> // computation.
> /// Given a private input, write the trace row for the wide Fibonacci example to dst.
> pub fn write_trace_row(
> ```

Coordinate this change with @shaharsamocha7

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/562)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

___
*[`src/examples/wide_fibonacci/structs.rs` line 1 at r3](https://reviewable.io/reviews/starkware-libs/stwo/562#-NvVng-E8FsAjHm6VLOO:-NvVoa7v57WTDmfhWGNd:b-voyyih) ([raw file](https://github.com/starkware-libs/stwo/blob/a4b4c44c7299f62a264be74c4be80e6704644242/src/examples/wide_fibonacci/structs.rs#L1)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Rename file to component.rs
</blockquote></details>

In a different Pr possibly

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/562)* status: 0 of 10 files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/examples/wide_fibonacci/trace_gen.rs` line 8 at r4](https://reviewable.io/reviews/starkware-libs/stwo/562#-NvfgV-x9jAbPu6YjhlO:-NvfgV-x9jAbPu6YjhlP:btugv82) ([raw file](https://github.com/starkware-libs/stwo/blob/d6f62d20e840c77b0007bb039188eb87004062dd/crates/prover/src/examples/wide_fibonacci/trace_gen.rs#L8)):*
> ```XML
> // computation.
> /// Given a private input, write the trace row for the wide Fibonacci example to dst.
> pub fn write_trace_row(
> ```

@shaharsamocha7 PTAL.
___
*[`src/examples/wide_fibonacci/structs.rs` line 1 at r3](https://reviewable.io/reviews/starkware-libs/stwo/562#-NvVng-E8FsAjHm6VLOO:-NvfgFZa1s5alwUa_qSz:b-hk2a5r) ([raw file](https://github.com/starkware-libs/stwo/blob/a4b4c44c7299f62a264be74c4be80e6704644242/src/examples/wide_fibonacci/structs.rs#L1)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

In a different Pr possibly
</blockquote></details>

Done by Shahar.
___
*[`src/examples/wide_fibonacci/structs.rs` line 18 at r3](https://reviewable.io/reviews/starkware-libs/stwo/562#-NvVnnDWEeKxDCe4oOBt:-Nvg52bIC4_9ILRmDj5N:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/a4b4c44c7299f62a264be74c4be80e6704644242/src/examples/wide_fibonacci/structs.rs#L18)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I don't think this should be a method of the component. AVX will have a different trace gen impl.
The component is shared.
</blockquote></details>

Done.
___
*[`src/examples/wide_fibonacci/trace_gen.rs` line 7 at r3](https://reviewable.io/reviews/starkware-libs/stwo/562#-NvVoCvQ8mKZNyLGCIGb:-NvfgDGJ8w8IiQe3ZqvX:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/a4b4c44c7299f62a264be74c4be80e6704644242/src/examples/wide_fibonacci/trace_gen.rs#L7)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Coordinate this change with @shaharsamocha7
</blockquote></details>

Done.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/562)* status: 5 of 10 files reviewed, 7 unresolved discussions (waiting on @alonh5 and @spapinistarkware)

___
*[`crates/prover/src/examples/wide_fibonacci/component.rs` line 13 at r5](https://reviewable.io/reviews/starkware-libs/stwo/562#-NvjsufH1AVf3ezLxlPI:-NvjsufH1AVf3ezLxlPJ:bjc8vnl) ([raw file](https://github.com/starkware-libs/stwo/blob/b4783da7cfcb58c63c1a266f756b58c21de00ddd/crates/prover/src/examples/wide_fibonacci/component.rs#L13)):*
> ```XML
> pub const N_COLUMNS: usize = 1 << LOG_N_COLUMNS;
> 
> /// Component that computes fibonacci numbers over [N_COLUMNS] columns.
> ```

?
N_COLUMNS is not the attribute in the struct.



_Suggestion:_
```XML
/// Component that computes fibonacci numbers over [log_fibonacci_size] columns
```
___
*[`crates/prover/src/examples/wide_fibonacci/component.rs` line 15 at r5](https://reviewable.io/reviews/starkware-libs/stwo/562#-Nvjsf241-GXKrqHQltl:-Nvjsf25853SgMeQ7rCx:b-28b270) ([raw file](https://github.com/starkware-libs/stwo/blob/b4783da7cfcb58c63c1a266f756b58c21de00ddd/crates/prover/src/examples/wide_fibonacci/component.rs#L15)):*
> ```XML
> /// Component that computes fibonacci numbers over [N_COLUMNS] columns.
> pub struct WideFibComponent {
>     pub log_fibonacci_size: u32,
> ```

This should be n_columns? why is it `log_`
Attribute names are not clear.



_Code quote:_
```XML
pub log_fibonacci_size: u32,
```
___
*[`crates/prover/src/examples/wide_fibonacci/component.rs` line 22 at r5](https://reviewable.io/reviews/starkware-libs/stwo/562#-Nvjt70tCW1nelyQKNVb:-Nvjt70tCW1nelyQKNVc:bfv2e76) ([raw file](https://github.com/starkware-libs/stwo/blob/b4783da7cfcb58c63c1a266f756b58c21de00ddd/crates/prover/src/examples/wide_fibonacci/component.rs#L22)):*
> ```XML
>     pub fn log_column_size(&self) -> u32 {
>         self.log_n_instances + self.log_fibonacci_size - LOG_N_COLUMNS as u32
>     }
> ```

Document.
Also I don't understand this formula



_Code quote:_
```XML
    pub fn log_column_size(&self) -> u32 {
        self.log_n_instances + self.log_fibonacci_size - LOG_N_COLUMNS as u32
    }
```
___
*[`crates/prover/src/examples/wide_fibonacci/constraint_eval.rs` line 20 at r5](https://reviewable.io/reviews/starkware-libs/stwo/562#-NvjtKNF2Qpa0HH6kslr:-NvjtKNG3VjcbVTvNLma:b-cfbe87) ([raw file](https://github.com/starkware-libs/stwo/blob/b4783da7cfcb58c63c1a266f756b58c21de00ddd/crates/prover/src/examples/wide_fibonacci/constraint_eval.rs#L20)):*
> ```XML
> impl Component<CPUBackend> for WideFibComponent {
>     fn n_constraints(&self) -> usize {
>         N_COLUMNS - 1
> ```

Can you use the struct attribute instead of the Constant?
i.e. self.n_columns() or something

In the entire file



_Code quote:_
```XML
N_COLUMNS - 1
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/562)* status: 5 of 10 files reviewed, 6 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/examples/wide_fibonacci/component.rs` line 13 at r5](https://reviewable.io/reviews/starkware-libs/stwo/562#-NvjsufH1AVf3ezLxlPI:-Nvk0jbp2PMtQw_VU11w:b-4n87bk) ([raw file](https://github.com/starkware-libs/stwo/blob/b4783da7cfcb58c63c1a266f756b58c21de00ddd/crates/prover/src/examples/wide_fibonacci/component.rs#L13)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

?
N_COLUMNS is not the attribute in the struct.
</blockquote></details>

It's not an attribute of the struct it's a constant. The meaning is that there are always `N_COLUMNS` columns. the `log_fibonacci_size` can be larger and then we get that it spans on a few rows.
___
*[`crates/prover/src/examples/wide_fibonacci/component.rs` line 15 at r5](https://reviewable.io/reviews/starkware-libs/stwo/562#-Nvjsf241-GXKrqHQltl:-Nvk19wE2RpSLcVPfjuq:bmhcwte) ([raw file](https://github.com/starkware-libs/stwo/blob/b4783da7cfcb58c63c1a266f756b58c21de00ddd/crates/prover/src/examples/wide_fibonacci/component.rs#L15)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

This should be n_columns? why is it `log_`
Attribute names are not clear.
</blockquote></details>

This is the log size of the fibonacci sequence, which can span on a few rows (see comment above).
___
*[`crates/prover/src/examples/wide_fibonacci/component.rs` line 22 at r5](https://reviewable.io/reviews/starkware-libs/stwo/562#-Nvjt70tCW1nelyQKNVb:-Nvk3WQ5CCXv-FaXMilc:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/b4783da7cfcb58c63c1a266f756b58c21de00ddd/crates/prover/src/examples/wide_fibonacci/component.rs#L22)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Document.
Also I don't understand this formula
</blockquote></details>

Done.
___
*[`crates/prover/src/examples/wide_fibonacci/constraint_eval.rs` line 20 at r5](https://reviewable.io/reviews/starkware-libs/stwo/562#-NvjtKNF2Qpa0HH6kslr:-Nvk5cvx9VOWZ_2cpknZ:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/b4783da7cfcb58c63c1a266f756b58c21de00ddd/crates/prover/src/examples/wide_fibonacci/constraint_eval.rs#L20)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can you use the struct attribute instead of the Constant?
i.e. self.n_columns() or something

In the entire file
</blockquote></details>

Done.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 10 files at r4, 1 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/562)* status: 6 of 10 files reviewed, 6 unresolved discussions (waiting on @alonh5 and @spapinistarkware)

___
*[`crates/prover/src/examples/wide_fibonacci/avx.rs` line 57 at r5](https://reviewable.io/reviews/starkware-libs/stwo/562#-NvkB69hA_cxUO5CZTQ4:-NvkB69hA_cxUO5CZTQ5:b45h) ([raw file](https://github.com/starkware-libs/stwo/blob/b4783da7cfcb58c63c1a266f756b58c21de00ddd/crates/prover/src/examples/wide_fibonacci/avx.rs#L57)):*
> ```XML
>     fn n_constraints(&self) -> usize {
>         N_COLUMNS - 1
>     }
> ```





_Suggestion:_
```XML
    fn n_constraints(&self) -> usize {
        self.column_size() - 1
    }
```
___
*[`crates/prover/src/examples/wide_fibonacci/avx.rs` line 129 at r5](https://reviewable.io/reviews/starkware-libs/stwo/562#-NvkBBkUADBAOxpGxvKa:-NvkBBkUADBAOxpGxvKb:bm1ehj8) ([raw file](https://github.com/starkware-libs/stwo/blob/b4783da7cfcb58c63c1a266f756b58c21de00ddd/crates/prover/src/examples/wide_fibonacci/avx.rs#L129)):*
> ```XML
>         point: CirclePoint<SecureField>,
>     ) -> ColumnVec<Vec<CirclePoint<SecureField>>> {
>         fixed_mask_points(&vec![vec![0_usize]; N_COLUMNS], point)
> ```

also here



_Code quote:_
```XML
N_COLUMNS
```
___
*[`crates/prover/src/examples/wide_fibonacci/component.rs` line 13 at r5](https://reviewable.io/reviews/starkware-libs/stwo/562#-NvjsufH1AVf3ezLxlPI:-NvkA6ukBikXBABOZ5GO:b6g739f) ([raw file](https://github.com/starkware-libs/stwo/blob/b4783da7cfcb58c63c1a266f756b58c21de00ddd/crates/prover/src/examples/wide_fibonacci/component.rs#L13)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

It's not an attribute of the struct it's a constant. The meaning is that there are always `N_COLUMNS` columns. the `log_fibonacci_size` can be larger and then we get that it spans on a few rows.
</blockquote></details>

Ok so can you fix the documentation such that it would be understood how many fibonacci sequences are you compute and of which length?
___
*[`crates/prover/src/examples/wide_fibonacci/component.rs` line 17 at r6](https://reviewable.io/reviews/starkware-libs/stwo/562#-NvkAeUQ2e1gYzU55Y7B:-NvkAeUQ2e1gYzU55Y7C:b-qrog25) ([raw file](https://github.com/starkware-libs/stwo/blob/3256f7affd077225c3b2052ccd2cfcc839f78ddb/crates/prover/src/examples/wide_fibonacci/component.rs#L17)):*
> ```XML
>     pub log_fibonacci_size: u32,
>     pub log_n_instances: u32,
> }
> ```

Consider to put n_columns as a parameter here?



_Code quote:_
```XML
pub struct WideFibComponent {
    pub log_fibonacci_size: u32,
    pub log_n_instances: u32,
}
```
___
*[`crates/prover/src/examples/wide_fibonacci/trace_gen.rs` line 8 at r4](https://reviewable.io/reviews/starkware-libs/stwo/562#-NvfgV-x9jAbPu6YjhlO:-NvkAwDu5cOGBSJuhH4L:bmj14e8) ([raw file](https://github.com/starkware-libs/stwo/blob/d6f62d20e840c77b0007bb039188eb87004062dd/crates/prover/src/examples/wide_fibonacci/trace_gen.rs#L8)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

@shaharsamocha7 PTAL.
</blockquote></details>

Can you document the return value?

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/562)* status: 6 of 10 files reviewed, 6 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/examples/wide_fibonacci/avx.rs` line 57 at r5](https://reviewable.io/reviews/starkware-libs/stwo/562#-NvkB69hA_cxUO5CZTQ4:-NvkCy6X0x02b-KO3ML5:b-8796ag) ([raw file](https://github.com/starkware-libs/stwo/blob/b4783da7cfcb58c63c1a266f756b58c21de00ddd/crates/prover/src/examples/wide_fibonacci/avx.rs#L57)):*
> ```XML
>     fn n_constraints(&self) -> usize {
>         N_COLUMNS - 1
>     }
> ```

Already changed it, maybe you're not looking at the latest revision?
___
*[`crates/prover/src/examples/wide_fibonacci/avx.rs` line 129 at r5](https://reviewable.io/reviews/starkware-libs/stwo/562#-NvkBBkUADBAOxpGxvKa:-NvkD6Sb1ZkOwu-lAV-d:b2nreh6) ([raw file](https://github.com/starkware-libs/stwo/blob/b4783da7cfcb58c63c1a266f756b58c21de00ddd/crates/prover/src/examples/wide_fibonacci/avx.rs#L129)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

also here
</blockquote></details>

Same as above.
___
*[`crates/prover/src/examples/wide_fibonacci/component.rs` line 17 at r6](https://reviewable.io/reviews/starkware-libs/stwo/562#-NvkAeUQ2e1gYzU55Y7B:-NvkEt0c3A5yqZBitHkB:b4at6ub) ([raw file](https://github.com/starkware-libs/stwo/blob/3256f7affd077225c3b2052ccd2cfcc839f78ddb/crates/prover/src/examples/wide_fibonacci/component.rs#L17)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Consider to put n_columns as a parameter here?
</blockquote></details>

I think I'll do this in a new PR. I have 3 PRs over this one and it's causing many conflicts. Also we can wait and see if it's needed.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r5, 1 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/562)* status: 8 of 10 files reviewed, 4 unresolved discussions (waiting on @alonh5 and @spapinistarkware)

___
*[`crates/prover/src/examples/wide_fibonacci/component.rs` line 26 at r7](https://reviewable.io/reviews/starkware-libs/stwo/562#-NvkJZ5W8EdQ4M1SyD7l:-NvkJZ5W8EdQ4M1SyD7m:b-l6mwxj) ([raw file](https://github.com/starkware-libs/stwo/blob/a90d06718ed9f7c908927d68481af0f410d4c4a8/crates/prover/src/examples/wide_fibonacci/component.rs#L26)):*
> ```XML
>     /// the log number of rows).
>     pub fn log_column_size(&self) -> u32 {
>         // log(n_instances * fibonacci_size / N_COLUMNS)
> ```

remove



_Code quote:_
```XML
// log(n_instances * fibonacci_size / N_COLUMNS)
```
___
*[`crates/prover/src/examples/wide_fibonacci/component.rs` line 49 at r7](https://reviewable.io/reviews/starkware-libs/stwo/562#-NvkJRYc-EQoPP0XE0be:-NvkJRYd-OT40DaFFML7:b7se5q7) ([raw file](https://github.com/starkware-libs/stwo/blob/a90d06718ed9f7c908927d68481af0f410d4c4a8/crates/prover/src/examples/wide_fibonacci/component.rs#L49)):*
> ```XML
> }
> 
> pub fn fill_initial_trace(
> ```

Document and maybe rename



_Code quote:_
```XML
pub fn fill_initial_trace(
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/562)* status: 8 of 10 files reviewed, 4 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/examples/wide_fibonacci/component.rs` line 26 at r7](https://reviewable.io/reviews/starkware-libs/stwo/562#-NvkJZ5W8EdQ4M1SyD7l:-NvkJoYq1UC0R-jCeX7y:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/a90d06718ed9f7c908927d68481af0f410d4c4a8/crates/prover/src/examples/wide_fibonacci/component.rs#L26)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.
___
*[`crates/prover/src/examples/wide_fibonacci/component.rs` line 49 at r7](https://reviewable.io/reviews/starkware-libs/stwo/562#-NvkJRYc-EQoPP0XE0be:-NvkK7GZ-CKO577HvCDJ:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/a90d06718ed9f7c908927d68481af0f410d4c4a8/crates/prover/src/examples/wide_fibonacci/component.rs#L49)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Document and maybe rename
</blockquote></details>

Done.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r6, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/562#-:-NvkjwCJBYffAWAPFU-Y:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 5 of 10 files at r4, 2 of 4 files at r6, 1 of 2 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/562)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/prover/src/examples/wide_fibonacci/component.rs` line 49 at r8](https://reviewable.io/reviews/starkware-libs/stwo/562#-NwE0XwSDB6AodoCnDrj:-NwE0XwSDB6AodoCnDrk:b-2evch7) ([raw file](https://github.com/starkware-libs/stwo/blob/c7251129ddc21f5eb697b446ba28972834eee903/crates/prover/src/examples/wide_fibonacci/component.rs#L49)):*
> ```XML
> 
> /// Generates the trace for the wide Fibonacci example.
> pub fn gen_trace(
> ```

Shouldnt this be in another file? It's only the generation for the cpu backend, not the AVX one.
___
*[`crates/prover/src/examples/wide_fibonacci/mod.rs` line 69 at r8](https://reviewable.io/reviews/starkware-libs/stwo/562#-NwE0tNC93of3vLeNQzL:-NwE0tNC93of3vLeNQzM:b-woih5v) ([raw file](https://github.com/starkware-libs/stwo/blob/c7251129ddc21f5eb697b446ba28972834eee903/crates/prover/src/examples/wide_fibonacci/mod.rs#L69)):*
> ```XML
>         let inputs = (0..1 << wide_fib.log_n_instances)
>             .map(|i| Input {
>                 a: m31!(1),
> ```

I don't like this macro. It's a simple function call, no need for a macro. Macros are harder to reason about.

**Review by spapinistarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/562)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/562#-:-NwEBuIU6Wj2LR3TJTc6:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/562)* status: 6 of 10 files reviewed, all discussions resolved (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/examples/wide_fibonacci/component.rs` line 49 at r8](https://reviewable.io/reviews/starkware-libs/stwo/562#-NwE0XwSDB6AodoCnDrj:-NwKFvpoBn6FC6_w44tw:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/c7251129ddc21f5eb697b446ba28972834eee903/crates/prover/src/examples/wide_fibonacci/component.rs#L49)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Shouldnt this be in another file? It's only the generation for the cpu backend, not the AVX one.
</blockquote></details>

Done.
___
*[`crates/prover/src/examples/wide_fibonacci/mod.rs` line 69 at r8](https://reviewable.io/reviews/starkware-libs/stwo/562#-NwE0tNC93of3vLeNQzL:-NwKGLI-DiXAQXwFTre8:b-gfzck1) ([raw file](https://github.com/starkware-libs/stwo/blob/c7251129ddc21f5eb697b446ba28972834eee903/crates/prover/src/examples/wide_fibonacci/mod.rs#L69)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I don't like this macro. It's a simple function call, no need for a macro. Macros are harder to reason about.
</blockquote></details>

I'm not sure I understand. This macro is just a shortened unchecked version for testing.

**Pull request merged**
