### PR TITLE
Add eq evals constraints

### PR DESCRIPTION
**Pull request by andrewmilson**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/741)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/741)* status: all files reviewed, 4 unresolved discussions (waiting on @andrewmilson)

___
*[`crates/prover/src/constraint_framework/constant_columns.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/stwo/741#-O2cYRIZEr5GF-z3hWfi:-O2cYRIZEr5GF-z3hWfj:b-xq6473) ([raw file](https://github.com/starkware-libs/stwo/blob/e813a313dcce774b66ff961f0e020859cee51989/crates/prover/src/constraint_framework/constant_columns.rs#L17)):*
> ```XML
> 
> /// Generates a column with a single one at every `2^log_step` positions, and zero elsewhere.
> // TODO(andrew): Optimize. Is a quotients of two coset_vanishing (use succinct rep for verifier).
> ```

Not 100% sure what's better for the verifier.



_Suggestion:_
```XML
// TODO(andrew): Consider optimizing. Is a quotients of two coset_vanishing (use succinct rep for verifier).
```
___
*[`crates/prover/src/constraint_framework/constant_columns.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/stwo/741#-O2cZ8Se3NO8MYyJzni4:-O2cZ8SfD5ZBofTx427_:b-eeo6qb) ([raw file](https://github.com/starkware-libs/stwo/blob/e813a313dcce774b66ff961f0e020859cee51989/crates/prover/src/constraint_framework/constant_columns.rs#L37)):*
> ```XML
> /// [`CircleDomain`]: crate::core::poly::circle::CircleDomain
> /// [`Coset`]: crate::core::circle::Coset
> fn coset_index_to_circle_domain_index(coset_index: usize, log_domain_size: u32) -> usize {
> ```

Looks very similar to `offset_bit_reversed_circle_domain_index()`. Can we unite?
___
*[`crates/prover/src/core/backend/simd/column.rs` line 118 at r1](https://reviewable.io/reviews/starkware-libs/stwo/741#-O2cZXrwBvCOfKBNxOkH:-O2cZXrwBvCOfKBNxOkI:b9wklmw) ([raw file](https://github.com/starkware-libs/stwo/blob/e813a313dcce774b66ff961f0e020859cee51989/crates/prover/src/core/backend/simd/column.rs#L118)):*
> ```XML
>         }
> 
>         let length = self.length;
> ```

Can we use collect() here as well?
___
*[`crates/prover/src/examples/xor/eq_eval_constraints.rs` line 249 at r1](https://reviewable.io/reviews/starkware-libs/stwo/741#-O2cZkcTDbBnRH-HXfJt:-O2cZkcTDbBnRH-HXfJu:b-gl509x) ([raw file](https://github.com/starkware-libs/stwo/blob/e813a313dcce774b66ff961f0e020859cee51989/crates/prover/src/examples/xor/eq_eval_constraints.rs#L249)):*
> ```XML
>     ) -> ColumnVec<CircleEvaluation<SimdBackend, BaseField, BitReversedOrder>> {
>         let eq_evals = SimdBackend::gen_eq_evals(eval_point, SecureField::one()).into_evals();
>         let eq_evals_coordinate_columns = eq_evals.into_secure_column().columns;
> ```

Might it be better to just keep eq_evals as a secure colum to begin with/

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/741)* status: all files reviewed, 4 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/constraint_framework/constant_columns.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/stwo/741#-O2cYRIZEr5GF-z3hWfi:-O4BYswp0IjIzfBe2cJD:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/e813a313dcce774b66ff961f0e020859cee51989/crates/prover/src/constraint_framework/constant_columns.rs#L17)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Not 100% sure what's better for the verifier.
</blockquote></details>

Done.
___
*[`crates/prover/src/constraint_framework/constant_columns.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/stwo/741#-O2cZ8Se3NO8MYyJzni4:-O4BYhyzBmPa1rIzXOP3:blb8tmf) ([raw file](https://github.com/starkware-libs/stwo/blob/e813a313dcce774b66ff961f0e020859cee51989/crates/prover/src/constraint_framework/constant_columns.rs#L37)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Looks very similar to `offset_bit_reversed_circle_domain_index()`. Can we unite?
</blockquote></details>

United with `coset_order_to_circle_domain_order_index`
___
*[`crates/prover/src/core/backend/simd/column.rs` line 118 at r1](https://reviewable.io/reviews/starkware-libs/stwo/741#-O2cZXrwBvCOfKBNxOkH:-O4BS0HdB-TFhAe5LRtV:bwcoaid) ([raw file](https://github.com/starkware-libs/stwo/blob/e813a313dcce774b66ff961f0e020859cee51989/crates/prover/src/core/backend/simd/column.rs#L118)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Can we use collect() here as well?
</blockquote></details>

Don't think it would be appropriate. 

Could do `self.into_iter<Item=SecureField>` and then collect into SecureColumn but I don't think that's very efficient given the way PackedSecureField is stored. Can't do `self.into_iter<Item=PackedSecureField>` because length information could be lost
___
*[`crates/prover/src/examples/xor/eq_eval_constraints.rs` line 249 at r1](https://reviewable.io/reviews/starkware-libs/stwo/741#-O2cZkcTDbBnRH-HXfJt:-O4BOtYL72Kcg3a_K0eJ:b-2efetw) ([raw file](https://github.com/starkware-libs/stwo/blob/e813a313dcce774b66ff961f0e020859cee51989/crates/prover/src/examples/xor/eq_eval_constraints.rs#L249)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Might it be better to just keep eq_evals as a secure colum to begin with/
</blockquote></details>

Yes. Would require a few changes so added as a TODO for now

**Comment by andrewmilson** [comment]
* **#741** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/741?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @andrewmilson and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 4 of 7 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/741)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @andrewmilson)

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/741)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @andrewmilson)

___
*[`crates/prover/src/examples/xor/eq_eval_constraints.rs` line 74 at r3](https://reviewable.io/reviews/starkware-libs/stwo/741#-O4EUfq442_HW1sDJa-p:-O4EUfq442_HW1sDJa-q:b-f416ot) ([raw file](https://github.com/starkware-libs/stwo/blob/45efb3721a2fbc1c917f11f07d3feeb078fce7de/crates/prover/src/examples/xor/eq_eval_constraints.rs#L74)):*
> ```XML
>         mask_offsets[1..].copy_from_slice(&variable_step_offsets);
> 
>         let mask_items = eval.next_extension_interaction_mask(TRACE, mask_offsets);
> ```

We should be able to do this with just next row offsets. Talk to me.

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 1 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/741)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @andrewmilson)

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/741)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/prover/src/examples/xor/eq_eval_constraints.rs` line 74 at r3](https://reviewable.io/reviews/starkware-libs/stwo/741#-O4EUfq442_HW1sDJa-p:-O4aKzMFEeapAciAgP3k:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/45efb3721a2fbc1c917f11f07d3feeb078fce7de/crates/prover/src/examples/xor/eq_eval_constraints.rs#L74)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

We should be able to do this with just next row offsets. Talk to me.
</blockquote></details>

Done.

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/741)* status: 6 of 8 files reviewed, 3 unresolved discussions (waiting on @andrewmilson)

___
*[`crates/prover/src/examples/xor/eq_eval_constraints.rs` line 13 at r4](https://reviewable.io/reviews/starkware-libs/stwo/741#-O4isAEPDdK-u924e1T6:-O4isAEPDdK-u924e1T7:b-lk14qz) ([raw file](https://github.com/starkware-libs/stwo/blob/134d883f1fa66f44992db3c4372906eaa73846c5/crates/prover/src/examples/xor/eq_eval_constraints.rs#L13)):*
> ```XML
> #[educe(Debug, Clone, Copy)]
> pub struct EqEvalsMask<E: EvalAtRow, const N_VARIABLES: usize> {
>     pub curr: E::EF,
> ```

Document fields.
___
*[`crates/prover/src/examples/xor/eq_eval_constraints.rs` line 57 at r4](https://reviewable.io/reviews/starkware-libs/stwo/741#-O4isXsT0z4I8hnFS7fV:-O4isXsT0z4I8hnFS7fW:b7yc9d8) ([raw file](https://github.com/starkware-libs/stwo/blob/134d883f1fa66f44992db3c4372906eaa73846c5/crates/prover/src/examples/xor/eq_eval_constraints.rs#L57)):*
> ```XML
>         // Check the initial value on half_coset0 and final value on half_coset1.
>         // Combining these constraints is safe because `is_first` and `is_second` are never
>         // non-zero at the same time on the trace.
> ```

Do we really need 2 selectors for each constraint?
We can probably have 1 selector with 2 offsets [0,1] or [0,-1], right?
Do you think it's better this way?

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/741)* status: 6 of 8 files reviewed, 5 unresolved discussions (waiting on @andrewmilson)

___
*[`crates/prover/src/examples/xor/eq_eval_constraints.rs` line 12 at r4](https://reviewable.io/reviews/starkware-libs/stwo/741#-O4itDe46ePLCNSpWh9f:-O4itDe46ePLCNSpWh9g:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/134d883f1fa66f44992db3c4372906eaa73846c5/crates/prover/src/examples/xor/eq_eval_constraints.rs#L12)):*
> ```XML
> #[derive(Educe)]
> #[educe(Debug, Clone, Copy)]
> pub struct EqEvalsMask<E: EvalAtRow, const N_VARIABLES: usize> {
> ```





_Suggestion:_
```XML
MulitlinearEqConstraints
```
___
*[`crates/prover/src/examples/xor/eq_eval_constraints.rs` line 12 at r4](https://reviewable.io/reviews/starkware-libs/stwo/741#-O4itJH61qPI84vyiFW7:-O4itJH61qPI84vyiFW8:bsr27e3) ([raw file](https://github.com/starkware-libs/stwo/blob/134d883f1fa66f44992db3c4372906eaa73846c5/crates/prover/src/examples/xor/eq_eval_constraints.rs#L12)):*
> ```XML
> #[derive(Educe)]
> #[educe(Debug, Clone, Copy)]
> pub struct EqEvalsMask<E: EvalAtRow, const N_VARIABLES: usize> {
> ```

```
/// Evaluates EqEvals constraints on a column.
/// Given a column c(P) defined on a circle domain D,
/// and an mle evalaution point r0, r1, ...
/// evaluates constraints that guarantee:
///   c(D[b0,b1,...]) = eq((b0,b1,...), (r0,r1,...))

```

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/741)* status: 6 of 8 files reviewed, 6 unresolved discussions (waiting on @andrewmilson)

___
*[`crates/prover/src/examples/xor/eq_eval_constraints.rs` line 17 at r4](https://reviewable.io/reviews/starkware-libs/stwo/741#-O4iv58G-mxSoCxYNyNp:-O4iv58G-mxSoCxYNyNq:b-8vqzxe) ([raw file](https://github.com/starkware-libs/stwo/blob/134d883f1fa66f44992db3c4372906eaa73846c5/crates/prover/src/examples/xor/eq_eval_constraints.rs#L17)):*
> ```XML
>     pub is_first: E::F,
>     pub is_second: E::F,
>     pub is_half_coset_step_by_log_size: [Option<CircleDomainStepMask<E>>; N_VARIABLES],
> ```

Isn't it prettier to just shift by 1?



_Suggestion:_
```XML
CircleDomainStepMask<E>
```
___
*[`crates/prover/src/examples/xor/eq_eval_constraints.rs` line 21 at r4](https://reviewable.io/reviews/starkware-libs/stwo/741#-O4iua3W5Yy9tDrByj_u:-O4iua3W5Yy9tDrByj_v:b3bfz4z) ([raw file](https://github.com/starkware-libs/stwo/blob/134d883f1fa66f44992db3c4372906eaa73846c5/crates/prover/src/examples/xor/eq_eval_constraints.rs#L21)):*
> ```XML
> 
> impl<E: EvalAtRow, const N_VARIABLES: usize> EqEvalsMask<E, N_VARIABLES> {
>     pub fn draw<const EQ_EVALS_TRACE: usize, const SELECTOR_TRACE: usize>(eval: &mut E) -> Self {
> ```

I think this is just `new`, not `draw`.

Also, not need to seperate this frunction from eval, right? They should always be called togther AFAIU.
Just make it a single function. I don't think we even need an auxilliary struct in this case.
___
*[`crates/prover/src/examples/xor/eq_eval_constraints.rs` line 57 at r4](https://reviewable.io/reviews/starkware-libs/stwo/741#-O4isXsT0z4I8hnFS7fV:-O4ivJKmE3O3L9ajFF6l:bktlln6) ([raw file](https://github.com/starkware-libs/stwo/blob/134d883f1fa66f44992db3c4372906eaa73846c5/crates/prover/src/examples/xor/eq_eval_constraints.rs#L57)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Do we really need 2 selectors for each constraint?
We can probably have 1 selector with 2 offsets [0,1] or [0,-1], right?
Do you think it's better this way?
</blockquote></details>

Nvm, I see you already do this
___
*[`crates/prover/src/examples/xor/eq_eval_constraints.rs` line 80 at r4](https://reviewable.io/reviews/starkware-libs/stwo/741#-O4ivDF78-Exncdua_ZR:-O4ivDF78-Exncdua_ZS:b-up1b9k) ([raw file](https://github.com/starkware-libs/stwo/blob/134d883f1fa66f44992db3c4372906eaa73846c5/crates/prover/src/examples/xor/eq_eval_constraints.rs#L80)):*
> ```XML
> #[derive(Educe)]
> #[educe(Debug, Clone, Copy)]
> pub struct CircleDomainStepMask<E: EvalAtRow> {
> ```

Document what this does, and what constant column it needs.

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/741)* status: 6 of 8 files reviewed, 6 unresolved discussions (waiting on @andrewmilson)

___
*[`crates/prover/src/examples/xor/eq_eval_constraints.rs` line 21 at r4](https://reviewable.io/reviews/starkware-libs/stwo/741#-O4iua3W5Yy9tDrByj_u:-O4iveUq3WkLGkrS-C9W:bde1g2j) ([raw file](https://github.com/starkware-libs/stwo/blob/134d883f1fa66f44992db3c4372906eaa73846c5/crates/prover/src/examples/xor/eq_eval_constraints.rs#L21)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I think this is just `new`, not `draw`.

Also, not need to seperate this frunction from eval, right? They should always be called togther AFAIU.
Just make it a single function. I don't think we even need an auxilliary struct in this case.
</blockquote></details>

You do need to externalize curr though. But no need for the entire struct.
I suggest calling the function somthing like `eval_eq_constraints` and letting it return the value of the eq column, to be used externally. This also makes sure you didn't forget to call the eval, and that you are using the same EvalAtRow, and dont call it twice, etc...

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/741)* status: 6 of 8 files reviewed, 6 unresolved discussions (waiting on @andrewmilson)

___
*[`crates/prover/src/examples/xor/eq_eval_constraints.rs` line 21 at r4](https://reviewable.io/reviews/starkware-libs/stwo/741#-O4iua3W5Yy9tDrByj_u:-O4ix43i4tttISwu5_a3:b-w44vla) ([raw file](https://github.com/starkware-libs/stwo/blob/134d883f1fa66f44992db3c4372906eaa73846c5/crates/prover/src/examples/xor/eq_eval_constraints.rs#L21)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

You do need to externalize curr though. But no need for the entire struct.
I suggest calling the function somthing like `eval_eq_constraints` and letting it return the value of the eq column, to be used externally. This also makes sure you didn't forget to call the eval, and that you are using the same EvalAtRow, and dont call it twice, etc...
</blockquote></details>

Note: If you had instantiated this before ever having EvalAtRow, so that you can hold preprocessed data, this would justify a struct.

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/741)* status: 6 of 8 files reviewed, 6 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/examples/xor/eq_eval_constraints.rs` line 12 at r4](https://reviewable.io/reviews/starkware-libs/stwo/741#-O4itDe46ePLCNSpWh9f:-O4jzAi85V6ODUcpJzEa:b-rpcy50) ([raw file](https://github.com/starkware-libs/stwo/blob/134d883f1fa66f44992db3c4372906eaa73846c5/crates/prover/src/examples/xor/eq_eval_constraints.rs#L12)):*
> ```XML
> #[derive(Educe)]
> #[educe(Debug, Clone, Copy)]
> pub struct EqEvalsMask<E: EvalAtRow, const N_VARIABLES: usize> {
> ```

Changed to function
___
*[`crates/prover/src/examples/xor/eq_eval_constraints.rs` line 12 at r4](https://reviewable.io/reviews/starkware-libs/stwo/741#-O4itJH61qPI84vyiFW7:-O4jzrSA61jNK1S5DHHN:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/134d883f1fa66f44992db3c4372906eaa73846c5/crates/prover/src/examples/xor/eq_eval_constraints.rs#L12)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

```
/// Evaluates EqEvals constraints on a column.
/// Given a column c(P) defined on a circle domain D,
/// and an mle evalaution point r0, r1, ...
/// evaluates constraints that guarantee:
///   c(D[b0,b1,...]) = eq((b0,b1,...), (r0,r1,...))

```
</blockquote></details>

Done.
___
*[`crates/prover/src/examples/xor/eq_eval_constraints.rs` line 13 at r4](https://reviewable.io/reviews/starkware-libs/stwo/741#-O4isAEPDdK-u924e1T6:-O4jzMY1ETuchnGfK13N:b-qf61l8) ([raw file](https://github.com/starkware-libs/stwo/blob/134d883f1fa66f44992db3c4372906eaa73846c5/crates/prover/src/examples/xor/eq_eval_constraints.rs#L13)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Document fields.
</blockquote></details>

Removed struct.
___
*[`crates/prover/src/examples/xor/eq_eval_constraints.rs` line 17 at r4](https://reviewable.io/reviews/starkware-libs/stwo/741#-O4iv58G-mxSoCxYNyNp:-O4jzOgY0tfzQhIenPhF:bss4a2b) ([raw file](https://github.com/starkware-libs/stwo/blob/134d883f1fa66f44992db3c4372906eaa73846c5/crates/prover/src/examples/xor/eq_eval_constraints.rs#L17)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Isn't it prettier to just shift by 1?
</blockquote></details>

Removed.
___
*[`crates/prover/src/examples/xor/eq_eval_constraints.rs` line 21 at r4](https://reviewable.io/reviews/starkware-libs/stwo/741#-O4iua3W5Yy9tDrByj_u:-O4jwbjW2t6Xw5JAgwTc:b-zcjvte) ([raw file](https://github.com/starkware-libs/stwo/blob/134d883f1fa66f44992db3c4372906eaa73846c5/crates/prover/src/examples/xor/eq_eval_constraints.rs#L21)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Note: If you had instantiated this before ever having EvalAtRow, so that you can hold preprocessed data, this would justify a struct.
</blockquote></details>

Thanks
___
*[`crates/prover/src/examples/xor/eq_eval_constraints.rs` line 80 at r4](https://reviewable.io/reviews/starkware-libs/stwo/741#-O4ivDF78-Exncdua_ZR:-O4jweGD5FXFTOqIkklQ:bss4a2b) ([raw file](https://github.com/starkware-libs/stwo/blob/134d883f1fa66f44992db3c4372906eaa73846c5/crates/prover/src/examples/xor/eq_eval_constraints.rs#L80)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Document what this does, and what constant column it needs.
</blockquote></details>

Removed.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/741#-:-O4nkKnL-c9rI-hQRCnS:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @andrewmilson)

___
*[`crates/prover/src/examples/xor/eq_eval_constraints.rs` line 17 at r5](https://reviewable.io/reviews/starkware-libs/stwo/741#-O4njmce5W1GoqvRvhvS:-O4njmce5W1GoqvRvhvT:b-2wzr0y) ([raw file](https://github.com/starkware-libs/stwo/blob/abf86a11e5b9e4295fe629c32e529d8f8e40125c/crates/prover/src/examples/xor/eq_eval_constraints.rs#L17)):*
> ```XML
> ///
> /// See <https://eprint.iacr.org/2023/1284.pdf> (Section 5.1).
> pub fn eval_eq_constraints<
> ```

Very cool

**Pull request merged**
