### PR TITLE
Separate verifier crate

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/586)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/586?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#586** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/586?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#585** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/585?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 79 of 80 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/586)* status: all files reviewed, 5 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/core/backend/avx512/circle.rs` line 329 at r2](https://reviewable.io/reviews/starkware-libs/stwo/586#-NwEuvVq5aTntmHU-yfg:-NwEuvVq5aTntmHU-yfh:b-v0duql) ([raw file](https://github.com/starkware-libs/stwo/blob/6d7d396624398401fd9b0014c9edf8256111b660/crates/prover/src/core/backend/avx512/circle.rs#L329)):*
> ```XML
>         a.swap_with_slice(&mut c[0..n0]);
>     }
>     fold(poly.coeffs.as_slice(), &mappings)
> ```

Why did you change it?



_Code quote:_
```XML
poly.coeffs.as_slice()
```
___
*[`crates/verifier/Cargo.toml` line 15 at r2](https://reviewable.io/reviews/starkware-libs/stwo/586#-NwEwgv48qiAkEPr-hwO:-NwEwgv48qiAkEPr-hwP:bwhauqh) ([raw file](https://github.com/starkware-libs/stwo/blob/6d7d396624398401fd9b0014c9edf8256111b660/crates/verifier/Cargo.toml#L15)):*
> ```TOML
> rand = { version = "0.8.5", features = ["small_rng"] }
> [lib]
> bench = false
> ```

Is this needed?



_Code quote:_
```TOML
[lib]
bench = false
```
___
*[`crates/verifier/Cargo.toml` line 25 at r2](https://reviewable.io/reviews/starkware-libs/stwo/586#-NwEwksq8llIvyCpziJU:-NwEwksq8llIvyCpziJV:byp18fd) ([raw file](https://github.com/starkware-libs/stwo/blob/6d7d396624398401fd9b0014c9edf8256111b660/crates/verifier/Cargo.toml#L25)):*
> ```TOML
> 
> [features]
> avx512 = []
> ```

Remove



_Code quote:_
```TOML
[features]
avx512 = []
```
___
*[`crates/verifier/src/core/fields/cm31.rs` line 63 at r2](https://reviewable.io/reviews/starkware-libs/stwo/586#-NwEzPj99Z25o_i2QHyq:-NwEzPj99Z25o_i2QHyr:b-a1sk3s) ([raw file](https://github.com/starkware-libs/stwo/blob/5b0ecc9a5a81bdb6c84a38321f3f0d3b2461e952/crates/verifier/src/core/fields/cm31.rs#L63)):*
> ```XML
> }
> 
> #[cfg(test)]
> ```

Can you keep it? Those functions were suppose to use us only for tests.
Same for the others.



_Code quote:_
```XML
#[cfg(test)]
```
___
*[`crates/verifier/src/core/fields/mod.rs` line 35 at r2](https://reviewable.io/reviews/starkware-libs/stwo/586#-NwEysma9Kk83wux6zXJ:-NwEysmb6vUyoqjrGMUn:bzh6c8c) ([raw file](https://github.com/starkware-libs/stwo/blob/6d7d396624398401fd9b0014c9edf8256111b660/crates/verifier/src/core/fields/mod.rs#L35)):*
> ```XML
> }
> 
> pub trait MulGroup: Mul<Output = Self> + MulAssign + Sized + One + Copy {
> ```

Can you add short documentation?



_Suggestion:_
```XML
/// Trait for performing field multiplicative group operations.
pub trait MulGroup: Mul<Output = Self> + MulAssign + Sized + One + Copy {
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/586)* status: all files reviewed, 5 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/verifier/src/core/fields/cm31.rs` line 63 at r2](https://reviewable.io/reviews/starkware-libs/stwo/586#-NwEzPj99Z25o_i2QHyq:-NwFF6s66WjBYllzQUJJ:b-tyeudl) ([raw file](https://github.com/starkware-libs/stwo/blob/5b0ecc9a5a81bdb6c84a38321f3f0d3b2461e952/crates/verifier/src/core/fields/cm31.rs#L63)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can you keep it? Those functions were suppose to use us only for tests.
Same for the others.
</blockquote></details>

One crate cannot access the test config items of another crate.

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/586)* status: all files reviewed, 5 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/verifier/src/core/fields/cm31.rs` line 63 at r2](https://reviewable.io/reviews/starkware-libs/stwo/586#-NwEzPj99Z25o_i2QHyq:-NwFIzq16acg8O0KJXs2:b-7ttm93) ([raw file](https://github.com/starkware-libs/stwo/blob/5b0ecc9a5a81bdb6c84a38321f3f0d3b2461e952/crates/verifier/src/core/fields/cm31.rs#L63)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

One crate cannot access the test config items of another crate.
</blockquote></details>

Ok.
Can you just confirm with AlonH if there was other reason why it is only for tests?
(unblocking)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/586)* status: 78 of 80 files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/prover/src/core/backend/avx512/circle.rs` line 329 at r2](https://reviewable.io/reviews/starkware-libs/stwo/586#-NwEuvVq5aTntmHU-yfg:-NwFRJru16vLIqC-fGg4:b-q37469) ([raw file](https://github.com/starkware-libs/stwo/blob/6d7d396624398401fd9b0014c9edf8256111b660/crates/prover/src/core/backend/avx512/circle.rs#L329)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why did you change it?
</blockquote></details>

It was reimplementing this funcationality, whic is a bit silly.
___
*[`crates/verifier/Cargo.toml` line 25 at r2](https://reviewable.io/reviews/starkware-libs/stwo/586#-NwEwksq8llIvyCpziJU:-NwFRTvhDV6kUoLPYsj_:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/6d7d396624398401fd9b0014c9edf8256111b660/crates/verifier/Cargo.toml#L25)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Remove
</blockquote></details>

Done.
___
*[`crates/verifier/src/core/fields/mod.rs` line 35 at r2](https://reviewable.io/reviews/starkware-libs/stwo/586#-NwEysma9Kk83wux6zXJ:-NwFRHztC2ATN10953dR:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/6d7d396624398401fd9b0014c9edf8256111b660/crates/verifier/src/core/fields/mod.rs#L35)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can you add short documentation?
</blockquote></details>

Done.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/586#-:-Nwipn3ECFl3fV6PaQ79:bnfp4nl)* status: 61 of 87 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by andrewmilson — CHANGES_REQUESTED** [review]
> Reviewed 51 of 80 files at r1, 1 of 2 files at r2, 2 of 2 files at r3, 33 of 33 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/586)* status: all files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/benches/eval_at_point.rs` line 11 at r4](https://reviewable.io/reviews/starkware-libs/stwo/586#-NwjjeDqAvhsbpWxU7Z_:-NwjjeDqAvhsbpWxU7Za:b-ezw6ai) ([raw file](https://github.com/starkware-libs/stwo/blob/981731857ac8c088501de845822ddc83d1122640/crates/prover/benches/eval_at_point.rs#L11)):*
> ```XML
>     use stwo_prover::core::poly::circle::{CanonicCoset, CircleEvaluation, PolyOps};
>     use stwo_prover::core::poly::NaturalOrder;
>     use stwo_verifier::core::fields::m31::BaseField;
> ```

I think it makes more sense to have a seperate `stwo_fields` crate. Seems strange importing fields from the verifier.
___
*[`crates/prover/src/core/backend/avx512/circle.rs` line 88 at r4](https://reviewable.io/reviews/starkware-libs/stwo/586#-NwjhcaY6PFbJTM79eU6:-NwjhcaY6PFbJTM79eU7:bb70wkm) ([raw file](https://github.com/starkware-libs/stwo/blob/981731857ac8c088501de845822ddc83d1122640/crates/prover/src/core/backend/avx512/circle.rs#L88)):*
> ```XML
>     fn twiddle_steps<F: Field>(mappings: &[F]) -> Vec<F>
>     where
>         F: MulGroup,
> ```

Nit:



_Suggestion:_
```XML
    fn twiddle_steps<F: Field + MulGroup>(mappings: &[F]) -> Vec<F>
```

**Pull request closed without merging**
