### PR TITLE
Blake scheduler

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/770)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/770?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#770** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/770?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#767** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/767?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#765** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/765?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#764** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/764?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#761** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/761?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#712** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/712?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#711** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/711?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#710** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/710?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#708** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/708?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#707** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/707?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#715** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/715?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#714** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/714?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#713** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/713?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#706** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/706?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#705** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/705?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#704** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/704?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#702** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/702?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#701** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/701?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r1, 2 of 6 files at r2, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/770)* status: 4 of 7 files reviewed, 6 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/examples/blake/round/gen.rs` line 103 at r3](https://reviewable.io/reviews/starkware-libs/stwo/770#-O3az1MRC1bxxImpXBBy:-O3az1MRC1bxxImpXBBz:byp1ktf) ([raw file](https://github.com/starkware-libs/stwo/blob/7d4609dd362b38b665f513476c384a1e94d8b6f3/crates/prover/src/examples/blake/round/gen.rs#L103)):*
> ```XML
>             .flat_map(to_felts)
>             .enumerate()
>             .for_each(|(i, val)| self.gen.round_lookup[i].data[self.vec_row] = val);
> ```

Rename



_Suggestion:_
```XML
.for_each(|(i, felt)| self.gen.round_lookup[i].data[self.vec_row] = felt);
```
___
*[`crates/prover/src/examples/blake/round/mod.rs` line 6 at r3](https://reviewable.io/reviews/starkware-libs/stwo/770#-O3azDlF3hAocqR2dOcI:-O3azDlF3hAocqR2dOcJ:b56dl37) ([raw file](https://github.com/starkware-libs/stwo/blob/7d4609dd362b38b665f513476c384a1e94d8b6f3/crates/prover/src/examples/blake/round/mod.rs#L6)):*
> ```XML
> use constraints::BlakeRoundEval;
> use num_traits::Zero;
> pub use r#gen::BlakeRoundInput;
> ```

what's r#?



_Code quote:_
```XML
pub use r#gen::BlakeRoundInput;
```
___
*[`crates/prover/src/examples/blake/scheduler/gen.rs` line 30 at r3](https://reviewable.io/reviews/starkware-libs/stwo/770#-O3b-cW52y2FfbUTBfOF:-O3b-cW52y2FfbUTBfOG:b6jt3y9) ([raw file](https://github.com/starkware-libs/stwo/blob/7d4609dd362b38b665f513476c384a1e94d8b6f3/crates/prover/src/examples/blake/scheduler/gen.rs#L30)):*
> ```XML
> 
> pub struct BlakeSchedulerLookupData {
>     pub round_lookups: [[BaseColumn; 16 * 3 * 2]; N_ROUNDS],
> ```

Consider to extract to a const



_Code quote:_
```XML
16 * 3 * 2
```
___
*[`crates/prover/src/examples/blake/scheduler/gen.rs` line 72 at r3](https://reviewable.io/reviews/starkware-libs/stwo/770#-O3b-6Vc5cCUpGbRBe4I:-O3b-6Vc5cCUpGbRBe4J:b-6pvral) ([raw file](https://github.com/starkware-libs/stwo/blob/7d4609dd362b38b665f513476c384a1e94d8b6f3/crates/prover/src/examples/blake/scheduler/gen.rs#L72)):*
> ```XML
>                 *col_index += 2;
>             });
>         };
> ```

Extract to `write_u32_array` func



_Code quote:_
```XML
        let mut write_array = |x: [u32x16; 16], col_index: &mut usize| {
            x.iter().for_each(|x| {
                trace[*col_index].data[vec_row] =
                    unsafe { PackedBaseField::from_simd_unchecked(*x & u32x16::splat(0xffff)) };
                trace[*col_index + 1].data[vec_row] =
                    unsafe { PackedBaseField::from_simd_unchecked(*x >> 16) };
                *col_index += 2;
            });
        };
```
___
*[`crates/prover/src/examples/blake/scheduler/gen.rs` line 93 at r3](https://reviewable.io/reviews/starkware-libs/stwo/770#-O3b0BiM0kG0iPi8FyRq:-O3b0BiM0kG0iPi8FyRr:b-63yp23) ([raw file](https://github.com/starkware-libs/stwo/blob/7d4609dd362b38b665f513476c384a1e94d8b6f3/crates/prover/src/examples/blake/scheduler/gen.rs#L93)):*
> ```XML
>                 prev_v.iter().flat_map(to_felts),
>                 v.iter().flat_map(to_felts),
>                 round_m.iter().flat_map(to_felts)
> ```

Don't you also need round_id or something?
How do we know that we used the correct `round_m` for the round input?



_Code quote:_
```XML
                prev_v.iter().flat_map(to_felts),
                v.iter().flat_map(to_felts),
                round_m.iter().flat_map(to_felts)
```
___
*[`crates/prover/src/examples/blake/scheduler/gen.rs` line 145 at r3](https://reviewable.io/reviews/starkware-libs/stwo/770#-O3b0mRv5fStGJD9K2nH:-O3b0mRv5fStGJD9K2nI:b-a9l0m) ([raw file](https://github.com/starkware-libs/stwo/blob/7d4609dd362b38b665f513476c384a1e94d8b6f3/crates/prover/src/examples/blake/scheduler/gen.rs#L145)):*
> ```XML
>     }
> 
>     // Last pair.
> ```

Please add a comment here that you 
Combine the lookups for blake yield with blake round in case of odd number of blake rounds.

IMO, you should discard this code and just add it separately as we currently only targeting Blake2s.



_Code quote:_
```XML
// Last pair.
```

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/770)* status: 4 of 7 files reviewed, 7 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/examples/blake/scheduler/mod.rs` line 7 at r3](https://reviewable.io/reviews/starkware-libs/stwo/770#-O3b1mwC4MIv4ZJew7HL:-O3b1mwC4MIv4ZJew7HM:b-tsgfof) ([raw file](https://github.com/starkware-libs/stwo/blob/7d4609dd362b38b665f513476c384a1e94d8b6f3/crates/prover/src/examples/blake/scheduler/mod.rs#L7)):*
> ```XML
> use num_traits::Zero;
> 
> use super::round::RoundElements;
> ```

consider to rename



_Suggestion:_
```XML
use super::round::BlakeStateElements;
```

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/770)* status: 4 of 7 files reviewed, 10 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/examples/blake/mod.rs` line 117 at r3](https://reviewable.io/reviews/starkware-libs/stwo/770#-O3b35xzAi18V8h0eou2:-O3b35xzAi18V8h0eou3:b-dvzz9p) ([raw file](https://github.com/starkware-libs/stwo/blob/7d4609dd362b38b665f513476c384a1e94d8b6f3/crates/prover/src/examples/blake/mod.rs#L117)):*
> ```XML
>         unsafe { PackedBaseField::from_simd_unchecked(x >> 16) },
>     ]
> }
> ```

Need another name and place for that



_Code quote:_
```XML
fn to_felts(x: &u32x16) -> [PackedBaseField; 2] {
    [
        unsafe { PackedBaseField::from_simd_unchecked(x & u32x16::splat(0xffff)) },
        unsafe { PackedBaseField::from_simd_unchecked(x >> 16) },
    ]
}
```
___
*[`crates/prover/src/examples/blake/scheduler/constraints.rs` line 19 at r3](https://reviewable.io/reviews/starkware-libs/stwo/770#-O3b2IS31glLdnh1R57W:-O3b2IS31glLdnh1R57X:b-692nzk) ([raw file](https://github.com/starkware-libs/stwo/blob/7d4609dd362b38b665f513476c384a1e94d8b6f3/crates/prover/src/examples/blake/scheduler/constraints.rs#L19)):*
> ```XML
>     pub fn eval(mut self) -> E {
>         let messages: [Fu32<E::F>; 16] = std::array::from_fn(|_| self.next_u32());
>         let states: [[Fu32<E::F>; 16]; N_ROUNDS + 1] =
> ```

the + 1 is since you need to store the initial and last states, right?



_Suggestion:_
```XML
let round_states: [[Fu32<E::F>; 16]; N_ROUNDS + 1] =
```
___
*[`crates/prover/src/examples/blake/scheduler/constraints.rs` line 20 at r3](https://reviewable.io/reviews/starkware-libs/stwo/770#-O3b1x3Q5Te7JeuxbMGt:-O3b1x3Q5Te7JeuxbMGu:bnn4mml) ([raw file](https://github.com/starkware-libs/stwo/blob/7d4609dd362b38b665f513476c384a1e94d8b6f3/crates/prover/src/examples/blake/scheduler/constraints.rs#L20)):*
> ```XML
>         let messages: [Fu32<E::F>; 16] = std::array::from_fn(|_| self.next_u32());
>         let states: [[Fu32<E::F>; 16]; N_ROUNDS + 1] =
>             std::array::from_fn(|_| std::array::from_fn(|_| self.next_u32()));
> ```

Those constants would induce a problem when moving to VeryPacked 



_Suggestion:_
```XML
        let messages: [Fu32<E::F>; N_LANES] = std::array::from_fn(|_| self.next_u32());
        let states: [[Fu32<E::F>; N_LANES]; N_ROUNDS + 1] =
            std::array::from_fn(|_| std::array::from_fn(|_| self.next_u32()));
```
___
*[`crates/prover/src/examples/blake/scheduler/constraints.rs` line 65 at r3](https://reviewable.io/reviews/starkware-libs/stwo/770#-O3b2rw27l0r9aZ4BLxL:-O3b2rw39CrOlVpqIHvC:begdh3) ([raw file](https://github.com/starkware-libs/stwo/blob/7d4609dd362b38b665f513476c384a1e94d8b6f3/crates/prover/src/examples/blake/scheduler/constraints.rs#L65)):*
> ```XML
>         let h = self.eval.next_trace_mask();
>         Fu32 { l, h }
>     }
> ```

FYI You already has this function in round



_Code quote:_
```XML
    fn next_u32(&mut self) -> Fu32<E::F> {
        let l = self.eval.next_trace_mask();
        let h = self.eval.next_trace_mask();
        Fu32 { l, h }
    }
```

**Review by shaharsamocha7 — COMMENTED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/770)* status: 5 of 7 files reviewed, 10 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/770)* status: 5 of 7 files reviewed, 9 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/prover/src/examples/blake/mod.rs` line 117 at r3](https://reviewable.io/reviews/starkware-libs/stwo/770#-O3b35xzAi18V8h0eou2:-O3bBBcl9yuzxclpptL0:bw3cg0w) ([raw file](https://github.com/starkware-libs/stwo/blob/7d4609dd362b38b665f513476c384a1e94d8b6f3/crates/prover/src/examples/blake/mod.rs#L117)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Need another name and place for that
</blockquote></details>

Suggestions are welcome
___
*[`crates/prover/src/examples/blake/round/gen.rs` line 103 at r3](https://reviewable.io/reviews/starkware-libs/stwo/770#-O3az1MRC1bxxImpXBBy:-O3b32I07-CuHPcNbWSf:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/7d4609dd362b38b665f513476c384a1e94d8b6f3/crates/prover/src/examples/blake/round/gen.rs#L103)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Rename
</blockquote></details>

Done.
___
*[`crates/prover/src/examples/blake/round/mod.rs` line 6 at r3](https://reviewable.io/reviews/starkware-libs/stwo/770#-O3azDlF3hAocqR2dOcI:-O3b337q0rmxb-0gtu8b:bewcb1c) ([raw file](https://github.com/starkware-libs/stwo/blob/7d4609dd362b38b665f513476c384a1e94d8b6f3/crates/prover/src/examples/blake/round/mod.rs#L6)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

what's r#?
</blockquote></details>

gen is apparently some reserved word, r# is for "raw", I believe.
___
*[`crates/prover/src/examples/blake/scheduler/constraints.rs` line 19 at r3](https://reviewable.io/reviews/starkware-libs/stwo/770#-O3b2IS31glLdnh1R57W:-O3b3BEp04124B-WdB1Q:b2nign6) ([raw file](https://github.com/starkware-libs/stwo/blob/7d4609dd362b38b665f513476c384a1e94d8b6f3/crates/prover/src/examples/blake/scheduler/constraints.rs#L19)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

the + 1 is since you need to store the initial and last states, right?
</blockquote></details>

yes
___
*[`crates/prover/src/examples/blake/scheduler/constraints.rs` line 20 at r3](https://reviewable.io/reviews/starkware-libs/stwo/770#-O3b1x3Q5Te7JeuxbMGt:-O3b3J0z3xOfOMw6fVWP:b-q2lk9d) ([raw file](https://github.com/starkware-libs/stwo/blob/7d4609dd362b38b665f513476c384a1e94d8b6f3/crates/prover/src/examples/blake/scheduler/constraints.rs#L20)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Those constants would induce a problem when moving to VeryPacked
</blockquote></details>

It's not 16 for packing. It's 16 because that's the state size for blake:)
___
*[`crates/prover/src/examples/blake/scheduler/constraints.rs` line 65 at r3](https://reviewable.io/reviews/starkware-libs/stwo/770#-O3b2rw27l0r9aZ4BLxL:-O3b3XPw5pc0RF6tSRK0:byr4flj) ([raw file](https://github.com/starkware-libs/stwo/blob/7d4609dd362b38b665f513476c384a1e94d8b6f3/crates/prover/src/examples/blake/scheduler/constraints.rs#L65)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

FYI You already has this function in round
</blockquote></details>

Right.
___
*[`crates/prover/src/examples/blake/scheduler/gen.rs` line 72 at r3](https://reviewable.io/reviews/starkware-libs/stwo/770#-O3b-6Vc5cCUpGbRBe4I:-O3bCA874D9qnNAZL8EK:b-17mldp) ([raw file](https://github.com/starkware-libs/stwo/blob/7d4609dd362b38b665f513476c384a1e94d8b6f3/crates/prover/src/examples/blake/scheduler/gen.rs#L72)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Extract to `write_u32_array` func
</blockquote></details>

That would require me to either make another TraceGen struct, or pass vec_row,trace,&mut col_index, x to the function. Is it worth it?
___
*[`crates/prover/src/examples/blake/scheduler/gen.rs` line 93 at r3](https://reviewable.io/reviews/starkware-libs/stwo/770#-O3b0BiM0kG0iPi8FyRq:-O3b3z049cuH9Nua-0li:b-fdakge) ([raw file](https://github.com/starkware-libs/stwo/blob/7d4609dd362b38b665f513476c384a1e94d8b6f3/crates/prover/src/examples/blake/scheduler/gen.rs#L93)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Don't you also need round_id or something?
How do we know that we used the correct `round_m` for the round input?
</blockquote></details>

round function given the permuted message, does not depend on the round id. You can think of blake as applying the pure `v=round(v,m[SIGMA[round_id]])` a few times. So, if the lookup to the round() call provides m[SIGMA[round_id]], we dont need to pass round_id.
___
*[`crates/prover/src/examples/blake/scheduler/gen.rs` line 145 at r3](https://reviewable.io/reviews/starkware-libs/stwo/770#-O3b0mRv5fStGJD9K2nH:-O3b4cRg4u12-MJPAlzh:b4o34h7) ([raw file](https://github.com/starkware-libs/stwo/blob/7d4609dd362b38b665f513476c384a1e94d8b6f3/crates/prover/src/examples/blake/scheduler/gen.rs#L145)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Please add a comment here that you 
Combine the lookups for blake yield with blake round in case of odd number of blake rounds.

IMO, you should discard this code and just add it separately as we currently only targeting Blake2s.
</blockquote></details>

I want to be able to show blake3 benchmarks as well, though. They are more impressive. 
___
*[`crates/prover/src/examples/blake/scheduler/mod.rs` line 7 at r3](https://reviewable.io/reviews/starkware-libs/stwo/770#-O3b1mwC4MIv4ZJew7HL:-O3bB-dk1GyoNlbalZxx:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/7d4609dd362b38b665f513476c384a1e94d8b6f3/crates/prover/src/examples/blake/scheduler/mod.rs#L7)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

consider to rename
</blockquote></details>

Done.

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/770)* status: 1 of 8 files reviewed, 5 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/examples/blake/round/mod.rs` line 6 at r3](https://reviewable.io/reviews/starkware-libs/stwo/770#-O3azDlF3hAocqR2dOcI:-O3bErAX4vh1B7xnrrJE:b32w6i) ([raw file](https://github.com/starkware-libs/stwo/blob/7d4609dd362b38b665f513476c384a1e94d8b6f3/crates/prover/src/examples/blake/round/mod.rs#L6)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

gen is apparently some reserved word, r# is for "raw", I believe.
</blockquote></details>

Ty
___
*[`crates/prover/src/examples/blake/scheduler/constraints.rs` line 20 at r3](https://reviewable.io/reviews/starkware-libs/stwo/770#-O3b1x3Q5Te7JeuxbMGt:-O3bF2XG2YjDBGEXJ1gx:bla2jqy) ([raw file](https://github.com/starkware-libs/stwo/blob/7d4609dd362b38b665f513476c384a1e94d8b6f3/crates/prover/src/examples/blake/scheduler/constraints.rs#L20)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

It's not 16 for packing. It's 16 because that's the state size for blake:)
</blockquote></details>

oh yeah, my bad
___
*[`crates/prover/src/examples/blake/scheduler/constraints.rs` line 28 at r4](https://reviewable.io/reviews/starkware-libs/stwo/770#-O3bGU6C7NwAgWy14py_:-O3bGU6C7NwAgWy14pya:b-hbz6of) ([raw file](https://github.com/starkware-libs/stwo/blob/9cb700dbe8f7d68dadb4daec9f862641604d04ee/crates/prover/src/examples/blake/scheduler/constraints.rs#L28)):*
> ```XML
>             let output_state = &states[i + 1];
>             let round_messages: [Fu32<E::F>; STATE_SIZE] =
>                 std::array::from_fn(|j| messages[SIGMA[i][j] as usize]);
> ```

Suggestion:



_Suggestion:_
```XML
            let round_messages: [Fu32<E::F>; STATE_SIZE] = SIGMA[i].map(|j| messages[j as usize]);
```
___
*[`crates/prover/src/examples/blake/scheduler/gen.rs` line 72 at r3](https://reviewable.io/reviews/starkware-libs/stwo/770#-O3b-6Vc5cCUpGbRBe4I:-O3bFBRx1R9TWAri98Uk:bsrg9o1) ([raw file](https://github.com/starkware-libs/stwo/blob/7d4609dd362b38b665f513476c384a1e94d8b6f3/crates/prover/src/examples/blake/scheduler/gen.rs#L72)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

That would require me to either make another TraceGen struct, or pass vec_row,trace,&mut col_index, x to the function. Is it worth it?
</blockquote></details>

so rename it?
___
*[`crates/prover/src/examples/blake/scheduler/mod.rs` line 7 at r3](https://reviewable.io/reviews/starkware-libs/stwo/770#-O3b1mwC4MIv4ZJew7HL:-O3bGqjPBa6ZAH91UEXL:b5ybf04) ([raw file](https://github.com/starkware-libs/stwo/blob/7d4609dd362b38b665f513476c384a1e94d8b6f3/crates/prover/src/examples/blake/scheduler/mod.rs#L7)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I thought the official for that is "Noted" :)

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/770)* status: 1 of 8 files reviewed, 5 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/examples/blake/mod.rs` line 117 at r3](https://reviewable.io/reviews/starkware-libs/stwo/770#-O3b35xzAi18V8h0eou2:-O3bHGWW5Mw_aolSVlIC:b-tz2jm2) ([raw file](https://github.com/starkware-libs/stwo/blob/7d4609dd362b38b665f513476c384a1e94d8b6f3/crates/prover/src/examples/blake/mod.rs#L117)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Suggestions are welcome
</blockquote></details>

Move to the gen.rs file
and also Fu32 to the constraints file

WDYT?

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/770)* status: 1 of 8 files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`crates/prover/src/examples/blake/mod.rs` line 117 at r3](https://reviewable.io/reviews/starkware-libs/stwo/770#-O3b35xzAi18V8h0eou2:-O3c5CBPE-xow1ElpClD:bjbywsw) ([raw file](https://github.com/starkware-libs/stwo/blob/7d4609dd362b38b665f513476c384a1e94d8b6f3/crates/prover/src/examples/blake/mod.rs#L117)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Move to the gen.rs file
and also Fu32 to the constraints file

WDYT?
</blockquote></details>

Those would be new gen and constraint files, since these are common to several components (that's why they are in blake, and not round or scheduler).
___
*[`crates/prover/src/examples/blake/scheduler/mod.rs` line 7 at r3](https://reviewable.io/reviews/starkware-libs/stwo/770#-O3b1mwC4MIv4ZJew7HL:-O3b8n2V4psbmx1inypr:bqjcaz1) ([raw file](https://github.com/starkware-libs/stwo/blob/7d4609dd362b38b665f513476c384a1e94d8b6f3/crates/prover/src/examples/blake/scheduler/mod.rs#L7)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I thought the official for that is "Noted" :)
</blockquote></details>

I fixed it! I adde BlakeElements below!  thought that's what you wanted.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 7 files at r4, 1 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/770#-:-O3cD4r4C6r_gLZKrL1D:bnfp4nl)* status: 5 of 8 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/prover/src/examples/blake/scheduler/gen.rs` line 71 at r4](https://reviewable.io/reviews/starkware-libs/stwo/770#-O3cCo4p0awF0akn2nvU:-O3cCo4qBEN6Ik6i0f-t:bt87j6x) ([raw file](https://github.com/starkware-libs/stwo/blob/9cb700dbe8f7d68dadb4daec9f862641604d04ee/crates/prover/src/examples/blake/scheduler/gen.rs#L71)):*
> ```XML
>                     unsafe { PackedBaseField::from_simd_unchecked(*x >> 16) };
>                 *col_index += 2;
>             });
> ```

Suggestion



_Suggestion:_
```XML
            x.iter().for_each(|x| {
                to_felts(x).iter().enumerate().for_each(|(i, val)| {
                    trace[*col_index + i].data[vec_row] = *val;
                });
                *col_index += 2;
            });
```
___
*[`crates/prover/src/examples/blake/scheduler/mod.rs` line 7 at r3](https://reviewable.io/reviews/starkware-libs/stwo/770#-O3b1mwC4MIv4ZJew7HL:-O3cBGCbAYzrICjP3p8J:b6425tb) ([raw file](https://github.com/starkware-libs/stwo/blob/7d4609dd362b38b665f513476c384a1e94d8b6f3/crates/prover/src/examples/blake/scheduler/mod.rs#L7)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I fixed it! I adde BlakeElements below!  thought that's what you wanted.
</blockquote></details>

It was, I didn't see it

Ohh lol, I l knew that this `Done` is tricky

**Review by shaharsamocha7 — APPROVED** [review]
> Reviewed 1 of 7 files at r4, 1 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/770)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
