### PR TITLE
Verify lookups.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/675)

### CODE REVIEW

**Comment by alonh5** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/675?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#675** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/675?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#672** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/672?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#674](https://github.com/starkware-libs/stwo/pull/674) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/674?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#671** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/671?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#669** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/669?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#667** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/667?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#664** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/664?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#662** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/662?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#646** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/646?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#644** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/644?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#654](https://github.com/starkware-libs/stwo/pull/654) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/654?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#642** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/642?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#639** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/639?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#638** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/638?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#637** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/637?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#636** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/636?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#651** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/651?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — COMMENTED** [review]
Implement only on Air, not on components

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/675#-:-O1Vhx2-EJSX3wEGrudi:bfn2jsr)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @andrewmilson and @shaharsamocha7)

**Review by alonh5 — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/675#-:-O1Vl7eI6Osz83XXkOrr:b-896fix)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @andrewmilson and @shaharsamocha7)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 8 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/675#-:-O1VluRq22Kn7NXueYwN:bnfp4nl)* status: 8 of 9 files reviewed, all discussions resolved (waiting on @andrewmilson and @shaharsamocha7)

**Review by alonh5 — COMMENTED** [review]
> Reviewed 1 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/675)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @andrewmilson and @shaharsamocha7)

**Pull request merged**
