### PR TITLE
Create component traces with air and commitment scheme.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/442)

### CODE REVIEW

**Comment by alonh5** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/442?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#442** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/442?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#436** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/436?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/442)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

___
*[`src/core/air/mod.rs` line 268 at r1](https://reviewable.io/reviews/starkware-libs/stwo/442#-NsMNqrIAVUuigkV0uYL:-NsMNqrIAVUuigkV0uYM:b-2didq6) ([raw file](https://github.com/starkware-libs/stwo/blob/856128a0eb983ca18a7da0fecf721c5c4a214a19/src/core/air/mod.rs#L268)):*
> ```XML
> }
> 
> struct ComponentTracesVisitor<'a, B: Backend> {
> ```

We should move AirExt and all of these implementtations into an inner module.
This file should contain the Air and Component traits, and do a pub use for AirExt.
___
*[`src/core/air/mod.rs` line 274 at r1](https://reviewable.io/reviews/starkware-libs/stwo/442#-NsMOGaz4lxI8U1nZn9p:-NsMOGaz4lxI8U1nZn9q:b-un7ikq) ([raw file](https://github.com/starkware-libs/stwo/blob/856128a0eb983ca18a7da0fecf721c5c4a214a19/src/core/air/mod.rs#L274)):*
> ```XML
> 
> impl<'a, B: Backend> ComponentTracesVisitor<'a, B> {
>     pub fn new(polynomials: &'a [CirclePoly<B, BaseField>]) -> Self {
> ```

I don't think we need the new() and finalize() on each one of these. The struct is private and this is only gonna be used as a helper in a single place in the AirExt impl. We can do it there.
Right now, I need 2 extra hops to read the code (dive into new and finalize, which are far from the caller).

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/442#-:-NsMP2cx2wEQLl5hasAV:bnfp4nl)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/442)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`src/core/air/mod.rs` line 268 at r1](https://reviewable.io/reviews/starkware-libs/stwo/442#-NsMNqrIAVUuigkV0uYL:-NsN3vJM0LwG0F_ekFHa:brkmsm4) ([raw file](https://github.com/starkware-libs/stwo/blob/856128a0eb983ca18a7da0fecf721c5c4a214a19/src/core/air/mod.rs#L268)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

We should move AirExt and all of these implementtations into an inner module.
This file should contain the Air and Component traits, and do a pub use for AirExt.
</blockquote></details>

I'll do this in a new PR.
___
*[`src/core/air/mod.rs` line 274 at r1](https://reviewable.io/reviews/starkware-libs/stwo/442#-NsMOGaz4lxI8U1nZn9p:-NsN5nSs32MRpPamnKlB:b-ccyuvu) ([raw file](https://github.com/starkware-libs/stwo/blob/856128a0eb983ca18a7da0fecf721c5c4a214a19/src/core/air/mod.rs#L274)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I don't think we need the new() and finalize() on each one of these. The struct is private and this is only gonna be used as a helper in a single place in the AirExt impl. We can do it there.
Right now, I need 2 extra hops to read the code (dive into new and finalize, which are far from the caller).
</blockquote></details>

Also in a new PR.

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/442)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Pull request merged**
