### PR TITLE
Poseidon2

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/683)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
* **#683** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/683?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/683)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/prover/src/examples/poseidon/mod.rs` line 184 at r1](https://reviewable.io/reviews/starkware-libs/stwo/683#-O0c8d8yBKScoWIefR5e:-O0c8d8yBKScoWIefR5f:b7on6sw) ([raw file](https://github.com/starkware-libs/stwo/blob/0610c88550887a60a972fe49a73882311fb2be06/crates/prover/src/examples/poseidon/mod.rs#L184)):*
> ```XML
> // Applies the internal round matrix.
> // See https://eprint.iacr.org/2023/323.pdf 5.2 .
> fn apply_internal_round_matrix<F>(state: &mut [F; 16])
> ```

Do we need to add round constants here?



_Code quote:_
```XML
fn apply_internal_round_matrix<F>(state: &mut [F; 16])
```

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/683)* status: all files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/examples/poseidon/mod.rs` line 183 at r1](https://reviewable.io/reviews/starkware-libs/stwo/683#-O0cHmYV-upSOtixgz7Q:-O0cHmYV-upSOtixgz7R:bm3mk9l) ([raw file](https://github.com/starkware-libs/stwo/blob/0610c88550887a60a972fe49a73882311fb2be06/crates/prover/src/examples/poseidon/mod.rs#L183)):*
> ```XML
> 
> // Applies the internal round matrix.
> // See https://eprint.iacr.org/2023/323.pdf 5.2 .
> ```

Can you state here what are the \mu that you are using?



_Code quote:_
```XML
// See https://eprint.iacr.org/2023/323.pdf 5.2 .
```
___
*[`crates/prover/src/examples/poseidon/mod.rs` line 188 at r1](https://reviewable.io/reviews/starkware-libs/stwo/683#-O0cHQui87u5K555J_-M:-O0cHQujB0HSqOQRKluj:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/0610c88550887a60a972fe49a73882311fb2be06/crates/prover/src/examples/poseidon/mod.rs#L188)):*
> ```XML
>     F: Copy + AddAssign<F> + Add<F, Output = F> + Sub<F, Output = F> + Mul<BaseField, Output = F>,
> {
>     // TODO(spapini): Check that these coefficients are good according to Seciotn 5.3 of Poseidon2
> ```





_Suggestion:_
```XML
// TODO(spapini): Check that these coefficients are good according to Section 5.3 of Poseidon2
```

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/683)* status: all files reviewed, 4 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/examples/poseidon/mod.rs` line 334 at r1](https://reviewable.io/reviews/starkware-libs/stwo/683#-O0cPHLz8GGD1_ya7qHj:-O0cPHLz8GGD1_ya7qHk:byp18fd) ([raw file](https://github.com/starkware-libs/stwo/blob/0610c88550887a60a972fe49a73882311fb2be06/crates/prover/src/examples/poseidon/mod.rs#L334)):*
> ```XML
> }
> 
> // TODO(AlonH): Implement.
> ```

Remove



_Code quote:_
```XML
// TODO(AlonH): Implement.
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/683)* status: 5 of 7 files reviewed, 4 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/prover/src/examples/poseidon/mod.rs` line 183 at r1](https://reviewable.io/reviews/starkware-libs/stwo/683#-O0cHmYV-upSOtixgz7Q:-O0cTba73LiopbYXMR9n:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/0610c88550887a60a972fe49a73882311fb2be06/crates/prover/src/examples/poseidon/mod.rs#L183)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can you state here what are the \mu that you are using?
</blockquote></details>

Done.
___
*[`crates/prover/src/examples/poseidon/mod.rs` line 188 at r1](https://reviewable.io/reviews/starkware-libs/stwo/683#-O0cHQui87u5K555J_-M:-O0cTcCc36dJh08RXQTd:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/0610c88550887a60a972fe49a73882311fb2be06/crates/prover/src/examples/poseidon/mod.rs#L188)):*
> ```XML
>     F: Copy + AddAssign<F> + Add<F, Output = F> + Sub<F, Output = F> + Mul<BaseField, Output = F>,
> {
>     // TODO(spapini): Check that these coefficients are good according to Seciotn 5.3 of Poseidon2
> ```

Done.
___
*[`crates/prover/src/examples/poseidon/mod.rs` line 334 at r1](https://reviewable.io/reviews/starkware-libs/stwo/683#-O0cPHLz8GGD1_ya7qHj:-O0cT_yQ21Wrh3ZLF8lM:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/0610c88550887a60a972fe49a73882311fb2be06/crates/prover/src/examples/poseidon/mod.rs#L334)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Remove
</blockquote></details>

Done.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/683#-:-O0cbuzK6ISCw9Y0X55K:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/683)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`crates/prover/src/examples/poseidon/mod.rs` line 184 at r1](https://reviewable.io/reviews/starkware-libs/stwo/683#-O0c8d8yBKScoWIefR5e:-O0cj0cODzwWpKKktmLl:b-55x3vo) ([raw file](https://github.com/starkware-libs/stwo/blob/0610c88550887a60a972fe49a73882311fb2be06/crates/prover/src/examples/poseidon/mod.rs#L184)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Do we need to add round constants here?
</blockquote></details>

Added at the callsite

**Review by shaharsamocha7 — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/683)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by shaharsamocha7 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/683)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
