### PR TITLE
Packed QM31

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/416)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/416?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#416** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/416?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#415** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/415?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#414** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/414?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by ilyalesokhin-starkware** [comment]
*[`src/core/backend/avx512/cm31.rs` line 7 at r1](https://reviewable.io/reviews/starkware-libs/stwo/416#-Ns2NxqX4BiD4ma9N8_w:-Ns2NxqX4BiD4ma9N8_x:b-kl43c0) ([raw file](https://github.com/starkware-libs/stwo/blob/4c8ce77c5ba48c1b65f15ca3285b374446ba5760/src/core/backend/avx512/cm31.rs#L7)):*
> ```XML
> 
> #[derive(Copy, Clone)]
> pub struct PackedCM31(pub [PackedBaseField; 2]);
> ```

document



_Code quote:_
```XML
pub struct PackedCM31(pub [PackedBaseField; 2]);
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/416)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @ohad-starkware)

___
*[`src/core/backend/avx512/cm31.rs` line 7 at r1](https://reviewable.io/reviews/starkware-libs/stwo/416#-Ns2NxqX4BiD4ma9N8_w:-Ns2SIbcBojqMrPInwz-:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/4c8ce77c5ba48c1b65f15ca3285b374446ba5760/src/core/backend/avx512/cm31.rs#L7)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

document
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/416#-:-Ns2ZRg1DB16yyYGuQ92:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ohad-starkware)

**Pull request merged**
