### PR TITLE
Implement MleOps for SIMD backend

### PR DESCRIPTION
**Pull request by andrewmilson**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/629)

### CODE REVIEW

**Comment by andrewmilson** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/629?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#630** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/630?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#629** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/629?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#623** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/623?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#620** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/620?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#621** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/621?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#581** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/581?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#617** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/617?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#616** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/616?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#615** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/615?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#614** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/614?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#613** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/613?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#612** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/612?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#611** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/611?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#610** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/610?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#609** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/609?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#608** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/608?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#607** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/607?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#606** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/606?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#605** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/605?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#604** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/604?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#603** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/603?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#599** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/599?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#596** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/596?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#602** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/602?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#595** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/595?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#601** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/601?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#594** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/594?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#600** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/600?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#593** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/593?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#592** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/592?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#591** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/591?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @andrewmilson and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/629)* status: all files reviewed, 2 unresolved discussions (waiting on @andrewmilson)

___
*[`crates/prover/src/core/backend/simd/lookups/mle.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/stwo/629#-O04YjNL2fQPB754uuYG:-O04YjNL2fQPB754uuYH:bismsz) ([raw file](https://github.com/starkware-libs/stwo/blob/5555a3e7aa66b73d9291d72265c4070bd610434b/crates/prover/src/core/backend/simd/lookups/mle.rs#L36)):*
> ```XML
>         let res = zip(lhs_evals, rhs_evals)
>             // Equivalent to `eq(0, assignment) * lhs_eval + eq(1, assignment) * rhs_eval`.
>             .map(|(&lhs_eval, &rhs_eval)| assignment * (rhs_eval - lhs_eval) + lhs_eval)
> ```

Consider having a `fold_packed_mle_evals`



_Code quote:_
```XML
            // Equivalent to `eq(0, assignment) * lhs_eval + eq(1, assignment) * rhs_eval`.
            .map(|(&lhs_eval, &rhs_eval)| assignment * (rhs_eval - lhs_eval) + lhs_eval)
```
___
*[`crates/prover/src/core/backend/simd/lookups/mle.rs` line 122 at r1](https://reviewable.io/reviews/starkware-libs/stwo/629#-O04am_S7cjX5E6oghCm:-O04am_S7cjX5E6oghCn:b-q6327j) ([raw file](https://github.com/starkware-libs/stwo/blob/5555a3e7aa66b73d9291d72265c4070bd610434b/crates/prover/src/core/backend/simd/lookups/mle.rs#L122)):*
> ```XML
> 
>     #[test]
>     fn sumcheck_works() {
> ```

Is this the correct place for this test?



_Code quote:_
```XML
    fn sumcheck_works() {
```

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/629)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`crates/prover/src/core/backend/simd/lookups/mle.rs` line 122 at r1](https://reviewable.io/reviews/starkware-libs/stwo/629#-O04am_S7cjX5E6oghCm:-O0C9x1CCtYZdBs5NWpD:b7pk50g) ([raw file](https://github.com/starkware-libs/stwo/blob/5555a3e7aa66b73d9291d72265c4070bd610434b/crates/prover/src/core/backend/simd/lookups/mle.rs#L122)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Is this the correct place for this test?
</blockquote></details>

Removed this test.
Added others.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/629#-:-O0Juy5o0CByRVEgnZKk:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @andrewmilson)

___
*[`crates/prover/src/core/backend/simd/lookups/mle.rs` line 121 at r2](https://reviewable.io/reviews/starkware-libs/stwo/629#-O0JuoWj2zhvO9ZAGB0k:-O0JuoWj2zhvO9ZAGB0l:bzdzad3) ([raw file](https://github.com/starkware-libs/stwo/blob/e175251eddf922c782ab710606bccec238633ffe/crates/prover/src/core/backend/simd/lookups/mle.rs#L121)):*
> ```XML
> 
> /// Computes all `eq(0, assignment_i) * lhs_eval_i + eq(1, assignment_i) * rhs_eval_i`.
> // TODO: Consider unifying fold_packed_mle_* functions once we have something like
> ```

Please put your name in the todo's. can be fixed later



_Code quote:_
```XML
TODO: 
```

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/629)* status: all files reviewed, 4 unresolved discussions (waiting on @andrewmilson)

___
*[`crates/prover/src/core/backend/simd/lookups/mle.rs` line 23 at r2](https://reviewable.io/reviews/starkware-libs/stwo/629#-O1plk6Q06huBN4MvZKm:-O1plk6Q06huBN4MvZKn:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/89a31c7bea11352456cae67a0721d20d7fb32029/crates/prover/src/core/backend/simd/lookups/mle.rs#L23)):*
> ```XML
>         let midpoint = mle.len() / 2;
> 
>         // Use CPU backend to to prevent dealing with instances smaller than `PackedSecureField`.
> ```





_Suggestion:_
```XML
// Use CPU backend to to avoid dealing with instances smaller than `PackedSecureField`.
```
___
*[`crates/prover/src/core/backend/simd/lookups/mle.rs` line 44 at r2](https://reviewable.io/reviews/starkware-libs/stwo/629#-O1pmYqZAnQH_ltUEybS:-O1pmYqZAnQH_ltUEybT:b-5vivzj) ([raw file](https://github.com/starkware-libs/stwo/blob/89a31c7bea11352456cae67a0721d20d7fb32029/crates/prover/src/core/backend/simd/lookups/mle.rs#L44)):*
> ```XML
> }
> 
> impl MleOps<SecureField> for SimdBackend {
> ```

Looks like exactly the same code. Can you unite by negin generic on F and EF, and requiring some ops?
Such as F: Mul<SecureField, Output=EF>
I head a similar issue at `crates/prover/src/constraint_framework/mod.rs`. Currently have a todo to use a better trait, so you can copy that TODO here as well, in addition.



_Code quote:_
```XML
impl MleOps<SecureField> for SimdBackend {
```
___
*[`crates/prover/src/core/backend/simd/lookups/mle.rs` line 78 at r2](https://reviewable.io/reviews/starkware-libs/stwo/629#-O1pnYSj3rfoTEqfOPUY:-O1pnYSj3rfoTEqfOPUZ:b-y2l7dz) ([raw file](https://github.com/starkware-libs/stwo/blob/89a31c7bea11352456cae67a0721d20d7fb32029/crates/prover/src/core/backend/simd/lookups/mle.rs#L78)):*
> ```XML
> }
> 
> impl MultivariatePolyOracle for Mle<SimdBackend, SecureField> {
> ```

Do we actually need this?
It seems a bit wierd, since you're trying to represent this Mle as a multilinear polynomial of it self. Why would we ever require this?
Seems to me that when we get a query to the first layer, the Mle, we can just answer the query directly using the reduction.

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/629)* status: all files reviewed, 5 unresolved discussions (waiting on @andrewmilson)

___
*[`crates/prover/src/core/backend/simd/lookups/mle.rs` line 123 at r2](https://reviewable.io/reviews/starkware-libs/stwo/629#-O1pqQ3SDqoaell6nw1K:-O1pqQ3SDqoaell6nw1L:bldztzt) ([raw file](https://github.com/starkware-libs/stwo/blob/89a31c7bea11352456cae67a0721d20d7fb32029/crates/prover/src/core/backend/simd/lookups/mle.rs#L123)):*
> ```XML
> // TODO: Consider unifying fold_packed_mle_* functions once we have something like
> // AbstractField/AbstractExtensionField traits implemented on packed types.
> fn fold_packed_mle_secure_evals(
> ```

Same as above, this can be generic on F and EF

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/629)* status: all files reviewed, 5 unresolved discussions (waiting on @andrewmilson)

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/629)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/lookups/mle.rs` line 23 at r2](https://reviewable.io/reviews/starkware-libs/stwo/629#-O1plk6Q06huBN4MvZKm:-O1wm6_74UPTuKTzrkiN:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/6b5a7f9a04ab8f3e622160fdaf09e5b1a04d8741/crates/prover/src/core/backend/simd/lookups/mle.rs#L23)):*
> ```XML
>         let midpoint = mle.len() / 2;
> 
>         // Use CPU backend to to prevent dealing with instances smaller than `PackedSecureField`.
> ```

Done.
___
*[`crates/prover/src/core/backend/simd/lookups/mle.rs` line 44 at r2](https://reviewable.io/reviews/starkware-libs/stwo/629#-O1pmYqZAnQH_ltUEybS:-O1wjviT1eheo9qxtGky:bmlrhin) ([raw file](https://github.com/starkware-libs/stwo/blob/6b5a7f9a04ab8f3e622160fdaf09e5b1a04d8741/crates/prover/src/core/backend/simd/lookups/mle.rs#L44)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Looks like exactly the same code. Can you unite by negin generic on F and EF, and requiring some ops?
Such as F: Mul<SecureField, Output=EF>
I head a similar issue at `crates/prover/src/constraint_framework/mod.rs`. Currently have a todo to use a better trait, so you can copy that TODO here as well, in addition.
</blockquote></details>

This implementation modifies in place but the other makes an allocation which makes it hard to unify.
___
*[`crates/prover/src/core/backend/simd/lookups/mle.rs` line 78 at r2](https://reviewable.io/reviews/starkware-libs/stwo/629#-O1pnYSj3rfoTEqfOPUY:-O1weHVB0Cw-mlWBz8yH:b-5mw4c9) ([raw file](https://github.com/starkware-libs/stwo/blob/6b5a7f9a04ab8f3e622160fdaf09e5b1a04d8741/crates/prover/src/core/backend/simd/lookups/mle.rs#L78)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Do we actually need this?
It seems a bit wierd, since you're trying to represent this Mle as a multilinear polynomial of it self. Why would we ever require this?
Seems to me that when we get a query to the first layer, the Mle, we can just answer the query directly using the reduction.
</blockquote></details>

Done. Removed
___
*[`crates/prover/src/core/backend/simd/lookups/mle.rs` line 121 at r2](https://reviewable.io/reviews/starkware-libs/stwo/629#-O0JuoWj2zhvO9ZAGB0k:-O1wlOm2CQ-hl-6jfFNj:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/6b5a7f9a04ab8f3e622160fdaf09e5b1a04d8741/crates/prover/src/core/backend/simd/lookups/mle.rs#L121)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Please put your name in the todo's. can be fixed later
</blockquote></details>

Done.
___
*[`crates/prover/src/core/backend/simd/lookups/mle.rs` line 123 at r2](https://reviewable.io/reviews/starkware-libs/stwo/629#-O1pqQ3SDqoaell6nw1K:-O1wlOIR0l_WcWygNqGv:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/6b5a7f9a04ab8f3e622160fdaf09e5b1a04d8741/crates/prover/src/core/backend/simd/lookups/mle.rs#L123)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Same as above, this can be generic on F and EF
</blockquote></details>

Done.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/629#-:-O1zmHyr3rP9tFR0Nmfs:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @andrewmilson)

___
*[`crates/prover/src/core/backend/simd/lookups/mle.rs` line 23 at r2](https://reviewable.io/reviews/starkware-libs/stwo/629#-O1plk6Q06huBN4MvZKm:-O1zlUkp5N76_3OSo2fZ:b-tywqfo) ([raw file](https://github.com/starkware-libs/stwo/blob/6b5a7f9a04ab8f3e622160fdaf09e5b1a04d8741/crates/prover/src/core/backend/simd/lookups/mle.rs#L23)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Remove extra 'to'

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/629)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/lookups/mle.rs` line 23 at r2](https://reviewable.io/reviews/starkware-libs/stwo/629#-O1plk6Q06huBN4MvZKm:-O201RC89rbhrXmGPIbD:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/6b5a7f9a04ab8f3e622160fdaf09e5b1a04d8741/crates/prover/src/core/backend/simd/lookups/mle.rs#L23)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Remove extra 'to'
</blockquote></details>

Done.

**Pull request merged**
