### PR TITLE
Add new PolyOps trait for evaluating many polynomials (columns) in the commitment extension

### PR DESCRIPTION
**Pull request by jarnesino**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/854)

### CODE REVIEW

**Comment by jarnesino** [comment]
> > Reviewed all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/854)_ status: 0 of 2 files reviewed, all discussions resolved
> 
> _[`crates/prover/src/core/poly/circle/ops.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/stwo/854#-O80Zeic7Km1B_yzA80l:-O80Zeic7Km1B_yzA80m:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/bda3932f36c80d22b9c131a3c057cd2112e59836/crates/prover/src/core/poly/circle/ops.rs#L50)):_
> 
> > ```
> >     /// Evaluates all polynomials at all points in the domain.
> >     /// Used by the [`CommitmentTreeProver::new()`] function.
> >     fn evaluate_columns(
> > ```
> 
> _Suggestion:_
> 
> ```
> evaluate_polynomials
> ```

Done!

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/854)* status: all files reviewed, 1 unresolved discussion (waiting on @jarnesino and @ohad-starkware)

___
*[`crates/prover/src/core/pcs/prover.rs` line 216 at r2](https://reviewable.io/reviews/starkware-libs/stwo/854#-O8VdrQh-5-kDhkYMHbf:-O8VdrQh-5-kDhkYMHbg:bw2ouzg) ([raw file](https://github.com/starkware-libs/stwo/blob/a95d5ec9c6737d55517f773940de3a979e4fa9ea/crates/prover/src/core/pcs/prover.rs#L216)):*
> ```XML
>     ) -> Self {
>         let span = span!(Level::INFO, "Extension").entered();
>         let evaluations = B::evaluate_columns(&mut polynomials, log_blowup_factor, twiddles);
> ```

Don't you need to change here too?



_Suggestion:_
```XML
B::evaluate_polynomials(&mut polynomials, log_blowup_factor, twiddles)
```

**Comment by jarnesino** [comment]
> > Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/854)_ status: all files reviewed, 1 unresolved discussion (waiting on @jarnesino and @ohad-starkware)
> 
> _[`crates/prover/src/core/pcs/prover.rs` line 216 at r2](https://reviewable.io/reviews/starkware-libs/stwo/854#-O8VdrQh-5-kDhkYMHbf:-O8VdrQh-5-kDhkYMHbg:bw2ouzg) ([raw file](https://github.com/starkware-libs/stwo/blob/a95d5ec9c6737d55517f773940de3a979e4fa9ea/crates/prover/src/core/pcs/prover.rs#L216)):_
> 
> > ```
> >     ) -> Self {
> >         let span = span!(Level::INFO, "Extension").entered();
> >         let evaluations = B::evaluate_columns(&mut polynomials, log_blowup_factor, twiddles);
> > ```
> 
> Don't you need to change here too?
> 
> _Suggestion:_
> 
> ```
> B::evaluate_polynomials(&mut polynomials, log_blowup_factor, twiddles)
> ```


Yep! Looks like I blindly trusted in my IDE's renaming tool and didn't test before pushing.
Won't happen again, thanks for pointing it out!

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/854#-:-O8c3ZMr4R5RtSoG2fHl:bnfp4nl)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @ohad-starkware)

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/854)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @jarnesino and @ohad-starkware)

___
*[`crates/prover/src/core/poly/circle/ops.rs` line 11 at r4](https://reviewable.io/reviews/starkware-libs/stwo/854#-O8c6eZi-4l84AQxAYjv:-O8c6eZjBTEsPEcjkDhJ:bloihu2) ([raw file](https://github.com/starkware-libs/stwo/blob/7fce909887778a2448e833c1b29743b3a26c330f/crates/prover/src/core/poly/circle/ops.rs#L11)):*
> ```XML
> use crate::core::poly::twiddles::TwiddleTree;
> use crate::core::poly::BitReversedOrder;
> use crate::core::ColumnVec;
> ```

I think also the formatter wants you to move that up (alphabetically) :(



_Code quote:_
```XML
use crate::core::ColumnVec;
```

**Comment by jarnesino** [comment]
> > _[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/854)_ status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @jarnesino and @ohad-starkware)
> 
> _[`crates/prover/src/core/poly/circle/ops.rs` line 11 at r4](https://reviewable.io/reviews/starkware-libs/stwo/854#-O8c6eZi-4l84AQxAYjv:-O8c6eZjBTEsPEcjkDhJ:bloihu2) ([raw file](https://github.com/starkware-libs/stwo/blob/7fce909887778a2448e833c1b29743b3a26c330f/crates/prover/src/core/poly/circle/ops.rs#L11)):_
> 
> > ```
> > use crate::core::poly::twiddles::TwiddleTree;
> > use crate::core::poly::BitReversedOrder;
> > use crate::core::ColumnVec;
> > ```
> 
> I think also the formatter wants you to move that up (alphabetically) :(
> 
> _Code quote:_
> 
> ```
> use crate::core::ColumnVec;
> ```

Hmmm that's weird. Both `cargo fmt` and `./scripts/rust_fmt.sh` correct it back to where it's now, if I try to move it. Is it different for you? @shaharsamocha7

**Review by shaharsamocha7 — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/854)* status: all files reviewed, 1 unresolved discussion (waiting on @ohad-starkware)

**Review by shaharsamocha7 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/854)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ohad-starkware)

**Pull request merged**
