### PR TITLE
Make prove() generic in Backend

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/490)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/490?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#491** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/491?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#490** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/490?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#489** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/489?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#488** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/488?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#487** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/487?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#486** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/486?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#484** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/484?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#483** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/483?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#482** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/482?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#481** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/481?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#480** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/480?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#479** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/479?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#478** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/478?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#463** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/463?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#477** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/477?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#476** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/476?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by andrewmilson — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/490#-:-NtJlDTVEBRYXBJLQ1eX:bnfp4nl)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`src/core/air/accumulation.rs` line 123 at r1](https://reviewable.io/reviews/starkware-libs/stwo/490#-NtJkvRy4G60bkuWXp99:-NtJkvRy4G60bkuWXp9A:bb752ax) ([raw file](https://github.com/starkware-libs/stwo/blob/05f6703ae226574f55e23f8c00d19b260b049114/src/core/air/accumulation.rs#L123)):*
> ```XML
> 
> pub trait AccumulationOps: FieldOps<BaseField> + Sized {
>     /// Accumulates other into colum:
> ```

Typo



_Suggestion:_
```XML
column
```

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/490)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`src/core/backend/cpu/mod.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/stwo/490#-NtJlNlm53qxZjgEI0KL:-NtJlNlm53qxZjgEI0KM:be1858) ([raw file](https://github.com/starkware-libs/stwo/blob/05f6703ae226574f55e23f8c00d19b260b049114/src/core/backend/cpu/mod.rs#L1)):*
> ```XML
> pub mod accumulation;
> ```

Nit: Does it need to be pub?

**Review by andrewmilson — APPROVED** [review]
:lgtm:

> Reviewed 1 of 9 files at r1, 2 of 5 files at r2, 1 of 2 files at r3, 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/490#-:-NtoB2bC39EatwBCghmm:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by andrewmilson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/490)* status: 5 of 11 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`src/core/prover/mod.rs` line 170 at r5](https://reviewable.io/reviews/starkware-libs/stwo/490#-NuIeyZZ8I20ZWwUjzHP:-NuIeyZZ8I20ZWwUjzHQ:bpt5cyo) ([raw file](https://github.com/starkware-libs/stwo/blob/42f9f4c859f220ed644668c128f1288caf6e7996/src/core/prover/mod.rs#L170)):*
> ```XML
>     air: &impl Air<B>,
>     mut sampled_values: TreeVec<ColumnVec<Vec<SecureField>>>,
> ) -> Result<(ComponentVec<Vec<SecureField>>, SecureField), ()> {
> ```

Can we have a specific error something like `InvalidOodsSampleStructure` or document the error case please?
___
*[`src/core/prover/mod.rs` line 171 at r5](https://reviewable.io/reviews/starkware-libs/stwo/490#-NuIZcYg6b8k2Ut-p-V4:-NuIZcYg6b8k2Ut-p-V5:b-mvvz7a) ([raw file](https://github.com/starkware-libs/stwo/blob/42f9f4c859f220ed644668c128f1288caf6e7996/src/core/prover/mod.rs#L171)):*
> ```XML
>     mut sampled_values: TreeVec<ColumnVec<Vec<SecureField>>>,
> ) -> Result<(ComponentVec<Vec<SecureField>>, SecureField), ()> {
>     let composition_partial_sampled_values = sampled_values.pop().ok_or(())?;
> ```

So the last value is always the composition? Should we document this? `/// Assumes the last sample corresponds to the OODS values for the composition columns.`

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/490)* status: 3 of 14 files reviewed, 2 unresolved discussions (waiting on @andrewmilson)

___
*[`src/core/prover/mod.rs` line 170 at r5](https://reviewable.io/reviews/starkware-libs/stwo/490#-NuIeyZZ8I20ZWwUjzHP:-NuZ4PND2SJOr1rwtaQm:b-8roy1t) ([raw file](https://github.com/starkware-libs/stwo/blob/42f9f4c859f220ed644668c128f1288caf6e7996/src/core/prover/mod.rs#L170)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Can we have a specific error something like `InvalidOodsSampleStructure` or document the error case please?
</blockquote></details>

Can we do this in another PR? It's not related to this one.
___
*[`src/core/prover/mod.rs` line 171 at r5](https://reviewable.io/reviews/starkware-libs/stwo/490#-NuIZcYg6b8k2Ut-p-V4:-NuZ4VKy3AjB65U1LF3B:b-8roy1t) ([raw file](https://github.com/starkware-libs/stwo/blob/42f9f4c859f220ed644668c128f1288caf6e7996/src/core/prover/mod.rs#L171)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

So the last value is always the composition? Should we document this? `/// Assumes the last sample corresponds to the OODS values for the composition columns.`
</blockquote></details>

Can we do this in another PR? It's not related to this one.

**Comment by spapinistarkware** [comment]
### Merge activity

* **Apr 4, 7:04 AM EDT**: @spapinistarkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/490).

**Pull request merged**
