### PR TITLE
Pass entire mask to components

### PR DESCRIPTION
**Pull request by andrewmilson**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/801)

### CODE REVIEW

**Comment by andrewmilson** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/801?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#801** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/801?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#800** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/800?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#799** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/799?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#798** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/798?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @andrewmilson and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 20 of 20 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/801)* status: all files reviewed, 5 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/component.rs` line 28 at r2](https://reviewable.io/reviews/starkware-libs/stwo/801#-O5DN5jp4ucR9uIVhjRj:-O5DN5jp4ucR9uIVhjRk:b2po01i) ([raw file](https://github.com/starkware-libs/stwo/blob/b214af40638b5e317f9c3f22b8317c1782116a93/crates/prover/src/constraint_framework/component.rs#L28)):*
> ```XML
> // TODO(andrew): Consider better location for this.
> #[derive(Debug, Default)]
> pub struct TreeColumnSpanProvider {
> ```

WDYT?
And maybe We should rename TreeColumnSpan to TraceLocation?



_Suggestion:_
```XML
TraceLocationAllocator
```
___
*[`crates/prover/src/constraint_framework/component.rs` line 30 at r2](https://reviewable.io/reviews/starkware-libs/stwo/801#-O5DLHQS3BpUJNiv0Z_p:-O5DLHQS3BpUJNiv0Z_q:b-n8jmj1) ([raw file](https://github.com/starkware-libs/stwo/blob/b214af40638b5e317f9c3f22b8317c1782116a93/crates/prover/src/constraint_framework/component.rs#L30)):*
> ```XML
> pub struct TreeColumnSpanProvider {
>     /// Mapping of tree index to next available column offset.
>     next_tree_offsets: BTreeMap<usize, usize>,
> ```

Why not TreeVec?



_Suggestion:_
```XML
TreeVec<usize>
```
___
*[`crates/prover/src/constraint_framework/component.rs` line 35 at r2](https://reviewable.io/reviews/starkware-libs/stwo/801#-O5DM4OM7ZtD2YjgMe10:-O5DM4OM7ZtD2YjgMe11:bnq8tmu) ([raw file](https://github.com/starkware-libs/stwo/blob/b214af40638b5e317f9c3f22b8317c1782116a93/crates/prover/src/constraint_framework/component.rs#L35)):*
> ```XML
> impl TreeColumnSpanProvider {
>     fn next_for_structure<T>(&mut self, structure: &TreeVec<ColumnVec<T>>) -> Vec<TreeColumnSpan> {
>         structure
> ```

        When next_tree_offsets is TreeVec:



_Suggestion:_
```XML
impl TreeColumnSpanProvider {
    fn next_for_structure<T>(&mut self, structure: &TreeVec<ColumnVec<T>>) -> TreeVec<TreeColumnSpan> {
        self.next_tree_offsets.resize(...)
        self.next_tree_offsets.as_mut().zip(structure).map(|(off, cols)|{
        ...
        })
`
```
___
*[`crates/prover/src/core/prover/mod.rs` line 76 at r2](https://reviewable.io/reviews/starkware-libs/stwo/801#-O5DNy1T9fq_Rg0AS3kV:-O5DNy1T9fq_Rg0AS3kW:b-9i2qeb) ([raw file](https://github.com/starkware-libs/stwo/blob/b214af40638b5e317f9c3f22b8317c1782116a93/crates/prover/src/core/prover/mod.rs#L76)):*
> ```XML
>     let commitment_scheme_proof = commitment_scheme.prove_values(sample_points, channel);
> 
>     // TODO(spapini): Save clone.
> ```

I don't think there's a clone here, right? Can you remove?
___
*[`crates/prover/src/core/prover/mod.rs` line 155 at r2](https://reviewable.io/reviews/starkware-libs/stwo/801#-O5DO7ks0yq83958gqxI:-O5DO7ks0yq83958gqxJ:b-po5q4x) ([raw file](https://github.com/starkware-libs/stwo/blob/b214af40638b5e317f9c3f22b8317c1782116a93/crates/prover/src/core/prover/mod.rs#L155)):*
> ```XML
>     let mut composition_cols = mask.last().into_iter().flatten();
> 
>     let col0 = &**composition_cols.next().ok_or(InvalidOodsSampleStructure)?;
> ```

Can you do this with std::array::from_fn?

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/801)* status: all files reviewed, 5 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/constraint_framework/component.rs` line 28 at r2](https://reviewable.io/reviews/starkware-libs/stwo/801#-O5DN5jp4ucR9uIVhjRj:-O5EIscIDN9S4PjG4Ujm:b61oz0e) ([raw file](https://github.com/starkware-libs/stwo/blob/b6c1cf1ee9d5c0bdb1fc28a1072b49b0012757b3/crates/prover/src/constraint_framework/component.rs#L28)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

WDYT?
And maybe We should rename TreeColumnSpan to TraceLocation?
</blockquote></details>

Updated. Personally prefer TreeColumnSpan since the trace location is made up of multiple WDYT?
___
*[`crates/prover/src/constraint_framework/component.rs` line 30 at r2](https://reviewable.io/reviews/starkware-libs/stwo/801#-O5DLHQS3BpUJNiv0Z_p:-O5ERtSFC0cbLLAI3NbW:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/b6c1cf1ee9d5c0bdb1fc28a1072b49b0012757b3/crates/prover/src/constraint_framework/component.rs#L30)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Why not TreeVec?
</blockquote></details>

Done.
___
*[`crates/prover/src/constraint_framework/component.rs` line 35 at r2](https://reviewable.io/reviews/starkware-libs/stwo/801#-O5DM4OM7ZtD2YjgMe10:-O5ER_0J1saszSwkDGIw:b-l8rdu0) ([raw file](https://github.com/starkware-libs/stwo/blob/b6c1cf1ee9d5c0bdb1fc28a1072b49b0012757b3/crates/prover/src/constraint_framework/component.rs#L35)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

When next_tree_offsets is TreeVec:
</blockquote></details>

Done. Seemed simpler to use regular iterators though because of needing the index.
___
*[`crates/prover/src/core/prover/mod.rs` line 76 at r2](https://reviewable.io/reviews/starkware-libs/stwo/801#-O5DNy1T9fq_Rg0AS3kV:-O5ES3p37f4k45malPB8:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/b6c1cf1ee9d5c0bdb1fc28a1072b49b0012757b3/crates/prover/src/core/prover/mod.rs#L76)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I don't think there's a clone here, right? Can you remove?
</blockquote></details>

Done.
___
*[`crates/prover/src/core/prover/mod.rs` line 155 at r2](https://reviewable.io/reviews/starkware-libs/stwo/801#-O5DO7ks0yq83958gqxI:-O5ENihu1WAJmIQt4FOu:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/b6c1cf1ee9d5c0bdb1fc28a1072b49b0012757b3/crates/prover/src/core/prover/mod.rs#L155)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Can you do this with std::array::from_fn?
</blockquote></details>

Done.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/801#-:-O5IjMB64T8UA0hdCS42:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/component.rs` line 28 at r2](https://reviewable.io/reviews/starkware-libs/stwo/801#-O5DN5jp4ucR9uIVhjRj:-O5Iibad617Q9_xI-Fig:bgazyvs) ([raw file](https://github.com/starkware-libs/stwo/blob/b6c1cf1ee9d5c0bdb1fc28a1072b49b0012757b3/crates/prover/src/constraint_framework/component.rs#L28)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Updated. Personally prefer TreeColumnSpan since the trace location is made up of multiple WDYT?
</blockquote></details>

I'm just afraid that new people looking at this code will think it's Jibrish...
I'm open to new names.
Maybe TraceSubspan ?
___
*[`crates/prover/src/core/pcs/mod.rs` line 28 at r3](https://reviewable.io/reviews/starkware-libs/stwo/801#-O5IjGGt6x7t_hi8sVdo:-O5IjGGt6x7t_hi8sVdp:ba3dfna) ([raw file](https://github.com/starkware-libs/stwo/blob/12d4559c15ed572518f2f03326f3709b9764623d/crates/prover/src/core/pcs/mod.rs#L28)):*
> ```XML
> }
> 
> // #[derive(Debug, Clone, PartialEq, Eq)]
> ```

Remove?

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/801)* status: 16 of 22 files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/constraint_framework/component.rs` line 28 at r2](https://reviewable.io/reviews/starkware-libs/stwo/801#-O5DN5jp4ucR9uIVhjRj:-O5LzNCE1MRxA0OR-C2f:bb6un1j) ([raw file](https://github.com/starkware-libs/stwo/blob/b6c1cf1ee9d5c0bdb1fc28a1072b49b0012757b3/crates/prover/src/constraint_framework/component.rs#L28)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I'm just afraid that new people looking at this code will think it's Jibrish...
I'm open to new names.
Maybe TraceSubspan ?
</blockquote></details>

Done
___
*[`crates/prover/src/core/pcs/mod.rs` line 28 at r3](https://reviewable.io/reviews/starkware-libs/stwo/801#-O5IjGGt6x7t_hi8sVdo:-O5LzO1EEJWD0RYhB7-z:bb6un1j) ([raw file](https://github.com/starkware-libs/stwo/blob/9afd05857060ddeb328b49178fc6f02a32b1480e/crates/prover/src/core/pcs/mod.rs#L28)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Remove?
</blockquote></details>

Done

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/801)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Pull request merged**
