### PR TITLE
Parallelize Poseidon constraint eval.

### PR DESCRIPTION
**Pull request by Alon-Ti**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/751)

### CODE REVIEW

**Comment by Alon-Ti** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/751?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#751** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/751?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#750** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/750?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#749** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/749?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#748** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/748?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Alon-Ti and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Alon-Ti — COMMENTED** [review]
On my (unexpectedly strong) machine, this cuts the eval time from ~1.2s to ~140ms on the benchmark (out of an overall time of ~2.7s).

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/751#-:-O2P3iTH3rwYGAeX2_x5:b2cxbdz)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @shaharsamocha7 and @spapinistarkware)

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/751)* status: all files reviewed, 2 unresolved discussions (waiting on @Alon-Ti and @spapinistarkware)

___
*[`poseidon_benchmark.sh` line 3 at r1](https://reviewable.io/reviews/starkware-libs/stwo/751#-O2PhsA-7tBLng9f3Fco:-O2PhsA-7tBLng9f3Fcp:b-dl4oec) ([raw file](https://github.com/starkware-libs/stwo/blob/8c307002ece2e6af88108d260326166a3add63f9/poseidon_benchmark.sh#L3)):*
> ```Shell
> LOG_N_INSTANCES=18 RUST_LOG_SPAN_EVENTS=enter,close RUST_LOG=info \
>     RUSTFLAGS="-C target-cpu=native -C opt-level=3" \
>     cargo test test_simd_poseidon_prove --features parallel -- --nocapture
> ```

I wonder maybe we want to put threads limit here?



_Code quote:_
```Shell
cargo test test_simd_poseidon_prove --features parallel -- --nocapture
```
___
*[`crates/prover/src/examples/poseidon/mod.rs` line 420 at r1](https://reviewable.io/reviews/starkware-libs/stwo/751#-O2Pick2-EJdhzyh0sOf:-O2Pick2-EJdhzyh0sOg:b-7zi8ni) ([raw file](https://github.com/starkware-libs/stwo/blob/8c307002ece2e6af88108d260326166a3add63f9/crates/prover/src/examples/poseidon/mod.rs#L420)):*
> ```XML
>             .zip(accum.col.chunks_mut(CHUNK_SIZE));
> 
>         iter.for_each(|(base_row, mut col_chunk)| {
> ```

WDYT?



_Suggestion:_
```XML
iter.for_each(|(chunk_offset, mut col_chunk)| {
```

**Review by Alon-Ti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/751)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/examples/poseidon/mod.rs` line 420 at r1](https://reviewable.io/reviews/starkware-libs/stwo/751#-O2Pick2-EJdhzyh0sOf:-O2UNcZO8iq_lsBvYtvS:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/8c307002ece2e6af88108d260326166a3add63f9/crates/prover/src/examples/poseidon/mod.rs#L420)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

WDYT?
</blockquote></details>

Done.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/751#-:-O2c_MIr3kfB9IyxL8IF:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Alon-Ti)

___
*[`crates/prover/src/examples/poseidon/mod.rs` line 409 at r3](https://reviewable.io/reviews/starkware-libs/stwo/751#-O2cZ-0N-J_D7X2ujhZu:-O2cZ-0N-J_D7X2ujhZv:blm80ow) ([raw file](https://github.com/starkware-libs/stwo/blob/c4d3fa05eb12bc55c9d76668dbe0b139310c79be/crates/prover/src/examples/poseidon/mod.rs#L409)):*
> ```XML
>         pows.reverse();
> 
>         const CHUNK_SIZE: usize = 16;
> ```

Why is it 16?
Do we need to change it in some cases?

I wonder if it should be defined in more general place.



_Code quote:_
```XML
        const CHUNK_SIZE: usize = 16;
```

**Pull request merged**
