### PR TITLE
Organize errors.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/523)

### CODE REVIEW

**Comment by alonh5** [comment]
* **#523** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/523?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/523)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5 and @spapinistarkware)

___
*[`src/core/commitment_scheme/mod.rs` line 377 at r1](https://reviewable.io/reviews/starkware-libs/stwo/523#-Ntkbux_AxNDF8S5omqH:-Ntkbuxa3bPL5r6IwrnF:b-uzipfa) ([raw file](https://github.com/starkware-libs/stwo/blob/5e143425872d543f0dbdbac3f397db6bcec4cfa8/src/core/commitment_scheme/mod.rs#L377)):*
> ```XML
>                 let values = queried_values.take(1 << subdomain.log_size).collect_vec();
>                 if values.len() != 1 << subdomain.log_size {
>                     return Err(VerificationError::InvalidStructure(
> ```

Do we want to return also the values/values len?



_Code quote:_
```XML
VerificationError::InvalidStructure(
```
___
*[`src/core/prover/mod.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/stwo/523#-NtkcFZ_9eGLW21-QQoI:-NtkcFZ_9eGLW21-QQoJ:b-6kffq5) ([raw file](https://github.com/starkware-libs/stwo/blob/5e143425872d543f0dbdbac3f397db6bcec4cfa8/src/core/prover/mod.rs#L146)):*
> ```XML
>     let (trace_oods_values, composition_oods_value) =
>         proved_values_to_mask(air, proof.commitment_scheme_proof.proved_values.clone())
>             .map_err(|_| VerificationError::InvalidStructure("Proved values".to_string()))?;
> ```

I think that this returned error string isn't really indicative. Maybe we should be able to infer in which phase of the algorithm it failed?



_Code quote:_
```XML
"Proved values".to_string()
```
___
*[`src/core/prover/mod.rs` line 157 at r1](https://reviewable.io/reviews/starkware-libs/stwo/523#-Ntkc4SS7cYSU6aOVZ1p:-Ntkc4ST8GCk1zyZ-JQI:b-jimjls) ([raw file](https://github.com/starkware-libs/stwo/blob/5e143425872d543f0dbdbac3f397db6bcec4cfa8/src/core/prover/mod.rs#L157)):*
> ```XML
> }
> 
> fn proved_values_to_mask(
> ```

Document



_Code quote:_
```XML
fn proved_values_to_mask(
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/523)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`src/core/prover/mod.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/stwo/523#-NtkcFZ_9eGLW21-QQoI:-NtorFlOB9qA2fmAjpgv:b-qgs8nj) ([raw file](https://github.com/starkware-libs/stwo/blob/5e143425872d543f0dbdbac3f397db6bcec4cfa8/src/core/prover/mod.rs#L146)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I think that this returned error string isn't really indicative. Maybe we should be able to infer in which phase of the algorithm it failed?
</blockquote></details>

It's not exactly failing in a certain phase, the structure of the passed proved values (oods values) isn't as expected. I modified the error message a bit, I think being more specific than this might be an overkill. WDYT?
___
*[`src/core/prover/mod.rs` line 157 at r1](https://reviewable.io/reviews/starkware-libs/stwo/523#-Ntkc4SS7cYSU6aOVZ1p:-NtooMiw-JdA9pnrbIyk:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/5e143425872d543f0dbdbac3f397db6bcec4cfa8/src/core/prover/mod.rs#L157)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Document
</blockquote></details>

Done.
___
*[`src/core/commitment_scheme/mod.rs` line 377 at r1](https://reviewable.io/reviews/starkware-libs/stwo/523#-Ntkbux_AxNDF8S5omqH:-NtosE2S6R7QJLLVBgUh:b-k0gjxc) ([raw file](https://github.com/starkware-libs/stwo/blob/5e143425872d543f0dbdbac3f397db6bcec4cfa8/src/core/commitment_scheme/mod.rs#L377)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Do we want to return also the values/values len?
</blockquote></details>

`values` here is is only the values of a specific `subdomain` in the iteration. I can calculate the actual total difference in queried values just for this error. Thinking of the possible reasons this error could occur I'm not sure if this extra information will actually help the user.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/523)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @spapinistarkware)

___
*[`src/core/prover/mod.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/stwo/523#-NtkcFZ_9eGLW21-QQoI:-NtqI33rCrfp_hmyXuX0:bsbomfy) ([raw file](https://github.com/starkware-libs/stwo/blob/5e143425872d543f0dbdbac3f397db6bcec4cfa8/src/core/prover/mod.rs#L146)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

It's not exactly failing in a certain phase, the structure of the passed proved values (oods values) isn't as expected. I modified the error message a bit, I think being more specific than this might be an overkill. WDYT?
</blockquote></details>

maybe proved_values or (sampled)
___
*[`src/core/commitment_scheme/mod.rs` line 377 at r1](https://reviewable.io/reviews/starkware-libs/stwo/523#-Ntkbux_AxNDF8S5omqH:-NtqIJ0a9XPfqR0CImVd:b86rrg4) ([raw file](https://github.com/starkware-libs/stwo/blob/5e143425872d543f0dbdbac3f397db6bcec4cfa8/src/core/commitment_scheme/mod.rs#L377)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

`values` here is is only the values of a specific `subdomain` in the iteration. I can calculate the actual total difference in queried values just for this error. Thinking of the possible reasons this error could occur I'm not sure if this extra information will actually help the user.
</blockquote></details>

E.g. if the values vector is empty that would give an extra information.
Maybe only print the len()?

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/523)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`src/core/prover/mod.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/stwo/523#-NtkcFZ_9eGLW21-QQoI:-NtqK8gV6Uvz0yT58fZU:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/5e143425872d543f0dbdbac3f397db6bcec4cfa8/src/core/prover/mod.rs#L146)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

maybe proved_values or (sampled)
</blockquote></details>

Done.
___
*[`src/core/commitment_scheme/mod.rs` line 377 at r1](https://reviewable.io/reviews/starkware-libs/stwo/523#-Ntkbux_AxNDF8S5omqH:-NtqJx8Q8Q2R-6n5zOug:b-7zi8ni) ([raw file](https://github.com/starkware-libs/stwo/blob/5e143425872d543f0dbdbac3f397db6bcec4cfa8/src/core/commitment_scheme/mod.rs#L377)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

E.g. if the values vector is empty that would give an extra information.
Maybe only print the len()?
</blockquote></details>

WDYT?

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/523)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5 and @spapinistarkware)

___
*[`src/core/commitment_scheme/verifier.rs` line 143 at r4](https://reviewable.io/reviews/starkware-libs/stwo/523#-Nttw0Oe6_yLFn_QWb_P:-Nttw0Oe6_yLFn_QWb_Q:b-o44jxr) ([raw file](https://github.com/starkware-libs/stwo/blob/c125e731bac9a9283eec99be235f61b8c764d7d8/src/core/commitment_scheme/verifier.rs#L143)):*
> ```XML
>     value: SecureField,
> ) -> Result<SparseCircleEvaluation<SecureField>, VerificationError> {
>     let queried_values_len = queried_values.len();
> ```

I would calculate that only if the error has happened.



_Code quote:_
```XML
let queried_values_len = queried_values.len();
```
___
*[`src/core/commitment_scheme/verifier.rs` line 152 at r4](https://reviewable.io/reviews/starkware-libs/stwo/523#-NttwXpO7V7ND_gaLz1p:-NttwXpO7V7ND_gaLz1q:b-2a8v45) ([raw file](https://github.com/starkware-libs/stwo/blob/c125e731bac9a9283eec99be235f61b8c764d7d8/src/core/commitment_scheme/verifier.rs#L152)):*
> ```XML
>                 if values.len() != 1 << subdomain.log_size {
>                     return Err(VerificationError::InvalidStructure(format!(
>                         "Insufficient number of queried values ({queried_values_len})"
> ```

not sure that this value help to understand the error message by itself.
Either also print expected number or values, or remove at all (your call)



_Code quote:_
```XML
{queried_values_len}
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/523)* status: all files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`src/core/commitment_scheme/verifier.rs` line 152 at r4](https://reviewable.io/reviews/starkware-libs/stwo/523#-NttwXpO7V7ND_gaLz1p:-Nttx_x-CVIuxuRQ-vYo:b-e8q6zy) ([raw file](https://github.com/starkware-libs/stwo/blob/c125e731bac9a9283eec99be235f61b8c764d7d8/src/core/commitment_scheme/verifier.rs#L152)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

not sure that this value help to understand the error message by itself.
Either also print expected number or values, or remove at all (your call)
</blockquote></details>

To calculate the expected number I would need to iterate over the domains again, calculate and sum the sized of each one. I think this is an overkill for values that won't give much information anyways, I'll just remove it from the error.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/523#-:-Ntu-ycb1PZj29dXzD_a:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @spapinistarkware)

**Review by shaharsamocha7 — APPROVED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/523)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
