### PR TITLE
Mut chunks for VeryPacked Base and Secure columns.

### PR DESCRIPTION
**Pull request by Alon-Ti**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/842)

### CODE REVIEW

**Comment by Alon-Ti** [comment]
* **#842** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/842?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Alon-Ti and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by Alon-Ti** [comment]
* **#843** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/843?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#842** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/842?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Alon-Ti and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/842)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @Alon-Ti)

___
*[`crates/prover/src/core/backend/simd/column.rs` line 223 at r1](https://reviewable.io/reviews/starkware-libs/stwo/842#-O78HvkmB1-J8CyMWy6a:-O78HvkmB1-J8CyMWy6b:bflvz30) ([raw file](https://github.com/starkware-libs/stwo/blob/2c88349c7b1bab70e5f96bb9deba5681d87250d1/crates/prover/src/core/backend/simd/column.rs#L223)):*
> ```XML
>     const N_ELEMS: usize = N_LANES * N_VERY_PACKED_ELEMS;
>     pub fn at(&self, index: usize) -> BaseField {
>         self.0[index / Self::N_ELEMS].to_array()[index % N_LANES]
> ```

I'm not sure it's correct.
Do we have tests for this code?



_Suggestion:_
```XML
self.0[index / Self::N_ELEMS].to_array()[index % self::N_ELEMS]
```
___
*[`crates/prover/src/core/backend/simd/column.rs` line 227 at r1](https://reviewable.io/reviews/starkware-libs/stwo/842#-O78GPdj1DrpuI-_CjWa:-O78GPdj1DrpuI-_CjWb:bt1b0cu) ([raw file](https://github.com/starkware-libs/stwo/blob/2c88349c7b1bab70e5f96bb9deba5681d87250d1/crates/prover/src/core/backend/simd/column.rs#L227)):*
> ```XML
> 
>     pub fn set(&mut self, index: usize, value: BaseField) {
>         let mut packed = self.0[index / Self::N_ELEMS].to_array();
> ```

Rename?



_Suggestion:_
```XML
let mut packed_as_array = self.0[index / Self::N_ELEMS].to_array();
```
___
*[`crates/prover/src/core/backend/simd/column.rs` line 519 at r1](https://reviewable.io/reviews/starkware-libs/stwo/842#-O78IUl42lK7C7TLXJ-z:-O78IUl42lK7C7TLXJ0-:b-8it01) ([raw file](https://github.com/starkware-libs/stwo/blob/2c88349c7b1bab70e5f96bb9deba5681d87250d1/crates/prover/src/core/backend/simd/column.rs#L519)):*
> ```XML
>             .iter()
>             .flat_map(|x| x.to_array())
>             .take(self.length)
> ```

Why do you need this? Don't you always want all the values?



_Code quote:_
```XML
.take(self.length)
```

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/842)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @Alon-Ti)

___
*[`crates/prover/src/core/backend/simd/column.rs` line 220 at r1](https://reviewable.io/reviews/starkware-libs/stwo/842#-O78ll5WA2IxyIYGiPj5:-O78ll5X9a1ILeWlOVUQ:b-p7ldtr) ([raw file](https://github.com/starkware-libs/stwo/blob/2c88349c7b1bab70e5f96bb9deba5681d87250d1/crates/prover/src/core/backend/simd/column.rs#L220)):*
> ```XML
> pub struct VeryPackedBaseColumnMutSlice<'a>(pub &'a mut [VeryPackedBaseField]);
> 
> impl<'a> VeryPackedBaseColumnMutSlice<'a> {
> ```

This entire impl can be removed



_Code quote:_
```XML
impl<'a> VeryPackedBaseColumnMutSlice<'a> {
```

**Review by Alon-Ti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/842)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/prover/src/core/backend/simd/column.rs` line 220 at r1](https://reviewable.io/reviews/starkware-libs/stwo/842#-O78ll5WA2IxyIYGiPj5:-O7NwVah4SDLMNadgWAg:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/2c88349c7b1bab70e5f96bb9deba5681d87250d1/crates/prover/src/core/backend/simd/column.rs#L220)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

This entire impl can be removed
</blockquote></details>

Done.
___
*[`crates/prover/src/core/backend/simd/column.rs` line 223 at r1](https://reviewable.io/reviews/starkware-libs/stwo/842#-O78HvkmB1-J8CyMWy6a:-O7NwlsC6KB_jBvpz5Pv:bss4a2b) ([raw file](https://github.com/starkware-libs/stwo/blob/2c88349c7b1bab70e5f96bb9deba5681d87250d1/crates/prover/src/core/backend/simd/column.rs#L223)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I'm not sure it's correct.
Do we have tests for this code?
</blockquote></details>

Removed.
___
*[`crates/prover/src/core/backend/simd/column.rs` line 227 at r1](https://reviewable.io/reviews/starkware-libs/stwo/842#-O78GPdj1DrpuI-_CjWa:-O7NznjT9ReRc95yQCSR:bss4a2b) ([raw file](https://github.com/starkware-libs/stwo/blob/2c88349c7b1bab70e5f96bb9deba5681d87250d1/crates/prover/src/core/backend/simd/column.rs#L227)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Rename?
</blockquote></details>

Removed.
___
*[`crates/prover/src/core/backend/simd/column.rs` line 519 at r1](https://reviewable.io/reviews/starkware-libs/stwo/842#-O78IUl42lK7C7TLXJ-z:-O7NztmW4aqysuRdUfE0:b-2aow8n) ([raw file](https://github.com/starkware-libs/stwo/blob/2c88349c7b1bab70e5f96bb9deba5681d87250d1/crates/prover/src/core/backend/simd/column.rs#L519)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why do you need this? Don't you always want all the values?
</blockquote></details>

That's specifically what length is for, so you can have vectors of length finer than whatever the packing is, the cpu impl would just save them at the correct length.

**Comment by Alon-Ti** [comment]
* **#843** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/843?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#842** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/842?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Alon-Ti and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/842#-:-O7OgjRm-9d_Vr2qJaXN:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Alon-Ti)

**Pull request merged**
