### PR TITLE
Air with dyn component

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/487)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/487?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#487** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/487?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#486** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/486?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#484** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/484?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#483** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/483?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#482** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/482?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#481** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/481?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#480** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/480?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#479** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/479?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#478** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/478?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#463** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/463?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#477** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/477?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#476** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/476?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 4 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/487)* status: all files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`src/core/air/component_visitors.rs` line 139 at r3](https://reviewable.io/reviews/starkware-libs/stwo/487#-NtGe9CeApAcxtHQiWs7:-NtGe9CeApAcxtHQiWs8:b-brycxj) ([raw file](https://github.com/starkware-libs/stwo/blob/519f4c01f87b1e739e293cf6915d0303b5120719/src/core/air/component_visitors.rs#L139)):*
> ```XML
>             .map(|component| {
>                 let n_columns = component.trace_log_degree_bounds().len();
>                 let columns = polynomials.iter().take(n_columns).collect();
> ```

I think this is needed to mutate `self.polynomials`.



_Suggestion:_
```XML
(&mut self.polynomials)
```
___
*[`src/core/prover/mod.rs` line 175 at r3](https://reviewable.io/reviews/starkware-libs/stwo/487#-NtGd18e2uQjig7q8pid:-NtGd18e2uQjig7q8pie:b-ske1qq) ([raw file](https://github.com/starkware-libs/stwo/blob/519f4c01f87b1e739e293cf6915d0303b5120719/src/core/prover/mod.rs#L175)):*
> ```XML
>     commitment_domains.push(CanonicCoset::new(
>         air.composition_log_degree_bound() + LOG_BLOWUP_FACTOR,
>     ));
> ```

Why not add this inside the air method?



_Code quote:_
```XML
    commitment_domains.push(CanonicCoset::new(
        air.composition_log_degree_bound() + LOG_BLOWUP_FACTOR,
    ));
```

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 3 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/487)* status: all files reviewed, 5 unresolved discussions (waiting on @spapinistarkware)

___
*[`src/core/air/component_visitors.rs` line 1 at r3](https://reviewable.io/reviews/starkware-libs/stwo/487#-NtKyc0X-2y7EhSFM3ax:-NtKyc0YA73Wlr_7JfAW:br2h7s) ([raw file](https://github.com/starkware-libs/stwo/blob/e9aa5fcddd571aaf9a2310f219d06b9ee050572d/src/core/air/component_visitors.rs#L1)):*
> ```XML
> use core::slice;
> ```

Maybe this file should be renamed?



_Code quote:_
```XML
use core::slice;
```
___
*[`src/core/air/component_visitors.rs` line 65 at r3](https://reviewable.io/reviews/starkware-libs/stwo/487#-NtL024j88oyb9ClZ_UU:-NtL024kAvEc3i4V9oSH:b4kgenn) ([raw file](https://github.com/starkware-libs/stwo/blob/519f4c01f87b1e739e293cf6915d0303b5120719/src/core/air/component_visitors.rs#L65)):*
> ```XML
>     }
> 
>     fn mask_points(
> ```

Unit test for this function?
I don't see where you move the mask by the component offset



_Code quote:_
```XML
fn mask_points(
```
___
*[`src/core/air/component_visitors.rs` line 100 at r3](https://reviewable.io/reviews/starkware-libs/stwo/487#-NtL-Wut9ZYzHOCZjylU:-NtL-Wut9ZYzHOCZjylV:b8k3vwi) ([raw file](https://github.com/starkware-libs/stwo/blob/519f4c01f87b1e739e293cf6915d0303b5120719/src/core/air/component_visitors.rs#L100)):*
> ```XML
> 
>     /// Returns the log degree bounds of the quotient polynomials in descending order.
>     fn quotient_log_bounds(&self) -> Vec<CirclePolyDegreeBound> {
> ```

Can we have a unit test to this function?
I don't understand how it is works in case you have multiple components



_Code quote:_
```XML
fn quotient_log_bounds(&self) -> Vec<CirclePolyDegreeBound> {
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/487)* status: 4 of 8 files reviewed, 4 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

___
*[`src/core/prover/mod.rs` line 175 at r3](https://reviewable.io/reviews/starkware-libs/stwo/487#-NtGd18e2uQjig7q8pid:-NtLTMxI0LcqLKkP7--0:bedf09i) ([raw file](https://github.com/starkware-libs/stwo/blob/519f4c01f87b1e739e293cf6915d0303b5120719/src/core/prover/mod.rs#L175)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Why not add this inside the air method?
</blockquote></details>

It's the only place that will need it. Why move it? It's more explicit this wait.
___
*[`src/core/air/component_visitors.rs` line 65 at r3](https://reviewable.io/reviews/starkware-libs/stwo/487#-NtL024j88oyb9ClZ_UU:-NtLSEco1KwrIHyZpP8O:b-ucchnt) ([raw file](https://github.com/starkware-libs/stwo/blob/519f4c01f87b1e739e293cf6915d0303b5120719/src/core/air/component_visitors.rs#L65)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Unit test for this function?
I don't see where you move the mask by the component offset
</blockquote></details>

What's a component offset?
I didnt change this function, just translated to a loop.
___
*[`src/core/air/component_visitors.rs` line 100 at r3](https://reviewable.io/reviews/starkware-libs/stwo/487#-NtL-Wut9ZYzHOCZjylU:-NtLSuIkBFzsZOcEjYmn:blcsd02) ([raw file](https://github.com/starkware-libs/stwo/blob/519f4c01f87b1e739e293cf6915d0303b5120719/src/core/air/component_visitors.rs#L100)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can we have a unit test to this function?
I don't understand how it is works in case you have multiple components
</blockquote></details>

I didnt change it. Adding tests sounds nice, but not for this PR.
___
*[`src/core/air/component_visitors.rs` line 139 at r3](https://reviewable.io/reviews/starkware-libs/stwo/487#-NtGe9CeApAcxtHQiWs7:-NtLTIJH2iSy32Y5f7E-:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/519f4c01f87b1e739e293cf6915d0303b5120719/src/core/air/component_visitors.rs#L139)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I think this is needed to mutate `self.polynomials`.
</blockquote></details>

Done.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/487)* status: all files reviewed, 4 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`src/core/air/mod.rs` line 18 at r4](https://reviewable.io/reviews/starkware-libs/stwo/487#-NtLvK6z46XtPug8BZQb:-NtLvK6z46XtPug8BZQc:bvp0s5h) ([raw file](https://github.com/starkware-libs/stwo/blob/13efd902901a69fc9a0dae6ff37e359eca61ad4d/src/core/air/mod.rs#L18)):*
> ```XML
> pub use air_ext::AirExt;
> 
> /// Aritair_exte Representation (AIR).
> ```

Restore.
___
*[`src/core/prover/mod.rs` line 175 at r3](https://reviewable.io/reviews/starkware-libs/stwo/487#-NtGd18e2uQjig7q8pid:-NtLvTgK9ws7exjYxFgv:b71e0j4) ([raw file](https://github.com/starkware-libs/stwo/blob/519f4c01f87b1e739e293cf6915d0303b5120719/src/core/prover/mod.rs#L175)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

It's the only place that will need it. Why move it? It's more explicit this wait.
</blockquote></details>

It seems more natural, the verify function is long as is. But your call, it's not crucial.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/487)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

___
*[`src/core/air/mod.rs` line 18 at r4](https://reviewable.io/reviews/starkware-libs/stwo/487#-NtLvK6z46XtPug8BZQb:-NtM-tfRAfse3JdN5zM0:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/13efd902901a69fc9a0dae6ff37e359eca61ad4d/src/core/air/mod.rs#L18)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Restore.
</blockquote></details>

Done.
___
*[`src/core/prover/mod.rs` line 175 at r3](https://reviewable.io/reviews/starkware-libs/stwo/487#-NtGd18e2uQjig7q8pid:-NtM-ycx5EPxjEFECuM4:b-pb3nat) ([raw file](https://github.com/starkware-libs/stwo/blob/519f4c01f87b1e739e293cf6915d0303b5120719/src/core/prover/mod.rs#L175)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

It seems more natural, the verify function is long as is. But your call, it's not crucial.
</blockquote></details>

It'll get shorter upstack.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/487#-:-NtM1gbY6dR53SnbP_YE:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7)

**Review by shaharsamocha7 — APPROVED** [review]

**Pull request merged**
