### PR TITLE
Eval framework info

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/715)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/715?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#712** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/712?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#711** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/711?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#710** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/710?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#708** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/708?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#707** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/707?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#715** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/715?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#714** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/714?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#713** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/713?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#706** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/706?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#705** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/705?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#704** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/704?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#702** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/702?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#701** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/701?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/715)* status: all files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/constraint_framework/info.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/stwo/715#-O1kzVjw9EmF4uZmfsys:-O1kzVjw9EmF4uZmfsyt:b-esd3pm) ([raw file](https://github.com/starkware-libs/stwo/blob/b9d91f59d05e5f691e22087ed31be79abaa2b6c4/crates/prover/src/constraint_framework/info.rs#L11)):*
> ```XML
> 
> #[derive(Default)]
> pub struct InfoEvaluator {
> ```

Document that this is used to collect the mask offsets and count the constraints for a specific component.



_Code quote:_
```XML
pub struct InfoEvaluator {
```
___
*[`crates/prover/src/constraint_framework/info.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/stwo/715#-O1kz-Rj7TebuQQ1MBhq:-O1kz-Rj7TebuQQ1MBhr:b-vpkzmk) ([raw file](https://github.com/starkware-libs/stwo/blob/b9d91f59d05e5f691e22087ed31be79abaa2b6c4/crates/prover/src/constraint_framework/info.rs#L30)):*
> ```XML
>         if self.mask_offsets.len() <= interaction {
>             self.mask_offsets.resize(interaction + 1, vec![]);
>         }
> ```

This code assumes that 'interaction` is continuous (which is true) but it may be called differently
Alternatively handle that differently



_Suggestion:_
```XML
        if self.mask_offsets.len() <= interaction {
            assert_eq(self.mask_offsets.len() == interaction + 1);
            self.mask_offsets.resize(interaction + 1, vec![]);
        }
```
___
*[`crates/prover/src/constraint_framework/info.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/stwo/715#-O1kyb6P0KfVTCt9V3gv:-O1kyb6Q1wb9mgL81tmJ:b2nhexc) ([raw file](https://github.com/starkware-libs/stwo/blob/b9d91f59d05e5f691e22087ed31be79abaa2b6c4/crates/prover/src/constraint_framework/info.rs#L41)):*
> ```XML
>     }
> 
>     fn combine_ef(_values: [Self::F; 4]) -> Self::EF {
> ```

Fix



_Suggestion:_
```XML
    fn combine_ef(values: [Self::F; SECURE_EXTENSION_DEGREE]) -> Self::EF {
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/715)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/info.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/stwo/715#-O1kzVjw9EmF4uZmfsys:-O1l3oGj-DdkG0KXRA-C:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/b9d91f59d05e5f691e22087ed31be79abaa2b6c4/crates/prover/src/constraint_framework/info.rs#L11)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Document that this is used to collect the mask offsets and count the constraints for a specific component.
</blockquote></details>

Done.
___
*[`crates/prover/src/constraint_framework/info.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/stwo/715#-O1kz-Rj7TebuQQ1MBhq:-O1l4xSO7namLfScXDZr:bs7iddk) ([raw file](https://github.com/starkware-libs/stwo/blob/b9d91f59d05e5f691e22087ed31be79abaa2b6c4/crates/prover/src/constraint_framework/info.rs#L30)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

This code assumes that 'interaction` is continuous (which is true) but it may be called differently
Alternatively handle that differently
</blockquote></details>

As discussed.
___
*[`crates/prover/src/constraint_framework/info.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/stwo/715#-O1kyb6P0KfVTCt9V3gv:-O1l4G5yBSne4v1-jrdH:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/b9d91f59d05e5f691e22087ed31be79abaa2b6c4/crates/prover/src/constraint_framework/info.rs#L41)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Fix
</blockquote></details>

Done.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/715#-:-O1l7DzH5HJ4-KFWFGGz:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Comment by spapinistarkware** [comment]
### Merge activity

* **Jul 14, 8:18 AM EDT**: @spapinistarkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/715).

**Pull request merged**
