### PR TITLE
Separate commitment prover and verifier to modules

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/482)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/482?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#482** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/482?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#481** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/481?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#480** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/480?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#479** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/479?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#478** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/478?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#463** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/463?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#477** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/477?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#476** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/476?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/482)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`src/core/commitment_scheme/prover.rs` line 6 at r2](https://reviewable.io/reviews/starkware-libs/stwo/482#-NtkhAWa74INF_sD8V5H:-NtkhAWa74INF_sD8V5I:bc1mtmf) ([raw file](https://github.com/starkware-libs/stwo/blob/095d7a870c7ccca25362db9ed6cb1810c6f49b64/src/core/commitment_scheme/prover.rs#L6)):*
> ```XML
> //! Note: This implementation is not really a polynomial commitment scheme, because we are not in
> //! the unique decoding regime. This is enough for a STARK proof though, where we onyl want to imply
> //! the existence of such polynomials, and re ok with having a small decoding list.
> ```

Move to mod.rs?



_Code quote:_
```XML
//! Implements a FRI polynomial commitment scheme.
//! This is a protocol where the prover can commit on a set of polynomials and then prove their
//! opening on a set of points.
//! Note: This implementation is not really a polynomial commitment scheme, because we are not in
//! the unique decoding regime. This is enough for a STARK proof though, where we onyl want to imply
//! the existence of such polynomials, and re ok with having a small decoding list.
```
___
*[`src/core/commitment_scheme/verifier.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/stwo/482#-NtkhFPZ7xb2VSvetPDj:-NtkhFPZ7xb2VSvetPDk:bal7sb3) ([raw file](https://github.com/starkware-libs/stwo/blob/095d7a870c7ccca25362db9ed6cb1810c6f49b64/src/core/commitment_scheme/verifier.rs#L27)):*
> ```XML
> type ProofChannel = Blake2sChannel;
> 
> /// The verifier side of a FRI polynomial commitment scheme. See [self].
> ```

Modify this.



_Code quote:_
```XML
See [self]
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/482)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5)

___
*[`src/core/commitment_scheme/prover.rs` line 6 at r2](https://reviewable.io/reviews/starkware-libs/stwo/482#-NtkhAWa74INF_sD8V5H:-NtkjIQN1JM_C-23xBKQ:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/095d7a870c7ccca25362db9ed6cb1810c6f49b64/src/core/commitment_scheme/prover.rs#L6)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Move to mod.rs?
</blockquote></details>

Done.
___
*[`src/core/commitment_scheme/verifier.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/stwo/482#-NtkhFPZ7xb2VSvetPDj:-NtkjcLW0gaWI1mjjT7p:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/095d7a870c7ccca25362db9ed6cb1810c6f49b64/src/core/commitment_scheme/verifier.rs#L27)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Modify this.
</blockquote></details>

Done.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/482#-:-NtlCZ_z2dXe0WYvAMDd:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
