### PR TITLE
avx poly extend

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/397)

### CODE REVIEW

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/397)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ohad-starkware and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo/397#-NshGadXE5cM_Izg7XEI:-NshGadY2wZAovYL5VrL:b-wg0kcm) (no related file):*
Do we want to merge this pr?

___

**Review by ohad-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/397)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo/397#-NshygSj70oEcTdf9bSU:-NshygSj70oEcTdf9bSV:b-hw2hcw) (no related file):*
 comment and the code seems lgtm , but adding to what shahar said, do we need t? you're not using it in the stack

___
___
*[`src/core/backend/avx512/circle.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/stwo/397#-Nsi-RgC-bav0rn0SBar:-Nsi-RgC-bav0rn0SBas:b-p3lj1w) ([raw file](https://github.com/starkware-libs/stwo/blob/bac218b3152bfcfb14e3a6e86a2626fb696861db/src/core/backend/avx512/circle.rs#L119)):*
> ```XML
> 
>     fn extend(poly: &CirclePoly<Self, BaseField>, log_size: u32) -> CirclePoly<Self, BaseField> {
>         // TODO(spapini): Optimize or get rid of extend.
> ```

move above?

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/397)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ohad-starkware and @shaharsamocha7)

*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo/397#-NshGadXE5cM_Izg7XEI:-NslBlJtAgczZo6wYJOy:bky5pyv) (no related file):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Do we want to merge this pr?
</blockquote></details>

Yes. We will need extend() for the constraint eval. Right now it's unclear if it's important to optimize.

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo/397#-NshygSj70oEcTdf9bSU:-NslC9l54BBvmwu9Cm5o:b-896fix) (no related file):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

comment and the code seems lgtm , but adding to what shahar said, do we need t? you're not using it in the stack
</blockquote></details>

Done.

___

**Review by ohad-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/397)* status: all files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo/397#-NshygSj70oEcTdf9bSU:-NslEog9AapRViVTeHJt:b-vjaozf) (no related file):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I meant the comment. 
lgtm.

___

**Review by ohad-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/397)* status: all files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo/397#-NshygSj70oEcTdf9bSU:-NslFB_eBCuZIA2kUhH8:bg7igkv) (no related file):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

I meant the comment. 
lgtm.
</blockquote></details>

:lgtm: 

___

**Review by alon-dotan-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/397)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`.github/workflows/coverage.yaml` line 22 at r3](https://reviewable.io/reviews/starkware-libs/stwo/397#-NslZG9zBuWiKfn7ORRX:-Nslbqsx-ysZlmKCJ9O6:b9o67g0) ([raw file](https://github.com/starkware-libs/stwo/blob/11bc12543714dd38391bb6aff7ccbf8606f8afa4/.github/workflows/coverage.yaml#L22)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Nice catch
</blockquote></details>

@spapinistarkware Thanks!!

**Review by alon-dotan-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/397#-:-NslbxVcBWl-c2rIwpDe:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Pull request merged**
