### PR TITLE
Uninitialized column

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/763)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
* **#763** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/763?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 9 of 12 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/763)* status: 11 of 12 files reviewed, 2 unresolved discussions (waiting on @Alon-Ti and @spapinistarkware)

___
*[`crates/prover/src/core/backend/mod.rs` line 41 at r2](https://reviewable.io/reviews/starkware-libs/stwo/763#-O31ckzl35CXISlQFS-p:-O31ckzl35CXISlQFS-q:bd8ir20) ([raw file](https://github.com/starkware-libs/stwo/blob/ab413cab546a54d82077c79b0cea313aaab6f108/crates/prover/src/core/backend/mod.rs#L41)):*
> ```XML
>     fn zeros(len: usize) -> Self;
>     /// # Safety
>     unsafe fn uninit(len: usize) -> Self;
> ```

Document that it should be used only for scenarios where you are going to fill the column with values.



_Suggestion:_
```XML
unsafe fn uninitilized(len: usize) -> Self;
```
___
*[`crates/prover/src/core/backend/simd/column.rs` line 77 at r2](https://reviewable.io/reviews/starkware-libs/stwo/763#-O31dEEe09bvWYwWMSNj:-O31dEEe09bvWYwWMSNk:b3tvgin) ([raw file](https://github.com/starkware-libs/stwo/blob/ab413cab546a54d82077c79b0cea313aaab6f108/crates/prover/src/core/backend/simd/column.rs#L77)):*
> ```XML
>     unsafe fn uninit(length: usize) -> Self {
>         let mut data = Vec::with_capacity(length.div_ceil(N_LANES));
>         data.set_len(length.div_ceil(N_LANES));
> ```

I wonder if this should be safe_div here?
Also for zeros



_Code quote:_
```XML
length.div_ceil(N_LANES));
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/763)* status: 11 of 12 files reviewed, 2 unresolved discussions (waiting on @Alon-Ti and @shaharsamocha7)

___
*[`crates/prover/src/core/backend/mod.rs` line 41 at r2](https://reviewable.io/reviews/starkware-libs/stwo/763#-O31ckzl35CXISlQFS-p:-O322rEaALR35hH0c22O:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/ab413cab546a54d82077c79b0cea313aaab6f108/crates/prover/src/core/backend/mod.rs#L41)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Document that it should be used only for scenarios where you are going to fill the column with values.
</blockquote></details>

Done.
___
*[`crates/prover/src/core/backend/simd/column.rs` line 77 at r2](https://reviewable.io/reviews/starkware-libs/stwo/763#-O31dEEe09bvWYwWMSNj:-O322wgV-xC9No_JChZi:b-4mi4em) ([raw file](https://github.com/starkware-libs/stwo/blob/ab413cab546a54d82077c79b0cea313aaab6f108/crates/prover/src/core/backend/simd/column.rs#L77)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I wonder if this should be safe_div here?
Also for zeros
</blockquote></details>

No, it should be div_ceil, since we support extra padding (this is why we save the original lenght, and not the divided length)

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 12 files at r1, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/763#-:-O3255ms48igx_IegvAc:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Alon-Ti)

**Pull request merged**
