### PR TITLE
Add wide fib lookup constraint.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/637)

### CODE REVIEW

**Comment by alonh5** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/637?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#637** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/637?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#636** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/636?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#634** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/634?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#633** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/633?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#631** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/631?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#582** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/582?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#589](https://github.com/starkware-libs/stwo/pull/589) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/589?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#573** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/573?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#574](https://github.com/starkware-libs/stwo/pull/574) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/574?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#572** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/572?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#562** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/562?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, 1 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/637)* status: 2 of 9 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @andrewmilson)

___
*[`crates/prover/src/core/constraints.rs` line 71 at r2](https://reviewable.io/reviews/starkware-libs/stwo/637#-O-WUN77DNnzjY81Iw6F:-O-WUN77DNnzjY81Iw6G:b2y5bpt) ([raw file](https://github.com/starkware-libs/stwo/blob/822ff20fe40e7c6ac79180e5e56908d95d359d30/crates/prover/src/core/constraints.rs#L71)):*
> ```XML
> ) -> EF {
>     let h = p - vanish_point.into_ef();
>     h.y / (EF::one() + h.x)
> ```

How come that you have to change this?



_Code quote:_
```XML
    let h = p - vanish_point.into_ef();
    h.y / (EF::one() + h.x)
```
___
*[`crates/prover/src/core/air/mod.rs` line 53 at r2](https://reviewable.io/reviews/starkware-libs/stwo/637#-O-WUE_c9iKL3ucj6eIU:-O-WUE_c9iKL3ucj6eIV:b-5mh60v) ([raw file](https://github.com/starkware-libs/stwo/blob/822ff20fe40e7c6ac79180e5e56908d95d359d30/crates/prover/src/core/air/mod.rs#L53)):*
> ```XML
>     fn max_constraint_log_degree_bound(&self) -> u32;
> 
>     fn n_phases(&self) -> u32;
> ```

Can you also document?



_Suggestion:_
```XML
fn n_interaction_phases(&self) -> u32;
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/637)* status: 2 of 9 files reviewed, 2 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`crates/prover/src/core/constraints.rs` line 71 at r2](https://reviewable.io/reviews/starkware-libs/stwo/637#-O-WUN77DNnzjY81Iw6F:-O-eAzJW3DLPUTTWPFnA:b-6cvegb) ([raw file](https://github.com/starkware-libs/stwo/blob/822ff20fe40e7c6ac79180e5e56908d95d359d30/crates/prover/src/core/constraints.rs#L71)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

How come that you have to change this?
</blockquote></details>

Because I'm now using it in `evaluate_constraint_quotients_at_point()` where the point `p` is of qm31, and the vanishing point is a point from the trace domain.
Previously this was used when evaluating the oods quotient so it had to be the other way around (we stopped using it regardless of this PR).
___
*[`crates/prover/src/core/air/mod.rs` line 53 at r2](https://reviewable.io/reviews/starkware-libs/stwo/637#-O-WUE_c9iKL3ucj6eIU:-O-eArea38cMkPiSQPkc:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/822ff20fe40e7c6ac79180e5e56908d95d359d30/crates/prover/src/core/air/mod.rs#L53)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can you also document?
</blockquote></details>

Done.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 5 files at r1, 2 of 7 files at r2, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/637#-:-O-eTI6w9kcc1wZkEz4K:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/637#-:-O-pELDPC-IFgD50VJEK:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @andrewmilson)

**Comment by alonh5** [comment]
### Merge activity

* **Jun 20, 6:54 AM EDT**: @alonh5 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/637).

**Pull request merged**
