### PR TITLE
eval_at_point opt

### PR DESCRIPTION
**Pull request by ohad-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/506)

### CODE REVIEW

**Comment by ohad-starkware** [comment]
* **#506** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/506?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ohad-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/506)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @andrewmilson and @ohad-starkware)

___
*[`src/core/backend/avx512/circle.rs` line 51 at r2](https://reviewable.io/reviews/starkware-libs/stwo/506#-NtGU83d1QoRe62-Nmd-:-NtGU83d1QoRe62-Nmd0:b-dg6oa0) ([raw file](https://github.com/starkware-libs/stwo/blob/c1b0a199622bf50dc49763628a0a93be6d71fe28/src/core/backend/avx512/circle.rs#L51)):*
> ```XML
> 
>     // TODO(Ohad): optimize.
>     fn twiddle_at<F: Field>(mappings: &[F], mut index: usize) -> F {
> ```

Can you use this in twiddle_lows?
___
*[`src/core/backend/avx512/circle.rs` line 253 at r2](https://reviewable.io/reviews/starkware-libs/stwo/506#-NtGUHB3EPQe_0j08D7G:-NtGUHB3EPQe_0j08D7H:b-mnlkv2) ([raw file](https://github.com/starkware-libs/stwo/blob/c1b0a199622bf50dc49763628a0a93be6d71fe28/src/core/backend/avx512/circle.rs#L253)):*
> ```XML
>             a.swap_with_slice(&mut c[0..n0]);
>             mappings.reverse();
>         }
> ```

Consider extracting this to a generic function that will be shared with exal_at_securefield_point



_Code quote:_
```XML
        let mut mappings = vec![point.y, point.x];
        let mut x = point.x;
        for _ in 2..poly.log_size() {
            x = CirclePoint::double_x(x);
            mappings.push(x);
        }

        // If the polynomial is large, the fft does a transpose in the middle.
        // TODO(Ohad): to avoid complexity for now, we just reverse the mappings, transpose, then
        // reverse back so the original transpose works. Optimize.
        if poly.log_size() as usize > CACHED_FFT_LOG_SIZE {
            mappings.reverse();
            let n = mappings.len();
            let n0 = (n - VECS_LOG_SIZE) / 2;
            let n1 = (n - VECS_LOG_SIZE + 1) / 2;
            let (ab, c) = mappings.split_at_mut(n1);
            let (a, _b) = ab.split_at_mut(n0);
            // Swap content of a,c.
            a.swap_with_slice(&mut c[0..n0]);
            mappings.reverse();
        }
```
___
*[`src/core/backend/avx512/circle.rs` line 265 at r2](https://reviewable.io/reviews/starkware-libs/stwo/506#-NtGUY4d5Mgu017KajCN:-NtGUY4d5Mgu017KajCO:b-hzqjjz) ([raw file](https://github.com/starkware-libs/stwo/blob/c1b0a199622bf50dc49763628a0a93be6d71fe28/src/core/backend/avx512/circle.rs#L265)):*
> ```XML
>         let mut sum = PackedBaseField::zeroed();
>         for (i, &coeff_chunk) in poly.coeffs.data.iter().enumerate() {
>             let cur_twiddle_high = AVX512Backend::twiddle_at(map_high, i);
> ```

Add a TODO: optimize aboev this line
___
*[`src/core/backend/avx512/circle.rs` line 366 at r2](https://reviewable.io/reviews/starkware-libs/stwo/506#-NtGUbmk45k1nDTWdLD6:-NtGUbmk45k1nDTWdLD7:b-ataz0f) ([raw file](https://github.com/starkware-libs/stwo/blob/c1b0a199622bf50dc49763628a0a93be6d71fe28/src/core/backend/avx512/circle.rs#L366)):*
> ```XML
>     #[test]
>     fn test_eval_basefield() {
>         use crate::core::backend::avx512::fft::MIN_FFT_LOG_SIZE;
> ```

Consider just comparing AVXBackend result to the CPUBackend result

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/506)* status: all files reviewed, 4 unresolved discussions (waiting on @andrewmilson and @ohad-starkware)

**Review by andrewmilson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/506)* status: 3 of 4 files reviewed, 7 unresolved discussions (waiting on @ohad-starkware and @spapinistarkware)

___
*[`src/core/backend/avx512/circle.rs` line 46 at r4](https://reviewable.io/reviews/starkware-libs/stwo/506#-NtK-WLL8hUK5it0jajE:-NtK-WLL8hUK5it0jajF:bcmrokf) ([raw file](https://github.com/starkware-libs/stwo/blob/5bba5a3aeced9706e0db51e05ac2c3520b771d1b/src/core/backend/avx512/circle.rs#L46)):*
> ```XML
>     // TODO(Ohad): consider moving this to to a more general place.
>     // Note: CACHED_FFT_LOG_SIZE is specific to the backend.
>     fn generate_evaluation_mappings<F: Field>(point: CirclePoint<F>, log_size: u32) -> Vec<F> {
> ```

I'd add a small amount of docs about the mappings and their order in relation to the transpose stuff - also perhaps link to the function that has the docs explaining the transpose details if it exists 🤞
___
*[`src/core/backend/avx512/m31.rs` line 114 at r4](https://reviewable.io/reviews/starkware-libs/stwo/506#-NtJyn9f2nlbUtNDbTxc:-NtJyn9f2nlbUtNDbTxd:b-qdprfs) ([raw file](https://github.com/starkware-libs/stwo/blob/5bba5a3aeced9706e0db51e05ac2c3520b771d1b/src/core/backend/avx512/m31.rs#L114)):*
> ```XML
>     pub fn pointwise_sum(self) -> M31 {
>         let v = self.to_array();
>         v.iter().fold(M31::zero(), |acc, x| acc + *x)
> ```

Once https://github.com/starkware-libs/stwo/pull/497 is merged (just added you to review) can do 



_Code snippet:_
```XML
self.to_array().into_iter().sum()
```
___
*[`src/core/poly/circle/ops.rs` line 52 at r4](https://reviewable.io/reviews/starkware-libs/stwo/506#-NtK16v35Lxpx7eO9uec:-NtK16v35Lxpx7eO9ued:b-1fw1dh) ([raw file](https://github.com/starkware-libs/stwo/blob/5bba5a3aeced9706e0db51e05ac2c3520b771d1b/src/core/poly/circle/ops.rs#L52)):*
> ```XML
>     fn precompute_twiddles(coset: Coset) -> TwiddleTree<Self>;
> 
>     fn eval_at_basefield_point(poly: &CirclePoly<Self>, point: CirclePoint<BaseField>)
> ```

nit: Thoughts?



_Suggestion:_
```XML
eval_at_base_point
```

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/506#-:-NtLk2Fm-suiAYZa04Si:bnfp4nl)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @ohad-starkware)

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/506)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @andrewmilson and @spapinistarkware)

___
*[`src/core/backend/avx512/circle.rs` line 46 at r4](https://reviewable.io/reviews/starkware-libs/stwo/506#-NtK-WLL8hUK5it0jajE:-NtPsnf4Dpm1fBYV53cE:b-7hbpla) ([raw file](https://github.com/starkware-libs/stwo/blob/5bba5a3aeced9706e0db51e05ac2c3520b771d1b/src/core/backend/avx512/circle.rs#L46)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

I'd add a small amount of docs about the mappings and their order in relation to the transpose stuff - also perhaps link to the function that has the docs explaining the transpose details if it exists 🤞
</blockquote></details>

wdyt?
___
*[`src/core/backend/avx512/m31.rs` line 114 at r4](https://reviewable.io/reviews/starkware-libs/stwo/506#-NtJyn9f2nlbUtNDbTxc:-NtPjYEq0JVEWfXIAJqc:bt1dwm8) ([raw file](https://github.com/starkware-libs/stwo/blob/5bba5a3aeced9706e0db51e05ac2c3520b771d1b/src/core/backend/avx512/m31.rs#L114)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Once https://github.com/starkware-libs/stwo/pull/497 is merged (just added you to review) can do
</blockquote></details>

done, thank you.
___
*[`src/core/poly/circle/ops.rs` line 52 at r4](https://reviewable.io/reviews/starkware-libs/stwo/506#-NtK16v35Lxpx7eO9uec:-NtPjjl5A42Y_t6daUco:bj0jjt8) ([raw file](https://github.com/starkware-libs/stwo/blob/5bba5a3aeced9706e0db51e05ac2c3520b771d1b/src/core/poly/circle/ops.rs#L52)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

nit: Thoughts?
</blockquote></details>

it's confusing to me without the field word

**Review by andrewmilson — APPROVED** [review]
:lgtm:
:lgtm:

> Reviewed 2 of 3 files at r2, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/506#-:-NtUR_DWEsTG5SR4UyUe:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ohad-starkware)

___
*[`src/core/backend/avx512/circle.rs` line 46 at r4](https://reviewable.io/reviews/starkware-libs/stwo/506#-NtK-WLL8hUK5it0jajE:-NtUO9Yc9L_-Ng7ukqHB:b-7af3cd) ([raw file](https://github.com/starkware-libs/stwo/blob/5bba5a3aeced9706e0db51e05ac2c3520b771d1b/src/core/backend/avx512/circle.rs#L46)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

wdyt?
</blockquote></details>

Nit: Looks good but instead of adding the comments in the function body I'd suggest adding them as docstrings to the function. Up to you, LGTMed the PR

**Review by ohad-starkware — COMMENTED** [review]
closed pr and implemented in securefield instead.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/506#-:-NtUdYym-LpajbFwbXPu:bhewomm)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ohad-starkware)

**Pull request closed without merging**
