### PR TITLE
Treespan

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/735)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
* **#735** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/735?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ohad-agadi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/735)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/core/pcs/prover.rs` line 156 at r2](https://reviewable.io/reviews/starkware-libs/stwo/735#-O2OCEo60Q0XPvXT-MDW:-O2OCEo60Q0XPvXT-MDX:b-nyro4g) ([raw file](https://github.com/starkware-libs/stwo/blob/eacdde377a864ec2ed6173d8a2031552b60b2e47/crates/prover/src/core/pcs/prover.rs#L156)):*
> ```XML
>     polys: ColumnVec<CirclePoly<B>>,
> }
> impl<'a, 'b, B: Backend + MerkleOps<MerkleHasher>> TreeBuilder<'a, 'b, B> {
> ```

drop line

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/735)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`crates/prover/src/core/pcs/prover.rs` line 156 at r2](https://reviewable.io/reviews/starkware-libs/stwo/735#-O2OCEo60Q0XPvXT-MDW:-O2cbQnL7moPSNImz-LJ:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/eacdde377a864ec2ed6173d8a2031552b60b2e47/crates/prover/src/core/pcs/prover.rs#L156)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

drop line
</blockquote></details>

Done.

**Review by ohad-agadi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/735#-:-O2cbZI2-L1UNlOfY11G:bnfp4nl)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Pull request merged**
