### PR TITLE
added mul to backend fieldops

### PR DESCRIPTION
**Pull request by ohad-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/441)

### CODE REVIEW

**Comment by ohad-starkware** [comment]
* **#441** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/441?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ohad-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — COMMENTED** [review]
Where is this gonna be used?

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/441#-:-NsMPK-v8oTYGQO9iMlL:b-dg06ne)* status: 0 of 3 files reviewed, all discussions resolved

**Review by ohad-starkware — COMMENTED** [review]
in the quotienting part of the fib component. It serves two purposes:
1. keeping values in terms of columns allows reuse of memory (because the implementation is hidden from the user, but the backend knows how to do it)
2. it's faster if the backend is faster. 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/441#-:-NsMQnAU2lejQL__1wG6:b-6xnmr1)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
As discussed, please close this

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/441#-:-NsXZqxO04ouhRCA6omM:bsdufm)* status: 0 of 3 files reviewed, all discussions resolved

**Pull request closed without merging**
