### PR TITLE
Change Eval Framework `Copy` requirement to `Clone`.

### PR DESCRIPTION
**Pull request by Alon-Ti**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/834)

### CODE REVIEW

**Comment by Alon-Ti** [comment]
* **#836** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/836?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#835** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/835?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#834** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/834?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Alon-Ti and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by andrewmilson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/834)* status: 0 of 23 files reviewed, 2 unresolved discussions (waiting on @Alon-Ti and @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/mod.rs` line 87 at r1](https://reviewable.io/reviews/starkware-libs/stwo/834#-O737WTlC3Q2n8zfSAWY:-O737WTlC3Q2n8zfSAWZ:b-6jausq) ([raw file](https://github.com/starkware-libs/stwo/blob/5cea2f8fbdb489bf4ab283f1e69f36b98650ac86/crates/prover/src/constraint_framework/mod.rs#L87)):*
> ```XML
>     ) -> [Self::EF; N] {
>         let res_col_major = array::from_fn(|_| self.next_interaction_mask(interaction, offsets));
>         array::from_fn(|i| Self::combine_ef(res_col_major.clone().map(|c| c[i].clone())))
> ```

Suggestion: without clone



_Suggestion:_
```XML
        let mut res_col_major =
            array::from_fn(|_| self.next_interaction_mask(interaction, offsets).into_iter());
        array::from_fn(|_| {
            Self::combine_ef(res_col_major.each_mut().map(|iter| iter.next().unwrap()))
        })
```
___
*[`crates/prover/src/core/fields/mod.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/stwo/834#-O73SkcM7NWYUF7epTet:-O73SkcM7NWYUF7epTeu:bejyn65) ([raw file](https://github.com/starkware-libs/stwo/blob/f7871979e6ea8e606dc4674301b7d8b28b5838ed/crates/prover/src/core/fields/mod.rs#L100)):*
> ```XML
>     + Neg<Output = Self>
>     + ComplexConjugate
>     + Copy
> ```

Does this need to have Copy removed?



_Code quote:_
```XML
+ Copy
```

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/834)* status: 0 of 23 files reviewed, 3 unresolved discussions (waiting on @Alon-Ti and @andrewmilson)

*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo/834#-O78QEQn84rakoQKkCNS:-O78QEQn84rakoQKkCNT:b-6s0zu7) (no related file):*
Main change here is that we removed the Copy trait for Field?
Can you explain why is it better?

___

**Review by Alon-Ti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/834)* status: 0 of 23 files reviewed, 3 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo/834#-O78QEQn84rakoQKkCNS:-O7OMW3X89gJD6YqFR1C:b-vyqou0) (no related file):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Main change here is that we removed the Copy trait for Field?
Can you explain why is it better?
</blockquote></details>

We replace `Copy` with `Clone`, the reason is that `Copy` can only be implemented for objects that can be copied by copying the underlying binary repr (so they should generally be small and constant size), while the formal polynomials are not.

For types that have `Copy`, `.clone()` should use it and be "optimized out", so this shouldn't change what the current code compiles to.

___
___
*[`crates/prover/src/constraint_framework/mod.rs` line 87 at r1](https://reviewable.io/reviews/starkware-libs/stwo/834#-O737WTlC3Q2n8zfSAWY:-O7OReiyEaZkwf4IabE1:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/5cea2f8fbdb489bf4ab283f1e69f36b98650ac86/crates/prover/src/constraint_framework/mod.rs#L87)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Suggestion: without clone
</blockquote></details>

Done.
___
*[`crates/prover/src/core/fields/mod.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/stwo/834#-O73SkcM7NWYUF7epTet:-O7ORv3Q0VQFBCxKY2jQ:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/f7871979e6ea8e606dc4674301b7d8b28b5838ed/crates/prover/src/core/fields/mod.rs#L100)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Does this need to have Copy removed?
</blockquote></details>

Done.

**Review by andrewmilson — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/834#-:-O7Rsv2T38JfYeJDQCcu:bnfp4nl)* status: 0 of 23 files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7)

**Review by andrewmilson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/834)* status: 0 of 23 files reviewed, 4 unresolved discussions (waiting on @Alon-Ti and @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/logup.rs` line 51 at r3](https://reviewable.io/reviews/starkware-libs/stwo/834#-O7XQv0NBn26ZQiHjTDb:-O7XQv0NBn26ZQiHjTDc:b45h) ([raw file](https://github.com/starkware-libs/stwo/blob/bd15d949eec9a54c491e433afd6a830e8570dec7/crates/prover/src/constraint_framework/logup.rs#L51)):*
> ```XML
>         // Add a constraint that num / denom = diff.
>         if let Some(cur_frac) = self.cur_frac.clone() {
>             let cur_cumsum = eval.next_extension_interaction_mask(self.interaction, [0])[0].clone();
> ```





_Suggestion:_
```XML
let [cur_cumsum] = eval.next_extension_interaction_mask(self.interaction, [0]);
```

**Review by andrewmilson — APPROVED** [review]
:lgtm: with comments

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/834#-:-O7XSsCc3TKbX0gDi171:bvaci67)* status: 0 of 23 files reviewed, 7 unresolved discussions (waiting on @Alon-Ti and @shaharsamocha7)

___
*[`crates/prover/src/examples/blake/round/constraints.rs` line 203 at r3](https://reviewable.io/reviews/starkware-libs/stwo/834#-O7XRh4t3hvrmVnz-9KC:-O7XRh4t3hvrmVnz-9KD:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/bd15d949eec9a54c491e433afd6a830e8570dec7/crates/prover/src/examples/blake/round/constraints.rs#L203)):*
> ```XML
>             numerator: comb0.clone() + comb1.clone(),
>             denominator: comb0 * comb1,
>         };
> ```





_Suggestion:_
```XML
Reciprocal::new(comb0) + Reciprocal::new(comb1)
```
___
*[`crates/prover/src/examples/blake/scheduler/constraints.rs` line 40 at r3](https://reviewable.io/reviews/starkware-libs/stwo/834#-O7XReFnBAm18xmZngD6:-O7XReFnBAm18xmZngD7:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/bd15d949eec9a54c491e433afd6a830e8570dec7/crates/prover/src/examples/blake/scheduler/constraints.rs#L40)):*
> ```XML
>         logup.write_frac(
>             eval,
>             Fraction::new(denom_i.clone() + denom_j.clone(), denom_i * denom_j),
> ```





_Suggestion:_
```XML
Reciprocal::new(denom_i) + Reciprocal::new(denom_j)
```
___
*[`crates/prover/src/examples/poseidon/mod.rs` line 198 at r3](https://reviewable.io/reviews/starkware-libs/stwo/834#-O7XRtaaC2cNhwjz1_d6:-O7XRtaaC2cNhwjz1_d7:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/bd15d949eec9a54c491e433afd6a830e8570dec7/crates/prover/src/examples/poseidon/mod.rs#L198)):*
> ```XML
>                 final_state_denom.clone() - initial_state_denom.clone(),
>                 initial_state_denom.clone() * final_state_denom.clone(),
>             ),
> ```





_Suggestion:_
```XML
            Reciprocal::new(final_state_denom) - Reciprocal::new(initial_state_denom),
```

**Comment by Alon-Ti** [comment]
### Merge activity

* **Sep 25, 9:20 AM EDT**: [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/834) disabled "merge when ready" on this PR due to: a merge conflict with the target branch; resolve the conflict and try again..

**Review by andrewmilson — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/834#-:-O7ew4_wDPy_nWUBf5P8:bnfp4nl)* status: 0 of 23 files reviewed, 6 unresolved discussions (waiting on @shaharsamocha7)

**Pull request merged**
