### PR TITLE
Serde Serialize/Deserialize on StarkProof

### LINKED ISSUE #731: Derive Serde for StarkProof Struct
## Title
Derive Serde for StarkProof Struct

## Description
Currently, the `StarkProof` struct does not implement serialization and deserialization via `serde`, which is necessary for our application to easily convert proofs to and from JSON format. Implementing `serde` will also allow for better interoperability with other services that consume or produce JSON data.

## Expected Behavior
After implementing `serde`:
- The `StarkProof` struct should be serializable to JSON format.
- The `StarkProof` struct should be deserializable from JSON format.

## Possible Solution
- Add `serde` crate to `Cargo.toml` if not already included:
  ```toml
  [dependencies]
  serde = { version = "1.0", features = ["derive"] }
  serde_json = "1.0"
  ```

- Modify the `StarkProof` struct definition to derive `Serialize` and `Deserialize`:
  ```rust
  #[derive(Serialize, Deserialize)]
  pub struct StarkProof {
      // struct fields
  }
  ```

- Ensure that all fields within the `StarkProof` struct are also compatible with `serde`.

## Additional Context
- This change will facilitate the development team in handling the proof data more efficiently, especially when interfacing with web applications.
- It's important to ensure that the serialization and deserialization process preserves all critical information within the struct without any data loss.

### PR DESCRIPTION
**Pull request by MSghais**
@AbdelStark close #731 

- Add serde and serde_json to the Cargo.toml of the crates prover.
- Serde macro to StarkProof struct.
- Serde to all attributes that's need this implement: CommitmentSchemeProof

Tests unit in the exemples:
1. Serialize & Deserialize test in exemples test unitaires: Fibo + Wide Fibo + Poseidon

2. Verify the deserialization & serialization of different attributes of the StarkProof:
- Commitments 
- Lookup
- Last layer poly
Commitment scheme proof Struct:
- Queried values
- Proof_of_work.Nnonce
- Decommitments
- Sampled values

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/732)

### CODE REVIEW

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 23 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/732)* status: all files reviewed, 3 unresolved discussions (waiting on @MSghais)

*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo/732#-O1znP7IBpRi5pK9QAqU:-O1znP7IBpRi5pK9QAqV:b-de5qmq) (no related file):*
Please run rust fmt on all files.

___
___
*[`crates/prover/src/core/vcs/ops.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/stwo/732#-O1zbfMs13FuG0PN3SiK:-O1zbfMs13FuG0PN3SiL:bco1vef) ([raw file](https://github.com/starkware-libs/stwo/blob/8401c93393108639750c3b3bbda05586c427ff2a/crates/prover/src/core/vcs/ops.rs#L24)):*
> ```XML
> }
> ```

Remove blank line.
___
*[`crates/prover/src/examples/fibonacci/mod.rs` line 248 at r1](https://reviewable.io/reviews/starkware-libs/stwo/732#-O1znTkfDFnpnIu10mGq:-O1znTkfDFnpnIu10mGr:bqj6o21) ([raw file](https://github.com/starkware-libs/stwo/blob/8401c93393108639750c3b3bbda05586c427ff2a/crates/prover/src/examples/fibonacci/mod.rs#L248)):*
> ```XML
> 
>     #[test]
>     fn test_fib_prove_and_serialize() {
> ```

You can remove all the tests - the serde crate ensures you're getting the same object.

**Comment by MSghais** [comment]
> > Reviewed 23 of 23 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/732)_ status: all files reviewed, 3 unresolved discussions (waiting on @MSghais)
> 
> _[a discussion](https://reviewable.io/reviews/starkware-libs/stwo/732#-O1znP7IBpRi5pK9QAqU:-O1znP7IBpRi5pK9QAqV:b-de5qmq) (no related file):_ Please run rust fmt on all files.
> 
> _[`crates/prover/src/core/vcs/ops.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/stwo/732#-O1zbfMs13FuG0PN3SiK:-O1zbfMs13FuG0PN3SiL:bco1vef) ([raw file](https://github.com/starkware-libs/stwo/blob/8401c93393108639750c3b3bbda05586c427ff2a/crates/prover/src/core/vcs/ops.rs#L24)):_
> 
> > ```
> > }
> > ```
> 
> Remove blank line.
> 
> _[`crates/prover/src/examples/fibonacci/mod.rs` line 248 at r1](https://reviewable.io/reviews/starkware-libs/stwo/732#-O1znTkfDFnpnIu10mGq:-O1znTkfDFnpnIu10mGr:bqj6o21) ([raw file](https://github.com/starkware-libs/stwo/blob/8401c93393108639750c3b3bbda05586c427ff2a/crates/prover/src/examples/fibonacci/mod.rs#L248)):_
> 
> > ```
> >     #[test]
> >     fn test_fib_prove_and_serialize() {
> > ```
> 
> You can remove all the tests - the serde crate ensures you're getting the same object.

Done thank you.
I've others tests on the exemple that's check the correct dese/seria of differents attributes. I need to delete it too?

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 12 of 14 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/732)* status: all files reviewed, 3 unresolved discussions (waiting on @MSghais)

___
*[`crates/prover/src/examples/fibonacci/mod.rs` line 248 at r1](https://reviewable.io/reviews/starkware-libs/stwo/732#-O1znTkfDFnpnIu10mGq:-O2-CL0bBJ2VX7k9nDV_:brau2gw) ([raw file](https://github.com/starkware-libs/stwo/blob/8401c93393108639750c3b3bbda05586c427ff2a/crates/prover/src/examples/fibonacci/mod.rs#L248)):*
<details><summary><i>Previously, MSghais (MSG) wrote…</i></summary><blockquote>

Done thank you.
I've others tests on the exemple that's check the correct dese/seria of differents attributes. I need to delete it too?

</blockquote></details>

Yes, remove all the serde tests.

**Comment by MSghais** [comment]
@alonh5 Hi, anything else I need to change to merged this PR?
If I can do something else, let me know!

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 23 files at r1, 1 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/732)* status: 4 of 23 files reviewed, 3 unresolved discussions (waiting on @MSghais)

___
*[`crates/prover/src/examples/wide_fibonacci/simd.rs` line 294 at r4](https://reviewable.io/reviews/starkware-libs/stwo/732#-O2OIVydBRoJNjSeaeNl:-O2OIVydBRoJNjSeaeNm:b-8u2lj9) ([raw file](https://github.com/starkware-libs/stwo/blob/cd96d667acded12e3a35b5d69f4e2eec711befe1/crates/prover/src/examples/wide_fibonacci/simd.rs#L294)):*
> ```XML
> 
>         // Deserialize & Serialize test
>         let serialize = serde_json::to_string(&proof).unwrap();
> ```

Please remove this test. Are there any other tests added for the (de)serialization?

**Review by alonh5 — COMMENTED** [review]
> Reviewed 5 of 23 files at r1, 10 of 14 files at r2, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/732)* status: all files reviewed, 3 unresolved discussions (waiting on @MSghais)

**Comment by MSghais** [comment]
> > Reviewed 1 of 23 files at r1, 1 of 14 files at r2.
> > _[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/732)_ status: 4 of 23 files reviewed, 3 unresolved discussions (waiting on @MSghais)
> 
> _[`crates/prover/src/examples/wide_fibonacci/simd.rs` line 294 at r4](https://reviewable.io/reviews/starkware-libs/stwo/732#-O2OIVydBRoJNjSeaeNl:-O2OIVydBRoJNjSeaeNm:b-8u2lj9) ([raw file](https://github.com/starkware-libs/stwo/blob/cd96d667acded12e3a35b5d69f4e2eec711befe1/crates/prover/src/examples/wide_fibonacci/simd.rs#L294)):_
> 
> > ```
> >         // Deserialize & Serialize test
> >         let serialize = serde_json::to_string(&proof).unwrap();
> > ```
> 
> Please remove this test. Are there any other tests added for the (de)serialization?

Hi, all tests to verify the de(serialization) are removed now. Thank you

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/732#-:-O2OdRfoBkQzLGt4meRU:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @MSghais)

**Review by alonh5 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/732)* status: all files reviewed, 2 unresolved discussions (waiting on @MSghais)

*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo/732#-O2OoBDxAtyUzXtgDWjH:-O2OoBDxAtyUzXtgDWjI:b-eduyon) (no related file):*
The udeps test failed: 
```
unused dependencies:
`stwo-prover v0.1.1 (/home/runner/work/stwo/stwo/crates/prover)`
└─── dependencies
     └─── "serde_json"
```

Did you mean to use that package as well?

___

**Comment by MSghais** [comment]
> > _[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/732)_ status: all files reviewed, 2 unresolved discussions (waiting on @MSghais)
> 
> _[a discussion](https://reviewable.io/reviews/starkware-libs/stwo/732#-O2OoBDxAtyUzXtgDWjH:-O2OoBDxAtyUzXtgDWjI:b-eduyon) (no related file):_ The udeps test failed:
> 
> ```
> unused dependencies:
> `stwo-prover v0.1.1 (/home/runner/work/stwo/stwo/crates/prover)`
> └─── dependencies
>      └─── "serde_json"
> ```
> 
> Did you mean to use that package as well?

Hi, I removed this unused package now sorry! 
Thank you for the help and patience ahah

**Review by alonh5 — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/732)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MSghais)

**Pull request merged**
