### PR TITLE
FRI: Enforce one column per size.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**

### CODE REVIEW

**Review by andrewmilson — APPROVED** [review]
:lgtm: with comment

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/905#-:-OChnnTF6WKooJ3c9de1:b10c0l0)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/prover/src/core/fri.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/stwo/905#-OChntMPBB3p0fbAf-x_:-OChntMPBB3p0fbAf-xa:b-qoy1i9) ([raw file](https://github.com/starkware-libs/stwo/blob/d0cbf1207eb6d94ae23a3cca1b025e354e9ff876/crates/prover/src/core/fri.rs#L159)):*
> ```XML
>         channel: &mut MC::C,
>         config: FriConfig,
>         columns: &'a [SecureEvaluation<B, BitReversedOrder>],
> ```

Not changing to BTreeMap?



_Code quote:_
```XML
columns: &'a [SecureEvaluation<B, BitReversedOrder>],
```
___
*[`crates/prover/src/core/fri.rs` line 164 at r1](https://reviewable.io/reviews/starkware-libs/stwo/905#-OChnQPT9UE35SSxtLjK:-OChnQPT9UE35SSxtLjL:b-b592gg) ([raw file](https://github.com/starkware-libs/stwo/blob/d0cbf1207eb6d94ae23a3cca1b025e354e9ff876/crates/prover/src/core/fri.rs#L164)):*
> ```XML
>         assert!(!columns.is_empty(), "no columns");
>         assert!(columns.is_sorted_by_key(|e| Reverse(e.len())), "not sorted");
>         assert!(columns.iter().map(|e| e.len()).dedup_with_count().all(|(count, _)| count == 1), "duplicate sizes");
> ```

These can be combined



_Suggestion:_
```XML
        assert!(columns.array_windows().all(|[a, b]| a.len() > b.len()));
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/prover/src/core/fri.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/stwo/905#-OChntMPBB3p0fbAf-x_:-OCi4s6RDZUJNYB1xVSM:b-tlsfoj) ([raw file](https://github.com/starkware-libs/stwo/blob/d0cbf1207eb6d94ae23a3cca1b025e354e9ff876/crates/prover/src/core/fri.rs#L159)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Not changing to BTreeMap?
</blockquote></details>

I tried:
https://reviewable.io/reviews/starkware-libs/stwo/907

It is not obvious what the key should be.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/prover/src/core/fri.rs` line 164 at r1](https://reviewable.io/reviews/starkware-libs/stwo/905#-OChnQPT9UE35SSxtLjK:-OCiAtlH1Q92aOwJni44:bq21wzo) ([raw file](https://github.com/starkware-libs/stwo/blob/d0cbf1207eb6d94ae23a3cca1b025e354e9ff876/crates/prover/src/core/fri.rs#L164)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

These can be combined
</blockquote></details>

I'm getting:
error[E0658]: use of unstable library feature 'array_windows'
   --> crates/prover/src/core/fri.rs:163:25

**Review by andrewmilson — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/905#-:-OCiF4WL5G_RWsWx6MMN:bnfp4nl)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/prover/src/core/fri.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/stwo/905#-OChntMPBB3p0fbAf-x_:-OCiEz-H6U94wULzIYxG:bzczab) ([raw file](https://github.com/starkware-libs/stwo/blob/d0cbf1207eb6d94ae23a3cca1b025e354e9ff876/crates/prover/src/core/fri.rs#L159)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I tried:
https://reviewable.io/reviews/starkware-libs/stwo/907

It is not obvious what the key should be.
</blockquote></details>

Ahh makes sense. Yeah array better
___
*[`crates/prover/src/core/fri.rs` line 164 at r1](https://reviewable.io/reviews/starkware-libs/stwo/905#-OChnQPT9UE35SSxtLjK:-OCiEU473GPNmpkOfpvk:b-tu8fv7) ([raw file](https://github.com/starkware-libs/stwo/blob/d0cbf1207eb6d94ae23a3cca1b025e354e9ff876/crates/prover/src/core/fri.rs#L164)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I'm getting:
error[E0658]: use of unstable library feature 'array_windows'
   --> crates/prover/src/core/fri.rs:163:25
</blockquote></details>

Can add to the top of lib.rs with the other unstable library features

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/905)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @andrewmilson)

___
*[`crates/prover/src/core/fri.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/stwo/905#-OChntMPBB3p0fbAf-x_:-OClgqHP39SGjDmYfm5H:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/d0cbf1207eb6d94ae23a3cca1b025e354e9ff876/crates/prover/src/core/fri.rs#L159)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Ahh makes sense. Yeah array better
</blockquote></details>

Done.
___
*[`crates/prover/src/core/fri.rs` line 164 at r1](https://reviewable.io/reviews/starkware-libs/stwo/905#-OChnQPT9UE35SSxtLjK:-OCljSWX9q2bL6I3WHd8:bu4ozr6) ([raw file](https://github.com/starkware-libs/stwo/blob/d0cbf1207eb6d94ae23a3cca1b025e354e9ff876/crates/prover/src/core/fri.rs#L164)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Can add to the top of lib.rs with the other unstable library features
</blockquote></details>

Done.
Thanks.

**Pull request merged**
