### PR TITLE
Exported shared code to temp variables in ExprEvaluator.

### PR DESCRIPTION
**Pull request by Alon-Ti**

### CODE REVIEW

**Comment by Alon-Ti** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/893?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#893** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/893?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/893?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#892** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/892?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#889** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/889?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#888** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/888?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#887** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/887?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#879** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/879?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#883](https://github.com/starkware-libs/stwo/pull/883) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/883?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#876** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/876?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#875** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/875?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/893)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/expr.rs` line 328 at r1](https://reviewable.io/reviews/starkware-libs/stwo/893#-OC-8Oxr5uDCbEu3zVXl:-OC8Ly5JBK33A28V-saA:b-oysgnd) ([raw file](https://github.com/starkware-libs/stwo/blob/0036faebcb22b315e5417b0f0a709ba10e5724e9/crates/prover/src/constraint_framework/expr.rs#L328)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

This was a pain to keep up to date, doesn't mean much to the reader, and became kind of redundant with the repr test.
</blockquote></details>

yes this is not a good test

**Review by ohad-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/893)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @Alon-Ti and @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/expr.rs` line 245 at r3](https://reviewable.io/reviews/starkware-libs/stwo/893#-OCTKPBh15CfXJbnpyb8:-OCTKPBh15CfXJbnpyb9:bhr47u5) ([raw file](https://github.com/starkware-libs/stwo/blob/d88f160d39aa1eddac4363126fd54af2a90faf7c/crates/prover/src/constraint_framework/expr.rs#L245)):*
> ```XML
>     pub logup: FormalLogupAtRow,
>     pub temp_vars: Vec<(String, Expr)>,
>     cur_temp_var_index: usize,
> ```

.len()
___
*[`crates/prover/src/constraint_framework/expr.rs` line 255 at r3](https://reviewable.io/reviews/starkware-libs/stwo/893#-OCTJycz0J2g_TXi64Pp:-OCTJycz0J2g_TXi64Pq:b45h) ([raw file](https://github.com/starkware-libs/stwo/blob/d88f160d39aa1eddac4363126fd54af2a90faf7c/crates/prover/src/constraint_framework/expr.rs#L255)):*
> ```XML
>             constraints: Default::default(),
>             logup: FormalLogupAtRow::new(INTERACTION_TRACE_IDX, has_partial_sum, log_size),
>             temp_vars: vec![],
> ```





_Suggestion:_
```XML
intermediates
```

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/893)* status: all files reviewed, 3 unresolved discussions (waiting on @Alon-Ti)

___
*[`crates/prover/src/constraint_framework/expr.rs` line 318 at r3](https://reviewable.io/reviews/starkware-libs/stwo/893#-OCTR9na64TZ31KnjUYD:-OCTR9na64TZ31KnjUYE:brob157) ([raw file](https://github.com/starkware-libs/stwo/blob/d88f160d39aa1eddac4363126fd54af2a90faf7c/crates/prover/src/constraint_framework/expr.rs#L318)):*
> ```XML
>         } else {
>             unreachable!();
>         }
> ```

Change to match



_Code quote:_
```XML
        if let Expr::Mul(one, constraint) = Expr::one() * constraint {
            assert_eq!(*one, Expr::one());
            self.constraints.push(*constraint);
        } else {
            unreachable!();
        }
```

**Review by Alon-Ti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/893)* status: all files reviewed, 3 unresolved discussions (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/expr.rs` line 245 at r3](https://reviewable.io/reviews/starkware-libs/stwo/893#-OCTKPBh15CfXJbnpyb8:-OCTxgxvCL992UJyg85A:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/d88f160d39aa1eddac4363126fd54af2a90faf7c/crates/prover/src/constraint_framework/expr.rs#L245)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

.len()
</blockquote></details>

Done.
___
*[`crates/prover/src/constraint_framework/expr.rs` line 318 at r3](https://reviewable.io/reviews/starkware-libs/stwo/893#-OCTR9na64TZ31KnjUYD:-OCTxmAoBsAZhqPm80Lo:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/d88f160d39aa1eddac4363126fd54af2a90faf7c/crates/prover/src/constraint_framework/expr.rs#L318)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Change to match
</blockquote></details>

Done.
___
*[`crates/prover/src/constraint_framework/expr.rs` line 255 at r3](https://reviewable.io/reviews/starkware-libs/stwo/893#-OCTJycz0J2g_TXi64Pp:-OCTxha60YbR25iODHjF:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/d88f160d39aa1eddac4363126fd54af2a90faf7c/crates/prover/src/constraint_framework/expr.rs#L255)):*
> ```XML
>             constraints: Default::default(),
>             logup: FormalLogupAtRow::new(INTERACTION_TRACE_IDX, has_partial_sum, log_size),
>             temp_vars: vec![],
> ```

Done.

**Review by ohad-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/893)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @Alon-Ti and @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/expr.rs` line 311 at r1](https://reviewable.io/reviews/starkware-libs/stwo/893#-OCXi1crCml59sX1SzWz:-OCXi1crCml59sX1SzX-:b-rnhooz) ([raw file](https://github.com/starkware-libs/stwo/blob/6a8182bcfd38228de54b6df629f7dc6b7da75377/crates/prover/src/constraint_framework/expr.rs#L311)):*
> ```XML
>     fn add_constraint<G>(&mut self, constraint: G)
>     where
>         Self::EF: std::ops::Mul<G, Output = Self::EF>,
> ```

add From<G> to the trait function, and use .into here instead of all this 



_Code quote:_
```XML
 Self::EF: std::ops::Mul<G, Output = Self::EF>
```

**Review by Alon-Ti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/893)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/expr.rs` line 311 at r1](https://reviewable.io/reviews/starkware-libs/stwo/893#-OCXi1crCml59sX1SzWz:-OCY-GZo9ub0TurAhPYl:byushy6) ([raw file](https://github.com/starkware-libs/stwo/blob/6a8182bcfd38228de54b6df629f7dc6b7da75377/crates/prover/src/constraint_framework/expr.rs#L311)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

add From<G> to the trait function, and use .into here instead of all this
</blockquote></details>

Fixed in 901.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/893)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @Alon-Ti and @ohad-starkware)

___
*[`crates/prover/src/constraint_framework/expr.rs` line 265 at r5](https://reviewable.io/reviews/starkware-libs/stwo/893#-OCYBpUw6T4WoriPWTrB:-OCYBpUw6T4WoriPWTrC:b-fn2t41) ([raw file](https://github.com/starkware-libs/stwo/blob/1a8cb5c059a531abcf7aeaa52b40d38ebc83f507/crates/prover/src/constraint_framework/expr.rs#L265)):*
> ```XML
>     }
> 
>     pub fn add_temp_var(&mut self, expr: Expr) -> Expr {
> ```

do we want to call it temp_var or intermediate?
In all places



_Code quote:_
```XML
pub fn add_temp_var(&mut self, expr: Expr) -> Expr {
```

**Review by ohad-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/893#-:-OCYnfDtC9aWukj2Adh2:bnfp4nl)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Alon-Ti and @shaharsamocha7)

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/893#-:-OCbXezeDIWM4u5wsQGG:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Alon-Ti)

**Pull request merged**
