### PR TITLE
Logup trace generation

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/711)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/711?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#712** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/712?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#711** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/711?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#710** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/710?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#708** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/708?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#707** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/707?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#706** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/706?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#705** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/705?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#704** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/704?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#702** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/702?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#701** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/701?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/711)* status: 0 of 6 files reviewed, 1 unresolved discussion

___
*[`crates/prover/src/constraint_framework/logup.rs` line 118 at r2](https://reviewable.io/reviews/starkware-libs/stwo/711#-O23yxkJ0rWE-TCVknOd:-O23yxkJ0rWE-TCVknOe:bqvs803) ([raw file](https://github.com/starkware-libs/stwo/blob/cd56fad618287d42ad425aebe9a5d530809f1b48/crates/prover/src/constraint_framework/logup.rs#L118)):*
> ```XML
> }
> 
> // TODO(spapini): Consider adding optional Ops.
> ```

Use the prefix sum andrew added

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r3, 2 of 3 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/711)* status: 6 of 7 files reviewed, 4 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/constraint_framework/logup.rs` line 133 at r5](https://reviewable.io/reviews/starkware-libs/stwo/711#-O2t2lIp8_qjkAEES03D:-O2t2lIp8_qjkAEES03E:b10700h) ([raw file](https://github.com/starkware-libs/stwo/blob/5e4f90b5395b7e720d37bebb8c12a5a6c74a5422/crates/prover/src/constraint_framework/logup.rs#L133)):*
> ```XML
>         FieldExpOps::batch_inverse(&self.gen.denom.data, &mut self.gen.denom_inv.data);
> 
>         #[allow(clippy::needless_range_loop)]
> ```

Are you sure you need this?



_Code quote:_
```XML
        #[allow(clippy::needless_range_loop)]
```
___
*[`crates/prover/src/core/fields/secure_column.rs` line 50 at r5](https://reviewable.io/reviews/starkware-libs/stwo/711#-O2t6EX1D7mNXPGfBFRa:-O2t6EX1D7mNXPGfBFRb:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/5e4f90b5395b7e720d37bebb8c12a5a6c74a5422/crates/prover/src/core/fields/secure_column.rs#L50)):*
> ```XML
>             self.columns[i].set(index, value.to_m31_array()[i]);
>         }
>     }
> ```





_Suggestion:_
```XML
    pub fn set(&mut self, index: usize, value: SecureField) {
        let value_array = value.to_m31_array();
        for i in 0..SECURE_EXTENSION_DEGREE {
            self.columns[i].set(index, value_array[i]);
        }
    }
```
___
*[`crates/prover/src/examples/poseidon/mod.rs` line 399 at r5](https://reviewable.io/reviews/starkware-libs/stwo/711#-O2tBMhbABCKbI2XwJZj:-O2tBMhbABCKbI2XwJZk:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/5e4f90b5395b7e720d37bebb8c12a5a6c74a5422/crates/prover/src/examples/poseidon/mod.rs#L399)):*
> ```XML
>                     .map(|s| s.data[vec_row]),
>             );
>             // 1 / denom1 - 1 / denom1 = (denom1 - denom0) / (denom0 * denom1).
> ```





_Suggestion:_
```XML
// (1 / denom1) - (1 / denom1) = (denom1 - denom0) / (denom0 * denom1).
```
___
*[`crates/prover/src/examples/poseidon/mod.rs` line 523 at r5](https://reviewable.io/reviews/starkware-libs/stwo/711#-O2tBaxJ4GbZmkzYefEB:-O2tBaxJ4GbZmkzYefEC:b-urtdh2) ([raw file](https://github.com/starkware-libs/stwo/blob/5e4f90b5395b7e720d37bebb8c12a5a6c74a5422/crates/prover/src/examples/poseidon/mod.rs#L523)):*
> ```XML
> }
> 
> pub fn prove_poseidon(log_n_instances: u32) -> (PoseidonAir, StarkProof) {
> ```

Should this be in the same PR?

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/711)* status: 3 of 8 files reviewed, 2 unresolved discussions (waiting on @alonh5)

___
*[`crates/prover/src/examples/poseidon/mod.rs` line 523 at r5](https://reviewable.io/reviews/starkware-libs/stwo/711#-O2tBaxJ4GbZmkzYefEB:-O2tIITH8G2oNiJ27K3H:bftl7gj) ([raw file](https://github.com/starkware-libs/stwo/blob/613e32c9ed59abe3a51a24b885b512482b0c395e/crates/prover/src/examples/poseidon/mod.rs#L523)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Should this be in the same PR?
</blockquote></details>

This is an example and a test for the use of logup.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 6 files at r1, 3 of 4 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/711#-:-O2tXuBw18rmzzy4oXCf:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/prover/src/core/fields/secure_column.rs` line 48 at r7](https://reviewable.io/reviews/starkware-libs/stwo/711#-O2tXGvl3NnzMA80G367:-O2tXGvl3NnzMA80G368:byyvhbt) ([raw file](https://github.com/starkware-libs/stwo/blob/216cbf5b08e478812ab4513f3498ae312b216db5/crates/prover/src/core/fields/secure_column.rs#L48)):*
> ```XML
>     pub fn set(&mut self, index: usize, value: SecureField) {
>         let values = value.to_m31_array();
>         #[allow(clippy::needless_range_loop)]
> ```

Unrelated but we should allow this across all files.



_Code quote:_
```XML
#[allow(clippy::needless_range_loop)]
```

**Pull request merged**
