### PR TITLE
WideFib test with AVX Backend

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/492)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/492?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#492** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/492?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#491** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/491?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#490** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/490?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#489** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/489?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#488** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/488?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#487** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/487?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#486** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/486?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#484** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/484?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#483** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/483?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#482** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/482?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#481** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/481?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#480** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/480?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#479** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/479?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#478** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/478?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#463** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/463?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#477** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/477?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#476** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/476?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/492)* status: 1 of 13 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`src/core/air/accumulation.rs` line 169 at r2](https://reviewable.io/reviews/starkware-libs/stwo/492#-NuYoFBH1yLGzN8sPxEj:-NuYoFBID_qBfhsaBQuB:b7epfl0) ([raw file](https://github.com/starkware-libs/stwo/blob/28f76850ac8d66cdef8195af78db45db84a7d8fc/src/core/air/accumulation.rs#L169)):*
> ```XML
> pub struct ColumnAccumulator<'a, B: Backend> {
>     pub random_coeff_pow: SecureField,
>     pub col: &'a mut SecureColumn<B>,
> ```

I changed this code. you probably have some conflicts :(



_Code quote:_
```XML
pub struct ColumnAccumulator<'a, B: Backend> {
    pub random_coeff_pow: SecureField,
    pub col: &'a mut SecureColumn<B>,
```

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/492)* status: 3 of 13 files reviewed, 6 unresolved discussions (waiting on @spapinistarkware)

___
*[`src/core/backend/avx512/blake2s.rs` line 28 at r2](https://reviewable.io/reviews/starkware-libs/stwo/492#-NuYortJ5s3fGd9XEbi5:-NuYortJ5s3fGd9XEbi6:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/28f76850ac8d66cdef8195af78db45db84a7d8fc/src/core/backend/avx512/blake2s.rs#L28)):*
> ```XML
>     ) -> Vec<Blake2sHash> {
>         // Pad prev_layer if too small.
>         if log_size < 4 {
> ```





_Suggestion:_
```XML
VECS_LOG_SIZE
```
___
*[`src/examples/wide_fibonacci/avx.rs` line 95 at r2](https://reviewable.io/reviews/starkware-libs/stwo/492#-NuYpuIREKHaXRfZXQhh:-NuYpuIREKHaXRfZXQhi:b-k0ttww) ([raw file](https://github.com/starkware-libs/stwo/blob/28f76850ac8d66cdef8195af78db45db84a7d8fc/src/examples/wide_fibonacci/avx.rs#L95)):*
> ```XML
>             let mut b = trace_eval[1].data[vec_row];
>             #[allow(clippy::needless_range_loop)]
>             for i in 0..(N_COLS - 2) {
> ```

Can you add the boundary constraint?



_Code quote:_
```XML
            #[allow(clippy::needless_range_loop)]
            for i in 0..(N_COLS - 2) {
```
___
*[`src/examples/wide_fibonacci/avx.rs` line 104 at r2](https://reviewable.io/reviews/starkware-libs/stwo/492#-NuYr66073mtR1qBdRyk:-NuYr66073mtR1qBdRyl:b-m3euac) ([raw file](https://github.com/starkware-libs/stwo/blob/28f76850ac8d66cdef8195af78db45db84a7d8fc/src/examples/wide_fibonacci/avx.rs#L104)):*
> ```XML
> 
>             // Denominator.
>             // TODO(spapini): Optimized this, for the small number of columns case.
> ```

Is this the coset_vanishing function?
Don't we already have one?



_Suggestion:_
```XML
// TODO(spapini): Move to PolyOps? and optimized for the small number of columns case.
```
___
*[`src/examples/wide_fibonacci/avx.rs` line 118 at r2](https://reviewable.io/reviews/starkware-libs/stwo/492#-NuYr4uw9MTPJzwGAzAG:-NuYr4uw9MTPJzwGAzAH:bgsqygf) ([raw file](https://github.com/starkware-libs/stwo/blob/28f76850ac8d66cdef8195af78db45db84a7d8fc/src/examples/wide_fibonacci/avx.rs#L118)):*
> ```XML
>             accum.col.set_packed(
>                 vec_row,
>                 accum.col.packed_at(vec_row) * PackedQM31::broadcast(accum.random_coeff_pow)
> ```

Where the denomenator is used?
___
*[`src/examples/wide_fibonacci/avx.rs` line 158 at r2](https://reviewable.io/reviews/starkware-libs/stwo/492#-NuYrvq-CuTuW80opqDp:-NuYrvq-CuTuW80opqDq:brrlwa8) ([raw file](https://github.com/starkware-libs/stwo/blob/28f76850ac8d66cdef8195af78db45db84a7d8fc/src/examples/wide_fibonacci/avx.rs#L158)):*
> ```XML
>     #[test]
>     fn test_avx_wide_fib_prove() {
>         // TODO(spapini): Increase to 20, to get 1GB of trace.
> ```

You can do these now, no?



_Code quote:_
```XML
 // TODO(spapini): Increase to 20, to get 1GB of trace.
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/492)* status: 1 of 13 files reviewed, 5 unresolved discussions (waiting on @shaharsamocha7)

___
*[`src/core/air/accumulation.rs` line 169 at r2](https://reviewable.io/reviews/starkware-libs/stwo/492#-NuYoFBH1yLGzN8sPxEj:-NuYzbHY37dXY80PXl3B:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/28f76850ac8d66cdef8195af78db45db84a7d8fc/src/core/air/accumulation.rs#L169)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I changed this code. you probably have some conflicts :(
</blockquote></details>

Done.
___
*[`src/examples/wide_fibonacci/avx.rs` line 95 at r2](https://reviewable.io/reviews/starkware-libs/stwo/492#-NuYpuIREKHaXRfZXQhh:-NuYxCQhENHDjxZNHX-l:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/28f76850ac8d66cdef8195af78db45db84a7d8fc/src/examples/wide_fibonacci/avx.rs#L95)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can you add the boundary constraint?
</blockquote></details>

Done.
___
*[`src/examples/wide_fibonacci/avx.rs` line 104 at r2](https://reviewable.io/reviews/starkware-libs/stwo/492#-NuYr66073mtR1qBdRyk:-NuYxNorCliIiHHDejn9:b-kpjata) ([raw file](https://github.com/starkware-libs/stwo/blob/28f76850ac8d66cdef8195af78db45db84a7d8fc/src/examples/wide_fibonacci/avx.rs#L104)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Is this the coset_vanishing function?
Don't we already have one?
</blockquote></details>

Sorry, leftovers.
___
*[`src/examples/wide_fibonacci/avx.rs` line 118 at r2](https://reviewable.io/reviews/starkware-libs/stwo/492#-NuYr4uw9MTPJzwGAzAG:-NuYzRop3V058f_p8NBJ:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/28f76850ac8d66cdef8195af78db45db84a7d8fc/src/examples/wide_fibonacci/avx.rs#L118)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Where the denomenator is used?
</blockquote></details>

Done.
___
*[`src/examples/wide_fibonacci/avx.rs` line 158 at r2](https://reviewable.io/reviews/starkware-libs/stwo/492#-NuYrvq-CuTuW80opqDp:-NuYzTGx9MqzczOOZYOM:b-3uitsv) ([raw file](https://github.com/starkware-libs/stwo/blob/28f76850ac8d66cdef8195af78db45db84a7d8fc/src/examples/wide_fibonacci/avx.rs#L158)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

You can do these now, no?
</blockquote></details>

When I test with AVX flags not on release, it's slow. I use it for my tests, so I'd rather only do this when I benchmark.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 13 files at r2, 7 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/492)* status: 10 of 13 files reviewed, 4 unresolved discussions (waiting on @spapinistarkware)

___
*[`src/core/air/accumulation.rs` line 65 at r3](https://reviewable.io/reviews/starkware-libs/stwo/492#-NuZ1zOe6Ryqtc9Yz5lO:-NuZ1zOf5ovRjbtHwhZH:b-vgxpi) ([raw file](https://github.com/starkware-libs/stwo/blob/bc6f0e444fc9315fc9654c6dbe4e2bda96ab63ab/src/core/air/accumulation.rs#L65)):*
> ```XML
>         Self {
>             random_coeff_powers: generate_secure_powers(random_coeff, total_columns),
>             sub_accumulations: (0..(max_log_size + 1)).map(|_| None).collect(),
> ```

For efficiency?



_Code quote:_
```XML
(0..(max_log_size + 1)).map(|_| None).collect(),
```
___
*[`src/examples/wide_fibonacci/constraint_eval.rs` line 436 at r3](https://reviewable.io/reviews/starkware-libs/stwo/492#-NuZ1P9_CO_NGCUKqYNy:-NuZ1P9_CO_NGCUKqYNz:b-39trco) ([raw file](https://github.com/starkware-libs/stwo/blob/bc6f0e444fc9315fc9654c6dbe4e2bda96ab63ab/src/examples/wide_fibonacci/constraint_eval.rs#L436)):*
> ```XML
>         evaluation_accumulator: &mut PointEvaluationAccumulator,
>     ) {
>         let constraint_zero_domain = Coset::subgroup(self.log_size);
> ```

Why it is not a CanonicCoset?



_Code quote:_
```XML
Coset::subgroup(self.log_size);
```
___
*[`src/examples/wide_fibonacci/mod.rs` line 50 at r3](https://reviewable.io/reviews/starkware-libs/stwo/492#-NuZ1hl_4ktJDKGG0iKG:-NuZ1hl_4ktJDKGG0iKH:b9sadzg) ([raw file](https://github.com/starkware-libs/stwo/blob/bc6f0e444fc9315fc9654c6dbe4e2bda96ab63ab/src/examples/wide_fibonacci/mod.rs#L50)):*
> ```XML
>             QM31::from_u32_unchecked(1, 2, 3, 4),
>             wide_fib.log_size + 1,
>             Component::<CPUBackend>::n_constraints(&wide_fib),
> ```

A question:
Why this change is good?



_Code quote:_
```XML
Component::<CPUBackend>::n_constraints(&wide_fib)
```
___
*[`src/examples/wide_fibonacci/avx.rs` line 158 at r2](https://reviewable.io/reviews/starkware-libs/stwo/492#-NuYrvq-CuTuW80opqDp:-NuZ10ub51B9b7i-gQ3v:bn9knjm) ([raw file](https://github.com/starkware-libs/stwo/blob/28f76850ac8d66cdef8195af78db45db84a7d8fc/src/examples/wide_fibonacci/avx.rs#L158)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

When I test with AVX flags not on release, it's slow. I use it for my tests, so I'd rather only do this when I benchmark.
</blockquote></details>

so this TODO is to add benchmark? can you change that?

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/492)* status: 8 of 13 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`src/core/air/accumulation.rs` line 65 at r3](https://reviewable.io/reviews/starkware-libs/stwo/492#-NuZ1zOe6Ryqtc9Yz5lO:-NuZ7sEGCWCV6ZIFqNfv:bts1aau) ([raw file](https://github.com/starkware-libs/stwo/blob/bc6f0e444fc9315fc9654c6dbe4e2bda96ab63ab/src/core/air/accumulation.rs#L65)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Because small sizes are not supported in AVX backend.
</blockquote></details>

I don't see the connection.
It seems that you don't initialize unused accumulations, no?
___
*[`src/examples/wide_fibonacci/constraint_eval.rs` line 436 at r3](https://reviewable.io/reviews/starkware-libs/stwo/492#-NuZ1P9_CO_NGCUKqYNy:-NuZ7hRg6J_TuqVs-S0d:b-dsn57e) ([raw file](https://github.com/starkware-libs/stwo/blob/bc6f0e444fc9315fc9654c6dbe4e2bda96ab63ab/src/examples/wide_fibonacci/constraint_eval.rs#L436)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Good point. I wonder why the test didnt catch it. We should inverstigate this.
</blockquote></details>

It works for both CanonicCoset and subgroup?
That's really strange.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/492)* status: 8 of 13 files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7)

___
*[`src/core/air/accumulation.rs` line 65 at r3](https://reviewable.io/reviews/starkware-libs/stwo/492#-NuZ1zOe6Ryqtc9Yz5lO:-NuZHV-P9M1RyJqQfeIv:b-z887) ([raw file](https://github.com/starkware-libs/stwo/blob/bc6f0e444fc9315fc9654c6dbe4e2bda96ab63ab/src/core/air/accumulation.rs#L65)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I don't see the connection.
It seems that you don't initialize unused accumulations, no?
</blockquote></details>

The issue was that I interpolate each of these sub accumulations. And I am not allowed to do it on small ones right now

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 10 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/492)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`src/examples/wide_fibonacci/constraint_eval.rs` line 436 at r3](https://reviewable.io/reviews/starkware-libs/stwo/492#-NuZ1P9_CO_NGCUKqYNy:-NuZWf5g1NpQY-WIwHuq:b-cp7lld) ([raw file](https://github.com/starkware-libs/stwo/blob/bc6f0e444fc9315fc9654c6dbe4e2bda96ab63ab/src/examples/wide_fibonacci/constraint_eval.rs#L436)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I agree. We should inverstigate this.
</blockquote></details>

Solution here is now clear, it worked since the poly was constant?
___
*[`src/examples/wide_fibonacci/avx.rs` line 161 at r4](https://reviewable.io/reviews/starkware-libs/stwo/492#-NuZWxYYDhY9jg7fl89J:-NuZWxYYDhY9jg7fl89K:b-8o8yga) ([raw file](https://github.com/starkware-libs/stwo/blob/22acef470476afdab922ab6a74863783ab2a802d/src/examples/wide_fibonacci/avx.rs#L161)):*
> ```XML
> 
>     #[test]
>     fn test_avx_wide_fib_prove() {
> ```

Need to fix this test before



_Code quote:_
```XML
fn test_avx_wide_fib_prove()
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/492)* status: all files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`src/examples/wide_fibonacci/constraint_eval.rs` line 436 at r3](https://reviewable.io/reviews/starkware-libs/stwo/492#-NuZ1P9_CO_NGCUKqYNy:-NucUmW167F-oUqWRLP3:b2nhswv) ([raw file](https://github.com/starkware-libs/stwo/blob/bc6f0e444fc9315fc9654c6dbe4e2bda96ab63ab/src/examples/wide_fibonacci/constraint_eval.rs#L436)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Solution here is now clear, it worked since the poly was constant?
</blockquote></details>

Yep
___
*[`src/examples/wide_fibonacci/avx.rs` line 161 at r4](https://reviewable.io/reviews/starkware-libs/stwo/492#-NuZWxYYDhY9jg7fl89J:-NucUoHy0CfyhCBnZYPv:b8itayk) ([raw file](https://github.com/starkware-libs/stwo/blob/22acef470476afdab922ab6a74863783ab2a802d/src/examples/wide_fibonacci/avx.rs#L161)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Need to fix this test before
</blockquote></details>

Waiting on you now (mask points change)

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/492#-:-NudBwer4m8U-GeWu5fo:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
