### PR TITLE
simple merkle benchmark

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/527)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/527?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#528** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/528?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#527** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/527?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#526** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/526?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#525** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/525?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#518** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/518?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/527)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`Cargo.toml` line 16 at r2](https://reviewable.io/reviews/starkware-libs/stwo/527#-Ntq-F-s7bjXCaD4f7yI:-Ntq-F-t56PvUM-rrQLX:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/1a950fc98b2093995ac6d86f49903e954c816f0f/Cargo.toml#L16)):*
> ```TOML
> merging-iterator = "1.3.0"
> bytemuck = { version = "1.14.3", features = ["derive"] }
> blake2 = "0.10.6"
> ```





_Suggestion:_
```TOML
[dependencies]
blake2 = "0.10.6"
blake3 = "1.5.0"
hex = "0.4.3"
itertools = "0.12.0"
num-traits = "0.2.17"
thiserror = "1.0.56"
merging-iterator = "1.3.0"
bytemuck = { version = "1.14.3", features = ["derive"] }
```
___
*[`Cargo.toml` line 60 at r2](https://reviewable.io/reviews/starkware-libs/stwo/527#-Ntq-Kb518ahxU6Ookiz:-Ntq-Kb518ahxU6Ookj-:b-9yzzyc) ([raw file](https://github.com/starkware-libs/stwo/blob/1a950fc98b2093995ac6d86f49903e954c816f0f/Cargo.toml#L60)):*
> ```TOML
> 
> [[bench]]
> name = "merkle"
> ```

What is the difference?
Rename or put them together



_Code quote:_
```TOML
[[bench]]
name = "merkle_bench"
harness = false

[[bench]]
name = "merkle"
```
___
*[`benches/merkle_bench.rs` line 97 at r2](https://reviewable.io/reviews/starkware-libs/stwo/527#-Ntq-loa70wlf8RBV5CQ:-Ntq-loa70wlf8RBV5CR:b2bcepm) ([raw file](https://github.com/starkware-libs/stwo/blob/16ee392660bea640e30d05d706f7e34a276480d7/benches/merkle_bench.rs#L97)):*
> ```XML
>         )
>     });
> }
> ```

Why did you remove this?
Do we need any benches from this file?



_Code quote:_
```XML
fn single_blake2s_hash_benchmark(c: &mut Criterion) {
    let input = [0u8; 1];
    c.bench_function("Single blake2s hash", |b| {
        b.iter_batched(
            || -> Blake2s256 { Blake2s256::new() },
            |mut h| {
                h.update(&input[..]);
                h.finalize()
            },
            BatchSize::SmallInput,
        )
    });
}
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/527)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7)

___
*[`Cargo.toml` line 16 at r2](https://reviewable.io/reviews/starkware-libs/stwo/527#-Ntq-F-s7bjXCaD4f7yI:-NttT4r61B0feIm1aF4i:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/01bea4e49be247a8be18325ca3a0484c503570d4/Cargo.toml#L16)):*
> ```TOML
> merging-iterator = "1.3.0"
> bytemuck = { version = "1.14.3", features = ["derive"] }
> blake2 = "0.10.6"
> ```

Done.
___
*[`Cargo.toml` line 60 at r2](https://reviewable.io/reviews/starkware-libs/stwo/527#-Ntq-Kb518ahxU6Ookiz:-NttT6F31fTPMYeP0HFO:b-8tsywm) ([raw file](https://github.com/starkware-libs/stwo/blob/01bea4e49be247a8be18325ca3a0484c503570d4/Cargo.toml#L60)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

What is the difference?
Rename or put them together
</blockquote></details>

merkle_bench will be removed soon
___
*[`benches/merkle_bench.rs` line 97 at r2](https://reviewable.io/reviews/starkware-libs/stwo/527#-Ntq-loa70wlf8RBV5CQ:-NttTRmg7cBnsMCNTJOR:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/67cf290f58571748ef418a826621dcae92e1d476/benches/merkle_bench.rs#L97)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why did you remove this?
Do we need any benches from this file?
</blockquote></details>

Done.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/527#-:-Ntu0Q4IARHGA-gzTQhY:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`benches/merkle_bench.rs` line 2 at r3](https://reviewable.io/reviews/starkware-libs/stwo/527#-Ntu0Kkj9A3Xr6zHRgs3:-Ntu0Kkj9A3Xr6zHRgs4:bv762cn) ([raw file](https://github.com/starkware-libs/stwo/blob/e5f2229259df6718f8d5dd92b5faf74fe9934dae/benches/merkle_bench.rs#L2)):*
> ```XML
> use blake2::{Blake2s256, Digest};
> // TODO(Ohad): write better benchmarks. Reduce the variance in sample size.
> ```

Revert change



_Suggestion:_
```XML
// TODO(Ohad): write better benchmarks. Reduce the variance in sample size.
use blake2::{Blake2s256, Digest};
```

**Comment by spapinistarkware** [comment]
### Merge activity

* **Apr 3, 2:30 AM EDT**: [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/527) rebased this pull request as part of a merge.

**Pull request merged**
