### PR TITLE
Revert logup without is_first

### PR DESCRIPTION
**Pull request by shaharsamocha7**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/818)

### CODE REVIEW

**Comment by shaharsamocha7** [comment]
* **#818** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/818?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @shaharsamocha7 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by andrewmilson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/818)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @Alon-Ti and @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/logup.rs` line 71 at r3](https://reviewable.io/reviews/starkware-libs/stwo/818#-O77NMh1-AaoKaW5lZsB:-O77NMh1-AaoKaW5lZsC:b-fo80j7) ([raw file](https://github.com/starkware-libs/stwo/blob/62727146b0e53ab6fa9e41072c11c4086da50fb0/crates/prover/src/constraint_framework/logup.rs#L71)):*
> ```XML
>         // Fix `prev_row_cumsum` by subtracting `claimed_sum` if this is the first row.
>         let fixed_prev_row_cumsum = prev_row_cumsum - self.is_first * self.claimed_sum;
>         let diff = cur_cumsum - fixed_prev_row_cumsum - self.prev_col_cumsum;
> ```

Isn't it more efficient how it was before?



_Code quote:_
```XML
        // Fix `prev_row_cumsum` by subtracting `claimed_sum` if this is the first row.
        let fixed_prev_row_cumsum = prev_row_cumsum - self.is_first * self.claimed_sum;
        let diff = cur_cumsum - fixed_prev_row_cumsum - self.prev_col_cumsum;
```

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/818)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @Alon-Ti and @andrewmilson)

___
*[`crates/prover/src/constraint_framework/logup.rs` line 71 at r3](https://reviewable.io/reviews/starkware-libs/stwo/818#-O77NMh1-AaoKaW5lZsB:-O7NwXys7LUySwxcXHrO:bz9pic) ([raw file](https://github.com/starkware-libs/stwo/blob/62727146b0e53ab6fa9e41072c11c4086da50fb0/crates/prover/src/constraint_framework/logup.rs#L71)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Isn't it more efficient how it was before?
</blockquote></details>

It was (by a bit), but I wanted to add the is_first column for the padding feature and wanted those to use the same mechanism

**Review by Alon-Ti — APPROVED** [review]
:lgtm:

> Reviewed 4 of 7 files at r1, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/818#-:-O7O0VqYBWGZayN7o7Ai:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @andrewmilson)

**Review by andrewmilson — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/818#-:-O7OAMZyEjP0DeMdMXDN:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Pull request merged**
