### PR TITLE
input registry

### PR DESCRIPTION
**Pull request by ohad-agadi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/670)

### CODE REVIEW

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/670)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ohad-starkware)

___
*[`crates/prover/src/trace_generation/mod.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/stwo/670#-O03oHXR2E3Y0mD69HQl:-O03oHXR2E3Y0mD69HQm:btu8ai0) ([raw file](https://github.com/starkware-libs/stwo/blob/7b82dddf6cd29b7494d324dbc1b5029912e39daf/crates/prover/src/trace_generation/mod.rs#L21)):*
> ```XML
> // Generates the trace given a list of inputs collects inputs for subcomponents.
> pub trait TraceGenerator<B: Backend> {
>     type ComponentInputs;
> ```

The component inputs is templated by the backend.
I'm not sure where it fails for SIMD, can't add_input always assume that it get non_packed elements?



_Code quote:_
```XML
type ComponentInputs;
```
___
*[`crates/prover/src/trace_generation/registry.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/stwo/670#-O03o7lL5jr54Fe1-vpd:-O03o7lMB6uw9bimgHJG:b-k1rgsi) ([raw file](https://github.com/starkware-libs/stwo/blob/7b82dddf6cd29b7494d324dbc1b5029912e39daf/crates/prover/src/trace_generation/registry.rs#L12)):*
> ```XML
> }
> 
> impl ComponentRegistry {
> ```

Do we need all these functions in the component registry?



_Code quote:_
```XML
impl ComponentRegistry {
```

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/670)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @ohad-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo/670#-O095UeC6EDecRlhEGt_:-O095UeC6EDecRlhEGta:b-oag8ub) (no related file):*
Can you rebase? AlonH also changes the TraceGenerator trait to ComponentTraceGenerator.
How come all this code looks new - we already merged parts of it

___

**Review by ohad-agadi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/670)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7)

*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo/670#-O095UeC6EDecRlhEGt_:-O096y_t2XLzBwO0hFwF:b-896fix) (no related file):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can you rebase? AlonH also changes the TraceGenerator trait to ComponentTraceGenerator.
How come all this code looks new - we already merged parts of it
</blockquote></details>

Done.

___

**Review by ohad-agadi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/670)* status: 0 of 29 files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/prover/src/trace_generation/mod.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/stwo/670#-O03oHXR2E3Y0mD69HQl:-O0975yuE9_Dia9Ae4SM:b-6dquwn) ([raw file](https://github.com/starkware-libs/stwo/blob/7b82dddf6cd29b7494d324dbc1b5029912e39daf/crates/prover/src/trace_generation/mod.rs#L21)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

The component inputs is templated by the backend.
I'm not sure where it fails for SIMD, can't add_input always assume that it get non_packed elements?
</blockquote></details>

add_input is now generic and accepts any backend type as long as its the same type every time.
___
*[`crates/prover/src/trace_generation/registry.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/stwo/670#-O03o7lL5jr54Fe1-vpd:-O097Fp3B4SLdz83Rn0B:b6dquuz) ([raw file](https://github.com/starkware-libs/stwo/blob/7b82dddf6cd29b7494d324dbc1b5029912e39daf/crates/prover/src/trace_generation/registry.rs#L12)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Do we need all these functions in the component registry?
</blockquote></details>

still not sure about register_component_with_input

**Pull request closed without merging**
