### PR TITLE
Fix CPU backend evaluation and interpolation bugs

### PR DESCRIPTION
**Pull request by andrewmilson**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/645)

### CODE REVIEW

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/645)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @andrewmilson)

___
*[`crates/prover/src/core/backend/cpu/circle.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/stwo/645#-NzvskJA2SC1L3x6HHOd:-NzvskJA2SC1L3x6HHOe:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/ed0c8c38ff136a79cd80996549f555cfba9eb106/crates/prover/src/core/backend/cpu/circle.rs#L49)):*
> ```XML
>         if eval.domain.log_size() == 1 {
>             let y = eval.domain.half_coset.initial.y;
>             let n = BaseField::from(2);
> ```





_Suggestion:_
```XML
let coset_size = BaseField::from(2);
```
___
*[`crates/prover/src/core/backend/cpu/circle.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/stwo/645#-Nzvse-rDV7b8WkM1N6d:-Nzvse-s4umcdwDIPCw7:boqbfad) ([raw file](https://github.com/starkware-libs/stwo/blob/ed0c8c38ff136a79cd80996549f555cfba9eb106/crates/prover/src/core/backend/cpu/circle.rs#L58)):*
> ```XML
>         }
> 
>         // `circle_twiddles_from_line_twiddles` only works for domains with size >4.
> ```

Can you move this comment to the function doc?



_Code quote:_
```XML
// `circle_twiddles_from_line_twiddles` only works for domains with size >4.
```

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/645)* status: all files reviewed, 3 unresolved discussions (waiting on @andrewmilson)

___
*[`crates/prover/src/core/backend/cpu/circle.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/stwo/645#-Nzvse-rDV7b8WkM1N6d:-O1I-DJ9-U_sG6wrb47p:bhh4bl1) ([raw file](https://github.com/starkware-libs/stwo/blob/ed0c8c38ff136a79cd80996549f555cfba9eb106/crates/prover/src/core/backend/cpu/circle.rs#L58)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can you move this comment to the function doc?
</blockquote></details>

Maybe we also want to document the upper bound? (29 I think)
___
*[`crates/prover/src/core/backend/cpu/circle.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/stwo/645#-O1I1I6sDyg2bbSKOExS:-O1I1I6sDyg2bbSKOExT:bpqu29g) ([raw file](https://github.com/starkware-libs/stwo/blob/b3f9285595cda915a50f4871e32026743010d382/crates/prover/src/core/backend/cpu/circle.rs#L74)):*
> ```XML
> 
>     fn eval_at_point(poly: &CirclePoly<Self>, point: CirclePoint<SecureField>) -> SecureField {
>         // TODO(Andrew): Allocation here expensive for small polynomials.
> ```

Not sure I understand why.

Also, why not alternating between push front/back instead of the reversing?



_Code quote:_
```XML
// TODO(Andrew): Allocation here expensive for small polynomials.
```

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/645)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/prover/src/core/backend/cpu/circle.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/stwo/645#-Nzvse-rDV7b8WkM1N6d:-O1KpVQv9EoSntkrTUlX:b-o2hazf) ([raw file](https://github.com/starkware-libs/stwo/blob/ed0c8c38ff136a79cd80996549f555cfba9eb106/crates/prover/src/core/backend/cpu/circle.rs#L58)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Maybe we also want to document the upper bound? (29 I think)
</blockquote></details>

Moved the comment.
I left out mentioning the upper bound since it's documented in terms of the domain not number of line twiddles.
___
*[`crates/prover/src/core/backend/cpu/circle.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/stwo/645#-O1I1I6sDyg2bbSKOExS:-O1Kq3R_AFkqLmbxCC3G:b-9dezhe) ([raw file](https://github.com/starkware-libs/stwo/blob/b3f9285595cda915a50f4871e32026743010d382/crates/prover/src/core/backend/cpu/circle.rs#L74)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Not sure I understand why.

Also, why not alternating between push front/back instead of the reversing?
</blockquote></details>

Removed the comment. Was outdated. I think at the time I was using it on very small slices of coefficients for FRI.

The twiddles map to the index bits in a way so it's just reversed as opposed to alternating.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/645#-:-O1L1lgK0jr8g_DP5Uk6:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @andrewmilson)

___
*[`crates/prover/src/core/backend/cpu/circle.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/stwo/645#-NzvskJA2SC1L3x6HHOd:-O1L1hoC3qiv7yZS0jPf:b4yswvg) ([raw file](https://github.com/starkware-libs/stwo/blob/ed0c8c38ff136a79cd80996549f555cfba9eb106/crates/prover/src/core/backend/cpu/circle.rs#L49)):*
> ```XML
>         if eval.domain.log_size() == 1 {
>             let y = eval.domain.half_coset.initial.y;
>             let n = BaseField::from(2);
> ```

Consider to make this change, non-blocking

**Pull request merged**
