### PR TITLE
Add safe simplify for expressions that compares random assignments before and after.

### PR DESCRIPTION
**Pull request by Alon-Ti**
before and after.

### CODE REVIEW

**Comment by Alon-Ti** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/918?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#918** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/918?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/918?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#908** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/908?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#904** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/904?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#903** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/903?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#901** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/901?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#894** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/894?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#893** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/893?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#892** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/892?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#889** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/889?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#888** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/888?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#887** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/887?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#879** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/879?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#883](https://github.com/starkware-libs/stwo/pull/883) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/883?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#876** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/876?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#875** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/875?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by Alon-Ti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/918)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/expr.rs` line 181 at r1](https://reviewable.io/reviews/starkware-libs/stwo/918#-OD6__J81U2rRJ1Rk47Q:-OD6ctpB9jcyY6_CbZzo:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/a198090495b6c9f10e805e3a6a67b3824edf3338/crates/prover/src/constraint_framework/expr.rs#L181)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

rename to unsafe
and document that this shouldn't be used and refer to the simplify function
</blockquote></details>

Done.
___
*[`crates/prover/src/constraint_framework/expr.rs` line 248 at r1](https://reviewable.io/reviews/starkware-libs/stwo/918#-OD6_zcH2Almbe-WW3a0:-OD6dNt4165Sfu_81AdF:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/a198090495b6c9f10e805e3a6a67b3824edf3338/crates/prover/src/constraint_framework/expr.rs#L248)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Assert that assignment.2 is empty?
</blockquote></details>

Done.
___
*[`crates/prover/src/constraint_framework/expr.rs` line 381 at r1](https://reviewable.io/reviews/starkware-libs/stwo/918#-OD6aIcv1Ww9rKzRRgCG:-OD6dr0D7W0EpVpV4Ynr:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/a198090495b6c9f10e805e3a6a67b3824edf3338/crates/prover/src/constraint_framework/expr.rs#L381)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Document
</blockquote></details>

Done.
___
*[`crates/prover/src/constraint_framework/expr.rs` line 196 at r2](https://reviewable.io/reviews/starkware-libs/stwo/918#-OD6aT3n0QE4QJDpIO26:-OD6cwRH-Xw2R4OpaLC8:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/f84268de9352e479b1888c2d29424885782fba39/crates/prover/src/constraint_framework/expr.rs#L196)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Document
And put note that
</blockquote></details>

Done.
___
*[`crates/prover/src/constraint_framework/expr.rs` line 391 at r2](https://reviewable.io/reviews/starkware-libs/stwo/918#-OD6ahA87YdumjwpWhvp:-OD6duy01Vp67uIWA-oK:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/f84268de9352e479b1888c2d29424885782fba39/crates/prover/src/constraint_framework/expr.rs#L391)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

move above ExprVariables
</blockquote></details>

Done.
___
*[`crates/prover/src/constraint_framework/expr.rs` line 418 at r2](https://reviewable.io/reviews/starkware-libs/stwo/918#-OD6amOm4iQ0S81hypF9:-OD6eJYQCO8LOR09frig:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/f84268de9352e479b1888c2d29424885782fba39/crates/prover/src/constraint_framework/expr.rs#L418)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Document
and maybe rename to random_assignment? WDYT?
</blockquote></details>

Done.

**Review by shaharsamocha7 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/918)* status: all files reviewed, 1 unresolved discussion (waiting on @Alon-Ti)

___
*[`crates/prover/src/constraint_framework/expr.rs` line 418 at r2](https://reviewable.io/reviews/starkware-libs/stwo/918#-OD6amOm4iQ0S81hypF9:-ODAg34h6CgEj-swwjDm:burgx8j) ([raw file](https://github.com/starkware-libs/stwo/blob/f84268de9352e479b1888c2d29424885782fba39/crates/prover/src/constraint_framework/expr.rs#L418)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Also write that this function uses only for tests.
Could we define it with cfg(tests) (not sure If I already suggested this)
___
*[`crates/prover/src/constraint_framework/expr.rs` line 1043 at r3](https://reviewable.io/reviews/starkware-libs/stwo/918#-ODAfqzJ8SB7F3cL5mVZ:-ODAfqzJ8SB7F3cL5mV_:b8roi1c) ([raw file](https://github.com/starkware-libs/stwo/blob/484a7d882db0ff050866fef6d228a2c63c524cca/crates/prover/src/constraint_framework/expr.rs#L1043)):*
> ```XML
>         let full_eval = expr.eval_expr::<AssertEvaluator<'_>, _, _, _>(&columns, &vars, &ext_vars);
>         let simplified_eval = expr
>             .unchecked_simplify()
> ```

why not just call simplify here?



_Code quote:_
```XML
unchecked_simplify
```

**Review by Alon-Ti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/918)* status: all files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/expr.rs` line 418 at r2](https://reviewable.io/reviews/starkware-libs/stwo/918#-OD6amOm4iQ0S81hypF9:-ODAgXLr8vVHg1RZZAGD:b-m17g2d) ([raw file](https://github.com/starkware-libs/stwo/blob/f84268de9352e479b1888c2d29424885782fba39/crates/prover/src/constraint_framework/expr.rs#L418)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Also write that this function uses only for tests.
Could we define it with cfg(tests) (not sure If I already suggested this)
</blockquote></details>

It's not just for tests though, it should run every time an expression is simplified, including (especially) real use cases.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/918#-:-ODAkHVr7JsN4SWQXQim:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @Alon-Ti)

**Comment by Alon-Ti** [comment]
### Merge activity

* **Dec 3, 4:02 AM EST**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/918).

**Pull request merged**
