### PR TITLE
zip_eq component traces.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/752)

### CODE REVIEW

**Comment by alonh5** [comment]
* **#752** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/752?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ohad-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/752)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @spapinistarkware)

___
*[`crates/prover/src/examples/poseidon/mod.rs` line 111 at r2](https://reviewable.io/reviews/starkware-libs/stwo/752#-O2PoF52DNFnpvBmefFY:-O2PoF52DNFnpvBmefFZ:b92p9kt) ([raw file](https://github.com/starkware-libs/stwo/blob/990381c3b7160f5757cf0535189633fdbfe3befc/crates/prover/src/examples/poseidon/mod.rs#L111)):*
> ```XML
>         TreeVec::new(vec![
>             vec![self.log_column_size(); N_COLUMNS],
>             vec![self.log_column_size()],
> ```

Poseidons don't have lookups
will this be necessary in every component then?

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/752#-:-O2TdnqE0bhrNX7-lwh_:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/752)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

___
*[`crates/prover/src/examples/poseidon/mod.rs` line 111 at r2](https://reviewable.io/reviews/starkware-libs/stwo/752#-O2PoF52DNFnpvBmefFY:-O2TdYbOB8ayDsUrhE26:b-endrho) ([raw file](https://github.com/starkware-libs/stwo/blob/990381c3b7160f5757cf0535189633fdbfe3befc/crates/prover/src/examples/poseidon/mod.rs#L111)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

nevermind, poseidon is a callee so it does need that.
</blockquote></details>

The extra column here is actually a constant column.

**Pull request merged**
