### PR TITLE
Denom is not zero

### PR DESCRIPTION
**Pull request by shaharsamocha7**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/793)

### CODE REVIEW

**Comment by shaharsamocha7** [comment]
* **#793** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/793?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @shaharsamocha7 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/793)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo/793#-O4jBGfkAnhwPTjnN_E2:-O4jBGfkAnhwPTjnN_E3:bn4nz3) (no related file):*
I encountered this when using dummy lookup elements for assert_constraints test.
Should we merge this?

___

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/793)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7)

*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo/793#-O4jBGfkAnhwPTjnN_E2:-O4jH9Bo5j5oPn57q2q2:bgzntu9) (no related file):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I encountered this when using dummy lookup elements for assert_constraints test.
Should we merge this?
</blockquote></details>

With debug assert, sure

___
___
*[`crates/prover/src/constraint_framework/logup.rs` line 248 at r2](https://reviewable.io/reviews/starkware-libs/stwo/793#-O4jH5ck581450b0R00L:-O4jH5ck581450b0R00M:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/0aea868eb182a32a8561860a882b223ed59993ae/crates/prover/src/constraint_framework/logup.rs#L248)):*
> ```XML
>         denom: PackedSecureField,
>     ) {
>         assert!(
> ```





_Suggestion:_
```XML
debug_assert!
```

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/793#-:-O4ne5ZL2eYdlTmSev4t:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Pull request merged**
