### PR TITLE
Implement GkrOps for CPU backend

### PR DESCRIPTION
**Pull request by andrewmilson**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/621)

### CODE REVIEW

**Comment by andrewmilson** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/621?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#621** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/621?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#581** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/581?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#620](https://github.com/starkware-libs/stwo/pull/620) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/620?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#617** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/617?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#616** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/616?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#615** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/615?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#614** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/614?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#613** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/613?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#612** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/612?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#611** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/611?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#610** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/610?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#609** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/609?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#608** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/608?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#607** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/607?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#606** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/606?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#605** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/605?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#604** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/604?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#603** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/603?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#599** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/599?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#596** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/596?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#602** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/602?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#595** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/595?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#601** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/601?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#594** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/594?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#600** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/600?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#593** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/593?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#592** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/592?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#591** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/591?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @andrewmilson and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/621#-:-Ny0SoSq3w1QuZUayKtc:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @andrewmilson)

___
*[`crates/prover/src/core/backend/cpu/lookups/gkr.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/stwo/621#-Ny0SWf5-eqst6RtoVzS:-Ny0SWf5-eqst6RtoVzT:b-qsrcs5) ([raw file](https://github.com/starkware-libs/stwo/blob/6b46730e858f8f672ff7013b91273996ba66f155/crates/prover/src/core/backend/cpu/lookups/gkr.rs#L17)):*
> ```XML
> fn gen_eq_evals(y: &[SecureField], v: SecureField) -> Vec<SecureField> {
>     match y {
>         [] => vec![v],
> ```

I would prefer to allocate this with capacity.
consider implementing this iteratively instead, if it helps.



_Code quote:_
```XML
vec![v]
```

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/621)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @andrewmilson and @spapinistarkware)

___
*[`crates/prover/src/core/backend/cpu/lookups/gkr.rs` line 3 at r2](https://reviewable.io/reviews/starkware-libs/stwo/621#-O-GD5v_9EVe7Yb1_1fH:-O-GD5va19VLBWJ020Ho:b-i4obtv) ([raw file](https://github.com/starkware-libs/stwo/blob/5705279a864454c8d8e9309544f7dca9930102b4/crates/prover/src/core/backend/cpu/lookups/gkr.rs#L3)):*
> ```XML
> use crate::core::backend::CpuBackend;
> use crate::core::fields::qm31::SecureField;
> use crate::core::lookups::gkr::GkrOps;
> ```

Shouldn't it be gkr_prover? can you rebase?



_Code quote:_
```XML
use crate::core::lookups::gkr::GkrOps;
```
___
*[`crates/prover/src/core/backend/cpu/lookups/gkr.rs` line 48 at r2](https://reviewable.io/reviews/starkware-libs/stwo/621#-O-GC1iXBDGSgsFacERv:-O-GC1iXBDGSgsFacERw:b2zlfua) ([raw file](https://github.com/starkware-libs/stwo/blob/5705279a864454c8d8e9309544f7dca9930102b4/crates/prover/src/core/backend/cpu/lookups/gkr.rs#L48)):*
> ```XML
>         let y = [7, 3].map(|v| BaseField::from(v).into());
> 
>         let eq_evals = CpuBackend::gen_eq_evals(&y, one);
> ```

Consider to test it with v != one.



_Code quote:_
```XML
let eq_evals = CpuBackend::gen_eq_evals(&y, one);
```

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/621)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/core/backend/cpu/lookups/gkr.rs` line 3 at r2](https://reviewable.io/reviews/starkware-libs/stwo/621#-O-GD5v_9EVe7Yb1_1fH:-O-HEq5IC6P8fizQ2EQ7:b-munwrr) ([raw file](https://github.com/starkware-libs/stwo/blob/5705279a864454c8d8e9309544f7dca9930102b4/crates/prover/src/core/backend/cpu/lookups/gkr.rs#L3)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Shouldn't it be gkr_prover? can you rebase?
</blockquote></details>

Thanks, updated

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/621#-:-O-ppuft9RZb7_7yfgQ_:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @andrewmilson)

**Review by shaharsamocha7 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/621)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @andrewmilson)

**Pull request merged**
