### PR TITLE
Parallelize quotients accumulation.

### PR DESCRIPTION
**Pull request by Alon-Ti**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/754)

### CODE REVIEW

**Comment by Alon-Ti** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/754?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#754** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/754?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#751** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/751?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#750** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/750?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#749** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/749?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#748** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/748?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Alon-Ti and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Alon-Ti — COMMENTED** [review]
Quotient accumulation drops from 146ms to time.busy=23.6ms.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/754#-:-O2ZkmLA4UgDaJW2OZTM:bsydtnx)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @shaharsamocha7 and @spapinistarkware)

**Review by Alon-Ti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/754)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/examples/poseidon/mod.rs` line 535 at r1](https://reviewable.io/reviews/starkware-libs/stwo/754#-O2_6tGb5L6Z3-ptwyY4:-O2_6tGb5L6Z3-ptwyY5:bn7y88t) ([raw file](https://github.com/starkware-libs/stwo/blob/50c3e2d024be0220fa2a4820dcffd30ef7c8bf24/crates/prover/src/examples/poseidon/mod.rs#L535)):*
> ```XML
>         // Get from environment variable:
>         let log_n_instances = env::var("LOG_N_INSTANCES")
>             .unwrap_or_else(|_| "12".to_string())
> ```

This is an unfortunate consequence of the fact that the iteration currently demands full chunks, I will fix this in the next PR.

**Review by shaharsamocha7 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/754)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @Alon-Ti and @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/column.rs` line 294 at r1](https://reviewable.io/reviews/starkware-libs/stwo/754#-O2ccD45EJ03ISbZ00r6:-O2ccD45EJ03ISbZ00r7:b-ll3e4a) ([raw file](https://github.com/starkware-libs/stwo/blob/b9aa943c1acc484f97ce6e9c69afeabb3894e6c8/crates/prover/src/core/backend/simd/column.rs#L294)):*
> ```XML
>     ) -> impl Iterator<Item = (usize, SecureColumnByCoordsMutSlice<'_>)> {
>         assert_eq!(self.packed_len() % chunk_size, 0);
>         (0..).step_by(chunk_size).zip(self.chunks_mut(chunk_size))
> ```

Are those the same?



_Suggestion:_
```XML
(0..self.packed_len())
```

**Review by Alon-Ti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/754)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/column.rs` line 294 at r1](https://reviewable.io/reviews/starkware-libs/stwo/754#-O2ccD45EJ03ISbZ00r6:-O2ck-XKCiepq6zQdaxT:bdkw4rg) ([raw file](https://github.com/starkware-libs/stwo/blob/b9aa943c1acc484f97ce6e9c69afeabb3894e6c8/crates/prover/src/core/backend/simd/column.rs#L294)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Are those the same?
</blockquote></details>

I think so, `(0..)` is an infinite iterable, it'll stop when the `chunks_mut` stops because of the zip. I'd have preferred to do the same in the parallel code but rayon doesn't support unbounded ranges (plus I have to compute the bounds in the next PR to support partial chunks anyway).

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/754)* status: 1 of 3 files reviewed, 5 unresolved discussions (waiting on @Alon-Ti and @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/column.rs` line 294 at r1](https://reviewable.io/reviews/starkware-libs/stwo/754#-O2ccD45EJ03ISbZ00r6:-O2dR6G73s5ipNULNG2E:b-t4sx6r) ([raw file](https://github.com/starkware-libs/stwo/blob/b9aa943c1acc484f97ce6e9c69afeabb3894e6c8/crates/prover/src/core/backend/simd/column.rs#L294)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

I think so, `(0..)` is an infinite iterable, it'll stop when the `chunks_mut` stops because of the zip. I'd have preferred to do the same in the parallel code but rayon doesn't support unbounded ranges (plus I have to compute the bounds in the next PR to support partial chunks anyway).
</blockquote></details>

so can you just do it with a bound?
I think its more readable anyway that way
___
*[`crates/prover/src/core/backend/simd/quotients.rs` line 98 at r2](https://reviewable.io/reviews/starkware-libs/stwo/754#-O2dRgOz2cqQL_YH-klM:-O2dRgOz2cqQL_YH-klN:b9ra1xg) ([raw file](https://github.com/starkware-libs/stwo/blob/c4eb3370a90c20691f350879ab933d00b97c2023/crates/prover/src/core/backend/simd/quotients.rs#L98)):*
> ```XML
>     let span = span!(Level::INFO, "Quotient accumulation").entered();
> 
>     const CHUNK_SIZE: usize = 4;
> ```

Is this really a constant? Or does it depend on the number of quotient polynomials?



_Code quote:_
```XML
const CHUNK_SIZE: usize = 4;
```
___
*[`crates/prover/src/core/backend/simd/quotients.rs` line 105 at r2](https://reviewable.io/reviews/starkware-libs/stwo/754#-O2dsiBa-MqsPu-hjY6s:-O2dsiBa-MqsPu-hjY6t:b-wml0cl) ([raw file](https://github.com/starkware-libs/stwo/blob/c4eb3370a90c20691f350879ab933d00b97c2023/crates/prover/src/core/backend/simd/quotients.rs#L105)):*
> ```XML
>         .for_each(|(chunk_offset, mut chunk)| {
>             for quad_row_offset in 0..CHUNK_SIZE {
>                 let quad_row = ((CHUNK_SIZE >> 2) * (chunk_offset >> 2)) + quad_row_offset;
> ```

Why do you have the >>2?



_Code quote:_
```XML
let quad_row = ((CHUNK_SIZE >> 2) * (chunk_offset >> 2)) + quad_row_offset;
```
___
*[`crates/prover/src/examples/poseidon/mod.rs` line 415 at r2](https://reviewable.io/reviews/starkware-libs/stwo/754#-O2dsZYT7IpnhrLPJbAt:-O2dsZYT7IpnhrLPJbAu:blizoth) ([raw file](https://github.com/starkware-libs/stwo/blob/c4eb3370a90c20691f350879ab933d00b97c2023/crates/prover/src/examples/poseidon/mod.rs#L415)):*
> ```XML
>             .col
>             .enumerate_chunks_mut(CHUNK_SIZE)
>             .for_each(|(chunk_offset, mut col_chunk)| {
> ```

should it be chunk here?
Similar to what you have in quotients?



_Suggestion:_
```XML
.for_each(|(chunk_offset, mut chunk)| {
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/754)* status: 1 of 3 files reviewed, 5 unresolved discussions (waiting on @Alon-Ti and @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/column.rs` line 289 at r2](https://reviewable.io/reviews/starkware-libs/stwo/754#-O2eEcU06CWfO50AZKAH:-O2eEcU06CWfO50AZKAI:bo4d8tg) ([raw file](https://github.com/starkware-libs/stwo/blob/c4eb3370a90c20691f350879ab933d00b97c2023/crates/prover/src/core/backend/simd/column.rs#L289)):*
> ```XML
>     /// Returns an iterator, parallel if enabled, of (chunk_offset, chunk).
>     #[cfg(not(feature = "parallel"))]
>     pub fn enumerate_chunks_mut(
> ```

if you're using this with const `chunk_size`,  consider: 



_Suggestion:_
```XML
 pub fn enumerate_chunks_mut<const CHUNK_SIZE:usize>(
```
___
*[`crates/prover/src/core/backend/simd/column.rs` line 290 at r2](https://reviewable.io/reviews/starkware-libs/stwo/754#-O2eEooS9x7xy_1X4fu2:-O2eEooS9x7xy_1X4fu3:b4pit43) ([raw file](https://github.com/starkware-libs/stwo/blob/c4eb3370a90c20691f350879ab933d00b97c2023/crates/prover/src/core/backend/simd/column.rs#L290)):*
> ```XML
>     #[cfg(not(feature = "parallel"))]
>     pub fn enumerate_chunks_mut(
>         &mut self,
> ```

then you can take care of the remainder with .remainder

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/754)* status: 1 of 3 files reviewed, 5 unresolved discussions (waiting on @Alon-Ti and @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/column.rs` line 276 at r2](https://reviewable.io/reviews/starkware-libs/stwo/754#-O2eF2hs6zFvGyCSMozM:-O2eF2hs6zFvGyCSMozN:bqsp5tq) ([raw file](https://github.com/starkware-libs/stwo/blob/c4eb3370a90c20691f350879ab933d00b97c2023/crates/prover/src/core/backend/simd/column.rs#L276)):*
> ```XML
>     /// `SECURE_EXTENSION_DEGREE` slices of `chunk_size` `PackedBasedField`s
>     /// (i.e, `chuck_size` * `N_LANES` secure field elements, by coordinates).
>     pub fn chunks_mut(&mut self, chunk_size: usize) -> Vec<SecureColumnByCoordsMutSlice<'_>> {
> ```

consider



_Suggestion:_
```XML
pub fn chunks_mut<const CHUNK_SIZE:usize>(&mut self, chunk_size: usize)
```
___
*[`crates/prover/src/core/backend/simd/column.rs` line 281 at r2](https://reviewable.io/reviews/starkware-libs/stwo/754#-O2eFEkh-MhyV6GwKWwE:-O2eFEkh-MhyV6GwKWwF:b-llepjr) ([raw file](https://github.com/starkware-libs/stwo/blob/c4eb3370a90c20691f350879ab933d00b97c2023/crates/prover/src/core/backend/simd/column.rs#L281)):*
> ```XML
>             .get_many_mut([0, 1, 2, 3])
>             .unwrap()
>             .map(|x| x.chunks_mut(chunk_size));
> ```

this function does not exist, but you can do this for the inner chunks_mut at BaseColumn::chunks_mut



_Suggestion:_
```XML
x.array_chunks_mut<CHUNK_SIZE>(chunk_size)
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/754)* status: 1 of 3 files reviewed, 5 unresolved discussions (waiting on @Alon-Ti and @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/column.rs` line 290 at r2](https://reviewable.io/reviews/starkware-libs/stwo/754#-O2eEooS9x7xy_1X4fu2:-O2eFVNk6_-yIVBxEIw1:b-aekotd) ([raw file](https://github.com/starkware-libs/stwo/blob/c4eb3370a90c20691f350879ab933d00b97c2023/crates/prover/src/core/backend/simd/column.rs#L290)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

then you can take care of the remainder with .remainder
</blockquote></details>

and outside of iterator
that way you are not forced to pay for chunk_size on every chunk

**Review by Alon-Ti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/754)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/quotients.rs` line 98 at r2](https://reviewable.io/reviews/starkware-libs/stwo/754#-O2dRgOz2cqQL_YH-klM:-O2tCga737O9PhLh90R0:bih211) ([raw file](https://github.com/starkware-libs/stwo/blob/c4eb3370a90c20691f350879ab933d00b97c2023/crates/prover/src/core/backend/simd/quotients.rs#L98)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Is this really a constant? Or does it depend on the number of quotient polynomials?
</blockquote></details>

We iterate on the separately, so this should be constant. I'm not sure this is the best constant, but I don't want to increase it before we support partial chunks so that I don't have to increase the test size.
___
*[`crates/prover/src/core/backend/simd/quotients.rs` line 105 at r2](https://reviewable.io/reviews/starkware-libs/stwo/754#-O2dsiBa-MqsPu-hjY6s:-O2tCUyfAaqYXX-fEyRm:b-ioptu9) ([raw file](https://github.com/starkware-libs/stwo/blob/c4eb3370a90c20691f350879ab933d00b97c2023/crates/prover/src/core/backend/simd/quotients.rs#L105)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why do you have the >>2?
</blockquote></details>

Reindexed everything with respect to real chunk size.
___
*[`crates/prover/src/examples/poseidon/mod.rs` line 415 at r2](https://reviewable.io/reviews/starkware-libs/stwo/754#-O2dsZYT7IpnhrLPJbAt:-O2tD3na4OZWp4intVC9:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/c4eb3370a90c20691f350879ab933d00b97c2023/crates/prover/src/examples/poseidon/mod.rs#L415)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

should it be chunk here?
Similar to what you have in quotients?
</blockquote></details>

Done.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/754)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @Alon-Ti and @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/quotients.rs` line 105 at r2](https://reviewable.io/reviews/starkware-libs/stwo/754#-O2dsiBa-MqsPu-hjY6s:-O37IAEf7L8deAUj9hxq:b-25lofr) ([raw file](https://github.com/starkware-libs/stwo/blob/c4eb3370a90c20691f350879ab933d00b97c2023/crates/prover/src/core/backend/simd/quotients.rs#L105)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

Reindexed everything with respect to real chunk size.
</blockquote></details>

Can you document that?

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/754#-:-O3Bw2gkCokG0dBiA-4c:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Alon-Ti, @ohad-starkware, and @shaharsamocha7)

**Pull request closed without merging**
