### PR TITLE
Logup - rename claimed_sum to total_sum

### PR DESCRIPTION
**Pull request by shaharsamocha7**
Rename claimed_sum to total_sum
Take total_sum from cum_sum column

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/825)

### CODE REVIEW

**Comment by shaharsamocha7** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/825?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#825** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/825?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#818** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/818?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @shaharsamocha7 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Alon-Ti — APPROVED** [review]
:lgtm:

> Reviewed 3 of 7 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/825#-:-O7O1POZ5tQfCLatqMo5:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/logup.rs` line 173 at r2](https://reviewable.io/reviews/starkware-libs/stwo/825#-O7O0vgkBOdH57-aYEiq:-O7O0vgl4ChZS36TVMXs:b-hwpnz7) ([raw file](https://github.com/starkware-libs/stwo/blob/f465a76972f9a291b5267630e4eda8fc2a595a9f/crates/prover/src/constraint_framework/logup.rs#L173)):*
> ```XML
>         };
> 
>         // The last element in bit-reversed order of the the circle order is at index 1.
> ```

We should come up with a name for this order, and maybe constants like `%sOrder::Last`, etc.

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/825)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @Alon-Ti)

___
*[`crates/prover/src/constraint_framework/logup.rs` line 173 at r2](https://reviewable.io/reviews/starkware-libs/stwo/825#-O7O0vgkBOdH57-aYEiq:-O7OCkh03Jd50FDlaYmy:b-omd7nb) ([raw file](https://github.com/starkware-libs/stwo/blob/f465a76972f9a291b5267630e4eda8fc2a595a9f/crates/prover/src/constraint_framework/logup.rs#L173)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

We should come up with a name for this order, and maybe constants like `%sOrder::Last`, etc.
</blockquote></details>

For now I called it bit-reversed circle domain order
Maybe in the future we will want an Order Struct but I think it is a premature now.

**Review by Alon-Ti — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/825)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Pull request merged**
