### PR TITLE
Create struct for column constants.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/556)

### CODE REVIEW

**Comment by alonh5** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/556?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#556** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/556?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#555** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/555?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/556)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @alonh5)

___
*[`src/core/backend/cpu/quotients.rs` line 112 at r1](https://reviewable.io/reviews/starkware-libs/stwo/556#-Nu4zFCo6RVAVCA5SS--:-Nu4zFCo6RVAVCA5SS-0:b-s7pei2) ([raw file](https://github.com/starkware-libs/stwo/blob/394b45d72257e90cabfabfd051a6b98b785f88f6/src/core/backend/cpu/quotients.rs#L112)):*
> ```XML
> }
> 
> /// Holds the constant values used in the quotient evaluation.
> ```

It's not really a column constant. It's per mask item.
___
*[`src/core/backend/cpu/quotients.rs` line 114 at r1](https://reviewable.io/reviews/starkware-libs/stwo/556#-Nu4zNwZ0HOToRJwhBFy:-Nu4zNwZ0HOToRJwhBFz:b2ni1ar) ([raw file](https://github.com/starkware-libs/stwo/blob/394b45d72257e90cabfabfd051a6b98b785f88f6/src/core/backend/cpu/quotients.rs#L114)):*
> ```XML
> /// Holds the constant values used in the quotient evaluation.
> pub struct ColumnConstants {
>     pub line_coeffs: Vec<Vec<(SecureField, SecureField, SecureField)>>,
> ```

doc

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/556)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`src/core/backend/cpu/quotients.rs` line 114 at r1](https://reviewable.io/reviews/starkware-libs/stwo/556#-Nu4zNwZ0HOToRJwhBFy:-NuIXkcyBmvk-8KzAN2J:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/394b45d72257e90cabfabfd051a6b98b785f88f6/src/core/backend/cpu/quotients.rs#L114)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

doc
</blockquote></details>

Done.

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/556)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`src/core/backend/cpu/quotients.rs` line 115 at r3](https://reviewable.io/reviews/starkware-libs/stwo/556#-NuOPksLBlBbkGGgqA6W:-NuOPksLBlBbkGGgqA6X:br96ze7) ([raw file](https://github.com/starkware-libs/stwo/blob/41c4e2170311c13895e6d2bddb9801dff952804e/src/core/backend/cpu/quotients.rs#L115)):*
> ```XML
> /// Holds the precomputed constant values used in each quotient evaluation.
> pub struct QuotientConstants {
>     /// The line coefficients for each quotient numerator term.
> ```

Document why it's Vec<Vec<, and what is the triplet

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/556)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`src/core/backend/cpu/quotients.rs` line 115 at r3](https://reviewable.io/reviews/starkware-libs/stwo/556#-NuOPksLBlBbkGGgqA6W:-NuP7l3hEKWFYmUvvuY6:bddzoyd) ([raw file](https://github.com/starkware-libs/stwo/blob/80277f242e182eadfe27e3531d744bfea5b5b6d3/src/core/backend/cpu/quotients.rs#L115)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Document why it's Vec<Vec<, and what is the triplet
</blockquote></details>

It's written in the function, I added a link.

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/556)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`src/core/backend/cpu/quotients.rs` line 115 at r3](https://reviewable.io/reviews/starkware-libs/stwo/556#-NuOPksLBlBbkGGgqA6W:-NuTd_JaA1w7fUnTpsh9:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/80277f242e182eadfe27e3531d744bfea5b5b6d3/src/core/backend/cpu/quotients.rs#L115)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

It's written in the function, I added a link.
</blockquote></details>

Done.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r2, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/556#-:-NuTlWPu3FoLuHfnYDn8:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Pull request merged**
