### PR TITLE
Parallel grind

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/786)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/786?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#786** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/786?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#785** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/785?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#784** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/784?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/786#-:-O4ADCt4714QYI3sithJ:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/grind.rs` line 17 at r2](https://reviewable.io/reviews/starkware-libs/stwo/786#-O4AD06lEZlBaZwRcDSR:-O4AD06lEZlBaZwRcDSS:b-ohsfkj) ([raw file](https://github.com/starkware-libs/stwo/blob/07c1d9ede729d004a9e292dd9da82f3c4c70907c/crates/prover/src/core/backend/simd/grind.rs#L17)):*
> ```XML
> 
> // Note: GRIND_LOW_BITS is a cap on how much extra time we need to wait for all threads to finish.
> const GRIND_LOW_BITS: u32 = 20;
> ```

Did you measure 20 to be the optimal chunk size?



_Code quote:_
```XML
20
```
___
*[`crates/prover/src/core/backend/simd/grind.rs` line 44 at r2](https://reviewable.io/reviews/starkware-libs/stwo/786#-O4ABCdYCo5DA5hl82yJ:-O4ABCdYCo5DA5hl82yK:be8wejq) ([raw file](https://github.com/starkware-libs/stwo/blob/07c1d9ede729d004a9e292dd9da82f3c4c70907c/crates/prover/src/core/backend/simd/grind.rs#L44)):*
> ```XML
>     let pow_bits = u32x16::splat(pow_bits);
> 
>     // TODO(spapini): Parallelize.
> ```

Can remove?



_Code quote:_
```XML
// TODO(spapini): Parallelize.
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/786)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/prover/src/core/backend/simd/grind.rs` line 17 at r2](https://reviewable.io/reviews/starkware-libs/stwo/786#-O4AD06lEZlBaZwRcDSR:-O4AQhKQ3CMbzLikvQoU:b78tz8m) ([raw file](https://github.com/starkware-libs/stwo/blob/07c1d9ede729d004a9e292dd9da82f3c4c70907c/crates/prover/src/core/backend/simd/grind.rs#L17)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Did you measure 20 to be the optimal chunk size?
</blockquote></details>

I wouldn't say optimal, but it's a good tradeoff.

**Review by alonh5 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/786)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by alonh5 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/786)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
