### PR TITLE
Add arithmetic op counts to InfoEvaluator

### PR DESCRIPTION
**Pull request by andrewmilson**
Couldn't see a way to add the counting types without removing `Copy` from a few places.
Some constraint code is a bit more ugly now :(

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/832)

### CODE REVIEW

**Comment by andrewmilson** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/832?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#832** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/832?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#831** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/831?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @andrewmilson and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Alon-Ti — CHANGES_REQUESTED** [review]
> Reviewed 2 of 15 files at r1, 14 of 14 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/832)* status: all files reviewed, 1 unresolved discussion (waiting on @andrewmilson and @shaharsamocha7)

___
*[`crates/prover/src/examples/poseidon/mod.rs` line 30 at r3](https://reviewable.io/reviews/starkware-libs/stwo/832#-O8pzgFh3Vl1FAIhHUdy:-O8pzgFh3Vl1FAIhHUdz:b-y3f6el) ([raw file](https://github.com/starkware-libs/stwo/blob/a46c994897cc81b60828813e1ac3e775e278e244/crates/prover/src/examples/poseidon/mod.rs#L30)):*
> ```XML
> use crate::core::ColumnVec;
> 
> const N_LOG_INSTANCES_PER_ROW: usize = 0;
> ```

It still works with 3 though, right?

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/832)* status: 3 of 19 files reviewed, 1 unresolved discussion (waiting on @Alon-Ti and @shaharsamocha7)

___
*[`crates/prover/src/examples/poseidon/mod.rs` line 30 at r3](https://reviewable.io/reviews/starkware-libs/stwo/832#-O8pzgFh3Vl1FAIhHUdy:-OCRKNd-9N07rd6sB72F:b-jec2jb) ([raw file](https://github.com/starkware-libs/stwo/blob/19e4fac9323b734bdb06a7086f22f67f42866220/crates/prover/src/examples/poseidon/mod.rs#L30)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

It still works with 3 though, right?
</blockquote></details>

It does. Reverted back

**Review by Alon-Ti — APPROVED** [review]
:lgtm:

> Reviewed 14 of 16 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/832#-:-OCSaNweDwvh6MVJrvaJ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Pull request merged**
