### PR TITLE
integrated mixed degree merkle tree

### PR DESCRIPTION
**Pull request by ohad-agadi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/515)

### CODE REVIEW

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/515)* status: all files reviewed, 7 unresolved discussions (waiting on @ohad-starkware)

___
*[`src/commitment_scheme/merkle_input.rs` line 155 at r2](https://reviewable.io/reviews/starkware-libs/stwo/515#-NtVFEo-DSQf_StYAH8c:-NtVFEo01pVXY5sG4U8h:b-j10jkb) ([raw file](https://github.com/starkware-libs/stwo/blob/2778b8d1be42d6a1ecba3167c4d9e011ce7af965/src/commitment_scheme/merkle_input.rs#L155)):*
> ```XML
>     pub fn build_input<'a, F: Field>(&self, columns: &[&'a [F]]) -> MerkleTreeInput<'a, F> {
>         MerkleTreeInput {
>             columns_to_inject: columns.to_vec(),
> ```

This is copying the data which defeats the purpose. Could you make it a reference in `MerkleTreeInput` also?



_Code quote:_
```XML
columns.to_vec()
```
___
*[`src/commitment_scheme/mixed_degree_decommitment.rs` line 35 at r2](https://reviewable.io/reviews/starkware-libs/stwo/515#-NtVFg-rCrUPuxda6L14:-NtVFg-rCrUPuxda6L15:b-725qc7) ([raw file](https://github.com/starkware-libs/stwo/blob/2778b8d1be42d6a1ecba3167c4d9e011ce7af965/src/commitment_scheme/mixed_degree_decommitment.rs#L35)):*
> ```XML
>             structure: MerkleTreeStructure::default(),
>         }
>     }
> ```

This should work I think. WDYT?



_Suggestion:_
```XML
#[derive(Debug, Default)]
pub struct MixedDecommitment<F: Field, H: Hasher> {
    pub hashes: Vec<H::Hash>,
    pub witness_elements: Vec<F>,

    // TODO(Ohad): remove these in non-debug builds.
    pub queried_values: Vec<F>,
    pub structure: MerkleTreeStructure,
}

impl<F: Field, H: Hasher> MixedDecommitment<F, H> {
    pub fn new() -> Self {
        Self::default()
    }
```
___
*[`src/core/commitment_scheme/mod.rs` line 109 at r2](https://reviewable.io/reviews/starkware-libs/stwo/515#-NtVIaXBA7pzywoGZslB:-NtVIaXBA7pzywoGZslC:biiz86s) ([raw file](https://github.com/starkware-libs/stwo/blob/2778b8d1be42d6a1ecba3167c4d9e011ce7af965/src/core/commitment_scheme/mod.rs#L109)):*
> ```XML
>         const LOG_N_BASEFIELD_ELEMENTS_IN_SACK: u32 = 4;
>         for column in evaluations.iter().map(|eval| &eval.values) {
>             let inject_depth = column.len().ilog2() - (LOG_N_BASEFIELD_ELEMENTS_IN_SACK - 1);
> ```

This could be non-positive.



_Code quote:_
```XML
column.len().ilog2() - (LOG_N_BASEFIELD_ELEMENTS_IN_SACK - 1);
```
___
*[`src/core/commitment_scheme/mod.rs` line 111 at r2](https://reviewable.io/reviews/starkware-libs/stwo/515#-NtVIiMS1Xi4bgLA-x83:-NtVIiMS1Xi4bgLA-x84:bhtzfc3) ([raw file](https://github.com/starkware-libs/stwo/blob/2778b8d1be42d6a1ecba3167c4d9e011ce7af965/src/core/commitment_scheme/mod.rs#L111)):*
> ```XML
>             let inject_depth = column.len().ilog2() - (LOG_N_BASEFIELD_ELEMENTS_IN_SACK - 1);
>             merkle_input.insert_column(inject_depth as usize, column);
>         }
> ```

Is this always the way we want to construct the input? If so this construction should be inside the merkle tree.



_Code quote:_
```XML
        let mut merkle_input = MerkleTreeInput::new();
        const LOG_N_BASEFIELD_ELEMENTS_IN_SACK: u32 = 4;
        for column in evaluations.iter().map(|eval| &eval.values) {
            let inject_depth = column.len().ilog2() - (LOG_N_BASEFIELD_ELEMENTS_IN_SACK - 1);
            merkle_input.insert_column(inject_depth as usize, column);
        }
```
___
*[`src/core/commitment_scheme/mod.rs` line 141 at r2](https://reviewable.io/reviews/starkware-libs/stwo/515#-NtVJ63gCjYSn8juaF6U:-NtVJ63gCjYSn8juaF6V:b-wxxqik) ([raw file](https://github.com/starkware-libs/stwo/blob/2778b8d1be42d6a1ecba3167c4d9e011ce7af965/src/core/commitment_scheme/mod.rs#L141)):*
> ```XML
>         let queries = std::iter::repeat(positions.to_vec())
>             .take(self.evaluations.len())
>             .collect_vec();
> ```

Can we not assume that here? Instead get a vector of queries as an argument to this function (positions: Vec<usize> -> queries: ColumnVec<Vec<usize>>)



_Code quote:_
```XML
        // Assuming rectangle trace, queries should be similar for all columns.
        let queries = std::iter::repeat(positions.to_vec())
            .take(self.evaluations.len())
            .collect_vec();
```
___
*[`src/core/commitment_scheme/mod.rs` line 149 at r2](https://reviewable.io/reviews/starkware-libs/stwo/515#-NtVKMdD0AYpzAwknuUt:-NtVKMdD0AYpzAwknuUu:b-7llvpd) ([raw file](https://github.com/starkware-libs/stwo/blob/2778b8d1be42d6a1ecba3167c4d9e011ce7af965/src/core/commitment_scheme/mod.rs#L149)):*
> ```XML
>             .map(|eval| &eval.values[..])
>             .collect_vec();
>         let input = self.structure.build_input(&eval_vec);
> ```

What's the alternative? After which tree refactor and why will it be easier then?



_Suggestion:_
```XML
        // TODO(Ohad): Rebuild the merkle input for now. Change after tree refactor.
        let eval_vec = self
            .evaluations
            .iter()
            .map(|eval| &eval.values[..])
            .collect_vec();
        let input = self.structure.build_input(&eval_vec);
```
___
*[`src/core/commitment_scheme/mod.rs` line 192 at r2](https://reviewable.io/reviews/starkware-libs/stwo/515#-NtVMSW5A2UvwwF03isX:-NtVMSW5A2UvwwF03isY:brhumzt) ([raw file](https://github.com/starkware-libs/stwo/blob/2778b8d1be42d6a1ecba3167c4d9e011ce7af965/src/core/commitment_scheme/mod.rs#L192)):*
> ```XML
>                 let positions = std::iter::repeat(positions.flatten())
>                     .take(decommitment.queried_values.len())
>                     .collect_vec();
> ```

Same here.



_Code quote:_
```XML
                let positions = std::iter::repeat(positions.flatten())
                    .take(decommitment.queried_values.len())
                    .collect_vec();
```

**Review by ohad-agadi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/515)* status: 0 of 8 files reviewed, 6 unresolved discussions (waiting on @alonh5)

___
*[`src/commitment_scheme/merkle_input.rs` line 155 at r2](https://reviewable.io/reviews/starkware-libs/stwo/515#-NtVFEo-DSQf_StYAH8c:-NtVbT9F0ryJ4JnCSeE3:b-diz304) ([raw file](https://github.com/starkware-libs/stwo/blob/2778b8d1be42d6a1ecba3167c4d9e011ce7af965/src/commitment_scheme/merkle_input.rs#L155)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

This is copying the data which defeats the purpose. Could you make it a reference in `MerkleTreeInput` also?
</blockquote></details>

it copies the refs
___
*[`src/commitment_scheme/mixed_degree_decommitment.rs` line 35 at r2](https://reviewable.io/reviews/starkware-libs/stwo/515#-NtVFg-rCrUPuxda6L14:-NtVcHdQ0naCzY03qPxd:bb7f2mf) ([raw file](https://github.com/starkware-libs/stwo/blob/2778b8d1be42d6a1ecba3167c4d9e011ce7af965/src/commitment_scheme/mixed_degree_decommitment.rs#L35)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

This should work I think. WDYT?
</blockquote></details>

done
___
*[`src/core/commitment_scheme/mod.rs` line 109 at r2](https://reviewable.io/reviews/starkware-libs/stwo/515#-NtVIaXBA7pzywoGZslB:-NtVdYB_7ZbbCikWm7mO:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/2778b8d1be42d6a1ecba3167c4d9e011ce7af965/src/core/commitment_scheme/mod.rs#L109)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

This could be non-positive.
</blockquote></details>

Done.
___
*[`src/core/commitment_scheme/mod.rs` line 111 at r2](https://reviewable.io/reviews/starkware-libs/stwo/515#-NtVIiMS1Xi4bgLA-x83:-NtVdYslC0zv1lPQjQ_m:bvr3gxw) ([raw file](https://github.com/starkware-libs/stwo/blob/2778b8d1be42d6a1ecba3167c4d9e011ce7af965/src/core/commitment_scheme/mod.rs#L111)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Is this always the way we want to construct the input? If so this construction should be inside the merkle tree.
</blockquote></details>

this is only assuming columns are equal length. merkle doesn't know about that.
___
*[`src/core/commitment_scheme/mod.rs` line 141 at r2](https://reviewable.io/reviews/starkware-libs/stwo/515#-NtVJ63gCjYSn8juaF6U:-NtVeh_-Bj0Z0ugk082i:bwuivj0) ([raw file](https://github.com/starkware-libs/stwo/blob/2778b8d1be42d6a1ecba3167c4d9e011ce7af965/src/core/commitment_scheme/mod.rs#L141)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Can we not assume that here? Instead get a vector of queries as an argument to this function (positions: Vec<usize> -> queries: ColumnVec<Vec<usize>>)
</blockquote></details>

it will move to the caller at line 150, which assumes the columns are equal length.
this has to be done somewhere outside the tree, because the tree wants queries for every column 
___
*[`src/core/commitment_scheme/mod.rs` line 149 at r2](https://reviewable.io/reviews/starkware-libs/stwo/515#-NtVKMdD0AYpzAwknuUt:-NtVe6wm4wh5iT1kTFlt:b-eeptw4) ([raw file](https://github.com/starkware-libs/stwo/blob/2778b8d1be42d6a1ecba3167c4d9e011ce7af965/src/core/commitment_scheme/mod.rs#L149)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

What's the alternative? After which tree refactor and why will it be easier then?
</blockquote></details>

I'm thinkning removing the input struct and have the decommitmen take queries and columns only. not too complicated but too much for this PR IMO

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/515)* status: all files reviewed, 8 unresolved discussions (waiting on @ohad-starkware)

___
*[`src/commitment_scheme/merkle_input.rs` line 155 at r2](https://reviewable.io/reviews/starkware-libs/stwo/515#-NtVFEo-DSQf_StYAH8c:-NtVfdov0ImJrkA7qmsC:bxh4ia8) ([raw file](https://github.com/starkware-libs/stwo/blob/2778b8d1be42d6a1ecba3167c4d9e011ce7af965/src/commitment_scheme/merkle_input.rs#L155)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

it copies the refs
</blockquote></details>

You're right, this is fine.
___
*[`src/commitment_scheme/mixed_degree_decommitment.rs` line 26 at r4](https://reviewable.io/reviews/starkware-libs/stwo/515#-NtVft1P4ln1ixpLDeXY:-NtVft1Q3kM97qL1pGti:b-ay6tlj) ([raw file](https://github.com/starkware-libs/stwo/blob/402b377662886d6d31e1a0f8b7e50b76d10c8768/src/commitment_scheme/mixed_degree_decommitment.rs#L26)):*
> ```XML
> }
> 
> #[allow(clippy::new_without_default)]
> ```

You can remove this now right?



_Code quote:_
```XML
#[allow(clippy::new_without_default)]
```
___
*[`src/core/commitment_scheme/mod.rs` line 141 at r2](https://reviewable.io/reviews/starkware-libs/stwo/515#-NtVJ63gCjYSn8juaF6U:-NtVlVgpE-8Lix_uImh9:bbv7vtl) ([raw file](https://github.com/starkware-libs/stwo/blob/2778b8d1be42d6a1ecba3167c4d9e011ce7af965/src/core/commitment_scheme/mod.rs#L141)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

it will move to the caller at line 150, which assumes the columns are equal length.
this has to be done somewhere outside the tree, because the tree wants queries for every column
</blockquote></details>

It should eventually be moved to the commitment scheme prover. Add a TODO for now.
___
*[`src/core/commitment_scheme/mod.rs` line 149 at r2](https://reviewable.io/reviews/starkware-libs/stwo/515#-NtVKMdD0AYpzAwknuUt:-NtVlzBy-wTpFpy-BMpC:b-i0qn0i) ([raw file](https://github.com/starkware-libs/stwo/blob/2778b8d1be42d6a1ecba3167c4d9e011ce7af965/src/core/commitment_scheme/mod.rs#L149)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

I'm thinkning removing the input struct and have the decommitmen take queries and columns only. not too complicated but too much for this PR IMO
</blockquote></details>

NP. Please elaborate on that change in the TODO, in case someone else does it.
___
*[`src/core/commitment_scheme/mod.rs` line 42 at r4](https://reviewable.io/reviews/starkware-libs/stwo/515#-NtVhfkwEaVs7D-uTwHT:-NtVhfkwEaVs7D-uTwHU:b-wo2vcm) ([raw file](https://github.com/starkware-libs/stwo/blob/402b377662886d6d31e1a0f8b7e50b76d10c8768/src/core/commitment_scheme/mod.rs#L42)):*
> ```XML
> type MerkleHasher = Blake2sHasher;
> type ProofChannel = Blake2sChannel;
> pub mod utils;
> ```

Move back to top of file.



_Code quote:_
```XML
pub mod utils;
```
___
*[`src/core/commitment_scheme/mod.rs` line 66 at r4](https://reviewable.io/reviews/starkware-libs/stwo/515#-NtVhZoFDv2DAssmDtWu:-NtVhZoFDv2DAssmDtWv:b-hfvh8x) ([raw file](https://github.com/starkware-libs/stwo/blob/402b377662886d6d31e1a0f8b7e50b76d10c8768/src/core/commitment_scheme/mod.rs#L66)):*
> ```XML
>         &self.0
>     }
> }
> ```

Remove these, they aren't used anymore.



_Code quote:_
```XML
/// Holds a vector for each tree, which holds a vector for each column, which holds its respective
/// opened values.
#[derive(Debug)]
pub struct OpenedValues(pub Vec<ColumnVec<Vec<BaseField>>>);

impl Deref for OpenedValues {
    type Target = Vec<Vec<Vec<BaseField>>>;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

#[derive(Debug)]
pub struct Decommitments(Vec<MixedDecommitment<BaseField, Blake2sHasher>>);

impl Deref for Decommitments {
    type Target = Vec<MixedDecommitment<BaseField, Blake2sHasher>>;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
```
___
*[`src/core/commitment_scheme/mod.rs` line 210 at r4](https://reviewable.io/reviews/starkware-libs/stwo/515#-NtViplU1oFHRMiZLyJE:-NtViplU1oFHRMiZLyJF:b-r9cqsg) ([raw file](https://github.com/starkware-libs/stwo/blob/402b377662886d6d31e1a0f8b7e50b76d10c8768/src/core/commitment_scheme/mod.rs#L210)):*
> ```XML
>             evaluations[0].len().ilog2() as i32 - (LOG_N_BASEFIELD_ELEMENTS_IN_SACK as i32 - 1),
>             1,
>         );
> ```

Add a TODO to remove this assumption.
Also document this calculation.



_Suggestion:_
```XML
        // Assuming rectangle trace, all columns go to the same depth.
        let inject_depth = std::cmp::max::<i32>(
            evaluations[0].len().ilog2() as i32 - (LOG_N_BASE_FIELD_ELEMENTS_IN_SACK as i32 - 1),
            1,
        );
```
___
*[`src/core/commitment_scheme/mod.rs` line 323 at r4](https://reviewable.io/reviews/starkware-libs/stwo/515#-NtVmDlyEMeZvReVCMDZ:-NtVmDlyEMeZvReVCMD_:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/402b377662886d6d31e1a0f8b7e50b76d10c8768/src/core/commitment_scheme/mod.rs#L323)):*
> ```XML
>         // Verify merkle decommitments.
> 
>         if !self
> ```





_Suggestion:_
```XML
        // Verify merkle decommitments.
        if !self
```

**Review by ohad-agadi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/515)* status: all files reviewed, 7 unresolved discussions (waiting on @alonh5)

___
*[`src/commitment_scheme/merkle_input.rs` line 155 at r2](https://reviewable.io/reviews/starkware-libs/stwo/515#-NtVFEo-DSQf_StYAH8c:-NtVobQV1Jq31QwyIGIB:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/2778b8d1be42d6a1ecba3167c4d9e011ce7af965/src/commitment_scheme/merkle_input.rs#L155)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

You're right, this is fine.
</blockquote></details>

Done.
___
*[`src/commitment_scheme/mixed_degree_decommitment.rs` line 26 at r4](https://reviewable.io/reviews/starkware-libs/stwo/515#-NtVft1P4ln1ixpLDeXY:-NtVog4a1VbTLoy2d7Ns:bqyvsvn) ([raw file](https://github.com/starkware-libs/stwo/blob/402b377662886d6d31e1a0f8b7e50b76d10c8768/src/commitment_scheme/mixed_degree_decommitment.rs#L26)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

You can remove this now right?
</blockquote></details>

yes, thank you
___
*[`src/core/commitment_scheme/mod.rs` line 141 at r2](https://reviewable.io/reviews/starkware-libs/stwo/515#-NtVJ63gCjYSn8juaF6U:-NtVnqnjCuMH3IObLQWW:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/2778b8d1be42d6a1ecba3167c4d9e011ce7af965/src/core/commitment_scheme/mod.rs#L141)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

It should eventually be moved to the commitment scheme prover. Add a TODO for now.
</blockquote></details>

Done.
___
*[`src/core/commitment_scheme/mod.rs` line 42 at r4](https://reviewable.io/reviews/starkware-libs/stwo/515#-NtVhfkwEaVs7D-uTwHT:-NtVnJzK1qKOmGPKkf7w:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/402b377662886d6d31e1a0f8b7e50b76d10c8768/src/core/commitment_scheme/mod.rs#L42)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Move back to top of file.
</blockquote></details>

Done.
___
*[`src/core/commitment_scheme/mod.rs` line 66 at r4](https://reviewable.io/reviews/starkware-libs/stwo/515#-NtVhZoFDv2DAssmDtWu:-NtVoiwK1CFFl3keEkk9:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/402b377662886d6d31e1a0f8b7e50b76d10c8768/src/core/commitment_scheme/mod.rs#L66)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Remove these, they aren't used anymore.
</blockquote></details>

Done.
___
*[`src/core/commitment_scheme/mod.rs` line 210 at r4](https://reviewable.io/reviews/starkware-libs/stwo/515#-NtViplU1oFHRMiZLyJE:-NtVndjp98efmEtdwvvE:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/402b377662886d6d31e1a0f8b7e50b76d10c8768/src/core/commitment_scheme/mod.rs#L210)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Add a TODO to remove this assumption.
Also document this calculation.
</blockquote></details>

Done.
___
*[`src/core/commitment_scheme/mod.rs` line 323 at r4](https://reviewable.io/reviews/starkware-libs/stwo/515#-NtVmDlyEMeZvReVCMDZ:-NtVoY9mBXfXuL5_neak:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/402b377662886d6d31e1a0f8b7e50b76d10c8768/src/core/commitment_scheme/mod.rs#L323)):*
> ```XML
>         // Verify merkle decommitments.
> 
>         if !self
> ```

Done.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/515#-:-NtVqOlg38u6BZpdeJww:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ohad-starkware)

___
*[`src/core/commitment_scheme/mod.rs` line 158 at r6](https://reviewable.io/reviews/starkware-libs/stwo/515#-NtVqG8w8tsSQxj8kaqq:-NtVqG8x8wD3I5VsJAyz:b-9xzyhe) ([raw file](https://github.com/starkware-libs/stwo/blob/c06d52debafb29316b4d3212fa1d980ded7f4f27/src/core/commitment_scheme/mod.rs#L158)):*
> ```XML
>     pub polynomials: ColumnVec<CPUCirclePoly>,
>     pub evaluations: ColumnVec<CPUCircleEvaluation<BaseField, BitReversedOrder>>,
>     // TODO(AlonH): Change to mixed degree merkle and remove values clone.
> ```

Remove please :)



_Code quote:_
```XML
// TODO(AlonH): Change to mixed degree merkle and remove values clone.
```
___
*[`src/core/commitment_scheme/mod.rs` line 182 at r6](https://reviewable.io/reviews/starkware-libs/stwo/515#-NtVpw-Q53psgKZo1wh0:-NtVpw-Q53psgKZo1wh1:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/c06d52debafb29316b4d3212fa1d980ded7f4f27/src/core/commitment_scheme/mod.rs#L182)):*
> ```XML
> 
>         // The desired depth for column of log_length n is such that Blake2s hashes are filled(64B).
>         // Explicitly: THere are 2^(d-1) hash 'sacks' at depth d, hence,  with elements of 4 bytes,
> ```





_Suggestion:_
```XML
There are
```

**Review by alonh5 — APPROVED** [review]
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/515)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ohad-starkware)

**Review by alonh5 — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/515)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ohad-starkware)

**Comment by ohad-starkware** [comment]
### Merge activity

* **Mar 21, 8:09 AM EDT**: @ohad-starkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/515).

**Pull request merged**
