### PR TITLE
add simd implementation to precompute_twiddles

### PR DESCRIPTION
**Pull request by carlogf**
This PR adds rayon parallelization to the function precompute_twiddles in the SIMD backend. We did some rough measures and saw an improvement of approximately 70% in time to precompute the twiddles in the test_simd_wide_fib_prove.

We also add a small test to compare the simd precompute_twiddles against the cpu backend precompute_twiddles.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/703)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
I tihnk it might be a bit premature to parallelize this. It's not even SIMD. It's not even algorithmically optimized. Using domain.at(), for example, is slow.

A better algorithm would use something like the `eval_at_point()` SIMD code.

We can note that moving from from arbitrary domain point at bit reversed index, say 0b10011, to the one at bit index 0b10100, is adding the a specific point, depending on the number of trailing ones of the former index. (Similar to `advance_twiddle()`)
So, we precompute these log n points.
Then, we can add just one point at each iteration, instead of calling at().
This can also be SIMD, by working with a vector with all the options for the lower bits (again, like `eval_at_point()`).

Don't know if you are up to it.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/703#-:-O1GmPF8BNdkOCET0NOy:bl1pty7)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @carlogf)

___
*[`crates/prover/src/core/backend/simd/circle.rs` line 287 at r1](https://reviewable.io/reviews/starkware-libs/stwo/703#-O1GlNpS1VEmQQlX9_T7:-O1GlNpS1VEmQQlX9_T8:bnf0nep) ([raw file](https://github.com/starkware-libs/stwo/blob/a5f8ee63d6614b018d516537ea0129b8b2d4389d/crates/prover/src/core/backend/simd/circle.rs#L287)):*
> ```XML
>         let mut doubling_coset = coset.clone();
> 
>         let twiddles_wrapped_pointer = SendMutU32Ptr(twiddles.as_mut_ptr());
> ```

The SendMutU32Ptr was on a draft. I don't really want to use, I'd rather using something safe. You can check out this PR for an example: [https://reviewable.io/reviews/starkware-libs/stwo/690](https://reviewable.io/reviews/starkware-libs/stwo/690)
I added chunks_mut() to Column.
___
*[`crates/prover/src/core/backend/simd/circle.rs` line 299 at r1](https://reviewable.io/reviews/starkware-libs/stwo/703#-O1GlhGY5gjCBWNSXE82:-O1GlhGY5gjCBWNSXE83:b-41ql9) ([raw file](https://github.com/starkware-libs/stwo/blob/a5f8ee63d6614b018d516537ea0129b8b2d4389d/crates/prover/src/core/backend/simd/circle.rs#L299)):*
> ```XML
> 
>             #[cfg(feature = "parallel")]
>             let iter = (0..chunk_length).into_par_iter();
> ```

Can we put this in a common function, so we won't have to write it all the time?



_Code quote:_
```XML
            #[cfg(not(feature = "parallel"))]
            let iter = 0..chunk_length;

            #[cfg(feature = "parallel")]
            let iter = (0..chunk_length).into_par_iter();
```

**Comment by carlogf** [comment]
Thanks for the input!

> We can note that moving from from arbitrary domain point at bit reversed index, say 0b10011, to the one at bit index 0b10100, is adding the a specific point, depending on the number of trailing ones of the former index. (Similar to `advance_twiddle()`)
> So, we precompute these log n points.

I'm looking into implementing this. I think I almost got it.

> The SendMutU32Ptr was on a draft. I don't really want to use, I'd rather using something safe. You can check out this PR for an example: https://reviewable.io/reviews/starkware-libs/stwo/690
> I added chunks_mut() to Column.

I was actually trying to avoid raw pointers until I saw your draft PR :sweat_smile: 



> Can we put this in a common function, so we won't have to write it all the time?

:+1: :+1: :+1:

**Review by spapinistarkware — COMMENTED** [review]
> I'm looking into implementing this. I think I almost got it.

Amazing

> I was actually trying to avoid raw pointers

and rightfully so!

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/703#-:-O1Vl73j4hMVE2IMBf_Q:b-t60m20)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @carlogf)

**Comment by carlogf** [comment]
Hey!
This pr now adds a simd implementation of precompute twiddles. It does it by doing it in two steps.
The first step goes through the coset in bit_reverse order and calculates the twiddles from the circle points
The second step takes the previous chunk of twiddles and applies the mapping (x -> 2x^2 -1) to calculate the next chunk. It does everything in the M31 field.

I ran test_simd_wide_fib with log_n_rows= 17 and saw the time to taken to precompute the twiddles drop from ~22ms to ~12ms.

If you guys are okay with this approach, it will be easy to add parallelization in the second step :)

Best!
Carlo

**Review by spapinistarkware — COMMENTED** [review]
Let's put this task on hold for now. It's not exactly what I had in mind, and precompute twiddles is not a high priorty.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/703#-:-O2c_mJp3Xkg1fhPH7m4:bc8gbku)* status: 0 of 3 files reviewed, all discussions resolved

**Comment by spapinistarkware** [comment]
On hold

**Pull request closed without merging**
