### PR TITLE
Fix dev.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/512)

### CODE REVIEW

**Comment by alonh5** [comment]
* **#512** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/512?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ohad-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/512)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

___
*[`src/core/prover/mod.rs` line 335 at r1](https://reviewable.io/reviews/starkware-libs/stwo/512#-NtQ0rFt3aLOLKpl-BFk:-NtQ0rFt3aLOLKpl-BFl:b8vbig) ([raw file](https://github.com/starkware-libs/stwo/blob/6129d86f6e6feaac1afcb3dd77115e4f3d4bac18/src/core/prover/mod.rs#L335)):*
> ```XML
>     use crate::qm31;
> 
>     struct TestAir<C: Component<CPUBackend>>(C);
> ```

Consider making this a non-tuple struct, to be uniform with other airs, it's confusing one returns self.0 and one is self.component
___
*[`src/core/prover/mod.rs` line 338 at r1](https://reviewable.io/reviews/starkware-libs/stwo/512#-NtQ0WUw3a9yeA8I7mVq:-NtQ0WUw3a9yeA8I7mVr:b-mmd98k) ([raw file](https://github.com/starkware-libs/stwo/blob/6129d86f6e6feaac1afcb3dd77115e4f3d4bac18/src/core/prover/mod.rs#L338)):*
> ```XML
> 
>     impl Air<CPUBackend> for TestAir<TestComponent> {
>         fn components(&self) -> Vec<&dyn Component<CPUBackend>> {
> ```

@spapinistarkware why the trait defines it &dyn and not &impl?
I tried to change it locally, and it worked.

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/512)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @ohad-starkware)

___
*[`src/core/prover/mod.rs` line 335 at r1](https://reviewable.io/reviews/starkware-libs/stwo/512#-NtQ0rFt3aLOLKpl-BFk:-NtQ4oqWD_GYL3MPbc-Z:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/6129d86f6e6feaac1afcb3dd77115e4f3d4bac18/src/core/prover/mod.rs#L335)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

Consider making this a non-tuple struct, to be uniform with other airs, it's confusing one returns self.0 and one is self.component
</blockquote></details>

Done.
___
*[`src/core/prover/mod.rs` line 338 at r1](https://reviewable.io/reviews/starkware-libs/stwo/512#-NtQ0WUw3a9yeA8I7mVq:-NtQ2XEODH-IJrf5-kbN:bae7urg) ([raw file](https://github.com/starkware-libs/stwo/blob/6129d86f6e6feaac1afcb3dd77115e4f3d4bac18/src/core/prover/mod.rs#L338)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

@spapinistarkware why the trait defines it &dyn and not &impl?
I tried to change it locally, and it worked.
</blockquote></details>

That's for having airs with multiple different impls of Component. You're right that atm we don't have that, but we will (like Cairo air which will have a cpu component, and a component for each builtin).

**Review by ohad-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/512)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @alonh5)

___
*[`src/core/prover/mod.rs` line 338 at r1](https://reviewable.io/reviews/starkware-libs/stwo/512#-NtQ0WUw3a9yeA8I7mVq:-NtQ5erM9UN2KI-G4SU5:b-ez2axr) ([raw file](https://github.com/starkware-libs/stwo/blob/6129d86f6e6feaac1afcb3dd77115e4f3d4bac18/src/core/prover/mod.rs#L338)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

That's for having airs with multiple different impls of Component. You're right that atm we don't have that, but we will (like Cairo air which will have a cpu component, and a component for each builtin).
</blockquote></details>

understood, thanks.

**Review by ohad-starkware — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/512#-:-NtQ6uSu9R5wcjVypm9R:bg7igkv)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @alonh5)

**Pull request merged**
