### PR TITLE
Fix the reference blake2s doc

### PR DESCRIPTION
**Pull request by dlubarov**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/858)

### CODE REVIEW

**Review by shaharsamocha7 — COMMENTED** [review]
We reference to this implementation and wanted to credit the writer.
Why do you suggest to change this doc?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/858#-:-OAlMG_wAqQGWb862PMN:b4znzrx)* status: 0 of 1 files reviewed, all discussions resolved

**Comment by dlubarov** [comment]
Oh, I'll add back the link then, but `An AVX512 implementation` seems like accidental copypasta in 9dbe5bc23d226414d9878d1a3aea63a546771fff since this one is the pure Rust implementation.

**Comment by dlubarov** [comment]
Done

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/858#-:-OBUPKgGA7q7HcR9Zfre:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dlubarov)

**Pull request merged**
