### PR TITLE
Initialize logups automatically when first used.

### PR DESCRIPTION
**Pull request by Alon-Ti**

### CODE REVIEW

**Comment by Alon-Ti** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/879?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#879** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/879?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#876** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/876?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#875** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/875?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Alon-Ti and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/879)* status: 0 of 23 files reviewed, 2 unresolved discussions (waiting on @Alon-Ti)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo/879#-OBV0Koq9r_GW0b7YZ2c:-OBV0KorEDrJxEbMheII:bb2wawr) (no related file):*
Can you split this pr in any way?
It is both move a lot of code and do non-trivial changes such that write_frac also initialize the logup
___
*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo/879#-OBV0gMl3n7sGTuXR68G:-OBV0gMl3n7sGTuXR68H:b-8bw57n) (no related file):*
I also think that we could extract some function from write_frac code macro to make it more clear

**Review by ohad-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/879)* status: 0 of 23 files reviewed, 6 unresolved discussions (waiting on @Alon-Ti and @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/component.rs` line 85 at r1](https://reviewable.io/reviews/starkware-libs/stwo/879#-OBV33Pt8oLtP3IELMQJ:-OBV33Pt8oLtP3IELMQK:b-ayvgwp) ([raw file](https://github.com/starkware-libs/stwo/blob/0c64f9280b89e2e427cace1020bef9b1fdae2c28/crates/prover/src/constraint_framework/component.rs#L85)):*
> ```XML
>     info: InfoEvaluator,
>     total_sum: SecureField,
>     claimed_sum: Option<ClaimedPrefixSum>,
> ```

use logup sums



_Code quote:_
```XML
    total_sum: SecureField,
    claimed_sum: Option<ClaimedPrefixSum>,
```
___
*[`crates/prover/src/constraint_framework/component.rs` line 172 at r1](https://reviewable.io/reviews/starkware-libs/stwo/879#-OBV238A8szwoUKAdERf:-OBV238B3jUO2IQnqXh_:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/0c64f9280b89e2e427cace1020bef9b1fdae2c28/crates/prover/src/constraint_framework/component.rs#L172)):*
> ```XML
>         let trace_domain = CanonicCoset::new(self.eval.log_size());
> 
>         println!("n polys: {}", trace.polys[0].len());
> ```


___
*[`crates/prover/src/constraint_framework/logup.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/stwo/879#-OBV2sfy223ZNk_ZwiXb:-OBV2sfy223ZNk_ZwiXc:b3kre) ([raw file](https://github.com/starkware-libs/stwo/blob/0c64f9280b89e2e427cace1020bef9b1fdae2c28/crates/prover/src/constraint_framework/logup.rs#L69)):*
> ```XML
>             prev_col_cumsum: E::EF::zero(),
>             cur_frac: None,
>             is_finalized: true,
> ```

?
___
*[`crates/prover/src/constraint_framework/logup.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/stwo/879#-OBV2w6YAVsFBEI3WV6x:-OBV2w6YAVsFBEI3WV6y:bb7r2f0) ([raw file](https://github.com/starkware-libs/stwo/blob/0c64f9280b89e2e427cace1020bef9b1fdae2c28/crates/prover/src/constraint_framework/logup.rs#L94)):*
> ```XML
> impl<E: EvalAtRow> Drop for LogupAtRow<E> {
>     fn drop(&mut self) {
>         // assert!(self.is_finalized, "LogupAtRow was not finalized");
> ```

why?

**Review by Alon-Ti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/879)* status: 0 of 25 files reviewed, 6 unresolved discussions (waiting on @ohad-starkware and @shaharsamocha7)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo/879#-OBV0Koq9r_GW0b7YZ2c:-OBXlJEu9s1Sy49OWxce:b-4h3edt) (no related file):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can you split this pr in any way?
It is both move a lot of code and do non-trivial changes such that write_frac also initialize the logup
</blockquote></details>

I don't think so, making components initialize the logup means you have to pass all the params to all of them.
___
*[`crates/prover/src/constraint_framework/component.rs` line 85 at r1](https://reviewable.io/reviews/starkware-libs/stwo/879#-OBV33Pt8oLtP3IELMQJ:-OBXmq7KAbPxHPCJMzcy:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/0c64f9280b89e2e427cace1020bef9b1fdae2c28/crates/prover/src/constraint_framework/component.rs#L85)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

use logup sums
</blockquote></details>

Done.
___
*[`crates/prover/src/constraint_framework/logup.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/stwo/879#-OBV2sfy223ZNk_ZwiXb:-OBXmyNQ5hoIp0zm0AdI:bwm8haj) ([raw file](https://github.com/starkware-libs/stwo/blob/0c64f9280b89e2e427cace1020bef9b1fdae2c28/crates/prover/src/constraint_framework/logup.rs#L69)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

?
</blockquote></details>

A logup starts finalized until it's used, when it becomes not finalized until `finalize_logup` is called. This is required for component that don't have logups.
___
*[`crates/prover/src/constraint_framework/logup.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/stwo/879#-OBV2w6YAVsFBEI3WV6x:-OBXnVmND0X2gzELTj6W:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/0c64f9280b89e2e427cace1020bef9b1fdae2c28/crates/prover/src/constraint_framework/logup.rs#L94)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

why?
</blockquote></details>

Done.
___
*[`crates/prover/src/constraint_framework/component.rs` line 172 at r1](https://reviewable.io/reviews/starkware-libs/stwo/879#-OBV238A8szwoUKAdERf:-OBXmvdF3_3KHKQblNFb:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/0c64f9280b89e2e427cace1020bef9b1fdae2c28/crates/prover/src/constraint_framework/component.rs#L172)):*
> ```XML
>         let trace_domain = CanonicCoset::new(self.eval.log_size());
> 
>         println!("n polys: {}", trace.polys[0].len());
> ```

Done.

**Review by shaharsamocha7 — APPROVED** [review]
> Reviewed 5 of 23 files at r1, 17 of 20 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/879)* status: all files reviewed, 6 unresolved discussions (waiting on @Alon-Ti)

___
*[`crates/prover/src/constraint_framework/info.rs` line 26 at r4](https://reviewable.io/reviews/starkware-libs/stwo/879#-OBe4RNNCvD6QRKQUBFJ:-OBe4RNNCvD6QRKQUBFK:b273w8m) ([raw file](https://github.com/starkware-libs/stwo/blob/7d3d67688815e83834207e8c81f644dba4aeca44/crates/prover/src/constraint_framework/info.rs#L26)):*
> ```XML
>     pub fn new(
>         log_size: u32,
>         preprocessed_columns: Vec<PreprocessedColumn>,
> ```

Why InfoEvaluator gets preprocessed_columns at all?
Shouldn't it be always empty at construction?



_Code quote:_
```XML
        preprocessed_columns: Vec<PreprocessedColumn>,
```
___
*[`crates/prover/src/constraint_framework/logup.rs` line 27 at r4](https://reviewable.io/reviews/starkware-libs/stwo/879#-OBe5QjF3OBvMZ9_UYVX:-OBe5QjF3OBvMZ9_UYVY:b8iwa6j) ([raw file](https://github.com/starkware-libs/stwo/blob/7d3d67688815e83834207e8c81f644dba4aeca44/crates/prover/src/constraint_framework/logup.rs#L27)):*
> ```XML
> /// Should be used to eliminate padded rows for the logup sum.
> pub type ClaimedPrefixSum = (SecureField, usize);
> // (total_sum, claimed_sum)
> ```

Claimed_sum should be set to none if equal to total_sum



_Code quote:_
```XML
// (total_sum, claimed_sum)
```
___
*[`crates/prover/src/constraint_framework/logup.rs` line 69 at r4](https://reviewable.io/reviews/starkware-libs/stwo/879#-OBe4sOj9otT3ymEdzqG:-OBe4sOj9otT3ymEdzqH:bl9nal5) ([raw file](https://github.com/starkware-libs/stwo/blob/7d3d67688815e83834207e8c81f644dba4aeca44/crates/prover/src/constraint_framework/logup.rs#L69)):*
> ```XML
>             prev_col_cumsum: E::EF::zero(),
>             cur_frac: None,
>             is_finalized: true,
> ```

Write a comment that this is turned to false only at first use



_Code quote:_
```XML
is_finalized: true,
```
___
*[`crates/prover/src/examples/blake/xor_table/gen.rs` line 168 at r4](https://reviewable.io/reviews/starkware-libs/stwo/879#-OBe5lr8EABO_gyllLSy:-OBe5lr8EABO_gyllLSz:b-ha1hd8) ([raw file](https://github.com/starkware-libs/stwo/blob/7d3d67688815e83834207e8c81f644dba4aeca44/crates/prover/src/examples/blake/xor_table/gen.rs#L168)):*
> ```XML
>         })
>         .to_vec();
>     constant_trace.push(gen_is_first(column_bits::<ELEM_BITS, EXPAND_BITS>()));
> ```

I don't understand this



_Code quote:_
```XML
constant_trace.push(gen_is_first(column_bits::<ELEM_BITS, EXPAND_BITS>()));
```
___
*[`crates/prover/src/constraint_framework/assert.rs` line 32 at r4](https://reviewable.io/reviews/starkware-libs/stwo/879#-OBe38zNBC-A9RJSDQ6D:-OBe38zNBC-A9RJSDQ6E:b-puuswc) ([raw file](https://github.com/starkware-libs/stwo/blob/7d3d67688815e83834207e8c81f644dba4aeca44/crates/prover/src/constraint_framework/assert.rs#L32)):*
> ```XML
>             col_index: TreeVec::new(vec![0; trace.len()]),
>             row,
>             logup: LogupAtRow::new(INTERACTION_TRACE_IDX, logup_sums.0, logup_sums.1, log_size),
> ```

Should we change LogupAtRow to get LogupSums?
Can be done in another pr



_Code quote:_
```XML
LogupAtRow::new(INTERACTION_TRACE_IDX, logup_sums.0, logup_sums.1, log_size)
```

**Comment by Alon-Ti** [comment]
### Merge activity

* **Nov 18, 2:41 AM EST**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/879).

**Pull request merged**
