### PR TITLE
Simd twiddles

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/820)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/820?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#820** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/820?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#819** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/819?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by alonh5 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/820)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @Alon-Ti, @shaharsamocha7, and @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/circle.rs` line 282 at r1](https://reviewable.io/reviews/starkware-libs/stwo/820#-O78_GqK6IlIE8N0m_m7:-O78_GqK6IlIE8N0m_m8:b-juueo6) ([raw file](https://github.com/starkware-libs/stwo/blob/755db7c561caa6aff26d322f98cf953f5e4d4833/crates/prover/src/core/backend/simd/circle.rs#L282)):*
> ```XML
> 
>     #[allow(clippy::int_plus_one)]
>     fn precompute_twiddles(mut coset: Coset) -> TwiddleTree<Self> {
> ```

Please add a unit test to compare with the CPU implementation.
___
*[`crates/prover/src/core/backend/simd/circle.rs` line 317 at r1](https://reviewable.io/reviews/starkware-libs/stwo/820#-O78XUx5B4VM6206ftiL:-O78XUx5B4VM6206ftiM:b-alo1lo) ([raw file](https://github.com/starkware-libs/stwo/blob/755db7c561caa6aff26d322f98cf953f5e4d4833/crates/prover/src/core/backend/simd/circle.rs#L317)):*
> ```XML
>         }
> 
>         xs.push(PackedM31::from_array(extra.try_into().unwrap()));
> ```

Does this try into work because it's initialized with capacity N_LANES? 



_Code quote:_
```XML
xs.push(PackedM31::from_array(extra.try_into().unwrap()));
```
___
*[`crates/prover/src/core/backend/simd/circle.rs` line 340 at r1](https://reviewable.io/reviews/starkware-libs/stwo/820#-O78_8Jt6HGK38AYhWTf:-O78_8Jt6HGK38AYhWTg:b-fl6deb) ([raw file](https://github.com/starkware-libs/stwo/blob/755db7c561caa6aff26d322f98cf953f5e4d4833/crates/prover/src/core/backend/simd/circle.rs#L340)):*
> ```XML
> 
> #[allow(clippy::int_plus_one)]
> fn gen_coset_xs(coset: Coset, res: &mut Vec<PackedM31>) {
> ```

Can you add documentation? Maybe a reference to the algorithm
___
*[`crates/prover/src/core/backend/simd/circle.rs` line 344 at r1](https://reviewable.io/reviews/starkware-libs/stwo/820#-O78XzHN2fuZ0RhUX6eC:-O78XzHN2fuZ0RhUX6eD:b2ta8jt) ([raw file](https://github.com/starkware-libs/stwo/blob/755db7c561caa6aff26d322f98cf953f5e4d4833/crates/prover/src/core/backend/simd/circle.rs#L344)):*
> ```XML
>     assert!(log_size >= LOG_N_LANES);
> 
>     let initial_points = std::array::from_fn(|i| coset.at(bit_reverse_index(i, log_size)));
> ```

Can this bit reverse be done for the whole coset at once?



_Code quote:_
```XML
let initial_points = std::array::from_fn(|i| coset.at(bit_reverse_index(i, log_size)));
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/820)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @Alon-Ti and @shaharsamocha7)

___
*[`crates/prover/src/core/backend/simd/circle.rs` line 282 at r1](https://reviewable.io/reviews/starkware-libs/stwo/820#-O78_GqK6IlIE8N0m_m7:-O7OclPkCfvxCLG1DLez:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/e666dfab00fdc94c40ee54dffb3eea0abd65f19b/crates/prover/src/core/backend/simd/circle.rs#L282)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Please add a unit test to compare with the CPU implementation.
</blockquote></details>

Done.
___
*[`crates/prover/src/core/backend/simd/circle.rs` line 340 at r1](https://reviewable.io/reviews/starkware-libs/stwo/820#-O78_8Jt6HGK38AYhWTf:-O7O_uJTE8EUNWh0MjQP:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/e666dfab00fdc94c40ee54dffb3eea0abd65f19b/crates/prover/src/core/backend/simd/circle.rs#L340)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Can you add documentation? Maybe a reference to the algorithm
</blockquote></details>

Done.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/820)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @Alon-Ti and @spapinistarkware)

___
*[`crates/prover/src/core/backend/cpu/circle.rs` line 199 at r3](https://reviewable.io/reviews/starkware-libs/stwo/820#-O7PShOF-wdeikOCw2mE:-O7PShOGAxf3MUiBGBuj:b-iaiqav) ([raw file](https://github.com/starkware-libs/stwo/blob/b7b2815a4d7b98364533cc0337161918f23a1e3d/crates/prover/src/core/backend/cpu/circle.rs#L199)):*
> ```XML
>         coset = coset.double();
>     }
>     twiddles.push(1.into());
> ```

Add a comment:
// Pad twiddles with Arbitrary value to a power of 2 vector. 



_Code quote:_
```XML
twiddles.push(1.into());
```
___
*[`crates/prover/src/core/backend/simd/circle.rs` line 303 at r3](https://reviewable.io/reviews/starkware-libs/stwo/820#-O7PTKMg5r3KMIBuJ5QV:-O7PTKMg5r3KMIBuJ5QW:bj6i1nz) ([raw file](https://github.com/starkware-libs/stwo/blob/b7b2815a4d7b98364533cc0337161918f23a1e3d/crates/prover/src/core/backend/simd/circle.rs#L303)):*
> ```XML
>         twiddles.push(PackedM31::from_array(
>             remaining_twiddles.try_into().unwrap(),
>         ));
> ```

Doesn't this code fail if the coset is smaller than 16?



_Code quote:_
```XML
        let remaining_twiddles = slow_precompute_twiddles(coset);

        twiddles.push(PackedM31::from_array(
            remaining_twiddles.try_into().unwrap(),
        ));
```
___
*[`crates/prover/src/core/backend/simd/circle.rs` line 310 at r3](https://reviewable.io/reviews/starkware-libs/stwo/820#-O7PTgzc1nQWnizgT4jD:-O7PTgzc1nQWnizgT4jE:b-d8vyf0) ([raw file](https://github.com/starkware-libs/stwo/blob/b7b2815a4d7b98364533cc0337161918f23a1e3d/crates/prover/src/core/backend/simd/circle.rs#L310)):*
> ```XML
>         let dbl_twiddles = twiddles
>             .into_iter()
>             .flat_map(|x| x.to_array().map(|x| x.0 * 2))
> ```

Mul by `PackedM31::broadcast(2)` instead of unpacking.
I think this unpacking is slow



_Code quote:_
```XML
 .flat_map(|x| x.to_array().map(|x| x.0 * 2))
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/820)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @Alon-Ti and @shaharsamocha7)

___
*[`crates/prover/src/core/backend/cpu/circle.rs` line 199 at r3](https://reviewable.io/reviews/starkware-libs/stwo/820#-O7PShOF-wdeikOCw2mE:-O7TD9sq6zdsLV_BJ46Q:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/b7b2815a4d7b98364533cc0337161918f23a1e3d/crates/prover/src/core/backend/cpu/circle.rs#L199)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Add a comment:
// Pad twiddles with Arbitrary value to a power of 2 vector.
</blockquote></details>

Done.
___
*[`crates/prover/src/core/backend/simd/circle.rs` line 303 at r3](https://reviewable.io/reviews/starkware-libs/stwo/820#-O7PTKMg5r3KMIBuJ5QV:-O7T02Ue-DtwBO-ZVDko:bdmekz9) ([raw file](https://github.com/starkware-libs/stwo/blob/b7b2815a4d7b98364533cc0337161918f23a1e3d/crates/prover/src/core/backend/simd/circle.rs#L303)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Doesn't this code fail if the coset is smaller than 16?
</blockquote></details>

It won't reach this if it's smaller than 16. It will go into the early return.
___
*[`crates/prover/src/core/backend/simd/circle.rs` line 310 at r3](https://reviewable.io/reviews/starkware-libs/stwo/820#-O7PTgzc1nQWnizgT4jD:-O7T1-qL51_fidlv8ymC:b-xzt3d) ([raw file](https://github.com/starkware-libs/stwo/blob/b7b2815a4d7b98364533cc0337161918f23a1e3d/crates/prover/src/core/backend/simd/circle.rs#L310)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Mul by `PackedM31::broadcast(2)` instead of unpacking.
I think this unpacking is slow
</blockquote></details>

That's a problem because of the reduction, we want to multiply by 2 as a u32 not a m31.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/820)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @Alon-Ti and @alonh5)

___
*[`crates/prover/src/core/backend/simd/circle.rs` line 310 at r3](https://reviewable.io/reviews/starkware-libs/stwo/820#-O7PTgzc1nQWnizgT4jD:-O7XrFcGCqtq59sj7Ng2:b-n40e0w) ([raw file](https://github.com/starkware-libs/stwo/blob/b7b2815a4d7b98364533cc0337161918f23a1e3d/crates/prover/src/core/backend/simd/circle.rs#L310)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

That's a problem because of the reduction, we want to multiply by 2 as a u32 not a m31.
</blockquote></details>

you have the `into_simd()` func, can you try using that?

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/820)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @Alon-Ti and @shaharsamocha7)

___
*[`crates/prover/src/core/backend/simd/circle.rs` line 310 at r3](https://reviewable.io/reviews/starkware-libs/stwo/820#-O7PTgzc1nQWnizgT4jD:-O7YpUg474GxGPfs5reO:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/b7b2815a4d7b98364533cc0337161918f23a1e3d/crates/prover/src/core/backend/simd/circle.rs#L310)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

you have the `into_simd()` func, can you try using that?
</blockquote></details>

Done.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/820#-:-O7Z5aZ8E298agAhLBFD:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Alon-Ti)

**Review by alonh5 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/820)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Alon-Ti)

**Comment by alonh5** [comment]
### Merge activity

* **Sep 24, 9:20 AM EDT**: @alonh5 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/820).

**Pull request merged**
