### PR TITLE
Support shared preproccessed columns.

### PR DESCRIPTION
**Pull request by ilyalesokhin-starkware**

### CODE REVIEW

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/869)* status: 0 of 9 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware, @ohad-starkware, and @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/component.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/stwo/869#-OAxRIno4zLQcDSlOjnM:-OAxRIno4zLQcDSlOjnN:b-7zi8ni) ([raw file](https://github.com/starkware-libs/stwo/blob/818e76658b640976ab8c604cd7c62f4498e62a96/crates/prover/src/constraint_framework/component.rs#L71)):*
> ```XML
>     }
> 
>     pub fn with_preproccessed_columnds(preprocessed_columns: &[PreprocessedColumn]) -> Self {
> ```

WDYT?



_Suggestion:_
```XML
new_with_preproccessed_columns
```
___
*[`crates/prover/src/constraint_framework/component.rs` line 167 at r1](https://reviewable.io/reviews/starkware-libs/stwo/869#-OAxRyOb0kILfLjZOiwA:-OAxRyOb0kILfLjZOiwB:b1q94wz) ([raw file](https://github.com/starkware-libs/stwo/blob/818e76658b640976ab8c604cd7c62f4498e62a96/crates/prover/src/constraint_framework/component.rs#L167)):*
> ```XML
>             .preprocessed_column_indices
>             .iter()
>             .map(|idx| mask.0[PREPROCESSED_TRACE_IDX][*idx].clone())
> ```

Nit: it's deref



_Suggestion:_
```XML
mask[
```
___
*[`crates/prover/src/constraint_framework/component.rs` line 171 at r1](https://reviewable.io/reviews/starkware-libs/stwo/869#-OAxSDMdEnwCZtnpIOFx:-OAxSDMdEnwCZtnpIOFy:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/818e76658b640976ab8c604cd7c62f4498e62a96/crates/prover/src/constraint_framework/component.rs#L171)):*
> ```XML
> 
>         let mut mask_points = mask.sub_tree(&self.trace_locations);
>         mask_points.0[PREPROCESSED_TRACE_IDX] = preprocessed_mask.iter().collect_vec();
> ```





_Suggestion:_
```XML
mask_points[PREPROCESSED_TRACE_IDX] = preprocessed_mask;
```
___
*[`crates/prover/src/core/air/components.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/stwo/869#-OAxT5nQEx8xaDVtYEaH:-OAxT5nQEx8xaDVtYEaI:b2nhkus) ([raw file](https://github.com/starkware-libs/stwo/blob/818e76658b640976ab8c604cd7c62f4498e62a96/crates/prover/src/core/air/components.rs#L35)):*
> ```XML
>         *preprocessed_mask_points = vec![vec![]; n_preprocessed_columns];
> 
>         for component in self.0.iter() {
> ```

Nit



_Suggestion:_
```XML
&self.0
```
___
*[`crates/prover/src/core/vcs/verifier.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/stwo/869#-OAzCti0BoFXZxYmwlAl:-OAzCti0BoFXZxYmwlAm:b-kt0r7y) ([raw file](https://github.com/starkware-libs/stwo/blob/818e76658b640976ab8c604cd7c62f4498e62a96/crates/prover/src/core/vcs/verifier.rs#L61)):*
> ```XML
>         let max_log_size = self.column_log_sizes.iter().max().copied().unwrap_or(0);
> 
>         eprintln!("self.column_log_sizes: {:?}", self.column_log_sizes);
> ```

Should we use tracing logs here i.e. ```info!(...)``` since we use for similar logs in other spots like [here](https://github.com/starkware-libs/stwo/blob/dev/crates/prover/src/core/prover/mod.rs#L80)

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/869)* status: 0 of 9 files reviewed, 6 unresolved discussions (waiting on @ilyalesokhin-starkware, @ohad-starkware, and @shaharsamocha7)

___
*[`crates/prover/src/examples/wide_fibonacci/mod.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/stwo/869#-OAzE_P6BUFtARCXvh9M:-OAzE_P6BUFtARCXvh9N:ba3dfna) ([raw file](https://github.com/starkware-libs/stwo/blob/818e76658b640976ab8c604cd7c62f4498e62a96/crates/prover/src/examples/wide_fibonacci/mod.rs#L35)):*
> ```XML
>     fn evaluate<E: EvalAtRow>(&self, mut eval: E) -> E {
>         // TODO(ilya): Remove the following once preproccessed columns are not mandatory.
>         // let _ = eval.get_preprocessed_column(PreprocessedColumn::IsFirst(self.log_size()));
> ```

Remove?

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/prover/src/core/vcs/verifier.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/stwo/869#-OAzCti0BoFXZxYmwlAl:-OB4KKn20fw0HQ0t5IS3:babwap2) ([raw file](https://github.com/starkware-libs/stwo/blob/818e76658b640976ab8c604cd7c62f4498e62a96/crates/prover/src/core/vcs/verifier.rs#L61)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Should we use tracing logs here i.e. ```info!(...)``` since we use for similar logs in other spots like [here](https://github.com/starkware-libs/stwo/blob/dev/crates/prover/src/core/prover/mod.rs#L80)
</blockquote></details>

IT was here for debugging, I'll remove that.
Thanks.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/869)* status: 0 of 9 files reviewed, 4 unresolved discussions (waiting on @andrewmilson, @ohad-starkware, and @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/component.rs` line 167 at r1](https://reviewable.io/reviews/starkware-libs/stwo/869#-OAxRyOb0kILfLjZOiwA:-OB5RD4_-iY7RnHvNcvm:bb7f2mf) ([raw file](https://github.com/starkware-libs/stwo/blob/818e76658b640976ab8c604cd7c62f4498e62a96/crates/prover/src/constraint_framework/component.rs#L167)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Nit: it's deref
</blockquote></details>

done
___
*[`crates/prover/src/constraint_framework/component.rs` line 171 at r1](https://reviewable.io/reviews/starkware-libs/stwo/869#-OAxSDMdEnwCZtnpIOFx:-OB5RF7B9ODfBC_BSEZN:bb7f2mf) ([raw file](https://github.com/starkware-libs/stwo/blob/818e76658b640976ab8c604cd7c62f4498e62a96/crates/prover/src/constraint_framework/component.rs#L171)):*
> ```XML
> 
>         let mut mask_points = mask.sub_tree(&self.trace_locations);
>         mask_points.0[PREPROCESSED_TRACE_IDX] = preprocessed_mask.iter().collect_vec();
> ```

done
___
*[`crates/prover/src/core/air/components.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/stwo/869#-OAxT5nQEx8xaDVtYEaH:-OB5RS80BcqwqZH3L0Gx:bb7f2mf) ([raw file](https://github.com/starkware-libs/stwo/blob/818e76658b640976ab8c604cd7c62f4498e62a96/crates/prover/src/core/air/components.rs#L35)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Nit
</blockquote></details>

done

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/869)* status: 0 of 13 files reviewed, 4 unresolved discussions (waiting on @andrewmilson, @ohad-starkware, and @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/component.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/stwo/869#-OAxRIno4zLQcDSlOjnM:-OB5RXDv8M4Ju-XpR90E:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/818e76658b640976ab8c604cd7c62f4498e62a96/crates/prover/src/constraint_framework/component.rs#L71)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

WDYT?
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/869)* status: 0 of 13 files reviewed, 4 unresolved discussions (waiting on @andrewmilson, @ohad-starkware, and @shaharsamocha7)

___
*[`crates/prover/src/examples/wide_fibonacci/mod.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/stwo/869#-OAzE_P6BUFtARCXvh9M:-OB5RjG2Be7WA_KkIXPe:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/818e76658b640976ab8c604cd7c62f4498e62a96/crates/prover/src/examples/wide_fibonacci/mod.rs#L35)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Remove?
</blockquote></details>

Done.

**Review by andrewmilson — APPROVED** [review]
:lgtm: with comment

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/869#-:-OB60h9b7YM381GrF09a:b10c0l0)* status: 0 of 13 files reviewed, 6 unresolved discussions (waiting on @ilyalesokhin-starkware, @ohad-starkware, and @shaharsamocha7)

___
*[`crates/prover/src/core/air/components.rs` line 37 at r3](https://reviewable.io/reviews/starkware-libs/stwo/869#-OB60Lku3Bd9tyqDZNfM:-OB60Lku3Bd9tyqDZNfN:b-7zi8ni) ([raw file](https://github.com/starkware-libs/stwo/blob/8c9f70651400a595f82898ba09fe6d07cad9aee5/crates/prover/src/core/air/components.rs#L37)):*
> ```XML
>         for component in &self.0 {
>             for idx in component.preproccessed_column_indices() {
>                 preprocessed_mask_points[idx].resize(1, point);
> ```

WDYT?



_Suggestion:_
```XML
preprocessed_mask_points[idx] = vec![point];
```
___
*[`crates/prover/src/core/prover/mod.rs` line 110 at r3](https://reviewable.io/reviews/starkware-libs/stwo/869#-OB60Wj_1kpcFx_VBAqp:-OB60Wj_1kpcFx_VBAqq:b-unp4j8) ([raw file](https://github.com/starkware-libs/stwo/blob/8c9f70651400a595f82898ba09fe6d07cad9aee5/crates/prover/src/core/prover/mod.rs#L110)):*
> ```XML
>     let oods_point = CirclePoint::<SecureField>::get_random_point(channel);
> 
>     eprintln!(
> ```

Is this eprintln (and the others) also for debugging?

**Review by shaharsamocha7 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/869)* status: 0 of 13 files reviewed, 8 unresolved discussions (waiting on @andrewmilson, @ilyalesokhin-starkware, and @ohad-starkware)

___
*[`crates/prover/src/constraint_framework/component.rs` line 141 at r3](https://reviewable.io/reviews/starkware-libs/stwo/869#-OB5p_iy8WAbA_KgQjwO:-OB5p_j-3PI-VezX3mfA:b-14e332) ([raw file](https://github.com/starkware-libs/stwo/blob/8c9f70651400a595f82898ba09fe6d07cad9aee5/crates/prover/src/constraint_framework/component.rs#L141)):*
> ```XML
>             .map(|tree_offsets| vec![self.eval.log_size(); tree_offsets.len()]);
> 
>         log_degree_bounds[0] = self
> ```

mask_offset [0] is empty vec before adding the preprocessed columns?
maybe we should put a dbg_assert?



_Code quote:_
```XML
log_degree_bounds[0] = self
```
___
*[`crates/prover/src/core/prover/mod.rs` line 117 at r3](https://reviewable.io/reviews/starkware-libs/stwo/869#-OB5qJRy9uxZIUo9a3ht:-OB5qJRz9rhbP2zqo-LF:b-p523sg) ([raw file](https://github.com/starkware-libs/stwo/blob/8c9f70651400a595f82898ba09fe6d07cad9aee5/crates/prover/src/core/prover/mod.rs#L117)):*
> ```XML
>             .column_log_sizes
>             .len()
>     );
> ```

Remove (or change to dbg!)



_Code quote:_
```XML
    eprintln!(
        "commitment_scheme.trees[PREPROCESSED_TRACE_IDX]
            .column_log_sizes
            .len()={}",
        commitment_scheme.trees[PREPROCESSED_TRACE_IDX]
            .column_log_sizes
            .len()
    );
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/prover/src/constraint_framework/component.rs` line 141 at r3](https://reviewable.io/reviews/starkware-libs/stwo/869#-OB5p_iy8WAbA_KgQjwO:-OBK79nwEATnYM1-PSLk:b2nign6) ([raw file](https://github.com/starkware-libs/stwo/blob/8c9f70651400a595f82898ba09fe6d07cad9aee5/crates/prover/src/constraint_framework/component.rs#L141)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

mask_offset [0] is empty vec before adding the preprocessed columns?
maybe we should put a dbg_assert?
</blockquote></details>

yes

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/prover/src/constraint_framework/component.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/stwo/869#-OAxRIno4zLQcDSlOjnM:-OBK7ESOCtAz0BCmuaNW:bb7f2mf) ([raw file](https://github.com/starkware-libs/stwo/blob/818e76658b640976ab8c604cd7c62f4498e62a96/crates/prover/src/constraint_framework/component.rs#L71)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

done

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/prover/src/core/air/components.rs` line 37 at r3](https://reviewable.io/reviews/starkware-libs/stwo/869#-OB60Lku3Bd9tyqDZNfM:-OBK7Oh1EG4jIN22cHsp:byt9gg) ([raw file](https://github.com/starkware-libs/stwo/blob/8c9f70651400a595f82898ba09fe6d07cad9aee5/crates/prover/src/core/air/components.rs#L37)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

WDYT?
</blockquote></details>

I think it is slightly less efficient, but I don't mind if you think it is better.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/869)* status: 0 of 13 files reviewed, 8 unresolved discussions (waiting on @Alon-Ti, @andrewmilson, @ohad-starkware, and @shaharsamocha7)

___
*[`crates/prover/src/core/prover/mod.rs` line 110 at r3](https://reviewable.io/reviews/starkware-libs/stwo/869#-OB60Wj_1kpcFx_VBAqp:-OBK7UlREkc0e_3yKtGf:b-hfpv0l) ([raw file](https://github.com/starkware-libs/stwo/blob/8c9f70651400a595f82898ba09fe6d07cad9aee5/crates/prover/src/core/prover/mod.rs#L110)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Is this eprintln (and the others) also for debugging?
</blockquote></details>

removed
___
*[`crates/prover/src/core/prover/mod.rs` line 117 at r3](https://reviewable.io/reviews/starkware-libs/stwo/869#-OB5qJRy9uxZIUo9a3ht:-OBK7Vwk7xMfnfp6JPeO:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/8c9f70651400a595f82898ba09fe6d07cad9aee5/crates/prover/src/core/prover/mod.rs#L117)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Remove (or change to dbg!)
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/869)* status: 0 of 13 files reviewed, 6 unresolved discussions (waiting on @Alon-Ti, @andrewmilson, and @ohad-starkware)

___
*[`crates/prover/src/examples/blake/air.rs` line 93 at r6](https://reviewable.io/reviews/starkware-libs/stwo/869#-OBLdRz6D4ylJhwOwy3x:-OBLdRz729VNkcXSbGXz:b-6erkjv) ([raw file](https://github.com/starkware-libs/stwo/blob/b36d75f09347977062a1eb077db6c11069996980/crates/prover/src/examples/blake/air.rs#L93)):*
> ```XML
>             }),
>         )
>         .collect_vec();
> ```

I'm not sure this is the right place to put it.



_Code quote:_
```XML
        log_sizes[PREPROCESSED_TRACE_IDX] = chain!(
            [log_size],
            ROUND_LOG_SPLIT.iter().map(|l| log_size + l),
            PREPROCESSED_XOR_COLUMNS.map(|column| match column {
                PreprocessedColumn::XorTable(elem_bits, expand_bits, _) =>
                    2 * (elem_bits - expand_bits),
                PreprocessedColumn::IsFirst(log_size) => log_size,
                _ => panic!("Unexpected column"),
            }),
        )
        .collect_vec();
```

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/869)* status: 0 of 13 files reviewed, 9 unresolved discussions (waiting on @Alon-Ti, @ilyalesokhin-starkware, and @ohad-starkware)

___
*[`crates/prover/src/core/air/components.rs` line 37 at r3](https://reviewable.io/reviews/starkware-libs/stwo/869#-OB60Lku3Bd9tyqDZNfM:-OBLg81vCGnFKfATPw8a:b7pdzsu) ([raw file](https://github.com/starkware-libs/stwo/blob/8c9f70651400a595f82898ba09fe6d07cad9aee5/crates/prover/src/core/air/components.rs#L37)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I think it is slightly less efficient, but I don't mind if you think it is better.
</blockquote></details>

Agree I just thought it was more readable. This function isn't performance critical.
___
*[`crates/prover/src/examples/blake/air.rs` line 93 at r6](https://reviewable.io/reviews/starkware-libs/stwo/869#-OBLdRz6D4ylJhwOwy3x:-OBLlX0P8R8x49Nmt9Ym:b-aetl4i) ([raw file](https://github.com/starkware-libs/stwo/blob/b36d75f09347977062a1eb077db6c11069996980/crates/prover/src/examples/blake/air.rs#L93)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I'm not sure this is the right place to put it.
</blockquote></details>

Seems ok to me for now.
Was there somewhere you wanted to put it?
___
*[`crates/prover/src/examples/blake/air.rs` line 85 at r6](https://reviewable.io/reviews/starkware-libs/stwo/869#-OBLlRNX6O_OD3dHGrFm:-OBLlRNY92y2jaB7Yn9z:bd7h0eh) ([raw file](https://github.com/starkware-libs/stwo/blob/b36d75f09347977062a1eb077db6c11069996980/crates/prover/src/examples/blake/air.rs#L85)):*
> ```XML
>         log_sizes[PREPROCESSED_TRACE_IDX] = chain!(
>             [log_size],
>             ROUND_LOG_SPLIT.iter().map(|l| log_size + l),
> ```

What are these first two for? Can it be documented plz?



_Code quote:_
```XML
            [log_size],
            ROUND_LOG_SPLIT.iter().map(|l| log_size + l),
```
___
*[`crates/prover/src/core/air/components.rs` line 68 at r6](https://reviewable.io/reviews/starkware-libs/stwo/869#-OBLiQ8f7y6eRo1xexDi:-OBLiQ8f7y6eRo1xexDj:bevo96a) ([raw file](https://github.com/starkware-libs/stwo/blob/b36d75f09347977062a1eb077db6c11069996980/crates/prover/src/core/air/components.rs#L68)):*
> ```XML
>     pub fn column_log_sizes(&self) -> TreeVec<ColumnVec<u32>> {
>         let mut preprocessed_columns = vec![0; self.n_preprocessed_columns];
>         let mut updated_columns = vec![false; self.n_preprocessed_columns];
> ```

Optional: could just do one storing Option.



_Code quote:_
```XML
        let mut preprocessed_columns = vec![0; self.n_preprocessed_columns];
        let mut updated_columns = vec![false; self.n_preprocessed_columns];
```
___
*[`crates/prover/src/core/air/components.rs` line 77 at r6](https://reviewable.io/reviews/starkware-libs/stwo/869#-OBLihlv0UMr3hPzUdml:-OBLihlv0UMr3hPzUdmm:b1ko67o) ([raw file](https://github.com/starkware-libs/stwo/blob/b36d75f09347977062a1eb077db6c11069996980/crates/prover/src/core/air/components.rs#L77)):*
> ```XML
>                 .into_iter()
>                 .zip(std::mem::take(&mut component_trace_log_sizes[0]))
>             {
> ```

This isn't performance critical. WDYT?
I think offset should be renamed to index because column offset I usually associate with a column's mask offset.



_Suggestion:_
```XML
            let mut preprocessed_trace_log_sizes = &component.trace_log_degree_bounds()[0];

            for (i, &log_size) in zip(component.preproccessed_column_indices(), preprocessed_trace_log_sizes) {
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/prover/src/examples/blake/air.rs` line 93 at r6](https://reviewable.io/reviews/starkware-libs/stwo/869#-OBLdRz6D4ylJhwOwy3x:-OBLnDywAew6SSIYQRCc:bgt2pmp) ([raw file](https://github.com/starkware-libs/stwo/blob/b36d75f09347977062a1eb077db6c11069996980/crates/prover/src/examples/blake/air.rs#L93)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Seems ok to me for now.
Was there somewhere you wanted to put it?
</blockquote></details>

maybe in verify\_blake? as the verifier is supposed to know the structure of the preproccess trace.

The problem is that I do want the assert here:
https://github.com/starkware-industries/stwo/blob/b36d75f09347977062a1eb077db6c11069996980/crates/prover/src/examples/blake/air.rs#L439

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/prover/src/core/air/components.rs` line 77 at r6](https://reviewable.io/reviews/starkware-libs/stwo/869#-OBLihlv0UMr3hPzUdml:-OBPrEmZ6ZebLDL7ooC7:b-iuepq6) ([raw file](https://github.com/starkware-libs/stwo/blob/b36d75f09347977062a1eb077db6c11069996980/crates/prover/src/core/air/components.rs#L77)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

This isn't performance critical. WDYT?
I think offset should be renamed to index because column offset I usually associate with a column's mask offset.
</blockquote></details>

I return component_trace_log_sizes at the end of the map.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/869)* status: 0 of 13 files reviewed, 9 unresolved discussions (waiting on @Alon-Ti, @andrewmilson, and @ohad-starkware)

___
*[`crates/prover/src/core/air/components.rs` line 37 at r3](https://reviewable.io/reviews/starkware-libs/stwo/869#-OB60Lku3Bd9tyqDZNfM:-OBPvM0fBFb_BuiCqaur:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/8c9f70651400a595f82898ba09fe6d07cad9aee5/crates/prover/src/core/air/components.rs#L37)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Agree I just thought it was more readable. This function isn't performance critical.
</blockquote></details>

Done.
___
*[`crates/prover/src/examples/blake/air.rs` line 85 at r6](https://reviewable.io/reviews/starkware-libs/stwo/869#-OBLlRNX6O_OD3dHGrFm:-OBPuhse4unHcq8C-ImS:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/b36d75f09347977062a1eb077db6c11069996980/crates/prover/src/examples/blake/air.rs#L85)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

What are these first two for? Can it be documented plz?
</blockquote></details>

Done.

**Review by andrewmilson — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/869#-:-OBQOM7w9G_hFlWGdKQf:bnfp4nl)* status: 0 of 13 files reviewed, 9 unresolved discussions (waiting on @Alon-Ti and @ohad-starkware)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/prover/src/constraint_framework/component.rs` line 134 at r8](https://reviewable.io/reviews/starkware-libs/stwo/869#-OBQOfZ59_INvDKE6ahu:-OBQOfZ59_INvDKE6ahv:b-qtbvzf) ([raw file](https://github.com/starkware-libs/stwo/blob/1cf64d0397f933ac9ded0b2fa26a31b60a074d1f/crates/prover/src/constraint_framework/component.rs#L134)):*
> ```XML
>                         );
>                         next_column
>                     })
> ```

Note that this removes duplicated columns.



_Code quote:_
```XML
                    .entry(*col)
                    .or_insert({
                        assert_matches!(
                            location_allocator.preprocessed_columns_allocation_mode,
                            PreprocessedColumnsAllocationMode::Dynamic,
                        );
                        next_column
                    })
```

**Pull request merged**
