### PR TITLE
Fix previous_bit_reversed_circle_domain_index.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/709)

### CODE REVIEW

**Comment by alonh5** [comment]
* **#709** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/709?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — APPROVED** [review]
:lgtm:
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/709#-:-O1BpqMx18E0hfXmH5f6:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/709)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/prover/src/core/utils.rs` line 204 at r1](https://reviewable.io/reviews/starkware-libs/stwo/709#-O1GPT8j-akAkN0wax-8:-O1GPT8j-akAkN0wax-9:bi6oz47) ([raw file](https://github.com/starkware-libs/stwo/blob/af41be959e70201c256186522296f13f2c8f4394/crates/prover/src/core/utils.rs#L204)):*
> ```XML
> 
>     #[test]
>     fn test_previous_bit_reversed_circle_domain_index() {
> ```

Fix test to use eval_log_size > domain_log_size - 1
so we can see that this fix worked



_Code quote:_
```XML
    #[test]
    fn test_previous_bit_reversed_circle_domain_index() {
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/709)* status: all files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`crates/prover/src/core/utils.rs` line 204 at r1](https://reviewable.io/reviews/starkware-libs/stwo/709#-O1GPT8j-akAkN0wax-8:-O1GQMD77Gu9hEWLZtVV:b-il2kqu) ([raw file](https://github.com/starkware-libs/stwo/blob/af41be959e70201c256186522296f13f2c8f4394/crates/prover/src/core/utils.rs#L204)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Fix test to use eval_log_size > domain_log_size - 1
so we can see that this fix worked
</blockquote></details>

I did, that's the addition at the end of the test.

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/709)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/core/utils.rs` line 204 at r1](https://reviewable.io/reviews/starkware-libs/stwo/709#-O1GPT8j-akAkN0wax-8:-O1GqyWd5t-O1XmGKPF5:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/af41be959e70201c256186522296f13f2c8f4394/crates/prover/src/core/utils.rs#L204)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I did, that's the addition at the end of the test.
</blockquote></details>

Done.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/709#-:-O1GrVOz1-bzcwv9VWdl:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Pull request merged**
