### PR TITLE
Precompute complex conjugate line constants.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/546)

### CODE REVIEW

**Comment by alonh5** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/546?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#547** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/547?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#546** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/546?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#545** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/545?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#544** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/544?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/546)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5)

___
*[`src/core/backend/cpu/quotients.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/stwo/546#-Ntzq8IZCQ7Cjtx5H9hW:-Ntzq8IZCQ7Cjtx5H9hX:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/78c5fda7c60e6b7b19199e6b5996e0ed6e24d09d/src/core/backend/cpu/quotients.rs#L90)):*
> ```XML
>                 .iter()
>                 .enumerate()
>                 .map(|(i, (_, sampled_value))| {
> ```





_Suggestion:_
```XML
column_index
```
___
*[`src/core/backend/cpu/quotients.rs` line 95 at r1](https://reviewable.io/reviews/starkware-libs/stwo/546#-NtzqdO9C1MdklKtMt2c:-NtzqdO9C1MdklKtMt2d:byjx9m5) ([raw file](https://github.com/starkware-libs/stwo/blob/78c5fda7c60e6b7b19199e6b5996e0ed6e24d09d/src/core/backend/cpu/quotients.rs#L95)):*
> ```XML
>                         value: *sampled_value,
>                     };
>                     complex_conjugate_line_constants(&sample, random_coeff.pow(i as u128))
> ```

don't compute all the powers. Since you are already going in order, just update the current alpha each iteration



_Code quote:_
```XML
random_coeff.pow(i as u128)
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/546)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`src/core/backend/cpu/quotients.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/stwo/546#-Ntzq8IZCQ7Cjtx5H9hW:-Nu-2uPA9QTO6SR-i-qd:bss4a2b) ([raw file](https://github.com/starkware-libs/stwo/blob/78c5fda7c60e6b7b19199e6b5996e0ed6e24d09d/src/core/backend/cpu/quotients.rs#L90)):*
> ```XML
>                 .iter()
>                 .enumerate()
>                 .map(|(i, (_, sampled_value))| {
> ```

Removed.
___
*[`src/core/backend/cpu/quotients.rs` line 95 at r1](https://reviewable.io/reviews/starkware-libs/stwo/546#-NtzqdO9C1MdklKtMt2c:-Nu-4aKx1Oz9ZcGzCjbP:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/78c5fda7c60e6b7b19199e6b5996e0ed6e24d09d/src/core/backend/cpu/quotients.rs#L95)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

don't compute all the powers. Since you are already going in order, just update the current alpha each iteration
</blockquote></details>

Done.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/546#-:-Nu-GWP556h1yHg4Jcwm:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Comment by alonh5** [comment]
### Merge activity

* **Mar 27, 10:46 AM EDT**: @alonh5 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/546).

**Pull request merged**
