### PR TITLE
Tests for poseidon2

### PR DESCRIPTION
**Pull request by shaharsamocha7**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/688)

### CODE REVIEW

**Comment by shaharsamocha7** [comment]
* **#688** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/688?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @shaharsamocha7 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/688)* status: all files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/prover/src/examples/poseidon/mod.rs` line 144 at r1](https://reviewable.io/reviews/starkware-libs/stwo/688#-O0d6tEz2Bm58UJ30C0x:-O0d6tF-8TwDQqeqcvoE:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/39f360a90436b648be8c9d09d13775bef14ae7d6/crates/prover/src/examples/poseidon/mod.rs#L144)):*
> ```XML
> 
> #[inline(always)]
> // Applies the M4 MDS matrix described in https://eprint.iacr.org/2023/323.pdf 5.1.
> ```





_Suggestion:_
```XML
/// Applies the M4 MDS matrix described in <https://eprint.iacr.org/2023/323.pdf> 5.1.
```
___
*[`crates/prover/src/examples/poseidon/mod.rs` line 163 at r1](https://reviewable.io/reviews/starkware-libs/stwo/688#-O0d6wYJDN8nOajCarRZ:-O0d6wYJDN8nOajCarR_:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/39f360a90436b648be8c9d09d13775bef14ae7d6/crates/prover/src/examples/poseidon/mod.rs#L163)):*
> ```XML
> 
> // Applies the external round matrix.
> // See https://eprint.iacr.org/2023/323.pdf 5.1 and Appendix B.
> ```





_Suggestion:_
```XML
/// Applies the external round matrix.
/// See <https://eprint.iacr.org/2023/323.pdf> 5.1 and Appendix B.
```
___
*[`crates/prover/src/examples/poseidon/mod.rs` line 526 at r1](https://reviewable.io/reviews/starkware-libs/stwo/688#-O0d74O80dkuwcj691uw:-O0d74O80dkuwcj691ux:ban0eub) ([raw file](https://github.com/starkware-libs/stwo/blob/39f360a90436b648be8c9d09d13775bef14ae7d6/crates/prover/src/examples/poseidon/mod.rs#L526)):*
> ```XML
>         //   -C target-cpu=native -C target-feature=+avx512f -C opt-level=3" cargo test
>         //   test_simd_poseidon_prove -- --nocapture
>         const LOG_N_ROWS: u32 = 8;
> ```

Add a comment that explains that the number of instances is 2**LOG_N_ROWS*N_REPS

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/688)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/examples/poseidon/mod.rs` line 144 at r1](https://reviewable.io/reviews/starkware-libs/stwo/688#-O0d6tEz2Bm58UJ30C0x:-O0dFLTr9Zfa_E761iMg:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/39f360a90436b648be8c9d09d13775bef14ae7d6/crates/prover/src/examples/poseidon/mod.rs#L144)):*
> ```XML
> 
> #[inline(always)]
> // Applies the M4 MDS matrix described in https://eprint.iacr.org/2023/323.pdf 5.1.
> ```

Done.
___
*[`crates/prover/src/examples/poseidon/mod.rs` line 163 at r1](https://reviewable.io/reviews/starkware-libs/stwo/688#-O0d6wYJDN8nOajCarRZ:-O0dFNXhAgAMrK_xR27e:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/39f360a90436b648be8c9d09d13775bef14ae7d6/crates/prover/src/examples/poseidon/mod.rs#L163)):*
> ```XML
> 
> // Applies the external round matrix.
> // See https://eprint.iacr.org/2023/323.pdf 5.1 and Appendix B.
> ```

Done.
___
*[`crates/prover/src/examples/poseidon/mod.rs` line 526 at r1](https://reviewable.io/reviews/starkware-libs/stwo/688#-O0d74O80dkuwcj691uw:-O0dG-Hj8pkHRQyQf74p:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/39f360a90436b648be8c9d09d13775bef14ae7d6/crates/prover/src/examples/poseidon/mod.rs#L526)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Add a comment that explains that the number of instances is 2**LOG_N_ROWS*N_REPS
</blockquote></details>

Done.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/688#-:-O0dT3rs6rAVfvbjMuir:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @shaharsamocha7)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/688#-:-O0dTDRN6LdjseKL9mgb:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @shaharsamocha7)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/688#-:-O0dU1od9vUbQ0UbVuj_:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Pull request merged**
