### PR TITLE
Incorporate fft in AVX backend

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/394)

### CODE REVIEW

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/394)* status: all files reviewed, 4 unresolved discussions (waiting on @spapinistarkware)

___
*[`src/core/backend/avx512/circle.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/stwo/394#-NsJY4Lp2rVEupGab2H-:-NsJY4Lp2rVEupGab2H0:by56wmc) ([raw file](https://github.com/starkware-libs/stwo/blob/da83eabf6cc2642ca279c7fd1435ffd45106a9ef/src/core/backend/avx512/circle.rs#L30)):*
> ```XML
>         AVX512Backend::bit_reverse_column(&mut values);
>         // TODO(spapini): Handle small cases.
>         let log_size = values.length.ilog2();
> ```

Move to the beginning of the function

I guess that if this is too small then we can just do trivial interpolation without twiddles or anything



_Code quote:_
```XML
        // TODO(spapini): Handle small cases.
        let log_size = values.length.ilog2();
```
___
*[`src/core/backend/avx512/circle.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/stwo/394#-NsJXcmZEnfWHEdmSVww:-NsJXcmZEnfWHEdmSVwx:b-bvkm03) ([raw file](https://github.com/starkware-libs/stwo/blob/da83eabf6cc2642ca279c7fd1435ffd45106a9ef/src/core/backend/avx512/circle.rs#L38)):*
> ```XML
>                 log_size as usize,
>             );
>         }
> ```

Should this be implemented also for AVX512?



_Code quote:_
```XML
        unsafe {
            ifft::ifft(
                std::mem::transmute(values.data.as_mut_ptr()),
                &twiddles[1..],
                log_size as usize,
            );
        }
```
___
*[`src/core/backend/avx512/circle.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/stwo/394#-NsJYU_U7sacQLiWQxl9:-NsJYU_U7sacQLiWQxlA:b-v0duql) ([raw file](https://github.com/starkware-libs/stwo/blob/da83eabf6cc2642ca279c7fd1435ffd45106a9ef/src/core/backend/avx512/circle.rs#L54)):*
> ```XML
>         _point: crate::core::circle::CirclePoint<E>,
>     ) -> E {
>         todo!()
> ```

Why did you change it?



_Code quote:_
```XML
    fn eval_at_point<E: crate::core::fields::ExtensionOf<BaseField>>(
        _poly: &CirclePoly<Self, BaseField>,
        _point: crate::core::circle::CirclePoint<E>,
    ) -> E {
        todo!()
```
___
*[`src/core/backend/avx512/circle.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/stwo/394#-NsJZTiFBjdl0vAMhLLO:-NsJZTiG-uf5JIUfNToe:b-bnfkzh) ([raw file](https://github.com/starkware-libs/stwo/blob/da83eabf6cc2642ca279c7fd1435ffd45106a9ef/src/core/backend/avx512/circle.rs#L64)):*
> ```XML
> 
>         // TODO(spapini): Precompute twiddles.
>         let twiddles = rfft::get_twiddle_dbls(domain);
> ```

Why this file is called `rfft`? (and not `fft`?)



_Code quote:_
```XML
rfft
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/394)* status: all files reviewed, 4 unresolved discussions (waiting on @shaharsamocha7)

___
*[`src/core/backend/avx512/circle.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/stwo/394#-NsJXcmZEnfWHEdmSVww:-NsJiYGEDew6lR2JMnK7:b406bol) ([raw file](https://github.com/starkware-libs/stwo/blob/da83eabf6cc2642ca279c7fd1435ffd45106a9ef/src/core/backend/avx512/circle.rs#L38)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Should this be implemented also for AVX512?
</blockquote></details>

This is the avx512 impl
___
*[`src/core/backend/avx512/circle.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/stwo/394#-NsJYU_U7sacQLiWQxl9:-NsJiPqZ7AwIJFHGcO96:bh2t4y7) ([raw file](https://github.com/starkware-libs/stwo/blob/da83eabf6cc2642ca279c7fd1435ffd45106a9ef/src/core/backend/avx512/circle.rs#L54)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why did you change it?
</blockquote></details>

It does not bring the right results now. Next few PRs fix this.
The orde of the coefficients is different with the new fft impl.
___
*[`src/core/backend/avx512/circle.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/stwo/394#-NsJZTiFBjdl0vAMhLLO:-NsJiisq3pKcPLBdJDn8:b-h4ggiy) ([raw file](https://github.com/starkware-libs/stwo/blob/da83eabf6cc2642ca279c7fd1435ffd45106a9ef/src/core/backend/avx512/circle.rs#L64)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why this file is called `rfft`? (and not `fft`?)
</blockquote></details>

Because rust doesn;t let me have fft module inside fft module.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/394)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @shaharsamocha7)

___
*[`src/core/backend/avx512/circle.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/stwo/394#-NsJY4Lp2rVEupGab2H-:-NsJjCA35RiAZLGhbjut:b-jg1lps) ([raw file](https://github.com/starkware-libs/stwo/blob/da83eabf6cc2642ca279c7fd1435ffd45106a9ef/src/core/backend/avx512/circle.rs#L30)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Move to the beginning of the function

I guess that if this is too small then we can just do trivial interpolation without twiddles or anything
</blockquote></details>

Done.

Yes, I'm adding this in the next few PRs.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/394#-:-NsJpFDcDLBFY3YrYrPO:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`src/core/backend/avx512/circle.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/stwo/394#-NsJXcmZEnfWHEdmSVww:-NsJoyOG-g7xl7OKrwgS:bwlfk6u) ([raw file](https://github.com/starkware-libs/stwo/blob/da83eabf6cc2642ca279c7fd1435ffd45106a9ef/src/core/backend/avx512/circle.rs#L38)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

This is the avx512 impl
</blockquote></details>

My bad
___
*[`src/core/backend/avx512/circle.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/stwo/394#-NsJZTiFBjdl0vAMhLLO:-NsJp7GkAxuB2C0ojGyf:bpnqbou) ([raw file](https://github.com/starkware-libs/stwo/blob/da83eabf6cc2642ca279c7fd1435ffd45106a9ef/src/core/backend/avx512/circle.rs#L64)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Because rust doesn;t let me have fft module inside fft module.
</blockquote></details>

so what rfft stands for?
maybe we should change the dir name to NTT?

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/394)* status: all files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`src/core/backend/avx512/circle.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/stwo/394#-NsJZTiFBjdl0vAMhLLO:-NsK9mii5knOITGDtQGn:b-cwsn77) ([raw file](https://github.com/starkware-libs/stwo/blob/da83eabf6cc2642ca279c7fd1435ffd45106a9ef/src/core/backend/avx512/circle.rs#L64)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

so what rfft stands for?
maybe we should change the dir name to NTT?
</blockquote></details>

regular. it says so at the top of the module.
I can change it in another PR. Let's discuss a good name tomorrow:)

**Pull request merged**
