### PR TITLE
Parallel fft

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/819)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
* **#820** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/820?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#819** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/819?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by spapinistarkware** [comment]
* **#820** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/820?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#819** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/819?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by andrewmilson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/819)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @Alon-Ti, @shaharsamocha7, and @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/fft/ifft.rs` line 157 at r1](https://reviewable.io/reviews/starkware-libs/stwo/819#-O60IpFl6aSKjE-ttC8_:-O60IpFl6aSKjE-ttC8a:b-d4p0oa) ([raw file](https://github.com/starkware-libs/stwo/blob/2a4fec2c1c6f7e88a6fbb8164521a38ad8bd433c/crates/prover/src/core/backend/simd/fft/ifft.rs#L157)):*
> ```XML
> 
>     let values = UnsafeMutI32(values);
>     iter.for_each(|index_h| {
> ```

Since this is so common might be worth creating macros for them like in https://github.com/arkworks-rs/std/blob/master/src/lib.rs.



_Suggestion:_
```XML
    iter!(0..1 << (log_size - fft_layers - LOG_N_LANES as usize)).for_each(|index_h| {
```
___
*[`crates/prover/src/core/backend/simd/fft/mod.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/stwo/819#-O60Ja0iBewFbzvLFN1H:-O60Ja0iBewFbzvLFN1I:b-jpyix9) ([raw file](https://github.com/starkware-libs/stwo/blob/2a4fec2c1c6f7e88a6fbb8164521a38ad8bd433c/crates/prover/src/core/backend/simd/fft/mod.rs#L16)):*
> ```XML
> pub const MIN_FFT_LOG_SIZE: u32 = 5;
> 
> pub struct UnsafeMutI32(pub *mut u32);
> ```

I'm a little worried the quantity of unsafe code is getting out of hand in the SimdBackend and that there are as performant safe ways of doing the implementation. Haven't benchmarked with "safe" changes yet though just concerned these changes add more unsafe implementation

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/819)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @Alon-Ti, @andrewmilson, @shaharsamocha7, and @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/fft/ifft.rs` line 157 at r1](https://reviewable.io/reviews/starkware-libs/stwo/819#-O60IpFl6aSKjE-ttC8_:-O74TWIV9gy5pb5tEEPJ:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/2a4fec2c1c6f7e88a6fbb8164521a38ad8bd433c/crates/prover/src/core/backend/simd/fft/ifft.rs#L157)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Since this is so common might be worth creating macros for them like in https://github.com/arkworks-rs/std/blob/master/src/lib.rs.
</blockquote></details>

Done.

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/819)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @Alon-Ti, @andrewmilson, and @shaharsamocha7)

___
*[`crates/prover/src/core/backend/simd/fft/mod.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/stwo/819#-O60Ja0iBewFbzvLFN1H:-O74UK1wDJ523zT9K2WC:bdx9w6o) ([raw file](https://github.com/starkware-libs/stwo/blob/2a4fec2c1c6f7e88a6fbb8164521a38ad8bd433c/crates/prover/src/core/backend/simd/fft/mod.rs#L16)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

I'm a little worried the quantity of unsafe code is getting out of hand in the SimdBackend and that there are as performant safe ways of doing the implementation. Haven't benchmarked with "safe" changes yet though just concerned these changes add more unsafe implementation
</blockquote></details>

I see the unsafe usage in this PR isn't new, just using old unsafe functions. Do you want to re-exmine those?

**Review by andrewmilson — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/819)* status: 1 of 5 files reviewed, 7 unresolved discussions (waiting on @Alon-Ti, @alonh5, @shaharsamocha7, and @spapinistarkware)

___
*[`crates/prover/src/core/mod.rs` line 65 at r2](https://reviewable.io/reviews/starkware-libs/stwo/819#-O78S7o58pqXFgQykI1v:-O78S7o58pqXFgQykI1w:b45h) ([raw file](https://github.com/starkware-libs/stwo/blob/b3b9ee02927d0a5af504aae6f1d50af29ce467db/crates/prover/src/core/mod.rs#L65)):*
> ```XML
>     ($i: expr) => {{
>         #[cfg(not(feature = "parallel"))]
>         let iter = $i;
> ```





_Suggestion:_
```XML
let iter = $i.into_iter();
```
___
*[`crates/prover/src/core/backend/simd/blake2s.rs` line 57 at r2](https://reviewable.io/reviews/starkware-libs/stwo/819#-O78UHjFEq8LfCyxFKre:-O78UHjFEq8LfCyxFKrf:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/b3b9ee02927d0a5af504aae6f1d50af29ce467db/crates/prover/src/core/backend/simd/blake2s.rs#L57)):*
> ```XML
>             let iter = parallel_iter!(0..1 << log_size);
> 
>             return iter
> ```





_Suggestion:_
```XML
        return parallel_iter!(0..1 << log_size)
```
___
*[`crates/prover/src/core/backend/simd/fft/ifft.rs` line 157 at r1](https://reviewable.io/reviews/starkware-libs/stwo/819#-O60IpFl6aSKjE-ttC8_:-O78TU6SC9Wieg1ljZTs:bs5dd8o) ([raw file](https://github.com/starkware-libs/stwo/blob/2a4fec2c1c6f7e88a6fbb8164521a38ad8bd433c/crates/prover/src/core/backend/simd/fft/ifft.rs#L157)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Allg since it's already been added but forgot to mention that I really like the way plonky3 handles this kind of functionality with their  
https://github.com/Plonky3/Plonky3/tree/main/maybe-rayon crate. I think it actually has some benefits over the macro approach. For instance don't have to conditionally compile any preludes. Also cleaner syntax IMO.
___
*[`crates/prover/src/core/backend/simd/fft/ifft.rs` line 92 at r2](https://reviewable.io/reviews/starkware-libs/stwo/819#-O78TJmq3q9VwtN0_9Mf:-O78TJmq3q9VwtN0_9Mg:bb70wkm) ([raw file](https://github.com/starkware-libs/stwo/blob/b3b9ee02927d0a5af504aae6f1d50af29ce467db/crates/prover/src/core/backend/simd/fft/ifft.rs#L92)):*
> ```XML
> 
>     let values = UnsafeMutI32(values);
>     iter.for_each(|index_h| {
> ```

Nit:



_Suggestion:_
```XML
    let values = UnsafeMutI32(values);
    parallel_iter!(0..1 << (log_size - fft_layers)).for_each(|index_h| {
```
___
*[`crates/prover/src/core/backend/simd/fft/mod.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/stwo/819#-O60Ja0iBewFbzvLFN1H:-O78TbeFEWqK4CM21gYO:b-2hfrhg) ([raw file](https://github.com/starkware-libs/stwo/blob/2a4fec2c1c6f7e88a6fbb8164521a38ad8bd433c/crates/prover/src/core/backend/simd/fft/mod.rs#L16)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I see the unsafe usage in this PR isn't new, just using old unsafe functions. Do you want to re-exmine those?
</blockquote></details>

Yeah, maybe you can add this todo for me plz
```
// TODO(andrew): Examine usage of unsafe in SIMD FFT.
```
___
*[`crates/prover/src/core/backend/simd/fft/rfft.rs` line 97 at r2](https://reviewable.io/reviews/starkware-libs/stwo/819#-O78Tyqi3AlymNp2KNCO:-O78Tyqi3AlymNp2KNCP:buo9nmt) ([raw file](https://github.com/starkware-libs/stwo/blob/b3b9ee02927d0a5af504aae6f1d50af29ce467db/crates/prover/src/core/backend/simd/fft/rfft.rs#L97)):*
> ```XML
>     let src = UnsafeConstI32(src);
>     let dst = UnsafeMutI32(dst);
>     iter.for_each(|index_h| {
> ```

Same here



_Code quote:_
```XML
    let iter = parallel_iter!(0..1 << (log_size - fft_layers));

    let src = UnsafeConstI32(src);
    let dst = UnsafeMutI32(dst);
    iter.for_each(|index_h| {
```
___
*[`crates/prover/src/core/backend/simd/fft/rfft.rs` line 163 at r2](https://reviewable.io/reviews/starkware-libs/stwo/819#-O78U-znB7BcpRaAjB4n:-O78U-znB7BcpRaAjB4o:buo9nmt) ([raw file](https://github.com/starkware-libs/stwo/blob/b3b9ee02927d0a5af504aae6f1d50af29ce467db/crates/prover/src/core/backend/simd/fft/rfft.rs#L163)):*
> ```XML
>     let src = UnsafeConstI32(src);
>     let dst = UnsafeMutI32(dst);
>     iter.for_each(|index_h| {
> ```

Same here



_Code quote:_
```XML
    let iter = parallel_iter!(0..1 << (log_size - fft_layers - LOG_N_LANES as usize));

    let src = UnsafeConstI32(src);
    let dst = UnsafeMutI32(dst);
    iter.for_each(|index_h| {
```

**Review by andrewmilson — APPROVED** [review]
:lgtm: with comments

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/819#-:-O78UWGt9B982chALdLI:bvaci67)* status: 1 of 5 files reviewed, 7 unresolved discussions (waiting on @Alon-Ti, @alonh5, @shaharsamocha7, and @spapinistarkware)

**Review by andrewmilson — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/819#-:-O7NwWXd0NetivI-m-9y:bnfp4nl)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @Alon-Ti, @shaharsamocha7, and @spapinistarkware)

**Comment by alonh5** [comment]
### Merge activity

* **Sep 24, 9:20 AM EDT**: @alonh5 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/819).

**Pull request merged**
