### PR TITLE
Refactor wide fibonacci Remove lookup - each row contain independent instance

### PR DESCRIPTION
**Pull request by shaharsamocha7**
Remove lookup - each row contain independent instance

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/811)

### CODE REVIEW

**Comment by shaharsamocha7** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/811?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#812** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/812?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#811** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/811?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#809** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/809?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @shaharsamocha7 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/811)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @shaharsamocha7)

___
*[`crates/prover/src/examples/wide_fibonacci/mod.rs` line 32 at r2](https://reviewable.io/reviews/starkware-libs/stwo/811#-O5Ibq8SBXsksEs-So4b:-O5Ibq8SBXsksEs-So4c:bjadqqp) ([raw file](https://github.com/starkware-libs/stwo/blob/d2470289d0d3e5f3eb09f2f138cb5fc6f408f66c/crates/prover/src/examples/wide_fibonacci/mod.rs#L32)):*
> ```XML
>     }
>     fn evaluate<E: EvalAtRow>(&self, eval: E) -> E {
>         let poseidon_eval = WideFibonacciEval { eval };
> ```

No need for a struct. Just inline the eval function.

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/811)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @spapinistarkware)

___
*[`crates/prover/src/examples/wide_fibonacci/mod.rs` line 32 at r2](https://reviewable.io/reviews/starkware-libs/stwo/811#-O5Ibq8SBXsksEs-So4b:-O5IiaOD2t_Y7HPyuasU:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/d2470289d0d3e5f3eb09f2f138cb5fc6f408f66c/crates/prover/src/examples/wide_fibonacci/mod.rs#L32)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

No need for a struct. Just inline the eval function.
</blockquote></details>

Done.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/811#-:-O5Ikgu08TIU3OVWVbMh:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/811)* status: all files reviewed, 4 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/prover/src/examples/wide_fibonacci/mod.rs` line 44 at r4](https://reviewable.io/reviews/starkware-libs/stwo/811#-O5S3fvK-Q909MUBUzM-:-O5S3fvK-Q909MUBUzM0:b-q4dk2x) ([raw file](https://github.com/starkware-libs/stwo/blob/6429ed80b81f281a8e11ebdd1f0c109d0ff50ee9/crates/prover/src/examples/wide_fibonacci/mod.rs#L44)):*
> ```XML
> }
> 
> pub fn generate_trace(
> ```

What about the interaction trace and the other structs we have? Do you want to implement those too?
___
*[`crates/prover/src/examples/wide_fibonacci/mod.rs` line 115 at r4](https://reviewable.io/reviews/starkware-libs/stwo/811#-O5S9s6Y73YqJ-vA7glk:-O5S9s6Y73YqJ-vA7gll:bbqr9c) ([raw file](https://github.com/starkware-libs/stwo/blob/6429ed80b81f281a8e11ebdd1f0c109d0ff50ee9/crates/prover/src/examples/wide_fibonacci/mod.rs#L115)):*
> ```XML
>             }
>             .evaluate(eval);
>         });
> ```

Can you extract this closure? It's a bit hard to read.
Also unrelated to this PR but do we really need a closure in this function? Why not just pass an `impl FramworkComponent` and call evaluate inside the function?



_Code quote:_
```XML
        assert_constraints(&trace_polys, CanonicCoset::new(LOG_N_ROWS), |eval| {
            WideFibonacciComponent {
                log_n_rows: LOG_N_ROWS,
            }
            .evaluate(eval);
        });
```
___
*[`crates/prover/src/examples/wide_fibonacci/mod.rs` line 215 at r4](https://reviewable.io/reviews/starkware-libs/stwo/811#-O5SBe-g14qm3DKux4XK:-O5SBe-g14qm3DKux4XL:b-g4ge29) ([raw file](https://github.com/starkware-libs/stwo/blob/6429ed80b81f281a8e11ebdd1f0c109d0ff50ee9/crates/prover/src/examples/wide_fibonacci/mod.rs#L215)):*
> ```XML
>             })
>             .collect_vec();
>         let trace = generate_trace(component.log_size(), &inputs);
> ```

Extract common code into test function. Also if there is other common code you think can be shared.



_Code quote:_
```XML
        let inputs = (0..(1 << (LOG_N_INSTANCES - LOG_N_LANES)))
            .map(|i| FibInput {
                a: PackedBaseField::one(),
                b: PackedBaseField::from_array(std::array::from_fn(|j| {
                    BaseField::from_u32_unchecked((i * 16 + j) as u32)
                })),
            })
            .collect_vec();
        let trace = generate_trace(component.log_size(), &inputs);
```
___
*[`crates/prover/src/examples/wide_fibonacci/mod.rs` line 224 at r4](https://reviewable.io/reviews/starkware-libs/stwo/811#-O5SBofG5JpexGqMNCxs:-O5SBofG5JpexGqMNCxt:b-9gd4b3) ([raw file](https://github.com/starkware-libs/stwo/blob/6429ed80b81f281a8e11ebdd1f0c109d0ff50ee9/crates/prover/src/examples/wide_fibonacci/mod.rs#L224)):*
> ```XML
>             log_n_rows: LOG_N_INSTANCES,
>         };
>         let proof = prove::<SimdBackend, Poseidon252MerkleChannel>(
> ```

How is this working when ColumnOps isn't implemented? Do we even need that bound in that case?



_Code quote:_
```XML
Poseidon252MerkleChannel
```

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/811)* status: 4 of 5 files reviewed, 4 unresolved discussions (waiting on @alonh5)

___
*[`crates/prover/src/examples/wide_fibonacci/mod.rs` line 44 at r4](https://reviewable.io/reviews/starkware-libs/stwo/811#-O5S3fvK-Q909MUBUzM-:-O5SNeho9m1lXyhCzPTO:b4jycan) ([raw file](https://github.com/starkware-libs/stwo/blob/6429ed80b81f281a8e11ebdd1f0c109d0ff50ee9/crates/prover/src/examples/wide_fibonacci/mod.rs#L44)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

What about the interaction trace and the other structs we have? Do you want to implement those too?
</blockquote></details>

I wanted to have the simplest example so thought to remove the lookup part for good.
In the poseidon example we have a logup argument similar to what we had here.

I can re-add it in another pr if you think we should
___
*[`crates/prover/src/examples/wide_fibonacci/mod.rs` line 115 at r4](https://reviewable.io/reviews/starkware-libs/stwo/811#-O5S9s6Y73YqJ-vA7glk:-O5ST_sJ5Whq9tjJHKCc:b-n08r5u) ([raw file](https://github.com/starkware-libs/stwo/blob/6429ed80b81f281a8e11ebdd1f0c109d0ff50ee9/crates/prover/src/examples/wide_fibonacci/mod.rs#L115)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Can you extract this closure? It's a bit hard to read.
Also unrelated to this PR but do we really need a closure in this function? Why not just pass an `impl FramworkComponent` and call evaluate inside the function?
</blockquote></details>

Done.

We can pass the component and assume that there is evaluate function in there.
Seems to me that it is more clear that the assert function get the closure to assert directly, WDYT?
___
*[`crates/prover/src/examples/wide_fibonacci/mod.rs` line 215 at r4](https://reviewable.io/reviews/starkware-libs/stwo/811#-O5SBe-g14qm3DKux4XK:-O5STvzh8OWyjHlBKHRF:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/6429ed80b81f281a8e11ebdd1f0c109d0ff50ee9/crates/prover/src/examples/wide_fibonacci/mod.rs#L215)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Extract common code into test function. Also if there is other common code you think can be shared.
</blockquote></details>

Done.
___
*[`crates/prover/src/examples/wide_fibonacci/mod.rs` line 224 at r4](https://reviewable.io/reviews/starkware-libs/stwo/811#-O5SBofG5JpexGqMNCxs:-O5SNT4E2R3c15USVQBD:b8cs0et) ([raw file](https://github.com/starkware-libs/stwo/blob/6429ed80b81f281a8e11ebdd1f0c109d0ff50ee9/crates/prover/src/examples/wide_fibonacci/mod.rs#L224)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

How is this working when ColumnOps isn't implemented? Do we even need that bound in that case?
</blockquote></details>

ColumnOps is implemented in the sense that the type Column is defined.
We can consider to move the bit_reverse func from that trait and move it somewhere else, WDYT?

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/811#-:-O5SWr1p1AK89GNJsrlJ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shaharsamocha7)

___
*[`crates/prover/src/examples/wide_fibonacci/mod.rs` line 44 at r4](https://reviewable.io/reviews/starkware-libs/stwo/811#-O5S3fvK-Q909MUBUzM-:-O5SVdBZ6_GK3zjI9M67:bwacnvr) ([raw file](https://github.com/starkware-libs/stwo/blob/6429ed80b81f281a8e11ebdd1f0c109d0ff50ee9/crates/prover/src/examples/wide_fibonacci/mod.rs#L44)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I wanted to have the simplest example so thought to remove the lookup part for good.
In the poseidon example we have a logup argument similar to what we had here.

I can re-add it in another pr if you think we should
</blockquote></details>

I don't, just wanted to make sure.
___
*[`crates/prover/src/examples/wide_fibonacci/mod.rs` line 115 at r4](https://reviewable.io/reviews/starkware-libs/stwo/811#-O5S9s6Y73YqJ-vA7glk:-O5SVyk38DI_ZeKLJ6LR:be37hyv) ([raw file](https://github.com/starkware-libs/stwo/blob/6429ed80b81f281a8e11ebdd1f0c109d0ff50ee9/crates/prover/src/examples/wide_fibonacci/mod.rs#L115)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Done.

We can pass the component and assume that there is evaluate function in there.
Seems to me that it is more clear that the assert function get the closure to assert directly, WDYT?
</blockquote></details>

You don't need to assume, any impl of FrameworkComponent has a evaluate function. I think the closure is a weird way to use it and creates boilerplate code, unless it has another use that I'm missing.
___
*[`crates/prover/src/examples/wide_fibonacci/mod.rs` line 224 at r4](https://reviewable.io/reviews/starkware-libs/stwo/811#-O5SBofG5JpexGqMNCxs:-O5SWUYSA8h3JnrgnEXa:bi86bzs) ([raw file](https://github.com/starkware-libs/stwo/blob/6429ed80b81f281a8e11ebdd1f0c109d0ff50ee9/crates/prover/src/examples/wide_fibonacci/mod.rs#L224)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

ColumnOps is implemented in the sense that the type Column is defined.
We can consider to move the bit_reverse func from that trait and move it somewhere else, WDYT?
</blockquote></details>

Seems like it should be, yeah sounds good

**Review by alonh5 — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/811)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Pull request merged**
