### PR TITLE
ifft_full

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/381)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`src/core/backend/avx512/fft.rs` line 104 at r2](https://reviewable.io/reviews/starkware-libs/stwo/381#-Ns8DWJ07cJ-dOxmyE-d:-Ns8DWJ13ZJ0tS-BjF-S:b-c4gi99) ([raw file](https://github.com/starkware-libs/stwo/blob/eb7274f15355d40365aa33e74030deef2ffc2ec5/src/core/backend/avx512/fft.rs#L104)):*
> ```XML
> 
> /// Transposes the AVX vectors in the given array.
> /// Swaps the bit index abc <-> cba, where |a|=|c| and |b| = 0 or 1, according to the parity of
> ```

is it obvious that this is ok?



_Code quote:_
```XML
Swaps the bit index abc <-> cba, where |a|=|c| and |b| = 0 or 1
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/381)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`src/core/backend/avx512/fft.rs` line 197 at r2](https://reviewable.io/reviews/starkware-libs/stwo/381#-Ns89JgD631tqV0cie-8:-Ns89JgD631tqV0cie-9:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/eb7274f15355d40365aa33e74030deef2ffc2ec5/src/core/backend/avx512/fft.rs#L197)):*
> ```XML
>     for index_h in 0..(1 << (log_size - fft_layers - VECS_LOG_SIZE)) {
>         for layer in (0..fft_layers).step_by(3) {
>             match fft_layers - layer {
> ```





_Suggestion:_
```XML
 while fft_layers - layer >= 3 {
     ...
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/381)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/381)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`src/core/backend/avx512/fft.rs` line 104 at r2](https://reviewable.io/reviews/starkware-libs/stwo/381#-Ns8DWJ07cJ-dOxmyE-d:-Ns8EYg621df8Rdtw2BE:b-69bemg) ([raw file](https://github.com/starkware-libs/stwo/blob/eb7274f15355d40365aa33e74030deef2ffc2ec5/src/core/backend/avx512/fft.rs#L104)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

is it obvious that this is ok?
</blockquote></details>

No, but it is ok.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/381#-:-Ns8IoMW-2RMvENVlJwB:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
