### PR TITLE
CommitmentSchemeProver generic in backend

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/489)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/489?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#491** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/491?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#490** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/490?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#489** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/489?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#488** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/488?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#487** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/487?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#486** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/486?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#484** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/484?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#483** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/483?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#482** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/482?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#481** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/481?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#480** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/480?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#479** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/479?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#478** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/478?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#463** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/463?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#477** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/477?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#476** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/476?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by andrewmilson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/489)* status: 0 of 14 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`src/core/backend/mod.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/stwo/489#-NtJi3Bd99yBJSl27ys-:-NtJhoNK-n1MG1DY9_10:b-9z03zo) ([raw file](https://github.com/starkware-libs/stwo/blob/f7a11cd8cbc0eadea66bd76b4e155a109fbbe379/src/core/backend/mod.rs#L32)):*
> ```XML
>     fn zeros(len: usize) -> Self;
>     /// Returns a cpu vector of the column.
>     fn to_cpu(&self) -> Vec<T>;
> ```

Personally think `to_vec` is clearer than `to_cpu` and that it's quite confusing unless you know our standard backend is referred to as CPU. Do we even want to associate `Vec<T>` with this?



_Suggestion:_
```XML
    fn to_vec(&self) -> Vec<T>;
```
___
*[`src/core/fields/secure.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/stwo/489#-NtJitooASzYebTWQlLX:-NtJitooASzYebTWQlLY:b7njnd) ([raw file](https://github.com/starkware-libs/stwo/blob/f7a11cd8cbc0eadea66bd76b4e155a109fbbe379/src/core/fields/secure.rs#L48)):*
> ```XML
>     // TODO(spapini): Remove when we no longer use CircleEvaluation<SecureField>.
>     pub fn to_cpu(&self) -> Vec<SecureField> {
>         (0..self.len()).map(|i| self.at(i)).collect()
> ```

This could be the default implementation on the trait.
___
*[`src/core/poly/circle/evaluation.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/stwo/489#-NtJjOzODhDGb0hx5bYj:-NtJjOzODhDGb0hx5bYk:b-j67rby) ([raw file](https://github.com/starkware-libs/stwo/blob/f7a11cd8cbc0eadea66bd76b4e155a109fbbe379/src/core/poly/circle/evaluation.rs#L37)):*
> ```XML
> // For example, the CPU backend implementation is in `src/core/backend/cpu/poly.rs`.
> impl<F: ExtensionOf<BaseField>, B: FieldOps<F>> CircleEvaluation<B, F, NaturalOrder> {
>     // TODO(spapini): Remove. Is this even used.
> ```

This used to exist when `trait PolyOracle { fn at(&self, point: CirclePointIndex) }` was implemented on `CircleEvaluation`.  Think it can be removed.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/489)* status: 0 of 14 files reviewed, 3 unresolved discussions (waiting on @andrewmilson)

___
*[`src/core/backend/mod.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/stwo/489#-NtJi3Bd99yBJSl27ys-:-NtLxBJJBAhbQ2RAh3qx:brq7mde) ([raw file](https://github.com/starkware-libs/stwo/blob/f7a11cd8cbc0eadea66bd76b4e155a109fbbe379/src/core/backend/mod.rs#L32)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Personally think `to_vec` is clearer than `to_cpu` and that it's quite confusing unless you know our standard backend is referred to as CPU. Do we even want to associate `Vec<T>` with this?
</blockquote></details>

I think to_vec() is confusing if you have a column that is supposed to be on the gpu.
___
*[`src/core/fields/secure.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/stwo/489#-NtJitooASzYebTWQlLX:-NtLxhwvA78iMBMhtNZE:b-lipwj1) ([raw file](https://github.com/starkware-libs/stwo/blob/f7a11cd8cbc0eadea66bd76b4e155a109fbbe379/src/core/fields/secure.rs#L48)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

This could be the default implementation on the trait.
</blockquote></details>

It's just temporary, and it's a very slow and bad function.
___
*[`src/core/poly/circle/evaluation.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/stwo/489#-NtJjOzODhDGb0hx5bYj:-NtLx5SyChhUuAtXrfBg:b-eqmlav) ([raw file](https://github.com/starkware-libs/stwo/blob/f7a11cd8cbc0eadea66bd76b4e155a109fbbe379/src/core/poly/circle/evaluation.rs#L37)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

This used to exist when `trait PolyOracle { fn at(&self, point: CirclePointIndex) }` was implemented on `CircleEvaluation`.  Think it can be removed.
</blockquote></details>

some tests used it, an it's a hussle to remove it in this PR. Ill do it later.

**Review by andrewmilson — APPROVED** [review]
:lgtm:

> Reviewed 7 of 14 files at r1, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/489#-:-NtoKYSc1kjerqSOMMpR:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
