### PR TITLE
Support mixed degree in commitment scheme.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/533)

### CODE REVIEW

**Comment by alonh5** [comment]
* **#533** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/533?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — COMMENTED** [review]
Can you add a test the checks this passes?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/533#-:-Ntkevn056nMdlYuswqk:b-lu9e9i)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Review by alonh5 — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/533#-:-NtpGpka8KS1EjHjosTo:b-896fix)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/533#-:-NtpW_Oe0peVkzdRf6dx:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Pull request merged**
