### PR TITLE
Implement Backend for AVX.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/561)

### CODE REVIEW

**Comment by alonh5** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/561?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#561** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/561?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#559** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/559?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#558** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/558?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#556** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/556?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#555** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/555?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/561)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`src/core/backend/avx512/quotients.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/stwo/561#-NuTYRvz0dm_FisIiRNW:-NuTYRvz0dm_FisIiRNX:bq3ccnc) ([raw file](https://github.com/starkware-libs/stwo/blob/a99a089134934212b6fd857a98571c76344aae18/src/core/backend/avx512/quotients.rs#L136)):*
> ```XML
>         &mut flat_denominator_inverses,
>     );
>     let mut flat_denominator_inverses = flat_denominator_inverses.data.into_iter();
> ```

Can't you do the chunks thing like before?

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 2 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/561)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/561)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`src/core/backend/avx512/quotients.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/stwo/561#-NuTYRvz0dm_FisIiRNW:-NuTl5miDnP2QQmI4OZu:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/a99a089134934212b6fd857a98571c76344aae18/src/core/backend/avx512/quotients.rs#L136)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Can't you do the chunks thing like before?
</blockquote></details>

Done.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/561#-:-NuTomwb8ObZJTFcZ0Rb:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Comment by alonh5** [comment]
### Merge activity

* **Apr 2, 9:14 AM EDT**: @alonh5 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/561).

**Pull request merged**
