### PR TITLE
VeryPacked

### PR DESCRIPTION
**Pull request by Alon-Ti**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/782)

### CODE REVIEW

**Comment by Alon-Ti** [comment]
* **#782** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/782?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Alon-Ti and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/782)* status: 4 of 7 files reviewed, 6 unresolved discussions (waiting on @Alon-Ti)

___
*[`crates/prover/src/core/backend/simd/column.rs` line 383 at r1](https://reviewable.io/reviews/starkware-libs/stwo/782#-O3kqeYdDhbw1K4Q_0uc:-O3kqeYdDhbw1K4Q_0ud:b-sfcpnq) ([raw file](https://github.com/starkware-libs/stwo/blob/aacf3f6c0c7a615d42d9fd49cb95349f802d9dc5/crates/prover/src/core/backend/simd/column.rs#L383)):*
> ```XML
>         SecureColumnByCoords { columns }
>     }
> }
> ```

Seems like we have a considerable amount of Columns right now. Perhaps this is a good time to think of a good abstraction for these. Have any ideas?
___
*[`crates/prover/src/core/backend/simd/column.rs` line 409 at r1](https://reviewable.io/reviews/starkware-libs/stwo/782#-O3kqKiYCuw6StZLhEAk:-O3kqKiYCuw6StZLhEAl:b-bbycu3) ([raw file](https://github.com/starkware-libs/stwo/blob/aacf3f6c0c7a615d42d9fd49cb95349f802d9dc5/crates/prover/src/core/backend/simd/column.rs#L409)):*
> ```XML
>             std::mem::forget(value);
>             ret
>         }
> ```

Try to use bytemuck for this.



_Code quote:_
```XML
        unsafe {
            let ret = Self {
                data: Vec::from_raw_parts(ptr as *mut VeryPackedBaseField, len, len),
                length: value.length,
            };
            std::mem::forget(value);
            ret
        }
```
___
*[`crates/prover/src/core/backend/simd/column.rs` line 425 at r1](https://reviewable.io/reviews/starkware-libs/stwo/782#-O3kqPvSCpT7_E9xqp6c:-O3kqPvSCpT7_E9xqp6d:bb7od0r) ([raw file](https://github.com/starkware-libs/stwo/blob/aacf3f6c0c7a615d42d9fd49cb95349f802d9dc5/crates/prover/src/core/backend/simd/column.rs#L425)):*
> ```XML
>             std::mem::forget(value);
>             ret
>         }
> ```

same



_Code quote:_
```XML
        unsafe {
            let ret = Self {
                data: Vec::from_raw_parts(ptr as *mut PackedBaseField, len, len),
                length: value.length,
            };
            std::mem::forget(value);
            ret
        }
```
___
*[`crates/prover/src/core/backend/simd/column.rs` line 498 at r1](https://reviewable.io/reviews/starkware-libs/stwo/782#-O3kqZvKDpGAqVx2aC2k:-O3kqZvKDpGAqVx2aC2l:bexzsho) ([raw file](https://github.com/starkware-libs/stwo/blob/aacf3f6c0c7a615d42d9fd49cb95349f802d9dc5/crates/prover/src/core/backend/simd/column.rs#L498)):*
> ```XML
> 
> impl From<&mut SecureColumnByCoords<SimdBackend>> for &mut VeryPackedSecureColumnByCoords {
>     fn from(value: &mut SecureColumnByCoords<SimdBackend>) -> Self {
> ```

Maybe for these too?
___
*[`crates/prover/src/core/backend/simd/very_packed_m31.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/stwo/782#-O3krLDKAb59hNtERg1J:-O3krLDKAb59hNtERg1K:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/aacf3f6c0c7a615d42d9fd49cb95349f802d9dc5/crates/prover/src/core/backend/simd/very_packed_m31.rs#L23)):*
> ```XML
> pub struct VeryPackedCM31(pub [VeryPackedM31; 2]);
> #[derive(Copy, Clone, Debug)]
> pub struct VeryPackedQM31(pub [VeryPackedCM31; 2]);
> ```





_Suggestion:_
```XML
#[derive(Copy, Clone, Debug)]
pub struct VeryPackedCM31(pub [VeryPackedM31; N_VERY_PACKED_ELEMS]);
#[derive(Copy, Clone, Debug)]
pub struct VeryPackedQM31(pub [VeryPackedCM31; N_VERY_PACKED_ELEMS]);
```
___
*[`crates/prover/src/core/backend/simd/very_packed_m31.rs` line 381 at r1](https://reviewable.io/reviews/starkware-libs/stwo/782#-O3krbGWCUbi5x-Z1mQj:-O3krbGWCUbi5x-Z1mQk:b9uo1nt) ([raw file](https://github.com/starkware-libs/stwo/blob/aacf3f6c0c7a615d42d9fd49cb95349f802d9dc5/crates/prover/src/core/backend/simd/very_packed_m31.rs#L381)):*
> ```XML
>             ac_p_bd.b() + bd_times_1_plus_i.b(),
>         ]);
>         Self([l, ad_p_bc])
> ```

Why not multiply pointwise?
Why not do all the ops pointwise, instead of reimplementing them? 



_Code quote:_
```XML
        // Compute using Karatsuba.
        //   (a + ub) * (c + ud) =
        //   (ac + (2+i)bd) + (ad + bc)u =
        //   ac + 2bd + ibd + (ad + bc)u.
        let ac = self.a() * rhs.a();
        let bd = self.b() * rhs.b();
        let bd_times_1_plus_i = VeryPackedCM31([bd.a() - bd.b(), bd.a() + bd.b()]);
        // Computes ac + bd.
        let ac_p_bd = ac + bd;
        // Computes ad + bc.
        let ad_p_bc = (self.a() + self.b()) * (rhs.a() + rhs.b()) - ac_p_bd;
        // ac + 2bd + ibd =
        // ac + bd + bd + ibd
        let l = VeryPackedCM31([
            ac_p_bd.a() + bd_times_1_plus_i.a(),
            ac_p_bd.b() + bd_times_1_plus_i.b(),
        ]);
        Self([l, ad_p_bc])
```

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/782)* status: 5 of 7 files reviewed, 6 unresolved discussions (waiting on @Alon-Ti)

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 2 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/782)* status: all files reviewed, 6 unresolved discussions (waiting on @Alon-Ti)

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/782)* status: 5 of 8 files reviewed, 5 unresolved discussions (waiting on @Alon-Ti)

___
*[`crates/prover/src/constraint_framework/component.rs` line 128 at r2](https://reviewable.io/reviews/starkware-libs/stwo/782#-O3zmjUL9y9SOQUVl8pn:-O3zmjUL9y9SOQUVl8po:b-s32y89) ([raw file](https://github.com/starkware-libs/stwo/blob/30a24630c2d71ef9b828f04a247af038dfae0e64/crates/prover/src/constraint_framework/component.rs#L128)):*
> ```XML
> 
>         let _span = span!(Level::INFO, "Constraint pointwise eval").entered();
>         let col: &mut VeryPackedSecureColumnByCoords = unsafe {
> ```

Can this be done in a safer way?
___
*[`crates/prover/src/core/backend/simd/very_packed_m31.rs` line 29 at r2](https://reviewable.io/reviews/starkware-libs/stwo/782#-O3zmWqxDfvaBPcFzdMK:-O3zmWqxDfvaBPcFzdML:b-qeouqp) ([raw file](https://github.com/starkware-libs/stwo/blob/30a24630c2d71ef9b828f04a247af038dfae0e64/crates/prover/src/core/backend/simd/very_packed_m31.rs#L29)):*
> ```XML
> pub type VeryPackedSecureField = VeryPackedQM31;
> 
> unsafe impl Pod for VeryPackedM31 {}
> ```

Derive didnt work?

**Review by Alon-Ti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/782)* status: 5 of 8 files reviewed, 5 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/constraint_framework/component.rs` line 128 at r2](https://reviewable.io/reviews/starkware-libs/stwo/782#-O3zmjUL9y9SOQUVl8pn:-O4-fMbJ-pJIwVSYpFCV:b6gu09) ([raw file](https://github.com/starkware-libs/stwo/blob/30a24630c2d71ef9b828f04a247af038dfae0e64/crates/prover/src/constraint_framework/component.rs#L128)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Can this be done in a safer way?
</blockquote></details>

I couldn't find any, do you know of one? We want to reinterpret the structure behind the pointer, this is inherently unsafe.
___
*[`crates/prover/src/core/backend/simd/column.rs` line 409 at r1](https://reviewable.io/reviews/starkware-libs/stwo/782#-O3kqKiYCuw6StZLhEAk:-O3lhUwE3RrJywLP2WpK:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/aacf3f6c0c7a615d42d9fd49cb95349f802d9dc5/crates/prover/src/core/backend/simd/column.rs#L409)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Try to use bytemuck for this.
</blockquote></details>

Done.
___
*[`crates/prover/src/core/backend/simd/column.rs` line 425 at r1](https://reviewable.io/reviews/starkware-libs/stwo/782#-O3kqPvSCpT7_E9xqp6c:-O3lhWGC5qMnPLQVr-yZ:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/aacf3f6c0c7a615d42d9fd49cb95349f802d9dc5/crates/prover/src/core/backend/simd/column.rs#L425)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[`crates/prover/src/core/backend/simd/column.rs` line 498 at r1](https://reviewable.io/reviews/starkware-libs/stwo/782#-O3kqZvKDpGAqVx2aC2k:-O3mVeqTDPnyy3LjYHGP:b-lbeob9) ([raw file](https://github.com/starkware-libs/stwo/blob/aacf3f6c0c7a615d42d9fd49cb95349f802d9dc5/crates/prover/src/core/backend/simd/column.rs#L498)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Maybe for these too?
</blockquote></details>

These are really unsafe, so I removed them in favor of ad hoc conversions where really needed.
___
*[`crates/prover/src/core/backend/simd/very_packed_m31.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/stwo/782#-O3krLDKAb59hNtERg1J:-O3l57sICz4BCeS5U2r_:b-d32ioo) ([raw file](https://github.com/starkware-libs/stwo/blob/aacf3f6c0c7a615d42d9fd49cb95349f802d9dc5/crates/prover/src/core/backend/simd/very_packed_m31.rs#L23)):*
> ```XML
> pub struct VeryPackedCM31(pub [VeryPackedM31; 2]);
> #[derive(Copy, Clone, Debug)]
> pub struct VeryPackedQM31(pub [VeryPackedCM31; 2]);
> ```

These are complex extension degrees
___
*[`crates/prover/src/core/backend/simd/very_packed_m31.rs` line 381 at r1](https://reviewable.io/reviews/starkware-libs/stwo/782#-O3krbGWCUbi5x-Z1mQj:-O3lh4SM8V1A_rLd3SZp:b-21owvq) ([raw file](https://github.com/starkware-libs/stwo/blob/aacf3f6c0c7a615d42d9fd49cb95349f802d9dc5/crates/prover/src/core/backend/simd/very_packed_m31.rs#L381)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Why not multiply pointwise?
Why not do all the ops pointwise, instead of reimplementing them?
</blockquote></details>

These are complex extensions of the smaller types, not vectored %cM31s. I'll generalize these to share the code in a future PR.
___
*[`crates/prover/src/core/backend/simd/very_packed_m31.rs` line 29 at r2](https://reviewable.io/reviews/starkware-libs/stwo/782#-O3zmWqxDfvaBPcFzdMK:-O4-d-9OCN8VQe7DcmkY:bezjeye) ([raw file](https://github.com/starkware-libs/stwo/blob/30a24630c2d71ef9b828f04a247af038dfae0e64/crates/prover/src/core/backend/simd/very_packed_m31.rs#L29)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Derive didnt work?
</blockquote></details>


The editor complains, but it works!

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/782)* status: 7 of 8 files reviewed, 5 unresolved discussions (waiting on @Alon-Ti)

___
*[`crates/prover/src/constraint_framework/component.rs` line 128 at r2](https://reviewable.io/reviews/starkware-libs/stwo/782#-O3zmjUL9y9SOQUVl8pn:-O4-x5Y4Bk9dMdG6oQ74:br4ckhm) ([raw file](https://github.com/starkware-libs/stwo/blob/30a24630c2d71ef9b828f04a247af038dfae0e64/crates/prover/src/constraint_framework/component.rs#L128)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

I couldn't find any, do you know of one? We want to reinterpret the structure behind the pointer, this is inherently unsafe.
</blockquote></details>

At least hide this behind a function in VeryPackedSecureColumnByCoords?
___
*[`crates/prover/src/constraint_framework/simd_domain.rs` line 75 at r3](https://reviewable.io/reviews/starkware-libs/stwo/782#-O4-xFp01lBkcaN0KI_Q:-O4-xFp01lBkcaN0KI_R:b-dh5xqh) ([raw file](https://github.com/starkware-libs/stwo/blob/c8c11d47dd6d380a08e3dbfbd2f5af226c66ae86/crates/prover/src/constraint_framework/simd_domain.rs#L75)):*
> ```XML
>                         .get_unchecked(col_index)
>                         .values;
>                     let very_packed_col =
> ```

This too
___
*[`crates/prover/src/core/backend/simd/very_packed_m31.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/stwo/782#-O3krLDKAb59hNtERg1J:-O4-xPuQCTIdRLijN9Ap:b-w1h3fg) ([raw file](https://github.com/starkware-libs/stwo/blob/aacf3f6c0c7a615d42d9fd49cb95349f802d9dc5/crates/prover/src/core/backend/simd/very_packed_m31.rs#L23)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

These are complex extension degrees
</blockquote></details>

can you remind me why not go the other way and make
```
VeryPackedM31(pub [PackedM31; N_VERY_PACKED_ELEMS])
```
?

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/782)* status: all files reviewed (commit messages unreviewed), 4 unresolved discussions (waiting on @Alon-Ti)

**Review by Alon-Ti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/782)* status: all files reviewed (commit messages unreviewed), 4 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/constraint_framework/component.rs` line 128 at r2](https://reviewable.io/reviews/starkware-libs/stwo/782#-O3zmjUL9y9SOQUVl8pn:-O40CGnEDS2QF8fjv1PQ:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/30a24630c2d71ef9b828f04a247af038dfae0e64/crates/prover/src/constraint_framework/component.rs#L128)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

At least hide this behind a function in VeryPackedSecureColumnByCoords?
</blockquote></details>

Done.
___
*[`crates/prover/src/constraint_framework/simd_domain.rs` line 75 at r3](https://reviewable.io/reviews/starkware-libs/stwo/782#-O4-xFp01lBkcaN0KI_Q:-O40EwGUCRN1OcGe6XoT:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/c8c11d47dd6d380a08e3dbfbd2f5af226c66ae86/crates/prover/src/constraint_framework/simd_domain.rs#L75)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

This too
</blockquote></details>

Done.
___
*[`crates/prover/src/core/backend/simd/very_packed_m31.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/stwo/782#-O3krLDKAb59hNtERg1J:-O4-yxDgBMmGM9qL7Qrx:b-v61lai) ([raw file](https://github.com/starkware-libs/stwo/blob/aacf3f6c0c7a615d42d9fd49cb95349f802d9dc5/crates/prover/src/core/backend/simd/very_packed_m31.rs#L23)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

can you remind me why not go the other way and make
```
VeryPackedM31(pub [PackedM31; N_VERY_PACKED_ELEMS])
```
?
</blockquote></details>

To mirror the structure of  the`Packed.M31`s to avoid confusion, I'll have a trait that generalizes both in a future PR.

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/782)* status: all files reviewed, 1 unresolved discussion (waiting on @Alon-Ti)

___
*[`crates/prover/src/core/backend/simd/very_packed_m31.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/stwo/782#-O3krLDKAb59hNtERg1J:-O40UIrf24axGSXERTCR:b1s2zoh) ([raw file](https://github.com/starkware-libs/stwo/blob/aacf3f6c0c7a615d42d9fd49cb95349f802d9dc5/crates/prover/src/core/backend/simd/very_packed_m31.rs#L23)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

To mirror the structure of  the`Packed.M31`s to avoid confusion, I'll have a trait that generalizes both in a future PR.
</blockquote></details>

I'm not convinced.
Here is my suggestion:
```
struct Packed<A, const N: usize>([A;N]);
impl<A,B: Add<A>,const N: usize> Add<Packed<A,N>> for Packed<B,N>{
fn add(self, other: Packed<B>) -> Packed<B::Output> {
Packed(std::array::from_fn(|i|self.0[i] + other.0[i]))
}
}
```

Kind of a generic vector structure.
WDYT?

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/782)* status: all files reviewed, 1 unresolved discussion (waiting on @Alon-Ti)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/782#-:-O49v1yi2aVLDQ5IjAuh:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Alon-Ti)

**Pull request merged**
