### PR TITLE
MerkleChannel

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/784)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
* **#784** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/784?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by alonh5 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/784)* status: 0 of 27 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/prover/src/core/proof_of_work.rs` line 11 at r2](https://reviewable.io/reviews/starkware-libs/stwo/784#-O40C0xy5_Evd0SYL5bF:-O40C0xy5_Evd0SYL5bG:b8iwtep) ([raw file](https://github.com/starkware-libs/stwo/blob/14e41f9f3fce3dd6d83bf7d562ca7d30caaeee69/crates/prover/src/core/proof_of_work.rs#L11)):*
> ```XML
> 
> // TODO(ShaharS): generalize to more channels and create a from function in the hash traits.
> pub struct ProofOfWork {
> ```

Is it possible to only couple the channel and merkle hasher traits without removeing the proof of work API?

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/784)* status: 0 of 27 files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/prover/src/core/proof_of_work.rs` line 11 at r2](https://reviewable.io/reviews/starkware-libs/stwo/784#-O40C0xy5_Evd0SYL5bF:-O40WAvlC1sjFqT0g0RB:b-5kqk9i) ([raw file](https://github.com/starkware-libs/stwo/blob/14e41f9f3fce3dd6d83bf7d562ca7d30caaeee69/crates/prover/src/core/proof_of_work.rs#L11)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Is it possible to only couple the channel and merkle hasher traits without removeing the proof of work API?
</blockquote></details>

this is not a bug, it's a feature.
1. We needed to make pow an op. Here I do it.
2. This proof of work API was bloat, IMO. I removed it.
3. POW now works for all hashes.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 26 of 27 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/784)* status: all files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/core/backend/mod.rs` line 34 at r2](https://reviewable.io/reviews/starkware-libs/stwo/784#-O456i7c80gUaor726OQ:-O456i7c80gUaor726OR:b-7yx4ku) ([raw file](https://github.com/starkware-libs/stwo/blob/d449b2dfd89a6539be2a9c7a5737dec699684ead/crates/prover/src/core/backend/mod.rs#L34)):*
> ```XML
> pub trait BackendForChannel<MC: MerkleChannel>:
>     Backend + MerkleOps<MC::H> + GrindOps<MC::C>
> {
> ```

Wdyt?



_Suggestion:_
```XML
pub trait BackendWithChannel<MC: MerkleChannel>:
    Backend + MerkleOps<MC::H> + GrindOps<MC::C>
{
```
___
*[`crates/prover/src/core/channel/blake2s.rs` line 163 at r2](https://reviewable.io/reviews/starkware-libs/stwo/784#-O458XuT-uqP7VBMA0SZ:-O458XuU2ZNEr3RL0TEE:b-lu9tvs) ([raw file](https://github.com/starkware-libs/stwo/blob/14e41f9f3fce3dd6d83bf7d562ca7d30caaeee69/crates/prover/src/core/channel/blake2s.rs#L163)):*
> ```XML
>         assert_eq!(channel.channel_time.n_sent, 6);
> 
>         channel.mix_digest(Blake2sHash::from(vec![1; 32]));
> ```

Test MC::mix_root() instead?
___
*[`crates/prover/src/core/channel/poseidon252.rs` line 81 at r2](https://reviewable.io/reviews/starkware-libs/stwo/784#-O45AYn20AiUzPlvhAXn:-O45AYn20AiUzPlvhAXo:b-5upn8p) ([raw file](https://github.com/starkware-libs/stwo/blob/d449b2dfd89a6539be2a9c7a5737dec699684ead/crates/prover/src/core/channel/poseidon252.rs#L81)):*
> ```XML
>     fn mix_nonce(&mut self, nonce: u64) {
>         self.digest = poseidon_hash(self.digest, nonce.into());
>         self.channel_time.inc_challenges();
> ```

Maybe have an update_digest method where you also call inc_challenges()? And keep digest and channel time private.



_Code quote:_
```XML
        self.digest = poseidon_hash(self.digest, nonce.into());
        self.channel_time.inc_challenges();
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/784)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5)

___
*[`crates/prover/src/core/backend/mod.rs` line 34 at r2](https://reviewable.io/reviews/starkware-libs/stwo/784#-O456i7c80gUaor726OQ:-O45HqK19RHNoE5PFSVc:b-m3p41j) ([raw file](https://github.com/starkware-libs/stwo/blob/d449b2dfd89a6539be2a9c7a5737dec699684ead/crates/prover/src/core/backend/mod.rs#L34)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Wdyt?
</blockquote></details>

If channel was an associated type, then it would make more sense.
It can't be associated since a backend can support multiple channels.
Given it's the backend that implements this for the channel MC, I think BackendForChannel makes ore sense.
___
*[`crates/prover/src/core/channel/blake2s.rs` line 163 at r2](https://reviewable.io/reviews/starkware-libs/stwo/784#-O458XuT-uqP7VBMA0SZ:-O45It1CB-eItA4Wd9vP:b-26r51n) ([raw file](https://github.com/starkware-libs/stwo/blob/14e41f9f3fce3dd6d83bf7d562ca7d30caaeee69/crates/prover/src/core/channel/blake2s.rs#L163)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Test MC::mix_root() instead?
</blockquote></details>

Added a test near Blake2sMerkleChannel

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/784)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/prover/src/core/channel/poseidon252.rs` line 88 at r3](https://reviewable.io/reviews/starkware-libs/stwo/784#-O45RzHg-r2xVaXcbeq4:-O45RzHg-r2xVaXcbeq5:b-z7vi8p) ([raw file](https://github.com/starkware-libs/stwo/blob/f2a6191d5be083390003430d269c7fc05069f2f5/crates/prover/src/core/channel/poseidon252.rs#L88)):*
> ```XML
>     fn mix_nonce(&mut self, nonce: u64) {
>         self.digest = poseidon_hash(self.digest, nonce.into());
>         self.channel_time.inc_challenges();
> ```

Use update_digest, also in other places (everywhere inc_challenges is used).



_Code quote:_
```XML
self.channel_time.inc_challenges();
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/784)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/prover/src/core/channel/poseidon252.rs` line 88 at r3](https://reviewable.io/reviews/starkware-libs/stwo/784#-O45RzHg-r2xVaXcbeq4:-O45UVmf2Pp-Lgj7Pc7B:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/f2a6191d5be083390003430d269c7fc05069f2f5/crates/prover/src/core/channel/poseidon252.rs#L88)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Use update_digest, also in other places (everywhere inc_challenges is used).
</blockquote></details>

Done.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/784#-:-O45Vu4N-KsstOU1K4M5:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
