### PR TITLE
Abdel cosmetic changes to the README

### PR DESCRIPTION
**Pull request by shaharsamocha7**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/691)

### CODE REVIEW

**Comment by shaharsamocha7** [comment]
* **#691** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/691?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @shaharsamocha7 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/691)* status: all files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`README.md` line 49 at r3](https://reviewable.io/reviews/starkware-libs/stwo/691#-O0hXCEIEA3FYNxGWQRI:-O0hXCEIEA3FYNxGWQRJ:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/6fa1f798df0c72baf106b8ff45f9a01c49779b67/README.md#L49)):*
> ```Markdown
> Run `poseidon_benchmark.sh` to run single-threaded poseidon2 hash proof benchmark.
> 
> For further benchmarks can be run using `cargo bench`.
> ```





_Suggestion:_
```Markdown
Run `poseidon_benchmark.sh` to run a single-threaded poseidon2 hash proof benchmark.

Further benchmarks can be run using `cargo bench`.
```

**Review by KineretS — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/691#-:-O0hh4vWBNm428P95TCh:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7)

___
*[`README.md` line 33 at r3](https://reviewable.io/reviews/starkware-libs/stwo/691#-O0hgecZ3xdko1fI1s69:-O0hgecZ3xdko1fI1s6A:b-sebt9c) ([raw file](https://github.com/starkware-libs/stwo/blob/6fa1f798df0c72baf106b8ff45f9a01c49779b67/README.md#L33)):*
> ```Markdown
> ## 🌟 About
> 
> Stwo is a next generation implementation of a [CSTARK](https://eprint.iacr.org/2024/278) prover and verifier, written in Rust 🦀.
> ```

why 'a' and  not 'the'? :) (non blocking)

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/691#-:-O0hnNMp08suJq9N195n:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @KineretS)

**Pull request merged**
