### PR TITLE
Test wasm32-unknown-unknown target

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/791)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
* **#791** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/791?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by andrewmilson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/791)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`.github/workflows/ci.yaml` line 81 at r1](https://reviewable.io/reviews/starkware-libs/stwo/791#-O4htQTTBgKP36XUavoR:-O4htQTTBgKP36XUavoS:bkf4uxu) ([raw file](https://github.com/starkware-libs/stwo/blob/e5aa6fe03b666d640a15701998a886af8229114c/.github/workflows/ci.yaml#L81)):*
> ```YAML
>       - run: cargo build --target wasm32-unknown-unknown
>         env:
>           RUSTFLAGS: -C target-feature=+simd128
> ```

scripts/wasm_test_runner.sh:
```
#!/bin/sh
# Test runner for "wasm32-unknown-unknown" target. Just returns exit status, no test logs.
# Source: https://internals.rust-lang.org/t/running-tests-on-wasm32-unknown-unknown/15010
# TODO(andrew): Switch to better solution using `wasm-pack` (which shows logs).
wasmtime run --invoke main "$@" 0 0
```



_Suggestion:_
```YAML
  run-wasm32-unknown-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2024-01-04
          targets: wasm32-unknown-unknown
      - uses: taiki-e/install-action@v2
        with:
          tool: wasmtime
      - uses: Swatinem/rust-cache@v2
      - run: cargo test --target wasm32-unknown-unknown
        env:
          CARGO_TARGET_WASM32_UNKNOWN_UNKNOWN_RUNNER: ./scripts/wasm_test_runner.sh
          RUSTFLAGS: -C target-feature=+simd128
```

**Review by andrewmilson — APPROVED** [review]
:lgtm: with comment

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/791#-:-O4hvR8EDaWsVtp9G9bb:b10c0l0)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/791)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @andrewmilson)

___
*[`.github/workflows/ci.yaml` line 81 at r1](https://reviewable.io/reviews/starkware-libs/stwo/791#-O4htQTTBgKP36XUavoR:-O4jOXB1EQRHMALmwBAf:b8619zl) ([raw file](https://github.com/starkware-libs/stwo/blob/e5aa6fe03b666d640a15701998a886af8229114c/.github/workflows/ci.yaml#L81)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

scripts/wasm_test_runner.sh:
```
#!/bin/sh
# Test runner for "wasm32-unknown-unknown" target. Just returns exit status, no test logs.
# Source: https://internals.rust-lang.org/t/running-tests-on-wasm32-unknown-unknown/15010
# TODO(andrew): Switch to better solution using `wasm-pack` (which shows logs).
wasmtime run --invoke main "$@" 0 0
```
</blockquote></details>

I don't think I can use wasmtime here. Don't think it guarantees browser run.
[wasm-pack](https://github.com/rustwasm/wasm-pack) claims it does.

**Review by andrewmilson — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/791#-:-O4jtXq69yWjfOKKDxk3:bnfp4nl)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/Cargo.toml` line 33 at r2](https://reviewable.io/reviews/starkware-libs/stwo/791#-O4jt-ONACbsitWFGVVP:-O4jt-OO7TRlsTy_oZzU:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/7d3d53401fa5b872448de84f573e7609b70f3097/crates/prover/Cargo.toml#L33)):*
> ```TOML
> test-log = { version = "0.2.15", features = ["trace"] }
> tracing-subscriber = "0.3.18"
> wasm-bindgen-test = "0.3.43"
> ```





_Suggestion:_
```TOML

[target.'cfg(all(target_family = "wasm", not(target_os = "wasi")))'.dev-dependencies]
wasm-bindgen-test = "0.3.43"
```
___
*[`crates/prover/src/examples/poseidon/mod.rs` line 390 at r2](https://reviewable.io/reviews/starkware-libs/stwo/791#-O4jt6Kr1Y8Z3NnV6DiH:-O4jt6Kr1Y8Z3NnV6DiI:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/7d3d53401fa5b872448de84f573e7609b70f3097/crates/prover/src/examples/poseidon/mod.rs#L390)):*
> ```XML
>     use num_traits::One;
>     #[cfg(target_arch = "wasm32")]
>     use wasm_bindgen_test::*;
> ```


___
*[`crates/prover/src/examples/poseidon/mod.rs` line 410 at r2](https://reviewable.io/reviews/starkware-libs/stwo/791#-O4jtFTXCA4Tay5GjsTq:-O4jtFTXCA4Tay5GjsTr:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/7d3d53401fa5b872448de84f573e7609b70f3097/crates/prover/src/examples/poseidon/mod.rs#L410)):*
> ```XML
> 
>     #[cfg(target_arch = "wasm32")]
>     #[wasm_bindgen_test]
> ```





_Suggestion:_
```XML
    #[cfg(all(target_family = "wasm", not(target_os = "wasi")))]
    #[wasm_bindgen_test::wasm_bindgen_test]
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/791)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @andrewmilson)

___
*[`crates/prover/Cargo.toml` line 33 at r2](https://reviewable.io/reviews/starkware-libs/stwo/791#-O4jt-ONACbsitWFGVVP:-O4ndPox04LCZbrEVm4G:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/7d3d53401fa5b872448de84f573e7609b70f3097/crates/prover/Cargo.toml#L33)):*
> ```TOML
> test-log = { version = "0.2.15", features = ["trace"] }
> tracing-subscriber = "0.3.18"
> wasm-bindgen-test = "0.3.43"
> ```

Done.
___
*[`crates/prover/src/examples/poseidon/mod.rs` line 410 at r2](https://reviewable.io/reviews/starkware-libs/stwo/791#-O4jtFTXCA4Tay5GjsTq:-O4ndgZ7Ar1c8T4d5ggD:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/7d3d53401fa5b872448de84f573e7609b70f3097/crates/prover/src/examples/poseidon/mod.rs#L410)):*
> ```XML
> 
>     #[cfg(target_arch = "wasm32")]
>     #[wasm_bindgen_test]
> ```

Done.

**Pull request merged**
