### PR TITLE
Batch inverse cpu quotient denominators.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/559)

### CODE REVIEW

**Comment by alonh5** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/559?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#559** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/559?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#558** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/558?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#556** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/556?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#555** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/555?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/559)* status: 3 of 4 files reviewed, all discussions resolved

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/559)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`src/core/backend/cpu/quotients.rs` line 114 at r3](https://reviewable.io/reviews/starkware-libs/stwo/559#-NuTUlf_6Uodf8677V1t:-NuTUlf_6Uodf8677V1u:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/a46760431b93afa8623382e53c51ead92f01e2ff/src/core/backend/cpu/quotients.rs#L114)):*
> ```XML
>     domain: CircleDomain,
> ) -> Vec<Col<CPUBackend, SecureField>> {
>     let mut flat_denominators = Vec::new();
> ```





_Suggestion:_
```XML
Vec::with_capacity()
```

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/559)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @alonh5)

___
*[`src/core/backend/cpu/quotients.rs` line 134 at r3](https://reviewable.io/reviews/starkware-libs/stwo/559#-NuTWKVr8804y0jztfQo:-NuTWKVr8804y0jztfQp:bqp8v9i) ([raw file](https://github.com/starkware-libs/stwo/blob/a46760431b93afa8623382e53c51ead92f01e2ff/src/core/backend/cpu/quotients.rs#L134)):*
> ```XML
>         .iter()
>         .map(|_| {
>             let denominator_inverses = flat_denominator_inverses.next().unwrap();
> ```

You can iterate flat_denominator_inverses instead.

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/559)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`src/core/backend/cpu/quotients.rs` line 114 at r3](https://reviewable.io/reviews/starkware-libs/stwo/559#-NuTUlf_6Uodf8677V1t:-NuTdxxE1uZuJeeWT_cD:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/a46760431b93afa8623382e53c51ead92f01e2ff/src/core/backend/cpu/quotients.rs#L114)):*
> ```XML
>     domain: CircleDomain,
> ) -> Vec<Col<CPUBackend, SecureField>> {
>     let mut flat_denominators = Vec::new();
> ```

Done.
___
*[`src/core/backend/cpu/quotients.rs` line 134 at r3](https://reviewable.io/reviews/starkware-libs/stwo/559#-NuTWKVr8804y0jztfQo:-NuTeBiw-RyTFB7EUDwJ:b-lbut5x) ([raw file](https://github.com/starkware-libs/stwo/blob/a46760431b93afa8623382e53c51ead92f01e2ff/src/core/backend/cpu/quotients.rs#L134)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

You can iterate flat_denominator_inverses instead.
</blockquote></details>

What do you mean?

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/559)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`src/core/backend/cpu/quotients.rs` line 134 at r3](https://reviewable.io/reviews/starkware-libs/stwo/559#-NuTWKVr8804y0jztfQo:-NuTlrUJCODE_CZ0ivUS:b-cblv4o) ([raw file](https://github.com/starkware-libs/stwo/blob/a46760431b93afa8623382e53c51ead92f01e2ff/src/core/backend/cpu/quotients.rs#L134)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

What do you mean?
</blockquote></details>

Added a suggestion
___
*[`src/core/backend/cpu/quotients.rs` line 140 at r4](https://reviewable.io/reviews/starkware-libs/stwo/559#-NuTliYzBRgMpS5MeUYr:-NuTliYzBRgMpS5MeUYs:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/b1d6d2d7812537486848f5324cfbb4b8ae236331/src/core/backend/cpu/quotients.rs#L140)):*
> ```XML
>             bit_reverse(denominator_inverses);
>             denominator_inverses.to_vec()
>         })
> ```





_Suggestion:_
```XML
    flat_denominator_inverses
        .into_iter()
        .map(|denominator_inverses| {
            bit_reverse(denominator_inverses);
            denominator_inverses.to_vec()
        })
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/559)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`src/core/backend/cpu/quotients.rs` line 140 at r4](https://reviewable.io/reviews/starkware-libs/stwo/559#-NuTliYzBRgMpS5MeUYr:-NuTo9hO50rESCoyZhWT:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/b1d6d2d7812537486848f5324cfbb4b8ae236331/src/core/backend/cpu/quotients.rs#L140)):*
> ```XML
>             bit_reverse(denominator_inverses);
>             denominator_inverses.to_vec()
>         })
> ```

Done.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/559#-:-NuTokjtEgqcXziSXZEZ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Comment by alonh5** [comment]
### Merge activity

* **Apr 2, 9:14 AM EDT**: @alonh5 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/559).

**Pull request merged**
