### PR TITLE
FRI using simple merkle

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/530)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/530?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#531** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/531?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#530** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/530?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#529** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/529?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#528** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/528?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#527** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/527?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#526** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/526?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#525** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/525?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#518** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/518?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by andrewmilson — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/530)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`src/commitment_scheme/prover.rs` line 94 at r2](https://reviewable.io/reviews/starkware-libs/stwo/530#-Ntp1Ob85v4-NcnBv1xD:-Ntp1Ob85v4-NcnBv1xE:b-32igoa) ([raw file](https://github.com/starkware-libs/stwo/blob/c79789761941edd48dea7e87f5a012e5d2ec8d37/src/commitment_scheme/prover.rs#L94)):*
> ```XML
>     pub witness: Vec<H::Hash>,
> }
> impl<H: MerkleHasher> Clone for Decommitment<H> {
> ```

Why not `derive(Clone)`?
___
*[`src/core/fri.rs` line 663 at r2](https://reviewable.io/reviews/starkware-libs/stwo/530#-Ntp12StAVPBUMfXwyLy:-Ntp12StAVPBUMfXwyLz:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/c79789761941edd48dea7e87f5a012e5d2ec8d37/src/core/fri.rs#L663)):*
> ```XML
>             .collect::<Vec<usize>>();
> 
>         let verifier = MerkleTreeVerifier { root: commitment };
> ```





_Suggestion:_
```XML
merkle_verifier
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/530)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @andrewmilson)

___
*[`src/commitment_scheme/prover.rs` line 94 at r2](https://reviewable.io/reviews/starkware-libs/stwo/530#-Ntp1Ob85v4-NcnBv1xD:-NtpU5Xd4ev_syJ7UReP:b-61zzzq) ([raw file](https://github.com/starkware-libs/stwo/blob/c79789761941edd48dea7e87f5a012e5d2ec8d37/src/commitment_scheme/prover.rs#L94)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Why not `derive(Clone)`?
</blockquote></details>

It requires H to be Clone, even though not necessary.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/530)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @andrewmilson)

___
*[`src/core/fri.rs` line 663 at r2](https://reviewable.io/reviews/starkware-libs/stwo/530#-Ntp12StAVPBUMfXwyLy:-NtpULCMEZmI9i1i1zZR:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/c79789761941edd48dea7e87f5a012e5d2ec8d37/src/core/fri.rs#L663)):*
> ```XML
>             .collect::<Vec<usize>>();
> 
>         let verifier = MerkleTreeVerifier { root: commitment };
> ```

Done.

**Review by andrewmilson — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/530#-:-NtrXJRf6rSHDE5s8Pva:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`src/commitment_scheme/prover.rs` line 94 at r2](https://reviewable.io/reviews/starkware-libs/stwo/530#-Ntp1Ob85v4-NcnBv1xD:-NtrW6or2eHYj1-vp0QU:b-4vu2ds) ([raw file](https://github.com/starkware-libs/stwo/blob/c79789761941edd48dea7e87f5a012e5d2ec8d37/src/commitment_scheme/prover.rs#L94)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

It requires H to be Clone, even though not necessary.
</blockquote></details>

Given the approach we take for types with generic backends it might be worth us using something like [derivative](https://crates.io/crates/derivative) which will give us the ability to specify the correct bounds https://mcarton.github.io/rust-derivative/latest/Default.html#custom-bound vs manually implement clone and debug everywhere. Do you mind adding a TODO for me to add this please?

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/530)* status: all files reviewed, 1 unresolved discussion (waiting on @andrewmilson)

___
*[`src/commitment_scheme/prover.rs` line 94 at r2](https://reviewable.io/reviews/starkware-libs/stwo/530#-Ntp1Ob85v4-NcnBv1xD:-NttStSW7x04sX5eHSaj:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/c79789761941edd48dea7e87f5a012e5d2ec8d37/src/commitment_scheme/prover.rs#L94)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Given the approach we take for types with generic backends it might be worth us using something like [derivative](https://crates.io/crates/derivative) which will give us the ability to specify the correct bounds https://mcarton.github.io/rust-derivative/latest/Default.html#custom-bound vs manually implement clone and debug everywhere. Do you mind adding a TODO for me to add this please?
</blockquote></details>

Done.

**Review by andrewmilson — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/530#-:-Ntxw58C8O54aJx79tUF:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by andrewmilson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/530)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`src/commitment_scheme/prover.rs` line 87 at r6](https://reviewable.io/reviews/starkware-libs/stwo/530#-NuIRaCT7CgLRD8JjP86:-NuIRaCT7CgLRD8JjP87:b-ci3v1v) ([raw file](https://github.com/starkware-libs/stwo/blob/bc098910357e7820eca35577531b84b896ae496b/src/commitment_scheme/prover.rs#L87)):*
> ```XML
> 
>         // Check that queries are sorted and deduped.
>         for queries in queries_per_log_size.values() {
> ```

Should the mapping be from log_size to `Queries` to prevent these kinds of checks?

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/530)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @andrewmilson)

___
*[`src/commitment_scheme/prover.rs` line 87 at r6](https://reviewable.io/reviews/starkware-libs/stwo/530#-NuIRaCT7CgLRD8JjP86:-NuXhmFs4sD9Fa4ibDBI:b-rg2n2o) ([raw file](https://github.com/starkware-libs/stwo/blob/bc098910357e7820eca35577531b84b896ae496b/src/commitment_scheme/prover.rs#L87)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Should the mapping be from log_size to `Queries` to prevent these kinds of checks?
</blockquote></details>

I think that might be an overkill here, but added a TODO for you

**Review by andrewmilson — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/530#-:-NuY4pHW0DwfYGoKDOev:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
