### PR TITLE
Eval framework point and domain

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/713)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/713?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#714** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/714?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#713** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/713?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#706** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/706?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#707](https://github.com/starkware-libs/stwo/pull/707) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/707?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#705** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/705?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#704** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/704?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#702** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/702?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#701** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/701?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/713)* status: 1 of 5 files reviewed, 4 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/constraint_framework/domain.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/stwo/713#-O1WSBgZ-tDBqU7KpQXI:-O1WSBgZ-tDBqU7KpQXJ:b-tu9fk1) ([raw file](https://github.com/starkware-libs/stwo/blob/5408ff6b59c802c9c92b8a8e5be0f50fe5d72b75/crates/prover/src/constraint_framework/domain.rs#L1)):*
> ```XML
> use std::ops::Mul;
> ```

Consider to rename to simd_domain.rs
___
*[`crates/prover/src/constraint_framework/domain.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/stwo/713#-O1WQOG51BUM7YqPqyfZ:-O1WQOG51BUM7YqPqyf_:b-9u97z8) ([raw file](https://github.com/starkware-libs/stwo/blob/5408ff6b59c802c9c92b8a8e5be0f50fe5d72b75/crates/prover/src/constraint_framework/domain.rs#L17)):*
> ```XML
> use crate::core::utils::offset_bit_reversed_circle_domain_index;
> 
> /// Evaluates expressions at an evaluation domain rows.
> ```

shouldn't we use here constraint notation?



_Suggestion:_
```XML
/// Evaluates constraints at an evaluation domain points.
```
___
*[`crates/prover/src/constraint_framework/domain.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/stwo/713#-O1WQThR2EY-ogmaSmzP:-O1WQThR2EY-ogmaSmzQ:b-v22xrm) ([raw file](https://github.com/starkware-libs/stwo/blob/5408ff6b59c802c9c92b8a8e5be0f50fe5d72b75/crates/prover/src/constraint_framework/domain.rs#L21)):*
> ```XML
>     pub trace_eval:
>         &'a TreeVec<Vec<&'a CircleEvaluation<SimdBackend, BaseField, BitReversedOrder>>>,
>     pub col_index: Vec<usize>,
> ```

rename as discussed



_Code quote:_
```XML
    pub col_index: Vec<usize>,
```
___
*[`crates/prover/src/constraint_framework/domain.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/stwo/713#-O1WSKxU9kBYTaI4tVoK:-O1WSKxU9kBYTaI4tVoL:b-ckcpzs) ([raw file](https://github.com/starkware-libs/stwo/blob/5408ff6b59c802c9c92b8a8e5be0f50fe5d72b75/crates/prover/src/constraint_framework/domain.rs#L66)):*
> ```XML
>                 return self.trace_eval[interaction][col_index].data[self.vec_row];
>             }
>             PackedBaseField::from_array(std::array::from_fn(|i| {
> ```

Add a comment to explain this



_Code quote:_
```XML
            // TODO(spapini): Optimize.
            if off == 0 {
                return self.trace_eval[interaction][col_index].data[self.vec_row];
            }
            PackedBaseField::from_array(std::array::from_fn(|i| {
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/713)* status: 1 of 5 files reviewed, 4 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/domain.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/stwo/713#-O1WSBgZ-tDBqU7KpQXI:-O1WZhRT7dtsNwtbpBsj:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/5408ff6b59c802c9c92b8a8e5be0f50fe5d72b75/crates/prover/src/constraint_framework/domain.rs#L1)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Consider to rename to simd_domain.rs
</blockquote></details>

Done.
___
*[`crates/prover/src/constraint_framework/domain.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/stwo/713#-O1WQOG51BUM7YqPqyfZ:-O1WZl4t4yHZEBl-a4qF:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/5408ff6b59c802c9c92b8a8e5be0f50fe5d72b75/crates/prover/src/constraint_framework/domain.rs#L17)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

shouldn't we use here constraint notation?
</blockquote></details>

Done.
___
*[`crates/prover/src/constraint_framework/domain.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/stwo/713#-O1WQThR2EY-ogmaSmzP:-O1W_-676O1ytzhTqMhX:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/5408ff6b59c802c9c92b8a8e5be0f50fe5d72b75/crates/prover/src/constraint_framework/domain.rs#L21)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

rename as discussed
</blockquote></details>

Done.
___
*[`crates/prover/src/constraint_framework/domain.rs` line 66 at r1](https://reviewable.io/reviews/starkware-libs/stwo/713#-O1WSKxU9kBYTaI4tVoK:-O1W_OlE3Z8RQgpZaGXq:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/5408ff6b59c802c9c92b8a8e5be0f50fe5d72b75/crates/prover/src/constraint_framework/domain.rs#L66)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Add a comment to explain this
</blockquote></details>

Done.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/713)* status: 2 of 5 files reviewed, 7 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/constraint_framework/mod.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/stwo/713#-O1X-KBIC6EnF3JtZJRE:-O1X-KBIC6EnF3JtZJRF:b-hmz26h) ([raw file](https://github.com/starkware-libs/stwo/blob/5408ff6b59c802c9c92b8a8e5be0f50fe5d72b75/crates/prover/src/constraint_framework/mod.rs#L63)):*
> ```XML
> 
>     /// Combines 4 base field values into a single extension field value.
>     fn combine_ef(values: [Self::F; 4]) -> Self::EF;
> ```

SECURE_EXTENSION_DEGREE

In all places



_Code quote:_
```XML
4
```
___
*[`crates/prover/src/examples/poseidon/mod.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/stwo/713#-O1WsCIv7kMdOdet_MGB:-O1WsCIv7kMdOdet_MGC:b-rkkj32) ([raw file](https://github.com/starkware-libs/stwo/blob/5408ff6b59c802c9c92b8a8e5be0f50fe5d72b75/crates/prover/src/examples/poseidon/mod.rs#L45)):*
> ```XML
> #[derive(Clone)]
> pub struct PoseidonComponent {
>     pub log_n_rows: u32,
> ```

Isn't it better to store log_n_instances?



_Code quote:_
```XML
pub log_n_rows: u32,
```
___
*[`crates/prover/src/examples/poseidon/mod.rs` line 131 at r1](https://reviewable.io/reviews/starkware-libs/stwo/713#-O1WtiMO8Yp-JqHDlOmA:-O1WtiMO8Yp-JqHDlOmB:byp1ktf) ([raw file](https://github.com/starkware-libs/stwo/blob/5408ff6b59c802c9c92b8a8e5be0f50fe5d72b75/crates/prover/src/examples/poseidon/mod.rs#L131)):*
> ```XML
>         let denom = coset_vanishing(constraint_zero_domain, point);
>         let denom_inverse = denom.inverse();
>         let mut eval = PoseidonEval {
> ```

Rename



_Suggestion:_
```XML
let mut poseidon_eval = PoseidonEval {
```
___
*[`crates/prover/src/examples/poseidon/mod.rs` line 380 at r1](https://reviewable.io/reviews/starkware-libs/stwo/713#-O1Wt_Bf4w1lgYBUBpnP:-O1Wt_Bf4w1lgYBUBpnQ:b-i7rm5h) ([raw file](https://github.com/starkware-libs/stwo/blob/5408ff6b59c802c9c92b8a8e5be0f50fe5d72b75/crates/prover/src/examples/poseidon/mod.rs#L380)):*
> ```XML
>             .as_cols_ref()
>             .map_cols(|col| col.evaluate_with_twiddles(eval_domain, &twiddles));
>         let trace_eval_ref = trace_eval.as_ref().map(|t| t.iter().collect_vec());
> ```

Isn't this effectively a clone?



_Code quote:_
```XML
let trace_eval_ref = trace_eval.as_ref().map(|t| t.iter().collect_vec());
```
___
*[`crates/prover/src/constraint_framework/simd_domain.rs` line 22 at r2](https://reviewable.io/reviews/starkware-libs/stwo/713#-O1WsVfu2Ecq_DuslnzH:-O1WsVfu2Ecq_DuslnzI:bt1trtp) ([raw file](https://github.com/starkware-libs/stwo/blob/58006ae14c6bee762181ee3e5ed9450e82ae7e57/crates/prover/src/constraint_framework/simd_domain.rs#L22)):*
> ```XML
>         &'a TreeVec<Vec<&'a CircleEvaluation<SimdBackend, BaseField, BitReversedOrder>>>,
>     pub column_index_per_interaction: Vec<usize>,
>     pub vec_row: usize,
> ```

what's vec_row stands for?



_Suggestion:_
```XML
pub row_index: usize,
```
___
*[`crates/prover/src/constraint_framework/simd_domain.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/stwo/713#-O1WsuqD68mUJD_PrgVo:-O1WsuqEBBQ9sfcELuph:byp1ktf) ([raw file](https://github.com/starkware-libs/stwo/blob/58006ae14c6bee762181ee3e5ed9450e82ae7e57/crates/prover/src/constraint_framework/simd_domain.rs#L27)):*
> ```XML
>     pub constraint_index: usize,
>     pub domain_log_size: u32,
>     pub eval_log_size: u32,
> ```

Rename



_Suggestion:_
```XML
pub eval_domain_log_size: u32,
```
___
*[`crates/prover/src/constraint_framework/simd_domain.rs` line 70 at r2](https://reviewable.io/reviews/starkware-libs/stwo/713#-O1Wr6QM5h5b5ef6j57p:-O1Wr6QN0wSVbw4fB_wd:byp1ktf) ([raw file](https://github.com/starkware-libs/stwo/blob/58006ae14c6bee762181ee3e5ed9450e82ae7e57/crates/prover/src/constraint_framework/simd_domain.rs#L70)):*
> ```XML
>             // at the bit-reversed natural order index at an offset.
>             PackedBaseField::from_array(std::array::from_fn(|i| {
>                 let index = offset_bit_reversed_circle_domain_index(
> ```

Rename



_Suggestion:_
```XML
let row_index = offset_bit_reversed_circle_domain_index(
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/713)* status: 2 of 5 files reviewed, 7 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/mod.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/stwo/713#-O1X-KBIC6EnF3JtZJRE:-O1kBB7d8s5OUFMH3CtJ:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/5408ff6b59c802c9c92b8a8e5be0f50fe5d72b75/crates/prover/src/constraint_framework/mod.rs#L63)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

SECURE_EXTENSION_DEGREE

In all places
</blockquote></details>

Done.
___
*[`crates/prover/src/examples/poseidon/mod.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/stwo/713#-O1WsCIv7kMdOdet_MGB:-O1kBu_E6LsA4nsLBnCQ:b-mkdqij) ([raw file](https://github.com/starkware-libs/stwo/blob/5408ff6b59c802c9c92b8a8e5be0f50fe5d72b75/crates/prover/src/examples/poseidon/mod.rs#L45)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Isn't it better to store log_n_instances?
</blockquote></details>

log_n_rows is a lot more useful. And log_n_instances is not always integer (e.g. if we have 3 repetitions).
___
*[`crates/prover/src/examples/poseidon/mod.rs` line 131 at r1](https://reviewable.io/reviews/starkware-libs/stwo/713#-O1WtiMO8Yp-JqHDlOmA:-O1kC4ip6gIjdGZGorT9:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/5408ff6b59c802c9c92b8a8e5be0f50fe5d72b75/crates/prover/src/examples/poseidon/mod.rs#L131)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Rename
</blockquote></details>

Done.
___
*[`crates/prover/src/examples/poseidon/mod.rs` line 380 at r1](https://reviewable.io/reviews/starkware-libs/stwo/713#-O1Wt_Bf4w1lgYBUBpnP:-O1kC6q8DRCqBaEewgyF:b-f2mjvh) ([raw file](https://github.com/starkware-libs/stwo/blob/5408ff6b59c802c9c92b8a8e5be0f50fe5d72b75/crates/prover/src/examples/poseidon/mod.rs#L380)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Isn't this effectively a clone?
</blockquote></details>

No. It's just references.
___
*[`crates/prover/src/constraint_framework/simd_domain.rs` line 22 at r2](https://reviewable.io/reviews/starkware-libs/stwo/713#-O1WsVfu2Ecq_DuslnzH:-O1kBW3HAxxm75rGW3H5:b-n3cxz4) ([raw file](https://github.com/starkware-libs/stwo/blob/58006ae14c6bee762181ee3e5ed9450e82ae7e57/crates/prover/src/constraint_framework/simd_domain.rs#L22)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

what's vec_row stands for?
</blockquote></details>

It's not the row, it's the row of the vector-of rows table. Since this is SIMD. We currently use vec_row everywhere in the project. We can change them all together in a PR if you like.
___
*[`crates/prover/src/constraint_framework/simd_domain.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/stwo/713#-O1WsuqD68mUJD_PrgVo:-O1kBitv5XSslARFsm6C:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/58006ae14c6bee762181ee3e5ed9450e82ae7e57/crates/prover/src/constraint_framework/simd_domain.rs#L27)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Rename
</blockquote></details>

Done.
___
*[`crates/prover/src/constraint_framework/simd_domain.rs` line 70 at r2](https://reviewable.io/reviews/starkware-libs/stwo/713#-O1Wr6QM5h5b5ef6j57p:-O1kBo155CjuYF6sRrBW:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/58006ae14c6bee762181ee3e5ed9450e82ae7e57/crates/prover/src/constraint_framework/simd_domain.rs#L70)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Rename
</blockquote></details>

Done.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/713#-:-O1kNt459kOVB1nt39x7:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/constraint_framework/mod.rs` line 2 at r3](https://reviewable.io/reviews/starkware-libs/stwo/713#-O1kMrFq0pK2w7pXBeKf:-O1kMrFrAkJorYMcabkc:b-b1t97d) ([raw file](https://github.com/starkware-libs/stwo/blob/5b06d1dc151bb58e0e7a4d294a90dd097e9ce5cc/crates/prover/src/constraint_framework/mod.rs#L2)):*
> ```XML
> mod point;
> /// ! This module contains helpers to express and use constraints for components.
> ```

shouldn't it be the first line?



_Code quote:_
```XML
/// ! This module contains helpers to express and use constraints for components.
```
___
*[`crates/prover/src/constraint_framework/simd_domain.rs` line 22 at r2](https://reviewable.io/reviews/starkware-libs/stwo/713#-O1WsVfu2Ecq_DuslnzH:-O1kNARj4MEtYRStMlpz:bxlzrtf) ([raw file](https://github.com/starkware-libs/stwo/blob/58006ae14c6bee762181ee3e5ed9450e82ae7e57/crates/prover/src/constraint_framework/simd_domain.rs#L22)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

It's not the row, it's the row of the vector-of rows table. Since this is SIMD. We currently use vec_row everywhere in the project. We can change them all together in a PR if you like.
</blockquote></details>

Ok, 
Let's consider changing it to packed_row (in a different pr as you said)

**Review by shaharsamocha7 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/713)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Comment by spapinistarkware** [comment]
### Merge activity

* **Jul 14, 8:05 AM EDT**: @spapinistarkware merged this pull request with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/713).

**Pull request merged**
