### PR TITLE
CommitmentScheme utils

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/500)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/500?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#496** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/496?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#495** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/495?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#494** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/494?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#493** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/493?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#492** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/492?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#491** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/491?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#490** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/490?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#489** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/489?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#488** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/488?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#487** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/487?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#486** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/486?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#484** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/484?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#483** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/483?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#482** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/482?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#481** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/481?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#480** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/480?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#479** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/479?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#478** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/478?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#463** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/463?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#477** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/477?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#476** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/476?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#501** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/501?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#500** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/500?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#499** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/499?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/500)* status: 2 of 5 files reviewed, 12 unresolved discussions (waiting on @spapinistarkware)

___
*[`src/core/air/component_visitors.rs` line 86 at r1](https://reviewable.io/reviews/starkware-libs/stwo/500#-NtBWpB83-mgrKE9e8CK:-NtBWpB83-mgrKE9e8CL:b-ffeuhi) ([raw file](https://github.com/starkware-libs/stwo/blob/c6adf13d7de143ba3c6f8e5a3275ecadc54a1d78/src/core/air/component_visitors.rs#L86)):*
> ```XML
>                 let trace = self.component_traces.next().unwrap();
>                 let (points, values) = component.mask_points_and_values(self.point, trace);
>                 self.component_points.0.push(points);
> ```

You should be able to remove these throughout the PR.



_Code quote:_
```XML
.0
```
___
*[`src/core/air/component_visitors.rs` line 205 at r2](https://reviewable.io/reviews/starkware-libs/stwo/500#-NtBXkWI-R2Hvq2AQizL:-NtBXkWI-R2Hvq2AQizM:b-p4b9ws) ([raw file](https://github.com/starkware-libs/stwo/blob/33328a46d03d56d915797243e4b07af426aa14b6/src/core/air/component_visitors.rs#L205)):*
> ```XML
>     }
> 
>     /// Returns the log degree bounds of the quotient polynomials in descending order.
> ```

Can you please move this comment to the function above? This is a mistake I made in a previous PR.



_Code quote:_
```XML
/// Returns the log degree bounds of the quotient polynomials in descending order.
```
___
*[`src/core/air/component_visitors.rs` line 206 at r2](https://reviewable.io/reviews/starkware-libs/stwo/500#-NtBY-a-3Z7ltfK2pvI3:-NtBY-a-3Z7ltfK2pvI4:bcgjvre) ([raw file](https://github.com/starkware-libs/stwo/blob/33328a46d03d56d915797243e4b07af426aa14b6/src/core/air/component_visitors.rs#L206)):*
> ```XML
> 
>     /// Returns the log degree bounds of the quotient polynomials in descending order.
>     fn column_log_sizes(&self) -> Vec<u32> {
> ```

Why this change?
___
*[`src/core/air/component_visitors.rs` line 207 at r2](https://reviewable.io/reviews/starkware-libs/stwo/500#-NtBY3vhD55qWe24XIm4:-NtBY3vhD55qWe24XIm5:b-85x9up) ([raw file](https://github.com/starkware-libs/stwo/blob/33328a46d03d56d915797243e4b07af426aa14b6/src/core/air/component_visitors.rs#L207)):*
> ```XML
>     /// Returns the log degree bounds of the quotient polynomials in descending order.
>     fn column_log_sizes(&self) -> Vec<u32> {
>         struct DomainsVisitor {
> ```

Please rename.



_Code quote:_
```XML
DomainsVisitor
```
___
*[`src/core/commitment_scheme/utils.rs` line 11 at r2](https://reviewable.io/reviews/starkware-libs/stwo/500#-NtBb3yMEJLCyKcoaFUE:-NtBb3yMEJLCyKcoaFUF:br4yiuq) ([raw file](https://github.com/starkware-libs/stwo/blob/33328a46d03d56d915797243e4b07af426aa14b6/src/core/commitment_scheme/utils.rs#L11)):*
> ```XML
> #[derive(Debug, Clone)]
> pub struct TreeVec<T>(pub Vec<T>);
> impl<T> TreeVec<T> {
> ```

Are all of these methods needed and used?
___
*[`src/core/commitment_scheme/utils.rs` line 95 at r2](https://reviewable.io/reviews/starkware-libs/stwo/500#-NtBclzEAXsaNkvvFiZv:-NtBclzF7acW_og_KdbB:bt1tcp6) ([raw file](https://github.com/starkware-libs/stwo/blob/33328a46d03d56d915797243e4b07af426aa14b6/src/core/commitment_scheme/utils.rs#L95)):*
> ```XML
>     }
>     /// Flattens the [TreeColumns] into a single [ColumnVec] with all the columns combined.
>     pub fn flatten(self) -> ColumnVec<T> {
> ```

Then it's just a `Vec`.



_Suggestion:_
```XML
Vec
```
___
*[`src/core/prover/mod.rs` line 178 at r2](https://reviewable.io/reviews/starkware-libs/stwo/500#-NtBYsqCBV4tbbVcplK3:-NtBYsqCBV4tbbVcplK4:b-5v7yv5) ([raw file](https://github.com/starkware-libs/stwo/blob/33328a46d03d56d915797243e4b07af426aa14b6/src/core/prover/mod.rs#L178)):*
> ```XML
>         .collect_vec();
>     commitment_domains.push(CanonicCoset::new(
>         air.max_constraint_log_degree_bound() + LOG_BLOWUP_FACTOR,
> ```

We should rename this right? The current name is more suiting for components.



_Suggestion:_
```XML
composition_polynomial_log_degree_bound
```
___
*[`src/core/prover/utils.rs` line 1 at r2](https://reviewable.io/reviews/starkware-libs/stwo/500#-NtBgZpHCM6LrgyP8hNB:-NtBgZpHCM6LrgyP8hNC:b-bbw133) ([raw file](https://github.com/starkware-libs/stwo/blob/33328a46d03d56d915797243e4b07af426aa14b6/src/core/prover/utils.rs#L1)):*
> ```XML
> use crate::core::air::{Air, Component, ComponentVisitor};
> ```

What should both of these functions be doing? ATM they are not symmetrical IIUC. The first takes a ComponentVec and turns it into a TreeColumns containing a single tree, and the second can take a TreeColumns containing multiple trees and turns it into a single ComponentVec.

Also I think we should add unit tests for these.
___
*[`src/core/prover/utils.rs` line 7 at r2](https://reviewable.io/reviews/starkware-libs/stwo/500#-NtBctzV3mWbBSG4hsb5:-NtBctzV3mWbBSG4hsb6:byprqdp) ([raw file](https://github.com/starkware-libs/stwo/blob/33328a46d03d56d915797243e4b07af426aa14b6/src/core/prover/utils.rs#L7)):*
> ```XML
> 
> pub fn component_wise_to_tree_wise<T>(
>     _air: &impl Air<CPUBackend>,
> ```

Why keep this arg?



_Code quote:_
```XML
    _air: &impl Air<CPUBackend>,
```
___
*[`src/core/prover/utils.rs` line 26 at r2](https://reviewable.io/reviews/starkware-libs/stwo/500#-NtBe9Z37NPDPtoplDFF:-NtBe9Z45nstG0AwJ5CU:b-cjvq1b) ([raw file](https://github.com/starkware-libs/stwo/blob/33328a46d03d56d915797243e4b07af426aa14b6/src/core/prover/utils.rs#L26)):*
> ```XML
>             self.by_component
>                 .0
>                 .push(self.by_tree.take(component.mask().len()).collect());
> ```

Can you make sure this is mutating `self.by_tree`? In other places Io had to do `(&mut self.by_tree).take`.



_Code quote:_
```XML
self.by_tree.take
```
___
*[`src/core/prover/utils.rs` line 26 at r2](https://reviewable.io/reviews/starkware-libs/stwo/500#-NtBfo2tBC8V-DXhLqzv:-NtBfo2tBC8V-DXhLqzw:bunzhjv) ([raw file](https://github.com/starkware-libs/stwo/blob/33328a46d03d56d915797243e4b07af426aa14b6/src/core/prover/utils.rs#L26)):*
> ```XML
>             self.by_component
>                 .0
>                 .push(self.by_tree.take(component.mask().len()).collect());
> ```

Shouldn't you be taking the number of columns and not the number of mask items?



_Code quote:_
```XML
component.mask().len()
```
___
*[`src/core/prover/utils.rs` line 29 at r2](https://reviewable.io/reviews/starkware-libs/stwo/500#-NtBf1WaEcwOOJRrpE0Q:-NtBf1WaEcwOOJRrpE0R:btxqyja) ([raw file](https://github.com/starkware-libs/stwo/blob/33328a46d03d56d915797243e4b07af426aa14b6/src/core/prover/utils.rs#L29)):*
> ```XML
>         }
>     }
>     let values = values.0.remove(0);
> ```

Can you explain please?



_Code quote:_
```XML
let values = values.0.remove(0);
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/500)* status: 1 of 9 files reviewed, 7 unresolved discussions (waiting on @alonh5)

___
*[`src/core/commitment_scheme/utils.rs` line 11 at r2](https://reviewable.io/reviews/starkware-libs/stwo/500#-NtBb3yMEJLCyKcoaFUE:-NtBkBj0AUDjTYDfIWDn:bb77ufg) ([raw file](https://github.com/starkware-libs/stwo/blob/33328a46d03d56d915797243e4b07af426aa14b6/src/core/commitment_scheme/utils.rs#L11)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Are all of these methods needed and used?
</blockquote></details>

Yes.
___
*[`src/core/commitment_scheme/utils.rs` line 95 at r2](https://reviewable.io/reviews/starkware-libs/stwo/500#-NtBclzEAXsaNkvvFiZv:-NtBkHDe61AFe8Na24S6:bozludk) ([raw file](https://github.com/starkware-libs/stwo/blob/33328a46d03d56d915797243e4b07af426aa14b6/src/core/commitment_scheme/utils.rs#L95)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Then it's just a `Vec`.
</blockquote></details>

Why just a vec? It's an element per column.
___
*[`src/core/air/component_visitors.rs` line 86 at r1](https://reviewable.io/reviews/starkware-libs/stwo/500#-NtBWpB83-mgrKE9e8CK:-NtGPICQ0v9lKvf6ucoZ:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/c6adf13d7de143ba3c6f8e5a3275ecadc54a1d78/src/core/air/component_visitors.rs#L86)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

You should be able to remove these throughout the PR.
</blockquote></details>

Done.
___
*[`src/core/air/component_visitors.rs` line 205 at r2](https://reviewable.io/reviews/starkware-libs/stwo/500#-NtBXkWI-R2Hvq2AQizL:-NtGPW1zEeAwOufnEat_:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/33328a46d03d56d915797243e4b07af426aa14b6/src/core/air/component_visitors.rs#L205)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Can you please move this comment to the function above? This is a mistake I made in a previous PR.
</blockquote></details>

Done.
___
*[`src/core/air/component_visitors.rs` line 207 at r2](https://reviewable.io/reviews/starkware-libs/stwo/500#-NtBY3vhD55qWe24XIm4:-NtGPY177tudV7fVKhvH:bl84e85) ([raw file](https://github.com/starkware-libs/stwo/blob/33328a46d03d56d915797243e4b07af426aa14b6/src/core/air/component_visitors.rs#L207)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Please rename.
</blockquote></details>

Still relevant?
___
*[`src/core/prover/utils.rs` line 1 at r2](https://reviewable.io/reviews/starkware-libs/stwo/500#-NtBgZpHCM6LrgyP8hNB:-NtGOuF-0IqLwdawzv19:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/33328a46d03d56d915797243e4b07af426aa14b6/src/core/prover/utils.rs#L1)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

What should both of these functions be doing? ATM they are not symmetrical IIUC. The first takes a ComponentVec and turns it into a TreeColumns containing a single tree, and the second can take a TreeColumns containing multiple trees and turns it into a single ComponentVec.

Also I think we should add unit tests for these.
</blockquote></details>

Done.
___
*[`src/core/prover/utils.rs` line 7 at r2](https://reviewable.io/reviews/starkware-libs/stwo/500#-NtBctzV3mWbBSG4hsb5:-NtGKX2B7Waibq498jAA:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/33328a46d03d56d915797243e4b07af426aa14b6/src/core/prover/utils.rs#L7)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Why keep this arg?
</blockquote></details>

Done.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/500)* status: 1 of 9 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`src/core/commitment_scheme/utils.rs` line 56 at r4](https://reviewable.io/reviews/starkware-libs/stwo/500#-NtL9KGl4rtFVj2yJyz9:-NtL9KGl4rtFVj2yJyzA:bx8tcp6) ([raw file](https://github.com/starkware-libs/stwo/blob/bdd9702ae84b1a720d1ef3c347c4367f6aade16e/src/core/commitment_scheme/utils.rs#L56)):*
> ```XML
> /// A container that holds an element for each column of each commitment tree.
> #[derive(Debug, Clone)]
> pub struct TreeColumns<T>(pub TreeVec<ColumnVec<T>>);
> ```

Why do you need this wrapper type? Isn't it enough to use `TreeVec<ColumnVec>`?

**Review by alonh5 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/500)* status: 1 of 9 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`src/core/prover/utils.rs` line 1 at r2](https://reviewable.io/reviews/starkware-libs/stwo/500#-NtBgZpHCM6LrgyP8hNB:-NtL9pHQ1fWCy4xNK64X:b-gdgdsb) ([raw file](https://github.com/starkware-libs/stwo/blob/33328a46d03d56d915797243e4b07af426aa14b6/src/core/prover/utils.rs#L1)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

To which branch did these move?

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/500)* status: 1 of 9 files reviewed, 3 unresolved discussions (waiting on @alonh5)

___
*[`src/core/commitment_scheme/utils.rs` line 56 at r4](https://reviewable.io/reviews/starkware-libs/stwo/500#-NtL9KGl4rtFVj2yJyz9:-NtLWET-5W-NDOFOT0lW:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/bdd9702ae84b1a720d1ef3c347c4367f6aade16e/src/core/commitment_scheme/utils.rs#L56)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Why do you need this wrapper type? Isn't it enough to use `TreeVec<ColumnVec>`?
</blockquote></details>

Done.
___
*[`src/core/prover/utils.rs` line 1 at r2](https://reviewable.io/reviews/starkware-libs/stwo/500#-NtBgZpHCM6LrgyP8hNB:-NtGKWoC6w3EW_NaoRQo:be5driu) ([raw file](https://github.com/starkware-libs/stwo/blob/33328a46d03d56d915797243e4b07af426aa14b6/src/core/prover/utils.rs#L1)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

To which branch did these move?
</blockquote></details>

They were eliminated, I didnt want them.

**Review by alonh5 — COMMENTED** [review]
> Reviewed 5 of 7 files at r4, 2 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/500)* status: 8 of 9 files reviewed, 1 unresolved discussion

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/500)* status: all files reviewed, 6 unresolved discussions (waiting on @spapinistarkware)

___
*[`src/core/commitment_scheme/utils.rs` line 1 at r5](https://reviewable.io/reviews/starkware-libs/stwo/500#-NtM1FF_8e2CIyC0FUj1:-NtM1FF_8e2CIyC0FUj2:b-7f6ryu) ([raw file](https://github.com/starkware-libs/stwo/blob/8d744c3993e1df8763ad85c3b0a1fb689403440c/src/core/commitment_scheme/utils.rs#L1)):*
> ```XML
> use std::iter::zip;
> ```

Please add blank lines between code blocks.
___
*[`src/core/commitment_scheme/utils.rs` line 16 at r5](https://reviewable.io/reviews/starkware-libs/stwo/500#-NtLyWru-48R3G69cL_W:-NtLyWru-48R3G69cL_X:buxmp34) ([raw file](https://github.com/starkware-libs/stwo/blob/8d744c3993e1df8763ad85c3b0a1fb689403440c/src/core/commitment_scheme/utils.rs#L16)):*
> ```XML
>     }
>     pub fn map<U, F: Fn(T) -> U>(self, f: F) -> TreeVec<U> {
>         TreeVec(self.0.into_iter().map(f).collect())
> ```

Can you remove all of these?



_Code quote:_
```XML
.0
```
___
*[`src/core/commitment_scheme/utils.rs` line 27 at r5](https://reviewable.io/reviews/starkware-libs/stwo/500#-NtM-0Z3EdCxsXkkycHa:-NtM-0Z3EdCxsXkkycHb:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/8d744c3993e1df8763ad85c3b0a1fb689403440c/src/core/commitment_scheme/utils.rs#L27)):*
> ```XML
>     }
> }
> // Converts &TreeVec<T> to TreeVec<&T>.
> ```





_Suggestion:_
```XML
/// Converts &TreeVec<T> to TreeVec<&T>.
```
___
*[`src/core/commitment_scheme/utils.rs` line 67 at r5](https://reviewable.io/reviews/starkware-libs/stwo/500#-NtM05Nn7I93MBx2sg5z:-NtM05Nn7I93MBx2sg6-:bll0t9w) ([raw file](https://github.com/starkware-libs/stwo/blob/8d744c3993e1df8763ad85c3b0a1fb689403440c/src/core/commitment_scheme/utils.rs#L67)):*
> ```XML
>     ) -> TreeVec<ColumnVec<(T, U)>> {
>         let other = other.into();
>         assert_eq!(self.0.len(), other.0.len());
> ```

Maybe also use `zip_eq`?



_Code quote:_
```XML
assert_eq!(self.0.len(), other.0.len());
```
___
*[`src/core/commitment_scheme/utils.rs` line 84 at r5](https://reviewable.io/reviews/starkware-libs/stwo/500#-NtM0O06154bsMbsOVjX:-NtM0O079B2YIcelqMSy:b-2uc5ym) ([raw file](https://github.com/starkware-libs/stwo/blob/8d744c3993e1df8763ad85c3b0a1fb689403440c/src/core/commitment_scheme/utils.rs#L84)):*
> ```XML
>         )
>     }
>     /// Flattens the [TreeColumns] into a single [ColumnVec] with all the columns combined.
> ```

Same below.



_Suggestion:_
```XML
/// Flattens the [TreeVec]
```
___
*[`src/core/commitment_scheme/utils.rs` line 97 at r5](https://reviewable.io/reviews/starkware-libs/stwo/500#-NtM0ryp7h-jBebAMUj1:-NtM0ryp7h-jBebAMUj2:bhwwiau) ([raw file](https://github.com/starkware-libs/stwo/blob/8d744c3993e1df8763ad85c3b0a1fb689403440c/src/core/commitment_scheme/utils.rs#L97)):*
> ```XML
>     /// Flattens a [TreeColumns] of [Vec]s into a single [Vec] with all the elements combined.
>     pub fn flatten_all(self) -> Vec<T> {
>         self.flatten().into_iter().flatten().collect()
> ```

The intermediate `collect()` is optimized out right?



_Code quote:_
```XML
self.flatten().into_iter().flatten().collect()
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/500)* status: all files reviewed, 5 unresolved discussions (waiting on @alonh5)

___
*[`src/core/commitment_scheme/utils.rs` line 1 at r5](https://reviewable.io/reviews/starkware-libs/stwo/500#-NtM1FF_8e2CIyC0FUj1:-NtM3VYj8yzOKYaxL6h5:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/8d744c3993e1df8763ad85c3b0a1fb689403440c/src/core/commitment_scheme/utils.rs#L1)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Please add blank lines between code blocks.
</blockquote></details>

Done.
___
*[`src/core/commitment_scheme/utils.rs` line 16 at r5](https://reviewable.io/reviews/starkware-libs/stwo/500#-NtLyWru-48R3G69cL_W:-NtM3qV85vtj4qywB3-g:b7vygy3) ([raw file](https://github.com/starkware-libs/stwo/blob/8d744c3993e1df8763ad85c3b0a1fb689403440c/src/core/commitment_scheme/utils.rs#L16)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Can you remove all of these?
</blockquote></details>

Removed wherever I could
___
*[`src/core/commitment_scheme/utils.rs` line 27 at r5](https://reviewable.io/reviews/starkware-libs/stwo/500#-NtM-0Z3EdCxsXkkycHa:-NtM4awK0DUHgZQJ6il1:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/8d744c3993e1df8763ad85c3b0a1fb689403440c/src/core/commitment_scheme/utils.rs#L27)):*
> ```XML
>     }
> }
> // Converts &TreeVec<T> to TreeVec<&T>.
> ```

Done.
___
*[`src/core/commitment_scheme/utils.rs` line 84 at r5](https://reviewable.io/reviews/starkware-libs/stwo/500#-NtM0O06154bsMbsOVjX:-NtM4Mgo91vpeseAtPJS:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/8d744c3993e1df8763ad85c3b0a1fb689403440c/src/core/commitment_scheme/utils.rs#L84)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Same below.
</blockquote></details>

Done.
___
*[`src/core/commitment_scheme/utils.rs` line 97 at r5](https://reviewable.io/reviews/starkware-libs/stwo/500#-NtM0ryp7h-jBebAMUj1:-NtM4PyN4S3p4eJBcJRc:bqyogzk) ([raw file](https://github.com/starkware-libs/stwo/blob/8d744c3993e1df8763ad85c3b0a1fb689403440c/src/core/commitment_scheme/utils.rs#L97)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

The intermediate `collect()` is optimized out right?
</blockquote></details>

Not sure what you mean. There is one collect at the end, and it's not optimized out. It builds a new vec. But there are no clones of T here.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/500)* status: all files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`src/core/commitment_scheme/utils.rs` line 1 at r5](https://reviewable.io/reviews/starkware-libs/stwo/500#-NtM1FF_8e2CIyC0FUj1:-NtM6F6O-dr7jrxKqSaM:bu8o8w5) ([raw file](https://github.com/starkware-libs/stwo/blob/8d744c3993e1df8763ad85c3b0a1fb689403440c/src/core/commitment_scheme/utils.rs#L1)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Also between functions? That's how I see it is in other crates.
___
*[`src/core/commitment_scheme/utils.rs` line 97 at r5](https://reviewable.io/reviews/starkware-libs/stwo/500#-NtM0ryp7h-jBebAMUj1:-NtM5QSJ7e5JL7NCu3Ly:bok4bsz) ([raw file](https://github.com/starkware-libs/stwo/blob/8d744c3993e1df8763ad85c3b0a1fb689403440c/src/core/commitment_scheme/utils.rs#L97)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Not sure what you mean. There is one collect at the end, and it's not optimized out. It builds a new vec. But there are no clones of T here.
</blockquote></details>

I mean the first `flatten()` iterates and collects, and then you iterate and collect again. The alternative would be this:
```
self.into_iter().flatten().flatten().collect()
```
___
*[`src/core/commitment_scheme/utils.rs` line 72 at r6](https://reviewable.io/reviews/starkware-libs/stwo/500#-NtM6Jzm8YjkLiAUpT2w:-NtM6Jzm8YjkLiAUpT2x:b-hokrd7) ([raw file](https://github.com/starkware-libs/stwo/blob/d05d2b024914135a764726b2a0a2a6e85def9923/src/core/commitment_scheme/utils.rs#L72)):*
> ```XML
>     ) -> TreeVec<ColumnVec<(T, U)>> {
>         let other = other.into();
>         assert_eq!(self.len(), other.len());
> ```

You can remove this now with the `zip_eq`?
Same in `TreeVec::zip()`.



_Code quote:_
```XML
assert_eq!(self.len(), other.len());
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/500)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5)

___
*[`src/core/commitment_scheme/utils.rs` line 1 at r5](https://reviewable.io/reviews/starkware-libs/stwo/500#-NtM1FF_8e2CIyC0FUj1:-NtM7qSLCtpBrE7HKvVx:b9rnwqi) ([raw file](https://github.com/starkware-libs/stwo/blob/8d744c3993e1df8763ad85c3b0a1fb689403440c/src/core/commitment_scheme/utils.rs#L1)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Also between functions? That's how I see it is in other crates.
</blockquote></details>

Nah, I think it's good as it is.
___
*[`src/core/commitment_scheme/utils.rs` line 97 at r5](https://reviewable.io/reviews/starkware-libs/stwo/500#-NtM0ryp7h-jBebAMUj1:-NtM7yAr6RZ5FTeALBc6:b-t040b4) ([raw file](https://github.com/starkware-libs/stwo/blob/8d744c3993e1df8763ad85c3b0a1fb689403440c/src/core/commitment_scheme/utils.rs#L97)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I mean the first `flatten()` iterates and collects, and then you iterate and collect again. The alternative would be this:
```
self.into_iter().flatten().flatten().collect()
```
</blockquote></details>

Got it. Changed.
___
*[`src/core/commitment_scheme/utils.rs` line 72 at r6](https://reviewable.io/reviews/starkware-libs/stwo/500#-NtM6Jzm8YjkLiAUpT2w:-NtM7wcxEVTv7ZD8JeXH:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/d05d2b024914135a764726b2a0a2a6e85def9923/src/core/commitment_scheme/utils.rs#L72)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

You can remove this now with the `zip_eq`?
Same in `TreeVec::zip()`.
</blockquote></details>

Done.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/500#-:-NtMA5LECt1xojwROQ5E:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`src/core/commitment_scheme/utils.rs` line 22 at r7](https://reviewable.io/reviews/starkware-libs/stwo/500#-NtM9xBVAcTdxiunFX2V:-NtM9xBVAcTdxiunFX2W:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/fc18b4da2daf941c4cddf497d7a9eda4eadcc314/src/core/commitment_scheme/utils.rs#L22)):*
> ```XML
>         let other = other.into();
>         assert_eq!(self.len(), other.len());
>         TreeVec(zip(self.0, other.0).collect())
> ```





_Suggestion:_
```XML
        TreeVec(zip_eq(self.0, other.0).collect())
```

**Review by alonh5 — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/500)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
