### PR TITLE
Enable 'rng.gen()'ing field types

### PR DESCRIPTION
**Pull request by andrewmilson**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/591)

### CODE REVIEW

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 13 of 16 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/591)* status: all files reviewed, 3 unresolved discussions (waiting on @andrewmilson)

___
*[`crates/prover/benches/field.rs` line 12 at r2](https://reviewable.io/reviews/starkware-libs/stwo/591#-NwnBG5B8kwVAp06uwf6:-NwnBG5B8kwVAp06uwf7:bimb4h3) ([raw file](https://github.com/starkware-libs/stwo/blob/a5e2491cb853f1aeade49b6d353d74d217b18546/crates/prover/benches/field.rs#L12)):*
> ```XML
> 
> pub fn m31_operations_bench(c: &mut criterion::Criterion) {
>     let mut rng = SmallRng::seed_from_u64(0);
> ```

This will always generate the same values, why not use `from_entropy()`? It's in the default-features and I noticed you disabled them.
Same for rest of PR.



_Code quote:_
```XML
let mut rng = SmallRng::seed_from_u64(0);
```
___
*[`crates/prover/src/core/backend/avx512/cm31.rs` line 118 at r2](https://reviewable.io/reviews/starkware-libs/stwo/591#-NwnJ74y17yVYwmFHGEX:-NwnJ74y17yVYwmFHGEY:bp3yw15) ([raw file](https://github.com/starkware-libs/stwo/blob/a5e2491cb853f1aeade49b6d353d74d217b18546/crates/prover/src/core/backend/avx512/cm31.rs#L118)):*
> ```XML
>         let mut rng = SmallRng::seed_from_u64(0);
>         let x = PackedCM31([
>             PackedBaseField::from_array(std::array::from_fn(|_| M31::from(rng.gen::<u32>() % P))),
> ```

Same in rest of PR.



_Suggestion:_
```XML
rng.gen()
```
___
*[`crates/prover/src/core/fields/m31.rs` line 129 at r1](https://reviewable.io/reviews/starkware-libs/stwo/591#-Nwkfd2RDRnCvpgJXAKF:-NwnJsrWEfPUOct0axbu:b-699ugo) ([raw file](https://github.com/starkware-libs/stwo/blob/63146487b73849abf3e5b1b7ab33a19f8f94ebea/crates/prover/src/core/fields/m31.rs#L129)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

I thought about only implementing these for `#[cfg(test)]` but it meant it wasn't implemented for benchmarks
</blockquote></details>

I think this is fine. Maybe add a comment it's not meant to be used for cryptography and therefore only for testing.

**Comment by andrewmilson** [comment]
* **#596** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/596?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#595** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/595?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#594** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/594?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#593** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/593?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#592** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/592?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#591** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/591?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @andrewmilson and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/591)* status: 9 of 17 files reviewed, 2 unresolved discussions (waiting on @alonh5)

___
*[`crates/prover/benches/field.rs` line 12 at r2](https://reviewable.io/reviews/starkware-libs/stwo/591#-NwnBG5B8kwVAp06uwf6:-NwoPV4B7fJgg9TY_YDM:b3ziz8b) ([raw file](https://github.com/starkware-libs/stwo/blob/a5e2491cb853f1aeade49b6d353d74d217b18546/crates/prover/benches/field.rs#L12)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

This will always generate the same values, why not use `from_entropy()`? It's in the default-features and I noticed you disabled them.
Same for rest of PR.
</blockquote></details>

Generating the same values is a good thing as otherwise our tests are no longer reproducible which is bad.
___
*[`crates/prover/src/core/backend/avx512/cm31.rs` line 118 at r2](https://reviewable.io/reviews/starkware-libs/stwo/591#-NwnJ74y17yVYwmFHGEX:-NwoTtNV2jPZkTliTmvv:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/a5e2491cb853f1aeade49b6d353d74d217b18546/crates/prover/src/core/backend/avx512/cm31.rs#L118)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Same in rest of PR.
</blockquote></details>

Done.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 8 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/591#-:-NwoZjl12V6F-b7EDl-T:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @andrewmilson)

___
*[`crates/prover/benches/field.rs` line 12 at r2](https://reviewable.io/reviews/starkware-libs/stwo/591#-NwnBG5B8kwVAp06uwf6:-NwoYWepCY09YFs41-4F:bl3uf7b) ([raw file](https://github.com/starkware-libs/stwo/blob/a5e2491cb853f1aeade49b6d353d74d217b18546/crates/prover/benches/field.rs#L12)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Generating the same values is a good thing as otherwise our tests are no longer reproducible which is bad.
</blockquote></details>

Okay, I agree. Also for benching?

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/591)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/prover/benches/field.rs` line 12 at r2](https://reviewable.io/reviews/starkware-libs/stwo/591#-NwnBG5B8kwVAp06uwf6:-Nwoage64VcyqrVddGOP:b-veg6h) ([raw file](https://github.com/starkware-libs/stwo/blob/a5e2491cb853f1aeade49b6d353d74d217b18546/crates/prover/benches/field.rs#L12)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Okay, I agree. Also for benching?
</blockquote></details>

Sure, would be bad if `from_entropy` values crashed a benchmark sporadically.

Less important but still worth noting that I believe from_entropy has issues when building for some targets i.e. WebAssembly.

**Review by alonh5 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/591)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @andrewmilson)

**Pull request merged**
