### PR TITLE
Eval framework asserts

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/714)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/714?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#714** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/714?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#713** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/713?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#706** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/706?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#707](https://github.com/starkware-libs/stwo/pull/707) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/707?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#705** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/705?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#704** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/704?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#702** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/702?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#701** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/701?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/714)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/prover/src/constraint_framework/mod.rs` line 2 at r1](https://reviewable.io/reviews/starkware-libs/stwo/714#-O1X5PUV1dxo9jMKVLeK:-O1X5PUV1dxo9jMKVLeL:b96so06) ([raw file](https://github.com/starkware-libs/stwo/blob/86be1d9a4c62a8f6b714b34a9a93e27437ae732e/crates/prover/src/constraint_framework/mod.rs#L2)):*
> ```XML
> /// ! This module contains helpers to express and use constraints for components.
> mod assert;
> ```

Is this uses only for tests?



_Code quote:_
```XML
mod assert;
```

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/714)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/constraint_framework/assert.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/stwo/714#-O1k1owK1RxkaLDRaBIP:-O1k1owK1RxkaLDRaBIQ:b-flkfdx) ([raw file](https://github.com/starkware-libs/stwo/blob/86be1d9a4c62a8f6b714b34a9a93e27437ae732e/crates/prover/src/constraint_framework/assert.rs#L38)):*
> ```XML
>         offsets.map(|off| {
>             self.trace[interaction][col_index][(self.row as isize + off)
>                 .rem_euclid(self.trace[interaction][col_index].len() as isize)
> ```

Can you extract this to a variable `col_length`?
I think it will make it more clear

Maybe also add a comment that the mask overflows



_Code quote:_
```XML
self.trace[interaction][col_index].len() as isize
```
___
*[`crates/prover/src/constraint_framework/assert.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/stwo/714#-O1k2HpvA3dpt-oVHB7X:-O1k2HpvA3dpt-oVHB7Y:bkcha2o) ([raw file](https://github.com/starkware-libs/stwo/blob/86be1d9a4c62a8f6b714b34a9a93e27437ae732e/crates/prover/src/constraint_framework/assert.rs#L48)):*
> ```XML
>     {
>         let res = SecureField::one() * constraint;
>         assert_eq!(res, SecureField::zero(), "row: {}", self.row);
> ```

Add a comment that we expect this to be zero because we evaluate directly on the trace points.
Not sure if it belongs here or in the doc of AssertEvaluator



_Code quote:_
```XML
assert_eq!(res, SecureField::zero(), "row: {}", self.row);
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/714)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/assert.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/stwo/714#-O1k1owK1RxkaLDRaBIP:-O1kCt4q3EBsLx6mT-ni:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/86be1d9a4c62a8f6b714b34a9a93e27437ae732e/crates/prover/src/constraint_framework/assert.rs#L38)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can you extract this to a variable `col_length`?
I think it will make it more clear

Maybe also add a comment that the mask overflows
</blockquote></details>

Done.
___
*[`crates/prover/src/constraint_framework/assert.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/stwo/714#-O1k2HpvA3dpt-oVHB7X:-O1kDA6D5qOH2rowzUiL:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/86be1d9a4c62a8f6b714b34a9a93e27437ae732e/crates/prover/src/constraint_framework/assert.rs#L48)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Add a comment that we expect this to be zero because we evaluate directly on the trace points.
Not sure if it belongs here or in the doc of AssertEvaluator
</blockquote></details>

Done.
___
*[`crates/prover/src/constraint_framework/mod.rs` line 2 at r1](https://reviewable.io/reviews/starkware-libs/stwo/714#-O1X5PUV1dxo9jMKVLeK:-O1kDBChBi9XvEA_Oclc:bjnd9q6) ([raw file](https://github.com/starkware-libs/stwo/blob/86be1d9a4c62a8f6b714b34a9a93e27437ae732e/crates/prover/src/constraint_framework/mod.rs#L2)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Is this uses only for tests?
</blockquote></details>

It won't be on production. But very useful for debugging, from experience.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/714)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/constraint_framework/assert.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/stwo/714#-O1kO31SBpHRqITr40LB:-O1kO31SBpHRqITr40LC:baf6zlm) ([raw file](https://github.com/starkware-libs/stwo/blob/1ee181a3be5c351f6a179718b57778f0b85a0ba1/crates/prover/src/constraint_framework/assert.rs#L50)):*
> ```XML
>         // Cast to SecureField.
>         let res = SecureField::one() * constraint;
>         // The constraint should be zero at the given row, since we are evaluating on the trace.
> ```

non-blocking



_Suggestion:_
```XML
since we are evaluating on the trace domain.
```
___
*[`crates/prover/src/constraint_framework/mod.rs` line 2 at r1](https://reviewable.io/reviews/starkware-libs/stwo/714#-O1X5PUV1dxo9jMKVLeK:-O1kO8GG4GQHf1ZjlIUe:b-x7wgjx) ([raw file](https://github.com/starkware-libs/stwo/blob/86be1d9a4c62a8f6b714b34a9a93e27437ae732e/crates/prover/src/constraint_framework/mod.rs#L2)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

It won't be on production. But very useful for debugging, from experience.
</blockquote></details>

I suggested adding #[cfg(tests)]

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/714)* status: all files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/mod.rs` line 2 at r1](https://reviewable.io/reviews/starkware-libs/stwo/714#-O1X5PUV1dxo9jMKVLeK:-O1kPWsw3ufCb8p8q5bz:bl87kuw) ([raw file](https://github.com/starkware-libs/stwo/blob/86be1d9a4c62a8f6b714b34a9a93e27437ae732e/crates/prover/src/constraint_framework/mod.rs#L2)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I suggested adding #[cfg(tests)]
</blockquote></details>

It's useful as a library, so I don't think I want to gate this.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/714#-:-O1ky0wu1nqNwunq2v9v:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @spapinistarkware)

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/714)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/prover/src/constraint_framework/assert.rs` line 55 at r4](https://reviewable.io/reviews/starkware-libs/stwo/714#-O1kyVv57E6Rm1yVEY3z:-O1kyVv57E6Rm1yVEY4-:b2nhexc) ([raw file](https://github.com/starkware-libs/stwo/blob/d4bdc0204a6227307da44eb73939b611205a2f23/crates/prover/src/constraint_framework/assert.rs#L55)):*
> ```XML
>     }
> 
>     fn combine_ef(values: [Self::F; 4]) -> Self::EF {
> ```

Fix



_Suggestion:_
```XML
    fn combine_ef(values: [Self::F; SECURE_EXTENSION_DEGREE]) -> Self::EF {
```

**Review by shaharsamocha7 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/714)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Comment by spapinistarkware** [comment]
### Merge activity

* **Jul 14, 8:06 AM EDT**: [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/714) rebased this pull request after merging its parent, because this pull request is set to merge when ready.

**Pull request merged**
