### PR TITLE
Create example airs folder

### PR DESCRIPTION
**Pull request by shaharsamocha7**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/540)

### CODE REVIEW

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/540)* status: all files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`src/example_airs/mod.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/stwo/540#-NttV-h91sxEC_oWcLfo:-NttV-h91sxEC_oWcLfp:b-n14cbl) ([raw file](https://github.com/starkware-libs/stwo/blob/f54068b8a70a7c51ff406c54a8235f753fba39cf/src/example_airs/mod.rs#L1)):*
> ```XML
> pub mod fibonacci;
> ```

Can you rename the directory to examples?

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/540)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`src/example_airs/mod.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/stwo/540#-NttV-h91sxEC_oWcLfo:-NttVk2LAKdoLAq1rBos:b-tgrbl3) ([raw file](https://github.com/starkware-libs/stwo/blob/f54068b8a70a7c51ff406c54a8235f753fba39cf/src/example_airs/mod.rs#L1)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Can you rename the directory to examples?
</blockquote></details>

Thought about example_components, WDYT?

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/540)* status: all files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`src/example_airs/mod.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/stwo/540#-NttV-h91sxEC_oWcLfo:-NttZ4o8DrLhkeuh59YT:b-9tffvu) ([raw file](https://github.com/starkware-libs/stwo/blob/f54068b8a70a7c51ff406c54a8235f753fba39cf/src/example_airs/mod.rs#L1)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Thought about example_components, WDYT?
</blockquote></details>

components/ is for reusable components.
examples/ is for examples on how to use stwo. fib and wide fib are greate xamples for tthat.

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/540)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Review by spapinistarkware — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/540#-:-NttbG4hAjKqUmz1dGjX:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/540)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Comment by shaharsamocha7** [comment]
### Merge activity

* **Mar 27, 8:10 AM EDT**: @shaharsamocha7 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/540).

**Pull request merged**
