### PR TITLE
Logup generator returns multiple prefix sums

### PR DESCRIPTION
**Pull request by shaharsamocha7**
Logup generator finalize get a list of indices and returns the corresponding prefix sum

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/829)

### CODE REVIEW

**Comment by shaharsamocha7** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/829?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#829** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/829?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#825** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/825?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#818** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/818?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @shaharsamocha7 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Alon-Ti — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/829)* status: all files reviewed, 1 unresolved discussion (waiting on @andrewmilson and @shaharsamocha7)

___
*[`crates/prover/src/examples/blake/round/gen.rs` line 280 at r1](https://reviewable.io/reviews/starkware-libs/stwo/829#-O7O2TG6Bx5RksTK5uVZ:-O7O2TG6Bx5RksTK5uV_:b-gxxda3) ([raw file](https://github.com/starkware-libs/stwo/blob/45206e8d2189b6a07e097f0487d53d157ee7075e/crates/prover/src/examples/blake/round/gen.rs#L280)):*
> ```XML
>     col_gen.finalize_col();
> 
>     let (trace, [total_sum]) = logup_gen.finalize([(1 << log_size) - 1]);
> ```

Isn't it a little weird that you have to specify an index that in all "normal" cases translates to a constant index? Maybe there should be a `finalize_last`, or conversely `finalize_at`?

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/829)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @Alon-Ti and @andrewmilson)

___
*[`crates/prover/src/examples/blake/round/gen.rs` line 280 at r1](https://reviewable.io/reviews/starkware-libs/stwo/829#-O7O2TG6Bx5RksTK5uVZ:-O7ODpXr6fk1nkfvDAp3:b-c4o9zy) ([raw file](https://github.com/starkware-libs/stwo/blob/45206e8d2189b6a07e097f0487d53d157ee7075e/crates/prover/src/examples/blake/round/gen.rs#L280)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

Isn't it a little weird that you have to specify an index that in all "normal" cases translates to a constant index? Maybe there should be a `finalize_last`, or conversely `finalize_at`?
</blockquote></details>

you suggest to rename finalize, to finalize_at()?
I think that there are more API functions that I want to rename here
e.g. next_interaction_mask(..) -> next_trace_column(..), WDYT?

**Review by andrewmilson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/829)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @Alon-Ti and @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/logup.rs` line 195 at r1](https://reviewable.io/reviews/starkware-libs/stwo/829#-O77SeONEN1s5KnIy1hw:-O77SeONEN1s5KnIy1hx:berjp0l) ([raw file](https://github.com/starkware-libs/stwo/blob/45206e8d2189b6a07e097f0487d53d157ee7075e/crates/prover/src/constraint_framework/logup.rs#L195)):*
> ```XML
>             .collect_vec();
>         (trace, returned_prefix_sums)
>     }
> ```

Agree with Alon.
Realise I already had this in Draft from a couple days ago but forgot to publish.



_Suggestion:_
```XML
    /// Returns the trace and the claimed sum of the last column.
    pub fn finalize_last(self) -> (
        ColumnVec<CircleEvaluation<SimdBackend, BaseField, BitReversedOrder>>,
        [SecureField; N],
    ) {
        let (trace, [cum_sum] = self.finalize_with_sum_at_indices(...);
        (trace, cum_sum)
    }
    
    /// Returns the trace and the prefix sum of the last column at the corresponding `indices`.
    pub fn finalize_at<const N: usize>(
        mut self,
        indices: [usize; N],
    ) -> (
        ColumnVec<CircleEvaluation<SimdBackend, BaseField, BitReversedOrder>>,
        [SecureField; N],
    ) {
        // Prefix sum the last column.
        let last_col_coords = self.trace.pop().unwrap().columns;
        let coord_prefix_sum = last_col_coords.map(inclusive_prefix_sum);
        let secure_prefix_sum = SecureColumnByCoords {
            columns: coord_prefix_sum,
        };
        let returned_prefix_sums = indices.map(|idx| {
            // Prefix sum column is in bit-reversed circle domain order.
            let fixed_index = bit_reverse_index(
                coset_index_to_circle_domain_index(idx, self.log_size),
                self.log_size,
            );
            secure_prefix_sum.at(fixed_index)
        });
        self.trace.push(secure_prefix_sum);

        let trace = self
            .trace
            .into_iter()
            .flat_map(|eval| {
                eval.columns.map(|c| {
                    CircleEvaluation::new(CanonicCoset::new(self.log_size).circle_domain(), c)
                })
            })
            .collect_vec();
        (trace, returned_prefix_sums)
    }
```

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/829)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @Alon-Ti and @andrewmilson)

___
*[`crates/prover/src/constraint_framework/logup.rs` line 195 at r1](https://reviewable.io/reviews/starkware-libs/stwo/829#-O77SeONEN1s5KnIy1hw:-O7TZRm2EBRELo3EZsj_:b1svodu) ([raw file](https://github.com/starkware-libs/stwo/blob/45206e8d2189b6a07e097f0487d53d157ee7075e/crates/prover/src/constraint_framework/logup.rs#L195)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Agree with Alon.
Realise I already had this in Draft from a couple days ago but forgot to publish.
</blockquote></details>

Do you suggest to rename finalize -> finalize_at?
or adding more functions?

I think this can be done in another pr, WDYT?

**Review by andrewmilson — APPROVED** [review]
:lgtm: with comment

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/829#-:-O7WrD3oD6bYjTb3LswU:b10c0l0)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @Alon-Ti and @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/logup.rs` line 195 at r1](https://reviewable.io/reviews/starkware-libs/stwo/829#-O77SeONEN1s5KnIy1hw:-O7WqaWe1yezTU5uabq1:b-yk8iaj) ([raw file](https://github.com/starkware-libs/stwo/blob/45206e8d2189b6a07e097f0487d53d157ee7075e/crates/prover/src/constraint_framework/logup.rs#L195)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Do you suggest to rename finalize -> finalize_at?
or adding more functions?

I think this can be done in another pr, WDYT?
</blockquote></details>

Sounds good to me

I'm not so fussed about the names it just seems that 
```
let (trace, [total_sum]) = logup_gen.finalize([(1 << log_size) - 1]);
(trace, total_sum)
``` 

will be a very common operation (will it be?) and seems nice to have a specific function for it

**Review by Alon-Ti — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/829#-:-O7YDDs5ETVLyvD0BB6L:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`crates/prover/src/examples/blake/round/gen.rs` line 280 at r1](https://reviewable.io/reviews/starkware-libs/stwo/829#-O7O2TG6Bx5RksTK5uVZ:-O7YCfJZE6ZyDEOO82RI:b-gvungo) ([raw file](https://github.com/starkware-libs/stwo/blob/45206e8d2189b6a07e097f0487d53d157ee7075e/crates/prover/src/examples/blake/round/gen.rs#L280)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

you suggest to rename finalize, to finalize_at()?
I think that there are more API functions that I want to rename here
e.g. next_interaction_mask(..) -> next_trace_column(..), WDYT?
</blockquote></details>

Agreed, I think `mask` isn't a word that should make it to the user.

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/829)* status: all files reviewed, 1 unresolved discussion (waiting on @andrewmilson)

___
*[`crates/prover/src/constraint_framework/logup.rs` line 195 at r1](https://reviewable.io/reviews/starkware-libs/stwo/829#-O77SeONEN1s5KnIy1hw:-O7YV7I797LRQOPM6B7P:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/45206e8d2189b6a07e097f0487d53d157ee7075e/crates/prover/src/constraint_framework/logup.rs#L195)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Sounds good to me

I'm not so fussed about the names it just seems that 
```
let (trace, [total_sum]) = logup_gen.finalize([(1 << log_size) - 1]);
(trace, total_sum)
``` 

will be a very common operation (will it be?) and seems nice to have a specific function for it
</blockquote></details>

Done.

**Pull request merged**
