### PR TITLE
Poseidon with logup

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/712)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/712?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#712** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/712?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#711** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/711?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#710** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/710?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#708** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/708?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#707** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/707?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#706** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/706?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#705** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/705?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#704** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/704?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#702** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/702?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#701** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/701?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/712)* status: 2 of 4 files reviewed, 9 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/constraint_framework/logup.rs` line 30 at r4](https://reviewable.io/reviews/starkware-libs/stwo/712#-O2tLREE9qP_RiD-H2k4:-O2tLREE9qP_RiD-H2k5:b-lnp78i) ([raw file](https://github.com/starkware-libs/stwo/blob/247a5f12365faf710f0e69279e1891d76044dc06/crates/prover/src/constraint_framework/logup.rs#L30)):*
> ```XML
>     pub prev_mask: E::EF,
>     pub is_first: E::F,
> }
> ```

Please document. Specifically what is queue and BATCH_SIZE.



_Code quote:_
```XML
pub struct LogupAtRow<const BATCH_SIZE: usize, E: EvalAtRow> {
    pub interaction: usize,
    pub queue: [(E::EF, E::EF); BATCH_SIZE],
    pub queue_size: usize,
    pub claimed_sum: SecureField,
    pub prev_mask: E::EF,
    pub is_first: E::F,
}
```
___
*[`crates/prover/src/constraint_framework/logup.rs` line 52 at r4](https://reviewable.io/reviews/starkware-libs/stwo/712#-O2tKKUq-Gr7HFb9FJvq:-O2tKKUq-Gr7HFb9FJvr:bq6lb64) ([raw file](https://github.com/starkware-libs/stwo/blob/247a5f12365faf710f0e69279e1891d76044dc06/crates/prover/src/constraint_framework/logup.rs#L52)):*
> ```XML
>             values,
>             E::EF::zero() + lookup_elements.alpha,
>             E::EF::zero() + lookup_elements.z,
> ```

Add `From<SecureField>` to `EF`?



_Suggestion:_
```XML
            lookup_elements.alpha.into(),
            lookup_elements.z.into(),
```
___
*[`crates/prover/src/constraint_framework/logup.rs` line 57 at r4](https://reviewable.io/reviews/starkware-libs/stwo/712#-O2tLoT8-azZY__CAV6O:-O2tLoT8-azZY__CAV6P:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/247a5f12365faf710f0e69279e1891d76044dc06/crates/prover/src/constraint_framework/logup.rs#L57)):*
> ```XML
>     }
> 
>     pub fn push_frac(&mut self, eval: &mut E, p: E::EF, q: E::EF) {
> ```





_Suggestion:_
```XML
pub fn push_frac(&mut self, eval: &mut E, numerator: E::EF, denom: E::EF) {
```
___
*[`crates/prover/src/constraint_framework/logup.rs` line 96 at r4](https://reviewable.io/reviews/starkware-libs/stwo/712#-O2tNOBt7jaKp8UQAYOQ:-O2tNOBt7jaKp8UQAYOR:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/247a5f12365faf710f0e69279e1891d76044dc06/crates/prover/src/constraint_framework/logup.rs#L96)):*
> ```XML
>             std::array::from_fn(|_| eval.next_interaction_mask(self.interaction, [0, -1]));
>         let cur = E::combine_ef(cumulative_mask_values.map(|[cur, _prev]| cur));
>         let up = E::combine_ef(cumulative_mask_values.map(|[_cur, prev]| prev));
> ```





_Suggestion:_
```XML
        let cur = E::combine_ef(cumulative_mask_values.map(|[cur, _up]| cur));
        let up = E::combine_ef(cumulative_mask_values.map(|[_cur, up]| up));
```
___
*[`crates/prover/src/examples/poseidon/mod.rs` line 118 at r4](https://reviewable.io/reviews/starkware-libs/stwo/712#-O2tP8HaCAyMJpTQHf-5:-O2tP8HaCAyMJpTQHf-6:bb2tsyb) ([raw file](https://github.com/starkware-libs/stwo/blob/247a5f12365faf710f0e69279e1891d76044dc06/crates/prover/src/examples/poseidon/mod.rs#L118)):*
> ```XML
>         logup: LogupAtRow::new(1, SecureField::zero(), BaseField::zero()),
>     };
>     counter.eval.next_interaction_mask(2, [0]);
> ```

Doesn't one of the columns have an offset -1 also? How does this work?



_Code quote:_
```XML
counter.eval.next_interaction_mask(2, [0]);
```
___
*[`crates/prover/src/examples/poseidon/mod.rs` line 131 at r4](https://reviewable.io/reviews/starkware-libs/stwo/712#-O2tQGNq3BUsfoOjUZzU:-O2tQGNq3BUsfoOjUZzV:b-stnxrn) ([raw file](https://github.com/starkware-libs/stwo/blob/247a5f12365faf710f0e69279e1891d76044dc06/crates/prover/src/examples/poseidon/mod.rs#L131)):*
> ```XML
>     }
> 
>     fn trace_log_degree_bounds(&self) -> TreeVec<ColumnVec<u32>> {
> ```

Can you move these two implementations below to `InfoEvaluator`?
___
*[`crates/prover/src/examples/poseidon/mod.rs` line 255 at r4](https://reviewable.io/reviews/starkware-libs/stwo/712#-O2tVGoC8jRhQgMSjgWN:-O2tVGoC8jRhQgMSjgWO:b-tg5clr) ([raw file](https://github.com/starkware-libs/stwo/blob/247a5f12365faf710f0e69279e1891d76044dc06/crates/prover/src/examples/poseidon/mod.rs#L255)):*
> ```XML
> struct PoseidonEval<E: EvalAtRow> {
>     eval: E,
>     logup: LogupAtRow<2, E>,
> ```

Does LogupAtRow have to be separate from EvalAtRow? Can it be internal?



_Code quote:_
```XML
LogupAtRow
```
___
*[`crates/prover/src/examples/poseidon/mod.rs` line 308 at r4](https://reviewable.io/reviews/starkware-libs/stwo/712#-O2tTP4D-tbArNmdKnng:-O2tTP4D-tbArNmdKnnh:b-447r4i) ([raw file](https://github.com/starkware-libs/stwo/blob/247a5f12365faf710f0e69279e1891d76044dc06/crates/prover/src/examples/poseidon/mod.rs#L308)):*
> ```XML
>             // Provide state lookup.
>             self.logup
>                 .push_lookup(&mut self.eval, -E::EF::one(), &state, self.lookup_elements);
> ```

Why is this -1 while the initial state's numerator is 1? Wouldn't the -1 be in the callers column?



_Code quote:_
```XML
-E::EF::one()
```
___
*[`crates/prover/src/examples/poseidon/mod.rs` line 362 at r4](https://reviewable.io/reviews/starkware-libs/stwo/712#-O2tOFvp4fcnEUAeZYfY:-O2tOFvp4fcnEUAeZYfZ:b-eopgfp) ([raw file](https://github.com/starkware-libs/stwo/blob/247a5f12365faf710f0e69279e1891d76044dc06/crates/prover/src/examples/poseidon/mod.rs#L362)):*
> ```XML
>                 .iter_mut()
>                 .zip(state)
>                 .for_each(|(res, si)| res.data[vec_index] = si);
> ```

Accident?



_Code quote:_
```XML
si
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/712)* status: 2 of 4 files reviewed, 9 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/constraint_framework/logup.rs` line 96 at r4](https://reviewable.io/reviews/starkware-libs/stwo/712#-O2tNOBt7jaKp8UQAYOQ:-O2yNSQkEzpRBVazG6KY:b-20rh6w) ([raw file](https://github.com/starkware-libs/stwo/blob/247a5f12365faf710f0e69279e1891d76044dc06/crates/prover/src/constraint_framework/logup.rs#L96)):*
> ```XML
>             std::array::from_fn(|_| eval.next_interaction_mask(self.interaction, [0, -1]));
>         let cur = E::combine_ef(cumulative_mask_values.map(|[cur, _prev]| cur));
>         let up = E::combine_ef(cumulative_mask_values.map(|[_cur, prev]| prev));
> ```

Or actually maybe lets use row_prev and col_prev?

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/712)* status: 1 of 7 files reviewed, 7 unresolved discussions (waiting on @alonh5)

___
*[`crates/prover/src/constraint_framework/logup.rs` line 30 at r4](https://reviewable.io/reviews/starkware-libs/stwo/712#-O2tLREE9qP_RiD-H2k4:-O2yfZlkBA97bBWk7san:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/247a5f12365faf710f0e69279e1891d76044dc06/crates/prover/src/constraint_framework/logup.rs#L30)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Please document. Specifically what is queue and BATCH_SIZE.
</blockquote></details>

Done.
___
*[`crates/prover/src/constraint_framework/logup.rs` line 57 at r4](https://reviewable.io/reviews/starkware-libs/stwo/712#-O2tLoT8-azZY__CAV6O:-O2yfn8D1UWrL229Gk2f:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/247a5f12365faf710f0e69279e1891d76044dc06/crates/prover/src/constraint_framework/logup.rs#L57)):*
> ```XML
>     }
> 
>     pub fn push_frac(&mut self, eval: &mut E, p: E::EF, q: E::EF) {
> ```

Done.
___
*[`crates/prover/src/examples/poseidon/mod.rs` line 118 at r4](https://reviewable.io/reviews/starkware-libs/stwo/712#-O2tP8HaCAyMJpTQHf-5:-O2yhVO-2VKnQ7eL2P_W:b61wxxb) ([raw file](https://github.com/starkware-libs/stwo/blob/247a5f12365faf710f0e69279e1891d76044dc06/crates/prover/src/examples/poseidon/mod.rs#L118)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Doesn't one of the columns have an offset -1 also? How does this work?
</blockquote></details>

It's is_first
___
*[`crates/prover/src/examples/poseidon/mod.rs` line 131 at r4](https://reviewable.io/reviews/starkware-libs/stwo/712#-O2tQGNq3BUsfoOjUZzU:-O2yhgjW27fJYrEELuo8:b-qsrny5) ([raw file](https://github.com/starkware-libs/stwo/blob/247a5f12365faf710f0e69279e1891d76044dc06/crates/prover/src/examples/poseidon/mod.rs#L131)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Can you move these two implementations below to `InfoEvaluator`?
</blockquote></details>

I don't understand. Also, note that in 2 PRs, these will be auto implemented for any framework component.
___
*[`crates/prover/src/examples/poseidon/mod.rs` line 255 at r4](https://reviewable.io/reviews/starkware-libs/stwo/712#-O2tVGoC8jRhQgMSjgWN:-O2yhoRa0An_ru7afntA:bhwloar) ([raw file](https://github.com/starkware-libs/stwo/blob/247a5f12365faf710f0e69279e1891d76044dc06/crates/prover/src/examples/poseidon/mod.rs#L255)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Does LogupAtRow have to be separate from EvalAtRow? Can it be internal?
</blockquote></details>

2 different things. EvalAtRow is a trait that we imoplemented with either point, domain, info or assert ops. LogupAtRow is a specific struct that does the constraints of logup. It also is generic over EvalAtRow, like the component constriants.
___
*[`crates/prover/src/examples/poseidon/mod.rs` line 308 at r4](https://reviewable.io/reviews/starkware-libs/stwo/712#-O2tTP4D-tbArNmdKnng:-O2yi5sD11F4xzPoej88:b-4j807c) ([raw file](https://github.com/starkware-libs/stwo/blob/247a5f12365faf710f0e69279e1891d76044dc06/crates/prover/src/examples/poseidon/mod.rs#L308)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Why is this -1 while the initial state's numerator is 1? Wouldn't the -1 be in the callers column?
</blockquote></details>

I decided to reverse this, since the callers will be called a lot more times than the callees (which have multiplicity). So, I thought it makes sense to not have negations in the common case. Also, the multiplicity could incorporate the negatives themeselves, so in most cases, no negations at all.
___
*[`crates/prover/src/examples/poseidon/mod.rs` line 362 at r4](https://reviewable.io/reviews/starkware-libs/stwo/712#-O2tOFvp4fcnEUAeZYfY:-O2yiQtw2Y83nnW-Xtp9:b7fm2dy) ([raw file](https://github.com/starkware-libs/stwo/blob/247a5f12365faf710f0e69279e1891d76044dc06/crates/prover/src/examples/poseidon/mod.rs#L362)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Accident?
</blockquote></details>

I wanted to distinguish this from state, since it's just a single elements of the state (state_i)

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/712)* status: all files reviewed, 5 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/constraint_framework/logup.rs` line 75 at r7](https://reviewable.io/reviews/starkware-libs/stwo/712#-O32aeti48kMC0gpuXLs:-O32aeti48kMC0gpuXLt:b-9wy07) ([raw file](https://github.com/starkware-libs/stwo/blob/051d90a3c4580f99b8a96ca19e047b984225099f/crates/prover/src/constraint_framework/logup.rs#L75)):*
> ```XML
>         }
> 
>         // Compute sum_i pi/qi over batch, as a fraction, p/q.
> ```

Fix to match name change.



_Code quote:_
```XML
// Compute sum_i pi/qi over batch, as a fraction, p/q.
```
___
*[`crates/prover/src/constraint_framework/logup.rs` line 87 at r7](https://reviewable.io/reviews/starkware-libs/stwo/712#-O32akP08Lqun4FCwV6i:-O32akP1BcOl2UVVWFgF:bgnoflo) ([raw file](https://github.com/starkware-libs/stwo/blob/051d90a3c4580f99b8a96ca19e047b984225099f/crates/prover/src/constraint_framework/logup.rs#L87)):*
> ```XML
>         self.queue_size = 1;
> 
>         // Add a constraint that p / q = diff.
> ```

Here also.



_Code quote:_
```XML
// Add a constraint that p / q = diff.
```
___
*[`crates/prover/src/constraint_framework/logup.rs` line 89 at r7](https://reviewable.io/reviews/starkware-libs/stwo/712#-O32avAD3egermuyydB2:-O32avAD3egermuyydB3:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/051d90a3c4580f99b8a96ca19e047b984225099f/crates/prover/src/constraint_framework/logup.rs#L89)):*
> ```XML
>         // Add a constraint that p / q = diff.
>         let cur_cumsum = E::combine_ef(std::array::from_fn(|_| {
>             eval.next_interaction_mask(1, [0])[0]
> ```





_Suggestion:_
```XML
self.interaction
```
___
*[`crates/prover/src/constraint_framework/logup.rs` line 107 at r7](https://reviewable.io/reviews/starkware-libs/stwo/712#-O32b_7SAX3gMLfeQ5Gj:-O32b_7SAX3gMLfeQ5Gk:b9d6es2) ([raw file](https://github.com/starkware-libs/stwo/blob/051d90a3c4580f99b8a96ca19e047b984225099f/crates/prover/src/constraint_framework/logup.rs#L107)):*
> ```XML
>             std::array::from_fn(|_| eval.next_interaction_mask(self.interaction, [0, -1]));
>         let cur_cumsum = E::combine_ef(cumsum_mask.map(|[cur_row, _prev_row]| cur_row));
>         let prev_row_cumsum = E::combine_ef(cumsum_mask.map(|[_cur_row, prev_row]| prev_row));
> ```

I thought row_prev could refer to the previous value in the row (left) and col_prev to the previous value in the column (up).
Alternatively you can say prev_row is the previous row value (up) and prev_col the previous columns value (left).
Now it's a mix of both and is more confusing IMO.



_Code quote:_
```XML
        let cur_cumsum = E::combine_ef(cumsum_mask.map(|[cur_row, _prev_row]| cur_row));
        let prev_row_cumsum = E::combine_ef(cumsum_mask.map(|[_cur_row, prev_row]| prev_row));
```
___
*[`crates/prover/src/examples/poseidon/mod.rs` line 362 at r4](https://reviewable.io/reviews/starkware-libs/stwo/712#-O2tOFvp4fcnEUAeZYfY:-O32Zhnq3QVpif_DOQR7:b-gb0lz8) ([raw file](https://github.com/starkware-libs/stwo/blob/247a5f12365faf710f0e69279e1891d76044dc06/crates/prover/src/examples/poseidon/mod.rs#L362)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I wanted to distinguish this from state, since it's just a single elements of the state (state_i)
</blockquote></details>

So how about `state_i`?

**Review by alonh5 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/712#-:-O32eZa100LbEpQkoRBh:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @spapinistarkware)

**Review by alonh5 — APPROVED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/712)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/prover/src/constraint_framework/logup.rs` line 87 at r8](https://reviewable.io/reviews/starkware-libs/stwo/712#-O32hbkS0e9ekOqQLJpa:-O32hbkS0e9ekOqQLJpb:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/19c7760c4b20e9a02820eeb5edd8b278018260f6/crates/prover/src/constraint_framework/logup.rs#L87)):*
> ```XML
>         self.queue_size = 1;
> 
>         // Add a constraint that p / q = diff.
> ```





_Suggestion:_
```XML
num / denom = diff
```

**Review by alonh5 — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/712)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Comment by spapinistarkware** [comment]
### Merge activity

* **Jul 30, 9:05 AM EDT**: @spapinistarkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/712).

**Pull request merged**
