### PR TITLE
Create ComponentTraceWriter trait.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/633)

### CODE REVIEW

**Comment by alonh5** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/633?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#633** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/633?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#631** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/631?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#582** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/582?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#589](https://github.com/starkware-libs/stwo/pull/589) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/589?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#573** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/573?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#574](https://github.com/starkware-libs/stwo/pull/574) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/574?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#572** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/572?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#562** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/562?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r1, 3 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/633)* status: 4 of 9 files reviewed, 5 unresolved discussions (waiting on @alonh5 and @andrewmilson)

___
*[`crates/prover/src/core/air/mod.rs` line 57 at r2](https://reviewable.io/reviews/starkware-libs/stwo/633#-NyU9cVs2oBN4XfodI8Z:-NyU9cVs2oBN4XfodI8_:bcg7xzo) ([raw file](https://github.com/starkware-libs/stwo/blob/68d7b886a1ff450afc19ae552e9b66f49af486f0/crates/prover/src/core/air/mod.rs#L57)):*
> ```XML
> 
> pub trait ComponentTraceWriter<B: Backend> {
>     fn write_interaction_trace(
> ```

Should this function be autogenerated per component?



_Code quote:_
```XML
fn write_interaction_trace(
```
___
*[`crates/prover/src/examples/wide_fibonacci/component.rs` line 104 at r2](https://reviewable.io/reviews/starkware-libs/stwo/633#-NyUAHuX2LMjQwRhzt62:-NyUAHuX2LMjQwRhzt63:b-e5v3t7) ([raw file](https://github.com/starkware-libs/stwo/blob/68d7b886a1ff450afc19ae552e9b66f49af486f0/crates/prover/src/examples/wide_fibonacci/component.rs#L104)):*
> ```XML
>         elements: &InteractionElements,
>     ) -> ColumnVec<CircleEvaluation<CPUBackend, BaseField, BitReversedOrder>> {
>         let domain = trace[0].domain;
> ```

I think that we should have a naming convention here.
trace -> refers to regular trace
interaction_trace -> refers to the interaction..

This convention assumes that we have only one interaction trace.



_Suggestion:_
```XML
let interaction_trace_domain = trace[0].domain;
```
___
*[`crates/prover/src/examples/wide_fibonacci/component.rs` line 105 at r2](https://reviewable.io/reviews/starkware-libs/stwo/633#-NyUAMsR7ptA2sKrH5tb:-NyUAMsR7ptA2sKrH5tc:b-7zi8ni) ([raw file](https://github.com/starkware-libs/stwo/blob/68d7b886a1ff450afc19ae552e9b66f49af486f0/crates/prover/src/examples/wide_fibonacci/component.rs#L105)):*
> ```XML
>     ) -> ColumnVec<CircleEvaluation<CPUBackend, BaseField, BitReversedOrder>> {
>         let domain = trace[0].domain;
>         let input_trace = trace.iter().map(|eval| &eval.values).collect_vec();
> ```

WDYT?



_Suggestion:_
```XML
  let trace_values = trace.iter().map(|eval| &eval.values).collect_vec();
```
___
*[`crates/prover/src/examples/wide_fibonacci/trace_gen.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/stwo/633#-NyU9xyZ4GQZJsxco8PY:-NyU9xyZ4GQZJsxco8PZ:bma1aa9) ([raw file](https://github.com/starkware-libs/stwo/blob/68d7b886a1ff450afc19ae552e9b66f49af486f0/crates/prover/src/examples/wide_fibonacci/trace_gen.rs#L25)):*
> ```XML
> }
> 
> pub fn write_lookup_column(
> ```

This function here is very specfic to fib lookup.
Do we want to generalize it eventually?



_Code quote:_
```XML
pub fn write_lookup_column(
```
___
*[`crates/prover/src/examples/wide_fibonacci/trace_gen.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/stwo/633#-NyUApfA6K9T08tRx0KM:-NyUApfA6K9T08tRx0KN:bwrm6m3) ([raw file](https://github.com/starkware-libs/stwo/blob/68d7b886a1ff450afc19ae552e9b66f49af486f0/crates/prover/src/examples/wide_fibonacci/trace_gen.rs#L25)):*
> ```XML
> }
> 
> pub fn write_lookup_column(
> ```

Also, document



_Code quote:_
```XML
pub fn write_lookup_column(
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/633)* status: 4 of 9 files reviewed, 5 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`crates/prover/src/core/air/mod.rs` line 57 at r2](https://reviewable.io/reviews/starkware-libs/stwo/633#-NyU9cVs2oBN4XfodI8Z:-NyUiqEjCqXLAd0B2smh:b-q1kpqh) ([raw file](https://github.com/starkware-libs/stwo/blob/68d7b886a1ff450afc19ae552e9b66f49af486f0/crates/prover/src/core/air/mod.rs#L57)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Should this function be autogenerated per component?
</blockquote></details>

Yes, I think so.
___
*[`crates/prover/src/examples/wide_fibonacci/component.rs` line 104 at r2](https://reviewable.io/reviews/starkware-libs/stwo/633#-NyUAHuX2LMjQwRhzt62:-NyUjcjsBmEQXI1qkFsq:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/68d7b886a1ff450afc19ae552e9b66f49af486f0/crates/prover/src/examples/wide_fibonacci/component.rs#L104)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I think that we should have a naming convention here.
trace -> refers to regular trace
interaction_trace -> refers to the interaction..

This convention assumes that we have only one interaction trace.
</blockquote></details>

Done.
___
*[`crates/prover/src/examples/wide_fibonacci/component.rs` line 105 at r2](https://reviewable.io/reviews/starkware-libs/stwo/633#-NyUAMsR7ptA2sKrH5tb:-NyUjS-O5tk5qEvvwb9I:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/68d7b886a1ff450afc19ae552e9b66f49af486f0/crates/prover/src/examples/wide_fibonacci/component.rs#L105)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

WDYT?
</blockquote></details>

Done.
___
*[`crates/prover/src/examples/wide_fibonacci/trace_gen.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/stwo/633#-NyU9xyZ4GQZJsxco8PY:-NyVbCeF5u9r-V7igYlU:b98kre6) ([raw file](https://github.com/starkware-libs/stwo/blob/68d7b886a1ff450afc19ae552e9b66f49af486f0/crates/prover/src/examples/wide_fibonacci/trace_gen.rs#L25)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

This function here is very specfic to fib lookup.
Do we want to generalize it eventually?
</blockquote></details>

We could generalize it to get the locations and lengths of the values that should be combined. Using it might make the auto generation easier.
___
*[`crates/prover/src/examples/wide_fibonacci/trace_gen.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/stwo/633#-NyUApfA6K9T08tRx0KM:-NyVbejh8_i2EW0vjY-l:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/68d7b886a1ff450afc19ae552e9b66f49af486f0/crates/prover/src/examples/wide_fibonacci/trace_gen.rs#L25)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Also, document
</blockquote></details>

Done.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r2, 2 of 3 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/633)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5 and @andrewmilson)

___
*[`crates/prover/src/core/mod.rs` line 68 at r4](https://reviewable.io/reviews/starkware-libs/stwo/633#-NyZSEtb2AAdCy1Xj1im:-NyZSEtb2AAdCy1Xj1in:b-9alr6n) ([raw file](https://github.com/starkware-libs/stwo/blob/7dd3dce6e4210f86cfefa7517d80809be6eef40e/crates/prover/src/core/mod.rs#L68)):*
> ```XML
>     type Output = BaseField;
> 
>     fn index(&self, index: &str) -> &Self::Output {
> ```

Do we need to return an error here in case that the element is not found?



_Code quote:_
```XML
fn index(&self, index: &str) -> &Self::Output {
```
___
*[`crates/prover/src/examples/wide_fibonacci/trace_gen.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/stwo/633#-NyU9xyZ4GQZJsxco8PY:-NyZTc43BN4qSkERm2Ed:b-w5nin1) ([raw file](https://github.com/starkware-libs/stwo/blob/68d7b886a1ff450afc19ae552e9b66f49af486f0/crates/prover/src/examples/wide_fibonacci/trace_gen.rs#L25)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

We could generalize it to get the locations and lengths of the values that should be combined. Using it might make the auto generation easier.
</blockquote></details>

It's not just the locations and length, generally we could get a list of expressions of values of the trace.
If we want to use that function and not autogenerate a different one for each component, it should have other interface.

Anyway it's ok for now.

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/633)* status: all files reviewed, 2 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`crates/prover/src/core/mod.rs` line 68 at r4](https://reviewable.io/reviews/starkware-libs/stwo/633#-NyZSEtb2AAdCy1Xj1im:-NyZZloA9WRBtyeOU3A6:b-4hrrgp) ([raw file](https://github.com/starkware-libs/stwo/blob/7dd3dce6e4210f86cfefa7517d80809be6eef40e/crates/prover/src/core/mod.rs#L68)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Do we need to return an error here in case that the element is not found?
</blockquote></details>

The way it is used, only if there's a bug an element can be not found. In that case according to what we decided it shouldn't return an error.
___
*[`crates/prover/src/examples/wide_fibonacci/trace_gen.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/stwo/633#-NyU9xyZ4GQZJsxco8PY:-NyZ_9Hy4dqBoDKpAriB:b4mhrki) ([raw file](https://github.com/starkware-libs/stwo/blob/68d7b886a1ff450afc19ae552e9b66f49af486f0/crates/prover/src/examples/wide_fibonacci/trace_gen.rs#L25)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

It's not just the locations and length, generally we could get a list of expressions of values of the trace.
If we want to use that function and not autogenerate a different one for each component, it should have other interface.

Anyway it's ok for now.
</blockquote></details>

Oh I see. Okay, let's discuss it further offline, for the future.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/633)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @andrewmilson)

___
*[`crates/prover/src/core/mod.rs` line 68 at r4](https://reviewable.io/reviews/starkware-libs/stwo/633#-NyZSEtb2AAdCy1Xj1im:-NyZtT4u813O45q7ILS4:b-xc8z1w) ([raw file](https://github.com/starkware-libs/stwo/blob/7dd3dce6e4210f86cfefa7517d80809be6eef40e/crates/prover/src/core/mod.rs#L68)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

The way it is used, only if there's a bug an element can be not found. In that case according to what we decided it shouldn't return an error.
</blockquote></details>

I'm saying it because the air infra can potentially have a mismatch in the random elements naming.
Can you explain why it shouldn't return an error?

**Review by andrewmilson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/633)* status: all files reviewed, 4 unresolved discussions (waiting on @alonh5)

___
*[`crates/prover/src/core/mod.rs` line 69 at r4](https://reviewable.io/reviews/starkware-libs/stwo/633#-Nyg3PNLBF0w2xfdceH8:-Nyg3PNLBF0w2xfdceH9:b-rt8bj9) ([raw file](https://github.com/starkware-libs/stwo/blob/7dd3dce6e4210f86cfefa7517d80809be6eef40e/crates/prover/src/core/mod.rs#L69)):*
> ```XML
> 
>     fn index(&self, index: &str) -> &Self::Output {
>         &self.0.iter().find(|(id, _)| id == index).unwrap().1
> ```

WDYT about using BTreeMap? https://doc.rust-lang.org/std/collections/struct.BTreeMap.html#impl-Index%3C%26Q%3E-for-BTreeMap%3CK,+V,+A%3E



_Suggestion:_
```XML
self.0[index]
```
___
*[`crates/prover/src/core/air/air_ext.rs` line 112 at r4](https://reviewable.io/reviews/starkware-libs/stwo/633#-Nyg8eFgEv3qM4G82IdP:-Nyg8eFgEv3qM4G82IdQ:bjb2zuu) ([raw file](https://github.com/starkware-libs/stwo/blob/7dd3dce6e4210f86cfefa7517d80809be6eef40e/crates/prover/src/core/air/air_ext.rs#L112)):*
> ```XML
>                 .iter()
>                 .map(|component| {
>                     let n_columns = component.trace_log_degree_bounds().len();
> ```

Should we add n_columns on Component?
___
*[`crates/prover/src/examples/wide_fibonacci/trace_gen.rs` line 29 at r4](https://reviewable.io/reviews/starkware-libs/stwo/633#-Nyg3uky2DfyWs5coma4:-Nyg3uky2DfyWs5coma5:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/7dd3dce6e4210f86cfefa7517d80809be6eef40e/crates/prover/src/examples/wide_fibonacci/trace_gen.rs#L29)):*
> ```XML
> /// the shifted secure combination of the last two elements in each row.
> pub fn write_lookup_column(
>     input_trace: &[&Vec<BaseField>],
> ```





_Suggestion:_
```XML
&[&[BaseField]]
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/633)* status: 9 of 10 files reviewed, 4 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`crates/prover/src/core/mod.rs` line 68 at r4](https://reviewable.io/reviews/starkware-libs/stwo/633#-NyZSEtb2AAdCy1Xj1im:-NypKKDiCIQUqJfdLtPy:btqcaqc) ([raw file](https://github.com/starkware-libs/stwo/blob/7dd3dce6e4210f86cfefa7517d80809be6eef40e/crates/prover/src/core/mod.rs#L68)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I'm saying it because the air infra can potentially have a mismatch in the random elements naming.
Can you explain why it shouldn't return an error?
</blockquote></details>

It should. Added a TODO.
___
*[`crates/prover/src/core/mod.rs` line 69 at r4](https://reviewable.io/reviews/starkware-libs/stwo/633#-Nyg3PNLBF0w2xfdceH8:-NypJZKPBv5E2RgO_E4A:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/7dd3dce6e4210f86cfefa7517d80809be6eef40e/crates/prover/src/core/mod.rs#L69)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

WDYT about using BTreeMap? https://doc.rust-lang.org/std/collections/struct.BTreeMap.html#impl-Index%3C%26Q%3E-for-BTreeMap%3CK,+V,+A%3E
</blockquote></details>

Done.
___
*[`crates/prover/src/core/air/air_ext.rs` line 112 at r4](https://reviewable.io/reviews/starkware-libs/stwo/633#-Nyg8eFgEv3qM4G82IdP:-NypJnyP01GzJgmRVskm:bnyiko6) ([raw file](https://github.com/starkware-libs/stwo/blob/7dd3dce6e4210f86cfefa7517d80809be6eef40e/crates/prover/src/core/air/air_ext.rs#L112)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Should we add n_columns on Component?
</blockquote></details>

Could be appropriate. Probably in a separate PR. @shaharsamocha7
___
*[`crates/prover/src/examples/wide_fibonacci/trace_gen.rs` line 29 at r4](https://reviewable.io/reviews/starkware-libs/stwo/633#-Nyg3uky2DfyWs5coma4:-NypHqro8bZNqlBPcJKg:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/7dd3dce6e4210f86cfefa7517d80809be6eef40e/crates/prover/src/examples/wide_fibonacci/trace_gen.rs#L29)):*
> ```XML
> /// the shifted secure combination of the last two elements in each row.
> pub fn write_lookup_column(
>     input_trace: &[&Vec<BaseField>],
> ```

Done.

**Review by andrewmilson — APPROVED** [review]
:lgtm:

> Reviewed 4 of 6 files at r4, 1 of 1 files at r5, 4 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/633#-:-NyrxStO34sSkunc_UxF:bnfp4nl)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7)

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/633)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @andrewmilson)

___
*[`crates/prover/src/core/air/air_ext.rs` line 112 at r4](https://reviewable.io/reviews/starkware-libs/stwo/633#-Nyg8eFgEv3qM4G82IdP:-Nyz2HyV6x-uFHc0K9m6:b-lcdlzu) ([raw file](https://github.com/starkware-libs/stwo/blob/7dd3dce6e4210f86cfefa7517d80809be6eef40e/crates/prover/src/core/air/air_ext.rs#L112)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Could be appropriate. Probably in a separate PR. @shaharsamocha7
</blockquote></details>

n_columns is derived from `component.trace_log_degree_bounds()`
Do you think that we need extra interface?

**Review by shaharsamocha7 — APPROVED** [review]
> Reviewed 3 of 5 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/633)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5 and @andrewmilson)

___
*[`crates/prover/src/core/air/air_ext.rs` line 111 at r7](https://reviewable.io/reviews/starkware-libs/stwo/633#-Nyz49Sf2PhpS3TAKd5l:-Nyz49SgC6GhJI-_lRPE:b-uax3b5) ([raw file](https://github.com/starkware-libs/stwo/blob/ef070f1bb6489034fbcd5a79ed54f9f3ffc13b2e/crates/prover/src/core/air/air_ext.rs#L111)):*
> ```XML
>                 .map(|component| {
>                     let n_columns = component.trace_log_degree_bounds().len();
>                     let trace_columns = trace_iter.take(n_columns).collect_vec();
> ```

This logic takes each component at a time?
I'm not sure I understand this logic.



_Code quote:_
```XML
                    let n_columns = component.trace_log_degree_bounds().len();
                    let trace_columns = trace_iter.take(n_columns).collect_vec();
```
___
*[`crates/prover/src/core/air/mod.rs` line 64 at r7](https://reviewable.io/reviews/starkware-libs/stwo/633#-Nyz312c0VBbUI8qd3rs:-Nyz312c0VBbUI8qd3rt:b-l3xpmb) ([raw file](https://github.com/starkware-libs/stwo/blob/ef070f1bb6489034fbcd5a79ed54f9f3ffc13b2e/crates/prover/src/core/air/mod.rs#L64)):*
> ```XML
> }
> 
> pub trait ComponentProver<B: Backend>: Component + ComponentTraceWriter<B> {
> ```

Please add a TODO here to rethink about this because I think it can be changed.
I think that we'll have a struct that impls the ComponentTraceWriter trait.
But maybe it will generate another struct that impl the Component trait.

I'm not sure that we can impl both traits for the same struct.



_Code quote:_
```XML
pub trait ComponentProver<B: Backend>: Component + ComponentTraceWriter<B> {
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/633)* status: all files reviewed, 3 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`crates/prover/src/core/air/air_ext.rs` line 112 at r4](https://reviewable.io/reviews/starkware-libs/stwo/633#-Nyg8eFgEv3qM4G82IdP:-Nyz5PGREEsjgAYe-vxq:bmyzywo) ([raw file](https://github.com/starkware-libs/stwo/blob/7dd3dce6e4210f86cfefa7517d80809be6eef40e/crates/prover/src/core/air/air_ext.rs#L112)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

n_columns is derived from `component.trace_log_degree_bounds()`
Do you think that we need extra interface?
</blockquote></details>

Not necessarily. I'm fine with either.
___
*[`crates/prover/src/core/air/air_ext.rs` line 111 at r7](https://reviewable.io/reviews/starkware-libs/stwo/633#-Nyz49Sf2PhpS3TAKd5l:-Nyz6RcN6oaZPAFeKRe6:b30tj3a) ([raw file](https://github.com/starkware-libs/stwo/blob/ef070f1bb6489034fbcd5a79ed54f9f3ffc13b2e/crates/prover/src/core/air/air_ext.rs#L111)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

This logic takes each component at a time?
I'm not sure I understand this logic.
</blockquote></details>

for each  component it takes the columns that are part of it, and passes them into `write_interaction_trace()`. It's similar to the logic in `component_traces()`.
___
*[`crates/prover/src/core/air/mod.rs` line 64 at r7](https://reviewable.io/reviews/starkware-libs/stwo/633#-Nyz312c0VBbUI8qd3rs:-Nyz5ei4ECpeCRAQfCzs:b-vveaba) ([raw file](https://github.com/starkware-libs/stwo/blob/ef070f1bb6489034fbcd5a79ed54f9f3ffc13b2e/crates/prover/src/core/air/mod.rs#L64)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Please add a TODO here to rethink about this because I think it can be changed.
I think that we'll have a struct that impls the ComponentTraceWriter trait.
But maybe it will generate another struct that impl the Component trait.

I'm not sure that we can impl both traits for the same struct.
</blockquote></details>

Added the TODO. Why can't we?

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/633)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5 and @andrewmilson)

___
*[`crates/prover/src/core/air/air_ext.rs` line 111 at r7](https://reviewable.io/reviews/starkware-libs/stwo/633#-Nyz49Sf2PhpS3TAKd5l:-Nyz7hHd8fpCyqEis8bV:byh5v4z) ([raw file](https://github.com/starkware-libs/stwo/blob/ef070f1bb6489034fbcd5a79ed54f9f3ffc13b2e/crates/prover/src/core/air/air_ext.rs#L111)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

for each  component it takes the columns that are part of it, and passes them into `write_interaction_trace()`. It's similar to the logic in `component_traces()`.
</blockquote></details>

Does it mean that the interaction columns are not included in the `n_columns`?
I wonder if we should have a separate function to fetch the component trace.
___
*[`crates/prover/src/core/air/mod.rs` line 64 at r7](https://reviewable.io/reviews/starkware-libs/stwo/633#-Nyz312c0VBbUI8qd3rs:-Nyz7xSU8c6i0RhBgSAu:bixhz0x) ([raw file](https://github.com/starkware-libs/stwo/blob/ef070f1bb6489034fbcd5a79ed54f9f3ffc13b2e/crates/prover/src/core/air/mod.rs#L64)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Added the TODO. Why can't we?
</blockquote></details>

because trace_writer will need to write the trace (and doesn't necessarily knows how many rows it will have eventually)
We do need to know n_rows for each component, so maybe we'll have that TraceWriter generates the corresponding component.

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/633)* status: all files reviewed, 3 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`crates/prover/src/core/air/air_ext.rs` line 111 at r7](https://reviewable.io/reviews/starkware-libs/stwo/633#-Nyz49Sf2PhpS3TAKd5l:-Nyz8igs1c3qIG8RAyZm:b45shyg) ([raw file](https://github.com/starkware-libs/stwo/blob/ef070f1bb6489034fbcd5a79ed54f9f3ffc13b2e/crates/prover/src/core/air/air_ext.rs#L111)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Does it mean that the interaction columns are not included in the `n_columns`?
I wonder if we should have a separate function to fetch the component trace.
</blockquote></details>

I didn't really do it in the right order because it was easier for me this way, but TAL at 638 - there the interaction columns are included in `trace_log_degree_bounds()`.

Do you mean to extract this into a function and use here and in `component_traces()`? It's just 2 lines and they aren't exactly the same, so I'm not sure if it'll be helpful.
___
*[`crates/prover/src/core/air/mod.rs` line 64 at r7](https://reviewable.io/reviews/starkware-libs/stwo/633#-Nyz312c0VBbUI8qd3rs:-Nyz9nYM4HOaQqo8CfZp:by4fa2) ([raw file](https://github.com/starkware-libs/stwo/blob/ef070f1bb6489034fbcd5a79ed54f9f3ffc13b2e/crates/prover/src/core/air/mod.rs#L64)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

because trace_writer will need to write the trace (and doesn't necessarily knows how many rows it will have eventually)
We do need to know n_rows for each component, so maybe we'll have that TraceWriter generates the corresponding component.
</blockquote></details>

Okay, let's discuss it offline.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/633#-:-NyzFH9eBY4s2ZsuOH8f:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @andrewmilson)

**Comment by alonh5** [comment]
### Merge activity

* **May 29, 3:41 AM EDT**: @alonh5 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/633).

**Pull request merged**
