### PR TITLE
derive par iter

### PR DESCRIPTION
**Pull request by ohad-agadi**

### CODE REVIEW

**Comment by ohad-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/955?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#955** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/955?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/955?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#953** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/953?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#946](https://github.com/starkware-libs/stwo/pull/946) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/946?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#952** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/952?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#948** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/948?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#945** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/945?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/955)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @ohad-starkware)

___
*[`crates/air_utils/src/lookup_data/mod.rs` line 40 at r3](https://reviewable.io/reviews/starkware-libs/stwo/955#-OFMqpJcC0-wCAX17WVg:-OFMqpJcC0-wCAX17WVh:b-pa2o9t) ([raw file](https://github.com/starkware-libs/stwo/blob/5764a4878f4a01e284fc422cde27aeff9944f660/crates/air_utils/src/lookup_data/mod.rs#L40)):*
> ```XML
> 
>     #[test]
>     fn test_derived_lookup_data_par_iter() {
> ```

Let's keep both tests



_Code quote:_
```XML
fn test_derived_lookup_data_par_iter() {
```
___
*[`crates/air_utils_derive/src/iterable_field.rs` line 219 at r3](https://reviewable.io/reviews/starkware-libs/stwo/955#-OFMrF1P5ZrgJV4jGqx6:-OFMrF1P5ZrgJV4jGqx7:briwbs2) ([raw file](https://github.com/starkware-libs/stwo/blob/5764a4878f4a01e284fc422cde27aeff9944f660/crates/air_utils_derive/src/iterable_field.rs#L219)):*
> ```XML
>         match self {
>             IterableField::PlainVec(plain_vec) => {
>                 let name = &plain_vec.name;
> ```

Introduce head var to match with the split_first, split_last impl



_Code quote:_
```XML
let name = &plain_vec.name;
```
___
*[`crates/air_utils_derive/src/par_iter.rs` line 9 at r3](https://reviewable.io/reviews/starkware-libs/stwo/955#-OFMxgYTDa0lPaEDzJHc:-OFMxgYU-2Lr1Dajp3ro:bdqrv90) ([raw file](https://github.com/starkware-libs/stwo/blob/5764a4878f4a01e284fc422cde27aeff9944f660/crates/air_utils_derive/src/par_iter.rs#L9)):*
> ```XML
> 
> #[allow(clippy::too_many_arguments)]
> pub fn expand_par_iter_mut_structs(
> ```

Change to multiple functions as in the previous pr



_Code quote:_
```XML
pub fn expand_par_iter_mut_structs(
```

**Review by ohad-agadi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/955)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @shaharsamocha7)

___
*[`crates/air_utils/src/lookup_data/mod.rs` line 40 at r3](https://reviewable.io/reviews/starkware-libs/stwo/955#-OFMqpJcC0-wCAX17WVg:-OFQlQba0r0xinAry0ys:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/5764a4878f4a01e284fc422cde27aeff9944f660/crates/air_utils/src/lookup_data/mod.rs#L40)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Let's keep both tests
</blockquote></details>

Done.
___
*[`crates/air_utils_derive/src/iterable_field.rs` line 219 at r3](https://reviewable.io/reviews/starkware-libs/stwo/955#-OFMrF1P5ZrgJV4jGqx6:-OFQlMwH1BrNT6lq5siw:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/5764a4878f4a01e284fc422cde27aeff9944f660/crates/air_utils_derive/src/iterable_field.rs#L219)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Introduce head var to match with the split_first, split_last impl
</blockquote></details>

Done.
___
*[`crates/air_utils_derive/src/par_iter.rs` line 9 at r3](https://reviewable.io/reviews/starkware-libs/stwo/955#-OFMxgYTDa0lPaEDzJHc:-OFQlNn07Vw2xCdcQ38x:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/5764a4878f4a01e284fc422cde27aeff9944f660/crates/air_utils_derive/src/par_iter.rs#L9)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Change to multiple functions as in the previous pr
</blockquote></details>

Done.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/955#-:-OFRQrGXB_VHR_aFeNBL:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @ohad-starkware)

___
*[`crates/air_utils_derive/src/par_iter.rs` line 18 at r5](https://reviewable.io/reviews/starkware-libs/stwo/955#-OFRQeeX5RpTngigpb3l:-OFRQeeX5RpTngigpb3m:b2ni2nk) ([raw file](https://github.com/starkware-libs/stwo/blob/a3b80560e7ee0df526ad2d88ac55259a00f6f415/crates/air_utils_derive/src/par_iter.rs#L18)):*
> ```XML
>     let producer_code =
>         generate_row_producer(struct_name, iterable_fields, &lifetime, &split_index);
>     let oar_iter_struct = generate_par_iter_struct(struct_name, iterable_fields, &lifetime);
> ```

fix



_Suggestion:_
```XML
let par_iter_struct = generate_par_iter_struct(struct_name, iterable_fields, &lifetime);
```

**Review by ohad-agadi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/955)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @shaharsamocha7)

___
*[`crates/air_utils_derive/src/par_iter.rs` line 18 at r5](https://reviewable.io/reviews/starkware-libs/stwo/955#-OFRQeeX5RpTngigpb3l:-OFRV1dBByE1vX5SbfMj:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/a3b80560e7ee0df526ad2d88ac55259a00f6f415/crates/air_utils_derive/src/par_iter.rs#L18)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

fix
</blockquote></details>

Done.

**Pull request merged**
