### PR TITLE
Make CommitmentSchemeProver::prove_values take ownership

### PR DESCRIPTION
**Pull request by andrewmilson**
Simplifies the implementation of quotient commitment tree in following PR

This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/852)

### CODE REVIEW

**Comment by andrewmilson** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/852?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#852** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/852?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#832** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/832?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#831** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/831?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @andrewmilson and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Alon-Ti — CHANGES_REQUESTED** [review]
:lgtm: up to stylistic question.

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/852#-:-O7YAaQJCPB6Yb5RuwYI:b-83myif)* status: all files reviewed, 1 unresolved discussion (waiting on @andrewmilson and @shaharsamocha7)

___
*[`crates/prover/src/core/prover/mod.rs` line 150 at r1](https://reviewable.io/reviews/starkware-libs/stwo/852#-O7YA1Um8f5Thqpeoh75:-O7YA1Un9PGYr9D7xfKu:b-upsva7) ([raw file](https://github.com/starkware-libs/stwo/blob/4de2301f0572058712985820d825980fa885fcd6/crates/prover/src/core/prover/mod.rs#L150)):*
> ```XML
>     fn extract_composition_oods_eval(&self) -> Result<SecureField, InvalidOodsSampleStructure> {
>         // TODO(andrew): `[.., composition_mask, _quotients_mask]` when add quotients commitment.
>         let [_traces_mask @ .., composition_mask] = &**self.sampled_values else {
> ```

Why are you binding `traces_mask`?

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/852)* status: all files reviewed, 1 unresolved discussion (waiting on @Alon-Ti and @shaharsamocha7)

___
*[`crates/prover/src/core/prover/mod.rs` line 150 at r1](https://reviewable.io/reviews/starkware-libs/stwo/852#-O7YA1Um8f5Thqpeoh75:-O7YAlAo3Web0mTK8aAi:bqj40f5) ([raw file](https://github.com/starkware-libs/stwo/blob/4de2301f0572058712985820d825980fa885fcd6/crates/prover/src/core/prover/mod.rs#L150)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

Why are you binding `traces_mask`?
</blockquote></details>

I would have done `_ @ ..` but it errors strangely.

OHHH. Wow didn't realise you can just do `..` SMH, tyty

**Review by Alon-Ti — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/852)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 9 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/852#-:-O7i_SBSCSzJdapgOeMR:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @andrewmilson)

**Review by shaharsamocha7 — APPROVED** [review]
> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/852)* status: all files reviewed, 1 unresolved discussion (waiting on @andrewmilson)

___
*[`crates/prover/src/examples/plonk/mod.rs` line 301 at r3](https://reviewable.io/reviews/starkware-libs/stwo/852#-OCSYYBi5A6XVtevlPvE:-OCSYYBi5A6XVtevlPvF:b-l6mkjh) ([raw file](https://github.com/starkware-libs/stwo/blob/c46d77be6a8d17d679139544c4e3ca021c1b1bef/crates/prover/src/examples/plonk/mod.rs#L301)):*
> ```XML
>         let sizes = component.trace_log_degree_bounds();
> 
>         // Constant columns.
> ```

rename



_Suggestion:_
```XML
// Preprocessed columns.
```

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/852)* status: 8 of 11 files reviewed, all discussions resolved (waiting on @shaharsamocha7)

___
*[`crates/prover/src/examples/plonk/mod.rs` line 301 at r3](https://reviewable.io/reviews/starkware-libs/stwo/852#-OCSYYBi5A6XVtevlPvE:-OCTkmQg18PeS5qe_G0_:bky53he) ([raw file](https://github.com/starkware-libs/stwo/blob/ba154887d25c2ec745ef4f44b169dd136f916b22/crates/prover/src/examples/plonk/mod.rs#L301)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

rename
</blockquote></details>

Done thanks

**Pull request merged**
