### PR TITLE
Unite impls of DomainEvaluationAccumulator

### PR DESCRIPTION
**Pull request by Gali-StarkWare**

### CODE REVIEW

**Comment by Gali-StarkWare** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/936?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#936** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/936?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/936?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#934** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/934?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#933** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/933?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#930** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/930?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/936#-:-OEIiItJCQeiKHBJueoq:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ohad-starkware)

**Review by shaharsamocha7 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/936)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ohad-starkware)

**Comment by Gali-StarkWare** [comment]
### Merge activity

* **Dec 18, 5:58 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/936).

**Pull request merged**
