### PR TITLE
Move verify function to prover module.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/457)

### CODE REVIEW

**Comment by alonh5** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/457?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#457** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/457?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#454** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/454?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#453** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/453?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/457)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`src/core/prover/mod.rs` line 138 at r1](https://reviewable.io/reviews/starkware-libs/stwo/457#-NsmUad7Ck0YlaqAsmPB:-NsmUad7Ck0YlaqAsmPC:b-e1r641) ([raw file](https://github.com/starkware-libs/stwo/blob/6c2f8b539ac7ced1a98a964ea7a76a80d94358ee/src/core/prover/mod.rs#L138)):*
> ```XML
>     trace_domain_log_size: u32,
> ) -> bool {
>     let mut commitment_scheme = CommitmentSchemeVerifier::new();
> ```

Add comments corresponding to the comment in the prove() function.
For example,
// Evaluate and commit on trace.
corresponds to
// Read trace commitment.

Andd add some comment here in general, for each part of the protocol.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/457#-:-Nsmp7TxCDjGz0butjTa:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

**Review by spapinistarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/457)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Pull request merged**
