### PR TITLE
Add sumcheck prover and verifier

### PR DESCRIPTION
**Pull request by andrewmilson**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/566)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/566)* status: all files reviewed, 5 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`src/core/lookups/sumcheck.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/stwo/566#-NvVt6PL7DUbVdN1z5VV:-NvVt6PM3ol-VgYahYWh:bug6xll) ([raw file](https://github.com/starkware-libs/stwo/blob/7fb26b59304109dec81916af7e9554e9ed6055f0/src/core/lookups/sumcheck.rs#L12)):*
> ```XML
> /// and making transformations on `g` in the context of the protocol. It is indented to be used in
> /// conjunction with [`prove()`] to generate proofs.
> pub trait SumcheckOracle: Sized {
> ```

Consider being more dedscriptive here, so readers won't have to dive into it to understand what it is.



_Suggestion:_
```XML
MultivariatePolyOracle
```
___
*[`src/core/lookups/sumcheck.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/stwo/566#-NvVuSWXE188Jtoaoms0:-NvVuSWXE188Jtoaoms1:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/7fb26b59304109dec81916af7e9554e9ed6055f0/src/core/lookups/sumcheck.rs#L14)):*
> ```XML
> pub trait SumcheckOracle: Sized {
>     /// Returns the number of variables in `g`.
>     fn num_variables(&self) -> usize;
> ```





_Suggestion:_
```XML
n_variables
```
___
*[`src/core/lookups/sumcheck.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/stwo/566#-NvVtO7M9EXJ6pSO1Edo:-NvVtO7M9EXJ6pSO1Edp:b-e9bykn) ([raw file](https://github.com/starkware-libs/stwo/blob/7fb26b59304109dec81916af7e9554e9ed6055f0/src/core/lookups/sumcheck.rs#L24)):*
> ```XML
>     /// knowing `claim` and either `f(0)` or `f(1)` allows us to immediately determine the other
>     /// value with a single subtraction.
>     fn univariate_sum(&self, claim: SecureField) -> UnivariatePolynomial<SecureField>;
> ```

Can we find a better name for this?
If we can describe it's summing over x_2,..., as a poly in x_1, in a single name, that would add so much to the readability.
Something like `sum_as_poly_in_first_var()`



_Code quote:_
```XML
univariate_sum
```
___
*[`src/core/lookups/sumcheck.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/stwo/566#-NvVunkKDz6LZIZ2ijNm:-NvVunkKDz6LZIZ2ijNn:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/7fb26b59304109dec81916af7e9554e9ed6055f0/src/core/lookups/sumcheck.rs#L43)):*
> ```XML
> pub fn prove<O: SumcheckOracle>(
>     mut claim: SecureField,
>     mut oracle: O,
> ```





_Suggestion:_
```XML
mut multivariate_poly: O,
```
___
*[`src/core/lookups/sumcheck.rs` line 85 at r1](https://reviewable.io/reviews/starkware-libs/stwo/566#-NvVv_Ky8JQHyKWbjG-W:-NvVv_Ky8JQHyKWbjG-X:b-ko9r9p) ([raw file](https://github.com/starkware-libs/stwo/blob/7fb26b59304109dec81916af7e9554e9ed6055f0/src/core/lookups/sumcheck.rs#L85)):*
> ```XML
>         }
> 
>         let sum = round_polynomial.eval_at_point(SecureField::zero())
> ```

Add a TODO to optimize this by sending one less coefficient, and compute it from the claim, instead of checking the claim.
(Can also be done by quotienting).

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/566)* status: 1 of 5 files reviewed, 4 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`src/core/lookups/sumcheck.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/stwo/566#-NvVt6PL7DUbVdN1z5VV:-NvZtqg81l7cGKCa18xl:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/7fb26b59304109dec81916af7e9554e9ed6055f0/src/core/lookups/sumcheck.rs#L12)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Consider being more dedscriptive here, so readers won't have to dive into it to understand what it is.
</blockquote></details>

Done.
___
*[`src/core/lookups/sumcheck.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/stwo/566#-NvVuSWXE188Jtoaoms0:-NvZtqG--9zVwktroV8K:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/7fb26b59304109dec81916af7e9554e9ed6055f0/src/core/lookups/sumcheck.rs#L14)):*
> ```XML
> pub trait SumcheckOracle: Sized {
>     /// Returns the number of variables in `g`.
>     fn num_variables(&self) -> usize;
> ```

Done.
___
*[`src/core/lookups/sumcheck.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/stwo/566#-NvVunkKDz6LZIZ2ijNm:-NvZtsPp1WVFLqfT5ShE:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/7fb26b59304109dec81916af7e9554e9ed6055f0/src/core/lookups/sumcheck.rs#L43)):*
> ```XML
> pub fn prove<O: SumcheckOracle>(
>     mut claim: SecureField,
>     mut oracle: O,
> ```

Done.
___
*[`src/core/lookups/sumcheck.rs` line 85 at r1](https://reviewable.io/reviews/starkware-libs/stwo/566#-NvVv_Ky8JQHyKWbjG-W:-NvZwqfm4IMJATi0c_ss:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/7fb26b59304109dec81916af7e9554e9ed6055f0/src/core/lookups/sumcheck.rs#L85)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Add a TODO to optimize this by sending one less coefficient, and compute it from the claim, instead of checking the claim.
(Can also be done by quotienting).
</blockquote></details>

Done.

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/566)* status: all files reviewed, 3 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`src/core/lookups/sumcheck.rs` line 60 at r3](https://reviewable.io/reviews/starkware-libs/stwo/566#-NvgB-4w1YK0qtSRwFWu:-NvgB-4w1YK0qtSRwFWv:b-6sghcr) ([raw file](https://github.com/starkware-libs/stwo/blob/9bc93a25a4a626278ad649c4b62ed352a1cae228/src/core/lookups/sumcheck.rs#L60)):*
> ```XML
> ) -> (SumcheckProof, Vec<SecureField>, Vec<O>, Vec<SecureField>) {
>     let n_vars = multivariate_polys[0].n_variables();
>     assert!(multivariate_polys.iter().all(|o| o.n_variables() == n_vars));
> ```

Aren't we supposed to batch polys of different degress in the input layer? Do you extend the smaller polys?
___
*[`src/core/lookups/sumcheck.rs` line 69 at r3](https://reviewable.io/reviews/starkware-libs/stwo/566#-NvgDuURA4uXFCoAbBdX:-NvgDuURA4uXFCoAbBdY:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/9bc93a25a4a626278ad649c4b62ed352a1cae228/src/core/lookups/sumcheck.rs#L69)):*
> ```XML
>         let this_round_polys = zip(&multivariate_polys, &claims)
>             .map(|(mvp, &claim)| mvp.sum_as_poly_in_first_variable(claim))
>             .collect::<Vec<UnivariatePoly<SecureField>>>();
> ```





_Suggestion:_
```XML
collect_vec
```
___
*[`src/core/lookups/sumcheck.rs` line 73 at r3](https://reviewable.io/reviews/starkware-libs/stwo/566#-NvgE5AAEoAFoZsf4hMM:-NvgE5AAEoAFoZsf4hMN:b89o78k) ([raw file](https://github.com/starkware-libs/stwo/blob/9bc93a25a4a626278ad649c4b62ed352a1cae228/src/core/lookups/sumcheck.rs#L73)):*
> ```XML
>         let round_poly = random_linear_combination(&this_round_polys, lambda);
> 
>         assert!(round_poly.degree() <= MAX_DEGREE,);
> ```

Why ","?



_Suggestion:_
```XML
assert!(round_poly.degree() <= MAX_DEGREE);
```

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/566)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`src/core/lookups/sumcheck.rs` line 60 at r3](https://reviewable.io/reviews/starkware-libs/stwo/566#-NvgB-4w1YK0qtSRwFWu:-NvgeAlA-Xn3XQMcQRK9:b-ni60zf) ([raw file](https://github.com/starkware-libs/stwo/blob/9bc93a25a4a626278ad649c4b62ed352a1cae228/src/core/lookups/sumcheck.rs#L60)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Aren't we supposed to batch polys of different degress in the input layer? Do you extend the smaller polys?
</blockquote></details>

I moved the batching logic from GKR into here now. WDYT?
___
*[`src/core/lookups/sumcheck.rs` line 69 at r3](https://reviewable.io/reviews/starkware-libs/stwo/566#-NvgDuURA4uXFCoAbBdX:-Nvgf0jTBLKkzA77W43L:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/9bc93a25a4a626278ad649c4b62ed352a1cae228/src/core/lookups/sumcheck.rs#L69)):*
> ```XML
>         let this_round_polys = zip(&multivariate_polys, &claims)
>             .map(|(mvp, &claim)| mvp.sum_as_poly_in_first_variable(claim))
>             .collect::<Vec<UnivariatePoly<SecureField>>>();
> ```

Done.
___
*[`src/core/lookups/sumcheck.rs` line 73 at r3](https://reviewable.io/reviews/starkware-libs/stwo/566#-NvgE5AAEoAFoZsf4hMM:-Nvgf17D-hWvtONp3YXa:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/9bc93a25a4a626278ad649c4b62ed352a1cae228/src/core/lookups/sumcheck.rs#L73)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Why ","?
</blockquote></details>

Done.

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/566)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`src/core/lookups/sumcheck.rs` line 60 at r3](https://reviewable.io/reviews/starkware-libs/stwo/566#-NvgB-4w1YK0qtSRwFWu:-NvlId_s3Kv8ohKB-OP-:bmxgzyj) ([raw file](https://github.com/starkware-libs/stwo/blob/9bc93a25a4a626278ad649c4b62ed352a1cae228/src/core/lookups/sumcheck.rs#L60)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

I moved the batching logic from GKR into here now. WDYT?
</blockquote></details>

Also updated the docs.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/566)* status: 3 of 5 files reviewed, 9 unresolved discussions (waiting on @andrewmilson and @spapinistarkware)

___
*[`src/core/backend/cpu/lookups/mle.rs` line 41 at r5](https://reviewable.io/reviews/starkware-libs/stwo/566#-Nw-6edC3-efeJZ1qcEo:-Nw-6edD9KUXz73q7z4H:bompbp2) ([raw file](https://github.com/starkware-libs/stwo/blob/439eaf3b6fd41395dbbc0cf5166296b299a0a944/src/core/backend/cpu/lookups/mle.rs#L41)):*
> ```XML
>             let rhs_eval = evals[i + midpoint];
>             // Equivalent to `eq(0, assignment) * lhs_eval + eq(1, assignment) * rhs_eval`.
>             evals[i] = lhs_eval + assignment * (rhs_eval - lhs_eval);
> ```

Consider separating this logic to a function



_Code quote:_
```XML
lhs_eval + assignment * (rhs_eval - lhs_eval)
```
___
*[`src/core/lookups/mle.rs` line 9 at r5](https://reviewable.io/reviews/starkware-libs/stwo/566#-Nw-6-y499PJsCwN2yPX:-Nw-6-y499PJsCwN2yPY:bdfpffm) ([raw file](https://github.com/starkware-libs/stwo/blob/439eaf3b6fd41395dbbc0cf5166296b299a0a944/src/core/lookups/mle.rs#L9)):*
> ```XML
> use crate::core::fields::Field;
> 
> /// TODO
> ```

What's this todo?



_Code quote:_
```XML
/// TODO
```
___
*[`src/core/lookups/sumcheck.rs` line 13 at r5](https://reviewable.io/reviews/starkware-libs/stwo/566#-Nw-49Lu0wvffBtDy1gk:-Nw-49Lu0wvffBtDy1gl:b-e5aqef) ([raw file](https://github.com/starkware-libs/stwo/blob/439eaf3b6fd41395dbbc0cf5166296b299a0a944/src/core/lookups/sumcheck.rs#L13)):*
> ```XML
> 
> /// The sum-check protocol enables proving claims about the sum of a multivariate polynomial
> /// `g(x_1, ..., x_n)` over the boolean hypercube. This trait provides methods for evaluating sums
> ```

Should this be in the file doc?

Can you also change to zero-based indexing? :)



_Code quote:_
```XML
/// The sum-check protocol enables proving claims about the sum of a multivariate polynomial
/// `g(x_1, ..., x_n)` over the boolean hypercube. This trait provides methods for evaluating sums
```
___
*[`src/core/lookups/sumcheck.rs` line 14 at r5](https://reviewable.io/reviews/starkware-libs/stwo/566#-Nw-4HzOEnt908abyFiT:-Nw-4HzOEnt908abyFiU:b3kre) ([raw file](https://github.com/starkware-libs/stwo/blob/439eaf3b6fd41395dbbc0cf5166296b299a0a944/src/core/lookups/sumcheck.rs#L14)):*
> ```XML
> /// The sum-check protocol enables proving claims about the sum of a multivariate polynomial
> /// `g(x_1, ..., x_n)` over the boolean hypercube. This trait provides methods for evaluating sums
> /// and making transformations on `g` in the context of the protocol. It is indented to be used in
> ```

?



_Suggestion:_
```XML
It is intended to be used
```
___
*[`src/core/lookups/sumcheck.rs` line 21 at r5](https://reviewable.io/reviews/starkware-libs/stwo/566#-Nw-7KXFBsndrwoVdnR3:-Nw-7KXG3yX7Om-vVR8t:b1p8hpo) ([raw file](https://github.com/starkware-libs/stwo/blob/439eaf3b6fd41395dbbc0cf5166296b299a0a944/src/core/lookups/sumcheck.rs#L21)):*
> ```XML
> 
>     /// Computes the sum of `g(x_1, x_2, ..., x_n)` over all `(x_2, ..., x_n)` in `{0, 1}^{n-1}`,
>     /// effectively reducing the sum over `g` to a univariate polynomial in `x_1`.
> ```

Is this univariate poly is always a line?



_Code quote:_
```XML
to a univariate polynomial in `x_1`.
```
___
*[`src/core/lookups/utils.rs` line 179 at r5](https://reviewable.io/reviews/starkware-libs/stwo/566#-Nw-7qZN1JcHF-BrkVje:-Nw-7qZOAiUK4-X9Pkpi:b-vn96w9) ([raw file](https://github.com/starkware-libs/stwo/blob/439eaf3b6fd41395dbbc0cf5166296b299a0a944/src/core/lookups/utils.rs#L179)):*
> ```XML
> 
>     #[test]
>     fn lagrange_interpolation_works() {
> ```

Can you also add test for horner_eval?



_Code quote:_
```XML
n lagrange_interpolation_works() {
```

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/566)* status: 1 of 5 files reviewed, 8 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`src/core/backend/cpu/lookups/mle.rs` line 41 at r5](https://reviewable.io/reviews/starkware-libs/stwo/566#-Nw-6edC3-efeJZ1qcEo:-Nw08e84B8tO6zDJkoye:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/439eaf3b6fd41395dbbc0cf5166296b299a0a944/src/core/backend/cpu/lookups/mle.rs#L41)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Consider separating this logic to a function
</blockquote></details>

Done.
___
*[`src/core/lookups/mle.rs` line 9 at r5](https://reviewable.io/reviews/starkware-libs/stwo/566#-Nw-6-y499PJsCwN2yPX:-Nw05hxxEd5dtemmVtFA:bm72c4z) ([raw file](https://github.com/starkware-libs/stwo/blob/439eaf3b6fd41395dbbc0cf5166296b299a0a944/src/core/lookups/mle.rs#L9)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

What's this todo?
</blockquote></details>

Done. My bad, removed, ty.
___
*[`src/core/lookups/sumcheck.rs` line 13 at r5](https://reviewable.io/reviews/starkware-libs/stwo/566#-Nw-49Lu0wvffBtDy1gk:-Nw02nytAZOaYecjTBGv:b-gnqrj2) ([raw file](https://github.com/starkware-libs/stwo/blob/439eaf3b6fd41395dbbc0cf5166296b299a0a944/src/core/lookups/sumcheck.rs#L13)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Should this be in the file doc?

Can you also change to zero-based indexing? :)
</blockquote></details>

Done.  Zero-based indexing is annoying with "(n-1)"s everywhere. Do you still think it should be changed?
___
*[`src/core/lookups/sumcheck.rs` line 14 at r5](https://reviewable.io/reviews/starkware-libs/stwo/566#-Nw-4HzOEnt908abyFiT:-Nw03dPlCl4HQx_uGa4Y:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/439eaf3b6fd41395dbbc0cf5166296b299a0a944/src/core/lookups/sumcheck.rs#L14)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.
___
*[`src/core/lookups/sumcheck.rs` line 21 at r5](https://reviewable.io/reviews/starkware-libs/stwo/566#-Nw-7KXFBsndrwoVdnR3:-Nw01qvZ2Va4Hj6t9hoN:bhsech0) ([raw file](https://github.com/starkware-libs/stwo/blob/439eaf3b6fd41395dbbc0cf5166296b299a0a944/src/core/lookups/sumcheck.rs#L21)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Is this univariate poly is always a line?
</blockquote></details>

No, oracles for grandproduct and logup return cubic polynomials
___
*[`src/core/lookups/utils.rs` line 179 at r5](https://reviewable.io/reviews/starkware-libs/stwo/566#-Nw-7qZN1JcHF-BrkVje:-Nw04WNC16a6k1cw8EbL:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/439eaf3b6fd41395dbbc0cf5166296b299a0a944/src/core/lookups/utils.rs#L179)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can you also add test for horner_eval?
</blockquote></details>

Done.

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/566)* status: 1 of 5 files reviewed, 4 unresolved discussions (waiting on @spapinistarkware)

___
*[`src/core/lookups/sumcheck.rs` line 13 at r5](https://reviewable.io/reviews/starkware-libs/stwo/566#-Nw-49Lu0wvffBtDy1gk:-Nw0I2TNAQ9baX4g-QgO:b-dkjj8t) ([raw file](https://github.com/starkware-libs/stwo/blob/439eaf3b6fd41395dbbc0cf5166296b299a0a944/src/core/lookups/sumcheck.rs#L13)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Done.  Zero-based indexing is annoying with "(n-1)"s everywhere. Do you still think it should be changed?
</blockquote></details>

I'm ok with that

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/566)* status: 0 of 8 files reviewed, 4 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`src/core/lookups/sumcheck.rs` line 13 at r5](https://reviewable.io/reviews/starkware-libs/stwo/566#-Nw-49Lu0wvffBtDy1gk:-Nw2W5ze1rvV9s4mAdiz:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/439eaf3b6fd41395dbbc0cf5166296b299a0a944/src/core/lookups/sumcheck.rs#L13)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I'm ok with that
</blockquote></details>

Done.

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/566)* status: all files reviewed, 2 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`crates/prover/src/core/backend/cpu/lookups/mle.rs` line 49 at r7](https://reviewable.io/reviews/starkware-libs/stwo/566#-NwE7QjYD6kJaJiKwkNE:-NwE7QjYD6kJaJiKwkNF:bzffe2t) ([raw file](https://github.com/starkware-libs/stwo/blob/bea59e8e29938f9a31207aa875d58a332715703d/crates/prover/src/core/backend/cpu/lookups/mle.rs#L49)):*
> ```XML
> }
> 
> impl MultivariatePolyOracle for Mle<CPUBackend, SecureField> {
> ```

Why only for CPUBackend?

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/566#-:-NwEBmkyC6uam0kpsnPe:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/566)* status: all files reviewed, 2 unresolved discussions (waiting on @andrewmilson)

___
*[`crates/prover/src/core/lookups/utils.rs` line 10 at r7](https://reviewable.io/reviews/starkware-libs/stwo/566#-NwFf7j5E5j-xWv9Fqe3:-NwFf7j5E5j-xWv9Fqe4:b-13pdhh) ([raw file](https://github.com/starkware-libs/stwo/blob/bea59e8e29938f9a31207aa875d58a332715703d/crates/prover/src/core/lookups/utils.rs#L10)):*
> ```XML
> /// Univariate polynomial stored as coefficients in the monomial basis.
> #[derive(Debug, Clone)]
> pub struct UnivariatePoly<F: Field>(Vec<F>);
> ```

Should this be under the regular Poly folder?



_Code quote:_
```XML
pub struct UnivariatePoly<F: Field>(Vec<F>);
```

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/566#-:-NwJmwesEpoL5_iMaiJi:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @andrewmilson)

___
*[`crates/prover/src/core/lookups/sumcheck.rs` line 292 at r7](https://reviewable.io/reviews/starkware-libs/stwo/566#-NwJmuRiACUPzMzoqSL9:-NwJmuRiACUPzMzoqSLA:byp18fd) ([raw file](https://github.com/starkware-libs/stwo/blob/bea59e8e29938f9a31207aa875d58a332715703d/crates/prover/src/core/lookups/sumcheck.rs#L292)):*
> ```XML
>         let seed = Blake2sHasher::hash(&[]);
>         Blake2sChannel::new(seed)
>     }
> ```

Remove



_Code quote:_
```XML
    fn test_channel() -> Blake2sChannel {
        let seed = Blake2sHasher::hash(&[]);
        Blake2sChannel::new(seed)
    }
```

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/566)* status: all files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/core/backend/cpu/lookups/mle.rs` line 49 at r7](https://reviewable.io/reviews/starkware-libs/stwo/566#-NwE7QjYD6kJaJiKwkNE:-NwFC6ke-Tc0n1_Kvgko:b-jn5s6n) ([raw file](https://github.com/starkware-libs/stwo/blob/bea59e8e29938f9a31207aa875d58a332715703d/crates/prover/src/core/backend/cpu/lookups/mle.rs#L49)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Why only for CPUBackend?
</blockquote></details>

Discussed offline.
___
*[`crates/prover/src/core/lookups/sumcheck.rs` line 292 at r7](https://reviewable.io/reviews/starkware-libs/stwo/566#-NwJmuRiACUPzMzoqSL9:-NwKIj-A0GIJMWjeev7P:b-6zptt6) ([raw file](https://github.com/starkware-libs/stwo/blob/bea59e8e29938f9a31207aa875d58a332715703d/crates/prover/src/core/lookups/sumcheck.rs#L292)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Remove
</blockquote></details>

Why can't it stay? It's a util for the tests
___
*[`crates/prover/src/core/lookups/utils.rs` line 10 at r7](https://reviewable.io/reviews/starkware-libs/stwo/566#-NwFf7j5E5j-xWv9Fqe3:-NwKIzQkAyMhFrtI2W8s:b-vrpq2x) ([raw file](https://github.com/starkware-libs/stwo/blob/bea59e8e29938f9a31207aa875d58a332715703d/crates/prover/src/core/lookups/utils.rs#L10)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Should this be under the regular Poly folder?
</blockquote></details>

It could. I put it in the lookups folder as a util because it's not optimised or intended for anything other than storing and evaluating the sumcheck rounds. Do you think it should still go in the poly folder?

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/566)* status: all files reviewed, 3 unresolved discussions (waiting on @andrewmilson and @spapinistarkware)

___
*[`crates/prover/src/core/lookups/sumcheck.rs` line 292 at r7](https://reviewable.io/reviews/starkware-libs/stwo/566#-NwJmuRiACUPzMzoqSL9:-NwKKAw34gaF7wAc1AhE:bwzef51) ([raw file](https://github.com/starkware-libs/stwo/blob/bea59e8e29938f9a31207aa875d58a332715703d/crates/prover/src/core/lookups/sumcheck.rs#L292)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Why can't it stay? It's a util for the tests
</blockquote></details>

Ohh my bad, thought that it is a test.

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/566)* status: all files reviewed, 3 unresolved discussions (waiting on @andrewmilson and @spapinistarkware)

___
*[`crates/prover/src/core/lookups/utils.rs` line 10 at r7](https://reviewable.io/reviews/starkware-libs/stwo/566#-NwFf7j5E5j-xWv9Fqe3:-NwKKHznEWJeFLcRDWjK:b97la6x) ([raw file](https://github.com/starkware-libs/stwo/blob/bea59e8e29938f9a31207aa875d58a332715703d/crates/prover/src/core/lookups/utils.rs#L10)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

It could. I put it in the lookups folder as a util because it's not optimised or intended for anything other than storing and evaluating the sumcheck rounds. Do you think it should still go in the poly folder?
</blockquote></details>

No, you can keep it here.

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/566)* status: all files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/core/lookups/sumcheck.rs` line 292 at r7](https://reviewable.io/reviews/starkware-libs/stwo/566#-NwJmuRiACUPzMzoqSL9:-NwKRxbQ7B2hmVj6ks3s:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/bea59e8e29938f9a31207aa875d58a332715703d/crates/prover/src/core/lookups/sumcheck.rs#L292)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Ohh my bad, thought that it is a test.
</blockquote></details>

Done.

**Review by shaharsamocha7 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/566)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Pull request merged**
