### PR TITLE
Modify trace_log_degree_bounds for interaction.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/638)

### CODE REVIEW

**Comment by alonh5** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/638?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#638** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/638?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#637** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/637?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#636** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/636?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#634** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/634?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#633** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/633?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#631** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/631?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#582** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/582?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#589](https://github.com/starkware-libs/stwo/pull/589) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/589?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#573** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/573?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#574](https://github.com/starkware-libs/stwo/pull/574) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/574?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#572** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/572?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#562** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/562?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by andrewmilson — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/638#-:-O-iScKd9ycLymVUmIxb:bnfp4nl)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @shaharsamocha7)

___
*[`crates/prover/src/core/air/air_ext.rs` line 102 at r2](https://reviewable.io/reviews/starkware-libs/stwo/638#-O-iQJuu7T2kJQedJFhM:-O-iQJuu7T2kJQedJFhN:bxwl6q8) ([raw file](https://github.com/starkware-libs/stwo/blob/6bd6f18d36e0ceb075967f3625205041d8f982a1/crates/prover/src/core/air/air_ext.rs#L102)):*
> ```XML
>                 .zip_eq(&mut component_traces)
>                 .for_each(|(component, component_trace)| {
>                     let n_columns = component.trace_log_degree_bounds()[1].len();
> ```

Perhaps we can store something like INTERACTION_TRACE = 1 otherwise I feel it's not immediately clear it's referring to the number of interaction trace columns. WDYT?



_Suggestion:_
```XML
let n_columns = component.trace_log_degree_bounds()[INTERACTION_TRACE].len();
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/638)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @andrewmilson and @shaharsamocha7)

___
*[`crates/prover/src/core/air/air_ext.rs` line 102 at r2](https://reviewable.io/reviews/starkware-libs/stwo/638#-O-iQJuu7T2kJQedJFhM:-O-kcvjc0DDTkWqkKtZ7:b-3rg28d) ([raw file](https://github.com/starkware-libs/stwo/blob/6bd6f18d36e0ceb075967f3625205041d8f982a1/crates/prover/src/core/air/air_ext.rs#L102)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Perhaps we can store something like INTERACTION_TRACE = 1 otherwise I feel it's not immediately clear it's referring to the number of interaction trace columns. WDYT?
</blockquote></details>

Good idea. Done in new PR (669) on top of the stack (too many conflicts).

**Review by andrewmilson — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/638#-:-O-mez7n-YV6CaF2ClW4:bnfp4nl)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Comment by alonh5** [comment]
### Merge activity

* **Jun 20, 6:54 AM EDT**: @alonh5 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/638).

**Pull request merged**
