### PR TITLE
Add SIMD prefix sum

### PR DESCRIPTION
**Pull request by andrewmilson**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/734)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/734)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @andrewmilson)

___
*[`crates/prover/src/core/backend/simd/prefix_sum.rs` line 143 at r1](https://reviewable.io/reviews/starkware-libs/stwo/734#-O1yqWzg0JISskr9DmyZ:-O1yqWzg0JISskr9Dmy_:bt0u6dy) ([raw file](https://github.com/starkware-libs/stwo/blob/70746856a668a21da4b6de3a69f3bffb9e601780/crates/prover/src/core/backend/simd/prefix_sum.rs#L143)):*
> ```XML
>     *hi += *lo;
>     *lo = tmp;
> }
> ```

Do these changes for inclusive sum



_Suggestion:_
```XML
fn up_sweep_val<F: AddAssign + Copy>(lo: F, hi: &mut F) {
    *lo += hi;
}

fn down_sweep_val<F: AddAssign + Copy>(lo: &mut F, hi: &mut F) {
    (*lo, *hi) = (*lo - *hi, *lo)
}
```

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/734)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @andrewmilson)

___
*[`crates/prover/src/core/backend/simd/prefix_sum.rs` line 143 at r1](https://reviewable.io/reviews/starkware-libs/stwo/734#-O1yqWzg0JISskr9DmyZ:-O1ywBvu-C-qjtZHiH8M:b-3s1i6n) ([raw file](https://github.com/starkware-libs/stwo/blob/70746856a668a21da4b6de3a69f3bffb9e601780/crates/prover/src/core/backend/simd/prefix_sum.rs#L143)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Do these changes for inclusive sum
</blockquote></details>

Also, when "recursing down", you should use the first chunk, not the last.

up_sweep makes the even indices (low) be the sum of the pair (even,odd).
The, we "recurse" by prefix summing the evens (i.e. pair sums).
Then, each entry in the evens array is the prefix sum incuding the pair. Thus, it is the prefix sum of the odd.
The even pefix sum is corrected by removing the odd element.

p[i] = a[2i]+a[2i+1]
prefix_sum(p)
p[i] = a[0] + .. + a[2i+1]
res[2i+1] = p[i]
res[2i] = p[i] - a[2i+1]

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/734)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/prefix_sum.rs` line 143 at r1](https://reviewable.io/reviews/starkware-libs/stwo/734#-O1yqWzg0JISskr9DmyZ:-O2-uGeZ2tMA-CHliqXP:br5s1ir) ([raw file](https://github.com/starkware-libs/stwo/blob/70746856a668a21da4b6de3a69f3bffb9e601780/crates/prover/src/core/backend/simd/prefix_sum.rs#L143)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Also, when "recursing down", you should use the first chunk, not the last.

up_sweep makes the even indices (low) be the sum of the pair (even,odd).
The, we "recurse" by prefix summing the evens (i.e. pair sums).
Then, each entry in the evens array is the prefix sum incuding the pair. Thus, it is the prefix sum of the odd.
The even pefix sum is corrected by removing the odd element.

p[i] = a[2i]+a[2i+1]
prefix_sum(p)
p[i] = a[0] + .. + a[2i+1]
res[2i+1] = p[i]
res[2i] = p[i] - a[2i+1]
</blockquote></details>

Fantastic, thanks

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/734#-:-O200iBV8f6xGJpD5fGW:bnfp4nl)* status: 2 of 5 files reviewed, all discussions resolved

**Pull request merged**
