### PR TITLE
Save twiddles

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/380)

### CODE REVIEW

**Review by ilyalesokhin-starkware — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/380#-:-Ns2HMUc4olLYnSMkkD0:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Comment by ilyalesokhin-starkware** [comment]
*[`src/core/backend/avx512/fft.rs` line 274 at r4](https://reviewable.io/reviews/starkware-libs/stwo/380#-Ns3G6FOBGEnhER8bOG5:-Ns3G6FOBGEnhER8bOG6:b-aflr8e) ([raw file](https://github.com/starkware-libs/stwo/blob/becaa490bcab5f35b78d1177af7030261e9df2ad/src/core/backend/avx512/fft.rs#L274)):*
> ```XML
>     };
>     let t = _mm512_permutexvar_epi32(INDICES_FROM_T1, t);
>     let t = _mm512_xor_epi32(t, NEGATION_MASK);
> ```

what is this?



_Code quote:_
```XML
    const INDICES_FROM_T1: __m512i = unsafe {
        core::mem::transmute([
            0b0001, 0b0001, 0b0000, 0b0000, 0b0011, 0b0011, 0b0010, 0b0010, 0b0101, 0b0101, 0b0100,
            0b0100, 0b0111, 0b0111, 0b0110, 0b0110,
        ])
    };
    const NEGATION_MASK: __m512i = unsafe {
        core::mem::transmute([0i32, -2, -2, 0, 0, -2, -2, 0, 0, -2, -2, 0, 0, -2, -2, 0])
    };
    let t = _mm512_permutexvar_epi32(INDICES_FROM_T1, t);
    let t = _mm512_xor_epi32(t, NEGATION_MASK);
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/380)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`src/core/backend/avx512/fft.rs` line 274 at r4](https://reviewable.io/reviews/starkware-libs/stwo/380#-Ns3G6FOBGEnhER8bOG5:-Ns3w-865VG0CdtsVzDU:b-ts0yes) ([raw file](https://github.com/starkware-libs/stwo/blob/becaa490bcab5f35b78d1177af7030261e9df2ad/src/core/backend/avx512/fft.rs#L274)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

what is this?
</blockquote></details>

// See the comments in its body for more info.

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/380)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`src/core/backend/avx512/fft.rs` line 328 at r5](https://reviewable.io/reviews/starkware-libs/stwo/380#-Ns7osvS2OnrT8N5eC0F:-Ns7osvS2OnrT8N5eC0G:b-fal8su) ([raw file](https://github.com/starkware-libs/stwo/blob/5615ce4e859f0ee0613be211ffb8e0d374189084/src/core/backend/avx512/fft.rs#L328)):*
> ```XML
>     };
>     let t = _mm512_permutexvar_epi32(INDICES_FROM_T1, t);
>     let t = _mm512_xor_epi32(t, NEGATION_MASK);
> ```

can you move this to a function?

compute_layer0_twiddles or something like that?



_Code quote:_
```XML
    const INDICES_FROM_T1: __m512i = unsafe {
        core::mem::transmute([
            0b0001, 0b0001, 0b0000, 0b0000, 0b0011, 0b0011, 0b0010, 0b0010, 0b0101, 0b0101, 0b0100,
            0b0100, 0b0111, 0b0111, 0b0110, 0b0110,
        ])
    };
    const NEGATION_MASK: __m512i = unsafe {
        core::mem::transmute([0i32, -2, -2, 0, 0, -2, -2, 0, 0, -2, -2, 0, 0, -2, -2, 0])
    };
    let t = _mm512_permutexvar_epi32(INDICES_FROM_T1, t);
    let t = _mm512_xor_epi32(t, NEGATION_MASK);
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/380)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`src/core/backend/avx512/fft.rs` line 328 at r5](https://reviewable.io/reviews/starkware-libs/stwo/380#-Ns7osvS2OnrT8N5eC0F:-Ns7uU3g00JUo0FQ9qNN:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/5615ce4e859f0ee0613be211ffb8e0d374189084/src/core/backend/avx512/fft.rs#L328)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

can you move this to a function?

compute_layer0_twiddles or something like that?
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/380)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
