### PR TITLE
Add blake2s implementation for SIMD backend

### PR DESCRIPTION
**Pull request by andrewmilson**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/601)

### CODE REVIEW

**Comment by andrewmilson** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/601?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#601** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/601?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#594** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/594?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#595](https://github.com/starkware-libs/stwo/pull/595) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/595?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#600** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/600?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#593** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/593?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#592** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/592?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#591** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/591?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @andrewmilson and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/601)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`crates/prover/src/core/backend/simd/blake2s.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/stwo/601#-Nx9Gutg2rX0CUTq2k3-:-Nx9Guth5aUShJzTqIEQ:b-pow6y8) ([raw file](https://github.com/starkware-libs/stwo/blob/fa27659c1377c1f3e8b81e91ff0423429fcec26c/crates/prover/src/core/backend/simd/blake2s.rs#L1)):*
> ```XML
> //! An AVX512 implementation of the BLAKE2s compression function.
> ```

Tried to make this file contain as close of a direct copy of backend/avx512/blake2s.rs and backend/avx512/blake2s_avx.rs. Most of the changes are just switching types i.e. __m512i replaced with u32x16

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/601)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @andrewmilson)

___
*[`crates/prover/src/core/backend/simd/blake2s.rs` line 270 at r2](https://reviewable.io/reviews/starkware-libs/stwo/601#-NxN_Shx0uUCTnE8wtLZ:-NxN_Shx0uUCTnE8wtL_:b-l6mkjh) ([raw file](https://github.com/starkware-libs/stwo/blob/4a7ffb289561904b20ecee775ecb098212bdcd9d/crates/prover/src/core/backend/simd/blake2s.rs#L270)):*
> ```XML
> /// representing 16 packed instances of a message word.
> /// # Safety
> pub unsafe fn transpose_msgs(mut data: [u32x16; 16]) -> [u32x16; 16] {
> ```

rename



_Suggestion:_
```XML
pub unsafe fn transpose_states(mut data: [u32x16; 16]) -> [u32x16; 16] {
```
___
*[`crates/prover/src/core/backend/simd/blake2s.rs` line 306 at r2](https://reviewable.io/reviews/starkware-libs/stwo/601#-NxR8369CNRG_FhPExUA:-NxR8369CNRG_FhPExUB:bws7pqb) ([raw file](https://github.com/starkware-libs/stwo/blob/4a7ffb289561904b20ecee775ecb098212bdcd9d/crates/prover/src/core/backend/simd/blake2s.rs#L306)):*
> ```XML
>     for _ in 0..3 {
>         states = [
>             LoLoInterleaveHiLo::concat_swizzle(states[0], states[4]),
> ```

Fix as we discussed.



_Code quote:_
```XML
LoLoInterleaveHiLo::concat_swizzle(states[0], states[4]),
```

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/601)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/prover/src/core/backend/simd/blake2s.rs` line 270 at r2](https://reviewable.io/reviews/starkware-libs/stwo/601#-NxN_Shx0uUCTnE8wtLZ:-NxSf_2a8qOMkWKH21st:b901lup) ([raw file](https://github.com/starkware-libs/stwo/blob/4a7ffb289561904b20ecee775ecb098212bdcd9d/crates/prover/src/core/backend/simd/blake2s.rs#L270)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

rename
</blockquote></details>

transpose_states is a different function
___
*[`crates/prover/src/core/backend/simd/blake2s.rs` line 306 at r2](https://reviewable.io/reviews/starkware-libs/stwo/601#-NxR8369CNRG_FhPExUA:-NxSfRpq5wQCFAFU_VOx:bjgleh8) ([raw file](https://github.com/starkware-libs/stwo/blob/4a7ffb289561904b20ecee775ecb098212bdcd9d/crates/prover/src/core/backend/simd/blake2s.rs#L306)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Fix as we discussed.
</blockquote></details>

Is already updated.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/601#-:-NxShFn89V7VMzlXvzi_:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7)

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/601)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @shaharsamocha7)

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/601#-:-NxwnudG02ZOo9wLJtBS:bnfp4nl)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @spapinistarkware)

**Pull request merged**
