### PR TITLE
avx poly

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/365)

### CODE REVIEW

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/365)* status: all files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`src/core/backend/avx512/circle.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/stwo/365#-Ns32K62BKS7D-Wfy3Mt:-Ns32K63-z2WZnKHCU8u:b-yww2gd) ([raw file](https://github.com/starkware-libs/stwo/blob/0a089c8d6e97229accc1755aaf22338cc74cefff/src/core/backend/avx512/circle.rs#L24)):*
> ```XML
>     }
> 
>     fn eval_at_point<E: crate::core::fields::ExtensionOf<BaseField>>(
> ```

Import instead?



_Suggestion:_
```XML
ExtensionOf<BaseField>
```
___
*[`src/core/backend/avx512/mod.rs` line 82 at r2](https://reviewable.io/reviews/starkware-libs/stwo/365#-Ns317mR5j714YhoFlzb:-Ns317mSBOsUQt4_jVRW:bnkd634) ([raw file](https://github.com/starkware-libs/stwo/blob/0a089c8d6e97229accc1755aaf22338cc74cefff/src/core/backend/avx512/mod.rs#L82)):*
> ```XML
> }
> 
> fn as_cpu_vec(values: BaseFieldVec) -> Vec<BaseField> {
> ```

Should we add a unit test for this?

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/365)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

___
*[`src/core/backend/avx512/circle.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/stwo/365#-Ns32K62BKS7D-Wfy3Mt:-Ns36CVnArZB1p0Udwke:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/0a089c8d6e97229accc1755aaf22338cc74cefff/src/core/backend/avx512/circle.rs#L24)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Import instead?
</blockquote></details>

Done.
___
*[`src/core/backend/avx512/mod.rs` line 82 at r2](https://reviewable.io/reviews/starkware-libs/stwo/365#-Ns317mR5j714YhoFlzb:-Ns37nK_Dy6L595MVCY3:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/0a089c8d6e97229accc1755aaf22338cc74cefff/src/core/backend/avx512/mod.rs#L82)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Should we add a unit test for this?
</blockquote></details>

Done.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/365)* status: all files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`src/core/backend/avx512/mod.rs` line 83 at r3](https://reviewable.io/reviews/starkware-libs/stwo/365#-Ns3DUlt6bFeU0GiJZiQ:-Ns3DUlt6bFeU0GiJZiR:b4kfylo) ([raw file](https://github.com/starkware-libs/stwo/blob/e88cbff2f622873a7fda95d5b2000f7d5c45c8a0/src/core/backend/avx512/mod.rs#L83)):*
> ```XML
> 
> fn as_cpu_vec(values: BaseFieldVec) -> Vec<BaseField> {
>     let capacity = values.data.capacity() * 16;
> ```

Is this `K_ELEMENTS`? or `K_BLOCK_SIZE`?  If they are the same you can keep only one.



_Code quote:_
```XML
16
```
___
*[`src/core/backend/avx512/mod.rs` line 160 at r3](https://reviewable.io/reviews/starkware-libs/stwo/365#-Ns3EQ6JB-BPbaYFvFkI:-Ns3EQ6JB-BPbaYFvFkJ:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/e88cbff2f622873a7fda95d5b2000f7d5c45c8a0/src/core/backend/avx512/mod.rs#L160)):*
> ```XML
>         let col = Col::<B, BaseField>::from_iter((0..100).map(BaseField::from));
>         let vec = as_cpu_vec(col);
>         assert_eq!(vec, (0..100).map(BaseField::from).collect::<Vec<_>>());
> ```





_Suggestion:_
```XML
        let original_vec = (1000..1100).map(BaseField::from).collect::<Vec<_>>();
        let col = Col::<B, BaseField>::from_iter(original_vec.clone());
        let vec = as_cpu_vec(col);
        assert_eq!(vec, original_vec);
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/365)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

___
*[`src/core/backend/avx512/mod.rs` line 83 at r3](https://reviewable.io/reviews/starkware-libs/stwo/365#-Ns3DUlt6bFeU0GiJZiQ:-Ns3GXoW-iieLkBsX2Xk:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/e88cbff2f622873a7fda95d5b2000f7d5c45c8a0/src/core/backend/avx512/mod.rs#L83)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Is this `K_ELEMENTS`? or `K_BLOCK_SIZE`?  If they are the same you can keep only one.
</blockquote></details>

Done.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/365#-:-Ns3IHPYAkwWVdkdxark:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shaharsamocha7)

___
*[`src/core/backend/avx512/mod.rs` line 83 at r3](https://reviewable.io/reviews/starkware-libs/stwo/365#-Ns3DUlt6bFeU0GiJZiQ:-Ns3I7bg2H1x-RRJeC1p:b-412umg) ([raw file](https://github.com/starkware-libs/stwo/blob/e88cbff2f622873a7fda95d5b2000f7d5c45c8a0/src/core/backend/avx512/mod.rs#L83)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Is `K_BLOCK_SIZE` the same? (non-blocking)

**Pull request merged**
