### PR TITLE
Remove FRI PolyOps dependency

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/399)

### CODE REVIEW

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/399)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`src/core/air/evaluation.rs` line 155 at r2](https://reviewable.io/reviews/starkware-libs/stwo/399#-NshG1j96ET0R9WFhmlg:-NshG1jA-Ab1aDrXb6GB:bz6die7) ([raw file](https://github.com/starkware-libs/stwo/blob/710a5389eff8e4577ec061f8fee68e61fbbe2514/src/core/air/evaluation.rs#L155)):*
> ```XML
> }
> 
> // TODO(spapini): Remove dependency on PolyOps<SecureField>.
> ```

I'm confused, you removed the dependency on `PolyOps<SecureField>` in the file below, no?
Does it mean we can also delete the extend function from the avx code?



_Code quote:_
```XML
// TODO(spapini): Remove dependency on PolyOps<SecureField>.
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/399)* status: all files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`src/core/air/evaluation.rs` line 155 at r2](https://reviewable.io/reviews/starkware-libs/stwo/399#-NshG1j96ET0R9WFhmlg:-NslIeBa5VNP2AWxH2iw:bqotl3p) ([raw file](https://github.com/starkware-libs/stwo/blob/710a5389eff8e4577ec061f8fee68e61fbbe2514/src/core/air/evaluation.rs#L155)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I'm confused, you removed the dependency on `PolyOps<SecureField>` in the file below, no?
Does it mean we can also delete the extend function from the avx code?
</blockquote></details>

Yes, this is an old comment. This PR is so old that we managed to remove this dependency a week ago.
We still need the extend unfortunately...

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/399)* status: all files reviewed, 4 unresolved discussions (waiting on @shaharsamocha7)

___
*[`src/core/fri.rs` line 148 at r4](https://reviewable.io/reviews/starkware-libs/stwo/399#-NsljdLd9qxeF17L9Ey5:-Nsltqkv-rB7jA3ybd54:b-pqs6oo) ([raw file](https://github.com/starkware-libs/stwo/blob/1996d4599453dcb5d9e36326c8b67d5623e37380/src/core/fri.rs#L148)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

which other function are going to be there?
</blockquote></details>

It has bit_reverse and batch_inverse and the Col type. We will need some place to have the quotient function as well

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/399)* status: 23 of 27 files reviewed, 4 unresolved discussions (waiting on @shaharsamocha7)

___
*[`src/core/utils.rs` line 42 at r4](https://reviewable.io/reviews/starkware-libs/stwo/399#-NsldNYU55KZeO9ccf22:-NsluEZp6q33cSBqISRy:b-cyymax) ([raw file](https://github.com/starkware-libs/stwo/blob/1996d4599453dcb5d9e36326c8b67d5623e37380/src/core/utils.rs#L42)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

WDYT?

Also, should this function check that those secure field are really elements from the base field?
</blockquote></details>

Copilot suggested secure_eval_to_base_eval
___
*[`src/core/utils.rs` line 45 at r4](https://reviewable.io/reviews/starkware-libs/stwo/399#-NsldjJK022zW9wdNGUj:-Nslu6kF2HhBJa-QGnZH:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/1996d4599453dcb5d9e36326c8b67d5623e37380/src/core/utils.rs#L45)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I think that this should be a function of SecureField
We already have there `to_m31_array`.
</blockquote></details>

Done.
___
*[`src/core/backend/mod.rs` line 19 at r4](https://reviewable.io/reviews/starkware-libs/stwo/399#-Nslf-oj6aDHk_WQV0P4:-NsluT1NCkNLMvhqqVZs:brw9o32) ([raw file](https://github.com/starkware-libs/stwo/blob/cd82aadd2b1c4e9db4a33c62eb0e0f50ec4d66a4/src/core/backend/mod.rs#L19)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Where should we comment that PolyOps assumes that the poly is over the BaseField?
</blockquote></details>

Added doc to PolyOps

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/399)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`src/core/fri.rs` line 148 at r4](https://reviewable.io/reviews/starkware-libs/stwo/399#-NsljdLd9qxeF17L9Ey5:-Nslx5mK0cpjKN7rNmZt:b-pcr704) ([raw file](https://github.com/starkware-libs/stwo/blob/1996d4599453dcb5d9e36326c8b67d5623e37380/src/core/fri.rs#L148)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

It has bit_reverse and batch_inverse and the Col type. We will need some place to have the quotient function as well
</blockquote></details>

The quotient is going to replace the batch_inverse?
The bit_reverse is a bit unrelated to FieldOps IMO.
___
*[`src/core/utils.rs` line 45 at r4](https://reviewable.io/reviews/starkware-libs/stwo/399#-NsldjJK022zW9wdNGUj:-Nsm6Ah-2OdVhlQt2MnZ:b4w99bq) ([raw file](https://github.com/starkware-libs/stwo/blob/1996d4599453dcb5d9e36326c8b67d5623e37380/src/core/utils.rs#L45)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It still doesn't check that the other m31 values are 0.
Do we want that?

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/399)* status: all files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7)

___
*[`src/core/utils.rs` line 45 at r4](https://reviewable.io/reviews/starkware-libs/stwo/399#-NsldjJK022zW9wdNGUj:-NsmL4eO0GftsoNkujEQ:b7n3z67) ([raw file](https://github.com/starkware-libs/stwo/blob/1996d4599453dcb5d9e36326c8b67d5623e37380/src/core/utils.rs#L45)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

It still doesn't check that the other m31 values are 0.
Do we want that?
</blockquote></details>

It's enough for the tests

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/399)* status: all files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7)

___
*[`src/core/fri.rs` line 148 at r4](https://reviewable.io/reviews/starkware-libs/stwo/399#-NsljdLd9qxeF17L9Ey5:-NsmL9Mo0vDBs40yKZEY:b-7sgjyg) ([raw file](https://github.com/starkware-libs/stwo/blob/1996d4599453dcb5d9e36326c8b67d5623e37380/src/core/fri.rs#L148)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

The quotient is going to replace the batch_inverse?
The bit_reverse is a bit unrelated to FieldOps IMO.
</blockquote></details>

No, we still need inverse for twiddles, and perhaps generic trace gen code (e.g. in pedersen)
Both Coil and bit reverse are unrelated to Field, I agree

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/399)* status: all files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`src/core/fri.rs` line 148 at r4](https://reviewable.io/reviews/starkware-libs/stwo/399#-NsljdLd9qxeF17L9Ey5:-NsmmXCKA4S1XNhu5IV-:b-kij80i) ([raw file](https://github.com/starkware-libs/stwo/blob/1996d4599453dcb5d9e36326c8b67d5623e37380/src/core/fri.rs#L148)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

ColumnOps?
</blockquote></details>

Sounds good. Creating a PR for it.
___
*[`src/core/utils.rs` line 45 at r4](https://reviewable.io/reviews/starkware-libs/stwo/399#-NsldjJK022zW9wdNGUj:-NsmmWbHCvhovWcJnnt5:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/1996d4599453dcb5d9e36326c8b67d5623e37380/src/core/utils.rs#L45)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

This function is only for tests? I'm a bit confused.
If so, can you mark that as such?
</blockquote></details>

Done.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/399)* status: 26 of 27 files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`src/core/fri.rs` line 148 at r4](https://reviewable.io/reviews/starkware-libs/stwo/399#-NsljdLd9qxeF17L9Ey5:-NsmooCu2DXYuO42fHpT:bl4j14n) ([raw file](https://github.com/starkware-libs/stwo/blob/1996d4599453dcb5d9e36326c8b67d5623e37380/src/core/fri.rs#L148)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Sounds good. Creating a PR for it.
</blockquote></details>

https://reviewable.io/reviews/starkware-libs/stwo/459

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/399#-:-Nsmr6Hd0AT3AdODPoIM:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
