### PR TITLE
Merge trace writer and trace generator.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/672)

### CODE REVIEW

**Comment by alonh5** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/672?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#672** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/672?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#671** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/671?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#669** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/669?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#667** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/667?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#664** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/664?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#662** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/662?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#646** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/646?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#644** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/644?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#654](https://github.com/starkware-libs/stwo/pull/654) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/654?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#642** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/642?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#639** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/639?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#638** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/638?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#637** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/637?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#636** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/636?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#651** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/651?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 9 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/672)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @alonh5)

___
*[`crates/prover/src/examples/fibonacci/component.rs` line 142 at r1](https://reviewable.io/reviews/starkware-libs/stwo/672#-O04X2gg-dxsvkn3WKUY:-O04X2gg-dxsvkn3WKUZ:b-weq9ok) ([raw file](https://github.com/starkware-libs/stwo/blob/ad0dfc32db9a2264d870c3b4dd1dddb51c545162/crates/prover/src/examples/fibonacci/component.rs#L142)):*
> ```XML
>         _registry: &mut ComponentRegistry,
>     ) -> ColumnVec<CircleEvaluation<CpuBackend, BaseField, BitReversedOrder>> {
>         vec![]
> ```

Do we want to implement write_trace here?
Could be done in another pr

What would it require to use this write_trace function instead of the current implementation?



_Code quote:_
```XML
vec![]
```
___
*[`crates/prover/src/examples/wide_fibonacci/component.rs` line 266 at r1](https://reviewable.io/reviews/starkware-libs/stwo/672#-O04X8Zg213ojB-s2GNU:-O04X8Zg213ojB-s2GNV:bb7od0r) ([raw file](https://github.com/starkware-libs/stwo/blob/ad0dfc32db9a2264d870c3b4dd1dddb51c545162/crates/prover/src/examples/wide_fibonacci/component.rs#L266)):*
> ```XML
>         _registry: &mut ComponentRegistry,
>     ) -> ColumnVec<CircleEvaluation<CpuBackend, BaseField, BitReversedOrder>> {
>         vec![]
> ```

same



_Code quote:_
```XML
        vec![]
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/672)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/prover/src/examples/fibonacci/component.rs` line 142 at r1](https://reviewable.io/reviews/starkware-libs/stwo/672#-O04X2gg-dxsvkn3WKUY:-O08A-KWEHqUu34BtSNq:bh690l3) ([raw file](https://github.com/starkware-libs/stwo/blob/ad0dfc32db9a2264d870c3b4dd1dddb51c545162/crates/prover/src/examples/fibonacci/component.rs#L142)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Do we want to implement write_trace here?
Could be done in another pr

What would it require to use this write_trace function instead of the current implementation?
</blockquote></details>

Yes I'll start working on it in a new PR.
___
*[`crates/prover/src/examples/wide_fibonacci/component.rs` line 266 at r1](https://reviewable.io/reviews/starkware-libs/stwo/672#-O04X8Zg213ojB-s2GNU:-O08A5pX5ExAYZE_b2ci:bb7od0r) ([raw file](https://github.com/starkware-libs/stwo/blob/ad0dfc32db9a2264d870c3b4dd1dddb51c545162/crates/prover/src/examples/wide_fibonacci/component.rs#L266)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

same
</blockquote></details>

same

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/672)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @alonh5)

___
*[`crates/prover/src/trace_generation/mod.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/stwo/672#-O08RkdM3ULKxGwUrMec:-O08RkdM3ULKxGwUrMed:bhyypor) ([raw file](https://github.com/starkware-libs/stwo/blob/ad0dfc32db9a2264d870c3b4dd1dddb51c545162/crates/prover/src/trace_generation/mod.rs#L19)):*
> ```XML
> // A trait to generate a a trace.
> // Generates the trace given a list of inputs collects inputs for subcomponents.
> pub trait TraceGenerator<B: Backend> {
> ```

Do you think we should do this renaming? because I see that we also have `AirTraceGenertor`.

If so, can you do it in another pr?



_Suggestion:_
```XML
pub trait ComponentTraceGenerator<B: Backend> {
```
___
*[`crates/prover/src/trace_generation/mod.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/stwo/672#-O08R6Lq89qGGLfRcEdb:-O08R6Lq89qGGLfRcEdc:b-fmwy53) ([raw file](https://github.com/starkware-libs/stwo/blob/ad0dfc32db9a2264d870c3b4dd1dddb51c545162/crates/prover/src/trace_generation/mod.rs#L45)):*
> ```XML
> pub trait AirTraceVerifier {
>     fn interaction_elements(&self, channel: &mut Blake2sChannel) -> InteractionElements;
> }
> ```

I think that this trait should be in the core library (it is used also by the verifier)



_Code quote:_
```XML
pub trait AirTraceVerifier {
    fn interaction_elements(&self, channel: &mut Blake2sChannel) -> InteractionElements;
}
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/672)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/prover/src/trace_generation/mod.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/stwo/672#-O08RkdM3ULKxGwUrMec:-O08fBzVCZ4HkPEZCR08:bpfik98) ([raw file](https://github.com/starkware-libs/stwo/blob/ad0dfc32db9a2264d870c3b4dd1dddb51c545162/crates/prover/src/trace_generation/mod.rs#L19)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Do you think we should do this renaming? because I see that we also have `AirTraceGenertor`.

If so, can you do it in another pr?
</blockquote></details>

Done in this PR.
___
*[`crates/prover/src/trace_generation/mod.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/stwo/672#-O08R6Lq89qGGLfRcEdb:-O08fjCBCi4I7cVqjeif:b-d1meqe) ([raw file](https://github.com/starkware-libs/stwo/blob/ad0dfc32db9a2264d870c3b4dd1dddb51c545162/crates/prover/src/trace_generation/mod.rs#L45)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I think that this trait should be in the core library (it is used also by the verifier)
</blockquote></details>

Technically the verify function receives an `Air` which is also an `AirTraceVerifier`, but I think it's better to leave it close to the `AirTraceGenerator`. Do you think that's okay?

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/672)* status: 1 of 10 files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/prover/src/trace_generation/mod.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/stwo/672#-O08R6Lq89qGGLfRcEdb:-O09-_jW1OV-3G699oaJ:bp6ssvf) ([raw file](https://github.com/starkware-libs/stwo/blob/ad0dfc32db9a2264d870c3b4dd1dddb51c545162/crates/prover/src/trace_generation/mod.rs#L45)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Technically the verify function receives an `Air` which is also an `AirTraceVerifier`, but I think it's better to leave it close to the `AirTraceGenerator`. Do you think that's okay?
</blockquote></details>

Yes, but that raises another question? 
Why isn't the function interaction_elements just part of the Air trait?

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/672)* status: 1 of 10 files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`crates/prover/src/trace_generation/mod.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/stwo/672#-O08R6Lq89qGGLfRcEdb:-O091MW90K9-4tmrGx2H:bb5usua) ([raw file](https://github.com/starkware-libs/stwo/blob/ad0dfc32db9a2264d870c3b4dd1dddb51c545162/crates/prover/src/trace_generation/mod.rs#L45)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Yes, but that raises another question? 
Why isn't the function interaction_elements just part of the Air trait?
</blockquote></details>

That's because for the prover we need that function before we know all the components, in the trace generation phase. If we want it to be part of Air then AirTraceGenerator would also have to be an Air and therefore know it's components (we've talked about this before).

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 10 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/672#-:-O094qya8yqD5QlfwGhc:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

___
*[`crates/prover/src/trace_generation/mod.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/stwo/672#-O08R6Lq89qGGLfRcEdb:-O094i9T475H7CUCmJfV:b-7jzv7t) ([raw file](https://github.com/starkware-libs/stwo/blob/ad0dfc32db9a2264d870c3b4dd1dddb51c545162/crates/prover/src/trace_generation/mod.rs#L45)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

That's because for the prover we need that function before we know all the components, in the trace generation phase. If we want it to be part of Air then AirTraceGenerator would also have to be an Air and therefore know it's components (we've talked about this before).
</blockquote></details>

right

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/672)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/prover/src/trace_generation/mod.rs` line 37 at r3](https://reviewable.io/reviews/starkware-libs/stwo/672#-O0sV-ajDsm2wsQVc-An:-O0sV-ajDsm2wsQVc-Ao:b7d9qeu) ([raw file](https://github.com/starkware-libs/stwo/blob/93dd654c7a8b7ccabd9f7b2fd91c11938e997000/crates/prover/src/trace_generation/mod.rs#L37)):*
> ```XML
>     ) -> ColumnVec<CircleEvaluation<B, BaseField, BitReversedOrder>>;
> 
>     fn write_interaction_trace(
> ```

Add documentation



_Code quote:_
```XML
fn write_interaction_trace(
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/672)* status: 3 of 11 files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`crates/prover/src/trace_generation/mod.rs` line 37 at r3](https://reviewable.io/reviews/starkware-libs/stwo/672#-O0sV-ajDsm2wsQVc-An:-O1H0WCvBFoUddBayeCy:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/93dd654c7a8b7ccabd9f7b2fd91c11938e997000/crates/prover/src/trace_generation/mod.rs#L37)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Add documentation
</blockquote></details>

Done.

**Review by shaharsamocha7 — APPROVED** [review]
> Reviewed 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/672)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Comment by alonh5** [comment]
### Merge activity

* **Jul 8, 7:18 AM EDT**: @alonh5 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/672).

**Pull request merged**
