### PR TITLE
Add bit_reverse for SIMD backend

### PR DESCRIPTION
**Pull request by andrewmilson**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/600)

### CODE REVIEW

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/600)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`crates/prover/src/core/backend/simd/bit_reverse.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/stwo/600#-Nx9GGsH1LAu_rNCSpg7:-Nx9GGsH1LAu_rNCSpg8:bvxlot1) ([raw file](https://github.com/starkware-libs/stwo/blob/83d24e0e6300ed9c6c09f62226dd16f29e1be75f/crates/prover/src/core/backend/simd/bit_reverse.rs#L1)):*
> ```XML
> use std::simd::{u32x16, Swizzle};
> ```

Tried to make this file as close of a direct copy of backend/avx512/bit_reverse.rs. Most of the changes are just switching types i.e. __m512i replaced with u32x16

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/600)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @andrewmilson)

___
*[`crates/prover/src/core/backend/simd/bit_reverse.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/stwo/600#-Nx9GGsH1LAu_rNCSpg7:-NxHu90qCepZcgt2mUNs:blza2lx) ([raw file](https://github.com/starkware-libs/stwo/blob/83d24e0e6300ed9c6c09f62226dd16f29e1be75f/crates/prover/src/core/backend/simd/bit_reverse.rs#L1)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Tried to make this file as close of a direct copy of backend/avx512/bit_reverse.rs. Most of the changes are just switching types i.e. __m512i replaced with u32x16
</blockquote></details>

Ty, those comments are helpful
___
*[`crates/prover/src/core/backend/simd/bit_reverse.rs` line 94 at r2](https://reviewable.io/reviews/starkware-libs/stwo/600#-NxHtw0A0FfFcd1KDnEL:-NxHtw0A0FfFcd1KDnEM:ba3dfna) ([raw file](https://github.com/starkware-libs/stwo/blob/545100b0a049235d30151fa4d342f6620053a734/crates/prover/src/core/backend/simd/bit_reverse.rs#L94)):*
> ```XML
>             0b11100, 0b01101, 0b11101, 0b01110, 0b11110, 0b01111, 0b11111,
>         ])
>     };
> ```

Remove?



_Code quote:_
```XML
    // L is an input to _mm512_permutex2var_epi32, and it is used to
    // interleave the first half of a with the first half of b.
    const _L: u32x16 = unsafe {
        core::mem::transmute([
            0b00000, 0b10000, 0b00001, 0b10001, 0b00010, 0b10010, 0b00011, 0b10011, 0b00100,
            0b10100, 0b00101, 0b10101, 0b00110, 0b10110, 0b00111, 0b10111,
        ])
    };
    // H is an input to _mm512_permutex2var_epi32, and it is used to interleave the second half
    // interleave the second half of a with the second half of b.
    const _H: u32x16 = unsafe {
        core::mem::transmute([
            0b01000, 0b11000, 0b01001, 0b11001, 0b01010, 0b11010, 0b01011, 0b11011, 0b01100,
            0b11100, 0b01101, 0b11101, 0b01110, 0b11110, 0b01111, 0b11111,
        ])
    };
```

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/600)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`crates/prover/src/core/backend/simd/bit_reverse.rs` line 94 at r2](https://reviewable.io/reviews/starkware-libs/stwo/600#-NxHtw0A0FfFcd1KDnEL:-NxI6k8H7Pv1UeFB0ZTu:b-i3ya5m) ([raw file](https://github.com/starkware-libs/stwo/blob/545100b0a049235d30151fa4d342f6620053a734/crates/prover/src/core/backend/simd/bit_reverse.rs#L94)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Remove?
</blockquote></details>

They get removed in the next PR https://reviewable.io/reviews/starkware-libs/stwo/594

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/600#-:-NxM9hsP5HtLhoSI8xaF:bnfp4nl)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

**Review by shaharsamocha7 — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/600)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @andrewmilson)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/600#-:-NxSgFfS5CLHa5kFcBwD:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @andrewmilson)

**Pull request merged**
