### PR TITLE
merkle intermediate layers

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/548)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
* **#531** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/531?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#530** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/530?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#529** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/529?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#528** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/528?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#527** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/527?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#526** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/526?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#548** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/548?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/548)* status: 2 of 4 files reviewed, 10 unresolved discussions (waiting on @spapinistarkware)

___
*[`src/commitment_scheme/blake2_merkle.rs` line 46 at r2](https://reviewable.io/reviews/starkware-libs/stwo/548#-NuSimY31QRVd5xtKC8c:-NuSimY31QRVd5xtKC8d:b-ahkrcl) ([raw file](https://github.com/starkware-libs/stwo/blob/f49ba4a63ed582fab78a6ec22e8e9e9b70acdbab/src/commitment_scheme/blake2_merkle.rs#L46)):*
> ```XML
>         // Write as hex.
>         for &byte in self.0.iter() {
>             write!(f, "{:02x}", byte)?;
> ```

Print a new line at the end?



_Code quote:_
```XML
write!(f, "{:02x}", byte)?;
```
___
*[`src/commitment_scheme/prover.rs` line 23 at r2](https://reviewable.io/reviews/starkware-libs/stwo/548#-NuSnEgl-FDPW0jWsXtw:-NuSnEgm8oRMzwUgZvtD:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/f49ba4a63ed582fab78a6ec22e8e9e9b70acdbab/src/commitment_scheme/prover.rs#L23)):*
> ```XML
> impl<B: MerkleOps<H>, H: MerkleHasher> MerkleProver<B, H> {
>     /// Commits to columns.
>     /// Columns must be of power of 2 sizes and sorted in descending order.
> ```





_Suggestion:_
```XML
/// Columns must be of power of 2 sizes.
```
___
*[`src/commitment_scheme/prover.rs` line 70 at r2](https://reviewable.io/reviews/starkware-libs/stwo/548#-NuSncZ80-Ad3rIK___k:-NuSncZ80-Ad3rIK___l:b4qc66i) ([raw file](https://github.com/starkware-libs/stwo/blob/f49ba4a63ed582fab78a6ec22e8e9e9b70acdbab/src/commitment_scheme/prover.rs#L70)):*
> ```XML
>     /// # Returns
>     ///
>     /// A `Decommitment` struct containing the witness.
> ```

It also returns the decommited values (order per column)



_Code quote:_
```XML
 /// A `Decommitment` struct containing the witness.
```
___
*[`src/commitment_scheme/prover.rs` line 92 at r2](https://reviewable.io/reviews/starkware-libs/stwo/548#-NuSnxYE4yC9UiNFCgCT:-NuSnxYE4yC9UiNFCgCU:b-exf04b) ([raw file](https://github.com/starkware-libs/stwo/blob/f49ba4a63ed582fab78a6ec22e8e9e9b70acdbab/src/commitment_scheme/prover.rs#L92)):*
> ```XML
>                 "Queries are not sorted."
>             );
>         }
> ```

move up



_Code quote:_
```XML
        // Check that queries are sorted and deduped.
        for queries in queries_per_log_size.values() {
            assert!(
                queries.windows(2).all(|w| w[0] < w[1]),
                "Queries are not sorted."
            );
        }
```
___
*[`src/commitment_scheme/prover.rs` line 120 at r2](https://reviewable.io/reviews/starkware-libs/stwo/548#-NuSoqcIDkC6DNwX7H2q:-NuSoqcIDkC6DNwX7H2r:bninkr3) ([raw file](https://github.com/starkware-libs/stwo/blob/f49ba4a63ed582fab78a6ec22e8e9e9b70acdbab/src/commitment_scheme/prover.rs#L120)):*
> ```XML
>                 .peekable();
> 
>             // Merge previous layer queries and column queries.
> ```

Document
Maybe seperate function



_Code quote:_
```XML
// Merge previous layer queries and column queries.
```
___
*[`src/commitment_scheme/prover.rs` line 185 at r2](https://reviewable.io/reviews/starkware-libs/stwo/548#-NuSqZxC7iil4kJ047ti:-NuSqZxD6oOBNbei_H4_:bux2vxo) ([raw file](https://github.com/starkware-libs/stwo/blob/f49ba4a63ed582fab78a6ec22e8e9e9b70acdbab/src/commitment_scheme/prover.rs#L185)):*
> ```XML
>                 a.iter_mut().map(|x| x.next().unwrap()).collect_vec()
>             })
>             .collect_vec();
> ```

separate to another function
and document



_Code quote:_
```XML
        // Rearrange returned queried values according to input, and not by layer.
        let mut queried_values_by_layer = queried_values_by_layer
            .into_iter()
            .map(|layer_results| {
                layer_results
                    .into_iter()
                    .map(|x| x.into_iter())
                    .collect_vec()
            })
            .collect_vec();

        let queried_values = columns
            .iter()
            .map(|column| {
                let a = queried_values_by_layer
                    .get_mut(column.len().ilog2() as usize)
                    .unwrap();
                a.iter_mut().map(|x| x.next().unwrap()).collect_vec()
            })
            .collect_vec();
```
___
*[`src/commitment_scheme/prover.rs` line 198 at r2](https://reviewable.io/reviews/starkware-libs/stwo/548#-NuSrFnJ3aCHki4JfDHt:-NuSrFnJ3aCHki4JfDHu:b-q0cqjp) ([raw file](https://github.com/starkware-libs/stwo/blob/f49ba4a63ed582fab78a6ec22e8e9e9b70acdbab/src/commitment_scheme/prover.rs#L198)):*
> ```XML
> pub struct MerkleDecommitment<H: MerkleHasher> {
>     pub hash_witness: Vec<H::Hash>,
>     pub column_witness: Vec<BaseField>,
> ```

rename or document



_Code quote:_
```XML
pub column_witness: Vec<BaseField>,
```
___
*[`src/commitment_scheme/verifier.rs` line 76 at r2](https://reviewable.io/reviews/starkware-libs/stwo/548#-NuSs8ZJ5agkejI7RQAc:-NuSs8ZJ5agkejI7RQAd:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/f49ba4a63ed582fab78a6ec22e8e9e9b70acdbab/src/commitment_scheme/verifier.rs#L76)):*
> ```XML
>                 .peek_take_while(|(log_size, _)| *log_size == layer_log_size)
>                 .collect_vec();
>             let n_cols = layer_queried_values.len();
> ```





_Suggestion:_
```XML
n_columns_in_layer
```
___
*[`src/commitment_scheme/verifier.rs` line 110 at r2](https://reviewable.io/reviews/starkware-libs/stwo/548#-NuSszFq7lcsyCGNmAh8:-NuSszFr3mCheyF8WzMh:b45h) ([raw file](https://github.com/starkware-libs/stwo/blob/f49ba4a63ed582fab78a6ec22e8e9e9b70acdbab/src/commitment_scheme/verifier.rs#L110)):*
> ```XML
>                     .peek_take_while(|q| q / 2 == node_index)
>                     .for_each(drop);
>                 // TODO: Handle first layer.
> ```


___
*[`src/core/utils.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/stwo/548#-NuSUyTe-d3419I3xH1g:-NuSUyTe-d3419I3xH1h:b3xynol) ([raw file](https://github.com/starkware-libs/stwo/blob/f49ba4a63ed582fab78a6ec22e8e9e9b70acdbab/src/core/utils.rs#L14)):*
> ```XML
> impl<'a, T: 'a, I: Iterator<Item = &'a mut T>> IteratorMutExt<'a, T> for I {}
> 
> // peek_take_while.
> ```

Remove and document 



_Code quote:_
```XML
// peek_take_while.
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/548)* status: 2 of 4 files reviewed, 9 unresolved discussions (waiting on @shaharsamocha7)

___
*[`src/commitment_scheme/blake2_merkle.rs` line 46 at r2](https://reviewable.io/reviews/starkware-libs/stwo/548#-NuSimY31QRVd5xtKC8c:-NuSy5-5EO0sw85KSve_:b-haxwn3) ([raw file](https://github.com/starkware-libs/stwo/blob/f49ba4a63ed582fab78a6ec22e8e9e9b70acdbab/src/commitment_scheme/blake2_merkle.rs#L46)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Print a new line at the end?
</blockquote></details>

It's not my job to add newlines. To print a debug with new lines, you shoudl use a pretty print - println!("{x:#?}")
___
*[`src/commitment_scheme/prover.rs` line 23 at r2](https://reviewable.io/reviews/starkware-libs/stwo/548#-NuSnEgl-FDPW0jWsXtw:-NuSyRJj7RUAHxsyEXf5:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/f49ba4a63ed582fab78a6ec22e8e9e9b70acdbab/src/commitment_scheme/prover.rs#L23)):*
> ```XML
> impl<B: MerkleOps<H>, H: MerkleHasher> MerkleProver<B, H> {
>     /// Commits to columns.
>     /// Columns must be of power of 2 sizes and sorted in descending order.
> ```

Done.
___
*[`src/commitment_scheme/prover.rs` line 70 at r2](https://reviewable.io/reviews/starkware-libs/stwo/548#-NuSncZ80-Ad3rIK___k:-NuSyhOV-NQ0oNoRGFzK:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/f49ba4a63ed582fab78a6ec22e8e9e9b70acdbab/src/commitment_scheme/prover.rs#L70)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

It also returns the decommited values (order per column)
</blockquote></details>

Done.
___
*[`src/commitment_scheme/prover.rs` line 92 at r2](https://reviewable.io/reviews/starkware-libs/stwo/548#-NuSnxYE4yC9UiNFCgCT:-NuSykZW9LAUjqEU19Qs:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/f49ba4a63ed582fab78a6ec22e8e9e9b70acdbab/src/commitment_scheme/prover.rs#L92)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

move up
</blockquote></details>

Done.
___
*[`src/commitment_scheme/prover.rs` line 120 at r2](https://reviewable.io/reviews/starkware-libs/stwo/548#-NuSoqcIDkC6DNwX7H2q:-NuTDw_f07Lj8gOlyBLt:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/f49ba4a63ed582fab78a6ec22e8e9e9b70acdbab/src/commitment_scheme/prover.rs#L120)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Document
Maybe seperate function
</blockquote></details>

Done.
___
*[`src/commitment_scheme/prover.rs` line 185 at r2](https://reviewable.io/reviews/starkware-libs/stwo/548#-NuSqZxC7iil4kJ047ti:-NuTQvX-DH-F14Yhggj2:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/f49ba4a63ed582fab78a6ec22e8e9e9b70acdbab/src/commitment_scheme/prover.rs#L185)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

separate to another function
and document
</blockquote></details>

Done.
___
*[`src/commitment_scheme/prover.rs` line 198 at r2](https://reviewable.io/reviews/starkware-libs/stwo/548#-NuSrFnJ3aCHki4JfDHt:-NuTRZd89tJ9ynylesNf:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/f49ba4a63ed582fab78a6ec22e8e9e9b70acdbab/src/commitment_scheme/prover.rs#L198)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

rename or document
</blockquote></details>

Done.
___
*[`src/commitment_scheme/verifier.rs` line 76 at r2](https://reviewable.io/reviews/starkware-libs/stwo/548#-NuSs8ZJ5agkejI7RQAc:-NuTRc5ND89grnFA8lGL:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/f49ba4a63ed582fab78a6ec22e8e9e9b70acdbab/src/commitment_scheme/verifier.rs#L76)):*
> ```XML
>                 .peek_take_while(|(log_size, _)| *log_size == layer_log_size)
>                 .collect_vec();
>             let n_cols = layer_queried_values.len();
> ```

Done.
___
*[`src/commitment_scheme/verifier.rs` line 110 at r2](https://reviewable.io/reviews/starkware-libs/stwo/548#-NuSszFq7lcsyCGNmAh8:-NuTRfjD3Hml8pwO4CYR:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/f49ba4a63ed582fab78a6ec22e8e9e9b70acdbab/src/commitment_scheme/verifier.rs#L110)):*
> ```XML
>                     .peek_take_while(|q| q / 2 == node_index)
>                     .for_each(drop);
>                 // TODO: Handle first layer.
> ```

Done.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/548#-:-NuTUvb-7SmGeg5OCfbR:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`src/commitment_scheme/utils.rs` line 19 at r3](https://reviewable.io/reviews/starkware-libs/stwo/548#-NuTUIX91WOSm1UVmSv2:-NuTUIX91WOSm1UVmSv3:b-k4h32b) ([raw file](https://github.com/starkware-libs/stwo/blob/0f5f4e3dd223e4eca6c860014420619732dc6785/src/commitment_scheme/utils.rs#L19)):*
> ```XML
> }
> 
> pub fn peek_merged_queries(
> ```

I think that the peek_merged_queries is an impl detail.

Can you document that this gives you the next query in the layer?



_Suggestion:_
```XML
get_next_query
```
___
*[`src/commitment_scheme/utils.rs` line 31 at r3](https://reviewable.io/reviews/starkware-libs/stwo/548#-NuTUEJc6D-QkiLTyT9X:-NuTUEJc6D-QkiLTyT9Y:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/0f5f4e3dd223e4eca6c860014420619732dc6785/src/commitment_scheme/utils.rs#L31)):*
> ```XML
> }
> 
> pub fn opt_flatten_peekable<'a, I: IntoIterator<Item = &'a usize>>(
> ```





_Suggestion:_
```XML
pub fn option_flatten_peekable
```

**Review by shaharsamocha7 — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/548)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Comment by spapinistarkware** [comment]
### Merge activity

* **Apr 2, 7:18 AM EDT**: @spapinistarkware merged this pull request with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/548).

**Pull request merged**
