### PR TITLE
Use SecureField in interaction.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/642)

### CODE REVIEW

**Comment by alonh5** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/642?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#642** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/642?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#639** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/639?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#638** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/638?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#637** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/637?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#636** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/636?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#634** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/634?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#633** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/633?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#631** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/631?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#582** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/582?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#589](https://github.com/starkware-libs/stwo/pull/589) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/589?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#573** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/573?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#574](https://github.com/starkware-libs/stwo/pull/574) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/574?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#572** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/572?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#562** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/562?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 11 files at r1, 1 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/642)* status: 2 of 12 files reviewed, 3 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

___
*[`crates/prover/src/core/utils.rs` line 94 at r3](https://reviewable.io/reviews/starkware-libs/stwo/642#-O-pqxNhCn24kpFRimJ_:-O-pqxNhCn24kpFRimJa:bwhauqh) ([raw file](https://github.com/starkware-libs/stwo/blob/b20b7cc2fe7d099c27fe1d33813b19ed02ff367f/crates/prover/src/core/utils.rs#L94)):*
> ```XML
> /// Securely combines the given values using the given random alpha and z.
> /// Alpha and z should be secure field elements for soundness.
> pub fn shifted_secure_combination<F: ExtensionOf<BaseField>>(
> ```

Is this needed?
___
*[`crates/prover/src/core/air/mod.rs` line 82 at r3](https://reviewable.io/reviews/starkware-libs/stwo/642#-O-pr9Xy9_TSeoRISd3B:-O-pr9Xy9_TSeoRISd3C:beo1v5y) ([raw file](https://github.com/starkware-libs/stwo/blob/b20b7cc2fe7d099c27fe1d33813b19ed02ff367f/crates/prover/src/core/air/mod.rs#L82)):*
> ```XML
>         trace: &ColumnVec<&CircleEvaluation<B, BaseField, BitReversedOrder>>,
>         elements: &InteractionElements,
>     ) -> ColumnVec<SecureEvaluation<B>>;
> ```

I don't think it is always a bunch of secure columns in general.
It should be exactly like trace, just a bunch of basefield columns.



_Code quote:_
```XML
ColumnVec<SecureEvaluation<B>>
```
___
*[`crates/prover/src/core/prover/mod.rs` line 74 at r3](https://reviewable.io/reviews/starkware-libs/stwo/642#-O-ps4fR3EJDySv6_FOC:-O-ps4fR3EJDySv6_FOD:b-mui327) ([raw file](https://github.com/starkware-libs/stwo/blob/b20b7cc2fe7d099c27fe1d33813b19ed02ff367f/crates/prover/src/core/prover/mod.rs#L74)):*
> ```XML
> 
>     let interaction_elements = air.interaction_elements(channel);
>     let interaction_trace_polys = air.interact(&trace, &interaction_elements);
> ```

1. This is not using the precomputed twiddles.
2. Do we need to change the interface? Can't interact() reutrn teh evaluation?

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/642)* status: 2 of 12 files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/core/utils.rs` line 94 at r3](https://reviewable.io/reviews/starkware-libs/stwo/642#-O-pqxNhCn24kpFRimJ_:-O-ptFWO4HBWRD6I5SQJ:b-aq0woi) ([raw file](https://github.com/starkware-libs/stwo/blob/b20b7cc2fe7d099c27fe1d33813b19ed02ff367f/crates/prover/src/core/utils.rs#L94)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Is this needed?
</blockquote></details>

Yes the values could be M31 (in the prover constraint evaluation) and QM31 (in the verifier oods constraint evaluation).
___
*[`crates/prover/src/core/air/mod.rs` line 82 at r3](https://reviewable.io/reviews/starkware-libs/stwo/642#-O-pr9Xy9_TSeoRISd3B:-O03JbwZAiAcxIEtd_AQ:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/b20b7cc2fe7d099c27fe1d33813b19ed02ff367f/crates/prover/src/core/air/mod.rs#L82)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I don't think it is always a bunch of secure columns in general.
It should be exactly like trace, just a bunch of basefield columns.
</blockquote></details>

Done.
___
*[`crates/prover/src/core/prover/mod.rs` line 74 at r3](https://reviewable.io/reviews/starkware-libs/stwo/642#-O-ps4fR3EJDySv6_FOC:-O03Ma9b72OikBHS_IZZ:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/b20b7cc2fe7d099c27fe1d33813b19ed02ff367f/crates/prover/src/core/prover/mod.rs#L74)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

1. This is not using the precomputed twiddles.
2. Do we need to change the interface? Can't interact() reutrn teh evaluation?
</blockquote></details>

Done.

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 11 files at r2, 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/642)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

___
*[`crates/prover/src/examples/wide_fibonacci/component.rs` line 135 at r4](https://reviewable.io/reviews/starkware-libs/stwo/642#-O0IYjlT-Aoy5t99liM2:-O0IYjlT-Aoy5t99liM3:b8d19du) ([raw file](https://github.com/starkware-libs/stwo/blob/6a16e2262c7978ea85e169f72c65a1299dabbcae/crates/prover/src/examples/wide_fibonacci/component.rs#L135)):*
> ```XML
>         let trace_values = trace.iter().map(|eval| &eval.values[..]).collect_vec();
>         let (alpha, z) = (elements[ALPHA_ID], elements[Z_ID]);
>         let values = write_lookup_column(&trace_values, alpha, z);
> ```

For efficientcy, we probably want `write_lookup_column()` to already return a SecureColumn.
You can add a TODO for that.
___
*[`crates/prover/src/examples/wide_fibonacci/component.rs` line 139 at r4](https://reviewable.io/reviews/starkware-libs/stwo/642#-O0IYXzN0yF67Q3Rf_R-:-O0IYXzN0yF67Q3Rf_R0:bcy6qny) ([raw file](https://github.com/starkware-libs/stwo/blob/6a16e2262c7978ea85e169f72c65a1299dabbcae/crates/prover/src/examples/wide_fibonacci/component.rs#L139)):*
> ```XML
>         for (i, value) in values.into_iter().enumerate() {
>             secure_column.set(i, value);
>         }
> ```

I think we have a FromIterator impl for SecureColumn. so, you can use `collect()`



_Code quote:_
```XML
        for (i, value) in values.into_iter().enumerate() {
            secure_column.set(i, value);
        }
```
___
*[`crates/prover/src/examples/wide_fibonacci/constraint_eval.rs` line 95 at r4](https://reviewable.io/reviews/starkware-libs/stwo/642#-O0IZ-cC6dNgExthd9fx:-O0IZ-cC6dNgExthd9fy:b-hoo4e) ([raw file](https://github.com/starkware-libs/stwo/blob/6a16e2262c7978ea85e169f72c65a1299dabbcae/crates/prover/src/examples/wide_fibonacci/constraint_eval.rs#L95)):*
> ```XML
>             // Lookup constraints.
>             let lookup_value =
>                 SecureCirclePoly::<CpuBackend>::eval_from_partial_evals(std::array::from_fn(|j| {
> ```

Both of us know what this function does, but I fear other people will be confused by it. Maybe we can consult with the team how to name this.



_Code quote:_
```XML
eval_from_partial_evals
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/642)* status: all files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/examples/wide_fibonacci/component.rs` line 135 at r4](https://reviewable.io/reviews/starkware-libs/stwo/642#-O0IYjlT-Aoy5t99liM2:-O0Izpbk1ShODL6j4ynb:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/6a16e2262c7978ea85e169f72c65a1299dabbcae/crates/prover/src/examples/wide_fibonacci/component.rs#L135)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

For efficientcy, we probably want `write_lookup_column()` to already return a SecureColumn.
You can add a TODO for that.
</blockquote></details>

Done.
___
*[`crates/prover/src/examples/wide_fibonacci/component.rs` line 139 at r4](https://reviewable.io/reviews/starkware-libs/stwo/642#-O0IYXzN0yF67Q3Rf_R-:-O0J-djK4JzRWE-inWaQ:b-dtkdrq) ([raw file](https://github.com/starkware-libs/stwo/blob/6a16e2262c7978ea85e169f72c65a1299dabbcae/crates/prover/src/examples/wide_fibonacci/component.rs#L139)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I think we have a FromIterator impl for SecureColumn. so, you can use `collect()`
</blockquote></details>

Done, thanks.
___
*[`crates/prover/src/examples/wide_fibonacci/constraint_eval.rs` line 95 at r4](https://reviewable.io/reviews/starkware-libs/stwo/642#-O0IZ-cC6dNgExthd9fx:-O0J0bq26aTsY2XGaY-A:b-orou68) ([raw file](https://github.com/starkware-libs/stwo/blob/6a16e2262c7978ea85e169f72c65a1299dabbcae/crates/prover/src/examples/wide_fibonacci/constraint_eval.rs#L95)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Both of us know what this function does, but I fear other people will be confused by it. Maybe we can consult with the team how to name this.
</blockquote></details>

Yes, I also think we should move it to be a method of secure field and then it will be more clear when it's next to `from_m31_array()`. I added a TODO also.

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/642)* status: 11 of 13 files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/examples/wide_fibonacci/constraint_eval.rs` line 95 at r4](https://reviewable.io/reviews/starkware-libs/stwo/642#-O0IZ-cC6dNgExthd9fx:-O0JDcGp9A5BJ9RKaAPG:bxf3ikf) ([raw file](https://github.com/starkware-libs/stwo/blob/6a16e2262c7978ea85e169f72c65a1299dabbcae/crates/prover/src/examples/wide_fibonacci/constraint_eval.rs#L95)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Yes, I also think we should move it to be a method of secure field and then it will be more clear when it's next to `from_m31_array()`. I added a TODO also.
</blockquote></details>

PR 679

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/642#-:-O0OgJbAAKEKxrmMmCCK:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Comment by alonh5** [comment]
### Merge activity

* **Jun 27, 8:38 AM EDT**: @alonh5 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/642).

**Pull request merged**
