### PR TITLE
Eval framework

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/706)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/706?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#706** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/706?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#705** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/705?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#704** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/704?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#702** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/702?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#701** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/701?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by alonh5 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/706)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo/706#-O1Heszh5nvRSkp8INE3:-O1Heszh5nvRSkp8INE4:b-gcfnb6) (no related file):*
Could you please split this PR and add documentation ?

___

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/706)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @alonh5)

*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo/706#-O1Heszh5nvRSkp8INE3:-O1KyJ3-AyHouz9_YJUW:b-896fix) (no related file):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Could you please split this PR and add documentation ?
</blockquote></details>

Done.

___

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 9 files at r1, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/706)* status: all files reviewed, 5 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/lib.rs` line 15 at r3](https://reviewable.io/reviews/starkware-libs/stwo/706#-O1LNvgGDEczt8P4NNB8:-O1LNvgGDEczt8P4NNB9:b2khmvd) ([raw file](https://github.com/starkware-libs/stwo/blob/55d0ff0072d41460fc3901fc80d263daaf071daa/crates/prover/src/lib.rs#L15)):*
> ```XML
>     portable_simd
> )]
> pub mod builder;
> ```

What does builder mean? Can you give a more indicative name?



_Code quote:_
```XML
builder
```
___
*[`crates/prover/src/builder/mod.rs` line 14 at r3](https://reviewable.io/reviews/starkware-libs/stwo/706#-O1LOVOB2Xb-8O9sNyOs:-O1LOVOB2Xb-8O9sNyOt:bou8joj) ([raw file](https://github.com/starkware-libs/stwo/blob/55d0ff0072d41460fc3901fc80d263daaf071daa/crates/prover/src/builder/mod.rs#L14)):*
> ```XML
> pub trait EvalAtRow {
>     /// The base field type.
>     type F: FieldExpOps
> ```

Add a TODO to combine and share traits between fields and packed fields.
___
*[`crates/prover/src/builder/mod.rs` line 49 at r3](https://reviewable.io/reviews/starkware-libs/stwo/706#-O1LQ9cX90zjmKwIByOh:-O1LQ9cX90zjmKwIByOi:b-glsssy) ([raw file](https://github.com/starkware-libs/stwo/blob/55d0ff0072d41460fc3901fc80d263daaf071daa/crates/prover/src/builder/mod.rs#L49)):*
> ```XML
>         interaction: usize,
>         offsets: [isize; N],
>     ) -> [Self::F; N];
> ```

What does next mask or next interaction mask mean? How is it used?



_Code quote:_
```XML
    /// Returns the next mask.
    fn next_mask(&mut self) -> Self::F {
        self.next_interaction_mask(0, [0])[0]
    }

    /// Returns the next mask for the given interaction.
    fn next_interaction_mask<const N: usize>(
        &mut self,
        interaction: usize,
        offsets: [isize; N],
    ) -> [Self::F; N];
```
___
*[`crates/prover/src/builder/mod.rs` line 54 at r3](https://reviewable.io/reviews/starkware-libs/stwo/706#-O1LRq8785nDYr46vIbO:-O1LRq8785nDYr46vIbP:b-4f9ivm) ([raw file](https://github.com/starkware-libs/stwo/blob/55d0ff0072d41460fc3901fc80d263daaf071daa/crates/prover/src/builder/mod.rs#L54)):*
> ```XML
>     fn add_constraint<G>(&mut self, constraint: G)
>     where
>         Self::EF: Mul<G, Output = Self::EF>;
> ```

How is the constraint added? What type should G be?



_Code quote:_
```XML
    /// Adds a constraint to the component.
    fn add_constraint<G>(&mut self, constraint: G)
    where
        Self::EF: Mul<G, Output = Self::EF>;
```
___
*[`crates/prover/src/builder/mod.rs` line 57 at r3](https://reviewable.io/reviews/starkware-libs/stwo/706#-O1LP1m85F2G-kyfM1e4:-O1LP1m95DlCbGLtflyh:btrq2rh) ([raw file](https://github.com/starkware-libs/stwo/blob/55d0ff0072d41460fc3901fc80d263daaf071daa/crates/prover/src/builder/mod.rs#L57)):*
> ```XML
> 
>     /// Combines 4 base field values into a single extension field value.
>     fn combine_ef(values: [Self::F; 4]) -> Self::EF;
> ```

Why do you need this in here in the trait? Isn't it only for PackedQM31?



_Suggestion:_
```XML
fn combine_ef(values: [Self::F; SECURE_EXTENSION_DEGREE]) -> Self::EF;
```

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r3, 2 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/706)* status: 8 of 9 files reviewed, 9 unresolved discussions (waiting on @alonh5 and @spapinistarkware)

___
*[`crates/prover/src/builder/mod.rs` line 57 at r3](https://reviewable.io/reviews/starkware-libs/stwo/706#-O1LP1m85F2G-kyfM1e4:-O1WNlw342VSAM4fDXdG:b84gqza) ([raw file](https://github.com/starkware-libs/stwo/blob/55d0ff0072d41460fc3901fc80d263daaf071daa/crates/prover/src/builder/mod.rs#L57)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

This trait isn't only for packed, hence the associated type. It is used for both at_point, on_domain, and on the trace, for assertions.
In all cases I need to be able to take 4 mask items, and combine them. This is because I have securefield constraints occasionaly, like in lookups.
</blockquote></details>

Rename the 4 to SECURE_EXTENSION_DEGREE]
___
*[`crates/prover/src/constraint_framework/mod.rs` line 41 at r4](https://reviewable.io/reviews/starkware-libs/stwo/706#-O1WLyFj0_02IAow4P4E:-O1WLyFj0_02IAow4P4F:b-glhca5) ([raw file](https://github.com/starkware-libs/stwo/blob/9994d77a3a631edd0e11d49bd09c03fee6a537ac/crates/prover/src/constraint_framework/mod.rs#L41)):*
> ```XML
> 
>     /// Returns the next mask value.
>     fn next_mask(&mut self) -> Self::F {
> ```

Maybe rename as follows?
and the doc

/// returns the mask item of the original trace at row 0. 



_Suggestion:_
```XML
fn next_trace_mask(&mut self) -> Self::F {
```
___
*[`crates/prover/src/constraint_framework/mod.rs` line 42 at r4](https://reviewable.io/reviews/starkware-libs/stwo/706#-O1WOmt34DGIE0Zp7NSH:-O1WOmt34DGIE0Zp7NSI:bx65wml) ([raw file](https://github.com/starkware-libs/stwo/blob/9994d77a3a631edd0e11d49bd09c03fee6a537ac/crates/prover/src/constraint_framework/mod.rs#L42)):*
> ```XML
>     /// Returns the next mask value.
>     fn next_mask(&mut self) -> Self::F {
>         self.next_interaction_mask(0, [0])[0]
> ```

I think the implementation is a bit misleading
`self.next_interaction_mask(0, [0])` returns a vec of single element



_Code quote:_
```XML
self.next_interaction_mask(0, [0])[0]
```
___
*[`crates/prover/src/constraint_framework/mod.rs` line 45 at r4](https://reviewable.io/reviews/starkware-libs/stwo/706#-O1WNt5r3efjq8NtWeFB:-O1WNt5r3efjq8NtWeFC:b-jlmcj6) ([raw file](https://github.com/starkware-libs/stwo/blob/9994d77a3a631edd0e11d49bd09c03fee6a537ac/crates/prover/src/constraint_framework/mod.rs#L45)):*
> ```XML
>     }
> 
>     /// Returns the next mask values for a given interaction.
> ```

update



_Suggestion:_
```XML
    /// Returns the mask values of the given offsets for the next column in the interaction.
```
___
*[`crates/prover/src/constraint_framework/mod.rs` line 53 at r4](https://reviewable.io/reviews/starkware-libs/stwo/706#-O1WML3-74dF2lBaY8k5:-O1WML3-74dF2lBaY8k6:bu8s7bq) ([raw file](https://github.com/starkware-libs/stwo/blob/9994d77a3a631edd0e11d49bd09c03fee6a537ac/crates/prover/src/constraint_framework/mod.rs#L53)):*
> ```XML
> 
>     /// Adds a constraint to the component.
>     fn add_constraint<G>(&mut self, constraint: G)
> ```

I think that this `G` should have more indicative name as it is not that generic.
Don't have a better suggestion TBH



_Suggestion:_
```XML
    fn accumulate_constraint<G>(&mut self, constraint_eval: G)
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/706)* status: 8 of 9 files reviewed, 7 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

___
*[`crates/prover/src/builder/mod.rs` line 57 at r3](https://reviewable.io/reviews/starkware-libs/stwo/706#-O1LP1m85F2G-kyfM1e4:-O1WVzib-KC9_DOm77-O:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/55d0ff0072d41460fc3901fc80d263daaf071daa/crates/prover/src/builder/mod.rs#L57)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Rename the 4 to SECURE_EXTENSION_DEGREE]
</blockquote></details>

Done.
___
*[`crates/prover/src/constraint_framework/mod.rs` line 41 at r4](https://reviewable.io/reviews/starkware-libs/stwo/706#-O1WLyFj0_02IAow4P4E:-O1WV_Uz-XvUHEOiW9tt:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/9994d77a3a631edd0e11d49bd09c03fee6a537ac/crates/prover/src/constraint_framework/mod.rs#L41)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Maybe rename as follows?
and the doc

/// returns the mask item of the original trace at row 0.
</blockquote></details>

Done.
___
*[`crates/prover/src/constraint_framework/mod.rs` line 45 at r4](https://reviewable.io/reviews/starkware-libs/stwo/706#-O1WNt5r3efjq8NtWeFB:-O1WW1Yi7KfqrTjmts1W:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/9994d77a3a631edd0e11d49bd09c03fee6a537ac/crates/prover/src/constraint_framework/mod.rs#L45)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

update
</blockquote></details>

Done.
___
*[`crates/prover/src/constraint_framework/mod.rs` line 53 at r4](https://reviewable.io/reviews/starkware-libs/stwo/706#-O1WML3-74dF2lBaY8k5:-O1WVn6UEfCS0L5JI_Pm:b-77pd2v) ([raw file](https://github.com/starkware-libs/stwo/blob/9994d77a3a631edd0e11d49bd09c03fee6a537ac/crates/prover/src/constraint_framework/mod.rs#L53)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I think that this `G` should have more indicative name as it is not that generic.
Don't have a better suggestion TBH
</blockquote></details>

I think it's ok. The signature shows it's anything that can be multiplied with EF.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/706#-:-O1WnzK74VbvzpTQBR7J:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @alonh5)

___
*[`crates/prover/src/constraint_framework/mod.rs` line 41 at r4](https://reviewable.io/reviews/starkware-libs/stwo/706#-O1WLyFj0_02IAow4P4E:-O1WntMO67vXSDue9cFm:b-vlm3t6) ([raw file](https://github.com/starkware-libs/stwo/blob/9994d77a3a631edd0e11d49bd09c03fee6a537ac/crates/prover/src/constraint_framework/mod.rs#L41)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

you didn't update the func docmuentation

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/706)* status: all files reviewed, 5 unresolved discussions (waiting on @alonh5 and @spapinistarkware)

___
*[`crates/prover/src/constraint_framework/mod.rs` line 15 at r5](https://reviewable.io/reviews/starkware-libs/stwo/706#-O1Wtv-R4Kck6DY5YKj2:-O1Wtv-SDMlhHNcQz6Ws:b-iqsyqy) ([raw file](https://github.com/starkware-libs/stwo/blob/b758587860b7e302e00a904bd903bcbeb811dc69/crates/prover/src/constraint_framework/mod.rs#L15)):*
> ```XML
> pub trait EvalAtRow {
>     // TODO(spapini): Use a better trait for these, like 'Algebra' or something.
>     /// The base field type.
> ```

F type could sometimes instantiated with SecureField
Doc?



_Code quote:_
```XML
/// The base field type.
```

**Comment by shaharsamocha7** [comment]
*[`crates/prover/src/constraint_framework/mod.rs` line 15 at r5](https://reviewable.io/reviews/starkware-libs/stwo/706#-O1Wtv-R4Kck6DY5YKj2:-O1Wz1qB9Xntz70k4F81:b-kmpfx0) ([raw file](https://github.com/starkware-libs/stwo/blob/b758587860b7e302e00a904bd903bcbeb811dc69/crates/prover/src/constraint_framework/mod.rs#L15)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

F type could sometimes instantiated with SecureField
Doc?
</blockquote></details>

maybe those types should be named as 
PolyField
EvalPointField

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/706)* status: all files reviewed, 5 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/mod.rs` line 15 at r5](https://reviewable.io/reviews/starkware-libs/stwo/706#-O1Wtv-R4Kck6DY5YKj2:-O1kAqWc2GBRdmGxm4FA:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/b758587860b7e302e00a904bd903bcbeb811dc69/crates/prover/src/constraint_framework/mod.rs#L15)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

maybe those types should be named as 
PolyField
EvalPointField
</blockquote></details>

Done.

**Review by shaharsamocha7 — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/706)* status: all files reviewed, 4 unresolved discussions (waiting on @alonh5)

**Pull request merged**
