### PR TITLE
Move prove() to trace gen

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/722)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/722?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#722** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/722?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#721** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/721?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#720** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/720?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/722)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/core/prover/mod.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/stwo/722#-O1lCiMm-bMK_fTkl-VF:-O1lCiMm-bMK_fTkl-VG:b-peyfuo) ([raw file](https://github.com/starkware-libs/stwo/blob/d714156a9cfd6c28207419b599a85ed3c4e91ed2/crates/prover/src/core/prover/mod.rs#L52)):*
> ```XML
> }
> 
> pub fn prove_without_commit<B: Backend + MerkleOps<MerkleHasher>>(
> ```

We said these should be just `prove` and `verify`, right?



_Suggestion:_
```XML
prove
```
___
*[`crates/prover/src/trace_generation/mod.rs` line 85 at r1](https://reviewable.io/reviews/starkware-libs/stwo/722#-O1lD19n4wUomELLLrqc:-O1lD19n4wUomELLLrqd:b-4tqucr) ([raw file](https://github.com/starkware-libs/stwo/blob/d714156a9cfd6c28207419b599a85ed3c4e91ed2/crates/prover/src/trace_generation/mod.rs#L85)):*
> ```XML
> }
> 
> pub fn commit_and_prove<B: Backend + MerkleOps<MerkleHasher>>(
> ```

Maybe move all this into a new file?

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/722)* status: 8 of 11 files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/prover/src/core/prover/mod.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/stwo/722#-O1lCiMm-bMK_fTkl-VF:-O1lEoMUE8d_RTDiTwce:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/d714156a9cfd6c28207419b599a85ed3c4e91ed2/crates/prover/src/core/prover/mod.rs#L52)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

We said these should be just `prove` and `verify`, right?
</blockquote></details>

Done.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/722#-:-O1lME63BTIPEk3aWhBv:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
