### PR TITLE
State machine prover

### PR DESCRIPTION
**Pull request by shaharsamocha7**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/845)

### CODE REVIEW

**Comment by shaharsamocha7** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/845?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#845** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/845?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#841** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/841?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#830** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/830?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#829** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/829?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#825** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/825?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#818** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/818?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @shaharsamocha7 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Alon-Ti — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/845#-:-O7OM9TgDX_6zx7__Tdk:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Review by Alon-Ti — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/845#-:-O7i5rPX4NGaJpwdAppr:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Comment by shaharsamocha7** [comment]
### Merge activity

* **Sep 26, 10:27 AM EDT**: @shaharsamocha7 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/845).

**Pull request merged**
