### PR TITLE
 removed line coeffs from constraint accumulation

### PR DESCRIPTION
**Pull request by ohad-agadi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/643)

### CODE REVIEW

**Comment by ohad-starkware** [comment]
* **#643** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/643?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ohad-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/643)* status: all files reviewed, 1 unresolved discussion (waiting on @ohad-starkware)

___
*[`crates/prover/src/core/backend/cpu/quotients.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/stwo/643#-O-UrZpn0Uq3dzPVY7_X:-O-UrZpn0Uq3dzPVY7_Y:byp18fd) ([raw file](https://github.com/starkware-libs/stwo/blob/95cfb98c2402f48ee4b0f8d75633f90c780ecd72/crates/prover/src/core/backend/cpu/quotients.rs#L67)):*
> ```XML
> /// `alpha^i * (c * F(p) - (a * p.y + b))`, we precompute and return the constants:
> /// (`alpha^i * a`, `alpha^i * b`, `alpha^i * c`).
> // TODO(Ohad): unused, remove or use.
> ```

Remove

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/643#-:-O-UrgbmANrknikQS7NG:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ohad-starkware)

**Review by ohad-agadi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/643)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/prover/src/core/backend/cpu/quotients.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/stwo/643#-O-UrZpn0Uq3dzPVY7_X:-O-_cSttEq0cEGTLTE9A:bb7mtv8) ([raw file](https://github.com/starkware-libs/stwo/blob/95cfb98c2402f48ee4b0f8d75633f90c780ecd72/crates/prover/src/core/backend/cpu/quotients.rs#L67)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Remove
</blockquote></details>

ptal

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/643#-:-O-_wKunAQnmoZgnJcAj:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ohad-starkware)

**Pull request merged**
