### PR TITLE
CM31 denoms

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/743)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
* **#744** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/744?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#743** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/743?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ohad-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/743)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/core/backend/cpu/quotients.rs` line 132 at r1](https://reviewable.io/reviews/starkware-libs/stwo/743#-O2OGv4F3Y7pzfQVo--E:-O2OGv4F3Y7pzfQVo--F:b-kl43c0) ([raw file](https://github.com/starkware-libs/stwo/blob/a8547913ced92e34e40f84a56cbcb5e85989de02/crates/prover/src/core/backend/cpu/quotients.rs#L132)):*
> ```XML
>         for row in 0..domain.size() {
>             let domain_point = domain.at(row);
>             flat_denominators.push((prx - domain_point.x) * piy - (pry - domain_point.y) * pix);
> ```

document
___
*[`crates/prover/src/core/backend/simd/column.rs` line 99 at r1](https://reviewable.io/reviews/starkware-libs/stwo/743#-O2OLaBj1eTF6TmPTtXC:-O2OLaBj1eTF6TmPTtXD:b-gqb1j3) ([raw file](https://github.com/starkware-libs/stwo/blob/a8547913ced92e34e40f84a56cbcb5e85989de02/crates/prover/src/core/backend/simd/column.rs#L99)):*
> ```XML
> // A efficient structure for storing and operating on a arbitrary number of [`SecureField`] values.
> #[derive(Clone, Debug)]
> pub struct CMFieldVec {
> ```

why not implement ColumnOps<CM31> for simd backend?
then quotient constants can be generic
___
*[`crates/prover/src/core/fields/qm31.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/stwo/743#-O2OJ6buCSs-CkwfSzKe:-O2OJ6buCSs-CkwfSzKf:b-hregys) ([raw file](https://github.com/starkware-libs/stwo/blob/a8547913ced92e34e40f84a56cbcb5e85989de02/crates/prover/src/core/fields/qm31.rs#L55)):*
> ```XML
>     }
> 
>     pub fn mul_cm31(self, rhs: CM31) -> Self {
> ```

1. is it in the right file?
2. why not trait impl?

**Review by ohad-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/743)* status: 0 of 10 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/core/fields/qm31.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/stwo/743#-O2OJ6buCSs-CkwfSzKe:-O2cfQ4x5QtGTRQKfTVM:b-l42r3p) ([raw file](https://github.com/starkware-libs/stwo/blob/a8547913ced92e34e40f84a56cbcb5e85989de02/crates/prover/src/core/fields/qm31.rs#L55)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

1. is it in the right file?
2. why not trait impl?
</blockquote></details>

it is the right file
and there is a trait impl,
if both are needed you can use this in the trait impl
or remove this

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/743)* status: 0 of 10 files reviewed, 3 unresolved discussions (waiting on @ohad-starkware)

___
*[`crates/prover/src/core/backend/simd/column.rs` line 99 at r1](https://reviewable.io/reviews/starkware-libs/stwo/743#-O2OLaBj1eTF6TmPTtXC:-O2cilm64Rq9KWxG5mWR:b-kj8ql1) ([raw file](https://github.com/starkware-libs/stwo/blob/a8547913ced92e34e40f84a56cbcb5e85989de02/crates/prover/src/core/backend/simd/column.rs#L99)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

why not implement ColumnOps<CM31> for simd backend?
then quotient constants can be generic
</blockquote></details>

I would like to remove bakcend generics here as much as possible.
These are only used by the impl for the QuotientOps anyway, so each backend has the freedom to do what he wants.
Adding generic can only help code reuse, but this also limits the backends to not diverge at all in their implemetnation.
Also, I would like the cpu backedn to be a 'reference impl', and not use this optimization.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/743)* status: 0 of 10 files reviewed, 3 unresolved discussions (waiting on @ohad-starkware)

___
*[`crates/prover/src/core/fields/qm31.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/stwo/743#-O2OJ6buCSs-CkwfSzKe:-O2cjIA_0FU00KEBKOkk:b-l4396t) ([raw file](https://github.com/starkware-libs/stwo/blob/a8547913ced92e34e40f84a56cbcb5e85989de02/crates/prover/src/core/fields/qm31.rs#L55)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

it is the right file
and there is a trait impl,
if both are needed you can use this in the trait impl
or remove this
</blockquote></details>

Added a comment

**Review by ohad-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/743#-:-O2clPiZDmEvFmlwJdoq:bnfp4nl)* status: 0 of 10 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/column.rs` line 99 at r1](https://reviewable.io/reviews/starkware-libs/stwo/743#-O2OLaBj1eTF6TmPTtXC:-O2clHOk5xfowmapihJW:biay1rk) ([raw file](https://github.com/starkware-libs/stwo/blob/a8547913ced92e34e40f84a56cbcb5e85989de02/crates/prover/src/core/backend/simd/column.rs#L99)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I would like to remove bakcend generics here as much as possible.
These are only used by the impl for the QuotientOps anyway, so each backend has the freedom to do what he wants.
Adding generic can only help code reuse, but this also limits the backends to not diverge at all in their implemetnation.
Also, I would like the cpu backedn to be a 'reference impl', and not use this optimization.
</blockquote></details>

understood
___
*[`crates/prover/src/core/fields/qm31.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/stwo/743#-O2OJ6buCSs-CkwfSzKe:-O2clLquEo4EILAJ5Rk9:bfn8qmw) ([raw file](https://github.com/starkware-libs/stwo/blob/a8547913ced92e34e40f84a56cbcb5e85989de02/crates/prover/src/core/fields/qm31.rs#L55)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Added a comment
</blockquote></details>

are you sure?

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/743)* status: 0 of 10 files reviewed, 3 unresolved discussions (waiting on @ohad-starkware)

___
*[`crates/prover/src/core/backend/cpu/quotients.rs` line 132 at r1](https://reviewable.io/reviews/starkware-libs/stwo/743#-O2OGv4F3Y7pzfQVo--E:-O2clahq6OSkY_Ieftqf:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/a8547913ced92e34e40f84a56cbcb5e85989de02/crates/prover/src/core/backend/cpu/quotients.rs#L132)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

document
</blockquote></details>

Done.
___
*[`crates/prover/src/core/backend/simd/column.rs` line 99 at r1](https://reviewable.io/reviews/starkware-libs/stwo/743#-O2OLaBj1eTF6TmPTtXC:-O2clbYvE3HRstGCE4fq:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/a8547913ced92e34e40f84a56cbcb5e85989de02/crates/prover/src/core/backend/simd/column.rs#L99)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

understood
</blockquote></details>

Done.
___
*[`crates/prover/src/core/fields/qm31.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/stwo/743#-O2OJ6buCSs-CkwfSzKe:-O2clmqfBvZBePb0EsH4:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/a8547913ced92e34e40f84a56cbcb5e85989de02/crates/prover/src/core/fields/qm31.rs#L55)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

are you sure?
</blockquote></details>

Done.

**Pull request merged**
