### PR TITLE
Poseidon252 channel

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/655)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
* **#655** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/655?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/655)* status: 3 of 5 files reviewed, 7 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/Cargo.toml` line 19 at r2](https://reviewable.io/reviews/starkware-libs/stwo/655#-NzcY1K9CqfzETYs1l24:-NzcY1K9CqfzETYs1l25:b-3mv78z) ([raw file](https://github.com/starkware-libs/stwo/blob/af66000de0d4419a9d3be9a9f70ffe18c2dda067/crates/prover/Cargo.toml#L19)):*
> ```TOML
> rand = { version = "0.8.5", default-features = false, features = ["small_rng"] }
> starknet-crypto = "0.6.2"
> starknet-ff = "0.3.7"
> ```

Can you use this crate instead?



_Suggestion:_
```TOML
starknet-types-core = { version = "0.0.11", features = ["hash"] }
```
___
*[`crates/prover/src/core/channel/poseidon252.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/stwo/655#-Nzc_2Bo5VyrN47gfCF5:-Nzc_2Bo5VyrN47gfCF6:bdiw49u) ([raw file](https://github.com/starkware-libs/stwo/blob/af66000de0d4419a9d3be9a9f70ffe18c2dda067/crates/prover/src/core/channel/poseidon252.rs#L27)):*
> ```XML
>     }
> 
>     /// Generates a uniform random vector of BaseField elements.
> ```

Is it correct?
I don't think that `u32s` is uniformly random.



_Code quote:_
```XML
    /// Generates a uniform random vector of BaseField elements.
```
___
*[`crates/prover/src/core/channel/poseidon252.rs` line 57 at r2](https://reviewable.io/reviews/starkware-libs/stwo/655#-Nzc_bHh3nOEb8Itcr0o:-Nzc_bHi2pkIfjDrrGWe:byit0su) ([raw file](https://github.com/starkware-libs/stwo/blob/af66000de0d4419a9d3be9a9f70ffe18c2dda067/crates/prover/src/core/channel/poseidon252.rs#L57)):*
> ```XML
> impl Channel for Poseidon252Channel {
>     type Digest = FieldElement252;
>     const BYTES_PER_HASH: usize = BLAKE_BYTES_PER_HASH;
> ```

Rename

or maybe we should remove this const and get n_bytes as a parameter?
If so, just put a TODO on me.



_Suggestion:_
```XML
BYTES_PER_HASH
```
___
*[`crates/prover/src/core/channel/poseidon252.rs` line 75 at r2](https://reviewable.io/reviews/starkware-libs/stwo/655#-NzcgJ1u1MYiG0ItdHY3:-NzcgJ1u1MYiG0ItdHY4:bt9pzxf) ([raw file](https://github.com/starkware-libs/stwo/blob/af66000de0d4419a9d3be9a9f70ffe18c2dda067/crates/prover/src/core/channel/poseidon252.rs#L75)):*
> ```XML
>     }
> 
>     fn mix_felts(&mut self, felts: &[SecureField]) {
> ```

Consider to mix one secure felt at a time. (for simplicity)



_Code quote:_
```XML
fn mix_felts(&mut self, felts: &[SecureField]) {
```
___
*[`crates/prover/src/core/channel/poseidon252.rs` line 115 at r2](https://reviewable.io/reviews/starkware-libs/stwo/655#-NzchXzT2CFPk_GZPqau:-NzchXzUDEp6jljUGuzi:b-8dvabk) ([raw file](https://github.com/starkware-libs/stwo/blob/af66000de0d4419a9d3be9a9f70ffe18c2dda067/crates/prover/src/core/channel/poseidon252.rs#L115)):*
> ```XML
>                 felts.next()?,
>                 felts.next()?,
>             ]))
> ```

Can you explain to me this impl? I don't understand why it works :(

How is the second felts.next()? doesn't call draw_base_felts()?
What would've happen if draw_base_felts() returns a [BaseField; 9]?



_Code quote:_
```XML
            Some(SecureField::from_m31_array([
                felts.next()?,
                felts.next()?,
                felts.next()?,
                felts.next()?,
            ]))
```
___
*[`crates/prover/src/core/channel/poseidon252.rs` line 120 at r2](https://reviewable.io/reviews/starkware-libs/stwo/655#-NzciFkS6WYrM4S5rRwu:-NzciFkS6WYrM4S5rRwv:blws50u) ([raw file](https://github.com/starkware-libs/stwo/blob/af66000de0d4419a9d3be9a9f70ffe18c2dda067/crates/prover/src/core/channel/poseidon252.rs#L120)):*
> ```XML
>     }
> 
>     fn draw_random_bytes(&mut self) -> Vec<u8> {
> ```

In Stone, we used the repeating method for this function.



_Code quote:_
```XML
    fn draw_random_bytes(&mut self) -> Vec<u8> {
```
___
*[`crates/prover/src/core/channel/blake2s.rs` line 114 at r2](https://reviewable.io/reviews/starkware-libs/stwo/655#-NzcYesmAsAvB7Al0L-s:-NzcYesmAsAvB7Al0L-t:b-u1vl2j) ([raw file](https://github.com/starkware-libs/stwo/blob/af66000de0d4419a9d3be9a9f70ffe18c2dda067/crates/prover/src/core/channel/blake2s.rs#L114)):*
> ```XML
>         hash_input.extend_from_slice(&padded_counter);
> 
>         // TODO(spapini): Are we worried about this drawing hash colliding with mix_digest?
> ```

Not sure that I understand this comment

ChannelState_i -> mix_digest -> draw_random
ChannelState_i -> draw_random

outputs different randomness



_Code quote:_
```XML
 // TODO(spapini): Are we worried about this drawing hash colliding with mix_digest?
```

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/655)* status: 3 of 5 files reviewed, 7 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/core/channel/poseidon252.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/stwo/655#-Nzc_2Bo5VyrN47gfCF5:-Nzvw19w3GsnXoj5XsX2:b-l51j6p) ([raw file](https://github.com/starkware-libs/stwo/blob/af66000de0d4419a9d3be9a9f70ffe18c2dda067/crates/prover/src/core/channel/poseidon252.rs#L27)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Is it correct?
I don't think that `u32s` is uniformly random.
</blockquote></details>

Why not using `draw_random_bytes` here?

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/655)* status: 3 of 5 files reviewed, 7 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/prover/Cargo.toml` line 19 at r2](https://reviewable.io/reviews/starkware-libs/stwo/655#-NzcY1K9CqfzETYs1l24:-Nzw6I552K7UtnsAJ3iH:bn7sb2l) ([raw file](https://github.com/starkware-libs/stwo/blob/af66000de0d4419a9d3be9a9f70ffe18c2dda067/crates/prover/Cargo.toml#L19)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can you use this crate instead?
</blockquote></details>

It had some issues.
___
*[`crates/prover/src/core/channel/poseidon252.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/stwo/655#-Nzc_2Bo5VyrN47gfCF5:-Nzw3xRi0sAUvEZ-Tny0:bfpm48h) ([raw file](https://github.com/starkware-libs/stwo/blob/af66000de0d4419a9d3be9a9f70ffe18c2dda067/crates/prover/src/core/channel/poseidon252.rs#L27)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why not using `draw_random_bytes` here?
</blockquote></details>

right, it's not uniform.

Uniform `draw_random_bytes` would also do rejection sampling, and doing rejection on top of rejection doesn't make sense (i.e. If I want to get uniform on [0,a], I won't try to get uniform on [0,b] first. That's not efficient and wierd).
___
*[`crates/prover/src/core/channel/poseidon252.rs` line 57 at r2](https://reviewable.io/reviews/starkware-libs/stwo/655#-Nzc_bHh3nOEb8Itcr0o:-Nzw4xHS3EmMxd5aSWRN:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/af66000de0d4419a9d3be9a9f70ffe18c2dda067/crates/prover/src/core/channel/poseidon252.rs#L57)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Rename

or maybe we should remove this const and get n_bytes as a parameter?
If so, just put a TODO on me.
</blockquote></details>

Done.
___
*[`crates/prover/src/core/channel/poseidon252.rs` line 75 at r2](https://reviewable.io/reviews/starkware-libs/stwo/655#-NzcgJ1u1MYiG0ItdHY3:-Nzw5-oU5NmVoqrhWpjA:bnkim9v) ([raw file](https://github.com/starkware-libs/stwo/blob/af66000de0d4419a9d3be9a9f70ffe18c2dda067/crates/prover/src/core/channel/poseidon252.rs#L75)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Consider to mix one secure felt at a time. (for simplicity)
</blockquote></details>

that's not efficient, and we want to minimize cairo steps.
___
*[`crates/prover/src/core/channel/poseidon252.rs` line 115 at r2](https://reviewable.io/reviews/starkware-libs/stwo/655#-NzchXzT2CFPk_GZPqau:-Nzw5KLo7HDKcIxN6Q4b:b-9tjxba) ([raw file](https://github.com/starkware-libs/stwo/blob/af66000de0d4419a9d3be9a9f70ffe18c2dda067/crates/prover/src/core/channel/poseidon252.rs#L115)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can you explain to me this impl? I don't understand why it works :(

How is the second felts.next()? doesn't call draw_base_felts()?
What would've happen if draw_base_felts() returns a [BaseField; 9]?
</blockquote></details>

You wrote this code:) You have .flatten() (The closure itself returns an array). This creates an iterator that consumes the elements in the array, and only when done, calls the function again.
`[BaseField; 9]?` would work similarly.
___
*[`crates/prover/src/core/channel/poseidon252.rs` line 120 at r2](https://reviewable.io/reviews/starkware-libs/stwo/655#-NzciFkS6WYrM4S5rRwu:-Nzw663O2khrlnPVQ0er:btlvwif) ([raw file](https://github.com/starkware-libs/stwo/blob/af66000de0d4419a9d3be9a9f70ffe18c2dda067/crates/prover/src/core/channel/poseidon252.rs#L120)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

In Stone, we used the repeating method for this function.
</blockquote></details>

what is the repeating method?
___
*[`crates/prover/src/core/channel/blake2s.rs` line 114 at r2](https://reviewable.io/reviews/starkware-libs/stwo/655#-NzcYesmAsAvB7Al0L-s:-Nzw3-yaDbOa6Htm-KLY:b-ufxyb6) ([raw file](https://github.com/starkware-libs/stwo/blob/af66000de0d4419a9d3be9a9f70ffe18c2dda067/crates/prover/src/core/channel/blake2s.rs#L114)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Not sure that I understand this comment

ChannelState_i -> mix_digest -> draw_random
ChannelState_i -> draw_random

outputs different randomness
</blockquote></details>

If I imagine an interactive scenario, and I did
a = draw_randomness()
send(a)
mix_digest()

And the state after mix_digest would e the same as a, then all the randomness could be "anticipated" byu the other party.

I'm not sure if this is relevant to Fiat Shamir, and not sure what we did in Stone, but I want to keep this in mind until I know.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/655)* status: 4 of 5 files reviewed, 4 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/Cargo.toml` line 19 at r2](https://reviewable.io/reviews/starkware-libs/stwo/655#-NzcY1K9CqfzETYs1l24:-NzwTDMnCWP7oA-DbjU_:b-sivaj6) ([raw file](https://github.com/starkware-libs/stwo/blob/af66000de0d4419a9d3be9a9f70ffe18c2dda067/crates/prover/Cargo.toml#L19)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

It had some issues.
</blockquote></details>

Can you please state one of them? For now we can import from starknet-crypto but maybe it is worth mentioning what this lib is lack of
___
*[`crates/prover/src/core/channel/poseidon252.rs` line 75 at r2](https://reviewable.io/reviews/starkware-libs/stwo/655#-NzcgJ1u1MYiG0ItdHY3:-NzwBQ7M1kU_2sDzeN82:b-9hs5mn) ([raw file](https://github.com/starkware-libs/stwo/blob/af66000de0d4419a9d3be9a9f70ffe18c2dda067/crates/prover/src/core/channel/poseidon252.rs#L75)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

that's not efficient, and we want to minimize cairo steps.
</blockquote></details>

It is just 2x hashes. Not sure that this logic wouldn't induce more trace cells.
I would go with the simple impl, but your call
___
*[`crates/prover/src/core/channel/poseidon252.rs` line 115 at r2](https://reviewable.io/reviews/starkware-libs/stwo/655#-NzchXzT2CFPk_GZPqau:-NzwBkk2DaTZP13OHSR5:b-bzyeu2) ([raw file](https://github.com/starkware-libs/stwo/blob/af66000de0d4419a9d3be9a9f70ffe18c2dda067/crates/prover/src/core/channel/poseidon252.rs#L115)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

You wrote this code:) You have .flatten() (The closure itself returns an array). This creates an iterator that consumes the elements in the array, and only when done, calls the function again.
`[BaseField; 9]?` would work similarly.
</blockquote></details>

Ty.
I understand it now
___
*[`crates/prover/src/core/channel/poseidon252.rs` line 120 at r2](https://reviewable.io/reviews/starkware-libs/stwo/655#-NzciFkS6WYrM4S5rRwu:-NzwSuec2hGCMNxchrmp:bjkm3xi) ([raw file](https://github.com/starkware-libs/stwo/blob/af66000de0d4419a9d3be9a9f70ffe18c2dda067/crates/prover/src/core/channel/poseidon252.rs#L120)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

what is the repeating method?
</blockquote></details>

nvm I thought that we repeat if it is not in the range n_bytes * C, but now I see that it is not the case.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/655)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`crates/prover/Cargo.toml` line 19 at r2](https://reviewable.io/reviews/starkware-libs/stwo/655#-NzcY1K9CqfzETYs1l24:-O-0I_qKEa8wGIebAmXc:b-sk1pem) ([raw file](https://github.com/starkware-libs/stwo/blob/af66000de0d4419a9d3be9a9f70ffe18c2dda067/crates/prover/Cargo.toml#L19)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can you please state one of them? For now we can import from starknet-crypto but maybe it is worth mentioning what this lib is lack of
</blockquote></details>

I was lacking conversions from and to integers.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/655#-:-O-0a-WuEf3eznFC8VzT:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
