### PR TITLE
Precompute alphas for quotients.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/558)

### CODE REVIEW

**Comment by alonh5** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/558?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#558** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/558?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#556** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/556?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#555** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/555?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/558)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`src/core/backend/cpu/quotients.rs` line 126 at r1](https://reviewable.io/reviews/starkware-libs/stwo/558#-NuOQ4KzEBi67gTW_W2b:-NuOQ4L-1D_ngYrpRi7S:blbckrk) ([raw file](https://github.com/starkware-libs/stwo/blob/db9e30086639514e5133cee3fe2341be1610d0fd/src/core/backend/cpu/quotients.rs#L126)):*
> ```XML
>     /// The line coefficients for each quotient numerator term.
>     pub line_coeffs: Vec<Vec<(SecureField, SecureField, SecureField)>>,
>     /// The random coefficients used to linearly combine the quotients.
> ```

this doesn't explain this enough.
It should mentione sampel batches IMO. This doesn't jsut combine the quotients, it combines the batches.

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/558)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`src/core/backend/cpu/quotients.rs` line 126 at r1](https://reviewable.io/reviews/starkware-libs/stwo/558#-NuOQ4KzEBi67gTW_W2b:-NuPBicu6O8cg8BmzOkP:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/98c336a422ba18cf69393d2257fc9d7eb07f0245/src/core/backend/cpu/quotients.rs#L126)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

this doesn't explain this enough.
It should mentione sampel batches IMO. This doesn't jsut combine the quotients, it combines the batches.
</blockquote></details>

Done.

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/558)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`src/core/backend/cpu/quotients.rs` line 126 at r1](https://reviewable.io/reviews/starkware-libs/stwo/558#-NuOQ4KzEBi67gTW_W2b:-NuTUNA2-PnPrzCcjhI6:b-row0ru) ([raw file](https://github.com/starkware-libs/stwo/blob/98c336a422ba18cf69393d2257fc9d7eb07f0245/src/core/backend/cpu/quotients.rs#L126)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Great. Now, if we can rename alpha to reflect this, it would be perfect!
Suggestion: batch_coeff

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/558)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`src/core/backend/cpu/quotients.rs` line 126 at r1](https://reviewable.io/reviews/starkware-libs/stwo/558#-NuOQ4KzEBi67gTW_W2b:-NuTd4-Q8j7Dz3u5dKAZ:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/98c336a422ba18cf69393d2257fc9d7eb07f0245/src/core/backend/cpu/quotients.rs#L126)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Great. Now, if we can rename alpha to reflect this, it would be perfect!
Suggestion: batch_coeff
</blockquote></details>

Done.

**Comment by alonh5** [comment]
### Merge activity

* **Apr 2, 9:14 AM EDT**: @alonh5 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/558).

**Pull request merged**
