### PR TITLE
Separated Base and Extension field expressions.

### PR DESCRIPTION
**Pull request by Alon-Ti**

### CODE REVIEW

**Comment by Alon-Ti** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/903?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#903** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/903?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/903?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#901** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/901?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#894** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/894?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#893** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/893?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#892** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/892?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#889** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/889?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#888** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/888?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#887** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/887?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#879** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/879?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#883](https://github.com/starkware-libs/stwo/pull/883) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/883?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#876** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/876?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#875** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/875?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/903)* status: 0 of 2 files reviewed, 9 unresolved discussions (waiting on @Alon-Ti)

___
*[`crates/prover/src/constraint_framework/expr.rs` line 21 at r2](https://reviewable.io/reviews/starkware-libs/stwo/903#-OCmYM6Z5I5COfbVtfzx:-OCmYM6Z5I5COfbVtfzy:b-8k4wmb) ([raw file](https://github.com/starkware-libs/stwo/blob/a65c07d5ecf1f52e8798172a1ca618f09a8f2209/crates/prover/src/constraint_framework/expr.rs#L21)):*
> ```XML
> 
> #[derive(Clone, Debug, PartialEq)]
> pub enum BaseExpr {
> ```

Can you document the Base and Ext expressions?
Specifically also mention that those types can interact with each other, and also with M31, QM31



_Code quote:_
```XML
#[derive(Clone, Debug, PartialEq)]
pub enum BaseExpr {
```
___
*[`crates/prover/src/constraint_framework/expr.rs` line 30 at r2](https://reviewable.io/reviews/starkware-libs/stwo/903#-OCmZwOo5eJZK612XTC6:-OCmZwOp1scfwv8Vsvy7:b7vx718) ([raw file](https://github.com/starkware-libs/stwo/blob/a65c07d5ecf1f52e8798172a1ca618f09a8f2209/crates/prover/src/constraint_framework/expr.rs#L30)):*
> ```XML
>     Mul(Box<BaseExpr>, Box<BaseExpr>),
>     Neg(Box<BaseExpr>),
>     Inv(Box<BaseExpr>),
> ```

Why do you have Inv here but not in the Extension?



_Code quote:_
```XML
    Inv(Box<BaseExpr>),
```
___
*[`crates/prover/src/constraint_framework/expr.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/stwo/903#-OCm_buYE6rwkm0bS40e:-OCm_buYE6rwkm0bS40f:buyeu96) ([raw file](https://github.com/starkware-libs/stwo/blob/a65c07d5ecf1f52e8798172a1ca618f09a8f2209/crates/prover/src/constraint_framework/expr.rs#L50)):*
> ```XML
> }
> 
> macro_rules! simplify_arithmetic {
> ```

Document this macro



_Code quote:_
```XML
macro_rules! simplify_arithmetic {
```
___
*[`crates/prover/src/constraint_framework/expr.rs` line 95 at r2](https://reviewable.io/reviews/starkware-libs/stwo/903#-OCmZ7CXCStMzNf5YHI9:-OCmZ7CXCStMzNf5YHIA:b-feec0v) ([raw file](https://github.com/starkware-libs/stwo/blob/a65c07d5ecf1f52e8798172a1ca618f09a8f2209/crates/prover/src/constraint_framework/expr.rs#L95)):*
> ```XML
>                     (_, Self::Neg(minus_b)) => -(a * *minus_b), // a * (-b) = -(a * b)
>                     (Self::Const(a_val), _) if -a_val == One::one() => -b, // -1 * b = -b
>                     (_, Self::Const(b_val)) if -b_val == One::one() => -a, // a * -1 = -a
> ```

I think we should add some comments here
LMK what you think



_Suggestion:_
```XML
                    // Simplify consts.
                    (Self::Const(a), Self::Const(b)) => Self::Const(a * b),
                    (Self::Const(a_val), _) if a_val.is_zero() => Self::zero(), // 0 * b = 0
                    (_, Self::Const(b_val)) if b_val.is_zero() => Self::zero(), // a * 0 = 0
                    (Self::Const(a_val), _) if a_val == One::one() => b,        // 1 * b = b
                    (_, Self::Const(b_val)) if b_val == One::one() => a,        // a * 1 = a
                    (Self::Const(a_val), _) if -a_val == One::one() => -b, // -1 * b = -b
                    (_, Self::Const(b_val)) if -b_val == One::one() => -a, // a * -1 = -a
                    
                    // Simplify negs.
                    (Self::Neg(minus_a), Self::Neg(minus_b)) => *minus_a * *minus_b, // (-a) * (-b) = a * b
                    (Self::Neg(minus_a), _) => -(*minus_a * b), // (-a) * b = -(a * b)
                    (_, Self::Neg(minus_b)) => -(a * *minus_b), // a * (-b) = -(a * b)
                    
                    // No simplification
                     _ => a * b,
```
___
*[`crates/prover/src/constraint_framework/expr.rs` line 101 at r2](https://reviewable.io/reviews/starkware-libs/stwo/903#-OCmZUxgC_j7lDFrGS-e:-OCmZUxgC_j7lDFrGS-f:b8cridw) ([raw file](https://github.com/starkware-libs/stwo/blob/a65c07d5ecf1f52e8798172a1ca618f09a8f2209/crates/prover/src/constraint_framework/expr.rs#L101)):*
> ```XML
>             Self::Neg(a) => {
>                 let a = a.simplify();
>                 match a {
> ```

Should we handle zero explicitly?



_Code quote:_
```XML
match a {
```
___
*[`crates/prover/src/constraint_framework/expr.rs` line 109 at r2](https://reviewable.io/reviews/starkware-libs/stwo/903#-OCmZjSHBrBM0L5-bK33:-OCmZjSHBrBM0L5-bK34:b7r5xui) ([raw file](https://github.com/starkware-libs/stwo/blob/a65c07d5ecf1f52e8798172a1ca618f09a8f2209/crates/prover/src/constraint_framework/expr.rs#L109)):*
> ```XML
>             }
>             other => other,
>         }
> ```

Comment



_Suggestion:_
```XML
            }
            // No simplification.
            other => other,
        }
```
___
*[`crates/prover/src/constraint_framework/expr.rs` line 163 at r2](https://reviewable.io/reviews/starkware-libs/stwo/903#-OCm_CfU3uCq6vr3wQpC:-OCm_CfU3uCq6vr3wQpD:b-fxi9ka) ([raw file](https://github.com/starkware-libs/stwo/blob/a65c07d5ecf1f52e8798172a1ca618f09a8f2209/crates/prover/src/constraint_framework/expr.rs#L163)):*
> ```XML
>             ExtExpr::SecureCol([a, b, c, d]) => {
>                 if **b == BaseExpr::zero() && **c == BaseExpr::zero() && **d == BaseExpr::zero() {
>                     a.format_expr()
> ```

how is that work?



_Code quote:_
```XML
a.format_expr()
```
___
*[`crates/prover/src/constraint_framework/expr.rs` line 580 at r2](https://reviewable.io/reviews/starkware-libs/stwo/903#-OCmaJG19X01Eji4zHMa:-OCmaJG19X01Eji4zHMb:b-az9gby) ([raw file](https://github.com/starkware-libs/stwo/blob/a65c07d5ecf1f52e8798172a1ca618f09a8f2209/crates/prover/src/constraint_framework/expr.rs#L580)):*
> ```XML
> impl EvalAtRow for ExprEvaluator {
>     // TODO(alont): Should there be a version of this that disallows Secure fields for F?
>     type F = BaseExpr;
> ```

What would fail if this is ExtExpr (the secure column things)?



_Code quote:_
```XML
type F = BaseExpr;
```
___
*[`crates/prover/src/constraint_framework/expr.rs` line 665 at r2](https://reviewable.io/reviews/starkware-libs/stwo/903#-OCmaE2122X4cgGtPj5J:-OCmaE2122X4cgGtPj5K:b-7yuv8z) ([raw file](https://github.com/starkware-libs/stwo/blob/a65c07d5ecf1f52e8798172a1ca618f09a8f2209/crates/prover/src/constraint_framework/expr.rs#L665)):*
> ```XML
>             ) \
>             * (intermediate0) \
>             - (1 + 0i);"
> ```

this is not extension field 



_Code quote:_
```XML
(1 + 0i)
```

**Review by Alon-Ti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/903)* status: 0 of 2 files reviewed, 9 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/expr.rs` line 21 at r2](https://reviewable.io/reviews/starkware-libs/stwo/903#-OCmYM6Z5I5COfbVtfzx:-OD0qsBkCtyUXy88l_BA:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/409513463053d7dfbb0ca6a3ce6a39b60d699b83/crates/prover/src/constraint_framework/expr.rs#L21)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can you document the Base and Ext expressions?
Specifically also mention that those types can interact with each other, and also with M31, QM31
</blockquote></details>

Done.
___
*[`crates/prover/src/constraint_framework/expr.rs` line 30 at r2](https://reviewable.io/reviews/starkware-libs/stwo/903#-OCmZwOo5eJZK612XTC6:-OCnIunp2JbNQOaNBzIh:bpf0hus) ([raw file](https://github.com/starkware-libs/stwo/blob/409513463053d7dfbb0ca6a3ce6a39b60d699b83/crates/prover/src/constraint_framework/expr.rs#L30)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why do you have Inv here but not in the Extension?
</blockquote></details>

`EvalAtRow::EF` isn't bound by `FieldExpOps`.
___
*[`crates/prover/src/constraint_framework/expr.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/stwo/903#-OCm_buYE6rwkm0bS40e:-OD0rQac4N_N8xqR0m21:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/409513463053d7dfbb0ca6a3ce6a39b60d699b83/crates/prover/src/constraint_framework/expr.rs#L50)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Document this macro
</blockquote></details>

Done.
___
*[`crates/prover/src/constraint_framework/expr.rs` line 95 at r2](https://reviewable.io/reviews/starkware-libs/stwo/903#-OCmZ7CXCStMzNf5YHI9:-OD0tQ8iBguxVzfKbEEJ:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/409513463053d7dfbb0ca6a3ce6a39b60d699b83/crates/prover/src/constraint_framework/expr.rs#L95)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I think we should add some comments here
LMK what you think
</blockquote></details>

Done.
___
*[`crates/prover/src/constraint_framework/expr.rs` line 101 at r2](https://reviewable.io/reviews/starkware-libs/stwo/903#-OCmZUxgC_j7lDFrGS-e:-OD0tZuk8a-VmUI_9Ldt:b-3hqvdq) ([raw file](https://github.com/starkware-libs/stwo/blob/409513463053d7dfbb0ca6a3ce6a39b60d699b83/crates/prover/src/constraint_framework/expr.rs#L101)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Should we handle zero explicitly?
</blockquote></details>

I think it's handled by the const branch correctly, right?
___
*[`crates/prover/src/constraint_framework/expr.rs` line 109 at r2](https://reviewable.io/reviews/starkware-libs/stwo/903#-OCmZjSHBrBM0L5-bK33:-OD0tgpcEn68c26oGcEg:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/409513463053d7dfbb0ca6a3ce6a39b60d699b83/crates/prover/src/constraint_framework/expr.rs#L109)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Comment
</blockquote></details>

Done.
___
*[`crates/prover/src/constraint_framework/expr.rs` line 163 at r2](https://reviewable.io/reviews/starkware-libs/stwo/903#-OCm_CfU3uCq6vr3wQpC:-OCnKDmIARHhMWYpgSN3:byrpps) ([raw file](https://github.com/starkware-libs/stwo/blob/409513463053d7dfbb0ca6a3ce6a39b60d699b83/crates/prover/src/constraint_framework/expr.rs#L163)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

how is that work?
</blockquote></details>

If you have a `SecureCol` that's actually constantly in the base field (i.e, its non-base components are constant zeroes) you can just return the real part's repr. I'll add a comment.
___
*[`crates/prover/src/constraint_framework/expr.rs` line 580 at r2](https://reviewable.io/reviews/starkware-libs/stwo/903#-OCmaJG19X01Eji4zHMa:-OCnK_jrEkm0m8DPSyHL:b-yrkr63) ([raw file](https://github.com/starkware-libs/stwo/blob/409513463053d7dfbb0ca6a3ce6a39b60d699b83/crates/prover/src/constraint_framework/expr.rs#L580)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

What would fail if this is ExtExpr (the secure column things)?
</blockquote></details>

There would be no non-hacky way to implement `EvalAtRow::combine_ef`.
___
*[`crates/prover/src/constraint_framework/expr.rs` line 665 at r2](https://reviewable.io/reviews/starkware-libs/stwo/903#-OCmaE2122X4cgGtPj5J:-OCnKsxI8Q4zukbJKJVq:b-3s4sk6) ([raw file](https://github.com/starkware-libs/stwo/blob/409513463053d7dfbb0ca6a3ce6a39b60d699b83/crates/prover/src/constraint_framework/expr.rs#L665)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

this is not extension field
</blockquote></details>

It has to be, because you subtract it from an extension field expression, I'd prefer if it didn't show the `i`, but that's in QM31's Display.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/903)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @Alon-Ti)

___
*[`crates/prover/src/constraint_framework/expr.rs` line 163 at r2](https://reviewable.io/reviews/starkware-libs/stwo/903#-OCm_CfU3uCq6vr3wQpC:-OD14NH6Bo0pqLWhU_D_:b-aglslu) ([raw file](https://github.com/starkware-libs/stwo/blob/409513463053d7dfbb0ca6a3ce6a39b60d699b83/crates/prover/src/constraint_framework/expr.rs#L163)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

If you have a `SecureCol` that's actually constantly in the base field (i.e, its non-base components are constant zeroes) you can just return the real part's repr. I'll add a comment.
</blockquote></details>

where's the comment? :)

**Review by Alon-Ti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/903)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/expr.rs` line 163 at r2](https://reviewable.io/reviews/starkware-libs/stwo/903#-OCm_CfU3uCq6vr3wQpC:-OD16hyB4NZnEJeyOdjL:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/409513463053d7dfbb0ca6a3ce6a39b60d699b83/crates/prover/src/constraint_framework/expr.rs#L163)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

where's the comment? :)
</blockquote></details>

Done.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/903#-:-OD1QiExDlByoBaQFs_C:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Alon-Ti)

___
*[`crates/prover/src/constraint_framework/expr.rs` line 665 at r2](https://reviewable.io/reviews/starkware-libs/stwo/903#-OCmaE2122X4cgGtPj5J:-OD1QY3s61_r587-GUM3:b9wcw7n) ([raw file](https://github.com/starkware-libs/stwo/blob/409513463053d7dfbb0ca6a3ce6a39b60d699b83/crates/prover/src/constraint_framework/expr.rs#L665)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

It has to be, because you subtract it from an extension field expression, I'd prefer if it didn't show the `i`, but that's in QM31's Display.
</blockquote></details>

should we test it with such element?

**Comment by Alon-Ti** [comment]
### Merge activity

* **Dec 1, 8:48 AM EST**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/903).

**Pull request merged**
