### PR TITLE
Modify FFT implementation for SIMD backend

### PR DESCRIPTION
**Pull request by andrewmilson**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/596)

### CODE REVIEW

**Comment by andrewmilson** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/596?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#596** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/596?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#595** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/595?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#594** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/594?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#593** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/593?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#592** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/592?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#591** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/591?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @andrewmilson and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/596)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @andrewmilson)

*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo/596#-NwsDLYoDdwUZpWDG_kn:-NwsDLYoDdwUZpWDG_ko:b-h5sqym) (no related file):*
It would be easier to check this Pr if you first add a commit that only copies the old files, so we can see in Reviewable just what changed.

___

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/596)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo/596#-NwsDLYoDdwUZpWDG_kn:-NwvuLF92TjC_OU7Llzd:bs7wumx) (no related file):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

It would be easier to check this Pr if you first add a commit that only copies the old files, so we can see in Reviewable just what changed.
</blockquote></details>

Done. 

___

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 4 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/596#-:-Ny0N_kp9QkNLw0aXO3c:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @andrewmilson)

___
*[`crates/prover/src/core/backend/simd/fft/mod.rs` line 40 at r4](https://reviewable.io/reviews/starkware-libs/stwo/596#-Ny0MzclDL1PiDa0IQ5k:-Ny0MzclDL1PiDa0IQ5l:bnl5zxk) ([raw file](https://github.com/starkware-libs/stwo/blob/2d7343646f1c00f092f6eebf3366f6b6db9bb1bd/crates/prover/src/core/backend/simd/fft/mod.rs#L40)):*
> ```XML
>                     continue;
>                 }
>                 let val0 = load(values.add(i << 4).cast_const());
> ```

Consider inlining load() and store()
___
*[`crates/prover/src/core/backend/simd/fft/rfft.rs` line 343 at r4](https://reviewable.io/reviews/starkware-libs/stwo/596#-Ny0NGP-79eAMhIDJ48Z:-Ny0NGP-79eAMhIDJ48_:b17lb14) ([raw file](https://github.com/starkware-libs/stwo/blob/2d7343646f1c00f092f6eebf3366f6b6db9bb1bd/crates/prover/src/core/backend/simd/fft/rfft.rs#L343)):*
> ```XML
> /// unreduced form, [0, P] including P. twiddle_dbl holds 16 values, each is a *double* of a twiddle
> /// factor, in unreduced form, [0, 2*P].
> pub fn butterfly(
> ```

butterfly() is a generic function that exists already, I want to not confuse them



_Suggestion:_
```XML
simd_butterfly
```

**Pull request merged**
