### PR TITLE
Test docs in CI

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/539)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
* **#539** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/539?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by andrewmilson — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/539)* status: 1 of 9 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`src/core/fri.rs` line 93 at r1](https://reviewable.io/reviews/starkware-libs/stwo/539#-NttBdueEsDrjETFyRCO:-NttBdueEsDrjETFyRCP:b4ytp1f) ([raw file](https://github.com/starkware-libs/stwo/blob/44fe5221589a5891243adc22fad06bdd80c8a6f2/src/core/fri.rs#L93)):*
> ```XML
>     ///
>     /// Let `src` be the evaluation of a circle polynomial `f` on a
>     /// [super::poly::circle::CircleDomain] `E`. This function computes evaluations of `f' = f0
> ```

Can the links be specified at the bottom of the docs

```

/// ... [`CircleDomain`] ...
/// ...
/// 
/// [`CircleDomain`]: super::poly::circle::CircleDomain
```
___
*[`src/core/commitment_scheme/utils.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/stwo/539#-NttBw5X1W-v-DhJRQYT:-NttBw5X1W-v-DhJRQYU:bq0wh99) ([raw file](https://github.com/starkware-libs/stwo/blob/44fe5221589a5891243adc22fad06bdd80c8a6f2/src/core/commitment_scheme/utils.rs#L79)):*
> ```XML
>         TreeVec(self.iter().map(|column| column.iter().collect()).collect())
>     }
>     /// Flattens the [`TreeVec<ColumVec<T>>`] into a single [ColumnVec] with all the columns
> ```

Perhaps we should do this for all type links



_Suggestion:_
```XML
[`ColumnVec`]
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/539)* status: 1 of 9 files reviewed, 2 unresolved discussions (waiting on @andrewmilson)

___
*[`src/core/fri.rs` line 93 at r1](https://reviewable.io/reviews/starkware-libs/stwo/539#-NttBdueEsDrjETFyRCO:-NttPCQ62GBYVspbg5hC:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/44fe5221589a5891243adc22fad06bdd80c8a6f2/src/core/fri.rs#L93)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Can the links be specified at the bottom of the docs

```

/// ... [`CircleDomain`] ...
/// ...
/// 
/// [`CircleDomain`]: super::poly::circle::CircleDomain
```
</blockquote></details>

Done.
___
*[`src/core/commitment_scheme/utils.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/stwo/539#-NttBw5X1W-v-DhJRQYT:-NttPKoN2bT3_UgoTPwq:b-hb7v68) ([raw file](https://github.com/starkware-libs/stwo/blob/44fe5221589a5891243adc22fad06bdd80c8a6f2/src/core/commitment_scheme/utils.rs#L79)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Perhaps we should do this for all type links
</blockquote></details>

I'll do it on all new ones

**Review by andrewmilson — APPROVED** [review]
:lgtm:

> Reviewed 5 of 9 files at r1, 4 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/539#-:-Nttcr6XBc5zIUZf8U5d:bnfp4nl)* status: 10 of 11 files reviewed, all discussions resolved

**Pull request merged**
