### PR TITLE
Add FFT implementation for SIMD backend

### PR DESCRIPTION
**Pull request by andrewmilson**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/602)

### CODE REVIEW

**Comment by andrewmilson** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/602?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#599** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/599?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#596** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/596?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#602** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/602?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#595** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/595?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#601** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/601?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#594** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/594?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#600** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/600?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#593** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/593?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#592** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/592?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#591** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/591?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @andrewmilson and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/602)* status: 1 of 4 files reviewed, 8 unresolved discussions (waiting on @andrewmilson)

___
*[`crates/prover/src/core/backend/simd/fft/ifft.rs` line 156 at r2](https://reviewable.io/reviews/starkware-libs/stwo/602#-NxRC60WEHRv2YeFgVoW:-NxRC60WEHRv2YeFgVoX:b-d5cbv3) ([raw file](https://github.com/starkware-libs/stwo/blob/4979fb3efac71bd99bb8f3a3f85fba130ad063f0/crates/prover/src/core/backend/simd/fft/ifft.rs#L156)):*
> ```XML
>     for index_l in 0..(1 << loop_bits) {
>         let index = (index_h << loop_bits) + index_l;
>         let mut val0 = PackedBaseField::load(values.add(index * 32).cast_const() as *const u32);
> ```

Perhaps it's better to change the type to u32 in the callers as well?
I see there's a lot of "as" casting here, which we probably want to avoid if possible.
___
*[`crates/prover/src/core/backend/simd/fft/ifft.rs` line 291 at r2](https://reviewable.io/reviews/starkware-libs/stwo/602#-NxRCfks0JutPxCPVsYR:-NxRCfks0JutPxCPVsYS:b-7cbin5) ([raw file](https://github.com/starkware-libs/stwo/blob/4979fb3efac71bd99bb8f3a3f85fba130ad063f0/crates/prover/src/core/backend/simd/fft/ifft.rs#L291)):*
> ```XML
>                 super::_mul_twiddle_simd(r1, twiddle_dbl)
>             }
>         }
> ```

Can you extract this block to a function mul_twiddle?



_Code quote:_
```XML
        cfg_if::cfg_if! {
            if #[cfg(all(target_feature = "neon", target_arch = "aarch64"))] {
                super::_mul_twiddle_neon(r1, twiddle_dbl)
            } else if #[cfg(all(target_feature = "simd128", target_arch = "wasm32"))] {
                super::_mul_twiddle_wasm(r1, twiddle_dbl)
            } else if #[cfg(all(target_arch = "x86_64", target_feature = "avx512f"))] {
                super::_mul_twiddle_avx512(r1, twiddle_dbl)
            } else if #[cfg(all(target_arch = "x86_64", target_feature = "avx2f"))] {
                super::_mul_twiddle_avx2(r1, twiddle_dbl)
            } else {
                super::_mul_twiddle_simd(r1, twiddle_dbl)
            }
        }
```
___
*[`crates/prover/src/core/backend/simd/fft/ifft.rs` line 346 at r2](https://reviewable.io/reviews/starkware-libs/stwo/602#-NxRCmhu5PPDLm99XKOe:-NxRCmhu5PPDLm99XKOf:b-r6s7x5) ([raw file](https://github.com/starkware-libs/stwo/blob/4979fb3efac71bd99bb8f3a3f85fba130ad063f0/crates/prover/src/core/backend/simd/fft/ifft.rs#L346)):*
> ```XML
> 
>     // The twiddles for layer 2 are replicated in the following pattern:
>     //   0 1 2 3 0 1 2 3 0 1 2 3 0 1 2 3
> ```

The explicit number below make this comment redundant. Remove it.
___
*[`crates/prover/src/core/backend/simd/fft/mod.rs` line 65 at r2](https://reviewable.io/reviews/starkware-libs/stwo/602#-NxRDUzM1D_fSuq7lhUH:-NxRDUzN6Zl0DLrQeSmV:b4y4cjl) ([raw file](https://github.com/starkware-libs/stwo/blob/4979fb3efac71bd99bb8f3a3f85fba130ad063f0/crates/prover/src/core/backend/simd/fft/mod.rs#L65)):*
> ```XML
> }
> 
> unsafe fn _mm512_load_epi32(mem_addr: *const i32) -> u32x16 {
> ```

I think this name should change, as it is a specific intel intrinsic. Perhaps just inline it?



_Code quote:_
```XML
_mm512_load_epi32
```
___
*[`crates/prover/src/core/backend/simd/fft/mod.rs` line 79 at r2](https://reviewable.io/reviews/starkware-libs/stwo/602#-NxRDbzD8ebdctNPgpwi:-NxRDbzD8ebdctNPgpwj:bwig45) ([raw file](https://github.com/starkware-libs/stwo/blob/4979fb3efac71bd99bb8f3a3f85fba130ad063f0/crates/prover/src/core/backend/simd/fft/mod.rs#L79)):*
> ```XML
>     // Start by loading the twiddles for the second layer (layer 1):
>     // The twiddles for layer 1 are replicated in the following pattern:
>     //   0 1 2 3 4 5 6 7 0 1 2 3 4 5 6 7
> ```

Same here. Remove line.
___
*[`crates/prover/src/core/backend/simd/fft/mod.rs` line 117 at r2](https://reviewable.io/reviews/starkware-libs/stwo/602#-NxRDpTEAy4Wapc4H0IW:-NxRDpTEAy4Wapc4H0IX:boscys9) ([raw file](https://github.com/starkware-libs/stwo/blob/4979fb3efac71bd99bb8f3a3f85fba130ad063f0/crates/prover/src/core/backend/simd/fft/mod.rs#L117)):*
> ```XML
>         ]))
>     };
>     let t0 = IndicesFromT1::swizzle(t1) ^ NEGATION_MASK;
> ```

why simd_swizzle! doesnt work here?
___
*[`crates/prover/src/core/backend/simd/fft/mod.rs` line 122 at r2](https://reviewable.io/reviews/starkware-libs/stwo/602#-NxRDxwD1Q57a96Omo6Z:-NxRDxwD1Q57a96Omo6_:b-8bunfe) ([raw file](https://github.com/starkware-libs/stwo/blob/4979fb3efac71bd99bb8f3a3f85fba130ad063f0/crates/prover/src/core/backend/simd/fft/mod.rs#L122)):*
> ```XML
> 
> #[cfg(target_arch = "aarch64")]
> fn _mul_twiddle_neon(a: PackedBaseField, twiddle_dbl: u32x16) -> PackedBaseField {
> ```

I don't think we should implement these again.
For architectures that in regular mul, need to double one argument, they should be refactored and the part after doubling extracted.
For other architectures, there's no need to save the twiddle as soubled at all. This was just done to save ops.
___
*[`crates/prover/src/core/backend/simd/fft/rfft.rs` line 312 at r2](https://reviewable.io/reviews/starkware-libs/stwo/602#-NxREMj46tkN769U5rp1:-NxREMj46tkN769U5rp2:bb73xfv) ([raw file](https://github.com/starkware-libs/stwo/blob/4979fb3efac71bd99bb8f3a3f85fba130ad063f0/crates/prover/src/core/backend/simd/fft/rfft.rs#L312)):*
> ```XML
>     twiddle_dbl: u32x16,
> ) -> (PackedBaseField, PackedBaseField) {
>     let prod = {
> ```

Same

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/602)* status: 1 of 4 files reviewed, 8 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/fft/ifft.rs` line 156 at r2](https://reviewable.io/reviews/starkware-libs/stwo/602#-NxRC60WEHRv2YeFgVoW:-NxU26bn4W6OuEOqKMx8:b771c9n) ([raw file](https://github.com/starkware-libs/stwo/blob/4979fb3efac71bd99bb8f3a3f85fba130ad063f0/crates/prover/src/core/backend/simd/fft/ifft.rs#L156)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Perhaps it's better to change the type to u32 in the callers as well?
I see there's a lot of "as" casting here, which we probably want to avoid if possible.
</blockquote></details>

These are changed in the next PR.
https://reviewable.io/reviews/starkware-libs/stwo/596
___
*[`crates/prover/src/core/backend/simd/fft/ifft.rs` line 291 at r2](https://reviewable.io/reviews/starkware-libs/stwo/602#-NxRCfks0JutPxCPVsYR:-NxZFuv2B38cuSN22UNa:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/4979fb3efac71bd99bb8f3a3f85fba130ad063f0/crates/prover/src/core/backend/simd/fft/ifft.rs#L291)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Can you extract this block to a function mul_twiddle?
</blockquote></details>

Done.
___
*[`crates/prover/src/core/backend/simd/fft/ifft.rs` line 346 at r2](https://reviewable.io/reviews/starkware-libs/stwo/602#-NxRCmhu5PPDLm99XKOe:-NxZKkKKAAeoPj1G7Xa6:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/4979fb3efac71bd99bb8f3a3f85fba130ad063f0/crates/prover/src/core/backend/simd/fft/ifft.rs#L346)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

The explicit number below make this comment redundant. Remove it.
</blockquote></details>

Done.
___
*[`crates/prover/src/core/backend/simd/fft/mod.rs` line 65 at r2](https://reviewable.io/reviews/starkware-libs/stwo/602#-NxRDUzM1D_fSuq7lhUH:-NxSol6Y8Q1oh_rLWSiE:brh11ei) ([raw file](https://github.com/starkware-libs/stwo/blob/4979fb3efac71bd99bb8f3a3f85fba130ad063f0/crates/prover/src/core/backend/simd/fft/mod.rs#L65)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I think this name should change, as it is a specific intel intrinsic. Perhaps just inline it?
</blockquote></details>

renamed in the next PR https://reviewable.io/reviews/starkware-libs/stwo/596
___
*[`crates/prover/src/core/backend/simd/fft/mod.rs` line 117 at r2](https://reviewable.io/reviews/starkware-libs/stwo/602#-NxRDpTEAy4Wapc4H0IW:-NxU2N4R8LXZYpXkSZLJ:b-bw8e14) ([raw file](https://github.com/starkware-libs/stwo/blob/4979fb3efac71bd99bb8f3a3f85fba130ad063f0/crates/prover/src/core/backend/simd/fft/mod.rs#L117)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

why simd_swizzle! doesnt work here?
</blockquote></details>

Updated.
___
*[`crates/prover/src/core/backend/simd/fft/mod.rs` line 122 at r2](https://reviewable.io/reviews/starkware-libs/stwo/602#-NxRDxwD1Q57a96Omo6Z:-NxZID6I-oG1ozNttFdK:b-w8gmcb) ([raw file](https://github.com/starkware-libs/stwo/blob/4979fb3efac71bd99bb8f3a3f85fba130ad063f0/crates/prover/src/core/backend/simd/fft/mod.rs#L122)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I don't think we should implement these again.
For architectures that in regular mul, need to double one argument, they should be refactored and the part after doubling extracted.
For other architectures, there's no need to save the twiddle as soubled at all. This was just done to save ops.
</blockquote></details>

Extracting the mul part after the doubling has removed a lot of the code duplication but WDYT about keeping the twiddles double for all platforms at the moment? Pros: All docs and naming is already for double twiddles, No performance cost to any platform leaving as is. Cons: we have two very similar looking mul implementations for Neon (as AFAIK this is the only architechture that has the doubling mul instruction).
___
*[`crates/prover/src/core/backend/simd/fft/rfft.rs` line 312 at r2](https://reviewable.io/reviews/starkware-libs/stwo/602#-NxREMj46tkN769U5rp1:-NxZKw7F8OWCvi-m1keF:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/4979fb3efac71bd99bb8f3a3f85fba130ad063f0/crates/prover/src/core/backend/simd/fft/rfft.rs#L312)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Same
</blockquote></details>

Done.

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/602)* status: 1 of 4 files reviewed, 8 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/fft/mod.rs` line 79 at r2](https://reviewable.io/reviews/starkware-libs/stwo/602#-NxRDbzD8ebdctNPgpwi:-NxZL5oX1m6ygNkSEVEM:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/4979fb3efac71bd99bb8f3a3f85fba130ad063f0/crates/prover/src/core/backend/simd/fft/mod.rs#L79)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Same here. Remove line.
</blockquote></details>

Done.

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/602)* status: 0 of 5 files reviewed, 8 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/fft/mod.rs` line 122 at r2](https://reviewable.io/reviews/starkware-libs/stwo/602#-NxRDxwD1Q57a96Omo6Z:-NxzHZg92jS-AueAINkX:b-unsmlk) ([raw file](https://github.com/starkware-libs/stwo/blob/4979fb3efac71bd99bb8f3a3f85fba130ad063f0/crates/prover/src/core/backend/simd/fft/mod.rs#L122)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Extracting the mul part after the doubling has removed a lot of the code duplication but WDYT about keeping the twiddles double for all platforms at the moment? Pros: All docs and naming is already for double twiddles, No performance cost to any platform leaving as is. Cons: we have two very similar looking mul implementations for Neon (as AFAIK this is the only architechture that has the doubling mul instruction).
</blockquote></details>

Added as a TODO. Will follow up in another PR.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r1, 1 of 4 files at r5, 1 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/602#-:-Ny-YdZXEYVVBegPf7Dw:bnfp4nl)* status: 2 of 5 files reviewed, all discussions resolved

**Pull request merged**
