### PR TITLE
Expression Evaluator.

### PR DESCRIPTION
**Pull request by Alon-Ti**

### CODE REVIEW

**Comment by Alon-Ti** [comment]
* **#861** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/861?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Alon-Ti and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by andrewmilson — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/861#-:-O9eiGxA7ezXAoeVUw8c:bnfp4nl)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @Alon-Ti)

___
*[`crates/prover/src/constraint_framework/expr.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/stwo/861#-O9egGnQ-3HRN6FogWDW:-O9egGnQ-3HRN6FogWDX:bxel4g4) ([raw file](https://github.com/starkware-libs/stwo/blob/1161cc1d3bd2b63f64b7caf55aeedbb6392742d8/crates/prover/src/constraint_framework/expr.rs#L25)):*
> ```XML
>     // if a = SecureCol(a0, a1, a2, a3), b = SecureCol(b0, b1, b2, b3) then
>     // a + b evaluates to Add(a, b) rather than
>     // SecureCol(Add(a0, b0), Add(a1, b1), Add(a2, b2), Add(a3, b3))
> ```

Docstring



_Suggestion:_
```XML
    Col(ColumnExpr),
    /// An atomic secure column constructed from 4 expressions.
    /// Expressions on the secure column are not reduced, i.e,
    /// if `a = SecureCol(a0, a1, a2, a3), b = SecureCol(b0, b1, b2, b3)` then
    /// `a + b` evaluates to `Add(a, b)` rather than
    /// `SecureCol(Add(a0, b0), Add(a1, b1), Add(a2, b2), Add(a3, b3))`
```
___
*[`crates/prover/src/constraint_framework/expr.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/stwo/861#-O9ehJDI7q6CQODU0hpH:-O9ehJDI7q6CQODU0hpI:b-a02lq9) ([raw file](https://github.com/starkware-libs/stwo/blob/1161cc1d3bd2b63f64b7caf55aeedbb6392742d8/crates/prover/src/constraint_framework/expr.rs#L83)):*
> ```XML
>         *self = Expr::Mul(Box::new(self.clone()), Box::new(rhs));
>     }
> }
> ```

Optional suggestion



_Suggestion:_
```XML
impl AddAssign for Expr {
    fn add_assign(&mut self, rhs: Self) {
        *self = self.clone() + rhs;
    }
}

impl MulAssign for Expr {
    fn mul_assign(&mut self, rhs: Self) {
        *self = self.clone() * rhs;
    }
}
```

**Review by Alon-Ti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/861)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @andrewmilson)

___
*[`crates/prover/src/constraint_framework/expr.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/stwo/861#-O9egGnQ-3HRN6FogWDW:-O9ejBeq2rLQUT8R0UbC:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/1161cc1d3bd2b63f64b7caf55aeedbb6392742d8/crates/prover/src/constraint_framework/expr.rs#L25)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Docstring
</blockquote></details>

Done.
___
*[`crates/prover/src/constraint_framework/expr.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/stwo/861#-O9ehJDI7q6CQODU0hpH:-O9ejCkHBN1_1CgkC2Tj:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/1161cc1d3bd2b63f64b7caf55aeedbb6392742d8/crates/prover/src/constraint_framework/expr.rs#L83)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Optional suggestion
</blockquote></details>

Done.

**Comment by Alon-Ti** [comment]
### Merge activity

* **Oct 20, 12:26 PM EDT**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/861).

**Pull request merged**
