### PR TITLE
avx slow eval

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/398)

### CODE REVIEW

**Review by ohad-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/398)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`src/core/backend/avx512/circle.rs` line 75 at r2](https://reviewable.io/reviews/starkware-libs/stwo/398#-NsObfeS9GUs4AnEI7FU:-NsObfeTDL2arrkdcgF_:b-eq1rcm) ([raw file](https://github.com/starkware-libs/stwo/blob/0182bdb3132cd0ebaac21e84505f99c430796f50/src/core/backend/avx512/circle.rs#L75)):*
> ```XML
>         let n = mappings.len();
>         let n0 = (n - VECS_LOG_SIZE) / 2;
>         let n1 = (n - VECS_LOG_SIZE + 1) / 2;
> ```

these only need to be evaluated if the predicate below is true, move below?



_Code quote:_
```XML
        let n = mappings.len();
        let n0 = (n - VECS_LOG_SIZE) / 2;
        let n1 = (n - VECS_LOG_SIZE + 1) / 2;
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/398)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @ohad-starkware)

___
*[`src/core/backend/avx512/circle.rs` line 75 at r2](https://reviewable.io/reviews/starkware-libs/stwo/398#-NsObfeS9GUs4AnEI7FU:-NslCuYb1OVf4Z9WiOkC:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/0182bdb3132cd0ebaac21e84505f99c430796f50/src/core/backend/avx512/circle.rs#L75)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

these only need to be evaluated if the predicate below is true, move below?
</blockquote></details>

Done.

**Review by ohad-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/398)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`src/core/backend/avx512/circle.rs` line 87 at r4](https://reviewable.io/reviews/starkware-libs/stwo/398#-NslFNQ_A2DC2Yi5ymZj:-NslFNQa7gHAIoaB9X0R:bqadre1) ([raw file](https://github.com/starkware-libs/stwo/blob/aff7ab8c43b756e4edbd0009fd84643422699f34/src/core/backend/avx512/circle.rs#L87)):*
> ```XML
>     }
> 
>     fn extend(poly: &CirclePoly<Self, BaseField>, log_size: u32) -> CirclePoly<Self, BaseField> {
> ```

this change shouldnt be here right>

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/398)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @ohad-starkware)

___
*[`src/core/backend/avx512/circle.rs` line 87 at r4](https://reviewable.io/reviews/starkware-libs/stwo/398#-NslFNQ_A2DC2Yi5ymZj:-NslJ6oGDUU2zacvWkrv:be96pz9) ([raw file](https://github.com/starkware-libs/stwo/blob/aff7ab8c43b756e4edbd0009fd84643422699f34/src/core/backend/avx512/circle.rs#L87)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

this change shouldnt be here right>
</blockquote></details>

It's not here. It's from the rebase (you can see the "perpendicular" symbols on the left)

**Review by ohad-starkware — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/398#-:-NsqfMXHDeKeVyVaeID9:bg7igkv)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

___
*[`src/core/backend/avx512/circle.rs` line 87 at r4](https://reviewable.io/reviews/starkware-libs/stwo/398#-NslFNQ_A2DC2Yi5ymZj:-NsqfGs54r9GupiKIWl2:bc0v0ip) ([raw file](https://github.com/starkware-libs/stwo/blob/68c1de699715b5e0be008c52688cc4ef2ba720e0/src/core/backend/avx512/circle.rs#L87)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

It's not here. It's from the rebase (you can see the "perpendicular" symbols on the left)
</blockquote></details>

it showed up green before, dsimissing.

**Pull request merged**
