### PR TITLE
Air is AirTraceVerifier.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/671)

### CODE REVIEW

**Comment by alonh5** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/671?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#671** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/671?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#669** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/669?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#667** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/667?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#664** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/664?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#662** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/662?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#646** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/646?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#644** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/644?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#654](https://github.com/starkware-libs/stwo/pull/654) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/654?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#642** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/642?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#639** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/639?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#638** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/638?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#637** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/637?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#636** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/636?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#651** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/651?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/671)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @alonh5)

*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo/671#-O0sVhqB3cZlpXFAQ7pp:-O0sVhqC39USME6JxuJi:b5b29ct) (no related file):*
Why do we need this pr?
Isn't it ok for those to be separated?

___

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/671)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo/671#-O0sVhqB3cZlpXFAQ7pp:-O0sXxqdCy-LB9gOi2nZ:b-wqzjyz) (no related file):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why do we need this pr?
Isn't it ok for those to be separated?
</blockquote></details>

It's just moving the bound from the verify function to the Air trait. Logically an Air should also be an AirTraceVerifier.

___

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/671)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @alonh5)

*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo/671#-O0sVhqB3cZlpXFAQ7pp:-O0sgGmrERC-Ivjaelnp:b-ovkln6) (no related file):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

It's just moving the bound from the verify function to the Air trait. Logically an Air should also be an AirTraceVerifier.
</blockquote></details>

I understand, but we talked about maybe the verifier won't have to communicate the interaction_values
with ids.
I suggest to leave it as is for now

___

**Pull request closed without merging**
