### PR TITLE
Implement FieldOps for SIMD backend

### PR DESCRIPTION
**Pull request by andrewmilson**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/593)

### CODE REVIEW

**Comment by andrewmilson** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/593?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#596** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/596?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#595** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/595?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#594** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/594?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#593** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/593?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#592** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/592?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#591** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/591?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @andrewmilson and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/593)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @andrewmilson)

___
*[`crates/prover/src/core/backend/simd/column.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/stwo/593#-Nwn09elD9xmOf5VUtF0:-Nwn09elD9xmOf5VUtF1:brrl5vb) ([raw file](https://github.com/starkware-libs/stwo/blob/9bd0fc44239cc0b9bf9e1bc17208cb13fa021ae1/crates/prover/src/core/backend/simd/column.rs#L15)):*
> ```XML
>     pub data: Vec<PackedBaseField>,
>     pub length: usize,
> }
> ```

We already have this struct in avx512.
Can't we reuse it?



_Code quote:_
```XML
#[derive(Clone, Debug)]
pub struct BaseFieldVec {
    pub data: Vec<PackedBaseField>,
    pub length: usize,
}
```

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/593)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`crates/prover/src/core/backend/simd/column.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/stwo/593#-Nwn09elD9xmOf5VUtF0:-NwoduOh8dhJrWJqN2Ji:b2mncie) ([raw file](https://github.com/starkware-libs/stwo/blob/9bd0fc44239cc0b9bf9e1bc17208cb13fa021ae1/crates/prover/src/core/backend/simd/column.rs#L15)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

We already have this struct in avx512.
Can't we reuse it?
</blockquote></details>

Resolved offline. 
`avx512` is conditionally compiled for x86.

**Review by spapinistarkware — COMMENTED** [review]
Like I said in rpevious PRs, it would be a lot easier to cehck these PRs if you first copied the avx file in a separate commit. Then we can just check the changes.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/593#-:-NxBaHA28cbYi20s21Oh:b-mbztu9)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/593)* status: all files reviewed, 2 unresolved discussions (waiting on @andrewmilson)

___
*[`crates/prover/src/core/backend/simd/column.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/stwo/593#-NxHsA440sAONXwOebYy:-NxHsA440sAONXwOebYz:bzcwwii) ([raw file](https://github.com/starkware-libs/stwo/blob/9509a53b6843f54f9d682779f5ac00982b52803d/crates/prover/src/core/backend/simd/column.rs#L27)):*
> ```XML
>         &mut cast_slice_mut(&mut self.data)[..self.length]
>     }
> }
> ```

We used to have as_slice, as_mut_slice. Is that ok?



_Code quote:_
```XML
impl AsRef<[BaseField]> for BaseFieldVec {
    fn as_ref(&self) -> &[BaseField] {
        &cast_slice(&self.data)[..self.length]
    }
}

impl AsMut<[BaseField]> for BaseFieldVec {
    fn as_mut(&mut self) -> &mut [BaseField] {
        &mut cast_slice_mut(&mut self.data)[..self.length]
    }
}
```
___
*[`crates/prover/src/core/backend/simd/mod.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/stwo/593#-NxHt35l8sEZhGicTrhf:-NxHt35m8O5rdbIeoLcp:b-sjiffs) ([raw file](https://github.com/starkware-libs/stwo/blob/9509a53b6843f54f9d682779f5ac00982b52803d/crates/prover/src/core/backend/simd/mod.rs#L24)):*
> ```XML
>         todo!()
>     }
> }
> ```

Why here and not in column.rs?



_Code quote:_
```XML
impl ColumnOps<BaseField> for SimdBackend {
    type Column = BaseFieldVec;

    fn bit_reverse_column(_column: &mut Self::Column) {
        todo!()
    }
}
```

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/593)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/prover/src/core/backend/simd/column.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/stwo/593#-NxHsA440sAONXwOebYy:-NxJ_MMp9nE7_ZwiAaXW:b1lfbek) ([raw file](https://github.com/starkware-libs/stwo/blob/9509a53b6843f54f9d682779f5ac00982b52803d/crates/prover/src/core/backend/simd/column.rs#L27)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

We used to have as_slice, as_mut_slice. Is that ok?
</blockquote></details>

Yeah, it's better. Updated
___
*[`crates/prover/src/core/backend/simd/mod.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/stwo/593#-NxHt35l8sEZhGicTrhf:-NxJ_TwUDZZl_AYFhQVt:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/9509a53b6843f54f9d682779f5ac00982b52803d/crates/prover/src/core/backend/simd/mod.rs#L24)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why here and not in column.rs?
</blockquote></details>

Done.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/593#-:-NxM1YCz0jGuXHHFnNb_:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @andrewmilson)

**Pull request merged**
