### PR TITLE
par trace

### PR DESCRIPTION
**Pull request by ohad-agadi**

### CODE REVIEW

**Comment by ohad-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/943?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#943** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/943?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/943?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#942** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/942?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/air_utils/src/trace/iterable_trace.rs` line 96 at r2](https://reviewable.io/reviews/starkware-libs/stwo/943#-OErxZI0D18oQh7Ujzh2:-OErxZI1ARssNy2080LA:b-b3z1yv) ([raw file](https://github.com/starkware-libs/stwo/blob/4f9b216daca68f0ef844e7b71a7563d9745ed98a/crates/air_utils/src/trace/iterable_trace.rs#L96)):*
> ```XML
>             .collect_vec()
>             .try_into()
>             .unwrap();
> ```

array::from_fn



_Code quote:_
```XML
        let v = self
            .data
            .iter_mut()
            .map(|column| column.as_mut_slice())
            .collect_vec()
            .try_into()
            .unwrap();
```

**Comment by ohad-starkware** [comment]
*[`crates/air_utils/src/trace/iterable_trace.rs` line 96 at r2](https://reviewable.io/reviews/starkware-libs/stwo/943#-OErxZI0D18oQh7Ujzh2:-OEs42rK0rOAndM4EY4M:b-oejx30) ([raw file](https://github.com/starkware-libs/stwo/blob/4f9b216daca68f0ef844e7b71a7563d9745ed98a/crates/air_utils/src/trace/iterable_trace.rs#L96)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

array::from_fn
</blockquote></details>

let v = std::array::from_fn(|i| self.data[i].as_mut_slice());
____________________________- ^^^^^^^^^^^^^^^^^^^^^^^^^^^ returns a reference to a captured variable which escapes the closure body

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/943)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @ohad-starkware)

___
*[`crates/air_utils/src/trace/component_trace.rs` line 152 at r5](https://reviewable.io/reviews/starkware-libs/stwo/943#-OEt6ft40d7uhqmHOzZY:-OEt6ft40d7uhqmHOzZZ:bn6e5zn) ([raw file](https://github.com/starkware-libs/stwo/blob/f9a8c33bdeea709f23cd071c7c841420b632cf49/crates/air_utils/src/trace/component_trace.rs#L152)):*
> ```XML
> }
> impl<const N: usize> ExactSizeIterator for RowIterMut<'_, N> {}
> impl<const N: usize> DoubleEndedIterator for RowIterMut<'_, N> {
> ```

Can you move all the RowIterMut, ParRowIterMut code to another file?
row_iterator.rs?



_Code quote:_
```XML
impl<const N: usize> ExactSizeIterator for RowIterMut<'_, N> {}
impl<const N: usize> DoubleEndedIterator for RowIterMut<'_, N> {
```
___
*[`crates/air_utils/src/trace/component_trace.rs` line 194 at r5](https://reviewable.io/reviews/starkware-libs/stwo/943#-OEt8K6D0pfRK1CqsY6J:-OEt8K6D0pfRK1CqsY6K:b-rzehgi) ([raw file](https://github.com/starkware-libs/stwo/blob/f9a8c33bdeea709f23cd071c7c841420b632cf49/crates/air_utils/src/trace/component_trace.rs#L194)):*
> ```XML
> }
> 
> pub struct ParRowIterMut<'trace, const N: usize> {
> ```

Document and can you explain why we had to implement ParallelIterator ourselves?



_Code quote:_
```XML
pub struct ParRowIterMut<'trace, const N: usize> {
```
___
*[`crates/air_utils/src/trace/component_trace.rs` line 258 at r5](https://reviewable.io/reviews/starkware-libs/stwo/943#-OEt8dkIAlDLhC_FsTNJ:-OEt8dkIAlDLhC_FsTNK:b-o68qeq) ([raw file](https://github.com/starkware-libs/stwo/blob/f9a8c33bdeea709f23cd071c7c841420b632cf49/crates/air_utils/src/trace/component_trace.rs#L258)):*
> ```XML
>             .par_iter_mut()
>             .zip(arr.par_chunks(N_LANES))
>             .chunks(4)
> ```

what 4 stands for?
Can we have a constant with a name?



_Code quote:_
```XML
.chunks(4)
```

**Review by ohad-agadi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/943)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @shaharsamocha7)

___
*[`crates/air_utils/src/trace/component_trace.rs` line 152 at r5](https://reviewable.io/reviews/starkware-libs/stwo/943#-OEt6ft40d7uhqmHOzZY:-OEt91m--O22lgmrtql4:bh0awov) ([raw file](https://github.com/starkware-libs/stwo/blob/f9a8c33bdeea709f23cd071c7c841420b632cf49/crates/air_utils/src/trace/component_trace.rs#L152)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can you move all the RowIterMut, ParRowIterMut code to another file?
row_iterator.rs?
</blockquote></details>

I don't think it's a positive change
90% of the code is this, otherwise ComponentTrace is not very interesting
___
*[`crates/air_utils/src/trace/component_trace.rs` line 194 at r5](https://reviewable.io/reviews/starkware-libs/stwo/943#-OEt8K6D0pfRK1CqsY6J:-OEt9VojAce9Mh3RI1ix:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/f9a8c33bdeea709f23cd071c7c841420b632cf49/crates/air_utils/src/trace/component_trace.rs#L194)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Document and can you explain why we had to implement ParallelIterator ourselves?
</blockquote></details>

Done.
___
*[`crates/air_utils/src/trace/component_trace.rs` line 258 at r5](https://reviewable.io/reviews/starkware-libs/stwo/943#-OEt8dkIAlDLhC_FsTNJ:-OEt9XbjBamJkxA9Cuap:b-w0b3nx) ([raw file](https://github.com/starkware-libs/stwo/blob/f9a8c33bdeea709f23cd071c7c841420b632cf49/crates/air_utils/src/trace/component_trace.rs#L258)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

what 4 stands for?
Can we have a constant with a name?
</blockquote></details>

chunks does not have to appear here. nevertheless, I do only want people to interact with it in chunks.
for testing purposes I removed that, but see that the rustdoc does show .chunks
___
*[`crates/air_utils/src/trace/iterable_trace.rs` line 96 at r2](https://reviewable.io/reviews/starkware-libs/stwo/943#-OErxZI0D18oQh7Ujzh2:-OEt8awfABllbG5bqAxq:byl5hxo) ([raw file](https://github.com/starkware-libs/stwo/blob/4f9b216daca68f0ef844e7b71a7563d9745ed98a/crates/air_utils/src/trace/iterable_trace.rs#L96)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

let v = std::array::from_fn(|i| self.data[i].as_mut_slice());
____________________________- ^^^^^^^^^^^^^^^^^^^^^^^^^^^ returns a reference to a captured variable which escapes the closure body
</blockquote></details>

nvm found each_mut

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/943)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @ohad-starkware)

___
*[`crates/air_utils/src/trace/component_trace.rs` line 152 at r5](https://reviewable.io/reviews/starkware-libs/stwo/943#-OEt6ft40d7uhqmHOzZY:-OEtFYQM2gXpuTKJK7WF:b-f4x9ck) ([raw file](https://github.com/starkware-libs/stwo/blob/f9a8c33bdeea709f23cd071c7c841420b632cf49/crates/air_utils/src/trace/component_trace.rs#L152)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

I don't think it's a positive change
90% of the code is this, otherwise ComponentTrace is not very interesting
</blockquote></details>

For ComponentTrace I just want to know the following
1. Self API
2. Iterable over rows
3. Support parallezation

The inner impl of the iterators is not interesting in this file IMO
___
*[`crates/air_utils/src/trace/component_trace.rs` line 194 at r5](https://reviewable.io/reviews/starkware-libs/stwo/943#-OEt8K6D0pfRK1CqsY6J:-OEtGNla7-qdqPHIsars:b94l6zp) ([raw file](https://github.com/starkware-libs/stwo/blob/f9a8c33bdeea709f23cd071c7c841420b632cf49/crates/air_utils/src/trace/component_trace.rs#L194)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Consider to also state how the iteration works 
___
*[`crates/air_utils/src/trace/component_trace.rs` line 258 at r5](https://reviewable.io/reviews/starkware-libs/stwo/943#-OEt8dkIAlDLhC_FsTNJ:-OEtGdPKEo6myW7M0ZJU:b-uhl2ku) ([raw file](https://github.com/starkware-libs/stwo/blob/f9a8c33bdeea709f23cd071c7c841420b632cf49/crates/air_utils/src/trace/component_trace.rs#L258)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

chunks does not have to appear here. nevertheless, I do only want people to interact with it in chunks.
for testing purposes I removed that, but see that the rustdoc does show .chunks
</blockquote></details>

If you want ppl to use the chunks please add it to the test as this is the reference of how to use it.
but what is the optimal chunk size that one should use?

**Review by ohad-agadi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/943)* status: 3 of 6 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @shaharsamocha7)

___
*[`crates/air_utils/src/trace/component_trace.rs` line 152 at r5](https://reviewable.io/reviews/starkware-libs/stwo/943#-OEt6ft40d7uhqmHOzZY:-OEtpGjo8_nxXnX18BfM:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/f9a8c33bdeea709f23cd071c7c841420b632cf49/crates/air_utils/src/trace/component_trace.rs#L152)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

For ComponentTrace I just want to know the following
1. Self API
2. Iterable over rows
3. Support parallezation

The inner impl of the iterators is not interesting in this file IMO
</blockquote></details>

Done.
___
*[`crates/air_utils/src/trace/component_trace.rs` line 258 at r5](https://reviewable.io/reviews/starkware-libs/stwo/943#-OEt8dkIAlDLhC_FsTNJ:-OEtnydl17hhXj_x5lVw:b-g2feom) ([raw file](https://github.com/starkware-libs/stwo/blob/f9a8c33bdeea709f23cd071c7c841420b632cf49/crates/air_utils/src/trace/component_trace.rs#L258)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

If you want ppl to use the chunks please add it to the test as this is the reference of how to use it.
but what is the optimal chunk size that one should use?
</blockquote></details>

TBD, added a todo

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/943#-:-OEyRiSv5LVZl6kH6zpX:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

**Comment by ohad-starkware** [comment]
### Merge activity

* **Dec 25, 10:51 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/943).

**Pull request merged**
