### PR TITLE
ifft_lower

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/379)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`src/core/backend/avx512/fft.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/stwo/379#-Ns3TwGA2ztdUCV24ewW:-Ns3TwGA2ztdUCV24ewX:b-36m1ln) ([raw file](https://github.com/starkware-libs/stwo/blob/7ea6c558908d298f026a3dad8c6e1099ffda0a31/src/core/backend/avx512/fft.rs#L88)):*
> ```XML
>         ifft_vecwise_loop(values, twiddle_dbl, fft_layers - VECWISE_FFT_BITS, index_h);
>         for layer in (VECWISE_FFT_BITS..fft_layers).step_by(3) {
>             match fft_layers - layer {
> ```

do you need a match at every layer?

why not 
while fft_layers - layer > 3 {
    ..
}
match  fft_layers - layer



_Code quote:_
```XML
        for layer in (VECWISE_FFT_BITS..fft_layers).step_by(3) {
            match fft_layers - layer {
```

**Comment by ilyalesokhin-starkware** [comment]
*[`src/core/backend/avx512/fft.rs` line 109 at r1](https://reviewable.io/reviews/starkware-libs/stwo/379#-Ns3VAv-BGaI-UyNoflb:-Ns3VAv-BGaI-UyNoflc:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/7ea6c558908d298f026a3dad8c6e1099ffda0a31/src/core/backend/avx512/fft.rs#L109)):*
> ```XML
> }
> 
> /// Runs the 5 first ifft layers across the entire array.
> ```





_Suggestion:_
```XML
Runs the first 5 ifft layers across the entire array.
```

**Comment by ilyalesokhin-starkware** [comment]
*[`src/core/backend/avx512/fft.rs` line 112 at r1](https://reviewable.io/reviews/starkware-libs/stwo/379#-Ns3VNkt1zJFfpbbWxOS:-Ns3VNkt1zJFfpbbWxOT:b-o4rld2) ([raw file](https://github.com/starkware-libs/stwo/blob/7ea6c558908d298f026a3dad8c6e1099ffda0a31/src/core/backend/avx512/fft.rs#L112)):*
> ```XML
> /// Parameters:
> ///   values - Pointer to the entire value array, aligned to 64 bytes.
> ///   twiddle_dbl - The doubles of the twiddle factors for each of the 5 ifft layers.
> ```

don't you have some alignement requirements for the twiddle factors?



_Code quote:_
```XML
twiddle_dbl - The doubles of the twiddle factors for each of the 5 ifft layers
```

**Comment by ilyalesokhin-starkware** [comment]
*[`src/core/backend/avx512/fft.rs` line 161 at r1](https://reviewable.io/reviews/starkware-libs/stwo/379#-Ns3WPB4-Z9QO3x8ylVa:-Ns3WPB4-Z9QO3x8ylVb:b-nuxdk0) ([raw file](https://github.com/starkware-libs/stwo/blob/7ea6c558908d298f026a3dad8c6e1099ffda0a31/src/core/backend/avx512/fft.rs#L161)):*
> ```XML
> ) {
>     for m in 0..(1 << loop_bits) {
>         let index = (index_h << loop_bits) + m;
> ```

Make this consistent with `ifft_vecwise_loop`



_Suggestion:_
```XML
 let index = (index_h << loop_bits) + index_l;
```

**Comment by ilyalesokhin-starkware** [comment]
*[`src/core/backend/avx512/fft.rs` line 248 at r1](https://reviewable.io/reviews/starkware-libs/stwo/379#-Ns3WeAb2Gnx4GHhqpYC:-Ns3WeAb2Gnx4GHhqpYD:b3kre) ([raw file](https://github.com/starkware-libs/stwo/blob/7ea6c558908d298f026a3dad8c6e1099ffda0a31/src/core/backend/avx512/fft.rs#L248)):*
> ```XML
>     let r1 = sub_mod_p(val0, val1);
> 
>     // Extract the even and odd parts of r1 and twiddle_m_e_dbldbl, and spread as 8 64bit values.
> ```

?



_Code quote:_
```XML
twiddle_m_e_dbldb
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/379)* status: 1 of 4 files reviewed, 5 unresolved discussions (waiting on @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/379)* status: 1 of 4 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`src/core/backend/avx512/fft.rs` line 112 at r1](https://reviewable.io/reviews/starkware-libs/stwo/379#-Ns3VNkt1zJFfpbbWxOS:-Ns3_RF1CyiNm0Pxkz4h:b-cpf7ph) ([raw file](https://github.com/starkware-libs/stwo/blob/7ea6c558908d298f026a3dad8c6e1099ffda0a31/src/core/backend/avx512/fft.rs#L112)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

don't you have some alignement requirements for the twiddle factors?
</blockquote></details>

No. Perhaps this code could be a bit more efficient with the first and second twiddle layers, but I load them as values, withouth the efficient pointer loading (i.e. let rust deal with it).

Most fo the times I just ened to load a single M31, and broadcast it.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/379)* status: 3 of 4 files reviewed, 5 unresolved discussions

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/379)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`src/core/backend/avx512/fft.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/stwo/379#-Ns3TwGA2ztdUCV24ewW:-Ns3ye_O8By2ngBq3O-m:b-k9skuy) ([raw file](https://github.com/starkware-libs/stwo/blob/7ea6c558908d298f026a3dad8c6e1099ffda0a31/src/core/backend/avx512/fft.rs#L88)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

do you need a match at every layer?

why not 
while fft_layers - layer > 3 {
    ..
}
match  fft_layers - layer
</blockquote></details>

Why is this better?
___
*[`src/core/backend/avx512/fft.rs` line 109 at r1](https://reviewable.io/reviews/starkware-libs/stwo/379#-Ns3VAv-BGaI-UyNoflb:-Ns3yjoc1m_2NbUZ8S4h:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/7ea6c558908d298f026a3dad8c6e1099ffda0a31/src/core/backend/avx512/fft.rs#L109)):*
> ```XML
> }
> 
> /// Runs the 5 first ifft layers across the entire array.
> ```

Done.
___
*[`src/core/backend/avx512/fft.rs` line 161 at r1](https://reviewable.io/reviews/starkware-libs/stwo/379#-Ns3WPB4-Z9QO3x8ylVa:-Ns411HmEjQqaszJJKk9:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/7ea6c558908d298f026a3dad8c6e1099ffda0a31/src/core/backend/avx512/fft.rs#L161)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Make this consistent with `ifft_vecwise_loop`
</blockquote></details>

Done.
___
*[`src/core/backend/avx512/fft.rs` line 248 at r1](https://reviewable.io/reviews/starkware-libs/stwo/379#-Ns3WeAb2Gnx4GHhqpYC:-Ns3yuaW1Z267akGriAu:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/7ea6c558908d298f026a3dad8c6e1099ffda0a31/src/core/backend/avx512/fft.rs#L248)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.

**Comment by ilyalesokhin-starkware** [comment]
*[`src/core/backend/avx512/fft.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/stwo/379#-Ns3TwGA2ztdUCV24ewW:-Ns7Q7njC0C7VVPWpwJi:b-szjd5y) ([raw file](https://github.com/starkware-libs/stwo/blob/7ea6c558908d298f026a3dad8c6e1099ffda0a31/src/core/backend/avx512/fft.rs#L88)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Why is this better?
</blockquote></details>

it makes it clear that match happens only at the last layer both for the reader and the compiler

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/379)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`src/core/backend/avx512/fft.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/stwo/379#-Ns3TwGA2ztdUCV24ewW:-Ns7lr6f-jG5tnlIh3d9:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/7ea6c558908d298f026a3dad8c6e1099ffda0a31/src/core/backend/avx512/fft.rs#L88)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

it makes it clear that match happens only at the last layer both for the reader and the compiler
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/379#-:-Ns7nDYY-vqeNjVq4jdO:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
