### PR TITLE
Implement GkrOps for SIMD backend

### PR DESCRIPTION
**Pull request by andrewmilson**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/630)

### CODE REVIEW

**Comment by andrewmilson** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/630?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#630** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/630?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#629** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/629?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#623** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/623?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#620** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/620?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#621** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/621?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#581** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/581?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#617** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/617?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#616** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/616?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#615** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/615?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#614** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/614?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#613** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/613?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#612** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/612?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#611** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/611?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#610** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/610?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#609** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/609?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#608** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/608?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#607** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/607?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#606** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/606?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#605** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/605?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#604** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/604?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#603** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/603?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#599** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/599?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#596** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/596?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#602** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/602?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#595** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/595?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#601** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/601?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#594** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/594?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#600** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/600?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#593** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/593?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#592** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/592?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#591** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/591?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @andrewmilson and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 6 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/630#-:-O-f8cgID8eZD9FOBTsf:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @andrewmilson)

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/630)* status: all files reviewed, 3 unresolved discussions (waiting on @andrewmilson)

___
*[`crates/prover/src/core/backend/simd/lookups/gkr.rs` line 21 at r3](https://reviewable.io/reviews/starkware-libs/stwo/630#-O08iroZ-G1tjuAwvT9B:-O08iro_0qh6zcoRxgoQ:b56co20) ([raw file](https://github.com/starkware-libs/stwo/blob/df87de378369b4207f3235698b8def7ee8749fb8/crates/prover/src/core/backend/simd/lookups/gkr.rs#L21)):*
> ```XML
>         }
> 
>         // Start DP with CPU backend to prevent dealing with instances smaller than a SIMD vector.
> ```

what's DP?



_Code quote:_
```XML
Start DP with
```
___
*[`crates/prover/src/core/backend/simd/lookups/gkr.rs` line 22 at r3](https://reviewable.io/reviews/starkware-libs/stwo/630#-O08k5u13BINFVZmUuij:-O08k5u13BINFVZmUuik:b3zzwdb) ([raw file](https://github.com/starkware-libs/stwo/blob/df87de378369b4207f3235698b8def7ee8749fb8/crates/prover/src/core/backend/simd/lookups/gkr.rs#L22)):*
> ```XML
> 
>         // Start DP with CPU backend to prevent dealing with instances smaller than a SIMD vector.
>         let (y_initial, y_rem) = y.split_last_chunk::<{ LOG_N_LANES as usize }>().unwrap();
> ```

y_initial is the last 4 elements in the vector, need another name IMO
or maybe comment that we pass on y in reverse order?



_Code quote:_
```XML
let (y_initial, y_rem) = y.split_last_chunk::<{ LOG_N_LANES as usize }>().unwrap();
```
___
*[`crates/prover/src/core/backend/simd/lookups/gkr.rs` line 70 at r3](https://reviewable.io/reviews/starkware-libs/stwo/630#-O08iuwiDmOufIupmojR:-O08iuwiDmOufIupmojS:b7vqhb1) ([raw file](https://github.com/starkware-libs/stwo/blob/df87de378369b4207f3235698b8def7ee8749fb8/crates/prover/src/core/backend/simd/lookups/gkr.rs#L70)):*
> ```XML
> 
>     #[test]
>     fn gen_eq_evals_matches_cpu() {
> ```

Can you also add a test where `y.len() < LOG_N_LANES`?



_Code quote:_
```XML
fn gen_eq_evals_matches_cpu() {
```

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/630)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/lookups/gkr.rs` line 21 at r3](https://reviewable.io/reviews/starkware-libs/stwo/630#-O08iroZ-G1tjuAwvT9B:-O0Aenr80gv6u3YbvJE-:b2rupoz) ([raw file](https://github.com/starkware-libs/stwo/blob/df87de378369b4207f3235698b8def7ee8749fb8/crates/prover/src/core/backend/simd/lookups/gkr.rs#L21)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

what's DP?
</blockquote></details>

Dynamic Programming
___
*[`crates/prover/src/core/backend/simd/lookups/gkr.rs` line 22 at r3](https://reviewable.io/reviews/starkware-libs/stwo/630#-O08k5u13BINFVZmUuij:-O0AfKGv26mzY4o5-4I0:b-9sogy4) ([raw file](https://github.com/starkware-libs/stwo/blob/df87de378369b4207f3235698b8def7ee8749fb8/crates/prover/src/core/backend/simd/lookups/gkr.rs#L22)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

y_initial is the last 4 elements in the vector, need another name IMO
or maybe comment that we pass on y in reverse order?
</blockquote></details>

Initial in the sense that it's the y values that create the initial values for the algorithm but I see how It's confusing. Changed to `y_last_chunk`. WDYT?
___
*[`crates/prover/src/core/backend/simd/lookups/gkr.rs` line 70 at r3](https://reviewable.io/reviews/starkware-libs/stwo/630#-O08iuwiDmOufIupmojR:-O0C9UJd2frY--ccUFss:b-8b11j9) ([raw file](https://github.com/starkware-libs/stwo/blob/df87de378369b4207f3235698b8def7ee8749fb8/crates/prover/src/core/backend/simd/lookups/gkr.rs#L70)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can you also add a test where `y.len() < LOG_N_LANES`?
</blockquote></details>

Added

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, 2 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/630)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7)

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/630#-:-O20x_jv0qoz3-Ua9Wne:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @andrewmilson)

**Pull request merged**
