### PR TITLE
Generalize AirExt::mask_points()

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/704)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/704?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#704** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/704?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#702** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/702?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#701** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/701?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/704#-:-O1BkZ-40HyMwXRpeQbz:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo/704#-O1BkTXo7g3__VSIJ9A_:-O1BkTXo7g3__VSIJ9Aa:b-2dtr6h) (no related file):*
This is great. thanks!
Just a comment on variable naming.

___
___
*[`crates/prover/src/core/air/air_ext.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/stwo/704#-O1Bj_dr98mm1SyJu1bv:-O1Bj_dr98mm1SyJu1bw:bbquvox) ([raw file](https://github.com/starkware-libs/stwo/blob/7846c47dd81a850437dee40ea2a5402e5590e515/crates/prover/src/core/air/air_ext.rs#L48)):*
> ```XML
>         // Add the composition polynomial mask points.
>         mask.push(vec![vec![point]; SECURE_EXTENSION_DEGREE]);
>         mask
> ```

Only a suggestion for renaming the variables. I understand the code but I think this will make it clearer for other readers.



_Suggestion:_
```XML
        let mut air_points = TreeVec::default();
        for component in self.components() {
            let component_points = component.mask_points(point);
            if air_points.len() < component_points.len() {
                air_points.resize(component_points.len(), vec![]);
            }
            air_points.as_mut().zip_eq(component_points).map(|(air_tree_points, component_tree_points)| {
                air_points.extend(component_points);
            });
        }
        // Add the composition polynomial mask points.
        air_points.push(vec![vec![point]; SECURE_EXTENSION_DEGREE]);
        air_points
```
___
*[`crates/prover/src/core/air/air_ext.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/stwo/704#-O1BkNl90wM_cyEZ1Udc:-O1BkNl90wM_cyEZ1Udd:b2nreh6) ([raw file](https://github.com/starkware-libs/stwo/blob/7846c47dd81a850437dee40ea2a5402e5590e515/crates/prover/src/core/air/air_ext.rs#L71)):*
> ```XML
> 
>     fn column_log_sizes(&self) -> TreeVec<ColumnVec<u32>> {
>         let mut sizes = TreeVec::default();
> ```

Same as above.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/704)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

___
*[`crates/prover/src/core/air/air_ext.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/stwo/704#-O1BkNl90wM_cyEZ1Udc:-O1BoJC26jy4_Y-03fj-:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/7846c47dd81a850437dee40ea2a5402e5590e515/crates/prover/src/core/air/air_ext.rs#L71)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.

**Review by alonh5 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/704)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Pull request merged**
