### PR TITLE
Implement from_qm31_array for QM31.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/679)

### CODE REVIEW

**Comment by alonh5** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/679?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#679** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/679?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#669** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/669?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 2 other dependent PRs ([#671](https://github.com/starkware-libs/stwo/pull/671) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/671?utm_source=stack-comment-icon" target="_blank">Graphite</a>, [#677](https://github.com/starkware-libs/stwo/pull/677) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/677?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#667** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/667?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#664** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/664?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#662** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/662?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#646** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/646?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#644** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/644?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#654](https://github.com/starkware-libs/stwo/pull/654) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/654?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#642** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/642?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#639** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/639?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#638** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/638?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#637** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/637?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#636** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/636?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#651** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/651?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/679)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/prover/src/core/fields/qm31.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/stwo/679#-O0md1p55DXgVtF_ClUj:-O0md1p6C6NGP9UpwhGU:bo9fr06) ([raw file](https://github.com/starkware-libs/stwo/blob/f12a4c85c492fa779e4d8f5b4fa054db419eed76/crates/prover/src/core/fields/qm31.rs#L47)):*
> ```XML
>     /// Returns the combined value, given the values of its composing base field polynomials at that
>     /// point.
>     pub fn from_qm31_array(evals: [Self; SECURE_EXTENSION_DEGREE]) -> Self {
> ```

Actually I don't like this name.
from_array sound as it just trivially pack them, but this is doing something else

WDYT?



_Code quote:_
```XML
pub fn from_qm31_array
```

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/679)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/prover/src/core/fields/qm31.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/stwo/679#-O0md1p55DXgVtF_ClUj:-O0nYrCI6Zj0JJMe-AFY:b-yo8ov) ([raw file](https://github.com/starkware-libs/stwo/blob/f12a4c85c492fa779e4d8f5b4fa054db419eed76/crates/prover/src/core/fields/qm31.rs#L47)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Changed the name, wdyt?
</blockquote></details>

maybe from_partial_evals

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/679#-:-O0nZlnCCGMm5BcxXnkV:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

**Review by shaharsamocha7 — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/679)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

**Review by shaharsamocha7 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/679)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Comment by alonh5** [comment]
### Merge activity

* **Jul 8, 4:33 AM EDT**: @alonh5 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/679).

**Pull request merged**
