### PR TITLE
Save inverse on quotient numerator

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/484)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/484?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#484** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/484?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#483** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/483?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#482** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/482?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#481** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/481?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#480** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/480?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#479** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/479?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#478** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/478?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#463** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/463?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#477** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/477?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#476** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/476?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by andrewmilson — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/484)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`src/core/constraints.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/stwo/484#-NtJ_lNyCYY0pExXlalo:-NtJ_lNyCYY0pExXlalp:bx39nk5) ([raw file](https://github.com/starkware-libs/stwo/blob/5f96433582ff4d7cf760b4ae30b81e8151d155e5/src/core/constraints.rs#L74)):*
> ```XML
> }
> 
> /// Line equation for the 3 points:
> ```

Not sure I understand what this function does.
___
*[`src/core/constraints.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/stwo/484#-NtJa5h76-VXisHgX6bR:-NtJa5h76-VXisHgX6bS:bibbhf2) ([raw file](https://github.com/starkware-libs/stwo/blob/5f96433582ff4d7cf760b4ae30b81e8151d155e5/src/core/constraints.rs#L74)):*
> ```XML
> }
> 
> /// Line equation for the 3 points:
> ```

Function docs should start with a verb and an implicit "this function..."
___
*[`src/core/constraints.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/stwo/484#-NtJYS0_3HuDIkUQNnxV:-NtJYS0_3HuDIkUQNnxW:b-1so5j1) ([raw file](https://github.com/starkware-libs/stwo/blob/5f96433582ff4d7cf760b4ae30b81e8151d155e5/src/core/constraints.rs#L90)):*
> ```XML
>         complex_value.complex_conjugate(),
>     );
>     x0 * y1 + x1 * y2 + x2 * y0 - x0 * y2 - x1 * y0 - x2 * y1
> ```

Is this more efficient `x0 * (y1 - y2) + x1 * (y2 - y0) + x2 * (y0 - y1)`?

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/484)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @andrewmilson)

___
*[`src/core/constraints.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/stwo/484#-NtJ_lNyCYY0pExXlalo:-NtLrFFf8CAcWhcXeXN8:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/5f96433582ff4d7cf760b4ae30b81e8151d155e5/src/core/constraints.rs#L74)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Not sure I understand what this function does.
</blockquote></details>

Done.
___
*[`src/core/constraints.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/stwo/484#-NtJa5h76-VXisHgX6bR:-NtLrG0H4TaMsoFwTJ3n:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/5f96433582ff4d7cf760b4ae30b81e8151d155e5/src/core/constraints.rs#L74)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Function docs should start with a verb and an implicit "this function..."
</blockquote></details>

Done.
___
*[`src/core/constraints.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/stwo/484#-NtJYS0_3HuDIkUQNnxV:-NtLrDulCgSa33CZ5Wvy:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/5f96433582ff4d7cf760b4ae30b81e8151d155e5/src/core/constraints.rs#L90)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Is this more efficient `x0 * (y1 - y2) + x1 * (y2 - y0) + x2 * (y0 - y1)`?
</blockquote></details>

Done.

**Review by andrewmilson — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/484#-:-NtoJUPd60QtSX2UDXto:bnfp4nl)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by andrewmilson — APPROVED** [review]
:lgtm:`

> Reviewed 2 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/484#-:-Ntt4ipt5JISocfU2T-6:bg7igmn)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by alonh5 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/484)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo/484#-NtushbG5dhTyg7e5d2Q:-NtushbG5dhTyg7e5d2R:b-qrzucr) (no related file):*
Can this PR be closed?
I'm changing it for the optimization anyways.

___

**Pull request closed without merging**
