### PR TITLE
Add size estimate for StarkProof

### PR DESCRIPTION
**Pull request by andrewmilson**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/831)

### CODE REVIEW

**Comment by andrewmilson** [comment]
* **#831** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/831?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @andrewmilson and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/831)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @andrewmilson)

*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo/831#-O6pP0Le1779KJNMCUp6:-O6pP0Le1779KJNMCUp7:b-jg96ao) (no related file):*
Can you add an example of the size_estimate output?

___
___
*[`crates/prover/src/core/prover/mod.rs` line 254 at r1](https://reviewable.io/reviews/starkware-libs/stwo/831#-O6pPGCe6ZAo0kyLHDHs:-O6pPGCe6ZAo0kyLHDHt:btam2al) ([raw file](https://github.com/starkware-libs/stwo/blob/b7bf1fef48756275e8907744b16ae8e4060eea6a/crates/prover/src/core/prover/mod.rs#L254)):*
> ```XML
> impl SizeEstimate for BaseField {
>     fn size_estimate(&self) -> usize {
>         mem::size_of::<Self>()
> ```

Can you add unit test that the base sizes are correct?



_Code quote:_
```XML
mem::size_of::<Self>()
```

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/831)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7)

*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo/831#-O6pP0Le1779KJNMCUp6:-O6rV_9i7Y0XGGVQmNQ1:b-896fix) (no related file):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can you add an example of the size_estimate output?
</blockquote></details>

Done.

___
___
*[`crates/prover/src/core/prover/mod.rs` line 254 at r1](https://reviewable.io/reviews/starkware-libs/stwo/831#-O6pPGCe6ZAo0kyLHDHs:-O6rVdSPCK9AXfq4RPgd:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/b7bf1fef48756275e8907744b16ae8e4060eea6a/crates/prover/src/core/prover/mod.rs#L254)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can you add unit test that the base sizes are correct?
</blockquote></details>

Done.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/831#-:-O6vA_8NDR4bEDIuJJAw:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @andrewmilson)

**Pull request merged**
