### PR TITLE
Added LogupAtRow functionality to EvalAtRow.

### PR DESCRIPTION
**Pull request by Alon-Ti**

### CODE REVIEW

**Comment by Alon-Ti** [comment]
* **#876** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/876?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#875** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/875?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Alon-Ti and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 17 of 19 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/875)* status: 18 of 19 files reviewed, 6 unresolved discussions (waiting on @Alon-Ti and @ohad-starkware)

___
*[`crates/prover/src/examples/blake/round/mod.rs` line 34 at r2](https://reviewable.io/reviews/starkware-libs/stwo/875#-OBPzXcyDkf5KEMslB7w:-OBPzXcyDkf5KEMslB7x:blav029) ([raw file](https://github.com/starkware-libs/stwo/blob/4aa5a22a91158f38cb38f08a4a4df37115245eb4/crates/prover/src/examples/blake/round/mod.rs#L34)):*
> ```XML
>     }
>     fn evaluate<E: EvalAtRow>(&self, mut eval: E) -> E {
>         let is_first = eval.get_preprocessed_column(PreprocessedColumn::IsFirst(self.log_size()));
> ```

why did you remove that? the logup define the use in it?



_Code quote:_
```XML
let is_first = eval.get_preprocessed_column(PreprocessedColumn::IsFirst(self.log_size()));
```
___
*[`crates/prover/src/constraint_framework/mod.rs` line 169 at r2](https://reviewable.io/reviews/starkware-libs/stwo/875#-OBPzlEU01-fdFtPrxpg:-OBPzlEU01-fdFtPrxph:b-gv62uk) ([raw file](https://github.com/starkware-libs/stwo/blob/f4aa5d7eccf942a66bde2839215fa8edf20c69d2/crates/prover/src/constraint_framework/mod.rs#L169)):*
> ```XML
>         }
> 
>         fn write_frac(&mut self, fraction: Fraction<Self::EF, Self::EF>) {
> ```

maybe this should be renamed to write_logup? write_logup_frac?
WDYT?



_Code quote:_
```XML
fn write_frac(&mut self, fraction: Fraction<Self::EF, Self::EF>) {
```
___
*[`crates/prover/src/constraint_framework/mod.rs` line 202 at r2](https://reviewable.io/reviews/starkware-libs/stwo/875#-OBPzDT910IwHabexrRt:-OBPzDT910IwHabexrRu:bi5abe3) ([raw file](https://github.com/starkware-libs/stwo/blob/f4aa5d7eccf942a66bde2839215fa8edf20c69d2/crates/prover/src/constraint_framework/mod.rs#L202)):*
> ```XML
>     fn get_alpha_powers(&self) -> &[EF];
>     fn name(&self) -> &str;
> }
> ```

should this code be here?



_Code quote:_
```XML
pub trait RelationType<F, EF>
where
    F: Clone,
    EF: Clone + Zero + From<F> + From<SecureField> + Mul<F, Output = EF> + Sub<EF, Output = EF>,
{
    fn combine(&self, values: &[F]) -> EF {
        values
            .iter()
            .zip(self.get_alpha_powers())
            .fold(EF::zero(), |acc, (value, power)| {
                acc + power.clone() * value.clone()
            })
            - self.get_z()
    }

    fn get_z(&self) -> EF;
    fn get_alpha_powers(&self) -> &[EF];
    fn name(&self) -> &str;
}
```
___
*[`crates/prover/src/examples/xor/gkr_lookups/mle_eval.rs` line 928 at r2](https://reviewable.io/reviews/starkware-libs/stwo/875#-OBQ-9gy7OOjKoXhwDE0:-OBQ-9gz4zL0EzZWN606:b3kre) ([raw file](https://github.com/starkware-libs/stwo/blob/4aa5a22a91158f38cb38f08a4a4df37115245eb4/crates/prover/src/examples/xor/gkr_lookups/mle_eval.rs#L928)):*
> ```XML
>                 is_second_eval,
>             )
>         });
> ```

?



_Code quote:_
```XML
        });
```
___
*[`crates/prover/src/constraint_framework/logup.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/stwo/875#-OBPz23qCkhwthtYQgfG:-OBPz23r8guxdT2SHpdy:b-krbrjc) ([raw file](https://github.com/starkware-libs/stwo/blob/f4aa5d7eccf942a66bde2839215fa8edf20c69d2/crates/prover/src/constraint_framework/logup.rs#L74)):*
> ```XML
>     pub fn dummy() -> Self {
>         Self {
>             interaction: 0,
> ```

I think it is better not to use real values here



_Suggestion:_
```XML
interaction: -1,
```
___
*[`crates/prover/src/constraint_framework/interaction_gen.rs` line 7 at r2](https://reviewable.io/reviews/starkware-libs/stwo/875#-OBPyACgC4YGEqy5F5Lj:-OBPyACgC4YGEqy5F5Lk:byquu61) ([raw file](https://github.com/starkware-libs/stwo/blob/f4aa5d7eccf942a66bde2839215fa8edf20c69d2/crates/prover/src/constraint_framework/interaction_gen.rs#L7)):*
> ```XML
> use crate::core::poly::BitReversedOrder;
> 
> pub struct InteractionTraceGenerator<'a> {}
> ```

Do we need this?



_Code quote:_
```XML
use crate::core::backend::simd::SimdBackend;
use crate::core::fields::m31::BaseField;
use crate::core::pcs::TreeVec;
use crate::core::poly::circle::CircleEvaluation;
use crate::core::poly::BitReversedOrder;

pub struct InteractionTraceGenerator<'a> {}
```

**Review by Alon-Ti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/875)* status: 8 of 19 files reviewed, 6 unresolved discussions (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/logup.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/stwo/875#-OBPz23qCkhwthtYQgfG:-OBXei5i5DNnnJfiV5bP:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/f4aa5d7eccf942a66bde2839215fa8edf20c69d2/crates/prover/src/constraint_framework/logup.rs#L74)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I think it is better not to use real values here
</blockquote></details>

Done.
___
*[`crates/prover/src/constraint_framework/mod.rs` line 169 at r2](https://reviewable.io/reviews/starkware-libs/stwo/875#-OBPzlEU01-fdFtPrxpg:-OBXev9vEUgYswFeAz-k:b-plbh02) ([raw file](https://github.com/starkware-libs/stwo/blob/f4aa5d7eccf942a66bde2839215fa8edf20c69d2/crates/prover/src/constraint_framework/mod.rs#L169)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

maybe this should be renamed to write_logup? write_logup_frac?
WDYT?
</blockquote></details>

I'll rename them in the PR above where I decouple this from LogupAtRow functionality.
___
*[`crates/prover/src/constraint_framework/mod.rs` line 202 at r2](https://reviewable.io/reviews/starkware-libs/stwo/875#-OBPzDT910IwHabexrRt:-OBXfwK54avPDBjfh5iL:b-r43gyr) ([raw file](https://github.com/starkware-libs/stwo/blob/f4aa5d7eccf942a66bde2839215fa8edf20c69d2/crates/prover/src/constraint_framework/mod.rs#L202)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

should this code be here?
</blockquote></details>

It's not used in this PR, removed.
___
*[`crates/prover/src/examples/blake/round/mod.rs` line 34 at r2](https://reviewable.io/reviews/starkware-libs/stwo/875#-OBPzXcyDkf5KEMslB7w:-OBQCsNE2BIWN853PmaB:b-naeibk) ([raw file](https://github.com/starkware-libs/stwo/blob/4aa5a22a91158f38cb38f08a4a4df37115245eb4/crates/prover/src/examples/blake/round/mod.rs#L34)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

why did you remove that? the logup define the use in it?
</blockquote></details>

Yes, once the logup is in the eval, this becomes part of the init (especially now that it's a const column). See `constraint_framework/mod.rs:157`.
___
*[`crates/prover/src/constraint_framework/interaction_gen.rs` line 7 at r2](https://reviewable.io/reviews/starkware-libs/stwo/875#-OBPyACgC4YGEqy5F5Lj:-OBQCYJM8TD6tziRs0Kk:b-w2yowe) ([raw file](https://github.com/starkware-libs/stwo/blob/f4aa5d7eccf942a66bde2839215fa8edf20c69d2/crates/prover/src/constraint_framework/interaction_gen.rs#L7)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Do we need this?
</blockquote></details>

Sorry, spoilers :)
___
*[`crates/prover/src/examples/xor/gkr_lookups/mle_eval.rs` line 928 at r2](https://reviewable.io/reviews/starkware-libs/stwo/875#-OBQ-9gy7OOjKoXhwDE0:-OBXgN061tfp1I9zyo4o:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/4aa5a22a91158f38cb38f08a4a4df37115245eb4/crates/prover/src/examples/xor/gkr_lookups/mle_eval.rs#L928)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/875#-:-OBZZXWM92vfWT0FFX9t:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ohad-starkware)

**Pull request merged**
