### PR TITLE
Simplify Air less

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/778)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
* **#778** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/778?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r1, 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/778)* status: 2 of 10 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/examples/fibonacci/air.rs` line 126 at r2](https://reviewable.io/reviews/starkware-libs/stwo/778#-O3Yf1rX2wQ8bGn1jeT9:-O3Yf1rX2wQ8bGn1jeTA:b-f2pshn) ([raw file](https://github.com/starkware-libs/stwo/blob/16541242a6f20d943801e5e0ea0598e1453bb96e/crates/prover/src/examples/fibonacci/air.rs#L126)):*
> ```XML
> pub struct MultiFibonacciAir {
>     pub components: Vec<FibonacciComponent>,
> }
> ```

Do we have another test that involves multiple components?



_Code quote:_
```XML
#[derive(Clone)]
pub struct MultiFibonacciAir {
    pub components: Vec<FibonacciComponent>,
}
```
___
*[`crates/prover/src/examples/fibonacci/mod.rs` line 203 at r2](https://reviewable.io/reviews/starkware-libs/stwo/778#-O3YeaOHCA26iYezuoVj:-O3YeaOHCA26iYezuoVk:blxfub3) ([raw file](https://github.com/starkware-libs/stwo/blob/16541242a6f20d943801e5e0ea0598e1453bb96e/crates/prover/src/examples/fibonacci/mod.rs#L203)):*
> ```XML
> 
>     #[test]
>     fn test_sparse_circle_points() {
> ```

Do we want to keep this test?



_Code quote:_
```XML
    #[test]
    fn test_sparse_circle_points() {
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/778)* status: 2 of 10 files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/prover/src/examples/fibonacci/air.rs` line 126 at r2](https://reviewable.io/reviews/starkware-libs/stwo/778#-O3Yf1rX2wQ8bGn1jeT9:-O3a8RJx4231_LJdAAI4:b-8ac74k) ([raw file](https://github.com/starkware-libs/stwo/blob/16541242a6f20d943801e5e0ea0598e1453bb96e/crates/prover/src/examples/fibonacci/air.rs#L126)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Do we have another test that involves multiple components?
</blockquote></details>

Blake
___
*[`crates/prover/src/examples/fibonacci/mod.rs` line 203 at r2](https://reviewable.io/reviews/starkware-libs/stwo/778#-O3YeaOHCA26iYezuoVj:-O3a9sej5hFyVeusoAgW:b-7zlhwx) ([raw file](https://github.com/starkware-libs/stwo/blob/16541242a6f20d943801e5e0ea0598e1453bb96e/crates/prover/src/examples/fibonacci/mod.rs#L203)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Do we want to keep this test?
</blockquote></details>

This tests Queries, and it seems it already has enough tests.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 9 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/778)* status: all files reviewed, 9 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/core/air/air_ext.rs` line 2 at r3](https://reviewable.io/reviews/starkware-libs/stwo/778#-O3aE1ou1R1gaMFbMxiu:-O3aE1ou1R1gaMFbMxiv:b-pm8xr5) ([raw file](https://github.com/starkware-libs/stwo/blob/8727b12be059a4003237c52bc04a92606deb1206/crates/prover/src/core/air/air_ext.rs#L2)):*
> ```XML
> use itertools::{zip_eq, Itertools};
> ```

Consider to rename this file
___
*[`crates/prover/src/core/air/air_ext.rs` line 67 at r3](https://reviewable.io/reviews/starkware-libs/stwo/778#-O3aDhKJ5pVX0sFwTeQk:-O3aDhKJ5pVX0sFwTeQl:b-lgkmby) ([raw file](https://github.com/starkware-libs/stwo/blob/8727b12be059a4003237c52bc04a92606deb1206/crates/prover/src/core/air/air_ext.rs#L67)):*
> ```XML
>     }
> 
>     pub fn column_log_sizes(&self) -> TreeVec<ColumnVec<u32>> {
> ```

Why are those function were not pub and now they do?



_Code quote:_
```XML
pub fn column_log_sizes(&self) -> TreeVec<ColumnVec<u32>> {
```
___
*[`crates/prover/src/core/air/air_ext.rs` line 87 at r3](https://reviewable.io/reviews/starkware-libs/stwo/778#-O3aGbS-A1EhI8uATD-l:-O3aGbS-A1EhI8uATD-m:b6mtpte) ([raw file](https://github.com/starkware-libs/stwo/blob/8727b12be059a4003237c52bc04a92606deb1206/crates/prover/src/core/air/air_ext.rs#L87)):*
> ```XML
> 
> impl<'a, B: Backend> ComponentProvers<'a, B> {
>     pub fn components(&self) -> Components<'_> {
> ```

I think we should rename this function or the resulted struct, not sure how
- fn public_component()

- VerifierComponent
- PublicComponent



_Code quote:_
```XML
pub fn components(&self) -> Components<'_> {
```
___
*[`crates/prover/src/core/air/air_ext.rs` line 114 at r3](https://reviewable.io/reviews/starkware-libs/stwo/778#-O3aEGvu2rWq5ansnWdw:-O3aEGvu2rWq5ansnWdx:b-1ndypc) ([raw file](https://github.com/starkware-libs/stwo/blob/8727b12be059a4003237c52bc04a92606deb1206/crates/prover/src/core/air/air_ext.rs#L114)):*
> ```XML
>     }
> 
>     pub fn component_traces<'b, H: MerkleHasher>(
> ```

Why does it need different lifetime?



_Code quote:_
```XML
pub fn component_traces<'b, H: MerkleHasher>
```
___
*[`crates/prover/src/core/air/mod.rs` line 15 at r3](https://reviewable.io/reviews/starkware-libs/stwo/778#-O3aFDRJ7YLeGbrE9ZmR:-O3aFDRJ7YLeGbrE9ZmS:b-6l13b4) ([raw file](https://github.com/starkware-libs/stwo/blob/16541242a6f20d943801e5e0ea0598e1453bb96e/crates/prover/src/core/air/mod.rs#L15)):*
> ```XML
> pub mod mask;
> 
> pub use air_ext::{AirExt, AirProverExt};
> ```

Consider to import only the things that you need



_Code quote:_
```XML
pub use air_ext::{AirExt, AirProverExt};
```
___
*[`crates/prover/src/core/prover/mod.rs` line 57 at r3](https://reviewable.io/reviews/starkware-libs/stwo/778#-O3aFR-Z-CX_SLF5OY3I:-O3aFR-Z-CX_SLF5OY3J:b-fxb0ll) ([raw file](https://github.com/starkware-libs/stwo/blob/8727b12be059a4003237c52bc04a92606deb1206/crates/prover/src/core/prover/mod.rs#L57)):*
> ```XML
>     H: MerkleHasher<Hash = C::Digest>,
> {
>     let components = ComponentProvers(components.to_vec());
> ```

`components.components() -> prover_components.components()`



_Suggestion:_
```XML
let prover_components = ComponentProvers(components.to_vec());
```
___
*[`crates/prover/src/examples/plonk/mod.rs` line 284 at r3](https://reviewable.io/reviews/starkware-libs/stwo/778#-O3aFya27lHYWgJk7buV:-O3aFya27lHYWgJk7buW:b1r7rp4) ([raw file](https://github.com/starkware-libs/stwo/blob/8727b12be059a4003237c52bc04a92606deb1206/crates/prover/src/examples/plonk/mod.rs#L284)):*
> ```XML
>         commitment_scheme.commit(proof.commitments[0], &sizes[0], channel);
>         // Draw lookup element.
>         let _lookup_elements = LookupElements::<2>::draw(channel);
> ```

Consider to generate the lookup elements properly or remove



_Code quote:_
```XML
let _lookup_elements = LookupElements::<2>::draw(channel);
```
___
*[`crates/prover/src/examples/poseidon/mod.rs` line 506 at r3](https://reviewable.io/reviews/starkware-libs/stwo/778#-O3aG8zTAXGzDg_oWXSy:-O3aG8zTAXGzDg_oWXSz:bb7od0r) ([raw file](https://github.com/starkware-libs/stwo/blob/8727b12be059a4003237c52bc04a92606deb1206/crates/prover/src/examples/poseidon/mod.rs#L506)):*
> ```XML
>         commitment_scheme.commit(proof.commitments[0], &sizes[0], channel);
>         // Draw lookup element.
>         let _lookup_elements = PoseidonElements::draw(channel);
> ```

same



_Code quote:_
```XML
let _lookup_elements = PoseidonElements::draw(channel);
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/778)* status: all files reviewed, 8 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/prover/src/core/air/air_ext.rs` line 2 at r3](https://reviewable.io/reviews/starkware-libs/stwo/778#-O3aE1ou1R1gaMFbMxiu:-O3aMsue4NOtZEUZbtM5:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/8727b12be059a4003237c52bc04a92606deb1206/crates/prover/src/core/air/air_ext.rs#L2)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Consider to rename this file
</blockquote></details>

Done.
___
*[`crates/prover/src/core/air/air_ext.rs` line 67 at r3](https://reviewable.io/reviews/starkware-libs/stwo/778#-O3aDhKJ5pVX0sFwTeQk:-O3aMePLD2nRPPP-zAng:bg05u3q) ([raw file](https://github.com/starkware-libs/stwo/blob/8727b12be059a4003237c52bc04a92606deb1206/crates/prover/src/core/air/air_ext.rs#L67)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why are those function were not pub and now they do?
</blockquote></details>

They were in a trait / impl of a trait (pub doesnt make sense there).
___
*[`crates/prover/src/core/air/air_ext.rs` line 87 at r3](https://reviewable.io/reviews/starkware-libs/stwo/778#-O3aGbS-A1EhI8uATD-l:-O3aP9O964qRnTfTyYJd:b-p8pxxl) ([raw file](https://github.com/starkware-libs/stwo/blob/8727b12be059a4003237c52bc04a92606deb1206/crates/prover/src/core/air/air_ext.rs#L87)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I think we should rename this function or the resulted struct, not sure how
- fn public_component()

- VerifierComponent
- PublicComponent
</blockquote></details>

If we make the distinction between component_provers and components, maybe this could stay components(), but we should make the variables holding type ComponentProvers be named `component_provers`. wdyt?
___
*[`crates/prover/src/core/air/air_ext.rs` line 114 at r3](https://reviewable.io/reviews/starkware-libs/stwo/778#-O3aEGvu2rWq5ansnWdw:-O3aNqEd9R11sdglJqpk:b-329owe) ([raw file](https://github.com/starkware-libs/stwo/blob/8727b12be059a4003237c52bc04a92606deb1206/crates/prover/src/core/air/air_ext.rs#L114)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why does it need different lifetime?
</blockquote></details>

Not sure what's happening here, but it doesn't compile without this.
___
*[`crates/prover/src/core/prover/mod.rs` line 57 at r3](https://reviewable.io/reviews/starkware-libs/stwo/778#-O3aFR-Z-CX_SLF5OY3I:-O3aOIib7wQ4u2s-G8XG:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/8727b12be059a4003237c52bc04a92606deb1206/crates/prover/src/core/prover/mod.rs#L57)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

`components.components() -> prover_components.components()`
</blockquote></details>

Done.
___
*[`crates/prover/src/examples/plonk/mod.rs` line 284 at r3](https://reviewable.io/reviews/starkware-libs/stwo/778#-O3aFya27lHYWgJk7buV:-O3aOQTM0VAkcwyMAXwR:bwygxsx) ([raw file](https://github.com/starkware-libs/stwo/blob/8727b12be059a4003237c52bc04a92606deb1206/crates/prover/src/examples/plonk/mod.rs#L284)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Consider to generate the lookup elements properly or remove
</blockquote></details>

Noted.
___
*[`crates/prover/src/examples/poseidon/mod.rs` line 506 at r3](https://reviewable.io/reviews/starkware-libs/stwo/778#-O3aG8zTAXGzDg_oWXSy:-O3aORuD9IGvg6FyeXY3:bwygxsx) ([raw file](https://github.com/starkware-libs/stwo/blob/8727b12be059a4003237c52bc04a92606deb1206/crates/prover/src/examples/poseidon/mod.rs#L506)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

same
</blockquote></details>

Noted.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/778)* status: all files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/prover/src/examples/plonk/mod.rs` line 284 at r3](https://reviewable.io/reviews/starkware-libs/stwo/778#-O3aFya27lHYWgJk7buV:-O3aUN1RAFH3bj5SRRGJ:b-78wvlm) ([raw file](https://github.com/starkware-libs/stwo/blob/8727b12be059a4003237c52bc04a92606deb1206/crates/prover/src/examples/plonk/mod.rs#L284)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Right. It's better for it to be here and not, but doing the full thing is out of scope for this PR
</blockquote></details>

Ill just bring back the assert.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/778#-:-O3agojWAjhIT3ErAVi7:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
