### PR TITLE
Add benchmarks for GKR lookups

### PR DESCRIPTION
**Pull request by andrewmilson**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/673)

### CODE REVIEW

**Comment by andrewmilson** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/673?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#673** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/673?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#641** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/641?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#640** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/640?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#630** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/630?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#629** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/629?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#623** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/623?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#620** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/620?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#621** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/621?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#581** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/581?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#617** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/617?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#616** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/616?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#615** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/615?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#614** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/614?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#613** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/613?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#612** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/612?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#611** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/611?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#610** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/610?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @andrewmilson and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — COMMENTED** [review]
> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/673)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @andrewmilson)

___
*[`crates/prover/benches/fft.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/stwo/673#-O2e9Q0L8Qto3--dnaTM:-O2e9Q0M08wv3o_o6xkN:b-i5ou10) ([raw file](https://github.com/starkware-libs/stwo/blob/c0d0453fb109dd826651d682b003bd2845a45bbd/crates/prover/benches/fft.rs#L21)):*
> ```XML
>     let mut group = c.benchmark_group("iffts");
> 
>     for log_size in 16..=16 {
> ```

Why did you shrink it?



_Code quote:_
```XML
for log_size in 16..=16 {
```
___
*[`crates/prover/src/core/lookups/gkr_prover.rs` line 93 at r1](https://reviewable.io/reviews/starkware-libs/stwo/673#-O2eA-QHA4moHv47UDqy:-O2eA-QHA4moHv47UDqz:b6g32vy) ([raw file](https://github.com/starkware-libs/stwo/blob/c0d0453fb109dd826651d682b003bd2845a45bbd/crates/prover/src/core/lookups/gkr_prover.rs#L93)):*
> ```XML
> /// [LogUp]: https://eprint.iacr.org/2023/1284.pdf
> #[derive(Educe)]
> #[educe(Debug, Clone)]
> ```

Why not in the simple way?



_Suggestion:_
```XML
#[derive(Debug, Clone)]
```

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/673)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/prover/benches/fft.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/stwo/673#-O2e9Q0L8Qto3--dnaTM:-O2ewS4Y4YezNvj3sO3H:b-c25zk) ([raw file](https://github.com/starkware-libs/stwo/blob/c0d0453fb109dd826651d682b003bd2845a45bbd/crates/prover/benches/fft.rs#L21)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why did you shrink it?
</blockquote></details>

Ohh thanks for this. Sorry forgot to remove from the PR.
___
*[`crates/prover/src/core/lookups/gkr_prover.rs` line 93 at r1](https://reviewable.io/reviews/starkware-libs/stwo/673#-O2eA-QHA4moHv47UDqy:-O2evHoLBc_LJXysN-fc:bwc0r67) ([raw file](https://github.com/starkware-libs/stwo/blob/c0d0453fb109dd826651d682b003bd2845a45bbd/crates/prover/src/core/lookups/gkr_prover.rs#L93)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why not in the simple way?
</blockquote></details>

The regular derive has bad trait bound requirements. 
e.g. default derive only implements Clone if `B: Clone`. But `Mle<B, SecureField>` is clone regardless of if `B` is Clone so `B: Clone` is a bad bound.
The educe derive understands that B doesn't have to be clone.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r1, 1 of 2 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/673#-:-O4pD7wZA8lxTiRLSoaA:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

**Pull request merged**
