### PR TITLE
AVX fft benchmark

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/382)

### CODE REVIEW

**Review by ohad-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/382)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`benches/fft.rs` line 5 at r1](https://reviewable.io/reviews/starkware-libs/stwo/382#-Ns8A-85-aBkGjejjl75:-Ns8A-85-aBkGjejjl76:b-9d3n5) ([raw file](https://github.com/starkware-libs/stwo/blob/36d08a97c85a945bfad51e502e1542ff418e699e/benches/fft.rs#L5)):*
> ```XML
> use criterion::Criterion;
> 
> #[cfg(target_arch = "x86_64")]
> ```

#[cfg(all(target_arch = "x86_64", target_feature = "avx512f"))], 
otherwise clippy will scream 
___
*[`benches/fft.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/stwo/382#-Ns89LUF7Eut4mMlpwRa:-Ns89LUF7Eut4mMlpwRb:bnj7hl0) ([raw file](https://github.com/starkware-libs/stwo/blob/36d08a97c85a945bfad51e502e1542ff418e699e/benches/fft.rs#L42)):*
> ```XML
> }
> 
> #[cfg(target_arch = "x86_64")]
> ```

same as above

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/382)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @ohad-starkware)

___
*[`benches/fft.rs` line 5 at r1](https://reviewable.io/reviews/starkware-libs/stwo/382#-Ns8A-85-aBkGjejjl75:-Ns8GsDK8zEdsBcHdfNL:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/36d08a97c85a945bfad51e502e1542ff418e699e/benches/fft.rs#L5)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

#[cfg(all(target_arch = "x86_64", target_feature = "avx512f"))], 
otherwise clippy will scream
</blockquote></details>

Done.
___
*[`benches/fft.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/stwo/382#-Ns89LUF7Eut4mMlpwRa:-Ns8GsV_032Dtd8hcuOk:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/36d08a97c85a945bfad51e502e1542ff418e699e/benches/fft.rs#L42)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.

**Review by ohad-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/382)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by ohad-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/382#-:-Ns8Q6sX8KgKcHVIc9LJ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
