### PR TITLE
Pass OODS values to channel.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/464)

### CODE REVIEW

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/464)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`src/core/channel.rs` line 55 at r2](https://reviewable.io/reviews/starkware-libs/stwo/464#-NsrvRwz1N9UcdDJOurP:-NsrxQVBEw5u9PoZf5-2:b-600uoz) ([raw file](https://github.com/starkware-libs/stwo/blob/1dd4d82d4d1d7d067c8b021cdadf5643c3ce0ca0/src/core/channel.rs#L55)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

You don't need this IMO.
Just call mix_felts() when needed
</blockquote></details>

I first extracted it into a function because it was bulky and duplicated. Then I liked it better as a method of channel than a function that receives it. Do you think I should have is as a function or have it as is and duplicated?

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/464)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`src/core/channel.rs` line 55 at r2](https://reviewable.io/reviews/starkware-libs/stwo/464#-NsrvRwz1N9UcdDJOurP:-Nswb5gTB4yCFvaQ7B-F:b-bhe2fq) ([raw file](https://github.com/starkware-libs/stwo/blob/1dd4d82d4d1d7d067c8b021cdadf5643c3ce0ca0/src/core/channel.rs#L55)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I first extracted it into a function because it was bulky and duplicated. Then I liked it better as a method of channel than a function that receives it. Do you think I should have is as a function or have it as is and duplicated?
</blockquote></details>

1. I don't think channel.rs is the right place for this. Channel doesn't need to know about the term `oods`.
2.  It's 2 calls, seems pretty small..
3. You can make a function for
```
.iter()
                .flatten()
                .flatten()
                .copied()
                .collect_vec()
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/464)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`src/core/channel.rs` line 55 at r2](https://reviewable.io/reviews/starkware-libs/stwo/464#-NsrvRwz1N9UcdDJOurP:-Nsww9Fw2TibAIx7-gPl:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/1dd4d82d4d1d7d067c8b021cdadf5643c3ce0ca0/src/core/channel.rs#L55)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

1. I don't think channel.rs is the right place for this. Channel doesn't need to know about the term `oods`.
2.  It's 2 calls, seems pretty small..
3. You can make a function for
```
.iter()
                .flatten()
                .flatten()
                .copied()
                .collect_vec()
```
</blockquote></details>

Done.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/464#-:-Nt6c3cvCfc4SYjlq5iJ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Pull request merged**
