### PR TITLE
Removed batching from LogupAtRow.

### PR DESCRIPTION
**Pull request by Alon-Ti**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/817)

### CODE REVIEW

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/817)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @Alon-Ti)

___
*[`crates/prover/src/constraint_framework/logup.rs` line 34 at r2](https://reviewable.io/reviews/starkware-libs/stwo/817#-O6LrpfFCTnY1dnHyw4s:-O6LrpfFCTnY1dnHyw4t:bnj2xqp) ([raw file](https://github.com/starkware-libs/stwo/blob/eeb96b0db1f4c5066c84a4c45e21a89b6e5f1943/crates/prover/src/constraint_framework/logup.rs#L34)):*
> ```XML
>     /// The evaluation of the last cumulative sum column.
>     pub prev_col_cumsum: E::EF,
>     cur_frac: Option<Fraction<E::EF, E::EF>>,
> ```

Why not initialize with (zero(), one())?
and remove the Option



_Code quote:_
```XML
cur_frac: Option<Fraction<E::EF, E::EF>>,
```
___
*[`crates/prover/src/examples/blake/scheduler/constraints.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/stwo/817#-O6LtKcT47Owhe-kESxB:-O6LtKcUDzoJd8rs6gBG:b-p3jb30) ([raw file](https://github.com/starkware-libs/stwo/blob/eeb96b0db1f4c5066c84a4c45e21a89b6e5f1943/crates/prover/src/examples/blake/scheduler/constraints.rs#L45)):*
> ```XML
> 
>     // TODO(spapini): Support multiplicities.
>     // TODO(spapini): Change to -1.
> ```

Can we fix those todos or remove the lookup if not needed?



_Code quote:_
```XML
    // TODO(spapini): Support multiplicities.
    // TODO(spapini): Change to -1.
```
___
*[`crates/prover/src/examples/poseidon/mod.rs` line 188 at r2](https://reviewable.io/reviews/starkware-libs/stwo/817#-O6LsRuZ8vIPPnorYHpm:-O6LsRuZ8vIPPnorYHpn:bdx2haz) ([raw file](https://github.com/starkware-libs/stwo/blob/eeb96b0db1f4c5066c84a4c45e21a89b6e5f1943/crates/prover/src/examples/poseidon/mod.rs#L188)):*
> ```XML
>         // Provide state lookups.
>         let final_state_denom: E::EF = lookup_elements.combine(&state);
>         // (1 / denom1) - (1 / denom1) = (denom1 - denom0) / (denom0 * denom1).
> ```

`(1 / denom1) - (1 / denom1) = 0`



_Suggestion:_
```XML
// (1 / denom0) - (1 / denom1) = (denom1 - denom0) / (denom0 * denom1).
```

**Review by Alon-Ti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/817)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/logup.rs` line 34 at r2](https://reviewable.io/reviews/starkware-libs/stwo/817#-O6LrpfFCTnY1dnHyw4s:-O6MBNAsBlJcOwC14n-k:b-ssvgk0) ([raw file](https://github.com/starkware-libs/stwo/blob/eeb96b0db1f4c5066c84a4c45e21a89b6e5f1943/crates/prover/src/constraint_framework/logup.rs#L34)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why not initialize with (zero(), one())?
and remove the Option
</blockquote></details>

Because of the `finalize` logic I only add a constraint on the next call for each frac, I need a way to identify the uninitialized state anyway, checking if there was a previous frac does that.
___
*[`crates/prover/src/examples/blake/scheduler/constraints.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/stwo/817#-O6LtKcT47Owhe-kESxB:-O6MB1Mf7285JL_P5sJR:bm133o9) ([raw file](https://github.com/starkware-libs/stwo/blob/eeb96b0db1f4c5066c84a4c45e21a89b6e5f1943/crates/prover/src/examples/blake/scheduler/constraints.rs#L45)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can we fix those todos or remove the lookup if not needed?
</blockquote></details>

I'm not sure, I just mechanically converted the lookups. Let's go over all spapini TODOs next week to see what should be done now and change ownership.
___
*[`crates/prover/src/examples/poseidon/mod.rs` line 188 at r2](https://reviewable.io/reviews/starkware-libs/stwo/817#-O6LsRuZ8vIPPnorYHpm:-O6MBKKuCBjKj2OSlbPC:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/eeb96b0db1f4c5066c84a4c45e21a89b6e5f1943/crates/prover/src/examples/poseidon/mod.rs#L188)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

`(1 / denom1) - (1 / denom1) = 0`
</blockquote></details>

Done.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/817)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @Alon-Ti)

___
*[`crates/prover/src/examples/blake/xor_table/constraints.rs` line 30 at r4](https://reviewable.io/reviews/starkware-libs/stwo/817#-O6MGE4E9kpkI_duWuI3:-O6MGE4E9kpkI_duWuI4:bunaz7e) ([raw file](https://github.com/starkware-libs/stwo/blob/58aba4b07c0fbb395e72ec2369ccdf7c89188dad/crates/prover/src/examples/blake/xor_table/constraints.rs#L30)):*
> ```XML
>         let frac_chunks: [Fraction<E::EF, E::EF>; 1 << (2 * EXPAND_BITS)] =
>             std::array::from_fn(|i| {
>                 let (i, j) = ((i >> EXPAND_BITS) as u32, (i % (1 << EXPAND_BITS)) as u32);
> ```

@andrewmilson Do you have another alternative?
This is pretty awful :(



_Code quote:_
```XML
        let frac_chunks: [Fraction<E::EF, E::EF>; 1 << (2 * EXPAND_BITS)] =
            std::array::from_fn(|i| {
                let (i, j) = ((i >> EXPAND_BITS) as u32, (i % (1 << EXPAND_BITS)) as u32);
```

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/817#-:-O6pOg6kB-xcuL6FMVj-:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Alon-Ti)

**Pull request merged**
