### PR TITLE
Fix CirclePointIndex bug in debug mode for 32-bit archs

### PR DESCRIPTION
**Pull request by andrewmilson**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/613)

### CODE REVIEW

**Comment by andrewmilson** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/613?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#613** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/613?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#612** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/612?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#611** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/611?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#610** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/610?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#609** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/609?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#608** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/608?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#607** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/607?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#606** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/606?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#605** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/605?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#604** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/604?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#603** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/603?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#599** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/599?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#596** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/596?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#602** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/602?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#595** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/595?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#601** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/601?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#594** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/594?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#600** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/600?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#593** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/593?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#592** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/592?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#591** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/591?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @andrewmilson and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/613)* status: 0 of 1 files reviewed, 1 unresolved discussion

___
*[`crates/prover/src/core/circle.rs` line 272 at r1](https://reviewable.io/reviews/starkware-libs/stwo/613#-NwwIiYF-y8jvc651zDW:-NwwIiYF-y8jvc651zDX:b-gk03vz) ([raw file](https://github.com/starkware-libs/stwo/blob/a871b87deb8a88f8b95b45e214917231796b39d3/crates/prover/src/core/circle.rs#L272)):*
> ```XML
> 
>     fn mul(self, rhs: usize) -> Self::Output {
>         Self(self.0.wrapping_mul(rhs)).reduce()
> ```

Test `examples::fibonacci::tests::test_mixed_degree_multi_fibonacci` caused an overflow here.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/613)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @andrewmilson)

___
*[`crates/prover/src/core/circle.rs` line 256 at r1](https://reviewable.io/reviews/starkware-libs/stwo/613#-NyLGBnB4qDNN6YjvOJt:-NyLGBnB4qDNN6YjvOJu:b-qfpnfm) ([raw file](https://github.com/starkware-libs/stwo/blob/f070d14a12077b1d90ab18b5f9d0df1d70a4e3af/crates/prover/src/core/circle.rs#L256)):*
> ```XML
> 
>     fn add(self, rhs: Self) -> Self::Output {
>         Self(self.0 + rhs.0).reduce()
> ```

Do we need also wrapping_add here?



_Code quote:_
```XML
self.0 + rhs.0
```
___
*[`crates/prover/src/core/circle.rs` line 272 at r1](https://reviewable.io/reviews/starkware-libs/stwo/613#-NwwIiYF-y8jvc651zDW:-NyLGEw740i27Xs1KRWp:bnau2ie) ([raw file](https://github.com/starkware-libs/stwo/blob/f070d14a12077b1d90ab18b5f9d0df1d70a4e3af/crates/prover/src/core/circle.rs#L272)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Test `examples::fibonacci::tests::test_mixed_degree_multi_fibonacci` caused an overflow here.
</blockquote></details>

how it didn't overflow up until now?

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/613)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

___
*[`crates/prover/src/core/circle.rs` line 256 at r1](https://reviewable.io/reviews/starkware-libs/stwo/613#-NyLGBnB4qDNN6YjvOJt:-NyLGstJ2X9BjQtchEtV:bs1iyvl) ([raw file](https://github.com/starkware-libs/stwo/blob/f070d14a12077b1d90ab18b5f9d0df1d70a4e3af/crates/prover/src/core/circle.rs#L256)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Do we need also wrapping_add here?
</blockquote></details>

We don't because all values are in the range [0, 2^31]
___
*[`crates/prover/src/core/circle.rs` line 272 at r1](https://reviewable.io/reviews/starkware-libs/stwo/613#-NwwIiYF-y8jvc651zDW:-NyLGT59CjVmROnnswxb:bfaznng) ([raw file](https://github.com/starkware-libs/stwo/blob/f070d14a12077b1d90ab18b5f9d0df1d70a4e3af/crates/prover/src/core/circle.rs#L272)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

how it didn't overflow up until now?
</blockquote></details>

Because it's usize. All the platforms we had currently tested on where 64 bit. Since we now test Wasm (tests added to CI in the next PR) which is 32 bit it caused overflow

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/613#-:-NyLI0Ks-RP7QNlQF-9B:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Pull request merged**
