### PR TITLE
Move SecureColumn

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/478)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/478?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#479** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/479?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#478** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/478?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#463** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/463?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#477** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/477?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#476** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/476?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — APPROVED** [review]
Is fields/secure the correct place for that logic?
Seems like this is a different field from qm31.

Also the logic here fits under poly dir, WDYT?

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/478#-:-NtL_tV26EGaL6aKfXXK:b-1ag3jz)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Comment by shaharsamocha7** [comment]
Is fields/secure.rs the correct place for that logic?  
Seems like this is a different field from qm31.

Also the logic here fits under poly dir, WDYT?

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/478)* status: 6 of 8 files reviewed, 5 unresolved discussions (waiting on @alonh5 and @spapinistarkware)

___
*[`src/core/fields/secure.rs` line 12 at r2](https://reviewable.io/reviews/starkware-libs/stwo/478#-NtUfOcJEYyYcZ5U8MGZ:-NtUfOcJEYyYcZ5U8MG_:bxb617h) ([raw file](https://github.com/starkware-libs/stwo/blob/2f3df09c88a534ed5e038666a0a6a911980227c9/src/core/fields/secure.rs#L12)):*
> ```XML
> 
> pub const SECURE_EXTENSION_DEGREE: usize =
>     <SecureField as ExtensionOf<BaseField>>::EXTENSION_DEGREE;
> ```

You have a const here
https://github.com/starkware-libs/stwo/blob/e3167b024b13cb1cf4d0d39725eefeb998c5da6f/src/core/fields/qm31.rs#L11

Maybe those can be combined?



_Code quote:_
```XML
pub const SECURE_EXTENSION_DEGREE: usize =
    <SecureField as ExtensionOf<BaseField>>::EXTENSION_DEGREE;
```
___
*[`src/core/fields/secure.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/stwo/478#-NtUfb5H7h06qQP-en2x:-NtUfb5H7h06qQP-en2y:b-jimjls) ([raw file](https://github.com/starkware-libs/stwo/blob/2f3df09c88a534ed5e038666a0a6a911980227c9/src/core/fields/secure.rs#L14)):*
> ```XML
>     <SecureField as ExtensionOf<BaseField>>::EXTENSION_DEGREE;
> 
> pub struct SecureColumn<B: Backend> {
> ```

Document



_Code quote:_
```XML
pub struct SecureColumn<B: Backend> {
```
___
*[`src/core/fields/secure.rs` line 15 at r2](https://reviewable.io/reviews/starkware-libs/stwo/478#-NtUfn1J78Ip6ITlnGHK:-NtUfn1J78Ip6ITlnGHL:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/2f3df09c88a534ed5e038666a0a6a911980227c9/src/core/fields/secure.rs#L15)):*
> ```XML
> 
> pub struct SecureColumn<B: Backend> {
>     pub cols: [Col<B, BaseField>; SECURE_EXTENSION_DEGREE],
> ```





_Suggestion:_
```XML
pub columns: [Col<B, BaseField>; SECURE_EXTENSION_DEGREE],
```
___
*[`src/core/fields/secure.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/stwo/478#-NtUf6zu0iiEhEmJ23Ps:-NtUf6zu0iiEhEmJ23Pt:b4m23yt) ([raw file](https://github.com/starkware-libs/stwo/blob/2f3df09c88a534ed5e038666a0a6a911980227c9/src/core/fields/secure.rs#L45)):*
> ```XML
> }
> 
> pub struct SecureCirclePoly(pub [CPUCirclePoly; SECURE_EXTENSION_DEGREE]);
> ```

I think that the previous place of that part of this file was better.



_Code quote:_
```XML
pub struct SecureCirclePoly(pub [CPUCirclePoly; SECURE_EXTENSION_DEGREE]);
```
___
*[`src/core/fields/secure.rs` line 71 at r2](https://reviewable.io/reviews/starkware-libs/stwo/478#-NtUfxjo7SB7NwWjWx58:-NtUfxjo7SB7NwWjWx59:b38ro0p) ([raw file](https://github.com/starkware-libs/stwo/blob/2f3df09c88a534ed5e038666a0a6a911980227c9/src/core/fields/secure.rs#L71)):*
> ```XML
> }
> 
> pub fn combine_secure_value(value: [SecureField; SECURE_EXTENSION_DEGREE]) -> SecureField {
> ```

This function should be documented.



_Code quote:_
```XML
pub fn combine_secure_value(value: [SecureField; SECURE_EXTENSION_DEGREE]) -> SecureField {
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/478)* status: 4 of 8 files reviewed, 5 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

___
*[`src/core/fields/secure.rs` line 12 at r2](https://reviewable.io/reviews/starkware-libs/stwo/478#-NtUfOcJEYyYcZ5U8MGZ:-NtVIJTo-dzEa_ec5Cdq:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/2f3df09c88a534ed5e038666a0a6a911980227c9/src/core/fields/secure.rs#L12)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

You have a const here
https://github.com/starkware-libs/stwo/blob/e3167b024b13cb1cf4d0d39725eefeb998c5da6f/src/core/fields/qm31.rs#L11

Maybe those can be combined?
</blockquote></details>

Done.
___
*[`src/core/fields/secure.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/stwo/478#-NtUfb5H7h06qQP-en2x:-NtVIcQNBMSxIwvf80ri:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/2f3df09c88a534ed5e038666a0a6a911980227c9/src/core/fields/secure.rs#L14)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Document
</blockquote></details>

Done.
___
*[`src/core/fields/secure.rs` line 15 at r2](https://reviewable.io/reviews/starkware-libs/stwo/478#-NtUfn1J78Ip6ITlnGHK:-NtVIe8cB4K5GJZBeF4R:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/2f3df09c88a534ed5e038666a0a6a911980227c9/src/core/fields/secure.rs#L15)):*
> ```XML
> 
> pub struct SecureColumn<B: Backend> {
>     pub cols: [Col<B, BaseField>; SECURE_EXTENSION_DEGREE],
> ```

Done.
___
*[`src/core/fields/secure.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/stwo/478#-NtUf6zu0iiEhEmJ23Ps:-NtVKgjRDUcIlZ16K3se:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/2f3df09c88a534ed5e038666a0a6a911980227c9/src/core/fields/secure.rs#L45)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I think that the previous place of that part of this file was better.
</blockquote></details>

Done.
___
*[`src/core/fields/secure.rs` line 71 at r2](https://reviewable.io/reviews/starkware-libs/stwo/478#-NtUfxjo7SB7NwWjWx58:-NtVKh866RH6Wgk0PngM:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/2f3df09c88a534ed5e038666a0a6a911980227c9/src/core/fields/secure.rs#L71)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

This function should be documented.
</blockquote></details>

Done.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/478)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5 and @spapinistarkware)

___
*[`src/core/channel.rs` line 126 at r4](https://reviewable.io/reviews/starkware-libs/stwo/478#-NtVdhuSDjnYMc774xLn:-NtVdhuSDjnYMc774xLo:bcqhe1m) ([raw file](https://github.com/starkware-libs/stwo/blob/585aa233c92b681722813b41fd4f7fb2eb1030c4/src/core/channel.rs#L126)):*
> ```XML
>         let felts: [BaseField; FELTS_PER_HASH] = self.draw_base_felts();
>         SecureField::from_m31_array(
>             felts[..<SecureField as ExtensionOf<BaseField>>::EXTENSION_DEGREE]
> ```

Why not using the const that you defined there?



_Suggestion:_
```XML
felts[..SECURE_EXTENSION_DEGREE]
```
___
*[`src/core/poly/circle/secure_poly.rs` line 28 at r4](https://reviewable.io/reviews/starkware-libs/stwo/478#-NtVeCna19tyJUatCleJ:-NtVeCna19tyJUatCleK:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/585aa233c92b681722813b41fd4f7fb2eb1030c4/src/core/poly/circle/secure_poly.rs#L28)):*
> ```XML
> 
>     /// Evaluates the polynomial at a point, given evaluations of its composing base field
>     /// polynomials' evaluations at that point.
> ```





_Suggestion:_
```XML
    /// Evaluates the polynomial at a point, given evaluations of its composing base field
    /// polynomials at that point.
```
___
*[`src/core/poly/circle/secure_poly.rs` line 29 at r4](https://reviewable.io/reviews/starkware-libs/stwo/478#-NtVe3FgBk38d8ImuYsN:-NtVe3FgBk38d8ImuYsO:b3kre) ([raw file](https://github.com/starkware-libs/stwo/blob/585aa233c92b681722813b41fd4f7fb2eb1030c4/src/core/poly/circle/secure_poly.rs#L29)):*
> ```XML
>     /// Evaluates the polynomial at a point, given evaluations of its composing base field
>     /// polynomials' evaluations at that point.
>     pub fn eval_from_partial_evals(value: [SecureField; SECURE_EXTENSION_DEGREE]) -> SecureField {
> ```

?



_Suggestion:_
```XML
evals
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/478)* status: 9 of 11 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

___
*[`src/core/channel.rs` line 126 at r4](https://reviewable.io/reviews/starkware-libs/stwo/478#-NtVdhuSDjnYMc774xLn:-NtVimnAEhGO2a3DhMg4:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/585aa233c92b681722813b41fd4f7fb2eb1030c4/src/core/channel.rs#L126)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why not using the const that you defined there?
</blockquote></details>

Done.
___
*[`src/core/poly/circle/secure_poly.rs` line 28 at r4](https://reviewable.io/reviews/starkware-libs/stwo/478#-NtVeCna19tyJUatCleJ:-NtVfY_D-20jUADJX1eT:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/585aa233c92b681722813b41fd4f7fb2eb1030c4/src/core/poly/circle/secure_poly.rs#L28)):*
> ```XML
> 
>     /// Evaluates the polynomial at a point, given evaluations of its composing base field
>     /// polynomials' evaluations at that point.
> ```

Done.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/478#-:-NtVk-PE6Gg9tY21PGc9:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Comment by spapinistarkware** [comment]
### Merge activity

* **Mar 21, 7:23 AM EDT**: @spapinistarkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/478).

**Pull request merged**
