### PR TITLE
Create MLE eval prover component

### PR DESCRIPTION
**Pull request by andrewmilson**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/804)

### CODE REVIEW

**Comment by andrewmilson** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/804?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#804** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/804?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#803** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/803?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#802** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/802?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#801** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/801?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#800** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/800?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#799** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/799?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#798** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/798?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @andrewmilson and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/804)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @andrewmilson and @shaharsamocha7)

___
*[`crates/prover/src/examples/xor/gkr_lookups/mle_eval.rs` line 211 at r2](https://reviewable.io/reviews/starkware-libs/stwo/804#-O5IkA6k0WL0-Q6BGnUX:-O5IkA6l5scQqBbDKP85:btvtk3w) ([raw file](https://github.com/starkware-libs/stwo/blob/6b4cd3367a636fff8703984973f8b6882d37fc5f/crates/prover/src/examples/xor/gkr_lookups/mle_eval.rs#L211)):*
> ```XML
>                 .values,
>         );
>         let is_second_lde = VeryPackedBaseColumn::from(
> ```

Do we really need is_second? Can you not just take is_first at a mask offset, 1?

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/804)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/examples/xor/gkr_lookups/mle_eval.rs` line 211 at r2](https://reviewable.io/reviews/starkware-libs/stwo/804#-O5IkA6k0WL0-Q6BGnUX:-O5OYSufB2cSCseTd7VO:b-84eliv) ([raw file](https://github.com/starkware-libs/stwo/blob/6b4cd3367a636fff8703984973f8b6882d37fc5f/crates/prover/src/examples/xor/gkr_lookups/mle_eval.rs#L211)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Do we really need is_second? Can you not just take is_first at a mask offset, 1?
</blockquote></details>

Updated to use the offset but honestly might be slower due to the bad access patterns.

**Comment by andrewmilson** [comment]
*[`crates/prover/src/examples/xor/gkr_lookups/mle_eval.rs` line 211 at r2](https://reviewable.io/reviews/starkware-libs/stwo/804#-O5IkA6k0WL0-Q6BGnUX:-O5P1APH1THpW1nQcCdX:b-rgsd1y) ([raw file](https://github.com/starkware-libs/stwo/blob/6b4cd3367a636fff8703984973f8b6882d37fc5f/crates/prover/src/examples/xor/gkr_lookups/mle_eval.rs#L211)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Updated to use the offset but honestly might be slower due to the bad access patterns.
</blockquote></details>

Actually I'm wrong never mind

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/804)* status: 4 of 5 files reviewed, 5 unresolved discussions (waiting on @andrewmilson and @spapinistarkware)

___
*[`crates/prover/src/examples/xor/gkr_lookups/mle_eval.rs` line 68 at r5](https://reviewable.io/reviews/starkware-libs/stwo/804#-O7P--YdCjTOSIZTirQD:-O7P--YdCjTOSIZTirQE:b-25lofr) ([raw file](https://github.com/starkware-libs/stwo/blob/f0d2917977319fc24ca188d869ff1967f3ae60f0/crates/prover/src/examples/xor/gkr_lookups/mle_eval.rs#L68)):*
> ```XML
> 
> impl<'twiddles, 'oracle, O: MleCoeffColumnOracle> MleEvalProverComponent<'twiddles, 'oracle, O> {
>     // TODO(andrew): Some eval points may affect completeness. Document.
> ```

Can you document that?



_Code quote:_
```XML
    // TODO(andrew): Some eval points may affect completeness. Document.
```
___
*[`crates/prover/src/examples/xor/gkr_lookups/mle_eval.rs` line 89 at r5](https://reviewable.io/reviews/starkware-libs/stwo/804#-O7P0-iT-g6i5swde4LS:-O7P0-iT-g6i5swde4LT:becb8fl) ([raw file](https://github.com/starkware-libs/stwo/blob/f0d2917977319fc24ca188d869ff1967f3ae60f0/crates/prover/src/examples/xor/gkr_lookups/mle_eval.rs#L89)):*
> ```XML
> 
>         let trace_structure = mle_eval_info(interaction, n_variables).mask_offsets;
>         let trace_locations = location_allocator.next_for_structure(&trace_structure);
> ```

Does TreeSubspan also useful for the constant columns?



_Code quote:_
```XML
 let trace_locations = location_allocator.next_for_structure(&trace_structure);
```
___
*[`crates/prover/src/examples/xor/gkr_lookups/mle_eval.rs` line 172 at r5](https://reviewable.io/reviews/starkware-libs/stwo/804#-O7P2h6B3SgatRg2Fhin:-O7P2h6B3SgatRg2Fhio:bn3a526) ([raw file](https://github.com/starkware-libs/stwo/blob/f0d2917977319fc24ca188d869ff1967f3ae60f0/crates/prover/src/examples/xor/gkr_lookups/mle_eval.rs#L172)):*
> ```XML
>             carry_quotients_col_eval,
>             is_first,
>             is_second,
> ```

Should we get those as arguments?
Can we just get the constant column and then extract those values inside?



_Code quote:_
```XML
            is_first,
            is_second,
```
___
*[`crates/prover/src/examples/xor/gkr_lookups/mle_eval.rs` line 1009 at r5](https://reviewable.io/reviews/starkware-libs/stwo/804#-O7P7NZhE5jpiQOhMfjy:-O7P7NZhE5jpiQOhMfjz:b-2mjb51) ([raw file](https://github.com/starkware-libs/stwo/blob/f0d2917977319fc24ca188d869ff1967f3ae60f0/crates/prover/src/examples/xor/gkr_lookups/mle_eval.rs#L1009)):*
> ```XML
>             let log_size = mle.n_variables() as u32;
>             let trace_domain = CanonicCoset::new(log_size).circle_domain();
>             let mle_coeffs_col_by_coords = mle.clone().into_evals().into_secure_column_by_coords();
> ```

Is this copy the entire column? or what?



_Code quote:_
```XML
.clone().
```

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/804)* status: 3 of 5 files reviewed, 5 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/examples/xor/gkr_lookups/mle_eval.rs` line 68 at r5](https://reviewable.io/reviews/starkware-libs/stwo/804#-O7P--YdCjTOSIZTirQD:-O7WbeuxC37eDtEib0vL:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/f0d2917977319fc24ca188d869ff1967f3ae60f0/crates/prover/src/examples/xor/gkr_lookups/mle_eval.rs#L68)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can you document that?
</blockquote></details>

Done.
___
*[`crates/prover/src/examples/xor/gkr_lookups/mle_eval.rs` line 89 at r5](https://reviewable.io/reviews/starkware-libs/stwo/804#-O7P0-iT-g6i5swde4LS:-O7Wbi_mBGj1wIEINl-A:b-jws8ov) ([raw file](https://github.com/starkware-libs/stwo/blob/f0d2917977319fc24ca188d869ff1967f3ae60f0/crates/prover/src/examples/xor/gkr_lookups/mle_eval.rs#L89)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Does TreeSubspan also useful for the constant columns?
</blockquote></details>

It can as constant columns are now. 
It treats the constant interaction tree just like any interaction tree.
___
*[`crates/prover/src/examples/xor/gkr_lookups/mle_eval.rs` line 172 at r5](https://reviewable.io/reviews/starkware-libs/stwo/804#-O7P2h6B3SgatRg2Fhin:-O7Wc4JI2Bd8cArpi4DE:bkd5ega) ([raw file](https://github.com/starkware-libs/stwo/blob/f0d2917977319fc24ca188d869ff1967f3ae60f0/crates/prover/src/examples/xor/gkr_lookups/mle_eval.rs#L172)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Should we get those as arguments?
Can we just get the constant column and then extract those values inside?
</blockquote></details>

Added a TODO
___
*[`crates/prover/src/examples/xor/gkr_lookups/mle_eval.rs` line 1009 at r5](https://reviewable.io/reviews/starkware-libs/stwo/804#-O7P7NZhE5jpiQOhMfjy:-O7Wd10W3piwdkox9dUo:bfff3m8) ([raw file](https://github.com/starkware-libs/stwo/blob/f0d2917977319fc24ca188d869ff1967f3ae60f0/crates/prover/src/examples/xor/gkr_lookups/mle_eval.rs#L1009)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Is this copy the entire column? or what?
</blockquote></details>

Yeah, it's just a test function

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r3, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/804#-:-O7ibvSeA9ETk_Cx21M_:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

**Pull request merged**
