### PR TITLE
uninitialized trace

### PR DESCRIPTION
**Pull request by ohad-agadi**

### CODE REVIEW

**Comment by ohad-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/948?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#948** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/948?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/948?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#945** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/945?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#946** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/946?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#944** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/944?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#943** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/943?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#942** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/942?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/948)* status: all files reviewed, 3 unresolved discussions (waiting on @ohad-starkware)

___
*[`crates/air_utils/src/trace/component_trace.rs` line 59 at r2](https://reviewable.io/reviews/starkware-libs/stwo/948#-OFGB8pm3WMa0n29V_PN:-OFGB8pm3WMa0n29V_PO:b-15ujr1) ([raw file](https://github.com/starkware-libs/stwo/blob/5b504ae20bfcc6d06425c6e64e491279bf1e5809/crates/air_utils/src/trace/component_trace.rs#L59)):*
> ```XML
>     /// Creates a new `ComponentTrace` with all values initialized to zero.
>     /// The number of rows in each column is `2^log_size`, padded to a multiple of [`N_LANES`].
>     pub fn zeroed(log_size: u32) -> Self {
> ```

I think that although this is trivial function we should test the case of small (<16) size column



_Code quote:_
```XML
pub fn zeroed(log_size: u32) -> Self {
```
___
*[`crates/air_utils/src/trace/component_trace.rs` line 63 at r2](https://reviewable.io/reviews/starkware-libs/stwo/948#-OFGAgco2Oebce0UeRVV:-OFGAgcpAGCWr2fOLZk6:b-iuwm5c) ([raw file](https://github.com/starkware-libs/stwo/blob/5b504ae20bfcc6d06425c6e64e491279bf1e5809/crates/air_utils/src/trace/component_trace.rs#L63)):*
> ```XML
>         let n_simd_elems = 1 << (log_size - LOG_N_LANES);
>         let data = [(); N].map(|_| vec![PackedM31::zeroed(); n_simd_elems]);
>         Self { data, log_size }
> ```

What happens here if log_size is indeed smaller than LOG_N_LANES?
We do need the information that there was some padding, no?



_Code quote:_
```XML
        let log_size = std::cmp::max(log_size, LOG_N_LANES);
        let n_simd_elems = 1 << (log_size - LOG_N_LANES);
        let data = [(); N].map(|_| vec![PackedM31::zeroed(); n_simd_elems]);
        Self { data, log_size }
```
___
*[`crates/air_utils/src/trace/component_trace.rs` line 72 at r2](https://reviewable.io/reviews/starkware-libs/stwo/948#-OFGAzKQAVrGfEtbe4Ph:-OFGAzKQAVrGfEtbe4Pi:bb7od0r) ([raw file](https://github.com/starkware-libs/stwo/blob/5b504ae20bfcc6d06425c6e64e491279bf1e5809/crates/air_utils/src/trace/component_trace.rs#L72)):*
> ```XML
>     #[allow(clippy::uninit_vec)]
>     pub unsafe fn uninitialized(log_size: u32) -> Self {
>         let log_size = std::cmp::max(log_size, LOG_N_LANES);
> ```

same



_Code quote:_
```XML
let log_size = std::cmp::max(log_size, LOG_N_LANES);
```

**Comment by ohad-starkware** [comment]
*[`crates/air_utils/src/trace/component_trace.rs` line 63 at r2](https://reviewable.io/reviews/starkware-libs/stwo/948#-OFGAgco2Oebce0UeRVV:-OFGRmym9exKq7O_V-6o:b-92lgz1) ([raw file](https://github.com/starkware-libs/stwo/blob/5b504ae20bfcc6d06425c6e64e491279bf1e5809/crates/air_utils/src/trace/component_trace.rs#L63)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

What happens here if log_size is indeed smaller than LOG_N_LANES?
We do need the information that there was some padding, no?
</blockquote></details>

it's doced

**Review by ohad-agadi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/948)* status: all files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/air_utils/src/trace/component_trace.rs` line 59 at r2](https://reviewable.io/reviews/starkware-libs/stwo/948#-OFGB8pm3WMa0n29V_PN:-OFGjxwJ9dmbQhY5QzC-:bb7f2mf) ([raw file](https://github.com/starkware-libs/stwo/blob/5b504ae20bfcc6d06425c6e64e491279bf1e5809/crates/air_utils/src/trace/component_trace.rs#L59)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I think that although this is trivial function we should test the case of small (<16) size column
</blockquote></details>

done
___
*[`crates/air_utils/src/trace/component_trace.rs` line 72 at r2](https://reviewable.io/reviews/starkware-libs/stwo/948#-OFGAzKQAVrGfEtbe4Ph:-OFGkUUM3p87qI4YXqBB:bb7od0r) ([raw file](https://github.com/starkware-libs/stwo/blob/5b504ae20bfcc6d06425c6e64e491279bf1e5809/crates/air_utils/src/trace/component_trace.rs#L72)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

same
</blockquote></details>

same

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/948)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @ohad-starkware)

___
*[`crates/air_utils/src/trace/component_trace.rs` line 59 at r2](https://reviewable.io/reviews/starkware-libs/stwo/948#-OFGB8pm3WMa0n29V_PN:-OFGrXNG2SpiFXb8pylV:b44r9f4) ([raw file](https://github.com/starkware-libs/stwo/blob/5b504ae20bfcc6d06425c6e64e491279bf1e5809/crates/air_utils/src/trace/component_trace.rs#L59)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

done
</blockquote></details>

I think that we should restrict the case that log_size < 4 in that case

**Review by ohad-agadi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/948)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/air_utils/src/trace/component_trace.rs` line 59 at r2](https://reviewable.io/reviews/starkware-libs/stwo/948#-OFGB8pm3WMa0n29V_PN:-OFH5t9R0DIVdEHv0inW:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/5b504ae20bfcc6d06425c6e64e491279bf1e5809/crates/air_utils/src/trace/component_trace.rs#L59)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I think that we should restrict the case that log_size < 4 in that case
</blockquote></details>

Done.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/948)* status: all files reviewed, 2 unresolved discussions (waiting on @ohad-starkware)

___
*[`crates/air_utils/src/trace/component_trace.rs` line 74 at r4](https://reviewable.io/reviews/starkware-libs/stwo/948#-OFH7HJv6o6zlNZj5hVP:-OFH7HJw-4MNdI0-XI8l:b-bkeriv) ([raw file](https://github.com/starkware-libs/stwo/blob/32803762378a660832e6ae3e9e6abc747c13da0a/crates/air_utils/src/trace/component_trace.rs#L74)):*
> ```XML
>     /// # Safety
>     /// The caller must ensure that the column is populated before being used.
>     /// The number of rows in each column is `2^log_size`, padded to a multiple of [`N_LANES`].
> ```

Fix comment
Document the panic case
Same for the zeroed function



_Code quote:_
```XML
    /// The caller must ensure that the column is populated before being used.
    /// The number of rows in each column is `2^log_size`, padded to a multiple of [`N_LANES`].
```
___
*[`crates/air_utils/src/trace/component_trace.rs` line 179 at r4](https://reviewable.io/reviews/starkware-libs/stwo/948#-OFH712jAQEMW8S5iFLb:-OFH712jAQEMW8S5iFLc:bey9m21) ([raw file](https://github.com/starkware-libs/stwo/blob/32803762378a660832e6ae3e9e6abc747c13da0a/crates/air_utils/src/trace/component_trace.rs#L179)):*
> ```XML
>         const LOG_SIZE: u32 = 3;
>         unsafe { super::ComponentTrace::<N_COLUMNS>::uninitialized(LOG_SIZE) };
>     }
> ```

Great!
So maybe add another success test?



_Code quote:_
```XML
    #[should_panic = "log_size < LOG_N_LANES not supported!"]
    #[test]
    fn test_log_size_too_small() {
        const N_COLUMNS: usize = 3;
        const LOG_SIZE: u32 = 3;
        unsafe { super::ComponentTrace::<N_COLUMNS>::uninitialized(LOG_SIZE) };
    }
```

**Review by ohad-agadi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/948)* status: all files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/air_utils/src/trace/component_trace.rs` line 74 at r4](https://reviewable.io/reviews/starkware-libs/stwo/948#-OFH7HJv6o6zlNZj5hVP:-OFHH2jg-bVpMeuq9nE-:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/32803762378a660832e6ae3e9e6abc747c13da0a/crates/air_utils/src/trace/component_trace.rs#L74)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Fix comment
Document the panic case
Same for the zeroed function
</blockquote></details>

Done.
___
*[`crates/air_utils/src/trace/component_trace.rs` line 179 at r4](https://reviewable.io/reviews/starkware-libs/stwo/948#-OFH712jAQEMW8S5iFLb:-OFHGcJC1KnDTQwDac0T:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/32803762378a660832e6ae3e9e6abc747c13da0a/crates/air_utils/src/trace/component_trace.rs#L179)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Great!
So maybe add another success test?
</blockquote></details>

Done.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/948)* status: all files reviewed, 2 unresolved discussions (waiting on @ohad-starkware)

___
*[`crates/air_utils/src/trace/component_trace.rs` line 179 at r5](https://reviewable.io/reviews/starkware-libs/stwo/948#-OFHOpGhC9LC3z-kVoZB:-OFHOpGhC9LC3z-kVoZC:bjjnj4k) ([raw file](https://github.com/starkware-libs/stwo/blob/764ac8ab81f3ce37df1ccbb260248e026f91d340/crates/air_utils/src/trace/component_trace.rs#L179)):*
> ```XML
>     #[should_panic = "log_size < LOG_N_LANES not supported!"]
>     #[test]
>     fn test_log_size_too_small() {
> ```

same
and reorder tests



_Suggestion:_
```XML
fn fn test_component_trace_uninitialized_fails() {
```
___
*[`crates/air_utils/src/trace/component_trace.rs` line 186 at r5](https://reviewable.io/reviews/starkware-libs/stwo/948#-OFHOfxDCKc9-bp8CXEm:-OFHOfxDCKc9-bp8CXEn:bny8xt) ([raw file](https://github.com/starkware-libs/stwo/blob/764ac8ab81f3ce37df1ccbb260248e026f91d340/crates/air_utils/src/trace/component_trace.rs#L186)):*
> ```XML
> 
>     #[test]
>     fn test_boundary_log_size() {
> ```

Consider to rename



_Suggestion:_
```XML
fn test_component_trace_uninitialized_success() {
```

**Review by ohad-agadi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/948)* status: all files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/air_utils/src/trace/component_trace.rs` line 179 at r5](https://reviewable.io/reviews/starkware-libs/stwo/948#-OFHOpGhC9LC3z-kVoZB:-OFHVcorAGVFaKpySlHK:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/764ac8ab81f3ce37df1ccbb260248e026f91d340/crates/air_utils/src/trace/component_trace.rs#L179)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

same
and reorder tests
</blockquote></details>

Done.
___
*[`crates/air_utils/src/trace/component_trace.rs` line 186 at r5](https://reviewable.io/reviews/starkware-libs/stwo/948#-OFHOfxDCKc9-bp8CXEm:-OFHVd796RQIQD6bC2cg:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/764ac8ab81f3ce37df1ccbb260248e026f91d340/crates/air_utils/src/trace/component_trace.rs#L186)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Consider to rename
</blockquote></details>

Done.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/948#-:-OFHlPik4ICyghOR4bq0:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ohad-starkware)

**Comment by ohad-starkware** [comment]
### Merge activity

* **Dec 29, 9:27 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/948).

**Pull request merged**
