### PR TITLE
Add build trace functions for MLE eval component

### PR DESCRIPTION
**Pull request by andrewmilson**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/803)

### CODE REVIEW

**Comment by andrewmilson** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/803?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#804** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/804?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#803** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/803?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#802** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/802?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#801** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/801?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#800** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/800?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#799** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/799?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#798** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/798?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @andrewmilson and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/803)* status: all files reviewed, 2 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`crates/prover/src/examples/xor/gkr_lookups/mle_eval.rs` line 156 at r1](https://reviewable.io/reviews/starkware-libs/stwo/803#-O5DVV7R-kSz_GlBbA7y:-O5DVV7R-kSz_GlBbA7z:brv6pjy) ([raw file](https://github.com/starkware-libs/stwo/blob/fd8ce1f3ef4d79d337a02ace5ced97931be42670/crates/prover/src/examples/xor/gkr_lookups/mle_eval.rs#L156)):*
> ```XML
> 
>     #[cfg(test)]
>     assert_eq!(claim, mle.eval_at_point(eval_point));
> ```

Consider



_Suggestion:_
```XML
    debug_assert_eq!(claim, mle.eval_at_point(eval_point));
```
___
*[`crates/prover/src/examples/xor/gkr_lookups/mle_eval.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/stwo/803#-O5DW8onB1uLCqHRjxpY:-O5DW8onB1uLCqHRjxpZ:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/fd8ce1f3ef4d79d337a02ace5ced97931be42670/crates/prover/src/examples/xor/gkr_lookups/mle_eval.rs#L159)):*
> ```XML
>     let shift = claim / BaseField::from(mle.len());
>     let packed_shift_coords = PackedSecureField::broadcast(shift).into_packed_m31s();
>     let mut shifted_mle_terms_cols = mle_terms_cols.clone();
> ```





_Suggestion:_
```XML
let mut shifted_mle_terms_cols = mle_terms_cols;
```
___
*[`crates/prover/src/examples/xor/gkr_lookups/mle_eval.rs` line 188 at r1](https://reviewable.io/reviews/starkware-libs/stwo/803#-O5DWHPI2_EUocb73Mo4:-O5DWHPI2_EUocb73Mo5:b-c7jj5) ([raw file](https://github.com/starkware-libs/stwo/blob/fd8ce1f3ef4d79d337a02ace5ced97931be42670/crates/prover/src/examples/xor/gkr_lookups/mle_eval.rs#L188)):*
> ```XML
> ) -> Vec<CircleEvaluation<SimdBackend, BaseField, BitReversedOrder>> {
>     let log_size = N_VARIABLES as u32;
>     vec![gen_is_first(log_size)]
> ```

Techinically, you can also compute this using vanishing cosets, same way you did for the smaller ones.

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/803)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/examples/xor/gkr_lookups/mle_eval.rs` line 156 at r1](https://reviewable.io/reviews/starkware-libs/stwo/803#-O5DVV7R-kSz_GlBbA7y:-O5EWj2x7PZFm4bTBchE:blxoehw) ([raw file](https://github.com/starkware-libs/stwo/blob/fd8ce1f3ef4d79d337a02ace5ced97931be42670/crates/prover/src/examples/xor/gkr_lookups/mle_eval.rs#L156)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Consider
</blockquote></details>

need the cfg(test) since eval_at_point defined behind cfg(test)
___
*[`crates/prover/src/examples/xor/gkr_lookups/mle_eval.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/stwo/803#-O5DW8onB1uLCqHRjxpY:-O5EWazn8LobN6VK2-R-:b32wy2) ([raw file](https://github.com/starkware-libs/stwo/blob/fd8ce1f3ef4d79d337a02ace5ced97931be42670/crates/prover/src/examples/xor/gkr_lookups/mle_eval.rs#L159)):*
> ```XML
>     let shift = claim / BaseField::from(mle.len());
>     let packed_shift_coords = PackedSecureField::broadcast(shift).into_packed_m31s();
>     let mut shifted_mle_terms_cols = mle_terms_cols.clone();
> ```

ty
___
*[`crates/prover/src/examples/xor/gkr_lookups/mle_eval.rs` line 188 at r1](https://reviewable.io/reviews/starkware-libs/stwo/803#-O5DWHPI2_EUocb73Mo4:-O5EWrfKA5wkkgAx_XAe:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/fd8ce1f3ef4d79d337a02ace5ced97931be42670/crates/prover/src/examples/xor/gkr_lookups/mle_eval.rs#L188)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Techinically, you can also compute this using vanishing cosets, same way you did for the smaller ones.
</blockquote></details>

Done.

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/803)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Pull request merged**
