### PR TITLE
Commitment Scheme evaluation per size

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/483)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/483?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#483** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/483?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#482** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/482?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#481** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/481?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#480** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/480?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#479** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/479?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#478** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/478?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#463** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/463?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#477** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/477?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#476** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/476?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by alonh5 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/483)* status: 0 of 9 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo/483#-NtpLJVo0neiaMY5-AMQ:-NtpLJVo0neiaMY5-AMR:b-o19c4f) (no related file):*
Please separate PR to (1) moving/refactoring/extracting code (2) logical/implementation changes.

___
___
*[`src/core/fri.rs` line 425 at r2](https://reviewable.io/reviews/starkware-libs/stwo/483#-NtpInM0CAyyPuXfBtP4:-NtpInM0CAyyPuXfBtP5:bku85ym) ([raw file](https://github.com/starkware-libs/stwo/blob/78514480159caf5175b2f8fef92d82fe67cdb144/src/core/fri.rs#L425)):*
> ```XML
>         assert_eq!(queries.log_domain_size, self.expected_query_log_domain_size);
>         assert_eq!(decommitted_values.len(), self.column_bounds.len());
>         println!("decommitted_values: {decommitted_values:#?}");
> ```

Forgot to remove?



_Code quote:_
```XML
println!("decommitted_values: {decommitted_values:#?}");
```
___
*[`src/core/commitment_scheme/prover.rs` line 72 at r2](https://reviewable.io/reviews/starkware-libs/stwo/483#-NtpJhPG2JDMzcfidLzm:-NtpJhPG2JDMzcfidLzn:b-d8h78o) ([raw file](https://github.com/starkware-libs/stwo/blob/78514480159caf5175b2f8fef92d82fe67cdb144/src/core/commitment_scheme/prover.rs#L72)):*
> ```XML
>     ) -> CommitmentSchemeProof {
>         // Evaluate polynomials on open points.
>         let openings = self
> ```

Can we stay with the "sample" terminology rather the "opening"? Same for whole PR.



_Suggestion:_
```XML
samples
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/483)* status: 0 of 11 files reviewed, 3 unresolved discussions (waiting on @alonh5)

*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo/483#-NtpLJVo0neiaMY5-AMQ:-NtpWBNa-hwwxsb6q5h4:b-896fix) (no related file):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Please separate PR to (1) moving/refactoring/extracting code (2) logical/implementation changes.
</blockquote></details>

Done.

___
___
*[`src/core/fri.rs` line 425 at r2](https://reviewable.io/reviews/starkware-libs/stwo/483#-NtpInM0CAyyPuXfBtP4:-NtpXK3f2bA26MKkHhfP:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/78514480159caf5175b2f8fef92d82fe67cdb144/src/core/fri.rs#L425)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Forgot to remove?
</blockquote></details>

Done.
___
*[`src/core/commitment_scheme/prover.rs` line 72 at r2](https://reviewable.io/reviews/starkware-libs/stwo/483#-NtpJhPG2JDMzcfidLzm:-NtpWyboDf8a_ktdIT9a:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/78514480159caf5175b2f8fef92d82fe67cdb144/src/core/commitment_scheme/prover.rs#L72)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Can we stay with the "sample" terminology rather the "opening"? Same for whole PR.
</blockquote></details>

Done.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r1, 2 of 4 files at r2, 3 of 3 files at r3, 5 of 5 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/483)* status: all files reviewed, 12 unresolved discussions (waiting on @spapinistarkware)

___
*[`src/core/commitment_scheme/prover.rs` line 89 at r5](https://reviewable.io/reviews/starkware-libs/stwo/483#-NtpdMJKCO5wp7uYkZ4b:-NtpdMJKCO5wp7uYkZ4c:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/4969daf4835e807454354e47b61039ae72873f92/src/core/commitment_scheme/prover.rs#L89)):*
> ```XML
>         channel.mix_felts(&proved_values.clone().flatten_cols());
> 
>         // Compute oods quotients for boundary constraints on sampled_points.
> ```





_Suggestion:_
```XML
the sampled points
```
___
*[`src/core/commitment_scheme/prover.rs` line 92 at r5](https://reviewable.io/reviews/starkware-libs/stwo/483#-NtprYN8670Tu2A4iDEp:-NtprYN8670Tu2A4iDEq:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/4969daf4835e807454354e47b61039ae72873f92/src/core/commitment_scheme/prover.rs#L92)):*
> ```XML
>         let columns = self.evaluations().flatten();
>         let quotients =
>             compute_fri_quotients(&columns[..], &samples.flatten(), channel.draw_felt());
> ```





_Suggestion:_
```XML
&columns
```
___
*[`src/core/commitment_scheme/prover.rs` line 134 at r5](https://reviewable.io/reviews/starkware-libs/stwo/483#-NtpepQ147LYMvk-lsIr:-NtpepQ147LYMvk-lsIs:bcgjvre) ([raw file](https://github.com/starkware-libs/stwo/blob/4969daf4835e807454354e47b61039ae72873f92/src/core/commitment_scheme/prover.rs#L134)):*
> ```XML
> #[derive(Debug)]
> pub struct CommitmentSchemeProof {
>     pub sampled_values: TreeVec<ColumnVec<Vec<SecureField>>>,
> ```

Why this change?



_Code quote:_
```XML
sampled_values
```
___
*[`src/core/commitment_scheme/quotients.rs` line 35 at r5](https://reviewable.io/reviews/starkware-libs/stwo/483#-Ntpu-zG6PND5ldj8eQQ:-Ntpu-zG6PND5ldj8eQR:bc0cgo0) ([raw file](https://github.com/starkware-libs/stwo/blob/4969daf4835e807454354e47b61039ae72873f92/src/core/commitment_scheme/quotients.rs#L35)):*
> ```XML
> 
> /// A batch of column samplings at a point.
> pub struct ColumnSampleBatch {
> ```

This is technically a row, right? Can we call it that?



_Suggestion:_
```XML
ColumnSampleRow
```
___
*[`src/core/commitment_scheme/quotients.rs` line 42 at r5](https://reviewable.io/reviews/starkware-libs/stwo/483#-Ntpi8bU8RtFSqkxO2Hb:-Ntpi8bU8RtFSqkxO2Hc:b-8wqsu5) ([raw file](https://github.com/starkware-libs/stwo/blob/4969daf4835e807454354e47b61039ae72873f92/src/core/commitment_scheme/quotients.rs#L42)):*
> ```XML
> }
> impl ColumnSampleBatch {
>     /// Groups column opening by opening point.
> ```

opening -> sample in this file too.



_Suggestion:_
```XML
sample
```
___
*[`src/core/commitment_scheme/quotients.rs` line 45 at r5](https://reviewable.io/reviews/starkware-libs/stwo/483#-Ntpv343DPUIjFzqREup:-Ntpv343DPUIjFzqREuq:b-n295zn) ([raw file](https://github.com/starkware-libs/stwo/blob/4969daf4835e807454354e47b61039ae72873f92/src/core/commitment_scheme/quotients.rs#L45)):*
> ```XML
>     /// # Arguments
>     /// opening: For each column, a vector of openings.
>     pub fn new(openings: &[&Vec<PointSample>]) -> Vec<Self> {
> ```

This is effectively transposing the samples. I think this can be made simpler, consider using a mapping as an intermediate data structure.
___
*[`src/core/commitment_scheme/quotients.rs` line 74 at r5](https://reviewable.io/reviews/starkware-libs/stwo/483#-NtpqPjRAkOTt-056pTD:-NtpqPjRAkOTt-056pTE:b45h) ([raw file](https://github.com/starkware-libs/stwo/blob/4969daf4835e807454354e47b61039ae72873f92/src/core/commitment_scheme/quotients.rs#L74)):*
> ```XML
>     random_coeff: SecureField,
> ) -> Vec<SecureEvaluation<B>> {
>     izip!(columns, samples)
> ```





_Suggestion:_
```XML
zip
```
___
*[`src/core/commitment_scheme/quotients.rs` line 75 at r5](https://reviewable.io/reviews/starkware-libs/stwo/483#-NtpsElW5BrEABaFbdQS:-NtpsElW5BrEABaFbdQT:b-dowz3n) ([raw file](https://github.com/starkware-libs/stwo/blob/4969daf4835e807454354e47b61039ae72873f92/src/core/commitment_scheme/quotients.rs#L75)):*
> ```XML
> ) -> Vec<SecureEvaluation<B>> {
>     izip!(columns, samples)
>         .group_by(|(c, _)| c.domain.log_size())
> ```

From what I see `group_by` only groups adjacent element with the same defined key. We want to group all columns of the same size regardless of location, right?
Consider using a mapping as an intermediate data structure.
Same below.



_Code quote:_
```XML
.group_by
```
___
*[`src/core/commitment_scheme/quotients.rs` line 79 at r5](https://reviewable.io/reviews/starkware-libs/stwo/483#-Ntppn_O0NUCQSZxnNwP:-Ntppn_O0NUCQSZxnNwQ:b-546ssx) ([raw file](https://github.com/starkware-libs/stwo/blob/4969daf4835e807454354e47b61039ae72873f92/src/core/commitment_scheme/quotients.rs#L79)):*
> ```XML
>         .sorted_by_key(|(log_size, _)| Reverse(*log_size))
>         .map(|(log_size, tuples)| {
>             let (columns, openings): (Vec<_>, Vec<_>) = multiunzip(tuples);
> ```

No need for multiple unzip.



_Suggestion:_
```XML
tuples.unzip()
```
___
*[`src/core/commitment_scheme/quotients.rs` line 160 at r5](https://reviewable.io/reviews/starkware-libs/stwo/483#-Ntq0lPI92ANwPxEBhoM:-Ntq0lPJ9L_3umQNIIeh:booae9t) ([raw file](https://github.com/starkware-libs/stwo/blob/4969daf4835e807454354e47b61039ae72873f92/src/core/commitment_scheme/quotients.rs#L160)):*
> ```XML
>             })
>             .collect(),
>     );
> ```

refactor into a for loop for readability?



_Code quote:_
```XML
    let res = SparseCircleEvaluation::new(
        query_domain
            .iter()
            .map(|subdomain| {
                let domain = subdomain.to_circle_domain(&commitment_domain);
                let column_evals = queried_values_per_column
                    .iter_mut()
                    .map(|q| {
                        CircleEvaluation::new(domain, q.take(domain.size()).copied().collect_vec())
                    })
                    .collect_vec();
                // TODO(spapini): bit reverse iterator.
                let values = (0..domain.size())
                    .map(|row| {
                        let domain_point = domain.at(bit_reverse_index(row, log_size));
                        accumulate_row_quotients(
                            &batched_openings,
                            &column_evals.iter().collect_vec(),
                            row,
                            random_coeff,
                            domain_point,
                        )
                    })
                    .collect();
                CircleEvaluation::new(domain, values)
            })
            .collect(),
    );
```
___
*[`src/core/commitment_scheme/verifier.rs` line 69 at r5](https://reviewable.io/reviews/starkware-libs/stwo/483#-NtphF5uCbhM2kMhMzUg:-NtphF5uCbhM2kMhMzUh:b-b98cmb) ([raw file](https://github.com/starkware-libs/stwo/blob/2f03ecd504e8a1d372bc9b315f84d82129a2cce8/src/core/commitment_scheme/verifier.rs#L69)):*
> ```XML
>                 vec![CirclePolyDegreeBound::new(log_size); prove_points.len()]
>             })
>             .flatten_cols_rev();
> ```

This can be removed now, right?



_Code quote:_
```XML
flatten_cols_rev
```
___
*[`src/core/commitment_scheme/verifier.rs` line 83 at r5](https://reviewable.io/reviews/starkware-libs/stwo/483#-NtpgTF62krJ5JnXXmhS:-NtpgTF62krJ5JnXXmhT:bt7n725) ([raw file](https://github.com/starkware-libs/stwo/blob/4969daf4835e807454354e47b61039ae72873f92/src/core/commitment_scheme/verifier.rs#L83)):*
> ```XML
> 
>         // Get FRI query domains.
>         let fri_query_domains = fri_verifier.column_sample_positions(channel);
> ```

I think these are actually the opening positions - the positions needed to be opened with respect to the queries. Sorry for the back and forth.



_Suggestion:_
```XML
column_opening_positions
```

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 1 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/483)* status: all files reviewed, 6 unresolved discussions (waiting on @alonh5)

___
*[`src/core/commitment_scheme/prover.rs` line 134 at r5](https://reviewable.io/reviews/starkware-libs/stwo/483#-NtpepQ147LYMvk-lsIr:-Ntq9YW6579mCVeLNeNU:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/4969daf4835e807454354e47b61039ae72873f92/src/core/commitment_scheme/prover.rs#L134)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Why this change?
</blockquote></details>

Done.
___
*[`src/core/commitment_scheme/quotients.rs` line 42 at r5](https://reviewable.io/reviews/starkware-libs/stwo/483#-Ntpi8bU8RtFSqkxO2Hb:-Ntq3qjlA92t8iFQFyDk:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/4969daf4835e807454354e47b61039ae72873f92/src/core/commitment_scheme/quotients.rs#L42)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

opening -> sample in this file too.
</blockquote></details>

Done.
___
*[`src/core/commitment_scheme/quotients.rs` line 45 at r5](https://reviewable.io/reviews/starkware-libs/stwo/483#-Ntpv343DPUIjFzqREup:-Ntq5BV3373xQ78vo3Ci:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/4969daf4835e807454354e47b61039ae72873f92/src/core/commitment_scheme/quotients.rs#L45)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

This is effectively transposing the samples. I think this can be made simpler, consider using a mapping as an intermediate data structure.
</blockquote></details>

Done.
___
*[`src/core/commitment_scheme/quotients.rs` line 75 at r5](https://reviewable.io/reviews/starkware-libs/stwo/483#-NtpsElW5BrEABaFbdQS:-Ntq5qYOAEO-w_YA1Syw:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/4969daf4835e807454354e47b61039ae72873f92/src/core/commitment_scheme/quotients.rs#L75)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

From what I see `group_by` only groups adjacent element with the same defined key. We want to group all columns of the same size regardless of location, right?
Consider using a mapping as an intermediate data structure.
Same below.
</blockquote></details>

Done.
___
*[`src/core/commitment_scheme/verifier.rs` line 69 at r5](https://reviewable.io/reviews/starkware-libs/stwo/483#-NtphF5uCbhM2kMhMzUg:-Ntq8NYQ7C5iZfwKl9Xf:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/2f03ecd504e8a1d372bc9b315f84d82129a2cce8/src/core/commitment_scheme/verifier.rs#L69)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

This can be removed now, right?
</blockquote></details>

Done.
___
*[`src/core/commitment_scheme/verifier.rs` line 83 at r5](https://reviewable.io/reviews/starkware-libs/stwo/483#-NtpgTF62krJ5JnXXmhS:-Ntq9VgO9D1a-PH30c-r:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/4969daf4835e807454354e47b61039ae72873f92/src/core/commitment_scheme/verifier.rs#L83)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I think these are actually the opening positions - the positions needed to be opened with respect to the queries. Sorry for the back and forth.
</blockquote></details>

Done.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/483)* status: all files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`src/core/commitment_scheme/quotients.rs` line 45 at r5](https://reviewable.io/reviews/starkware-libs/stwo/483#-Ntpv343DPUIjFzqREup:-NtqC_FBENzDmA6TUhhJ:bb70w76) ([raw file](https://github.com/starkware-libs/stwo/blob/4969daf4835e807454354e47b61039ae72873f92/src/core/commitment_scheme/quotients.rs#L45)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nice
___
*[`src/core/commitment_scheme/quotients.rs` line 95 at r7](https://reviewable.io/reviews/starkware-libs/stwo/483#-NtqDwUrA0kXEAhXsoam:-NtqDwUrA0kXEAhXsoan:b-ikt57h) ([raw file](https://github.com/starkware-libs/stwo/blob/17ba74a73248dd75dd5fa7d1cc01d3becd32e83e/src/core/commitment_scheme/quotients.rs#L95)):*
> ```XML
> pub fn fri_answers(
>     column_log_sizes: Vec<u32>,
>     openings: &[Vec<PointSample>],
> ```

There are still 12 places in this file this needs to be modified



_Suggestion:_
```XML
samples
```
___
*[`src/core/commitment_scheme/quotients.rs` line 137 at r7](https://reviewable.io/reviews/starkware-libs/stwo/483#-NtqFjWIBr2R6IYwPBIx:-NtqFjWJ6h04oK_JJ0Rv:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/17ba74a73248dd75dd5fa7d1cc01d3becd32e83e/src/core/commitment_scheme/quotients.rs#L137)):*
> ```XML
>         .collect_vec();
> 
>     let mut result = Vec::new();
> ```





_Suggestion:_
```XML
evals
```
___
*[`src/core/commitment_scheme/quotients.rs` line 141 at r7](https://reviewable.io/reviews/starkware-libs/stwo/483#-NtqH4-75T5XL2f4V1oE:-NtqH4-8EKjugKKc2SMz:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/17ba74a73248dd75dd5fa7d1cc01d3becd32e83e/src/core/commitment_scheme/quotients.rs#L141)):*
> ```XML
>         let domain = subdomain.to_circle_domain(&commitment_domain);
>         let mut column_evals = Vec::new();
>         for q in queried_values_per_column.iter_mut() {
> ```





_Suggestion:_
```XML
for column_values in
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/483)* status: 11 of 12 files reviewed, 3 unresolved discussions (waiting on @alonh5)

___
*[`src/core/commitment_scheme/quotients.rs` line 95 at r7](https://reviewable.io/reviews/starkware-libs/stwo/483#-NtqDwUrA0kXEAhXsoam:-NttHbqh-UaeNdx0eU8K:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/17ba74a73248dd75dd5fa7d1cc01d3becd32e83e/src/core/commitment_scheme/quotients.rs#L95)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

There are still 12 places in this file this needs to be modified
</blockquote></details>

Done.
___
*[`src/core/commitment_scheme/quotients.rs` line 137 at r7](https://reviewable.io/reviews/starkware-libs/stwo/483#-NtqFjWIBr2R6IYwPBIx:-NttHzBgDADgMhiaXBS9:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/17ba74a73248dd75dd5fa7d1cc01d3becd32e83e/src/core/commitment_scheme/quotients.rs#L137)):*
> ```XML
>         .collect_vec();
> 
>     let mut result = Vec::new();
> ```

Done.
___
*[`src/core/commitment_scheme/quotients.rs` line 141 at r7](https://reviewable.io/reviews/starkware-libs/stwo/483#-NtqH4-75T5XL2f4V1oE:-NttHz021YRKM3caEApN:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/17ba74a73248dd75dd5fa7d1cc01d3becd32e83e/src/core/commitment_scheme/quotients.rs#L141)):*
> ```XML
>         let domain = subdomain.to_circle_domain(&commitment_domain);
>         let mut column_evals = Vec::new();
>         for q in queried_values_per_column.iter_mut() {
> ```

Done.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/483#-:-Ntttrzq0YUFbtYgl42I:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by alonh5 — APPROVED** [review]
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/483)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
