### PR TITLE
avx merkle

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/528)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/528?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#528** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/528?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#527** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/527?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#526** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/526?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#525** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/525?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#518** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/518?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by spapinistarkware** [comment]
### Merge activity

* **Apr 3, 2:35 AM EDT**: [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/528) rebased this pull request after merging its parent, because this pull request is set to merge when ready.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r1, 2 of 3 files at r3, 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/528)* status: 4 of 7 files reviewed, 6 unresolved discussions (waiting on @spapinistarkware)

___
*[`src/core/backend/avx512/blake2s.rs` line 18 at r4](https://reviewable.io/reviews/starkware-libs/stwo/528#-NuYGJIj36FwTth1brF4:-NuYGJIj36FwTth1brF5:b-g5h7l5) ([raw file](https://github.com/starkware-libs/stwo/blob/332c97846ec8ac670dc32616950853e9a3bb9efb/src/core/backend/avx512/blake2s.rs#L18)):*
> ```XML
>     fn bit_reverse_column(_column: &mut Self::Column) {
>         unimplemented!()
>     }
> ```

Will we need to implement that?



_Code quote:_
```XML
    fn bit_reverse_column(_column: &mut Self::Column) {
        unimplemented!()
    }
```
___
*[`src/core/backend/avx512/blake2s.rs` line 29 at r4](https://reviewable.io/reviews/starkware-libs/stwo/528#-NuYWhaMDsCk6jk0GpvO:-NuYWhaMDsCk6jk0GpvP:b3kre) ([raw file](https://github.com/starkware-libs/stwo/blob/332c97846ec8ac670dc32616950853e9a3bb9efb/src/core/backend/avx512/blake2s.rs#L29)):*
> ```XML
>         // Pad prev_layer if too small.
>         let mut padded_buffer = vec![];
>         let prev_layer = if log_size < 4 {
> ```

?



_Suggestion:_
```XML
VECS_LOG_SIZE
```
___
*[`src/core/backend/avx512/blake2s.rs` line 46 at r4](https://reviewable.io/reviews/starkware-libs/stwo/528#-NuYVn_q6ZtO75Ddzll3:-NuYVn_q6ZtO75Ddzll4:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/332c97846ec8ac670dc32616950853e9a3bb9efb/src/core/backend/avx512/blake2s.rs#L46)):*
> ```XML
>         for i in 0..(1 << (log_size - VECS_LOG_SIZE as u32)) {
>             let mut state: [__m512i; 8] = unsafe { std::mem::zeroed() };
>             // Hash prev_layer.
> ```





_Suggestion:_
```XML
// Hash prev_layer, if exists.
```
___
*[`src/core/backend/avx512/blake2s.rs` line 48 at r4](https://reviewable.io/reviews/starkware-libs/stwo/528#-NuYGjdf-yGrufEK2IhB:-NuYGjdf-yGrufEK2IhC:b-n413t4) ([raw file](https://github.com/starkware-libs/stwo/blob/332c97846ec8ac670dc32616950853e9a3bb9efb/src/core/backend/avx512/blake2s.rs#L48)):*
> ```XML
>             // Hash prev_layer.
>             if let Some(prev_layer) = prev_layer {
>                 let ptr = prev_layer[(i << 5)..(i << 5) + 32].as_ptr() as *const __m512i;
> ```

You should use Blake2sHash size here (do we have such const?)



_Code quote:_
```XML
(i << 5)..(i << 5) + 32
```
___
*[`src/core/backend/avx512/blake2s.rs` line 66 at r4](https://reviewable.io/reviews/starkware-libs/stwo/528#-NuYX53wEuILlyAyzNH6:-NuYX53wEuILlyAyzNH7:bowmwj6) ([raw file](https://github.com/starkware-libs/stwo/blob/332c97846ec8ac670dc32616950853e9a3bb9efb/src/core/backend/avx512/blake2s.rs#L66)):*
> ```XML
>             for col_chunk in &mut col_chunk_iter {
>                 let msgs = col_chunk.map(|column| column.data[i].0);
>                 state = unsafe { compress16(state, msgs, set1(0), set1(0), set1(0), set1(0)) };
> ```

Why do we always have that in the compress function?
Should those be default values?



_Code quote:_
```XML
set1(0), set1(0), set1(0), set1(0)
```
___
*[`src/core/backend/cpu/blake2s.rs` line 18 at r4](https://reviewable.io/reviews/starkware-libs/stwo/528#-NuYFVZ3E6kpadc9cnNS:-NuYFVZ3E6kpadc9cnNT:bcannfj) ([raw file](https://github.com/starkware-libs/stwo/blob/332c97846ec8ac670dc32616950853e9a3bb9efb/src/core/backend/cpu/blake2s.rs#L18)):*
> ```XML
>             .map(|i| {
>                 Blake2sMerkleHasher::hash_node(
>                     prev_layer.map(|prev_layer| (prev_layer[2 * i], prev_layer[2 * i + 1])),
> ```

This code works in case that prev_layer is Option?



_Code quote:_
```XML
(prev_layer[2 * i], prev_layer[2 * i + 1]))
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/528)* status: 4 of 7 files reviewed, 6 unresolved discussions (waiting on @shaharsamocha7)

___
*[`src/core/backend/avx512/blake2s.rs` line 18 at r4](https://reviewable.io/reviews/starkware-libs/stwo/528#-NuYGJIj36FwTth1brF4:-NuYZQgeCLkWFp3hTHml:b32w12) ([raw file](https://github.com/starkware-libs/stwo/blob/332c97846ec8ac670dc32616950853e9a3bb9efb/src/core/backend/avx512/blake2s.rs#L18)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Will we need to implement that?
</blockquote></details>

No
___
*[`src/core/backend/avx512/blake2s.rs` line 29 at r4](https://reviewable.io/reviews/starkware-libs/stwo/528#-NuYWhaMDsCk6jk0GpvO:-NuYZs_r0kNDXRqOjofU:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/332c97846ec8ac670dc32616950853e9a3bb9efb/src/core/backend/avx512/blake2s.rs#L29)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.
___
*[`src/core/backend/avx512/blake2s.rs` line 46 at r4](https://reviewable.io/reviews/starkware-libs/stwo/528#-NuYVn_q6ZtO75Ddzll3:-NuYZwYvAwvE9ENdb5Zt:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/332c97846ec8ac670dc32616950853e9a3bb9efb/src/core/backend/avx512/blake2s.rs#L46)):*
> ```XML
>         for i in 0..(1 << (log_size - VECS_LOG_SIZE as u32)) {
>             let mut state: [__m512i; 8] = unsafe { std::mem::zeroed() };
>             // Hash prev_layer.
> ```

Done.
___
*[`src/core/backend/avx512/blake2s.rs` line 48 at r4](https://reviewable.io/reviews/starkware-libs/stwo/528#-NuYGjdf-yGrufEK2IhB:-NuY_Lsy-rnOXFoIn54i:b-bjpj7a) ([raw file](https://github.com/starkware-libs/stwo/blob/332c97846ec8ac670dc32616950853e9a3bb9efb/src/core/backend/avx512/blake2s.rs#L48)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

You should use Blake2sHash size here (do we have such const?)
</blockquote></details>

Better?
___
*[`src/core/backend/avx512/blake2s.rs` line 66 at r4](https://reviewable.io/reviews/starkware-libs/stwo/528#-NuYX53wEuILlyAyzNH6:-NuY_N9DCWawHdY0pB3N:bnucyvq) ([raw file](https://github.com/starkware-libs/stwo/blob/332c97846ec8ac670dc32616950853e9a3bb9efb/src/core/backend/avx512/blake2s.rs#L66)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why do we always have that in the compress function?
Should those be default values?
</blockquote></details>

Im using the blake2s permutation with count=lastblock=lastnode=0.
We don't need them really in known-merkle mode.
___
*[`src/core/backend/cpu/blake2s.rs` line 18 at r4](https://reviewable.io/reviews/starkware-libs/stwo/528#-NuYFVZ3E6kpadc9cnNS:-NuY_dwb2Y8FHBTOQKln:bol2uk4) ([raw file](https://github.com/starkware-libs/stwo/blob/332c97846ec8ac670dc32616950853e9a3bb9efb/src/core/backend/cpu/blake2s.rs#L18)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

This code works in case that prev_layer is Option?
</blockquote></details>

prev_layer *is* Option. That's why I have .map().
The hash_node func expects Option<(H,H)>

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 7 files at r1, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/528#-:-NuYeFit7ZSiGxMax_5k:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`src/core/backend/avx512/blake2s.rs` line 48 at r4](https://reviewable.io/reviews/starkware-libs/stwo/528#-NuYGjdf-yGrufEK2IhB:-NuYdRcyEbXthgyUm6S3:bk85vah) ([raw file](https://github.com/starkware-libs/stwo/blob/332c97846ec8ac670dc32616950853e9a3bb9efb/src/core/backend/avx512/blake2s.rs#L48)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Better?
</blockquote></details>

I think that it should be explicit that it refers to the digest size of blake2s.
Your call (unblocking)
___
*[`src/core/backend/avx512/blake2s.rs` line 66 at r4](https://reviewable.io/reviews/starkware-libs/stwo/528#-NuYX53wEuILlyAyzNH6:-NuYdex9CYAUiuj8kq_W:bk8chyz) ([raw file](https://github.com/starkware-libs/stwo/blob/332c97846ec8ac670dc32616950853e9a3bb9efb/src/core/backend/avx512/blake2s.rs#L66)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Im using the blake2s permutation with count=lastblock=lastnode=0.
We don't need them really in known-merkle mode.
</blockquote></details>

Do we want to have a compress function for known size mode?

**Pull request merged**
