### PR TITLE
Merkle simd parallelization

### PR DESCRIPTION
**Pull request by carlogf**
Description:

We use Rayon to add parallelization option for applying hashes when building the merkle tree.
We extended the wide fibonacci trace to 2^10 columns.
This is achieved by introducing conditional compilation features to switch between parallel and single threads.

We saw improvements of about 10% in the total proving time and >80% in the trace commitment. We note that we had to change the total columns of the wide fibonacci trace from 2^8 to 2^10 to see these improvements.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/658)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/658)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @carlogf)

___
*[`crates/prover/src/core/backend/simd/blake2s.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/stwo/658#-O--yYTi8Mt8esPO7zrQ:-O--yYTi8Mt8esPO7zrR:b-1hbr7m) ([raw file](https://github.com/starkware-libs/stwo/blob/2fd1b01bc24cdeea809a0b9ec865e8f4eaaf9cd3/crates/prover/src/core/backend/simd/blake2s.rs#L55)):*
> ```XML
>         if log_size < N_LANES as u32 {
>     
>             #[cfg(not(feature = "parallel"))]
> ```

It looks like you are only parallelizing the small case. Why is that? And how did it yield 80% improvement?

**Comment by carlogf** [comment]
> > _[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/658)_ status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @carlogf)
> 
> _[`crates/prover/src/core/backend/simd/blake2s.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/stwo/658#-O--yYTi8Mt8esPO7zrQ:-O--yYTi8Mt8esPO7zrR:b-1hbr7m) ([raw file](https://github.com/starkware-libs/stwo/blob/2fd1b01bc24cdeea809a0b9ec865e8f4eaaf9cd3/crates/prover/src/core/backend/simd/blake2s.rs#L55)):_
> 
> > ```
> >         if log_size < N_LANES as u32 {
> >     
> >             #[cfg(not(feature = "parallel"))]
> > ```
> 
> It looks like you are only parallelizing the small case. Why is that? And how did it yield 80% improvement?

Thanks for the quick reply! I overlooked the large case. I'm using the test test_simd_wide_fib_prove to benchmark the proving time and it uses a trace size of 2^12 rows so I was only testing the small case. I still saw improvements when the trace size is 2^17.
I'll look into the large case next.

**Comment by carlogf** [comment]
I added the parallelization for the large case and ran some benchmarks
image
this is the improvement for the simd merkle bench

And the improvement for the test_simd_wide_fib went from  `3.23s` to `2.50s` with `LOG_N_COLUMNS=10` and `LOG_N_ROWS=16`

As an additional comment, the original implementation instantiated an empty `vec::with_capacity` and proceded to use `.extend` to push slices of 16 hashes into it. Here I instantiated the whole vector with default values and modified it in chunks of 16. I saw no significant difference in the performance of the two implementations for the serialized case.

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/658)* status: all files reviewed, 3 unresolved discussions (waiting on @carlogf)

___
*[`crates/prover/src/core/backend/simd/blake2s.rs` line 113 at r2](https://reviewable.io/reviews/starkware-libs/stwo/658#-O-UqSnwDckVpM3r0DDG:-O-UqSnwDckVpM3r0DDH:b-wzcco9) ([raw file](https://github.com/starkware-libs/stwo/blob/cc90701376769f48684aa6849101c8bed165f83c/crates/prover/src/core/backend/simd/blake2s.rs#L113)):*
> ```XML
>             }
>             let state: [Blake2sHash; 16] = unsafe { transmute(untranspose_states(state)) };
>             // res.extend_from_slice(&state);
> ```

Remove the commented lines.
___
*[`crates/prover/src/examples/wide_fibonacci/component.rs` line 17 at r2](https://reviewable.io/reviews/starkware-libs/stwo/658#-O-UqXwd2s9im-diQE0I:-O-UqXwd2s9im-diQE0J:ba854ie) ([raw file](https://github.com/starkware-libs/stwo/blob/cc90701376769f48684aa6849101c8bed165f83c/crates/prover/src/examples/wide_fibonacci/component.rs#L17)):*
> ```XML
> use crate::examples::wide_fibonacci::trace_gen::write_lookup_column;
> 
> pub const LOG_N_COLUMNS: usize = 10;
> ```

Revert?
___
*[`crates/prover/src/examples/wide_fibonacci/simd.rs` line 143 at r2](https://reviewable.io/reviews/starkware-libs/stwo/658#-O-Uq_RrCAzqGOuaWXNt:-O-Uq_RrCAzqGOuaWXNu:byp6rt5) ([raw file](https://github.com/starkware-libs/stwo/blob/cc90701376769f48684aa6849101c8bed165f83c/crates/prover/src/examples/wide_fibonacci/simd.rs#L143)):*
> ```XML
> 
>         // Note: 17 means 128MB of trace.
>         const LOG_N_ROWS: u32 = 16;
> ```

Revert

**Review by spapinistarkware — COMMENTED** [review]
Sounds good

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/658#-:-O-UqiATEvgGm7E124YS:b-hfghm4)* status: all files reviewed, 3 unresolved discussions (waiting on @carlogf)

**Review by spapinistarkware — COMMENTED** [review]
Fix comments and rebase

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/658#-:-O-Uqtle0AZxTvy-YnLH:btk6atl)* status: all files reviewed, 3 unresolved discussions (waiting on @carlogf)

**Comment by carlogf** [comment]
Thanks! All issues have been addressed :)

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/658)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @carlogf)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/658#-:-O-eDBKU2tbakzjN2OsA:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @carlogf)

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/658)* status: all files reviewed, 1 unresolved discussion (waiting on @carlogf)

*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo/658#-O-eTot4EKZUhAo3edwf:-O-eTot5D-M7oXNPxfZV:b-s5s1l7) (no related file):*
udeps doesn't like the conditional rayong dependency. Can you maybe run it with that feature, or fix ni another way?

___

**Pull request merged**
