### PR TITLE
Parallelize bit reverse m31.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/855)

### CODE REVIEW

**Comment by alonh5** [comment]
* **#855** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/855?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by andrewmilson — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/855)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @Alon-Ti, @alonh5, and @shaharsamocha7)

___
*[`crates/prover/src/core/backend/simd/m31.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/stwo/855#-O7cWZKM0lOjawzYQt73:-O7cWZKM0lOjawzYQt74:bdttg15) ([raw file](https://github.com/starkware-libs/stwo/blob/544b2257be7749a417b678f6095ef544902bd498/crates/prover/src/core/backend/simd/m31.rs#L42)):*
> ```XML
> 
> unsafe impl Send for UnsafePackedM31Array {}
> unsafe impl Sync for UnsafePackedM31Array {}
> ```

Perhaps we can move to utils.rs and unify with the `UnsafeMut` types in the fft code



_Suggestion:_
```XML
pub struct UnsafeMut<T>(pub *mut T);
impl<T> UnsafeMut<T> {
    pub unsafe fn get(&self) -> *mut T {
        self.0
    }
}

unsafe impl<T> Send for UnsafeMut<T> {}
unsafe impl<T> Sync for UnsafeMut<T> {}
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/855)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @Alon-Ti, @andrewmilson, and @shaharsamocha7)

___
*[`crates/prover/src/core/backend/simd/m31.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/stwo/855#-O7cWZKM0lOjawzYQt73:-O7ceDhl5wpARd8Z-7NI:b-fflhqt) ([raw file](https://github.com/starkware-libs/stwo/blob/544b2257be7749a417b678f6095ef544902bd498/crates/prover/src/core/backend/simd/m31.rs#L42)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Perhaps we can move to utils.rs and unify with the `UnsafeMut` types in the fft code
</blockquote></details>

Great idea. Done.

**Review by andrewmilson — APPROVED** [review]
:lgtm: With comment

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/855#-:-O7h1Lq512_cXmcbVssT:b3q5yxg)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @Alon-Ti, @alonh5, and @shaharsamocha7)

___
*[`crates/prover/src/core/mod.rs` line 99 at r2](https://reviewable.io/reviews/starkware-libs/stwo/855#-O7h18U79Lz3zosG34o9:-O7h18U79Lz3zosG34oA:bc31v3l) ([raw file](https://github.com/starkware-libs/stwo/blob/0f629cbdd8ebf4eec03a36dce1c80246b4d7477a/crates/prover/src/core/mod.rs#L99)):*
> ```XML
> 
> unsafe impl<T> Send for UnsafeConst<T> {}
> unsafe impl<T> Sync for UnsafeConst<T> {}
> ```

Maybe `simd/utils.rs` is better. 
Not sure we want to expose these in our public API



_Code quote:_
```XML
// TODO(andrew): Examine usage of unsafe in SIMD FFT.
pub struct UnsafeMut<T: ?Sized>(pub *mut T);
impl<T: ?Sized> UnsafeMut<T> {
    /// # Safety
    ///
    /// Returns a raw mutable pointer.
    pub unsafe fn get(&self) -> *mut T {
        self.0
    }
}

unsafe impl<T: ?Sized> Send for UnsafeMut<T> {}
unsafe impl<T: ?Sized> Sync for UnsafeMut<T> {}

pub struct UnsafeConst<T>(pub *const T);
impl<T> UnsafeConst<T> {
    /// # Safety
    ///
    /// Returns a raw constant pointer.
    pub unsafe fn get(&self) -> *const T {
        self.0
    }
}

unsafe impl<T> Send for UnsafeConst<T> {}
unsafe impl<T> Sync for UnsafeConst<T> {}
```

**Review by shaharsamocha7 — COMMENTED** [review]
I moved UnsafeMut to simd utils

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/855#-:-O81Pw-K5NqoIlOhbBZO:bnex0ps)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @Alon-Ti, @alonh5, and @andrewmilson)

**Review by andrewmilson — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/855#-:-O81ga6gBEneipdWjWa3:bnfp4nl)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @Alon-Ti and @alonh5)

**Pull request merged**
