### PR TITLE
Create MultiFibonacci.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/509)

### CODE REVIEW

**Comment by alonh5** [comment]
* **#509** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/509?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/509)* status: all files reviewed (commit messages unreviewed), 4 unresolved discussions (waiting on @alonh5)

___
*[`src/fibonacci/mod.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/stwo/509#-NtQCVwt2x9-5xbiYZQW:-NtQCVwu8iH6RQjZPJP-:byh3hto) ([raw file](https://github.com/starkware-libs/stwo/blob/32a5acaed7ade6477ce58b55fd22438540ae77a8/src/fibonacci/mod.rs#L20)):*
> ```XML
> pub struct Fibonacci {
>     pub air: FibonacciAir,
>     pub log_size: u32,
> ```

I think that storing here as well is duplicated.
Consider to remove this change



_Code quote:_
```XML
pub log_size: u32,
```
___
*[`src/fibonacci/mod.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/stwo/509#-NtQDJSN4IDezbXcE0yQ:-NtQDJSN4IDezbXcE0yR:b-h7luox) ([raw file](https://github.com/starkware-libs/stwo/blob/32a5acaed7ade6477ce58b55fd22438540ae77a8/src/fibonacci/mod.rs#L21)):*
> ```XML
>     pub air: FibonacciAir,
>     pub log_size: u32,
>     pub claim: BaseField,
> ```

Consider to change that to a list of secrets, claims
That way we will have different Fibonnaci traces

Could be done in another pr.



_Code quote:_
```XML
pub claim: BaseField,
```
___
*[`src/fibonacci/mod.rs` line 70 at r1](https://reviewable.io/reviews/starkware-libs/stwo/509#-NtQD-YtB2QD0arjzv4I:-NtQD-YtB2QD0arjzv4J:b-65ywpj) ([raw file](https://github.com/starkware-libs/stwo/blob/32a5acaed7ade6477ce58b55fd22438540ae77a8/src/fibonacci/mod.rs#L70)):*
> ```XML
> pub struct MultiFibonacci {
>     pub air: MultiFibonacciAir,
>     single_fib: Fibonacci,
> ```

I don't think we need to store that as well.
Can we just use Fibonnaci::get_trace() in this struct get_trace?



_Code quote:_
```XML
single_fib: Fibonacci,
```
___
*[`src/fibonacci/mod.rs` line 247 at r1](https://reviewable.io/reviews/starkware-libs/stwo/509#-NtQDcxi2t9wTBY2DD4o:-NtQDcxj6Kdm1tk9AHSo:b-56zv3u) ([raw file](https://github.com/starkware-libs/stwo/blob/32a5acaed7ade6477ce58b55fd22438540ae77a8/src/fibonacci/mod.rs#L247)):*
> ```XML
>             hz
>         );
>         fib.verify(proof);
> ```

Do we need an assert on that?



_Code quote:_
```XML
fib.verify(proof);
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/509)* status: all files reviewed (commit messages unreviewed), 4 unresolved discussions (waiting on @shaharsamocha7)

___
*[`src/fibonacci/mod.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/stwo/509#-NtQCVwt2x9-5xbiYZQW:-NtQFnL_8CJjTj8QNzFf:b-lsdac7) ([raw file](https://github.com/starkware-libs/stwo/blob/32a5acaed7ade6477ce58b55fd22438540ae77a8/src/fibonacci/mod.rs#L20)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I think that storing here as well is duplicated.
Consider to remove this change
</blockquote></details>

Done. I also removed `claim` because it was also duplicated.
___
*[`src/fibonacci/mod.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/stwo/509#-NtQDJSN4IDezbXcE0yQ:-NtQG0GI6_TrALQHAmvi:by9v18x) ([raw file](https://github.com/starkware-libs/stwo/blob/32a5acaed7ade6477ce58b55fd22438540ae77a8/src/fibonacci/mod.rs#L21)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Consider to change that to a list of secrets, claims
That way we will have different Fibonnaci traces

Could be done in another pr.
</blockquote></details>

I'm not sure I understand.
___
*[`src/fibonacci/mod.rs` line 70 at r1](https://reviewable.io/reviews/starkware-libs/stwo/509#-NtQD-YtB2QD0arjzv4I:-NtQGMgO5p-EeyyfZmUR:b39c0v4) ([raw file](https://github.com/starkware-libs/stwo/blob/32a5acaed7ade6477ce58b55fd22438540ae77a8/src/fibonacci/mod.rs#L70)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I don't think we need to store that as well.
Can we just use Fibonnaci::get_trace() in this struct get_trace?
</blockquote></details>

We need an instance of Fibonacci for that. We can store the `log_size` and `claim` in MultiFibonacci and then create an instance of Fibonacci when we need the trace, do you think that's better?
___
*[`src/fibonacci/mod.rs` line 247 at r1](https://reviewable.io/reviews/starkware-libs/stwo/509#-NtQDcxi2t9wTBY2DD4o:-NtQGAQ0Bx8dKP1Yemgr:b-2226h9) ([raw file](https://github.com/starkware-libs/stwo/blob/32a5acaed7ade6477ce58b55fd22438540ae77a8/src/fibonacci/mod.rs#L247)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Do we need an assert on that?
</blockquote></details>

It returns an error now so I unwrapped instead.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/509)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @alonh5)

___
*[`src/fibonacci/mod.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/stwo/509#-NtQDJSN4IDezbXcE0yQ:-NtQYHUK6FPKXXiws3u6:bjdbyx) ([raw file](https://github.com/starkware-libs/stwo/blob/32a5acaed7ade6477ce58b55fd22438540ae77a8/src/fibonacci/mod.rs#L21)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I'm not sure I understand.
</blockquote></details>

It's will give you support in traces with different secrets and claims.
Not relevant for now.
___
*[`src/fibonacci/mod.rs` line 70 at r1](https://reviewable.io/reviews/starkware-libs/stwo/509#-NtQD-YtB2QD0arjzv4I:-NtQYSi36FWyF06aHpiR:b-xxwqjs) ([raw file](https://github.com/starkware-libs/stwo/blob/32a5acaed7ade6477ce58b55fd22438540ae77a8/src/fibonacci/mod.rs#L70)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

We need an instance of Fibonacci for that. We can store the `log_size` and `claim` in MultiFibonacci and then create an instance of Fibonacci when we need the trace, do you think that's better?
</blockquote></details>

This is because get_trace is a method function, right?
I think it is because you don't really need a single_fib attribute here, it is just that you need the get_trace method.
___
*[`src/fibonacci/mod.rs` line 247 at r1](https://reviewable.io/reviews/starkware-libs/stwo/509#-NtQDcxi2t9wTBY2DD4o:-NtQY2W35Gdok9oy4aRQ:b-l2bq06) ([raw file](https://github.com/starkware-libs/stwo/blob/32a5acaed7ade6477ce58b55fd22438540ae77a8/src/fibonacci/mod.rs#L247)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

It returns an error now so I unwrapped instead.
</blockquote></details>

Didn't look on the last revision, thanks.

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/509)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`src/fibonacci/mod.rs` line 70 at r1](https://reviewable.io/reviews/starkware-libs/stwo/509#-NtQD-YtB2QD0arjzv4I:-NtQ_iOfChraJ-L5gvQ5:b-ri1f31) ([raw file](https://github.com/starkware-libs/stwo/blob/32a5acaed7ade6477ce58b55fd22438540ae77a8/src/fibonacci/mod.rs#L70)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

This is because get_trace is a method function, right?
I think it is because you don't really need a single_fib attribute here, it is just that you need the get_trace method.
</blockquote></details>

Discussed offline and left as is.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/509#-:-NtQlgjk6g-JEzoiuIir:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @alonh5)

**Pull request merged**
