### PR TITLE
ColumnOps

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/459)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/459?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#459** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/459?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#443** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/443?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#401** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/401?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#399** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/399?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#398** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/398?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#397** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/397?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#396** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/396?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#395** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/395?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#394** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/394?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#390** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/390?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#389** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/389?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#383** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/383?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#382** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/382?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#381** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/381?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#380** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/380?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#379** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/379?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#378** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/378?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#377** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/377?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#368** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/368?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#367** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/367?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#366** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/366?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#365** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/365?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 9 of 12 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/459)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`src/core/backend/mod.rs` line 18 at r2](https://reviewable.io/reviews/starkware-libs/stwo/459#-NsmsbQbEy-_bIE0OUVK:-NsmsbQbEy-_bIE0OUVL:blv0p0q) ([raw file](https://github.com/starkware-libs/stwo/blob/ef4fa7b1e79374554ef101ca18db3fb3f2ac4974/src/core/backend/mod.rs#L18)):*
> ```XML
> }
> 
> pub trait ColumnOps<T> {
> ```

We are defining columns only for felts, right?



_Suggestion:_
```XML
F: Field
```
___
*[`src/core/backend/avx512/mod.rs` line 63 at r2](https://reviewable.io/reviews/starkware-libs/stwo/459#-Nsmrevj44JVFDg3sDb-:-NsmrevkBxKIEgQKBUWC:bk05dgt) ([raw file](https://github.com/starkware-libs/stwo/blob/ef4fa7b1e79374554ef101ca18db3fb3f2ac4974/src/core/backend/avx512/mod.rs#L63)):*
> ```XML
> }
> 
> impl FieldOps<BaseField> for AVX512Backend {
> ```

Consider moving this to the avx field file.



_Code quote:_
```XML
impl FieldOps<BaseField> for AVX512Backend {
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/459)* status: 10 of 15 files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7)

___
*[`src/core/backend/mod.rs` line 18 at r2](https://reviewable.io/reviews/starkware-libs/stwo/459#-NsmsbQbEy-_bIE0OUVK:-NsmubY006m4KDcNKoTE:bg43ktk) ([raw file](https://github.com/starkware-libs/stwo/blob/ef4fa7b1e79374554ef101ca18db3fb3f2ac4974/src/core/backend/mod.rs#L18)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

We are defining columns only for felts, right?
</blockquote></details>

If it's only for felts, that it would be more sensible to add this in FieldOps.
I think there's also value in other columns. For Hashes, and twiddle factors (which are not reduced, and hence, not BaseField)
___
*[`src/core/backend/avx512/mod.rs` line 63 at r2](https://reviewable.io/reviews/starkware-libs/stwo/459#-Nsmrevj44JVFDg3sDb-:-Nsmv72OEJtSkjk80OlE:bk0ry2d) ([raw file](https://github.com/starkware-libs/stwo/blob/ef4fa7b1e79374554ef101ca18db3fb3f2ac4974/src/core/backend/avx512/mod.rs#L63)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Consider moving this to the avx field file.
</blockquote></details>

Noted.
don't think there enough to put there just yet.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 5 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/459#-:-Nsn2xHuABx6jsVdBHxo:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`src/core/backend/mod.rs` line 18 at r2](https://reviewable.io/reviews/starkware-libs/stwo/459#-NsmsbQbEy-_bIE0OUVK:-Nsn2hdF90kfwsNs3oyw:bpjo2zv) ([raw file](https://github.com/starkware-libs/stwo/blob/ef4fa7b1e79374554ef101ca18db3fb3f2ac4974/src/core/backend/mod.rs#L18)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

If it's only for felts, that it would be more sensible to add this in FieldOps.
I think there's also value in other columns. For Hashes, and twiddle factors (which are not reduced, and hence, not BaseField)
</blockquote></details>

Now I see why they are not BaseField...

**Review by shaharsamocha7 — APPROVED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/459)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by shaharsamocha7 — APPROVED** [review]
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/459)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
