### PR TITLE
Expr formatting.

### PR DESCRIPTION
**Pull request by Alon-Ti**

### CODE REVIEW

**Comment by Alon-Ti** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/888?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#889** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/889?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#888** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/888?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#887** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/887?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#879** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/879?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#883](https://github.com/starkware-libs/stwo/pull/883) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/883?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#876** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/876?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#875** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/875?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Alon-Ti and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/888)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @Alon-Ti)

___
*[`crates/prover/src/constraint_framework/expr.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/stwo/888#-OBtXD3k5rVJXDzQ-d7S:-OBtXD3l8qpM4WPHbc5f:b5oy13l) ([raw file](https://github.com/starkware-libs/stwo/blob/e0a38e94fceadca19da73c276e18c8c3383f8015/crates/prover/src/constraint_framework/expr.rs#L56)):*
> ```XML
>                 d.format_expr()
>             ),
>             Expr::Const(c) => c.0.to_string(),
> ```

Const is a BaseField so why are you treat it as a string?



_Code quote:_
```XML
Expr::Const(c) => c.0.to_string(),
```
___
*[`crates/prover/src/constraint_framework/expr.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/stwo/888#-OBtXN6qABWnwNxfrfms:-OBtXN6qABWnwNxfrfmt:b9e3z6u) ([raw file](https://github.com/starkware-libs/stwo/blob/e0a38e94fceadca19da73c276e18c8c3383f8015/crates/prover/src/constraint_framework/expr.rs#L59)):*
> ```XML
>             Expr::Var(v) => v.to_string(),
>             Expr::Add(a, b) => format!("{} + {}", a.format_expr(), b.format_expr()),
>             Expr::Sub(a, b) => format!("{} - ({})", a.format_expr(), b.format_expr()),
> ```

don't you need to add parenthesis on this too?



_Suggestion:_
```XML
Expr::Sub(a, b) => format!("({}) - ({})", a.format_expr(), b.format_expr())
```
___
*[`crates/prover/src/constraint_framework/expr.rs` line 444 at r1](https://reviewable.io/reviews/starkware-libs/stwo/888#-OBtXXFB6vVdaY6T0Bs_:-OBtXXFB6vVdaY6T0Bsa:b-q0p5z3) ([raw file](https://github.com/starkware-libs/stwo/blob/e0a38e94fceadca19da73c276e18c8c3383f8015/crates/prover/src/constraint_framework/expr.rs#L444)):*
> ```XML
>         let eval = test_struct.evaluate(ExprEvaluator::new(16, (SecureField::zero(), None)));
>         assert_eq!(eval.constraints[0].format_expr(), "(1) * ((((col_1_0[0]) * (col_1_1[0])) * (col_1_2[0])) * (1/(col_1_0[0] + col_1_1[0])))");
>         assert_eq!(eval.constraints[1].format_expr(), "(1) * ((SecureCol(col_2_4[0], col_2_6[0], col_2_8[0], col_2_10[0]) - (SecureCol(col_2_5[18446744073709551615], col_2_7[18446744073709551615], col_2_9[18446744073709551615], col_2_11[18446744073709551615]) - ((col_0_3[0]) * (SecureCol(0, 0, 0, 0)))) - (0)) * (0 + (TestRelation_alpha0) * (col_1_0[0]) + (TestRelation_alpha1) * (col_1_1[0]) + (TestRelation_alpha2) * (col_1_2[0]) - (TestRelation_z)) - (1))");
> ```

I think you should write it in a clearer indentation, (so it will be easy to understand what the constraints are, and then you it in the test.



_Code quote:_
```XML
        assert_eq!(eval.constraints[0].format_expr(), "(1) * ((((col_1_0[0]) * (col_1_1[0])) * (col_1_2[0])) * (1/(col_1_0[0] + col_1_1[0])))");
        assert_eq!(eval.constraints[1].format_expr(), "(1) * ((SecureCol(col_2_4[0], col_2_6[0], col_2_8[0], col_2_10[0]) - (SecureCol(col_2_5[18446744073709551615], col_2_7[18446744073709551615], col_2_9[18446744073709551615], col_2_11[18446744073709551615]) - ((col_0_3[0]) * (SecureCol(0, 0, 0, 0)))) - (0)) * (0 + (TestRelation_alpha0) * (col_1_0[0]) + (TestRelation_alpha1) * (col_1_1[0]) + (TestRelation_alpha2) * (col_1_2[0]) - (TestRelation_z)) - (1))");
```

**Review by Alon-Ti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/888)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/expr.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/stwo/888#-OBtXD3k5rVJXDzQ-d7S:-OBtye7QBrFH6ZpLWN1f:b-j11uji) ([raw file](https://github.com/starkware-libs/stwo/blob/36aa69d3c215bc9ce7a1ca6a3b228f3a0b9eec46/crates/prover/src/constraint_framework/expr.rs#L56)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Const is a BaseField so why are you treat it as a string?
</blockquote></details>

Oh, right, the unreduced form :(
___
*[`crates/prover/src/constraint_framework/expr.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/stwo/888#-OBtXN6qABWnwNxfrfms:-OBtxyWi2MXDu5DTW4cs:bxtyhf1) ([raw file](https://github.com/starkware-libs/stwo/blob/36aa69d3c215bc9ce7a1ca6a3b228f3a0b9eec46/crates/prover/src/constraint_framework/expr.rs#L59)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

don't you need to add parenthesis on this too?
</blockquote></details>

Isn't it correct like this? I think add doesn't need parens, sub needs parens on the negative part and mul needs parens on both.

`a * b - d + c - (x * y + z)   <=>   (a * b - d + c) - (x * y + z)`
___
*[`crates/prover/src/constraint_framework/expr.rs` line 444 at r1](https://reviewable.io/reviews/starkware-libs/stwo/888#-OBtXXFB6vVdaY6T0Bs_:-OBu2I6z-ubg5Nns-z-X:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/36aa69d3c215bc9ce7a1ca6a3b228f3a0b9eec46/crates/prover/src/constraint_framework/expr.rs#L444)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I think you should write it in a clearer indentation, (so it will be easy to understand what the constraints are, and then you it in the test.
</blockquote></details>

Done.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/888#-:-OBzGlyA26rHft0SWh5N:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Alon-Ti)

**Pull request merged**
