### PR TITLE
relation summary

### PR DESCRIPTION
**Pull request by ohad-agadi**

### CODE REVIEW

**Comment by ohad-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/911?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#911** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/911?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/911?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#909** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/909?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by Alon-Ti — APPROVED** [review]
:lgtm: with minor pondering

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/911#-:-OD5_m8d2ND62ExNyPOl:b-t9kyxi)* status: all files reviewed, 1 unresolved discussion (waiting on @ohad-starkware)

___
*[`crates/prover/src/constraint_framework/relation_tracker.rs` line 192 at r1](https://reviewable.io/reviews/starkware-libs/stwo/911#-OD5Y7KD1aY3PMia6-5G:-OD5Y7KD1aY3PMia6-5H:b-n0nroj) ([raw file](https://github.com/starkware-libs/stwo/blob/4816a4a8812f0b31b757c2de83f543fa203de721/crates/prover/src/constraint_framework/relation_tracker.rs#L192)):*
> ```XML
> }
> 
> type RelationInfo = (String, Vec<(Vec<M31>, M31)>);
> ```

Is there a non-destructive way to unify this, `RelationEntry` and `RelationTrackerEntry`?

**Review by ohad-agadi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/911)* status: all files reviewed, 1 unresolved discussion (waiting on @Alon-Ti)

___
*[`crates/prover/src/constraint_framework/relation_tracker.rs` line 192 at r1](https://reviewable.io/reviews/starkware-libs/stwo/911#-OD5Y7KD1aY3PMia6-5G:-OD5kNcmBBdTHftaVp-_:bnq8wnf) ([raw file](https://github.com/starkware-libs/stwo/blob/4816a4a8812f0b31b757c2de83f543fa203de721/crates/prover/src/constraint_framework/relation_tracker.rs#L192)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

Is there a non-destructive way to unify this, `RelationEntry` and `RelationTrackerEntry`?
</blockquote></details>

the relation tracker could sit with the logup stuff under some "lookup_utils" folder in the constraint(air) framework

**Comment by ohad-starkware** [comment]
### Merge activity

* **Dec 2, 4:45 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/911).

**Comment by ohad-starkware** [comment]
*[`crates/prover/src/constraint_framework/relation_tracker.rs` line 192 at r1](https://reviewable.io/reviews/starkware-libs/stwo/911#-OD5Y7KD1aY3PMia6-5G:-OD5ll9i7PVTCRkeRUFI:br5ti2c) ([raw file](https://github.com/starkware-libs/stwo/blob/1400ec6588709392fbe8809448fdf09af39a0a44/crates/prover/src/constraint_framework/relation_tracker.rs#L192)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

the relation tracker could sit with the logup stuff under some "lookup_utils" folder in the constraint(air) framework
</blockquote></details>

oh if you meant unifying to a single struct then no, this represents multiple entries that are not even from the same trace

**Pull request merged**
