### PR TITLE
TraceGenerator trait

### PR DESCRIPTION
**Pull request by shaharsamocha7**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/663)

### CODE REVIEW

**Comment by shaharsamocha7** [comment]
* **#663** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/663?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @shaharsamocha7 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/663#-:-O-Uu6PDAQdJ28i19ZFn:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ohad-starkware)

**Review by ohad-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/663#-:-O-ZxtBT0FK6r5hVs4Zj:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shaharsamocha7)

___
*[`crates/prover/src/trace_generation/mod.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/stwo/663#-O-GujM2189OwxGqJ_9v:-O-GujM2189OwxGqJ_9w:b-cdxb8v) ([raw file](https://github.com/starkware-libs/stwo/blob/419c4e48e762f02e015fda843df54de136504705/crates/prover/src/trace_generation/mod.rs#L26)):*
> ```XML
>     /// This function should be called from the caller components before calling `write_trace` of
>     /// this component.
>     fn add_inputs(&mut self, inputs: &[Self::ComponentInput]);
> ```

writing down our irl discussion - 
input type might need to be dynamic to avoid converting non-cpu types every add.
lgtm.

**Review by ohad-starkware — CHANGES_REQUESTED** [review]
added a comment

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/663#-:-O-kBs8d3vL2qCI4nhyn:b-4mhpgl)* status: all files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`crates/prover/src/trace_generation/mod.rs` line 20 at r3](https://reviewable.io/reviews/starkware-libs/stwo/663#-O-kBnu57lFqPdm6FC_k:-O-kBnu57lFqPdm6FC_l:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/ad4c71ce4c24946d679171da2b648a0801edab3a/crates/prover/src/trace_generation/mod.rs#L20)):*
> ```XML
> // A trait to generate a a trace.
> // Generates the trace given a list of inputs collects inputs for subcomponents.
> trait TraceGenerator<B: Backend> {
> ```





_Suggestion:_
```XML
pub trait
```

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/663)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @ohad-starkware)

___
*[`crates/prover/src/trace_generation/mod.rs` line 20 at r3](https://reviewable.io/reviews/starkware-libs/stwo/663#-O-kBnu57lFqPdm6FC_k:-O-oejTvCgWi7xzAIgM3:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/ad4c71ce4c24946d679171da2b648a0801edab3a/crates/prover/src/trace_generation/mod.rs#L20)):*
> ```XML
> // A trait to generate a a trace.
> // Generates the trace given a list of inputs collects inputs for subcomponents.
> trait TraceGenerator<B: Backend> {
> ```

Done.

**Review by ohad-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/663#-:-O-ohAF3DBlM4D8w4-Bw:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Comment by shaharsamocha7** [comment]
### Merge activity

* **Jun 20, 4:43 AM EDT**: @shaharsamocha7 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/663).

**Pull request merged**
