### PR TITLE
Fall back to CPU in small FRI.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/840)

### CODE REVIEW

**Comment by alonh5** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/840?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#840** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/840?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#838** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/838?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#827** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/827?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by andrewmilson — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/840)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

___
*[`crates/prover/src/core/backend/simd/circle.rs` line 337 at r1](https://reviewable.io/reviews/starkware-libs/stwo/840#-O77POAz9Obo_-p3T6ay:-O77POAz9Obo_-p3T6az:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/89d9f9bd8531709493eeb8917bfd89c847404b96/crates/prover/src/core/backend/simd/circle.rs#L337)):*
> ```XML
>         a.swap_with_slice(&mut c[0..n0]);
>     }
>     fold(&poly.coeffs.to_cpu(), &mappings)
> ```





_Suggestion:_
```XML
poly.coeffs.as_slice()
```
___
*[`crates/prover/src/core/backend/simd/fri.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/stwo/840#-O77ReQx7KfRuq8FNlaD:-O77ReQy8tYWtBCmTlJl:b-93pfzd) ([raw file](https://github.com/starkware-libs/stwo/blob/89d9f9bd8531709493eeb8917bfd89c847404b96/crates/prover/src/core/backend/simd/fri.rs#L59)):*
> ```XML
>     }
> 
>     fn fold_circle_into_line(
> ```

Tests for these?

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/840)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`crates/prover/src/core/backend/simd/circle.rs` line 337 at r1](https://reviewable.io/reviews/starkware-libs/stwo/840#-O77POAz9Obo_-p3T6ay:-O78R-xVBjSlz5Pr_-HQ:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/89d9f9bd8531709493eeb8917bfd89c847404b96/crates/prover/src/core/backend/simd/circle.rs#L337)):*
> ```XML
>         a.swap_with_slice(&mut c[0..n0]);
>     }
>     fold(&poly.coeffs.to_cpu(), &mappings)
> ```

Done.
___
*[`crates/prover/src/core/backend/simd/fri.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/stwo/840#-O77ReQx7KfRuq8FNlaD:-O78R5Qu48lWw3pwPowa:b-oofdry) ([raw file](https://github.com/starkware-libs/stwo/blob/89d9f9bd8531709493eeb8917bfd89c847404b96/crates/prover/src/core/backend/simd/fri.rs#L59)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Tests for these?
</blockquote></details>

I added tests for a full proof of wide_fib with sizes 3 and 2, do you think that should be enough?

**Review by andrewmilson — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/840#-:-O7NwCSZDBN69Mfqy6Oh:bnfp4nl)* status: 2 of 6 files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Comment by alonh5** [comment]
### Merge activity

* **Sep 24, 4:47 AM EDT**: @alonh5 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/840).

**Pull request merged**
