### PR TITLE
replace get_random_point with bws_get_random_point from Bitcoin-Wildlife-Sanctuary/stwo

### PR DESCRIPTION
**Pull request by PayneJoe**
per discussion, this PR replaces the current point sampling algorithm (referring the `Lemma 1` of #[Circle STARKs](https://eprint.iacr.org/2024/278.pdf)) into one that doesn’t use rejection sampling, with some security loss subject to the bias of sampling a secure field element from the channel.

PS: this PR comes from Bitcoin-Wildlife-Sanctuary

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/661)

### CODE REVIEW

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/661#-:-O1MjjclCj_CHTQdKHGv:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @PayneJoe)

___
*[`crates/prover/src/core/circle.rs` line 155 at r1](https://reviewable.io/reviews/starkware-libs/stwo/661#-O1Mj_qx4HaRIDHeDXol:-O1Mj_qyA73sGU0SYny_:b44stu) ([raw file](https://github.com/starkware-libs/stwo/blob/15a96a2314a44b9370ec879e805cd37788899afd/crates/prover/src/core/circle.rs#L155)):*
> ```XML
>         let t = channel.draw_felt();
> 
>         let one_plus_tsquared_inv = t.square().add(SecureField::one()).inverse();
> ```

Extract to a variable.



_Suggestion:_
```XML
let t_squared = t.square();
```

**Comment by PayneJoe** [comment]
> :lgtm:
> 
> > Reviewed 1 of 1 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/661#-:-O1MjjclCj_CHTQdKHGv:bnfp4nl)_ status: all files reviewed, 1 unresolved discussion (waiting on @PayneJoe)
> 
> _[`crates/prover/src/core/circle.rs` line 155 at r1](https://reviewable.io/reviews/starkware-libs/stwo/661#-O1Mj_qx4HaRIDHeDXol:-O1Mj_qyA73sGU0SYny_:b44stu) ([raw file](https://github.com/starkware-libs/stwo/blob/15a96a2314a44b9370ec879e805cd37788899afd/crates/prover/src/core/circle.rs#L155)):_
> 
> > ```
> >         let t = channel.draw_felt();
> > 
> >         let one_plus_tsquared_inv = t.square().add(SecureField::one()).inverse();
> > ```
> 
> Extract to a variable.
> 
> _Suggestion:_
> 
> ```
> let t_squared = t.square();
> ```

thanks Alon, it's done

**Review by alonh5 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/661)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @PayneJoe)

**Comment by PayneJoe** [comment]
coverage failed, trigger once more?

**Comment by weikengchen** [comment]
@alonh5 I think a possible reason why the coverage is failing is because this PR is from an external repo? If that is the case, maybe we can either copy-paste this branch into starkware-libs/stwo (which would allow us to keep a record of the coverage) or merge ignoring that failing test.

**Review by alonh5 — APPROVED** [review]
I merged for now. We'll look into why the coverage is failing.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/661#-:-O2UefsA9_bA1rgoVzIj:b4mbbi)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @PayneJoe)

**Pull request merged**
