### PR TITLE
Expression evaluator: Ordnung muß sein.

### PR DESCRIPTION
**Pull request by Alon-Ti**

### CODE REVIEW

**Comment by Alon-Ti** [comment]
* **#927** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/927?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/927?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `dev`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/927)* status: all files reviewed, 2 unresolved discussions (waiting on @Alon-Ti)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo/927#-ODjOUM99wdI4G9FaGVv:-ODjOUM99wdI4G9FaGVw:bf9ki0d) (no related file):*
You are not German yet
___
*[`crates/prover/src/constraint_framework/expr/eval.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/stwo/927#-ODjOl45Ao-7HKuGKpxN:-ODjOl46DF7pJeKwinai:b-67rl8p) ([raw file](https://github.com/starkware-libs/stwo/blob/5d68434bf35bfe3058c97119c14083b6c332475e/crates/prover/src/constraint_framework/expr/eval.rs#L1)):*
> ```XML
> use std::collections::{HashMap, HashSet};
> ```

I'm not sure about this file name
You also have evaluator.rs for the evaluations

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/927)* status: all files reviewed, 2 unresolved discussions (waiting on @Alon-Ti)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo/927#-ODjOUM99wdI4G9FaGVv:-ODjPAjG0VU7AO3e2KT2:b5s1ayp) (no related file):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

You are not German yet
</blockquote></details>

Very nice PR!

**Review by Alon-Ti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/927)* status: all files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/expr/eval.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/stwo/927#-ODjOl45Ao-7HKuGKpxN:-ODkCH6D8qI_XmgtclPj:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/5d68434bf35bfe3058c97119c14083b6c332475e/crates/prover/src/constraint_framework/expr/eval.rs#L1)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I'm not sure about this file name
You also have evaluator.rs for the evaluations
</blockquote></details>

Done.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/927#-:-ODkDQYRCwl5R5DlXc1O:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Alon-Ti)

**Review by shaharsamocha7 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/927)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Alon-Ti)

**Pull request merged**
