### PR TITLE
Implement PolyOps for SIMD backend

### PR DESCRIPTION
**Pull request by andrewmilson**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/599)

### CODE REVIEW

**Comment by andrewmilson** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/599?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#599** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/599?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#596** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/596?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#595** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/595?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#594** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/594?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#593** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/593?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#592** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/592?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#591** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/591?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @andrewmilson and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ohad-agadi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 9 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/599#-:-Nx7Q6k3Ceq_o2QiH2bw:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @andrewmilson)

**Review by ohad-agadi — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/599)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @andrewmilson)

___
*[`crates/prover/src/core/backend/simd/column.rs` line 35 at r3](https://reviewable.io/reviews/starkware-libs/stwo/599#-NxRoTCsETZgHGLd9LvR:-NxRoTCsETZgHGLd9LvS:b535uan) ([raw file](https://github.com/starkware-libs/stwo/blob/5f808cc9a00a52231119d3f8f23585467285a265/crates/prover/src/core/backend/simd/column.rs#L35)):*
> ```XML
> }
> 
> impl BaseFieldVec {
> ```

Why are non-trait functions better here?

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/599)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @ohad-starkware)

___
*[`crates/prover/src/core/backend/simd/column.rs` line 35 at r3](https://reviewable.io/reviews/starkware-libs/stwo/599#-NxRoTCsETZgHGLd9LvR:-NxSn0V9A6VkeqB0yTMs:bbixw0c) ([raw file](https://github.com/starkware-libs/stwo/blob/5f808cc9a00a52231119d3f8f23585467285a265/crates/prover/src/core/backend/simd/column.rs#L35)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

Why are non-trait functions better here?
</blockquote></details>

Do you mean something like `impl AsRef<[BaseField]>` vs `fn as_slice`? Pros: No generics so no turbo fishes, simpler and more clear IMO.

**Review by ohad-agadi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 7 files at r3, 2 of 4 files at r4, 1 of 3 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/599#-:-Ny0UzICCf2r2nTuy2DN:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @andrewmilson)

**Pull request merged**
