### PR TITLE
Add GKR implementation of Logup lookups

### PR DESCRIPTION
**Pull request by andrewmilson**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/623)

### CODE REVIEW

**Comment by andrewmilson** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/623?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#623** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/623?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#620** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/620?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#621** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/621?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#581** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/581?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#617** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/617?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#616** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/616?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#615** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/615?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#614** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/614?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#613** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/613?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#612** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/612?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#611** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/611?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#610** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/610?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#609** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/609?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#608** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/608?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#607** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/607?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#606** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/606?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#605** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/605?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#604** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/604?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#603** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/603?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#599** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/599?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#596** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/596?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#602** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/602?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#595** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/595?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#601** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/601?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#594** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/594?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#600** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/600?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#593** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/593?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#592** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/592?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#591** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/591?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @andrewmilson and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 8 files at r3, 2 of 2 files at r5, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/623)* status: all files reviewed, 1 unresolved discussion (waiting on @andrewmilson and @shaharsamocha7)

___
*[`crates/prover/src/core/backend/cpu/lookups/gkr.rs` line 180 at r8](https://reviewable.io/reviews/starkware-libs/stwo/623#-O1WIKQMCFXAb0Ynnlsr:-O1WIKQMCFXAb0Ynnlss:b-khhiak) ([raw file](https://github.com/starkware-libs/stwo/blob/1945331fabf83fa1fc25d33e0b0c6804a1e72ae1/crates/prover/src/core/backend/cpu/lookups/gkr.rs#L180)):*
> ```XML
> ) -> (SecureField, SecureField) {
>     /// Represents the fraction `1 / x`
>     struct Reciprocal {
> ```

I wonder if this is needed, or we can use Fraction with a constant numerator, and the compiler will optimizes with constant propagation...



_Code quote:_
```XML
struct Reciprocal
```

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/623#-:-O1WJyIxDcpyBsdkb7VW:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @andrewmilson and @shaharsamocha7)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/623#-:-O1pbmrZ4KES2wgaMVYI:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @andrewmilson and @shaharsamocha7)

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/623)* status: 6 of 10 files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/core/backend/cpu/lookups/gkr.rs` line 180 at r8](https://reviewable.io/reviews/starkware-libs/stwo/623#-O1WIKQMCFXAb0Ynnlsr:-O1XEP1G8L_3I2V6bpXj:b4eqnh3) ([raw file](https://github.com/starkware-libs/stwo/blob/1945331fabf83fa1fc25d33e0b0c6804a1e72ae1/crates/prover/src/core/backend/cpu/lookups/gkr.rs#L180)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I wonder if this is needed, or we can use Fraction with a constant numerator, and the compiler will optimizes with constant propagation...
</blockquote></details>

Does not make the optimisation: https://godbolt.org/z/Mvz1YvdfT.
I remove this in a later PR in favour of a more general Reciprocal type (supporting regular and packed field types)

**Pull request merged**
