### PR TITLE
Abstracted `eval.write_frac`s to `eval.add_to_relation`s.

### PR DESCRIPTION
**Pull request by Alon-Ti**

### CODE REVIEW

**Comment by Alon-Ti** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/876?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#876** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/876?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#875** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/875?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Alon-Ti and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 9 of 14 files at r1, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/876)* status: all files reviewed, 4 unresolved discussions (waiting on @Alon-Ti and @ohad-starkware)

___
*[`crates/prover/src/examples/plonk/mod.rs` line 33 at r3](https://reviewable.io/reviews/starkware-libs/stwo/876#-OBUta0W6GtSnyEY__9f:-OBUta0X108mnUNpJR_I:b-aki5pr) ([raw file](https://github.com/starkware-libs/stwo/blob/e6cd98e9b23f09d84694e5e582414764e28f94c2/crates/prover/src/examples/plonk/mod.rs#L33)):*
> ```XML
> pub struct PlonkEval {
>     pub log_n_rows: u32,
>     pub lookup_elements: PlonkLookupElements,
> ```

Should this be plonk_relation now?
I think we maybe need a big renaming pr
X_lookup_elements -> X_relation



_Code quote:_
```XML
pub lookup_elements: PlonkLookupElements,
```
___
*[`crates/prover/src/constraint_framework/mod.rs` line 115 at r3](https://reviewable.io/reviews/starkware-libs/stwo/876#-OBUieSq5CftURfs2_5t:-OBUieSq5CftURfs2_5u:b2a1jo1) ([raw file](https://github.com/starkware-libs/stwo/blob/e6cd98e9b23f09d84694e5e582414764e28f94c2/crates/prover/src/constraint_framework/mod.rs#L115)):*
> ```XML
> 
>     /// Adds `entry.elems` to `entry.relation` with `entry.multiplicity` for all 'entry' in
>     /// 'entries', batched together.
> ```

Please add a note here that number of relations here affects the constraint degree



_Code quote:_
```XML
    /// Adds `entry.elems` to `entry.relation` with `entry.multiplicity` for all 'entry' in
    /// 'entries', batched together.
```
___
*[`crates/prover/src/constraint_framework/mod.rs` line 219 at r3](https://reviewable.io/reviews/starkware-libs/stwo/876#-OBUrN4OBsqMKgmnin_U:-OBUrN4OBsqMKgmnin_V:b-zcrubc) ([raw file](https://github.com/starkware-libs/stwo/blob/e6cd98e9b23f09d84694e5e582414764e28f94c2/crates/prover/src/constraint_framework/mod.rs#L219)):*
> ```XML
> }
> 
> pub struct RelationEntry<'a, F: Clone, EF: RelationEFTraitBound<F>, Relation: RelationType<F, EF>> {
> ```

Add documentation
Specifically, also write about multiplicity sign use/yield



_Code quote:_
```XML
pub struct RelationEntry
```
___
*[`crates/prover/src/constraint_framework/mod.rs` line 222 at r3](https://reviewable.io/reviews/starkware-libs/stwo/876#-OBUsg0nBqAVYKkFVLvq:-OBUsg0oE5ZdGw1Y964Y:bhv0tov) ([raw file](https://github.com/starkware-libs/stwo/blob/e6cd98e9b23f09d84694e5e582414764e28f94c2/crates/prover/src/constraint_framework/mod.rs#L222)):*
> ```XML
>     relation: &'a Relation,
>     multiplicity: EF,
>     elems: &'a [F],
> ```

Rename?
I don't want it to be confused with lookup_elements



_Suggestion:_
```XML
values: &'a [F],
```

**Review by ohad-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/876)* status: all files reviewed, 5 unresolved discussions (waiting on @Alon-Ti)

___
*[`crates/prover/src/constraint_framework/mod.rs` line 265 at r3](https://reviewable.io/reviews/starkware-libs/stwo/876#-OBV-c-14v2XbI2ga8UY:-OBV-c-14v2XbI2ga8UZ:bf8bmab) ([raw file](https://github.com/starkware-libs/stwo/blob/e6cd98e9b23f09d84694e5e582414764e28f94c2/crates/prover/src/constraint_framework/mod.rs#L265)):*
> ```XML
>             fn get_name(&self) -> &str {
>                 stringify!($name)
>             }
> ```

implement combine here and leave it unimplemented in Relation trait?
I think alpha, z are an implementation detail, and it does not make sense to expose them  



_Code quote:_
```XML
            fn get_z(&self) -> crate::core::fields::qm31::SecureField {
                self.0.z
            }

            fn get_alpha_powers(&self) -> &[crate::core::fields::qm31::SecureField] {
                &self.0.alpha_powers
            }

            fn get_name(&self) -> &str {
                stringify!($name)
            }
```

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/876)* status: all files reviewed, 5 unresolved discussions (waiting on @Alon-Ti and @ohad-starkware)

___
*[`crates/prover/src/constraint_framework/mod.rs` line 265 at r3](https://reviewable.io/reviews/starkware-libs/stwo/876#-OBV-c-14v2XbI2ga8UY:-OBV8s0tCISK7ci0sGiV:b5t6vh6) ([raw file](https://github.com/starkware-libs/stwo/blob/e6cd98e9b23f09d84694e5e582414764e28f94c2/crates/prover/src/constraint_framework/mod.rs#L265)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

implement combine here and leave it unimplemented in Relation trait?
I think alpha, z are an implementation detail, and it does not make sense to expose them
</blockquote></details>

He need to expose those because he uses them in the combine implementation

**Review by ohad-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/876)* status: all files reviewed, 5 unresolved discussions (waiting on @Alon-Ti and @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/mod.rs` line 265 at r3](https://reviewable.io/reviews/starkware-libs/stwo/876#-OBV-c-14v2XbI2ga8UY:-OBVZktL4G2rX824Gx58:bkoci0c) ([raw file](https://github.com/starkware-libs/stwo/blob/e6cd98e9b23f09d84694e5e582414764e28f94c2/crates/prover/src/constraint_framework/mod.rs#L265)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

He need to expose those because he uses them in the combine implementation
</blockquote></details>

I dont want the combine implementation to appear in the interface

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/876)* status: all files reviewed, 5 unresolved discussions (waiting on @Alon-Ti)

___
*[`crates/prover/src/constraint_framework/mod.rs` line 265 at r3](https://reviewable.io/reviews/starkware-libs/stwo/876#-OBV-c-14v2XbI2ga8UY:-OBVcq5QCSIwXITWTkKu:b-cu8isb) ([raw file](https://github.com/starkware-libs/stwo/blob/e6cd98e9b23f09d84694e5e582414764e28f94c2/crates/prover/src/constraint_framework/mod.rs#L265)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

I dont want the combine implementation to appear in the interface
</blockquote></details>

so you suggest to implement combine here in the macro?
@Alon-Ti WDYT?

**Review by Alon-Ti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/876)* status: 6 of 14 files reviewed, 5 unresolved discussions (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/mod.rs` line 115 at r3](https://reviewable.io/reviews/starkware-libs/stwo/876#-OBUieSq5CftURfs2_5t:-OBXhOZgAdI1x4Fuv9G-:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/e6cd98e9b23f09d84694e5e582414764e28f94c2/crates/prover/src/constraint_framework/mod.rs#L115)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Please add a note here that number of relations here affects the constraint degree
</blockquote></details>

Done.
___
*[`crates/prover/src/constraint_framework/mod.rs` line 219 at r3](https://reviewable.io/reviews/starkware-libs/stwo/876#-OBUrN4OBsqMKgmnin_U:-OBXiw9S9rWXEbceiKsm:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/e6cd98e9b23f09d84694e5e582414764e28f94c2/crates/prover/src/constraint_framework/mod.rs#L219)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Add documentation
Specifically, also write about multiplicity sign use/yield
</blockquote></details>

Done.
___
*[`crates/prover/src/constraint_framework/mod.rs` line 222 at r3](https://reviewable.io/reviews/starkware-libs/stwo/876#-OBUsg0nBqAVYKkFVLvq:-OBXiwPD06CgyV-WIWN7:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/e6cd98e9b23f09d84694e5e582414764e28f94c2/crates/prover/src/constraint_framework/mod.rs#L222)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Rename?
I don't want it to be confused with lookup_elements
</blockquote></details>

Done.
___
*[`crates/prover/src/constraint_framework/mod.rs` line 265 at r3](https://reviewable.io/reviews/starkware-libs/stwo/876#-OBV-c-14v2XbI2ga8UY:-OBXja_c441S99hxOnST:b-1cp456) ([raw file](https://github.com/starkware-libs/stwo/blob/e6cd98e9b23f09d84694e5e582414764e28f94c2/crates/prover/src/constraint_framework/mod.rs#L265)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

so you suggest to implement combine here in the macro?
@Alon-Ti WDYT?
</blockquote></details>

I think if this exposes `z` and `alphas` combine belongs here too. Would you feel better about it if this got a `RelationEntry` directly and returned the full fraction?
___
*[`crates/prover/src/examples/plonk/mod.rs` line 33 at r3](https://reviewable.io/reviews/starkware-libs/stwo/876#-OBUta0W6GtSnyEY__9f:-OBXkjb-1GDfSio892cq:bnh32h) ([raw file](https://github.com/starkware-libs/stwo/blob/e6cd98e9b23f09d84694e5e582414764e28f94c2/crates/prover/src/examples/plonk/mod.rs#L33)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Should this be plonk_relation now?
I think we maybe need a big renaming pr
X_lookup_elements -> X_relation
</blockquote></details>

I agree, adding a TODO here, we'll do it with the merge so it happens for stwo-cairo too.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/876)* status: all files reviewed, 2 unresolved discussions (waiting on @Alon-Ti and @ohad-starkware)

___
*[`crates/prover/src/constraint_framework/mod.rs` line 236 at r4](https://reviewable.io/reviews/starkware-libs/stwo/876#-OBZZpGW9RQiT5J1wZ8w:-OBZZpGW9RQiT5J1wZ8x:bm1ehj8) ([raw file](https://github.com/starkware-libs/stwo/blob/670e588c211b831bd273a9f7e9746b319b7dffc0/crates/prover/src/constraint_framework/mod.rs#L236)):*
> ```XML
>     RelationEntry<'a, F, EF, Relation>
> {
>     pub fn new(relation: &'a Relation, multiplicity: EF, elems: &'a [F]) -> Self {
> ```

also here



_Suggestion:_
```XML
values: &'a [F]
```

**Review by shaharsamocha7 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/876)* status: all files reviewed, 1 unresolved discussion (waiting on @ohad-starkware)

**Review by ohad-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/876#-:-OBZtJ4oCAtxJyfpJ0e2:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Alon-Ti)

**Review by ohad-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/876)* status: all files reviewed, 2 unresolved discussions (waiting on @Alon-Ti)

___
*[`crates/prover/src/constraint_framework/mod.rs` line 206 at r5](https://reviewable.io/reviews/starkware-libs/stwo/876#-OBt-aBg1GCXC-aFt3yZ:-OBt-aBg1GCXC-aFt3y_:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/e57adf91f6656ec481a2f102bd3604fdedebb13b/crates/prover/src/constraint_framework/mod.rs#L206)):*
> ```XML
> 
> /// A trait for defining a logup relation type.
> pub trait RelationType<F: Clone, EF: RelationEFTraitBound<F>>: Sized {
> ```





_Suggestion:_
```XML
Relation
```
___
*[`crates/prover/src/constraint_framework/mod.rs` line 223 at r5](https://reviewable.io/reviews/starkware-libs/stwo/876#-OBt-dIREQMj486q6Ihv:-OBt-dIREQMj486q6Ihw:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/e57adf91f6656ec481a2f102bd3604fdedebb13b/crates/prover/src/constraint_framework/mod.rs#L223)):*
> ```XML
>     values: &'a [F],
> }
> impl<'a, F: Clone, EF: RelationEFTraitBound<F>, Relation: RelationType<F, EF>>
> ```





_Suggestion:_
```XML
R: Relation
```

**Review by Alon-Ti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/876)* status: all files reviewed, 2 unresolved discussions (waiting on @ohad-starkware)

___
*[`crates/prover/src/constraint_framework/mod.rs` line 206 at r5](https://reviewable.io/reviews/starkware-libs/stwo/876#-OBt-aBg1GCXC-aFt3yZ:-OBtiwtb1OedWUFGL2w5:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/0bd5a5344df2735eda33cb61fc14b8d7fb75953a/crates/prover/src/constraint_framework/mod.rs#L206)):*
> ```XML
> 
> /// A trait for defining a logup relation type.
> pub trait RelationType<F: Clone, EF: RelationEFTraitBound<F>>: Sized {
> ```

Done.
___
*[`crates/prover/src/constraint_framework/mod.rs` line 223 at r5](https://reviewable.io/reviews/starkware-libs/stwo/876#-OBt-dIREQMj486q6Ihv:-OBtiwgw0RCozKIwuAr4:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/0bd5a5344df2735eda33cb61fc14b8d7fb75953a/crates/prover/src/constraint_framework/mod.rs#L223)):*
> ```XML
>     values: &'a [F],
> }
> impl<'a, F: Clone, EF: RelationEFTraitBound<F>, Relation: RelationType<F, EF>>
> ```

Done.

**Review by ohad-starkware — APPROVED** [review]
:lgtm:

> Reviewed 7 of 8 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/876#-:-OBuWns-2-yyG7FAGU-J:bnfp4nl)* status: 13 of 14 files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Pull request merged**
