### PR TITLE
Add multilinear extension

### PR DESCRIPTION
**Pull request by andrewmilson**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/565)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/565)* status: 4 of 8 files reviewed, 1 unresolved discussion (waiting on @andrewmilson and @shaharsamocha7)

___
*[`src/core/lookups/mle.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/stwo/565#-NvVs-Vs7bUPiCH6ZmxM:-NvVs-Vs7bUPiCH6ZmxN:bwgbqb2) ([raw file](https://github.com/starkware-libs/stwo/blob/c40af8dfe195b6072dcdf0e55e7fb40b0ce754dc/src/core/lookups/mle.rs#L12)):*
> ```XML
> pub trait MleOps<F: Field>: ColumnOps<F> + Sized {
>     /// Evaluates `mle` at `point`.
>     fn eval_at_point(mle: &Mle<Self, F>, point: &[F]) -> F;
> ```

This is not for use in any place in the algorithm, right?
If it's only for test, put it in a test module.
Also, I don't think it should be generic. We can assume extension field here

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/565)* status: 4 of 8 files reviewed, 2 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`src/core/lookups/mle.rs` line 62 at r1](https://reviewable.io/reviews/starkware-libs/stwo/565#-NvVsvQNDUf0ShPpdNx1:-NvVsvQNDUf0ShPpdNx2:bak6pxd) ([raw file](https://github.com/starkware-libs/stwo/blob/c40af8dfe195b6072dcdf0e55e7fb40b0ce754dc/src/core/lookups/mle.rs#L62)):*
> ```XML
> 
>     /// Returns the number of variables in the polynomial.
>     pub fn num_variables(&self) -> usize {
> ```

We use the convension `n_bla`



_Suggestion:_
```XML
n_variables
```

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/565)* status: 5 of 8 files reviewed, 2 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/565)* status: 5 of 8 files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`src/core/lookups/mle.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/stwo/565#-NvVs-Vs7bUPiCH6ZmxM:-NvY8Egx1edXm8A1gVUf:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/c40af8dfe195b6072dcdf0e55e7fb40b0ce754dc/src/core/lookups/mle.rs#L12)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

This is not for use in any place in the algorithm, right?
If it's only for test, put it in a test module.
Also, I don't think it should be generic. We can assume extension field here
</blockquote></details>

Done.
___
*[`src/core/lookups/mle.rs` line 62 at r1](https://reviewable.io/reviews/starkware-libs/stwo/565#-NvVsvQNDUf0ShPpdNx1:-NvY8F5149fiRkNwiH_1:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/c40af8dfe195b6072dcdf0e55e7fb40b0ce754dc/src/core/lookups/mle.rs#L62)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

We use the convension `n_bla`
</blockquote></details>

Done.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 8 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/565#-:-Nva250jDOC9DTxsgF5L:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Pull request merged**
