### PR TITLE
Poseidon plain proof

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/708)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/708?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#708** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/708?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#707** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/707?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#706** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/706?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#705** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/705?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#704** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/704?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#702** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/702?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#701** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/701?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/708)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo/708#-O1m5KuX56I3u7X3-J5m:-O1m5KuX56I3u7X3-J5n:bwnu016) (no related file):*
Can you explain why we need this pr?

___
___
*[`crates/prover/src/core/prover/mod.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/stwo/708#-O1m4rmb0XGDRD1SWhSW:-O1m4rmb0XGDRD1SWhSX:b-5tbbpu) ([raw file](https://github.com/starkware-libs/stwo/blob/93ace9005072f6a1fc4c8ba0b01a906a603a205b/crates/prover/src/core/prover/mod.rs#L82)):*
> ```XML
> 
> // TODO(spapini): Rename to prove, and rename prover to prove_and_commit.
> pub fn prove_without_commit<B: Backend + MerkleOps<MerkleHasher>>(
> ```

Then why did you rename that?



_Code quote:_
```XML
// TODO(spapini): Rename to prove, and rename prover to prove_and_commit.
pub fn prove_without_commit<B: Backend + MerkleOps<MerkleHasher>>(
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/708)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7)

*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo/708#-O1m5KuX56I3u7X3-J5m:-O1p_RZ0AQzgXFdYeatW:b-896fix) (no related file):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can you explain why we need this pr?
</blockquote></details>

Done.

___
___
*[`crates/prover/src/core/prover/mod.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/stwo/708#-O1m4rmb0XGDRD1SWhSW:-O1p_WlO1vVC-f46i_FE:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/93ace9005072f6a1fc4c8ba0b01a906a603a205b/crates/prover/src/core/prover/mod.rs#L82)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Then why did you rename that?
</blockquote></details>

Done.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/708)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/examples/poseidon/mod.rs` line 542 at r2](https://reviewable.io/reviews/starkware-libs/stwo/708#-O1pnUOfEfAOIRDYdRDE:-O1pnUOg8jdI5V7on6BH:b-neu3t4) ([raw file](https://github.com/starkware-libs/stwo/blob/282c69f72298ad1b27ac656d0b4806edd51b38b8/crates/prover/src/examples/poseidon/mod.rs#L542)):*
> ```XML
>         // Trace.
>         let span = span!(Level::INFO, "Trace").entered();
>         let span1 = span!(Level::INFO, "Generation").entered();
> ```

maybe this should be inside gen_trace?



_Code quote:_
```XML
        let span1 = span!(Level::INFO, "Generation").entered();
```
___
*[`crates/prover/src/examples/poseidon/mod.rs` line 565 at r2](https://reviewable.io/reviews/starkware-libs/stwo/708#-O1poIt54TLhXCUNozII:-O1poIt54TLhXCUNozIJ:blmcf5t) ([raw file](https://github.com/starkware-libs/stwo/blob/282c69f72298ad1b27ac656d0b4806edd51b38b8/crates/prover/src/examples/poseidon/mod.rs#L565)):*
> ```XML
> 
>         // Decommit.
>         let sizes = air.column_log_sizes();
> ```

rename and document



_Code quote:_
```XML
let sizes = air.column_log_sizes();
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/708)* status: all files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`crates/prover/src/examples/poseidon/mod.rs` line 565 at r2](https://reviewable.io/reviews/starkware-libs/stwo/708#-O1poIt54TLhXCUNozII:-O1ppej9CB3682GMTryi:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/282c69f72298ad1b27ac656d0b4806edd51b38b8/crates/prover/src/examples/poseidon/mod.rs#L565)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

rename and document
</blockquote></details>

Done.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/708#-:-O1vRXrhD0_sboZZktKe:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
