### PR TITLE
fft without copying

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/535)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
* **#535** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/535?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by spapinistarkware** [comment]
This change avoids the initial "copy" of the coefficients when doing an LDE. Benchmarks show 6% improvement.

**Comment by ilyalesokhin-starkware** [comment]
*[`benches/fft.rs` line 50 at r3](https://reviewable.io/reviews/starkware-libs/stwo/535#-NtopVbT1lzqqwB2XzhT:-NtopVbT1lzqqwB2XzhU:b-yami19) ([raw file](https://github.com/starkware-libs/stwo/blob/c0cbc3ccd66c6ebc35b13f330352a23eb63271b1/benches/fft.rs#L50)):*
> ```XML
>     if !platform::avx512_detected() {
>         return;
>     }
> ```

Why is it here?



_Code quote:_
```XML
    if !platform::avx512_detected() {
        return;
    }
```

**Comment by ilyalesokhin-starkware** [comment]
*[`benches/fft.rs` line 50 at r3](https://reviewable.io/reviews/starkware-libs/stwo/535#-NtopVbT1lzqqwB2XzhT:-Ntopf5P7QvADnXOROUJ:bzhz482) ([raw file](https://github.com/starkware-libs/stwo/blob/c0cbc3ccd66c6ebc35b13f330352a23eb63271b1/benches/fft.rs#L50)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Why is it here?
</blockquote></details>

nvm, just saw that its is a benchmark

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/535#-:-NtorBQw-tkbOj6ACYTh:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
