### PR TITLE
ComponentRegistry

### PR DESCRIPTION
**Pull request by shaharsamocha7**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/665)

### CODE REVIEW

**Comment by shaharsamocha7** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/665?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#665** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/665?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#663** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/663?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @shaharsamocha7 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/665)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`crates/prover/src/trace_generation/registry.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/stwo/665#-O-_vwBM47KKmB41HoOz:-O-_vwBN4STtjb7UQJiy:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/f142cbaf45849dd2f49d6032d653252253506ff1/crates/prover/src/trace_generation/registry.rs#L13)):*
> ```XML
>     pub fn register_component(&mut self, component_id: String, component: Box<dyn ComponentGen>) {
>         self.components.insert(component_id, component);
>     }
> ```





_Suggestion:_
```XML
    pub fn register_component(&mut self, component_id: String, component: impl ComponentGen) {
        self.components.insert(component_id, Box::new(component));
    }
```

**Review by ohad-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/665)* status: all files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/prover/src/trace_generation/registry.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/stwo/665#-O-aZMjwDqZYknpY8M20:-O-aZMjwDqZYknpY8M21:b-gz4u6n) ([raw file](https://github.com/starkware-libs/stwo/blob/f142cbaf45849dd2f49d6032d653252253506ff1/crates/prover/src/trace_generation/registry.rs#L20)):*
> ```XML
>             .unwrap()
>             .downcast_ref()
>             .unwrap()
> ```

add error message to each unwrap so we know why it crashes

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/665)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @ohad-starkware and @spapinistarkware)

___
*[`crates/prover/src/trace_generation/registry.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/stwo/665#-O-_vwBM47KKmB41HoOz:-O-agf-zDWEZMtMOMZMb:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/f142cbaf45849dd2f49d6032d653252253506ff1/crates/prover/src/trace_generation/registry.rs#L13)):*
> ```XML
>     pub fn register_component(&mut self, component_id: String, component: Box<dyn ComponentGen>) {
>         self.components.insert(component_id, component);
>     }
> ```

Done.
___
*[`crates/prover/src/trace_generation/registry.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/stwo/665#-O-aZMjwDqZYknpY8M20:-O-agg5E9IPn6z7A8WsH:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/f142cbaf45849dd2f49d6032d653252253506ff1/crates/prover/src/trace_generation/registry.rs#L20)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

add error message to each unwrap so we know why it crashes
</blockquote></details>

Done.

**Review by ohad-starkware — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/665#-:-O-j7X_N2LnCHS4boEGH:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Comment by ohad-starkware** [comment]
*[`crates/prover/src/trace_generation/registry.rs` line 13 at r3](https://reviewable.io/reviews/starkware-libs/stwo/665#-O-kIgZG6_HubyCC1I84:-O-kIgZG6_HubyCC1I85:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/9f56171106dd67d0cb4ba2c78420d6e4c73de125/crates/prover/src/trace_generation/registry.rs#L13)):*
> ```XML
>     pub fn register_component(&mut self, component_id: String, component: impl ComponentGen) {
>         self.components.insert(component_id, Box::new(component));
>     }
> ```





_Suggestion:_
```XML
    pub fn register_component(&mut self, component_id: &str, component: impl ComponentGen) {
        self.components.insert(component_id.to_string(), Box::new(component));
    }
```

**Review by ohad-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/665)* status: all files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/prover/src/trace_generation/registry.rs` line 21 at r3](https://reviewable.io/reviews/starkware-libs/stwo/665#-O-kLB_09h_JpEbeedxM:-O-kLB_09h_JpEbeedxN:b6slemb) ([raw file](https://github.com/starkware-libs/stwo/blob/9f56171106dd67d0cb4ba2c78420d6e4c73de125/crates/prover/src/trace_generation/registry.rs#L21)):*
> ```XML
>             .downcast_ref()
>             .unwrap()
>     }
> ```

we want to do a get then add inputs to the pre-registered component, right?



_Suggestion:_
```XML
    pub fn get_component<T: ComponentGen>(&mut self, component_id: &str) -> &mut T {
        self.components
            .get(component_id)
            .unwrap_or_else(|| panic!("Component name {} not found.", component_id))
            .downcast_ref()
            .unwrap()
    }
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/665)* status: all files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`crates/prover/src/trace_generation/registry.rs` line 21 at r3](https://reviewable.io/reviews/starkware-libs/stwo/665#-O-kLB_09h_JpEbeedxM:-O-kLpnh31cy_XhMZCjw:b-hgtbrk) ([raw file](https://github.com/starkware-libs/stwo/blob/9f56171106dd67d0cb4ba2c78420d6e4c73de125/crates/prover/src/trace_generation/registry.rs#L21)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

we want to do a get then add inputs to the pre-registered component, right?
</blockquote></details>

didnt look below

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/665)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ohad-starkware and @spapinistarkware)

___
*[`crates/prover/src/trace_generation/registry.rs` line 13 at r3](https://reviewable.io/reviews/starkware-libs/stwo/665#-O-kIgZG6_HubyCC1I84:-O-of4Kc0BbfBAzA74U_:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/9f56171106dd67d0cb4ba2c78420d6e4c73de125/crates/prover/src/trace_generation/registry.rs#L13)):*
> ```XML
>     pub fn register_component(&mut self, component_id: String, component: impl ComponentGen) {
>         self.components.insert(component_id, Box::new(component));
>     }
> ```

Done.

**Review by ohad-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/665#-:-O-ogzJP5EQjsHJcTLo9:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Comment by shaharsamocha7** [comment]
### Merge activity

* **Jun 20, 4:43 AM EDT**: @shaharsamocha7 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/665).

**Pull request merged**
