### PR TITLE
constant column attempt 1

### PR DESCRIPTION
**Pull request by ohad-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/849)

### CODE REVIEW

**Comment by ohad-starkware** [comment]
* **#849** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/849?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ohad-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/prover/src/core/air/components.rs` line 49 at r4](https://reviewable.io/reviews/starkware-libs/stwo/849#-OACJquf8Le1aGoVa1JS:-OACJquf8Le1aGoVa1JT:b-aftocr) ([raw file](https://github.com/starkware-libs/stwo/blob/26bb2a24af1aa1e5bf428d9db300aa40ed46fbc7/crates/prover/src/core/air/components.rs#L49)):*
> ```XML
>         let mut static_column_masks: Vec<BTreeSet<CirclePoint<SecureField>>> = vec![];
>         for component in &self.0 {
>             let component_static_masks = &component.mask_points(point)[CONST_INTERACTION];
> ```

What about the other interactions?



_Code quote:_
```XML
      let component_static_masks = &component.mask_points(point)[CONST_INTERACTION];
```

**Comment by ohad-starkware** [comment]
*[`crates/prover/src/core/air/components.rs` line 49 at r4](https://reviewable.io/reviews/starkware-libs/stwo/849#-OACJquf8Le1aGoVa1JS:-OACKjBs0vGVGuh8dqzD:b-9l6ryj) ([raw file](https://github.com/starkware-libs/stwo/blob/26bb2a24af1aa1e5bf428d9db300aa40ed46fbc7/crates/prover/src/core/air/components.rs#L49)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

What about the other interactions?
</blockquote></details>

look at the function above

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/prover/src/core/pcs/utils.rs` line 130 at r4](https://reviewable.io/reviews/starkware-libs/stwo/849#-OAI_voJD2k2l0xxnAxh:-OAI_voJD2k2l0xxnAxi:b-7syh4g) ([raw file](https://github.com/starkware-libs/stwo/blob/26bb2a24af1aa1e5bf428d9db300aa40ed46fbc7/crates/prover/src/core/pcs/utils.rs#L130)):*
> ```XML
>         let mut res = TreeVec(vec![Vec::new(); max_tree_index + 1]);
> 
>         for &location in locations.iter().filter(|l| l.col_start != l.col_end) {
> ```

What is happening here?



_Code quote:_
```XML
.iter().filter(|l| l.col_start != l.col_end)
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/849)* status: 0 of 30 files reviewed, 2 unresolved discussions (waiting on @ohad-starkware)

___
*[`crates/prover/src/constraint_framework/component.rs` line 182 at r4](https://reviewable.io/reviews/starkware-libs/stwo/849#-OANGxesEqOzuQRhPDKm:-OANGxesEqOzuQRhPDKn:b-6ghq89) ([raw file](https://github.com/starkware-libs/stwo/blob/26bb2a24af1aa1e5bf428d9db300aa40ed46fbc7/crates/prover/src/constraint_framework/component.rs#L182)):*
> ```XML
>             [
>                 trace.polys.sub_tree(&mask_spans),
>                 trace.polys.sub_tree_sparse(&self.static_columns_locations),
> ```

Why is this at the end?



_Code quote:_
```XML
 trace.polys.sub_tree_sparse(&self.static_columns_locations),
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/849)* status: 0 of 30 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/prover/src/constraint_framework/component.rs` line 182 at r4](https://reviewable.io/reviews/starkware-libs/stwo/849#-OANGxesEqOzuQRhPDKm:-OANeYPS1XmnsBdzKwoT:b5nufvm) ([raw file](https://github.com/starkware-libs/stwo/blob/26bb2a24af1aa1e5bf428d9db300aa40ed46fbc7/crates/prover/src/constraint_framework/component.rs#L182)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Why is this at the end?
</blockquote></details>

order wont matter here - 
Treevec::concat_cols is concat-by-index, meaning  res[i] = concat (tree_0[i]..tree_n[i])
here there are 2 trees, the first has an empty vec in its first entry, and the second is empty in the rest.

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/849)* status: 0 of 30 files reviewed, 3 unresolved discussions (waiting on @ohad-starkware)

___
*[`crates/prover/src/core/air/components.rs` line 83 at r4](https://reviewable.io/reviews/starkware-libs/stwo/849#-OAR_C_J5yCNUkV-_QSG:-OAR_C_J5yCNUkV-_QSH:b8b25vt) ([raw file](https://github.com/starkware-libs/stwo/blob/26bb2a24af1aa1e5bf428d9db300aa40ed46fbc7/crates/prover/src/core/air/components.rs#L83)):*
> ```XML
>         mask_values: &[Vec<SecureField>],
>     ) -> ColumnVec<Vec<SecureField>> {
>         let mask_by_column = &self.mask_points_by_column(point)[CONST_INTERACTION];
> ```

Why not?



_Suggestion:_
```XML
&self.const_mask_points_by_column(point);
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/849)* status: 0 of 30 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/prover/src/core/air/components.rs` line 83 at r4](https://reviewable.io/reviews/starkware-libs/stwo/849#-OAR_C_J5yCNUkV-_QSG:-OARh_3k7pSJYVaOn_hv:b-fxtx3s) ([raw file](https://github.com/starkware-libs/stwo/blob/26bb2a24af1aa1e5bf428d9db300aa40ed46fbc7/crates/prover/src/core/air/components.rs#L83)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Why not?
</blockquote></details>

I guess it was a mistake
iirc I tried to allow 'global access' regardless of the interaction, and later gave up on that.

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/prover/src/constraint_framework/constant_columns.rs` line 97 at r4](https://reviewable.io/reviews/starkware-libs/stwo/849#-OAvjL98-9fkLlqb4ASp:-OAvjL995YSzbkVdXcxb:bb9pu9i) ([raw file](https://github.com/starkware-libs/stwo/blob/26bb2a24af1aa1e5bf428d9db300aa40ed46fbc7/crates/prover/src/constraint_framework/constant_columns.rs#L97)):*
> ```XML
>         locations.add(ConstantColumn::XorTable(4, 0, 0), 9);
>         locations.add(ConstantColumn::XorTable(4, 0, 1), 10);
>         locations.add(ConstantColumn::XorTable(4, 0, 2), 11);
> ```

why this order?



_Code quote:_
```XML
        locations.add(ConstantColumn::XorTable(7, 2, 0), 12);
        locations.add(ConstantColumn::XorTable(7, 2, 1), 13);
        locations.add(ConstantColumn::XorTable(7, 2, 2), 14);

        locations.add(ConstantColumn::XorTable(4, 0, 0), 9);
        locations.add(ConstantColumn::XorTable(4, 0, 1), 10);
        locations.add(ConstantColumn::XorTable(4, 0, 2), 11);
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/849)* status: 0 of 30 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/prover/src/constraint_framework/constant_columns.rs` line 97 at r4](https://reviewable.io/reviews/starkware-libs/stwo/849#-OAvjL98-9fkLlqb4ASp:-OAw3Lti3g2hP0XkTgXg:b-z5748l) ([raw file](https://github.com/starkware-libs/stwo/blob/26bb2a24af1aa1e5bf428d9db300aa40ed46fbc7/crates/prover/src/constraint_framework/constant_columns.rs#L97)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why this order?
</blockquote></details>

testing edge cases for reorganize_by_column etc

**Pull request closed without merging**
