### PR TITLE
SIMD grind

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/785)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/785?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#785** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/785?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#784** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/784?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 9 files at r1, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/785)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/grind.rs` line 30 at r4](https://reviewable.io/reviews/starkware-libs/stwo/785#-O49yUJ5BUi3uuRuZd88:-O49yUJ5BUi3uuRuZd89:blorf1v) ([raw file](https://github.com/starkware-libs/stwo/blob/7bd1b0a7af8e262a598438d1434f93484d39665e/crates/prover/src/core/backend/simd/grind.rs#L30)):*
> ```XML
>             for l in (0..=u32::MAX).step_by(16) {
>                 let res = compress16(state, attempt, zero, zero, zero, zero);
>                 let success_mask = res[0].trailing_zeros().simd_ge(pow_bits);
> ```

Support up to 64 pow_bits, or add a todo for it (and an assertion).



_Code quote:_
```XML
let success_mask = res[0].trailing_zeros().simd_ge(pow_bits);
```
___
*[`crates/prover/src/core/backend/simd/grind.rs` line 33 at r4](https://reviewable.io/reviews/starkware-libs/stwo/785#-O49yxIBAG9kLa_FAhBv:-O49yxIBAG9kLa_FAhBw:bri4o4p) ([raw file](https://github.com/starkware-libs/stwo/blob/7bd1b0a7af8e262a598438d1434f93484d39665e/crates/prover/src/core/backend/simd/grind.rs#L33)):*
> ```XML
>                 if success_mask.any() {
>                     let i = success_mask.to_array().iter().position(|&x| x).unwrap();
>                     return h as u64 + l as u64 + i as u64;
> ```

shift h.



_Code quote:_
```XML
return h as u64 + l as u64 + i as u64;
```

**Review by alonh5 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/785)* status: all files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/grind.rs` line 33 at r4](https://reviewable.io/reviews/starkware-libs/stwo/785#-O4A5pfW0WQaeqU_3yXG:-O4A5pfW0WQaeqU_3yXH:brv6pjy) ([raw file](https://github.com/starkware-libs/stwo/blob/7bd1b0a7af8e262a598438d1434f93484d39665e/crates/prover/src/core/backend/simd/grind.rs#L33)):*
> ```XML
>                 if success_mask.any() {
>                     let i = success_mask.to_array().iter().position(|&x| x).unwrap();
>                     return h as u64 + l as u64 + i as u64;
> ```

Consider



_Suggestion:_
```XML
return high as u64 + low as u64 + i as u64;
```

**Review by alonh5 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/785)* status: all files reviewed, 4 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/grind.rs` line 24 at r4](https://reviewable.io/reviews/starkware-libs/stwo/785#-O4AAxsB3ML8abno9ZHW:-O4AAxsB3ML8abno9ZHX:b-y2besv) ([raw file](https://github.com/starkware-libs/stwo/blob/7bd1b0a7af8e262a598438d1434f93484d39665e/crates/prover/src/core/backend/simd/grind.rs#L24)):*
> ```XML
>         let state: [u32x16; 8] = std::array::from_fn(|i| u32x16::splat(digest[i]));
> 
>         let mut attempt = [zero; 16];
> ```

Also below.



_Suggestion:_
```XML
N_LANES
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/785)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @alonh5)

___
*[`crates/prover/src/core/backend/simd/grind.rs` line 24 at r4](https://reviewable.io/reviews/starkware-libs/stwo/785#-O4AAxsB3ML8abno9ZHW:-O4APcs_509DcCPCb4_9:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/7bd1b0a7af8e262a598438d1434f93484d39665e/crates/prover/src/core/backend/simd/grind.rs#L24)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Also below.
</blockquote></details>

Done.
___
*[`crates/prover/src/core/backend/simd/grind.rs` line 30 at r4](https://reviewable.io/reviews/starkware-libs/stwo/785#-O49yUJ5BUi3uuRuZd88:-O4APXK54N8mIxk6-EsT:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/7bd1b0a7af8e262a598438d1434f93484d39665e/crates/prover/src/core/backend/simd/grind.rs#L30)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Support up to 64 pow_bits, or add a todo for it (and an assertion).
</blockquote></details>

Done.
___
*[`crates/prover/src/core/backend/simd/grind.rs` line 33 at r4](https://reviewable.io/reviews/starkware-libs/stwo/785#-O49yxIBAG9kLa_FAhBv:-O4APXu2BHJH0e6ZHtxF:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/7bd1b0a7af8e262a598438d1434f93484d39665e/crates/prover/src/core/backend/simd/grind.rs#L33)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

shift h.
</blockquote></details>

Done.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/785)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/grind.rs` line 17 at r5](https://reviewable.io/reviews/starkware-libs/stwo/785#-O4AQxMCDQlfeXZObfwK:-O4AQxMCDQlfeXZObfwL:b-606r63) ([raw file](https://github.com/starkware-libs/stwo/blob/0a0f64634927101de5daccfb632b70fc5752ba75/crates/prover/src/core/backend/simd/grind.rs#L17)):*
> ```XML
> impl GrindOps<Blake2sChannel> for SimdBackend {
>     fn grind(channel: &Blake2sChannel, pow_bits: u32) -> u64 {
>         assert!(pow_bits <= 32, "pow_bits >= 32 is not supported");
> ```

Add TODO?



_Suggestion:_
```XML
assert!(pow_bits <= 32, "pow_bits > 32 is not supported");
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/785)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/prover/src/core/backend/simd/grind.rs` line 17 at r5](https://reviewable.io/reviews/starkware-libs/stwo/785#-O4AQxMCDQlfeXZObfwK:-O4AxotYBlAkabZr-z3g:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/0a0f64634927101de5daccfb632b70fc5752ba75/crates/prover/src/core/backend/simd/grind.rs#L17)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Add TODO?
</blockquote></details>

Done.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/785#-:-O4B-CmH2W0i9kXSgOu-:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
