### PR TITLE
Optimize base field inverse

### PR DESCRIPTION
**Pull request by andrewmilson**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/571)

### CODE REVIEW

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/571)* status: all files reviewed, 1 unresolved discussion (waiting on @andrewmilson)

___
*[`src/core/fields/m31.rs` line 141 at r1](https://reviewable.io/reviews/starkware-libs/stwo/571#-NvCEOZfAhbtGIEWFc1G:-NvCEOZfAhbtGIEWFc1H:b48vmvp) ([raw file](https://github.com/starkware-libs/stwo/blob/c76501e567ae3ce50c448f40121404b708851439/src/core/fields/m31.rs#L141)):*
> ```XML
> /// multiplications. Made generic to support both vectorized and non-vectorized implementations.
> /// Multiplication tree found with [addchain](https://github.com/mmcloughlin/addchain).
> pub fn pow2147483645<T: FieldExpOps>(v: T) -> T {
> ```

Add unit test?

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/571)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`src/core/fields/m31.rs` line 141 at r1](https://reviewable.io/reviews/starkware-libs/stwo/571#-NvCEOZfAhbtGIEWFc1G:-NvwKtFW2-PfE2D4Xb8c:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/c76501e567ae3ce50c448f40121404b708851439/src/core/fields/m31.rs#L141)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Add unit test?
</blockquote></details>

Done.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/571#-:-NwnWN672s4xdl5KXmSs:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @andrewmilson)

___
*[`crates/prover/src/core/fields/m31.rs` line 216 at r2](https://reviewable.io/reviews/starkware-libs/stwo/571#-NwnW5do-hysO1j7z8cc:-NwnW5do-hysO1j7z8cd:b-z6j8s1) ([raw file](https://github.com/starkware-libs/stwo/blob/316fac46a595c6ce66f32e4fdb081dd81f269548/crates/prover/src/core/fields/m31.rs#L216)):*
> ```XML
>     #[test]
>     fn pow2147483645_works() {
>         let v = BaseField::from(2);
> ```

Consider choosing a less trivial number or using generating a random one.



_Code quote:_
```XML
let v = BaseField::from(2);
```

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/571)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/prover/src/core/fields/m31.rs` line 216 at r2](https://reviewable.io/reviews/starkware-libs/stwo/571#-NwnW5do-hysO1j7z8cc:-NwoOmA010klSLMt0ZJA:bdbv0xx) ([raw file](https://github.com/starkware-libs/stwo/blob/316fac46a595c6ce66f32e4fdb081dd81f269548/crates/prover/src/core/fields/m31.rs#L216)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Consider choosing a less trivial number or using generating a random one.
</blockquote></details>

How does another value test the function better than 2?

**Review by alonh5 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/571)* status: all files reviewed, 1 unresolved discussion (waiting on @andrewmilson)

___
*[`crates/prover/src/core/fields/m31.rs` line 216 at r2](https://reviewable.io/reviews/starkware-libs/stwo/571#-NwnW5do-hysO1j7z8cc:-NwoQUic0xfoIHfEijP6:b-kx2c0t) ([raw file](https://github.com/starkware-libs/stwo/blob/316fac46a595c6ce66f32e4fdb081dd81f269548/crates/prover/src/core/fields/m31.rs#L216)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

How does another value test the function better than 2?
</blockquote></details>

It probably doesn't, just in the case the trick somehow only works for 2.

For example if you're testing a function that should implement pow(a, b) and you check that pow(2, 2) == 4. It would pass even if it implements addition or multiplication. I think there's a higher probability of that happening when it's a number like 2 rather than say 19.

It doesn't really matter, just very easy to change. Anyway it's non blocking I LGTMed.

**Review by alonh5 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/571)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @andrewmilson)

**Pull request merged**
