### PR TITLE
SIMD backend for poseidon252 merkle ops - CPU IMPL

### PR DESCRIPTION
**Pull request by shaharsamocha7**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/809)

### CODE REVIEW

**Comment by shaharsamocha7** [comment]
* **#809** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/809?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @shaharsamocha7 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/809)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/mod.rs` line 5 at r2](https://reviewable.io/reviews/starkware-libs/stwo/809#-O5H_gA_Dzbm5Ek-2FoG:-O5H_gA_Dzbm5Ek-2FoH:bt21es) ([raw file](https://github.com/starkware-libs/stwo/blob/22e7b3b5f0514401b15dc74c9ad98c2f593f316a/crates/prover/src/core/backend/simd/mod.rs#L5)):*
> ```XML
> use super::{Backend, BackendForChannel};
> use crate::core::vcs::blake2_merkle::Blake2sMerkleChannel;
> #[cfg(not(target_arch = "wasm32"))]
> ```

@spapinistarkware 
Why the poseidon isn't supported on wasm? Can we sort it differently so we don't have this line everywhere?



_Code quote:_
```XML
#[cfg(not(target_arch = "wasm32"))]
```

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/809)* status: all files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/prover/src/core/backend/simd/mod.rs` line 5 at r2](https://reviewable.io/reviews/starkware-libs/stwo/809#-O5H_gA_Dzbm5Ek-2FoG:-O5IbGKF9PZJUTyeiAXX:bkr7c50) ([raw file](https://github.com/starkware-libs/stwo/blob/22e7b3b5f0514401b15dc74c9ad98c2f593f316a/crates/prover/src/core/backend/simd/mod.rs#L5)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

@spapinistarkware 
Why the poseidon isn't supported on wasm? Can we sort it differently so we don't have this line everywhere?
</blockquote></details>

I'd like that very much. Can you check what goes wrong without this line?
I think it's related to Felt impl somehow, not sure.
___
*[`crates/prover/src/examples/plonk/mod.rs` line 183 at r2](https://reviewable.io/reviews/starkware-libs/stwo/809#-O5IbaPj51TqZZQMsBRw:-O5IbaPj51TqZZQMsBRx:b-fsalay) ([raw file](https://github.com/starkware-libs/stwo/blob/22e7b3b5f0514401b15dc74c9ad98c2f593f316a/crates/prover/src/examples/plonk/mod.rs#L183)):*
> ```XML
>     let span = span!(Level::INFO, "Trace").entered();
>     let trace = gen_trace(log_n_rows, &circuit);
>     let mut tree_builder: TreeBuilder<'_, '_, SimdBackend, Blake2sMerkleChannel> =
> ```

Can you move these generic to the commitment_scheme definition?
___
*[`crates/prover/src/examples/poseidon/mod.rs` line 350 at r2](https://reviewable.io/reviews/starkware-libs/stwo/809#-O5Ibfhh-Hy2Vov5Lk2s:-O5Ibfhh-Hy2Vov5Lk2t:bb73xfv) ([raw file](https://github.com/starkware-libs/stwo/blob/22e7b3b5f0514401b15dc74c9ad98c2f593f316a/crates/prover/src/examples/poseidon/mod.rs#L350)):*
> ```XML
>     let span = span!(Level::INFO, "Trace").entered();
>     let (trace, lookup_data) = gen_trace(log_n_rows);
>     let mut tree_builder: TreeBuilder<'_, '_, SimdBackend, Blake2sMerkleChannel> =
> ```

Same

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/809)* status: 7 of 9 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/mod.rs` line 5 at r2](https://reviewable.io/reviews/starkware-libs/stwo/809#-O5H_gA_Dzbm5Ek-2FoG:-O5IflDjDDt8y4x0-Pcj:btdv34e) ([raw file](https://github.com/starkware-libs/stwo/blob/22e7b3b5f0514401b15dc74c9ad98c2f593f316a/crates/prover/src/core/backend/simd/mod.rs#L5)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I'd like that very much. Can you check what goes wrong without this line?
I think it's related to Felt impl somehow, not sure.
</blockquote></details>

I will
___
*[`crates/prover/src/examples/plonk/mod.rs` line 183 at r2](https://reviewable.io/reviews/starkware-libs/stwo/809#-O5IbaPj51TqZZQMsBRw:-O5IfWFB3Wp-HnQTJNUq:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/22e7b3b5f0514401b15dc74c9ad98c2f593f316a/crates/prover/src/examples/plonk/mod.rs#L183)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Can you move these generic to the commitment_scheme definition?
</blockquote></details>

Done.
___
*[`crates/prover/src/examples/poseidon/mod.rs` line 350 at r2](https://reviewable.io/reviews/starkware-libs/stwo/809#-O5Ibfhh-Hy2Vov5Lk2s:-O5Ifg6eCjMkt98LfmPE:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/22e7b3b5f0514401b15dc74c9ad98c2f593f316a/crates/prover/src/examples/poseidon/mod.rs#L350)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Same
</blockquote></details>

Done.

**Review by spapinistarkware — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/809)* status: all files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r1, 5 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/809)* status: all files reviewed, 4 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/poseidon252.rs` line 16 at r3](https://reviewable.io/reviews/starkware-libs/stwo/809#-O5Ixgha65gSKNRvF21G:-O5Ixgha65gSKNRvF21H:b-mw0jct) ([raw file](https://github.com/starkware-libs/stwo/blob/7159780bc39c3931171c0378d6382cc11bce41f6/crates/prover/src/core/backend/simd/poseidon252.rs#L16)):*
> ```XML
> 
>     fn bit_reverse_column(_column: &mut Self::Column) {
>         unimplemented!()
> ```

Why is this needed now if it's not used?
___
*[`crates/prover/src/core/vcs/poseidon252_merkle.rs` line 50 at r3](https://reviewable.io/reviews/starkware-libs/stwo/809#-O5IxVDW1APjrL_A7DSa:-O5IxVDXCoLyk2aRlF9v:bqsiitr) ([raw file](https://github.com/starkware-libs/stwo/blob/40cb2feac9229c5dc42aec33f8f6b9979d7a204b/crates/prover/src/core/vcs/poseidon252_merkle.rs#L50)):*
> ```XML
> 
> impl MerkleOps<Poseidon252MerkleHasher> for CpuBackend {
>     fn commit_on_layer(
> ```

Maybe instead of removing you can call this from the simd impl?
___
*[`crates/prover/src/examples/plonk/mod.rs` line 179 at r3](https://reviewable.io/reviews/starkware-libs/stwo/809#-O5IyUFu0R3ErWLjpN0m:-O5IyUFu0R3ErWLjpN0n:brejra4) ([raw file](https://github.com/starkware-libs/stwo/blob/7159780bc39c3931171c0378d6382cc11bce41f6/crates/prover/src/examples/plonk/mod.rs#L179)):*
> ```XML
>     let channel = &mut Blake2sChannel::default();
>     let commitment_scheme =
>         &mut CommitmentSchemeProver::<SimdBackend, Blake2sMerkleChannel>::new(config, &twiddles);
> ```

Same below



_Suggestion:_
```XML
<_, Blake2sMerkleChannel>
```

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/809)* status: 6 of 9 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/poseidon252.rs` line 16 at r3](https://reviewable.io/reviews/starkware-libs/stwo/809#-O5Ixgha65gSKNRvF21G:-O5JLNXz0GwH_FVv6hHG:bbro7lg) ([raw file](https://github.com/starkware-libs/stwo/blob/7159780bc39c3931171c0378d6382cc11bce41f6/crates/prover/src/core/backend/simd/poseidon252.rs#L16)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Why is this needed now if it's not used?
</blockquote></details>

We need to have ColumnOps to implement MerkleOps.
___
*[`crates/prover/src/core/vcs/poseidon252_merkle.rs` line 50 at r3](https://reviewable.io/reviews/starkware-libs/stwo/809#-O5IxVDW1APjrL_A7DSa:-O5JLAkW4ICLKaTyjrHM:bxgbrw5) ([raw file](https://github.com/starkware-libs/stwo/blob/40cb2feac9229c5dc42aec33f8f6b9979d7a204b/crates/prover/src/core/vcs/poseidon252_merkle.rs#L50)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Maybe instead of removing you can call this from the simd impl?
</blockquote></details>

I moved this code to a poseidon252.rs file under cpu folder, to match the convention as in SIMD
___
*[`crates/prover/src/examples/plonk/mod.rs` line 179 at r3](https://reviewable.io/reviews/starkware-libs/stwo/809#-O5IyUFu0R3ErWLjpN0m:-O5JNIPODrqyKkUft6Et:b-896fja) ([raw file](https://github.com/starkware-libs/stwo/blob/7159780bc39c3931171c0378d6382cc11bce41f6/crates/prover/src/examples/plonk/mod.rs#L179)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Same below
</blockquote></details>

Done!

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/809#-:-O5MxNexAc56gXDbe5Cy:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shaharsamocha7)

___
*[`crates/prover/src/core/vcs/poseidon252_merkle.rs` line 50 at r3](https://reviewable.io/reviews/starkware-libs/stwo/809#-O5IxVDW1APjrL_A7DSa:-O5MwHJQ1AcKncFoD9vA:bpvhg3f) ([raw file](https://github.com/starkware-libs/stwo/blob/40cb2feac9229c5dc42aec33f8f6b9979d7a204b/crates/prover/src/core/vcs/poseidon252_merkle.rs#L50)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I moved this code to a poseidon252.rs file under cpu folder, to match the convention as in SIMD
</blockquote></details>

Oh I missed that.

**Comment by shaharsamocha7** [comment]
### Merge activity

* **Aug 29, 6:21 AM EDT**: @shaharsamocha7 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/809).

**Pull request merged**
