### PR TITLE
Logup without is_first

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/780)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
* **#780** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/780?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/780)* status: all files reviewed, 2 unresolved discussions (waiting on @Alon-Ti and @spapinistarkware)

___
*[`crates/prover/src/constraint_framework/logup.rs` line 217 at r1](https://reviewable.io/reviews/starkware-libs/stwo/780#-O3gRxKG5c5vmQyHRyWZ:-O3gRxKG5c5vmQyHRyW_:ba3dfmt) ([raw file](https://github.com/starkware-libs/stwo/blob/ac8116f79da8e535132f32e2920c779accef11f3/crates/prover/src/constraint_framework/logup.rs#L217)):*
> ```XML
>             columns: coord_prefix_sum,
>         });
>         // let claimed_sum = self.trace.last().unwrap().at(1);
> ```

Remove.



_Code quote:_
```XML
 // let claimed_sum = self.trace.last().unwrap().at(1);
```
___
*[`crates/prover/src/examples/blake/scheduler/mod.rs` line 91 at r1](https://reviewable.io/reviews/starkware-libs/stwo/780#-O3gYaTU9oz7aQ04HbNq:-O3gYaTU9oz7aQ04HbNr:bqzl1fc) ([raw file](https://github.com/starkware-libs/stwo/blob/ac8116f79da8e535132f32e2920c779accef11f3/crates/prover/src/examples/blake/scheduler/mod.rs#L91)):*
> ```XML
>         );
> 
>         let trace = TreeVec::new(vec![trace, interaction_trace, vec![]]);
> ```

Do we still need this third empty trace?



_Code quote:_
```XML
vec![]
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/780)* status: all files reviewed, 1 unresolved discussion (waiting on @Alon-Ti and @alonh5)

___
*[`crates/prover/src/constraint_framework/logup.rs` line 217 at r1](https://reviewable.io/reviews/starkware-libs/stwo/780#-O3gRxKG5c5vmQyHRyWZ:-O3gf9E44o_mZdWkcKNL:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/ac8116f79da8e535132f32e2920c779accef11f3/crates/prover/src/constraint_framework/logup.rs#L217)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Remove.
</blockquote></details>

Done.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/780#-:-O3gfkoABIzawxXnpE-S:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Alon-Ti)

**Pull request merged**
