### PR TITLE
Blake air

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/773)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/773?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#773** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/773?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#770** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/770?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#767** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/767?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#765** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/765?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#764** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/764?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#761** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/761?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#712** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/712?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#711** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/711?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#710** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/710?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#708** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/708?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#707** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/707?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#715** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/715?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#714** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/714?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#713** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/713?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#706** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/706?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#705** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/705?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#704** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/704?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#702** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/702?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#701** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/701?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 8 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/773)* status: 8 of 9 files reviewed, 11 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/examples/blake/air.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/stwo/773#-O3bueIMD1h1WbDiZJ0Z:-O3bueIMD1h1WbDiZJ0_:bcdepph) ([raw file](https://github.com/starkware-libs/stwo/blob/e1c33e0734d0c2e399b0eff36f9d3c7d57aba07a/crates/prover/src/examples/blake/air.rs#L73)):*
> ```XML
> 
> #[allow(unused)]
> pub fn prove_blake(log_size: u32) -> (BlakeAir, StarkProof<Blake2sMerkleHasher>) {
> ```

You can use general hash function instead



_Code quote:_
```XML
<Blake2sMerkleHasher
```
___
*[`crates/prover/src/examples/blake/air.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/stwo/773#-O3bwNGI7FnX_LdneAqi:-O3bwNGJCVSVsVC3_7vW:b-7cho2c) ([raw file](https://github.com/starkware-libs/stwo/blob/e1c33e0734d0c2e399b0eff36f9d3c7d57aba07a/crates/prover/src/examples/blake/air.rs#L78)):*
> ```XML
>     // Precompute twiddles.
>     let span = span!(Level::INFO, "Precompute twiddles").entered();
>     let log_max_rows = (log_size + 3).max(20);
> ```

+3 is for rounds and 20 is for xor?
I thought xor<12,4> induces columns of size 16..

Anyway make constants with name or explain with comment



_Code quote:_
```XML
let log_max_rows = (log_size + 3).max(20);
```
___
*[`crates/prover/src/examples/blake/air.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/stwo/773#-O3buvM3EQqngC2_4_Y_:-O3buvM3EQqngC2_4_Ya:b3kre) ([raw file](https://github.com/starkware-libs/stwo/blob/e1c33e0734d0c2e399b0eff36f9d3c7d57aba07a/crates/prover/src/examples/blake/air.rs#L80)):*
> ```XML
>     let log_max_rows = (log_size + 3).max(20);
>     let twiddles = SimdBackend::precompute_twiddles(
>         CanonicCoset::new(log_max_rows + 1 + LOG_BLOWUP_FACTOR)
> ```

?



_Suggestion:_
```XML
max(log_max_rows + 1, log_max_rows + LOG_BLOWUP_FACTOR)
```
___
*[`crates/prover/src/examples/blake/air.rs` line 105 at r1](https://reviewable.io/reviews/starkware-libs/stwo/773#-O3bwr1t1DxI5-Nrtpr5:-O3bwr1t1DxI5-Nrtpr6:b-4jubql) ([raw file](https://github.com/starkware-libs/stwo/blob/e1c33e0734d0c2e399b0eff36f9d3c7d57aba07a/crates/prover/src/examples/blake/air.rs#L105)):*
> ```XML
> 
>     // Split round inputs to components, of size 8 and 2.
>     const ROUND_LOG_SPLIT: [u32; 2] = [3, 1];
> ```

This is very specific for Blake2s.
I think you should call it blake2s with current impl



_Code quote:_
```XML
const ROUND_LOG_SPLIT: [u32; 2] = [3, 1];
```
___
*[`crates/prover/src/examples/blake/air.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/stwo/773#-O3bxeoI-hakIqzdL-_Z:-O3bxeoI-hakIqzdL-__:bt87j6x) ([raw file](https://github.com/starkware-libs/stwo/blob/e1c33e0734d0c2e399b0eff36f9d3c7d57aba07a/crates/prover/src/examples/blake/air.rs#L119)):*
> ```XML
>             rest = r;
>             round::generate_trace(log_size + l, cur_inputs, &mut xor_accums)
>         }));
> ```

Suggestion



_Suggestion:_
```XML
    // Rounds.
    let mut rest = &round_inputs[..];
    let mut xor_accums = XorAccums::default();
    let (round_traces, round_lookup_datas): (Vec<_>, Vec<_>) =
        multiunzip(ROUND_LOG_SPLIT.map(|l| {
            let (cur_inputs, r) = rest.split_at(1 << (log_size - LOG_N_LANES + l));
            rest = r;
            round::generate_trace(log_size + l, cur_inputs, &mut xor_accums)
        }));
```
___
*[`crates/prover/src/examples/blake/air.rs` line 147 at r1](https://reviewable.io/reviews/starkware-libs/stwo/773#-O3bxvXN3SFAAYmQDCV_:-O3bxvXN3SFAAYmQDCVa:b-iwdrse) ([raw file](https://github.com/starkware-libs/stwo/blob/e1c33e0734d0c2e399b0eff36f9d3c7d57aba07a/crates/prover/src/examples/blake/air.rs#L147)):*
> ```XML
>     // Draw lookup element.
>     let blake_lookup_elements = RoundElements::draw(channel);
>     let round_lookup_elements = RoundElements::draw(channel);
> ```

Note: this looks like a bug (I know it ain't)



_Code quote:_
```XML
    let blake_lookup_elements = RoundElements::draw(channel);
    let round_lookup_elements = RoundElements::draw(channel);
```
___
*[`crates/prover/src/examples/blake/air.rs` line 171 at r1](https://reviewable.io/reviews/starkware-libs/stwo/773#-O3by7L85APAe701hUtE:-O3by7L85APAe701hUtF:b-bfbe29) ([raw file](https://github.com/starkware-libs/stwo/blob/e1c33e0734d0c2e399b0eff36f9d3c7d57aba07a/crates/prover/src/examples/blake/air.rs#L171)):*
> ```XML
>                 )
>             }),
>     );
> ```

Can this multiunzip code abstracted away from this function?
Not for this pr



_Code quote:_
```XML
    let (round_traces, round_claimed_sums): (Vec<_>, Vec<_>) = multiunzip(
        ROUND_LOG_SPLIT
            .iter()
            .zip(round_lookup_datas)
            .map(|(l, lookup_data)| {
                round::generate_interaction_trace(
                    log_size + l,
                    lookup_data,
                    &xor_lookup_elements,
                    &round_lookup_elements,
                )
            }),
    );
```
___
*[`crates/prover/src/examples/blake/air.rs` line 223 at r1](https://reviewable.io/reviews/starkware-libs/stwo/773#-O3byVw383Btf1xglsD4:-O3byVw383Btf1xglsD5:b3kre) ([raw file](https://github.com/starkware-libs/stwo/blob/e1c33e0734d0c2e399b0eff36f9d3c7d57aba07a/crates/prover/src/examples/blake/air.rs#L223)):*
> ```XML
>         blake_lookup_elements,
>         round_lookup_elements: round_lookup_elements.clone(),
>         claimed_sum: scheduler_claimed_sum, // TODO: This is not correct.
> ```

?



_Code quote:_
```XML
// TODO: This is not correct.
```
___
*[`crates/prover/src/examples/blake/air.rs` line 321 at r1](https://reviewable.io/reviews/starkware-libs/stwo/773#-O3bzBZ59kHQjDg4ppX-:-O3bzBZ59kHQjDg4ppX0:b-slq4t) ([raw file](https://github.com/starkware-libs/stwo/blob/e1c33e0734d0c2e399b0eff36f9d3c7d57aba07a/crates/prover/src/examples/blake/air.rs#L321)):*
> ```XML
>         let _blake_lookup_elements = RoundElements::draw(channel);
>         let _round_lookup_elements = RoundElements::draw(channel);
>         let _xor_lookup_elements = XorElements::draw(channel);
> ```

I think we should add the assert here as well



_Code quote:_
```XML
        let _blake_lookup_elements = RoundElements::draw(channel);
        let _round_lookup_elements = RoundElements::draw(channel);
        let _xor_lookup_elements = XorElements::draw(channel);
```
___
*[`crates/prover/src/examples/blake/air.rs` line 322 at r1](https://reviewable.io/reviews/starkware-libs/stwo/773#-O3bzJlFBXoh6EKHB-L1:-O3bzJlFBXoh6EKHB-L2:b1cnkgt) ([raw file](https://github.com/starkware-libs/stwo/blob/e1c33e0734d0c2e399b0eff36f9d3c7d57aba07a/crates/prover/src/examples/blake/air.rs#L322)):*
> ```XML
>         let _round_lookup_elements = RoundElements::draw(channel);
>         let _xor_lookup_elements = XorElements::draw(channel);
>         // TODO(spapini): Check claimed sum against first and last instances.
> ```

Can we add this check?



_Code quote:_
```XML
// TODO(spapini): Check claimed sum against first and last instances.
```
___
*[`crates/prover/src/examples/blake/air.rs` line 331 at r1](https://reviewable.io/reviews/starkware-libs/stwo/773#-O3byx9i0mrEUnIbAIdd:-O3byx9i0mrEUnIbAIde:b-5skvpt) ([raw file](https://github.com/starkware-libs/stwo/blob/e1c33e0734d0c2e399b0eff36f9d3c7d57aba07a/crates/prover/src/examples/blake/air.rs#L331)):*
> ```XML
>             &air,
>             channel,
>             &InteractionElements::default(),
> ```

Maybe let's add a comment here that this variable is not in use



_Code quote:_
```XML
&InteractionElements::default(),
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/773)* status: 1 of 10 files reviewed, 9 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/prover/src/examples/blake/air.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/stwo/773#-O3bueIMD1h1WbDiZJ0Z:-O3c8v_E-e-4KZhNwHRz:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/e1c33e0734d0c2e399b0eff36f9d3c7d57aba07a/crates/prover/src/examples/blake/air.rs#L73)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

You can use general hash function instead
</blockquote></details>

Done.
___
*[`crates/prover/src/examples/blake/air.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/stwo/773#-O3bwNGI7FnX_LdneAqi:-O3c9-3A7lveusPhVXG9:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/e1c33e0734d0c2e399b0eff36f9d3c7d57aba07a/crates/prover/src/examples/blake/air.rs#L78)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

+3 is for rounds and 20 is for xor?
I thought xor<12,4> induces columns of size 16..

Anyway make constants with name or explain with comment
</blockquote></details>

Done.
___
*[`crates/prover/src/examples/blake/air.rs` line 80 at r1](https://reviewable.io/reviews/starkware-libs/stwo/773#-O3buvM3EQqngC2_4_Y_:-O3c9XCoD-c7rmnxM2RU:b-c9ti3v) ([raw file](https://github.com/starkware-libs/stwo/blob/e1c33e0734d0c2e399b0eff36f9d3c7d57aba07a/crates/prover/src/examples/blake/air.rs#L80)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

?
</blockquote></details>

+1 for extension and +1 for commitment on composition.
___
*[`crates/prover/src/examples/blake/air.rs` line 105 at r1](https://reviewable.io/reviews/starkware-libs/stwo/773#-O3bwr1t1DxI5-Nrtpr5:-O3c9kK7AuBgso4D-eFA:b-o89shu) ([raw file](https://github.com/starkware-libs/stwo/blob/e1c33e0734d0c2e399b0eff36f9d3c7d57aba07a/crates/prover/src/examples/blake/air.rs#L105)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

This is very specific for Blake2s.
I think you should call it blake2s with current impl
</blockquote></details>

Moved near N_ROUNDS and documented. WDYT?
___
*[`crates/prover/src/examples/blake/air.rs` line 171 at r1](https://reviewable.io/reviews/starkware-libs/stwo/773#-O3by7L85APAe701hUtE:-O3cB1nDAfmmqggt-DDD:b-ika7uk) ([raw file](https://github.com/starkware-libs/stwo/blob/e1c33e0734d0c2e399b0eff36f9d3c7d57aba07a/crates/prover/src/examples/blake/air.rs#L171)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can this multiunzip code abstracted away from this function?
Not for this pr
</blockquote></details>

Yes, with the "statement" design. I think Ill do it for the verifier as well, after this PR.
___
*[`crates/prover/src/examples/blake/air.rs` line 223 at r1](https://reviewable.io/reviews/starkware-libs/stwo/773#-O3byVw383Btf1xglsD4:-O3cB8eRAkv-HlUhIwYH:bvn942g) ([raw file](https://github.com/starkware-libs/stwo/blob/e1c33e0734d0c2e399b0eff36f9d3c7d57aba07a/crates/prover/src/examples/blake/air.rs#L223)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

?
</blockquote></details>

I think I meant that nothing "cancels" the logup sum for the inputs. That is, the verifier should remember to subtract it from the final sum. At least for this test.
___
*[`crates/prover/src/examples/blake/air.rs` line 321 at r1](https://reviewable.io/reviews/starkware-libs/stwo/773#-O3bzBZ59kHQjDg4ppX-:-O3cEQlRDBqPis_B0UGP:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/e1c33e0734d0c2e399b0eff36f9d3c7d57aba07a/crates/prover/src/examples/blake/air.rs#L321)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I think we should add the assert here as well
</blockquote></details>

Done.
___
*[`crates/prover/src/examples/blake/air.rs` line 322 at r1](https://reviewable.io/reviews/starkware-libs/stwo/773#-O3bzJlFBXoh6EKHB-L1:-O3cERfP5k37SSZa0Efw:bckzr0y) ([raw file](https://github.com/starkware-libs/stwo/blob/e1c33e0734d0c2e399b0eff36f9d3c7d57aba07a/crates/prover/src/examples/blake/air.rs#L322)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can we add this check?
</blockquote></details>

We will, next PR.
___
*[`crates/prover/src/examples/blake/air.rs` line 331 at r1](https://reviewable.io/reviews/starkware-libs/stwo/773#-O3byx9i0mrEUnIbAIdd:-O3cEc3MBlHRPi0dKP7_:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/e1c33e0734d0c2e399b0eff36f9d3c7d57aba07a/crates/prover/src/examples/blake/air.rs#L331)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Maybe let's add a comment here that this variable is not in use
</blockquote></details>

Done.

**Review by Alon-Ti — APPROVED** [review]
> Reviewed 5 of 9 files at r2, 2 of 2 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/773)* status: all files reviewed, 10 unresolved discussions (waiting on @alonh5, @shaharsamocha7, and @spapinistarkware)

___
*[`crates/prover/src/examples/blake/air.rs` line 103 at r4](https://reviewable.io/reviews/starkware-libs/stwo/773#-O4-NruO0Upx59UyCV-4:-O4-NruO0Upx59UyCV-5:b-nxsfar) ([raw file](https://github.com/starkware-libs/stwo/blob/8bd4bff1e3d352f834e428d7b489bd8c46dc6625/crates/prover/src/examples/blake/air.rs#L103)):*
> ```XML
>             BlakeInput { v, m }
>         })
>         .collect::<Vec<_>>();
> ```

Is `collect_vec()` the same as this?

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/773)* status: all files reviewed, 9 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

___
*[`crates/prover/src/examples/blake/air.rs` line 103 at r4](https://reviewable.io/reviews/starkware-libs/stwo/773#-O4-NruO0Upx59UyCV-4:-O4-W0hoDBP29ZeO7E54:bb77ufg) ([raw file](https://github.com/starkware-libs/stwo/blob/8bd4bff1e3d352f834e428d7b489bd8c46dc6625/crates/prover/src/examples/blake/air.rs#L103)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

Is `collect_vec()` the same as this?
</blockquote></details>

Yes.

**Review by Alon-Ti — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/773#-:-O453SsfBz1cj1DW6ngj:bnfp4nl)* status: all files reviewed, 9 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

**Comment by spapinistarkware** [comment]
### Merge activity

* **Aug 12, 6:21 AM EDT**: @spapinistarkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/773).

**Pull request merged**
