### PR TITLE
Run tests with "parallel" feature in CI

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/853)

### CODE REVIEW

**Review by ohad-starkware — COMMENTED** [review]
do we want to test with both parallel & avx turned on at the same time?
The bench does cover it... 

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/853#-:-O7bttUf2CPcap35M-qh:b-ykpntl)* status: all files reviewed, 1 unresolved discussion (waiting on @Alon-Ti, @alonh5, and @shaharsamocha7)

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/853)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Alon-Ti, @andrewmilson, @ohad-starkware, and @shaharsamocha7)

___
*[`.github/workflows/ci.yaml` line 193 at r2](https://reviewable.io/reviews/starkware-libs/stwo/853#-O7_YF_-5ErgE4Wqq0DE:-O7c8KMc0_dQ0o6a7xKf:bjkeh97) ([raw file](https://github.com/starkware-libs/stwo/blob/34c3edd90a5407569591c2ded4b0784321454ecd/.github/workflows/ci.yaml#L193)):*
> ```YAML
>           toolchain: nightly-2024-01-04
>       - uses: Swatinem/rust-cache@v2
>       - run: cargo +nightly-2024-01-04 test --release --features="parallel"
> ```

Done. Why is that better?

**Review by ohad-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/853)* status: all files reviewed, 1 unresolved discussion (waiting on @Alon-Ti, @andrewmilson, and @shaharsamocha7)

___
*[`-- commits` line 8 at r3](https://reviewable.io/reviews/starkware-libs/stwo/853#-O7wU-V59pDoVRVBbC47):*
squash?
___
*[`.github/workflows/ci.yaml` line 193 at r2](https://reviewable.io/reviews/starkware-libs/stwo/853#-O7_YF_-5ErgE4Wqq0DE:-O7wSWeS6UXG5T3oPfq3:b-9wb4r8) ([raw file](https://github.com/starkware-libs/stwo/blob/34c3edd90a5407569591c2ded4b0784321454ecd/.github/workflows/ci.yaml#L193)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Done. Why is that better?
</blockquote></details>

--release disables debug assertions and some bounds checking
it does enable optimizations so you want it where performance matter

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/853)* status: all files reviewed, 1 unresolved discussion (waiting on @Alon-Ti, @andrewmilson, and @shaharsamocha7)

___
*[`-- commits` line 8 at r3](https://reviewable.io/reviews/starkware-libs/stwo/853#-O7wU-V59pDoVRVBbC47):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

squash?
</blockquote></details>

Will squash when merging.
___
*[`.github/workflows/ci.yaml` line 193 at r2](https://reviewable.io/reviews/starkware-libs/stwo/853#-O7_YF_-5ErgE4Wqq0DE:-O8pslpG9tU23pJ_R57-:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/34c3edd90a5407569591c2ded4b0784321454ecd/.github/workflows/ci.yaml#L193)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

--release disables debug assertions and some bounds checking
it does enable optimizations so you want it where performance matter
</blockquote></details>

Done.

**Review by andrewmilson — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/853#-:-O8qZlEE0GYYu4sJ7sN1:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Alon-Ti and @shaharsamocha7)

**Pull request merged**
