### PR TITLE
Fall back to CPU in small constraint eval.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/838)

### CODE REVIEW

**Review by andrewmilson — CHANGES_REQUESTED** [review]
> Reviewed 1 of 10 files at r1, 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/838)* status: 2 of 10 files reviewed, 4 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

___
*[`crates/prover/src/core/backend/simd/circle.rs` line 338 at r2](https://reviewable.io/reviews/starkware-libs/stwo/838#-O7NxVgx-Gif4h4-h2IM:-O7NxVgy7z5R00HXpxB_:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/125f43e8b1247ba896f1cb5987d51556424d71d7/crates/prover/src/core/backend/simd/circle.rs#L338)):*
> ```XML
>     }
>     fold(
>         &cast_slice::<_, BaseField>(&poly.coeffs.data)[..poly.coeffs.length],
> ```





_Suggestion:_
```XML
poly.coeffs.data.as_slice()
```
___
*[`crates/prover/src/core/backend/simd/column.rs` line 67 at r2](https://reviewable.io/reviews/starkware-libs/stwo/838#-O7NxiZr6wwvRo5n90ij:-O7NxiZr6wwvRo5n90ik:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/125f43e8b1247ba896f1cb5987d51556424d71d7/crates/prover/src/core/backend/simd/column.rs#L67)):*
> ```XML
>             .map(PackedBaseField::from_slice)
>             .collect();
>         Self { data, length }
> ```





_Suggestion:_
```XML
        values.into_iter().collect()
```
___
*[`crates/prover/src/core/backend/simd/m31.rs` line 49 at r2](https://reviewable.io/reviews/starkware-libs/stwo/838#-O7Nxo5M6TRVhfELV7ze:-O7Nxo5M6TRVhfELV7zf:b45h) ([raw file](https://github.com/starkware-libs/stwo/blob/125f43e8b1247ba896f1cb5987d51556424d71d7/crates/prover/src/core/backend/simd/m31.rs#L49)):*
> ```XML
>         res[..values.len()].copy_from_slice(values);
>         Self::from_array(res)
>     }
> ```


___
*[`crates/prover/src/core/fields/secure_column.rs` line 29 at r2](https://reviewable.io/reviews/starkware-libs/stwo/838#-O7Ny1u0AwQFI6-Qnad-:-O7Ny1u0AwQFI6-Qnad0:b-vdh4ka) ([raw file](https://github.com/starkware-libs/stwo/blob/125f43e8b1247ba896f1cb5987d51556424d71d7/crates/prover/src/core/fields/secure_column.rs#L29)):*
> ```XML
>         SecureColumnByCoords {
>             columns: self.columns.map(BaseColumn::from_cpu_vec),
>         }
> ```

Now `SecureColumnByCoords<CpuBackend>` has a dependence on SimdBackend.
WDYT of having a from_cpu on `SecureColumnByCoords<SimdBackend>` to be consistent with `BaseColumn::from_cpu_vec`



_Code quote:_
```XML
    pub fn to_simd(self) -> SecureColumnByCoords<SimdBackend> {
        SecureColumnByCoords {
            columns: self.columns.map(BaseColumn::from_cpu_vec),
        }
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/838)* status: 2 of 10 files reviewed, 4 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`crates/prover/src/core/backend/simd/circle.rs` line 338 at r2](https://reviewable.io/reviews/starkware-libs/stwo/838#-O7NxVgx-Gif4h4-h2IM:-O7O9pTADtIjPfYxUHmM:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/125f43e8b1247ba896f1cb5987d51556424d71d7/crates/prover/src/core/backend/simd/circle.rs#L338)):*
> ```XML
>     }
>     fold(
>         &cast_slice::<_, BaseField>(&poly.coeffs.data)[..poly.coeffs.length],
> ```

Done.
___
*[`crates/prover/src/core/backend/simd/column.rs` line 67 at r2](https://reviewable.io/reviews/starkware-libs/stwo/838#-O7NxiZr6wwvRo5n90ij:-O7OAm022lHh4wwMt4Xs:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/125f43e8b1247ba896f1cb5987d51556424d71d7/crates/prover/src/core/backend/simd/column.rs#L67)):*
> ```XML
>             .map(PackedBaseField::from_slice)
>             .collect();
>         Self { data, length }
> ```

Done.
___
*[`crates/prover/src/core/backend/simd/m31.rs` line 49 at r2](https://reviewable.io/reviews/starkware-libs/stwo/838#-O7Nxo5M6TRVhfELV7ze:-O7OB2F01poqFf-sQXjq:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/125f43e8b1247ba896f1cb5987d51556424d71d7/crates/prover/src/core/backend/simd/m31.rs#L49)):*
> ```XML
>         res[..values.len()].copy_from_slice(values);
>         Self::from_array(res)
>     }
> ```

Done.
___
*[`crates/prover/src/core/fields/secure_column.rs` line 29 at r2](https://reviewable.io/reviews/starkware-libs/stwo/838#-O7Ny1u0AwQFI6-Qnad-:-O7OCJS33QCY8ejVIBub:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/125f43e8b1247ba896f1cb5987d51556424d71d7/crates/prover/src/core/fields/secure_column.rs#L29)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Now `SecureColumnByCoords<CpuBackend>` has a dependence on SimdBackend.
WDYT of having a from_cpu on `SecureColumnByCoords<SimdBackend>` to be consistent with `BaseColumn::from_cpu_vec`
</blockquote></details>

Done.

**Review by andrewmilson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/838)* status: 2 of 10 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/cpu_domain.rs` line 16 at r3](https://reviewable.io/reviews/starkware-libs/stwo/838#-O7QjAAk-8pgF_quwkkw:-O7QjAAlE23EQQFZXEza:bs5wnko) ([raw file](https://github.com/starkware-libs/stwo/blob/ec3018623fde7f4de3254a56941e33290705c5e7/crates/prover/src/constraint_framework/cpu_domain.rs#L16)):*
> ```XML
> 
> /// Evaluates constraints at an evaluation domain points.
> pub struct CpuDomainEvaluator<'a> {
> ```

I'd have thought SimdDomainEvaluator already works for small sizes no?

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/838)* status: 2 of 10 files reviewed, 1 unresolved discussion (waiting on @andrewmilson and @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/cpu_domain.rs` line 16 at r3](https://reviewable.io/reviews/starkware-libs/stwo/838#-O7QjAAk-8pgF_quwkkw:-O7TSP1a2FYPxAvk_rp2:b1sppv1) ([raw file](https://github.com/starkware-libs/stwo/blob/ec3018623fde7f4de3254a56941e33290705c5e7/crates/prover/src/constraint_framework/cpu_domain.rs#L16)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

I'd have thought SimdDomainEvaluator already works for small sizes no?
</blockquote></details>

How would it work with sizes smaller than 16? It works with packed elements

**Review by andrewmilson — APPROVED** [review]
:lgtm: with comment

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/838#-:-O7WpOnu40nZ1sLmun0k:b10c0l0)* status: 2 of 10 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/component.rs` line 180 at r3](https://reviewable.io/reviews/starkware-libs/stwo/838#-O7WgT8oCAWlxW1DPOlo:-O7WgT8oCAWlxW1DPOlp:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/ec3018623fde7f4de3254a56941e33290705c5e7/crates/prover/src/constraint_framework/component.rs#L180)):*
> ```XML
>         let _span = span!(Level::INFO, "Constraint point-wise eval").entered();
> 
>         if trace_domain.log_size() <= LOG_N_LANES {
> ```





_Suggestion:_
```XML
if trace_domain.log_size() <= LOG_N_LANES + LOG_N_VERY_PACKED_ELEMS {
```
___
*[`crates/prover/src/constraint_framework/cpu_domain.rs` line 16 at r3](https://reviewable.io/reviews/starkware-libs/stwo/838#-O7QjAAk-8pgF_quwkkw:-O7WfFHpEHsv-lhgRrrH:bfxz9oa) ([raw file](https://github.com/starkware-libs/stwo/blob/ec3018623fde7f4de3254a56941e33290705c5e7/crates/prover/src/constraint_framework/cpu_domain.rs#L16)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

How would it work with sizes smaller than 16? It works with packed elements
</blockquote></details>

I think it would work. The mechanism to get offsets already support sizes smaller than 16. Maybe I'm thinking about it wrong. Is there a example it fails for size smaller than 16?

Just looked at the `SimdDomainEvaluator` code, I think a problem with it is the use of `VeryPackedColumn::transform_under_ref` which has undefined behaviour when called on `BaseColumn`'s with capacity less than `VeryPackedM31`.  If `BaseColumn` always allocates space for at least one `VeryPackedM31` I don't see why we couldn't use `SimdDomainEvaluator`. This change feels a bit fragile though and worse than the duplicated code. Allg, `CpuDomainEvaluator` LGTM.

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/838)* status: 2 of 10 files reviewed, 2 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/component.rs` line 180 at r3](https://reviewable.io/reviews/starkware-libs/stwo/838#-O7WgT8oCAWlxW1DPOlo:-O7Y6Zg6AJWCJKRrwUxw:bc39xgq) ([raw file](https://github.com/starkware-libs/stwo/blob/ec3018623fde7f4de3254a56941e33290705c5e7/crates/prover/src/constraint_framework/component.rs#L180)):*
> ```XML
>         let _span = span!(Level::INFO, "Constraint point-wise eval").entered();
> 
>         if trace_domain.log_size() <= LOG_N_LANES {
> ```

Actually the bound comes from line 226. Fixed it, thanks.
___
*[`crates/prover/src/constraint_framework/cpu_domain.rs` line 16 at r3](https://reviewable.io/reviews/starkware-libs/stwo/838#-O7QjAAk-8pgF_quwkkw:-O7Y8W3m8Xa4Dl--HHeJ:b-89q77k) ([raw file](https://github.com/starkware-libs/stwo/blob/ec3018623fde7f4de3254a56941e33290705c5e7/crates/prover/src/constraint_framework/cpu_domain.rs#L16)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

I think it would work. The mechanism to get offsets already support sizes smaller than 16. Maybe I'm thinking about it wrong. Is there a example it fails for size smaller than 16?

Just looked at the `SimdDomainEvaluator` code, I think a problem with it is the use of `VeryPackedColumn::transform_under_ref` which has undefined behaviour when called on `BaseColumn`'s with capacity less than `VeryPackedM31`.  If `BaseColumn` always allocates space for at least one `VeryPackedM31` I don't see why we couldn't use `SimdDomainEvaluator`. This change feels a bit fragile though and worse than the duplicated code. Allg, `CpuDomainEvaluator` LGTM.
</blockquote></details>

Cool.

**Review by andrewmilson — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/838#-:-O7YAddM8WfchQ_bHV1G:bnfp4nl)* status: 2 of 10 files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

**Pull request merged**
