### PR TITLE
relation tracker

### PR DESCRIPTION
**Pull request by ohad-starkware**
macro export (#900)

Commit to FRI first layer (#897)

Exported shared code to temp variables in ExprEvaluator. (#893)

relation tracker

### CODE REVIEW

**Comment by ohad-starkware** [comment]
* **#909** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/909?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/909?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `dev`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by Alon-Ti — APPROVED** [review]
:lgtm:

> Reviewed 2 of 5 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/909#-:-OD5XrWd-IXrj8BUEBjf:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`crates/prover/src/core/pcs/utils.rs` line 44 at r3](https://reviewable.io/reviews/starkware-libs/stwo/909#-OD5XkVsCJhU66F8CXMg:-OD5XkVsCJhU66F8CXMh:b-nvgao4) ([raw file](https://github.com/starkware-libs/stwo/blob/b4fefbfd824a1a418b65fecddac4b7acca288d06/crates/prover/src/core/pcs/utils.rs#L44)):*
> ```XML
> }
> 
> /// Converts `&TreeVec<&Vec<T>>` to `TreeVec<Vec<&T>>`.
> ```

Thank you! I needed this like 3 times and was always too lazy.

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/909)* status: all files reviewed, 1 unresolved discussion (waiting on @Alon-Ti and @shaharsamocha7)

___
*[`crates/prover/src/core/pcs/utils.rs` line 44 at r3](https://reviewable.io/reviews/starkware-libs/stwo/909#-OD5XkVsCJhU66F8CXMg:-OD5kBHQ75OHppGIo7nv:bcmem6u) ([raw file](https://github.com/starkware-libs/stwo/blob/b4fefbfd824a1a418b65fecddac4b7acca288d06/crates/prover/src/core/pcs/utils.rs#L44)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

Thank you! I needed this like 3 times and was always too lazy.
</blockquote></details>

no problem bud

**Comment by ohad-starkware** [comment]
### Merge activity

* **Dec 2, 4:45 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/909).

**Pull request merged**
