### PR TITLE
Formal Expr logup variables.

### PR DESCRIPTION
**Pull request by Alon-Ti**

### CODE REVIEW

**Comment by Alon-Ti** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/887?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#889** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/889?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#888** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/888?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#887** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/887?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#879** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/879?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#883](https://github.com/starkware-libs/stwo/pull/883) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/883?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#876** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/876?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#875** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/875?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Alon-Ti and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/887)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @Alon-Ti)

___
*[`crates/prover/src/constraint_framework/expr.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/stwo/887#-OBfVw7S9uzFPM05qIjZ:-OBfVw7T1f_wMGQMSLrr:b-36cehr) ([raw file](https://github.com/starkware-libs/stwo/blob/059b0f48bd299eddaf7840b62b985b665234347f/crates/prover/src/constraint_framework/expr.rs#L30)):*
> ```XML
>     SecureCol([Box<Expr>; 4]),
>     Const(BaseField),
>     Var(String),
> ```

consider to rename



_Suggestion:_
```XML
ExternalVar(String),
```
___
*[`crates/prover/src/constraint_framework/expr.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/stwo/887#-OBfWEbR31SXDuYOdsPw:-OBfWEbR31SXDuYOdsPx:b-1aivwr) ([raw file](https://github.com/starkware-libs/stwo/blob/059b0f48bd299eddaf7840b62b985b665234347f/crates/prover/src/constraint_framework/expr.rs#L30)):*
> ```XML
>     SecureCol([Box<Expr>; 4]),
>     Const(BaseField),
>     Var(String),
> ```

Should it also help with preprocessed columns?
Document



_Code quote:_
```XML
Var(String),
```
___
*[`crates/prover/src/constraint_framework/expr.rs` line 155 at r1](https://reviewable.io/reviews/starkware-libs/stwo/887#-OBfWQ503xC1fg1dlvRF:-OBfWQ503xC1fg1dlvRG:b84ald6) ([raw file](https://github.com/starkware-libs/stwo/blob/059b0f48bd299eddaf7840b62b985b665234347f/crates/prover/src/constraint_framework/expr.rs#L155)):*
> ```XML
>     let z = Expr::Var(relation.get_name().to_owned() + "_z");
>     let alpha_powers = (0..relation.get_size())
>         .map(|i| Expr::Var(relation.get_name().to_owned() + "_alpha" + &i.to_string()));
> ```

Can you put those strings as consts in the top of the function?



_Suggestion:_
```XML
"_alpha", "z"
```
___
*[`crates/prover/src/constraint_framework/expr.rs` line 232 at r1](https://reviewable.io/reviews/starkware-libs/stwo/887#-OBfXkjJDbBJqySDrhW9:-OBfXkjJDbBJqySDrhWA:b3fz2kp) ([raw file](https://github.com/starkware-libs/stwo/blob/059b0f48bd299eddaf7840b62b985b665234347f/crates/prover/src/constraint_framework/expr.rs#L232)):*
> ```XML
>                      values,
>                  }| {
>                     Fraction::new(multiplicity.clone(), combine_formal(*relation, values))
> ```

Can't it use the default impl for add_to_relation?
this is because the combine_formal?



_Code quote:_
```XML
Fraction::new(multiplicity.clone(), combine_formal(*relation, values))
```
___
*[`crates/prover/src/constraint_framework/expr.rs` line 333 at r1](https://reviewable.io/reviews/starkware-libs/stwo/887#-OBfY0_46TNcDD_TbxSt:-OBfY0_59jbYNqUquS8j:b-6zjfw7) ([raw file](https://github.com/starkware-libs/stwo/blob/059b0f48bd299eddaf7840b62b985b665234347f/crates/prover/src/constraint_framework/expr.rs#L333)):*
> ```XML
>                                             interaction: 2,
>                                             idx: 5,
>                                             offset: 18446744073709551615
> ```

Why we got this nubmer? (1 << 64)



_Code quote:_
```XML
offset: 18446744073709551615
```

**Review by Alon-Ti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/887)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/expr.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/stwo/887#-OBfVw7S9uzFPM05qIjZ:-OBtpV8U792fXR2TixuH:b-nmyhjj) ([raw file](https://github.com/starkware-libs/stwo/blob/4f5955bd0507572eae1845caaf9a602133aeba74/crates/prover/src/constraint_framework/expr.rs#L30)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

consider to rename
</blockquote></details>

`Param`?
___
*[`crates/prover/src/constraint_framework/expr.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/stwo/887#-OBfWEbR31SXDuYOdsPw:-OBtq-c-6HZK4hCLQ1QM:b-3hwb5m) ([raw file](https://github.com/starkware-libs/stwo/blob/4f5955bd0507572eae1845caaf9a602133aeba74/crates/prover/src/constraint_framework/expr.rs#L30)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Should it also help with preprocessed columns?
Document
</blockquote></details>

Preprocessed columns are just columns that exist in the trace, I think the expr evaluator doesn't care how they're generated and who has access to them, at least until we have named columns in general.
___
*[`crates/prover/src/constraint_framework/expr.rs` line 155 at r1](https://reviewable.io/reviews/starkware-libs/stwo/887#-OBfWQ503xC1fg1dlvRF:-OBtrN1B23UV0hLUrvPT:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/4f5955bd0507572eae1845caaf9a602133aeba74/crates/prover/src/constraint_framework/expr.rs#L155)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can you put those strings as consts in the top of the function?
</blockquote></details>

Done.
___
*[`crates/prover/src/constraint_framework/expr.rs` line 232 at r1](https://reviewable.io/reviews/starkware-libs/stwo/887#-OBfXkjJDbBJqySDrhW9:-OBtrRHFANYBL2L3vzhH:bqbmbvy) ([raw file](https://github.com/starkware-libs/stwo/blob/4f5955bd0507572eae1845caaf9a602133aeba74/crates/prover/src/constraint_framework/expr.rs#L232)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can't it use the default impl for add_to_relation?
this is because the combine_formal?
</blockquote></details>

Yes. `combine` is a property of the relation itself, so it can't vary by evaluator.
___
*[`crates/prover/src/constraint_framework/expr.rs` line 333 at r1](https://reviewable.io/reviews/starkware-libs/stwo/887#-OBfY0_46TNcDD_TbxSt:-OBtxohj-pSwkMBRTSaX:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/4f5955bd0507572eae1845caaf9a602133aeba74/crates/prover/src/constraint_framework/expr.rs#L333)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why we got this nubmer? (1 << 64)
</blockquote></details>

Done.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/887#-:-OBuADy33WA8YOoyGraf:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Alon-Ti)

___
*[`crates/prover/src/constraint_framework/expr.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/stwo/887#-OBfWEbR31SXDuYOdsPw:-OBu8vO6DmOJWwO0VbQ1:ba3g1w9) ([raw file](https://github.com/starkware-libs/stwo/blob/4f5955bd0507572eae1845caaf9a602133aeba74/crates/prover/src/constraint_framework/expr.rs#L30)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

Preprocessed columns are just columns that exist in the trace, I think the expr evaluator doesn't care how they're generated and who has access to them, at least until we have named columns in general.
</blockquote></details>

so it should access them by index same as any other column?
___
*[`crates/prover/src/constraint_framework/expr.rs` line 30 at r2](https://reviewable.io/reviews/starkware-libs/stwo/887#-OBu9l4M2ZFzhICFu9k1:-OBu9l4M2ZFzhICFu9k2:b-emzlar) ([raw file](https://github.com/starkware-libs/stwo/blob/2601e113913667132a75587fe5796b7b07e7ee97/crates/prover/src/constraint_framework/expr.rs#L30)):*
> ```XML
>     SecureCol([Box<Expr>; 4]),
>     Const(BaseField),
>     /// A parameter external to the AIR, for example the interaction elements of a relation.
> ```

why is it called external?



_Suggestion:_
```XML
/// External parameter to the AIR, for example the interaction elements of a relation.
```

**Review by shaharsamocha7 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/887)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @Alon-Ti)

**Review by shaharsamocha7 — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/887)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Alon-Ti)

**Comment by Alon-Ti** [comment]
### Merge activity

* **Nov 18, 11:45 AM EST**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/887).

**Pull request merged**
