### PR TITLE
Decoupled batching from `add_to_relation`.

### PR DESCRIPTION
**Pull request by Alon-Ti**

### CODE REVIEW

**Comment by Alon-Ti** [comment]
* **#922** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/922?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/922?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `dev`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 10 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/922)* status: 3 of 11 files reviewed, 2 unresolved discussions (waiting on @Alon-Ti and @ohad-starkware)

___
*[`crates/prover/src/constraint_framework/mod.rs` line 148 at r5](https://reviewable.io/reviews/starkware-libs/stwo/922#-ODM8LXOEYg3w1Mond5o:-ODM8LXP2WtqLSh807lC:bex2qde) ([raw file](https://github.com/starkware-libs/stwo/blob/5817df646a7856ec2a880154961788119eeb648a/crates/prover/src/constraint_framework/mod.rs#L148)):*
> ```XML
>         unimplemented!()
>     }
>     fn finalize_logup_batched(&mut self, _batching: &[usize]) {
> ```

document? Here is a good place for that?
Also document the format of batching



_Code quote:_
```XML
fn finalize_logup_batched(&mut self, _batching: &[usize]) {
```
___
*[`crates/prover/src/constraint_framework/mod.rs` line 234 at r5](https://reviewable.io/reviews/starkware-libs/stwo/922#-ODMAqe02uvC_ue4b3vN:-ODMAqe02uvC_ue4b3vO:b-ylzf9s) ([raw file](https://github.com/starkware-libs/stwo/blob/5817df646a7856ec2a880154961788119eeb648a/crates/prover/src/constraint_framework/mod.rs#L234)):*
> ```XML
>         /// Finalizes the row's logup in the default way. Currently, this means no batching.
>         fn finalize_logup(&mut self) {
>             self.finalize_logup_batched(&vec![1; self.logup.fracs.len()])
> ```

I think the format should be cluster id per index



_Code quote:_
```XML
self.finalize_logup_batched(&vec![1; self.logup.fracs.len()])
```

**Review by Alon-Ti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/922)* status: 2 of 11 files reviewed, 2 unresolved discussions (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/mod.rs` line 148 at r5](https://reviewable.io/reviews/starkware-libs/stwo/922#-ODM8LXOEYg3w1Mond5o:-ODMkYRm8S0bf7ZrXZat:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/5817df646a7856ec2a880154961788119eeb648a/crates/prover/src/constraint_framework/mod.rs#L148)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

document? Here is a good place for that?
Also document the format of batching
</blockquote></details>

Done.
___
*[`crates/prover/src/constraint_framework/mod.rs` line 234 at r5](https://reviewable.io/reviews/starkware-libs/stwo/922#-ODMAqe02uvC_ue4b3vN:-ODMkYsx3ufnhzMJjnu-:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/5817df646a7856ec2a880154961788119eeb648a/crates/prover/src/constraint_framework/mod.rs#L234)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I think the format should be cluster id per index
</blockquote></details>

Done.

**Review by ohad-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/922)* status: 2 of 11 files reviewed, 7 unresolved discussions (waiting on @Alon-Ti and @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/mod.rs` line 148 at r6](https://reviewable.io/reviews/starkware-libs/stwo/922#-OD_DbG5AcMRX0xCtUXG:-OD_DbG5AcMRX0xCtUXH:b-od7uho) ([raw file](https://github.com/starkware-libs/stwo/blob/4ba5961aa058984d2044b1a7d991d5ca33dbfaf0/crates/prover/src/constraint_framework/mod.rs#L148)):*
> ```XML
>         unimplemented!()
>     }
>     fn finalize_logup_batched(&mut self, _batching: &[usize]) {
> ```

consider typedefing Batching = Vec<usize>



_Suggestion:_
```XML
Batching
```
___
*[`crates/prover/src/constraint_framework/mod.rs` line 200 at r6](https://reviewable.io/reviews/starkware-libs/stwo/922#-OD_EQIi4fVP17AhTvRi:-OD_EQIi4fVP17AhTvRj:b-bewqyr) ([raw file](https://github.com/starkware-libs/stwo/blob/4ba5961aa058984d2044b1a7d991d5ca33dbfaf0/crates/prover/src/constraint_framework/mod.rs#L200)):*
> ```XML
> 
>             let keys_set: std::collections::HashSet<usize> =
>                 fracs_by_batch.keys().cloned().collect();
> ```

to avoid line drop
and same for below 



_Suggestion:_
```XML
            let keys_set = fracs_by_batch.keys().cloned().collect::<std::collections::HashSet<_>>();
```
___
*[`crates/prover/src/constraint_framework/mod.rs` line 208 at r6](https://reviewable.io/reviews/starkware-libs/stwo/922#-OD_Ekwm62XGalwCGFx1:-OD_Ekwm62XGalwCGFx2:bwc1s5p) ([raw file](https://github.com/starkware-libs/stwo/blob/4ba5961aa058984d2044b1a7d991d5ca33dbfaf0/crates/prover/src/constraint_framework/mod.rs#L208)):*
> ```XML
>             );
> 
>             #[cfg_attr(rustfmt, rustfmt_skip)]
> ```

after I did the above changes, fmt was stable without this



_Code quote:_
```XML
            #[cfg_attr(rustfmt, rustfmt_skip)]
```
___
*[`crates/prover/src/constraint_framework/mod.rs` line 211 at r6](https://reviewable.io/reviews/starkware-libs/stwo/922#-OD_EqmyAITHB-6lwd33:-OD_EqmzERpqhAAV420T:bhe4c5p) ([raw file](https://github.com/starkware-libs/stwo/blob/4ba5961aa058984d2044b1a7d991d5ca33dbfaf0/crates/prover/src/constraint_framework/mod.rs#L211)):*
> ```XML
>             let mut prev_col_cumsum = <Self::EF as num_traits::Zero>::zero();
> 
>             // All except the last batch.
> ```

document what happens to all except the last batch



_Code quote:_
```XML
/ All except the last batch.
```
___
*[`crates/prover/src/constraint_framework/mod.rs` line 213 at r6](https://reviewable.io/reviews/starkware-libs/stwo/922#-OD_FG-pC_apIfd-JROU:-OD_FG-q4-mA2pQcWn7G:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/4ba5961aa058984d2044b1a7d991d5ca33dbfaf0/crates/prover/src/constraint_framework/mod.rs#L213)):*
> ```XML
>             // All except the last batch.
>             for batch_id in (0..last_batch) {
>                 let cur_frac: Fraction<Self::EF, Self::EF> =
> ```





_Suggestion:_
```XML
Fraction<_, _> 
```
___
*[`crates/prover/src/constraint_framework/mod.rs` line 223 at r6](https://reviewable.io/reviews/starkware-libs/stwo/922#-OD_FX9E99X30Oy9FXHV:-OD_FX9E99X30Oy9FXHW:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/4ba5961aa058984d2044b1a7d991d5ca33dbfaf0/crates/prover/src/constraint_framework/mod.rs#L223)):*
> ```XML
> 
>             let frac: Fraction<Self::EF, Self::EF> =
>                 fracs_by_batch[&last_batch].clone().into_iter().sum();
> ```





_Suggestion:_
```XML
           let frac: Fraction<_, _> = fracs_by_batch[&last_batch].iter().cloned().sum();
```

**Review by Alon-Ti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/922)* status: 2 of 11 files reviewed, 7 unresolved discussions (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/mod.rs` line 200 at r6](https://reviewable.io/reviews/starkware-libs/stwo/922#-OD_EQIi4fVP17AhTvRi:-OD_KRSQ9vv1_RjSP4uD:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/4ba5961aa058984d2044b1a7d991d5ca33dbfaf0/crates/prover/src/constraint_framework/mod.rs#L200)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

to avoid line drop
and same for below
</blockquote></details>

Done.
___
*[`crates/prover/src/constraint_framework/mod.rs` line 208 at r6](https://reviewable.io/reviews/starkware-libs/stwo/922#-OD_Ekwm62XGalwCGFx1:-OD_OWNYAJCFAJdkI43f:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/4ba5961aa058984d2044b1a7d991d5ca33dbfaf0/crates/prover/src/constraint_framework/mod.rs#L208)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

after I did the above changes, fmt was stable without this
</blockquote></details>

Done.
___
*[`crates/prover/src/constraint_framework/mod.rs` line 211 at r6](https://reviewable.io/reviews/starkware-libs/stwo/922#-OD_EqmyAITHB-6lwd33:-OD_OXCb2euP8hUtZI2H:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/4ba5961aa058984d2044b1a7d991d5ca33dbfaf0/crates/prover/src/constraint_framework/mod.rs#L211)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

document what happens to all except the last batch
</blockquote></details>

Done.
___
*[`crates/prover/src/constraint_framework/mod.rs` line 213 at r6](https://reviewable.io/reviews/starkware-libs/stwo/922#-OD_FG-pC_apIfd-JROU:-OD_OmfVCfZN64ZkrooX:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/4ba5961aa058984d2044b1a7d991d5ca33dbfaf0/crates/prover/src/constraint_framework/mod.rs#L213)):*
> ```XML
>             // All except the last batch.
>             for batch_id in (0..last_batch) {
>                 let cur_frac: Fraction<Self::EF, Self::EF> =
> ```

Done.
___
*[`crates/prover/src/constraint_framework/mod.rs` line 223 at r6](https://reviewable.io/reviews/starkware-libs/stwo/922#-OD_FX9E99X30Oy9FXHV:-OD_PEId1bU7tz4sU7DS:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/4ba5961aa058984d2044b1a7d991d5ca33dbfaf0/crates/prover/src/constraint_framework/mod.rs#L223)):*
> ```XML
> 
>             let frac: Fraction<Self::EF, Self::EF> =
>                 fracs_by_batch[&last_batch].clone().into_iter().sum();
> ```

Done.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 11 files at r1, 6 of 8 files at r6, 1 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/922)* status: all files reviewed, 1 unresolved discussion (waiting on @Alon-Ti)

___
*[`crates/prover/src/constraint_framework/mod.rs` line 35 at r8](https://reviewable.io/reviews/starkware-libs/stwo/922#-ODg9x6M3i0BWFWjy1xs:-ODg9x6M3i0BWFWjy1xt:b-jimjls) ([raw file](https://github.com/starkware-libs/stwo/blob/7dfb94452707e1d5c2344c09ead9f5d13e8cb04b/crates/prover/src/constraint_framework/mod.rs#L35)):*
> ```XML
> pub const INTERACTION_TRACE_IDX: usize = 2;
> 
> type Batching = Vec<usize>;
> ```

Document



_Code quote:_
```XML
type Batching = Vec<usize>;
```

**Review by Alon-Ti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/922)* status: all files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/mod.rs` line 35 at r8](https://reviewable.io/reviews/starkware-libs/stwo/922#-ODg9x6M3i0BWFWjy1xs:-ODgA7254Jjzd1CqKXeY:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/7dfb94452707e1d5c2344c09ead9f5d13e8cb04b/crates/prover/src/constraint_framework/mod.rs#L35)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Document
</blockquote></details>

Done.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/922#-:-ODgBo421xDqkis-9nf7:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @Alon-Ti)

**Pull request merged**
