### PR TITLE
wrote decomposition

### PR DESCRIPTION
**Pull request by ohad-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/588)

### CODE REVIEW

**Comment by ohad-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/588?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#588** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/588?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#583** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/583?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ohad-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/588)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @ohad-starkware)

___
*[`crates/prover/src/core/fri.rs` line 118 at r4](https://reviewable.io/reviews/starkware-libs/stwo/588#-NwrwtGk49PGN7ulcQBB:-NwrwtGk49PGN7ulcQBC:b-u5dvgs) ([raw file](https://github.com/starkware-libs/stwo/blob/ba5baeedfaf2519ff53b85cd196dcf622b25626f/crates/prover/src/core/fri.rs#L118)):*
> ```XML
>     /// Decomposes a polynomial of degree N/2 in 'x', into a polynomial inside the fft-space and the
>     /// remainder term. Based on lemma #12 from the CircleStark paper: f = g +
>     /// alternating(lambda), where lambda is the cosset diff of eval, and g is the polynomial
> ```

Consider `f(P)=g(P)+lambda * alternating(P)`
___
*[`crates/prover/src/core/backend/avx512/fri.rs` line 106 at r4](https://reviewable.io/reviews/starkware-libs/stwo/588#-NwrxJcj9Q0Sb2ol3c_F:-NwrxJck3mSB3j4g8eOK:b-24tyg6) ([raw file](https://github.com/starkware-libs/stwo/blob/ba5baeedfaf2519ff53b85cd196dcf622b25626f/crates/prover/src/core/backend/avx512/fri.rs#L106)):*
> ```XML
> 
>         let cols = &eval.values.columns;
>         let g_values: [BaseFieldVec; SECURE_EXTENSION_DEGREE] = (0..SECURE_EXTENSION_DEGREE)
> ```

SecureColumn has methods in the AVX backend to get and set packed elements

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/588)* status: 1 of 4 files reviewed, 5 unresolved discussions (waiting on @ohad-starkware)

___
*[`crates/prover/src/core/backend/avx512/fri.rs` line 106 at r4](https://reviewable.io/reviews/starkware-libs/stwo/588#-NwrxJcj9Q0Sb2ol3c_F:-Nwrxv2Z-eAdmEuCegmN:b-z8hcx1) ([raw file](https://github.com/starkware-libs/stwo/blob/ba5baeedfaf2519ff53b85cd196dcf622b25626f/crates/prover/src/core/backend/avx512/fri.rs#L106)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

SecureColumn has methods in the AVX backend to get and set packed elements
</blockquote></details>

And perhaps it's better to modify the column inplace?
___
*[`crates/prover/src/core/backend/avx512/fri.rs` line 140 at r4](https://reviewable.io/reviews/starkware-libs/stwo/588#-NwrxR-K350w6s7TgwwB:-NwrxR-K350w6s7TgwwC:b-98ehs5) ([raw file](https://github.com/starkware-libs/stwo/blob/ba5baeedfaf2519ff53b85cd196dcf622b25626f/crates/prover/src/core/backend/avx512/fri.rs#L140)):*
> ```XML
>     /// See [`CPUBackend::decomposition_coefficient`].
>     ///
>     /// [`CPUBackend::decomposition_coefficient`]: crate::core::backend::cpu::CPUBackend::decomposition_coefficient
> ```

Can you squeeze this in a single line (<=100 chars)?
___
*[`crates/prover/src/core/backend/avx512/fri.rs` line 280 at r4](https://reviewable.io/reviews/starkware-libs/stwo/588#-Nwrx_I7CqSX_d-gWOoC:-Nwrx_I7CqSX_d-gWOoD:bzd11qw) ([raw file](https://github.com/starkware-libs/stwo/blob/ba5baeedfaf2519ff53b85cd196dcf622b25626f/crates/prover/src/core/backend/avx512/fri.rs#L280)):*
> ```XML
>         assert_eq!(avx_lambda, cpu_lambda);
> 
>         for i in 0..(1 << DOMAIN_LOG_SIZE) {
> ```

Can you assert_eq!(avx_g.to_cpu(),cpu_g)?
___
*[`crates/prover/src/core/backend/avx512/mod.rs` line 117 at r4](https://reviewable.io/reviews/starkware-libs/stwo/588#-NwrxfWdAvTXW9l___jg:-NwrxfWdAvTXW9l___jh:bukte9u) ([raw file](https://github.com/starkware-libs/stwo/blob/ba5baeedfaf2519ff53b85cd196dcf622b25626f/crates/prover/src/core/backend/avx512/mod.rs#L117)):*
> ```XML
> }
> 
> impl From<Vec<PackedBaseField>> for BaseFieldVec {
> ```

We already have FromIteratorWou

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/588)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @ohad-starkware)

___
*[`crates/prover/src/core/backend/avx512/mod.rs` line 117 at r4](https://reviewable.io/reviews/starkware-libs/stwo/588#-NwrxfWdAvTXW9l___jg:-Nwry27D4Zq4oLrhgKil:b-3nxmie) ([raw file](https://github.com/starkware-libs/stwo/blob/ba5baeedfaf2519ff53b85cd196dcf622b25626f/crates/prover/src/core/backend/avx512/mod.rs#L117)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

We already have FromIteratorWou
</blockquote></details>

Maybe this will go away after the changes above

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/588)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/core/fri.rs` line 118 at r4](https://reviewable.io/reviews/starkware-libs/stwo/588#-NwrwtGk49PGN7ulcQBB:-Nx7TJ6zBRmb4dMSqlk4:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/ba5baeedfaf2519ff53b85cd196dcf622b25626f/crates/prover/src/core/fri.rs#L118)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Consider `f(P)=g(P)+lambda * alternating(P)`
</blockquote></details>

Done.
___
*[`crates/prover/src/core/backend/avx512/fri.rs` line 106 at r4](https://reviewable.io/reviews/starkware-libs/stwo/588#-NwrxJcj9Q0Sb2ol3c_F:-Nx7UWtvBKngaQc8d0rX:bvqdpca) ([raw file](https://github.com/starkware-libs/stwo/blob/ba5baeedfaf2519ff53b85cd196dcf622b25626f/crates/prover/src/core/backend/avx512/fri.rs#L106)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

And perhaps it's better to modify the column inplace?
</blockquote></details>

changed to take ownership
___
*[`crates/prover/src/core/backend/avx512/fri.rs` line 140 at r4](https://reviewable.io/reviews/starkware-libs/stwo/588#-NwrxR-K350w6s7TgwwB:-Nx7ZcWN6FkjTArzIwAT:b2nign6) ([raw file](https://github.com/starkware-libs/stwo/blob/ba5baeedfaf2519ff53b85cd196dcf622b25626f/crates/prover/src/core/backend/avx512/fri.rs#L140)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Can you squeeze this in a single line (<=100 chars)?
</blockquote></details>

yes
___
*[`crates/prover/src/core/backend/avx512/fri.rs` line 280 at r4](https://reviewable.io/reviews/starkware-libs/stwo/588#-Nwrx_I7CqSX_d-gWOoC:-Nx7Zojm-Fi9JUk20-pK:brpmr64) ([raw file](https://github.com/starkware-libs/stwo/blob/ba5baeedfaf2519ff53b85cd196dcf622b25626f/crates/prover/src/core/backend/avx512/fri.rs#L280)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Can you assert_eq!(avx_g.to_cpu(),cpu_g)?
</blockquote></details>

avx\_g.to\_cpu() is securecolumn and there is no`==` for SecureColumn
___
*[`crates/prover/src/core/backend/avx512/mod.rs` line 117 at r4](https://reviewable.io/reviews/starkware-libs/stwo/588#-NwrxfWdAvTXW9l___jg:-Nx7a1KM6WJ02_W9mseE:b-pb9bue) ([raw file](https://github.com/starkware-libs/stwo/blob/ba5baeedfaf2519ff53b85cd196dcf622b25626f/crates/prover/src/core/backend/avx512/mod.rs#L117)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Maybe this will go away after the changes above
</blockquote></details>

indeed

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/588)* status: all files reviewed, 2 unresolved discussions (waiting on @ohad-starkware)

___
*[`crates/prover/src/core/backend/avx512/fri.rs` line 101 at r6](https://reviewable.io/reviews/starkware-libs/stwo/588#-NxBd7zk-SWWHDa07LKc:-NxBd7zk-SWWHDa07LKd:b73fb84) ([raw file](https://github.com/starkware-libs/stwo/blob/22cc0fd65ce657695e6dcb6c9efd61635836d233/crates/prover/src/core/backend/avx512/fri.rs#L101)):*
> ```XML
>         let col = &mut eval.values;
> 
>         (0..col.len().div_ceil(K_BLOCK_SIZE)).for_each(|i| {
> ```

Don't do if inside the loop. It's potentially less efficient. Instead, do 2 loops. (Consider either creating two ranges or splitting in the middle, or chunks)
Below too.

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/588)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/core/backend/avx512/fri.rs` line 101 at r6](https://reviewable.io/reviews/starkware-libs/stwo/588#-NxBd7zk-SWWHDa07LKc:-NxRYY_g5B8cS_7ZRMhn:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/22cc0fd65ce657695e6dcb6c9efd61635836d233/crates/prover/src/core/backend/avx512/fri.rs#L101)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Don't do if inside the loop. It's potentially less efficient. Instead, do 2 loops. (Consider either creating two ranges or splitting in the middle, or chunks)
Below too.
</blockquote></details>

Done.

**Pull request merged**
