### PR TITLE
ProverCommitmentScheme::commit_on_evals()

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/707)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/707?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#707** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/707?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#706** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/706?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#705** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/705?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#704** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/704?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#702** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/702?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#701** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/701?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/707)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/core/pcs/prover.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/stwo/707#-O1l--y200xM-rF0poCZ:-O1l--y200xM-rF0poC_:b3kre) ([raw file](https://github.com/starkware-libs/stwo/blob/e4cf4fa79c9f89d9e73e69844a5e7dfc11ef14c8/crates/prover/src/core/pcs/prover.rs#L61)):*
> ```XML
>         &mut self,
>         evals: ColumnVec<CircleEvaluation<B, BaseField, BitReversedOrder>>,
>         channel: &mut Blake2sChannel,
> ```

?



_Suggestion:_
```XML
        channel: &mut ProofChannel,
```
___
*[`crates/prover/src/core/pcs/prover.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/stwo/707#-O1l-K38EdoINRlwCDL0:-O1l-K38EdoINRlwCDL1:b-n5w4l5) ([raw file](https://github.com/starkware-libs/stwo/blob/e4cf4fa79c9f89d9e73e69844a5e7dfc11ef14c8/crates/prover/src/core/pcs/prover.rs#L64)):*
> ```XML
>         twiddles: &TwiddleTree<B>,
>     ) {
>         let span = span!(Level::INFO, "Interpolation").entered();
> ```

Do we care that this interpolation is for commitment? and not for constraints?



_Suggestion:_
```XML
        let span = span!(Level::INFO, "Interpolation for commitment").entered();
```

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/707)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/prover/src/core/pcs/prover.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/stwo/707#-O1l--y200xM-rF0poCZ:-O1l5Ah41R-DDWxpsd34:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/e4cf4fa79c9f89d9e73e69844a5e7dfc11ef14c8/crates/prover/src/core/pcs/prover.rs#L61)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.
___
*[`crates/prover/src/core/pcs/prover.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/stwo/707#-O1l-K38EdoINRlwCDL0:-O1l5CprERaWowc5XHc0:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/e4cf4fa79c9f89d9e73e69844a5e7dfc11ef14c8/crates/prover/src/core/pcs/prover.rs#L64)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Do we care that this interpolation is for commitment? and not for constraints?
</blockquote></details>

Done.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/707#-:-O1lFIAp-c1T4M2IUYoq:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
