### PR TITLE
Implement trace generator for fibonacci.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/674)

### CODE REVIEW

**Comment by alonh5** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/674?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#674** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/674?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#672** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/672?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#671** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/671?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#669** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/669?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#667** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/667?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#664** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/664?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#662** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/662?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#646** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/646?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#644** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/644?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#654](https://github.com/starkware-libs/stwo/pull/654) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/654?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#642** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/642?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#639** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/639?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#638** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/638?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#637** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/637?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#636** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/636?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#651** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/651?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ohad-agadi — CHANGES_REQUESTED** [review]
> Reviewed 9 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/674)* status: 9 of 12 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

___
*[`crates/prover/src/examples/fibonacci/air.rs` line 51 at r3](https://reviewable.io/reviews/starkware-libs/stwo/674#-O0rgfwb6EgLKOQB3z7m:-O0rgfwb6EgLKOQB3z7n:bcsh6sb) ([raw file](https://github.com/starkware-libs/stwo/blob/45989becf04bf7417b2c96a4a019ec7366a1ccdd/crates/prover/src/examples/fibonacci/air.rs#L51)):*
> ```XML
>             .registry
>             .get_generator::<FibonacciTraceGenerator>("fibonacci");
>         // TODO(AlonH): Take instead of clone.
> ```

left by accident?
___
*[`crates/prover/src/examples/fibonacci/component.rs` line 137 at r3](https://reviewable.io/reviews/starkware-libs/stwo/674#-O0ri4HqACEI3paUNijc:-O0ri4HqACEI3paUNijd:bfke5fj) ([raw file](https://github.com/starkware-libs/stwo/blob/45989becf04bf7417b2c96a4a019ec7366a1ccdd/crates/prover/src/examples/fibonacci/component.rs#L137)):*
> ```XML
> 
> #[derive(Clone)]
> pub struct FibonacciTraceGenerator {
> ```

Option<FibonaciInput>
___
*[`crates/prover/src/examples/fibonacci/component.rs` line 172 at r3](https://reviewable.io/reviews/starkware-libs/stwo/674#-O0rlZgL9YrcuLEr9qUh:-O0rlZgM9s-CzqCB3UBz:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/45989becf04bf7417b2c96a4a019ec7366a1ccdd/crates/prover/src/examples/fibonacci/component.rs#L172)):*
> ```XML
>         registry: &mut ComponentGenerationRegistry,
>     ) -> ColumnVec<CircleEvaluation<CpuBackend, BaseField, BitReversedOrder>> {
>         let component = registry.get_generator_mut::<Self>(component_id);
> ```





_Suggestion:_
```XML
trace_generator
```
___
*[`crates/prover/src/examples/wide_fibonacci/simd.rs` line 53 at r3](https://reviewable.io/reviews/starkware-libs/stwo/674#-O0rmMMjCWNywla8MyhO:-O0rmMMjCWNywla8MyhP:bbct70u) ([raw file](https://github.com/starkware-libs/stwo/blob/45989becf04bf7417b2c96a4a019ec7366a1ccdd/crates/prover/src/examples/wide_fibonacci/simd.rs#L53)):*
> ```XML
> 
> // TODO(AlonH): Remove this once the Cpu and Simd implementations are aligned.
> #[derive(Clone)]
> ```

The way to get rid of this struct is to have a separate WideFibSimdTraceGenerator and implementing  TraceGenerator<Simd>
___
*[`crates/prover/src/trace_generation/mod.rs` line 54 at r3](https://reviewable.io/reviews/starkware-libs/stwo/674#-O0rms8R7I-gkappfQYK:-O0rms8R7I-gkappfQYL:b-cnarur) ([raw file](https://github.com/starkware-libs/stwo/blob/45989becf04bf7417b2c96a4a019ec7366a1ccdd/crates/prover/src/trace_generation/mod.rs#L54)):*
> ```XML
> 
>     fn write_trace(&mut self) -> Vec<CircleEvaluation<B, BaseField, BitReversedOrder>> {
>         vec![]
> ```

temporary, right?

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/674)* status: 9 of 12 files reviewed, 2 unresolved discussions (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`crates/prover/src/examples/fibonacci/air.rs` line 51 at r3](https://reviewable.io/reviews/starkware-libs/stwo/674#-O0rgfwb6EgLKOQB3z7m:-O0rzt9i1u6ViltaXEpK:b-k614gh) ([raw file](https://github.com/starkware-libs/stwo/blob/45989becf04bf7417b2c96a4a019ec7366a1ccdd/crates/prover/src/examples/fibonacci/air.rs#L51)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

left by accident?
</blockquote></details>

Yes, thanks.
___
*[`crates/prover/src/examples/fibonacci/component.rs` line 137 at r3](https://reviewable.io/reviews/starkware-libs/stwo/674#-O0ri4HqACEI3paUNijc:-O0s-yHDCxrpyK97ZW0w:b-7zi8tj) ([raw file](https://github.com/starkware-libs/stwo/blob/45989becf04bf7417b2c96a4a019ec7366a1ccdd/crates/prover/src/examples/fibonacci/component.rs#L137)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

Option<FibonaciInput>
</blockquote></details>

WDYM?
___
*[`crates/prover/src/examples/wide_fibonacci/simd.rs` line 53 at r3](https://reviewable.io/reviews/starkware-libs/stwo/674#-O0rmMMjCWNywla8MyhO:-O0s-KF498WpKoK4pQX4:bc1z64) ([raw file](https://github.com/starkware-libs/stwo/blob/45989becf04bf7417b2c96a4a019ec7366a1ccdd/crates/prover/src/examples/wide_fibonacci/simd.rs#L53)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

The way to get rid of this struct is to have a separate WideFibSimdTraceGenerator and implementing  TraceGenerator<Simd>
</blockquote></details>

We will still need this struct then, it just own't implement TraceGenerator.
___
*[`crates/prover/src/trace_generation/mod.rs` line 54 at r3](https://reviewable.io/reviews/starkware-libs/stwo/674#-O0rms8R7I-gkappfQYK:-O0s-_CoDyECxvUi2B1-:bwuk0hz) ([raw file](https://github.com/starkware-libs/stwo/blob/45989becf04bf7417b2c96a4a019ec7366a1ccdd/crates/prover/src/trace_generation/mod.rs#L54)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

temporary, right?
</blockquote></details>

Yes, added a TODO to remove it.

**Review by ohad-agadi — COMMENTED** [review]
> Reviewed 1 of 12 files at r3, 2 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/674)* status: 11 of 12 files reviewed, all discussions resolved (waiting on @shaharsamocha7)

___
*[`crates/prover/src/examples/fibonacci/component.rs` line 139 at r4](https://reviewable.io/reviews/starkware-libs/stwo/674#-O0s1i9x2xcMhp9T8yxX:-O0s1i9x2xcMhp9T8yxY:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/5e17a6ebb53c2f2faa0cedb06822bae82c2f2613/crates/prover/src/examples/fibonacci/component.rs#L139)):*
> ```XML
> pub struct FibonacciTraceGenerator {
>     log_size: Option<u32>,
>     claim: Option<BaseField>,
> ```





_Suggestion:_
```XML
input: Option<FibonacciInput>
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/674)* status: 10 of 12 files reviewed, all discussions resolved (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`crates/prover/src/examples/fibonacci/component.rs` line 139 at r4](https://reviewable.io/reviews/starkware-libs/stwo/674#-O0s1i9x2xcMhp9T8yxX:-O0s2RF0AlLQCi64xkDL:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/5e17a6ebb53c2f2faa0cedb06822bae82c2f2613/crates/prover/src/examples/fibonacci/component.rs#L139)):*
> ```XML
> pub struct FibonacciTraceGenerator {
>     log_size: Option<u32>,
>     claim: Option<BaseField>,
> ```

Done.

**Review by ohad-agadi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/674#-:-O0s4znmBDEQl5UEwUuq:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Comment by alonh5** [comment]
### Merge activity

* **Jul 8, 7:18 AM EDT**: @alonh5 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/674).

**Pull request merged**
