### PR TITLE
Fri AVX ops

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/563)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/563?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#511** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/511?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#496** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/496?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#495** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/495?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#494** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/494?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#493** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/493?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#492** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/492?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#491** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/491?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#490** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/490?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#489** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/489?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#563** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/563?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#488** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/488?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#486** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/486?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#531** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/531?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#530** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/530?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#529** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/529?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#528** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/528?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#527** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/527?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#526** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/526?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#548** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/548?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
Add tests

> Reviewed 8 of 12 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/563#-:-NuYs_2-Es5yijHtVIiR:b-5i6aoz)* status: 10 of 12 files reviewed, 5 unresolved discussions (waiting on @spapinistarkware)

___
*[`src/core/fri.rs` line 1071 at r2](https://reviewable.io/reviews/starkware-libs/stwo/563#-NuYstt98I1LCD3_TnOb:-NuYstt98I1LCD3_TnOc:bld1e57) ([raw file](https://github.com/starkware-libs/stwo/blob/6fb0019d56c722bec626589394f138a1e03641e1/src/core/fri.rs#L1071)):*
> ```XML
>             config,
>             &[evaluation.clone()],
>             &CPUBackend::precompute_twiddles(evaluation.domain.half_coset),
> ```

Do we want to calculate real data here if it is not being used?



_Code quote:_
```XML
 &CPUBackend::precompute_twiddles(evaluation.domain.half_coset),
```
___
*[`src/core/backend/avx512/qm31.rs` line 53 at r2](https://reviewable.io/reviews/starkware-libs/stwo/563#-NuYtYcy28CjBfPvMHmX:-NuYtYcz5EtW9IxExWVt:bnuy5ve) ([raw file](https://github.com/starkware-libs/stwo/blob/6fb0019d56c722bec626589394f138a1e03641e1/src/core/backend/avx512/qm31.rs#L53)):*
> ```XML
>         let c = self.0[1].0[0] * rhs;
>         let d = self.0[1].0[1] * rhs;
>         PackedSecureField([PackedCM31([a, b]), PackedCM31([c, d])])
> ```

can you use here to/from_packed



_Code quote:_
```XML
    pub fn mul_packed_m31(&self, rhs: PackedBaseField) -> PackedSecureField {
        let a = self.0[0].0[0] * rhs;
        let b = self.0[0].0[1] * rhs;
        let c = self.0[1].0[0] * rhs;
        let d = self.0[1].0[1] * rhs;
        PackedSecureField([PackedCM31([a, b]), PackedCM31([c, d])])
```
___
*[`src/core/backend/cpu/fri.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/stwo/563#-NuYtk3nBhSpD-vKKRH3:-NuYtk3nBhSpD-vKKRH4:bsdjdbj) ([raw file](https://github.com/starkware-libs/stwo/blob/6fb0019d56c722bec626589394f138a1e03641e1/src/core/backend/cpu/fri.rs#L14)):*
> ```XML
>         _twiddles: &TwiddleTree<Self>,
>     ) -> LineEvaluation<Self> {
>         fold_line(eval, alpha)
> ```

Add a todo to optimize those functions as well



_Code quote:_
```XML
fold_line(eval, alpha)
```
___
*[`src/core/poly/utils.rs` line 60 at r2](https://reviewable.io/reviews/starkware-libs/stwo/563#-NuYuFVw4QwQ_srSyW7O:-NuYuFVw4QwQ_srSyW7P:b-u6m1ic) ([raw file](https://github.com/starkware-libs/stwo/blob/6fb0019d56c722bec626589394f138a1e03641e1/src/core/poly/utils.rs#L60)):*
> ```XML
> ///
> /// [`CircleDomain`]: super::circle::CircleDomain
> pub fn domain_line_twiddles_from_tree<T>(
> ```

This change also support folding line twiddles to line twiddles
update documentation



_Code quote:_
```XML
pub fn domain_line_twiddles_from_tree<T>(
```
___
*[`src/core/poly/circle/secure_poly.rs` line 55 at r2](https://reviewable.io/reviews/starkware-libs/stwo/563#-NuYuaLT5FWgiS151mW4:-NuYuaLT5FWgiS151mW5:b-bj5lfc) ([raw file](https://github.com/starkware-libs/stwo/blob/6fb0019d56c722bec626589394f138a1e03641e1/src/core/poly/circle/secure_poly.rs#L55)):*
> ```XML
> }
> 
> #[derive(Clone)]
> ```

Do we want that? looks risky



_Code quote:_
```XML
#[derive(Clone)]
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/563)* status: 10 of 12 files reviewed, 4 unresolved discussions (waiting on @shaharsamocha7)

___
*[`src/core/fri.rs` line 1071 at r2](https://reviewable.io/reviews/starkware-libs/stwo/563#-NuYstt98I1LCD3_TnOb:-NuZ-zpPCt6DSk8FXbns:b72w7us) ([raw file](https://github.com/starkware-libs/stwo/blob/efe300ae2a6b6acedacef4fccc88cf55c9d201c3/src/core/fri.rs#L1071)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Do we want to calculate real data here if it is not being used?
</blockquote></details>

readl data? WDYM?
___
*[`src/core/backend/cpu/fri.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/stwo/563#-NuYtk3nBhSpD-vKKRH3:-NuZ-S6Q9Cx7Kbxxn6QC:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/efe300ae2a6b6acedacef4fccc88cf55c9d201c3/src/core/backend/cpu/fri.rs#L14)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Add a todo to optimize those functions as well
</blockquote></details>

Done.
___
*[`src/core/poly/utils.rs` line 60 at r2](https://reviewable.io/reviews/starkware-libs/stwo/563#-NuYuFVw4QwQ_srSyW7O:-NuZ-fh99YpCydZyXTZT:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/efe300ae2a6b6acedacef4fccc88cf55c9d201c3/src/core/poly/utils.rs#L60)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

This change also support folding line twiddles to line twiddles
update documentation
</blockquote></details>

Done.
___
*[`src/core/poly/circle/secure_poly.rs` line 55 at r2](https://reviewable.io/reviews/starkware-libs/stwo/563#-NuYuaLT5FWgiS151mW4:-NuZ-ivQ7_i8Uxz3STJF:b-f40iyb) ([raw file](https://github.com/starkware-libs/stwo/blob/efe300ae2a6b6acedacef4fccc88cf55c9d201c3/src/core/poly/circle/secure_poly.rs#L55)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Do we want that? looks risky
</blockquote></details>

Well, it's not Copy, so it'll be explicit.

**Review by shaharsamocha7 — COMMENTED** [review]
> Reviewed 1 of 12 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/563)* status: 11 of 12 files reviewed, all discussions resolved

___
*[`src/core/fri.rs` line 1071 at r2](https://reviewable.io/reviews/starkware-libs/stwo/563#-NuYstt98I1LCD3_TnOb:-NuZX6gfBtcCXwnWSNlB:bktc4m2) ([raw file](https://github.com/starkware-libs/stwo/blob/efe300ae2a6b6acedacef4fccc88cf55c9d201c3/src/core/fri.rs#L1071)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

readl data? WDYM?
</blockquote></details>

Thought that since we are not using it we can just put here mock data.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/563)* status: 11 of 12 files reviewed, all discussions resolved (waiting on @shaharsamocha7)

___
*[`src/core/fri.rs` line 1071 at r2](https://reviewable.io/reviews/starkware-libs/stwo/563#-NuYstt98I1LCD3_TnOb:-NuZXnFw4IBcPV4vISDt:b1nbjrg) ([raw file](https://github.com/starkware-libs/stwo/blob/efe300ae2a6b6acedacef4fccc88cf55c9d201c3/src/core/fri.rs#L1071)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Thought that since we are not using it we can just put here mock data.
</blockquote></details>

The AVX backend uses it, and it's real data.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/563)* status: 11 of 12 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`src/core/backend/avx512/fri.rs` line 39 at r3](https://reviewable.io/reviews/starkware-libs/stwo/563#-Nubp3rm3dPgDEKdNx4K:-Nubp3rnCfFxjCi9WDim:b-5j1o0i) ([raw file](https://github.com/starkware-libs/stwo/blob/fdc8c295ec006a016d0af0df53437a077747db4a/src/core/backend/avx512/fri.rs#L39)):*
> ```XML
>                 let els: [_; 4] = std::array::from_fn(|i| {
>                     avx_ibutterfly(val0[i], val1[i], std::mem::transmute(twiddle_dbl))
>                 });
> ```

what els stands for?



_Code quote:_
```XML
                let els: [_; 4] = std::array::from_fn(|i| {
                    avx_ibutterfly(val0[i], val1[i], std::mem::transmute(twiddle_dbl))
                });
```
___
*[`src/core/backend/avx512/fri.rs` line 61 at r3](https://reviewable.io/reviews/starkware-libs/stwo/563#-NubpT9B4OQzrGkB4ftD:-NubpT9B4OQzrGkB4ftE:bkmj5vb) ([raw file](https://github.com/starkware-libs/stwo/blob/fdc8c295ec006a016d0af0df53437a077747db4a/src/core/backend/avx512/fri.rs#L61)):*
> ```XML
>         let domain = src.domain;
>         let alpha_sq = alpha * alpha;
>         let itwiddles = domain_line_twiddles_from_tree(domain, &twiddles.itwiddles)[0];
> ```

I thought that we have some tricks to compute the twiddles for the circle layer.
Are we precompute them directly now?



_Code quote:_
```XML
let itwiddles = domain_line_twiddles_from_tree(domain, &twiddles.itwiddles)[0];
```
___
*[`src/core/backend/avx512/fri.rs` line 66 at r3](https://reviewable.io/reviews/starkware-libs/stwo/563#-Nubperk8A0KElSYKQGP:-Nubperk8A0KElSYKQGQ:b-okuy6b) ([raw file](https://github.com/starkware-libs/stwo/blob/fdc8c295ec006a016d0af0df53437a077747db4a/src/core/backend/avx512/fri.rs#L66)):*
> ```XML
>             let value = unsafe {
>                 let twiddle_dbl: [i32; 8] =
>                     std::array::from_fn(|i| *itwiddles.get_unchecked(vec_index * 8 + i));
> ```

why is it 8 now instead of 16?



_Code quote:_
```XML
vec_index * 8 + i
```

**Review by spapinistarkware — COMMENTED** [review]
Ty. That fixed my issues:)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/563#-:-Nubu8_Y1TLvsQIbegTY:b-fudya4)* status: 11 of 12 files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7)

___
*[`src/core/backend/avx512/fri.rs` line 39 at r3](https://reviewable.io/reviews/starkware-libs/stwo/563#-Nubp3rm3dPgDEKdNx4K:-NubugNa3eTzE6XcD0Up:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/fdc8c295ec006a016d0af0df53437a077747db4a/src/core/backend/avx512/fri.rs#L39)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

what els stands for?
</blockquote></details>

Done.
___
*[`src/core/backend/avx512/fri.rs` line 61 at r3](https://reviewable.io/reviews/starkware-libs/stwo/563#-NubpT9B4OQzrGkB4ftD:-Nubul-U2FzrTOQ6pWKo:b-z3g4fs) ([raw file](https://github.com/starkware-libs/stwo/blob/fdc8c295ec006a016d0af0df53437a077747db4a/src/core/backend/avx512/fri.rs#L61)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I thought that we have some tricks to compute the twiddles for the circle layer.
Are we precompute them directly now?
</blockquote></details>

Note that call to compute_first_twiddles below. That is the trick.
___
*[`src/core/backend/avx512/fri.rs` line 66 at r3](https://reviewable.io/reviews/starkware-libs/stwo/563#-Nubperk8A0KElSYKQGP:-Nubv2525a3HIQEHVkqu:b-7j4mck) ([raw file](https://github.com/starkware-libs/stwo/blob/fdc8c295ec006a016d0af0df53437a077747db4a/src/core/backend/avx512/fri.rs#L66)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

why is it 8 now instead of 16?
</blockquote></details>

Because of the trick. These are the 8 twiddles of the line domain "after" this circle domain.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/563)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`src/core/backend/avx512/fri.rs` line 66 at r3](https://reviewable.io/reviews/starkware-libs/stwo/563#-Nubperk8A0KElSYKQGP:-NubyAjZ1MOQQMBJcGpX:b-kl43c0) ([raw file](https://github.com/starkware-libs/stwo/blob/fdc8c295ec006a016d0af0df53437a077747db4a/src/core/backend/avx512/fri.rs#L66)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Because of the trick. These are the 8 twiddles of the line domain "after" this circle domain.
</blockquote></details>

document

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/563#-:-Nuc4n4yEaDlPvtosiyO:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/563)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

___
*[`src/core/backend/avx512/fri.rs` line 66 at r3](https://reviewable.io/reviews/starkware-libs/stwo/563#-Nubperk8A0KElSYKQGP:-Nuc1T3_64OH15g_Qtq4:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/fdc8c295ec006a016d0af0df53437a077747db4a/src/core/backend/avx512/fri.rs#L66)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

document
</blockquote></details>

Done.

**Pull request merged**
