### PR TITLE
avx blake

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/518)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
* **#518** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/518?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ohad-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/518)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`src/commitment_scheme/blake2_hash.rs` line 108 at r1](https://reviewable.io/reviews/starkware-libs/stwo/518#-NtV0NFO97C0rKbpmMfr:-NtV0NFO97C0rKbpmMfs:btai5te) ([raw file](https://github.com/starkware-libs/stwo/blob/42d62430620f336b2db9debf3b90b476616fd6b9/src/commitment_scheme/blake2_hash.rs#L108)):*
> ```XML
>     fn finalize(mut self) -> Blake2sHash {
>         if self.current_len != 0 {
>             self.update(&[0; 64]);
> ```

finalize is not a regular compression,
maybe we should expose a finalize without a finalization flag
___
*[`src/commitment_scheme/blake2_hash.rs` line 114 at r1](https://reviewable.io/reviews/starkware-libs/stwo/518#-NtUzisb4vKG84VD53S5:-NtUzisb4vKG84VD53S6:b45h) ([raw file](https://github.com/starkware-libs/stwo/blob/42d62430620f336b2db9debf3b90b476616fd6b9/src/commitment_scheme/blake2_hash.rs#L114)):*
> ```XML
> 
>     fn finalize_reset(&mut self) -> Blake2sHash {
>         let hash = self.clone().finalize();
> ```





_Suggestion:_
```XML
let hash = Blake2sHash(unsafe{ std::mem::transmute_copy(&self.state)})
```
___
*[`src/commitment_scheme/blake2s_avx.rs` line 216 at r1](https://reviewable.io/reviews/starkware-libs/stwo/518#-NtUxkSc3JZuOhYTMnjt:-NtUxkSc3JZuOhYTMnju:b-5b6fqr) ([raw file](https://github.com/starkware-libs/stwo/blob/42d62430620f336b2db9debf3b90b476616fd6b9/src/commitment_scheme/blake2s_avx.rs#L216)):*
> ```XML
> }
> 
> /// # Safety
> ```

doc/make private
___
*[`src/commitment_scheme/blake2s_ref.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/stwo/518#-NtV11sM2LGolruWID0x:-NtV11sM2LGolruWID0y:b-csq96m) ([raw file](https://github.com/starkware-libs/stwo/blob/42d62430620f336b2db9debf3b90b476616fd6b9/src/commitment_scheme/blake2s_ref.rs#L1)):*
> ```XML
> //! Based on bla bla's impl. TODO: add the link.
> ```

just a reminder to not forget these
___
*[`src/core/proof_of_work.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/stwo/518#-NtUxMvN4Wmk6Uh3K9Yx:-NtUxMvN4Wmk6Uh3K9Yy:b-5ggsmv) ([raw file](https://github.com/starkware-libs/stwo/blob/3bc4c79140c72a1beb244c919076868e2135abba/src/core/proof_of_work.rs#L100)):*
> ```XML
> 
>     #[test]
>     fn test_verify_proof_of_work_success() {
> ```

why delete this?

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/518)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @ohad-starkware)

___
*[`src/commitment_scheme/blake2_hash.rs` line 108 at r1](https://reviewable.io/reviews/starkware-libs/stwo/518#-NtV0NFO97C0rKbpmMfr:-NtV6aN60v2b0dOAaZ1_:b-1k4j84) ([raw file](https://github.com/starkware-libs/stwo/blob/42d62430620f336b2db9debf3b90b476616fd6b9/src/commitment_scheme/blake2_hash.rs#L108)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

finalize is not a regular compression,
maybe we should expose a finalize without a finalization flag
</blockquote></details>

For stark, we dont care about finalization.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/518)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @ohad-starkware)

___
*[`src/core/proof_of_work.rs` line 100 at r1](https://reviewable.io/reviews/starkware-libs/stwo/518#-NtUxMvN4Wmk6Uh3K9Yx:-NtV6ikM1lSXJOstemA_:b3o5g17) ([raw file](https://github.com/starkware-libs/stwo/blob/3bc4c79140c72a1beb244c919076868e2135abba/src/core/proof_of_work.rs#L100)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

why delete this?
</blockquote></details>

This test depends on concrete values of the hash, so it's not really a POW test. The 3rd tests in this file is enough IMO

**Review by ohad-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/518)* status: 2 of 7 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`src/commitment_scheme/blake2_hash.rs` line 94 at r2](https://reviewable.io/reviews/starkware-libs/stwo/518#-NtVylaC7xfALo_DjwY5:-NtVylaC7xfALo_DjwY6:b-gftyjo) ([raw file](https://github.com/starkware-libs/stwo/blob/5c080ca73e262632411263a4c9bcaa8b13938d66/src/commitment_scheme/blake2_hash.rs#L94)):*
> ```XML
> 
>     fn update(&mut self, mut data: &[u8]) {
>         while self.pending_len + data.len() >= 64 {
> ```

use Self::BLOCK_SIZE 
(in the lower level stuff I think raw numbers is fine)
___
*[`src/commitment_scheme/blake2_hash.rs` line 101 at r2](https://reviewable.io/reviews/starkware-libs/stwo/518#-NtVz7eN01BoeG7xe9P6:-NtVz7eN01BoeG7xe9P7:b-al4vqc) ([raw file](https://github.com/starkware-libs/stwo/blob/5c080ca73e262632411263a4c9bcaa8b13938d66/src/commitment_scheme/blake2_hash.rs#L101)):*
> ```XML
>             let words =
>                 unsafe { std::mem::transmute::<&[u8; 64], &[u32; 16]>(&self.pending_buffer) };
>             blake2s_ref::compress(&mut self.state, words, 0, 0, 0, 0);
> ```

if count arguments = 0 is intentional, document
___
*[`src/commitment_scheme/blake2_hash.rs` line 139 at r2](https://reviewable.io/reviews/starkware-libs/stwo/518#-NtW-F1aAKHGdNdLQE_D:-NtW-DcREm1WlGswuykd:b-qxu6ps) ([raw file](https://github.com/starkware-libs/stwo/blob/5c080ca73e262632411263a4c9bcaa8b13938d66/src/commitment_scheme/blake2_hash.rs#L139)):*
> ```XML
>             dst = dst.add(16 * 32);
>         }
>         // Handle the remainder.
> ```

below too



_Suggestion:_
```XML
        }
        
        // Handle the remainder.
```
___
*[`src/commitment_scheme/blake2_hash.rs` line 163 at r2](https://reviewable.io/reviews/starkware-libs/stwo/518#-NtW0xoj7CCf0MmQaqmA:-NtW0xoj7CCf0MmQaqmB:b7yetzm) ([raw file](https://github.com/starkware-libs/stwo/blob/5c080ca73e262632411263a4c9bcaa8b13938d66/src/commitment_scheme/blake2_hash.rs#L163)):*
> ```XML
> unsafe fn compress16(inputs: &[*const u8; 16], single_input_length_bytes: usize) -> [u8; 16 * 32] {
>     let mut states = [set1(0); 8];
>     let mut inputs = inputs.map(|input| input);
> ```

or take ownership 



_Suggestion:_
```XML
*inputs
```
___
*[`src/commitment_scheme/blake2_hash.rs` line 166 at r2](https://reviewable.io/reviews/starkware-libs/stwo/518#-NtW-iyhD7KNiEtLbjuL:-NtW-hig7ZEPygJFtIwj:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/5c080ca73e262632411263a4c9bcaa8b13938d66/src/commitment_scheme/blake2_hash.rs#L166)):*
> ```XML
> 
>     // Compress in chunks of 64 bytes.
>     for _j in (0..single_input_length_bytes).step_by(64) {
> ```





_Suggestion:_
```XML
_
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/518)* status: 0 of 7 files reviewed, 3 unresolved discussions (waiting on @ohad-starkware)

___
*[`src/commitment_scheme/blake2_hash.rs` line 139 at r2](https://reviewable.io/reviews/starkware-libs/stwo/518#-NtW-F1aAKHGdNdLQE_D:-NtkfLQF6dLR9feNmbXN:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/5c080ca73e262632411263a4c9bcaa8b13938d66/src/commitment_scheme/blake2_hash.rs#L139)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

below too
</blockquote></details>

Done.
___
*[`src/commitment_scheme/blake2_hash.rs` line 163 at r2](https://reviewable.io/reviews/starkware-libs/stwo/518#-NtW0xoj7CCf0MmQaqmA:-Ntkg5PrCqA5dKw_P8Z-:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/5c080ca73e262632411263a4c9bcaa8b13938d66/src/commitment_scheme/blake2_hash.rs#L163)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

or take ownership
</blockquote></details>

Done.
___
*[`src/commitment_scheme/blake2_hash.rs` line 166 at r2](https://reviewable.io/reviews/starkware-libs/stwo/518#-NtW-iyhD7KNiEtLbjuL:-NtkfLs4A-AE2UkTtsJz:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/5c080ca73e262632411263a4c9bcaa8b13938d66/src/commitment_scheme/blake2_hash.rs#L166)):*
> ```XML
> 
>     // Compress in chunks of 64 bytes.
>     for _j in (0..single_input_length_bytes).step_by(64) {
> ```

Done.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/518)* status: 0 of 7 files reviewed, 8 unresolved discussions (waiting on @andrewmilson, @ohad-starkware, and @spapinistarkware)

___
*[`src/commitment_scheme/blake2_hash.rs` line 67 at r4](https://reviewable.io/reviews/starkware-libs/stwo/518#-Ntkum27DOfjhV3Xp7H5:-Ntkum27DOfjhV3Xp7H6:bb7q05e) ([raw file](https://github.com/starkware-libs/stwo/blob/b8b4d6b67b0e1656805301631e13e68d500f26f4/src/commitment_scheme/blake2_hash.rs#L67)):*
> ```XML
> 
> /// Wrapper for the blake2s Hashing functionalities.
> /// This blake2s hasher is intended to be sued only when the structure of the input is agreed upon.
> ```

used



_Code quote:_
```XML
sued
```
___
*[`src/commitment_scheme/blake2_hash.rs` line 71 at r4](https://reviewable.io/reviews/starkware-libs/stwo/518#-NtkvXUE8cuzmvGIbED0:-NtkvXUE8cuzmvGIbED1:b8ut2tn) ([raw file](https://github.com/starkware-libs/stwo/blob/b8b4d6b67b0e1656805301631e13e68d500f26f4/src/commitment_scheme/blake2_hash.rs#L71)):*
> ```XML
> /// The blake2s permutation is used as a hash chain, with no counts, flags or proper padding.
> #[derive(Clone, Debug)]
> pub struct Blake2sHasher {
> ```

We should do finialize for the channel hash.
Only the merkle can reduce it



_Code quote:_
```XML
pub struct Blake2sHasher {
```
___
*[`src/commitment_scheme/blake2_hash.rs` line 73 at r4](https://reviewable.io/reviews/starkware-libs/stwo/518#-NtkvnCVDBEWtv_2cf3j:-NtkvnCVDBEWtv_2cf3k:b-yd1kpa) ([raw file](https://github.com/starkware-libs/stwo/blob/b8b4d6b67b0e1656805301631e13e68d500f26f4/src/commitment_scheme/blake2_hash.rs#L73)):*
> ```XML
> pub struct Blake2sHasher {
>     state: [u32; 8],
>     pending_buffer: [u8; 64],
> ```

Document that this is double than the state size.



_Code quote:_
```XML
pending_buffer: [u8; 64],
```
___
*[`src/commitment_scheme/hasher.rs` line 81 at r4](https://reviewable.io/reviews/starkware-libs/stwo/518#-NtkwsuYCA7qdtkmKSVa:-NtkwsuZ2lLhBjMauxt5:b-l6hdjr) ([raw file](https://github.com/starkware-libs/stwo/blob/b8b4d6b67b0e1656805301631e13e68d500f26f4/src/commitment_scheme/hasher.rs#L81)):*
> ```XML
>             })
>     }
> }
> ```

revert



_Code quote:_
```XML
    ) {
        data.iter()
            .map(|p| std::slice::from_raw_parts(*p, single_input_length_bytes))
            .zip(
                dst.iter()
                    .map(|p| std::slice::from_raw_parts_mut(*p, Self::OUTPUT_SIZE)),
            )
            .for_each(|(input, out)| {
                let mut hasher = Self::new();
                hasher.update(input);
                out.clone_from_slice(&hasher.finalize().into());
            })
    }
}
```
___
*[`src/core/proof_of_work.rs` line 106 at r4](https://reviewable.io/reviews/starkware-libs/stwo/518#-NtkwxNY-WZKhRSaZmKy:-NtkwxNY-WZKhRSaZmKz:b-l6hdjr) ([raw file](https://github.com/starkware-libs/stwo/blob/20412e4a9f00507d771f24d66e4dbd59d0c66849/src/core/proof_of_work.rs#L106)):*
> ```XML
> 
>         proof_of_work_prover.verify(&mut channel, &proof).unwrap();
>     }
> ```

revert



_Code quote:_
```XML
    #[test]
    fn test_verify_proof_of_work_success() {
        let mut channel = Blake2sChannel::new(Blake2sHash::from(vec![0; 32]));
        let proof_of_work_prover = ProofOfWork { n_bits: 11 };
        let proof = ProofOfWorkProof { nonce: 133 };

        proof_of_work_prover.verify(&mut channel, &proof).unwrap();
    }
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/518)* status: 0 of 7 files reviewed, 8 unresolved discussions (waiting on @andrewmilson, @ohad-starkware, and @shaharsamocha7)

___
*[`src/commitment_scheme/blake2_hash.rs` line 67 at r4](https://reviewable.io/reviews/starkware-libs/stwo/518#-Ntkum27DOfjhV3Xp7H5:-Nto2ZEwByuLXAVF_mKG:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/b8b4d6b67b0e1656805301631e13e68d500f26f4/src/commitment_scheme/blake2_hash.rs#L67)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

used
</blockquote></details>

Done.
___
*[`src/commitment_scheme/blake2_hash.rs` line 71 at r4](https://reviewable.io/reviews/starkware-libs/stwo/518#-NtkvXUE8cuzmvGIbED0:-Nto2Slu2fNxoS2_MTm8:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/b8b4d6b67b0e1656805301631e13e68d500f26f4/src/commitment_scheme/blake2_hash.rs#L71)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

We should do finialize for the channel hash.
Only the merkle can reduce it
</blockquote></details>

Done.
___
*[`src/commitment_scheme/blake2_hash.rs` line 73 at r4](https://reviewable.io/reviews/starkware-libs/stwo/518#-NtkvnCVDBEWtv_2cf3j:-Nto2TFNEKGDwzbkypsy:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/b8b4d6b67b0e1656805301631e13e68d500f26f4/src/commitment_scheme/blake2_hash.rs#L73)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Document that this is double than the state size.
</blockquote></details>

Done.
___
*[`src/commitment_scheme/hasher.rs` line 81 at r4](https://reviewable.io/reviews/starkware-libs/stwo/518#-NtkwsuYCA7qdtkmKSVa:-Nto2VVf4hVWpjncNdi3:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/b8b4d6b67b0e1656805301631e13e68d500f26f4/src/commitment_scheme/hasher.rs#L81)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

revert
</blockquote></details>

Done.
___
*[`src/core/proof_of_work.rs` line 106 at r4](https://reviewable.io/reviews/starkware-libs/stwo/518#-NtkwxNY-WZKhRSaZmKy:-Nto2Xo5BT9uAPnVlsSP:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/20412e4a9f00507d771f24d66e4dbd59d0c66849/src/core/proof_of_work.rs#L106)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

revert
</blockquote></details>

Done.

**Review by shaharsamocha7 — COMMENTED** [review]
> Reviewed 1 of 5 files at r2, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/518)* status: 4 of 7 files reviewed, 8 unresolved discussions (waiting on @andrewmilson and @ohad-starkware)

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/518)* status: 5 of 7 files reviewed, 6 unresolved discussions (waiting on @andrewmilson, @ohad-starkware, and @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo/518#-Ntohauv6_lmHdCfUdYq:-Ntohauv6_lmHdCfUdYr:b-z8gy5v) (no related file):*
move this logic to avx_backend

___
___
*[`src/commitment_scheme/blake2s_avx.rs` line 179 at r5](https://reviewable.io/reviews/starkware-libs/stwo/518#-NtohGItBuNbMdnNLQ59:-NtohGItBuNbMdnNLQ5A:b-gia70j) ([raw file](https://github.com/starkware-libs/stwo/blob/884140b3a6f777686a2a634a20b7a9f312884878/src/commitment_scheme/blake2s_avx.rs#L179)):*
> ```XML
> }
> 
> const EVENS_CONCAT_EVENS: __m512i = unsafe {
> ```

Can this be unified with the fft into transpose_utils?



_Code quote:_
```XML
const EVENS_CONCAT_EVENS: __m512i = unsafe {
```
___
*[`src/commitment_scheme/blake2s_avx.rs` line 209 at r5](https://reviewable.io/reviews/starkware-libs/stwo/518#-Ntohm3Q6Q9UTrQzVyYo:-Ntohm3Q6Q9UTrQzVyYp:b-a94t7x) ([raw file](https://github.com/starkware-libs/stwo/blob/884140b3a6f777686a2a634a20b7a9f312884878/src/commitment_scheme/blake2s_avx.rs#L209)):*
> ```XML
> /// # Safety
> pub unsafe fn transpose_msgs(mut data: [__m512i; 16]) -> [__m512i; 16] {
>     // Transpose by applying 4 times the index permutation:
> ```

applying 4 times rotr(index, 1)
Maybe write the result of applying that 4 times



_Code quote:_
```XML
// Transpose by applying 4 times the index permutation:
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/518)* status: 5 of 7 files reviewed, 6 unresolved discussions (waiting on @andrewmilson, @ohad-starkware, and @shaharsamocha7)

*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo/518#-Ntohauv6_lmHdCfUdYq:-NtosMR-1MzocxDZLl0Y:b-896fix) (no related file):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

move this logic to avx_backend
</blockquote></details>

Done.

___
___
*[`src/commitment_scheme/blake2s_avx.rs` line 179 at r5](https://reviewable.io/reviews/starkware-libs/stwo/518#-NtohGItBuNbMdnNLQ59:-NtoscPmBvx4mfobQ2DK:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/884140b3a6f777686a2a634a20b7a9f312884878/src/commitment_scheme/blake2s_avx.rs#L179)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can this be unified with the fft into transpose_utils?
</blockquote></details>

Done.
___
*[`src/commitment_scheme/blake2s_avx.rs` line 209 at r5](https://reviewable.io/reviews/starkware-libs/stwo/518#-Ntohm3Q6Q9UTrQzVyYo:-NtotriI7Ev88_gUiOUr:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/884140b3a6f777686a2a634a20b7a9f312884878/src/commitment_scheme/blake2s_avx.rs#L209)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

applying 4 times rotr(index, 1)
Maybe write the result of applying that 4 times
</blockquote></details>

Done.

**Comment by shaharsamocha7** [comment]
*[`src/core/backend/avx512/blake2s_avx.rs` line 190 at r6](https://reviewable.io/reviews/starkware-libs/stwo/518#-NtpHp2N03UTZZCyIOtN:-NtpHp2N03UTZZCyIOtO:b82i04d) ([raw file](https://github.com/starkware-libs/stwo/blob/ec5d9d8b04393789a24c18cc8f7ce9f8cafba88b/src/core/backend/avx512/blake2s_avx.rs#L190)):*
> ```XML
>     //   abcd:0123 => 3abc:d012
>     // where abcd:0123 denotes that 0b 0123 word in the 0b abcd chunk.
>     // In other words, rotate the index to the right by 1.
> ```

Each _m512i chunk contains 16 u32 words.
Index abcd:xyzw, refers to a specific word in data as follows:
abcd - chunk index (in base 2)
xyzw - word offset (in base 2)



_Code quote:_
```XML
    // Transpose by applying 4 times the index permutation:
    //   abcd:0123 => 3abc:d012
    // where abcd:0123 denotes that 0b 0123 word in the 0b abcd chunk.
    // In other words, rotate the index to the right by 1.
```

**Review by shaharsamocha7 — APPROVED** [review]
> Reviewed 1 of 3 files at r4, 4 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/518)* status: 9 of 10 files reviewed, 4 unresolved discussions (waiting on @andrewmilson, @ohad-starkware, and @spapinistarkware)

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/518#-:-Ntpz-6X-Y7IxOEFiODo:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @andrewmilson and @ohad-starkware)

**Pull request merged**
