### PR TITLE
Test secure field circle gen

### PR DESCRIPTION
**Pull request by shaharsamocha7**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/452)

### CODE REVIEW

**Comment by shaharsamocha7** [comment]
* **#452** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/452?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @shaharsamocha7 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/452)* status: all files reviewed, 4 unresolved discussions (waiting on @shaharsamocha7)

___
*[`src/core/circle.rs` line 527 at r1](https://reviewable.io/reviews/starkware-libs/stwo/452#-NsbzNJGCldFs-On-3RV:-NsbzNJGCldFs-On-3RW:b-tzoxb9) ([raw file](https://github.com/starkware-libs/stwo/blob/dd87e0bf281dbb7d2aac8f07b1abf4f5a3f034e9/src/core/circle.rs#L527)):*
> ```XML
> 
>     #[test]
>     pub fn test_secure_field_circle_gen() {
> ```

Maybe we should also check that the point is on the circle?
```
assert_eq!(
            SECURE_FIELD_CIRCLE_GEN.x.square() + SECURE_FIELD_CIRCLE_GEN.y.square(),
            QM31::one()
        );
```
___
*[`src/core/circle.rs` line 528 at r1](https://reviewable.io/reviews/starkware-libs/stwo/452#-Nsbxsjg11lbtsDas33v:-Nsbxsjg11lbtsDas33w:bgby1yb) ([raw file](https://github.com/starkware-libs/stwo/blob/dd87e0bf281dbb7d2aac8f07b1abf4f5a3f034e9/src/core/circle.rs#L528)):*
> ```XML
>     #[test]
>     pub fn test_secure_field_circle_gen() {
>         let prime_factors = [
> ```

Do we want to check these are indeed prime?
___
*[`src/core/circle.rs` line 544 at r1](https://reviewable.io/reviews/starkware-libs/stwo/452#-NsbxS5P02W_vgmL72U2:-NsbxS5P02W_vgmL72U3:buy9fba) ([raw file](https://github.com/starkware-libs/stwo/blob/dd87e0bf281dbb7d2aac8f07b1abf4f5a3f034e9/src/core/circle.rs#L544)):*
> ```XML
>             x: SecureField::one(),
>             y: SecureField::zero(),
>         };
> ```

Is this called one or zero?



_Suggestion:_
```XML
        let circle_one = CirclePoint::zero();
```
___
*[`src/core/circle.rs` line 555 at r1](https://reviewable.io/reviews/starkware-libs/stwo/452#-NsbwYhVAvPUeq8zuQfI:-NsbwYhVAvPUeq8zuQfJ:b-bwql1p) ([raw file](https://github.com/starkware-libs/stwo/blob/dd87e0bf281dbb7d2aac8f07b1abf4f5a3f034e9/src/core/circle.rs#L555)):*
> ```XML
>         assert_eq!(SECURE_FIELD_CIRCLE_GEN.mul(P4 - 1), circle_one);
>         for (p, _) in prime_factors.iter() {
>             assert_ne!(SECURE_FIELD_CIRCLE_GEN.mul(*p - 1), circle_one);
> ```

This is the check you need to do:



_Suggestion:_
```XML
assert_ne!(SECURE_FIELD_CIRCLE_GEN.mul((P4 - 1) / p), circle_one);
```

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/452)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @alonh5)

___
*[`src/core/circle.rs` line 527 at r1](https://reviewable.io/reviews/starkware-libs/stwo/452#-NsbzNJGCldFs-On-3RV:-NscNLcg1mEMpbdWKH-P:bo1yulf) ([raw file](https://github.com/starkware-libs/stwo/blob/dd87e0bf281dbb7d2aac8f07b1abf4f5a3f034e9/src/core/circle.rs#L527)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Maybe we should also check that the point is on the circle?
```
assert_eq!(
            SECURE_FIELD_CIRCLE_GEN.x.square() + SECURE_FIELD_CIRCLE_GEN.y.square(),
            QM31::one()
        );
```
</blockquote></details>

This is inheret because the circle is a group, don't think that it is relevant for this test.
___
*[`src/core/circle.rs` line 528 at r1](https://reviewable.io/reviews/starkware-libs/stwo/452#-Nsbxsjg11lbtsDas33v:-NscNOXx2ue5E9BxK99w:b6bczll) ([raw file](https://github.com/starkware-libs/stwo/blob/dd87e0bf281dbb7d2aac8f07b1abf4f5a3f034e9/src/core/circle.rs#L528)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Do we want to check these are indeed prime?
</blockquote></details>

This check is too heavy and I think that if one want to be convinced of that he can check it offline.
WDYT?
___
*[`src/core/circle.rs` line 555 at r1](https://reviewable.io/reviews/starkware-libs/stwo/452#-NsbwYhVAvPUeq8zuQfI:-NscOOdQ1xMK2oDaeW3Q:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/dd87e0bf281dbb7d2aac8f07b1abf4f5a3f034e9/src/core/circle.rs#L555)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

This is the check you need to do:
</blockquote></details>

Done.

**Review by alonh5 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/452)* status: all files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7)

___
*[`src/core/circle.rs` line 527 at r1](https://reviewable.io/reviews/starkware-libs/stwo/452#-NsbzNJGCldFs-On-3RV:-NscXPzGCN5bPav7AuMq:b-ow9yma) ([raw file](https://github.com/starkware-libs/stwo/blob/dd87e0bf281dbb7d2aac8f07b1abf4f5a3f034e9/src/core/circle.rs#L527)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

This is inheret because the circle is a group, don't think that it is relevant for this test.
</blockquote></details>

If we change the `SECURE_FIELD_CIRCLE_GEN` it could be off the circle, because it's hard coded and unchecked.
___
*[`src/core/circle.rs` line 528 at r1](https://reviewable.io/reviews/starkware-libs/stwo/452#-Nsbxsjg11lbtsDas33v:-NscYNcg0ArT213XEY4v:bxamu25) ([raw file](https://github.com/starkware-libs/stwo/blob/dd87e0bf281dbb7d2aac8f07b1abf4f5a3f034e9/src/core/circle.rs#L528)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

This check is too heavy and I think that if one want to be convinced of that he can check it offline.
WDYT?
</blockquote></details>

We can have this test only run on nightly if it takes too long.
If we want it to be sound then we need this (and to check that the point is on the circle), but I'm not sure how important it is.
What is the test for?

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/452)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`src/core/circle.rs` line 528 at r1](https://reviewable.io/reviews/starkware-libs/stwo/452#-Nsbxsjg11lbtsDas33v:-Nsca5zC9jq7TEZ2DvnE:b3f34ev) ([raw file](https://github.com/starkware-libs/stwo/blob/dd87e0bf281dbb7d2aac8f07b1abf4f5a3f034e9/src/core/circle.rs#L528)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

We can have this test only run on nightly if it takes too long.
If we want it to be sound then we need this (and to check that the point is on the circle), but I'm not sure how important it is.
What is the test for?
</blockquote></details>

To be sure that our circle point generates all the points.
I was asked about that and I didn't remember what we checked when we generated this.

I still don't think that the prime elements are important to check, they shouldn't change at all.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/452#-:-Nsci_9D96I1u_RS1tie:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`src/core/circle.rs` line 528 at r1](https://reviewable.io/reviews/starkware-libs/stwo/452#-Nsbxsjg11lbtsDas33v:-NschJ_97EYUaOPs6ARu:b-dugtg7) ([raw file](https://github.com/starkware-libs/stwo/blob/dd87e0bf281dbb7d2aac8f07b1abf4f5a3f034e9/src/core/circle.rs#L528)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

To be sure that our circle point generates all the points.
I was asked about that and I didn't remember what we checked when we generated this.

I still don't think that the prime elements are important to check, they shouldn't change at all.
</blockquote></details>

Okay, NP. (just note that without that check it doesn't show that necessarily).

**Pull request merged**
