### PR TITLE
Constraint accumulator precompute random coeff powers

### PR DESCRIPTION
**Pull request by shaharsamocha7**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/554)

### CODE REVIEW

**Comment by shaharsamocha7** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/554?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#554** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/554?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#553** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/553?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @shaharsamocha7 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/554)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

___
*[`src/core/air/accumulation.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/stwo/554#-Nu5A0NI2047WajYyHLW:-Nu5A0NJ6UmeJB49qvgS:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/617fa88cee0efd6f056c4580ae3adfcf683f5bc4/src/core/air/accumulation.rs#L82)):*
> ```XML
>     /// `random_coeff` should be a secure random field element, drawn from the channel.
>     /// `max_log_size` is the maximum log_size of the accumulated evaluations.
>     pub fn new(random_coeff: SecureField, max_log_size: u32, total_columns: usize) -> Self {
> ```





_Suggestion:_
```XML
otal_constraints
```
___
*[`src/examples/wide_fibonacci/constraint_eval.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/stwo/554#-Nu5ATk_-dvcSo3Gcj_K:-Nu5ATk_-dvcSo3Gcj_L:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/617fa88cee0efd6f056c4580ae3adfcf683f5bc4/src/examples/wide_fibonacci/constraint_eval.rs#L18)):*
> ```XML
> impl Component<CPUBackend> for WideFibComponent {
>     fn n_constraints(&self) -> usize {
>         62
> ```





_Suggestion:_
```XML
252
```

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/554)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/554)* status: 3 of 9 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @spapinistarkware)

___
*[`src/examples/wide_fibonacci/constraint_eval.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/stwo/554#-Nu5ATk_-dvcSo3Gcj_K:-NuION1061n5yc66KSM9:b36kegi) ([raw file](https://github.com/starkware-libs/stwo/blob/617fa88cee0efd6f056c4580ae3adfcf683f5bc4/src/examples/wide_fibonacci/constraint_eval.rs#L18)):*
> ```XML
> impl Component<CPUBackend> for WideFibComponent {
>     fn n_constraints(&self) -> usize {
>         62
> ```

Done.
Tests are passing with 62, does it fail on avx512?

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/554)* status: 3 of 9 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @spapinistarkware)

___
*[`src/core/air/accumulation.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/stwo/554#-Nu5A0NI2047WajYyHLW:-NuIPFXcDghBE0HRmNsq:b-m2h10u) ([raw file](https://github.com/starkware-libs/stwo/blob/617fa88cee0efd6f056c4580ae3adfcf683f5bc4/src/core/air/accumulation.rs#L82)):*
> ```XML
>     /// `random_coeff` should be a secure random field element, drawn from the channel.
>     /// `max_log_size` is the maximum log_size of the accumulated evaluations.
>     pub fn new(random_coeff: SecureField, max_log_size: u32, total_columns: usize) -> Self {
> ```

I'm considering to renaming everything here to constraints instead of columns, WDYT?

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/554)* status: 2 of 9 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @spapinistarkware)

___
*[`src/examples/wide_fibonacci/constraint_eval.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/stwo/554#-Nu5ATk_-dvcSo3Gcj_K:-NuKUykW2Wak4XNuqmCm:bn849nk) ([raw file](https://github.com/starkware-libs/stwo/blob/617fa88cee0efd6f056c4580ae3adfcf683f5bc4/src/examples/wide_fibonacci/constraint_eval.rs#L18)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Done.
Tests are passing with 62, does it fail on avx512?
</blockquote></details>

I'll change it to 252 in a pr that changes the wide fib code.

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/554)* status: 2 of 9 files reviewed, 3 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

___
*[`src/core/utils.rs` line 46 at r3](https://reviewable.io/reviews/starkware-libs/stwo/554#-NuSUpB0CqvL7fOsiC3F:-NuSUpB12go-ohqlh_sj:bib2fca) ([raw file](https://github.com/starkware-libs/stwo/blob/eafac5e50680346b08e8f075460d3f351c1d4270/src/core/utils.rs#L46)):*
> ```XML
> pub fn generate_secure_powers(felt: SecureField, n_powers: usize) -> Vec<SecureField> {
>     let mut res = vec![];
>     for _ in 0..min(1, n_powers) {
> ```

Put in prev PR

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/554)* status: 2 of 9 files reviewed, 4 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

___
*[`src/core/air/accumulation.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/stwo/554#-Nu5A0NI2047WajYyHLW:-NuSmogBDPE940L0mhQl:b2nhswy) ([raw file](https://github.com/starkware-libs/stwo/blob/617fa88cee0efd6f056c4580ae3adfcf683f5bc4/src/core/air/accumulation.rs#L82)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I'm considering to renaming everything here to constraints instead of columns, WDYT?
</blockquote></details>

Yes
___
*[`src/core/air/accumulation.rs` line 50 at r3](https://reviewable.io/reviews/starkware-libs/stwo/554#-NuSmVNKBW_9XTDNDC4g:-NuSmVNKBW_9XTDNDC4h:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/eafac5e50680346b08e8f075460d3f351c1d4270/src/core/air/accumulation.rs#L50)):*
> ```XML
>     /// Accumulated evaluations for each log_size.
>     /// Each `sub_accumulation` holds `sum_{i=0}^{N-1} evaluation_i * alpha^(N - 1 - i)`
>     /// for all the evaluation for this log size and `N` is the total number of evaluations.
> ```





_Suggestion:_
```XML
    /// Each `sub_accumulation` holds the sum over all columns i of that log_size, of
    /// `evaluation_i * alpha^(N - 1 - i)`
    /// where `N` is the total number of evaluations.
```

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/554)* status: 2 of 9 files reviewed, 4 unresolved discussions (waiting on @alonh5 and @spapinistarkware)

___
*[`src/core/air/accumulation.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/stwo/554#-Nu5A0NI2047WajYyHLW:-NuSzzOSBS14QNsoHaQ5:b-7yd1q4) ([raw file](https://github.com/starkware-libs/stwo/blob/617fa88cee0efd6f056c4580ae3adfcf683f5bc4/src/core/air/accumulation.rs#L82)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Yes
</blockquote></details>

Added a TODO.
___
*[`src/core/air/accumulation.rs` line 50 at r3](https://reviewable.io/reviews/starkware-libs/stwo/554#-NuSmVNKBW_9XTDNDC4g:-NuSzTbF1g9ymvpJL_qq:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/eafac5e50680346b08e8f075460d3f351c1d4270/src/core/air/accumulation.rs#L50)):*
> ```XML
>     /// Accumulated evaluations for each log_size.
>     /// Each `sub_accumulation` holds `sum_{i=0}^{N-1} evaluation_i * alpha^(N - 1 - i)`
>     /// for all the evaluation for this log size and `N` is the total number of evaluations.
> ```

Done.
___
*[`src/core/utils.rs` line 46 at r3](https://reviewable.io/reviews/starkware-libs/stwo/554#-NuSUpB0CqvL7fOsiC3F:-NuSyXwT7Ax28e1qSDnp:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/eafac5e50680346b08e8f075460d3f351c1d4270/src/core/utils.rs#L46)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Put in prev PR
</blockquote></details>

Done.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 6 files at r2, 2 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/554#-:-NuTSsU18CgcFIGZkBPG:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/554#-:-NuXhCoX3b-4ByoBMpj0:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Comment by shaharsamocha7** [comment]
### Merge activity

* **Apr 3, 3:03 AM EDT**: @shaharsamocha7 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/554).

**Pull request merged**
