### PR TITLE
Dumb down FRI

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/529)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/529?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#531** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/531?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#530** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/530?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#529** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/529?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#528** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/528?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#527** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/527?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#526** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/526?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#525** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/525?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#518** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/518?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by andrewmilson — APPROVED** [review]
:lgtm:

> Reviewed 1 of 10 files at r1, 3 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/529#-:-Ntp6OCV3BNxvWapWz36:bnfp4nl)* status: 4 of 13 files reviewed, all discussions resolved

**Review by andrewmilson — APPROVED** [review]
:lgtm:

> Reviewed 1 of 10 files at r1, 1 of 7 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/529#-:-Ntt8BIr6ah5ZcVEf5Df:bnfp4nl)* status: 6 of 13 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`src/core/backend/cpu/mod.rs` line 51 at r3](https://reviewable.io/reviews/starkware-libs/stwo/529#-Ntt5Gff9r4_hu_GfUmE:-Ntt5Gff9r4_hu_GfUmF:bfd6rvb) ([raw file](https://github.com/starkware-libs/stwo/blob/9ab528554359bb76214a926a4deb88d9bd4a3011/src/core/backend/cpu/mod.rs#L51)):*
> ```XML
> pub type CPUCirclePoly = CirclePoly<CPUBackend>;
> pub type CPUCircleEvaluation<F, EvalOrder> = CircleEvaluation<CPUBackend, F, EvalOrder>;
> // TODO(spapini): Remove the EvalOrder on LineEvaluation.
> ```

Should the `TODO` be removed now?

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/529)* status: 6 of 13 files reviewed, 1 unresolved discussion (waiting on @andrewmilson)

___
*[`src/core/backend/cpu/mod.rs` line 51 at r3](https://reviewable.io/reviews/starkware-libs/stwo/529#-Ntt5Gff9r4_hu_GfUmE:-NttSFv4-UtFvBTwDFOe:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/9ab528554359bb76214a926a4deb88d9bd4a3011/src/core/backend/cpu/mod.rs#L51)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Should the `TODO` be removed now?
</blockquote></details>

Done.

**Review by andrewmilson — APPROVED** [review]
:lgtm:

> Reviewed 2 of 10 files at r1, 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/529#-:-NtxvgSV0nFBtUHXsfsv:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by andrewmilson — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/529)* status: 13 of 14 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`src/core/commitment_scheme/verifier.rs` line 103 at r5](https://reviewable.io/reviews/starkware-libs/stwo/529#-Nu2WZheEdhqeuuAvtFo:-Nu2WZheEdhqeuuAvtFp:bgxskj3) ([raw file](https://github.com/starkware-libs/stwo/blob/2c85fba83b281eb5898a20ad1a750fcb179f640f/src/core/commitment_scheme/verifier.rs#L103)):*
> ```XML
>                 tree.verify(queries, queried_values, decommitment)
>             })
>             .0
> ```

What is this value?

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/529)* status: 8 of 14 files reviewed, 1 unresolved discussion (waiting on @andrewmilson)

___
*[`src/core/commitment_scheme/verifier.rs` line 103 at r5](https://reviewable.io/reviews/starkware-libs/stwo/529#-Nu2WZheEdhqeuuAvtFo:-NuTZSgU-TCzbUzHil9A:b-t74bso) ([raw file](https://github.com/starkware-libs/stwo/blob/2c85fba83b281eb5898a20ad1a750fcb179f640f/src/core/commitment_scheme/verifier.rs#L103)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

What is this value?
</blockquote></details>

It's a TreeVec. .0 accesses the inner Vec.

**Review by andrewmilson — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r5, 5 of 5 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/529#-:-NuX8koeD8ZXeHFb4eSu:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @spapinistarkware)

**Review by andrewmilson — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/529#-:-NuY5FQJ-e7NBccTIDrF:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Comment by spapinistarkware** [comment]
### Merge activity

* **Apr 3, 7:16 AM EDT**: [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/529) rebased this pull request as part of a merge.

**Pull request merged**
