### PR TITLE
Modify mask_points for interaction.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/639)

### CODE REVIEW

**Comment by alonh5** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/639?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#639** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/639?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#638** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/638?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#637** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/637?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#636** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/636?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#634** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/634?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#633** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/633?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#631** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/631?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#582** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/582?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#589](https://github.com/starkware-libs/stwo/pull/589) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/589?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#573** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/573?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#574](https://github.com/starkware-libs/stwo/pull/574) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/574?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#572** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/572?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#562** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/562?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/639)* status: 1 of 7 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @andrewmilson)

___
*[`crates/prover/src/core/air/mod.rs` line 59 at r3](https://reviewable.io/reviews/starkware-libs/stwo/639#-O03HzW97gAdVO8nBY_w:-O03HzW97gAdVO8nBY_x:b-oy0ien) ([raw file](https://github.com/starkware-libs/stwo/blob/cc969160fb5721dfbe30ccd73c836d236275755a/crates/prover/src/core/air/mod.rs#L59)):*
> ```XML
>     fn trace_log_degree_bounds(&self) -> TreeVec<ColumnVec<u32>>;
> 
>     fn mask_points(
> ```

Document.
Should this TreeVec be of size n_interaction_phases?



_Code quote:_
```XML
fn mask_points(
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/639)* status: 1 of 7 files reviewed, 1 unresolved discussion (waiting on @andrewmilson and @shaharsamocha7)

___
*[`crates/prover/src/core/air/mod.rs` line 59 at r3](https://reviewable.io/reviews/starkware-libs/stwo/639#-O03HzW97gAdVO8nBY_w:-O03OAfuD5OhZj77sNrr:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/cc969160fb5721dfbe30ccd73c836d236275755a/crates/prover/src/core/air/mod.rs#L59)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Document.
Should this TreeVec be of size n_interaction_phases?
</blockquote></details>

Done.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/639)* status: 2 of 7 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @andrewmilson)

___
*[`crates/prover/src/core/air/air_ext.rs` line 48 at r4](https://reviewable.io/reviews/starkware-libs/stwo/639#-O049mPICJlZNPfOgDxo:-O049mPICJlZNPfOgDxp:bpd235c) ([raw file](https://github.com/starkware-libs/stwo/blob/7443767851b0941fc2b8f6e49f79e4dfae54a15f/crates/prover/src/core/air/air_ext.rs#L48)):*
> ```XML
>         {
>             points.push(interaction_component_points);
>         }
> ```

Why not just return empty vec if there are not interaction traces?



_Code quote:_
```XML
        if !interaction_component_points
            .iter()
            .all(|column| column.is_empty())
        {
            points.push(interaction_component_points);
        }
```

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/639)* status: 2 of 7 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @andrewmilson)

___
*[`crates/prover/src/core/prover/mod.rs` line 119 at r4](https://reviewable.io/reviews/starkware-libs/stwo/639#-O04AK_j5MGXXZLPmcZ_:-O04AK_j5MGXXZLPmcZa:b8fi5w9) ([raw file](https://github.com/starkware-libs/stwo/blob/7443767851b0941fc2b8f6e49f79e4dfae54a15f/crates/prover/src/core/prover/mod.rs#L119)):*
> ```XML
> 
>     // Get composition polynomial sample points.
>     sample_points.push(vec![vec![oods_point]; 4]);
> ```

Maybe this could be also part of the mask_points in air_ext?



_Code quote:_
```XML
sample_points.push(vec![vec![oods_point]; 4]);
```

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/639)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @alonh5 and @andrewmilson)

___
*[`crates/prover/src/core/prover/mod.rs` line 281 at r4](https://reviewable.io/reviews/starkware-libs/stwo/639#-O04AdzAB-x0A3f_FlQf:-O04AdzB3CvLk4oxNe--:bwwakyt) ([raw file](https://github.com/starkware-libs/stwo/blob/7443767851b0941fc2b8f6e49f79e4dfae54a15f/crates/prover/src/core/prover/mod.rs#L281)):*
> ```XML
>                 values.extend(
>                     interaction_values
>                         .take(component.mask_points(CirclePoint::zero())[1].len())
> ```

can you put that in a variable? n_interaction_columns?



_Code quote:_
```XML
component.mask_points(CirclePoint::zero())[1].len()
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/639)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`crates/prover/src/core/air/air_ext.rs` line 48 at r4](https://reviewable.io/reviews/starkware-libs/stwo/639#-O049mPICJlZNPfOgDxo:-O04DvXp1NdSB_7rZ5Ob:b-42pogw) ([raw file](https://github.com/starkware-libs/stwo/blob/7443767851b0941fc2b8f6e49f79e4dfae54a15f/crates/prover/src/core/air/air_ext.rs#L48)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why not just return empty vec if there are not interaction traces?
</blockquote></details>

Then in `prove_values()` the structure of the polynomials committed on and the sampled point won't match in case there was any interaction. We can either add an empty tree to the commitment scheme or remove that empty sampled points element as is done now. WDYT?
___
*[`crates/prover/src/core/prover/mod.rs` line 119 at r4](https://reviewable.io/reviews/starkware-libs/stwo/639#-O04AK_j5MGXXZLPmcZ_:-O04CLmuEUSFRUcBYQyO:b-6ffqqm) ([raw file](https://github.com/starkware-libs/stwo/blob/7443767851b0941fc2b8f6e49f79e4dfae54a15f/crates/prover/src/core/prover/mod.rs#L119)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Maybe this could be also part of the mask_points in air_ext?
</blockquote></details>

Great idea, thanks.
___
*[`crates/prover/src/core/prover/mod.rs` line 281 at r4](https://reviewable.io/reviews/starkware-libs/stwo/639#-O04AdzAB-x0A3f_FlQf:-O04Bmyn5xW6CH7pS6KD:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/7443767851b0941fc2b8f6e49f79e4dfae54a15f/crates/prover/src/core/prover/mod.rs#L281)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

can you put that in a variable? n_interaction_columns?
</blockquote></details>

Done.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/639#-:-O04Wiu65_ZTHSaMfzf0:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @andrewmilson)

**Pull request merged**
