### PR TITLE
Create MLE eval verifier component

### PR DESCRIPTION
**Pull request by andrewmilson**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/805)

### CODE REVIEW

**Comment by andrewmilson** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/805?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#805** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/805?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#804** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/804?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#803** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/803?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#802** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/802?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#801** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/801?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#800** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/800?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#799** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/799?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#798** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/798?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @andrewmilson and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/805)* status: all files reviewed, 1 unresolved discussion (waiting on @andrewmilson and @spapinistarkware)

___
*[`crates/prover/src/examples/xor/gkr_lookups/mle_eval.rs` line 356 at r2](https://reviewable.io/reviews/starkware-libs/stwo/805#-O7P7p_F2rBZFSt9NF_5:-O7P7p_F2rBZFSt9NF_6:b2s0t5j) ([raw file](https://github.com/starkware-libs/stwo/blob/14eb2a202d78c83c5ccf22a5e11b51979f86e85f/crates/prover/src/examples/xor/gkr_lookups/mle_eval.rs#L356)):*
> ```XML
>         let mle_coeff_col_eval = self.mle_coeff_column_oracle.evaluate_at_point(point, mask);
>         let carry_quotients_col_eval = eval_carry_quotient_col(&self.mle_eval_point, point);
>         let is_first = eval_is_first(trace_coset, point);
> ```

Should we use this succinct version instead of committing to the is_first column in the constant tree?



_Code quote:_
```XML
eval_is_first(trace_coset, point)
```

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/805)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/examples/xor/gkr_lookups/mle_eval.rs` line 356 at r2](https://reviewable.io/reviews/starkware-libs/stwo/805#-O7P7p_F2rBZFSt9NF_5:-O7WdtMb3s1nLMl4Pa7c:busybtt) ([raw file](https://github.com/starkware-libs/stwo/blob/14eb2a202d78c83c5ccf22a5e11b51979f86e85f/crates/prover/src/examples/xor/gkr_lookups/mle_eval.rs#L356)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Should we use this succinct version instead of committing to the is_first column in the constant tree?
</blockquote></details>

We could. I remember ShaharP mentioning he thought constant column might be more efficient for the verifier. Not sure if this is just Bitcoin case or all cases

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/805#-:-O7icY_J2KJ6Wz3bTOVu:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @andrewmilson and @spapinistarkware)

___
*[`crates/prover/src/examples/xor/gkr_lookups/mle_eval.rs` line 356 at r2](https://reviewable.io/reviews/starkware-libs/stwo/805#-O7P7p_F2rBZFSt9NF_5:-O7ic8zBAbR39syLCCVM:b8mg3z1) ([raw file](https://github.com/starkware-libs/stwo/blob/14eb2a202d78c83c5ccf22a5e11b51979f86e85f/crates/prover/src/examples/xor/gkr_lookups/mle_eval.rs#L356)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

We could. I remember ShaharP mentioning he thought constant column might be more efficient for the verifier. Not sure if this is just Bitcoin case or all cases
</blockquote></details>

`coset_vanishing(coset, p) / (point_vanishing(coset.initial, p) * BaseField::from(1 << coset.log_size))`

Maybe it is because of the inverse but I guess that we can implement it efficiently using a hint.

**Pull request merged**
