### PR TITLE
iterable trace

### PR DESCRIPTION
**Pull request by ohad-starkware**

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/air_utils/src/trace/iterable_trace.rs` line 114 at r2](https://reviewable.io/reviews/starkware-libs/stwo/942#-OErWDTj4LCG0CP5XiqL:-OErWDTj4LCG0CP5XiqM:b8b25vt) ([raw file](https://github.com/starkware-libs/stwo/blob/a58b4caae4c58fbcdf35a5bfeffd687d54b4c16e/crates/air_utils/src/trace/iterable_trace.rs#L114)):*
> ```XML
> 
> pub struct RowIterMut<'trace, const N: usize> {
>     v: [*mut [PackedM31]; N],
> ```

Why not?



_Suggestion:_
```XML
  v: [&'trace mut [PackedM31]; N],
```

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/air_utils/src/trace/iterable_trace.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/stwo/942#-OErZzE86vngLXm63NZD:-OErZzE86vngLXm63NZE:b-7b62gz) ([raw file](https://github.com/starkware-libs/stwo/blob/a58b4caae4c58fbcdf35a5bfeffd687d54b4c16e/crates/air_utils/src/trace/iterable_trace.rs#L13)):*
> ```XML
> /// A 2D Matrix of [`PackedM31`] values.
> /// Used for generating the witness of 'Stwo' proofs.
> /// Stored in column-major order, exposes a vectorized iterator over rows.
> ```

The concept of "column-major" or "row-major" storage refers to how data is laid out in **contiguous memory** for a matrix. If each column in a matrix is stored in a separate vector, the storage pattern no longer strictly adheres to the conventional definition of column-major or row-major because the matrix isn't stored as a single contiguous block of memory.



_Code quote:_
```XML
column-major
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 3 of 6 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/942)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @ohad-starkware and @shaharsamocha7)

**Comment by ilyalesokhin-starkware** [comment]
*[`crates/air_utils/src/trace/iterable_trace.rs` line 49 at r2](https://reviewable.io/reviews/starkware-libs/stwo/942#-OEr_q0V37bWqYMWjwrO:-OEr_q0V37bWqYMWjwrP:b-pbukim) ([raw file](https://github.com/starkware-libs/stwo/blob/a58b4caae4c58fbcdf35a5bfeffd687d54b4c16e/crates/air_utils/src/trace/iterable_trace.rs#L49)):*
> ```XML
> /// ```
> #[derive(Debug)]
> pub struct IterableTrace<const N: usize> {
> ```

I'm not happy with the name.

Maybe ComponentTrace?



_Code quote:_
```XML
 IterableTrace
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/942)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @shaharsamocha7)

___
*[`crates/air_utils/src/trace/iterable_trace.rs` line 114 at r2](https://reviewable.io/reviews/starkware-libs/stwo/942#-OErWDTj4LCG0CP5XiqL:-OEraW5v7DDSAujME9_-:b62pm2b) ([raw file](https://github.com/starkware-libs/stwo/blob/a58b4caae4c58fbcdf35a5bfeffd687d54b4c16e/crates/air_utils/src/trace/iterable_trace.rs#L114)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Why not?
</blockquote></details>

the borrow checker is mad with "captured variable cannot escape \`FnMut\` closure body"
I copied core::slice::iter::ChunksMut implementation https://doc.rust-lang.org/src/core/slice/iter.rs.html#1663
probably will implement get_unchecked soon

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/942)* status: all files reviewed, 10 unresolved discussions (waiting on @ilyalesokhin-starkware and @ohad-starkware)

___
*[`crates/air_utils/src/trace/iterable_trace.rs` line 52 at r2](https://reviewable.io/reviews/starkware-libs/stwo/942#-OErcAmE6FwH03dkd8TL:-OErcAmE6FwH03dkd8TM:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/a58b4caae4c58fbcdf35a5bfeffd687d54b4c16e/crates/air_utils/src/trace/iterable_trace.rs#L52)):*
> ```XML
>     data: [Vec<PackedM31>; N],
> 
>     /// Log number of M31 rows in each column.
> ```





_Suggestion:_
```XML
/// Log number of rows in each column.
```
___
*[`crates/air_utils/src/trace/iterable_trace.rs` line 59 at r2](https://reviewable.io/reviews/starkware-libs/stwo/942#-OErc5MG2zlROfdJBn8r:-OErc5MH4fjBBnxNY3FA:b-syss94) ([raw file](https://github.com/starkware-libs/stwo/blob/a58b4caae4c58fbcdf35a5bfeffd687d54b4c16e/crates/air_utils/src/trace/iterable_trace.rs#L59)):*
> ```XML
>     pub fn zeroed(log_size: u32) -> Self {
>         let length = 1 << log_size;
>         let n_simd_elems = length / N_LANES;
> ```

div_ceil



_Code quote:_
```XML
length / N_LANES
```
___
*[`crates/air_utils/src/trace/iterable_trace.rs` line 90 at r2](https://reviewable.io/reviews/starkware-libs/stwo/942#-OErcEa5Dt08q6xIyVdA:-OErcEa5Dt08q6xIyVdB:bx6gzwq) ([raw file](https://github.com/starkware-libs/stwo/blob/a58b4caae4c58fbcdf35a5bfeffd687d54b4c16e/crates/air_utils/src/trace/iterable_trace.rs#L90)):*
> ```XML
>     }
> 
>     pub fn pretty_print(&self, row_limit: usize) -> String {
> ```

I don't think this function belong to this pr



_Code quote:_
```XML
pub fn pretty_print(&self, row_limit: usize) -> String {
```
___
*[`crates/air_utils/src/trace/iterable_trace.rs` line 113 at r2](https://reviewable.io/reviews/starkware-libs/stwo/942#-OErcZKD3tkU61LKJ9Dj:-OErcZKD3tkU61LKJ9Dk:bqgiym9) ([raw file](https://github.com/starkware-libs/stwo/blob/a58b4caae4c58fbcdf35a5bfeffd687d54b4c16e/crates/air_utils/src/trace/iterable_trace.rs#L113)):*
> ```XML
> pub type MutRow<'trace, const N: usize> = [&'trace mut PackedM31; N];
> 
> pub struct RowIterMut<'trace, const N: usize> {
> ```

Document, and maybe rename N



_Suggestion:_
```XML
pub struct RowIterMut<'trace, const N_COLUMNS: usize> {
```
___
*[`crates/air_utils/src/trace/iterable_trace.rs` line 141 at r2](https://reviewable.io/reviews/starkware-libs/stwo/942#-OErgFNoEiisDNvmVy5J:-OErgFNoEiisDNvmVy5K:b-snqe43) ([raw file](https://github.com/starkware-libs/stwo/blob/a58b4caae4c58fbcdf35a5bfeffd687d54b4c16e/crates/air_utils/src/trace/iterable_trace.rs#L141)):*
> ```XML
>     }
> 
>     fn size_hint(&self) -> (usize, Option<usize>) {
> ```

Document (and maybe rename s.t. it'll be clear that this refer to column size)
Why this returns (len, some(len))? see 



_Suggestion:_
```XML
fn size_hint(&self) -> Option<usize> {
```
___
*[`crates/air_utils/src/trace/iterable_trace.rs` line 142 at r2](https://reviewable.io/reviews/starkware-libs/stwo/942#-OErgdYk0-Ldm_YcCuDK:-OErgdYk0-Ldm_YcCuDL:bcpwdqd) ([raw file](https://github.com/starkware-libs/stwo/blob/a58b4caae4c58fbcdf35a5bfeffd687d54b4c16e/crates/air_utils/src/trace/iterable_trace.rs#L142)):*
> ```XML
> 
>     fn size_hint(&self) -> (usize, Option<usize>) {
>         let len = self.v[0].len();
> ```

you should check that v is not empty, right?



_Code quote:_
```XML
let len = self.v[0].len();
```
___
*[`crates/air_utils/src/trace/iterable_trace.rs` line 149 at r2](https://reviewable.io/reviews/starkware-libs/stwo/942#-OErdInz0Wn7HxB9yTHO:-OErdInz0Wn7HxB9yTHP:b-it8ftn) ([raw file](https://github.com/starkware-libs/stwo/blob/a58b4caae4c58fbcdf35a5bfeffd687d54b4c16e/crates/air_utils/src/trace/iterable_trace.rs#L149)):*
> ```XML
> 
> #[cfg(test)]
> mod tests {
> ```

Do we need both the test and the doc test?



_Code quote:_
```XML
#[cfg(test)]
mod tests {
```

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/942)* status: all files reviewed, 10 unresolved discussions (waiting on @ilyalesokhin-starkware and @ohad-starkware)

___
*[`crates/air_utils/src/trace/iterable_trace.rs` line 149 at r2](https://reviewable.io/reviews/starkware-libs/stwo/942#-OErdInz0Wn7HxB9yTHO:-OErlZ9WCuWpjSSmgp52:bxk1kww) ([raw file](https://github.com/starkware-libs/stwo/blob/a58b4caae4c58fbcdf35a5bfeffd687d54b4c16e/crates/air_utils/src/trace/iterable_trace.rs#L149)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Do we need both the test and the doc test?
</blockquote></details>

You can keep it if this is going to be a parallel test, just write a TODO or rename so I know

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/942)* status: all files reviewed, 10 unresolved discussions (waiting on @ilyalesokhin-starkware and @shaharsamocha7)

___
*[`crates/air_utils/src/trace/iterable_trace.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/stwo/942#-OErZzE86vngLXm63NZD:-OErjsK3ErZJ2c47eQnY:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/a58b4caae4c58fbcdf35a5bfeffd687d54b4c16e/crates/air_utils/src/trace/iterable_trace.rs#L13)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

The concept of "column-major" or "row-major" storage refers to how data is laid out in **contiguous memory** for a matrix. If each column in a matrix is stored in a separate vector, the storage pattern no longer strictly adheres to the conventional definition of column-major or row-major because the matrix isn't stored as a single contiguous block of memory.
</blockquote></details>

Done.
___
*[`crates/air_utils/src/trace/iterable_trace.rs` line 49 at r2](https://reviewable.io/reviews/starkware-libs/stwo/942#-OEr_q0V37bWqYMWjwrO:-OErjubI2rReEbLsMHlL:bjcz4p1) ([raw file](https://github.com/starkware-libs/stwo/blob/a58b4caae4c58fbcdf35a5bfeffd687d54b4c16e/crates/air_utils/src/trace/iterable_trace.rs#L49)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I'm not happy with the name.

Maybe ComponentTrace?
</blockquote></details>

im not too happy with either
@shaharsamocha7 idea?
___
*[`crates/air_utils/src/trace/iterable_trace.rs` line 59 at r2](https://reviewable.io/reviews/starkware-libs/stwo/942#-OErc5MG2zlROfdJBn8r:-OErkIHm8rI_nsdNHJMd:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/a58b4caae4c58fbcdf35a5bfeffd687d54b4c16e/crates/air_utils/src/trace/iterable_trace.rs#L59)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

div_ceil
</blockquote></details>

Done.
___
*[`crates/air_utils/src/trace/iterable_trace.rs` line 90 at r2](https://reviewable.io/reviews/starkware-libs/stwo/942#-OErcEa5Dt08q6xIyVdA:-OErk_TjBvJlrIhnzDcZ:bc3v9e0) ([raw file](https://github.com/starkware-libs/stwo/blob/a58b4caae4c58fbcdf35a5bfeffd687d54b4c16e/crates/air_utils/src/trace/iterable_trace.rs#L90)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I don't think this function belong to this pr
</blockquote></details>

I do want to use something like that in doc test, wdyt about row_at?
___
*[`crates/air_utils/src/trace/iterable_trace.rs` line 113 at r2](https://reviewable.io/reviews/starkware-libs/stwo/942#-OErcZKD3tkU61LKJ9Dj:-OErn3y0Dh05mpZUkMgx:bz5pylw) ([raw file](https://github.com/starkware-libs/stwo/blob/a58b4caae4c58fbcdf35a5bfeffd687d54b4c16e/crates/air_utils/src/trace/iterable_trace.rs#L113)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Document, and maybe rename N
</blockquote></details>

documentad
im on the fence about renaming N, specified what is stands for in the trace doc. lmk if you think that's not clear
___
*[`crates/air_utils/src/trace/iterable_trace.rs` line 52 at r2](https://reviewable.io/reviews/starkware-libs/stwo/942#-OErcAmE6FwH03dkd8TL:-OErk2uBEsSXy_8kngP3:b3rxuxz) ([raw file](https://github.com/starkware-libs/stwo/blob/a58b4caae4c58fbcdf35a5bfeffd687d54b4c16e/crates/air_utils/src/trace/iterable_trace.rs#L52)):*
> ```XML
>     data: [Vec<PackedM31>; N],
> 
>     /// Log number of M31 rows in each column.
> ```

is it clear the the logsize refers to the non packed type?

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/942)* status: 5 of 6 files reviewed, 10 unresolved discussions (waiting on @ilyalesokhin-starkware and @shaharsamocha7)

___
*[`crates/air_utils/src/trace/iterable_trace.rs` line 141 at r2](https://reviewable.io/reviews/starkware-libs/stwo/942#-OErgFNoEiisDNvmVy5J:-OErobEL5j-JjrPYGppr:b-szkm3o) ([raw file](https://github.com/starkware-libs/stwo/blob/a58b4caae4c58fbcdf35a5bfeffd687d54b4c16e/crates/air_utils/src/trace/iterable_trace.rs#L141)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Document (and maybe rename s.t. it'll be clear that this refer to column size)
Why this returns (len, some(len))? see
</blockquote></details>

it's a trait implementation
https://doc.rust-lang.org/std/iter/trait.Iterator.html#:~:text=size_hint()%20is%20primarily%20intended,lead%20to%20memory%20safety%20violations.
___
*[`crates/air_utils/src/trace/iterable_trace.rs` line 142 at r2](https://reviewable.io/reviews/starkware-libs/stwo/942#-OErgdYk0-Ldm_YcCuDK:-OEroxGp1vy8GA1lgHvu:bv6e1zh) ([raw file](https://github.com/starkware-libs/stwo/blob/a58b4caae4c58fbcdf35a5bfeffd687d54b4c16e/crates/air_utils/src/trace/iterable_trace.rs#L142)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

you should check that v is not empty, right?
</blockquote></details>

0 is a valid length,
code is derived off of rayon's own implementations:
https://docs.rs/rayon/latest/src/rayon/iter/chunks.rs.html#187
___
*[`crates/air_utils/src/trace/iterable_trace.rs` line 149 at r2](https://reviewable.io/reviews/starkware-libs/stwo/942#-OErdInz0Wn7HxB9yTHO:-OErpPeCCATvexi4IJRl:bcdprmv) ([raw file](https://github.com/starkware-libs/stwo/blob/a58b4caae4c58fbcdf35a5bfeffd687d54b4c16e/crates/air_utils/src/trace/iterable_trace.rs#L149)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

You can keep it if this is going to be a parallel test, just write a TODO or rename so I know
</blockquote></details>

removed, parallel will get it's own test

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/942)* status: all files reviewed, 7 unresolved discussions (waiting on @ilyalesokhin-starkware and @ohad-starkware)

___
*[`crates/air_utils/src/trace/iterable_trace.rs` line 49 at r2](https://reviewable.io/reviews/starkware-libs/stwo/942#-OEr_q0V37bWqYMWjwrO:-OEs-O7f7RSodqVmVV_j:b-7xxogg) ([raw file](https://github.com/starkware-libs/stwo/blob/a58b4caae4c58fbcdf35a5bfeffd687d54b4c16e/crates/air_utils/src/trace/iterable_trace.rs#L49)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

im not too happy with either
@shaharsamocha7 idea?
</blockquote></details>

IMO ComponentTrace is better
The parallel iteration things are implementation details
___
*[`crates/air_utils/src/trace/iterable_trace.rs` line 52 at r2](https://reviewable.io/reviews/starkware-libs/stwo/942#-OErcAmE6FwH03dkd8TL:-OEs-Bw66i46_IUnbOuJ:b4g0vm7) ([raw file](https://github.com/starkware-libs/stwo/blob/a58b4caae4c58fbcdf35a5bfeffd687d54b4c16e/crates/air_utils/src/trace/iterable_trace.rs#L52)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

is it clear the the logsize refers to the non packed type?
</blockquote></details>

I see, WDYT about?
// Log number of non-packed rows in each column in the trace.
___
*[`crates/air_utils/src/trace/iterable_trace.rs` line 90 at r2](https://reviewable.io/reviews/starkware-libs/stwo/942#-OErcEa5Dt08q6xIyVdA:-OEs-qMw11O4pFXmdhwg:b-npkmp1) ([raw file](https://github.com/starkware-libs/stwo/blob/a58b4caae4c58fbcdf35a5bfeffd687d54b4c16e/crates/air_utils/src/trace/iterable_trace.rs#L90)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

I do want to use something like that in doc test, wdyt about row_at?
</blockquote></details>

I think it is better
___
*[`crates/air_utils/src/trace/iterable_trace.rs` line 46 at r4](https://reviewable.io/reviews/starkware-libs/stwo/942#-OEs0edpCJU1jIal4pmb:-OEs0edpCJU1jIal4pmc:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/f956ccaeb82a479a1c3f6f1ca075c268a6046f3d/crates/air_utils/src/trace/iterable_trace.rs#L46)):*
> ```XML
> ///
> /// let expected_first_3_rows = [[0,1,1], [1,2,5], [2,3,13]].map(|row| row.map(M31::from));
> /// let first_3_rows = [0,1,2].map(|i| trace.row_at(i));
> ```





_Suggestion:_
```XML
/// const N_COLUMNS: usize = 3;
/// const LOG_SIZE: u32 = 8;
/// let expected_first_3_rows = [[0,1,1], [1,2,5], [2,3,13]].map(|row| row.map(M31::from));
/// let mut trace = IterableTrace::<N_COLUMNS>::zeroed(LOG_SIZE);
/// let example_input = (0..1 << LOG_SIZE).map(M31::from).collect_vec(); // 0..256
/// trace
///     .iter_mut()
///     .zip(example_input.chunks(N_LANES))
///     .chunks(4)
///     .into_iter()
///     .for_each(|chunk| {
///         chunk.into_iter().for_each(|(row, input)| {
///             *row[0] = PackedM31::from_array(input.try_into().unwrap());
///             *row[1] = *row[0] + PackedM31::broadcast(M31(1));
///             *row[2] = row[0].square() + row[1].square();
///         })
///     });
///

/// let first_3_rows = (0..N_COLUMNS).iter().map(|i| trace.row_at(i));
```
___
*[`crates/air_utils/src/trace/iterable_trace.rs` line 93 at r4](https://reviewable.io/reviews/starkware-libs/stwo/942#-OEs-wn06a04wep6eyqu:-OEs-wn06a04wep6eyqv:bjxrfgp) ([raw file](https://github.com/starkware-libs/stwo/blob/f956ccaeb82a479a1c3f6f1ca075c268a6046f3d/crates/air_utils/src/trace/iterable_trace.rs#L93)):*
> ```XML
>     pub fn row_at(&self, row: usize) -> [M31; N] {
>         let packed_row = row / N_LANES;
>         let idx_in_simd_vector = row % N_LANES;
> ```

Do we want to assert that row is in bounds?



_Code quote:_
```XML
        let packed_row = row / N_LANES;
        let idx_in_simd_vector = row % N_LANES;
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/942)* status: 5 of 6 files reviewed, 7 unresolved discussions (waiting on @ilyalesokhin-starkware and @shaharsamocha7)

___
*[`crates/air_utils/src/trace/iterable_trace.rs` line 49 at r2](https://reviewable.io/reviews/starkware-libs/stwo/942#-OEr_q0V37bWqYMWjwrO:-OEs5g1OCRYV7vmRuDJt:bb7f2mf) ([raw file](https://github.com/starkware-libs/stwo/blob/a58b4caae4c58fbcdf35a5bfeffd687d54b4c16e/crates/air_utils/src/trace/iterable_trace.rs#L49)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

IMO ComponentTrace is better
The parallel iteration things are implementation details
</blockquote></details>

done
___
*[`crates/air_utils/src/trace/iterable_trace.rs` line 52 at r2](https://reviewable.io/reviews/starkware-libs/stwo/942#-OErcAmE6FwH03dkd8TL:-OEs5qpm76xfoGPaFTET:b-7rl0jd) ([raw file](https://github.com/starkware-libs/stwo/blob/a58b4caae4c58fbcdf35a5bfeffd687d54b4c16e/crates/air_utils/src/trace/iterable_trace.rs#L52)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I see, WDYT about?
// Log number of non-packed rows in each column in the trace.
</blockquote></details>

done.
___
*[`crates/air_utils/src/trace/iterable_trace.rs` line 90 at r2](https://reviewable.io/reviews/starkware-libs/stwo/942#-OErcEa5Dt08q6xIyVdA:-OEs5sSd-EyuA08MgL-c:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/a58b4caae4c58fbcdf35a5bfeffd687d54b4c16e/crates/air_utils/src/trace/iterable_trace.rs#L90)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I think it is better
</blockquote></details>

Done.
___
*[`crates/air_utils/src/trace/iterable_trace.rs` line 93 at r4](https://reviewable.io/reviews/starkware-libs/stwo/942#-OEs-wn06a04wep6eyqu:-OEs5uotBQqNT9ahCQ88:b2nign6) ([raw file](https://github.com/starkware-libs/stwo/blob/f956ccaeb82a479a1c3f6f1ca075c268a6046f3d/crates/air_utils/src/trace/iterable_trace.rs#L93)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Do we want to assert that row is in bounds?
</blockquote></details>

yes
___
*[`crates/air_utils/src/trace/iterable_trace.rs` line 46 at r4](https://reviewable.io/reviews/starkware-libs/stwo/942#-OEs0edpCJU1jIal4pmb:-OEs4xwl6lm2KtV-Maf5:b-h06krz) ([raw file](https://github.com/starkware-libs/stwo/blob/f956ccaeb82a479a1c3f6f1ca075c268a6046f3d/crates/air_utils/src/trace/iterable_trace.rs#L46)):*
> ```XML
> ///
> /// let expected_first_3_rows = [[0,1,1], [1,2,5], [2,3,13]].map(|row| row.map(M31::from));
> /// let first_3_rows = [0,1,2].map(|i| trace.row_at(i));
> ```

I think that in doctests there's usually a pattern of showing what the output is at the end of the doc
wdyt about the current attempt?

**Review by shaharsamocha7 — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/942)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/942#-:-OEsJrWE1sAITwZbEOhT:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/942)* status: all files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @ohad-starkware)

___
*[`crates/air_utils/src/trace/component_trace.rs` line 104 at r7](https://reviewable.io/reviews/starkware-libs/stwo/942#-OEt6Ynw5M6JU153ogKx:-OEt6YnxEgu87R9pBlqu:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/7aebc87cb049462fa2e09eec2b311c098187dbc2/crates/air_utils/src/trace/component_trace.rs#L104)):*
> ```XML
> pub type MutRow<'trace, const N: usize> = [&'trace mut PackedM31; N];
> 
> /// An iterator over mutable references to the rows of a [`IterableTrace`].
> ```





_Suggestion:_
```XML
`ComponentTrace`
```

**Review by shaharsamocha7 — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/942)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

**Comment by ohad-starkware** [comment]
### Merge activity

* **Dec 25, 10:51 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/942).

**Pull request merged**
