### PR TITLE
AVX quotients

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/488)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/488?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#488** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/488?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#487** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/487?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#486** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/486?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#484** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/484?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#483** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/483?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#482** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/482?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#481** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/481?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#480** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/480?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#479** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/479?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#478** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/478?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#463** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/463?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#477** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/477?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#476** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/476?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by andrewmilson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/488)* status: 0 of 11 files reviewed, 9 unresolved discussions (waiting on @spapinistarkware)

___
*[`benches/quotients.rs` line 5 at r2](https://reviewable.io/reviews/starkware-libs/stwo/488#-NtJc1UnEGNdiLYTXYNI:-NtJc1UnEGNdiLYTXYNJ:bohuxiq) ([raw file](https://github.com/starkware-libs/stwo/blob/24889ee78f76f5ab4013a8e41e9bb40c2ccb9c63/benches/quotients.rs#L5)):*
> ```XML
> use criterion::Criterion;
> 
> #[cfg(target_arch = "x86_64")]
> ```

Can this be removed since it compiles for non x86_64
___
*[`benches/quotients.rs` line 7 at r2](https://reviewable.io/reviews/starkware-libs/stwo/488#-NtJcUpc9rMd8ms52qbh:-NtJcUpc9rMd8ms52qbi:b7eqelv) ([raw file](https://github.com/starkware-libs/stwo/blob/24889ee78f76f5ab4013a8e41e9bb40c2ccb9c63/benches/quotients.rs#L7)):*
> ```XML
> #[cfg(target_arch = "x86_64")]
> pub fn cpu_quotients(c: &mut criterion::Criterion) {
>     use itertools::Itertools;
> ```

These can be imported at the module level.
___
*[`benches/quotients.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/stwo/488#-NtJegrt9TA1cXBqdNIp:-NtJegrt9TA1cXBqdNIq:b2nhkus) ([raw file](https://github.com/starkware-libs/stwo/blob/24889ee78f76f5ab4013a8e41e9bb40c2ccb9c63/benches/quotients.rs#L24)):*
> ```XML
>             let values = (0..SIZE as u32)
>                 .map(BaseField::from_u32_unchecked)
>                 .collect();
> ```

Nit



_Suggestion:_
```XML
            let values = (0..SIZE).map(BaseField::from).collect();
```
___
*[`benches/quotients.rs` line 29 at r2](https://reviewable.io/reviews/starkware-libs/stwo/488#-NtJfBzb2tegjWdgsFd1:-NtJfBzb2tegjWdgsFd2:biba5ja) ([raw file](https://github.com/starkware-libs/stwo/blob/24889ee78f76f5ab4013a8e41e9bb40c2ccb9c63/benches/quotients.rs#L29)):*
> ```XML
>         .collect_vec();
>     let random_coeff = SecureField::from_m31_array(std::array::from_fn(BaseField::from));
>     let a = SecureField::from_m31_array(std::array::from_fn(|i| BaseField::from(3 * i)));
> ```

Nit: can we simplify the logic in the bench



_Suggestion:_
```XML
let random_coeff = SecureField::from_u32_unchecked(0, 1, 2, 3);
let a = SecureField::from_u32_unchecked(5, 6, 7, 8);
```
___
*[`benches/quotients.rs` line 42 at r2](https://reviewable.io/reviews/starkware-libs/stwo/488#-NtJfjGoDhbWgb31MXa4:-NtJfjGoDhbWgb31MXa5:bd99w57) ([raw file](https://github.com/starkware-libs/stwo/blob/24889ee78f76f5ab4013a8e41e9bb40c2ccb9c63/benches/quotients.rs#L42)):*
> ```XML
>                 random_coeff,
>                 &openings,
>             )
> ```

https://docs.rs/criterion/latest/criterion/fn.black_box.html



_Suggestion:_
```XML
            black_box(CPUBackend::accumulate_quotients(
                black_box(domain),
                black_box(&cols.iter().collect_vec()),
                black_box(random_coeff),
                black_box(&openings),
            ))
```
___
*[`benches/quotients.rs` line 94 at r2](https://reviewable.io/reviews/starkware-libs/stwo/488#-NtJcR0j9enaaoSUvPZV:-NtJcR0j9enaaoSUvPZW:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/24889ee78f76f5ab4013a8e41e9bb40c2ccb9c63/benches/quotients.rs#L94)):*
> ```XML
>     config = Criterion::default().sample_size(10);
>     targets=avx512_quotients, cpu_quotients);
> criterion::criterion_main!(avx_quotients);
> ```





_Suggestion:_
```XML
#[cfg(target_arch = "x86_64")]
criterion::criterion_group!(
    name=quotients;
    config = Criterion::default().sample_size(10);
    targets=avx512_quotients, cpu_quotients);
#[cfg(not(target_arch = "x86_64"))]
criterion::criterion_group!(
    name=quotients;
    config = Criterion::default().sample_size(10);
    targets=cpu_quotients);
criterion::criterion_main!(quotients);
```
___
*[`src/core/backend/avx512/mod.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/stwo/488#-NtJeNwmAPqEb_ZIXWr_:-NtJeNwn5x--6PjVcX1M:b-vu4bgq) ([raw file](https://github.com/starkware-libs/stwo/blob/24889ee78f76f5ab4013a8e41e9bb40c2ccb9c63/src/core/backend/avx512/mod.rs#L24)):*
> ```XML
> use crate::core::utils;
> 
> pub const VECS_LOG_SIZE: usize = 4;
> ```

Can we store logarithms as `u32` to be consistent
___
*[`src/core/backend/avx512/mod.rs` line 160 at r2](https://reviewable.io/reviews/starkware-libs/stwo/488#-NtJdYdfCu-Y3_oXk5si:-NtJdYdfCu-Y3_oXk5sj:bcjf6zq) ([raw file](https://github.com/starkware-libs/stwo/blob/24889ee78f76f5ab4013a8e41e9bb40c2ccb9c63/src/core/backend/avx512/mod.rs#L160)):*
> ```XML
>     }
> 
>     pub fn to_cpu(&self) -> Vec<SecureField> {
> ```

Are we sure we want to call this `to_cpu`?  I find `to_vec` clearer. 
___
*[`src/core/backend/avx512/qm31.rs` line 90 at r2](https://reviewable.io/reviews/starkware-libs/stwo/488#-NtJdv788_m1VaSChZrd:-NtJdv788_m1VaSChZre:bfsga2b) ([raw file](https://github.com/starkware-libs/stwo/blob/24889ee78f76f5ab4013a8e41e9bb40c2ccb9c63/src/core/backend/avx512/qm31.rs#L90)):*
> ```XML
> impl FieldExpOps for PackedQM31 {
>     fn inverse(&self) -> Self {
>         self.pow(P4 - 2)
> ```

I wonder if we should think about a more optimized [addchain](https://github.com/mmcloughlin/addchain) implementation at some point.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/488)* status: 0 of 11 files reviewed, 7 unresolved discussions (waiting on @andrewmilson)

___
*[`benches/quotients.rs` line 5 at r2](https://reviewable.io/reviews/starkware-libs/stwo/488#-NtJc1UnEGNdiLYTXYNI:-NtLrge_9E4IT_m00IhC:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/24889ee78f76f5ab4013a8e41e9bb40c2ccb9c63/benches/quotients.rs#L5)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Can this be removed since it compiles for non x86_64
</blockquote></details>

Done.
___
*[`benches/quotients.rs` line 7 at r2](https://reviewable.io/reviews/starkware-libs/stwo/488#-NtJcUpc9rMd8ms52qbh:-NtLrhFB6JRPS3iqHHyJ:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/24889ee78f76f5ab4013a8e41e9bb40c2ccb9c63/benches/quotients.rs#L7)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

These can be imported at the module level.
</blockquote></details>

Done.
___
*[`benches/quotients.rs` line 42 at r2](https://reviewable.io/reviews/starkware-libs/stwo/488#-NtJfjGoDhbWgb31MXa4:-NtLsHok4eu8Bmk5Karb:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/24889ee78f76f5ab4013a8e41e9bb40c2ccb9c63/benches/quotients.rs#L42)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

https://docs.rs/criterion/latest/criterion/fn.black_box.html
</blockquote></details>

Done.
___
*[`benches/quotients.rs` line 94 at r2](https://reviewable.io/reviews/starkware-libs/stwo/488#-NtJcR0j9enaaoSUvPZV:-NtLtZHs9pW-S39BjbRs:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/24889ee78f76f5ab4013a8e41e9bb40c2ccb9c63/benches/quotients.rs#L94)):*
> ```XML
>     config = Criterion::default().sample_size(10);
>     targets=avx512_quotients, cpu_quotients);
> criterion::criterion_main!(avx_quotients);
> ```

Done.
___
*[`src/core/backend/avx512/mod.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/stwo/488#-NtJeNwmAPqEb_ZIXWr_:-NtLta620rwdgIMUXnAp:b8nlmnf) ([raw file](https://github.com/starkware-libs/stwo/blob/24889ee78f76f5ab4013a8e41e9bb40c2ccb9c63/src/core/backend/avx512/mod.rs#L24)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Can we store logarithms as `u32` to be consistent
</blockquote></details>

We should, yes. This would make too manu changes in this PR.
I'm not sure if we catually want u32 for this, or usize. Half of the places need usize.
___
*[`src/core/backend/avx512/mod.rs` line 160 at r2](https://reviewable.io/reviews/starkware-libs/stwo/488#-NtJdYdfCu-Y3_oXk5si:-NtLtvZG2JtuaDzyDNMR:bgrnpbn) ([raw file](https://github.com/starkware-libs/stwo/blob/24889ee78f76f5ab4013a8e41e9bb40c2ccb9c63/src/core/backend/avx512/mod.rs#L160)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Are we sure we want to call this `to_cpu`?  I find `to_vec` clearer.
</blockquote></details>

I think to_cpu() is clearer.
For example, in fri last layer, we are moving from the backend(avx or even gpu), and we are purposely moving it to the cpu.
wdyt?
___
*[`src/core/backend/avx512/qm31.rs` line 90 at r2](https://reviewable.io/reviews/starkware-libs/stwo/488#-NtJdv788_m1VaSChZrd:-NtLuEXZ9f3j1pZq6P5m:b-v43zb3) ([raw file](https://github.com/starkware-libs/stwo/blob/24889ee78f76f5ab4013a8e41e9bb40c2ccb9c63/src/core/backend/avx512/qm31.rs#L90)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

I wonder if we should think about a more optimized [addchain](https://github.com/mmcloughlin/addchain) implementation at some point.
</blockquote></details>

Probably. Wanna do it?
This is the bit representation of P**4-2:
0b1111111111111111111111111110100000000000000000000000000011010111111111111111111111111100101000000000000000000000000001001111
It has 63 1s.
I think we can do it with ~128+10 muls.

**Review by andrewmilson — CHANGES_REQUESTED** [review]
> Reviewed 1 of 11 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/488)* status: 2 of 11 files reviewed, 5 unresolved discussions (waiting on @spapinistarkware)

___
*[`benches/quotients.rs` line 35 at r4](https://reviewable.io/reviews/starkware-libs/stwo/488#-NtNV-EI-h5FAUZVyX0R:-NtNV-EI-h5FAUZVyX0S:b-pmkkyi) ([raw file](https://github.com/starkware-libs/stwo/blob/2c9792cd41ec3809bf844176e2c21ef0a20c2add/benches/quotients.rs#L35)):*
> ```XML
>             black_box(CPUBackend::accumulate_quotients(
>                 black_box(domain),
>                 black_box(&cols.iter().collect_vec()),
> ```

Does the allocation affect the benchmark? Should it be constructed outside?
___
*[`benches/quotients.rs` line 69 at r4](https://reviewable.io/reviews/starkware-libs/stwo/488#-NtNUvvO8SLC4jcxv9Sk:-NtNUvvO8SLC4jcxv9Sl:bkduqjd) ([raw file](https://github.com/starkware-libs/stwo/blob/2c9792cd41ec3809bf844176e2c21ef0a20c2add/benches/quotients.rs#L69)):*
> ```XML
>         b.iter(|| {
>             AVX512Backend::accumulate_quotients(
>                 domain,
> ```

black_box?
___
*[`src/core/backend/avx512/mod.rs` line 160 at r2](https://reviewable.io/reviews/starkware-libs/stwo/488#-NtJdYdfCu-Y3_oXk5si:-NtMF3ALCdHvYjuA77nL:b-nastvp) ([raw file](https://github.com/starkware-libs/stwo/blob/24889ee78f76f5ab4013a8e41e9bb40c2ccb9c63/src/core/backend/avx512/mod.rs#L160)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I think to_cpu() is clearer.
For example, in fri last layer, we are moving from the backend(avx or even gpu), and we are purposely moving it to the cpu.
wdyt?
</blockquote></details>

Does the function need to signify anything about where the memory of the SecureColumn is? To me the only important information about the interface is that it returns a `Vec<T>`. Also `to_cpu` is inconsistent for avx backend given it already lives on the CPU memory. 

As an aside, perhaps it makes sense if this function takes ownership `fn into_vec/into_cpu(self) -> Vec<SecureField>` given the places we intend to use it.
___
*[`src/core/backend/avx512/qm31.rs` line 90 at r2](https://reviewable.io/reviews/starkware-libs/stwo/488#-NtJdv788_m1VaSChZrd:-NtNY6tmAXJ-Qq7iDtqW:bwr7hrv) ([raw file](https://github.com/starkware-libs/stwo/blob/24889ee78f76f5ab4013a8e41e9bb40c2ccb9c63/src/core/backend/avx512/qm31.rs#L90)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Probably. Wanna do it?
This is the bit representation of P**4-2:
0b1111111111111111111111111110100000000000000000000000000011010111111111111111111111111100101000000000000000000000000001001111
It has 63 1s.
I think we can do it with ~128+10 muls.
</blockquote></details>

Happy to do it, can you add a TODO for me please?

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/488)* status: 0 of 13 files reviewed, 5 unresolved discussions (waiting on @andrewmilson)

___
*[`benches/quotients.rs` line 35 at r4](https://reviewable.io/reviews/starkware-libs/stwo/488#-NtNV-EI-h5FAUZVyX0R:-NtPixLfB__El52SwG4f:b-6d8hsg) ([raw file](https://github.com/starkware-libs/stwo/blob/2c9792cd41ec3809bf844176e2c21ef0a20c2add/benches/quotients.rs#L35)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Does the allocation affect the benchmark? Should it be constructed outside?
</blockquote></details>

It's just constructing 256 pointers. Should be negligable.
___
*[`benches/quotients.rs` line 69 at r4](https://reviewable.io/reviews/starkware-libs/stwo/488#-NtNUvvO8SLC4jcxv9Sk:-NtVcPQ14hfsseRf7ldB:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/2c9792cd41ec3809bf844176e2c21ef0a20c2add/benches/quotients.rs#L69)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

black_box?
</blockquote></details>

Done.
___
*[`src/core/backend/avx512/mod.rs` line 160 at r2](https://reviewable.io/reviews/starkware-libs/stwo/488#-NtJdYdfCu-Y3_oXk5si:-NtPjID65Xo14gfDumn0:b70ikn4) ([raw file](https://github.com/starkware-libs/stwo/blob/24889ee78f76f5ab4013a8e41e9bb40c2ccb9c63/src/core/backend/avx512/mod.rs#L160)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Does the function need to signify anything about where the memory of the SecureColumn is? To me the only important information about the interface is that it returns a `Vec<T>`. Also `to_cpu` is inconsistent for avx backend given it already lives on the CPU memory. 

As an aside, perhaps it makes sense if this function takes ownership `fn into_vec/into_cpu(self) -> Vec<SecureField>` given the places we intend to use it.
</blockquote></details>

It's going to move to SecureColumn, and be generic on the backend.
This function is "expensive" and I want to make it clear that it is. `to_vec()`, IMO, doesn't make it clear that this is expensive.
Any 3rd option?
___
*[`src/core/backend/avx512/qm31.rs` line 90 at r2](https://reviewable.io/reviews/starkware-libs/stwo/488#-NtJdv788_m1VaSChZrd:-NtVcEgGCXjV7a0BUWgc:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/24889ee78f76f5ab4013a8e41e9bb40c2ccb9c63/src/core/backend/avx512/qm31.rs#L90)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Happy to do it, can you add a TODO for me please?
</blockquote></details>

Done.

**Review by andrewmilson — CHANGES_REQUESTED** [review]
> Reviewed 1 of 11 files at r1, 5 of 11 files at r5, 2 of 3 files at r6, 3 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/488)* status: 11 of 13 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`src/core/backend/avx512/quotients.rs` line 88 at r7](https://reviewable.io/reviews/starkware-libs/stwo/488#-NtoIBvQDuFKMI_nTOwZ:-NtoIBvQDuFKMI_nTOw_:b-g0a8xt) ([raw file](https://github.com/starkware-libs/stwo/blob/889e6fdacd5ce10d42d4f02cb75a5b316ad45cb8/src/core/backend/avx512/quotients.rs#L88)):*
> ```XML
> }
> 
> fn cross(
> ```

Docs? I don't know what cross means
___
*[`src/core/backend/cpu/quotients.rs` line 22 at r7](https://reviewable.io/reviews/starkware-libs/stwo/488#-NtoJ2077k-xnc9GDhfK:-NtoCbJeB68tWArFj0mj:b2nhkus) ([raw file](https://github.com/starkware-libs/stwo/blob/889e6fdacd5ce10d42d4f02cb75a5b316ad45cb8/src/core/backend/cpu/quotients.rs#L22)):*
> ```XML
>         samples: &[ColumnSampleBatch],
>     ) -> SecureEvaluation<Self> {
>         let mut values = SecureColumn::<CPUBackend>::zeros(domain.size());
> ```

Nit



_Suggestion:_
```XML
let mut values = SecureColumn::<Self>::zeros(domain.size());
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/488)* status: 11 of 13 files reviewed, 1 unresolved discussion (waiting on @andrewmilson)

___
*[`src/core/backend/avx512/quotients.rs` line 88 at r7](https://reviewable.io/reviews/starkware-libs/stwo/488#-NtoIBvQDuFKMI_nTOwZ:-NtofCPx3i75WgmqWrQs:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/889e6fdacd5ce10d42d4f02cb75a5b316ad45cb8/src/core/backend/avx512/quotients.rs#L88)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Docs? I don't know what cross means
</blockquote></details>

Done.

**Review by andrewmilson — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/488#-:-Ntp24ZN-Xo5pndo1oz6:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by andrewmilson — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/488#-:-Ntt4of_2s-iBEt782em:bnfp4nl)* status: 12 of 13 files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by andrewmilson — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/488#-:-Nu2Vh2F2lQx6Ci2Zdmu:bnfp4nl)* status: 4 of 13 files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by andrewmilson — APPROVED** [review]
:lgtm:

> Reviewed 7 of 9 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/488#-:-NuGqRkI4H4v-oVD_YuP:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`src/core/backend/avx512/mod.rs` line 154 at r11](https://reviewable.io/reviews/starkware-libs/stwo/488#-NuGqF47Cr67ZuOAS5dv:-NuGqF47Cr67ZuOAS5dw:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/1bc7cc44dffcca55f86e5e276672c8fa20ddab5d/src/core/backend/avx512/mod.rs#L154)):*
> ```XML
>     }
> 
>     pub fn set_packed(&mut self, vec_index: usize, value: PackedQM31) {
> ```





_Suggestion:_
```XML
pub unsafe fn set_packed
```

**Comment by andrewmilson** [comment]
*[`src/core/backend/avx512/mod.rs` line 139 at r11](https://reviewable.io/reviews/starkware-libs/stwo/488#-NuGqVCgEAro4zeQ5Ejk:-NuGqVCh4ixnJIuMwpmo:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/1bc7cc44dffcca55f86e5e276672c8fa20ddab5d/src/core/backend/avx512/mod.rs#L139)):*
> ```XML
> 
> impl SecureColumn<AVX512Backend> {
>     pub fn packed_at(&self, vec_index: usize) -> PackedQM31 {
> ```





_Suggestion:_
```XML
pub unsafe fn packed_at
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/488)* status: 2 of 13 files reviewed, 2 unresolved discussions (waiting on @andrewmilson)

___
*[`src/core/backend/avx512/mod.rs` line 139 at r11](https://reviewable.io/reviews/starkware-libs/stwo/488#-NuGqVCgEAro4zeQ5Ejk:-NuZ1Lyf-pRYZAT8wFVt:b4v4jwg) ([raw file](https://github.com/starkware-libs/stwo/blob/1bc7cc44dffcca55f86e5e276672c8fa20ddab5d/src/core/backend/avx512/mod.rs#L139)):*
> ```XML
> 
> impl SecureColumn<AVX512Backend> {
>     pub fn packed_at(&self, vec_index: usize) -> PackedQM31 {
> ```

It's not a part of this PR now. This can be done independently in another PR.
___
*[`src/core/backend/avx512/mod.rs` line 154 at r11](https://reviewable.io/reviews/starkware-libs/stwo/488#-NuGqF47Cr67ZuOAS5dv:-NuZ1R0R8L6c_rXINVLg:bb73xfv) ([raw file](https://github.com/starkware-libs/stwo/blob/1bc7cc44dffcca55f86e5e276672c8fa20ddab5d/src/core/backend/avx512/mod.rs#L154)):*
> ```XML
>     }
> 
>     pub fn set_packed(&mut self, vec_index: usize, value: PackedQM31) {
> ```

Same

**Comment by spapinistarkware** [comment]
### Merge activity

* **Apr 3, 11:19 AM EDT**: @spapinistarkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/488).

**Pull request merged**
