### PR TITLE
New AVX quotients

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/549)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
* **#549** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/549?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 8 of 12 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/549)* status: all files reviewed, 9 unresolved discussions (waiting on @spapinistarkware)

___
*[`benches/quotients.rs` line 26 at r2](https://reviewable.io/reviews/starkware-libs/stwo/549#-Nu3Moj808mE-0uzhBXi:-Nu3Moj808mE-0uzhBXj:b45h) ([raw file](https://github.com/starkware-libs/stwo/blob/99ee4677bf4d2f43f0a03ff8c6e593d8dd7ff4d2/benches/quotients.rs#L26)):*
> ```XML
>     let random_coeff = SecureField::from_u32_unchecked(0, 1, 2, 3);
>     let a = SecureField::from_u32_unchecked(5, 6, 7, 8);
>     let openings = vec![ColumnSampleBatch {
> ```





_Suggestion:_
```XML
samples
```
___
*[`benches/quotients.rs` line 34 at r2](https://reviewable.io/reviews/starkware-libs/stwo/549#-Nu3N0tM6ermI3FmGZLZ:-Nu3N0tM6ermI3FmGZL_:bageapi) ([raw file](https://github.com/starkware-libs/stwo/blob/99ee4677bf4d2f43f0a03ff8c6e593d8dd7ff4d2/benches/quotients.rs#L34)):*
> ```XML
>         b.iter(|| {
>             black_box(CPUBackend::accumulate_quotients(
>                 black_box(domain),
> ```

Why do you need a `black_box` around the arguments? There isn't any computation.



_Code quote:_
```XML
black_box(domain)
```
___
*[`benches/quotients.rs` line 40 at r2](https://reviewable.io/reviews/starkware-libs/stwo/549#-Nu3OK7-6-dWZN52qv3_:-Nu3OK7-6-dWZN52qv3a:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/99ee4677bf4d2f43f0a03ff8c6e593d8dd7ff4d2/benches/quotients.rs#L40)):*
> ```XML
>             ))
>         })
>     });
> ```





_Suggestion:_
```XML
    let cols = cols.iter().collect_vec();
    c.bench_function("cpu quotients 2^8 x 2^16", |b| {
        b.iter(|| {
            black_box(CPUBackend::accumulate_quotients(
                black_box(domain),
                black_box(&cols),
                black_box(random_coeff),
                black_box(&openings),
            ))
        })
    });
```
___
*[`src/core/backend/avx512/cm31.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/stwo/549#-Nu3EelM9gEHkUlsUHuR:-Nu3EelM9gEHkUlsUHuS:bixxakr) ([raw file](https://github.com/starkware-libs/stwo/blob/99ee4677bf4d2f43f0a03ff8c6e593d8dd7ff4d2/src/core/backend/avx512/cm31.rs#L74)):*
> ```XML
> impl FieldExpOps for PackedCM31 {
>     fn inverse(&self) -> Self {
>         self.pow((P2 - 2) as u128)
> ```

Should we have this assertion like in the regular field elements?



_Suggestion:_
```XML
assert!(!self.is_zero(), "0 has no inverse");
self.pow((P2 - 2) as u128)
```
___
*[`src/core/backend/avx512/quotients.rs` line 88 at r2](https://reviewable.io/reviews/starkware-libs/stwo/549#-Nu3Rbab3YqC0E_Nc9xb:-Nu3Rbab3YqC0E_Nc9xc:bchmbft) ([raw file](https://github.com/starkware-libs/stwo/blob/99ee4677bf4d2f43f0a03ff8c6e593d8dd7ff4d2/src/core/backend/avx512/quotients.rs#L88)):*
> ```XML
>         row_accumlator = row_accumlator
>             * PackedQM31::broadcast(random_coeff.pow(sample.columns_and_values.len() as u128))
>             + numerator * denominator.inverse();
> ```

Impl Div?



_Code quote:_
```XML
numerator * denominator.inverse();
```
___
*[`src/core/backend/avx512/quotients.rs` line 119 at r2](https://reviewable.io/reviews/starkware-libs/stwo/549#-Nu3ik245yCA89c8p_EL:-Nu3ik245yCA89c8p_EM:b-vvrn7g) ([raw file](https://github.com/starkware-libs/stwo/blob/99ee4677bf4d2f43f0a03ff8c6e593d8dd7ff4d2/src/core/backend/avx512/quotients.rs#L119)):*
> ```XML
> 
>     #[test]
>     fn test_avx_accumulate_quotients() {
> ```

Add a test to check that the quotient is of low degree.
___
*[`src/core/backend/avx512/quotients.rs` line 130 at r2](https://reviewable.io/reviews/starkware-libs/stwo/549#-Nu3jE6rBKKnV5CC1Mc5:-Nu3jE6rBKKnV5CC1Mc6:bkhgwzu) ([raw file](https://github.com/starkware-libs/stwo/blob/99ee4677bf4d2f43f0a03ff8c6e593d8dd7ff4d2/src/core/backend/avx512/quotients.rs#L130)):*
> ```XML
>         let random_coeff = SecureField::from_m31_array(std::array::from_fn(BaseField::from));
>         let a = SecureField::from_m31_array(std::array::from_fn(|i| BaseField::from(3 * i)));
>         let b = SecureField::from_m31_array(std::array::from_fn(|i| BaseField::from(4 * i)));
> ```

Consider using `qm31!` macro for readability.



_Code quote:_
```XML
        let random_coeff = SecureField::from_m31_array(std::array::from_fn(BaseField::from));
        let a = SecureField::from_m31_array(std::array::from_fn(|i| BaseField::from(3 * i)));
        let b = SecureField::from_m31_array(std::array::from_fn(|i| BaseField::from(4 * i)));
```
___
*[`src/core/backend/avx512/quotients.rs` line 134 at r2](https://reviewable.io/reviews/starkware-libs/stwo/549#-Nu3j-suEal7tTqa8TqV:-Nu3j-suEal7tTqa8TqW:bwu7xoo) ([raw file](https://github.com/starkware-libs/stwo/blob/99ee4677bf4d2f43f0a03ff8c6e593d8dd7ff4d2/src/core/backend/avx512/quotients.rs#L134)):*
> ```XML
>             point: SECURE_FIELD_CIRCLE_GEN,
>             columns_and_values: vec![(0, a), (0, b)],
>         }];
> ```

add column 1 values?



_Code quote:_
```XML
        let samples = vec![ColumnSampleBatch {
            point: SECURE_FIELD_CIRCLE_GEN,
            columns_and_values: vec![(0, a), (0, b)],
        }];
```
___
*[`src/core/backend/avx512/quotients.rs` line 162 at r2](https://reviewable.io/reviews/starkware-libs/stwo/549#-Nu3iUhS3wY3wPe48AH1:-Nu3iUhS3wY3wPe48AH2:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/99ee4677bf4d2f43f0a03ff8c6e593d8dd7ff4d2/src/core/backend/avx512/quotients.rs#L162)):*
> ```XML
> 
>         // TODO(spapini): This is calculated in a different way from CPUBackend right now.
>         assert_ne!(avx_result.to_vec(), cpu_result.values.to_vec());
> ```





_Suggestion:_
```XML
        let cpu_result = CPUBackend::accumulate_quotients(
            domain,
            &cpu_columns.iter().collect_vec(),
            random_coeff,
            &samples,
        )
        .values
        .to_vec();

        // TODO(spapini): This is calculated in a different way from CPUBackend right now.
        assert_ne!(avx_result, cpu_result);
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/549)* status: all files reviewed, 4 unresolved discussions (waiting on @alonh5)

___
*[`benches/quotients.rs` line 34 at r2](https://reviewable.io/reviews/starkware-libs/stwo/549#-Nu3N0tM6ermI3FmGZLZ:-Nu42E16Al21r5eEH-J-:b-k01rxr) ([raw file](https://github.com/starkware-libs/stwo/blob/99ee4677bf4d2f43f0a03ff8c6e593d8dd7ff4d2/benches/quotients.rs#L34)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Why do you need a `black_box` around the arguments? There isn't any computation.
</blockquote></details>

I don't 100% understand black_box, but the docs say it just makes the result opaque to the compiler. My thinking was that if it wasn't opaque, it could do constant propagation and inline it into the function.
___
*[`src/core/backend/avx512/cm31.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/stwo/549#-Nu3EelM9gEHkUlsUHuR:-Nu42pOU82xhXe7p3ugY:brxp9sq) ([raw file](https://github.com/starkware-libs/stwo/blob/99ee4677bf4d2f43f0a03ff8c6e593d8dd7ff4d2/src/core/backend/avx512/cm31.rs#L74)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Should we have this assertion like in the regular field elements?
</blockquote></details>

Sounds good.
___
*[`src/core/backend/avx512/quotients.rs` line 88 at r2](https://reviewable.io/reviews/starkware-libs/stwo/549#-Nu3Rbab3YqC0E_Nc9xb:-Nu42uwL-rvg5GleVMHW:by8kwy5) ([raw file](https://github.com/starkware-libs/stwo/blob/99ee4677bf4d2f43f0a03ff8c6e593d8dd7ff4d2/src/core/backend/avx512/quotients.rs#L88)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Impl Div?
</blockquote></details>

I think this is more explicit.
___
*[`src/core/backend/avx512/quotients.rs` line 119 at r2](https://reviewable.io/reviews/starkware-libs/stwo/549#-Nu3ik245yCA89c8p_EL:-Nu44DQXE9V3jOgYTVwt:bj4aahr) ([raw file](https://github.com/starkware-libs/stwo/blob/99ee4677bf4d2f43f0a03ff8c6e593d8dd7ff4d2/src/core/backend/avx512/quotients.rs#L119)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Add a test to check that the quotient is of low degree.
</blockquote></details>

As discussed, will wait for you to add an impl that agrees with the cpu impl.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/549#-:-Nu45duz6w4FZbVL7wSm:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`benches/quotients.rs` line 34 at r2](https://reviewable.io/reviews/starkware-libs/stwo/549#-Nu3N0tM6ermI3FmGZLZ:-Nu44j-w2pWZnWTP1AZ8:b5td9bv) ([raw file](https://github.com/starkware-libs/stwo/blob/99ee4677bf4d2f43f0a03ff8c6e593d8dd7ff4d2/benches/quotients.rs#L34)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I don't 100% understand black_box, but the docs say it just makes the result opaque to the compiler. My thinking was that if it wasn't opaque, it could do constant propagation and inline it into the function.
</blockquote></details>

Okay. I'm note sure either. but I guess it doesn't hurt.
___
*[`benches/quotients.rs` line 71 at r3](https://reviewable.io/reviews/starkware-libs/stwo/549#-Nu44hng1_PbEsDMzfn1:-Nu44hng1_PbEsDMzfn2:brhun0a) ([raw file](https://github.com/starkware-libs/stwo/blob/ca970208b7037edbb9fa7954ae498c3107162ac2/benches/quotients.rs#L71)):*
> ```XML
>             black_box(AVX512Backend::accumulate_quotients(
>                 black_box(domain),
>                 black_box(&cols.iter().collect_vec()),
> ```

Same here?



_Code quote:_
```XML
black_box(&cols.iter().collect_vec()),
```
___
*[`src/core/backend/avx512/cm31.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/stwo/549#-Nu3EelM9gEHkUlsUHuR:-Nu45LDCDzvHUdST4yYs:bwddg3m) ([raw file](https://github.com/starkware-libs/stwo/blob/99ee4677bf4d2f43f0a03ff8c6e593d8dd7ff4d2/src/core/backend/avx512/cm31.rs#L74)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Sounds good.
</blockquote></details>

Cool. Add it to the other packed inverses?
___
*[`src/core/backend/avx512/quotients.rs` line 119 at r2](https://reviewable.io/reviews/starkware-libs/stwo/549#-Nu3ik245yCA89c8p_EL:-Nu45306C_WET8AoaNi3:brxp9sq) ([raw file](https://github.com/starkware-libs/stwo/blob/99ee4677bf4d2f43f0a03ff8c6e593d8dd7ff4d2/src/core/backend/avx512/quotients.rs#L119)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

As discussed, will wait for you to add an impl that agrees with the cpu impl.
</blockquote></details>

Sounds good.
___
*[`src/core/backend/avx512/quotients.rs` line 129 at r3](https://reviewable.io/reviews/starkware-libs/stwo/549#-Nu45EaW-fQmZLj0Q-Fh:-Nu45EaW-fQmZLj0Q-Fi:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/ca970208b7037edbb9fa7954ae498c3107162ac2/src/core/backend/avx512/quotients.rs#L129)):*
> ```XML
>             CircleEvaluation::<AVX512Backend, _, BitReversedOrder>::new(domain, e1),
>         ];
>         let random_coeff = SecureField::from_m31_array(std::array::from_fn(BaseField::from));
> ```





_Suggestion:_
```XML
let random_coeff = qm31!(1, 2, 3, 4);
```

**Pull request merged**
