### PR TITLE
FRI quotients y optimization

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/686)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/686?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#686** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/686?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#685** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/685?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#684** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/684?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ohad-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/686)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/quotients.rs` line 114 at r2](https://reviewable.io/reviews/starkware-libs/stwo/686#-O0hBl7LAVcb_95hd2l4:-O0hBl7LAVcb_95hd2l5:b-gserrh) ([raw file](https://github.com/starkware-libs/stwo/blob/da6cb9d99ac35b6503057a373dad5332b987bd21/crates/prover/src/core/backend/simd/quotients.rs#L114)):*
> ```XML
>             let column = &columns[*column_index];
>             let value = PackedSecureField::broadcast(*c) * column.data[vec_row];
>             // The numerator is a line equation passing through
> ```

move the doc to the cpu code ?
___
*[`crates/prover/src/core/backend/simd/quotients.rs` line 125 at r2](https://reviewable.io/reviews/starkware-libs/stwo/686#-O0hBbWq2pnK7aEZ55VA:-O0hBbWq2pnK7aEZ55VB:b6ryq8i) ([raw file](https://github.com/starkware-libs/stwo/blob/e5229a66085376a35623062f020711c5caa641ca/crates/prover/src/core/backend/simd/quotients.rs#L125)):*
> ```XML
>                 PackedSecureField::broadcast(*c) * column.data[(quad_row << 2) + i]
>             });
>             // y values are y,-y,-y,y.
> ```

Drop line, 
also - this needs to be explained somewhere.
maybe we can implement in cpu also and doc there, this is less confusing without the interleaves.

**Review by ohad-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/686#-:-O0i5DLK-qbwHeCVQ3g3:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/686)* status: all files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/quotients.rs` line 103 at r3](https://reviewable.io/reviews/starkware-libs/stwo/686#-O0ivr---WSrUFZqwK7i:-O0ivr---WSrUFZqwK7j:b-y9ex8a) ([raw file](https://github.com/starkware-libs/stwo/blob/84309f3b65bde09b7eb1197aa760f27b950dc3a0/crates/prover/src/core/backend/simd/quotients.rs#L103)):*
> ```XML
> 
> /// Accumulates the quotients for 4 * N_LANES rows at a time.
> /// spaced_ys - y values for N_LANES points in the domain, in jumps of 4.
> ```

Can you update that in the reverse order, each 4 consecutive rows are the points (P, P+H, -P, -P-H)?



_Suggestion:_
```XML
/// Accumulates the quotients for 4 * N_LANES rows at a time.
/// spaced_ys - y values for N_LANES points in the domain, in jumps of 4.
```
___
*[`crates/prover/src/core/backend/simd/quotients.rs` line 127 at r3](https://reviewable.io/reviews/starkware-libs/stwo/686#-O0iwS_jEOiPbBuf4a6x:-O0iwS_jEOiPbBuf4a6y:b3kre) ([raw file](https://github.com/starkware-libs/stwo/blob/84309f3b65bde09b7eb1197aa760f27b950dc3a0/crates/prover/src/core/backend/simd/quotients.rs#L127)):*
> ```XML
> 
>             // The numerator is the line equation:
>             //   value - a * point.y - b;
> ```

?



_Suggestion:_
```XML
            // The numerator is the line equation:
            //   c * value - a * point.y - b;
```
___
*[`crates/prover/src/examples/poseidon/mod.rs` line 533 at r3](https://reviewable.io/reviews/starkware-libs/stwo/686#-O0iwGmt33Ja2zVpWZhC:-O0iwGmu-1ufY5NqzdMr:bsa8vv6) ([raw file](https://github.com/starkware-libs/stwo/blob/84309f3b65bde09b7eb1197aa760f27b950dc3a0/crates/prover/src/examples/poseidon/mod.rs#L533)):*
> ```XML
>         // Get from environment variable:
>         let log_n_instances = env::var("LOG_N_INSTANCES")
>             .unwrap_or_else(|_| "10".to_string())
> ```

Doesn't take too much time? (non-blocking)
is 8 less then minimal for a component?



_Code quote:_
```XML
"10"
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/686)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`crates/prover/src/core/backend/simd/quotients.rs` line 103 at r3](https://reviewable.io/reviews/starkware-libs/stwo/686#-O0ivr---WSrUFZqwK7i:-O0lb7xz1SGoVPDiVPAr:bcsu61z) ([raw file](https://github.com/starkware-libs/stwo/blob/84309f3b65bde09b7eb1197aa760f27b950dc3a0/crates/prover/src/core/backend/simd/quotients.rs#L103)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can you update that in the reverse order, each 4 consecutive rows are the points (P, P+H, -P, -P-H)?
</blockquote></details>

Added in the body.
___
*[`crates/prover/src/examples/poseidon/mod.rs` line 533 at r3](https://reviewable.io/reviews/starkware-libs/stwo/686#-O0iwGmt33Ja2zVpWZhC:-O0lbFJi8mjq1DcOzVSW:bsqk8nl) ([raw file](https://github.com/starkware-libs/stwo/blob/84309f3b65bde09b7eb1197aa760f27b950dc3a0/crates/prover/src/examples/poseidon/mod.rs#L533)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Doesn't take too much time? (non-blocking)
is 8 less then minimal for a component?
</blockquote></details>

Doesn't take too much time. 8 is too small.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/686)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @ohad-starkware and @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/quotients.rs` line 137 at r5](https://reviewable.io/reviews/starkware-libs/stwo/686#-O0mtCWgD4_PmAU6Clp5:-O0mtCWgD4_PmAU6Clp6:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/600ce36a638df7d2421238cb8aea06e90e92d5b8/crates/prover/src/core/backend/simd/quotients.rs#L137)):*
> ```XML
> 
>             // The numerator is the line equation:
>             //   value - a * point.y - b;
> ```





_Suggestion:_
```XML
/   c * value - a * point.y - b;
```
___
*[`crates/prover/src/core/backend/simd/quotients.rs` line 155 at r5](https://reviewable.io/reviews/starkware-libs/stwo/686#-O0mtcDK5vtbc0YUqnos:-O0mtcDK5vtbc0YUqnot:b-exf04b) ([raw file](https://github.com/starkware-libs/stwo/blob/600ce36a638df7d2421238cb8aea06e90e92d5b8/crates/prover/src/core/backend/simd/quotients.rs#L155)):*
> ```XML
>                 // Note that all summands were multiplied by coefficients (a, b or c).
>                 // These coefficients already hold the constraint coeff (random_coeff^i).
>                 // This is why we only add here.
> ```

move up



_Code quote:_
```XML
                // Note that all summands were multiplied by coefficients (a, b or c).
                // These coefficients already hold the constraint coeff (random_coeff^i).
                // This is why we only add here.
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/686)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`crates/prover/src/core/backend/simd/quotients.rs` line 137 at r5](https://reviewable.io/reviews/starkware-libs/stwo/686#-O0mtCWgD4_PmAU6Clp5:-O0mu1kQ5CkJ-IR1xxd7:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/600ce36a638df7d2421238cb8aea06e90e92d5b8/crates/prover/src/core/backend/simd/quotients.rs#L137)):*
> ```XML
> 
>             // The numerator is the line equation:
>             //   value - a * point.y - b;
> ```

Done.
___
*[`crates/prover/src/core/backend/simd/quotients.rs` line 155 at r5](https://reviewable.io/reviews/starkware-libs/stwo/686#-O0mtcDK5vtbc0YUqnos:-O0mu2D42B4nS-jGBnE5:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/600ce36a638df7d2421238cb8aea06e90e92d5b8/crates/prover/src/core/backend/simd/quotients.rs#L155)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

move up
</blockquote></details>

Done.

**Review by shaharsamocha7 — COMMENTED** [review]
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/686)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @ohad-starkware and @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/quotients.rs` line 132 at r6](https://reviewable.io/reviews/starkware-libs/stwo/686#-O0nQc5N3xqNlU5RZxDe:-O0nQc5OBP5z9X9jQ-dS:b3kre) ([raw file](https://github.com/starkware-libs/stwo/blob/b11de5544667c3610419c8e267a98d71c6cc38e1/crates/prover/src/core/backend/simd/quotients.rs#L132)):*
> ```XML
>         {
>             let column = &columns[*column_index];
>             let values: [_; 4] = std::array::from_fn(|i| {
> ```

?



_Suggestion:_
```XML
let cvalues: [_; 4] = std::array::from_fn(|i| {
```
___
*[`crates/prover/src/core/backend/simd/quotients.rs` line 144 at r6](https://reviewable.io/reviews/starkware-libs/stwo/686#-O0nNtNo9igcMXwyg_Hw:-O0nNtNo9igcMXwyg_Hx:b4jykxn) ([raw file](https://github.com/starkware-libs/stwo/blob/b11de5544667c3610419c8e267a98d71c6cc38e1/crates/prover/src/core/backend/simd/quotients.rs#L144)):*
> ```XML
>             //   G, -G, G + H, -G + H.
>             // H being the half point (-1,0). The y values for these are
>             //   y, -y, -y, y.
> ```

I would change that to P instead of G.
Not sure if it is better.



_Suggestion:_
```XML
//   P.y, -P.y, -P.y, P.y.
```

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/686)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @ohad-starkware and @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/quotients.rs` line 41 at r7](https://reviewable.io/reviews/starkware-libs/stwo/686#-O0nVG4M5bR7sZb-vHlN:-O0nVG4M5bR7sZb-vHlO:b-31g9w4) ([raw file](https://github.com/starkware-libs/stwo/blob/18edaa69b97e68e1850f42b1057e2d34abb3f742/crates/prover/src/core/backend/simd/quotients.rs#L41)):*
> ```XML
>         let span = span!(Level::INFO, "Quotient accumulation").entered();
>         // TODO(spapini): bit reverse iterator.
>         for quad_row in 0..1 << (subdomain.log_size() - LOG_N_LANES - 2) {
> ```

Add the comment



_Suggestion:_
```XML
        // Accumulate the quotients on subdomain.
        for quad_row in 0..1 << (subdomain.log_size() - LOG_N_LANES - 2) {
```

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/686#-:-O0nXDgnBVC1KsCjMOa0:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
