### PR TITLE
Implement GrandProductOps for SIMD backend

### PR DESCRIPTION
**Pull request by andrewmilson**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/640)

### CODE REVIEW

**Comment by andrewmilson** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/640?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#640** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/640?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#630** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/630?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#629** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/629?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#623** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/623?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#620** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/620?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#621** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/621?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#581** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/581?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#617** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/617?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#616** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/616?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#615** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/615?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#614** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/614?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#613** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/613?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#612** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/612?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#611** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/611?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#610** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/610?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @andrewmilson and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r2, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/640)* status: all files reviewed, 4 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`crates/prover/src/core/backend/cpu/lookups/gkr.rs` line 90 at r5](https://reviewable.io/reviews/starkware-libs/stwo/640#-O1zmlfl9CM-vo_meeJn:-O1zmlfl9CM-vo_meeJo:blqggkp) ([raw file](https://github.com/starkware-libs/stwo/blob/490481c77efdec39ae8d0bb4277756f35a92b327/crates/prover/src/core/backend/cpu/lookups/gkr.rs#L90)):*
> ```XML
>         // Note `inp(r, t, x) = eq(t, 0) * inp(r, 0, x) + eq(t, 1) * inp(r, 1, x)`
>         //   => `inp(r, 2, x) = 2 * inp(r, 1, x) - inp(r, 0, x)`
>         // TODO: Consider evaluation at `1/2` to save an addition operation since `inp(r, 1/2, x) =
> ```

Cool idea



_Suggestion:_
```XML
/ TODO(andrew): Consider e
```
___
*[`crates/prover/src/core/backend/simd/lookups/gkr.rs` line 120 at r5](https://reviewable.io/reviews/starkware-libs/stwo/640#-O1zni_t621MdxCl5CUY:-O1zni_t621MdxCl5CUZ:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/490481c77efdec39ae8d0bb4277756f35a92b327/crates/prover/src/core/backend/simd/lookups/gkr.rs#L120)):*
> ```XML
> 
> // Can assume `len(layer) > N_LANES * 2`
> fn next_grand_product_layer(layer: &Mle<SimdBackend, SecureField>) -> Layer<SimdBackend> {
> ```





_Suggestion:_
```XML
/// Assumpion: `len(layer) > N_LANES * 2`
fn next_grand_product_layer(layer: &Mle<SimdBackend, SecureField>) -> Layer<SimdBackend> {
```
___
*[`crates/prover/src/core/backend/simd/lookups/mod.rs` line 2 at r5](https://reviewable.io/reviews/starkware-libs/stwo/640#-O1znqqq4hhR6Y_7YBrL:-O1znqqq4hhR6Y_7YBrM:ba3dfna) ([raw file](https://github.com/starkware-libs/stwo/blob/490481c77efdec39ae8d0bb4277756f35a92b327/crates/prover/src/core/backend/simd/lookups/mod.rs#L2)):*
> ```XML
> mod gkr;
> // mod grandproduct;
> ```

Remove?
___
*[`crates/prover/src/core/lookups/gkr_prover.rs` line 6 at r5](https://reviewable.io/reviews/starkware-libs/stwo/640#-O1znv0f0XAgRkyqfKvv:-O1znv0f0XAgRkyqfKvw:b2s2ria) ([raw file](https://github.com/starkware-libs/stwo/blob/490481c77efdec39ae8d0bb4277756f35a92b327/crates/prover/src/core/lookups/gkr_prover.rs#L6)):*
> ```XML
> use std::ops::Deref;
> 
> use educe::Educe;
> ```

What is this?

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/640)* status: 6 of 10 files reviewed, 4 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/core/backend/cpu/lookups/gkr.rs` line 90 at r5](https://reviewable.io/reviews/starkware-libs/stwo/640#-O1zmlfl9CM-vo_meeJn:-O26CNww1pp0TTy3eHr8:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/490481c77efdec39ae8d0bb4277756f35a92b327/crates/prover/src/core/backend/cpu/lookups/gkr.rs#L90)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Cool idea
</blockquote></details>

Done.
___
*[`crates/prover/src/core/backend/simd/lookups/gkr.rs` line 120 at r5](https://reviewable.io/reviews/starkware-libs/stwo/640#-O1zni_t621MdxCl5CUY:-O26CTHN3VzjT7eIVgpa:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/490481c77efdec39ae8d0bb4277756f35a92b327/crates/prover/src/core/backend/simd/lookups/gkr.rs#L120)):*
> ```XML
> 
> // Can assume `len(layer) > N_LANES * 2`
> fn next_grand_product_layer(layer: &Mle<SimdBackend, SecureField>) -> Layer<SimdBackend> {
> ```

Done.
___
*[`crates/prover/src/core/backend/simd/lookups/mod.rs` line 2 at r5](https://reviewable.io/reviews/starkware-libs/stwo/640#-O1znqqq4hhR6Y_7YBrL:-O26AlCH7W52Fe_OavFZ:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/490481c77efdec39ae8d0bb4277756f35a92b327/crates/prover/src/core/backend/simd/lookups/mod.rs#L2)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Remove?
</blockquote></details>

Done.
___
*[`crates/prover/src/core/lookups/gkr_prover.rs` line 6 at r5](https://reviewable.io/reviews/starkware-libs/stwo/640#-O1znv0f0XAgRkyqfKvv:-O26AlYzCU6yYyWw4so2:b9xb3s3) ([raw file](https://github.com/starkware-libs/stwo/blob/490481c77efdec39ae8d0bb4277756f35a92b327/crates/prover/src/core/lookups/gkr_prover.rs#L6)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

What is this?
</blockquote></details>

Gives us better derive macros for Clone Debug etc. 
It gets around trait bound requirements of the default derive.

e.g.

#[derive(clone)]
struct Something<B: Backend> {
  column: Col<B, SecureField>
}

This only implements Clone if B: Clone. But Col<B, SecureField> is Clone so B:Clone is a bad bound.

#[derive(Educe)]
#[educe(Clone)]
struct Something<B: Backend> {
  column: Col<B, SecureField>
}

Understands that B doesn't have to be clone

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/640#-:-O2cY6-z-Vo5xm1AlLgz:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Pull request merged**
