### PR TITLE
is_first constant column

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/710)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/710?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#710** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/710?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#708** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/708?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#707** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/707?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#706** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/706?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#705** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/705?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#704** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/704?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#702** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/702?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#701** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/701?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/710)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/constraint_framework/constant_cols.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/stwo/710#-O1zaIpE3V1PO3mjScyC:-O1zaIpF0Xmk-_qgjD2n:b-jimjls) ([raw file](https://github.com/starkware-libs/stwo/blob/d21df66d9265ec97f8327c2a9c0b6309e484ee55/crates/prover/src/constraint_framework/constant_cols.rs#L8)):*
> ```XML
> use crate::core::poly::BitReversedOrder;
> 
> pub fn gen_is_first<B: Backend>(log_size: u32) -> CircleEvaluation<B, BaseField, BitReversedOrder> {
> ```

Document



_Code quote:_
```XML
pub fn gen_is_first<B: Backend>(log_size: u32) -> CircleEvaluation<B, BaseField, BitReversedOrder> {
```
___
*[`crates/prover/src/constraint_framework/mod.rs` line 3 at r1](https://reviewable.io/reviews/starkware-libs/stwo/710#-O1zaLFB2TSC96EybJ-R:-O1zaLFB2TSC96EybJ-S:b-ms124n) ([raw file](https://github.com/starkware-libs/stwo/blob/d21df66d9265ec97f8327c2a9c0b6309e484ee55/crates/prover/src/constraint_framework/mod.rs#L3)):*
> ```XML
> /// ! This module contains helpers to express and use constraints for components.
> mod assert;
> pub mod constant_cols;
> ```

rename file



_Suggestion:_
```XML
constant_columns
```
___
*[`crates/prover/src/core/backend/mod.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/stwo/710#-O1z_zce-QYVKNWYg84p:-O1z_zce-QYVKNWYg84q:bw229bq) ([raw file](https://github.com/starkware-libs/stwo/blob/d21df66d9265ec97f8327c2a9c0b6309e484ee55/crates/prover/src/core/backend/mod.rs#L51)):*
> ```XML
>     fn at(&self, index: usize) -> T;
>     /// Sets the element at the given index.
>     fn set(&mut self, index: usize, value: T);
> ```

Do we want to mention that this function is slow, and shouldn't be used much?
Specially for simd



_Code quote:_
```XML
    /// Sets the element at the given index.
    fn set(&mut self, index: usize, value: T);
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/710)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/constant_cols.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/stwo/710#-O1zaIpE3V1PO3mjScyC:-O2-59V1ATetx84CcxH2:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/d21df66d9265ec97f8327c2a9c0b6309e484ee55/crates/prover/src/constraint_framework/constant_cols.rs#L8)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Document
</blockquote></details>

Done.
___
*[`crates/prover/src/constraint_framework/mod.rs` line 3 at r1](https://reviewable.io/reviews/starkware-libs/stwo/710#-O1zaLFB2TSC96EybJ-R:-O2-5DNW3yoypREw2pER:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/d21df66d9265ec97f8327c2a9c0b6309e484ee55/crates/prover/src/constraint_framework/mod.rs#L3)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

rename file
</blockquote></details>

Done.
___
*[`crates/prover/src/core/backend/mod.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/stwo/710#-O1z_zce-QYVKNWYg84p:-O2-5Jat65OPRahzvUIe:bheftls) ([raw file](https://github.com/starkware-libs/stwo/blob/d21df66d9265ec97f8327c2a9c0b6309e484ee55/crates/prover/src/core/backend/mod.rs#L51)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Do we want to mention that this function is slow, and shouldn't be used much?
Specially for simd
</blockquote></details>

There is no way to be mistaken about it. It returns a non packed element. Also, it's just the coutnerpart of at().

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/710#-:-O2-9AlH4rSRtuRrexXo:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
