### PR TITLE
PCS benchmark.

### PR DESCRIPTION
**Pull request by Alon-Ti**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/766)

### CODE REVIEW

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/766)* status: all files reviewed, 4 unresolved discussions (waiting on @Alon-Ti and @ohad-starkware)

___
*[`crates/prover/benches/pcs.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/stwo/766#-O2zp-df0C7iO0od5_mJ:-O2zp-dgAnQ7-WrSPv_v:bb7kry6) ([raw file](https://github.com/starkware-libs/stwo/blob/b24f86f0ab9b3e6944970cd7e1158dfcb420a414/crates/prover/benches/pcs.rs#L37)):*
> ```XML
>     let small_domain = CanonicCoset::new(LOG_COSET_SIZE);
> 
>     let twiddles = B::precompute_twiddles(big_domain.half_coset());
> ```

Remove empty line



_Suggestion:_
```XML
    let small_domain = CanonicCoset::new(LOG_COSET_SIZE);
    let big_domain = CanonicCoset::new(LOG_COSET_SIZE + LOG_BLOWUP_FACTOR);
    let twiddles = B::precompute_twiddles(big_domain.half_coset());
```
___
*[`crates/prover/benches/pcs.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/stwo/766#-O2zp6tM1aHnCAYjkpU8:-O2zp6tM1aHnCAYjkpU9:bym0xew) ([raw file](https://github.com/starkware-libs/stwo/blob/b24f86f0ab9b3e6944970cd7e1158dfcb420a414/crates/prover/benches/pcs.rs#L40)):*
> ```XML
> 
>     let initial_digest = Blake2sHash::from(vec![0; 32]);
>     let mut channel = Blake2sChannel::new(initial_digest);
> ```

https://wiki.c2.com/?ArrangeActAssert



_Suggestion:_
```XML
    let mut channel = Blake2sChannel::new(Blake2sHash::default());
```
___
*[`crates/prover/benches/pcs.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/stwo/766#-O2zqEGo9SXHAhE9c2LX:-O2zqEGo9SXHAhE9c2LY:b-za4k5p) ([raw file](https://github.com/starkware-libs/stwo/blob/b24f86f0ab9b3e6944970cd7e1158dfcb420a414/crates/prover/benches/pcs.rs#L49)):*
> ```XML
>     })
>     .take(N_POLYS)
>     .collect();
> ```

Please use different elements for the eval.
That way the your polynomials are constant.



_Code quote:_
```XML
    let evals: Vec<CircleEvaluation<B, BaseField, BitReversedOrder>> = iter::repeat_with(|| {
        CircleEvaluation::new(
            small_domain.circle_domain(),
            (0..1 << LOG_COSET_SIZE).map(BaseField::from).collect(),
        )
    })
    .take(N_POLYS)
    .collect();
```
___
*[`crates/prover/benches/pcs.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/stwo/766#-O2zqLkjAXiaZYufsCHJ:-O2zqLkjAXiaZYufsCHK:byquo9c) ([raw file](https://github.com/starkware-libs/stwo/blob/b24f86f0ab9b3e6944970cd7e1158dfcb420a414/crates/prover/benches/pcs.rs#L76)):*
> ```XML
> criterion_group!(
>     name = benches;
>     config = Criterion::default().sample_size(10);
> ```

Do we need that?



_Code quote:_
```XML
.sample_size(10);
```

**Review by Alon-Ti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/766)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`crates/prover/benches/pcs.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/stwo/766#-O2zp-df0C7iO0od5_mJ:-O32TKxz8aLS3ar9Okaz:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/b24f86f0ab9b3e6944970cd7e1158dfcb420a414/crates/prover/benches/pcs.rs#L37)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Remove empty line
</blockquote></details>

Done.
___
*[`crates/prover/benches/pcs.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/stwo/766#-O2zp6tM1aHnCAYjkpU8:-O32VOU1EN3QxdqtC2Bg:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/b24f86f0ab9b3e6944970cd7e1158dfcb420a414/crates/prover/benches/pcs.rs#L40)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

https://wiki.c2.com/?ArrangeActAssert
</blockquote></details>

Done.
___
*[`crates/prover/benches/pcs.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/stwo/766#-O2zqEGo9SXHAhE9c2LX:-O32V41L44l2H1glx5C9:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/b24f86f0ab9b3e6944970cd7e1158dfcb420a414/crates/prover/benches/pcs.rs#L49)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Please use different elements for the eval.
That way the your polynomials are constant.
</blockquote></details>

Done.
___
*[`crates/prover/benches/pcs.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/stwo/766#-O2zqLkjAXiaZYufsCHJ:-O32VBO7DF3Ruc9cCp82:b-ihgm2c) ([raw file](https://github.com/starkware-libs/stwo/blob/b24f86f0ab9b3e6944970cd7e1158dfcb420a414/crates/prover/benches/pcs.rs#L76)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Do we need that?
</blockquote></details>

All the other benches have a sample size 10, it smooths over the lengths a bit.

**Review by ohad-starkware — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/766#-:-O36PDkYEUwP9LnJpWUG:bnfp4nl)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @Alon-Ti and @shaharsamocha7)

___
*[`crates/prover/benches/pcs.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/stwo/766#-O2zqLkjAXiaZYufsCHJ:-O36Ow9yCWQIz-fka6Ce:b9ge02t) ([raw file](https://github.com/starkware-libs/stwo/blob/b24f86f0ab9b3e6944970cd7e1158dfcb420a414/crates/prover/benches/pcs.rs#L76)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

All the other benches have a sample size 10, it smooths over the lengths a bit.
</blockquote></details>

yes, criterion's default is to do 100 rounds, which would be 100 seconds here.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/766#-:-O37Hlx_8jDNq1Tebrio:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Alon-Ti)

**Pull request merged**
