### PR TITLE
Separate ifft

### PR DESCRIPTION
**Pull request by spapinistarkware**
Separate ifft

Copied ifft into fft

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/389)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`src/core/backend/avx512/fft/mod.rs` line 131 at r2](https://reviewable.io/reviews/starkware-libs/stwo/389#-NsHXjeqDQcePV_v1e59:-NsHXjeqDQcePV_v1e5A:bn1jutp) ([raw file](https://github.com/starkware-libs/stwo/blob/a600463855cf37539ef86b4d3659139c390c31f8/src/core/backend/avx512/fft/mod.rs#L131)):*
> ```XML
> }
> 
> // TODO(spapini): Move these to M31 AVX.
> ```

still needed?



_Code quote:_
```XML
// TODO(spapini): Move these to M31 AVX.
```

**Comment by ilyalesokhin-starkware** [comment]
*[`src/core/backend/avx512/fft/rfft.rs` line 10 at r2](https://reviewable.io/reviews/starkware-libs/stwo/389#-NsHXscy-GsCeVYBFYQ8:-NsHXscy-GsCeVYBFYQ9:bowkymz) ([raw file](https://github.com/starkware-libs/stwo/blob/a600463855cf37539ef86b4d3659139c390c31f8/src/core/backend/avx512/fft/rfft.rs#L10)):*
> ```XML
>     LHALF_INTERLEAVE_LHALF, ODDS_INTERLEAVE_ODDS,
> };
> ```

what does r in `rfft` stand for? can you document the file?

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed 2 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/389)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/389)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`src/core/backend/avx512/fft/mod.rs` line 131 at r2](https://reviewable.io/reviews/starkware-libs/stwo/389#-NsHXjeqDQcePV_v1e59:-NsIWu5eCQTMgRIBMQIb:bt2nyrr) ([raw file](https://github.com/starkware-libs/stwo/blob/a600463855cf37539ef86b4d3659139c390c31f8/src/core/backend/avx512/fft/mod.rs#L131)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

still needed?
</blockquote></details>

I'll remove these in a different PR.
___
*[`src/core/backend/avx512/fft/rfft.rs` line 10 at r2](https://reviewable.io/reviews/starkware-libs/stwo/389#-NsHXscy-GsCeVYBFYQ8:-NsIWsYu1DQd0LS680sY:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/a600463855cf37539ef86b4d3659139c390c31f8/src/core/backend/avx512/fft/rfft.rs#L10)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

what does r in `rfft` stand for? can you document the file?
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/389#-:-NsJ6wKY3ZAMgC3T8hX6:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
