### PR TITLE
DomainAccumulator allows accumulating a row at once

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/480)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/480?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#480** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/480?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#479** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/479?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#478** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/478?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#463** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/463?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#477** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/477?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#476** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/476?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/480)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`src/core/air/accumulation.rs` line 107 at r3](https://reviewable.io/reviews/starkware-libs/stwo/480#-NtjWDqs2iEOzHOvs196:-NtjWDqs2iEOzHOvs197:b-7t9emc) ([raw file](https://github.com/starkware-libs/stwo/blob/7eaa3053a4170ebcc7b906eafb270404f8846c98/src/core/air/accumulation.rs#L107)):*
> ```XML
>             .unwrap_or_else(|e| panic!("invalid log_sizes: {}", e))
>             .map(|c| ColumnAccumulator {
>                 random_coeff_pow: self.random_coeff,
> ```

I don't understand this, seems that it always get the same element.
Why not give the ColumnAccumulator the correct pow in advance?

(I thought this change reduces the need of exposing the random coeff from this struct)



_Code quote:_
```XML
random_coeff_pow: self.random_coeff,
```
___
*[`src/core/air/accumulation.rs` line 112 at r3](https://reviewable.io/reviews/starkware-libs/stwo/480#-NtjVaxb8R3QGLfKOCBT:-NtjVaxb8R3QGLfKOCBU:b-e4geuz) ([raw file](https://github.com/starkware-libs/stwo/blob/7eaa3053a4170ebcc7b906eafb270404f8846c98/src/core/air/accumulation.rs#L112)):*
> ```XML
>         for i in 0..N {
>             res[i].random_coeff_pow = self.random_coeff.pow(n_cols_per_size[i].1 as u128);
>         }
> ```

Don't we want to calculate the powers more efficiently?



_Code quote:_
```XML
        for i in 0..N {
            res[i].random_coeff_pow = self.random_coeff.pow(n_cols_per_size[i].1 as u128);
        }
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/480)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7)

___
*[`src/core/air/accumulation.rs` line 107 at r3](https://reviewable.io/reviews/starkware-libs/stwo/480#-NtjWDqs2iEOzHOvs196:-NtkRAhS1ajHgOswbyT1:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/7eaa3053a4170ebcc7b906eafb270404f8846c98/src/core/air/accumulation.rs#L107)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I don't understand this, seems that it always get the same element.
Why not give the ColumnAccumulator the correct pow in advance?

(I thought this change reduces the need of exposing the random coeff from this struct)
</blockquote></details>

Done.
___
*[`src/core/air/accumulation.rs` line 112 at r3](https://reviewable.io/reviews/starkware-libs/stwo/480#-NtjVaxb8R3QGLfKOCBT:-NtkRAWb8bGKZUWLRl40:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/7eaa3053a4170ebcc7b906eafb270404f8846c98/src/core/air/accumulation.rs#L112)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Don't we want to calculate the powers more efficiently?
</blockquote></details>

Done.

**Review by shaharsamocha7 — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/480)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Comment by spapinistarkware** [comment]
### Merge activity

* **Mar 24, 9:16 AM EDT**: @spapinistarkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/480).

**Pull request merged**
