### PR TITLE
Framework component

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/761)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/761?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#761** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/761?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#712** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/712?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#711** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/711?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#710** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/710?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#708** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/708?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#707** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/707?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#715** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/715?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#714** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/714?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#713** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/713?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#706** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/706?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#705** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/705?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#704** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/704?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#702** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/702?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#701** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/701?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/761)* status: 2 of 4 files reviewed, 6 unresolved discussions (waiting on @spapinistarkware)

___
*[`.gitignore` line 7 at r2](https://reviewable.io/reviews/starkware-libs/stwo/761#-O2tCdIB0B8M8JZbbA_t:-O2tCdIB0B8M8JZbbA_u:b2tpq4o) ([raw file](https://github.com/starkware-libs/stwo/blob/d53d91fcf8c41a0f61ed72706fb99bbad0f4f4ca/.gitignore#L7)):*
> ```ignore
> build
> dist
> target*
> ```

It's a folder, right?



_Suggestion:_
```ignore
target/*
```
___
*[`crates/prover/src/constraint_framework/component.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/stwo/761#-O2tEXtm4zDQt8lJFuMn:-O2tEXtnCXkEmyNpRaJ0:b-y2vzej) ([raw file](https://github.com/starkware-libs/stwo/blob/d53d91fcf8c41a0f61ed72706fb99bbad0f4f4ca/crates/prover/src/constraint_framework/component.rs#L20)):*
> ```XML
> use crate::core::{utils, InteractionElements, LookupValues};
> 
> pub trait FrameworkComponent {
> ```

Document
This framework supports components that allow only constraints inside the row right? (or lookup)
Also, it assumes that all the rows (for specific interaction) are of the same length, no?



_Code quote:_
```XML
pub trait FrameworkComponent {
```
___
*[`crates/prover/src/constraint_framework/component.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/stwo/761#-O2tFXF1628tHLVifKHZ:-O2tFXF1628tHLVifKH_:bh9xnao) ([raw file](https://github.com/starkware-libs/stwo/blob/d53d91fcf8c41a0f61ed72706fb99bbad0f4f4ca/crates/prover/src/constraint_framework/component.rs#L50)):*
> ```XML
>     ) -> crate::core::pcs::TreeVec<
>         crate::core::ColumnVec<
>             Vec<crate::core::circle::CirclePoint<crate::core::fields::qm31::SecureField>>,
> ```

In all of them



_Suggestion:_
```XML
SecureField
```
___
*[`crates/prover/src/constraint_framework/component.rs` line 65 at r2](https://reviewable.io/reviews/starkware-libs/stwo/761#-O2tGK1j-ebhEQpNKv9S:-O2tGK1j-ebhEQpNKv9T:bsqvl3i) ([raw file](https://github.com/starkware-libs/stwo/blob/d53d91fcf8c41a0f61ed72706fb99bbad0f4f4ca/crates/prover/src/constraint_framework/component.rs#L65)):*
> ```XML
>                 })
>                 .collect()
>         })
> ```

You can use this:
https://github.com/starkware-libs/stwo/blob/a5e69d9fccec5af095667a89c05607399727f139/crates/prover/src/core/air/mask.rs#L36



_Code quote:_
```XML
        info.mask_offsets.map(|tree_mask| {
            tree_mask
                .iter()
                .map(|col_mask| {
                    col_mask
                        .iter()
                        .map(|off| point + trace_step.mul_signed(*off).into_ef())
                        .collect()
                })
                .collect()
        })
```
___
*[`crates/prover/src/constraint_framework/component.rs` line 100 at r2](https://reviewable.io/reviews/starkware-libs/stwo/761#-O2tH2wQ9tp4BN0J3wKn:-O2tH2wQ9tp4BN0J3wKo:b50vvyg) ([raw file](https://github.com/starkware-libs/stwo/blob/d53d91fcf8c41a0f61ed72706fb99bbad0f4f4ca/crates/prover/src/constraint_framework/component.rs#L100)):*
> ```XML
>         let trace: TreeVec<
>             Vec<Cow<'_, CircleEvaluation<SimdBackend, BaseField, BitReversedOrder>>>,
>         > = if eval_domain.log_size() != self.log_size() + LOG_BLOWUP_FACTOR {
> ```

I think you want it only in case that the eval_domain is bigger, no?



_Suggestion:_
```XML
if eval_domain.log_size() > self.log_size() + LOG_BLOWUP_FACTOR
```
___
*[`crates/prover/src/constraint_framework/component.rs` line 151 at r2](https://reviewable.io/reviews/starkware-libs/stwo/761#-O2tHaKnCUK0noFUvsFG:-O2tHaKnCUK0noFUvsFH:byrbzgb) ([raw file](https://github.com/starkware-libs/stwo/blob/d53d91fcf8c41a0f61ed72706fb99bbad0f4f4ca/crates/prover/src/constraint_framework/component.rs#L151)):*
> ```XML
>     fn lookup_values(&self, _trace: &ComponentTrace<'_, SimdBackend>) -> LookupValues {
>         LookupValues::default()
>     }
> ```

What's that, is it unimplemented?



_Code quote:_
```XML
    fn lookup_values(&self, _trace: &ComponentTrace<'_, SimdBackend>) -> LookupValues {
        LookupValues::default()
    }
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/761)* status: 2 of 4 files reviewed, 6 unresolved discussions (waiting on @shaharsamocha7)

___
*[`.gitignore` line 7 at r2](https://reviewable.io/reviews/starkware-libs/stwo/761#-O2tCdIB0B8M8JZbbA_t:-O2tIaVf0pbXyzuafFrc:bxswfv1) ([raw file](https://github.com/starkware-libs/stwo/blob/d53d91fcf8c41a0f61ed72706fb99bbad0f4f4ca/.gitignore#L7)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

It's a folder, right?
</blockquote></details>

No, it's another target folder. I'm using targetavx for my avx compilations, so it won't interfere with the IDE.
___
*[`crates/prover/src/constraint_framework/component.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/stwo/761#-O2tEXtm4zDQt8lJFuMn:-O2tJGtL5nuBWZmgL18j:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/d53d91fcf8c41a0f61ed72706fb99bbad0f4f4ca/crates/prover/src/constraint_framework/component.rs#L20)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Document
This framework supports components that allow only constraints inside the row right? (or lookup)
Also, it assumes that all the rows (for specific interaction) are of the same length, no?
</blockquote></details>

Done.
___
*[`crates/prover/src/constraint_framework/component.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/stwo/761#-O2tFXF1628tHLVifKHZ:-O2tJSaO8YiDpgdvf_yM:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/d53d91fcf8c41a0f61ed72706fb99bbad0f4f4ca/crates/prover/src/constraint_framework/component.rs#L50)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

In all of them
</blockquote></details>

Done.
___
*[`crates/prover/src/constraint_framework/component.rs` line 65 at r2](https://reviewable.io/reviews/starkware-libs/stwo/761#-O2tGK1j-ebhEQpNKv9S:-O2tJwLI4jg0B9lIZWeO:b-x6b4og) ([raw file](https://github.com/starkware-libs/stwo/blob/d53d91fcf8c41a0f61ed72706fb99bbad0f4f4ca/crates/prover/src/constraint_framework/component.rs#L65)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

You can use this:
https://github.com/starkware-libs/stwo/blob/a5e69d9fccec5af095667a89c05607399727f139/crates/prover/src/core/air/mask.rs#L36
</blockquote></details>

I'd have to createa a vector of domains though...
___
*[`crates/prover/src/constraint_framework/component.rs` line 100 at r2](https://reviewable.io/reviews/starkware-libs/stwo/761#-O2tH2wQ9tp4BN0J3wKn:-O2tMHjf4LFDmZoN05XN:bqruhsn) ([raw file](https://github.com/starkware-libs/stwo/blob/d53d91fcf8c41a0f61ed72706fb99bbad0f4f4ca/crates/prover/src/constraint_framework/component.rs#L100)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I think you want it only in case that the eval_domain is bigger, no?
</blockquote></details>

Theoretically, yes. But we need to do modifications to reuse the commitment evaluation in that case, which I don't want to write now. The way I wrote now, if , it's correct in that case, although, not as efficient is it could be.
___
*[`crates/prover/src/constraint_framework/component.rs` line 151 at r2](https://reviewable.io/reviews/starkware-libs/stwo/761#-O2tHaKnCUK0noFUvsFG:-O2tNNSG-bp83sAQ5q2n:b3gq6cq) ([raw file](https://github.com/starkware-libs/stwo/blob/d53d91fcf8c41a0f61ed72706fb99bbad0f4f4ca/crates/prover/src/constraint_framework/component.rs#L151)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

What's that, is it unimplemented?
</blockquote></details>

Don't need lookup_values in this interface.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/761)* status: all files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/constraint_framework/component.rs` line 65 at r2](https://reviewable.io/reviews/starkware-libs/stwo/761#-O2tGK1j-ebhEQpNKv9S:-O2tdlAT3FzuMHLTsWkq:b-pbgxlv) ([raw file](https://github.com/starkware-libs/stwo/blob/d53d91fcf8c41a0f61ed72706fb99bbad0f4f4ca/crates/prover/src/constraint_framework/component.rs#L65)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I'd have to createa a vector of domains though...
</blockquote></details>

should we change that function to get trace_step instead of domains?
Not necessarily for this pr
___
*[`crates/prover/src/constraint_framework/component.rs` line 100 at r2](https://reviewable.io/reviews/starkware-libs/stwo/761#-O2tH2wQ9tp4BN0J3wKn:-O2te2RX2-CRHiCLbjTh:brjvuvm) ([raw file](https://github.com/starkware-libs/stwo/blob/d53d91fcf8c41a0f61ed72706fb99bbad0f4f4ca/crates/prover/src/constraint_framework/component.rs#L100)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Theoretically, yes. But we need to do modifications to reuse the commitment evaluation in that case, which I don't want to write now. The way I wrote now, if , it's correct in that case, although, not as efficient is it could be.
</blockquote></details>

Can you add a TODO to consider to optimize that?
___
*[`crates/prover/src/constraint_framework/component.rs` line 25 at r3](https://reviewable.io/reviews/starkware-libs/stwo/761#-O2tdLqj2U2eUo_U0aAF:-O2tdLqj2U2eUo_U0aAG:bb7phvt) ([raw file](https://github.com/starkware-libs/stwo/blob/deaefadc134668a4b90ee5ea8aab077175edebde/crates/prover/src/constraint_framework/component.rs#L25)):*
> ```XML
> /// Implementing this trait introduces implementations for [Component] and [ComponentProver] for the
> /// SIMD backend.
> /// Note that the constraint framework only support components with columns of the size size.
> ```

typo



_Suggestion:_
```XML
/// Note that the constraint framework only support components with columns of the same size.
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/761)* status: all files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/component.rs` line 65 at r2](https://reviewable.io/reviews/starkware-libs/stwo/761#-O2tGK1j-ebhEQpNKv9S:-O2yiqjLALnJI9o3tCio:b-ttntz9) ([raw file](https://github.com/starkware-libs/stwo/blob/d53d91fcf8c41a0f61ed72706fb99bbad0f4f4ca/crates/prover/src/constraint_framework/component.rs#L65)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

should we change that function to get trace_step instead of domains?
Not necessarily for this pr
</blockquote></details>

Perhaps. It really depends on the concrete use cases of that function. For example, if we'd stop having any uses of it, we could delete it.
___
*[`crates/prover/src/constraint_framework/component.rs` line 100 at r2](https://reviewable.io/reviews/starkware-libs/stwo/761#-O2tH2wQ9tp4BN0J3wKn:-O2yjDLk2mPRT6cfYPVP:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/d53d91fcf8c41a0f61ed72706fb99bbad0f4f4ca/crates/prover/src/constraint_framework/component.rs#L100)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can you add a TODO to consider to optimize that?
</blockquote></details>

Done.
___
*[`crates/prover/src/constraint_framework/component.rs` line 25 at r3](https://reviewable.io/reviews/starkware-libs/stwo/761#-O2tdLqj2U2eUo_U0aAF:-O2yilGdBPFilxM3tegb:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/deaefadc134668a4b90ee5ea8aab077175edebde/crates/prover/src/constraint_framework/component.rs#L25)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

typo
</blockquote></details>

Done.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/761#-:-O2yurm7E0xQN1mur10S:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Comment by spapinistarkware** [comment]
### Merge activity

* **Jul 30, 9:05 AM EDT**: @spapinistarkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/761).

**Pull request merged**
