### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/564)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
* **#564** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/564?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by andrewmilson — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/564)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`src/core/backend/avx512/mod.rs` line 219 at r1](https://reviewable.io/reviews/starkware-libs/stwo/564#-NvWnA91D5KvN3ySf7J8:-NvWnA91D5KvN3ySf7J9:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/d6ded725688f079dfdd198313d6c2c065ac4f80c/src/core/backend/avx512/mod.rs#L219)):*
> ```XML
> 
> impl SecureColumn<AVX512Backend> {
>     /// Safety: `vec_index` must be a valid index.
> ```





_Suggestion:_
```XML
/// # Safety
/// 
/// `vec_index` must be a valid index.
```
___
*[`src/core/backend/avx512/mod.rs` line 233 at r1](https://reviewable.io/reviews/starkware-libs/stwo/564#-NvWnGtJ7oGrJxS42ppB:-NvWnGtKDNDgE-aWlmgB:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/d6ded725688f079dfdd198313d6c2c065ac4f80c/src/core/backend/avx512/mod.rs#L233)):*
> ```XML
>     }
> 
>     /// Safety: `vec_index` must be a valid index.
> ```





_Suggestion:_
```XML
/// # Safety
/// 
/// `vec_index` must be a valid index.
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/564)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @andrewmilson)

___
*[`src/core/backend/avx512/mod.rs` line 219 at r1](https://reviewable.io/reviews/starkware-libs/stwo/564#-NvWnA91D5KvN3ySf7J8:-NvahWLZ-nNsxPjbD4qA:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/d6ded725688f079dfdd198313d6c2c065ac4f80c/src/core/backend/avx512/mod.rs#L219)):*
> ```XML
> 
> impl SecureColumn<AVX512Backend> {
>     /// Safety: `vec_index` must be a valid index.
> ```

Done.
___
*[`src/core/backend/avx512/mod.rs` line 233 at r1](https://reviewable.io/reviews/starkware-libs/stwo/564#-NvWnGtJ7oGrJxS42ppB:-NvahWds4r8zEm1wkxYM:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/d6ded725688f079dfdd198313d6c2c065ac4f80c/src/core/backend/avx512/mod.rs#L233)):*
> ```XML
>     }
> 
>     /// Safety: `vec_index` must be a valid index.
> ```

Done.

**Review by andrewmilson — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/564#-:-Nvaqsmd5iIbyQPms6Rr:bnfp4nl)* status: 0 of 3 files reviewed, 2 unresolved discussions

**Review by andrewmilson — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/564#-:-NvcM4uk3WPBRkQtTk4g:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
