### PR TITLE
Add prove verification error.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/498)

### CODE REVIEW

**Comment by alonh5** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/498?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#498** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/498?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#470** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/470?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#468** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/468?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/498#-:-NtBYbp-DdsGppD32t2J:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @andrewmilson and @shaharsamocha7)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/498#-:-NtGQm707sOdRX8kI0dv:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @andrewmilson and @shaharsamocha7)

**Review by andrewmilson — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/498#-:-NtJwfxhCaYSQPHeHl_l:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @shaharsamocha7)

___
*[`src/core/prover/mod.rs` line 304 at r3](https://reviewable.io/reviews/starkware-libs/stwo/498#-NtJvWb97xr4I9x2eBAH:-NtJvWb97xr4I9x2eBAI:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/0bd7ba73615dedeaa8c2e1b794b64d8580d014d8/src/core/prover/mod.rs#L304)):*
> ```XML
> pub enum VerificationError {
>     #[error(transparent)]
>     FriVerificationError(#[from] FriVerificationError),
> ```





_Suggestion:_
```XML
Fri(#[from] FriVerificationError),
```

**Review by shaharsamocha7 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/498)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/498)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @andrewmilson and @spapinistarkware)

___
*[`src/core/prover/mod.rs` line 304 at r3](https://reviewable.io/reviews/starkware-libs/stwo/498#-NtJvWb97xr4I9x2eBAH:-NtL5Mk7C1uN45QBia6v:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/0bd7ba73615dedeaa8c2e1b794b64d8580d014d8/src/core/prover/mod.rs#L304)):*
> ```XML
> pub enum VerificationError {
>     #[error(transparent)]
>     FriVerificationError(#[from] FriVerificationError),
> ```

Done.

**Review by andrewmilson — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/498#-:-NtM7Sx03NsGWJ7avVx-:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Comment by alonh5** [comment]
### Merge activity

* **Mar 20, 4:13 AM EDT**: @alonh5 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/498).

**Pull request merged**
