### PR TITLE
Add final lookup constraint.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/667)

### CODE REVIEW

**Comment by alonh5** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/667?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#667** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/667?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#664** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/664?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#662** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/662?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#646** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/646?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#644** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/644?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#654](https://github.com/starkware-libs/stwo/pull/654) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/654?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#642** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/642?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#639** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/639?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#638** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/638?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#637** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/637?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#636** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/636?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#651** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/651?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/667)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @alonh5 and @spapinistarkware)

___
*[`crates/prover/src/examples/wide_fibonacci/constraint_eval.rs` line 199 at r2](https://reviewable.io/reviews/starkware-libs/stwo/667#-O0mQp0d003QdkIg_vXk:-O0mQp0d003QdkIg_vXl:b-gpa8) ([raw file](https://github.com/starkware-libs/stwo/blob/d76e1de4a773e938c0c6900a6fe45e2f76115f73/crates/prover/src/examples/wide_fibonacci/constraint_eval.rs#L199)):*
> ```XML
>                         &[
>                             lookup_values[LOOKUP_VALUE_N_MINUS_2_ID],
>                             lookup_values[LOOKUP_VALUE_N_MINUS_1_ID],
> ```

Those should be fetched at the beginning of the function instead of reading it for each numerator calculation



_Code quote:_
```XML
                            lookup_values[LOOKUP_VALUE_N_MINUS_2_ID],
                            lookup_values[LOOKUP_VALUE_N_MINUS_1_ID],
```
___
*[`crates/prover/src/examples/wide_fibonacci/constraint_eval.rs` line 211 at r2](https://reviewable.io/reviews/starkware-libs/stwo/667#-O0mPxlWErnD9Sa_VRfT:-O0mPxlWErnD9Sa_VRfU:bgg1bkt) ([raw file](https://github.com/starkware-libs/stwo/blob/d76e1de4a773e938c0c6900a6fe45e2f76115f73/crates/prover/src/examples/wide_fibonacci/constraint_eval.rs#L211)):*
> ```XML
>                         alpha,
>                         z,
>                     ));
> ```

This can be a shared utility function for both the step constraint and the boundary constraint



_Code quote:_
```XML
                * ((value
                    * shifted_secure_combination(
                        &[
                            lookup_values[LOOKUP_VALUE_N_MINUS_2_ID],
                            lookup_values[LOOKUP_VALUE_N_MINUS_1_ID],
                        ],
                        alpha,
                        z,
                    ))
                    - shifted_secure_combination(
                        &[
                            lookup_values[LOOKUP_VALUE_0_ID],
                            lookup_values[LOOKUP_VALUE_1_ID],
                        ],
                        alpha,
                        z,
                    ));
```
___
*[`crates/prover/src/examples/wide_fibonacci/constraint_eval.rs` line 327 at r2](https://reviewable.io/reviews/starkware-libs/stwo/667#-O0mOunz3rOhXYKWEXVP:-O0mOunz3rOhXYKWEXVQ:bgccf5o) ([raw file](https://github.com/starkware-libs/stwo/blob/d76e1de4a773e938c0c6900a6fe45e2f76115f73/crates/prover/src/examples/wide_fibonacci/constraint_eval.rs#L327)):*
> ```XML
>             zero_domain,
>             &mut accum,
>         );
> ```

It would be more efficient to evaluate the numerators together
and the denominators together (i.e. in the same for loop)

That way the memory access pattern is more efficient



_Code quote:_
```XML
        self.evaluate_trace_boundary_constraints(
            trace_evals,
            trace_eval_domain,
            zero_domain,
            &mut accum,
            lookup_values,
        );
        self.evaluate_lookup_step_constraints(
            trace_evals,
            trace_eval_domain,
            zero_domain,
            &mut accum,
            interaction_elements,
        );
        self.evaluate_lookup_boundary_constraints(
            trace_evals,
            trace_eval_domain,
            zero_domain,
            &mut accum,
            interaction_elements,
            lookup_values,
        );
        self.evaluate_trace_step_constraints(
            trace_evals,
            trace_eval_domain,
            zero_domain,
            &mut accum,
        );
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/667)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/examples/wide_fibonacci/constraint_eval.rs` line 199 at r2](https://reviewable.io/reviews/starkware-libs/stwo/667#-O0mQp0d003QdkIg_vXk:-O0nJkUq8UOJ9chn63rl:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/d76e1de4a773e938c0c6900a6fe45e2f76115f73/crates/prover/src/examples/wide_fibonacci/constraint_eval.rs#L199)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Those should be fetched at the beginning of the function instead of reading it for each numerator calculation
</blockquote></details>

Done.
___
*[`crates/prover/src/examples/wide_fibonacci/constraint_eval.rs` line 211 at r2](https://reviewable.io/reviews/starkware-libs/stwo/667#-O0mPxlWErnD9Sa_VRfT:-O0nQdwW3G7ypzBZdS9S:b41xog5) ([raw file](https://github.com/starkware-libs/stwo/blob/d76e1de4a773e938c0c6900a6fe45e2f76115f73/crates/prover/src/examples/wide_fibonacci/constraint_eval.rs#L211)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

This can be a shared utility function for both the step constraint and the boundary constraint
</blockquote></details>

I tried it and it didn't really save lines of code, so I'll leave it as is for now.
___
*[`crates/prover/src/examples/wide_fibonacci/constraint_eval.rs` line 327 at r2](https://reviewable.io/reviews/starkware-libs/stwo/667#-O0mOunz3rOhXYKWEXVP:-O0nKAvC1Ez7UF22cF3I:b-7yd1q4) ([raw file](https://github.com/starkware-libs/stwo/blob/d76e1de4a773e938c0c6900a6fe45e2f76115f73/crates/prover/src/examples/wide_fibonacci/constraint_eval.rs#L327)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

It would be more efficient to evaluate the numerators together
and the denominators together (i.e. in the same for loop)

That way the memory access pattern is more efficient
</blockquote></details>

Added a TODO.

**Review by shaharsamocha7 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/667)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/667#-:-O0xRfxD1LaZSuymJP25:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/667#-:-O1FtA8v-kTHc2oUvPxJ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Comment by alonh5** [comment]
### Merge activity

* **Jul 8, 4:33 AM EDT**: @alonh5 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/667).

**Pull request merged**
