### PR TITLE
Add SIMD prefix sum

### PR DESCRIPTION
**Pull request by andrewmilson**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/729)

### CODE REVIEW

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/729#-:-O1uaQvuA48_nbcEV_st:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @andrewmilson)

**Review by spapinistarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/729)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @andrewmilson)

___
*[`crates/prover/src/examples/xor/prefix_sum/mod.rs` line 93 at r1](https://reviewable.io/reviews/starkware-libs/stwo/729#-O1v_nD0CNHvw3PPd89H:-O1v_nD0CNHvw3PPd89I:b-j4fgsk) ([raw file](https://github.com/starkware-libs/stwo/blob/62c63fd92a6fc44b68532cb7334b11e4f71ceadf/crates/prover/src/examples/xor/prefix_sum/mod.rs#L93)):*
> ```XML
> /// <https://developer.nvidia.com/gpugems/gpugems3/part-vi-gpu-computing/chapter-39-parallel-prefix-sum-scan-cuda>
> pub fn exclusive_prefix_sum_simd(
>     eval: CircleEvaluation<SimdBackend, BaseField, BitReversedOrder>,
> ```

Can you change this to just Col<SimdBackend, BaseField> ?

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/729)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`crates/prover/src/examples/xor/prefix_sum/mod.rs` line 93 at r1](https://reviewable.io/reviews/starkware-libs/stwo/729#-O1v_nD0CNHvw3PPd89H:-O1yO1WB1iglTNpv2_7q:b5pbb8f) ([raw file](https://github.com/starkware-libs/stwo/blob/62c63fd92a6fc44b68532cb7334b11e4f71ceadf/crates/prover/src/examples/xor/prefix_sum/mod.rs#L93)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Can you change this to just Col<SimdBackend, BaseField> ?
</blockquote></details>

https://github.com/starkware-libs/stwo/pull/734

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/729)* status: all files reviewed, 1 unresolved discussion

___
*[`crates/prover/src/examples/xor/prefix_sum/mod.rs` line 214 at r1](https://reviewable.io/reviews/starkware-libs/stwo/729#-O1yq7c2-r_LimnCCS6v:-O1yq7c2-r_LimnCCS6w:b9q4i7f) ([raw file](https://github.com/starkware-libs/stwo/blob/62c63fd92a6fc44b68532cb7334b11e4f71ceadf/crates/prover/src/examples/xor/prefix_sum/mod.rs#L214)):*
> ```XML
>     *hi += *lo;
>     *lo = tmp;
> }
> ```

Do these changes for inclusive



_Suggestion:_
```XML
fn up_sweep_val<F: AddAssign + Copy>(lo: F, hi: &mut F) {
    *lo += hi;
}

fn down_sweep_val<F: AddAssign + Copy>(lo: &mut F, hi: &mut F) {
    (*lo, *hi) = (*lo - *hi, *lo)
}
```

**Pull request closed without merging**
