### PR TITLE
Remove wide fibonacci boundary constraint.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/582)

### CODE REVIEW

**Comment by alonh5** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/582?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#582** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/582?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#573** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/573?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#574](https://github.com/starkware-libs/stwo/pull/574) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/574?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#572** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/572?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#562** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/562?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/582)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/prover/src/examples/wide_fibonacci/avx.rs` line 89 at r2](https://reviewable.io/reviews/starkware-libs/stwo/582#-NyFfwr295fpmLcn3HhF:-NyFfwr295fpmLcn3HhG:b-xd5p2a) ([raw file](https://github.com/starkware-libs/stwo/blob/3f1588d944820712785ce898047cd54ec6cfbe48/crates/prover/src/examples/wide_fibonacci/avx.rs#L89)):*
> ```XML
>                     PackedBaseField::zero(),
>                     PackedBaseField::zero(),
>                 ]) * PackedSecureField::broadcast(accum.random_coeff_powers[self.n_columns() - 2]);
> ```

You also need to do the relevant changes in the component implementation.
I.e. you need to reduce the number of constraints by 1.



_Code quote:_
```XML
                PackedSecureField::from_packed_m31s([
                    a - PackedBaseField::one(),
                    PackedBaseField::zero(),
                    PackedBaseField::zero(),
                    PackedBaseField::zero(),
                ]) * PackedSecureField::broadcast(accum.random_coeff_powers[self.n_columns() - 2]);
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/582)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`crates/prover/src/examples/wide_fibonacci/avx.rs` line 89 at r2](https://reviewable.io/reviews/starkware-libs/stwo/582#-NyFfwr295fpmLcn3HhF:-NyFhbAaBSjHBmS3GL7O:b-i21bbo) ([raw file](https://github.com/starkware-libs/stwo/blob/3f1588d944820712785ce898047cd54ec6cfbe48/crates/prover/src/examples/wide_fibonacci/avx.rs#L89)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

You also need to do the relevant changes in the component implementation.
I.e. you need to reduce the number of constraints by 1.
</blockquote></details>

Thanks. Done.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/582#-:-NyJgfvG9xExaO8RNlzi:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Pull request merged**
