### PR TITLE
Add MLE eval constraints

### PR DESCRIPTION
**Pull request by andrewmilson**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/742)

### CODE REVIEW

**Comment by andrewmilson** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/742?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#742** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/742?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#741** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/741?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @andrewmilson and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/742)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @andrewmilson)

___
*[`crates/prover/src/examples/xor/mle_eval_constraints.rs` line 11 at r3](https://reviewable.io/reviews/starkware-libs/stwo/742#-O4EVN1M8WhsEGpgiAyN:-O4EVN1M8WhsEGpgiAyO:b-ccvcd2) ([raw file](https://github.com/starkware-libs/stwo/blob/ebd11992073282549f05793c26ed05db8b7611d5/crates/prover/src/examples/xor/mle_eval_constraints.rs#L11)):*
> ```XML
> pub fn mle_eval_check<E: EvalAtRow, const N_VARIABLES: usize>(
>     eval: &mut E,
>     point_meta: PointMeta<N_VARIABLES>,
> ```

I think this can be named better. What exactly does this hold?
Is it some precomuptation regarding the MLE evaluation point in EF^N_VARS ?
If so, maybe MleEvalPoint ?



_Code quote:_
```XML
PointMeta
```
___
*[`crates/prover/src/examples/xor/mle_eval_constraints.rs` line 12 at r3](https://reviewable.io/reviews/starkware-libs/stwo/742#-O4EWs8k45_J1QdYR5gJ:-O4EWs8k45_J1QdYR5gK:b5uynkm) ([raw file](https://github.com/starkware-libs/stwo/blob/ebd11992073282549f05793c26ed05db8b7611d5/crates/prover/src/examples/xor/mle_eval_constraints.rs#L12)):*
> ```XML
>     eval: &mut E,
>     point_meta: PointMeta<N_VARIABLES>,
>     mle_coeff: E::EF,
> ```

What's this?
___
*[`crates/prover/src/examples/xor/mle_eval_constraints.rs` line 15 at r3](https://reviewable.io/reviews/starkware-libs/stwo/742#-O4EWtvz2h06BSynF5qa:-O4EWtvz2h06BSynF5qb:b-japejw) ([raw file](https://github.com/starkware-libs/stwo/blob/ebd11992073282549f05793c26ed05db8b7611d5/crates/prover/src/examples/xor/mle_eval_constraints.rs#L15)):*
> ```XML
>     mle_claim: SecureField,
>     eq_evals_at: &EqEvalsMaskAt<E, N_VARIABLES>,
>     eq_evals_is: &EqEvalsMaskIs<E, N_VARIABLES>,
> ```

I don't understand what these are. Can they have better names?



_Code quote:_
```XML
    eq_evals_at: &EqEvalsMaskAt<E, N_VARIABLES>,
    eq_evals_is: &EqEvalsMaskIs<E, N_VARIABLES>,
```
___
*[`crates/prover/src/examples/xor/mle_eval_constraints.rs` line 23 at r3](https://reviewable.io/reviews/starkware-libs/stwo/742#-O4EWgki-Y4FzrnBuxQn:-O4EWgki-Y4FzrnBuxQo:b64ze4m) ([raw file](https://github.com/starkware-libs/stwo/blob/ebd11992073282549f05793c26ed05db8b7611d5/crates/prover/src/examples/xor/mle_eval_constraints.rs#L23)):*
> ```XML
>     eq_evals_check(eval, point_meta, eq_evals_at, eq_evals_is);
>     let mle_term = mle_coeff * eq_evals_at.curr;
>     inclusive_prefix_sum_check(eval, mle_term, mle_claim, eq_evals_is.first, prefix_sum_at);
> ```

Lior suggested another way to do the prefix check, without is_first. I implemented it in logup. The idea is to first subtract claimed_sum/N_ROWS from the values, so that their sum is 0. Now, we dont need is_first, because the diff constraint applies also at the transition from the last row to the first.
1. Consider using it.
2. Consider reusing code from logup.rs



_Code quote:_
```XML
inclusive_prefix_sum_check(eval, mle_term, mle_claim, eq_evals_is.first, prefix_sum_at);
```

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/742)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/examples/xor/mle_eval_constraints.rs` line 11 at r3](https://reviewable.io/reviews/starkware-libs/stwo/742#-O4EVN1M8WhsEGpgiAyN:-O4aL14z7RdrtYyaVHfx:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/ebd11992073282549f05793c26ed05db8b7611d5/crates/prover/src/examples/xor/mle_eval_constraints.rs#L11)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I think this can be named better. What exactly does this hold?
Is it some precomuptation regarding the MLE evaluation point in EF^N_VARS ?
If so, maybe MleEvalPoint ?
</blockquote></details>

Done.
___
*[`crates/prover/src/examples/xor/mle_eval_constraints.rs` line 12 at r3](https://reviewable.io/reviews/starkware-libs/stwo/742#-O4EWs8k45_J1QdYR5gJ:-O4aL5kWConVfAWpQCYl:b-bttoee) ([raw file](https://github.com/starkware-libs/stwo/blob/ebd11992073282549f05793c26ed05db8b7611d5/crates/prover/src/examples/xor/mle_eval_constraints.rs#L12)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

What's this?
</blockquote></details>

Added comment
___
*[`crates/prover/src/examples/xor/mle_eval_constraints.rs` line 15 at r3](https://reviewable.io/reviews/starkware-libs/stwo/742#-O4EWtvz2h06BSynF5qa:-O4aL860Cni52jmRCxBz:b26n5bb) ([raw file](https://github.com/starkware-libs/stwo/blob/ebd11992073282549f05793c26ed05db8b7611d5/crates/prover/src/examples/xor/mle_eval_constraints.rs#L15)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I don't understand what these are. Can they have better names?
</blockquote></details>

Refactored to just a single EqEvalsMask
___
*[`crates/prover/src/examples/xor/mle_eval_constraints.rs` line 23 at r3](https://reviewable.io/reviews/starkware-libs/stwo/742#-O4EWgki-Y4FzrnBuxQn:-O4aLDHv5bcJuTo4KFn7:bju7emp) ([raw file](https://github.com/starkware-libs/stwo/blob/ebd11992073282549f05793c26ed05db8b7611d5/crates/prover/src/examples/xor/mle_eval_constraints.rs#L23)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Lior suggested another way to do the prefix check, without is_first. I implemented it in logup. The idea is to first subtract claimed_sum/N_ROWS from the values, so that their sum is 0. Now, we dont need is_first, because the diff constraint applies also at the transition from the last row to the first.
1. Consider using it.
2. Consider reusing code from logup.rs
</blockquote></details>

Done 1.
Didn't do 2. as the code in logup.rs seems quite coupled to LogUp

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/742)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @andrewmilson)

___
*[`crates/prover/src/examples/xor/mle_eval_constraints.rs` line 7 at r4](https://reviewable.io/reviews/starkware-libs/stwo/742#-O4ixHtJ6QnGdweMwHHq:-O4iwh3D7xBMUxV8OsPq:bokkjro) ([raw file](https://github.com/starkware-libs/stwo/blob/79642f9c49b6df3e656cdfd6347de1250b103f6f/crates/prover/src/examples/xor/mle_eval_constraints.rs#L7)):*
> ```XML
> use crate::examples::xor::prefix_sum_constraints::PrefixSumMask;
> 
> pub struct MleEvalMask<E: EvalAtRow, const N_VARIABLES: usize> {
> ```

1. Like before, do we really need a struct here?
2. Do we need PrefixSumMask to be a struct? (e.g. does it hold preprocessed data shared by all rows?)
___
*[`crates/prover/src/examples/xor/mle_eval_constraints.rs` line 7 at r4](https://reviewable.io/reviews/starkware-libs/stwo/742#-O4ixYeQ0Pw4ojilkRpP:-O4ixYeQ0Pw4ojilkRpQ:b1dszo2) ([raw file](https://github.com/starkware-libs/stwo/blob/79642f9c49b6df3e656cdfd6347de1250b103f6f/crates/prover/src/examples/xor/mle_eval_constraints.rs#L7)):*
> ```XML
> use crate::examples::xor::prefix_sum_constraints::PrefixSumMask;
> 
> pub struct MleEvalMask<E: EvalAtRow, const N_VARIABLES: usize> {
> ```

This struct isn't really the Mask I believe, since you are not gonna use it externally as a mask item. It's only here to evaluate the constraints. Whether this stays a struct or becomes a function, rename it to something that conveys this evaluates constraints.
___
*[`crates/prover/src/examples/xor/mle_eval_constraints.rs` line 9 at r4](https://reviewable.io/reviews/starkware-libs/stwo/742#-O4ixqm06QyGjgRQfwmJ:-O4ixqm06QyGjgRQfwmK:b8jkxhv) ([raw file](https://github.com/starkware-libs/stwo/blob/79642f9c49b6df3e656cdfd6347de1250b103f6f/crates/prover/src/examples/xor/mle_eval_constraints.rs#L9)):*
> ```XML
> pub struct MleEvalMask<E: EvalAtRow, const N_VARIABLES: usize> {
>     /// Mask item on the column that interpolates all MLE coefficients in the lagrange basis.
>     mle_coeff: E::EF,
> ```

Is this a coeff or a mask item? Maybe it's a column value? whatever you chose, make the name and documentation consistent.

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/742)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/examples/xor/mle_eval_constraints.rs` line 7 at r4](https://reviewable.io/reviews/starkware-libs/stwo/742#-O4ixHtJ6QnGdweMwHHq:-O4k4giz3gi19lJNCczu:bss4a2b) ([raw file](https://github.com/starkware-libs/stwo/blob/79642f9c49b6df3e656cdfd6347de1250b103f6f/crates/prover/src/examples/xor/mle_eval_constraints.rs#L7)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

1. Like before, do we really need a struct here?
2. Do we need PrefixSumMask to be a struct? (e.g. does it hold preprocessed data shared by all rows?)
</blockquote></details>

Removed.
___
*[`crates/prover/src/examples/xor/mle_eval_constraints.rs` line 7 at r4](https://reviewable.io/reviews/starkware-libs/stwo/742#-O4ixYeQ0Pw4ojilkRpP:-O4n-bDR8AasjgpsX_if:b-zcjvte) ([raw file](https://github.com/starkware-libs/stwo/blob/79642f9c49b6df3e656cdfd6347de1250b103f6f/crates/prover/src/examples/xor/mle_eval_constraints.rs#L7)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

This struct isn't really the Mask I believe, since you are not gonna use it externally as a mask item. It's only here to evaluate the constraints. Whether this stays a struct or becomes a function, rename it to something that conveys this evaluates constraints.
</blockquote></details>

Thanks
___
*[`crates/prover/src/examples/xor/mle_eval_constraints.rs` line 9 at r4](https://reviewable.io/reviews/starkware-libs/stwo/742#-O4ixqm06QyGjgRQfwmJ:-O4n-gs6DjWoSXdyTBJe:bb6un1j) ([raw file](https://github.com/starkware-libs/stwo/blob/79642f9c49b6df3e656cdfd6347de1250b103f6f/crates/prover/src/examples/xor/mle_eval_constraints.rs#L9)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Is this a coeff or a mask item? Maybe it's a column value? whatever you chose, make the name and documentation consistent.
</blockquote></details>

Done

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/742#-:-O4nlBVz-wHU7O8-42oP:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @andrewmilson)

**Pull request merged**
