### PR TITLE
Add interaction_element_ids to Component trait.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/631)

### CODE REVIEW

**Comment by alonh5** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/631?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#631** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/631?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#582** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/582?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#589](https://github.com/starkware-libs/stwo/pull/589) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/589?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#573** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/573?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#574](https://github.com/starkware-libs/stwo/pull/574) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/574?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#572** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/572?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#562** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/562?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/631)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5 and @andrewmilson)

___
*[`crates/prover/src/core/mod.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/stwo/631#-NyU62WeCPJEzwzIuR6T:-NyU62WeCPJEzwzIuR6U:b-1zo43u) ([raw file](https://github.com/starkware-libs/stwo/blob/b3619fe7711f28563942ec4c1ba2fc4c3e565432/crates/prover/src/core/mod.rs#L63)):*
> ```XML
> }
> 
> pub struct InteractionElements(Vec<(String, BaseField)>);
> ```

This should be SecureField



_Code quote:_
```XML
BaseField
```
___
*[`crates/prover/src/core/air/air_ext.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/stwo/631#-NyU69Fa2qNHLgEH3tm6:-NyU69Fa2qNHLgEH3tm7:bjuq1hv) ([raw file](https://github.com/starkware-libs/stwo/blob/b3619fe7711f28563942ec4c1ba2fc4c3e565432/crates/prover/src/core/air/air_ext.rs#L53)):*
> ```XML
>                 .dedup()
>                 .map(|id| {
>                     let element = channel.draw_felt().0 .0;
> ```

Consider to draw all the elements together.
I think we have `draw_felts` function
Each channel hash could give you more then one element



_Code quote:_
```XML
channel.draw_felt().0
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/631)* status: all files reviewed, 2 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`crates/prover/src/core/mod.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/stwo/631#-NyU62WeCPJEzwzIuR6T:-NyUg6lO9AtNOyVb4zU9:bzhyh70) ([raw file](https://github.com/starkware-libs/stwo/blob/b3619fe7711f28563942ec4c1ba2fc4c3e565432/crates/prover/src/core/mod.rs#L63)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

This should be SecureField
</blockquote></details>

Right. I did this on purpose to add a constraint first more easily, and I plan to change it to a SecureField on top of this stack (there's  also a TODO for it).
___
*[`crates/prover/src/core/air/air_ext.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/stwo/631#-NyU69Fa2qNHLgEH3tm6:-NyUi-OW-TSyQWvMgFFz:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/b3619fe7711f28563942ec4c1ba2fc4c3e565432/crates/prover/src/core/air/air_ext.rs#L53)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Consider to draw all the elements together.
I think we have `draw_felts` function
Each channel hash could give you more then one element
</blockquote></details>

Done.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:
Please wait for @andrewmilson review

> Reviewed 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/631#-:-NyZRyfB5kok5AJqU4Kv:bsngaum)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @andrewmilson)

**Review by andrewmilson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/631)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/prover/src/core/mod.rs` line 63 at r3](https://reviewable.io/reviews/starkware-libs/stwo/631#-Ny_enLE9oVS_MgJG527:-Ny_enLE9oVS_MgJG528:b-q8s9n0) ([raw file](https://github.com/starkware-libs/stwo/blob/49b2acbdd73804f43122133c0473284734a13399/crates/prover/src/core/mod.rs#L63)):*
> ```XML
> }
> 
> pub struct InteractionElements(Vec<(String, BaseField)>);
> ```

Shouldn't this be SecureField?



_Code quote:_
```XML
BaseField
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/631)* status: all files reviewed, 1 unresolved discussion (waiting on @andrewmilson)

___
*[`crates/prover/src/core/mod.rs` line 63 at r3](https://reviewable.io/reviews/starkware-libs/stwo/631#-Ny_enLE9oVS_MgJG527:-NynkeRc8_qI_ZvQ2hXd:b-jhwf96) ([raw file](https://github.com/starkware-libs/stwo/blob/49b2acbdd73804f43122133c0473284734a13399/crates/prover/src/core/mod.rs#L63)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Shouldn't this be SecureField?
</blockquote></details>

Right. I did this on purpose to add a constraint first more easily, and I plan to change it to a SecureField on top of this stack (there's also a TODO for it).

**Review by andrewmilson — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/631#-:-Nyp9mYx9sPjIzyZhE4y:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/prover/src/core/air/mod.rs` line 44 at r3](https://reviewable.io/reviews/starkware-libs/stwo/631#-Nyg2W5EDWspBTt3WHGK:-Nyg2W5EDWspBTt3WHGL:b45h) ([raw file](https://github.com/starkware-libs/stwo/blob/49b2acbdd73804f43122133c0473284734a13399/crates/prover/src/core/air/mod.rs#L44)):*
> ```XML
>     ) -> ColumnVec<Vec<CirclePoint<SecureField>>>;
> 
>     // Returns the ids of the interaction elements used by the component.
> ```





_Suggestion:_
```XML
///
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/631)* status: all files reviewed, 1 unresolved discussion (waiting on @andrewmilson)

___
*[`crates/prover/src/core/air/mod.rs` line 44 at r3](https://reviewable.io/reviews/starkware-libs/stwo/631#-Nyg2W5EDWspBTt3WHGK:-NypGFWW27P9odPp3ECM:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/49b2acbdd73804f43122133c0473284734a13399/crates/prover/src/core/air/mod.rs#L44)):*
> ```XML
>     ) -> ColumnVec<Vec<CirclePoint<SecureField>>>;
> 
>     // Returns the ids of the interaction elements used by the component.
> ```

Done.

**Review by andrewmilson — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 6 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/631#-:-Nys-KhI2j5fDB8nPJ0g:bg7igkv)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @shaharsamocha7)

___
*[`crates/prover/src/core/air/air_ext.rs` line 55 at r4](https://reviewable.io/reviews/starkware-libs/stwo/631#-NyrxvEw67EjMF6NBBjM:-NyrxvEw67EjMF6NBBjN:bwzzv1d) ([raw file](https://github.com/starkware-libs/stwo/blob/ab4f4c110da3d854063419a3a717927c54804e07/crates/prover/src/core/air/air_ext.rs#L55)):*
> ```XML
>         let elements = channel.draw_felts(ids.len()).into_iter().map(|e| e.0 .0);
>         InteractionElements(zip_eq(ids, elements).collect_vec())
>     }
> ```

Optional: could use `BTreeSet<String>` for interaction_element_ids



_Suggestion:_
```XML
    fn interaction_elements(&self, channel: &mut Blake2sChannel) -> InteractionElements {
        let mut ids = BTreeSet::new();
        
        for component in self.components() {
            ids = &ids | &component.interaction_element_ids();
        }
        
        let elements = channel.draw_felts(ids.len()).into_iter().map(|e| e.0 .0);
        InteractionElements(zip_eq(ids, elements).collect_vec())
    }
```

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/631)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @andrewmilson and @shaharsamocha7)

___
*[`crates/prover/src/core/air/air_ext.rs` line 55 at r4](https://reviewable.io/reviews/starkware-libs/stwo/631#-NyrxvEw67EjMF6NBBjM:-NysyHf04o4SEFNefqT3:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/ab4f4c110da3d854063419a3a717927c54804e07/crates/prover/src/core/air/air_ext.rs#L55)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Optional: could use `BTreeSet<String>` for interaction_element_ids
</blockquote></details>

Done.

**Pull request merged**
