### PR TITLE
Use precomputed twiddles in avx

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/443)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/443?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#443** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/443?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#401** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/401?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#399** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/399?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#398** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/398?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#397** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/397?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#396** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/396?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#395** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/395?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#394** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/394?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#390** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/390?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#389** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/389?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#383** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/383?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#382** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/382?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#381** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/381?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#380** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/380?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#379** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/379?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#378** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/378?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#377** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/377?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#368** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/368?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#367** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/367?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#366** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/366?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#365** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/365?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/443)* status: all files reviewed, 5 unresolved discussions (waiting on @spapinistarkware)

___
*[`src/core/backend/avx512/circle.rs` line 22 at r4](https://reviewable.io/reviews/starkware-libs/stwo/443#-NsriFpX9wTXEbkhPhJD:-NsriFpYAo7MpOML1_E9:b-r0sdg4) ([raw file](https://github.com/starkware-libs/stwo/blob/917bf93cd346e2f7bd37e596c02203aae952313e/src/core/backend/avx512/circle.rs#L22)):*
> ```XML
> // Decide if and when it's ok and what to do if it's not.
> impl PolyOps for AVX512Backend {
>     type Twiddles = Vec<i32>;
> ```

I think that something should be written here w.r.t why the twiddle in the avx is a vec of i32.



_Code quote:_
```XML
type Twiddles = Vec<i32>
```
___
*[`src/core/backend/avx512/circle.rs` line 118 at r4](https://reviewable.io/reviews/starkware-libs/stwo/443#-NsrvNIx8sbGj41ncXQJ:-NsrvNIx8sbGj41ncXQK:b-4e0gt) ([raw file](https://github.com/starkware-libs/stwo/blob/917bf93cd346e2f7bd37e596c02203aae952313e/src/core/backend/avx512/circle.rs#L118)):*
> ```XML
>                     &twiddles[layer_i]
>                         [i << (fft_log_size - 2 - layer_i)..(i + 1) << (fft_log_size - 2 - layer_i)]
>                 })
> ```

Why do we want this change?



_Code quote:_
```XML
            let subdomain_twiddles = (0..(fft_log_size - 1))
                .map(|layer_i| {
                    &twiddles[layer_i]
                        [i << (fft_log_size - 2 - layer_i)..(i + 1) << (fft_log_size - 2 - layer_i)]
                })
```
___
*[`src/core/backend/avx512/circle.rs` line 147 at r4](https://reviewable.io/reviews/starkware-libs/stwo/443#-Nsrw5QP5r2WUqeK1RXH:-Nsrw5QP5r2WUqeK1RXI:b-6y3wic) ([raw file](https://github.com/starkware-libs/stwo/blob/917bf93cd346e2f7bd37e596c02203aae952313e/src/core/backend/avx512/circle.rs#L147)):*
> ```XML
>     }
> 
>     fn precompute_twiddles(coset: Coset) -> TwiddleTree<Self> {
> ```

Do we maybe want the twiddles to be stored also in avx registers?



_Code quote:_
```XML
fn precompute_twiddles(coset: Coset) -> TwiddleTree<Self> {
```
___
*[`src/core/backend/avx512/circle.rs` line 152 at r4](https://reviewable.io/reviews/starkware-libs/stwo/443#-NsrwvRP9UNqe2zIgMap:-NsrwvRQE04dtpvGzUwe:b-o1mzx) ([raw file](https://github.com/starkware-libs/stwo/blob/917bf93cd346e2f7bd37e596c02203aae952313e/src/core/backend/avx512/circle.rs#L152)):*
> ```XML
> 
>         // TODO(spapini): Optimize.
>         for layer in &rfft::get_twiddle_dbls(coset)[1..] {
> ```

Is this the only use of get_twiddle_dbls?
Why are we storing the layer0 twiddles there if we are going to ignore them anyway?



_Code quote:_
```XML
&rfft::get_twiddle_dbls(coset)[1..] 
```
___
*[`src/core/backend/avx512/circle.rs` line 155 at r4](https://reviewable.io/reviews/starkware-libs/stwo/443#-Nsrx5n57s4GcoLvMSZ-:-Nsrx5n57s4GcoLvMSZ0:b-tm4afi) ([raw file](https://github.com/starkware-libs/stwo/blob/917bf93cd346e2f7bd37e596c02203aae952313e/src/core/backend/avx512/circle.rs#L155)):*
> ```XML
>             twiddles.extend(layer);
>         }
>         twiddles.push(2);
> ```

Explain



_Code quote:_
```XML
twiddles.push(2)
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/443)* status: 2 of 7 files reviewed, 5 unresolved discussions (waiting on @shaharsamocha7)

___
*[`src/core/backend/avx512/circle.rs` line 22 at r4](https://reviewable.io/reviews/starkware-libs/stwo/443#-NsriFpX9wTXEbkhPhJD:-NswkTYyEPV9x9OT9FYL:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/917bf93cd346e2f7bd37e596c02203aae952313e/src/core/backend/avx512/circle.rs#L22)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I think that something should be written here w.r.t why the twiddle in the avx is a vec of i32.
</blockquote></details>

Done.
___
*[`src/core/backend/avx512/circle.rs` line 118 at r4](https://reviewable.io/reviews/starkware-libs/stwo/443#-NsrvNIx8sbGj41ncXQJ:-NswmzeCC6fWJiLj8P2S:bdw0qzp) ([raw file](https://github.com/starkware-libs/stwo/blob/917bf93cd346e2f7bd37e596c02203aae952313e/src/core/backend/avx512/circle.rs#L118)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why do we want this change?
</blockquote></details>

It seems that without it, I would need to access `twiddles[layer_i-1]`, and doing the -1 is weird.
___
*[`src/core/backend/avx512/circle.rs` line 147 at r4](https://reviewable.io/reviews/starkware-libs/stwo/443#-Nsrw5QP5r2WUqeK1RXH:-Nswkkgo4WuUJmbakvkY:b-b7htlo) ([raw file](https://github.com/starkware-libs/stwo/blob/917bf93cd346e2f7bd37e596c02203aae952313e/src/core/backend/avx512/circle.rs#L147)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Do we maybe want the twiddles to be stored also in avx registers?
</blockquote></details>

Not all twiddles can, and its not that important.
Except for the first layer, only the first is loaded as an AVX register. The other are broadcasted.
___
*[`src/core/backend/avx512/circle.rs` line 152 at r4](https://reviewable.io/reviews/starkware-libs/stwo/443#-NsrwvRP9UNqe2zIgMap:-Nswn77RDtYLpuEA5vth:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/917bf93cd346e2f7bd37e596c02203aae952313e/src/core/backend/avx512/circle.rs#L152)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Is this the only use of get_twiddle_dbls?
Why are we storing the layer0 twiddles there if we are going to ignore them anyway?
</blockquote></details>

Done.
___
*[`src/core/backend/avx512/circle.rs` line 155 at r4](https://reviewable.io/reviews/starkware-libs/stwo/443#-Nsrx5n57s4GcoLvMSZ-:-NswofFiB7UZ26Cal1l_:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/917bf93cd346e2f7bd37e596c02203aae952313e/src/core/backend/avx512/circle.rs#L155)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Explain
</blockquote></details>

Done.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/443)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`src/core/backend/avx512/fft/ifft.rs` line 377 at r4](https://reviewable.io/reviews/starkware-libs/stwo/443#-NsxNniYCJ_efMPFHnO6:-NsxNniZ0KJtiRYMox5y:b-6ggwel) ([raw file](https://github.com/starkware-libs/stwo/blob/917bf93cd346e2f7bd37e596c02203aae952313e/src/core/backend/avx512/fft/ifft.rs#L377)):*
> ```XML
> }
> 
> pub fn get_itwiddle_dbls(mut coset: Coset) -> Vec<Vec<i32>> {
> ```

Document that this returns all the twiddles that relevant only for the line domains.



_Code quote:_
```XML
pub fn get_itwiddle_dbls(mut coset: Coset) -> Vec<Vec<i32>> {
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/443)* status: all files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`src/core/backend/avx512/fft/ifft.rs` line 377 at r4](https://reviewable.io/reviews/starkware-libs/stwo/443#-NsxNniYCJ_efMPFHnO6:-NsxUnCECUBrd0nDz7qr:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/917bf93cd346e2f7bd37e596c02203aae952313e/src/core/backend/avx512/fft/ifft.rs#L377)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Document that this returns all the twiddles that relevant only for the line domains.
</blockquote></details>

Done.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/443#-:-NsxXBwO0gtnRuUzsKaj:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
