### PR TITLE
AVX regular fft

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/390)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`src/core/backend/avx512/fft/ifft.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/stwo/390#-NsJ78Aa3lpw7bJie-jq:-NsJ78Aa3lpw7bJie-jr:b-75z9wn) ([raw file](https://github.com/starkware-libs/stwo/blob/436ea83f7be6d2bce1a32f95dcff0693ce19cfb3/src/core/backend/avx512/fft/ifft.rs#L83)):*
> ```XML
>         ifft_vecwise_loop(values, twiddle_dbl, fft_layers - VECWISE_FFT_BITS, index_h);
>         for layer in (VECWISE_FFT_BITS..fft_layers).step_by(3) {
>             match fft_layers - layer {
> ```

are you trying to sneak this back in?



_Code quote:_
```XML
        for layer in (VECWISE_FFT_BITS..fft_layers).step_by(3) {
            match fft_layers - layer {
```

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/390)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`src/core/backend/avx512/fft/ifft.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/stwo/390#-NsJ78Aa3lpw7bJie-jq:-NsJ7FSA8boptDGy1X48:bp130p8) ([raw file](https://github.com/starkware-libs/stwo/blob/436ea83f7be6d2bce1a32f95dcff0693ce19cfb3/src/core/backend/avx512/fft/ifft.rs#L83)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

are you trying to sneak this back in?
</blockquote></details>

do you think doing a match on every layer is better?

**Comment by ilyalesokhin-starkware** [comment]
*[`src/core/backend/avx512/fft/ifft.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/stwo/390#-NsJ78Aa3lpw7bJie-jq:-NsJAH4-74uyMITt3HqX:b9es4m5) ([raw file](https://github.com/starkware-libs/stwo/blob/436ea83f7be6d2bce1a32f95dcff0693ce19cfb3/src/core/backend/avx512/fft/ifft.rs#L83)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Since I added the fft, I want it to be visible that fft is exactly the same thing in reverse order.
The `while` didn't really show this, since I needed to start the while from something weird like `(fft_layers-4)/3*3+fft_layers`
</blockquote></details>

where do you need to start from something weird?

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/390)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`src/core/backend/avx512/fft/ifft.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/stwo/390#-NsJ78Aa3lpw7bJie-jq:-NsJD1L08qdKdAdaxYeL:b-ie8yu9) ([raw file](https://github.com/starkware-libs/stwo/blob/436ea83f7be6d2bce1a32f95dcff0693ce19cfb3/src/core/backend/avx512/fft/ifft.rs#L83)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

where do you need to start from something weird?
</blockquote></details>

In the regular fft (which is starting from higher bits).
And I want it to look exactly like the reverse of this (easier to understand why they are inverse of each other)

**Comment by ilyalesokhin-starkware** [comment]
*[`src/core/backend/avx512/fft/ifft.rs` line 696 at r1](https://reviewable.io/reviews/starkware-libs/stwo/390#-NsJDIsa49h_Z481b5iK:-NsJDIsa49h_Z481b5iL:b-iyszfr) ([raw file](https://github.com/starkware-libs/stwo/blob/436ea83f7be6d2bce1a32f95dcff0693ce19cfb3/src/core/backend/avx512/fft/ifft.rs#L696)):*
> ```XML
>     #[test]
>     fn test_ifft_lower_with_vecwise() {
>         for log_size in 5..=11 {
> ```

what is this syntax?



_Code quote:_
```XML
5..=11 
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/390)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`src/core/backend/avx512/fft/ifft.rs` line 696 at r1](https://reviewable.io/reviews/starkware-libs/stwo/390#-NsJDIsa49h_Z481b5iK:-NsJEmWl73J-mp_x7CzW:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/2c277df01bf009e92807778f2b1d6eb250b9bd81/src/core/backend/avx512/fft/ifft.rs#L696)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

what is this syntax?
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/390#-:-NsJFPcA2DrkHOJVjhAu:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
