### PR TITLE
integrated point vanishing in fri quotients

### PR DESCRIPTION
**Pull request by ohad-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/619)

### CODE REVIEW

**Comment by ohad-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/619?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#619** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/619?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#598** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/598?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#618](https://github.com/starkware-libs/stwo/pull/618) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/618?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#588** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/588?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#597](https://github.com/starkware-libs/stwo/pull/597) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/597?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#583** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/583?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ohad-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/619)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @andrewmilson, @ohad-starkware, and @spapinistarkware)

___
*[`crates/prover/src/core/constraints.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/stwo/619#-NxDIGVABeBvnF4wmg7-:-NxDIGVB3ppeOw9NOFet:b-jimjls) ([raw file](https://github.com/starkware-libs/stwo/blob/7b55e912a11657b6e69465eba184b32596c9e92f/crates/prover/src/core/constraints.rs#L74)):*
> ```XML
> }
> 
> pub fn point_vanishing_fraction<F: ExtensionOf<BaseField>, EF: ExtensionOf<F>>(
> ```

Document



_Code quote:_
```XML
pub fn point_vanishing_fraction<F: ExtensionOf<BaseField>, EF: ExtensionOf<F>>(
```
___
*[`crates/prover/src/core/constraints.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/stwo/619#-NxDIdA9EfrZswqo45fP:-NxDIdA9EfrZswqo45fQ:bqn4wzu) ([raw file](https://github.com/starkware-libs/stwo/blob/7b55e912a11657b6e69465eba184b32596c9e92f/crates/prover/src/core/constraints.rs#L74)):*
> ```XML
> }
> 
> pub fn point_vanishing_fraction<F: ExtensionOf<BaseField>, EF: ExtensionOf<F>>(
> ```

Maybe rename to point_vanishing and just document that it returns it in as (numer, denom)



_Code quote:_
```XML
pub fn point_vanishing_fraction<F: ExtensionOf<BaseField>, EF: ExtensionOf<F>>(
```
___
*[`crates/prover/src/core/backend/cpu/quotients.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/stwo/619#-NxDJCeE0Btw0O-UxVyy:-NxDJCeE0Btw0O-UxVyz:bny8xt) ([raw file](https://github.com/starkware-libs/stwo/blob/7b55e912a11657b6e69465eba184b32596c9e92f/crates/prover/src/core/backend/cpu/quotients.rs#L119)):*
> ```XML
>     let mut flat_denominators = Vec::with_capacity(sample_batches.len() * domain.size());
>     let mut flat_denominator_denominators =
>         Vec::with_capacity(sample_batches.len() * domain.size());
> ```

Consider to rename



_Code quote:_
```XML
    let mut flat_denominator_denominators =
        Vec::with_capacity(sample_batches.len() * domain.size());
```
___
*[`crates/prover/src/core/pcs/quotients.rs` line 188 at r1](https://reviewable.io/reviews/starkware-libs/stwo/619#-NxDISKBAMDMCxZgMaLD:-NxDISKBAMDMCxZgMaLE:b-126ey2) ([raw file](https://github.com/starkware-libs/stwo/blob/7b55e912a11657b6e69465eba184b32596c9e92f/crates/prover/src/core/pcs/quotients.rs#L188)):*
> ```XML
> 
>     #[test]
>     #[ignore]
> ```

?
Tests are not passing?



_Code quote:_
```XML
#[ignore]
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/619)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @andrewmilson, @shaharsamocha7, and @spapinistarkware)

___
*[`crates/prover/src/core/constraints.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/stwo/619#-NxDIdA9EfrZswqo45fP:-NxRlUsE0N--rck0OCd-:bmhsr8i) ([raw file](https://github.com/starkware-libs/stwo/blob/7b55e912a11657b6e69465eba184b32596c9e92f/crates/prover/src/core/constraints.rs#L74)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Maybe rename to point_vanishing and just document that it returns it in as (numer, denom)
</blockquote></details>

Agreed, but this will induce changes in test functions that I don't want to include in this pr. Added a todo.
___
*[`crates/prover/src/core/constraints.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/stwo/619#-NxDIGVABeBvnF4wmg7-:-NxRlpyZ86jGqaouIMZl:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/7b55e912a11657b6e69465eba184b32596c9e92f/crates/prover/src/core/constraints.rs#L74)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Document
</blockquote></details>

Done.
___
*[`crates/prover/src/core/backend/cpu/quotients.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/stwo/619#-NxDJCeE0Btw0O-UxVyy:-NxRmEXi1LCfCbJSJbxJ:bcjympq) ([raw file](https://github.com/starkware-libs/stwo/blob/7b55e912a11657b6e69465eba184b32596c9e92f/crates/prover/src/core/backend/cpu/quotients.rs#L119)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Consider to rename
</blockquote></details>

ChatGPT said nested/secondery, wdyt?
___
*[`crates/prover/src/core/pcs/quotients.rs` line 188 at r1](https://reviewable.io/reviews/starkware-libs/stwo/619#-NxDISKBAMDMCxZgMaLD:-NxRmIA95Efb9GXvCAR4:b9fwra9) ([raw file](https://github.com/starkware-libs/stwo/blob/7b55e912a11657b6e69465eba184b32596c9e92f/crates/prover/src/core/pcs/quotients.rs#L188)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

?
Tests are not passing?
</blockquote></details>

yes, documented now. 
they should not pass, as the quotients are now not in the fft-space.
maybe there is a place for a .is_in_fri_space() function? as it now differs from the fft-space.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/619)* status: 1 of 5 files reviewed, 5 unresolved discussions (waiting on @andrewmilson, @ohad-starkware, and @spapinistarkware)

___
*[`crates/prover/src/core/constraints.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/stwo/619#-NxDIGVABeBvnF4wmg7-:-NxRzsHo29ClXH62ClRE:bxnf5df) ([raw file](https://github.com/starkware-libs/stwo/blob/7b55e912a11657b6e69465eba184b32596c9e92f/crates/prover/src/core/constraints.rs#L74)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Add
/// Note that this function has a pole on the antipode of the vanish\_point.
___
*[`crates/prover/src/core/backend/avx512/fri.rs` line 262 at r3](https://reviewable.io/reviews/starkware-libs/stwo/619#-NxS-NDQEPOYmB0_05Bw:-NxS-NDQEPOYmB0_05Bx:bdfl32u) ([raw file](https://github.com/starkware-libs/stwo/blob/04cb6662bc7292f29fa8acfd5bc784e07e4de544/crates/prover/src/core/backend/avx512/fri.rs#L262)):*
> ```XML
>         assert_eq!(avx_lambda, cpu_lambda);
> 
>         assert_eq!(avx_lambda, cpu_lambda);
> ```

Remove
probably merge conflict



_Code quote:_
```XML
        assert_eq!(avx_lambda, cpu_lambda);
```
___
*[`crates/prover/src/core/backend/cpu/quotients.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/stwo/619#-NxDJCeE0Btw0O-UxVyy:-NxS03Iw7nI2R70f0rbk:b-937j9u) ([raw file](https://github.com/starkware-libs/stwo/blob/7b55e912a11657b6e69465eba184b32596c9e92f/crates/prover/src/core/backend/cpu/quotients.rs#L119)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

ChatGPT said nested/secondery, wdyt?
</blockquote></details>

I think that the previous is better, what about just calling it numerator/denomerator?
___
*[`crates/prover/src/core/backend/cpu/quotients.rs` line 118 at r3](https://reviewable.io/reviews/starkware-libs/stwo/619#-NxS0Eak2FhWJy3XHlY8:-NxS0Eak2FhWJy3XHlY9:b-6g5m7g) ([raw file](https://github.com/starkware-libs/stwo/blob/04cb6662bc7292f29fa8acfd5bc784e07e4de544/crates/prover/src/core/backend/cpu/quotients.rs#L118)):*
> ```XML
> ) -> Vec<Col<CPUBackend, SecureField>> {
>     let mut flat_denominators = Vec::with_capacity(sample_batches.len() * domain.size());
>     let mut nested_denominators = Vec::with_capacity(sample_batches.len() * domain.size());
> ```

Consider to change:

or something like that



_Suggestion:_
```XML
    let n_fractions = sample_batches.len() * domain.size();
    let mut flat_denominators = Vec::with_capacity(n_fractions);
    let mut nested_denominators = Vec::with_capacity(n_fractions);
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/619)* status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @andrewmilson, @shaharsamocha7, and @spapinistarkware)

___
*[`crates/prover/src/core/constraints.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/stwo/619#-NxDIGVABeBvnF4wmg7-:-NxS2rua0x7Sg_oUP7Z5:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/7b55e912a11657b6e69465eba184b32596c9e92f/crates/prover/src/core/constraints.rs#L74)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Add
/// Note that this function has a pole on the antipode of the vanish\_point.
</blockquote></details>

Done.
___
*[`crates/prover/src/core/backend/avx512/fri.rs` line 262 at r3](https://reviewable.io/reviews/starkware-libs/stwo/619#-NxS-NDQEPOYmB0_05Bw:-NxS2yG_0_uF9UtYef2R:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/04cb6662bc7292f29fa8acfd5bc784e07e4de544/crates/prover/src/core/backend/avx512/fri.rs#L262)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Remove
probably merge conflict
</blockquote></details>

Done.
___
*[`crates/prover/src/core/backend/cpu/quotients.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/stwo/619#-NxDJCeE0Btw0O-UxVyy:-NxSTMia4EavMfuOdJ1k:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/7b55e912a11657b6e69465eba184b32596c9e92f/crates/prover/src/core/backend/cpu/quotients.rs#L119)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I think that the previous is better, what about just calling it numerator/denomerator?
</blockquote></details>

Done.
___
*[`crates/prover/src/core/backend/cpu/quotients.rs` line 118 at r3](https://reviewable.io/reviews/starkware-libs/stwo/619#-NxS0Eak2FhWJy3XHlY8:-NxSTPnL0siLo6iuEtCW:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/04cb6662bc7292f29fa8acfd5bc784e07e4de544/crates/prover/src/core/backend/cpu/quotients.rs#L118)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Consider to change:

or something like that
</blockquote></details>

Done.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/619)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @andrewmilson, @ohad-starkware, and @spapinistarkware)

___
*[`crates/prover/src/core/constraints.rs` line 74 at r4](https://reviewable.io/reviews/starkware-libs/stwo/619#-NxSgexx1c65en2YPhEn:-NxSgexx1c65en2YPhEo:b-3icl5p) ([raw file](https://github.com/starkware-libs/stwo/blob/d82287fb5558e4f11fe3d257fc1a285ca19068c4/crates/prover/src/core/constraints.rs#L74)):*
> ```XML
> }
> 
> /// Evaluates a vanishing polynomial of the vanish_point at a point, but skips the division.
> ```

It is called "projective coordinates"



_Code quote:_
```XML
, but skips the division.
```
___
*[`crates/prover/src/core/pcs/quotients.rs` line 188 at r1](https://reviewable.io/reviews/starkware-libs/stwo/619#-NxDISKBAMDMCxZgMaLD:-NxSSB9J9z5hDq7Znpkt:bl6m5ft) ([raw file](https://github.com/starkware-libs/stwo/blob/7b55e912a11657b6e69465eba184b32596c9e92f/crates/prover/src/core/pcs/quotients.rs#L188)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

yes, documented now. 
they should not pass, as the quotients are now not in the fft-space.
maybe there is a place for a .is_in_fri_space() function? as it now differs from the fft-space.
</blockquote></details>

I'm a bit confused but I don't think we want to remove the test entirely.
Can we adapt the test?

**Review by shaharsamocha7 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/619)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @andrewmilson, @ohad-starkware, and @spapinistarkware)

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/619)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @andrewmilson, @shaharsamocha7, and @spapinistarkware)

___
*[`crates/prover/src/core/constraints.rs` line 74 at r4](https://reviewable.io/reviews/starkware-libs/stwo/619#-NxSgexx1c65en2YPhEn:-NxfLV3i6PcuuVtZkA8B:b-p074py) ([raw file](https://github.com/starkware-libs/stwo/blob/d82287fb5558e4f11fe3d257fc1a285ca19068c4/crates/prover/src/core/constraints.rs#L74)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

It is called "projective coordinates"
</blockquote></details>

I don't like it. 
___
*[`crates/prover/src/core/pcs/quotients.rs` line 188 at r1](https://reviewable.io/reviews/starkware-libs/stwo/619#-NxDISKBAMDMCxZgMaLD:-NxfOtYEAW0UgCtk7Dm9:bb68cql) ([raw file](https://github.com/starkware-libs/stwo/blob/7b55e912a11657b6e69465eba184b32596c9e92f/crates/prover/src/core/pcs/quotients.rs#L188)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I'm a bit confused but I don't think we want to remove the test entirely.
Can we adapt the test?
</blockquote></details>

#627

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/619)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`crates/prover/src/core/constraints.rs` line 74 at r4](https://reviewable.io/reviews/starkware-libs/stwo/619#-NxSgexx1c65en2YPhEn:-NxvCeGF5y62m9Hqv42K:bpfecnz) ([raw file](https://github.com/starkware-libs/stwo/blob/d82287fb5558e4f11fe3d257fc1a285ca19068c4/crates/prover/src/core/constraints.rs#L74)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

I don't like it.
</blockquote></details>

You can also call it "as a fraction"

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/619)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @andrewmilson, @ohad-starkware, and @shaharsamocha7)

___
*[`crates/prover/src/core/constraints.rs` line 74 at r4](https://reviewable.io/reviews/starkware-libs/stwo/619#-NxSgexx1c65en2YPhEn:-NxvD6G38Z0cxXuHCVUG:b1ha93j) ([raw file](https://github.com/starkware-libs/stwo/blob/d82287fb5558e4f11fe3d257fc1a285ca19068c4/crates/prover/src/core/constraints.rs#L74)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

You can also call it "as a fraction"
</blockquote></details>

Perhaps even better than documenting it with words, add a Fraction struct.
___
*[`crates/prover/src/core/backend/avx512/quotients.rs` line 87 at r5](https://reviewable.io/reviews/starkware-libs/stwo/619#-NxvDCrPDNgnJ6IbMYU_:-NxvDCrPDNgnJ6IbMYUa:b-lj0dfg) ([raw file](https://github.com/starkware-libs/stwo/blob/59c16c83eb0269ac6447944a639c63342f754d88/crates/prover/src/core/backend/avx512/quotients.rs#L87)):*
> ```XML
> /// Pair vanishing for the packed representation of the points. See
> /// [crate::core::constraints::pair_vanishing] for more details.
> /// TODO: remove _ when in use.
> ```

Do you see a use in upcoming PRs? If not, just remove it.

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/619)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @andrewmilson, @ohad-starkware, and @shaharsamocha7)

___
*[`crates/prover/src/core/backend/avx512/quotients.rs` line 116 at r5](https://reviewable.io/reviews/starkware-libs/stwo/619#-NxvF26n31eRMOS0saos:-NxvF26n31eRMOS0saot:bn7420e) ([raw file](https://github.com/starkware-libs/stwo/blob/59c16c83eb0269ac6447944a639c63342f754d88/crates/prover/src/core/backend/avx512/quotients.rs#L116)):*
> ```XML
>     domain: CircleDomain,
> ) -> Vec<Col<AVX512Backend, SecureField>> {
>     let mut numerator_terms = Vec::with_capacity(sample_batches.len() * domain.size());
> ```

It's not very pretty that you are generating nums an denoms in the loop, but they are returned in a differnet way. One is the return of the map, and the other is with a mutabl push.
They should be the same.

Consider unzip.

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/619)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @andrewmilson, @ohad-starkware, and @shaharsamocha7)

___
*[`crates/prover/src/core/backend/cpu/quotients.rs` line 44 at r5](https://reviewable.io/reviews/starkware-libs/stwo/619#-NxvFLC599CbX5AFiVE6:-NxvFLC599CbX5AFiVE7:b-wpcecn) ([raw file](https://github.com/starkware-libs/stwo/blob/59c16c83eb0269ac6447944a639c63342f754d88/crates/prover/src/core/backend/cpu/quotients.rs#L44)):*
> ```XML
> }
> 
> // TODO(Ohad): no longer using pair_vanishing, remove domain_point_vec and line_coeffs, or write a
> ```

Please do this soon
___
*[`crates/prover/src/core/pcs/quotients.rs` line 189 at r5](https://reviewable.io/reviews/starkware-libs/stwo/619#-NxvF_Rf3pCDGLIsJcbW:-NxvF_Rf3pCDGLIsJcbX:b-9r1qcz) ([raw file](https://github.com/starkware-libs/stwo/blob/59c16c83eb0269ac6447944a639c63342f754d88/crates/prover/src/core/pcs/quotients.rs#L189)):*
> ```XML
>     #[test]
>     // Ignored because we allow polynomials outside of fft-space, hence it is not a bug anymore.
>     // TODO(Ohad): consider adding a test for the new behavior,
> ```

Don't consider, do it:)

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 1 of 5 files at r2, 3 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/619)* status: all files reviewed, 4 unresolved discussions (waiting on @andrewmilson, @ohad-starkware, and @shaharsamocha7)

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/619)* status: 3 of 6 files reviewed, 4 unresolved discussions (waiting on @andrewmilson, @shaharsamocha7, and @spapinistarkware)

___
*[`crates/prover/src/core/constraints.rs` line 74 at r4](https://reviewable.io/reviews/starkware-libs/stwo/619#-NxSgexx1c65en2YPhEn:-NxvFM9UAqJ0tIe88vsZ:b-rx2xhu) ([raw file](https://github.com/starkware-libs/stwo/blob/d82287fb5558e4f11fe3d257fc1a285ca19068c4/crates/prover/src/core/constraints.rs#L74)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Perhaps even better than documenting it with words, add a Fraction struct.
</blockquote></details>

I added the word fraction in the doc, IMO it's clear enough as is. Fractions struct I think might be also useful during trace-gen, but don't think it belongs in this pr.
___
*[`crates/prover/src/core/backend/avx512/quotients.rs` line 87 at r5](https://reviewable.io/reviews/starkware-libs/stwo/619#-NxvDCrPDNgnJ6IbMYU_:-NxvTw_CEezrfKUuVAqr:bb7f2mf) ([raw file](https://github.com/starkware-libs/stwo/blob/59c16c83eb0269ac6447944a639c63342f754d88/crates/prover/src/core/backend/avx512/quotients.rs#L87)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Do you see a use in upcoming PRs? If not, just remove it.
</blockquote></details>

done
___
*[`crates/prover/src/core/backend/avx512/quotients.rs` line 116 at r5](https://reviewable.io/reviews/starkware-libs/stwo/619#-NxvF26n31eRMOS0saos:-NxvTcRS14Iqy6YEfgg2:b-mzvjf0) ([raw file](https://github.com/starkware-libs/stwo/blob/59c16c83eb0269ac6447944a639c63342f754d88/crates/prover/src/core/backend/avx512/quotients.rs#L116)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

It's not very pretty that you are generating nums an denoms in the loop, but they are returned in a differnet way. One is the return of the map, and the other is with a mutabl push.
They should be the same.

Consider unzip.
</blockquote></details>

thank you, done.
___
*[`crates/prover/src/core/pcs/quotients.rs` line 189 at r5](https://reviewable.io/reviews/starkware-libs/stwo/619#-NxvF_Rf3pCDGLIsJcbW:-NxvTf4-9_pIUMGSSnyy:bb68cql) ([raw file](https://github.com/starkware-libs/stwo/blob/59c16c83eb0269ac6447944a639c63342f754d88/crates/prover/src/core/pcs/quotients.rs#L189)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Don't consider, do it:)
</blockquote></details>

#627

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/619#-:-Nxw51HG6RqGm8UPNicp:bnfp4nl)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @andrewmilson and @spapinistarkware)

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/619#-:-Ny-WtufA_VsSSvPeWVm:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @andrewmilson)

**Pull request merged**
