### PR TITLE
Separated Xor table types.

### PR DESCRIPTION
**Pull request by Alon-Ti**

### CODE REVIEW

**Comment by Alon-Ti** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/883?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#883** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/883?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#879** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/879?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#876** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/876?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#875** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/875?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Alon-Ti and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ohad-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/883)* status: 0 of 19 files reviewed, 2 unresolved discussions (waiting on @Alon-Ti and @shaharsamocha7)

___
*[`crates/prover/src/examples/state_machine/components.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/stwo/883#-OBeOYcqBMSt3dh8kzDs:-OBeOYcqBMSt3dh8kzDt:b-2w4yfw) ([raw file](https://github.com/starkware-libs/stwo/blob/eb215aab506029a205b1347d62d26eaa38fd85ae/crates/prover/src/examples/state_machine/components.rs#L51)):*
> ```XML
> 
>         eval.add_to_relation(&[
>             RelationEntry::new(&self.lookup_elements, E::EF::one(), &input_state),
> ```

unrelated to this pr, whiy is multiplicity EF and not F? wouldn't that conflict with future optimizations to these muls?
___
*[`crates/prover/src/constraint_framework/mod.rs` line 121 at r1](https://reviewable.io/reviews/starkware-libs/stwo/883#-OBePB5e7vVf3Q0bTYvw:-OBePB5f5bKWKNDNwsnu:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/eb215aab506029a205b1347d62d26eaa38fd85ae/crates/prover/src/constraint_framework/mod.rs#L121)):*
> ```XML
>     fn add_to_relation<Relation: RelationType<Self::F, Self::EF>>(
>         &mut self,
>         _entries: &[RelationEntry<'_, Self::F, Self::EF, Relation>],
> ```


___
*[`crates/prover/src/constraint_framework/mod.rs` line 127 at r1](https://reviewable.io/reviews/starkware-libs/stwo/883#-OBePDHt-9_J7yUJ4tyO:-OBePDHt-9_J7yUJ4tyP:bwsq967) ([raw file](https://github.com/starkware-libs/stwo/blob/eb215aab506029a205b1347d62d26eaa38fd85ae/crates/prover/src/constraint_framework/mod.rs#L127)):*
> ```XML
> }
> 
> pub trait EvalAtRowWithLogup {
> ```

are you planning to kill EvalAtRow?
does it make sense to have both and still have add_to_relation for the regular Eval?
why not a super trait? (genuinely asking,  don't know if it would work,)
___
*[`crates/prover/src/constraint_framework/logup.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/stwo/883#-OBeNGtb6kC79GjcLswa:-OBeNGtb6kC79GjcLswb:b-r611zn) ([raw file](https://github.com/starkware-libs/stwo/blob/eb215aab506029a205b1347d62d26eaa38fd85ae/crates/prover/src/constraint_framework/logup.rs#L92)):*
> ```XML
> /// Ensures that the LogupAtRow is finalized.
> /// LogupAtRow should be finalized exactly once.
> impl<F: Clone, EF: RelationEFTraitBound<F>> Drop for LogupAtRow<F, EF> {
> ```

non blocking



_Suggestion:_
```XML
 RelationEF
```
___
*[`crates/prover/src/examples/blake/xor_table/gen.rs` line 208 at r1](https://reviewable.io/reviews/starkware-libs/stwo/883#-OBeODT9BFbgsP8jac69:-OBeODTA7VvkA88frQHY:b9benum) ([raw file](https://github.com/starkware-libs/stwo/blob/eb215aab506029a205b1347d62d26eaa38fd85ae/crates/prover/src/examples/blake/xor_table/gen.rs#L208)):*
> ```XML
> }
> 
> xor_table_gen!(xor12, XorElements12, 12, 4);
> ```

maybe these should be coupled with the eval macro?
non blocking

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/883)* status: 4 of 19 files reviewed, 3 unresolved discussions (waiting on @Alon-Ti and @ohad-starkware)

___
*[`crates/prover/src/constraint_framework/mod.rs` line 127 at r1](https://reviewable.io/reviews/starkware-libs/stwo/883#-OBeXbgN0jgsRdyJhKJK:-OBeXbgN0jgsRdyJhKJL:b2k4a0) ([raw file](https://github.com/starkware-libs/stwo/blob/eb215aab506029a205b1347d62d26eaa38fd85ae/crates/prover/src/constraint_framework/mod.rs#L127)):*
> ```XML
> }
> 
> pub trait EvalAtRowWithLogup {
> ```

This trait shouldn't be implemented directly from outside of this module right?
It's only for the use of the framework itself. Can you document?

Maybe we should have a utils file in this folder so mod will only contain API traits.



_Code quote:_
```XML
pub trait EvalAtRowWithLogup {
```

**Review by ohad-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/883)* status: 4 of 19 files reviewed, 4 unresolved discussions (waiting on @Alon-Ti and @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/mod.rs` line 277 at r1](https://reviewable.io/reviews/starkware-libs/stwo/883#-OBt-owB2Xhi3dP3UlX1:-OBt-owB2Xhi3dP3UlX2:b-jh3acy) ([raw file](https://github.com/starkware-libs/stwo/blob/eb215aab506029a205b1347d62d26eaa38fd85ae/crates/prover/src/constraint_framework/mod.rs#L277)):*
> ```XML
>             )
>             .collect();
>         self.write_logup_frac(fracs.into_iter().sum());
> ```

redundant collect 



_Suggestion:_
```XML
        let fracs = entries.iter().map(
            |RelationEntry {
                 relation,
                 multiplicity,
                 values,
             }| { Fraction::new(multiplicity.clone(), relation.combine(values)) },
        );
        self.write_logup_frac(fracs.sum());
```

**Review by ohad-starkware — COMMENTED** [review]
xor changes  looking good

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/883#-:-OBt01a96jA1wTROMSIQ:b1tazcn)* status: 4 of 19 files reviewed, 4 unresolved discussions (waiting on @Alon-Ti and @shaharsamocha7)

**Review by Alon-Ti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/883)* status: 0 of 20 files reviewed, 4 unresolved discussions (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`crates/prover/src/examples/blake/xor_table/gen.rs` line 208 at r1](https://reviewable.io/reviews/starkware-libs/stwo/883#-OBeODT9BFbgsP8jac69:-OC3dD92-FQrfaecuGk1:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/b61d6c91d3f9e357f9c1adebab1396205f555466/crates/prover/src/examples/blake/xor_table/gen.rs#L208)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

maybe these should be coupled with the eval macro?
non blocking
</blockquote></details>

Done.
___
*[`crates/prover/src/constraint_framework/logup.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/stwo/883#-OBeNGtb6kC79GjcLswa:-OC3dFdLBKxrWtLJwv9F:bp3aow6) ([raw file](https://github.com/starkware-libs/stwo/blob/b61d6c91d3f9e357f9c1adebab1396205f555466/crates/prover/src/constraint_framework/logup.rs#L92)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

non blocking
</blockquote></details>

Reverted.
___
*[`crates/prover/src/constraint_framework/mod.rs` line 127 at r1](https://reviewable.io/reviews/starkware-libs/stwo/883#-OBePDHt-9_J7yUJ4tyO:-OC3d57a9Rn60_1QCXZW:bp3aow6) ([raw file](https://github.com/starkware-libs/stwo/blob/b61d6c91d3f9e357f9c1adebab1396205f555466/crates/prover/src/constraint_framework/mod.rs#L127)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

are you planning to kill EvalAtRow?
does it make sense to have both and still have add_to_relation for the regular Eval?
why not a super trait? (genuinely asking,  don't know if it would work,)
</blockquote></details>

Reverted.
___
*[`crates/prover/src/constraint_framework/mod.rs` line 127 at r1](https://reviewable.io/reviews/starkware-libs/stwo/883#-OBeXbgN0jgsRdyJhKJK:-OC3d6SX8TVqFly7sf7Z:bp3aow6) ([raw file](https://github.com/starkware-libs/stwo/blob/b61d6c91d3f9e357f9c1adebab1396205f555466/crates/prover/src/constraint_framework/mod.rs#L127)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

This trait shouldn't be implemented directly from outside of this module right?
It's only for the use of the framework itself. Can you document?

Maybe we should have a utils file in this folder so mod will only contain API traits.
</blockquote></details>

Reverted.
___
*[`crates/prover/src/constraint_framework/mod.rs` line 277 at r1](https://reviewable.io/reviews/starkware-libs/stwo/883#-OBt-owB2Xhi3dP3UlX1:-OC3d8ej-PtDrVbI6_Gq:bp3aow6) ([raw file](https://github.com/starkware-libs/stwo/blob/b61d6c91d3f9e357f9c1adebab1396205f555466/crates/prover/src/constraint_framework/mod.rs#L277)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

redundant collect
</blockquote></details>

Reverted.
___
*[`crates/prover/src/constraint_framework/mod.rs` line 121 at r1](https://reviewable.io/reviews/starkware-libs/stwo/883#-OBePB5e7vVf3Q0bTYvw:-OC3dIfy0j9VsSLbkQRC:bp3aow6) ([raw file](https://github.com/starkware-libs/stwo/blob/b61d6c91d3f9e357f9c1adebab1396205f555466/crates/prover/src/constraint_framework/mod.rs#L121)):*
> ```XML
>     fn add_to_relation<Relation: RelationType<Self::F, Self::EF>>(
>         &mut self,
>         _entries: &[RelationEntry<'_, Self::F, Self::EF, Relation>],
> ```

Reverted.

**Comment by Alon-Ti** [comment]
### Merge activity

* **Nov 22, 11:20 PM EST**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/883).

**Pull request merged**
