### PR TITLE
avx vecwise ibutterfly

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/368)

### CODE REVIEW

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/368)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`src/core/backend/avx512/fft.rs` line 179 at r2](https://reviewable.io/reviews/starkware-libs/stwo/368#-Nr_mECQ-dUgdLGG19ur:-Ns2AmPe3Ru1tXkrjy_h:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/755eb0ca1cdac9dd6e73bf4d4749b239ba269e25/src/core/backend/avx512/fft.rs#L179)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

wdyt about the following:

The twiddles for layer 0 are unique and arranged as follows: 0 1 2 3 4 5 6 7 8 9 a b c d e f.

The twiddles for layer 1 are replicated in the following pattern: 0 1 2 3 4 5 6 7 0 1 2 3 4 5 6 7.
...
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/368)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`src/core/backend/avx512/fft.rs` line 179 at r2](https://reviewable.io/reviews/starkware-libs/stwo/368#-Nr_mECQ-dUgdLGG19ur:-Ns2EX6LEW7TNBdHvsS7:bqwbrvv) ([raw file](https://github.com/starkware-libs/stwo/blob/755eb0ca1cdac9dd6e73bf4d4749b239ba269e25/src/core/backend/avx512/fft.rs#L179)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not pushed
___
*[`src/core/backend/avx512/fft.rs` line 200 at r2](https://reviewable.io/reviews/starkware-libs/stwo/368#-Nr_lVt11o2zG8yzx2kb:-Nr_lVt11o2zG8yzx2kc:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/755eb0ca1cdac9dd6e73bf4d4749b239ba269e25/src/core/backend/avx512/fft.rs#L200)):*
> ```XML
> 
>     // The twiddles for layer 2 are packed like:
>     //   0 1 2 3 0 1 2 3 0 1 2 3 0 1 2 3
> ```





_Suggestion:_
```XML
    // The twiddles for layer 2 are replicated in the following pattern:
    //   0 1 2 3 0 1 2 3 0 1 2 3 0 1 2 3
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/368)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`src/core/backend/avx512/fft.rs` line 179 at r2](https://reviewable.io/reviews/starkware-libs/stwo/368#-Nr_mECQ-dUgdLGG19ur:-Ns2Pxdr-AvAQcYZZFjy:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/755eb0ca1cdac9dd6e73bf4d4749b239ba269e25/src/core/backend/avx512/fft.rs#L179)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

not pushed
</blockquote></details>

Done.
___
*[`src/core/backend/avx512/fft.rs` line 200 at r2](https://reviewable.io/reviews/starkware-libs/stwo/368#-Nr_lVt11o2zG8yzx2kb:-Ns2PxPsEoa6JCk82tcK:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/755eb0ca1cdac9dd6e73bf4d4749b239ba269e25/src/core/backend/avx512/fft.rs#L200)):*
> ```XML
> 
>     // The twiddles for layer 2 are packed like:
>     //   0 1 2 3 0 1 2 3 0 1 2 3 0 1 2 3
> ```

Done.

**Review by ilyalesokhin-starkware — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/368#-:-Ns2Ysuw9cdLEjzs6H6R:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
