### PR TITLE
Remove old merkle

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/531)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/531?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#531** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/531?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#530** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/530?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#529** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/529?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#528** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/528?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#527** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/527?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#526** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/526?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#525** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/525?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#518** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/518?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — COMMENTED** [review]
> Reviewed 2 of 15 files at r1, 4 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/531)* status: 6 of 21 files reviewed, all discussions resolved

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 6 of 15 files at r1, 9 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/531#-:-NuZWA_Y5oEMlPrNO29a:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`src/examples/fibonacci/mod.rs` line 131 at r3](https://reviewable.io/reviews/starkware-libs/stwo/531#-NuZWJep1faMC54WxGK-:-NuZWJeq2Hol5wN29Lqh:b32vhv) ([raw file](https://github.com/starkware-libs/stwo/blob/be29c984306dc7ca068a8bdc83e93e6e15ccf5af/src/examples/fibonacci/mod.rs#L131)):*
> ```XML
>     use crate::{m31, qm31};
> 
>     pub fn generate_test_queries(n_queries: usize, trace_length: usize) -> Vec<usize> {
> ```

:(



_Suggestion:_
```XML
#[cfg(test)]
pub fn generate_test_queries(n
```

**Review by shaharsamocha7 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/531)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
