### PR TITLE
Update toolchain

### PR DESCRIPTION
**Pull request by ohad-starkware**

### CODE REVIEW

**Comment by ohad-starkware** [comment]
* **#937** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/937?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/937?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `dev`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by shaharsamocha7 — COMMENTED** [review]
> Reviewed 25 of 61 files at r1, 1 of 7 files at r2, 3 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/937)* status: 29 of 62 files reviewed, all discussions resolved (waiting on @ohad-starkware)

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 27 of 61 files at r1, 4 of 7 files at r2, 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/937)* status: 61 of 62 files reviewed, 6 unresolved discussions (waiting on @ohad-starkware)

___
*[`scripts/bench.sh` line 5 at r3](https://reviewable.io/reviews/starkware-libs/stwo/937#-OEPHFGZ0UpWWq0Q6LbU:-OEPHFG_ERCzSJVQ0czd:b-l6hdjr) ([raw file](https://github.com/starkware-libs/stwo/blob/3e95f5398ab6c3d343c94158a4e281706efc6eea/scripts/bench.sh#L5)):*
> ```Shell
> # For example, `./scripts/bench.sh` will run all benchmarks.
> # or `./scripts/bench.sh M31` will run only the M31 benchmarks.
> RUSTFLAGS="-Awarnings -C target-cpu=native -C target-feature=+avx512f -C opt-level=3" cargo bench $@
> ```

revert



_Code quote:_
```Shell
"-Awarnings 
```
___
*[`scripts/clippy.sh` line 2 at r3](https://reviewable.io/reviews/starkware-libs/stwo/937#-OEPHJSVA4T_QW7EawhN:-OEPHJSVA4T_QW7EawhO:b-yy4zpf) ([raw file](https://github.com/starkware-libs/stwo/blob/3e95f5398ab6c3d343c94158a4e281706efc6eea/scripts/clippy.sh#L2)):*
> ```Shell
> #!/bin/bash
> cargo +nightly-2024-01-04 clippy "$@" --all-targets --all-features -- -D warnings -D future-incompatible \
> ```

put the correct version



_Code quote:_
```Shell
+nightly-2024-01-04 
```
___
*[`scripts/rust_fmt.sh` line 3 at r3](https://reviewable.io/reviews/starkware-libs/stwo/937#-OEPHM1d85HdaoEx3NGw:-OEPHM1d85HdaoEx3NGx:bb7od0r) ([raw file](https://github.com/starkware-libs/stwo/blob/3e95f5398ab6c3d343c94158a4e281706efc6eea/scripts/rust_fmt.sh#L3)):*
> ```Shell
> #!/bin/bash
> 
> cargo +nightly-2024-01-04 fmt --all -- "$@"
> ```

same



_Code quote:_
```Shell
+nightly-2024-01-04
```
___
*[`crates/prover/src/examples/blake/scheduler/mod.rs` line 19 at r3](https://reviewable.io/reviews/starkware-libs/stwo/937#-OEPH9YB5X2GWv5_nW5v:-OEPH9YB5X2GWv5_nW5w:bb73xfv) ([raw file](https://github.com/starkware-libs/stwo/blob/cf5e91979f4bb3874f6164a8d661f41a4a173b10/crates/prover/src/examples/blake/scheduler/mod.rs#L19)):*
> ```XML
> relation!(BlakeElements, N_ROUND_INPUT_FELTS);
> 
> #[allow(dead_code)]
> ```

Same



_Code quote:_
```XML
#[allow(dead_code)]
```
___
*[`crates/prover/src/examples/blake/round/constraints.rs` line 13 at r3](https://reviewable.io/reviews/starkware-libs/stwo/937#-OEPH4sn1AubExyFp0a4:-OEPH4so-xydfs0MCM5t:bgrxdcr) ([raw file](https://github.com/starkware-libs/stwo/blob/cf5e91979f4bb3874f6164a8d661f41a4a173b10/crates/prover/src/examples/blake/round/constraints.rs#L13)):*
> ```XML
> const TWO: BaseField = BaseField::from_u32_unchecked(2);
> 
> #[allow(dead_code)]
> ```

Can we check if it is needed?



_Code quote:_
```XML
#[allow(dead_code)]
```
___
*[`scripts/test_avx.sh` line 4 at r3](https://reviewable.io/reviews/starkware-libs/stwo/937#-OEPHPzJ-yiAsQzK_6BH:-OEPHPzJ-yiAsQzK_6BI:b-khwcts) ([raw file](https://github.com/starkware-libs/stwo/blob/cf5e91979f4bb3874f6164a8d661f41a4a173b10/scripts/test_avx.sh#L4)):*
> ```Shell
> # Can be used as a drop in replacement for `cargo test` with avx512f flag on.
> # For example, `./scripts/test_avx.sh` will run all tests(not only avx).
> RUSTFLAGS="-Awarnings -C target-cpu=native -C target-feature=+avx512f -C opt-level=3" cargo +nightly-2024-11-17 test "$@"
> ```

We can keep it opt_level=2 if we have the benches



_Code quote:_
```Shell
opt-level=3
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/937)* status: 61 of 62 files reviewed, 6 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/prover/src/examples/blake/round/constraints.rs` line 13 at r3](https://reviewable.io/reviews/starkware-libs/stwo/937#-OEPH4sn1AubExyFp0a4:-OEPJSfE7pMG1RF6UgdG:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/cf5e91979f4bb3874f6164a8d661f41a4a173b10/crates/prover/src/examples/blake/round/constraints.rs#L13)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can we check if it is needed?
</blockquote></details>

Done.
___
*[`crates/prover/src/examples/blake/scheduler/mod.rs` line 19 at r3](https://reviewable.io/reviews/starkware-libs/stwo/937#-OEPH9YB5X2GWv5_nW5v:-OEPKJRd6YM9EH9az9EY:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/cf5e91979f4bb3874f6164a8d661f41a4a173b10/crates/prover/src/examples/blake/scheduler/mod.rs#L19)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Same
</blockquote></details>

Done.
___
*[`scripts/bench.sh` line 5 at r3](https://reviewable.io/reviews/starkware-libs/stwo/937#-OEPHFGZ0UpWWq0Q6LbU:-OEPKPe6Bq_Z7ijWfLC4:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/3e95f5398ab6c3d343c94158a4e281706efc6eea/scripts/bench.sh#L5)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

revert
</blockquote></details>

Done.
___
*[`scripts/clippy.sh` line 2 at r3](https://reviewable.io/reviews/starkware-libs/stwo/937#-OEPHJSVA4T_QW7EawhN:-OEPKjD92sCwyuBZnhjW:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/3e95f5398ab6c3d343c94158a4e281706efc6eea/scripts/clippy.sh#L2)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

put the correct version
</blockquote></details>

Done.
___
*[`scripts/rust_fmt.sh` line 3 at r3](https://reviewable.io/reviews/starkware-libs/stwo/937#-OEPHM1d85HdaoEx3NGw:-OEPKjaPA8La0pi5OMvf:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/3e95f5398ab6c3d343c94158a4e281706efc6eea/scripts/rust_fmt.sh#L3)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[`scripts/test_avx.sh` line 4 at r3](https://reviewable.io/reviews/starkware-libs/stwo/937#-OEPHPzJ-yiAsQzK_6BH:-OEPKi7w1BkC62pbSwoA:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/cf5e91979f4bb3874f6164a8d661f41a4a173b10/scripts/test_avx.sh#L4)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

We can keep it opt_level=2 if we have the benches
</blockquote></details>

Done.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 61 files at r1, 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/937)* status: all files reviewed, 1 unresolved discussion (waiting on @ohad-starkware)

___
*[`scripts/test_avx.sh` line 4 at r4](https://reviewable.io/reviews/starkware-libs/stwo/937#-OEPTcRs2DtxzajYxGue:-OEPTcRs2DtxzajYxGuf:bsxyist) ([raw file](https://github.com/starkware-libs/stwo/blob/3ae70e11ce8880c2a53deb92e66fef461e52a877/scripts/test_avx.sh#L4)):*
> ```Shell
> # Can be used as a drop in replacement for `cargo test` with avx512f flag on.
> # For example, `./scripts/test_avx.sh` will run all tests(not only avx).
> RUSTFLAGS="-Awarnings -C target-cpu=native -C target-feature=+avx512f -C opt-level=2" cargo +nightly-2024-11-17 test "$@"
> ```

This is not the correct version



_Suggestion:_
```Shell
+nightly-2024-11-06
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/937)* status: all files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`scripts/test_avx.sh` line 4 at r4](https://reviewable.io/reviews/starkware-libs/stwo/937#-OEPTcRs2DtxzajYxGue:-OEPVD881HeqWJxLZWUm:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/3ae70e11ce8880c2a53deb92e66fef461e52a877/scripts/test_avx.sh#L4)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

This is not the correct version
</blockquote></details>

Done.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/937#-:-OEPVUDV7PMcTKqtbX9U:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ohad-starkware)

**Comment by ohad-starkware** [comment]
### Merge activity

* **Dec 18, 11:10 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/937).

**Pull request merged**
