### PR TITLE
avx ifft3

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/378)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`src/core/backend/avx512/fft.rs` line 321 at r1](https://reviewable.io/reviews/starkware-libs/stwo/378#-Ns3EVbe1TW5sOf3NC8k:-Ns3EVbe1TW5sOf3NC8l:bq18c2l) ([raw file](https://github.com/starkware-libs/stwo/blob/ca4bb5cce82c62307fc26d7f68b74431478f2ae6/src/core/backend/avx512/fft.rs#L321)):*
> ```XML
>     let step_in_u32s = step_in_vecs + 4;
>     // Load the 8 AVX vectors from the array.
>     let mut val0 = _mm512_load_epi32(values.add(offset + (0 << step_in_u32s)).cast_const());
> ```

what does this do



_Code quote:_
```XML
cast_const(
```

**Review by ilyalesokhin-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/378)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`src/core/backend/avx512/fft.rs` line 309 at r1](https://reviewable.io/reviews/starkware-libs/stwo/378#-Ns3F313-UqtMtra3D3r:-Ns3F313-UqtMtra3D3s:b-l6mwxj) ([raw file](https://github.com/starkware-libs/stwo/blob/ca4bb5cce82c62307fc26d7f68b74431478f2ae6/src/core/backend/avx512/fft.rs#L309)):*
> ```XML
> ///   twiddles_dbl0/1/2 - The double of the twiddles for the 3 layers of butterflies.
> ///   Each layer has 4/2/1 twiddles.
> ///     
> ```

remove



_Code quote:_
```XML
·····
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/378)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @spapinistarkware)

___
*[`src/core/backend/avx512/fft.rs` line 309 at r1](https://reviewable.io/reviews/starkware-libs/stwo/378#-Ns3F313-UqtMtra3D3r:-Ns3Mrkz4mPZDVoG0muo:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/e0311175db5bc8905cc713636f6fe5d2602c9d11/src/core/backend/avx512/fft.rs#L309)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.
___
*[`src/core/backend/avx512/fft.rs` line 321 at r1](https://reviewable.io/reviews/starkware-libs/stwo/378#-Ns3EVbe1TW5sOf3NC8k:-Ns3MuvWAwYYNrhfkLjU:btzcs6d) ([raw file](https://github.com/starkware-libs/stwo/blob/e0311175db5bc8905cc713636f6fe5d2602c9d11/src/core/backend/avx512/fft.rs#L321)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

what does this do
</blockquote></details>

Convert mut ptr to const ptr. That's what `_mm512_load_epi32` expects.

**Review by ilyalesokhin-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/378)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`src/core/backend/avx512/fft.rs` line 309 at r1](https://reviewable.io/reviews/starkware-libs/stwo/378#-Ns3F313-UqtMtra3D3r:-Ns7Q25O3jOKuyT6dqRT:bqwbrvv) ([raw file](https://github.com/starkware-libs/stwo/blob/90a4940a3fa52e67277bc6e5e659a4369acd0116/src/core/backend/avx512/fft.rs#L309)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not pushed

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/378)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)

___
*[`src/core/backend/avx512/fft.rs` line 309 at r1](https://reviewable.io/reviews/starkware-libs/stwo/378#-Ns3F313-UqtMtra3D3r:-Ns7kn9n7tDNGhPRHViE:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/90a4940a3fa52e67277bc6e5e659a4369acd0116/src/core/backend/avx512/fft.rs#L309)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

not pushed
</blockquote></details>

Done.

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/378#-:-Ns7myl33SRYt1Rwwntd:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
