### PR TITLE
Multi crate infrastructure

### PR DESCRIPTION
**Pull request by shaharsamocha7**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/579)

### CODE REVIEW

**Comment by shaharsamocha7** [comment]
* **#579** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/579?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @shaharsamocha7 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 94 of 96 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/579)* status: 94 of 96 files reviewed, all discussions resolved

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/579)* status: 91 of 100 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`Cargo.toml` line 2 at r2](https://reviewable.io/reviews/starkware-libs/stwo/579#-NvavMYQ-69MAGcB29cj:-Nvaxp_E2IJxoSMAcv3J:b-4qn8wn) ([raw file](https://github.com/starkware-libs/stwo/blob/529ccc3fad495efd80edf2d071173cc536144127/Cargo.toml#L2)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Add version and edition here
</blockquote></details>

It's in workspace.package.
Can't move it.
___
*[`crates/prover/Cargo.toml` line 4 at r2](https://reviewable.io/reviews/starkware-libs/stwo/579#-NvavPTXDS4_ZkxveGnm:-Nvaxy8-ApV-fM_txoJP:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/529ccc3fad495efd80edf2d071173cc536144127/crates/prover/Cargo.toml#L4)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Change to 
version.workspace = true

edition.workspace = true
</blockquote></details>

Done.
___
*[`crates/prover/Cargo.toml` line 38 at r2](https://reviewable.io/reviews/starkware-libs/stwo/579#-NvavRdC29P8fXeToyhC:-Nvaxl0MCJRQyr9i-BBV:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/529ccc3fad495efd80edf2d071173cc536144127/crates/prover/Cargo.toml#L38)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Move this section to the root cargo
</blockquote></details>

Done.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/579#-:-Nvb1NEH1Jt3ClcObeTi:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Pull request merged**
