### PR TITLE
Batch inverse lookup column denominators.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/677)

### CODE REVIEW

**Comment by alonh5** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/677?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#677** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/677?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#669** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/669?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#671](https://github.com/starkware-libs/stwo/pull/671) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/671?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#667** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/667?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#664** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/664?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#662** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/662?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#646** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/646?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#644** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/644?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#654](https://github.com/starkware-libs/stwo/pull/654) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/654?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#642** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/642?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#639** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/639?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#638** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/638?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#637** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/637?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#636** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/636?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#651** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/651?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ohad-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/677)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @shaharsamocha7)

___
*[`crates/prover/src/examples/wide_fibonacci/simd.rs` line 164 at r2](https://reviewable.io/reviews/starkware-libs/stwo/677#-O1H57o16K28iH_q2i38:-O1H57o16K28iH_q2i39:b-y8w6qo) ([raw file](https://github.com/starkware-libs/stwo/blob/91a283339268aec60e6c482236861b22dcf21093/crates/prover/src/examples/wide_fibonacci/simd.rs#L164)):*
> ```XML
> }
> 
> // TODO(AlonH): Implement.
> ```

its still not implemented

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/677)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`crates/prover/src/examples/wide_fibonacci/simd.rs` line 164 at r2](https://reviewable.io/reviews/starkware-libs/stwo/677#-O1H57o16K28iH_q2i38:-O1QqsyQBD3acEq0wnyZ:bc81ia5) ([raw file](https://github.com/starkware-libs/stwo/blob/91a283339268aec60e6c482236861b22dcf21093/crates/prover/src/examples/wide_fibonacci/simd.rs#L164)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

its still not implemented
</blockquote></details>

Right but I don't think the todo is necessary, there's a bunch of things still not implemented.

**Comment by ohad-starkware** [comment]
*[`crates/prover/src/examples/wide_fibonacci/simd.rs` line 164 at r2](https://reviewable.io/reviews/starkware-libs/stwo/677#-O1H57o16K28iH_q2i38:-O1RAEez5enmy3HDARsc:b-t77xc3) ([raw file](https://github.com/starkware-libs/stwo/blob/91a283339268aec60e6c482236861b22dcf21093/crates/prover/src/examples/wide_fibonacci/simd.rs#L164)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Right but I don't think the todo is necessary, there's a bunch of things still not implemented.
</blockquote></details>

agreed

**Review by ohad-starkware — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/677#-:-O1RAIojACX4PsD7XB91:bg7igkv)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Pull request merged**
