### PR TITLE
iter mut

### PR DESCRIPTION
**Pull request by ohad-starkware**

### CODE REVIEW

**Comment by ohad-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/953?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#953** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/953?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/953?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#952** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/952?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#948** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/948?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#946](https://github.com/starkware-libs/stwo/pull/946) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/946?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#945** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/945?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/953)* status: 1 of 4 files reviewed, 6 unresolved discussions (waiting on @ilyalesokhin-starkware and @ohad-starkware)

___
*[`crates/air_utils_derive/src/iterable_field.rs` line 69 at r3](https://reviewable.io/reviews/starkware-libs/stwo/953#-OFM8rJX-6qbaOhPbjI9:-OFM8rJX-6qbaOhPbjIA:bbw2h4c) ([raw file](https://github.com/starkware-libs/stwo/blob/de0b1cf48333482c7659f038913928891420889d/crates/air_utils_derive/src/iterable_field.rs#L69)):*
> ```XML
>     /// E.g. `&'a mut [u32]` for a `Vec<u32>` field.
>     /// E.g. [`&'a mut u32; N]` for a `[Vec<u32>; N]` field.
>     pub fn mut_slice_type(&self, lifetime: &Lifetime) -> TokenStream {
> ```

Can we rename those functions?
All the names have the same meaning for me

Why not combining into a single function with or without liftetime etc?



_Code quote:_
```XML
    pub fn mut_slice_type(&self, lifetime: &Lifetime) -> TokenStream {
```
___
*[`crates/air_utils/src/lookup_data/mod.rs` line 41 at r3](https://reviewable.io/reviews/starkware-libs/stwo/953#-OFM5lXM9tBF2svpVXu4:-OFM5lXN6JmPuHjnMdJg:b-l6mkjh) ([raw file](https://github.com/starkware-libs/stwo/blob/de0b1cf48333482c7659f038913928891420889d/crates/air_utils/src/lookup_data/mod.rs#L41)):*
> ```XML
>     fn test_derived_lookup_data_iter_mut() {
>         const N_COLUMNS: usize = 5;
>         const LOG_SIZE: u32 = 8;
> ```

rename



_Suggestion:_
```XML
const LOG_N_ROWS: u32 = 8;
```
___
*[`crates/air_utils/src/lookup_data/mod.rs` line 45 at r3](https://reviewable.io/reviews/starkware-libs/stwo/953#-OFM6BioExOi-Tl5xdB4:-OFM6Bip3L8nmnZSEMtS:b-dyz7qh) ([raw file](https://github.com/starkware-libs/stwo/blob/de0b1cf48333482c7659f038913928891420889d/crates/air_utils/src/lookup_data/mod.rs#L45)):*
> ```XML
>         let arr = (0..1 << LOG_SIZE).map(M31::from).collect_vec();
>         let mut lookup_data = unsafe { LookupData::uninitialized(LOG_SIZE - LOG_N_LANES) };
>         let expected: (Vec<_>, Vec<_>, Vec<_>) = arr
> ```

Consider to unparse directly
related to next comment



_Suggestion:_
```XML
let (expected_field0, expected_field1, expected_field2): (Vec<_>, Vec<_>, Vec<_>) = arr
```
___
*[`crates/air_utils/src/lookup_data/mod.rs` line 93 at r3](https://reviewable.io/reviews/starkware-libs/stwo/953#-OFM6Nwb4lZsb4fWsUcs:-OFM6Nwb4lZsb4fWsUct:bofhzpo) ([raw file](https://github.com/starkware-libs/stwo/blob/de0b1cf48333482c7659f038913928891420889d/crates/air_utils/src/lookup_data/mod.rs#L93)):*
> ```XML
>             ),
>             "Failed on Vec<PackedM31>"
>         );
> ```

Consider to remove all this code below and implement assert_field on the lookup struct



_Code quote:_
```XML
        let actual = (
            lookup_data.field0,
            lookup_data.field1,
            (lookup_data.field2[0].clone(), lookup_data.field2[1].clone()),
        );

        assert!(
            all(
                expected
                    .0
                    .iter()
                    .zip(actual.0.iter())
                    .map(|(expected, actual)| (expected.to_array(), actual.to_array())),
                |(expected, actual)| expected == actual
            ),
            "Failed on Vec<PackedM31>"
        );
```
___
*[`crates/air_utils_derive/src/iter_mut.rs` line 8 at r3](https://reviewable.io/reviews/starkware-libs/stwo/953#-OFM77lo8Abz_Ae2_YHw:-OFM77lo8Abz_Ae2_YHx:bpeerdj) ([raw file](https://github.com/starkware-libs/stwo/blob/de0b1cf48333482c7659f038913928891420889d/crates/air_utils_derive/src/iter_mut.rs#L8)):*
> ```XML
> use crate::iterable_field::IterableField;
> 
> pub fn expand_iter_mut_structs(
> ```

I think you should break this function



_Code quote:_
```XML
pub fn expand_iter_mut_structs(
```
___
*[`crates/air_utils_derive/src/iter_mut.rs` line 45 at r3](https://reviewable.io/reviews/starkware-libs/stwo/953#-OFM71GP0-ToLyncjSSx:-OFM71GQ9VH-Kw0s9ciT:ban8x0n) ([raw file](https://github.com/starkware-libs/stwo/blob/de0b1cf48333482c7659f038913928891420889d/crates/air_utils_derive/src/iter_mut.rs#L45)):*
> ```XML
>             )
>         })
>         .multiunzip();
> ```

Can we not have this code :)?
Some of those vars are only used once



_Code quote:_
```XML
    let (
        field_names,
        mut_chunk_types,
        mut_slice_types,
        mut_ptr_types,
        as_mut_slice,
        as_mut_ptr,
        split_first,
        split_last,
    ): (
        Vec<_>,
        Vec<_>,
        Vec<_>,
        Vec<_>,
        Vec<_>,
        Vec<_>,
        Vec<_>,
        Vec<_>,
    ) = iterable_fields
        .iter()
        .map(|f| {
            (
                f.name(),
                f.mut_chunk_type(&lifetime),
                f.mut_slice_type(&lifetime),
                f.mut_slice_ptr_type(),
                f.as_mut_slice(),
                f.as_mut_ptr(),
                f.split_first(),
                f.split_last(&format_ident!("len")),
            )
        })
        .multiunzip();
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/953)* status: 1 of 4 files reviewed, 6 unresolved discussions (waiting on @ilyalesokhin-starkware and @shaharsamocha7)

___
*[`crates/air_utils/src/lookup_data/mod.rs` line 41 at r3](https://reviewable.io/reviews/starkware-libs/stwo/953#-OFM5lXM9tBF2svpVXu4:-OFMAfrA5pSxG_7l2lvo:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/de0b1cf48333482c7659f038913928891420889d/crates/air_utils/src/lookup_data/mod.rs#L41)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

rename
</blockquote></details>

Done.
___
*[`crates/air_utils/src/lookup_data/mod.rs` line 45 at r3](https://reviewable.io/reviews/starkware-libs/stwo/953#-OFM6BioExOi-Tl5xdB4:-OFMAoXJ4CeVnjNwlInR:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/de0b1cf48333482c7659f038913928891420889d/crates/air_utils/src/lookup_data/mod.rs#L45)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Consider to unparse directly
related to next comment
</blockquote></details>

Done.
___
*[`crates/air_utils/src/lookup_data/mod.rs` line 93 at r3](https://reviewable.io/reviews/starkware-libs/stwo/953#-OFM6Nwb4lZsb4fWsUcs:-OFMDWr65J8o3uM9bJ9H:bvyb82y) ([raw file](https://github.com/starkware-libs/stwo/blob/de0b1cf48333482c7659f038913928891420889d/crates/air_utils/src/lookup_data/mod.rs#L93)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Consider to remove all this code below and implement assert_field on the lookup struct
</blockquote></details>

better?
___
*[`crates/air_utils_derive/src/iter_mut.rs` line 8 at r3](https://reviewable.io/reviews/starkware-libs/stwo/953#-OFM77lo8Abz_Ae2_YHw:-OFMAvsfDef0wpK587Ix:b-6a8p01) ([raw file](https://github.com/starkware-libs/stwo/blob/de0b1cf48333482c7659f038913928891420889d/crates/air_utils_derive/src/iter_mut.rs#L8)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I think you should break this function
</blockquote></details>

is that a must?
I think the correct way to handle proc macros is to leave as few logic as possible in the main proc_macro function
___
*[`crates/air_utils_derive/src/iter_mut.rs` line 45 at r3](https://reviewable.io/reviews/starkware-libs/stwo/953#-OFM71GP0-ToLyncjSSx:-OFMB6VY4FnWj9I_dbTu:b2nxi8z) ([raw file](https://github.com/starkware-libs/stwo/blob/de0b1cf48333482c7659f038913928891420889d/crates/air_utils_derive/src/iter_mut.rs#L45)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can we not have this code :)?
Some of those vars are only used once
</blockquote></details>

quote! syntax does not allow #(some_function()), you have to declare your variable and then #var_name
this is a different quote than the one we are using in code gen
___
*[`crates/air_utils_derive/src/iterable_field.rs` line 69 at r3](https://reviewable.io/reviews/starkware-libs/stwo/953#-OFM8rJX-6qbaOhPbjI9:-OFMBRtcAzAqTejDTQlf:b-gvolid) ([raw file](https://github.com/starkware-libs/stwo/blob/de0b1cf48333482c7659f038913928891420889d/crates/air_utils_derive/src/iterable_field.rs#L69)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can we rename those functions?
All the names have the same meaning for me

Why not combining into a single function with or without liftetime etc?
</blockquote></details>

I don't want to state the lifetime in a few places, that might cause bugs upon refactor
as for renaming, suggestion?

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/953)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware and @ohad-starkware)

___
*[`crates/air_utils/src/lookup_data/mod.rs` line 93 at r3](https://reviewable.io/reviews/starkware-libs/stwo/953#-OFM6Nwb4lZsb4fWsUcs:-OFMJuEz75053SBZTZIT:b-bd4g5y) ([raw file](https://github.com/starkware-libs/stwo/blob/de0b1cf48333482c7659f038913928891420889d/crates/air_utils/src/lookup_data/mod.rs#L93)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

better?
</blockquote></details>

Yes
Consider to change fields_are_equal() to assert_field()
non-blocking
___
*[`crates/air_utils_derive/src/iter_mut.rs` line 8 at r3](https://reviewable.io/reviews/starkware-libs/stwo/953#-OFM77lo8Abz_Ae2_YHw:-OFMKK6q09kNfyKgpsHC:b-h9b9fb) ([raw file](https://github.com/starkware-libs/stwo/blob/de0b1cf48333482c7659f038913928891420889d/crates/air_utils_derive/src/iter_mut.rs#L8)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

is that a must?
I think the correct way to handle proc macros is to leave as few logic as possible in the main proc_macro function
</blockquote></details>

break as split it to multiple functions
___
*[`crates/air_utils_derive/src/iter_mut.rs` line 45 at r3](https://reviewable.io/reviews/starkware-libs/stwo/953#-OFM71GP0-ToLyncjSSx:-OFMKWWp5Bj8822vQIYp:bbulze1) ([raw file](https://github.com/starkware-libs/stwo/blob/de0b1cf48333482c7659f038913928891420889d/crates/air_utils_derive/src/iter_mut.rs#L45)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

quote! syntax does not allow #(some_function()), you have to declare your variable and then #var_name
this is a different quote than the one we are using in code gen
</blockquote></details>

So it's another reason to split the function
I think you should get the mut_* things together, but it is unrelated to split_first/split_last
___
*[`crates/air_utils_derive/src/iterable_field.rs` line 69 at r3](https://reviewable.io/reviews/starkware-libs/stwo/953#-OFM8rJX-6qbaOhPbjI9:-OFML4J0ENJcOwHO1z0b:b-u2jl30) ([raw file](https://github.com/starkware-libs/stwo/blob/de0b1cf48333482c7659f038913928891420889d/crates/air_utils_derive/src/iterable_field.rs#L69)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

I don't want to state the lifetime in a few places, that might cause bugs upon refactor
as for renaming, suggestion?
</blockquote></details>

I thought that you'll have a use_lifetime flag and then you'll generate the exact type using a match
WDYT?
___
*[`crates/air_utils/src/lookup_data/mod.rs` line 80 at r4](https://reviewable.io/reviews/starkware-libs/stwo/953#-OFMJwbl7w2NUTEL2Cmu:-OFMJwbl7w2NUTEL2Cmv:bj0g42z) ([raw file](https://github.com/starkware-libs/stwo/blob/76da1ce54e9255a450f9437e2aaacf8fb1a82111/crates/air_utils/src/lookup_data/mod.rs#L80)):*
> ```XML
>             lookup_data.field1,
>             (lookup_data.field2[0].clone(), lookup_data.field2[1].clone()),
>         );
> ```

I would also remove this code and send lookup_data.field* to fields_are_equal directly



_Code quote:_
```XML
        let actual = (
            lookup_data.field0,
            lookup_data.field1,
            (lookup_data.field2[0].clone(), lookup_data.field2[1].clone()),
        );
```

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/953)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @shaharsamocha7)

___
*[`crates/air_utils/src/lookup_data/mod.rs` line 80 at r4](https://reviewable.io/reviews/starkware-libs/stwo/953#-OFMJwbl7w2NUTEL2Cmu:-OFMNiLW0hpfLdGOMl_u:b-tfan8w) ([raw file](https://github.com/starkware-libs/stwo/blob/76da1ce54e9255a450f9437e2aaacf8fb1a82111/crates/air_utils/src/lookup_data/mod.rs#L80)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I would also remove this code and send lookup_data.field* to fields_are_equal directly
</blockquote></details>

we dont have Eq on PackedM31
___
*[`crates/air_utils_derive/src/iter_mut.rs` line 8 at r3](https://reviewable.io/reviews/starkware-libs/stwo/953#-OFM77lo8Abz_Ae2_YHw:-OFMOBGo7-wFaiKM87ba:b-x9txhw) ([raw file](https://github.com/starkware-libs/stwo/blob/de0b1cf48333482c7659f038913928891420889d/crates/air_utils_derive/src/iter_mut.rs#L8)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

break as split it to multiple functions
</blockquote></details>

yes and call  
quote! {
   #something
    #something2,
    ...
}

this adds logic, and will make the file bigger, which I really don't want
I already have 3 proc macros here
___
*[`crates/air_utils_derive/src/iter_mut.rs` line 45 at r3](https://reviewable.io/reviews/starkware-libs/stwo/953#-OFM71GP0-ToLyncjSSx:-OFM_gTR1FXLgjeeWsnr:bvyb82y) ([raw file](https://github.com/starkware-libs/stwo/blob/de0b1cf48333482c7659f038913928891420889d/crates/air_utils_derive/src/iter_mut.rs#L45)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

So it's another reason to split the function
I think you should get the mut_* things together, but it is unrelated to split_first/split_last
</blockquote></details>

better?
___
*[`crates/air_utils_derive/src/iterable_field.rs` line 69 at r3](https://reviewable.io/reviews/starkware-libs/stwo/953#-OFM8rJX-6qbaOhPbjI9:-OFMRcHk54wLZxPKguDq:bmo6fr5) ([raw file](https://github.com/starkware-libs/stwo/blob/de0b1cf48333482c7659f038913928891420889d/crates/air_utils_derive/src/iterable_field.rs#L69)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I thought that you'll have a use_lifetime flag and then you'll generate the exact type using a match
WDYT?
</blockquote></details>

I didn't understand
you still need to know which lifetime
what happns when you add another lifetime for some reason?

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, 1 of 2 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/953)* status: all files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware and @ohad-starkware)

___
*[`crates/air_utils_derive/src/iter_mut.rs` line 45 at r3](https://reviewable.io/reviews/starkware-libs/stwo/953#-OFM71GP0-ToLyncjSSx:-OFMdUTu0s0SFFOlVHBw:bpz8t6x) ([raw file](https://github.com/starkware-libs/stwo/blob/de0b1cf48333482c7659f038913928891420889d/crates/air_utils_derive/src/iter_mut.rs#L45)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

better?
</blockquote></details>

IMO much better
___
*[`crates/air_utils_derive/src/iterable_field.rs` line 68 at r5](https://reviewable.io/reviews/starkware-libs/stwo/953#-OFMq6Ly-Ntqi8BQmc9L:-OFMq6Ly-Ntqi8BQmc9M:bo0okr3) ([raw file](https://github.com/starkware-libs/stwo/blob/fe969946b6643612de0643f62fa8849e4313882d/crates/air_utils_derive/src/iterable_field.rs#L68)):*
> ```XML
>     /// Generate the type of a mutable slice of the field.
>     /// E.g. `&'a mut [u32]` for a `Vec<u32>` field.
>     /// E.g. [`&'a mut u32; N]` for a `[Vec<u32>; N]` field.
> ```

Fix comment



_Suggestion:_
```XML
/// E.g. [`&'a mut [u32]; N]` for a `[Vec<u32>; N]` field.
```
___
*[`crates/air_utils_derive/src/iterable_field.rs` line 110 at r5](https://reviewable.io/reviews/starkware-libs/stwo/953#-OFMqEW49o5Ts6suuM0S:-OFMqEW49o5Ts6suuM0T:bb73xfv) ([raw file](https://github.com/starkware-libs/stwo/blob/fe969946b6643612de0643f62fa8849e4313882d/crates/air_utils_derive/src/iterable_field.rs#L110)):*
> ```XML
>     /// Generate the type of a mutable slice pointer to the field.
>     /// E.g. `*mut [u32]` for a `Vec<u32>` field.
>     /// E.g. [`*mut u32; N]` for a `[Vec<u32>; N]` field.
> ```

Same



_Suggestion:_
```XML
/// E.g. [`*mut [u32]; N]` for a `[Vec<u32>; N]` field.
```
___
*[`crates/air_utils_derive/src/iterable_field.rs` line 157 at r5](https://reviewable.io/reviews/starkware-libs/stwo/953#-OFMqNSR4eo07ruYL10Y:-OFMqNSR4eo07ruYL10Z:bnep848) ([raw file](https://github.com/starkware-libs/stwo/blob/fe969946b6643612de0643f62fa8849e4313882d/crates/air_utils_derive/src/iterable_field.rs#L157)):*
> ```XML
>     /// Generate the code to split the first element from the field.
>     /// E.g. `let (head, tail) = self.field.split_at_mut(1);
>     /// self.field = tail; let field = &mut (*head)[0];`
> ```

can you doc which trait those functions intend to implement?



_Code quote:_
```XML
    /// self.field = tail; let field = &mut (*head)[0];`
```
___
*[`crates/air_utils/src/lookup_data/mod.rs` line 49 at r5](https://reviewable.io/reviews/starkware-libs/stwo/953#-OFMgsIACvV8BvlPKgtV:-OFMgsIACvV8BvlPKgtW:ba1u6x8) ([raw file](https://github.com/starkware-libs/stwo/blob/fe969946b6643612de0643f62fa8849e4313882d/crates/air_utils/src/lookup_data/mod.rs#L49)):*
> ```XML
>             Vec<_>,
>             Vec<_>,
>         ) = arr
> ```

and remove expected2



_Suggestion:_
```XML
        let (expected_field0, expected_field1, expected_field2): (
            Vec<_>,
            Vec<_>,
            (Vec<_>, Vec<_>,)
        ) = arr
```
___
*[`crates/air_utils_derive/src/iter_mut.rs` line 23 at r5](https://reviewable.io/reviews/starkware-libs/stwo/953#-OFMmmsy8EQKRkUeX-tT:-OFMmmsy8EQKRkUeX-tU:bjg90x) ([raw file](https://github.com/starkware-libs/stwo/blob/fe969946b6643612de0643f62fa8849e4313882d/crates/air_utils_derive/src/iter_mut.rs#L23)):*
> ```XML
>         #mut_chunk_struct
>         #iter_mut_struct
>         #iter_mut_new
> ```

These two could be the same function (non-blocking)



_Code quote:_
```XML
        #iter_mut_struct
        #iter_mut_new
```

**Review by shaharsamocha7 — APPROVED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/953)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

___
*[`crates/air_utils/src/lookup_data/mod.rs` line 49 at r5](https://reviewable.io/reviews/starkware-libs/stwo/953#-OFMgsIACvV8BvlPKgtV:-OFQQum3BHNx4AsCK2xO:b3nx8hp) ([raw file](https://github.com/starkware-libs/stwo/blob/fe969946b6643612de0643f62fa8849e4313882d/crates/air_utils/src/lookup_data/mod.rs#L49)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'm confused why don't you check field2?

**Review by ohad-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/953)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

___
*[`crates/air_utils/src/lookup_data/mod.rs` line 49 at r5](https://reviewable.io/reviews/starkware-libs/stwo/953#-OFMgsIACvV8BvlPKgtV:-OFQhcFo2V13DKp_wSNp:bb7f2mf) ([raw file](https://github.com/starkware-libs/stwo/blob/fe969946b6643612de0643f62fa8849e4313882d/crates/air_utils/src/lookup_data/mod.rs#L49)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I'm confused why don't you check field2?
</blockquote></details>

done

**Pull request merged**
