### PR TITLE
Modify bit_reverse for SIMD backend

### PR DESCRIPTION
**Pull request by andrewmilson**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/594)

### CODE REVIEW

**Comment by andrewmilson** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/594?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#596** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/596?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#595** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/595?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#594** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/594?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#593** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/593?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#592** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/592?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#591** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/591?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @andrewmilson and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/594)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @andrewmilson)

*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo/594#-NwsSQWI0T__v64dRb35:-NwsSQWI0T__v64dRb36:b-rzzhnv) (no related file):*
Same here, do a first commit with just copying

___

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/594)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo/594#-NwsSQWI0T__v64dRb35:-NwvuWNV60rt3OxyX90V:b-896fix) (no related file):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Same here, do a first commit with just copying
</blockquote></details>

Done.

___

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/594)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @andrewmilson and @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/bit_reverse.rs` line 124 at r2](https://reviewable.io/reviews/starkware-libs/stwo/594#-NxHxZgsEzI242gWWGs4:-NxHxZgsEzI242gWWGs5:bslszby) ([raw file](https://github.com/starkware-libs/stwo/blob/a6a991b384380ecc5206b4832f9278650ab73620/crates/prover/src/core/backend/simd/bit_reverse.rs#L124)):*
> ```XML
>     }
> 
>     unsafe { transmute(data) }
> ```

Suggestion:
Have from_simd func?



_Code quote:_
```XML
    unsafe { transmute(data) }
```
___
*[`crates/prover/src/core/backend/simd/bit_reverse.rs` line 139 at r2](https://reviewable.io/reviews/starkware-libs/stwo/594#-NxHxzys8J8PMeuEFyu6:-NxHxzys8J8PMeuEFyu7:b-hff6xw) ([raw file](https://github.com/starkware-libs/stwo/blob/a6a991b384380ecc5206b4832f9278650ab73620/crates/prover/src/core/backend/simd/bit_reverse.rs#L139)):*
> ```XML
>     use crate::core::backend::Column;
>     use crate::core::fields::m31::BaseField;
>     use crate::core::utils::bit_reverse as ground_truth_bit_reverse;
> ```

rename?



_Suggestion:_
```XML
cpu_bit_reverse
```
___
*[`crates/prover/src/core/backend/simd/bit_reverse.rs` line 144 at r2](https://reviewable.io/reviews/starkware-libs/stwo/594#-NxHxsk6BZf9r-4we6H7:-NxHxsk6BZf9r-4we6H8:bvz6wba) ([raw file](https://github.com/starkware-libs/stwo/blob/a6a991b384380ecc5206b4832f9278650ab73620/crates/prover/src/core/backend/simd/bit_reverse.rs#L144)):*
> ```XML
>     fn test_bit_reverse16() {
>         let data: Aligned<A64, [u32; 256]> = Aligned(array::from_fn(|i| i as u32));
>         let mut expected: Aligned<A64, [u32; 256]> = data;
> ```

Can you explain/document why we need this Aligned?



_Code quote:_
```XML
        let data: Aligned<A64, [u32; 256]> = Aligned(array::from_fn(|i| i as u32));
        let mut expected: Aligned<A64, [u32; 256]> = data;
```
___
*[`crates/prover/src/core/backend/simd/mod.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/stwo/594#-NxI-b64Cp70iQrKJTQy:-NxI-b64Cp70iQrKJTQz:b-bosgcr) ([raw file](https://github.com/starkware-libs/stwo/blob/a6a991b384380ecc5206b4832f9278650ab73620/crates/prover/src/core/backend/simd/mod.rs#L45)):*
> ```XML
> 
>     fn bit_reverse_column(_column: &mut Self::Column) {
>         todo!()
> ```


Don't you implement also this one?



_Code quote:_
```XML
todo!()
```

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/594)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/bit_reverse.rs` line 139 at r2](https://reviewable.io/reviews/starkware-libs/stwo/594#-NxHxzys8J8PMeuEFyu6:-NxIlPpU0ueRjDpyOKGp:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/a6a991b384380ecc5206b4832f9278650ab73620/crates/prover/src/core/backend/simd/bit_reverse.rs#L139)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

rename?
</blockquote></details>

Done.
___
*[`crates/prover/src/core/backend/simd/bit_reverse.rs` line 144 at r2](https://reviewable.io/reviews/starkware-libs/stwo/594#-NxHxsk6BZf9r-4we6H7:-NxIlAc_3Ywr8xILbAhY:b-ehojj2) ([raw file](https://github.com/starkware-libs/stwo/blob/a6a991b384380ecc5206b4832f9278650ab73620/crates/prover/src/core/backend/simd/bit_reverse.rs#L144)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can you explain/document why we need this Aligned?
</blockquote></details>

Removed, updated.
___
*[`crates/prover/src/core/backend/simd/mod.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/stwo/594#-NxI-b64Cp70iQrKJTQy:-NxIEKxM1jRJ1SduVBbU:b3m1hxw) ([raw file](https://github.com/starkware-libs/stwo/blob/a6a991b384380ecc5206b4832f9278650ab73620/crates/prover/src/core/backend/simd/mod.rs#L45)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Don't you implement also this one?
</blockquote></details>

Not for &mut [PackedSecureField] only for &mut [PackedBaseField]

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/594#-:-NxMLO6t5BJp8Ui1jcjs:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/mod.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/stwo/594#-NxI-b64Cp70iQrKJTQy:-NxMKuDVEFWlOgW8-lZb:b-imxtr8) ([raw file](https://github.com/starkware-libs/stwo/blob/a6a991b384380ecc5206b4832f9278650ab73620/crates/prover/src/core/backend/simd/mod.rs#L45)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Not for &mut [PackedSecureField] only for &mut [PackedBaseField]
</blockquote></details>

Why not? in another pr?

**Review by andrewmilson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/594)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7 and @spapinistarkware)

___
*[`crates/prover/src/core/backend/simd/mod.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/stwo/594#-NxI-b64Cp70iQrKJTQy:-NxSosaR3WRaZDS1R0NG:b-wzvyky) ([raw file](https://github.com/starkware-libs/stwo/blob/a6a991b384380ecc5206b4832f9278650ab73620/crates/prover/src/core/backend/simd/mod.rs#L45)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why not? in another pr?
</blockquote></details>

Sure, it's not used anywhere at the moment AFAIK and it's not trivial. AVX backend has a bogus implementation of it too

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/594)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @andrewmilson)

___
*[`crates/prover/src/core/backend/simd/bit_reverse.rs` line 119 at r5](https://reviewable.io/reviews/starkware-libs/stwo/594#-NxvGfJl8XqCgW6VKxKu:-NxvGfJl8XqCgW6VKxKv:b-sd1qc3) ([raw file](https://github.com/starkware-libs/stwo/blob/27199658fcebff1979e345bbc91091073084f1ef/crates/prover/src/core/backend/simd/bit_reverse.rs#L119)):*
> ```XML
>     for _ in 0..4 {
>         // Apply the abcd:0123 => 0abc:123d permutation.
>         // `LoLoInterleaveHiLo` allows us to interleave the first half of 2 words.
> ```

I don't see any reference for this (before as well). Maybe skip it, and just keep the interleave.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/594#-:-NxvH5CvDsvRMqd-FgOD:bnfp4nl)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @andrewmilson)

**Review by spapinistarkware — APPROVED** [review]
with one comment

> Reviewed 1 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/594#-:-NxvHFWNAlEoTIUH_Max:b-or8z3k)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @andrewmilson)

**Pull request merged**
