### PR TITLE
Added `From<G>` in `add_constraint`.

### PR DESCRIPTION
**Pull request by Alon-Ti**

### CODE REVIEW

**Comment by Alon-Ti** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/901?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#901** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/901?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/901?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#894** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/894?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#893** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/893?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#892** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/892?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#889** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/889?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#888** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/888?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#887** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/887?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#879** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/879?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#883](https://github.com/starkware-libs/stwo/pull/883) <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/883?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#876** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/876?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#875** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/875?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by ohad-starkware — APPROVED** [review]
:lgtm: with comment

> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/901#-:-OCYnY_h6S6nEa8pvMXL:b10c0l0)* status: 1 of 5 files reviewed, all discussions resolved

___
*[`crates/prover/src/constraint_framework/expr.rs` line 403 at r1](https://reviewable.io/reviews/starkware-libs/stwo/901#-OCYnLLG8Dx8poMW9elf:-OCYnLLG8Dx8poMW9elg:b-r611zn) ([raw file](https://github.com/starkware-libs/stwo/blob/5d3a395ae10d778a48344b3407d701715da30ca9/crates/prover/src/constraint_framework/expr.rs#L403)):*
> ```XML
>     fn add_constraint<G>(&mut self, constraint: G)
>     where
>         Self::EF: std::ops::Mul<G, Output = Self::EF> + From<G>,
> ```

non blocking



_Suggestion:_
```XML
 Self::EF: From<G
```

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 5 files at r1, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/901#-:-OCiBE3u2RWxTozusbGU:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Alon-Ti)

**Comment by Alon-Ti** [comment]
### Merge activity

* **Nov 28, 10:29 AM EST**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/901).

**Pull request merged**
