### PR TITLE
Constraints eval for wide fib

### PR DESCRIPTION
**Pull request by shaharsamocha7**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/543)

### CODE REVIEW

**Comment by shaharsamocha7** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/543?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#543** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/543?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#542** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/542?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#541** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/541?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#540** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/540?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @shaharsamocha7 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/543)* status: all files reviewed, 3 unresolved discussions (waiting on @shaharsamocha7)

___
*[`src/example_airs/wide_fibonacci/constraint_eval.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/stwo/543#-NttYd7H9qJLUF58noBS:-NttYd7H9qJLUF58noBT:b-y8bq6z) ([raw file](https://github.com/starkware-libs/stwo/blob/fe4ddf4d5c49abcabea03f0af2877c80ddf66c16/src/example_airs/wide_fibonacci/constraint_eval.rs#L39)):*
> ```XML
>             let trace_eval_domain =
>                 CanonicCoset::new(self.max_constraint_log_degree_bound()).circle_domain();
>             trace_evals.push(poly.evaluate(trace_eval_domain).bit_reverse());
> ```

Add a TODO to save this evaluation.
___
*[`src/example_airs/wide_fibonacci/constraint_eval.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/stwo/543#-NttYitG6jiEFpEkMWTz:-NttYitG6jiEFpEkMWU-:b-l17qxg) ([raw file](https://github.com/starkware-libs/stwo/blob/fe4ddf4d5c49abcabea03f0af2877c80ddf66c16/src/example_airs/wide_fibonacci/constraint_eval.rs#L56)):*
> ```XML
>             evaluation_accumulator.columns([(self.max_constraint_log_degree_bound(), 64)]);
>         for (i, point_index) in eval_domain.iter_indices().enumerate() {
>             numerators[i] = numerators[i] * random_coeff
> ```

Add a todo to precompute powers
___
*[`src/example_airs/wide_fibonacci/constraint_eval.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/stwo/543#-NttYmtI6tYTAd0S_X6g:-NttYmtI6tYTAd0S_X6h:b8qeqh7) ([raw file](https://github.com/starkware-libs/stwo/blob/fe4ddf4d5c49abcabea03f0af2877c80ddf66c16/src/example_airs/wide_fibonacci/constraint_eval.rs#L56)):*
> ```XML
>             evaluation_accumulator.columns([(self.max_constraint_log_degree_bound(), 64)]);
>         for (i, point_index) in eval_domain.iter_indices().enumerate() {
>             numerators[i] = numerators[i] * random_coeff
> ```

Add a todo to use intermediate values to save computation

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/543)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`src/example_airs/wide_fibonacci/constraint_eval.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/stwo/543#-NttYd7H9qJLUF58noBS:-Ntzhgv51B9zw34KWraw:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/fe4ddf4d5c49abcabea03f0af2877c80ddf66c16/src/example_airs/wide_fibonacci/constraint_eval.rs#L39)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Add a TODO to save this evaluation.
</blockquote></details>

Done.
___
*[`src/example_airs/wide_fibonacci/constraint_eval.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/stwo/543#-NttYitG6jiEFpEkMWTz:-NtzhhG2BxeVAbCx19ae:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/fe4ddf4d5c49abcabea03f0af2877c80ddf66c16/src/example_airs/wide_fibonacci/constraint_eval.rs#L56)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Add a todo to precompute powers
</blockquote></details>

Done.
___
*[`src/example_airs/wide_fibonacci/constraint_eval.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/stwo/543#-NttYmtI6tYTAd0S_X6g:-Ntzhh_o8o8jWXE7blsE:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/fe4ddf4d5c49abcabea03f0af2877c80ddf66c16/src/example_airs/wide_fibonacci/constraint_eval.rs#L56)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Add a todo to use intermediate values to save computation
</blockquote></details>

Done.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/543#-:-NtzidH61TpBOTlPgNpU:bnfp4nl)* status: 1 of 4 files reviewed, all discussions resolved

**Comment by shaharsamocha7** [comment]
### Merge activity

* **Mar 27, 8:10 AM EDT**: @shaharsamocha7 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/543).

**Pull request merged**
