### PR TITLE
Parallelize `evaluate_constraint_quotients_on_domain`.

### PR DESCRIPTION
**Pull request by Alon-Ti**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/843)

### CODE REVIEW

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/843)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Alon-Ti)

___
*[`crates/prover/src/constraint_framework/component.rs` line 192 at r1](https://reviewable.io/reviews/starkware-libs/stwo/843#-O78PSm18nAGTjrZkT36:-O78PSm18nAGTjrZkT37:b6efnyj) ([raw file](https://github.com/starkware-libs/stwo/blob/5c158eb262767177d502cf5becd5421880e18f2f/crates/prover/src/constraint_framework/component.rs#L192)):*
> ```XML
>             .into_par_iter()
>             .step_by(CHUNK_SIZE)
>             .zip(col.chunks_mut(CHUNK_SIZE));
> ```

Why do you have CHUNK_SIZE here?
I thought that we parallelize over each VeryPacked object



_Code quote:_
```XML
        let iter = range
            .into_par_iter()
            .step_by(CHUNK_SIZE)
            .zip(col.chunks_mut(CHUNK_SIZE));
```

**Comment by Alon-Ti** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/843?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#843** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/843?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#842** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/842?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Alon-Ti and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by Alon-Ti — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/843)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`crates/prover/src/constraint_framework/component.rs` line 192 at r1](https://reviewable.io/reviews/starkware-libs/stwo/843#-O78PSm18nAGTjrZkT36:-O7Nuy-WB8hUv4oXtG7q:b1kt8nv) ([raw file](https://github.com/starkware-libs/stwo/blob/13bf3c9b927edf0c7a22bcd54c42d15275de780a/crates/prover/src/constraint_framework/component.rs#L192)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why do you have CHUNK_SIZE here?
I thought that we parallelize over each VeryPacked object
</blockquote></details>

`VeryPacked` objects are for memory fetching optimization, optimal parallelization chunks might be larger, currently keeping them the same but we can tinker with it later based on hardware.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/843)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @Alon-Ti)

___
*[`poseidon_benchmark.sh` line 3 at r1](https://reviewable.io/reviews/starkware-libs/stwo/843#-O7Oh8kuBTdIgPP_575x:-O7Oh8kuBTdIgPP_575y:btplg9v) ([raw file](https://github.com/starkware-libs/stwo/blob/13bf3c9b927edf0c7a22bcd54c42d15275de780a/poseidon_benchmark.sh#L3)):*
> ```Shell
> LOG_N_INSTANCES=18 RUST_LOG_SPAN_EVENTS=enter,close RUST_LOG=info \
>     RUSTFLAGS="-C target-cpu=native -C opt-level=3" \
>     cargo test test_simd_poseidon_prove --features parallel -- --nocapture
> ```

Can we compare the bench with the single thread one?
Also, maybe we should compare with ShaharP stuck that was trying to make the poseidon bench fast.



_Code quote:_
```Shell
cargo test test_simd_poseidon_prove --features parallel -- --nocapture
```
___
*[`crates/prover/src/constraint_framework/component.rs` line 137 at r1](https://reviewable.io/reviews/starkware-libs/stwo/843#-O7OhUgV-3aETz74RRLd:-O7OhUgV-3aETz74RRLe:bl9w4qh) ([raw file](https://github.com/starkware-libs/stwo/blob/13bf3c9b927edf0c7a22bcd54c42d15275de780a/crates/prover/src/constraint_framework/component.rs#L137)):*
> ```XML
> }
> 
> impl<E: FrameworkEval + Sync> ComponentProver<SimdBackend> for FrameworkComponent<E> {
> ```

What's that?
Maybe FrameworkEval: Sync?



_Code quote:_
```XML
 + Sync
```

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/843#-:-O7ib8X1CYo9jWg3Y0N7:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Alon-Ti)

**Pull request merged**
