### PR TITLE
added coset_diff

### PR DESCRIPTION
**Pull request by ohad-agadi**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/583)

### CODE REVIEW

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/583)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @ohad-starkware)

___
*[`crates/prover/src/core/backend/cpu/fri.rs` line 27 at r3](https://reviewable.io/reviews/starkware-libs/stwo/583#-NwJNDqREAwiZxVW-mmb:-NwJNDqREAwiZxVW-mmc:b-ib90xj) ([raw file](https://github.com/starkware-libs/stwo/blob/d36fc39e9c11330c0e4c644aef81e385c2605f3f/crates/prover/src/core/backend/cpu/fri.rs#L27)):*
> ```XML
>     }
> 
>     fn coset_diff(eval: &SecureEvaluation<Self>) -> SecureField {
> ```

Add an assert somewhere related that the log blowup factor is 1, otherwise, we would need to fix / generalize the logic here.
___
*[`crates/prover/src/core/backend/cpu/fri.rs` line 61 at r3](https://reviewable.io/reviews/starkware-libs/stwo/583#-NwJNdln8_GuNSVMV6vl:-NwJNdln8_GuNSVMV6vm:b-kbc4u8) ([raw file](https://github.com/starkware-libs/stwo/blob/d36fc39e9c11330c0e4c644aef81e385c2605f3f/crates/prover/src/core/backend/cpu/fri.rs#L61)):*
> ```XML
>     #[test]
>     fn coset_diff_out_fft_space_test() {
>         const DOMAIN_LOG_SIZE: u32 = 5;
> ```

Check with multiple log domains



_Code quote:_
```XML
5
```

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/583)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @ohad-starkware)

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/583)* status: 1 of 6 files reviewed, 3 unresolved discussions (waiting on @ohad-starkware)

___
*[`crates/prover/src/core/backend/avx512/fri.rs` line 199 at r3](https://reviewable.io/reviews/starkware-libs/stwo/583#-NwJSPU18EMiVAXWf9Zd:-NwJSPU18EMiVAXWf9Ze:b-j0qe9a) ([raw file](https://github.com/starkware-libs/stwo/blob/d36fc39e9c11330c0e4c644aef81e385c2605f3f/crates/prover/src/core/backend/avx512/fri.rs#L199)):*
> ```XML
>     #[test]
>     fn coset_diff_out_fft_space_test() {
>         const DOMAIN_LOG_SIZE: u32 = 5;
> ```

I think an easier test for AVX backend is to compare against the CPU backend, and it will be good for examples for other backends.

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/583)* status: 1 of 6 files reviewed, 4 unresolved discussions (waiting on @ohad-starkware)

___
*[`crates/prover/src/core/fri.rs` line 116 at r3](https://reviewable.io/reviews/starkware-libs/stwo/583#-NwJS_oCCkyPUIZYv7n7:-NwJS_oCCkyPUIZYv7n8:bkcv7xl) ([raw file](https://github.com/starkware-libs/stwo/blob/d36fc39e9c11330c0e4c644aef81e385c2605f3f/crates/prover/src/core/fri.rs#L116)):*
> ```XML
>     );
> 
>     /// Computes the difference in evaluations on the  [`CircleDomain`]'s half-coset and it's
> ```

Extend the doc here with some more math

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 2 of 5 files at r2, 3 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/583)* status: all files reviewed, 4 unresolved discussions (waiting on @ohad-starkware)

**Review by ohad-agadi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/583)* status: 4 of 6 files reviewed, 4 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/core/fri.rs` line 116 at r3](https://reviewable.io/reviews/starkware-libs/stwo/583#-NwJS_oCCkyPUIZYv7n7:-NwJc4dc4o_VVvknlyv3:bb6un1j) ([raw file](https://github.com/starkware-libs/stwo/blob/d36fc39e9c11330c0e4c644aef81e385c2605f3f/crates/prover/src/core/fri.rs#L116)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Extend the doc here with some more math
</blockquote></details>

Done
___
*[`crates/prover/src/core/backend/avx512/fri.rs` line 199 at r3](https://reviewable.io/reviews/starkware-libs/stwo/583#-NwJSPU18EMiVAXWf9Zd:-NwJSo6eAZt82vJLH06w:bpoboti) ([raw file](https://github.com/starkware-libs/stwo/blob/d36fc39e9c11330c0e4c644aef81e385c2605f3f/crates/prover/src/core/backend/avx512/fri.rs#L199)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

I think an easier test for AVX backend is to compare against the CPU backend, and it will be good for examples for other backends.
</blockquote></details>

i'm doing that
___
*[`crates/prover/src/core/backend/cpu/fri.rs` line 27 at r3](https://reviewable.io/reviews/starkware-libs/stwo/583#-NwJNDqREAwiZxVW-mmb:-NwJZvQi1OkKjbz24Udc:b-wt5n94) ([raw file](https://github.com/starkware-libs/stwo/blob/d36fc39e9c11330c0e4c644aef81e385c2605f3f/crates/prover/src/core/backend/cpu/fri.rs#L27)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Add an assert somewhere related that the log blowup factor is 1, otherwise, we would need to fix / generalize the logic here.
</blockquote></details>

will do, is it ok if it's just a warning for now, and later ill assert it in one of the callers?
___
*[`crates/prover/src/core/backend/cpu/fri.rs` line 61 at r3](https://reviewable.io/reviews/starkware-libs/stwo/583#-NwJNdln8_GuNSVMV6vl:-NwJdEix4Ak-iaDAMsX6:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/d36fc39e9c11330c0e4c644aef81e385c2605f3f/crates/prover/src/core/backend/cpu/fri.rs#L61)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Check with multiple log domains
</blockquote></details>

Done.

**Review by ohad-agadi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/583)* status: 4 of 6 files reviewed, 4 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/core/backend/cpu/fri.rs` line 27 at r3](https://reviewable.io/reviews/starkware-libs/stwo/583#-NwJNDqREAwiZxVW-mmb:-NwJl7745pduW7DdL64w:b-ue5nqr) ([raw file](https://github.com/starkware-libs/stwo/blob/d36fc39e9c11330c0e4c644aef81e385c2605f3f/crates/prover/src/core/backend/cpu/fri.rs#L27)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

will do, is it ok if it's just a warning for now, and later ill assert it in one of the callers?
</blockquote></details>

actually it doesn't fit in decompose either, maybe it should be during fri::commit.

**Comment by ohad-starkware** [comment]
* **#588** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/588?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#583** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/583?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ohad-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — COMMENTED** [review]
> Reviewed 2 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/583)* status: all files reviewed, 1 unresolved discussion (waiting on @ohad-starkware)

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/583)* status: all files reviewed, 1 unresolved discussion (waiting on @ohad-starkware)

___
*[`crates/prover/src/core/backend/cpu/fri.rs` line 27 at r3](https://reviewable.io/reviews/starkware-libs/stwo/583#-NwJNDqREAwiZxVW-mmb:-NwrwcJ7-J2_1WygN53c:bbtocjw) ([raw file](https://github.com/starkware-libs/stwo/blob/d36fc39e9c11330c0e4c644aef81e385c2605f3f/crates/prover/src/core/backend/cpu/fri.rs#L27)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

actually it doesn't fit in decompose either, maybe it should be during fri::commit.
</blockquote></details>

Sure. But add an assert so that when someone tries to change the blowup factor he'll get an explicit error.

**Review by ohad-agadi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/583)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @ohad-starkware and @spapinistarkware)

___
*[`crates/prover/src/core/backend/cpu/fri.rs` line 27 at r3](https://reviewable.io/reviews/starkware-libs/stwo/583#-NwJNDqREAwiZxVW-mmb:-Nx7RNV81SLu4luob_V0:b-gdcjs7) ([raw file](https://github.com/starkware-libs/stwo/blob/d36fc39e9c11330c0e4c644aef81e385c2605f3f/crates/prover/src/core/backend/cpu/fri.rs#L27)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Sure. But add an assert so that when someone tries to change the blowup factor he'll get an explicit error.
</blockquote></details>

added in #598

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/583)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @ohad-starkware)

___
*[`crates/prover/src/core/backend/avx512/fri.rs` line 99 at r7](https://reviewable.io/reviews/starkware-libs/stwo/583#-NxBcFKCEL745jYnoyvb:-NxBcFKCEL745jYnoyvc:bf60gvj) ([raw file](https://github.com/starkware-libs/stwo/blob/0d12cbc2ae804e326cd1616457125bc227787159/crates/prover/src/core/backend/avx512/fri.rs#L99)):*
> ```XML
>     /// See [`CPUBackend::decomposition_coefficient`].
>     ///
>     /// [`CPUBackend::decomposition_coefficient`]: crate::core::backend::cpu::CPUBackend::decomposition_coefficient
> ```

Line too long

**Review by ohad-agadi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/583)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/core/backend/avx512/fri.rs` line 99 at r7](https://reviewable.io/reviews/starkware-libs/stwo/583#-NxBcFKCEL745jYnoyvb:-NxRPndH31Bd542-o2_U:bb7f2mf) ([raw file](https://github.com/starkware-libs/stwo/blob/0d12cbc2ae804e326cd1616457125bc227787159/crates/prover/src/core/backend/avx512/fri.rs#L99)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Line too long
</blockquote></details>

done

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/583#-:-Nxv4op46Mba_daqmOfs:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ohad-starkware)

**Pull request merged**
