### PR TITLE
avx512 eval secure

### PR DESCRIPTION
**Pull request by ohad-agadi**
Add errors in prove. (#468)

Add constraints not satisfied error. (#470)

Add prove verification error. (#498)

Add OODS verification error. (#502)

Add proof of work verification error. (#503)

Fix dev. (#512)

Create MultiFibonacci. (#509)

avx512 eval at secure point

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/513)

### CODE REVIEW

**Comment by ohad-starkware** [comment]
* **#513** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/513?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ohad-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/513)* status: 2 of 7 files reviewed, 3 unresolved discussions (waiting on @ohad-starkware)

___
*[`src/core/backend/avx512/circle.rs` line 92 at r2](https://reviewable.io/reviews/starkware-libs/stwo/513#-NtRNBqR2AW5nzkpNVYi:-NtRNBqR2AW5nzkpNVYj:b7putuo) ([raw file](https://github.com/starkware-libs/stwo/blob/59f85ab3f6f1eedf2287776b62397ef526afbe19/src/core/backend/avx512/circle.rs#L92)):*
> ```XML
>             let mut denominator = denominators[i - 1];
>             denominator *= mappings[i];
>             denominators.push(denominator);
> ```

Consider this



_Suggestion:_
```XML
            denominators.push(denominators[i - 1] * mappings[i]);
```
___
*[`src/core/backend/avx512/circle.rs` line 287 at r2](https://reviewable.io/reviews/starkware-libs/stwo/513#-NtRMP-cDuPrOpC5W7rq:-NtRMP-cDuPrOpC5W7rr:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/59f85ab3f6f1eedf2287776b62397ef526afbe19/src/core/backend/avx512/circle.rs#L287)):*
> ```XML
>         let mappings = Self::generate_evaluation_mappings(point, poly.log_size());
> 
>         // 8 lowest mappings produce the first 2^8 twiddles. Seperate to optimize each calculation.
> ```





_Suggestion:_
```XML
Separate
```
___
*[`src/core/backend/avx512/circle.rs` line 320 at r2](https://reviewable.io/reviews/starkware-libs/stwo/513#-NtRMrvG1aPvteSCl9Ui:-NtRMrvG1aPvteSCl9Uj:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/59f85ab3f6f1eedf2287776b62397ef526afbe19/src/core/backend/avx512/circle.rs#L320)):*
> ```XML
>             }
> 
>             // Advanced twiddle high.
> ```





_Suggestion:_
```XML
Advance
```

**Review by ohad-agadi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/513)* status: 2 of 7 files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`src/core/backend/avx512/circle.rs` line 92 at r2](https://reviewable.io/reviews/starkware-libs/stwo/513#-NtRNBqR2AW5nzkpNVYi:-NtROS0zEGKxPYkbbKPQ:bb7oryy) ([raw file](https://github.com/starkware-libs/stwo/blob/59f85ab3f6f1eedf2287776b62397ef526afbe19/src/core/backend/avx512/circle.rs#L92)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Consider this
</blockquote></details>

sure
___
*[`src/core/backend/avx512/circle.rs` line 287 at r2](https://reviewable.io/reviews/starkware-libs/stwo/513#-NtRMP-cDuPrOpC5W7rq:-NtROTLNDu1KZDBHPH83:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/59f85ab3f6f1eedf2287776b62397ef526afbe19/src/core/backend/avx512/circle.rs#L287)):*
> ```XML
>         let mappings = Self::generate_evaluation_mappings(point, poly.log_size());
> 
>         // 8 lowest mappings produce the first 2^8 twiddles. Seperate to optimize each calculation.
> ```

Done.
___
*[`src/core/backend/avx512/circle.rs` line 320 at r2](https://reviewable.io/reviews/starkware-libs/stwo/513#-NtRMrvG1aPvteSCl9Ui:-NtROCGUASE6nxjmrQI8:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/59f85ab3f6f1eedf2287776b62397ef526afbe19/src/core/backend/avx512/circle.rs#L320)):*
> ```XML
>             }
> 
>             // Advanced twiddle high.
> ```

Done.

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/513#-:-NtRRRQx5vwfJLCtN1BQ:bnfp4nl)* status: 2 of 7 files reviewed, all discussions resolved

**Pull request merged**
