### PR TITLE
Reuse commitment evaluation

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/495)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/495?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#495** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/495?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#494** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/494?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#493** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/493?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#492** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/492?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#491** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/491?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#490** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/490?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#489** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/489?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#488** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/488?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#487** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/487?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#486** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/486?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#484** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/484?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#483** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/483?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#482** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/482?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#481** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/481?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#480** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/480?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#479** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/479?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#478** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/478?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#463** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/463?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#477** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/477?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#476** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/476?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/495)* status: 3 of 8 files reviewed, 3 unresolved discussions (waiting on @alonh5 and @spapinistarkware)

___
*[`src/core/air/air_ext.rs` line 58 at r3](https://reviewable.io/reviews/starkware-libs/stwo/495#-NvWS7bJE5oaqbHHvdAj:-NvWS7bJE5oaqbHHvdAk:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/b72acc6fe9606bd85346429f37d3664d71fc920a/src/core/air/air_ext.rs#L58)):*
> ```XML
>         ComponentVec<Vec<SecureField>>,
>     ) {
>         let _span = span!(Level::INFO, "Eval columns ood").entered();
> ```





_Suggestion:_
```XML
let _span = span!(Level::INFO, "Eval OODS values").entered();
```
___
*[`src/core/air/mod.rs` line 88 at r3](https://reviewable.io/reviews/starkware-libs/stwo/495#-NvWSzPRAB3w4ZzdRAb7:-NvWSzPRAB3w4ZzdRAb8:b-yayd99) ([raw file](https://github.com/starkware-libs/stwo/blob/b72acc6fe9606bd85346429f37d3664d71fc920a/src/core/air/mod.rs#L88)):*
> ```XML
> }
> 
> pub struct ComponentTrace<'a, B: Backend> {
> ```

Document this struct, (and explain why we have it both polys and evals form)



_Code quote:_
```XML
pub struct ComponentTrace<'a, B: Backend> {
```
___
*[`src/examples/fibonacci/mod.rs` line 146 at r3](https://reviewable.io/reviews/starkware-libs/stwo/495#-NvWTZmm3pv1VgQBpTBv:-NvWTZmm3pv1VgQBpTBw:b-3ce9hb) ([raw file](https://github.com/starkware-libs/stwo/blob/b72acc6fe9606bd85346429f37d3664d71fc920a/src/examples/fibonacci/mod.rs#L146)):*
> ```XML
>         let trace = fib.get_trace();
>         let trace_poly = trace.interpolate();
>         let trace = ComponentTrace::new(vec![&trace_poly], vec![]);
> ```

I don't like that (although this is just a test).
Should it be asserted that the coeff form matches the evaluations form?



_Code quote:_
```XML
let trace = ComponentTrace::new(vec![&trace_poly], vec![]);
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/495)* status: 3 of 8 files reviewed, 3 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

___
*[`src/core/air/mod.rs` line 88 at r3](https://reviewable.io/reviews/starkware-libs/stwo/495#-NvWSzPRAB3w4ZzdRAb7:-NvWqjQbEYAyUswIqvMh:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/b72acc6fe9606bd85346429f37d3664d71fc920a/src/core/air/mod.rs#L88)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Document this struct, (and explain why we have it both polys and evals form)
</blockquote></details>

Done.
___
*[`src/examples/fibonacci/mod.rs` line 146 at r3](https://reviewable.io/reviews/starkware-libs/stwo/495#-NvWTZmm3pv1VgQBpTBv:-NvX26az8tpfSp1w5lSO:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/b72acc6fe9606bd85346429f37d3664d71fc920a/src/examples/fibonacci/mod.rs#L146)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I don't like that (although this is just a test).
Should it be asserted that the coeff form matches the evaluations form?
</blockquote></details>

Done.

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/495)* status: 3 of 8 files reviewed, 3 unresolved discussions (waiting on @alonh5 and @shaharsamocha7)

___
*[`src/core/air/air_ext.rs` line 58 at r3](https://reviewable.io/reviews/starkware-libs/stwo/495#-NvWS7bJE5oaqbHHvdAj:-NvX2dnK4qQBfLEP3amC:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/b72acc6fe9606bd85346429f37d3664d71fc920a/src/core/air/air_ext.rs#L58)):*
> ```XML
>         ComponentVec<Vec<SecureField>>,
>     ) {
>         let _span = span!(Level::INFO, "Eval columns ood").entered();
> ```

Done.

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r3, 1 of 1 files at r4, 2 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/495)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @spapinistarkware)

___
*[`src/core/air/mod.rs` line 89 at r5](https://reviewable.io/reviews/starkware-libs/stwo/495#-NvX4x5i63ddqXZvymN_:-NvX4x5i63ddqXZvymNa:b-7zi8ni) ([raw file](https://github.com/starkware-libs/stwo/blob/8572ccd2176904612bab8413ac04fc5a37cad0a3/src/core/air/mod.rs#L89)):*
> ```XML
> }
> 
> /// A component trace is a set of polynomials and evaluations for each column on that component.
> ```

WDYT?



_Suggestion:_
```XML
/// A component trace is a set of polynomials for each column on that component.
/// Each polynomial is stored both in a coefficients, and evaluations form (for efficiency)
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/495)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @shaharsamocha7)

___
*[`src/core/air/mod.rs` line 89 at r5](https://reviewable.io/reviews/starkware-libs/stwo/495#-NvX4x5i63ddqXZvymN_:-NvX5o7G2SGH0_3aZGvy:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/8572ccd2176904612bab8413ac04fc5a37cad0a3/src/core/air/mod.rs#L89)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

WDYT?
</blockquote></details>

Done.

**Review by shaharsamocha7 — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/495)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Pull request merged**
