### PR TITLE
Rename mix_nonce -> mix_u64

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/828)

### CODE REVIEW

**Comment by alonh5** [comment]
* **#828** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/828?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/828)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @alonh5)

___
*[`crates/prover/src/core/channel/mod.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/stwo/828#-O6Ld1PU4NPuhIhKY_ci:-O6Ld1PU4NPuhIhKY_cj:b-qhkh3i) ([raw file](https://github.com/starkware-libs/stwo/blob/9973dfa678c6b0af7426b9a83f769f9c2bb4759a/crates/prover/src/core/channel/mod.rs#L38)):*
> ```XML
>     // Mix functions.
>     fn mix_felts(&mut self, felts: &[SecureField]);
>     fn mix_u64(&mut self, nonce: u64);
> ```

Also rename



_Suggestion:_
```XML
    fn mix_u64(&mut self, value: u64);
```
___
*[`crates/prover/src/examples/blake/air.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/stwo/828#-O6Ld9AY2--a6QdTdBCx:-O6Ld9AY2--a6QdTdBCy:bcxiwde) ([raw file](https://github.com/starkware-libs/stwo/blob/9973dfa678c6b0af7426b9a83f769f9c2bb4759a/crates/prover/src/examples/blake/air.rs#L58)):*
> ```XML
>     }
>     fn mix_into(&self, channel: &mut impl Channel) {
>         // TODO(spapini): Do this better.
> ```

What's this TODO?



_Code quote:_
```XML
// TODO(spapini): Do this better.
```

**Review by alonh5 — COMMENTED** [review]
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/828)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7)

___
*[`crates/prover/src/core/channel/mod.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/stwo/828#-O6Ld1PU4NPuhIhKY_ci:-O6LnmhaB7fbtsD9Fvn8:b36pig5) ([raw file](https://github.com/starkware-libs/stwo/blob/9973dfa678c6b0af7426b9a83f769f9c2bb4759a/crates/prover/src/core/channel/mod.rs#L38)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Also rename
</blockquote></details>

oops, thanks
___
*[`crates/prover/src/examples/blake/air.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/stwo/828#-O6Ld9AY2--a6QdTdBCx:-O6Lnt6R4GZWk53zkHbp:bhadxqu) ([raw file](https://github.com/starkware-libs/stwo/blob/9973dfa678c6b0af7426b9a83f769f9c2bb4759a/crates/prover/src/examples/blake/air.rs#L58)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

What's this TODO?
</blockquote></details>

I think he was addressing what this PR is fixing, it was a wrong use of the API, but I think the renaming is an OK solution. I removed the TODO.

**Review by shaharsamocha7 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/828#-:-O6LrZaD1TK2ML9rp9TH:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Pull request merged**
