### PR TITLE
Separate verify

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/721)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/721?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#721** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/721?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#720** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/720?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/721)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/core/prover/mod.rs` line 195 at r1](https://reviewable.io/reviews/starkware-libs/stwo/721#-O1WWvwQ6moAPVAUiq7B:-O1WWvwQ6moAPVAUiq7C:byrehbc) ([raw file](https://github.com/starkware-libs/stwo/blob/072ad923c8ff9c6399f103872468af941bd902e3/crates/prover/src/core/prover/mod.rs#L195)):*
> ```XML
>     );
> 
>     prove_without_commit(
> ```

and change prove to be `commit_and_prove`.
Also in verifier.



_Suggestion:_
```XML
prove
```
___
*[`crates/prover/src/core/prover/mod.rs` line 206 at r1](https://reviewable.io/reviews/starkware-libs/stwo/721#-O1WWOCk1AHBjj_4LKti:-O1WWOCl5dRyJV0F7oh5:bpotd9a) ([raw file](https://github.com/starkware-libs/stwo/blob/072ad923c8ff9c6399f103872468af941bd902e3/crates/prover/src/core/prover/mod.rs#L206)):*
> ```XML
> pub fn verify(
>     proof: StarkProof,
>     air: &(impl Air + AirTraceVerifier),
> ```

To be symmetric with `prove`.



_Suggestion:_
```XML
air: &AirTraceVerifier,
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/721)* status: 0 of 14 files reviewed, 1 unresolved discussion (waiting on @alonh5)

___
*[`crates/prover/src/core/prover/mod.rs` line 206 at r1](https://reviewable.io/reviews/starkware-libs/stwo/721#-O1WWOCk1AHBjj_4LKti:-O1WY82g0pwipw4UEvj6:bjsusmh) ([raw file](https://github.com/starkware-libs/stwo/blob/072ad923c8ff9c6399f103872468af941bd902e3/crates/prover/src/core/prover/mod.rs#L206)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

To be symmetric with `prove`.
</blockquote></details>

A bit harder, but went an extra step towards there. And added a TODO.

**Review by alonh5 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 11 files at r3, 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/721)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`crates/prover/src/core/prover/mod.rs` line 79 at r4](https://reviewable.io/reviews/starkware-libs/stwo/721#-O1WaN93B9K-B-yd4X25:-O1WaN93B9K-B-yd4X26:bv2qg5t) ([raw file](https://github.com/starkware-libs/stwo/blob/210bc34acf30d6150a53ed3d1991879f06e0c907/crates/prover/src/core/prover/mod.rs#L79)):*
> ```XML
>     let interaction_elements = air.interaction_elements(channel);
>     let interaction_trace = air.interact(&trace, &interaction_elements);
>     if !interaction_elements.is_empty() {
> ```

Why this change? Technically a component could declare interaction elements without having an interaction trace, this would cause an panic when trying to commit on an empty vec.
___
*[`crates/prover/src/core/prover/mod.rs` line 222 at r4](https://reviewable.io/reviews/starkware-libs/stwo/721#-O1WasRh1N5jvqTjzU0m:-O1WasRh1N5jvqTjzU0n:b28s3t2) ([raw file](https://github.com/starkware-libs/stwo/blob/210bc34acf30d6150a53ed3d1991879f06e0c907/crates/prover/src/core/prover/mod.rs#L222)):*
> ```XML
>     let interaction_elements = air.interaction_elements(channel);
> 
>     if !interaction_elements.is_empty() {
> ```

Similarly to the previous comment, this could cause an out of range index in the commitments. Once you complete the TODO you can use the column log sizes. Until then maybe check the length of the commitments?

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/721)* status: 13 of 14 files reviewed, 2 unresolved discussions (waiting on @alonh5)

___
*[`crates/prover/src/core/prover/mod.rs` line 79 at r4](https://reviewable.io/reviews/starkware-libs/stwo/721#-O1WaN93B9K-B-yd4X25:-O1WkWJH-wC81qM9Mf31:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/210bc34acf30d6150a53ed3d1991879f06e0c907/crates/prover/src/core/prover/mod.rs#L79)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Why this change? Technically a component could declare interaction elements without having an interaction trace, this would cause an panic when trying to commit on an empty vec.
</blockquote></details>

Done.
___
*[`crates/prover/src/core/prover/mod.rs` line 222 at r4](https://reviewable.io/reviews/starkware-libs/stwo/721#-O1WasRh1N5jvqTjzU0m:-O1WkXAP2nPc_JnsPvE8:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/210bc34acf30d6150a53ed3d1991879f06e0c907/crates/prover/src/core/prover/mod.rs#L222)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Similarly to the previous comment, this could cause an out of range index in the commitments. Once you complete the TODO you can use the column log sizes. Until then maybe check the length of the commitments?
</blockquote></details>

Done.

**Review by alonh5 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/721#-:-O1WrEFE0ZAT-MpImeeB:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
