### PR TITLE
More detailed fft benchmarks

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/532)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
* **#532** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/532?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by andrewmilson — CHANGES_REQUESTED** [review]
FYI the fft benchmark breaks the benchmarks on non x86.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/532#-:-Ntp-bpu1gJ-MExX6Tt4:b-ce4ols)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @spapinistarkware)

___
*[`benches/fft.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/stwo/532#-NtoyPpJ-G5vqdMmTDj4:-NtoyPpJ-G5vqdMmTDj5:b-61rnj8) ([raw file](https://github.com/starkware-libs/stwo/blob/bd87cf96ac7a3195a41ff55645a3df393a93a895/benches/fft.rs#L26)):*
> ```XML
>         let twiddle_dbls = get_itwiddle_dbls(domain.half_coset);
> 
>         group.throughput(criterion::Throughput::Bytes(4 << log_size));
> ```

I think this is clearer



_Suggestion:_
```XML
group.throughput(criterion::Throughput::Bytes(size_of::<BaseField>() << log_size));
```
___
*[`benches/fft.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/stwo/532#-NtoyNdEC_JkisfKT4mk:-NtoyNdEC_JkisfKT4ml:b-i5ve21) ([raw file](https://github.com/starkware-libs/stwo/blob/bd87cf96ac7a3195a41ff55645a3df393a93a895/benches/fft.rs#L27)):*
> ```XML
> 
>         group.throughput(criterion::Throughput::Bytes(4 << log_size));
>         group.bench_function(criterion::BenchmarkId::new("avx ifft", log_size), |b| {
> ```

Why aren't the criterion types imported like everything else?
___
*[`benches/fft.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/stwo/532#-NtoypFDCkunXBTpt9cj:-NtoypFDCkunXBTpt9ck:undefined) ([raw file](https://github.com/starkware-libs/stwo/blob/bd87cf96ac7a3195a41ff55645a3df393a93a895/benches/fft.rs#L60)):*
> ```XML
>     let mut group = c.benchmark_group("ifft parts");
> 
>     group.throughput(criterion::Throughput::Bytes(4 << 14));
> ```





_Suggestion:_
```XML
log_size
```
___
*[`benches/fft.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/stwo/532#-NtoyqN1BcZKDTsWHM-t:-NtoyqN1BcZKDTsWHM-u:bdbznn4) ([raw file](https://github.com/starkware-libs/stwo/blob/bd87cf96ac7a3195a41ff55645a3df393a93a895/benches/fft.rs#L61)):*
> ```XML
> 
>     group.throughput(criterion::Throughput::Bytes(4 << 14));
>     group.bench_function("avx ifft_vecwise_loop 2^14", |b| {
> ```

Same here. Shouldn't it be `avx ifft_vecwise_loop 2^20`?

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/532)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @andrewmilson)

___
*[`benches/fft.rs` line 26 at r1](https://reviewable.io/reviews/starkware-libs/stwo/532#-NtoyPpJ-G5vqdMmTDj4:-Ntp1mGU6eGhevU4vkkX:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/bd87cf96ac7a3195a41ff55645a3df393a93a895/benches/fft.rs#L26)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

I think this is clearer
</blockquote></details>

Done.
___
*[`benches/fft.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/stwo/532#-NtoyNdEC_JkisfKT4mk:-Ntp1uAn4bFPZjNr5Z3B:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/bd87cf96ac7a3195a41ff55645a3df393a93a895/benches/fft.rs#L27)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Why aren't the criterion types imported like everything else?
</blockquote></details>

Done.
___
*[`benches/fft.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/stwo/532#-NtoypFDCkunXBTpt9cj:-Ntp2KKz8IkrVHytVs9b:bivp4ms) ([raw file](https://github.com/starkware-libs/stwo/blob/bd87cf96ac7a3195a41ff55645a3df393a93a895/benches/fft.rs#L60)):*
> ```XML
>     let mut group = c.benchmark_group("ifft parts");
> 
>     group.throughput(criterion::Throughput::Bytes(4 << 14));
> ```

No, this is actually 14.
___
*[`benches/fft.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/stwo/532#-NtoyqN1BcZKDTsWHM-t:-Ntp2QG40B-0f6Uf_-b5:bivp4ms) ([raw file](https://github.com/starkware-libs/stwo/blob/bd87cf96ac7a3195a41ff55645a3df393a93a895/benches/fft.rs#L61)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Same here. Shouldn't it be `avx ifft_vecwise_loop 2^20`?
</blockquote></details>

No, this is actually 14.
___
*[`benches/fft.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/stwo/532#-Ntp2U1L6KPTto5UCqdj:-Ntp2U1L6KPTto5UCqdk:b-wqt9g4) ([raw file](https://github.com/starkware-libs/stwo/blob/bd87cf96ac7a3195a41ff55645a3df393a93a895/benches/fft.rs#L92)):*
> ```XML
> 
>     group.throughput(criterion::Throughput::Bytes(4 << 20));
>     group.bench_function("avx transpose_vecs 2^20", |b| {
> ```

It's only 20 here.

**Review by andrewmilson — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/532)* status: all files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`benches/fft.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/stwo/532#-NtoypFDCkunXBTpt9cj:-NtsZ9e85TCUnInLYi8q:bqx7kwe) ([raw file](https://github.com/starkware-libs/stwo/blob/bd87cf96ac7a3195a41ff55645a3df393a93a895/benches/fft.rs#L60)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

No, this is actually 14.
</blockquote></details>

Can it be documented please? It's not immediately clear to me why
___
*[`benches/fft.rs` line 4 at r2](https://reviewable.io/reviews/starkware-libs/stwo/532#-NtsXJQk3ZiL3DhaeWsX:-NtsXJQk3ZiL3DhaeWsY:b-k90os4) ([raw file](https://github.com/starkware-libs/stwo/blob/9aa1fe7f420606fe0159bb6cf79b3000c314fe7c/benches/fft.rs#L4)):*
> ```XML
> 
> use criterion::{BenchmarkId, Criterion, Throughput};
> use stwo::core::backend::avx512::fft::ifft::get_itwiddle_dbls;
> ```

Even these imports will cause the build to break. Should be able to evaluate the changes with this:

```
rustup target add aarch64-unknown-linux-gnu
cargo bench --no-run --target aarch64-unknown-linux-gnu
```

It seems there are a few other places that are problematic. I'll submit a PR for it. LGTM

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/532)* status: all files reviewed, 2 unresolved discussions (waiting on @andrewmilson)

___
*[`benches/fft.rs` line 4 at r2](https://reviewable.io/reviews/starkware-libs/stwo/532#-NtsXJQk3ZiL3DhaeWsX:-NttPzPkDW_7uzlrY336:b-x6my02) ([raw file](https://github.com/starkware-libs/stwo/blob/9aa1fe7f420606fe0159bb6cf79b3000c314fe7c/benches/fft.rs#L4)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Even these imports will cause the build to break. Should be able to evaluate the changes with this:

```
rustup target add aarch64-unknown-linux-gnu
cargo bench --no-run --target aarch64-unknown-linux-gnu
```

It seems there are a few other places that are problematic. I'll submit a PR for it. LGTM
</blockquote></details>

Can you also add these check to the CI?
Note that I tried to add it to the ci by adding `macos-latest-xlarge` checks, but with this aarch64-unknown-linux-gnu trick you can remove the macos.
Add test and bench builds.
ty

**Review by andrewmilson — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/532)* status: all files reviewed, 1 unresolved discussion

**Review by andrewmilson — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/532#-:-NuIVTaz4SwnhrdaveLa:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
