### PR TITLE
Implement Backend for AVX512Backend

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/491)

### CODE REVIEW

**Comment by spapinistarkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/491?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#491** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/491?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#490** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/490?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#489** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/489?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#488** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/488?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#487** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/487?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#486** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/486?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#484** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/484?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#483** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/483?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#482** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/482?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#481** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/481?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#480** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/480?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#479** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/479?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#478** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/478?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#463** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/463?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#477** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/477?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#476** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/476?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @spapinistarkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by andrewmilson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/491)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @spapinistarkware)

___
*[`src/core/backend/avx512/mod.rs` line 134 at r1](https://reviewable.io/reviews/starkware-libs/stwo/491#-NtJlxv0CVbedCcAjstA:-NtJlxv0CVbedCcAjstB:brgr0cg) ([raw file](https://github.com/starkware-libs/stwo/blob/a8014d1042b24e9d45307ff5e3bb9bb6b6d0c460/src/core/backend/avx512/mod.rs#L134)):*
> ```XML
> 
> impl SecureColumn<AVX512Backend> {
>     pub fn set_vec(&mut self, vec_index: usize, value: PackedQM31) {
> ```

Thoughts?



_Suggestion:_
```XML
set_packed
```
___
*[`src/core/backend/avx512/mod.rs` line 142 at r1](https://reviewable.io/reviews/starkware-libs/stwo/491#-NtJmPY72xoPg3LfGxmA:-NtJmPY72xoPg3LfGxmB:b-8iy5kg) ([raw file](https://github.com/starkware-libs/stwo/blob/a8014d1042b24e9d45307ff5e3bb9bb6b6d0c460/src/core/backend/avx512/mod.rs#L142)):*
> ```XML
>         }
>     }
>     pub fn get_vec(&self, vec_index: usize) -> PackedQM31 {
> ```

Should this be `pub unsafe fn` and documented?



_Code snippet:_
```XML
    /// # Safety
    ///
    /// Calling this method with an out-of-bounds index is undefined behavior.
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/491)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @andrewmilson)

___
*[`src/core/backend/avx512/mod.rs` line 134 at r1](https://reviewable.io/reviews/starkware-libs/stwo/491#-NtJlxv0CVbedCcAjstA:-NtLyLaR55zjols0z6e2:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/8c1ef14bf7fdeb70ede6c9ceb3aef63ec6cca246/src/core/backend/avx512/mod.rs#L134)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Thoughts?
</blockquote></details>

Done.
___
*[`src/core/backend/avx512/mod.rs` line 142 at r1](https://reviewable.io/reviews/starkware-libs/stwo/491#-NtJmPY72xoPg3LfGxmA:-NtLyhWEBYZaqHVnaE6Y:b-a17dq1) ([raw file](https://github.com/starkware-libs/stwo/blob/8c1ef14bf7fdeb70ede6c9ceb3aef63ec6cca246/src/core/backend/avx512/mod.rs#L142)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Should this be `pub unsafe fn` and documented?
</blockquote></details>

Sounds better.

**Review by andrewmilson — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/491#-:-NtM7FakCpVmKVMRJDYH:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by andrewmilson — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/491#-:-NtoA4sK5NwJL0OnyS_t:bnfp4nl)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Review by andrewmilson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/491)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @spapinistarkware)

___
*[`src/core/backend/avx512/mod.rs` line 139 at r4](https://reviewable.io/reviews/starkware-libs/stwo/491#-NuIVrHH8zAZaLfoL9MD:-NuIVcXA2K0hZt-s4Lz4:bgpg8oi) ([raw file](https://github.com/starkware-libs/stwo/blob/0a615462f28d68106a24094ce84ee06ea38baa2d/src/core/backend/avx512/mod.rs#L139)):*
> ```XML
> 
> impl SecureColumn<AVX512Backend> {
>     pub fn packed_at(&self, vec_index: usize) -> PackedQM31 {
> ```

Why removed the Safety and unsafe?

**Pull request closed without merging**
