### PR TITLE
Create commitment scheme.

### PR DESCRIPTION
**Pull request by alonh5**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/453)

### CODE REVIEW

**Comment by alonh5** [comment]
* **#454** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/454?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#453** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo/453?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alonh5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/453#-:-NsmS34N9SdR2haB61Ee:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5)

___
*[`src/core/commitment_scheme.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/stwo/453#-NsmRGQ_DqXdgtU7UGfh:-NsmRGQ_DqXdgtU7UGfi:bsxezqq) ([raw file](https://github.com/starkware-libs/stwo/blob/589e9ce078827de0b360c5c231784b65607eb954/src/core/commitment_scheme.rs#L19)):*
> ```XML
> use crate::core::channel::Channel;
> 
> pub type OpenedValues = Vec<Vec<Vec<BaseField>>>;
> ```

Document.
It's per tree, column, mask item, right?
___
*[`src/core/commitment_scheme.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/stwo/453#-NsmRm3_DIRoI2KLN9EG:-NsmRm3_DIRoI2KLN9EH:b-xasl5p) ([raw file](https://github.com/starkware-libs/stwo/blob/589e9ce078827de0b360c5c231784b65607eb954/src/core/commitment_scheme.rs#L19)):*
> ```XML
> use crate::core::channel::Channel;
> 
> pub type OpenedValues = Vec<Vec<Vec<BaseField>>>;
> ```

Consider creating a type for thing, instead of a type alias.
___
*[`src/core/commitment_scheme.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/stwo/453#-NsmRjKw0dxDo7eTt7sO:-NsmRjKw0dxDo7eTt7sP:b9y8awx) ([raw file](https://github.com/starkware-libs/stwo/blob/589e9ce078827de0b360c5c231784b65607eb954/src/core/commitment_scheme.rs#L23)):*
> ```XML
> 
> pub struct CommitmentSchemeProver {
>     pub trees: Vec<CommitmentTreeProver>,
> ```

Do these need to be public?

**Review by alonh5 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/453)* status: all files reviewed, 3 unresolved discussions (waiting on @spapinistarkware)

___
*[`src/core/commitment_scheme.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/stwo/453#-NsmRGQ_DqXdgtU7UGfh:-NsmYbnyCYo8jivwaGdk:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/589e9ce078827de0b360c5c231784b65607eb954/src/core/commitment_scheme.rs#L19)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Document.
It's per tree, column, mask item, right?
</blockquote></details>

Done.
___
*[`src/core/commitment_scheme.rs` line 19 at r1](https://reviewable.io/reviews/starkware-libs/stwo/453#-NsmRm3_DIRoI2KLN9EG:-NsmYc1K1YVdCqcul3rN:b-896fix) ([raw file](https://github.com/starkware-libs/stwo/blob/589e9ce078827de0b360c5c231784b65607eb954/src/core/commitment_scheme.rs#L19)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Consider creating a type for thing, instead of a type alias.
</blockquote></details>

Done.
___
*[`src/core/commitment_scheme.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/stwo/453#-NsmRjKw0dxDo7eTt7sO:-NsmYcC60hIlZv20SfoJ:b-ocrf7) ([raw file](https://github.com/starkware-libs/stwo/blob/589e9ce078827de0b360c5c231784b65607eb954/src/core/commitment_scheme.rs#L23)):*
<details><summary><i>Previously, spapinistarkware (Shahar Papini) wrote…</i></summary><blockquote>

Do these need to be public?
</blockquote></details>

For now yes, to get the evaluations (for the component vec and for the oods quotient calculations).

**Review by spapinistarkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/453#-:-Nsmbjl0D1FlX4VXbMed:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alonh5)

**Pull request merged**
