### PR TITLE
Generic Backend Secure Powers Generation

### PR DESCRIPTION
**Pull request by Gali-StarkWare**

### CODE REVIEW

**Review by ohad-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/934)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @Gali-StarkWare and @shaharsamocha7)

___
*[`crates/prover/src/core/backend/mod.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/stwo/934#-OEEcIQ40hyRUpNjqBMU:-OEEcIQ40hyRUpNjqBMV:bv7828h) ([raw file](https://github.com/starkware-libs/stwo/blob/7f50706929d394b2a2104989aa8673dea3edba92/crates/prover/src/core/backend/mod.rs#L45)):*
> ```XML
> }
> 
> pub trait PowersGeneration {
> ```

I don't think it deserves a separate trait
perhaps it should sit behind AccumulationOps, as it's used for accumulating..? @shaharsamocha7

**Review by shaharsamocha7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/934)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @Gali-StarkWare and @ohad-starkware)

___
*[`crates/prover/src/core/backend/mod.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/stwo/934#-OEEcIQ40hyRUpNjqBMU:-OEExBTu7cK06UFw5s5S:b32v57) ([raw file](https://github.com/starkware-libs/stwo/blob/7f50706929d394b2a2104989aa8673dea3edba92/crates/prover/src/core/backend/mod.rs#L45)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

I don't think it deserves a separate trait
perhaps it should sit behind AccumulationOps, as it's used for accumulating..? @shaharsamocha7
</blockquote></details>

+1

**Review by Gali-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/934)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @Gali-StarkWare and @ohad-starkware)

___
*[`crates/prover/src/core/backend/mod.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/stwo/934#-OEEcIQ40hyRUpNjqBMU:-OEEybLHD9LvWDunoWZE:b-h19y9d) ([raw file](https://github.com/starkware-libs/stwo/blob/7f50706929d394b2a2104989aa8673dea3edba92/crates/prover/src/core/backend/mod.rs#L45)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

+1
</blockquote></details>

Agree, done. When do you define a new trait? In this case AccumulationOps had only one function before, but I understand why it's not related to any of the other traits Backend has to impl. So It's a balance between structuring the code into sections and not having too fine-grained partition?

**Review by shaharsamocha7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/934)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @Gali-StarkWare and @ohad-starkware)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo/934#-OEIaI3t8jPIcm8NRE_Q:-OEIaI3t8jPIcm8NRE_R:b4hmtaz) (no related file):*
Seems that doc test is failing.
Run `cargo doc` to see the error.
___
*[`crates/prover/src/core/backend/mod.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/stwo/934#-OEEcIQ40hyRUpNjqBMU:-OEIaaykCGWh00gWQ3S8:bh0d10o) ([raw file](https://github.com/starkware-libs/stwo/blob/7f50706929d394b2a2104989aa8673dea3edba92/crates/prover/src/core/backend/mod.rs#L45)):*
<details><summary><i>Previously, Gali-StarkWare wrote…</i></summary><blockquote>

Agree, done. When do you define a new trait? In this case AccumulationOps had only one function before, but I understand why it's not related to any of the other traits Backend has to impl. So It's a balance between structuring the code into sections and not having too fine-grained partition?
</blockquote></details>

Yes, generally we don't want to create too many traits.
OTOH, defining all of those functions in a single trait is also weird as some of those function are not related at all.

**Review by ohad-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/934)* status: 1 of 7 files reviewed, 2 unresolved discussions (waiting on @Gali-StarkWare)

___
*[`crates/prover/src/core/backend/mod.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/stwo/934#-OEEcIQ40hyRUpNjqBMU:-OEIaPwu7vXr2GQOS0CZ:b-2qy8id) ([raw file](https://github.com/starkware-libs/stwo/blob/7f50706929d394b2a2104989aa8673dea3edba92/crates/prover/src/core/backend/mod.rs#L45)):*
<details><summary><i>Previously, Gali-StarkWare wrote…</i></summary><blockquote>

Agree, done. When do you define a new trait? In this case AccumulationOps had only one function before, but I understand why it's not related to any of the other traits Backend has to impl. So It's a balance between structuring the code into sections and not having too fine-grained partition?
</blockquote></details>

if trait A <=> trait B  A then there's no point in exposing two interfaces
___
*[`crates/prover/src/core/air/accumulation.rs` line 108 at r2](https://reviewable.io/reviews/starkware-libs/stwo/934#-OEIbH7j64j2mWBU6Lep:-OEIbH7j64j2mWBU6Leq:br0zwm7) ([raw file](https://github.com/starkware-libs/stwo/blob/7e1be59a7678187cb71c6fc56b41e3ec1a2c13fe/crates/prover/src/core/air/accumulation.rs#L108)):*
> ```XML
>     ///   column = column + other.
>     fn accumulate(column: &mut SecureColumnByCoords<Self>, other: &SecureColumnByCoords<Self>);
>     fn generate_secure_powers(felt: SecureField, n_powers: usize) -> Vec<SecureField>;
> ```

add a space and document

**Review by Gali-StarkWare — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/934)* status: 1 of 7 files reviewed, 2 unresolved discussions (waiting on @Gali-StarkWare, @ohad-starkware, and @shaharsamocha7)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo/934#-OEIaI3t8jPIcm8NRE_Q:-OEIiQuqEV0Z-E9fAalY:b-2h4fkn) (no related file):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Seems that doc test is failing.
Run `cargo doc` to see the error.
</blockquote></details>

Done. Adding to my checklist before submitting PRs
___
*[`crates/prover/src/core/air/accumulation.rs` line 108 at r2](https://reviewable.io/reviews/starkware-libs/stwo/934#-OEIbH7j64j2mWBU6Lep:-OEIj1Gm-86va22gwoBz:bt8s9cd) ([raw file](https://github.com/starkware-libs/stwo/blob/7e1be59a7678187cb71c6fc56b41e3ec1a2c13fe/crates/prover/src/core/air/accumulation.rs#L108)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

add a space and document
</blockquote></details>

Done. Deleted the comment from the cpu impl

**Review by ohad-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/934#-:-OEIs71pAyBVOYuc8CPD:bnfp4nl)* status: 1 of 7 files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7)

**Comment by Gali-StarkWare** [comment]
### Merge activity

* **Dec 18, 5:58 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo/934).

**Pull request merged**
