### PR TITLE
avx vecwise butterflies

### PR DESCRIPTION
**Pull request by spapinistarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/377)

### CODE REVIEW

**Comment by ilyalesokhin-starkware** [comment]
*[`src/core/backend/avx512/fft.rs` line 160 at r1](https://reviewable.io/reviews/starkware-libs/stwo/377#-Ns3DJCt9Sa1cubNXShN:-Ns3DJCt9Sa1cubNXShO:bswfkyy) ([raw file](https://github.com/starkware-libs/stwo/blob/4f07fa1e1b437b5fb347e9fb80ce421ddc6715b1/src/core/backend/avx512/fft.rs#L160)):*
> ```XML
> /// Runs fft on 2 vectors of 16 M31 elements.
> /// This amounts to 4 butterfly layers, each with 16 butterflies.
> /// Each of the vectors represents natural ordered polynomial coefficeint.
> ```

Isn't this true only at the first layer?



_Code quote:_
```XML
/// Each of the vectors represents natural ordered polynomial coefficeint.
```

**Comment by ilyalesokhin-starkware** [comment]
*[`src/core/backend/avx512/fft.rs` line 178 at r1](https://reviewable.io/reviews/starkware-libs/stwo/377#-Ns3DVQyA3-0M31V76j_:-Ns3DVQyA3-0M31V76ja:b1n3xvq) ([raw file](https://github.com/starkware-libs/stwo/blob/4f07fa1e1b437b5fb347e9fb80ce421ddc6715b1/src/core/backend/avx512/fft.rs#L178)):*
> ```XML
>     // TODO(spapini): The permute can be fused with the _mm512_srli_epi64 inside the butterfly.
>     // The implementation is the exact reverse of vecwise_ibutterflies().
>     // See the comments in its body for more info.
> ```

what body?



_Code quote:_
```XML
See the comments in its body for more info.
```

**Review by spapinistarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/377)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`src/core/backend/avx512/fft.rs` line 160 at r1](https://reviewable.io/reviews/starkware-libs/stwo/377#-Ns3DJCt9Sa1cubNXShN:-Ns3MSO1CGPpS3htuyYq:b-bg7dx7) ([raw file](https://github.com/starkware-libs/stwo/blob/a9f4c6e5a81e692c3e2ed26cc182db707f5403de/src/core/backend/avx512/fft.rs#L160)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Isn't this true only at the first layer?
</blockquote></details>

Yes, and this function only runs on the first layer, or equivalently, perform a full fft on the coefficients.
___
*[`src/core/backend/avx512/fft.rs` line 178 at r1](https://reviewable.io/reviews/starkware-libs/stwo/377#-Ns3DVQyA3-0M31V76j_:-Ns3Mhvz0E8mMcY4e4wD:b4yz8tx) ([raw file](https://github.com/starkware-libs/stwo/blob/a9f4c6e5a81e692c3e2ed26cc182db707f5403de/src/core/backend/avx512/fft.rs#L178)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

what body?
</blockquote></details>

vecwise_ibutterflies()

**Review by ilyalesokhin-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo/377#-:-Ns7Pvn141Xc0i9k9KbJ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spapinistarkware)

**Pull request merged**
